#!/bin/sh

function usage() {
   echo "Usage: INSTALL --help        print this text"
   echo " "
   echo "Usage: INSTALL target options"
   echo " "
   echo " where target options are chosen from the following ... "
   echo " "
   echo "    To override the default choice of BLAS/LAPACK libraries set the environment"
   echo "    variables MADBLAS and/or MADLAPACK."
   echo " "
   echo "    To override the default compiler optimization flags set MADCOPT."
   echo " "
   echo "    To override the default architecture choice set MADARCH."
   echo " "
   echo "    To set additional defines/includes set MADCDEF."
   echo " "
   echo "    To set additional libraries set MADLIBS."
   echo " "
   echo "    For full control, run the configure script."
   echo " "
}

if [ "$1" == "--help" ] ; then
    usage
    exit 0
fi

target="$*"

function contains() {
    echo "$1" | grep -qi "$2"
}

function using() {
    contains "$target" "$1"
}

function isgcc() {
    contains "`$CXX -v 2>&1`" "gcc"
}

function isgcc4() {
    contains "`$CXX -v 2>&1`" "gcc version 4"
}

# Assume MPICH-like interface if not CXX is not set
if [ "$CXX" == "" ] ; then
    CXX=mpicxx
    CC=mpicc
fi

if [ "$MADDEF" == "" ] ; then
    MADDEF="-DX8632 -DHAS_XTERM_DEBUG"
fi

if [ "$MADLAPACK" == "" ] ; then
    MADLAPACK="-llapack"
fi

if [ "$MADBLAS" == "" ] ; then
    MADBLAS="-lblas"
fi

# Tweaks for gcc 
if isgcc ; then
    if isgcc4 ; then
        MADARCH=-march=native
    else
        MADLIBS="$MADLIBS -lg2c"
        MADFINT="--with-fortran-integer=int"
    fi
    if [ "$MADCOPT" == "" ] ; then
        if using debug ; then
            MADCOPT="-Wall -ansi -O0 -g $MADARCH"
        else
            MADCOPT="-Wall -ansi -O3 -ffast-math -fomit-frame-pointer -funroll-loops -malign-double -mfpmath=sse -msse2 $MADARCH"
        fi
    fi
fi

if using "x86-64" ; then
   MADDEF="$MADDEF -DX8664"
elif using "x86" ; then
   MADDEF="$MADDEF -DX8632"
fi

MADCOPT="$MADCOPT $MADDEF"


# Now handle all special cases in detail with default covering
# most systems after setting flags above
case "$1" in
    *)
        echo ./configure --with-cxx=\"$CXX\" \\
        echo "            "--with-cc=\"$CC\" \\
        echo "            "--with-cxx-optflags=\"$MADCOPT\"  \\
        echo "            "--with-cc-optflags=\"$MADCOPT\" \\
        echo "            "--with-blas=\"$MADBLAS\" --with-lapack=\"$MADLAPACK\" \\
        echo "            "--with-libs=\"$MADLIBS\" $MADFINT

        ./configure --with-cxx="$CXX" --with-cc="$CC" \
            --with-cxx-optflags="$MADCOPT" --with-cc-optflags="$MADCOPT" \
            --with-blas="$MADBLAS" --with-lapack="$MADLAPACK" \
            --with-libs="$MADLIBS" $MADFINT

        ;;
esac
