TOPDIR = ../../..

TARGET_TO_MAKE = libMADtinyxml

CXXSRC = tinystr.cc  tinyxml.cc  tinyxmlerror.cc  tinyxmlparser.cc

# GlobalMakefile now does most of the work for you
include $(TOPDIR)/config/GlobalMakefile

INCLUDES += -I.
