#!/bin/bash
name=`echo ${1} | sed s/"\.x"//g`
#echo ${name}
dirname=${name}_`date +%d%b%Y_%Hh%Mm`
mkdir ${dirname}
cp ${name}.x *.cc Makefile ${dirname}/.
cd ${dirname}
qsub -t 30 -n 1 -m smp ${name}.x
