MADNESS: nemo.cc File Reference
apps/nemo/nemo.cc File Reference
#include <madness/chem/SCFOperators.h>
#include <madness/chem/molecular_optimizer.h>
#include <madness/chem/nemo.h>
#include <madness/chem/projector.h>
#include <madness/misc/info.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References e(), energy, madness::error(), madness::finalize(), madness::Tensor< T >::flat(), madness::Nemo::help(), madness::initialize(), madness::commandlineparser::key_exists(), madness::MolecularOptimizer::optimize(), madness::MolecularOptimizer::parameters, madness::QCCalculationParametersBase::print(), madness::print(), madness::print_header1(), madness::print_header2(), madness::Nemo::print_parameters(), madness::info::print_revision_information(), madness::World::rank(), madness::MolecularOptimizer::set_hessian(), madness::startup(), and madness::wall_time().