MADNESS: mp2.cc File Reference
apps/mp2/mp2.cc File Reference
Solves molecular MP2 equations.
#include "madness/chem/mp2.h"
#include "madness/misc/info.h"
Functions
int main (int argc, char **argv)
Detailed Description
Solves molecular MP2 equations.
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::World::rank(), and madness::startup().