MADNESS: benchmark_exchange_operator.cc File Reference
benchmark_exchange_operator.cc File Reference
#include <madness.h>
#include <madness/chem/SCF.h>
#include <madness/chem/SCFOperators.h>
#include <madness/chem/nemo.h>
#include <madness/chem/write_test_input.h>
#include <madness/misc/info.h>
#include <madness/world/test_utilities.h>
#include <ParameterManager.hpp>
Classes
class MemoryParameters
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::SCF::amo, MemoryParameters::cloud_distribution(), madness::MacroTaskInfo::cloud_distribution_policy, MemoryParameters::cloud_storage(), madness::cpu_time(), e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::Molecule::get_all_coords(), madness::World::gop, madness::CalculationParameters::hfexalg(), madness::initialize(), K(), madness::commandlineparser::key_exists(), madness::LoadBalanceDeux< NDIM >::load_balance(), madness::CalculationParameters::loadbalparts(), me, madness::SCF::molecule, madness::SCF::param, madness::QCCalculationParametersBase::print(), madness::print(), madness::Molecule::print(), madness::info::print_revision_information(), madness::MacroTaskInfo::ptr_target_distribution_policy, madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), madness::commandlineparser::set_keyval(), madness::SCF::set_protocol(), madness::World::size(), madness::startup(), madness::MacroTaskInfo::storage_policy, madness::Exchange< T, NDIM >::string2algorithm(), MemoryParameters::target_distribution(), and madness::to_string().