MADNESS: binaryop.cc File Reference
binaryop.cc File Reference
Illustrates general composition of two functions.
#include <madness/mra/mra.h>
Classes
struct Uop
Functions
double delta (const coord_3d &r)
int main (int argc, char **argv)
double uexact (const coord_3d &r)
Variables
static const long k = 8
static const double L = 30
static const double small = thresh*1e-4
static const double thresh = 1e-6
Detailed Description
Illustrates general composition of two functions.
Function Documentation
delta()
double delta (const coord_3d & r)
References e().
Referenced by main(), and uexact().
main()
int main (int argc, char ** argv)
References madness::binary_op(), SafeMPI::COMM_WORLD, delta(), madness::Function< T, NDIM >::err(), exact(), madness::finalize(), madness::initialize(), k, L, lo, madness::plot_line(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, and madness::Function< T, NDIM >::truncate().
uexact()
double uexact (const coord_3d & r)
References delta(), and pow().
Referenced by main().
Variable Documentation
k
const long k = 8 static
Referenced by main().
L
const double L = 30 static
Referenced by main().
small
const double small = thresh*1e-4 static
Referenced by apply_BSH(), apply_BSH_new(), madness::SRConf< T >::check_right_orthonormality(), main(), and Uop::operator()().
thresh
const double thresh = 1e-6 static
Referenced by main().