MADNESS: cc2.cc File Reference
cc2.cc File Reference
#include "madness/chem/CC2.h"
#include "madness/misc/info.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::World::rank(), and madness::startup().