MADNESS: clapack_fortran.h File Reference
clapack_fortran.h File Reference
Legacy C++ prototypes for Fortran LAPACK with associated typedefs and macos.
#include <madness/fortran_ctypes.h>
Functions
void cgeev_ (const char *jobz, const char *uplo, integer *n, complex_real4 *a, integer *lda, complex_real4 *w, complex_real4 *vl, integer *ldvl, complex_real4 *vr, integer *ldvr, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void cgels_ (const char *trans, integer *m, integer *n, integer *nrhs, complex_real4 *a, integer *lda, complex_real4 *b, integer *ldb, complex_real4 *work, integer *lwork, real4 *rwork, integer *infoOUT, char_len translen)
void cgelss_ (integer *m, integer *n, integer *nrhs, complex_real4 *a, integer *lda, complex_real4 *b, integer *ldb, real4 *sOUT, real4 *rcondIN, integer *rankOUT, complex_real4 *work, integer *lwork, real4 *rwork, integer *infoOUT)
void cgeqp3_ (integer *m, integer *n, complex_real4 *a, integer *lda, integer *jpvt, complex_real4 *tau, complex_real4 *work, integer *lwork, real4 *rwork, integer *infoOUT)
void cgeqrf_ (integer *m, integer *n, complex_real4 *a, integer *lda, complex_real4 *tau, complex_real4 *work, integer *lwork, integer *infoOUT)
void cgesv_ (integer *n, integer *nrhs, complex_real4 *AT, integer *lda, integer *piv, complex_real4 *x, integer *ldx, integer *info)
void cgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, complex_real4 *a, integer *lda, real4 *s, complex_real4 *u, integer *ldu, complex_real4 *vt, integer *ldvt, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobulen, char_len jobvtlen)
void cgetrf_ (const integer *m, const integer *n, complex_real4 *a, const integer *lda, integer *ipiv, integer *info)
void cgetri_ (const integer *n, complex_real4 *a, const integer *lda, const integer *ipiv, complex_real4 *work, const integer *lwork, integer *info)
void cggev_ (const char *jobz, const char *uplo, integer *n, complex_real4 *a, integer *lda, complex_real4 *b, integer *ldb, complex_real4 *alpha, complex_real4 *beta, complex_real4 *vl, integer *ldvl, complex_real4 *vr, integer *ldvr, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void cheev_ (const char *jobz, const char *uplo, integer *n, complex_real4 *a, integer *lda, real4 *w, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void chegv_ (integer *itype, const char *jobz, const char *uplo, integer *n, complex_real4 *a, integer *lda, complex_real4 *b, integer *ldb, real4 *w, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void cpotrf_ (const char *uplo, const integer *n, complex_real4 *a, const integer *lda, integer *info, char_len uplo_len)
void cpstrf_ (const char *uplo, const integer *n, complex_real4 *a, const integer *lda, integer *ipiv, integer *rank, real4 *tol, complex_real4 *work, integer *info)
void ctrsm_ (const char *side, const char *uplo, const char *transa, const char *diag, const integer *m, const integer *n, const complex_real4 *alpha, const complex_real4 *a, const integer *lda, complex_real4 *b, const integer *ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
void ctrtri_ (const char *uplo, const char *diag, const integer *n, const complex_real4 *a, const integer *lda, integer *info)
void cungqr_ (integer *m, integer *n, integer *k, complex_real4 *a, integer *lda, complex_real4 *tau, complex_real4 *work, integer *lwork, integer *info)
void dgeev_ (const char *jobz, const char *uplo, integer *n, real8 *a, integer *lda, real8 *w_real, real8 *w_imag, real8 *v, integer *ldv, real8 *vr, integer *ldvr, real8 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void dgels_ (const char *trans, integer *m, integer *n, integer *nrhs, real8 *a, integer *lda, real8 *b, integer *ldb, real8 *work, integer *lwork, integer *infoOUT, char_len translen)
void dgelss_ (integer *m, integer *n, integer *nrhs, real8 *a, integer *lda, real8 *b, integer *ldb, real8 *sOUT, real8 *rcondIN, integer *rankOUT, real8 *work, integer *lwork, integer *infoOUT)
void dgeqp3_ (integer *m, integer *n, real8 *a, integer *lda, integer *jpvt, real8 *tau, real8 *work, integer *lwork, integer *infoOUT)
void dgeqrf_ (integer *m, integer *n, real8 *a, integer *lda, real8 *tau, real8 *work, integer *lwork, integer *infoOUT)
void dgesv_ (integer *n, integer *nrhs, real8 *AT, integer *lda, integer *piv, real8 *x, integer *ldx, integer *info)
void dgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, real8 *a, integer *lda, real8 *s, real8 *u, integer *ldu, real8 *vt, integer *ldvt, real8 *work, integer *lwork, integer *info, char_len jobulen, char_len jobvtlen)
void dgetrf_ (const integer *m, const integer *n, real8 *a, const integer *lda, integer *ipiv, integer *info)
void dgetri_ (const integer *n, real8 *a, const integer *lda, const integer *ipiv, real8 *work, const integer *lwork, integer *info)
void dggev_ (const char *jobl, const char *jobr, integer *n, real8 *a, integer *lda, real8 *b, integer *ldb, real8 *w_real, real8 *w_imag, real8 *beta, real8 *vl, integer *ldvl, real8 *vr, integer *ldvr, real8 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
double dlamch_ (const char *mode, int modelen)
void dorgqr_ (integer *m, integer *n, integer *k, real8 *a, integer *lda, real8 *tau, real8 *work, integer *lwork, integer *info)
void dpotrf_ (const char *uplo, const integer *n, real8 *a, const integer *lda, integer *info, char_len uplo_len)
void dpstrf_ (const char *uplo, const integer *n, real8 *a, const integer *lda, integer *ipiv, integer *rank, real8 *tol, real8 *work, integer *info)
void dsyev_ (const char *jobz, const char *uplo, integer *n, real8 *a, integer *lda, real8 *w, real8 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void dsygv_ (integer *itype, const char *jobz, const char *uplo, integer *n, real8 *a, integer *lda, real8 *b, integer *ldb, real8 *w, real8 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void dtrsm_ (const char *side, const char *uplo, const char *transa, const char *diag, const integer *m, const integer *n, const real8 *alpha, const real8 *a, const integer *lda, real8 *b, const integer *ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
void dtrtri_ (const char *uplo, const char *diag, const integer *n, const real8 *a, const integer *lda, integer *info)
void sgeev_ (const char *jobz, const char *uplo, integer *n, real4 *a, integer *lda, real4 *w_real, real4 *w_imag, real4 *v, integer *ldv, real4 *vr, integer *ldvr, real4 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void sgels_ (const char *trans, integer *m, integer *n, integer *nrhs, real4 *a, integer *lda, real4 *b, integer *ldb, real4 *work, integer *lwork, integer *infoOUT, char_len translen)
void sgelss_ (integer *m, integer *n, integer *nrhs, real4 *a, integer *lda, real4 *b, integer *ldb, real4 *sOUT, real4 *rcondIN, integer *rankOUT, real4 *work, integer *lwork, integer *infoOUT)
void sgeqp3_ (integer *m, integer *n, real4 *a, integer *lda, integer *jpvt, real4 *tau, real4 *work, integer *lwork, integer *infoOUT)
void sgeqrf_ (integer *m, integer *n, real4 *a, integer *lda, real4 *tau, real4 *work, integer *lwork, integer *infoOUT)
void sgesv_ (integer *n, integer *nrhs, real4 *AT, integer *lda, integer *piv, real4 *x, integer *ldx, integer *info)
void sgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, real4 *a, integer *lda, real4 *s, real4 *u, integer *ldu, real4 *vt, integer *ldvt, real4 *work, integer *lwork, integer *info, char_len jobulen, char_len jobvtlen)
void sgetrf_ (const integer *m, const integer *n, real4 *a, const integer *lda, integer *ipiv, integer *info)
void sgetri_ (const integer *n, real4 *a, const integer *lda, const integer *ipiv, real4 *work, const integer *lwork, integer *info)
void sggev_ (const char *jobz, const char *uplo, integer *n, real4 *a, integer *lda, real4 *b, integer *ldb, real4 *alphar, real4 *alphai, real4 *beta, real4 *vl, integer *ldvl, real4 *vr, integer *ldvr, real4 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
float slamch_ (const char *mode, int modelen)
void sorgqr_ (integer *m, integer *n, integer *k, real4 *a, integer *lda, real4 *tau, real4 *work, integer *lwork, integer *info)
void spotrf_ (const char *uplo, const integer *n, real4 *a, const integer *lda, integer *info, char_len uplo_len)
void spstrf_ (const char *uplo, const integer *n, real4 *a, const integer *lda, integer *ipiv, integer *rank, real4 *tol, real4 *work, integer *info)
void ssyev_ (const char *jobz, const char *uplo, integer *n, real4 *a, integer *lda, real4 *w, real4 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void ssygv_ (integer *itype, const char *jobz, const char *uplo, integer *n, real4 *a, integer *lda, real4 *b, integer *ldb, real4 *w, real4 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void strsm_ (const char *side, const char *uplo, const char *transa, const char *diag, const integer *m, const integer *n, const real4 *alpha, const real4 *a, const integer *lda, real4 *b, const integer *ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
void strtri_ (const char *uplo, const char *diag, const integer *n, const real4 *a, const integer *lda, integer *info)
void zgeev_ (const char *jobz, const char *uplo, integer *n, complex_real8 *a, integer *lda, complex_real8 *w, complex_real8 *vl, integer *ldvl, complex_real8 *vr, integer *ldvr, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void zgels_ (const char *trans, integer *m, integer *n, integer *nrhs, complex_real8 *a, integer *lda, complex_real8 *b, integer *ldb, complex_real8 *work, integer *lwork, real8 *rwork, integer *infoOUT, char_len translen)
void zgelss_ (integer *m, integer *n, integer *nrhs, complex_real8 *a, integer *lda, complex_real8 *b, integer *ldb, real8 *sOUT, real8 *rcondIN, integer *rankOUT, complex_real8 *work, integer *lwork, real8 *rwork, integer *infoOUT)
void zgeqp3_ (integer *m, integer *n, complex_real8 *a, integer *lda, integer *jpvt, complex_real8 *tau, complex_real8 *work, integer *lwork, real8 *rwork, integer *infoOUT)
void zgeqrf_ (integer *m, integer *n, complex_real8 *a, integer *lda, complex_real8 *tau, complex_real8 *work, integer *lwork, integer *infoOUT)
void zgesv_ (integer *n, integer *nrhs, complex_real8 *AT, integer *lda, integer *piv, complex_real8 *x, integer *ldx, integer *info)
void zgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, complex_real8 *a, integer *lda, real8 *s, complex_real8 *u, integer *ldu, complex_real8 *vt, integer *ldvt, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobulen, char_len jobvtlen)
void zgetrf_ (const integer *m, const integer *n, complex_real8 *a, const integer *lda, integer *ipiv, integer *info)
void zgetri_ (const integer *n, complex_real8 *a, const integer *lda, const integer *ipiv, complex_real8 *work, const integer *lwork, integer *info)
void zggev_ (const char *jobz, const char *uplo, integer *n, complex_real8 *a, integer *lda, complex_real8 *b, integer *ldb, complex_real8 *alpha, complex_real8 *beta, complex_real8 *vl, integer *ldvl, complex_real8 *vr, integer *ldvr, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void zheev_ (const char *jobz, const char *uplo, integer *n, complex_real8 *a, integer *lda, real8 *w, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void zhegv_ (integer *itype, const char *jobz, const char *uplo, integer *n, complex_real8 *a, integer *lda, complex_real8 *b, integer *ldb, real8 *w, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void zpotrf_ (const char *uplo, const integer *n, complex_real8 *a, const integer *lda, integer *info, char_len uplo_len)
void zpstrf_ (const char *uplo, const integer *n, complex_real8 *a, const integer *lda, integer *ipiv, integer *rank, real8 *tol, complex_real8 *work, integer *info)
void ztrsm_ (const char *side, const char *uplo, const char *transa, const char *diag, const integer *m, const integer *n, const complex_real8 *alpha, const complex_real8 *a, const integer *lda, complex_real8 *b, const integer *ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
void ztrtri_ (const char *uplo, const char *diag, const integer *n, const complex_real8 *a, const integer *lda, integer *info)
void zungqr_ (integer *m, integer *n, integer *k, complex_real8 *a, integer *lda, complex_real8 *tau, complex_real8 *work, integer *lwork, integer *info)
Detailed Description
Legacy C++ prototypes for Fortran LAPACK with associated typedefs and macos.
Function Documentation
cgeev_()
void cgeev_ (const char * jobz, const char * uplo, integer * n, complex_real4 * a, integer * lda, complex_real4 * w, complex_real4 * vl, integer * ldvl, complex_real4 * vr, integer * ldvr, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by geev_().
cgels_()
void cgels_ (const char * trans, integer * m, integer * n, integer * nrhs, complex_real4 * a, integer * lda, complex_real4 * b, integer * ldb, complex_real4 * work, integer * lwork, real4 * rwork, integer * infoOUT, char_len translen)
cgelss_()
void cgelss_ (integer * m, integer * n, integer * nrhs, complex_real4 * a, integer * lda, complex_real4 * b, integer * ldb, real4 * sOUT, real4 * rcondIN, integer * rankOUT, complex_real4 * work, integer * lwork, real4 * rwork, integer * infoOUT)
Referenced by gelss_().
cgeqp3_()
void cgeqp3_ (integer * m, integer * n, complex_real4 * a, integer * lda, integer * jpvt, complex_real4 * tau, complex_real4 * work, integer * lwork, real4 * rwork, integer * infoOUT)
Referenced by geqp3_().
cgeqrf_()
void cgeqrf_ (integer * m, integer * n, complex_real4 * a, integer * lda, complex_real4 * tau, complex_real4 * work, integer * lwork, integer * infoOUT)
Referenced by geqrf_().
cgesv_()
void cgesv_ (integer * n, integer * nrhs, complex_real4 * AT, integer * lda, integer * piv, complex_real4 * x, integer * ldx, integer * info)
Referenced by gesv_().
cgesvd_()
void cgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, complex_real4 * a, integer * lda, real4 * s, complex_real4 * u, integer * ldu, complex_real4 * vt, integer * ldvt, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by gesvd_(), and madness::svd().
cgetrf_()
void cgetrf_ (const integer * m, const integer * n, complex_real4 * a, const integer * lda, integer * ipiv, integer * info)
Referenced by getrf_().
cgetri_()
void cgetri_ (const integer * n, complex_real4 * a, const integer * lda, const integer * ipiv, complex_real4 * work, const integer * lwork, integer * info)
Referenced by getri_().
cggev_()
void cggev_ (const char * jobz, const char * uplo, integer * n, complex_real4 * a, integer * lda, complex_real4 * b, integer * ldb, complex_real4 * alpha, complex_real4 * beta, complex_real4 * vl, integer * ldvl, complex_real4 * vr, integer * ldvr, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by ggev_().
cheev_()
void cheev_ (const char * jobz, const char * uplo, integer * n, complex_real4 * a, integer * lda, real4 * w, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig(), and syev_().
chegv_()
void chegv_ (integer * itype, const char * jobz, const char * uplo, integer * n, complex_real4 * a, integer * lda, complex_real4 * b, integer * ldb, real4 * w, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig_gen(), and sygv_().
cpotrf_()
void cpotrf_ (const char * uplo, const integer * n, complex_real4 * a, const integer * lda, integer * info, char_len uplo_len)
Referenced by madness::cholesky(), and potrf_().
cpstrf_()
void cpstrf_ (const char * uplo, const integer * n, complex_real4 * a, const integer * lda, integer * ipiv, integer * rank, real4 * tol, complex_real4 * work, integer * info)
Referenced by pstrf_().
ctrsm_()
void ctrsm_ (const char * side, const char * uplo, const char * transa, const char * diag, const integer * m, const integer * n, const complex_real4 * alpha, const complex_real4 * a, const integer * lda, complex_real4 * b, const integer * ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
ctrtri_()
void ctrtri_ (const char * uplo, const char * diag, const integer * n, const complex_real4 * a, const integer * lda, integer * info)
cungqr_()
void cungqr_ (integer * m, integer * n, integer * k, complex_real4 * a, integer * lda, complex_real4 * tau, complex_real4 * work, integer * lwork, integer * info)
Referenced by orgqr_().
dgeev_()
void dgeev_ (const char * jobz, const char * uplo, integer * n, real8 * a, integer * lda, real8 * w_real, real8 * w_imag, real8 * v, integer * ldv, real8 * vr, integer * ldvr, real8 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by geev_().
dgels_()
void dgels_ (const char * trans, integer * m, integer * n, integer * nrhs, real8 * a, integer * lda, real8 * b, integer * ldb, real8 * work, integer * lwork, integer * infoOUT, char_len translen)
Referenced by solve().
dgelss_()
void dgelss_ (integer * m, integer * n, integer * nrhs, real8 * a, integer * lda, real8 * b, integer * ldb, real8 * sOUT, real8 * rcondIN, integer * rankOUT, real8 * work, integer * lwork, integer * infoOUT)
Referenced by gelss_().
dgeqp3_()
void dgeqp3_ (integer * m, integer * n, real8 * a, integer * lda, integer * jpvt, real8 * tau, real8 * work, integer * lwork, integer * infoOUT)
Referenced by geqp3_().
dgeqrf_()
void dgeqrf_ (integer * m, integer * n, real8 * a, integer * lda, real8 * tau, real8 * work, integer * lwork, integer * infoOUT)
Referenced by geqrf_().
dgesv_()
void dgesv_ (integer * n, integer * nrhs, real8 * AT, integer * lda, integer * piv, real8 * x, integer * ldx, integer * info)
Referenced by gesv_().
dgesvd_()
void dgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, real8 * a, integer * lda, real8 * s, real8 * u, integer * ldu, real8 * vt, integer * ldvt, real8 * work, integer * lwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by gesvd_(), and madness::svd().
dgetrf_()
void dgetrf_ (const integer * m, const integer * n, real8 * a, const integer * lda, integer * ipiv, integer * info)
Referenced by getrf_().
dgetri_()
void dgetri_ (const integer * n, real8 * a, const integer * lda, const integer * ipiv, real8 * work, const integer * lwork, integer * info)
Referenced by getri_().
dggev_()
void dggev_ (const char * jobl, const char * jobr, integer * n, real8 * a, integer * lda, real8 * b, integer * ldb, real8 * w_real, real8 * w_imag, real8 * beta, real8 * vl, integer * ldvl, real8 * vr, integer * ldvr, real8 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by ggev_().
dlamch_()
double dlamch_ (const char * mode, int modelen)
Referenced by madness::init_tensor_lapack().
dorgqr_()
void dorgqr_ (integer * m, integer * n, integer * k, real8 * a, integer * lda, real8 * tau, real8 * work, integer * lwork, integer * info)
Referenced by orgqr_().
dpotrf_()
void dpotrf_ (const char * uplo, const integer * n, real8 * a, const integer * lda, integer * info, char_len uplo_len)
Referenced by madness::cholesky(), and potrf_().
dpstrf_()
void dpstrf_ (const char * uplo, const integer * n, real8 * a, const integer * lda, integer * ipiv, integer * rank, real8 * tol, real8 * work, integer * info)
Referenced by pstrf_().
dsyev_()
void dsyev_ (const char * jobz, const char * uplo, integer * n, real8 * a, integer * lda, real8 * w, real8 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig(), and syev_().
dsygv_()
void dsygv_ (integer * itype, const char * jobz, const char * uplo, integer * n, real8 * a, integer * lda, real8 * b, integer * ldb, real8 * w, real8 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig_gen(), and sygv_().
dtrsm_()
void dtrsm_ (const char * side, const char * uplo, const char * transa, const char * diag, const integer * m, const integer * n, const real8 * alpha, const real8 * a, const integer * lda, real8 * b, const integer * ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
dtrtri_()
void dtrtri_ (const char * uplo, const char * diag, const integer * n, const real8 * a, const integer * lda, integer * info)
sgeev_()
void sgeev_ (const char * jobz, const char * uplo, integer * n, real4 * a, integer * lda, real4 * w_real, real4 * w_imag, real4 * v, integer * ldv, real4 * vr, integer * ldvr, real4 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by geev_().
sgels_()
void sgels_ (const char * trans, integer * m, integer * n, integer * nrhs, real4 * a, integer * lda, real4 * b, integer * ldb, real4 * work, integer * lwork, integer * infoOUT, char_len translen)
sgelss_()
void sgelss_ (integer * m, integer * n, integer * nrhs, real4 * a, integer * lda, real4 * b, integer * ldb, real4 * sOUT, real4 * rcondIN, integer * rankOUT, real4 * work, integer * lwork, integer * infoOUT)
Referenced by gelss_().
sgeqp3_()
void sgeqp3_ (integer * m, integer * n, real4 * a, integer * lda, integer * jpvt, real4 * tau, real4 * work, integer * lwork, integer * infoOUT)
Referenced by geqp3_().
sgeqrf_()
void sgeqrf_ (integer * m, integer * n, real4 * a, integer * lda, real4 * tau, real4 * work, integer * lwork, integer * infoOUT)
Referenced by geqrf_().
sgesv_()
void sgesv_ (integer * n, integer * nrhs, real4 * AT, integer * lda, integer * piv, real4 * x, integer * ldx, integer * info)
Referenced by gesv_().
sgesvd_()
void sgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, real4 * a, integer * lda, real4 * s, real4 * u, integer * ldu, real4 * vt, integer * ldvt, real4 * work, integer * lwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by gesvd_(), and madness::svd().
sgetrf_()
void sgetrf_ (const integer * m, const integer * n, real4 * a, const integer * lda, integer * ipiv, integer * info)
Referenced by getrf_().
sgetri_()
void sgetri_ (const integer * n, real4 * a, const integer * lda, const integer * ipiv, real4 * work, const integer * lwork, integer * info)
Referenced by getri_().
sggev_()
void sggev_ (const char * jobz, const char * uplo, integer * n, real4 * a, integer * lda, real4 * b, integer * ldb, real4 * alphar, real4 * alphai, real4 * beta, real4 * vl, integer * ldvl, real4 * vr, integer * ldvr, real4 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by ggev_().
slamch_()
float slamch_ (const char * mode, int modelen)
Referenced by madness::init_tensor_lapack().
sorgqr_()
void sorgqr_ (integer * m, integer * n, integer * k, real4 * a, integer * lda, real4 * tau, real4 * work, integer * lwork, integer * info)
Referenced by orgqr_().
spotrf_()
void spotrf_ (const char * uplo, const integer * n, real4 * a, const integer * lda, integer * info, char_len uplo_len)
Referenced by madness::cholesky(), and potrf_().
spstrf_()
void spstrf_ (const char * uplo, const integer * n, real4 * a, const integer * lda, integer * ipiv, integer * rank, real4 * tol, real4 * work, integer * info)
Referenced by pstrf_().
ssyev_()
void ssyev_ (const char * jobz, const char * uplo, integer * n, real4 * a, integer * lda, real4 * w, real4 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig(), and syev_().
ssygv_()
void ssygv_ (integer * itype, const char * jobz, const char * uplo, integer * n, real4 * a, integer * lda, real4 * b, integer * ldb, real4 * w, real4 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig_gen(), and sygv_().
strsm_()
void strsm_ (const char * side, const char * uplo, const char * transa, const char * diag, const integer * m, const integer * n, const real4 * alpha, const real4 * a, const integer * lda, real4 * b, const integer * ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
strtri_()
void strtri_ (const char * uplo, const char * diag, const integer * n, const real4 * a, const integer * lda, integer * info)
zgeev_()
void zgeev_ (const char * jobz, const char * uplo, integer * n, complex_real8 * a, integer * lda, complex_real8 * w, complex_real8 * vl, integer * ldvl, complex_real8 * vr, integer * ldvr, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by geev_().
zgels_()
void zgels_ (const char * trans, integer * m, integer * n, integer * nrhs, complex_real8 * a, integer * lda, complex_real8 * b, integer * ldb, complex_real8 * work, integer * lwork, real8 * rwork, integer * infoOUT, char_len translen)
zgelss_()
void zgelss_ (integer * m, integer * n, integer * nrhs, complex_real8 * a, integer * lda, complex_real8 * b, integer * ldb, real8 * sOUT, real8 * rcondIN, integer * rankOUT, complex_real8 * work, integer * lwork, real8 * rwork, integer * infoOUT)
Referenced by gelss_().
zgeqp3_()
void zgeqp3_ (integer * m, integer * n, complex_real8 * a, integer * lda, integer * jpvt, complex_real8 * tau, complex_real8 * work, integer * lwork, real8 * rwork, integer * infoOUT)
Referenced by geqp3_().
zgeqrf_()
void zgeqrf_ (integer * m, integer * n, complex_real8 * a, integer * lda, complex_real8 * tau, complex_real8 * work, integer * lwork, integer * infoOUT)
Referenced by geqrf_().
zgesv_()
void zgesv_ (integer * n, integer * nrhs, complex_real8 * AT, integer * lda, integer * piv, complex_real8 * x, integer * ldx, integer * info)
Referenced by gesv_().
zgesvd_()
void zgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, complex_real8 * a, integer * lda, real8 * s, complex_real8 * u, integer * ldu, complex_real8 * vt, integer * ldvt, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by gesvd_(), and madness::svd().
zgetrf_()
void zgetrf_ (const integer * m, const integer * n, complex_real8 * a, const integer * lda, integer * ipiv, integer * info)
Referenced by getrf_().
zgetri_()
void zgetri_ (const integer * n, complex_real8 * a, const integer * lda, const integer * ipiv, complex_real8 * work, const integer * lwork, integer * info)
Referenced by getri_().
zggev_()
void zggev_ (const char * jobz, const char * uplo, integer * n, complex_real8 * a, integer * lda, complex_real8 * b, integer * ldb, complex_real8 * alpha, complex_real8 * beta, complex_real8 * vl, integer * ldvl, complex_real8 * vr, integer * ldvr, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by ggev_().
zheev_()
void zheev_ (const char * jobz, const char * uplo, integer * n, complex_real8 * a, integer * lda, real8 * w, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig(), and syev_().
zhegv_()
void zhegv_ (integer * itype, const char * jobz, const char * uplo, integer * n, complex_real8 * a, integer * lda, complex_real8 * b, integer * ldb, real8 * w, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by madness::hereig_gen(), and sygv_().
zpotrf_()
void zpotrf_ (const char * uplo, const integer * n, complex_real8 * a, const integer * lda, integer * info, char_len uplo_len)
Referenced by madness::cholesky(), and potrf_().
zpstrf_()
void zpstrf_ (const char * uplo, const integer * n, complex_real8 * a, const integer * lda, integer * ipiv, integer * rank, real8 * tol, complex_real8 * work, integer * info)
Referenced by pstrf_().
ztrsm_()
void ztrsm_ (const char * side, const char * uplo, const char * transa, const char * diag, const integer * m, const integer * n, const complex_real8 * alpha, const complex_real8 * a, const integer * lda, complex_real8 * b, const integer * ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
ztrtri_()
void ztrtri_ (const char * uplo, const char * diag, const integer * n, const complex_real8 * a, const integer * lda, integer * info)
zungqr_()
void zungqr_ (integer * m, integer * n, integer * k, complex_real8 * a, integer * lda, complex_real8 * tau, complex_real8 * work, integer * lwork, integer * info)
Referenced by orgqr_().