MADNESS: madness::profiling::TaskEventList Class Reference
madness::profiling::TaskEventList Class Reference
A list of task events.
#include <thread.h>
Public Member Functions
TaskEventList (const unsigned int nmax)
Default constructor.
virtual ~TaskEventList ()=default
Virtual destructor.
TaskEvent * event ()
Get a new event from this list.
Public Member Functions inherited from madness::profiling::TaskEventListBase
TaskEventListBase ()
Default constructor.
virtual ~TaskEventListBase ()=default
Virtual destructor.
void insert (TaskEventListBase *list)
Insert list after this list.
TaskEventListBase * next () const
Get the next event list in the linked list.
Private Member Functions
TaskEventList (const TaskEventList &)=delete
TaskEventList & operator= (const TaskEventList &)=delete
virtual std::ostream & print_events (std::ostream &os) const
Print events recorded in this list.
Private Attributes
std::unique_ptr< TaskEvent[]> events_
The event array.
unsigned int n_
The number of events recorded.
Detailed Description
A list of task events.
This object is used by the thread pool to record task data.
Constructor & Destructor Documentation
TaskEventList() [1/2]
madness::profiling::TaskEventList::TaskEventList (const TaskEventList &) private delete
TaskEventList() [2/2]
madness::profiling::TaskEventList::TaskEventList (const unsigned int nmax) inline
Default constructor.
Parameters
[in] nmax The maximum number of task events.
Todo:
Should nmax be stored? I think it used to be a template parameter (N), which is no longer present.
~TaskEventList()
virtual madness::profiling::TaskEventList::~TaskEventList () virtual default
Virtual destructor.
Member Function Documentation
event()
TaskEvent * madness::profiling::TaskEventList::event () inline
Get a new event from this list.
Warning
This function can only be called nmax times. It is the caller's resonsibility to ensure that it is not called too many times.
Returns
The new event from the list.
References events_, and n_.
Referenced by madness::ThreadPool::run_task(), and madness::ThreadPool::run_tasks().
operator=()
TaskEventList & madness::profiling::TaskEventList::operator= (const TaskEventList &) private delete
print_events()
virtual std::ostream & madness::profiling::TaskEventList::print_events (std::ostream & os) const inline private virtual
Print events recorded in this list.
Parameters
[in,out] os The output stream.
Returns
The modified output stream.
Implements madness::profiling::TaskEventListBase.
References events_, madness::ThreadBase::get_pool_thread_index(), n_, and madness::ThreadBase::this_thread().
Member Data Documentation
events_
std::unique_ptr<TaskEvent[]> madness::profiling::TaskEventList::events_ private
The event array.
Referenced by event(), and print_events().
n_
unsigned int madness::profiling::TaskEventList::n_ private
The number of events recorded.
Referenced by event(), and print_events().
The documentation for this class was generated from the following file:
thread.h