MADNESS: madness::FunctionDefaults< NDIM > Class Template Reference
madness::FunctionDefaults< NDIM > Class Template Reference
Mra
FunctionDefaults holds default paramaters as static class members.
#include <funcdefaults.h>
Static Public Member Functions
static bool get_apply_randomize ()
Gets the random load balancing for integral operators flag.
static bool get_autorefine ()
Gets the default adaptive autorefinement flag.
static const BoundaryConditions< NDIM > & get_bc ()
Returns the default boundary conditions.
static const Tensor< double > & get_cell ()
Gets the user cell for the simulation.
static double get_cell_min_width ()
Returns the minimum width of any user cell dimension.
static double get_cell_volume ()
Returns the volume of the user cell.
static const Tensor< double > & get_cell_width ()
Returns the width of each user cell dimension.
static bool get_debug ()
Gets the default debug flag (is this used anymore?)
static int get_initial_level ()
Returns the default initial projection level.
static int get_k ()
Returns the default wavelet order.
static int get_max_refine_level ()
Gets the default maximum adaptive refinement level.
static std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & get_pmap ()
Returns the default process map that was last initialized via set_default_pmap()
static std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > get_pmap (World &world)
Returns the default process map that can be used with the given world.
static int get_pmap_nproc ()
Returns number of the default processes returned by get_pmap()
static bool get_project_randomize ()
Gets the random load balancing for projection flag.
static const Tensor< double > & get_rcell_width ()
Returns the reciprocal of the width of each user cell dimension.
static bool get_refine ()
Gets the default adaptive refinement flag.
static int get_special_level ()
Returns the default projection level for special boxes.
static TensorType get_tensor_type ()
Returns the default tensor type.
static const double & get_thresh ()
Returns the default threshold.
static int get_truncate_mode ()
Gets the default truncation mode.
static bool get_truncate_on_project ()
Gets the default truncate on project flag.
static std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > make_default_pmap (World &world)
Makes a default process map for the given world.
static void print ()
static void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &newpmap)
Sets the default process map and redistributes all functions using the old map.
static void set_apply_randomize (bool value)
Sets the random load balancing for integral operators flag.
static void set_autorefine (bool value)
Sets the default adaptive autorefinement flag.
static void set_bc (const BoundaryConditions< NDIM > &value)
Sets the default boundary conditions.
static void set_cell (const Tensor< double > &value)
Gets the user cell for the simulation.
static void set_cubic_cell (double lo, double hi)
Sets the user cell to be cubic with each dimension having range [lo,hi].
static void set_debug (bool value)
Sets the default debug flag (is this used anymore?)
static void set_default_pmap (World &world)
static void set_defaults (World &world)
static void set_initial_level (int value)
Sets the default initial projection level.
static void set_k (int value)
Sets the default wavelet order.
static int set_length_scale (const double lo, const size_t k=get_k())
adapt the special level to resolve the smallest length scale
static void set_max_refine_level (int value)
Sets the default maximum adaptive refinement level.
static void set_pmap (const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &value)
Sets the default process map (does not redistribute existing functions)
static void set_project_randomize (bool value)
Sets the random load balancing for projection flag.
static void set_refine (bool value)
Sets the default adaptive refinement flag.
static void set_special_level (int value)
Existing functions are unaffected.
static void set_tensor_type (const TensorType &t)
Sets the default tensor type.
static void set_thresh (double value)
Sets the default threshold.
static void set_truncate_mode (int value)
Sets the default truncation mode.
static void set_truncate_on_project (bool value)
Sets the default truncate on project flag.
Static Private Member Functions
static Tensor< double > make_default_cell ()
static Tensor< double > make_default_cell_width ()
static void recompute_cell_info ()
Static Private Attributes
static bool apply_randomize = false
If true use randomization for load balancing in apply integral operator.
static bool autorefine = true
Whether to autorefine in multiplication, etc.
static std::optional< BoundaryConditions< NDIM > > bc
Default boundary conditions, not initialized by default and must be set explicitly before use.
static Tensor< double > cell = FunctionDefaults<NDIM>::make_default_cell()
cell[NDIM][2] Simulation cell, cell(0,0)=xlo, cell(0,1)=xhi, ...
static double cell_min_width = 1.
Size of smallest dimension.
static double cell_volume = 1.
Volume of simulation cell.
static Tensor< double > cell_width = FunctionDefaults<NDIM>::make_default_cell_width()
Width of simulation cell in each dimension.
static bool debug = false
Controls output of debug info.
static int initial_level = 2
Initial level for fine scale projection.
static int k = 6
Wavelet order.
static int max_refine_level = 30
Level at which to stop refinement.
static std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > pmap
Default mapping of keys to processes.
static int pmap_nproc {-1}
Number of processes assumed by pmap, -1 indicates uninitialized pmap.
static bool project_randomize = false
If true use randomization for load balancing in project/refine.
static Tensor< double > rcell_width = FunctionDefaults<NDIM>::make_default_cell_width()
Reciprocal of width.
static bool refine = true
Whether to refine new functions.
static int special_level = 3
Minimum level for fine scale projection of special boxes.
static double thresh = 1e-4
Truncation threshold.
static int truncate_mode = 0
Truncation method.
static bool truncate_on_project = true
If true initial projection inserts at n-1 not n.
static TensorType tt = TT_FULL
structure of the tensor in FunctionNode
Detailed Description
template<std::size_t NDIM>
class madness::FunctionDefaults< NDIM >
FunctionDefaults holds default paramaters as static class members.
Declared and initialized in mra.cc and/or funcimpl::initialize.
Currently all functions of the same dimension share the same cell dimensions since they are stored inside FunctionDefaults ... if you change the cell dimensions all functions of that dimension are affected.
N.B. Ultimately, we may need to make these defaults specific to each world, as should be all global state.
Member Function Documentation
get_apply_randomize()
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_apply_randomize () inline static
Gets the random load balancing for integral operators flag.
References madness::FunctionDefaults< NDIM >::apply_randomize.
Referenced by madness::FunctionImpl< T, NDIM >::apply(), and madness::FunctionImpl< T, NDIM >::apply_source_driven().
get_autorefine()
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_autorefine () inline static
Gets the default adaptive autorefinement flag.
References madness::FunctionDefaults< NDIM >::autorefine.
get_bc()
template<std::size_t NDIM> static const BoundaryConditions< NDIM > & madness::FunctionDefaults< NDIM >::get_bc () inline static
Returns the default boundary conditions.
References madness::FunctionDefaults< NDIM >::bc, MADNESS_EXCEPTION, and NDIM.
Referenced by MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), madness::Specialbox_op< T, NDIM >::check_special_points(), laplacian(), madness::ElectronCuspyBox_op< T, NDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::project_refine_op().
get_cell()
template<std::size_t NDIM> static const Tensor< double > & madness::FunctionDefaults< NDIM >::get_cell () inline static
Gets the user cell for the simulation.
References madness::FunctionDefaults< NDIM >::cell.
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), madness::Diamagnetic_potential_factor::compute_nabla_R_div_R(), madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::FunctionImpl< T, NDIM >::do_print_plane(), madness::fcube(), madness::randomgrid< NDIM >::get_grid(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), iterate(), kth_moment_func3d(), madness::Solver< T, NDIM >::make_nuclear_potential(), madness::FunctionImpl< T, NDIM >::print_plane_local(), r2_func3d(), random_gaussian(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), save_function(), madness::sim_to_user(), write_function(), and FunctionIO< T, NDIM >::write_function().
get_cell_min_width()
template<std::size_t NDIM> static double madness::FunctionDefaults< NDIM >::get_cell_min_width () inline static
Returns the minimum width of any user cell dimension.
References madness::FunctionDefaults< NDIM >::cell_min_width.
Referenced by dostuff(), main(), madness::smooth< T, NDIM >::make_plots(), madness::Nemo::make_plots(), madness::qm_free_particle_propagator(), madness::qm_free_particle_propagatorPtr(), slymer::Gaussian_Functor::special_level(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
get_cell_volume()
template<std::size_t NDIM> static double madness::FunctionDefaults< NDIM >::get_cell_volume () inline static
Returns the volume of the user cell.
References madness::FunctionDefaults< NDIM >::cell_volume.
get_cell_width()
template<std::size_t NDIM> static const Tensor< double > & madness::FunctionDefaults< NDIM >::get_cell_width () inline static
Returns the width of each user cell dimension.
References madness::FunctionDefaults< NDIM >::cell_width.
Referenced by madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::GeneralTwoElectronInterface< T, NDIM >::GeneralTwoElectronInterface(), MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), madness::Solver< T, NDIM >::Solver(), madness::Solver< T, NDIM >::Solver(), madness::TwoElectronInterface< T, NDIM >::TwoElectronInterface(), madness::BSHOperatorPtr3D(), madness::DFT< T, NDIM >::calculate_tot_coulomb_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::SeparatedConvolution< Q, NDIM >::check_cubic(), madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::fcube(), madness::GradBSHOperator(), GradBSHOperator_Joel(), madness::GradCoulombOperator(), gradPbarA(), madness::GradSlaterOperator(), madness::Solver< T, NDIM >::initial_guess(), madness::TwoElectronInterface< T, NDIM >::initialize(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), madness::trajectory< NDIM >::line_xyz(), madness::SeparatedConvolution< Q, NDIM >::make_coeff_for_operator(), make_grad_operator(), madness::plot_plane(), madness::plot_plane(), madness::plot_plane(), madness::FunctionImpl< T, NDIM >::print_plane_local(), printfunc(), MolecularEntity::read_file(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), madness::FunctionDefaults< NDIM >::set_length_scale(), madness::FunctionFunctorInterface< T, NDIM >::set_length_scale(), madness::EigSolver< T, NDIM >::solve(), solve(), test_he_potential(), test_modified(), test_opdir(), test_qm(), test_recursive_application(), testNavierStokes(), and testPeriodicCoulomb3d().
get_debug()
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_debug () inline static
Gets the default debug flag (is this used anymore?)
References madness::FunctionDefaults< NDIM >::debug.
get_initial_level()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_initial_level () inline static
Returns the default initial projection level.
References madness::FunctionDefaults< NDIM >::initial_level.
get_k()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_k () inline static
Returns the default wavelet order.
References madness::FunctionDefaults< NDIM >::k.
Referenced by madness::TwoElectronFactory< T, NDIM >::TwoElectronFactory(), MiniDFT::doit(), gradPbarA(), madness::SCF::load_mos(), Calculation::load_mos(), madness::Solver< T, NDIM >::load_orbitals(), main(), madness::EigSolver< T, NDIM >::make_bsh_operators(), madness::density_mask_operator::operator()(), madness::MolecularEnergy::output_calc_info_schema(), madness::SCF::output_scf_info_schema(), madness::Znemo::read_real_guess(), madness::SCF::save_mos(), madness::Derivative< T, NDIM >::set_ble1(), madness::Derivative< T, NDIM >::set_ble2(), madness::Derivative< T, NDIM >::set_bspline1(), madness::Derivative< T, NDIM >::set_bspline2(), madness::Derivative< T, NDIM >::set_bspline3(), madness::apply_kernel_helper::slater_apply(), solve(), test_adaptive_tree(), test_conversion(), and test_opdir().
get_max_refine_level()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_max_refine_level () inline static
Gets the default maximum adaptive refinement level.
References madness::FunctionDefaults< NDIM >::max_refine_level.
Referenced by madness::FunctionImpl< T, NDIM >::partial_inner().
get_pmap() [1/2]
template<std::size_t NDIM> static std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & madness::FunctionDefaults< NDIM >::get_pmap () inline static
Returns the default process map that was last initialized via set_default_pmap()
References madness::World::get_default(), madness::initialized(), madness::FunctionDefaults< NDIM >::pmap, and madness::FunctionDefaults< NDIM >::set_default_pmap().
Referenced by madness::copy(), madness::FunctionDefaults< NDIM >::get_pmap(), madness::SCF::make_fock_matrix(), madness::MacroTaskQ::run_all(), and trotter().
get_pmap() [2/2]
template<std::size_t NDIM> static std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > madness::FunctionDefaults< NDIM >::get_pmap (World & world) inline static
Returns the default process map that can be used with the given world.
References madness::FunctionDefaults< NDIM >::get_pmap(), madness::FunctionDefaults< NDIM >::get_pmap_nproc(), madness::FunctionDefaults< NDIM >::make_default_pmap(), and madness::World::nproc().
get_pmap_nproc()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_pmap_nproc () inline static
Returns number of the default processes returned by get_pmap()
References madness::FunctionDefaults< NDIM >::pmap_nproc.
Referenced by madness::FunctionDefaults< NDIM >::get_pmap().
get_project_randomize()
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_project_randomize () inline static
Gets the random load balancing for projection flag.
References madness::FunctionDefaults< NDIM >::project_randomize.
get_rcell_width()
template<std::size_t NDIM> static const Tensor< double > & madness::FunctionDefaults< NDIM >::get_rcell_width () inline static
Returns the reciprocal of the width of each user cell dimension.
References madness::FunctionDefaults< NDIM >::rcell_width.
Referenced by madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::do_diff2i(), and madness::user_to_sim().
get_refine()
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_refine () inline static
Gets the default adaptive refinement flag.
References madness::FunctionDefaults< NDIM >::refine.
get_special_level()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_special_level () inline static
Returns the default projection level for special boxes.
References madness::FunctionDefaults< NDIM >::special_level.
get_tensor_type()
template<std::size_t NDIM> static TensorType madness::FunctionDefaults< NDIM >::get_tensor_type () inline static
Returns the default tensor type.
References madness::FunctionDefaults< NDIM >::tt.
Referenced by madness::zero_functions_auto_tree_state().
get_thresh()
template<std::size_t NDIM> static const double & madness::FunctionDefaults< NDIM >::get_thresh () inline static
Returns the default threshold.
References madness::FunctionDefaults< NDIM >::thresh.
Referenced by madness::Localizer::Localizer(), madness::TwoElectronFactory< T, NDIM >::TwoElectronFactory(), madness::MP2::add_local_coupling(), apply_periodic_bsh(), madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), madness::MolecularOrbitals< T, NDIM >::compute_center(), madness::CC2::compute_local_coupling(), dnuclear_anchor_test(), do_plot(), MiniDFT::doit(), madness::estimate_area(), madness::smooth< T, NDIM >::get_density_thresh(), madness::MP2::guess_mp1_3(), GygiPot::GuessPotential(), madness::hartree_product(), madness::hartree_product(), madness::TDHF::initialize(), madness::Znemo::iterate(), madness::SCF::load_mos(), Calculation::load_mos(), madness::Solver< T, NDIM >::load_orbitals(), main(), madness::EigSolver< T, NDIM >::make_bsh_operators(), madness::Solver< T, NDIM >::make_bsh_operators(), MiniDFT::make_bsh_operators(), madness::SCF::make_bsh_operators(), MiniDFT::make_coulomb_potential(), DF::make_fermi_potential(), madness::Nemo::make_sigma(), madness::MP2::make_Uphi0(), molresponseExchange(), nuclear_anchor_test(), madness::StrongOrthogonalityProjector< T, NDIM >::operator()(), madness::DNuclear< T, NDIM >::operator()(), madness::XCOperator< T, NDIM >::operator()(), madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize(), madness::PNO::orthonormalize_cholesky(), madness::MolecularEnergy::output_calc_info_schema(), madness::SCF::output_scf_info_schema(), madness::FunctionImpl< T, NDIM >::partial_inner(), madness::CCPairFunction< T, NDIM >::remove_linearly_dependent_terms(), madness::Znemo::rotate_subspace(), madness::Nemo_complex_Parameters::set_derived_values(), Calculation::set_protocol(), madness::SCF::set_protocol(), madness::smooth< T, NDIM >::smooth_density_from_orbitals(), madness::EigSolver< T, NDIM >::solve(), solve(), test_adaptive_tree(), test_arithmetic(), test_combined_operators(), test_converged_function(), test_coulomb(), test_dnuclear(), madness::test_exchange(), test_exchange(), test_fock(), test_gconv(), madness::Diamagnetic_potential_factor::test_harmonic_potential(), test_inner(), test_inner(), test_Kcommutator(), test_kinetic(), madness::Diamagnetic_potential_factor::test_lz_commutator(), test_multiply(), test_multiply_with_f12(), test_nemo(), test_nuclear(), test_partial_inner_3d(), test_partial_inner_6d(), test_projector(), test_Q12_projector(), test_scalar_multiplication(), madness::Diamagnetic_potential_factor::test_scalar_potentials(), test_slater_exchange(), madness::Znemo::test_U_potentials(), madness::Diamagnetic_potential_factor::test_vector_potentials(), test_XCOperator(), madness::PNO::transform_pairs(), and madness::SCF::twoint().
get_truncate_mode()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_truncate_mode () inline static
Gets the default truncation mode.
References madness::FunctionDefaults< NDIM >::truncate_mode.
get_truncate_on_project()
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_truncate_on_project () inline static
Gets the default truncate on project flag.
References madness::FunctionDefaults< NDIM >::truncate_on_project.
make_default_cell()
template<std::size_t NDIM> static Tensor< double > madness::FunctionDefaults< NDIM >::make_default_cell () inline static private
References madness::_(), madness::FunctionDefaults< NDIM >::cell, and NDIM.
make_default_cell_width()
template<std::size_t NDIM> static Tensor< double > madness::FunctionDefaults< NDIM >::make_default_cell_width () inline static private
References madness::_(), madness::FunctionDefaults< NDIM >::cell, and NDIM.
make_default_pmap()
template<std::size_t NDIM> std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > madness::FunctionDefaults< NDIM >::make_default_pmap (World & world) static
Makes a default process map for the given world.
Referenced by madness::FunctionDefaults< NDIM >::get_pmap().
print()
template<std::size_t NDIM> void madness::FunctionDefaults< NDIM >::print () static
References debug, k, NDIM, madness::refine(), thresh, and truncate_mode.
Referenced by main().
recompute_cell_info()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::recompute_cell_info () inline static private
References madness::_(), madness::FunctionDefaults< NDIM >::cell, madness::FunctionDefaults< NDIM >::cell_min_width, madness::FunctionDefaults< NDIM >::cell_volume, madness::FunctionDefaults< NDIM >::cell_width, madness::copy(), madness::BaseTensor::dim(), MADNESS_ASSERT, madness::Tensor< T >::min(), NDIM, madness::BaseTensor::ndim(), madness::Tensor< T >::product(), and madness::FunctionDefaults< NDIM >::rcell_width.
Referenced by madness::FunctionDefaults< NDIM >::set_cell(), and madness::FunctionDefaults< NDIM >::set_cubic_cell().
redistribute()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::redistribute (World & world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & newpmap) inline static
Sets the default process map and redistributes all functions using the old map.
References madness::FunctionDefaults< NDIM >::pmap.
Referenced by DF::DF_load_balance(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), initial_loadbal(), iterate(), madness::load_balance(), EmbeddedDirichlet::load_balance(), load_balance(), madness::load_balance(), madness::SCF::loadbal(), loadbal(), loadbal(), main(), preloadbal(), run(), and test().
set_apply_randomize()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_apply_randomize (bool value) inline static
Sets the random load balancing for integral operators flag.
References madness::FunctionDefaults< NDIM >::apply_randomize.
Referenced by doit(), main(), Calculation::set_protocol(), madness::SCF::set_protocol(), test2(), and test_coulomb().
set_autorefine()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_autorefine (bool value) inline static
Sets the default adaptive autorefinement flag.
Existing functions are unaffected
References madness::FunctionDefaults< NDIM >::autorefine.
Referenced by doit(), main(), moments(), Calculation::set_protocol(), madness::SCF::set_protocol(), test2(), test_bsh(), test_hf_be(), test_hf_he(), test_math(), test_opdir(), test_proj(), test_unaryop(), and testgradG().
set_bc()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_bc (const BoundaryConditions< NDIM > & value) inline static
Sets the default boundary conditions.
References madness::FunctionDefaults< NDIM >::bc.
Referenced by madness::Solver< T, NDIM >::Solver(), laplacian(), main(), test(), test_gaussian_num_coeffs(), test_gconv(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), and testNavierStokes().
set_cell()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_cell (const Tensor< double > & value) inline static
Gets the user cell for the simulation.
Existing functions are probably rendered useless
References madness::FunctionDefaults< NDIM >::cell, madness::copy(), and madness::FunctionDefaults< NDIM >::recompute_cell_info().
Referenced by FunctionIOData< T, NDIM >::create_function(), doit(), Plotter::doplot1(), read_function(), FunctionIO< T, NDIM >::read_function(), test_add(), test_basic(), test_cross(), test_dot(), test_inner(), test_matrix_mul_sparse(), test_multi_to_multi_op(), test_opdir(), test_rot(), test_transform(), and testgradG().
set_cubic_cell()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_cubic_cell (double lo, double hi) inline static
Sets the user cell to be cubic with each dimension having range [lo,hi].
Existing functions are probably rendered useless
References madness::_(), madness::FunctionDefaults< NDIM >::cell, lo, and madness::FunctionDefaults< NDIM >::recompute_cell_info().
Referenced by Calculation::Calculation(), MiniDFT::MiniDFT(), madness::SCF::SCF(), madness::Znemo::Znemo(), doit(), madness::Solver< T, NDIM >::init(), initialize(), main(), main(), madness::InitParameters::read(), madness::InitParameters::readnw(), run(), madness::SCF::set_protocol(), test(), test(), test2(), test2(), madness::smooth< T, NDIM >::test_1d(), test_apply_push_1d(), test_bsh(), test_chin_chen(), test_combined_operators(), test_conv(), test_coulomb(), test_diff(), test_dnuclear(), madness::test_exchange(), test_exchange(), test_gaussian_num_coeffs(), test_he(), test_he_potential(), test_hf_be(), test_hf_h2(), test_hf_he(), test_hydro(), test_io(), test_kinetic(), test_math(), test_nuclear(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_op(), test_per(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), test_plot(), test_proj(), test_qm(), test_trotter(), test_unaryop(), test_xc2(), test_XCOperator(), testNavierStokes(), and testPeriodicCoulomb3d().
set_debug()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_debug (bool value) inline static
Sets the default debug flag (is this used anymore?)
Not sure if this does anything useful
References madness::FunctionDefaults< NDIM >::debug.
set_default_pmap()
template<std::size_t NDIM> void madness::FunctionDefaults< NDIM >::set_default_pmap (World & world) static
Sets the default process map for the use with WorldObjects in world
Note
sets default pmap to make_default_pmap(world)
References madness::World::nproc().
Referenced by madness::FunctionDefaults< NDIM >::get_pmap(), madness::MacroTaskQ::set_pmap(), and test_size().
set_defaults()
template<std::size_t NDIM> void madness::FunctionDefaults< NDIM >::set_defaults (World & world) static
Used to set defaults to k=7, thresh=1-5, for a unit cube [0,1].
Warning
does not reset the boundary conditions if they are already set
References madness::BC_FREE, debug, e(), k, madness::refine(), thresh, truncate_mode, and madness::TT_FULL.
Referenced by initialize(), main(), and madness::startup().
set_initial_level()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_initial_level (int value) inline static
Sets the default initial projection level.
Existing functions are unaffected
References madness::FunctionDefaults< NDIM >::initial_level, MADNESS_ASSERT, and madness::MAXLEVEL.
Referenced by EmbeddedDirichlet::EmbeddedDirichlet(), madness::Znemo::Znemo(), doit(), madness::CC2::initialize(), initialize(), main(), Calculation::set_protocol(), madness::SCF::set_protocol(), test(), test2(), test2(), test_add(), test_apply_push_1d(), test_basic(), test_bsh(), test_coulomb(), test_cross(), test_diff(), test_dot(), test_he(), test_hf_be(), test_hf_h2(), test_hf_he(), test_inner(), test_io(), test_math(), test_matrix_mul_sparse(), test_multi_to_multi_op(), test_op(), test_opdir(), test_plot(), test_proj(), test_qm(), test_rot(), test_transform(), and testgradG().
set_k()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_k (int value) inline static
Sets the default wavelet order.
Existing functions are unaffacted.
References madness::FunctionDefaults< NDIM >::k, MADNESS_ASSERT, and madness::MAXK.
Referenced by DF::DF(), MiniDFT::MiniDFT(), madness::Znemo::Znemo(), MiniDFT::doit(), doit(), dostuff(), madness::Solver< T, NDIM >::init(), madness::CC2::initialize(), initialize(), load_function(), main(), madness::main(), main(), GroundStateCalculation::read(), madness::InitParameters::read(), madness::InitParameters::readnw(), madness::Solver< T, NDIM >::reproject(), run(), Calculation::set_protocol(), madness::SCF::set_protocol(), test(), test(), test2(), test2(), madness::smooth< T, NDIM >::test_1d(), test_add(), test_apply_push_1d(), test_basic(), test_bsh(), test_chin_chen(), test_combined_operators(), test_coulomb(), test_cross(), test_diff(), test_dot(), test_gaussian_num_coeffs(), test_he(), test_he_potential(), test_hf_be(), test_hf_h2(), test_hf_he(), test_hydro(), test_inner(), test_io(), test_math(), test_matrix_mul_sparse(), test_multi_to_multi_op(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_op(), test_opdir(), test_per(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), test_plot(), test_proj(), test_qm(), test_rot(), test_transform(), test_trotter(), test_unaryop(), test_xc2(), testgradG(), testNavierStokes(), and testPeriodicCoulomb3d().
set_length_scale()
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::set_length_scale (const double lo, const size_t k = get_k()) inline static
adapt the special level to resolve the smallest length scale
References madness::FunctionDefaults< NDIM >::get_cell_width(), madness::FunctionDefaults< NDIM >::k, lo, madness::Tensor< T >::max(), and madness::FunctionDefaults< NDIM >::special_level.
Referenced by madness::BasisFunctions::SolidHarmonicGaussian::special_level().
set_max_refine_level()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_max_refine_level (int value) inline static
Sets the default maximum adaptive refinement level.
Existing functions are unaffected
References madness::FunctionDefaults< NDIM >::initial_level, MADNESS_ASSERT, madness::FunctionDefaults< NDIM >::max_refine_level, madness::MAXLEVEL, and madness::FunctionDefaults< NDIM >::special_level.
Referenced by main().
set_pmap()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_pmap (const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & value) inline static
Sets the default process map (does not redistribute existing functions)
Existing functions are probably rendered useless
References madness::FunctionDefaults< NDIM >::pmap.
Referenced by doit(), loadbal(), main(), madness::SCF::make_fock_matrix(), madness::MacroTaskQ::run_all(), test2(), and trotter().
set_project_randomize()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_project_randomize (bool value) inline static
Sets the random load balancing for projection flag.
References madness::FunctionDefaults< NDIM >::project_randomize.
Referenced by main(), Calculation::set_protocol(), madness::SCF::set_protocol(), and test2().
set_refine()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_refine (bool value) inline static
Sets the default adaptive refinement flag.
Existing functions are unaffected
References madness::FunctionDefaults< NDIM >::refine.
Referenced by madness::Znemo::Znemo(), doit(), initialize(), main(), Calculation::set_protocol(), madness::SCF::set_protocol(), test(), test_add(), test_apply_push_1d(), test_basic(), test_bsh(), test_coulomb(), test_cross(), test_diff(), test_dot(), test_he(), test_hf_be(), test_hf_h2(), test_hf_he(), test_inner(), test_io(), test_math(), test_matrix_mul_sparse(), test_multi_to_multi_op(), test_op(), test_opdir(), test_plot(), test_proj(), test_qm(), test_rot(), test_transform(), and testgradG().
set_special_level()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_special_level (int value) inline static
Existing functions are unaffected.
References MADNESS_ASSERT, madness::FunctionDefaults< NDIM >::max_refine_level, madness::MAXLEVEL, and madness::FunctionDefaults< NDIM >::special_level.
Referenced by madness::CC2::initialize().
set_tensor_type()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_tensor_type (const TensorType & t) inline static
Sets the default tensor type.
References madness::FunctionDefaults< NDIM >::tt, and madness::TT_FULL.
Referenced by main(), test_hartree_product(), test_multiply(), test_partial_inner(), test_projector(), test_Q12_projector(), and test_vector_composite().
set_thresh()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_thresh (double value) inline static
Sets the default threshold.
Existing functions are unaffected
References madness::FunctionDefaults< NDIM >::thresh.
Referenced by DF::DF(), MiniDFT::MiniDFT(), madness::Znemo::Znemo(), MiniDFT::doit(), doit(), dostuff(), madness::MP2::guess_mp1_3(), madness::Solver< T, NDIM >::init(), madness::CC2::initialize(), initialize(), load_function(), main(), main(), madness::Nemo::make_sigma(), madness::StrongOrthogonalityProjector< T, NDIM >::operator()(), madness::Solver< T, NDIM >::reproject(), run(), Calculation::set_protocol(), madness::SCF::set_protocol(), test(), test(), test2(), test2(), madness::smooth< T, NDIM >::test_1d(), test_add(), test_apply_push_1d(), test_basic(), test_bsh(), test_chin_chen(), test_combined_operators(), test_coulomb(), test_cross(), test_diff(), test_dnuclear(), test_dot(), madness::test_exchange(), test_exchange(), test_fock(), test_gaussian_num_coeffs(), test_he(), test_he_potential(), test_hf_be(), test_hf_h2(), test_hf_he(), test_hydro(), test_inner(), test_io(), test_math(), test_matrix_mul_sparse(), test_multi_to_multi_op(), test_nemo(), test_nuclear(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_op(), test_opdir(), test_partial_inner(), test_per(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), test_plot(), test_proj(), test_qm(), test_rot(), test_tight_diffuse(), test_transform(), test_trotter(), test_unaryop(), test_xc2(), test_XCOperator(), testgradG(), testNavierStokes(), testPeriodicCoulomb3d(), and madness::Nemo::value().
set_truncate_mode()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_truncate_mode (int value) inline static
Sets the default truncation mode.
Existing functions are unaffected
References MADNESS_ASSERT, and madness::FunctionDefaults< NDIM >::truncate_mode.
Referenced by DF::DF(), MiniDFT::MiniDFT(), madness::MP2::MP2(), madness::SCF::SCF(), madness::Znemo::Znemo(), doit(), madness::CC2::initialize(), initialize(), main(), main(), run(), Calculation::set_protocol(), test(), test(), test2(), test2(), test_add(), test_basic(), test_bsh(), test_coulomb(), test_cross(), test_diff(), test_dot(), test_he(), test_hf_be(), test_hf_h2(), test_hf_he(), test_inner(), test_io(), test_math(), test_matrix_mul_sparse(), test_multi_to_multi_op(), test_op(), test_opdir(), test_per(), test_proj(), test_qm(), test_rot(), test_transform(), and testgradG().
set_truncate_on_project()
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_truncate_on_project (bool value) inline static
Sets the default truncate on project flag.
Existing functions are unaffected
References madness::FunctionDefaults< NDIM >::truncate_on_project.
Referenced by doit(), main(), test(), test2(), test_bsh(), test_opdir(), test_per(), test_proj(), and testgradG().
Member Data Documentation
apply_randomize
template<std::size_t NDIM> bool madness::FunctionDefaults< NDIM >::apply_randomize = false static private
If true use randomization for load balancing in apply integral operator.
Referenced by madness::FunctionDefaults< NDIM >::get_apply_randomize(), and madness::FunctionDefaults< NDIM >::set_apply_randomize().
autorefine
template<std::size_t NDIM> bool madness::FunctionDefaults< NDIM >::autorefine = true static private
Whether to autorefine in multiplication, etc.
Referenced by madness::FunctionDefaults< NDIM >::get_autorefine(), and madness::FunctionDefaults< NDIM >::set_autorefine().
bc
template<std::size_t NDIM> std::optional< BoundaryConditions< NDIM > > madness::FunctionDefaults< NDIM >::bc static private
Default boundary conditions, not initialized by default and must be set explicitly before use.
Referenced by madness::FunctionDefaults< NDIM >::get_bc(), and madness::FunctionDefaults< NDIM >::set_bc().
cell
template<std::size_t NDIM> Tensor< double > madness::FunctionDefaults< NDIM >::cell = FunctionDefaults<NDIM>::make_default_cell() static private
cell[NDIM][2] Simulation cell, cell(0,0)=xlo, cell(0,1)=xhi, ...
Referenced by madness::FunctionDefaults< NDIM >::get_cell(), madness::FunctionDefaults< NDIM >::make_default_cell(), madness::FunctionDefaults< NDIM >::make_default_cell_width(), madness::FunctionDefaults< NDIM >::recompute_cell_info(), madness::FunctionDefaults< NDIM >::set_cell(), and madness::FunctionDefaults< NDIM >::set_cubic_cell().
cell_min_width
template<std::size_t NDIM> double madness::FunctionDefaults< NDIM >::cell_min_width = 1. static private
Size of smallest dimension.
Referenced by madness::FunctionDefaults< NDIM >::get_cell_min_width(), and madness::FunctionDefaults< NDIM >::recompute_cell_info().
cell_volume
template<std::size_t NDIM> double madness::FunctionDefaults< NDIM >::cell_volume = 1. static private
Volume of simulation cell.
Referenced by madness::FunctionDefaults< NDIM >::get_cell_volume(), and madness::FunctionDefaults< NDIM >::recompute_cell_info().
cell_width
template<std::size_t NDIM> Tensor< double > madness::FunctionDefaults< NDIM >::cell_width = FunctionDefaults<NDIM>::make_default_cell_width() static private
Width of simulation cell in each dimension.
Referenced by madness::FunctionDefaults< NDIM >::get_cell_width(), and madness::FunctionDefaults< NDIM >::recompute_cell_info().
debug
template<std::size_t NDIM> bool madness::FunctionDefaults< NDIM >::debug = false static private
Controls output of debug info.
Referenced by madness::FunctionDefaults< NDIM >::get_debug(), and madness::FunctionDefaults< NDIM >::set_debug().
initial_level
template<std::size_t NDIM> int madness::FunctionDefaults< NDIM >::initial_level = 2 static private
Initial level for fine scale projection.
Referenced by madness::FunctionDefaults< NDIM >::get_initial_level(), madness::FunctionDefaults< NDIM >::set_initial_level(), and madness::FunctionDefaults< NDIM >::set_max_refine_level().
k
template<std::size_t NDIM> int madness::FunctionDefaults< NDIM >::k = 6 static private
Wavelet order.
Referenced by madness::FunctionDefaults< NDIM >::get_k(), madness::FunctionDefaults< NDIM >::set_k(), and madness::FunctionDefaults< NDIM >::set_length_scale().
max_refine_level
template<std::size_t NDIM> int madness::FunctionDefaults< NDIM >::max_refine_level = 30 static private
Level at which to stop refinement.
Referenced by madness::FunctionDefaults< NDIM >::get_max_refine_level(), madness::FunctionDefaults< NDIM >::set_max_refine_level(), and madness::FunctionDefaults< NDIM >::set_special_level().
pmap
template<std::size_t NDIM> std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > madness::FunctionDefaults< NDIM >::pmap static private
Default mapping of keys to processes.
Referenced by madness::FunctionDefaults< NDIM >::get_pmap(), madness::FunctionDefaults< NDIM >::redistribute(), and madness::FunctionDefaults< NDIM >::set_pmap().
pmap_nproc
template<std::size_t NDIM> int madness::FunctionDefaults< NDIM >::pmap_nproc {-1} static private
Number of processes assumed by pmap, -1 indicates uninitialized pmap.
Referenced by madness::FunctionDefaults< NDIM >::get_pmap_nproc().
project_randomize
template<std::size_t NDIM> bool madness::FunctionDefaults< NDIM >::project_randomize = false static private
If true use randomization for load balancing in project/refine.
Referenced by madness::FunctionDefaults< NDIM >::get_project_randomize(), and madness::FunctionDefaults< NDIM >::set_project_randomize().
rcell_width
template<std::size_t NDIM> Tensor< double > madness::FunctionDefaults< NDIM >::rcell_width = FunctionDefaults<NDIM>::make_default_cell_width() static private
Reciprocal of width.
Referenced by madness::FunctionDefaults< NDIM >::get_rcell_width(), and madness::FunctionDefaults< NDIM >::recompute_cell_info().
refine
template<std::size_t NDIM> bool madness::FunctionDefaults< NDIM >::refine = true static private
Whether to refine new functions.
Referenced by madness::FunctionDefaults< NDIM >::get_refine(), and madness::FunctionDefaults< NDIM >::set_refine().
special_level
template<std::size_t NDIM> int madness::FunctionDefaults< NDIM >::special_level = 3 static private
Minimum level for fine scale projection of special boxes.
Referenced by madness::FunctionDefaults< NDIM >::get_special_level(), madness::FunctionDefaults< NDIM >::set_length_scale(), madness::FunctionDefaults< NDIM >::set_max_refine_level(), and madness::FunctionDefaults< NDIM >::set_special_level().
thresh
template<std::size_t NDIM> double madness::FunctionDefaults< NDIM >::thresh = 1e-4 static private
Truncation threshold.
Referenced by madness::FunctionDefaults< NDIM >::get_thresh(), madness::PotentialManager::make_nuclear_potential(), and madness::FunctionDefaults< NDIM >::set_thresh().
truncate_mode
template<std::size_t NDIM> int madness::FunctionDefaults< NDIM >::truncate_mode = 0 static private
Truncation method.
Referenced by madness::FunctionDefaults< NDIM >::get_truncate_mode(), and madness::FunctionDefaults< NDIM >::set_truncate_mode().
truncate_on_project
template<std::size_t NDIM> bool madness::FunctionDefaults< NDIM >::truncate_on_project = true static private
If true initial projection inserts at n-1 not n.
Referenced by madness::FunctionDefaults< NDIM >::get_truncate_on_project(), and madness::FunctionDefaults< NDIM >::set_truncate_on_project().
tt
template<std::size_t NDIM> TensorType madness::FunctionDefaults< NDIM >::tt = TT_FULL static private
structure of the tensor in FunctionNode
Referenced by madness::FunctionDefaults< NDIM >::get_tensor_type(), and madness::FunctionDefaults< NDIM >::set_tensor_type().
The documentation for this class was generated from the following files:
funcdefaults.h
mraimpl.h