MADNESS: QuasiNewton Class Reference
QuasiNewton Class Reference
Optimization via quasi-Newton (BFGS or SR1 update)
Public Member Functions
QuasiNewton (const std::shared_ptr< OptimizationTargetInterface > &target, double tol=1e-6, double value_precision=1e-12, double gradient_precision=1e-12)
bool converged () const
double gradient_norm () const
bool optimize (Tensor< double > &x)
void set_update (const string &method)
double value () const
Public Member Functions inherited from madness::OptimizerInterface
virtual ~OptimizerInterface ()
Private Member Functions
void hessian_update_bfgs (const Tensor< double > &dx, const Tensor< double > &dg)
void hessian_update_sr1 (const Tensor< double > &s, const Tensor< double > &y)
double line_search (double a1, double f0, double dxgrad, const Tensor< double > &x, const Tensor< double > &dx)
Tensor< double > new_search_direction (const Tensor< double > &g)
Private Attributes
double f
double gnorm
const double gradient_precision
Tensor< double > h
int n
std::shared_ptr< OptimizationTargetInterface > target
const double tol
string update
const double value_precision
Detailed Description
Optimization via quasi-Newton (BFGS or SR1 update)
Constructor & Destructor Documentation
QuasiNewton()
QuasiNewton::QuasiNewton (const std::shared_ptr< OptimizationTargetInterface > & target, double tol = 1e-6, double value_precision = 1e-12, double gradient_precision = 1e-12) inline
References target.
Member Function Documentation
converged()
bool QuasiNewton::converged () const inline virtual
Implements madness::OptimizerInterface.
References gnorm, and tol.
Referenced by optimize().
gradient_norm()
double QuasiNewton::gradient_norm () const inline virtual
Implements madness::OptimizerInterface.
References gnorm.
hessian_update_bfgs()
void QuasiNewton::hessian_update_bfgs (const Tensor< double > & dx, const Tensor< double > & dg) inline private
References madness::abs(), h, madness::inner(), and n.
Referenced by optimize().
hessian_update_sr1()
void QuasiNewton::hessian_update_sr1 (const Tensor< double > & s, const Tensor< double > & y) inline private
References madness::abs(), e(), h, madness::inner(), madness::outer(), q(), and madness::Tensor< T >::scale().
Referenced by optimize().
line_search()
double QuasiNewton::line_search (double a1, double f0, double dxgrad, const Tensor< double > & x, const Tensor< double > & dx) inline private
References a1, a2, madness::abs(), f1, madness::print(), target, and value_precision.
Referenced by optimize().
new_search_direction()
Tensor< double > QuasiNewton::new_search_direction (const Tensor< double > & g) inline private
References madness::abs(), e(), madness::g, gradient_precision, h, madness::inner(), n, madness::syev(), tol, and v.
Referenced by optimize().
optimize()
bool QuasiNewton::optimize (Tensor< double > & x) inline virtual
Implements madness::OptimizerInterface.
References converged(), madness::BaseTensor::dim(), f, madness::g, gnorm, h, hessian_update_bfgs(), hessian_update_sr1(), line_search(), n, new_search_direction(), madness::Tensor< T >::normf(), madness::print(), madness::Tensor< T >::scale(), madness::BaseTensor::size(), target, update, and value_precision.
Referenced by main().
set_update()
void QuasiNewton::set_update (const string & method) inline
References update.
Referenced by main().
value()
double QuasiNewton::value () const inline virtual
Implements madness::OptimizerInterface.
References f.
Member Data Documentation
f
double QuasiNewton::f private
Referenced by optimize(), and value().
gnorm
double QuasiNewton::gnorm private
Referenced by converged(), gradient_norm(), and optimize().
gradient_precision
const double QuasiNewton::gradient_precision private
Referenced by new_search_direction().
h
Tensor<double> QuasiNewton::h private
Referenced by hessian_update_bfgs(), hessian_update_sr1(), new_search_direction(), and optimize().
n
int QuasiNewton::n private
Referenced by hessian_update_bfgs(), new_search_direction(), and optimize().
target
std::shared_ptr<OptimizationTargetInterface> QuasiNewton::target private
Referenced by QuasiNewton(), line_search(), and optimize().
tol
const double QuasiNewton::tol private
Referenced by converged(), and new_search_direction().
update
string QuasiNewton::update private
Referenced by optimize(), and set_update().
value_precision
const double QuasiNewton::value_precision private
Referenced by line_search(), and optimize().
The documentation for this class was generated from the following file:
kain.cc