MADNESS: madness::scf_data Class Reference
madness::scf_data Class Reference
#include <SCF.h>
Public Member Functions
scf_data ()
void add_data (std::map< std::string, double > values)
void add_gradient (const Tensor< double > &grad)
void print_data ()
void to_json (json &j) const
Private Attributes
std::map< std::string, std::vector< double > > e_data
json gradient
json hessian
int iter
Constructor & Destructor Documentation
scf_data()
madness::scf_data::scf_data ()
References e_data.
Member Function Documentation
add_data()
void madness::scf_data::add_data (std::map< std::string, double > values)
References e_data, iter, and v.
Referenced by madness::SCF::solve().
add_gradient()
void madness::scf_data::add_gradient (const Tensor< double > & grad)
References madness::grad(), and gradient.
Referenced by main().
print_data()
void madness::scf_data::print_data ()
References e_data, and madness::print().
to_json()
void madness::scf_data::to_json (json & j) const
References e(), e_data, iter, and madness::print().
Referenced by madness::MolecularEnergy::output_calc_info_schema(), and madness::SCF::output_calc_info_schema().
Member Data Documentation
e_data
std::map<std::string, std::vector<double> > madness::scf_data::e_data private
Referenced by scf_data(), add_data(), print_data(), and to_json().
gradient
json madness::scf_data::gradient private
Referenced by add_gradient().
hessian
json madness::scf_data::hessian private
iter
int madness::scf_data::iter private
Referenced by add_data(), and to_json().
The documentation for this class was generated from the following files:
SCF.h
SCF.cc