MADNESS: madness::MutexWaiter Class Reference
madness::MutexWaiter Class Reference
#include <worldmutex.h>
Public Member Functions
MutexWaiter ()
void reset ()
void wait ()
Private Member Functions
void yield (int us)
Private Attributes
unsigned int count
Constructor & Destructor Documentation
MutexWaiter()
madness::MutexWaiter::MutexWaiter () inline
Member Function Documentation
reset()
void madness::MutexWaiter::reset () inline
References count.
Referenced by madness::ThreadPool::await(), and madness::RMI::RmiTask::process_some().
wait()
void madness::MutexWaiter::wait ()
References count, madness::cpu_relax(), and yield().
Referenced by madness::ThreadPool::await(), madness::Hash_private::bin< keyT, valueT >::find(), and madness::Hash_private::bin< keyT, valueT >::insert().
yield()
void madness::MutexWaiter::yield (int us) inline private
Yield for specified number of microseconds unless dedicated CPU Blue Gene always has a dedicated hw thread
References madness::myusleep().
Referenced by wait().
Member Data Documentation
count
unsigned int madness::MutexWaiter::count private
Referenced by reset(), and wait().
The documentation for this class was generated from the following files:
worldmutex.h
worldmutex.cc