MADNESS: madness::QCPropertyInterface Class Reference
madness::QCPropertyInterface Class Reference abstract
class implementing properties of QC models
#include <QCPropertyInterface.h>
Private Member Functions
virtual real_function_3d density () const
virtual std::vector< double > multipole_moment (const real_function_3d &density, const int l, const Molecule &molecule, const std::shared_ptr< NuclearCorrelationFactor > ncf=0) const
virtual std::string name () const =0
virtual real_function_3d no_cusp_density () const
virtual real_function_3d no_cusp_spindensity (const int spin) const
virtual Tensor< double > nuclear_derivative (const real_function_3d &density, const Molecule &molecule, const std::shared_ptr< NuclearCorrelationFactor > ncf=0) const
virtual bool selftest ()=0
virtual real_function_3d spindensity (const int spin) const
Detailed Description
class implementing properties of QC models
Member Function Documentation
density()
virtual real_function_3d madness::QCPropertyInterface::density () const inline private virtual
References MADNESS_EXCEPTION, name(), and madness::print().
Referenced by madness::Znemo::analyze(), madness::Zcis::canonicalize(), madness::OEP::compute_coulomb_potential(), madness::Znemo::compute_current_density(), madness::OEP::compute_density(), madness::Znemo::compute_energy(), madness::OEP::compute_energy(), madness::Znemo::compute_nemo_density(), madness::Znemo::compute_nemo_spin_density(), madness::Znemo::compute_potentials(), madness::Znemo::iterate(), madness::Zcis::make_guess(), and madness::Nemo::solve().
multipole_moment()
virtual std::vector< double > madness::QCPropertyInterface::multipole_moment (const real_function_3d & density, const int l, const Molecule & molecule, const std::shared_ptr< NuclearCorrelationFactor > ncf = 0) const inline private virtual
References MADNESS_EXCEPTION, name(), and madness::print().
name()
virtual std::string madness::QCPropertyInterface::name () const private pure virtual
Implemented in madness::CC2, madness::MP2, madness::Nemo, madness::PNO, madness::MolecularEnergy, madness::TDHF, madness::Zcis, madness::OEP, and madness::Znemo.
Referenced by density(), multipole_moment(), no_cusp_density(), no_cusp_spindensity(), nuclear_derivative(), and spindensity().
no_cusp_density()
virtual real_function_3d madness::QCPropertyInterface::no_cusp_density () const inline private virtual
References MADNESS_EXCEPTION, name(), and madness::print().
no_cusp_spindensity()
virtual real_function_3d madness::QCPropertyInterface::no_cusp_spindensity (const int spin) const inline private virtual
References MADNESS_ASSERT, MADNESS_EXCEPTION, name(), and madness::print().
nuclear_derivative()
virtual Tensor< double > madness::QCPropertyInterface::nuclear_derivative (const real_function_3d & density, const Molecule & molecule, const std::shared_ptr< NuclearCorrelationFactor > ncf = 0) const inline private virtual
References MADNESS_EXCEPTION, name(), and madness::print().
selftest()
virtual bool madness::QCPropertyInterface::selftest () private pure virtual
Implemented in madness::CC2, madness::MP2, madness::Nemo, madness::PNO, madness::MolecularEnergy, madness::TDHF, madness::Zcis, madness::OEP, and madness::Znemo.
spindensity()
virtual real_function_3d madness::QCPropertyInterface::spindensity (const int spin) const inline private virtual
References MADNESS_ASSERT, MADNESS_EXCEPTION, name(), and madness::print().
Referenced by madness::Znemo::analyze().
The documentation for this class was generated from the following file:
QCPropertyInterface.h