MADNESS: madness::MP3::MacroTaskMP3 Class Reference
madness::MP3::MacroTaskMP3 Class Reference
helper class for calculating the MP3 energy contributions
Classes
class Partitioner
Public Types
typedef std::tuple< const std::string &, const std::vector< int > &, const std::vector< int > &, const std::vector< std::vector< CCPairFunction< double, 6 > > > &, const std::vector< Function< double, 3 > > &, const std::vector< Function< double, 3 > > &, const CCParameters &, const Molecule &, const Function< double, 3 > &, const std::vector< std::string > & > argtupleT
using resultT = ScalarResult< double >
Public Member Functions
MacroTaskMP3 (const std::string shape)
resultT allocator (World &world, const argtupleT &argtuple) const
resultT operator() (const std::string &diagram, const std::vector< int > &ij_vec, const std::vector< int > &j_vec, const std::vector< std::vector< CCPairFunction< double, 6 > > > &pair_square, const std::vector< Function< double, 3 > > &mo_ket, const std::vector< Function< double, 3 > > &mo_bra, const CCParameters &parameters, const Molecule &molecule, const Function< double, 3 > &Rsquare, const std::vector< std::string > &argument) const
Public Member Functions inherited from madness::MacroTaskOperationBase
MacroTaskOperationBase ()
Additional Inherited Members
Public Attributes inherited from madness::MacroTaskOperationBase
Batch batch
std::string name ="unknown_task"
std::shared_ptr< MacroTaskPartitioner > partitioner =0
Detailed Description
helper class for calculating the MP3 energy contributions
Member Typedef Documentation
argtupleT
typedef std::tuple< const std::string&, const std::vector<int>&, const std::vector<int>&, const std::vector<std::vector<CCPairFunction<double,6> > >& , const std::vector<Function<double,3> >&, const std::vector<Function<double,3> >&, const CCParameters&, const Molecule&, const Function<double,3>&, const std::vector<std::string>& > madness::MP3::MacroTaskMP3::argtupleT
resultT
using madness::MP3::MacroTaskMP3::resultT = ScalarResult<double>
Constructor & Destructor Documentation
MacroTaskMP3()
madness::MP3::MacroTaskMP3::MacroTaskMP3 (const std::string shape) inline
References madness::MacroTaskOperationBase::partitioner.
Member Function Documentation
allocator()
resultT madness::MP3::MacroTaskMP3::allocator (World & world, const argtupleT & argtuple) const inline
operator()()
resultT madness::MP3::MacroTaskMP3::operator() (const std::string & diagram, const std::vector< int > & ij_vec, const std::vector< int > & j_vec, const std::vector< std::vector< CCPairFunction< double, 6 > > > & pair_square, const std::vector< Function< double, 3 > > & mo_ket, const std::vector< Function< double, 3 > > & mo_bra, const CCParameters & parameters, const Molecule & molecule, const Function< double, 3 > & Rsquare, const std::vector< std::string > & argument) const inline
References madness::MacroTaskOperationBase::batch, madness::Batch_1D::begin, madness::MP3::compute_mp3_cd(), madness::MP3::compute_mp3_ef(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_klmn(), madness::CCParameters::freeze(), ij(), madness::Batch::input, MADNESS_CHECK, MADNESS_EXCEPTION, madness::PairVectorMap::map, molecule, madness::MacroTaskOperationBase::partitioner, madness::PairVectorMap::quadratic_map(), madness::Batch::result, madness::Batch_1D::size(), madness::PairVectorMap::triangular_map(), and madness::Function< T, NDIM >::world().
The documentation for this class was generated from the following file:
mp3.h