MADNESS: madness::F12Parameters Class Reference
madness::F12Parameters Class Reference
#include <PNOParameters.h>
Public Member Functions
F12Parameters (const PNOParameters &param)
F12Parameters (World &world, const commandlineparser &parser, const PNOParameters &param, const std::string &TAG="pno")
bool abs_c () const
bool abs_u () const
std::map< std::string, std::vector< int > > auxbas () const
std::string auxbas_file () const
double cabs_thresh () const
EnergyType energytype () const
bool f12 () const
double gamma () const
std::string get_tag () const override
void initialize_f12_parameters ()
void set_derived_values ()
Public Member Functions inherited from madness::PNOParameters
PNOParameters ()
PNOParameters (const QCCalculationParametersBase &param)
PNOParameters (World &world, const commandlineparser &parser, const Molecule &molecule, const std::string &TAG="pno")
PNOParameters (World &world, const commandlineparser &parser, const std::string &TAG="pno")
std::vector< int > active_pairs_of_orbital () const
PairType adaptive_solver () const
template<typename T >
T assign_from_string (const std::string &string) const
bool canonicalize_pno () const
int chunk () const
std::vector< std::pair< int, double > > cispd () const
double dconv () const
bool debug () const
bool diagonal () const
double econv () const
double econv_macro () const
double econv_micro () const
double econv_pairs () const
std::string exchange () const
std::string exop () const
bool exop_trigo () const
bool f12 () const
std::size_t freeze () const
std::vector< std::pair< int, int > > freeze_pairs () const
std::vector< int > freeze_pairs_of_orbital () const
std::string get_tag () const override
GuessType guesstype () const
void initialize_pno_parameters ()
bool kain () const
std::size_t kain_subspace () const
int maxiter () const
int maxiter_macro () const
int maxiter_micro () const
int maxiter_t () const
int maxrank () const
PairType no_compute () const
PairType no_guess () const
PairType no_opt () const
bool no_opt_in_first_iteration () const
double op_thresh () const
std::map< std::string, std::vector< int > > partial_wave (const std::string &key="partial_wave") const
std::string predefined_guess () const
std::vector< std::vector< double > > protocol () const
int rank_increase () const
PairType restart () const
bool save_pnos () const
void set_derived_values (const Molecule &molecule)
double thresh () const
double tpno () const
double tpno_tight () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
F12Parameters() [1/2]
madness::F12Parameters::F12Parameters (const PNOParameters & param) inline
References initialize_f12_parameters().
F12Parameters() [2/2]
madness::F12Parameters::F12Parameters (World & world, const commandlineparser & parser, const PNOParameters & param, const std::string & TAG = "pno") inline
References initialize_f12_parameters(), and madness::QCCalculationParametersBase::read_input_and_commandline_options().
Member Function Documentation
abs_c()
bool madness::F12Parameters::abs_c () const inline
Referenced by madness::F12Potentials::compute_f12_correction().
abs_u()
bool madness::F12Parameters::abs_u () const inline
Referenced by madness::F12Potentials::compute_f12_correction().
auxbas()
std::map< std::string, std::vector< int > > madness::F12Parameters::auxbas () const inline
References madness::PNOParameters::partial_wave().
Referenced by madness::F12Potentials::compute_hylleraas_f12_energies().
auxbas_file()
std::string madness::F12Parameters::auxbas_file () const inline
Referenced by madness::F12Potentials::compute_hylleraas_f12_energies(), and madness::F12Potentials::read_cabs_from_file().
cabs_thresh()
double madness::F12Parameters::cabs_thresh () const inline
energytype()
EnergyType madness::F12Parameters::energytype () const inline
References MADNESS_ASSERT, and madness::UNKNOWN_ENERGYTYPE.
Referenced by madness::F12Potentials::compute_f12_energies(), madness::F12Potentials::compute_f12_energies(), madness::PNO::energytype(), set_derived_values(), and madness::PNO::solve_mp2().
f12()
bool madness::F12Parameters::f12 () const inline
gamma()
double madness::F12Parameters::gamma () const inline
Referenced by madness::F12Potentials::F12Potentials(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::F12Potentials::convolve_with_fg(), madness::F12Potentials::convolve_with_fg(), madness::F12Potentials::convolve_with_fU(), madness::F12Potentials::convolve_with_local_U(), and madness::F12Potentials::convolve_with_nonlocal_U().
get_tag()
std::string madness::F12Parameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
initialize_f12_parameters()
void madness::F12Parameters::initialize_f12_parameters () inline
Referenced by F12Parameters(), and F12Parameters().
set_derived_values()
void madness::F12Parameters::set_derived_values () inline
References energytype(), madness::HYLLERAAS_ENERGYTYPE, madness::QCCalculationParametersBase::set_derived_value(), and madness::PNOParameters::thresh().
The documentation for this class was generated from the following file:
PNOParameters.h