MADNESS: madness::guessfactory::ExopUnaryOpStructure Class Reference
madness::guessfactory::ExopUnaryOpStructure Class Reference
#include <GuessFactory.h>
Public Member Functions
ExopUnaryOpStructure (const std::shared_ptr< FunctionFunctorInterface< double, 3 > > &f)
void operator() (const Key< 3 > &key, Tensor< double > &t) const
multiplies the target function by the excitation operator defined by exfunc
void operator() (const Key< 3 > &key, Tensor< double_complex > &t) const
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
FunctionCommonData< double, 3 > cdata
std::shared_ptr< FunctionFunctorInterface< double, 3 > > exfunc
shared pointer to object of excitation operator
Detailed Description
create excitation operators with unaryop (faster as explicit construction and multiplication) Guess function do not need to be perfectly refined
Constructor & Destructor Documentation
ExopUnaryOpStructure()
madness::guessfactory::ExopUnaryOpStructure::ExopUnaryOpStructure (const std::shared_ptr< FunctionFunctorInterface< double, 3 > > & f) inline
Member Function Documentation
operator()() [1/2]
void madness::guessfactory::ExopUnaryOpStructure::operator() (const Key< 3 > & key, Tensor< double > & t) const
multiplies the target function by the excitation operator defined by exfunc
References cdata, madness::BaseTensor::dims(), madness::Tensor< T >::emul(), exfunc, madness::fcube(), madness::BaseTensor::ndim(), and madness::FunctionCommonData< T, NDIM >::quad_x.
operator()() [2/2]
void madness::guessfactory::ExopUnaryOpStructure::operator() (const Key< 3 > & key, Tensor< double_complex > & t) const
References cdata, madness::BaseTensor::dims(), madness::Tensor< T >::emul(), exfunc, madness::fcube(), madness::BaseTensor::ndim(), and madness::FunctionCommonData< T, NDIM >::quad_x.
serialize()
template<typename Archive > void madness::guessfactory::ExopUnaryOpStructure::serialize (Archive & ar) inline
Member Data Documentation
cdata
FunctionCommonData<double,3> madness::guessfactory::ExopUnaryOpStructure::cdata
Referenced by operator()(), and operator()().
exfunc
std::shared_ptr<FunctionFunctorInterface<double,3> > madness::guessfactory::ExopUnaryOpStructure::exfunc
shared pointer to object of excitation operator
Referenced by operator()(), and operator()().
The documentation for this class was generated from the following files:
GuessFactory.h
GuessFactory.cc