MADNESS: madness::WorldProfileObj Class Reference
madness::WorldProfileObj Class Reference
#include <worldprofile.h>
Public Member Functions
WorldProfileObj (int id)
~WorldProfileObj ()
void pause (double now, const RMIStats &stats)
Pause profiling while we are not executing ... accumulate time in self.
void resume (double now, const RMIStats &stats)
Resume profiling.
Private Attributes
const double cpu_base
Time that I started executing.
double cpu_start
Time that I was at top of stack.
const int id
My entry in the world profiler.
WorldProfileObj *const prev
Pointer to the entry that called me.
RMIStats stats_base
Msg stats when I start executing.
RMIStats stats_start
Msg stats when I was at top of stack;.
Static Private Attributes
static thread_local WorldProfileObj * call_stack = 0
Current top of this thread's call stack.
static thread_local int mythreadid = -1
My unique thread id.
Constructor & Destructor Documentation
WorldProfileObj()
madness::WorldProfileObj::WorldProfileObj (int id)
References call_stack, cpu_base, cpu_start, madness::WorldProfileEntry::depth, madness::WorldProfile::get_entry(), MADNESS_ASSERT, mythreadid, pause(), prev, stats_base, stats_start, and madness::threadcounter.
~WorldProfileObj()
madness::WorldProfileObj::~WorldProfileObj ()
References call_stack, cpu_base, cpu_start, madness::cpu_time(), d, madness::WorldProfile::get_entry(), madness::RMI::get_stats(), mythreadid, madness::RMIStats::nbyte_recv, madness::RMIStats::nbyte_sent, madness::RMIStats::nmsg_recv, madness::RMIStats::nmsg_sent, prev, resume(), stats, stats_base, and stats_start.
Member Function Documentation
pause()
void madness::WorldProfileObj::pause (double now, const RMIStats & stats)
Pause profiling while we are not executing ... accumulate time in self.
References cpu_start, d, madness::WorldProfile::get_entry(), madness::RMIStats::nbyte_recv, madness::RMIStats::nbyte_sent, madness::RMIStats::nmsg_recv, madness::RMIStats::nmsg_sent, stats, and stats_start.
Referenced by WorldProfileObj().
resume()
void madness::WorldProfileObj::resume (double now, const RMIStats & stats)
Resume profiling.
References cpu_start, and stats_start.
Referenced by ~WorldProfileObj().
Member Data Documentation
call_stack
thread_local WorldProfileObj * madness::WorldProfileObj::call_stack = 0 static private
Current top of this thread's call stack.
Referenced by WorldProfileObj(), and ~WorldProfileObj().
cpu_base
const double madness::WorldProfileObj::cpu_base private
Time that I started executing.
Referenced by WorldProfileObj(), and ~WorldProfileObj().
cpu_start
double madness::WorldProfileObj::cpu_start private
Time that I was at top of stack.
Referenced by WorldProfileObj(), ~WorldProfileObj(), pause(), and resume().
id
const int madness::WorldProfileObj::id private
My entry in the world profiler.
mythreadid
thread_local int madness::WorldProfileObj::mythreadid = -1 static private
My unique thread id.
Referenced by WorldProfileObj(), and ~WorldProfileObj().
prev
WorldProfileObj* const madness::WorldProfileObj::prev private
Pointer to the entry that called me.
Referenced by WorldProfileObj(), and ~WorldProfileObj().
stats_base
RMIStats madness::WorldProfileObj::stats_base private
Msg stats when I start executing.
Referenced by WorldProfileObj(), and ~WorldProfileObj().
stats_start
RMIStats madness::WorldProfileObj::stats_start private
Msg stats when I was at top of stack;.
Referenced by WorldProfileObj(), ~WorldProfileObj(), pause(), and resume().
The documentation for this class was generated from the following files:
worldprofile.h
worldprofile.cc