MADNESS: madness::RecursiveMutex Class Reference
madness::RecursiveMutex Class Reference
Recursive mutex using pthread mutex operations.
#include <worldmutex.h>
Public Member Functions
RecursiveMutex ()
Make and initialize a mutex ... initial state is unlocked.
~RecursiveMutex ()
void lock () const
Acquire the mutex waiting if necessary.
pthread_mutex_t * ptr () const
Return a pointer to the pthread mutex for use by a condition variable.
bool try_lock () const
Try to acquire the mutex ... return true on success, false on failure.
void unlock () const
Free a mutex owned by this thread.
Private Member Functions
RecursiveMutex (const RecursiveMutex &)
Copy constructor is forbidden.
void operator= (const RecursiveMutex &)
Assignment is forbidden.
Private Attributes
pthread_mutex_t mutex
Detailed Description
Recursive mutex using pthread mutex operations.
Constructor & Destructor Documentation
RecursiveMutex() [1/2]
madness::RecursiveMutex::RecursiveMutex (const RecursiveMutex &) private
Copy constructor is forbidden.
RecursiveMutex() [2/2]
madness::RecursiveMutex::RecursiveMutex ()
Make and initialize a mutex ... initial state is unlocked.
References MADNESS_EXCEPTION, and mutex.
~RecursiveMutex()
madness::RecursiveMutex::~RecursiveMutex () inline
References mutex.
Member Function Documentation
lock()
void madness::RecursiveMutex::lock () const inline
Acquire the mutex waiting if necessary.
References MADNESS_EXCEPTION, mutex, and madness::detail::print_mutex_error().
Referenced by madness::detail::DeferredCleanup::destroy(), madness::detail::DeferredCleanup::destroy(), and madness::detail::DeferredCleanup::do_cleanup().
operator=()
void madness::RecursiveMutex::operator= (const RecursiveMutex &) private
Assignment is forbidden.
ptr()
pthread_mutex_t * madness::RecursiveMutex::ptr () const inline
Return a pointer to the pthread mutex for use by a condition variable.
References mutex.
try_lock()
bool madness::RecursiveMutex::try_lock () const inline
Try to acquire the mutex ... return true on success, false on failure.
References mutex.
unlock()
void madness::RecursiveMutex::unlock () const inline
Free a mutex owned by this thread.
References MADNESS_EXCEPTION, mutex, and madness::detail::print_mutex_error().
Referenced by madness::detail::DeferredCleanup::destroy(), madness::detail::DeferredCleanup::destroy(), and madness::detail::DeferredCleanup::do_cleanup().
Member Data Documentation
mutex
pthread_mutex_t madness::RecursiveMutex::mutex mutable private
Referenced by RecursiveMutex(), ~RecursiveMutex(), lock(), ptr(), try_lock(), and unlock().
The documentation for this class was generated from the following files:
worldmutex.h
worldmutex.cc