MADNESS: madness::ProjectorBase Class Reference
madness::ProjectorBase Class Reference abstract
#include <projector.h>
Public Member Functions
virtual ~ProjectorBase ()
virtual int get_particle () const
virtual void set_particle (const int p)
virtual std::string type () const =0
Protected Attributes
int particle =-1
a projector might work only on a subset of dimensions, e.g. P(1) | \psi(1,2) >
Constructor & Destructor Documentation
~ProjectorBase()
virtual madness::ProjectorBase::~ProjectorBase () inline virtual
Member Function Documentation
get_particle()
virtual int madness::ProjectorBase::get_particle () const inline virtual
Reimplemented in madness::QProjector< T, NDIM >, madness::QProjector< double, 3 >, and madness::QProjector< double_complex, 3 >.
References particle.
Referenced by madness::Projector< T, NDIM >::operator()().
set_particle()
virtual void madness::ProjectorBase::set_particle (const int p) inline virtual
Reimplemented in madness::QProjector< T, NDIM >, madness::QProjector< double, 3 >, madness::QProjector< double_complex, 3 >, madness::StrongOrthogonalityProjector< T, NDIM >, and madness::StrongOrthogonalityProjector< double, 3 >.
References MADNESS_CHECK_THROW, and p().
Referenced by madness::CCPairFunction< T, NDIM >::apply(), test_projector(), and test_Q12_projector().
type()
virtual std::string madness::ProjectorBase::type () const pure virtual
Implemented in madness::Projector< T, NDIM >, madness::Projector< double, NDIM >, madness::Projector< double_complex, NDIM >, madness::QProjector< T, NDIM >, madness::QProjector< double, 3 >, madness::QProjector< double_complex, 3 >, madness::StrongOrthogonalityProjector< T, NDIM >, madness::StrongOrthogonalityProjector< double, 3 >, and madness::OuterProjector< projT, projQ >.
Member Data Documentation
particle
int madness::ProjectorBase::particle =-1 protected
a projector might work only on a subset of dimensions, e.g. P(1) | \psi(1,2) >
Referenced by get_particle().
The documentation for this class was generated from the following file:
projector.h