MADNESS: madness::FunctionSpace< T, NDIM > Class Template Reference
madness::FunctionSpace< T, NDIM > Class Template Reference
A vector space using MADNESS Functions.
#include <gmres.h>
Public Types
typedef TensorTypeData< T >::float_scalar_type real_type
typedef T scalar_type
Public Member Functions
FunctionSpace (World &world)
virtual ~FunctionSpace ()
virtual void destroy (Function< scalar_type, NDIM > &f) const
Any special instructions to be executed when a vector is no longer needed.
virtual Function< scalar_type, NDIM > & gaxpy (Function< scalar_type, NDIM > &x, const scalar_type &a, const Function< scalar_type, NDIM > &y, const scalar_type &b) const
Standard bilinear gaxpy.
virtual scalar_type inner (const Function< scalar_type, NDIM > &l, const Function< scalar_type, NDIM > &r) const
The inner product between two vectors.
virtual real_type norm (const Function< scalar_type, NDIM > &vec) const
The norm of a vector.
virtual Function< scalar_type, NDIM > & scale (Function< scalar_type, NDIM > &vec, const scalar_type &c) const
Scales the vector (in-place) by a constant.
Public Member Functions inherited from madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >
AbstractVectorSpace (World &world)
Make a vector space.
virtual ~AbstractVectorSpace ()
Additional Inherited Members
Public Attributes inherited from madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >
World & world
The world.
Detailed Description
template<typename T, int NDIM>
class madness::FunctionSpace< T, NDIM >
A vector space using MADNESS Functions.
Member Typedef Documentation
real_type
template<typename T , int NDIM> typedef TensorTypeData<T>::float_scalar_type madness::FunctionSpace< T, NDIM >::real_type
scalar_type
template<typename T , int NDIM> typedef T madness::FunctionSpace< T, NDIM >::scalar_type
Constructor & Destructor Documentation
FunctionSpace()
template<typename T , int NDIM> madness::FunctionSpace< T, NDIM >::FunctionSpace (World & world) inline
~FunctionSpace()
template<typename T , int NDIM> virtual madness::FunctionSpace< T, NDIM >::~FunctionSpace () inline virtual
Member Function Documentation
destroy()
template<typename T , int NDIM> virtual void madness::FunctionSpace< T, NDIM >::destroy (Function< scalar_type, NDIM > &) const inline virtual
Any special instructions to be executed when a vector is no longer needed.
Unless otherwise specified, do nothing.
Reimplemented from madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >.
References madness::f.
gaxpy()
template<typename T , int NDIM> virtual Function< scalar_type, NDIM > & madness::FunctionSpace< T, NDIM >::gaxpy (Function< scalar_type, NDIM > & x, const scalar_type & a, const Function< scalar_type, NDIM > & y, const scalar_type & b) const inline virtual
Standard bilinear gaxpy.
Returns
The new vector,
Implements madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >.
References a, b, and madness::Function< T, NDIM >::gaxpy().
inner()
template<typename T , int NDIM> virtual scalar_type madness::FunctionSpace< T, NDIM >::inner (const Function< scalar_type, NDIM > & , const Function< scalar_type, NDIM > &) const inline virtual
The inner product between two vectors.
Implements madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >.
norm()
template<typename T , int NDIM> virtual real_type madness::FunctionSpace< T, NDIM >::norm (const Function< scalar_type, NDIM > &) const inline virtual
The norm of a vector.
Implements madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >.
References madness::vec().
Referenced by cplxfunc0(), cplxfunc1(), cplxfunc2(), realfunc0(), realfunc1(), and realfunc2().
scale()
template<typename T , int NDIM> virtual Function< scalar_type, NDIM > & madness::FunctionSpace< T, NDIM >::scale (Function< scalar_type, NDIM > & , const scalar_type &) const inline virtual
Scales the vector (in-place) by a constant.
Returns
The scaled vector
Implements madness::AbstractVectorSpace< Function< T, NDIM >, TensorTypeData< T >::float_scalar_type, T >.
References c, and madness::vec().
The documentation for this class was generated from the following file:
gmres.h