MADNESS: madness::profiling::TaskEventListBase Class Reference
madness::profiling::TaskEventListBase Class Reference abstract
Task event list base class.
#include <thread.h>
Public Member Functions
TaskEventListBase ()
Default constructor.
virtual ~TaskEventListBase ()=default
Virtual destructor.
void insert (TaskEventListBase *list)
Insert list after this list.
TaskEventListBase * next () const
Get the next event list in the linked list.
Private Member Functions
TaskEventListBase (const TaskEventListBase &)=delete
TaskEventListBase & operator= (const TaskEventListBase &)=delete
virtual std::ostream & print_events (std::ostream &) const =0
Print the events.
Private Attributes
TaskEventListBase * next_
The next task event in the list.
Friends
std::ostream & operator<< (std::ostream &os, const TaskEventListBase &tel)
Output a task event list to an output stream.
Detailed Description
Task event list base class.
This base class allows the data to be stored in a linked list.
Constructor & Destructor Documentation
TaskEventListBase() [1/2]
madness::profiling::TaskEventListBase::TaskEventListBase (const TaskEventListBase &) private delete
TaskEventListBase() [2/2]
madness::profiling::TaskEventListBase::TaskEventListBase () inline
Default constructor.
~TaskEventListBase()
virtual madness::profiling::TaskEventListBase::~TaskEventListBase () virtual default
Virtual destructor.
Member Function Documentation
insert()
void madness::profiling::TaskEventListBase::insert (TaskEventListBase * list) inline
Insert list after this list.
Parameters
[in] list The list to be inserted.
References next_.
Referenced by madness::profiling::TaskProfiler::new_list().
next()
TaskEventListBase * madness::profiling::TaskEventListBase::next () const inline
Get the next event list in the linked list.
Returns
The next event list.
References next_.
Referenced by madness::profiling::TaskProfiler::~TaskProfiler(), and madness::profiling::TaskProfiler::write_to_file().
operator=()
TaskEventListBase & madness::profiling::TaskEventListBase::operator= (const TaskEventListBase &) private delete
print_events()
virtual std::ostream & madness::profiling::TaskEventListBase::print_events (std::ostream &) const private pure virtual
Print the events.
Implemented in madness::profiling::TaskEventList.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const TaskEventListBase & tel) friend
Output a task event list to an output stream.
Parameters
[in,out] os The ouptut stream.
[in] tel The task event list to be output.
Returns
The modified output stream.
Member Data Documentation
next_
TaskEventListBase* madness::profiling::TaskEventListBase::next_ private
The next task event in the list.
Referenced by insert(), and next().
The documentation for this class was generated from the following file:
thread.h