MADNESS: madchem::AtomicAttractionFunctor Class Reference
madchem::AtomicAttractionFunctor Class Reference
#include <molecular_functors.h>
Public Member Functions
AtomicAttractionFunctor (const madness::Molecule &molecule, int iatom)
double operator() (const madness::coord_3d &x) const
std::vector< madness::coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level () const
Override this to change the minimum level of refinement at special points (default is 6)
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const int iatom
const madness::Molecule & molecule
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
AtomicAttractionFunctor()
madchem::AtomicAttractionFunctor::AtomicAttractionFunctor (const madness::Molecule & molecule, int iatom) inline
Member Function Documentation
operator()()
double madchem::AtomicAttractionFunctor::operator() (const madness::coord_3d & x) const inline
References madness::Molecule::get_atom(), madness::Molecule::get_rcut(), iatom, molecule, madness::Atom::q, madness::smoothed_potential(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
special_points()
std::vector< madness::coord_3d > madchem::AtomicAttractionFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References madness::Molecule::get_atom(), madness::Atom::get_coords(), iatom, and molecule.
Member Data Documentation
iatom
const int madchem::AtomicAttractionFunctor::iatom private
Referenced by operator()(), and special_points().
molecule
const madness::Molecule& madchem::AtomicAttractionFunctor::molecule private
Referenced by operator()(), and special_points().
The documentation for this class was generated from the following file:
molecular_functors.h