MADNESS: madness::DerivativeBase< T, NDIM > Class Template Reference
madness::DerivativeBase< T, NDIM > Class Template Reference abstract
Mra
Tri-diagonal operator traversing tree primarily for derivative operator.
#include <derivative.h>
Public Types
typedef std::pair< keyT, coeffT > argT
typedef GenTensor< T > coeffT
holding the node's coeffs (possibly low rank)
typedef WorldContainer< Key< NDIM >, FunctionNode< T, NDIM > > dcT
typedef Function< T, NDIM > functionT
typedef FunctionImpl< T, NDIM > implT
typedef Key< NDIM > keyT
typedef FunctionNode< T, NDIM > nodeT
typedef Tensor< T > tensorT
regular tensors, like rm, etc
Public Types inherited from madness::WorldObject< DerivativeBase< T, NDIM > >
typedef WorldObject< DerivativeBase< T, NDIM > > objT
Public Member Functions
DerivativeBase (World &world, std::size_t axis, int k, BoundaryConditions< NDIM > bc)
virtual ~DerivativeBase ()
void do_diff1 (const implT *f, implT *df, const keyT &key, const argT &left, const argT &center, const argT &right) const
virtual void do_diff2b (const implT *f, implT *df, const keyT &key, const argT &left, const argT &center, const argT &right) const =0
virtual void do_diff2i (const implT *f, implT *df, const keyT &key, const argT &left, const argT &center, const argT &right) const =0
Future< argT > find_neighbor (const implT *f, const Key< NDIM > &key, int step) const
void forward_do_diff1 (const implT *f, implT *df, const keyT &key, const argT &left, const argT &center, const argT &right) const
Key< NDIM > neighbor (const keyT &key, int step) const
Function< T, NDIM > operator() (const functionT &f, bool fence=true) const
Differentiate w.r.t. given coordinate (x=0, y=1, ...) with optional fence.
template<typename Archive >
void serialize (const Archive &ar) const
Public Member Functions inherited from madness::WorldObject< DerivativeBase< T, NDIM > >
WorldObject (const WorldObject &other)
WorldObject (World &world)
Constructor that associates an object (via the derived class) with a globally unique ID.
virtual ~WorldObject ()
World & get_world () const
Returns a reference to the world.
const uniqueidT & id () const
Returns the globally unique object ID.
WorldObject & operator= (const WorldObject &)=delete
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9) const
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8,a9).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)().
Public Member Functions inherited from madness::WorldObjectBase
virtual ~WorldObjectBase ()=default
Static Public Member Functions
static bool enforce_bc (int bc_left, int bc_right, Level n, Translation &l)
Protected Attributes
const std::size_t axis
Axis along which the operation is performed.
const BoundaryConditions< NDIM > bc
const int k
Number of wavelets of the function.
const std::vector< long > vk
(k,...) used to initialize Tensors
World & world
Private Types
typedef WorldObject< DerivativeBase< T, NDIM > > woT
Friends
class FunctionImpl< T, NDIM >
Additional Inherited Members
Protected Member Functions inherited from madness::WorldObject< DerivativeBase< T, NDIM > >
void process_pending ()
To be called from derived constructor to process pending messages.
Detailed Description
template<typename T, std::size_t NDIM>
class madness::DerivativeBase< T, NDIM >
Tri-diagonal operator traversing tree primarily for derivative operator.
Member Typedef Documentation
argT
template<typename T , std::size_t NDIM> typedef std::pair<keyT,coeffT> madness::DerivativeBase< T, NDIM >::argT
coeffT
template<typename T , std::size_t NDIM> typedef GenTensor<T> madness::DerivativeBase< T, NDIM >::coeffT
holding the node's coeffs (possibly low rank)
dcT
template<typename T , std::size_t NDIM> typedef WorldContainer<Key<NDIM> , FunctionNode<T, NDIM> > madness::DerivativeBase< T, NDIM >::dcT
functionT
template<typename T , std::size_t NDIM> typedef Function<T,NDIM> madness::DerivativeBase< T, NDIM >::functionT
implT
template<typename T , std::size_t NDIM> typedef FunctionImpl<T,NDIM> madness::DerivativeBase< T, NDIM >::implT
keyT
template<typename T , std::size_t NDIM> typedef Key<NDIM> madness::DerivativeBase< T, NDIM >::keyT
nodeT
template<typename T , std::size_t NDIM> typedef FunctionNode<T,NDIM> madness::DerivativeBase< T, NDIM >::nodeT
tensorT
template<typename T , std::size_t NDIM> typedef Tensor<T> madness::DerivativeBase< T, NDIM >::tensorT
regular tensors, like rm, etc
woT
template<typename T , std::size_t NDIM> typedef WorldObject< DerivativeBase<T, NDIM> > madness::DerivativeBase< T, NDIM >::woT private
Constructor & Destructor Documentation
DerivativeBase()
template<typename T , std::size_t NDIM> madness::DerivativeBase< T, NDIM >::DerivativeBase (World & world, std::size_t axis, int k, BoundaryConditions< NDIM > bc) inline
~DerivativeBase()
template<typename T , std::size_t NDIM> virtual madness::DerivativeBase< T, NDIM >::~DerivativeBase () inline virtual
Member Function Documentation
do_diff1()
template<typename T , std::size_t NDIM> void madness::DerivativeBase< T, NDIM >::do_diff1 (const implT * f, implT * df, const keyT & key, const argT & left, const argT & center, const argT & right) const inline
References madness::DerivativeBase< T, NDIM >::axis, madness::f, madness::DerivativeBase< T, NDIM >::forward_do_diff1(), madness::FunctionImpl< T, NDIM >::get_coeffs(), MADNESS_ASSERT, NDIM, madness::WorldContainer< keyT, valueT, hashfunT >::replace(), and madness::Key< NDIM >::translation().
do_diff2b()
template<typename T , std::size_t NDIM> virtual void madness::DerivativeBase< T, NDIM >::do_diff2b (const implT * f, implT * df, const keyT & key, const argT & left, const argT & center, const argT & right) const pure virtual
Implemented in madness::Derivative< T, NDIM >.
do_diff2i()
template<typename T , std::size_t NDIM> virtual void madness::DerivativeBase< T, NDIM >::do_diff2i (const implT * f, implT * df, const keyT & key, const argT & left, const argT & center, const argT & right) const pure virtual
Implemented in madness::Derivative< T, NDIM >.
enforce_bc()
template<typename T , std::size_t NDIM> static bool madness::DerivativeBase< T, NDIM >::enforce_bc (int bc_left, int bc_right, Level n, Translation & l) inline static
References madness::BC_DIRICHLET, madness::BC_FREE, madness::BC_NEUMANN, madness::BC_PERIODIC, madness::BC_ZERO, madness::BC_ZERONEUMANN, MADNESS_ASSERT, and MADNESS_EXCEPTION.
Referenced by madness::DerivativeBase< T, NDIM >::neighbor().
find_neighbor()
template<typename T , std::size_t NDIM> Future< argT > madness::DerivativeBase< T, NDIM >::find_neighbor (const implT * f, const Key< NDIM > & key, int step) const inline
References madness::f, madness::TaskAttributes::hipri(), madness::Key< NDIM >::is_invalid(), madness::DerivativeBase< T, NDIM >::neighbor(), madness::Future< T >::remote_ref(), madness::FunctionImpl< T, NDIM >::sock_it_to_me(), madness::DerivativeBase< T, NDIM >::vk, and madness::DerivativeBase< T, NDIM >::world.
Referenced by madness::DerivativeBase< T, NDIM >::forward_do_diff1().
forward_do_diff1()
template<typename T , std::size_t NDIM> void madness::DerivativeBase< T, NDIM >::forward_do_diff1 (const implT * f, implT * df, const keyT & key, const argT & left, const argT & center, const argT & right) const inline
References madness::f, madness::DerivativeBase< T, NDIM >::find_neighbor(), madness::TaskAttributes::hipri(), madness::World::rank(), madness::WorldObject< Derived >::task(), madness::WorldObject< DerivativeBase< T, NDIM > >::task(), and madness::DerivativeBase< T, NDIM >::world.
Referenced by madness::DerivativeBase< T, NDIM >::do_diff1().
neighbor()
template<typename T , std::size_t NDIM> Key< NDIM > madness::DerivativeBase< T, NDIM >::neighbor (const keyT & key, int step) const inline
References madness::DerivativeBase< T, NDIM >::axis, madness::DerivativeBase< T, NDIM >::bc, madness::DerivativeBase< T, NDIM >::enforce_bc(), madness::Key< NDIM >::invalid(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::translation().
Referenced by madness::DerivativeBase< T, NDIM >::find_neighbor().
operator()()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::DerivativeBase< T, NDIM >::operator() (const functionT & f, bool fence = true) const inline
Differentiate w.r.t. given coordinate (x=0, y=1, ...) with optional fence.
Returns a new function with the same distribution
References madness::f, MADNESS_CHECK_THROW, madness::reconstructed, and VERIFY_TREE.
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::DerivativeBase< T, NDIM >::serialize (const Archive & ar) const inline
Friends And Related Symbol Documentation
FunctionImpl< T, NDIM >
template<typename T , std::size_t NDIM> friend class FunctionImpl< T, NDIM > friend
Member Data Documentation
axis
template<typename T , std::size_t NDIM> const std::size_t madness::DerivativeBase< T, NDIM >::axis protected
Axis along which the operation is performed.
Referenced by madness::Derivative< T, NDIM >::Derivative(), madness::DerivativeBase< T, NDIM >::do_diff1(), madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::do_diff2i(), madness::Derivative< T, NDIM >::initCoefficients(), and madness::DerivativeBase< T, NDIM >::neighbor().
bc
template<typename T , std::size_t NDIM> const BoundaryConditions<NDIM> madness::DerivativeBase< T, NDIM >::bc protected
Referenced by madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::initCoefficients(), and madness::DerivativeBase< T, NDIM >::neighbor().
k
template<typename T , std::size_t NDIM> const int madness::DerivativeBase< T, NDIM >::k protected
Number of wavelets of the function.
Referenced by madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::initCoefficients(), madness::Derivative< T, NDIM >::read_from_file(), madness::Derivative< T, NDIM >::set_ble1(), madness::Derivative< T, NDIM >::set_ble2(), madness::Derivative< T, NDIM >::set_bspline1(), madness::Derivative< T, NDIM >::set_bspline2(), and madness::Derivative< T, NDIM >::set_bspline3().
vk
template<typename T , std::size_t NDIM> const std::vector<long> madness::DerivativeBase< T, NDIM >::vk protected
(k,...) used to initialize Tensors
Referenced by madness::DerivativeBase< T, NDIM >::find_neighbor().
world
template<typename T , std::size_t NDIM> World& madness::DerivativeBase< T, NDIM >::world protected
Referenced by madness::DerivativeBase< T, NDIM >::find_neighbor(), and madness::DerivativeBase< T, NDIM >::forward_do_diff1().
The documentation for this class was generated from the following file:
derivative.h