MADNESS: madness::FunctionCommonFunctionality< T, NDIM > Class Template Reference
madness::FunctionCommonFunctionality< T, NDIM > Class Template Reference
collect common functionality does not need to be member function of funcimpl
#include <function_common_data.h>
Public Member Functions
FunctionCommonFunctionality (const FunctionCommonData< T, NDIM > &cdata)
FunctionCommonFunctionality (const long k)
GenTensor< T > coeffs2values (const Key< NDIM > &key, const GenTensor< T > &coeff) const
Tensor< T > coeffs2values (const Key< NDIM > &key, const Tensor< T > &coeff) const
GenTensor< T > values2coeffs (const Key< NDIM > &key, const GenTensor< T > &values) const
Tensor< T > values2coeffs (const Key< NDIM > &key, const Tensor< T > &values) const
Public Attributes
const FunctionCommonData< T, NDIM > & cdata
Detailed Description
template<typename T, std::size_t NDIM>
class madness::FunctionCommonFunctionality< T, NDIM >
collect common functionality does not need to be member function of funcimpl
Constructor & Destructor Documentation
FunctionCommonFunctionality() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionCommonFunctionality< T, NDIM >::FunctionCommonFunctionality (const FunctionCommonData< T, NDIM > & cdata) inline
FunctionCommonFunctionality() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionCommonFunctionality< T, NDIM >::FunctionCommonFunctionality (const long k) inline
Member Function Documentation
coeffs2values() [1/2]
template<typename T , std::size_t NDIM> GenTensor< T > madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values (const Key< NDIM > & key, const GenTensor< T > & coeff) const inline
References madness::FunctionCommonFunctionality< T, NDIM >::cdata, madness::Key< NDIM >::level(), NDIM, pow(), madness::scale(), and madness::transform().
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()().
coeffs2values() [2/2]
template<typename T , std::size_t NDIM> Tensor< T > madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values (const Key< NDIM > & key, const Tensor< T > & coeff) const inline
References madness::FunctionCommonFunctionality< T, NDIM >::cdata, madness::Key< NDIM >::level(), NDIM, pow(), madness::scale(), and madness::transform().
values2coeffs() [1/2]
template<typename T , std::size_t NDIM> GenTensor< T > madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs (const Key< NDIM > & key, const GenTensor< T > & values) const inline
References madness::FunctionCommonFunctionality< T, NDIM >::cdata, madness::Key< NDIM >::level(), NDIM, pow(), madness::scale(), and madness::transform().
values2coeffs() [2/2]
template<typename T , std::size_t NDIM> Tensor< T > madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs (const Key< NDIM > & key, const Tensor< T > & values) const inline
Return the scaling function coeffs when given the function values at the quadrature points
Parameters
[in] key the key of the function node (box)
Returns
function values for function node (box)
References madness::FunctionCommonFunctionality< T, NDIM >::cdata, madness::Key< NDIM >::level(), NDIM, pow(), madness::scale(), and madness::transform().
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()().
Member Data Documentation
cdata
template<typename T , std::size_t NDIM> const FunctionCommonData<T,NDIM>& madness::FunctionCommonFunctionality< T, NDIM >::cdata
Referenced by madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs(), and madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs().
The documentation for this class was generated from the following file:
function_common_data.h