MADNESS: madness::TaskThreadEnv Class Reference
madness::TaskThreadEnv Class Reference
MADNESS libraries » Parallel programming environment » Multi-threading » Threads
Used to pass information about the thread environment to a user's task.
#include <thread.h>
Public Member Functions
TaskThreadEnv (int nthread, int id)
Constructor collecting necessary environmental information.
TaskThreadEnv (int nthread, int id, Barrier *barrier)
Constructor collecting necessary environmental information.
bool barrier () const
int id () const
Get the ID of this thread.
int nthread () const
Get the number of threads collaborating on this task.
Private Attributes
Barrier * _barrier
Pointer to the shared barrier, null if there is only a single thread.
const int _id
ID of this thread (0,...,nthread-1).
const int _nthread
Number of threads collaborating on task.
Detailed Description
Used to pass information about the thread environment to a user's task.
Constructor & Destructor Documentation
TaskThreadEnv() [1/2]
madness::TaskThreadEnv::TaskThreadEnv (int nthread, int id, Barrier * barrier) inline
Constructor collecting necessary environmental information.
Todo:
Verify this documentation.
Parameters
[in] nthread The number of threads collaborating on this task.
[in] id The ID of this thread.
[in] barrier Pointer to the shared barrier.
References madness::ThreadBinder::bind(), and madness::binder.
TaskThreadEnv() [2/2]
madness::TaskThreadEnv::TaskThreadEnv (int nthread, int id) inline
Constructor collecting necessary environmental information.
Todo:
Verify this documentation.
Parameters
[in] nthread The number of threads collaborating on this task.
[in] id The ID of this thread.
Todo:
I cannot get the TaskThreadEnv to work with Barrier. Need to figure out why.
References madness::ThreadBinder::bind(), and madness::binder.
Member Function Documentation
barrier()
bool madness::TaskThreadEnv::barrier () const inline
Todo:
Brief description needed.
Todo:
Descriptions needed.
Returns
Description needed.
References _barrier, _id, _nthread, madness::Barrier::enter(), and MADNESS_ASSERT.
Referenced by TestBarrier::run(), and TimeBarrier::run().
id()
int madness::TaskThreadEnv::id () const inline
Get the ID of this thread.
Returns
The ID of this thread.
References _id.
Referenced by TestSystolicMatrixAlgorithm< T >::converged(), madness::SystolicFixOrbitalOrders::end_iteration_hook(), madness::SystolicPMOrbitalLocalize::end_iteration_hook(), TestBarrier::run(), madness::SystolicFixOrbitalOrders::start_iteration_hook(), madness::SystolicPMOrbitalLocalize::start_iteration_hook(), and TestSystolicMatrixAlgorithm< T >::start_iteration_hook().
nthread()
int madness::TaskThreadEnv::nthread () const inline
Get the number of threads collaborating on this task.
Returns
The number of threads.
References _nthread.
Referenced by madness::SystolicMatrixAlgorithm< T >::run(), madness::TaskInterface::run(), and TestBarrier::run().
Member Data Documentation
_barrier
Barrier* madness::TaskThreadEnv::_barrier private
Pointer to the shared barrier, null if there is only a single thread.
Referenced by barrier().
_id
const int madness::TaskThreadEnv::_id private
ID of this thread (0,...,nthread-1).
Referenced by barrier(), and id().
_nthread
const int madness::TaskThreadEnv::_nthread private
Number of threads collaborating on task.
Referenced by barrier(), and nthread().
The documentation for this class was generated from the following file:
thread.h