MADNESS: MolecularPotentialFunctor Class Reference
MolecularPotentialFunctor Class Reference
#include <electronicstructureapp.h>
Public Member Functions
MolecularPotentialFunctor (const MolecularEntity &mentity)
MolecularPotentialFunctor (const Molecule &molecule)
double operator() (const coord_3d &x) const
double operator() (const coordT &x) const
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level () const
Override this to change the minimum level of refinement at special points (default is 6)
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const MolecularEntity & _mentity
const Molecule & molecule
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
MolecularPotentialFunctor() [1/2]
MolecularPotentialFunctor::MolecularPotentialFunctor (const Molecule & molecule) inline
MolecularPotentialFunctor() [2/2]
MolecularPotentialFunctor::MolecularPotentialFunctor (const MolecularEntity & mentity) inline
Member Function Documentation
operator()() [1/2]
double MolecularPotentialFunctor::operator() (const coord_3d & x) const inline
References molecule, and madness::Molecule::nuclear_attraction_potential().
operator()() [2/2]
double MolecularPotentialFunctor::operator() (const coordT & x) const inline
References _mentity, and MolecularEntity::nuclear_attraction_potential().
special_points()
std::vector< coord_3d > MolecularPotentialFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References madness::Molecule::get_all_coords_vec(), and molecule.
Member Data Documentation
_mentity
const MolecularEntity& MolecularPotentialFunctor::_mentity private
Referenced by operator()().
molecule
const Molecule& MolecularPotentialFunctor::molecule private
Referenced by operator()(), and special_points().
The documentation for this class was generated from the following files:
preal.cc
electronicstructureapp.h