MADNESS: EwaldNuclearPotentialFunctor Class Reference
EwaldNuclearPotentialFunctor Class Reference
Public Member Functions
EwaldNuclearPotentialFunctor (World &world, MolecularEntity *mentity, double alpha)
virtual ~EwaldNuclearPotentialFunctor ()
double_complex do_G_sum_v1 (const coordT &r) const
double_complex do_G_sum_v2 (const coordT &r) const
double_complex do_R_sum_v1 (const coordT &r) const
double operator() (const coordT &r) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level () const
Override this to change the minimum level of refinement at special points (default is 6)
virtual std::vector< Vector< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
double alpha
std::vector< double_complex > gsfactor
std::vector< Vector< double, 3 > > gvecs
MolecularEntity * mentity
std::vector< Vector< double, 3 > > rvecs
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
EwaldNuclearPotentialFunctor()
EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor (World & world, MolecularEntity * mentity, double alpha) inline
References std::abs(), alpha, e(), G2, generate_G_vectors(), generate_R_vectors(), MolecularEntity::get_atom(), gsfactor, gvecs, L, mentity, MolecularEntity::natom(), madness::constants::pi, madness::print(), madness::Atom::q, madness::World::rank(), rvecs, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
~EwaldNuclearPotentialFunctor()
virtual EwaldNuclearPotentialFunctor::~EwaldNuclearPotentialFunctor () inline virtual
Member Function Documentation
do_G_sum_v1()
double_complex EwaldNuclearPotentialFunctor::do_G_sum_v1 (const coordT & r) const inline
References alpha, compute_volume(), gsfactor, gvecs, mentity, MolecularEntity::natom(), madness::constants::pi, MolecularEntity::total_nuclear_charge(), and v.
Referenced by operator()().
do_G_sum_v2()
double_complex EwaldNuclearPotentialFunctor::do_G_sum_v2 (const coordT & r) const inline
References alpha, compute_volume(), e(), G2, MolecularEntity::get_atom(), gvecs, MADNESS_ASSERT, mentity, MolecularEntity::natom(), madness::constants::pi, madness::Atom::q, MolecularEntity::total_nuclear_charge(), v, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
do_R_sum_v1()
double_complex EwaldNuclearPotentialFunctor::do_R_sum_v1 (const coordT & r) const inline
References alpha, compute_volume(), MolecularEntity::get_atom(), mentity, MolecularEntity::natom(), madness::constants::pi, madness::Atom::q, rvecs, v, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by operator()().
operator()()
double EwaldNuclearPotentialFunctor::operator() (const coordT & r) const inline
References do_G_sum_v1(), and do_R_sum_v1().
Member Data Documentation
alpha
double EwaldNuclearPotentialFunctor::alpha private
Referenced by EwaldNuclearPotentialFunctor(), do_G_sum_v1(), do_G_sum_v2(), and do_R_sum_v1().
gsfactor
std::vector<double_complex> EwaldNuclearPotentialFunctor::gsfactor private
Referenced by EwaldNuclearPotentialFunctor(), and do_G_sum_v1().
gvecs
std::vector< Vector<double,3> > EwaldNuclearPotentialFunctor::gvecs private
Referenced by EwaldNuclearPotentialFunctor(), do_G_sum_v1(), and do_G_sum_v2().
mentity
MolecularEntity* EwaldNuclearPotentialFunctor::mentity private
Referenced by EwaldNuclearPotentialFunctor(), do_G_sum_v1(), do_G_sum_v2(), and do_R_sum_v1().
rvecs
std::vector< Vector<double,3> > EwaldNuclearPotentialFunctor::rvecs private
Referenced by EwaldNuclearPotentialFunctor(), and do_R_sum_v1().
The documentation for this class was generated from the following file:
ewald.cc