MADNESS: madness::Gnuplot Class Reference
madness::Gnuplot Class Reference
#include <gnuplot.h>
Public Member Functions
Gnuplot (const Gnuplot &)=delete
Gnuplot (const std::string &cmd="", const std::string &teefile="")
~Gnuplot ()
template<typename T , typename... Ts>
void db (const std::string &name, const T &x, Ts... values)
template<typename T , typename... Ts>
void db (const std::string &name, size_t size, const T &x, Ts... values)
void operator() (const char *cmd, bool EOL=true)
void operator() (const std::string &cmd, bool EOL=true)
Gnuplot & operator= (const Gnuplot &)=delete
Gnuplot & operator= (Gnuplot &&)=delete
template<typename T , typename... Ts>
void plot (const T &x, Ts... values)
Static Public Member Functions
static void test ()
Private Member Functions
template<typename T >
void dbvalue (size_t i, const T &t)
template<typename T , typename... Ts>
void dbvalue (size_t i, const T &t, Ts... values)
template<int n, typename T >
void doplot (const char *name, const T &value0)
template<int n, typename T , typename... Ts>
void doplot (const char *name, const T &value0, Ts... values)
Private Attributes
FILE * f
FILE * ftee
pid_t pid
Constructor & Destructor Documentation
Gnuplot() [1/2]
madness::Gnuplot::Gnuplot (const Gnuplot &) delete
Gnuplot() [2/2]
madness::Gnuplot::Gnuplot (const std::string & cmd = "", const std::string & teefile = "") inline
References f, ftee, p(), and pid.
~Gnuplot()
madness::Gnuplot::~Gnuplot () inline
References f, ftee, and pid.
Member Function Documentation
db() [1/2]
template<typename T , typename... Ts> void madness::Gnuplot::db (const std::string & name, const T & x, Ts... values) inline
References db(), and madness::name().
db() [2/2]
template<typename T , typename... Ts> void madness::Gnuplot::db (const std::string & name, size_t size, const T & x, Ts... values) inline
References dbvalue(), and madness::name().
Referenced by db(), plot(), and test().
dbvalue() [1/2]
template<typename T > void madness::Gnuplot::dbvalue (size_t i, const T & t) inline private
Referenced by db(), and dbvalue().
dbvalue() [2/2]
template<typename T , typename... Ts> void madness::Gnuplot::dbvalue (size_t i, const T & t, Ts... values) inline private
References dbvalue().
doplot() [1/2]
template<int n, typename T > void madness::Gnuplot::doplot (const char * name, const T & value0) inline private
References madness::name().
Referenced by doplot(), and plot().
doplot() [2/2]
template<int n, typename T , typename... Ts> void madness::Gnuplot::doplot (const char * name, const T & value0, Ts... values) inline private
References doplot(), and madness::name().
operator()() [1/2]
void madness::Gnuplot::operator() (const char * cmd, bool EOL = true) inline
References f, and ftee.
operator()() [2/2]
void madness::Gnuplot::operator() (const std::string & cmd, bool EOL = true) inline
operator=() [1/2]
Gnuplot & madness::Gnuplot::operator= (const Gnuplot &) delete
operator=() [2/2]
Gnuplot & madness::Gnuplot::operator= (Gnuplot &&) delete
plot()
template<typename T , typename... Ts> void madness::Gnuplot::plot (const T & x, Ts... values) inline
References db(), and doplot().
Referenced by main().
test()
static void madness::Gnuplot::test () inline static
References db(), madness::g, npts, and madness::phase().
Referenced by main().
Member Data Documentation
f
FILE* madness::Gnuplot::f private
Referenced by Gnuplot(), ~Gnuplot(), and operator()().
ftee
FILE* madness::Gnuplot::ftee private
Referenced by Gnuplot(), ~Gnuplot(), and operator()().
pid
pid_t madness::Gnuplot::pid private
Referenced by Gnuplot(), and ~Gnuplot().
The documentation for this class was generated from the following file:
gnuplot.h