MADNESS: madness::int_factor_functor< NDIM > Class Template Reference
madness::int_factor_functor< NDIM > Class Template Reference
Functor for the correction factor, which is multiplied with the exchange correlation potential.
#include <AC.h>
Public Member Functions
int_factor_functor ()
int_factor_functor (const ACParameters< NDIM > &ac_param)
double int_factor (const Vector< double, NDIM > &r, std::vector< atom_information< NDIM > > between) const
double operator() (const Vector< double, NDIM > &r) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, NDIM >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level () const
Override this to change the minimum level of refinement at special points (default is 6)
virtual std::vector< Vector< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Member Functions
double get_distance (Vector< double, NDIM > elec, Vector< double, NDIM > nuc) const
Private Attributes
const ACParameters< NDIM > & ac_param_
Parameter for the asymtotic correction.
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, NDIM >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, NDIM >
Level special_level_
Detailed Description
template<unsigned long int NDIM>
class madness::int_factor_functor< NDIM >
Functor for the correction factor, which is multiplied with the exchange correlation potential.
Constructor & Destructor Documentation
int_factor_functor() [1/2]
template<unsigned long int NDIM> madness::int_factor_functor< NDIM >::int_factor_functor () inline
int_factor_functor() [2/2]
template<unsigned long int NDIM> madness::int_factor_functor< NDIM >::int_factor_functor (const ACParameters< NDIM > & ac_param) inline
Member Function Documentation
get_distance()
template<unsigned long int NDIM> double madness::int_factor_functor< NDIM >::get_distance (Vector< double, NDIM > elec, Vector< double, NDIM > nuc) const inline private
Computes the distance between electron and nucleus
Parameters
[in] elec position of electron
[in] nuc position of nucleus
[out] distance distance between electron and nucleus
References madness::distance(), and NDIM.
Referenced by madness::int_factor_functor< NDIM >::int_factor(), and madness::int_factor_functor< NDIM >::operator()().
int_factor()
template<unsigned long int NDIM> double madness::int_factor_functor< NDIM >::int_factor (const Vector< double, NDIM > & r, std::vector< atom_information< NDIM > > between) const inline
Computes correction factor for the exchange correlation potential if electron position is between R1 and R2
Parameters
[in] r position of electron
[in] between vector of the atom_information of all atoms for that electron position is between R1 and R2
[out] int_factor correction factor
References madness::int_factor_functor< NDIM >::ac_param_, madness::int_factor_functor< NDIM >::get_distance(), and madness::int_factor_functor< NDIM >::int_factor().
Referenced by madness::int_factor_functor< NDIM >::int_factor(), madness::lr_pot_functor< NDIM >::int_factor(), and madness::int_factor_functor< NDIM >::operator()().
operator()()
template<unsigned long int NDIM> double madness::int_factor_functor< NDIM >::operator() (const Vector< double, NDIM > & r) const inline virtual
Computes correction factor for exchange correlation potential
Parameters
[in] r position of the electron
[out] correction factor for exchange correlation potential at position r
Implements madness::FunctionFunctorInterface< double, NDIM >.
References madness::int_factor_functor< NDIM >::ac_param_, d, madness::int_factor_functor< NDIM >::get_distance(), and madness::int_factor_functor< NDIM >::int_factor().
Member Data Documentation
ac_param_
template<unsigned long int NDIM> const ACParameters<NDIM>& madness::int_factor_functor< NDIM >::ac_param_ private
Parameter for the asymtotic correction.
Referenced by madness::int_factor_functor< NDIM >::int_factor(), and madness::int_factor_functor< NDIM >::operator()().
The documentation for this class was generated from the following file:
AC.h