MADNESS: madness::VectorOfFunctionsSpace< T, VDIM, FDIM > Class Template Reference
madness::VectorOfFunctionsSpace< T, VDIM, FDIM > Class Template Reference
A vector space using MADNESS Vectors of MADNESS Functions.
#include <gmres.h>
Public Types
typedef TensorTypeData< T >::float_scalar_type real_type
typedef T scalar_type
Public Member Functions
VectorOfFunctionsSpace (World &world)
virtual ~VectorOfFunctionsSpace ()
virtual void destroy (Vector< Function< scalar_type, FDIM >, VDIM > &f) const
Any special instructions to be executed when a vector is no longer needed.
virtual Vector< Function< scalar_type, FDIM >, VDIM > & gaxpy (Vector< Function< scalar_type, FDIM >, VDIM > &x, const scalar_type &a, const Vector< Function< scalar_type, FDIM >, VDIM > &y, const scalar_type &b) const
Standard bilinear gaxpy.
virtual scalar_type inner (const Vector< Function< scalar_type, FDIM >, VDIM > &l, const Vector< Function< scalar_type, FDIM >, VDIM > &r) const
The inner product between two vectors.
virtual real_type norm (const Vector< Function< scalar_type, FDIM >, VDIM > &vec) const
The norm of a vector.
virtual Vector< Function< scalar_type, FDIM >, VDIM > & scale (Vector< Function< scalar_type, FDIM >, VDIM > &vec, const scalar_type &c) const
Scales the vector (in-place) by a constant.
Public Member Functions inherited from madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >
AbstractVectorSpace (World &world)
Make a vector space.
virtual ~AbstractVectorSpace ()
Additional Inherited Members
Public Attributes inherited from madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >
World & world
The world.
Detailed Description
template<typename T, int VDIM, int FDIM>
class madness::VectorOfFunctionsSpace< T, VDIM, FDIM >
A vector space using MADNESS Vectors of MADNESS Functions.
Member Typedef Documentation
real_type
template<typename T , int VDIM, int FDIM> typedef TensorTypeData<T>::float_scalar_type madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::real_type
scalar_type
template<typename T , int VDIM, int FDIM> typedef T madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::scalar_type
Constructor & Destructor Documentation
VectorOfFunctionsSpace()
template<typename T , int VDIM, int FDIM> madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::VectorOfFunctionsSpace (World & world) inline
~VectorOfFunctionsSpace()
template<typename T , int VDIM, int FDIM> virtual madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::~VectorOfFunctionsSpace () inline virtual
Member Function Documentation
destroy()
template<typename T , int VDIM, int FDIM> virtual void madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::destroy (Vector< Function< scalar_type, FDIM >, VDIM > &) const inline virtual
Any special instructions to be executed when a vector is no longer needed.
Unless otherwise specified, do nothing.
Reimplemented from madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >.
References madness::f.
gaxpy()
template<typename T , int VDIM, int FDIM> virtual Vector< Function< scalar_type, FDIM >, VDIM > & madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::gaxpy (Vector< Function< scalar_type, FDIM >, VDIM > & x, const scalar_type & a, const Vector< Function< scalar_type, FDIM >, VDIM > & y, const scalar_type & b) const inline virtual
Standard bilinear gaxpy.
Returns
The new vector,
Implements madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >.
References a, b, and madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::gaxpy().
Referenced by madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::gaxpy().
inner()
template<typename T , int VDIM, int FDIM> virtual scalar_type madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::inner (const Vector< Function< scalar_type, FDIM >, VDIM > & , const Vector< Function< scalar_type, FDIM >, VDIM > &) const inline virtual
The inner product between two vectors.
Implements madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >.
References madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::inner().
Referenced by madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::inner().
norm()
template<typename T , int VDIM, int FDIM> virtual real_type madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::norm (const Vector< Function< scalar_type, FDIM >, VDIM > &) const inline virtual
The norm of a vector.
Implements madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >.
References madness::vec().
scale()
template<typename T , int VDIM, int FDIM> virtual Vector< Function< scalar_type, FDIM >, VDIM > & madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::scale (Vector< Function< scalar_type, FDIM >, VDIM > & , const scalar_type &) const inline virtual
Scales the vector (in-place) by a constant.
Returns
The scaled vector
Implements madness::AbstractVectorSpace< Vector< Function< T, FDIM >, VDIM >, TensorTypeData< T >::float_scalar_type, T >.
References c, madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::scale(), and madness::vec().
Referenced by madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::scale().
The documentation for this class was generated from the following file:
gmres.h