MADNESS: madness::WorldDCPmapInterface< keyT > Class Template Reference
madness::WorldDCPmapInterface< keyT > Class Template Reference abstract
Worlddc
Interface to be provided by any process map.
#include <worlddc.h>
Public Types
typedef WorldDCRedistributeInterface< keyT > * ptrT
Public Member Functions
virtual ~WorldDCPmapInterface ()
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
virtual DistributionType distribution_type () const
by default the map is distributed
std::size_t global_size (World &world) const
Counts global number of entries in all containers associated with this process map.
std::size_t local_size () const
Counts local number of entries in all containers associated with this process map.
virtual ProcessID owner (const keyT &key) const =0
Maps key to processor.
virtual void print () const
void print_data_sizes (World &world, const std::string msg="") const
Prints size info to std::cout.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< keyT > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
Private Attributes
std::set< ptrT > ptrs
Detailed Description
template<typename keyT>
class madness::WorldDCPmapInterface< keyT >
Interface to be provided by any process map.
NOTE: if the map is not distributed, but replicated, you must override the distribution_type() method.
Member Typedef Documentation
ptrT
template<typename keyT > typedef WorldDCRedistributeInterface<keyT>* madness::WorldDCPmapInterface< keyT >::ptrT
Constructor & Destructor Documentation
~WorldDCPmapInterface()
template<typename keyT > virtual madness::WorldDCPmapInterface< keyT >::~WorldDCPmapInterface () inline virtual
Member Function Documentation
deregister_callback()
template<typename keyT > void madness::WorldDCPmapInterface< keyT >::deregister_callback (ptrT ptr) inline
Deregisters object for receipt of redistribute callbacks.
Parameters
[in] ptr Pointer to class derived from WorldDCRedistributedInterface
References madness::WorldDCPmapInterface< keyT >::ptrs.
distribution_type()
template<typename keyT > virtual DistributionType madness::WorldDCPmapInterface< keyT >::distribution_type () const inline virtual
by default the map is distributed
Reimplemented in madness::WorldDCLocalPmap< keyT, hashfunT >, and madness::WorldDCNodeReplicatedPmap< keyT, hashfunT >.
References madness::Distributed.
global_size()
template<typename keyT > std::size_t madness::WorldDCPmapInterface< keyT >::global_size (World & world) const inline
Counts global number of entries in all containers associated with this process map.
Collective operation with global fence
References madness::WorldGopInterface::fence(), madness::World::gop, madness::WorldDCPmapInterface< keyT >::local_size(), sum, and madness::WorldGopInterface::sum().
Referenced by madness::WorldDCPmapInterface< keyT >::print_data_sizes().
local_size()
template<typename keyT > std::size_t madness::WorldDCPmapInterface< keyT >::local_size () const inline
Counts local number of entries in all containers associated with this process map.
References madness::WorldDCPmapInterface< keyT >::ptrs, and sum.
Referenced by madness::WorldDCPmapInterface< keyT >::global_size(), and madness::WorldDCPmapInterface< keyT >::print_data_sizes().
owner()
template<typename keyT > virtual ProcessID madness::WorldDCPmapInterface< keyT >::owner (const keyT & key) const pure virtual
Maps key to processor.
Parameters
[in] key Key for container
Returns
Processor that logically owns the key
Implemented in TestPmap, LevelPmap, LevelPmap, LevelPmapX, PartitionPmap, madness::MyPmap< D >, madness::SimplePmap< keyT >, madness::LevelPmap< keyT >, madness::LBDeuxPmap< NDIM >, madness::WorldDCDefaultPmap< keyT, hashfunT >, madness::WorldDCLocalPmap< keyT, hashfunT >, and madness::WorldDCNodeReplicatedPmap< keyT, hashfunT >.
print()
template<typename keyT > virtual void madness::WorldDCPmapInterface< keyT >::print () const inline virtual
Reimplemented in madness::LBDeuxPmap< NDIM >, and madness::MyPmap< D >.
print_data_sizes()
template<typename keyT > void madness::WorldDCPmapInterface< keyT >::print_data_sizes (World & world, const std::string msg = "") const inline
Prints size info to std::cout.
Collective operation with global fence
References madness::WorldGopInterface::fence(), madness::WorldDCPmapInterface< keyT >::global_size(), madness::World::gop, madness::WorldDCPmapInterface< keyT >::local_size(), madness::print(), madness::World::rank(), madness::World::size(), and madness::WorldGopInterface::sum().
Referenced by madness::WorldDCPmapInterface< keyT >::redistribute().
redistribute()
template<typename keyT > void madness::WorldDCPmapInterface< keyT >::redistribute (World & world, const std::shared_ptr< WorldDCPmapInterface< keyT > > & newpmap) inline
Invoking this switches all registered objects from this process map to the new one.
After invoking this routine all objects will be registered with the new map and no objects will be registered in the current map.
Parameters
[in] world The associated world
[in] newpmap The new process map
References madness::WorldGopInterface::fence(), madness::World::gop, madness::WorldDCPmapInterface< keyT >::print_data_sizes(), and madness::WorldDCPmapInterface< keyT >::ptrs.
register_callback()
template<typename keyT > void madness::WorldDCPmapInterface< keyT >::register_callback (ptrT ptr) inline
Registers object for receipt of redistribute callbacks.
Parameters
[in] ptr Pointer to class derived from WorldDCRedistributedInterface
References madness::WorldDCPmapInterface< keyT >::ptrs.
Member Data Documentation
ptrs
template<typename keyT > std::set<ptrT> madness::WorldDCPmapInterface< keyT >::ptrs private
Referenced by madness::WorldDCPmapInterface< keyT >::deregister_callback(), madness::WorldDCPmapInterface< keyT >::local_size(), madness::WorldDCPmapInterface< keyT >::redistribute(), and madness::WorldDCPmapInterface< keyT >::register_callback().
The documentation for this class was generated from the following file:
worlddc.h