MADNESS: madness::WorldContainerImpl< keyT, valueT, hashfunT > Class Template Reference
madness::WorldContainerImpl< keyT, valueT, hashfunT > Class Template Reference
Worlddc
Internal implementation of distributed container to facilitate shallow copy.
#include <worlddc.h>
Classes
struct P2Op
Public Types
typedef internal_containerT::accessor accessor
typedef internal_containerT::const_accessor const_accessor
typedef WorldContainerIterator< internal_const_iteratorT > const_iterator
typedef WorldContainerIterator< internal_const_iteratorT > const_iteratorT
typedef const pairT const_pairT
typedef WorldContainerImpl< keyT, valueT, hashfunT > implT
typedef internal_containerT::const_iterator internal_const_iteratorT
typedef ConcurrentHashMap< keyT, valueT, hashfunT > internal_containerT
typedef internal_containerT::iterator internal_iteratorT
typedef WorldContainerIterator< internal_iteratorT > iterator
typedef WorldContainerIterator< internal_iteratorT > iteratorT
typedef std::pair< const keyT, valueT > pairT
Public Types inherited from madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >
typedef WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > > objT
Public Member Functions
WorldContainerImpl (World &world, const std::shared_ptr< WorldDCPmapInterface< keyT > > &pm, const hashfunT &hf)
virtual ~WorldContainerImpl ()
iterator begin ()
const_iterator begin () const
void clear ()
void do_replicate (World &world)
iterator end ()
const_iterator end () const
void erase (const keyT &key)
template<typename InIter >
void erase (InIter first, InIter last)
template<typename InIter >
void erase (InIter it)
bool find (accessor &acc, const keyT &key)
Future< iterator > find (const keyT &key)
Future< const_iterator > find (const keyT &key) const
bool find (const_accessor &acc, const keyT &key) const
const hashfunT & get_hash () const
std::shared_ptr< WorldDCPmapInterface< keyT > > & get_pmap ()
const std::shared_ptr< WorldDCPmapInterface< keyT > > & get_pmap () const
void insert (const pairT &datum)
bool insert_acc (accessor &acc, const keyT &key)
bool insert_const_acc (const_accessor &acc, const keyT &key)
bool is_local (const keyT &key) const
template<typename memfunT >
itemfun (const keyT &key, memfunT memfun)
template<typename memfunT , typename arg1T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1)
template<typename memfunT , typename arg1T , typename arg2T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1, const arg2T &arg2)
template<typename memfunT , typename arg1T , typename arg2T , typename arg3T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1, const arg2T &arg2, const arg3T &arg3)
template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1, const arg2T &arg2, const arg3T &arg3, const arg4T &arg4)
template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T , typename arg5T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1, const arg2T &arg2, const arg3T &arg3, const arg4T &arg4, const arg5T &arg5)
template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T , typename arg5T , typename arg6T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1, const arg2T &arg2, const arg3T &arg3, const arg4T &arg4, const arg5T &arg5, const arg6T &arg6)
template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T , typename arg5T , typename arg6T , typename arg7T >
itemfun (const keyT &key, memfunT memfun, const arg1T &arg1, const arg2T &arg2, const arg3T &arg3, const arg4T &arg4, const arg5T &arg5, const arg6T &arg6, const arg7T &arg7)
ProcessID owner (const keyT &key) const
bool probe (const keyT &key) const
void redistribute_phase1 (const std::shared_ptr< WorldDCPmapInterface< keyT > > &newpmap)
void redistribute_phase2 ()
void redistribute_phase3 ()
void replicate (bool fence)
void replicate_on_hosts (bool fence)
void reset_pmap_to_local ()
std::size_t size () const
Public Member Functions inherited from madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >
WorldObject (const WorldObject &other)
WorldObject (World &world)
Constructor that associates an object (via the derived class) with a globally unique ID.
virtual ~WorldObject ()
World & get_world () const
Returns a reference to the world.
const uniqueidT & id () const
Returns the globally unique object ID.
WorldObject & operator= (const WorldObject &)=delete
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9) const
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8,a9).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)().
Public Member Functions inherited from madness::WorldObjectBase
virtual ~WorldObjectBase ()=default
Public Member Functions inherited from madness::WorldDCRedistributeInterface< keyT >
virtual ~WorldDCRedistributeInterface ()
Private Member Functions
WorldContainerImpl ()
void find_failure_handler (const RemoteReference< FutureImpl< iterator > > &ref)
Handles unsuccessful find response.
void find_handler (ProcessID requestor, const keyT &key, const RemoteReference< FutureImpl< iterator > > &ref)
Handles find request.
void find_success_handler (const RemoteReference< FutureImpl< iterator > > &ref, const pairT &datum)
Handles successful find response.
Private Attributes
internal_containerT local
Locally owned data.
const ProcessID me
My MPI rank.
std::vector< keyT > * move_list
Tempoary used to record data that needs redistributing.
std::shared_ptr< WorldDCPmapInterface< keyT > > pmap
Function/class to map from keys to owning process.
Friends
class WorldContainer< keyT, valueT, hashfunT >
Additional Inherited Members
Protected Member Functions inherited from madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >
void process_pending ()
To be called from derived constructor to process pending messages.
Detailed Description
template<typename keyT, typename valueT, typename hashfunT>
class madness::WorldContainerImpl< keyT, valueT, hashfunT >
Internal implementation of distributed container to facilitate shallow copy.
Member Typedef Documentation
accessor
template<typename keyT , typename valueT , typename hashfunT > typedef internal_containerT::accessor madness::WorldContainerImpl< keyT, valueT, hashfunT >::accessor
const_accessor
template<typename keyT , typename valueT , typename hashfunT > typedef internal_containerT::const_accessor madness::WorldContainerImpl< keyT, valueT, hashfunT >::const_accessor
const_iterator
template<typename keyT , typename valueT , typename hashfunT > typedef WorldContainerIterator<internal_const_iteratorT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::const_iterator
const_iteratorT
template<typename keyT , typename valueT , typename hashfunT > typedef WorldContainerIterator<internal_const_iteratorT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::const_iteratorT
const_pairT
template<typename keyT , typename valueT , typename hashfunT > typedef const pairT madness::WorldContainerImpl< keyT, valueT, hashfunT >::const_pairT
implT
template<typename keyT , typename valueT , typename hashfunT > typedef WorldContainerImpl<keyT, valueT, hashfunT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::implT
internal_const_iteratorT
template<typename keyT , typename valueT , typename hashfunT > typedef internal_containerT::const_iterator madness::WorldContainerImpl< keyT, valueT, hashfunT >::internal_const_iteratorT
internal_containerT
template<typename keyT , typename valueT , typename hashfunT > typedef ConcurrentHashMap<keyT, valueT, hashfunT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::internal_containerT
internal_iteratorT
template<typename keyT , typename valueT , typename hashfunT > typedef internal_containerT::iterator madness::WorldContainerImpl< keyT, valueT, hashfunT >::internal_iteratorT
iterator
template<typename keyT , typename valueT , typename hashfunT > typedef WorldContainerIterator<internal_iteratorT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::iterator
iteratorT
template<typename keyT , typename valueT , typename hashfunT > typedef WorldContainerIterator<internal_iteratorT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::iteratorT
pairT
template<typename keyT , typename valueT , typename hashfunT > typedef std::pair<const keyT, valueT> madness::WorldContainerImpl< keyT, valueT, hashfunT >::pairT
Constructor & Destructor Documentation
WorldContainerImpl() [1/2]
template<typename keyT , typename valueT , typename hashfunT > madness::WorldContainerImpl< keyT, valueT, hashfunT >::WorldContainerImpl () private
WorldContainerImpl() [2/2]
template<typename keyT , typename valueT , typename hashfunT > madness::WorldContainerImpl< keyT, valueT, hashfunT >::WorldContainerImpl (World & world, const std::shared_ptr< WorldDCPmapInterface< keyT > > & pm, const hashfunT & hf) inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
~WorldContainerImpl()
template<typename keyT , typename valueT , typename hashfunT > virtual madness::WorldContainerImpl< keyT, valueT, hashfunT >::~WorldContainerImpl () inline virtual
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
Member Function Documentation
begin() [1/2]
template<typename keyT , typename valueT , typename hashfunT > iterator madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin () inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts().
begin() [2/2]
template<typename keyT , typename valueT , typename hashfunT > const_iterator madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
clear()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::clear () inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts().
do_replicate()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate (World & world) inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin(), madness::WorldGopInterface::broadcast_serializable(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::World::gop, madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert(), madness::World::rank(), madness::World::size(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::size(), and madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::world.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts().
end() [1/2]
template<typename keyT , typename valueT , typename hashfunT > iterator madness::WorldContainerImpl< keyT, valueT, hashfunT >::end () inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_failure_handler(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts().
end() [2/2]
template<typename keyT , typename valueT , typename hashfunT > const_iterator madness::WorldContainerImpl< keyT, valueT, hashfunT >::end () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
erase() [1/3]
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase (const keyT & key) inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, MADNESS_ASSERT, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner(), madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::send(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::try_erase().
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase().
erase() [2/3]
template<typename keyT , typename valueT , typename hashfunT > template<typename InIter > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase (InIter first, InIter last) inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase().
erase() [3/3]
template<typename keyT , typename valueT , typename hashfunT > template<typename InIter > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase (InIter it) inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), and MADNESS_ASSERT.
find() [1/4]
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::find (accessor & acc, const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, and madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner().
find() [2/4]
template<typename keyT , typename valueT , typename hashfunT > Future< iterator > madness::WorldContainerImpl< keyT, valueT, hashfunT >::find (const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner(), madness::Future< T >::remote_ref(), and madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::send().
find() [3/4]
template<typename keyT , typename valueT , typename hashfunT > Future< const_iterator > madness::WorldContainerImpl< keyT, valueT, hashfunT >::find (const keyT & key) const inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::find().
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::find().
find() [4/4]
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::find (const_accessor & acc, const keyT & key) const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, and madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner().
find_failure_handler()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_failure_handler (const RemoteReference< FutureImpl< iterator > > & ref) inline private
Handles unsuccessful find response.
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::f, and madness::FutureImpl< T >::get().
find_handler()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_handler (ProcessID requestor, const keyT & key, const RemoteReference< FutureImpl< iterator > > & ref) inline private
Handles find request.
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, and madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::send().
find_success_handler()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_success_handler (const RemoteReference< FutureImpl< iterator > > & ref, const pairT & datum) inline private
Handles successful find response.
References madness::f, and madness::FutureImpl< T >::get().
get_hash()
template<typename keyT , typename valueT , typename hashfunT > const hashfunT & madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_hash () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::get_hash(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
get_pmap() [1/2]
template<typename keyT , typename valueT , typename hashfunT > std::shared_ptr< WorldDCPmapInterface< keyT > > & madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_pmap () inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
get_pmap() [2/2]
template<typename keyT , typename valueT , typename hashfunT > const std::shared_ptr< WorldDCPmapInterface< keyT > > & madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_pmap () const inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
insert()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert (const pairT & datum) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner(), and madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::send().
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate().
insert_acc()
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_acc (accessor & acc, const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, MADNESS_ASSERT, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, and madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner().
insert_const_acc()
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_const_acc (const_accessor & acc, const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, MADNESS_ASSERT, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, and madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner().
is_local()
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::is_local (const keyT & key) const inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, and madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner().
itemfun() [1/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [2/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [3/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T , typename arg2T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1, const arg2T & arg2) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [4/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T , typename arg2T , typename arg3T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1, const arg2T & arg2, const arg3T & arg3) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [5/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1, const arg2T & arg2, const arg3T & arg3, const arg4T & arg4) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [6/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T , typename arg5T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1, const arg2T & arg2, const arg3T & arg3, const arg4T & arg4, const arg5T & arg5) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [7/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T , typename arg5T , typename arg6T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1, const arg2T & arg2, const arg3T & arg3, const arg4T & arg4, const arg5T & arg5, const arg6T & arg6) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
itemfun() [8/8]
template<typename keyT , typename valueT , typename hashfunT > template<typename memfunT , typename arg1T , typename arg2T , typename arg3T , typename arg4T , typename arg5T , typename arg6T , typename arg7T > madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun (const keyT & key, memfunT memfun, const arg1T & arg1, const arg2T & arg2, const arg3T & arg3, const arg4T & arg4, const arg5T & arg5, const arg6T & arg6, const arg7T & arg7) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::local.
owner()
template<typename keyT , typename valueT , typename hashfunT > ProcessID madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner (const keyT & key) const inline
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_const_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::is_local(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::probe(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1().
probe()
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::probe (const keyT & key) const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, and madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner().
redistribute_phase1()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1 (const std::shared_ptr< WorldDCPmapInterface< keyT > > & newpmap) inline virtual
Implements madness::WorldDCRedistributeInterface< keyT >.
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, madness::WorldContainerImpl< keyT, valueT, hashfunT >::me, madness::WorldContainerImpl< keyT, valueT, hashfunT >::move_list, madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
redistribute_phase2()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase2 () inline virtual
Implements madness::WorldDCRedistributeInterface< keyT >.
References madness::WorldTaskQueue::for_each(), madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::get_world(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::move_list, and madness::World::taskq.
redistribute_phase3()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase3 () inline virtual
Implements madness::WorldDCRedistributeInterface< keyT >.
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::move_list.
replicate()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate (bool fence) inline
replicates this WorldContainer on all ProcessIDs and generates a ProcessMap where all nodes are local
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate(), madness::WorldGopInterface::fence(), madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::get_world(), madness::World::gop, madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap, and madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::world.
replicate_on_hosts()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts (bool fence) inline
replicates this WorldContainer on all hosts and generates a ProcessMap where all nodes are host-local (not rank-local) will always fence
print in rank-order
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin(), madness::WorldGopInterface::broadcast_serializable(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::clear(), madness::WorldMpiInterface::comm(), SafeMPI::Intracomm::Create(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::WorldGopInterface::fence(), SafeMPI::Intracomm::Get_group(), madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::get_world(), madness::World::gop, SafeMPI::Group::Incl(), madness::lowest_rank_on_host_of_rank(), MADNESS_CHECK, madness::World::mpi, madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap, madness::primary_ranks_per_host(), madness::World::rank(), madness::ranks_per_host(), madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::send(), madness::World::size(), and madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::world.
reset_pmap_to_local()
template<typename keyT , typename valueT , typename hashfunT > void madness::WorldContainerImpl< keyT, valueT, hashfunT >::reset_pmap_to_local () inline
References madness::WorldObject< WorldContainerImpl< keyT, valueT, hashfunT > >::get_world(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap.
size()
template<typename keyT , typename valueT , typename hashfunT > std::size_t madness::WorldContainerImpl< keyT, valueT, hashfunT >::size () const inline virtual
Implements madness::WorldDCRedistributeInterface< keyT >.
References madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size().
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::do_replicate().
Friends And Related Symbol Documentation
WorldContainer< keyT, valueT, hashfunT >
template<typename keyT , typename valueT , typename hashfunT > friend class WorldContainer< keyT, valueT, hashfunT > friend
Member Data Documentation
local
template<typename keyT , typename valueT , typename hashfunT > internal_containerT madness::WorldContainerImpl< keyT, valueT, hashfunT >::local private
Locally owned data.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::clear(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_handler(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_hash(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_const_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::probe(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::size().
me
template<typename keyT , typename valueT , typename hashfunT > const ProcessID madness::WorldContainerImpl< keyT, valueT, hashfunT >::me private
My MPI rank.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_const_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::is_local(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::probe(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1().
move_list
template<typename keyT , typename valueT , typename hashfunT > std::vector<keyT>* madness::WorldContainerImpl< keyT, valueT, hashfunT >::move_list private
Tempoary used to record data that needs redistributing.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase2(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase3().
pmap
template<typename keyT , typename valueT , typename hashfunT > std::shared_ptr<WorldDCPmapInterface<keyT> > madness::WorldContainerImpl< keyT, valueT, hashfunT >::pmap private
Function/class to map from keys to owning process.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::WorldContainerImpl(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::~WorldContainerImpl(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_pmap(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_pmap(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts(), and madness::WorldContainerImpl< keyT, valueT, hashfunT >::reset_pmap_to_local().
The documentation for this class was generated from the following file:
worlddc.h