MADNESS: NuclearVector Class Reference
NuclearVector Class Reference
#include <property.h>
Public Member Functions
NuclearVector (World &world, Molecule &molecule)
Public Member Functions inherited from PropertyBase
PropertyBase ()
Additional Inherited Members
Public Attributes inherited from PropertyBase
size_t num_operators
vector_real_function_3d operator_vector
Constructor & Destructor Documentation
NuclearVector()
NuclearVector::NuclearVector (World & world, Molecule & molecule)
References axis, madness::func(), molecule, madness::Molecule::natom(), madness::norm2(), PropertyBase::num_operators, PropertyBase::operator_vector, madness::print(), madness::truncate(), and truncate_mode.
The documentation for this class was generated from the following files:
property.h
property.cc