MADNESS: madness::GradientalGaussSlater Class Reference
madness::GradientalGaussSlater Class Reference
A nuclear correlation factor class.
#include <correlationfactor.h>
Public Member Functions
GradientalGaussSlater (World &world, const Molecule &mol, const double a)
ctor
corrfactype type () const
Public Member Functions inherited from madness::NuclearCorrelationFactor
NuclearCorrelationFactor (World &world, const Molecule &mol)
ctor
virtual ~NuclearCorrelationFactor ()
virtual destructor
virtual real_function_3d apply_U (const real_function_3d &rhs) const
apply the regularized potential U_nuc on a given function rhs
coord_3d dsmoothed_unitvec (const coord_3d &xyz, const int axis, double smoothing=0.0) const
derivative of smoothed unit vector wrt the electronic coordinate
virtual real_function_3d function () const
return the nuclear correlation factor
void initialize (const double vtol1)
initialize the regularized potentials U1 and U2
virtual real_function_3d inverse () const
return the inverse nuclear correlation factor
coord_3d smoothed_unitvec (const coord_3d &xyz, double smoothing=0.0) const
smoothed unit vector for the computation of the U1 potential
virtual real_function_3d square () const
return the square of the nuclear correlation factor
virtual real_function_3d square_times_V_derivative (const int iatom, const int axis) const
virtual const real_function_3d U1 (const int axis) const
return the U1 term of the correlation function
std::vector< real_function_3d > U1vec () const
return the U1 functions in a vector
virtual const real_function_3d U2 () const
return the U2 term of the correlation function
Private Member Functions
double S (const double &r, const double &Z) const
the nuclear correlation factor
coord_3d Sp (const coord_3d &vr1A, const double &Z) const
radial part first derivative of the nuclear correlation factor
double Spp_div_S (const double &r, const double &Z) const
second derivative of the nuclear correlation factor
double Sr_div_S (const double &r, const double &Z) const
double Srr_div_S (const double &r, const double &Z) const
double Srrr_div_S (const double &r, const double &Z) const
double U2X_spherical (const double &r, const double &Z, const double &rcut) const
derivative of the U2 potential wrt nuclear coordinate X (spherical part)
Private Attributes
const double a
Additional Inherited Members
Public Types inherited from madness::NuclearCorrelationFactor
enum corrfactype {
None , GradientalGaussSlater , GaussSlater , LinearSlater ,
Polynomial , Slater , poly4erfc , Two ,
Adhoc
}
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
Protected Attributes inherited from madness::NuclearCorrelationFactor
std::vector< real_function_3d > U1_function
the three components of the U1 potential
real_function_3d U2_function
the purely local U2 potential, having absorbed the nuclear pot V_nuc
Detailed Description
A nuclear correlation factor class.
The nuclear correlation factor is given by [f R = \prod S_A ; S_A=exp(-Z_A r_{1A}) + (1 - exp(-r_{1A}^2)) ]f
Constructor & Destructor Documentation
GradientalGaussSlater()
madness::GradientalGaussSlater::GradientalGaussSlater (World & world, const Molecule & mol, const double a) inline
ctor
Parameters
[in] world the world
[in] mol molecule with the sites of the nuclei
References a, madness::Molecule::get_eprec(), madness::print(), madness::World::rank(), and madness::NuclearCorrelationFactor::world.
Member Function Documentation
S()
double madness::GradientalGaussSlater::S (const double & r, const double & Z) const inline private virtual
the nuclear correlation factor
Implements madness::NuclearCorrelationFactor.
References a, and Z.
Sp()
coord_3d madness::GradientalGaussSlater::Sp (const coord_3d & vr1A, const double & Z) const inline private virtual
radial part first derivative of the nuclear correlation factor
Implements madness::NuclearCorrelationFactor.
References a, madness::NuclearCorrelationFactor::smoothed_unitvec(), and Z.
Spp_div_S()
double madness::GradientalGaussSlater::Spp_div_S (const double & r, const double & Z) const inline private virtual
second derivative of the nuclear correlation factor
-1/2 S"/S - Z/r
Implements madness::NuclearCorrelationFactor.
References a, a2, e(), madness::g, and Z.
Sr_div_S()
double madness::GradientalGaussSlater::Sr_div_S (const double & r, const double & Z) const inline private virtual
first derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implements madness::NuclearCorrelationFactor.
References a, e(), madness::g, and Z.
Srr_div_S()
double madness::GradientalGaussSlater::Srr_div_S (const double & r, const double & Z) const inline private virtual
second derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implements madness::NuclearCorrelationFactor.
References a, e(), madness::g, madness::power< 4 >(), and Z.
Srrr_div_S()
double madness::GradientalGaussSlater::Srrr_div_S (const double & r, const double & Z) const inline private virtual
third derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implements madness::NuclearCorrelationFactor.
References a, e(), madness::g, madness::power< 3 >(), madness::power< 4 >(), madness::power< 6 >(), and Z.
type()
corrfactype madness::GradientalGaussSlater::type () const inline virtual
Implements madness::NuclearCorrelationFactor.
References madness::NuclearCorrelationFactor::GradientalGaussSlater.
U2X_spherical()
double madness::GradientalGaussSlater::U2X_spherical (const double & r, const double & Z, const double & rcut) const inline private virtual
derivative of the U2 potential wrt nuclear coordinate X (spherical part)
need to reimplement this for all derived classes due to the range for r -> 0, where the singular terms cancel. With
returns the term in the parenthesis without the the derivative of rho
Reimplemented from madness::NuclearCorrelationFactor.
References a, a2, madness::r2(), madness::NuclearCorrelationFactor::Sr_div_S(), madness::NuclearCorrelationFactor::Srr_div_S(), madness::NuclearCorrelationFactor::Srrr_div_S(), Z, and Z2().
Member Data Documentation
a
const double madness::GradientalGaussSlater::a private
The documentation for this class was generated from the following file:
correlationfactor.h