MADNESS: FunctionIO< T, NDIM > Class Template Reference
FunctionIO< T, NDIM > Class Template Reference
#include <FunctionIO.h>
Static Public Member Functions
static size_t count_leaf_nodes (const Function< T, NDIM > &f)
static size_t count_leaf_nodes (const Function< T, NDIM > &f)
static size_t count_leaf_nodes (const Function< T, NDIM > &f)
static Function< T, NDIM > read_function (World &world, std::istream &in)
static Function< T, NDIM > read_function (World &world, std::istream &in)
static Function< T, NDIM > read_function (World &world, std::istream &in)
static void read_function_coeffs (Function< T, NDIM > &f, std::istream &in, int num_leaf_nodes)
static void read_function_coeffs (Function< T, NDIM > &f, std::istream &in, int num_leaf_nodes)
static void read_function_coeffs (Function< T, NDIM > &f, std::istream &in, int num_leaf_nodes)
static void write_function (const Function< T, NDIM > &f, std::ostream &out)
static void write_function (const Function< T, NDIM > &f, std::ostream &out)
static void write_function (const Function< T, NDIM > &f, std::ostream &out)
static void write_function_coeffs (const Function< T, NDIM > &f, std::ostream &out, const Key< NDIM > &key)
static void write_function_coeffs (const Function< T, NDIM > &f, std::ostream &out, const Key< NDIM > &key)
static void write_function_coeffs (const Function< T, NDIM > &f, std::ostream &out, const Key< NDIM > &key)
Private Attributes
long k = FunctionDefaults<NDIM>::get_k()
long ndims = NDIM
long npts_per_box = simple_pow(k, ndims)
Member Function Documentation
count_leaf_nodes() [1/3]
template<typename T , std::size_t NDIM> static size_t FunctionIO< T, NDIM >::count_leaf_nodes (const Function< T, NDIM > & f) inline static
References madness::f.
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), test(), and FunctionIO< T, NDIM >::write_function().
count_leaf_nodes() [2/3]
template<typename T , std::size_t NDIM> static size_t FunctionIO< T, NDIM >::count_leaf_nodes (const Function< T, NDIM > & f) inline static
References madness::f.
count_leaf_nodes() [3/3]
template<typename T , std::size_t NDIM> static size_t FunctionIO< T, NDIM >::count_leaf_nodes (const Function< T, NDIM > & f) inline static
References madness::f.
read_function() [1/3]
template<typename T , std::size_t NDIM> static Function< T, NDIM > FunctionIO< T, NDIM >::read_function (World & world, std::istream & in) inline static
References d, madness::FunctionFactory< T, NDIM >::empty(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, FunctionIO< T, NDIM >::k, madness::FunctionFactory< T, NDIM >::k(), MADNESS_CHECK, NDIM, FunctionIO< T, NDIM >::read_function_coeffs(), and madness::FunctionDefaults< NDIM >::set_cell().
read_function() [2/3]
template<typename T , std::size_t NDIM> static Function< T, NDIM > FunctionIO< T, NDIM >::read_function (World & world, std::istream & in) inline static
References d, madness::FunctionFactory< T, NDIM >::empty(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, FunctionIO< T, NDIM >::k, madness::FunctionFactory< T, NDIM >::k(), MADNESS_CHECK, NDIM, FunctionIO< T, NDIM >::read_function_coeffs(), and madness::FunctionDefaults< NDIM >::set_cell().
read_function() [3/3]
template<typename T , std::size_t NDIM> static Function< T, NDIM > FunctionIO< T, NDIM >::read_function (World & world, std::istream & in) inline static
References d, madness::FunctionFactory< T, NDIM >::empty(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, FunctionIO< T, NDIM >::k, madness::FunctionFactory< T, NDIM >::k(), MADNESS_CHECK, NDIM, FunctionIO< T, NDIM >::read_function_coeffs(), and madness::FunctionDefaults< NDIM >::set_cell().
read_function_coeffs() [1/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::read_function_coeffs (Function< T, NDIM > & f, std::istream & in, int num_leaf_nodes) inline static
References madness::f, NDIM, madness::Tensor< T >::ptr(), and madness::BaseTensor::size().
Referenced by FunctionIO< T, NDIM >::read_function().
read_function_coeffs() [2/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::read_function_coeffs (Function< T, NDIM > & f, std::istream & in, int num_leaf_nodes) inline static
References madness::f, NDIM, madness::Tensor< T >::ptr(), and madness::BaseTensor::size().
read_function_coeffs() [3/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::read_function_coeffs (Function< T, NDIM > & f, std::istream & in, int num_leaf_nodes) inline static
References madness::f, NDIM, madness::Tensor< T >::ptr(), and madness::BaseTensor::size().
write_function() [1/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::write_function (const Function< T, NDIM > & f, std::ostream & out) inline static
References FunctionIO< T, NDIM >::count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), NDIM, and FunctionIO< T, NDIM >::write_function_coeffs().
write_function() [2/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::write_function (const Function< T, NDIM > & f, std::ostream & out) inline static
References FunctionIO< T, NDIM >::count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), NDIM, and FunctionIO< T, NDIM >::write_function_coeffs().
write_function() [3/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::write_function (const Function< T, NDIM > & f, std::ostream & out) inline static
References FunctionIO< T, NDIM >::count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), NDIM, and FunctionIO< T, NDIM >::write_function_coeffs().
write_function_coeffs() [1/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::write_function_coeffs (const Function< T, NDIM > & f, std::ostream & out, const Key< NDIM > & key) inline static
References madness::f, madness::Key< NDIM >::level(), MADNESS_EXCEPTION, NDIM, madness::Key< NDIM >::translation(), and FunctionIO< T, NDIM >::write_function_coeffs().
Referenced by FunctionIO< T, NDIM >::write_function(), and FunctionIO< T, NDIM >::write_function_coeffs().
write_function_coeffs() [2/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::write_function_coeffs (const Function< T, NDIM > & f, std::ostream & out, const Key< NDIM > & key) inline static
References madness::f, madness::Key< NDIM >::level(), MADNESS_EXCEPTION, NDIM, madness::Key< NDIM >::translation(), and FunctionIO< T, NDIM >::write_function_coeffs().
write_function_coeffs() [3/3]
template<typename T , std::size_t NDIM> static void FunctionIO< T, NDIM >::write_function_coeffs (const Function< T, NDIM > & f, std::ostream & out, const Key< NDIM > & key) inline static
References madness::f, madness::Key< NDIM >::level(), NDIM, madness::Key< NDIM >::translation(), and FunctionIO< T, NDIM >::write_function_coeffs().
Member Data Documentation
k
template<typename T , std::size_t NDIM> long FunctionIO< T, NDIM >::k = FunctionDefaults<NDIM>::get_k() private
Referenced by FunctionIO< T, NDIM >::read_function().
ndims
template<typename T , std::size_t NDIM> long FunctionIO< T, NDIM >::ndims = NDIM private
npts_per_box
template<typename T , std::size_t NDIM> long FunctionIO< T, NDIM >::npts_per_box = simple_pow(k, ndims) private
The documentation for this class was generated from the following files:
FunctionIO.h
FunctionIO2.h
FunctionIOHDF5.h