MADNESS: CFFT Class Reference
CFFT Class Reference
#include <cfft.h>
Static Public Member Functions
static bool Forward (const double_complex *const Input, double_complex *const Output, const unsigned int N)
static bool Forward (double_complex *const Data, const unsigned int N)
static bool Inverse (const double_complex *const Input, double_complex *const Output, const unsigned int N, const bool Scale=true)
static bool Inverse (double_complex *const Data, const unsigned int N, const bool Scale=true)
Static Protected Member Functions
static void Perform (double_complex *const Data, const unsigned int N, const bool Inverse=false)
static void Rearrange (const double_complex *const Input, double_complex *const Output, const unsigned int N)
static void Rearrange (double_complex *const Data, const unsigned int N)
static void Scale (double_complex *const Data, const unsigned int N)
Member Function Documentation
Forward() [1/2]
bool CFFT::Forward (const double_complex *const Input, double_complex *const Output, const unsigned int N) static
References N, Perform(), and Rearrange().
Forward() [2/2]
bool CFFT::Forward (double_complex *const Data, const unsigned int N) static
References N, Perform(), and Rearrange().
Inverse() [1/2]
bool CFFT::Inverse (const double_complex *const Input, double_complex *const Output, const unsigned int N, const bool Scale = true) static
References N, Perform(), Rearrange(), and Scale().
Referenced by madness::BandlimitedPropagator::BandlimitedPropagator(), and Perform().
Inverse() [2/2]
bool CFFT::Inverse (double_complex *const Data, const unsigned int N, const bool Scale = true) static
References N, Perform(), Rearrange(), and Scale().
Perform()
void CFFT::Perform (double_complex *const Data, const unsigned int N, const bool Inverse = false) static protected
References delta, Inverse(), N, and pi.
Referenced by Forward(), Forward(), Inverse(), and Inverse().
Rearrange() [1/2]
void CFFT::Rearrange (const double_complex *const Input, double_complex *const Output, const unsigned int N) static protected
References N.
Referenced by Forward(), Forward(), Inverse(), and Inverse().
Rearrange() [2/2]
void CFFT::Rearrange (double_complex *const Data, const unsigned int N) static protected
References N.
Scale()
void CFFT::Scale (double_complex *const Data, const unsigned int N) static protected
References N.
Referenced by Inverse(), and Inverse().
The documentation for this class was generated from the following files:
cfft.h
cfft.cc