MADNESS: madness::XNonlinearSolver< T, C, Alloc > Class Template Reference
madness::XNonlinearSolver< T, C, Alloc > Class Template Reference
Mra » Simple Krylov-subspace nonlinear equation solver
Generalized version of NonlinearSolver not limited to a single madness function.
#include <nonlinsol.h>
Public Member Functions
XNonlinearSolver (const Alloc &alloc=Alloc(), bool print=false)
XNonlinearSolver (const XNonlinearSolver &other)
void clear_subspace ()
Tensor< C > get_c () const
std::vector< T > & get_plist ()
std::vector< T > & get_rlist ()
std::vector< T > & get_ulist ()
void initialize (const T &u_initial)
void set_maxsub (int maxsub)
T update (const T &u, const T &r, const double rcondtol=1e-8, const double cabsmax=1000.0)
Computes next trial solution vector.
T update (const T &u_preliminary, const double rcondtol=1e-8, const double cabsmax=1000.0)
Computes next trial solution vector.
Public Attributes
bool do_print
Private Attributes
Alloc alloc
Tensor< C > c
coefficients for linear combination
unsigned int maxsub
Maximum size of subspace dimension.
std::vector< T > plist
Subspace information.
Tensor< C > Q
std::vector< T > rlist
std::vector< T > ulist
Detailed Description
template<class T, class C = double, class Alloc = default_allocator<T>>
class madness::XNonlinearSolver< T, C, Alloc >
Generalized version of NonlinearSolver not limited to a single madness function.
This solves the equation where u and r are both of type T and inner products between two items of type T produce a number of type C (defaulting to double). The type T must support storage in an STL vector, scaling by a constant of type C, inplace addition (+=), subtraction, allocation with value zero, and inner products computed with the interface inner(a,b). Have a look in examples/testsolver.cc for a simple but complete example, and in examples/h2dynamic.cc for a more complex example.
I've not yet tested with anything except C=double and I think that the KAIN routine will need extending for anything else.
Constructor & Destructor Documentation
XNonlinearSolver() [1/2]
template<class T , class C = double, class Alloc = default_allocator<T>> madness::XNonlinearSolver< T, C, Alloc >::XNonlinearSolver (const Alloc & alloc = Alloc(), bool print = false) inline
XNonlinearSolver() [2/2]
template<class T , class C = double, class Alloc = default_allocator<T>> madness::XNonlinearSolver< T, C, Alloc >::XNonlinearSolver (const XNonlinearSolver< T, C, Alloc > & other) inline
Member Function Documentation
clear_subspace()
template<class T , class C = double, class Alloc = default_allocator<T>> void madness::XNonlinearSolver< T, C, Alloc >::clear_subspace () inline
References madness::XNonlinearSolver< T, C, Alloc >::plist, madness::XNonlinearSolver< T, C, Alloc >::Q, madness::XNonlinearSolver< T, C, Alloc >::rlist, and madness::XNonlinearSolver< T, C, Alloc >::ulist.
Referenced by madness::XNonlinearSolver< T, C, Alloc >::initialize(), iterate(), and madness::Zcis::iterate().
get_c()
template<class T , class C = double, class Alloc = default_allocator<T>> Tensor< C > madness::XNonlinearSolver< T, C, Alloc >::get_c () const inline
References madness::XNonlinearSolver< T, C, Alloc >::c.
get_plist()
template<class T , class C = double, class Alloc = default_allocator<T>> std::vector< T > & madness::XNonlinearSolver< T, C, Alloc >::get_plist () inline
References madness::XNonlinearSolver< T, C, Alloc >::plist.
get_rlist()
template<class T , class C = double, class Alloc = default_allocator<T>> std::vector< T > & madness::XNonlinearSolver< T, C, Alloc >::get_rlist () inline
References madness::XNonlinearSolver< T, C, Alloc >::rlist.
get_ulist()
template<class T , class C = double, class Alloc = default_allocator<T>> std::vector< T > & madness::XNonlinearSolver< T, C, Alloc >::get_ulist () inline
References madness::XNonlinearSolver< T, C, Alloc >::ulist.
initialize()
template<class T , class C = double, class Alloc = default_allocator<T>> void madness::XNonlinearSolver< T, C, Alloc >::initialize (const T & u_initial) inline
References madness::XNonlinearSolver< T, C, Alloc >::alloc, madness::XNonlinearSolver< T, C, Alloc >::clear_subspace(), madness::XNonlinearSolver< T, C, Alloc >::plist, and madness::XNonlinearSolver< T, C, Alloc >::ulist.
Referenced by test_with_function().
set_maxsub()
template<class T , class C = double, class Alloc = default_allocator<T>> void madness::XNonlinearSolver< T, C, Alloc >::set_maxsub (int maxsub) inline
References madness::XNonlinearSolver< T, C, Alloc >::maxsub.
Referenced by iterate(), run(), DF::solve_occupied(), and madness::PNO::t_solve().
update() [1/2]
template<class T , class C = double, class Alloc = default_allocator<T>> T madness::XNonlinearSolver< T, C, Alloc >::update (const T & u, const T & r, const double rcondtol = 1e-8, const double cabsmax = 1000.0) inline
Computes next trial solution vector.
You are responsible for performing step restriction or line search (not necessary for linear problems).
Parameters
u Current solution vector
r Corresponding residual
Returns
Next trial solution vector
Parameters
[in] rcondtol rcond less than this will cause the subspace to be shrunk due to linear dependence
[in] cabsmax maximum element of c greater than this will cause the subspace to be shrunk due to li
References madness::XNonlinearSolver< T, C, Alloc >::alloc, madness::XNonlinearSolver< T, C, Alloc >::c, madness::check_linear_dependence(), madness::copy(), madness::XNonlinearSolver< T, C, Alloc >::do_print, madness::inner(), madness::KAIN(), madness::XNonlinearSolver< T, C, Alloc >::maxsub, madness::print(), madness::XNonlinearSolver< T, C, Alloc >::Q, madness::XNonlinearSolver< T, C, Alloc >::rlist, T(), u(), and madness::XNonlinearSolver< T, C, Alloc >::ulist.
Referenced by iterate(), madness::Zcis::iterate(), madness::PNO::t_solve(), and test_with_function().
update() [2/2]
template<class T , class C = double, class Alloc = default_allocator<T>> T madness::XNonlinearSolver< T, C, Alloc >::update (const T & u_preliminary, const double rcondtol = 1e-8, const double cabsmax = 1000.0) inline
Computes next trial solution vector.
this version of update avoids using the residual by computing it on the fly note the distinction between u_preliminary (input) and u_kain (output) residual[i] = u_kain[i] - u_preliminary[i+1] ulist[i] = u_kain[i] plist[i] = u_preliminary[i]
Parameters
[in] u_preliminary new solution before KAIN
[out] u_kain new solution after KAIN
References madness::XNonlinearSolver< T, C, Alloc >::alloc, madness::XNonlinearSolver< T, C, Alloc >::c, madness::change_tree_state(), madness::check_linear_dependence(), madness::compressed, madness::copy(), madness::XNonlinearSolver< T, C, Alloc >::do_print, madness::inner(), madness::KAIN(), MADNESS_CHECK_THROW, madness::XNonlinearSolver< T, C, Alloc >::maxsub, p(), madness::XNonlinearSolver< T, C, Alloc >::plist, madness::print(), madness::XNonlinearSolver< T, C, Alloc >::Q, madness::reconstruct(), madness::reconstructed, madness::XNonlinearSolver< T, C, Alloc >::rlist, T(), madness::TT_FULL, u(), madness::XNonlinearSolver< T, C, Alloc >::ulist, madness::unknown, and v.
Member Data Documentation
alloc
template<class T , class C = double, class Alloc = default_allocator<T>> Alloc madness::XNonlinearSolver< T, C, Alloc >::alloc private
Referenced by madness::XNonlinearSolver< T, C, Alloc >::initialize(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
c
template<class T , class C = double, class Alloc = default_allocator<T>> Tensor<C> madness::XNonlinearSolver< T, C, Alloc >::c private
coefficients for linear combination
Referenced by madness::XNonlinearSolver< T, C, Alloc >::get_c(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
do_print
template<class T , class C = double, class Alloc = default_allocator<T>> bool madness::XNonlinearSolver< T, C, Alloc >::do_print
Referenced by iterate(), madness::PNO::t_solve(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
maxsub
template<class T , class C = double, class Alloc = default_allocator<T>> unsigned int madness::XNonlinearSolver< T, C, Alloc >::maxsub private
Maximum size of subspace dimension.
Referenced by madness::XNonlinearSolver< T, C, Alloc >::set_maxsub(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
plist
template<class T , class C = double, class Alloc = default_allocator<T>> std::vector<T> madness::XNonlinearSolver< T, C, Alloc >::plist private
Subspace information.
Referenced by madness::XNonlinearSolver< T, C, Alloc >::clear_subspace(), madness::XNonlinearSolver< T, C, Alloc >::get_plist(), madness::XNonlinearSolver< T, C, Alloc >::initialize(), and madness::XNonlinearSolver< T, C, Alloc >::update().
Q
template<class T , class C = double, class Alloc = default_allocator<T>> Tensor<C> madness::XNonlinearSolver< T, C, Alloc >::Q private
Referenced by madness::XNonlinearSolver< T, C, Alloc >::clear_subspace(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
rlist
template<class T , class C = double, class Alloc = default_allocator<T>> std::vector<T> madness::XNonlinearSolver< T, C, Alloc >::rlist private
Referenced by madness::XNonlinearSolver< T, C, Alloc >::clear_subspace(), madness::XNonlinearSolver< T, C, Alloc >::get_rlist(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
ulist
template<class T , class C = double, class Alloc = default_allocator<T>> std::vector<T> madness::XNonlinearSolver< T, C, Alloc >::ulist private
Referenced by madness::XNonlinearSolver< T, C, Alloc >::clear_subspace(), madness::XNonlinearSolver< T, C, Alloc >::get_ulist(), madness::XNonlinearSolver< T, C, Alloc >::initialize(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
The documentation for this class was generated from the following file:
nonlinsol.h