MADNESS: madness::LowRankFunctionFactory< T, NDIM, LDIM > Class Template Reference
madness::LowRankFunctionFactory< T, NDIM, LDIM > Class Template Reference
#include <lowrankfunction.h>
Public Member Functions
LowRankFunctionFactory ()=default
LowRankFunctionFactory (const LowRankFunctionFactory &other)=default
LowRankFunctionFactory (const LowRankFunctionParameters param, const Molecule &molecule)
LowRankFunctionFactory (const LowRankFunctionParameters param, const std::vector< Vector< double, LDIM > > origins={})
LowRankFunction< T, NDIM > project (const LRFunctorBase< T, NDIM > &lrfunctor) const
LowRankFunctionFactory & set_orthomethod (const std::string orthomethod)
LowRankFunctionFactory & set_radius (const double radius)
LowRankFunctionFactory & set_rank_revealing_tol (const double rrtol)
LowRankFunctionFactory & set_volume_element (const double volume_element)
std::vector< Function< T, LDIM > > Yformer (const LRFunctorBase< T, NDIM > &lrfunctor1, const std::vector< Vector< double, LDIM > > &grid, const std::string rhsfunctiontype, const double exponent=30.0) const
apply a rhs (delta or exponential) on grid points to the hi-dim function and form Y = A_ij w_j (in Halko's language)
Public Attributes
std::vector< Vector< double, LDIM > > origins
origins of the molecular grid
const particle< LDIM > p1 =particle<LDIM>::particle1()
const particle< LDIM > p2 =particle<LDIM>::particle2()
LowRankFunctionParameters parameters
Constructor & Destructor Documentation
LowRankFunctionFactory() [1/4]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunctionFactory< T, NDIM, LDIM >::LowRankFunctionFactory () default
LowRankFunctionFactory() [2/4]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunctionFactory< T, NDIM, LDIM >::LowRankFunctionFactory (const LowRankFunctionParameters param, const std::vector< Vector< double, LDIM > > origins = {}) inline
LowRankFunctionFactory() [3/4]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunctionFactory< T, NDIM, LDIM >::LowRankFunctionFactory (const LowRankFunctionParameters param, const Molecule & molecule) inline
LowRankFunctionFactory() [4/4]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunctionFactory< T, NDIM, LDIM >::LowRankFunctionFactory (const LowRankFunctionFactory< T, NDIM, LDIM > & other) default
Member Function Documentation
project()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction< T, NDIM > madness::LowRankFunctionFactory< T, NDIM, LDIM >::project (const LRFunctorBase< T, NDIM > & lrfunctor) const inline
References madness::timer::do_print, madness::g, madness::molecular_grid< NDIM >::get_grid(), madness::get_size(), madness::grid(), h(), madness::inner(), madness::matrix_inner(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::origins, madness::LowRankFunctionParameters::orthomethod(), madness::orthonormalize_rrcd(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::p1, madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters, madness::print(), madness::World::rank(), madness::LowRankFunctionParameters::rhsfunctiontype(), madness::timer::tag(), madness::LowRankFunctionParameters::tol(), madness::truncate(), madness::LRFunctorBase< T, NDIM, LDIM >::world(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer().
Referenced by test_arithmetic(), test_construction_optimization(), test_full_rank_functor(), test_inner(), test_Kcommutator(), test_lowrank_function(), and test_molecular_grid().
set_orthomethod()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunctionFactory & madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_orthomethod (const std::string orthomethod) inline
References madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters, and madness::QCCalculationParametersBase::set_user_defined_value().
Referenced by test_arithmetic(), test_full_rank_functor(), and test_inner().
set_radius()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunctionFactory & madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_radius (const double radius) inline
References madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters, and madness::QCCalculationParametersBase::set_user_defined_value().
Referenced by test_arithmetic(), test_full_rank_functor(), and test_inner().
set_rank_revealing_tol()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunctionFactory & madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_rank_revealing_tol (const double rrtol) inline
References madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters, and madness::QCCalculationParametersBase::set_user_defined_value().
Referenced by test_arithmetic(), test_full_rank_functor(), and test_inner().
set_volume_element()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunctionFactory & madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_volume_element (const double volume_element) inline
References madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters, and madness::QCCalculationParametersBase::set_user_defined_value().
Referenced by test_arithmetic(), test_full_rank_functor(), and test_inner().
Yformer()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer (const LRFunctorBase< T, NDIM > & lrfunctor1, const std::vector< Vector< double, LDIM > > & grid, const std::string rhsfunctiontype, const double exponent = 30.0) const inline
apply a rhs (delta or exponential) on grid points to the hi-dim function and form Y = A_ij w_j (in Halko's language)
References madness::FunctionFactory< T, NDIM >::functor(), madness::grid(), madness::inner(), MADNESS_EXCEPTION, madness::norm2s(), madness::normalize(), omega, madness::LowRankFunctionFactory< T, NDIM, LDIM >::p1, madness::LowRankFunctionFactory< T, NDIM, LDIM >::p2, madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters, madness::constants::pi, madness::LowRankFunctionParameters::tol(), and madness::LRFunctorBase< T, NDIM, LDIM >::world().
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project().
Member Data Documentation
origins
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector<Vector<double,LDIM> > madness::LowRankFunctionFactory< T, NDIM, LDIM >::origins
origins of the molecular grid
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project().
p1
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> const particle<LDIM> madness::LowRankFunctionFactory< T, NDIM, LDIM >::p1 =particle<LDIM>::particle1()
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer().
p2
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> const particle<LDIM> madness::LowRankFunctionFactory< T, NDIM, LDIM >::p2 =particle<LDIM>::particle2()
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer().
parameters
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunctionParameters madness::LowRankFunctionFactory< T, NDIM, LDIM >::parameters
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_orthomethod(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_radius(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_rank_revealing_tol(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_volume_element(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer().
The documentation for this class was generated from the following file:
lowrankfunction.h