MADNESS: GroundStateCalculation Class Reference
GroundStateCalculation Class Reference
#include <ground_parameters.h>
Public Member Functions
GroundStateCalculation (const GroundStateCalculation &other)=default
GroundStateCalculation (World &world)
GroundStateCalculation (World &world, std::string input_file)
std::string get_archive () const
Tensor< double > get_energies () const
int get_k () const
double get_L () const
std::string get_localize_method () const
Tensor< double > get_occ () const
std::string get_xc () const
bool is_spinrestricted () const
Molecule molecule () const
unsigned int n_orbitals () const
vector_real_function_3d & orbitals ()
void print_params () const
void read (World &world)
Private Attributes
double converged_for_thresh {}
Convergence threshold used in ground state calculation.
Tensor< double > energies {}
Energy of ground state orbitals.
std::vector< real_function_3d > g_orbitals {}
The ground state orbitals.
std::string inFile {"../moldft.restartdata"}
Name of input archive to read in ground state.
int k {}
Order of polynomial used in ground state.
double L {}
Box size of ground state - response calcluation is in same box.
std::string localize_method {}
Name of localization method used in ground state.
Molecule molecule_in {}
The molecule used in ground state calculation.
unsigned int num_orbitals {}
Number of orbitals in ground state.
Tensor< double > occ {}
Occupancy of ground state orbitals.
bool spinrestricted {true}
Indicates if ground state calc. was open or closed shell.
std::string xc {}
Name of xc functional used in ground state.
Constructor & Destructor Documentation
GroundStateCalculation() [1/3]
GroundStateCalculation::GroundStateCalculation (World & world) inline explicit
References read().
GroundStateCalculation() [2/3]
GroundStateCalculation::GroundStateCalculation (World & world, std::string input_file) inline explicit
References read().
GroundStateCalculation() [3/3]
GroundStateCalculation::GroundStateCalculation (const GroundStateCalculation & other) default
Member Function Documentation
get_archive()
std::string GroundStateCalculation::get_archive () const inline
References xc.
get_energies()
Tensor< double > GroundStateCalculation::get_energies () const inline
References energies.
get_k()
int GroundStateCalculation::get_k () const inline
References k.
get_L()
double GroundStateCalculation::get_L () const inline
References L.
Referenced by madness::ResponseParameters::set_ground_state_calculation_data().
get_localize_method()
std::string GroundStateCalculation::get_localize_method () const inline
References localize_method.
Referenced by madness::ResponseParameters::set_ground_state_calculation_data().
get_occ()
Tensor< double > GroundStateCalculation::get_occ () const inline
References occ.
get_xc()
std::string GroundStateCalculation::get_xc () const inline
References xc.
Referenced by madness::ResponseParameters::set_ground_state_calculation_data().
is_spinrestricted()
bool GroundStateCalculation::is_spinrestricted () const inline
References spinrestricted.
Referenced by madness::ResponseParameters::set_ground_state_calculation_data().
molecule()
Molecule GroundStateCalculation::molecule () const inline
References molecule_in.
Referenced by madness::ResponseParameters::set_ground_state_calculation_data().
n_orbitals()
unsigned int GroundStateCalculation::n_orbitals () const inline
References num_orbitals.
Referenced by madness::ResponseParameters::set_ground_state_calculation_data().
orbitals()
vector_real_function_3d & GroundStateCalculation::orbitals () inline
References g_orbitals.
print_params()
void GroundStateCalculation::print_params () const inline
References energies, inFile, k, L, localize_method, num_orbitals, madness::print(), spinrestricted, and xc.
read()
void GroundStateCalculation::read (World & world) inline
References converged_for_thresh, energies, madness::WorldGopInterface::fence(), g_orbitals, madness::World::gop, inFile, k, L, localize_method, molecule_in, num_orbitals, occ, madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_k(), spinrestricted, madness::truncate(), and xc.
Referenced by GroundStateCalculation(), and GroundStateCalculation().
Member Data Documentation
converged_for_thresh
double GroundStateCalculation::converged_for_thresh {} private
Convergence threshold used in ground state calculation.
Referenced by read().
energies
Tensor<double> GroundStateCalculation::energies {} private
Energy of ground state orbitals.
Referenced by get_energies(), print_params(), and read().
g_orbitals
std::vector<real_function_3d> GroundStateCalculation::g_orbitals {} private
The ground state orbitals.
Referenced by orbitals(), and read().
inFile
std::string GroundStateCalculation::inFile {"../moldft.restartdata"} private
Name of input archive to read in ground state.
Referenced by print_params(), and read().
k
int GroundStateCalculation::k {} private
Order of polynomial used in ground state.
Referenced by get_k(), print_params(), and read().
L
double GroundStateCalculation::L {} private
Box size of ground state - response calcluation is in same box.
Referenced by get_L(), print_params(), and read().
localize_method
std::string GroundStateCalculation::localize_method {} private
Name of localization method used in ground state.
Referenced by get_localize_method(), print_params(), and read().
molecule_in
Molecule GroundStateCalculation::molecule_in {} private
The molecule used in ground state calculation.
Referenced by molecule(), and read().
num_orbitals
unsigned int GroundStateCalculation::num_orbitals {} private
Number of orbitals in ground state.
Referenced by n_orbitals(), print_params(), and read().
occ
Tensor<double> GroundStateCalculation::occ {} private
Occupancy of ground state orbitals.
Referenced by get_occ(), and read().
spinrestricted
bool GroundStateCalculation::spinrestricted {true} private
Indicates if ground state calc. was open or closed shell.
Referenced by is_spinrestricted(), print_params(), and read().
xc
std::string GroundStateCalculation::xc {} private
Name of xc functional used in ground state.
Referenced by get_archive(), get_xc(), print_params(), and read().
The documentation for this class was generated from the following file:
ground_parameters.h