MADNESS: SVPESolver Class Reference
SVPESolver Class Reference
Public Member Functions
SVPESolver (World &world, double sigma, double epsilon_0, double epsilon_1, const vector_real &atomic_radii, const vector_coord_3d &atomic_coords, const double minlen)
real_function_3d make_surface_charge (const real_function_3d &u) const
Given the full Coulomb potential computes the surface charge.
real_function_3d solve (const real_function_3d &rho, const real_function_3d uguess=real_function_3d(), bool printing=true) const
Solve for the full Coulomb potential using the free-particle GF.
Private Attributes
vector_real_function_3d dlog
const double epsilon_0
const double epsilon_1
const double minlen
real_convolution_3d op
real_function_3d rdielectric
const double sigma
const double thresh
Constructor & Destructor Documentation
SVPESolver()
SVPESolver::SVPESolver (World & world, double sigma, double epsilon_0, double epsilon_1, const vector_real & atomic_radii, const vector_coord_3d & atomic_coords, const double minlen) inline
References dlog, epsilon_0, epsilon_1, madness::constants::pi, rdielectric, madness::scale(), sigma, madness::Function< T, NDIM >::truncate(), and madness::truncate().
Member Function Documentation
make_surface_charge()
real_function_3d SVPESolver::make_surface_charge (const real_function_3d & u) const inline
Given the full Coulomb potential computes the surface charge.
References dlog, and u().
Referenced by main(), and solve().
solve()
real_function_3d SVPESolver::solve (const real_function_3d & rho, const real_function_3d uguess = real_function_3d(), bool printing = true) const inline
Solve for the full Coulomb potential using the free-particle GF.
References madness::Function< T, NDIM >::clear(), e(), madness::Function< T, NDIM >::is_initialized(), make_surface_charge(), madness::Function< T, NDIM >::norm2(), madness::norm2(), op, madness::print(), rdielectric, thresh, madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), madness::truncate(), u(), and madness::wall_time().
Referenced by main().
Member Data Documentation
dlog
vector_real_function_3d SVPESolver::dlog private
Referenced by SVPESolver(), and make_surface_charge().
epsilon_0
const double SVPESolver::epsilon_0 private
Referenced by SVPESolver().
epsilon_1
const double SVPESolver::epsilon_1 private
Referenced by SVPESolver().
minlen
const double SVPESolver::minlen private
op
real_convolution_3d SVPESolver::op private
Referenced by solve().
rdielectric
real_function_3d SVPESolver::rdielectric private
Referenced by SVPESolver(), and solve().
sigma
const double SVPESolver::sigma private
Referenced by SVPESolver().
thresh
const double SVPESolver::thresh private
Referenced by solve().
The documentation for this class was generated from the following file:
svpe.cc