MADNESS: madness::MP3 Class Reference
madness::MP3 Class Reference
#include <mp3.h>
Classes
class MacroTaskMP3
helper class for calculating the MP3 energy contributions
Public Member Functions
MP3 (World &world, const Info &info)
double mp3_energy_contribution (const Pairs< CCPair > &mp2pairs) const
double mp3_energy_contribution_macrotask_driver (const Pairs< CCPair > &mp2pairs) const
compute the MP3 energy contribution, macrotask version
Private Member Functions
double compute_mp3_cd (const Pairs< CCPair > &mp2pairs, const Info &info) const
double compute_mp3_ef (const Pairs< CCPair > &mp2pairs, const Info &info) const
double compute_mp3_ef_as_overlap (const Pairs< CCPair > &mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info &info) const
double compute_mp3_ef_low_scaling (const Pairs< CCPair > &mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info &info) const
double compute_mp3_ef_with_permutational_symmetry (const Pairs< CCPair > &mp2pairs, const Info &info) const
compute the EF term of the MP3 energy with permutational symmetry
double compute_mp3_ghij (const Pairs< CCPair > &mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info &info) const
double compute_mp3_ghij_fast (const Pairs< CCPair > &mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info &info) const
double compute_mp3_klmn (const Pairs< CCPair > &mp2pairs, const Info &info) const
double compute_mp3_klmn_fast (const Pairs< CCPair > &mp2pairs, const Info &info) const
double mp3_test (const Pairs< CCPair > &mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info &info) const
Static Private Member Functions
static double compute_mp3_cd (World &world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > &pair_square, const Info &info, const std::vector< std::string > &argument)
compute the cd term for single pair ij
static double compute_mp3_ef (World &world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > &pair_square, const Info &info, const std::vector< std::string > &argument)
compute the ef term for single pair ij
static double compute_mp3_ghij (World &world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > &pair_square, const Info &info, const std::vector< std::string > &argument)
static double compute_mp3_klmn (World &world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > &pair_square, const Info &info, const std::vector< std::string > &argument)
compute the klmn term for single pair ij
Private Attributes
const Info & info
World & world
Constructor & Destructor Documentation
MP3()
madness::MP3::MP3 (World & world, const Info & info) inline
Member Function Documentation
compute_mp3_cd() [1/2]
double madness::MP3::compute_mp3_cd (const Pairs< CCPair > & mp2pairs, const Info & info) const private
References madness::CCParameters::freeze(), info, madness::inner(), madness::Info::mo_ket, madness::OT_G12, madness::Info::parameters, madness::print(), madness::print_header3(), R2, madness::Info::R_square, and world.
Referenced by mp3_energy_contribution(), and madness::MP3::MacroTaskMP3::operator()().
compute_mp3_cd() [2/2]
double madness::MP3::compute_mp3_cd (World & world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > & pair_square, const Info & info, const std::vector< std::string > & argument) static private
compute the cd term for single pair ij
References bufsize, info, madness::inner(), madness::OT_G12, madness::Info::parameters, madness::print(), madness::Info::R_square, and world.
compute_mp3_ef() [1/2]
double madness::MP3::compute_mp3_ef (const Pairs< CCPair > & mp2pairs, const Info & info) const private
References madness::CCParameters::freeze(), info, madness::inner(), k, madness::Info::mo_bra, madness::Info::mo_ket, madness::OT_G12, madness::Info::parameters, madness::print_header3(), R2, madness::Info::R_square, and world.
Referenced by madness::MP3::MacroTaskMP3::operator()().
compute_mp3_ef() [2/2]
double madness::MP3::compute_mp3_ef (World & world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > & pair_square, const Info & info, const std::vector< std::string > & argument) static private
compute the ef term for single pair ij
<ij | kl > = (ik | jl)
References bufsize, madness::CCParameters::freeze(), info, madness::inner(), k, madness::permutation::make_all_tau_permutations(), madness::Info::mo_bra, madness::Info::mo_ket, madness::OT_G12, madness::Info::parameters, madness::print(), madness::Info::R_square, madness::timer::tag(), weight(), and world.
compute_mp3_ef_as_overlap()
double madness::MP3::compute_mp3_ef_as_overlap (const Pairs< CCPair > & mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info & info) const private
compute_mp3_ef_low_scaling()
double madness::MP3::compute_mp3_ef_low_scaling (const Pairs< CCPair > & mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info & info) const private
<ij | kl > = (ik | jl)
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), info, madness::inner(), madness::timer::interrupt(), k, madness::Info::mo_bra, madness::Info::mo_ket, madness::OT_G12, madness::Info::parameters, madness::timer::print(), madness::print_header3(), R2, madness::Info::R_square, madness::timer::resume(), sigma, and world.
compute_mp3_ef_with_permutational_symmetry()
double madness::MP3::compute_mp3_ef_with_permutational_symmetry (const Pairs< CCPair > & mp2pairs, const Info & info) const private
compute the EF term of the MP3 energy with permutational symmetry
there is the usual 8-fold permutational symmetry for 2-electron integrals <ij | kl > = <ji | lk > = <kj | il > = < il | kj > = <kl | ij> = <lk | ji > = <il | kj > = < kj | il > implemented as loop over (ij) = \sum_i<j and (ij) < (kl)
<ij | kl > = (ik | jl)
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), ij(), info, madness::inner(), k, MADNESS_CHECK_THROW, madness::permutation::make_all_tau_permutations(), madness::PairVectorMap::map, madness::Info::mo_bra, madness::Info::mo_ket, madness::OT_G12, p(), madness::Info::parameters, madness::print_header3(), R2, madness::Info::R_square, madness::permutation::remove_duplicates(), madness::PairVectorMap::triangular_map(), weight(), and world.
Referenced by mp3_energy_contribution().
compute_mp3_ghij() [1/2]
double madness::MP3::compute_mp3_ghij (const Pairs< CCPair > & mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info & info) const private
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), madness::g, I, info, madness::inner(), madness::Info::mo_bra, madness::Info::mo_ket, madness::multiply(), madness::OT_G12, madness::Info::parameters, madness::print(), R2, madness::Info::R_square, madness::timer::tag(), and world.
Referenced by madness::MP3::MacroTaskMP3::operator()().
compute_mp3_ghij() [2/2]
double madness::MP3::compute_mp3_ghij (World & world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > & pair_square, const Info & info, const std::vector< std::string > & argument) static private
compute the ghij term for single pair ij
the term actually scales linearly with the number of occupied orbitals i, so for all i!=j return zero
References bufsize, madness::CCParameters::freeze(), madness::g, info, madness::inner(), madness::Info::mo_bra, madness::Info::mo_ket, madness::Info::molecular_coordinates, madness::multiply(), madness::OT_G12, madness::Info::parameters, madness::print(), madness::print_header3(), madness::Info::R_square, madness::SeparatedConvolution< Q, NDIM >::set_particle(), madness::timer::tag(), and world.
compute_mp3_ghij_fast()
double madness::MP3::compute_mp3_ghij_fast (const Pairs< CCPair > & mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info & info) const private
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), madness::g, info, madness::inner(), madness::Info::mo_bra, madness::Info::mo_ket, madness::Info::molecular_coordinates, madness::multiply(), madness::OT_G12, madness::Info::parameters, madness::print(), madness::print_header3(), R2, madness::Info::R_square, madness::SeparatedConvolution< Q, NDIM >::set_particle(), madness::timer::tag(), and world.
Referenced by mp3_energy_contribution().
compute_mp3_klmn() [1/2]
double madness::MP3::compute_mp3_klmn (const Pairs< CCPair > & mp2pairs, const Info & info) const private
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), info, madness::inner(), madness::Pairs< T >::insert(), madness::timer::interrupt(), k, K(), L, madness::Info::mo_bra, madness::Info::mo_ket, madness::multiply(), N, madness::OT_G12, madness::Info::parameters, madness::timer::print(), R2, madness::Info::R_square, madness::timer::resume(), and world.
Referenced by madness::MP3::MacroTaskMP3::operator()().
compute_mp3_klmn() [2/2]
double madness::MP3::compute_mp3_klmn (World & world, const long i, const long j, const Pairs< std::vector< CCPairFunction< double, 6 > > > & pair_square, const Info & info, const std::vector< std::string > & argument) static private
compute the klmn term for single pair ij
References bufsize, madness::CCParameters::freeze(), info, madness::inner(), madness::Pairs< T >::insert(), madness::timer::interrupt(), k, madness::Info::mo_bra, madness::Info::mo_ket, madness::multiply(), madness::OT_G12, madness::Info::parameters, madness::timer::print(), madness::print(), madness::print_header3(), madness::Info::R_square, madness::timer::resume(), and world.
compute_mp3_klmn_fast()
double madness::MP3::compute_mp3_klmn_fast (const Pairs< CCPair > & mp2pairs, const Info & info) const private
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), info, madness::inner(), madness::Pairs< T >::insert(), madness::timer::interrupt(), k, madness::Info::mo_bra, madness::Info::mo_ket, madness::multiply(), madness::OT_G12, madness::Info::parameters, madness::timer::print(), R2, madness::Info::R_square, madness::timer::resume(), and world.
Referenced by mp3_energy_contribution().
mp3_energy_contribution()
double madness::MP3::mp3_energy_contribution (const Pairs< CCPair > & mp2pairs) const
References madness::Pairs< T >::allpairs, compute_mp3_cd(), compute_mp3_ef_with_permutational_symmetry(), compute_mp3_ghij_fast(), compute_mp3_klmn_fast(), madness::CCParameters::freeze(), info, madness::Info::mo_ket, madness::Info::parameters, madness::print(), madness::print_header2(), madness::timer::tag(), and world.
mp3_energy_contribution_macrotask_driver()
double madness::MP3::mp3_energy_contribution_macrotask_driver (const Pairs< CCPair > & mp2pairs) const
compute the MP3 energy contribution, macrotask version
References madness::Pairs< T >::allpairs, madness::CCParameters::freeze(), function(), info, madness::Info::mo_ket, madness::Info::parameters, madness::print(), madness::print_header2(), madness::PairVectorMap::quadratic_map(), madness::World::rank(), madness::timer::tag(), and world.
Referenced by madness::CC2::compute_mp3().
mp3_test()
double madness::MP3::mp3_test (const Pairs< CCPair > & mp2pairs, const Pairs< std::vector< CCPairFunction< double, 6 > > > clusterfunctions, const Info & info) const private
References madness::Pairs< T >::allpairs, ij(), info, madness::inner(), madness::Info::mo_bra, madness::Info::mo_ket, madness::OT_G12, madness::print(), madness::print_header2(), R2, madness::Info::R_square, and world.
Member Data Documentation
info
const Info& madness::MP3::info private
Referenced by compute_mp3_cd(), compute_mp3_cd(), compute_mp3_ef(), compute_mp3_ef(), compute_mp3_ef_low_scaling(), compute_mp3_ef_with_permutational_symmetry(), compute_mp3_ghij(), compute_mp3_ghij(), compute_mp3_ghij_fast(), compute_mp3_klmn(), compute_mp3_klmn(), compute_mp3_klmn_fast(), mp3_energy_contribution(), mp3_energy_contribution_macrotask_driver(), mp3_test(), and madness::MP3::MacroTaskMP3::operator()().
world
World& madness::MP3::world private
Referenced by madness::MP3::MacroTaskMP3::allocator(), compute_mp3_cd(), compute_mp3_cd(), compute_mp3_ef(), compute_mp3_ef(), compute_mp3_ef_low_scaling(), compute_mp3_ef_with_permutational_symmetry(), compute_mp3_ghij(), compute_mp3_ghij(), compute_mp3_ghij_fast(), compute_mp3_klmn(), compute_mp3_klmn(), compute_mp3_klmn_fast(), mp3_energy_contribution(), mp3_energy_contribution_macrotask_driver(), mp3_test(), and madness::MP3::MacroTaskMP3::operator()().
The documentation for this class was generated from the following files:
mp3.h
mp3.cc