MADNESS: madness::BSHApply< T, NDIM > Class Template Reference
madness::BSHApply< T, NDIM > Class Template Reference
apply the BSH operator on a vector of functions with corresponding potentials
#include <BSHApply.h>
Public Types
enum return_value { update , residual }
Public Member Functions
BSHApply (World &world)
std::vector< Function< T, NDIM > > add_coupling_and_levelshift (const std::vector< Function< T, NDIM > > psi, const Tensor< T > fock1) const
double eps_in_green (const T eps) const
limit the orbital energy (diagonal fock matrix element) entering the Green's function parameter mu
std::vector< Function< T, NDIM > > make_bra (const std::vector< Function< T, NDIM > > &rhs) const
MolecularOrbitals< T, NDIM > operator() (const MolecularOrbitals< T, NDIM > &arg, const std::vector< Function< T, NDIM > > &Vpsi) const
apply the BSH operator on the vector of functions and respective potentials
std::tuple< std::vector< Function< T, NDIM > >, Tensor< double > > operator() (const std::vector< Function< T, NDIM > > psi, const Tensor< T > eps, const std::vector< Function< T, NDIM > > &Vpsi1) const
apply the BSH operator on the vector of functions and respective potentials
Public Attributes
double bshtol =1.e-5
bool destroy_Vpsi =false
double levelshift =0.0
double lo =1.e-6
Function< double, NDIM > metric
bool printme =false
return_value ret_value =residual
World & world
Detailed Description
template<typename T, std::size_t NDIM>
class madness::BSHApply< T, NDIM >
apply the BSH operator on a vector of functions with corresponding potentials
this class
constructs the bsh operator with the appropriate exponents
performs a level shift if necessary
adds coupling terms: (T - fock(i,i)) psi_i = -V psi_i + \sum_{j\neq i} psi_j fock(j,i) TODO: adding a level shift seems to make the operation less precise, why??
Member Enumeration Documentation
return_value
template<typename T , std::size_t NDIM> enum madness::BSHApply::return_value
Enumerator
update
residual
Constructor & Destructor Documentation
BSHApply()
template<typename T , std::size_t NDIM> madness::BSHApply< T, NDIM >::BSHApply (World & world) inline
References madness::BSHApply< T, NDIM >::bshtol, madness::BSHApply< T, NDIM >::printme, madness::World::rank(), and madness::BSHApply< T, NDIM >::world.
Member Function Documentation
add_coupling_and_levelshift()
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::BSHApply< T, NDIM >::add_coupling_and_levelshift (const std::vector< Function< T, NDIM > > psi, const Tensor< T > fock1) const inline
References madness::copy(), madness::BaseTensor::dim(), madness::BSHApply< T, NDIM >::eps_in_green(), MADNESS_EXCEPTION, madness::BaseTensor::ndim(), madness::print(), madness::BSHApply< T, NDIM >::printme, psi(), madness::scale(), madness::transform(), and madness::BSHApply< T, NDIM >::world.
Referenced by madness::BSHApply< T, NDIM >::operator()().
eps_in_green()
template<typename T , std::size_t NDIM> double madness::BSHApply< T, NDIM >::eps_in_green (const T eps) const inline
limit the orbital energy (diagonal fock matrix element) entering the Green's function parameter mu
References madness::BSHApply< T, NDIM >::levelshift, and MADNESS_EXCEPTION.
Referenced by madness::BSHApply< T, NDIM >::add_coupling_and_levelshift(), and madness::BSHApply< T, NDIM >::operator()().
make_bra()
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::BSHApply< T, NDIM >::make_bra (const std::vector< Function< T, NDIM > > & rhs) const inline
References madness::Function< T, NDIM >::is_initialized(), and madness::BSHApply< T, NDIM >::metric.
Referenced by madness::BSHApply< T, NDIM >::operator()().
operator()() [1/2]
template<typename T , std::size_t NDIM> MolecularOrbitals< T, NDIM > madness::BSHApply< T, NDIM >::operator() (const MolecularOrbitals< T, NDIM > & arg, const std::vector< Function< T, NDIM > > & Vpsi) const inline
apply the BSH operator on the vector of functions and respective potentials
Parameters
[in] arg the MO structure holding MOs and orbital energies
[in] Vpsi vector of functions V*MOs
Returns
an MO structure holding the residuals and the orbital energy updates
References madness::arg(), madness::MolecularOrbitals< T, NDIM >::get_mos(), and madness::BSHApply< T, NDIM >::operator()().
operator()() [2/2]
template<typename T , std::size_t NDIM> std::tuple< std::vector< Function< T, NDIM > >, Tensor< double > > madness::BSHApply< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > psi, const Tensor< T > eps, const std::vector< Function< T, NDIM > > & Vpsi1) const inline
apply the BSH operator on the vector of functions and respective potentials
Parameters
[in] eps orbital energies or the square fock matrix
[in] Vpsi vector of functions V*MOs
Returns
an MO structure holding the residuals and the orbital energy updates
References madness::BSHApply< T, NDIM >::add_coupling_and_levelshift(), madness::apply(), madness::BSHApply< T, NDIM >::bshtol, madness::copy(), madness::cpu_time(), madness::BaseTensor::dim(), madness::BSHApply< T, NDIM >::eps_in_green(), madness::inner(), madness::BSHApply< T, NDIM >::lo, MADNESS_EXCEPTION, madness::BSHApply< T, NDIM >::make_bra(), madness::BaseTensor::ndim(), madness::print(), madness::BSHApply< T, NDIM >::printme, psi(), madness::real(), madness::BSHApply< T, NDIM >::residual, madness::BSHApply< T, NDIM >::ret_value, madness::BaseTensor::size(), T(), madness::truncate(), madness::BSHApply< T, NDIM >::update, and madness::BSHApply< T, NDIM >::world.
Referenced by madness::BSHApply< T, NDIM >::operator()().
Member Data Documentation
bshtol
template<typename T , std::size_t NDIM> double madness::BSHApply< T, NDIM >::bshtol =1.e-5
Referenced by madness::BSHApply< T, NDIM >::BSHApply(), and madness::BSHApply< T, NDIM >::operator()().
destroy_Vpsi
template<typename T , std::size_t NDIM> bool madness::BSHApply< T, NDIM >::destroy_Vpsi =false
levelshift
template<typename T , std::size_t NDIM> double madness::BSHApply< T, NDIM >::levelshift =0.0
Referenced by madness::BSHApply< T, NDIM >::eps_in_green(), madness::OEP::iterate(), madness::Nemo::solve(), test_converged_function(), and test_convergence().
lo
template<typename T , std::size_t NDIM> double madness::BSHApply< T, NDIM >::lo =1.e-6
Referenced by madness::OEP::iterate(), madness::BSHApply< T, NDIM >::operator()(), and madness::Nemo::solve().
metric
template<typename T , std::size_t NDIM> Function<double,NDIM> madness::BSHApply< T, NDIM >::metric
Referenced by madness::OEP::iterate(), madness::BSHApply< T, NDIM >::make_bra(), and madness::Nemo::solve().
printme
template<typename T , std::size_t NDIM> bool madness::BSHApply< T, NDIM >::printme =false
Referenced by madness::BSHApply< T, NDIM >::BSHApply(), madness::BSHApply< T, NDIM >::add_coupling_and_levelshift(), and madness::BSHApply< T, NDIM >::operator()().
ret_value
template<typename T , std::size_t NDIM> return_value madness::BSHApply< T, NDIM >::ret_value =residual
Referenced by madness::BSHApply< T, NDIM >::operator()(), and madness::Nemo::solve().
world
template<typename T , std::size_t NDIM> World& madness::BSHApply< T, NDIM >::world
Referenced by madness::BSHApply< T, NDIM >::BSHApply(), madness::BSHApply< T, NDIM >::add_coupling_and_levelshift(), and madness::BSHApply< T, NDIM >::operator()().
The documentation for this class was generated from the following file:
BSHApply.h