MADNESS: madness::BasisFunctions::SolidHarmonicGaussian Class Reference
madness::BasisFunctions::SolidHarmonicGaussian Class Reference
#include <PNOGuessFunctions.h>
Public Member Functions
SolidHarmonicGaussian (const Atom &atom, const double e, int l, int m)
double operator() (const coord_3d &xyz) const
template<typename T >
int sgn (T val) const
Level special_level () const final
Override this to change the minimum level of refinement at special points (default is 6)
std::vector< coord_3d > special_points () const final
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Public Attributes
double exponent
exponent
int l
int m
(real) solid harmonic quanta
double x
double y
double z
origin
double Z
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Detailed Description
real solid harmonic Gaussian
Note
see https://en.wikipedia.org/wiki/Spherical_harmonics and https://en.wikipedia.org/wiki/Solid_harmonics
Constructor & Destructor Documentation
SolidHarmonicGaussian()
madness::BasisFunctions::SolidHarmonicGaussian::SolidHarmonicGaussian (const Atom & atom, const double e, int l, int m) inline
Member Function Documentation
operator()()
double madness::BasisFunctions::SolidHarmonicGaussian::operator() (const coord_3d & xyz) const
References std::abs(), exponent, l, m, MADNESS_EXCEPTION, pow(), madness::r2(), x, y, and z.
sgn()
template<typename T > int madness::BasisFunctions::SolidHarmonicGaussian::sgn (T val) const inline
References T().
special_level()
Level madness::BasisFunctions::SolidHarmonicGaussian::special_level () const inline final virtual
Override this to change the minimum level of refinement at special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References exponent, and madness::FunctionDefaults< NDIM >::set_length_scale().
special_points()
std::vector< coord_3d > madness::BasisFunctions::SolidHarmonicGaussian::special_points () const inline final virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References x, y, and z.
Member Data Documentation
exponent
double madness::BasisFunctions::SolidHarmonicGaussian::exponent
exponent
Referenced by operator()(), and special_level().
l
int madness::BasisFunctions::SolidHarmonicGaussian::l
Referenced by operator()().
m
int madness::BasisFunctions::SolidHarmonicGaussian::m
(real) solid harmonic quanta
Referenced by operator()().
x
double madness::BasisFunctions::SolidHarmonicGaussian::x
Referenced by operator()(), and special_points().
y
double madness::BasisFunctions::SolidHarmonicGaussian::y
Referenced by operator()(), and special_points().
z
double madness::BasisFunctions::SolidHarmonicGaussian::z
origin
Referenced by operator()(), and special_points().
Z
double madness::BasisFunctions::SolidHarmonicGaussian::Z
The documentation for this class was generated from the following files:
PNOGuessFunctions.h
PNOGuessFunctions.cpp