MADNESS: madness::TwoBodyFunctionSeparatedComponent< T, NDIM > Class Template Reference
madness::TwoBodyFunctionSeparatedComponent< T, NDIM > Class Template Reference
#include <ccpairfunction.h>
Public Member Functions
TwoBodyFunctionSeparatedComponent ()=default
TwoBodyFunctionSeparatedComponent (const std::vector< Function< T, LDIM > > &a, const std::vector< Function< T, LDIM > > &b)
TwoBodyFunctionSeparatedComponent (const std::vector< Function< T, LDIM > > &a, const std::vector< Function< T, LDIM > > &b, const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op)
TwoBodyFunctionSeparatedComponent (const TwoBodyFunctionSeparatedComponent &other)=default
template<typename Q , std::size_t MDIM>
TwoBodyFunctionPureComponent< T, NDIM > apply (const SeparatedConvolution< Q, MDIM > *op, const int particle=0)
std::shared_ptr< TwoBodyFunctionComponentBase > clone () override
deep copy
std::vector< Function< T, LDIM > > get_a () const
std::vector< Function< T, LDIM > > get_b () const
const std::shared_ptr< CCConvolutionOperator< T, LDIM > > get_operator_ptr () const
std::vector< Function< T, LDIM > > get_vector (const int i) const
bool has_operator () const override
hashT hash () const override
bool is_decomposed () const override
std::string name (const bool transpose) const override
template<typename Q >
TwoBodyFunctionSeparatedComponent & operator*= (const Q fac)
void print_size (const std::string name1="") const override
long rank () const
void serialize ()
void set_operator (const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op1)
void swap_particles_inplace () override
return f(2,1)
World & world () const override
Public Member Functions inherited from madness::TwoBodyFunctionComponentBase
virtual ~TwoBodyFunctionComponentBase ()
virtual bool is_pure () const
Private Attributes
std::vector< Function< T, LDIM > > a
std::vector< Function< T, LDIM > > b
std::shared_ptr< CCConvolutionOperator< T, LDIM > > op
Static Private Attributes
static constexpr std::size_t LDIM =NDIM/2
Detailed Description
template<typename T, std::size_t NDIM>
class madness::TwoBodyFunctionSeparatedComponent< T, NDIM >
holds two vectors a and b of low-dimensional functions forming a high-dim function by a sum of outer products f(1,2) = sum_i |a_i b_i >
Constructor & Destructor Documentation
TwoBodyFunctionSeparatedComponent() [1/4]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::TwoBodyFunctionSeparatedComponent () default
TwoBodyFunctionSeparatedComponent() [2/4]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::TwoBodyFunctionSeparatedComponent (const std::vector< Function< T, LDIM > > & a, const std::vector< Function< T, LDIM > > & b) inline
TwoBodyFunctionSeparatedComponent() [3/4]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::TwoBodyFunctionSeparatedComponent (const std::vector< Function< T, LDIM > > & a, const std::vector< Function< T, LDIM > > & b, const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op) inline
TwoBodyFunctionSeparatedComponent() [4/4]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::TwoBodyFunctionSeparatedComponent (const TwoBodyFunctionSeparatedComponent< T, NDIM > & other) default
Member Function Documentation
apply()
template<typename T , std::size_t NDIM> template<typename Q , std::size_t MDIM> TwoBodyFunctionPureComponent< T, NDIM > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::apply (const SeparatedConvolution< Q, MDIM > * op, const int particle = 0) inline
References MADNESS_EXCEPTION.
clone()
template<typename T , std::size_t NDIM> std::shared_ptr< TwoBodyFunctionComponentBase > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::clone () inline override virtual
deep copy
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b, madness::copy(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::op, and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::world().
get_a()
template<typename T , std::size_t NDIM> std::vector< Function< T, LDIM > > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_a () const inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a.
get_b()
template<typename T , std::size_t NDIM> std::vector< Function< T, LDIM > > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_b () const inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b.
get_operator_ptr()
template<typename T , std::size_t NDIM> const std::shared_ptr< CCConvolutionOperator< T, LDIM > > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_operator_ptr () const inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::op.
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::name().
get_vector()
template<typename T , std::size_t NDIM> std::vector< Function< T, LDIM > > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_vector (const int i) const inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b, MADNESS_CHECK, and MADNESS_EXCEPTION.
has_operator()
template<typename T , std::size_t NDIM> bool madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::has_operator () const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::op.
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::name().
hash()
template<typename T , std::size_t NDIM> hashT madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::hash () const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, aa, madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b, madness::hash_combine(), madness::hash_value(), and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::op.
is_decomposed()
template<typename T , std::size_t NDIM> bool madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::is_decomposed () const inline override virtual
Reimplemented from madness::TwoBodyFunctionComponentBase.
name()
template<typename T , std::size_t NDIM> std::string madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::name (const bool transpose) const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_operator_ptr(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::has_operator(), and madness::transpose().
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::print_size().
operator*=()
template<typename T , std::size_t NDIM> template<typename Q > TwoBodyFunctionSeparatedComponent & madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::operator*= (const Q fac) inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, and madness::scale().
print_size()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::print_size (const std::string name1 = "") const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b, madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::name(), madness::print_size(), and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::world().
rank()
template<typename T , std::size_t NDIM> long madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::rank () const inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b, and MADNESS_CHECK.
serialize()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::serialize () inline
set_operator()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::set_operator (const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op1) inline
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::op.
swap_particles_inplace()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::swap_particles_inplace () inline override virtual
return f(2,1)
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b.
world()
template<typename T , std::size_t NDIM> World & madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::world () const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a, and MADNESS_ASSERT.
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::clone(), and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::print_size().
Member Data Documentation
a
template<typename T , std::size_t NDIM> std::vector<Function<T,LDIM> > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::a private
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::clone(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_a(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_vector(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::hash(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::operator*=(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::print_size(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::rank(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::swap_particles_inplace(), and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::world().
b
template<typename T , std::size_t NDIM> std::vector<Function<T,LDIM> > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::b private
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::clone(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_b(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_vector(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::hash(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::print_size(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::rank(), and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::swap_particles_inplace().
LDIM
template<typename T , std::size_t NDIM> constexpr std::size_t madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::LDIM =NDIM/2 static constexpr private
op
template<typename T , std::size_t NDIM> std::shared_ptr<CCConvolutionOperator<T,LDIM> > madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::op private
Referenced by madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::clone(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::get_operator_ptr(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::has_operator(), madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::hash(), and madness::TwoBodyFunctionSeparatedComponent< T, NDIM >::set_operator().
The documentation for this class was generated from the following file:
ccpairfunction.h