MADNESS: madness::OEP_Parameters Class Reference
madness::OEP_Parameters Class Reference
#include <oep.h>
Public Member Functions
OEP_Parameters ()
OEP_Parameters (const OEP_Parameters &other)=default
OEP_Parameters (World &world, const commandlineparser &parser)
double dens_thresh_hi () const
double dens_thresh_inv () const
double dens_thresh_lo () const
std::string get_tag () const override
std::vector< double > kain_param () const
double levelshift () const
unsigned int maxiter () const
std::vector< std::string > model () const
bool no_compute () const
bool restart () const
unsigned int save_iter_corrections () const
unsigned int saving_amount () const
void set_derived_values (const CalculationParameters &cparam)
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Static Public Attributes
static constexpr char const * tag = "oep"
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Detailed Description
TODO:
change algorithm to handle localized orbitals
do not recompute the OEP potentials that don't depend on the orbital energies/Fock matrix elements
do not recompute the HF contributions to the OEP potentials
think about the long-range part of the Slater potential (or medium-range)
Constructor & Destructor Documentation
OEP_Parameters() [1/3]
madness::OEP_Parameters::OEP_Parameters () inline
OEP_Parameters() [2/3]
madness::OEP_Parameters::OEP_Parameters (World & world, const commandlineparser & parser) inline
References madness::QCCalculationParametersBase::read_input_and_commandline_options().
OEP_Parameters() [3/3]
madness::OEP_Parameters::OEP_Parameters (const OEP_Parameters & other) default
Member Function Documentation
dens_thresh_hi()
double madness::OEP_Parameters::dens_thresh_hi () const inline
Referenced by madness::OEP::compute_dcep_correction(), madness::OEP::compute_mrks_correction(), madness::OEP::compute_ocep_correction(), madness::OEP::compute_slater_potential(), and set_derived_values().
dens_thresh_inv()
double madness::OEP_Parameters::dens_thresh_inv () const inline
Referenced by madness::OEP::compute_dcep_correction(), madness::OEP::compute_mrks_correction(), madness::OEP::compute_ocep_correction(), and madness::OEP::compute_slater_potential().
dens_thresh_lo()
double madness::OEP_Parameters::dens_thresh_lo () const inline
Referenced by madness::OEP::compute_dcep_correction(), madness::OEP::compute_mrks_correction(), madness::OEP::compute_ocep_correction(), madness::OEP::compute_slater_potential(), and set_derived_values().
get_tag()
std::string madness::OEP_Parameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
kain_param()
std::vector< double > madness::OEP_Parameters::kain_param () const inline
Referenced by madness::OEP::iterate().
levelshift()
double madness::OEP_Parameters::levelshift () const inline
Referenced by madness::OEP::iterate(), and set_derived_values().
maxiter()
unsigned int madness::OEP_Parameters::maxiter () const inline
Referenced by madness::OEP::iterate().
model()
std::vector< std::string > madness::OEP_Parameters::model () const inline
Referenced by madness::OEP::output_calc_info_schema(), and madness::OEP::solve().
no_compute()
bool madness::OEP_Parameters::no_compute () const inline
Referenced by madness::OEP::value().
restart()
bool madness::OEP_Parameters::restart () const inline
Referenced by madness::OEP::solve(), and madness::OEP::value().
save_iter_corrections()
unsigned int madness::OEP_Parameters::save_iter_corrections () const inline
Referenced by madness::OEP::iterate().
saving_amount()
unsigned int madness::OEP_Parameters::saving_amount () const inline
Referenced by madness::OEP::compute_slater_potential(), madness::OEP::iterate(), and madness::OEP::solve().
set_derived_values()
void madness::OEP_Parameters::set_derived_values (const CalculationParameters & cparam) inline
References dens_thresh_hi(), dens_thresh_lo(), madness::CalculationParameters::econv(), levelshift(), MADNESS_EXCEPTION, madness::QCCalculationParametersBase::print(), and madness::QCCalculationParametersBase::set_derived_value().
Referenced by madness::OEP::OEP(), and madness::OEP::OEP().
Member Data Documentation
tag
constexpr char const* madness::OEP_Parameters::tag = "oep" static constexpr
The documentation for this class was generated from the following file:
oep.h