MADNESS: madness::LowRankFunction< T, NDIM, LDIM > Class Template Reference
madness::LowRankFunction< T, NDIM, LDIM > Class Template Reference
LowRankFunction represents a hi-dimensional (NDIM) function as a sum of products of low-dimensional (LDIM) functions.
#include <lowrankfunction.h>
Public Member Functions
LowRankFunction (const LowRankFunction &other)
shallow copy ctor
LowRankFunction (std::vector< Function< T, LDIM > > g, std::vector< Function< T, LDIM > > h, double tol, std::string orthomethod)
LowRankFunction (World &world)
double check_orthonormality (const std::vector< Function< T, LDIM > > &v) const
double check_orthonormality (const Tensor< T > &ovlp) const
std::vector< Function< T, LDIM > > get_functions (const particle< LDIM > &p) const
std::vector< Function< T, LDIM > > get_g () const
std::vector< Function< T, LDIM > > get_h () const
double l2error (const LRFunctorBase< T, NDIM > &lrfunctor1) const
compute the l2 error |functor - \sum_i g_ih_i|_2
TensorTypeData< T >::scalar_type norm2 () const
l2 norm
T operator() (const Vector< double, NDIM > &r) const
function evaluation
template<typename Q >
LowRankFunction operator* (const Q a) const
scale by a scalar
LowRankFunction operator* (const T a) const
out-of-place scale by a scalar (no type conversion)
LowRankFunction & operator*= (const T a)
in-place scale by a scalar (no type conversion)
LowRankFunction operator+ (const LowRankFunction &b) const
addition
LowRankFunction & operator+= (const LowRankFunction &b)
in-place addition
LowRankFunction operator- (const LowRankFunction &b) const
subtraction
LowRankFunction & operator-= (const LowRankFunction &b)
in-place subtraction
LowRankFunction & operator= (const LowRankFunction &f)
void optimize (const LRFunctorBase< T, NDIM > &lrfunctor1, const long nopt=1)
optimize the lrf using the lrfunctor
std::vector< Function< T, LDIM > > orthonormalize (const std::vector< Function< T, LDIM > > &g) const
orthonormalize the argument vector
long rank () const
Function< T, NDIM > reconstruct () const
void reorthonormalize (double thresh=-1.0)
void reorthonormalize_canonical (double thresh=-1.0)
after external operations g might not be orthonormal and/or optimal – reorthonormalize
void reorthonormalize_rrcd (double thresh=-1.0)
double size () const
return the size in GByte
Public Attributes
bool do_print =false
std::vector< Function< T, LDIM > > g
std::vector< Function< T, LDIM > > h
std::string orthomethod ="canonical"
const particle< LDIM > p1 =particle<LDIM>::particle1()
const particle< LDIM > p2 =particle<LDIM>::particle2()
double rank_revealing_tol =1.e-8
World & world
Friends
LowRankFunction copy (const LowRankFunction &other)
deep copy
LowRankFunction operator* (const T a, const LowRankFunction &other)
multiplication with a scalar
Detailed Description
template<typename T, std::size_t NDIM, std::size_t LDIM = NDIM/2>
class madness::LowRankFunction< T, NDIM, LDIM >
LowRankFunction represents a hi-dimensional (NDIM) function as a sum of products of low-dimensional (LDIM) functions.
f(1,2) = \sum_i g_i(1) h_i(2) a LowRankFunction can be created from a hi-dim function directly, or from a composite like f(1,2) phi(1) psi(2), where f(1,2) is a two-particle function (e.g. a Slater function)
Constructor & Destructor Documentation
LowRankFunction() [1/3]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunction< T, NDIM, LDIM >::LowRankFunction (World & world) inline
LowRankFunction() [2/3]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunction< T, NDIM, LDIM >::LowRankFunction (std::vector< Function< T, LDIM > > g, std::vector< Function< T, LDIM > > h, double tol, std::string orthomethod) inline
LowRankFunction() [3/3]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LowRankFunction< T, NDIM, LDIM >::LowRankFunction (const LowRankFunction< T, NDIM, LDIM > & other) inline
shallow copy ctor
Member Function Documentation
check_orthonormality() [1/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> double madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality (const std::vector< Function< T, LDIM > > & v) const inline
References madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::matrix_inner(), v, and madness::LowRankFunction< T, NDIM, LDIM >::world.
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), and madness::LowRankFunction< T, NDIM, LDIM >::l2error().
check_orthonormality() [2/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> double madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality (const Tensor< T > & ovlp) const inline
References madness::Tensor< T >::absmax(), madness::BaseTensor::dim(), madness::LowRankFunction< T, NDIM, LDIM >::do_print, madness::timer::do_print, madness::Tensor< T >::normf(), madness::print(), madness::World::rank(), madness::BaseTensor::size(), madness::timer::tag(), and madness::LowRankFunction< T, NDIM, LDIM >::world.
get_functions()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > madness::LowRankFunction< T, NDIM, LDIM >::get_functions (const particle< LDIM > & p) const inline
References madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, MADNESS_CHECK, and p().
get_g()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > madness::LowRankFunction< T, NDIM, LDIM >::get_g () const inline
References madness::LowRankFunction< T, NDIM, LDIM >::g.
Referenced by madness::CCPairFunction< T, NDIM >::op_dec_to_dec(), and madness::CCPairFunction< T, NDIM >::remove_linearly_dependent_terms().
get_h()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > madness::LowRankFunction< T, NDIM, LDIM >::get_h () const inline
References madness::LowRankFunction< T, NDIM, LDIM >::h.
Referenced by madness::CCPairFunction< T, NDIM >::op_dec_to_dec(), and madness::CCPairFunction< T, NDIM >::remove_linearly_dependent_terms().
l2error()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> double madness::LowRankFunction< T, NDIM, LDIM >::l2error (const LRFunctorBase< T, NDIM > & lrfunctor1) const inline
compute the l2 error |functor - \sum_i g_ih_i|_2
\int (f(1,2) - gh(1,2))^2 = \int f(1,2)^2 - 2\int f(1,2) gh(1,2) + \int gh(1,2)^2 since we are subtracting large numbers the numerics are sensitive, and NaN may be returned..
References madness::arg(), madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::LowRankFunction< T, NDIM, LDIM >::do_print, madness::timer::do_print, madness::error(), madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, madness::inner(), madness::matrix_inner(), madness::LRFunctorBase< T, NDIM, LDIM >::norm2(), madness::LowRankFunction< T, NDIM, LDIM >::p1, madness::LowRankFunction< T, NDIM, LDIM >::p2, madness::print(), madness::World::rank(), madness::timer::tag(), and madness::LowRankFunction< T, NDIM, LDIM >::world.
norm2()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> TensorTypeData< T >::scalar_type madness::LowRankFunction< T, NDIM, LDIM >::norm2 () const inline
l2 norm
References madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, madness::matrix_inner(), and madness::LowRankFunction< T, NDIM, LDIM >::world.
operator()()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> T madness::LowRankFunction< T, NDIM, LDIM >::operator() (const Vector< double, NDIM > & r) const inline
function evaluation
References madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, and madness::LowRankFunction< T, NDIM, LDIM >::rank().
operator*() [1/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> template<typename Q > LowRankFunction madness::LowRankFunction< T, NDIM, LDIM >::operator* (const Q a) const inline
scale by a scalar
References a, madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, NDIM, madness::LowRankFunction< T, NDIM, LDIM >::orthomethod, Q(), and madness::LowRankFunction< T, NDIM, LDIM >::rank_revealing_tol.
operator*() [2/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction madness::LowRankFunction< T, NDIM, LDIM >::operator* (const T a) const inline
out-of-place scale by a scalar (no type conversion)
References a, madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, madness::LowRankFunction< T, NDIM, LDIM >::orthomethod, and madness::LowRankFunction< T, NDIM, LDIM >::rank_revealing_tol.
operator*=()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction & madness::LowRankFunction< T, NDIM, LDIM >::operator*= (const T a) inline
in-place scale by a scalar (no type conversion)
References a, and madness::LowRankFunction< T, NDIM, LDIM >::g.
operator+()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction madness::LowRankFunction< T, NDIM, LDIM >::operator+ (const LowRankFunction< T, NDIM, LDIM > & b) const inline
addition
References b, and madness::LowRankFunction< T, NDIM, LDIM >::copy.
operator+=()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction & madness::LowRankFunction< T, NDIM, LDIM >::operator+= (const LowRankFunction< T, NDIM, LDIM > & b) inline
in-place addition
References madness::append(), b, madness::LowRankFunction< T, NDIM, LDIM >::copy, madness::LowRankFunction< T, NDIM, LDIM >::g, and madness::LowRankFunction< T, NDIM, LDIM >::h.
operator-()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction madness::LowRankFunction< T, NDIM, LDIM >::operator- (const LowRankFunction< T, NDIM, LDIM > & b) const inline
subtraction
References b, and madness::LowRankFunction< T, NDIM, LDIM >::copy.
operator-=()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction & madness::LowRankFunction< T, NDIM, LDIM >::operator-= (const LowRankFunction< T, NDIM, LDIM > & b) inline
in-place subtraction
References madness::append(), b, madness::LowRankFunction< T, NDIM, LDIM >::copy, madness::LowRankFunction< T, NDIM, LDIM >::g, and madness::LowRankFunction< T, NDIM, LDIM >::h.
operator=()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction & madness::LowRankFunction< T, NDIM, LDIM >::operator= (const LowRankFunction< T, NDIM, LDIM > & f) inline
References madness::f, madness::LowRankFunction< T, NDIM, LDIM >::g, and madness::LowRankFunction< T, NDIM, LDIM >::h.
optimize()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> void madness::LowRankFunction< T, NDIM, LDIM >::optimize (const LRFunctorBase< T, NDIM > & lrfunctor1, const long nopt = 1) inline
optimize the lrf using the lrfunctor
Parameters
[in] nopt number of iterations (wrt to Alg. 4.3 in Halko)
References madness::LowRankFunction< T, NDIM, LDIM >::do_print, madness::timer::do_print, madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, madness::inner(), madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize(), madness::LowRankFunction< T, NDIM, LDIM >::p1, madness::LowRankFunction< T, NDIM, LDIM >::p2, madness::timer::tag(), madness::truncate(), and madness::LowRankFunction< T, NDIM, LDIM >::world.
Referenced by madness::CCPairFunction< T, NDIM >::op_dec_to_dec().
orthonormalize()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize (const std::vector< Function< T, LDIM > > & g) const inline
orthonormalize the argument vector
References madness::LowRankFunction< T, NDIM, LDIM >::g, madness::FunctionDefaults< NDIM >::get_thresh(), MADNESS_EXCEPTION, madness::matrix_inner(), madness::LowRankFunction< T, NDIM, LDIM >::orthomethod, madness::orthonormalize_canonical(), madness::orthonormalize_rrcd(), madness::print(), madness::LowRankFunction< T, NDIM, LDIM >::rank_revealing_tol, madness::truncate(), and madness::LowRankFunction< T, NDIM, LDIM >::world.
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::optimize().
rank()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> long madness::LowRankFunction< T, NDIM, LDIM >::rank () const inline
References madness::LowRankFunction< T, NDIM, LDIM >::g.
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::operator()(), and madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd().
reconstruct()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> Function< T, NDIM > madness::LowRankFunction< T, NDIM, LDIM >::reconstruct () const inline
References madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, and madness::hartree_product().
reorthonormalize()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> void madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize (double thresh = -1.0) inline
References MADNESS_EXCEPTION, madness::LowRankFunction< T, NDIM, LDIM >::orthomethod, madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd(), and thresh.
Referenced by madness::CCPairFunction< T, NDIM >::remove_linearly_dependent_terms().
reorthonormalize_canonical()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> void madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical (double thresh = -1.0) inline
after external operations g might not be orthonormal and/or optimal – reorthonormalize
orthonormalization similar to Bischoff, Harrison, Valeev, JCP 137 104103 (2012), Sec II C 3 f =\sum_i g_i h_i = g X- (X+)^T (Y+)^T Y- h = g X- U S V^T Y- h = g (X- U) (S V^T Y-) h requires 2 matrix_inner and 2 transforms. g and h are optimal
Parameters
[in] thresh SVD threshold
References madness::_(), madness::LowRankFunction< T, NDIM, LDIM >::copy, madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, madness::inner(), MADNESS_CHECK_THROW, madness::matrix_inner(), madness::LowRankFunction< T, NDIM, LDIM >::rank_revealing_tol, madness::svd(), madness::syev(), thresh, madness::transform(), madness::transpose(), madness::truncate(), and madness::LowRankFunction< T, NDIM, LDIM >::world.
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize().
reorthonormalize_rrcd()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> void madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd (double thresh = -1.0) inline
remove linear dependencies using rank-revealing cholesky decomposition
Returns
this with g orthonormal and h orthogonal
References madness::_(), madness::LowRankFunction< T, NDIM, LDIM >::copy, madness::BaseTensor::dim(), madness::LowRankFunction< T, NDIM, LDIM >::g, madness::LowRankFunction< T, NDIM, LDIM >::h, madness::inner(), madness::inverse(), L, madness::matrix_inner(), p(), madness::print(), madness::LowRankFunction< T, NDIM, LDIM >::rank(), madness::LowRankFunction< T, NDIM, LDIM >::rank_revealing_tol, madness::rr_cholesky(), madness::transform(), madness::transpose(), v, and madness::LowRankFunction< T, NDIM, LDIM >::world.
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize().
size()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> double madness::LowRankFunction< T, NDIM, LDIM >::size () const inline
return the size in GByte
References madness::LowRankFunction< T, NDIM, LDIM >::g, madness::get_size(), madness::LowRankFunction< T, NDIM, LDIM >::h, and madness::LowRankFunction< T, NDIM, LDIM >::world.
Friends And Related Symbol Documentation
copy
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction copy (const LowRankFunction< T, NDIM, LDIM > & other) friend
deep copy
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::operator+(), madness::LowRankFunction< T, NDIM, LDIM >::operator+=(), madness::LowRankFunction< T, NDIM, LDIM >::operator-(), madness::LowRankFunction< T, NDIM, LDIM >::operator-=(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical(), and madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd().
operator*
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> LowRankFunction operator* (const T a, const LowRankFunction< T, NDIM, LDIM > & other) friend
multiplication with a scalar
Member Data Documentation
do_print
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> bool madness::LowRankFunction< T, NDIM, LDIM >::do_print =false
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::LowRankFunction< T, NDIM, LDIM >::l2error(), and madness::LowRankFunction< T, NDIM, LDIM >::optimize().
g
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector<Function<T,LDIM> > madness::LowRankFunction< T, NDIM, LDIM >::g
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::get_functions(), madness::LowRankFunction< T, NDIM, LDIM >::get_g(), madness::inner(), madness::LowRankFunction< T, NDIM, LDIM >::l2error(), madness::LowRankFunction< T, NDIM, LDIM >::norm2(), madness::LowRankFunction< T, NDIM, LDIM >::operator()(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator*=(), madness::LowRankFunction< T, NDIM, LDIM >::operator+=(), madness::LowRankFunction< T, NDIM, LDIM >::operator-=(), madness::LowRankFunction< T, NDIM, LDIM >::operator=(), madness::LowRankFunction< T, NDIM, LDIM >::optimize(), madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize(), madness::LowRankFunction< T, NDIM, LDIM >::rank(), madness::LowRankFunction< T, NDIM, LDIM >::reconstruct(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd(), madness::LowRankFunction< T, NDIM, LDIM >::size(), and test_Kcommutator().
h
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector<Function<T,LDIM> > madness::LowRankFunction< T, NDIM, LDIM >::h
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::get_functions(), madness::LowRankFunction< T, NDIM, LDIM >::get_h(), madness::inner(), madness::LowRankFunction< T, NDIM, LDIM >::l2error(), madness::LowRankFunction< T, NDIM, LDIM >::norm2(), madness::LowRankFunction< T, NDIM, LDIM >::operator()(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator+=(), madness::LowRankFunction< T, NDIM, LDIM >::operator-=(), madness::LowRankFunction< T, NDIM, LDIM >::operator=(), madness::LowRankFunction< T, NDIM, LDIM >::optimize(), madness::LowRankFunction< T, NDIM, LDIM >::reconstruct(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd(), madness::LowRankFunction< T, NDIM, LDIM >::size(), and test_Kcommutator().
orthomethod
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::string madness::LowRankFunction< T, NDIM, LDIM >::orthomethod ="canonical"
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize(), and madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize().
p1
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> const particle<LDIM> madness::LowRankFunction< T, NDIM, LDIM >::p1 =particle<LDIM>::particle1()
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::l2error(), and madness::LowRankFunction< T, NDIM, LDIM >::optimize().
p2
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> const particle<LDIM> madness::LowRankFunction< T, NDIM, LDIM >::p2 =particle<LDIM>::particle2()
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::l2error(), and madness::LowRankFunction< T, NDIM, LDIM >::optimize().
rank_revealing_tol
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> double madness::LowRankFunction< T, NDIM, LDIM >::rank_revealing_tol =1.e-8
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical(), and madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd().
world
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> World& madness::LowRankFunction< T, NDIM, LDIM >::world
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::LowRankFunction< T, NDIM, LDIM >::l2error(), madness::LowRankFunction< T, NDIM, LDIM >::norm2(), madness::LowRankFunction< T, NDIM, LDIM >::optimize(), madness::LowRankFunction< T, NDIM, LDIM >::orthonormalize(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_canonical(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd(), and madness::LowRankFunction< T, NDIM, LDIM >::size().
The documentation for this class was generated from the following file:
lowrankfunction.h