MADNESS: madness::Key< NDIM > Class Template Reference
madness::Key< NDIM > Class Template Reference
Key is the index for a node of the 2^NDIM-tree.
#include <key.h>
Public Member Functions
Key ()
Default constructor makes an uninitialized key.
Key (int n)
Constructor with given n and l=0.
Key (Level n, const Vector< Translation, NDIM > &l)
Constructor with given n, l.
template<std::size_t LDIM, std::size_t KDIM>
void break_apart (Key< LDIM > &key1, Key< KDIM > &key2) const
break key into two low-dimensional keys
uint64_t distsq () const
uint64_t distsq_bc (const array_of_bools< NDIM > &is_periodic) const
like distsq() but accounts for periodicity
uint64_t distsq_bc (const array_of_bools< NDIM > &is_periodic, const std::array< std::size_t, NDIM2 > &axes) const
template<std::size_t VDIM>
Key< VDIM > extract_back () const
extract a new key consisting of last VDIM dimensions of this
template<std::size_t VDIM>
Key< NDIM-VDIM > extract_complement_key (const std::array< int, VDIM > &v) const
extract a new key with the Translations complementary to the ones indicated in the v array
template<std::size_t VDIM>
Key< VDIM > extract_front () const
extract a new key consisting of first VDIM dimensions of this
template<std::size_t VDIM>
Key< VDIM > extract_key (const std::array< int, VDIM > &v) const
extract a new key with the Translations indicated in the v array
hashT hash () const
bool is_child_of (const Key &key) const
bool is_farther_out_than (const Key< NDIM > &other) const
return if the other key is pointing in the same direction and is farther out
bool is_invalid () const
Checks if a key is invalid.
bool is_neighbor_of (const Key &key, const array_of_bools< NDIM > &bperiodic) const
Assuming keys are at the same level, returns true if displaced by no more than 1 in any direction.
bool is_parent_of (const Key &key) const
bool is_valid () const
Checks if a key is valid.
Level level () const
template<std::size_t LDIM>
Key< NDIM+LDIM > merge_with (const Key< LDIM > &rhs) const
merge with other key (ie concatenate), use level of rhs, not of this
Key neighbor (const Key< NDIM > &disp) const
given a displacement, generate a neighbor key; ignore boundary conditions and disp's level
Key neighbor (const Vector< Translation, NDIM > &disp) const
given a displacement, generate a neighbor key; ignore boundary conditions and disp's level
bool operator!= (const Key &other) const
bool operator< (const Key &other) const
Comparison operator less than to enable storage in STL map.
bool operator== (const Key &other) const
Equality test.
const Translation & operator[] (std::size_t d) const
const accessor to elements of this->translation()
Key parent (int generation=1) const
Returns the key of the parent.
void rehash ()
Recomputes hashval ... presently only done when reading from external storage.
bool thisKeyContains (const Vector< double, NDIM > &x, const unsigned int &dim0, const unsigned int &dim1) const
check if this MultiIndex contains point x, disregarding these two dimensions
const Vector< Translation, NDIM > & translation () const
Static Public Member Functions
static Key< NDIM > invalid ()
Returns an invalid key.
Static Public Attributes
static const std::size_t static_size = NDIM
Private Attributes
hashT hashval
Vector< Translation, NDIM > l
Level n
Friends
class KeyChildIterator< NDIM >
Detailed Description
template<std::size_t NDIM>
class madness::Key< NDIM >
Key is the index for a node of the 2^NDIM-tree.
See KeyChildIterator for facile generation of children, and foreach_child(parent,op) for facile application of operators to child keys.
Constructor & Destructor Documentation
Key() [1/3]
template<std::size_t NDIM> madness::Key< NDIM >::Key () inline
Default constructor makes an uninitialized key.
Referenced by Key::foreach_child(), madness::Key< NDIM >::neighbor(), madness::Key< NDIM >::neighbor(), Key::parent(), and madness::Key< NDIM >::parent().
Key() [2/3]
template<std::size_t NDIM> madness::Key< NDIM >::Key (Level n, const Vector< Translation, NDIM > & l) inline
Constructor with given n, l.
References MADNESS_ASSERT, madness::Key< NDIM >::n, and madness::Key< NDIM >::rehash().
Key() [3/3]
template<std::size_t NDIM> madness::Key< NDIM >::Key (int n) inline
Constructor with given n and l=0.
References MADNESS_ASSERT, madness::Key< NDIM >::n, and madness::Key< NDIM >::rehash().
Member Function Documentation
break_apart()
template<std::size_t NDIM> template<std::size_t LDIM, std::size_t KDIM> void madness::Key< NDIM >::break_apart (Key< LDIM > & key1, Key< KDIM > & key2) const inline
break key into two low-dimensional keys
References madness::Key< NDIM >::l, MADNESS_EXCEPTION, madness::Key< NDIM >::n, and NDIM.
Referenced by madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::compute_error_from_inaccurate_refinement(), madness::FunctionImpl< T, NDIM >::dirac_convolution_op(), madness::FunctionImpl< T, NDIM >::do_dirac_convolution(), madness::SeparatedConvolution< Q, NDIM >::get_source_key(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::make_child(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::make_sum_coeffs(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), madness::ElectronCuspyBox_op< T, NDIM >::operator()(), madness::NuclearCuspyBox_op< T, NDIM >::operator()(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::operator()(), madness::FunctionImpl< T, NDIM >::partial_inner_contract(), and madness::FunctionImpl< T, NDIM >::project_out2().
distsq()
template<std::size_t NDIM> uint64_t madness::Key< NDIM >::distsq () const inline
References d, dist(), madness::Key< NDIM >::l, and NDIM.
distsq_bc() [1/2]
template<std::size_t NDIM> uint64_t madness::Key< NDIM >::distsq_bc (const array_of_bools< NDIM > & is_periodic) const inline
like distsq() but accounts for periodicity
References d, madness::Key< NDIM >::level(), MADNESS_ASSERT, NDIM, and madness::Key< NDIM >::translation().
distsq_bc() [2/2]
template<std::size_t NDIM> uint64_t madness::Key< NDIM >::distsq_bc (const array_of_bools< NDIM > & is_periodic, const std::array< std::size_t, NDIM2 > & axes) const inline
References a, d, madness::Key< NDIM >::level(), MADNESS_ASSERT, NDIM, and madness::Key< NDIM >::translation().
extract_back()
template<std::size_t NDIM> template<std::size_t VDIM> Key< VDIM > madness::Key< NDIM >::extract_back () const inline
extract a new key consisting of last VDIM dimensions of this
References madness::Key< NDIM >::level(), NDIM, and madness::Key< NDIM >::translation().
extract_complement_key()
template<std::size_t NDIM> template<std::size_t VDIM> Key< NDIM-VDIM > madness::Key< NDIM >::extract_complement_key (const std::array< int, VDIM > & v) const inline
extract a new key with the Translations complementary to the ones indicated in the v array
References madness::Key< NDIM >::extract_key(), NDIM, and v.
Referenced by madness::FunctionImpl< T, NDIM >::recur_down_for_contraction_map().
extract_front()
template<std::size_t NDIM> template<std::size_t VDIM> Key< VDIM > madness::Key< NDIM >::extract_front () const inline
extract a new key consisting of first VDIM dimensions of this
References madness::Key< NDIM >::level(), NDIM, and madness::Key< NDIM >::translation().
extract_key()
template<std::size_t NDIM> template<std::size_t VDIM> Key< VDIM > madness::Key< NDIM >::extract_key (const std::array< int, VDIM > & v) const inline
extract a new key with the Translations indicated in the v array
References madness::Key< NDIM >::level(), and madness::Key< NDIM >::translation().
Referenced by madness::Key< NDIM >::extract_complement_key(), and madness::FunctionImpl< T, NDIM >::recur_down_for_contraction_map().
hash()
template<std::size_t NDIM> hashT madness::Key< NDIM >::hash () const inline
References madness::Key< NDIM >::hashval.
Referenced by operator<<(), LevelPmap::owner(), LevelPmapX::owner(), PartitionPmap::owner(), madness::LevelPmap< keyT >::owner(), and madness::MyPmap< D >::simple_hash().
invalid()
template<std::size_t NDIM> static Key< NDIM > madness::Key< NDIM >::invalid () inline static
Returns an invalid key.
References madness::Key< NDIM >::l, madness::Key< NDIM >::n, and madness::Key< NDIM >::rehash().
Referenced by madness::DerivativeBase< T, NDIM >::neighbor().
is_child_of()
template<std::size_t NDIM> bool madness::Key< NDIM >::is_child_of (const Key< NDIM > & key) const inline
References madness::Key< NDIM >::n, and madness::Key< NDIM >::parent().
Referenced by madness::Key< NDIM >::is_parent_of().
is_farther_out_than()
template<std::size_t NDIM> bool madness::Key< NDIM >::is_farther_out_than (const Key< NDIM > & other) const inline
return if the other key is pointing in the same direction and is farther out
unlike in distsq() the direction is taken into account, and other must be longer than this in each dimension
Parameters
[in] other a key
Returns
if other is farther out
References madness::Key< NDIM >::l, NDIM, and madness::Key< NDIM >::translation().
is_invalid()
template<std::size_t NDIM> bool madness::Key< NDIM >::is_invalid () const inline
Checks if a key is invalid.
References madness::Key< NDIM >::n.
Referenced by madness::DerivativeBase< T, NDIM >::find_neighbor(), and madness::FunctionImpl< T, NDIM >::parent_to_child().
is_neighbor_of()
template<std::size_t NDIM> bool madness::Key< NDIM >::is_neighbor_of (const Key< NDIM > & key, const array_of_bools< NDIM > & bperiodic) const inline
Assuming keys are at the same level, returns true if displaced by no more than 1 in any direction.
Assumes key and this are at the same level
References std::abs(), dist(), madness::Key< NDIM >::l, madness::Key< NDIM >::n, and NDIM.
Referenced by madness::Specialbox_op< T, NDIM >::check_special_points(), and madness::FunctionImpl< T, NDIM >::project_refine_op().
is_parent_of()
template<std::size_t NDIM> bool madness::Key< NDIM >::is_parent_of (const Key< NDIM > & key) const inline
References madness::Key< NDIM >::is_child_of().
is_valid()
template<std::size_t NDIM> bool madness::Key< NDIM >::is_valid () const inline
Checks if a key is valid.
References madness::Key< NDIM >::n.
Referenced by madness::FunctionImpl< T, NDIM >::broaden(), madness::FunctionImpl< T, NDIM >::do_apply(), and madness::FunctionImpl< T, NDIM >::do_apply_directed_screening().
level()
template<std::size_t NDIM> Level madness::Key< NDIM >::level () const inline
References madness::Key< NDIM >::n.
Referenced by madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::ScalingFunctionFunctor(), madness::FunctionNode< T, NDIM >::accumulate(), madness::FunctionNode< T, NDIM >::accumulate2(), madness::FunctionImpl< T, NDIM >::apply_1d_realspace_push_op(), madness::Specialbox_op< T, NDIM >::box_is_at_boundary(), madness::FunctionImpl< T, NDIM >::broaden(), madness::Specialbox_op< T, NDIM >::check_special_points(), madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::Leaf_op< T, NDIM, opT, specialboxT >::compare_to_parent(), madness::FunctionImpl< T, NDIM >::compress_op(), madness::FunctionImpl< T, NDIM >::compress_spawn(), madness::Key< NDIM >::distsq_bc(), madness::Key< NDIM >::distsq_bc(), madness::FunctionImpl< T, NDIM >::do_apply(), madness::FunctionImpl< T, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< T, NDIM >::do_binary_op(), madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::do_diff2i(), madness::FunctionImpl< T, NDIM >::do_mul(), madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::FunctionImpl< T, NDIM >::do_print_tree(), madness::FunctionImpl< T, NDIM >::do_print_tree_graphviz(), madness::FunctionImpl< T, NDIM >::do_print_tree_json(), madness::FunctionImpl< T, NDIM >::erase(), madness::FunctionImpl< T, NDIM >::err_box(), madness::FunctionImpl< T, NDIM >::eval(), madness::FunctionImpl< T, NDIM >::eval_local_only(), madness::FunctionImpl< T, NDIM >::evaldepthpt(), madness::FunctionImpl< T, NDIM >::evalR(), madness::Key< NDIM >::extract_back(), madness::Key< NDIM >::extract_front(), madness::Key< NDIM >::extract_key(), madness::fcube(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::finalize(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::finalize(), madness::FunctionImpl< T, NDIM >::get_contraction_node_lists(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), madness::FunctionImpl< T, NDIM >::insert_zero_down_to_initial_level(), madness::TwoElectronInterface< T, NDIM >::make_coeff(), madness::Key< NDIM >::merge_with(), madness::Convolution1D< Q >::mod_nonstandard(), madness::FunctionImpl< T, NDIM >::mul(), madness::Key< NDIM >::neighbor(), madness::FunctionImpl< T, NDIM >::neighbor(), madness::DerivativeBase< T, NDIM >::neighbor(), madness::Key< NDIM >::neighbor(), madness::FunctionImpl< T, NDIM >::neighbor_in_volume(), madness::MyPmap< D >::not_so_simple_hash(), madness::FunctionImpl< T, NDIM >::NS_fcube_for_mul(), madness::FunctionImpl< T, NDIM >::NScoeffs2values(), LBCost::operator()(), LBCost::operator()(), YetAnotherWrapperClass::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::operator()(), madness::op_leaf_op< T, NDIM, opT >::operator()(), madness::ElectronCuspyBox_op< T, NDIM >::operator()(), madness::NuclearCuspyBox_op< T, NDIM >::operator()(), DirichletLBCost< NDIM >::operator()(), lbcost< T, NDIM >::operator()(), madness::lbcost< T, NDIM >::operator()(), madness::op_leaf_op< T, NDIM, opT >::operator()(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::hartree_convolute_leaf_op< T, NDIM, LDIM, opT >::operator()(), true_if_n_gt_op::operator()(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::do_mapdim::operator()(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), madness::FunctionImpl< T, NDIM >::do_standard::operator()(), madness::operator<<(), LevelPmap::owner(), LevelPmapX::owner(), PartitionPmap::owner(), madness::LBDeuxPmap< NDIM >::owner(), madness::FunctionImpl< T, NDIM >::parent_to_child(), madness::FunctionImpl< T, NDIM >::parent_to_child_NS(), madness::FunctionImpl< T, NDIM >::partial_inner_contract(), madness::Leaf_op< T, NDIM, opT, specialboxT >::post_screening(), madness::FunctionImpl< T, NDIM >::print_plane_local(), madness::FunctionImpl< T, NDIM >::project(), madness::FunctionImpl< T, NDIM >::project_refine_op(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), madness::FunctionImpl< T, NDIM >::reconstruct_op(), madness::FunctionImpl< T, NDIM >::recur_down_for_contraction_map(), madness::FunctionImpl< T, NDIM >::refine_op(), madness::FunctionNode< T, NDIM >::set_has_children_recursive(), madness::MyPmap< D >::simple_hash(), madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::special_level(), madness::Leaf_op< T, NDIM, opT, specialboxT >::special_refinement_needed(), madness::FunctionImpl< T, NDIM >::trace_local(), madness::FunctionImpl< T, NDIM >::truncate_op(), madness::FunctionImpl< T, NDIM >::truncate_reconstructed_op(), madness::FunctionImpl< T, NDIM >::truncate_spawn(), madness::FunctionImpl< T, NDIM >::truncate_tol(), madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs(), madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs(), madness::FunctionImpl< T, NDIM >::values2coeffs(), madness::FunctionImpl< T, NDIM >::values2coeffs(), madness::FunctionImpl< T, NDIM >::values2NScoeffs(), madness::FunctionImpl< T, NDIM >::vtransform_doit(), write_function_coeffs(), and FunctionIO< T, NDIM >::write_function_coeffs().
merge_with()
template<std::size_t NDIM> template<std::size_t LDIM> Key< NDIM+LDIM > madness::Key< NDIM >::merge_with (const Key< LDIM > & rhs) const inline
merge with other key (ie concatenate), use level of rhs, not of this
References madness::Key< NDIM >::level(), NDIM, and madness::Key< NDIM >::translation().
Referenced by madness::FunctionImpl< T, NDIM >::do_apply_directed_screening(), madness::SeparatedConvolution< Q, NDIM >::getop_modified(), and madness::FunctionImpl< T, NDIM >::recur_down_for_contraction_map().
neighbor() [1/2]
template<std::size_t NDIM> Key madness::Key< NDIM >::neighbor (const Key< NDIM > & disp) const inline
given a displacement, generate a neighbor key; ignore boundary conditions and disp's level
Parameters
[in] disp the displacement
Returns
a new key
References madness::Key< NDIM >::Key(), madness::Key< NDIM >::l, madness::Key< NDIM >::level(), and madness::Key< NDIM >::translation().
neighbor() [2/2]
template<std::size_t NDIM> Key madness::Key< NDIM >::neighbor (const Vector< Translation, NDIM > & disp) const inline
given a displacement, generate a neighbor key; ignore boundary conditions and disp's level
Parameters
[in] disp the displacement
Returns
a new key
References madness::Key< NDIM >::Key(), madness::Key< NDIM >::l, madness::Key< NDIM >::level(), and madness::Key< NDIM >::translation().
operator!=()
template<std::size_t NDIM> bool madness::Key< NDIM >::operator!= (const Key< NDIM > & other) const inline
operator<()
template<std::size_t NDIM> bool madness::Key< NDIM >::operator< (const Key< NDIM > & other) const inline
Comparison operator less than to enable storage in STL map.
References madness::Key< NDIM >::hashval, madness::Key< NDIM >::l, madness::Key< NDIM >::n, and NDIM.
operator==()
template<std::size_t NDIM> bool madness::Key< NDIM >::operator== (const Key< NDIM > & other) const inline
Equality test.
References madness::Key< NDIM >::hashval, madness::Key< NDIM >::l, madness::Key< NDIM >::n, and NDIM.
operator[]()
template<std::size_t NDIM> const Translation & madness::Key< NDIM >::operator[] (std::size_t d) const inline
const accessor to elements of this->translation()
References d, and madness::Key< NDIM >::l.
parent()
template<std::size_t NDIM> Key madness::Key< NDIM >::parent (int generation = 1) const inline
Returns the key of the parent.
Default is the immediate parent (generation=1). To get the grandparent use generation=2, and similarly for great-grandparents.
!! If there is no such parent it quietly returns the closest match (which may be self if this is the top of the tree).
References madness::Key< NDIM >::Key(), madness::Key< NDIM >::l, madness::Key< NDIM >::n, and NDIM.
Referenced by madness::FunctionNode< T, NDIM >::accumulate(), madness::FunctionNode< T, NDIM >::accumulate2(), madness::FunctionImpl< T, NDIM >::get_contraction_node_lists(), madness::Key< NDIM >::is_child_of(), madness::MyPmap< D >::not_so_simple_hash(), madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::operator()(), LevelPmap::owner(), LevelPmapX::owner(), PartitionPmap::owner(), madness::LBDeuxPmap< NDIM >::owner(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), madness::FunctionNode< T, NDIM >::set_has_children_recursive(), madness::MyPmap< D >::simple_hash(), madness::FunctionImpl< T, NDIM >::sock_it_to_me(), madness::FunctionImpl< T, NDIM >::sock_it_to_me_too(), madness::FunctionImpl< T, NDIM >::verify_parents_and_children(), and madness::FunctionImpl< T, NDIM >::vtransform_doit().
rehash()
template<std::size_t NDIM> void madness::Key< NDIM >::rehash () inline
Recomputes hashval ... presently only done when reading from external storage.
References madness::hash_combine(), madness::hash_value(), madness::Key< NDIM >::hashval, madness::Key< NDIM >::l, and madness::Key< NDIM >::n.
Referenced by madness::Key< NDIM >::Key(), madness::Key< NDIM >::Key(), madness::Key< NDIM >::invalid(), and madness::archive::ArchiveLoadImpl< BinaryFstreamInputArchive, Key< NDIM > >::load().
thisKeyContains()
template<std::size_t NDIM> bool madness::Key< NDIM >::thisKeyContains (const Vector< double, NDIM > & x, const unsigned int & dim0, const unsigned int & dim1) const inline
check if this MultiIndex contains point x, disregarding these two dimensions
References madness::Key< NDIM >::l, MADNESS_ASSERT, madness::Key< NDIM >::n, and NDIM.
Referenced by madness::FunctionImpl< T, NDIM >::print_plane_local().
translation()
template<std::size_t NDIM> const Vector< Translation, NDIM > & madness::Key< NDIM >::translation () const inline
References madness::Key< NDIM >::l.
Referenced by madness::FunctionImpl< T, NDIM >::apply_1d_realspace_push_op(), madness::Specialbox_op< T, NDIM >::box_is_at_boundary(), madness::FunctionImpl< T, NDIM >::broaden(), madness::FunctionImpl< T, NDIM >::child_patch(), madness::Key< NDIM >::distsq_bc(), madness::Key< NDIM >::distsq_bc(), madness::DerivativeBase< T, NDIM >::do_diff1(), madness::Derivative< T, NDIM >::do_diff2b(), madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::FunctionImpl< T, NDIM >::do_print_tree_graphviz(), madness::FunctionImpl< T, NDIM >::do_print_tree_json(), madness::FunctionImpl< T, NDIM >::eval(), madness::FunctionImpl< T, NDIM >::eval_local_only(), madness::FunctionImpl< T, NDIM >::evaldepthpt(), madness::FunctionImpl< T, NDIM >::evalR(), madness::Key< NDIM >::extract_back(), madness::Key< NDIM >::extract_front(), madness::Key< NDIM >::extract_key(), madness::fcube(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), madness::FunctionImpl< T, NDIM >::get_contraction_node_lists(), madness::SeparatedConvolution< Q, NDIM >::getmuop(), madness::SeparatedConvolution< Q, NDIM >::getmuop_modified(), madness::SimpleCache< Q, NDIM >::getptr(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), madness::Key< NDIM >::is_farther_out_than(), madness::TwoElectronInterface< T, NDIM >::make_coeff(), madness::Key< NDIM >::merge_with(), madness::Convolution1D< Q >::mod_nonstandard(), madness::Key< NDIM >::neighbor(), madness::FunctionImpl< T, NDIM >::neighbor(), madness::DerivativeBase< T, NDIM >::neighbor(), madness::Key< NDIM >::neighbor(), madness::FunctionImpl< T, NDIM >::neighbor_in_volume(), madness::MyPmap< D >::not_so_simple_hash(), madness::FunctionImpl< T, NDIM >::NS_fcube_for_mul(), YetAnotherWrapperClass::operator()(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::do_mapdim::operator()(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), madness::operator<<(), madness::SeparatedConvolution< Q, NDIM >::partial_upsample(), madness::FunctionImpl< T, NDIM >::print_plane_local(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), madness::SimpleCache< Q, NDIM >::set(), madness::SeparatedConvolution< Q, NDIM >::upsample(), madness::FunctionImpl< T, NDIM >::upsample(), write_function_coeffs(), and FunctionIO< T, NDIM >::write_function_coeffs().
Friends And Related Symbol Documentation
KeyChildIterator< NDIM >
template<std::size_t NDIM> friend class KeyChildIterator< NDIM > friend
Member Data Documentation
hashval
template<std::size_t NDIM> hashT Key::hashval private
Referenced by Key::Key(), madness::Key< NDIM >::hash(), Key::hash(), madness::Key< NDIM >::operator<(), Key::operator==(), madness::Key< NDIM >::operator==(), madness::Key< NDIM >::rehash(), and Key::serialize().
l
template<std::size_t NDIM> Vector<Translation, NDIM> madness::Key< NDIM >::l private
Referenced by madness::Key< NDIM >::break_apart(), madness::Key< NDIM >::distsq(), madness::Key< NDIM >::invalid(), madness::Key< NDIM >::is_farther_out_than(), madness::Key< NDIM >::is_neighbor_of(), madness::Key< NDIM >::neighbor(), madness::Key< NDIM >::neighbor(), madness::Key< NDIM >::operator<(), madness::Key< NDIM >::operator==(), madness::Key< NDIM >::operator[](), madness::Key< NDIM >::parent(), madness::Key< NDIM >::rehash(), madness::Key< NDIM >::thisKeyContains(), and madness::Key< NDIM >::translation().
n
template<std::size_t NDIM> ulong Key::n private
Referenced by madness::Key< NDIM >::Key(), madness::Key< NDIM >::Key(), Key::Key(), madness::Key< NDIM >::break_apart(), Key::foreach_child(), madness::Key< NDIM >::invalid(), madness::Key< NDIM >::is_child_of(), madness::Key< NDIM >::is_invalid(), madness::Key< NDIM >::is_neighbor_of(), madness::Key< NDIM >::is_valid(), madness::Key< NDIM >::level(), madness::Key< NDIM >::operator<(), operator<<(), Key::operator==(), madness::Key< NDIM >::operator==(), Key::parent(), madness::Key< NDIM >::parent(), Node::random_insert(), Node::recursive_print(), madness::Key< NDIM >::rehash(), Key::serialize(), and madness::Key< NDIM >::thisKeyContains().
static_size
template<std::size_t NDIM> const std::size_t madness::Key< NDIM >::static_size = NDIM static
The documentation for this class was generated from the following files:
key.h
test_world.cc