MADNESS: Foo Class Reference
Foo Class Reference
Public Member Functions
Foo (World &world, int a)
Foo (World &world, int bar)
virtual ~Foo ()
virtual ~Foo ()
const std::vector< double > & dbuf () const
const std::vector< double > & dbuf_long () const
const std::vector< double > & dbuf_short () const
decltype(auto) get () const
int get0 ()
int get0c () const
Future< int > get0f ()
int get1 (int a1)
int get1c (int a1) const
int get2 (int a1, char a2)
int get2c (int a1, char a2) const
int get3 (int a1, char a2, short a3)
int get3c (int a1, char a2, short a3) const
int get4 (int a1, char a2, short a3, long a4)
int get4c (int a1, char a2, short a3, long a4) const
int get5 (int a1, char a2, short a3, long a4, short a5)
int get5c (int a1, char a2, short a3, long a4, short a5) const
double getbuf0 (const std::vector< double > &buf)
double getbuf0c (const std::vector< double > &buf) const
void ping (int from, int speed)
void ping_am (int from, int speed)
void pong (int from, int speed)
void pong_am (int from, int speed)
Public Member Functions inherited from madness::WorldObject< Foo >
WorldObject (const WorldObject &other)
WorldObject (World &world)
Constructor that associates an object (via the derived class) with a globally unique ID.
virtual ~WorldObject ()
World & get_world () const
Returns a reference to the world.
const uniqueidT & id () const
Returns the globally unique object ID.
WorldObject & operator= (const WorldObject &)=delete
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9) const
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8,a9).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)().
Public Member Functions inherited from madness::WorldObjectBase
virtual ~WorldObjectBase ()=default
Private Attributes
int a
std::vector< int > bar
std::vector< double > dbuf_long_
std::vector< double > dbuf_short_
Additional Inherited Members
Public Types inherited from madness::WorldObject< Foo >
typedef WorldObject< Foo > objT
Protected Member Functions inherited from madness::WorldObject< Foo >
void process_pending ()
To be called from derived constructor to process pending messages.
Constructor & Destructor Documentation
Foo() [1/2]
Foo::Foo (World & world, int bar) inline
References madness::WorldObject< Foo >::process_pending().
~Foo() [1/2]
virtual Foo::~Foo () inline virtual
Foo() [2/2]
Foo::Foo (World & world, int a) inline
References dbuf_long_, dbuf_short_, madness::RMI::max_msg_len(), madness::World::nproc(), madness::WorldObject< Foo >::process_pending(), and madness::WorldObject< Foo >::world.
~Foo() [2/2]
virtual Foo::~Foo () inline virtual
Member Function Documentation
dbuf()
const std::vector< double > & Foo::dbuf () const inline
References dbuf_long().
dbuf_long()
const std::vector< double > & Foo::dbuf_long () const inline
References dbuf_long_.
Referenced by dbuf().
dbuf_short()
const std::vector< double > & Foo::dbuf_short () const inline
References dbuf_short_.
get()
decltype(auto) Foo::get () const inline
References bar.
Referenced by main().
get0()
int Foo::get0 () inline
References a.
Referenced by test6().
get0c()
int Foo::get0c () const inline
References a.
Referenced by test6().
get0f()
Future< int > Foo::get0f () inline
References a.
Referenced by test6().
get1()
int Foo::get1 (int a1) inline
References a, and a1.
Referenced by test6().
get1c()
int Foo::get1c (int a1) const inline
References a, and a1.
Referenced by test6().
get2()
int Foo::get2 (int a1, char a2) inline
References a, a1, and a2.
Referenced by test6().
get2c()
int Foo::get2c (int a1, char a2) const inline
References a, a1, and a2.
Referenced by test6().
get3()
int Foo::get3 (int a1, char a2, short a3) inline
References a, a1, and a2.
Referenced by test6().
get3c()
int Foo::get3c (int a1, char a2, short a3) const inline
References a, a1, and a2.
Referenced by test6().
get4()
int Foo::get4 (int a1, char a2, short a3, long a4) inline
References a, a1, and a2.
Referenced by test6().
get4c()
int Foo::get4c (int a1, char a2, short a3, long a4) const inline
References a, a1, and a2.
Referenced by test6().
get5()
int Foo::get5 (int a1, char a2, short a3, long a4, short a5) inline
References a, a1, and a2.
Referenced by test6().
get5c()
int Foo::get5c (int a1, char a2, short a3, long a4, short a5) const inline
References a, a1, and a2.
Referenced by test6().
getbuf0()
double Foo::getbuf0 (const std::vector< double > & buf) inline
References a.
Referenced by test6().
getbuf0c()
double Foo::getbuf0c (const std::vector< double > & buf) const inline
References a.
Referenced by test6().
ping()
void Foo::ping (int from, int speed) inline
References madness::WorldObject< Foo >::get_world(), pong(), madness::print(), and madness::WorldObject< Foo >::task().
Referenced by pong(), and test6().
ping_am()
void Foo::ping_am (int from, int speed) inline
References madness::WorldObject< Foo >::get_world(), pong_am(), madness::print(), and madness::WorldObject< Foo >::send().
Referenced by pong_am(), and test6().
pong()
void Foo::pong (int from, int speed) inline
References madness::WorldObject< Foo >::get_world(), ping(), madness::print(), and madness::WorldObject< Foo >::task().
Referenced by ping().
pong_am()
void Foo::pong_am (int from, int speed) inline
References madness::WorldObject< Foo >::get_world(), ping_am(), madness::print(), and madness::WorldObject< Foo >::send().
Referenced by ping_am().
Member Data Documentation
a
int Foo::a private
Referenced by get0(), get0c(), get0f(), get1(), get1c(), get2(), get2c(), get3(), get3c(), get4(), get4c(), get5(), get5c(), getbuf0(), and getbuf0c().
bar
std::vector<int> Foo::bar private
Referenced by get().
dbuf_long_
std::vector<double> Foo::dbuf_long_ private
Referenced by Foo(), and dbuf_long().
dbuf_short_
std::vector<double> Foo::dbuf_short_ private
Referenced by Foo(), and dbuf_short().
The documentation for this class was generated from the following files:
test_future3.cc
test_world.cc