MADNESS: madness::CubicInterpolationTable< T > Class Template Reference
madness::CubicInterpolationTable< T > Class Template Reference
An class for 1-D data interpolation based on cubic polynomials.
#include <interpolation_1d.h>
Public Member Functions
CubicInterpolationTable ()
template<typename functionT >
CubicInterpolationTable (double lo, double hi, int npt, const functionT &f)
CubicInterpolationTable (double lo, double hi, int npt, const std::vector< T > &y)
CubicInterpolationTable (std::vector< T > x, std::vector< T > y)
template<typename functionT >
CubicInterpolationTable (World &world, double lo, double hi, int npt, const functionT &f, const int min_npts_per_task=min_npts_per_task_default)
virtual ~CubicInterpolationTable ()
template<typename functionT >
double err (const functionT &f) const
double get_hi () const
double get_lo () const
T operator() (double y) const
Static Public Attributes
static int min_npts_per_task_default = 1024
minimum # of points per task
Protected Member Functions
template<typename functionT >
CubicInterpolationTable (World *world_ptr, double lo, double hi, int npt, const functionT &f, const int min_npts_per_task=std::numeric_limits< double >::max())
void make_interpolation (const std::vector< double > &x, const std::vector< T > &p, const int npts_per_task=std::numeric_limits< int >::max() - 1, World *world_ptr=nullptr)
Static Protected Member Functions
static void cubic_fit (const double *x, const T *f, T *a)
Grid points. Only stored if not evenly spaced. Empty otherwise.
Protected Attributes
std::vector< T > a
double h
Below variables meaningful if user does specifies uniform spacing.
double hi
Interpolation is in range [lo,hi].
double lo
Interpolation is in range [lo,hi].
int npt
No. of grid points.
std::vector< double > pts_
Below variables meaningful if user provides grid points.
double rh
Detailed Description
template<typename T>
class madness::CubicInterpolationTable< T >
An class for 1-D data interpolation based on cubic polynomials.
Needs to be passed the endpoints of the interpolation: [lo,hi] and the number of grid points.
Two methods for generating the interpolation are presently supported: 1) Pass in a std::vector containing the y-points. 2) Pass in some object that provides an appropriate () operator, perhaps a function pointer.
Constructor & Destructor Documentation
CubicInterpolationTable() [1/6]
template<typename T > template<typename functionT > madness::CubicInterpolationTable< T >::CubicInterpolationTable (World * world_ptr, double lo, double hi, int npt, const functionT & f, const int min_npts_per_task = std::numeric_limits<double>::max()) inline protected
constructs the interpolation table using optional tasking
Parameters
world_ptr pointer to the World object whose local taskq to use for tasking; if null, will compute serially
lo the lower bound of the interpolation interval
up the upper bound of the interpolation interval
npt the number of interpolation points
[in] f a T(T) callable; should be reentrant if npt is less than min_npts_per_task
[in] min_npts_per_task if npt is greater than this and there is more than 1 thread will use tasks
Warning
computes data locally even if world has more than 1 rank
References madness::WorldTaskQueue::add(), madness::f, madness::WorldTaskQueue::fence(), madness::CubicInterpolationTable< T >::h, madness::CubicInterpolationTable< T >::make_interpolation(), madness::CubicInterpolationTable< T >::npt, p(), madness::ThreadPool::size(), task(), and madness::World::taskq.
CubicInterpolationTable() [2/6]
template<typename T > madness::CubicInterpolationTable< T >::CubicInterpolationTable () inline
CubicInterpolationTable() [3/6]
template<typename T > template<typename functionT > madness::CubicInterpolationTable< T >::CubicInterpolationTable (double lo, double hi, int npt, const functionT & f) inline
constructs the interpolation table serially
Parameters
lo the lower bound of the interpolation interval
up the upper bound of the interpolation interval
npt the number of interpolation points
[in] f a T(T) callable; should be reentrant if npt is less than min_npts_per_task
[in] min_npts_per_task if npt is greater than this and there is more than 1 thread will use tasks
CubicInterpolationTable() [4/6]
template<typename T > template<typename functionT > madness::CubicInterpolationTable< T >::CubicInterpolationTable (World & world, double lo, double hi, int npt, const functionT & f, const int min_npts_per_task = min_npts_per_task_default) inline
constructs the interpolation table using optional tasking
Parameters
world the World object whose local taskq to use for tasking
lo the lower bound of the interpolation interval
up the upper bound of the interpolation interval
npt the number of interpolation points
[in] f a T(T) callable; should be reentrant if npt is less than min_npts_per_task
[in] min_npts_per_task if npt is greater than this and there is more than 1 thread will use tasks
Warning
computes data locally even if world has more than 1 rank
CubicInterpolationTable() [5/6]
template<typename T > madness::CubicInterpolationTable< T >::CubicInterpolationTable (std::vector< T > x, std::vector< T > y) inline
References madness::CubicInterpolationTable< T >::hi, madness::CubicInterpolationTable< T >::lo, madness::CubicInterpolationTable< T >::make_interpolation(), and madness::CubicInterpolationTable< T >::pts_.
CubicInterpolationTable() [6/6]
template<typename T > madness::CubicInterpolationTable< T >::CubicInterpolationTable (double lo, double hi, int npt, const std::vector< T > & y) inline
References madness::CubicInterpolationTable< T >::h, madness::CubicInterpolationTable< T >::lo, madness::CubicInterpolationTable< T >::make_interpolation(), and madness::CubicInterpolationTable< T >::npt.
~CubicInterpolationTable()
template<typename T > virtual madness::CubicInterpolationTable< T >::~CubicInterpolationTable () inline virtual
Member Function Documentation
cubic_fit()
template<typename T > static void madness::CubicInterpolationTable< T >::cubic_fit (const double * x, const T * f, T * a) inline static protected
Grid points. Only stored if not evenly spaced. Empty otherwise.
References madness::CubicInterpolationTable< T >::a, and madness::f.
Referenced by madness::CubicInterpolationTable< T >::make_interpolation().
err()
template<typename T > template<typename functionT > double madness::CubicInterpolationTable< T >::err (const functionT & f) const inline
References exact, madness::f, fit(), madness::CubicInterpolationTable< T >::h, madness::CubicInterpolationTable< T >::lo, madness::CubicInterpolationTable< T >::npt, madness::CubicInterpolationTable< T >::pts_, and T().
get_hi()
template<typename T > double madness::CubicInterpolationTable< T >::get_hi () const inline
References madness::CubicInterpolationTable< T >::hi.
get_lo()
template<typename T > double madness::CubicInterpolationTable< T >::get_lo () const inline
References madness::CubicInterpolationTable< T >::lo.
make_interpolation()
template<typename T > void madness::CubicInterpolationTable< T >::make_interpolation (const std::vector< double > & x, const std::vector< T > & p, const int npts_per_task = std::numeric_limits<int>::max() - 1, World * world_ptr = nullptr) inline protected
References madness::CubicInterpolationTable< T >::a, madness::CubicInterpolationTable< T >::cubic_fit(), madness::CubicInterpolationTable< T >::npt, p(), and task().
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::CubicInterpolationTable(), and madness::CubicInterpolationTable< T >::CubicInterpolationTable().
operator()()
template<typename T > T madness::CubicInterpolationTable< T >::operator() (double y) const inline
References madness::CubicInterpolationTable< T >::a, madness::CubicInterpolationTable< T >::hi, madness::CubicInterpolationTable< T >::lo, madness::CubicInterpolationTable< T >::npt, madness::CubicInterpolationTable< T >::pts_, madness::CubicInterpolationTable< T >::rh, and T().
Member Data Documentation
a
template<typename T > std::vector<T> madness::CubicInterpolationTable< T >::a protected
(1+4)*npt vector of x and polynomial coefficients
Referenced by madness::CubicInterpolationTable< T >::cubic_fit(), madness::CubicInterpolationTable< T >::make_interpolation(), and madness::CubicInterpolationTable< T >::operator()().
h
template<typename T > double madness::CubicInterpolationTable< T >::h protected
Below variables meaningful if user does specifies uniform spacing.
Grid spacing.
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::CubicInterpolationTable(), and madness::CubicInterpolationTable< T >::err().
hi
template<typename T > double madness::CubicInterpolationTable< T >::hi protected
Interpolation is in range [lo,hi].
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::get_hi(), and madness::CubicInterpolationTable< T >::operator()().
lo
template<typename T > double madness::CubicInterpolationTable< T >::lo protected
Interpolation is in range [lo,hi].
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::err(), madness::CubicInterpolationTable< T >::get_lo(), and madness::CubicInterpolationTable< T >::operator()().
min_npts_per_task_default
template<typename T > int madness::CubicInterpolationTable< T >::min_npts_per_task_default = 1024 static
minimum # of points per task
npt
template<typename T > int madness::CubicInterpolationTable< T >::npt protected
No. of grid points.
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::err(), madness::CubicInterpolationTable< T >::make_interpolation(), and madness::CubicInterpolationTable< T >::operator()().
pts_
template<typename T > std::vector<double> madness::CubicInterpolationTable< T >::pts_ protected
Below variables meaningful if user provides grid points.
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::CubicInterpolationTable< T >::err(), and madness::CubicInterpolationTable< T >::operator()().
rh
template<typename T > double madness::CubicInterpolationTable< T >::rh protected
1/h
Referenced by madness::CubicInterpolationTable< T >::operator()().
The documentation for this class was generated from the following file:
interpolation_1d.h