MADNESS: madness::CorePotentialManager Class Reference
madness::CorePotentialManager Class Reference
#include <corepotential.h>
Public Member Functions
CorePotentialManager ()
CorePotentialManager (std::string filename, double eprec)
double core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const
double core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const
AtomCore get_atom_core (unsigned int atn) const
double get_core_bc (unsigned int atn, unsigned int core) const
unsigned int get_core_l (unsigned int atn, unsigned int core) const
CorePotential get_potential (unsigned int atn) const
std::string guess_file () const
bool is_defined (const unsigned int atn) const
unsigned int n_core_orb (const unsigned int atn) const
unsigned int n_core_orb_base (const unsigned int atn) const
double potential (unsigned int atn, double r) const
double potential_derivative (unsigned int atn, double xi, double r) const
void read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
template<typename Archive >
void serialize (Archive &ar)
void set_eprec (double value)
void set_rcut (double value)
Private Attributes
std::map< unsigned int, AtomCore > atom_core
core potential data mapped atn to potential
std::string core_type
core potential type (eg. mcp)
std::string guess_filename
filename of initial guess density data
Static Private Attributes
static const double fc = 2.0
Constructor & Destructor Documentation
CorePotentialManager() [1/2]
madness::CorePotentialManager::CorePotentialManager () inline
CorePotentialManager() [2/2]
madness::CorePotentialManager::CorePotentialManager (std::string filename, double eprec) inline
References eprec, madness::filename, and read_file().
Member Function Documentation
core_derivative()
double madness::CorePotentialManager::core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const inline
References axis, get_atom_core(), m, madness::AtomCore::orbital, and xi.
Referenced by madness::Molecule::core_derivative().
core_eval()
double madness::CorePotentialManager::core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const inline
References get_atom_core(), m, and madness::AtomCore::orbital.
Referenced by madness::Molecule::core_eval(), and CoreOrbitalFunctor::operator()().
get_atom_core()
AtomCore madness::CorePotentialManager::get_atom_core (unsigned int atn) const inline
References atom_core.
Referenced by core_derivative(), core_eval(), get_core_bc(), and get_core_l().
get_core_bc()
double madness::CorePotentialManager::get_core_bc (unsigned int atn, unsigned int core) const inline
References fc, get_atom_core(), and madness::AtomCore::orbital.
Referenced by madness::Molecule::get_core_bc(), and Calculation::make_reference().
get_core_l()
unsigned int madness::CorePotentialManager::get_core_l (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and madness::AtomCore::orbital.
Referenced by madness::Molecule::get_core_l(), and Calculation::make_reference().
get_potential()
CorePotential madness::CorePotentialManager::get_potential (unsigned int atn) const inline
References atom_core.
Referenced by main().
guess_file()
std::string madness::CorePotentialManager::guess_file () const inline
References guess_filename.
Referenced by madness::Molecule::guess_file().
is_defined()
bool madness::CorePotentialManager::is_defined (const unsigned int atn) const inline
References atom_core.
Referenced by Calculation::Calculation(), madness::Molecule::is_potential_defined(), madness::Molecule::is_potential_defined_atom(), madness::Molecule::molecular_core_potential(), madness::Molecule::n_core_orb(), madness::Molecule::n_core_orb_all(), madness::Molecule::nuclear_dipole(), madness::Molecule::nuclear_repulsion_derivative(), madness::Molecule::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_second_derivative(), and madness::Molecule::read_core_file().
n_core_orb()
unsigned int madness::CorePotentialManager::n_core_orb (const unsigned int atn) const inline
References atom_core.
Referenced by Calculation::Calculation(), madness::Molecule::n_core_orb_all(), madness::Molecule::nuclear_dipole(), madness::Molecule::nuclear_repulsion_derivative(), madness::Molecule::nuclear_repulsion_energy(), and madness::Molecule::read_core_file().
n_core_orb_base()
unsigned int madness::CorePotentialManager::n_core_orb_base (const unsigned int atn) const inline
References atom_core.
Referenced by madness::Molecule::n_core_orb().
potential()
double madness::CorePotentialManager::potential (unsigned int atn, double r) const inline
References atom_core, madness::CorePotential::eval(), and madness::AtomCore::potential.
Referenced by madness::Molecule::molecular_core_potential().
potential_derivative()
double madness::CorePotentialManager::potential_derivative (unsigned int atn, double xi, double r) const inline
References atom_core, madness::CorePotential::eval_derivative(), madness::AtomCore::potential, and xi.
Referenced by madness::Molecule::core_potential_derivative().
read_file()
void madness::CorePotentialManager::read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
References atom_core, core_type, madness::dir, eprec, madness::filename, guess_filename, MADNESS_EXCEPTION, madness::AtomCore::n_orbital(), madness::print(), madness::read_atom(), and madness::symbol_to_atomic_number().
Referenced by Calculation::Calculation(), CorePotentialManager(), and madness::Molecule::read_core_file().
serialize()
template<typename Archive > void madness::CorePotentialManager::serialize (Archive & ar) inline
References atom_core, core_type, and guess_filename.
set_eprec()
void madness::CorePotentialManager::set_eprec (double value)
References atom_core, q(), and madness::smoothing_parameter().
Referenced by madness::Molecule::set_core_eprec(), and madness::Molecule::update_rcut_with_eprec().
set_rcut()
void madness::CorePotentialManager::set_rcut (double value)
References atom_core.
Referenced by madness::Molecule::set_core_rcut().
Member Data Documentation
atom_core
std::map<unsigned int,AtomCore> madness::CorePotentialManager::atom_core private
core potential data mapped atn to potential
Referenced by get_atom_core(), get_potential(), is_defined(), n_core_orb(), n_core_orb_base(), potential(), potential_derivative(), read_file(), serialize(), set_eprec(), and set_rcut().
core_type
std::string madness::CorePotentialManager::core_type private
core potential type (eg. mcp)
Referenced by read_file(), and serialize().
fc
const double madness::CorePotentialManager::fc = 2.0 static private
Referenced by get_core_bc().
guess_filename
std::string madness::CorePotentialManager::guess_filename private
filename of initial guess density data
Referenced by guess_file(), read_file(), and serialize().
The documentation for this class was generated from the following files:
corepotential.h
corepotential.cc