MADNESS: madness::MacroTaskQFactory Class Reference
madness::MacroTaskQFactory Class Reference
Factory for the MacroTaskQ.
#include <macrotaskq.h>
Public Member Functions
MacroTaskQFactory (World &universe)
MacroTaskQFactory & preset (const std::string name)
MacroTaskQFactory & set_cloud_distribution_policy (const DistributionType dp)
MacroTaskQFactory & set_nworld (const long n)
MacroTaskQFactory & set_policy (const MacroTaskInfo p)
MacroTaskQFactory & set_printlevel (const long p)
MacroTaskQFactory & set_ptr_target_distribution_policy (const DistributionType dp)
MacroTaskQFactory & set_storage_policy (const MacroTaskInfo::StoragePolicy sp)
Public Attributes
long nworld =1
MacroTaskInfo policy =MacroTaskInfo::preset("default")
long printlevel =0
World & world
Detailed Description
Factory for the MacroTaskQ.
Constructor & Destructor Documentation
MacroTaskQFactory()
madness::MacroTaskQFactory::MacroTaskQFactory (World & universe) inline
Member Function Documentation
preset()
MacroTaskQFactory & madness::MacroTaskQFactory::preset (const std::string name) inline
set_cloud_distribution_policy()
MacroTaskQFactory & madness::MacroTaskQFactory::set_cloud_distribution_policy (const DistributionType dp) inline
References madness::MacroTaskInfo::cloud_distribution_policy, and policy.
set_nworld()
MacroTaskQFactory & madness::MacroTaskQFactory::set_nworld (const long n) inline
References nworld.
set_policy()
MacroTaskQFactory & madness::MacroTaskQFactory::set_policy (const MacroTaskInfo p) inline
References p(), and policy.
set_printlevel()
MacroTaskQFactory & madness::MacroTaskQFactory::set_printlevel (const long p) inline
References p(), and printlevel.
set_ptr_target_distribution_policy()
MacroTaskQFactory & madness::MacroTaskQFactory::set_ptr_target_distribution_policy (const DistributionType dp) inline
References policy, and madness::MacroTaskInfo::ptr_target_distribution_policy.
set_storage_policy()
MacroTaskQFactory & madness::MacroTaskQFactory::set_storage_policy (const MacroTaskInfo::StoragePolicy sp) inline
References policy, and madness::MacroTaskInfo::storage_policy.
Member Data Documentation
nworld
long madness::MacroTaskQFactory::nworld =1
Referenced by set_nworld().
policy
MacroTaskInfo madness::MacroTaskQFactory::policy =MacroTaskInfo::preset("default")
Referenced by set_cloud_distribution_policy(), set_policy(), set_ptr_target_distribution_policy(), and set_storage_policy().
printlevel
long madness::MacroTaskQFactory::printlevel =0
Referenced by set_printlevel().
world
World& madness::MacroTaskQFactory::world
The documentation for this class was generated from the following file:
macrotaskq.h