MADNESS: madness::CCFunction< T, NDIM > Class Template Reference
madness::CCFunction< T, NDIM > Class Template Reference
structure for a CC Function 3D which holds an index and a type
#include <ccpairfunction.h>
Public Member Functions
CCFunction ()
CCFunction (const CCFunction &other)
CCFunction (const Function< T, NDIM > &f)
CCFunction (const Function< T, NDIM > &f, const size_t &ii, const FuncType &type_)
Function< T, NDIM > f () const
Function< T, NDIM > get () const
void info (World &world, const std::string &msg=" ") const
double inner (const CCFunction &f) const
double inner (const Function< T, NDIM > &f) const
std::string name () const
CCFunction operator* (const double &fac) const
scalar multiplication
bool operator== (const CCFunction &other) const
void plot (const std::string &msg="") const
plotting
template<typename Archive >
void serialize (const Archive &ar)
void set (const Function< T, NDIM > &other)
Public Attributes
double current_error
Function< T, NDIM > function
size_t i
FuncType type
Friends
CCFunction copy (const CCFunction &other)
deep copy
Detailed Description
template<typename T = double, std::size_t NDIM = 3>
class madness::CCFunction< T, NDIM >
structure for a CC Function 3D which holds an index and a type
Constructor & Destructor Documentation
CCFunction() [1/4]
template<typename T = double, std::size_t NDIM = 3> madness::CCFunction< T, NDIM >::CCFunction () inline
Referenced by madness::CCFunction< T, NDIM >::operator*().
CCFunction() [2/4]
template<typename T = double, std::size_t NDIM = 3> madness::CCFunction< T, NDIM >::CCFunction (const Function< T, NDIM > & f) inline
CCFunction() [3/4]
template<typename T = double, std::size_t NDIM = 3> madness::CCFunction< T, NDIM >::CCFunction (const Function< T, NDIM > & f, const size_t & ii, const FuncType & type_) inline
CCFunction() [4/4]
template<typename T = double, std::size_t NDIM = 3> madness::CCFunction< T, NDIM >::CCFunction (const CCFunction< T, NDIM > & other) inline
Member Function Documentation
f()
template<typename T = double, std::size_t NDIM = 3> Function< T, NDIM > madness::CCFunction< T, NDIM >::f () const inline
References madness::CCFunction< T, NDIM >::function.
Referenced by madness::CCFunction< T, NDIM >::inner(), and madness::CCFunction< T, NDIM >::inner().
get()
template<typename T = double, std::size_t NDIM = 3> Function< T, NDIM > madness::CCFunction< T, NDIM >::get () const inline
References madness::CCFunction< T, NDIM >::function.
info()
template<typename T = double, std::size_t NDIM = 3> void madness::CCFunction< T, NDIM >::info (World & world, const std::string & msg = " ") const inline
References madness::CCFunction< T, NDIM >::current_error, madness::CCFunction< T, NDIM >::function, madness::CCFunction< T, NDIM >::name(), and madness::World::rank().
inner() [1/2]
template<typename T = double, std::size_t NDIM = 3> double madness::CCFunction< T, NDIM >::inner (const CCFunction< T, NDIM > & f) const inline
References madness::CCFunction< T, NDIM >::f(), and madness::CCFunction< T, NDIM >::inner().
Referenced by madness::CCFunction< T, NDIM >::inner().
inner() [2/2]
template<typename T = double, std::size_t NDIM = 3> double madness::CCFunction< T, NDIM >::inner (const Function< T, NDIM > & f) const inline
References madness::CCFunction< T, NDIM >::f(), and madness::CCFunction< T, NDIM >::function.
name()
template<typename T = double, std::size_t NDIM = 3> std::string madness::CCFunction< T, NDIM >::name () const inline
References madness::HOLE, madness::CCFunction< T, NDIM >::i, madness::MIXED, madness::PARTICLE, madness::RESPONSE, madness::stringify(), and madness::CCFunction< T, NDIM >::type.
Referenced by madness::CCFunction< T, NDIM >::info(), madness::CCConvolutionOperator< T, NDIM >::operator()(), and madness::CCFunction< T, NDIM >::plot().
operator*()
template<typename T = double, std::size_t NDIM = 3> CCFunction madness::CCFunction< T, NDIM >::operator* (const double & fac) const inline
scalar multiplication
References madness::CCFunction< T, NDIM >::CCFunction(), madness::CCFunction< T, NDIM >::function, madness::CCFunction< T, NDIM >::i, and madness::CCFunction< T, NDIM >::type.
operator==()
template<typename T = double, std::size_t NDIM = 3> bool madness::CCFunction< T, NDIM >::operator== (const CCFunction< T, NDIM > & other) const inline
References madness::CCFunction< T, NDIM >::i, and madness::CCFunction< T, NDIM >::type.
plot()
template<typename T = double, std::size_t NDIM = 3> void madness::CCFunction< T, NDIM >::plot (const std::string & msg = "") const inline
plotting
References madness::CCFunction< T, NDIM >::function, madness::CCFunction< T, NDIM >::name(), and madness::plot_plane().
serialize()
template<typename T = double, std::size_t NDIM = 3> template<typename Archive > void madness::CCFunction< T, NDIM >::serialize (const Archive & ar) inline
References madness::CCFunction< T, NDIM >::current_error, madness::CCFunction< T, NDIM >::function, madness::CCFunction< T, NDIM >::i, and madness::CCFunction< T, NDIM >::type.
set()
template<typename T = double, std::size_t NDIM = 3> void madness::CCFunction< T, NDIM >::set (const Function< T, NDIM > & other) inline
References madness::CCFunction< T, NDIM >::function.
Friends And Related Symbol Documentation
copy
template<typename T = double, std::size_t NDIM = 3> CCFunction copy (const CCFunction< T, NDIM > & other) friend
deep copy
Member Data Documentation
current_error
template<typename T = double, std::size_t NDIM = 3> double madness::CCFunction< T, NDIM >::current_error
Referenced by madness::CCFunction< T, NDIM >::info(), and madness::CCFunction< T, NDIM >::serialize().
function
template<typename T = double, std::size_t NDIM = 3> Function<T,NDIM> madness::CCFunction< T, NDIM >::function
Referenced by madness::CCPairFunction< T, NDIM >::dirac_convolution_decomposed(), madness::CCFunction< T, NDIM >::f(), madness::CCFunction< T, NDIM >::get(), madness::CCFunction< T, NDIM >::info(), madness::CCFunction< T, NDIM >::inner(), madness::CCPairFunction< T, NDIM >::make_xy_u(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::CCFunction< T, NDIM >::operator*(), madness::CCFunction< T, NDIM >::plot(), madness::CCFunction< T, NDIM >::serialize(), madness::CCFunction< T, NDIM >::set(), and madness::CCConvolutionOperator< T, NDIM >::update_elements().
i
template<typename T = double, std::size_t NDIM = 3> size_t madness::CCFunction< T, NDIM >::i
Referenced by madness::CCFunction< T, NDIM >::name(), madness::CC_vecfunction::operator()(), madness::CC_vecfunction::operator()(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::CCFunction< T, NDIM >::operator*(), madness::CCFunction< T, NDIM >::operator==(), madness::CCFunction< T, NDIM >::serialize(), and madness::CCConvolutionOperator< T, NDIM >::update_elements().
type
template<typename T = double, std::size_t NDIM = 3> FuncType madness::CCFunction< T, NDIM >::type
Referenced by madness::CCFunction< T, NDIM >::name(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::CCFunction< T, NDIM >::operator*(), madness::CCFunction< T, NDIM >::operator==(), and madness::CCFunction< T, NDIM >::serialize().
The documentation for this class was generated from the following file:
ccpairfunction.h