MADNESS: Fcwf Class Reference
Fcwf Class Reference
#include <fcwf.h>
Public Member Functions
Fcwf ()
Fcwf (const complex_function_3d &wf1, const complex_function_3d &wf2, const complex_function_3d &wf3, const complex_function_3d &wf4)
Fcwf (const Fcwf &phi)
Fcwf (std::vector< complex_function_3d > &phi)
Fcwf (World &world)
void apply (World &world, complex_derivative_3d &D)
void apply (World &world, real_convolution_3d &op)
void compress ()
bool getinitialize ()
bool getinitialize () const
std::complex< double > inner (World &world, const Fcwf &phi) const
Fcwf KramersPair ()
double norm2 ()
void normalize ()
Fcwf operator* (madness::complex_function_3d &phi)
Fcwf operator* (madness::real_function_3d &phi)
Fcwf operator* (std::complex< double > a) const
Fcwf operator+ (const Fcwf &phi)
Fcwf operator+= (const Fcwf &phi)
Fcwf operator- (const Fcwf &phi) const
Fcwf operator-= (const Fcwf &phi)
Fcwf operator= (const Fcwf &phi)
complex_function_3d & operator[] (const int i)
const complex_function_3d & operator[] (const int i) const
void reconstruct ()
void scale (std::complex< double > a)
unsigned int size ()
unsigned int size () const
void truncate ()
Private Attributes
bool m_initialized
std::vector< complex_function_3d > m_psi
Constructor & Destructor Documentation
Fcwf() [1/5]
Fcwf::Fcwf ()
References m_initialized.
Referenced by KramersPair(), operator*(), operator*(), operator*(), operator+(), and operator-().
Fcwf() [2/5]
Fcwf::Fcwf (const complex_function_3d & wf1, const complex_function_3d & wf2, const complex_function_3d & wf3, const complex_function_3d & wf4)
References m_initialized, m_psi, and MADNESS_ASSERT.
Fcwf() [3/5]
Fcwf::Fcwf (World & world)
References m_initialized, m_psi, and MADNESS_ASSERT.
Fcwf() [4/5]
Fcwf::Fcwf (std::vector< complex_function_3d > & phi) explicit
References m_initialized, m_psi, and MADNESS_ASSERT.
Fcwf() [5/5]
Fcwf::Fcwf (const Fcwf & phi)
References copy(), m_initialized, m_psi, MADNESS_ASSERT, and size().
Member Function Documentation
apply() [1/2]
void Fcwf::apply (World & world, complex_derivative_3d & D)
References madness::apply(), and m_psi.
apply() [2/2]
void Fcwf::apply (World & world, real_convolution_3d & op)
References madness::apply(), m_psi, and op().
Referenced by apply(), and apply().
compress()
void Fcwf::compress ()
References compress(), m_initialized, m_psi, and MADNESS_ASSERT.
Referenced by apply_T(), and compress().
getinitialize() [1/2]
bool Fcwf::getinitialize ()
References m_initialized.
Referenced by inner(), inner(), inner_func(), operator+(), operator+=(), operator-(), and operator-=().
getinitialize() [2/2]
bool Fcwf::getinitialize () const
References m_initialized.
inner()
std::complex< double > Fcwf::inner (World & world, const Fcwf & phi) const
References getinitialize(), madness::inner(), m_initialized, m_psi, and MADNESS_ASSERT.
KramersPair()
Fcwf Fcwf::KramersPair ()
References Fcwf(), madness::conj(), and m_psi.
norm2()
double Fcwf::norm2 ()
References madness::inner(), m_initialized, m_psi, and MADNESS_ASSERT.
Referenced by normalize().
normalize()
void Fcwf::normalize ()
References m_initialized, m_psi, MADNESS_ASSERT, norm(), and norm2().
Referenced by madness::InitParameters::read(), and madness::InitParameters::readnw().
operator*() [1/3]
Fcwf Fcwf::operator* (madness::complex_function_3d & phi)
References Fcwf(), m_initialized, m_psi, and MADNESS_ASSERT.
operator*() [2/3]
Fcwf Fcwf::operator* (madness::real_function_3d & phi)
References Fcwf(), m_initialized, m_psi, and MADNESS_ASSERT.
operator*() [3/3]
Fcwf Fcwf::operator* (std::complex< double > a) const
References Fcwf(), a, m_initialized, m_psi, and MADNESS_ASSERT.
operator+()
Fcwf Fcwf::operator+ (const Fcwf & phi)
References Fcwf(), copy(), getinitialize(), m_initialized, m_psi, and MADNESS_ASSERT.
operator+=()
Fcwf Fcwf::operator+= (const Fcwf & phi)
References copy(), getinitialize(), m_initialized, m_psi, and MADNESS_ASSERT.
operator-()
Fcwf Fcwf::operator- (const Fcwf & phi) const
References Fcwf(), copy(), getinitialize(), m_initialized, m_psi, and MADNESS_ASSERT.
operator-=()
Fcwf Fcwf::operator-= (const Fcwf & phi)
References copy(), getinitialize(), m_initialized, m_psi, MADNESS_ASSERT, and scale().
operator=()
Fcwf Fcwf::operator= (const Fcwf & phi)
References m_initialized, and m_psi.
operator[]() [1/2]
complex_function_3d & Fcwf::operator[] (const int i)
References m_initialized, m_psi, and MADNESS_ASSERT.
operator[]() [2/2]
const complex_function_3d & Fcwf::operator[] (const int i) const
References m_initialized, m_psi, and MADNESS_ASSERT.
reconstruct()
void Fcwf::reconstruct ()
References m_initialized, m_psi, MADNESS_ASSERT, and reconstruct().
Referenced by reconstruct().
scale()
void Fcwf::scale (std::complex< double > a)
References a, m_initialized, m_psi, and MADNESS_ASSERT.
Referenced by inner_func(), DF::iterate(), operator-=(), madness::InitParameters::read(), and madness::InitParameters::readnw().
size() [1/2]
unsigned int Fcwf::size ()
References m_initialized, m_psi, and MADNESS_ASSERT.
Referenced by Fcwf().
size() [2/2]
unsigned int Fcwf::size () const
References m_initialized, m_psi, and MADNESS_ASSERT.
truncate()
void Fcwf::truncate ()
References m_initialized, m_psi, and MADNESS_ASSERT.
Referenced by DF::iterate(), and main().
Member Data Documentation
m_initialized
bool Fcwf::m_initialized private
Referenced by Fcwf(), Fcwf(), Fcwf(), Fcwf(), Fcwf(), compress(), getinitialize(), getinitialize(), inner(), norm2(), normalize(), operator*(), operator*(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator[](), operator[](), reconstruct(), scale(), size(), size(), and truncate().
m_psi
std::vector<complex_function_3d> Fcwf::m_psi private
Referenced by Fcwf(), Fcwf(), Fcwf(), Fcwf(), apply(), apply(), compress(), inner(), KramersPair(), norm2(), normalize(), operator*(), operator*(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator[](), operator[](), reconstruct(), scale(), size(), size(), and truncate().
The documentation for this class was generated from the following files:
fcwf.h
fcwf.cc