MADNESS: madness::RMI Class Reference
madness::RMI Class Reference
This class implements the communications server thread and provides the only send interface.
#include <worldrmi.h>
Classes
class RmiTask
Public Types
typedef SafeMPI::Request Request
Static Public Member Functions
static void assert_aslr_off (const SafeMPI::Intracomm &comm=SafeMPI::COMM_WORLD)
static void begin (const SafeMPI::Intracomm &comm=SafeMPI::COMM_WORLD)
static void end ()
static bool get_debug ()
static const RMIStats & get_stats ()
static bool get_this_thread_is_server ()
static Request isend (const void *buf, size_t nbyte, ProcessID dest, rmi_handlerT func, unsigned int attr=ATTR_UNORDERED)
Send a remote method invocation (again you should probably be looking at worldam.h instead)
static std::size_t max_msg_len ()
Returns the size of recv buffers, in bytes.
static std::size_t maxq ()
static std::size_t nrecv ()
Returns the number of recv buffers.
static void set_debug (bool status)
static void set_this_thread_is_server (bool flag=true)
Static Public Attributes
static const size_t ALIGNMENT = 64
static const attrT ATTR_ORDERED =0x1
static const attrT ATTR_UNORDERED =0x0
static const size_t HEADER_LEN = ALIGNMENT
static std::list< std::unique_ptr< RMISendReq > > send_req
static int testsome_backoff_us = 2
Private Types
typedef qmsg::attrT attrT
typedef qmsg::counterT counterT
Private Member Functions
RMI (const RMI &)
RMI & operator= (const RMI &)
Static Private Member Functions
static void clear_send_req ()
static bool & is_server_thread_accessor ()
Static Private Attributes
static bool debugging = false
static const size_t DEFAULT_MAX_MSG_LEN = 3*512*1024
the default size of recv buffers, in bytes; the actual size can be configured by the user via envvar MAD_BUFFER_SIZE
static const int DEFAULT_NRECV = 128
the default # of recv buffers; the actual number can be configured by the user via envvar MAD_RECV_BUFFERS
static RMIStats stats
static std::unique_ptr< RmiTask > task_ptr = nullptr
Detailed Description
This class implements the communications server thread and provides the only send interface.
Member Typedef Documentation
attrT
typedef qmsg::attrT madness::RMI::attrT private
counterT
typedef qmsg::counterT madness::RMI::counterT private
Request
typedef SafeMPI::Request madness::RMI::Request
Constructor & Destructor Documentation
RMI()
madness::RMI::RMI (const RMI &) private
Member Function Documentation
assert_aslr_off()
void madness::RMI::assert_aslr_off (const SafeMPI::Intracomm & comm = SafeMPI::COMM_WORLD) static
will complain to std::cerr and throw if ASLR is on by making sure that address of this function matches across comm
Parameters
[in] comm the communicator
References assert_aslr_off(), madness::detail::compare_fn_addresses(), SafeMPI::Intracomm::Get_rank(), MADNESS_ASSERT, MADNESS_EXCEPTION, MPI_LONG, SafeMPI::Op_create(), SafeMPI::Op_free(), and SafeMPI::Intracomm::Reduce().
Referenced by assert_aslr_off(), and begin().
begin()
void madness::RMI::begin (const SafeMPI::Intracomm & comm = SafeMPI::COMM_WORLD) static
References assert_aslr_off(), MADNESS_ASSERT, madness::myusleep(), madness::rmi_task_is_running, task_ptr, madness::ThreadPool::tbb_arena, and testsome_backoff_us.
clear_send_req()
static void madness::RMI::clear_send_req () inline static private
References madness::RMIStats::max_serv_send_q, send_req, and stats.
Referenced by madness::RMI::RmiTask::process_some().
end()
static void madness::RMI::end () inline static
References task_ptr.
get_debug()
static bool madness::RMI::get_debug () inline static
References debugging.
get_stats()
static const RMIStats & madness::RMI::get_stats () inline static
References stats.
Referenced by madness::WorldProfileObj::~WorldProfileObj(), and madness::print_stats().
get_this_thread_is_server()
static bool madness::RMI::get_this_thread_is_server () inline static
References is_server_thread_accessor().
Referenced by madness::WorldAmInterface::send().
is_server_thread_accessor()
bool & madness::RMI::is_server_thread_accessor () static private
Returns
reference to the boolean variable indicating whether this thread is the server thread
Referenced by get_this_thread_is_server(), and set_this_thread_is_server().
isend()
static Request madness::RMI::isend (const void * buf, size_t nbyte, ProcessID dest, rmi_handlerT func, unsigned int attr = ATTR_UNORDERED) inline static
Send a remote method invocation (again you should probably be looking at worldam.h instead)
Parameters
[in] buf Pointer to the data buffer (do not modify until send is completed)
[in] nbyte Size of the data in bytes
[in] dest Process to receive the message
[in] func The function to handle the message on the remote end
[in] attr Attributes of the message (ATTR_UNORDERED or ATTR_ORDERED)
Returns
The status as an RMI::Request that presently is a SafeMPI::Request
References madness::func(), MADNESS_EXCEPTION, madness::print_error(), and task_ptr.
Referenced by madness::WorldAmInterface::send().
max_msg_len()
static std::size_t madness::RMI::max_msg_len () inline static
Returns the size of recv buffers, in bytes.
Returns
The size of recv buffers, in bytes
Note
The default value is given by RMI::DEFAULT_MAX_MSG_LEN, can be overridden at runtime by the user via environment variable MAD_BUFFER_SIZE.
Warning
Cannot be smaller than 1024 bytes.
References MADNESS_ASSERT, and task_ptr.
Referenced by madness::BinSorter< T, inserterT >::BinSorter(), and Foo::Foo().
maxq()
static std::size_t madness::RMI::maxq () inline static
References MADNESS_ASSERT, and task_ptr.
nrecv()
static std::size_t madness::RMI::nrecv () inline static
Returns the number of recv buffers.
Returns
The number of recv buffers
Note
The default value is given by RMI::DEFAULT_NRECV, can be overridden at runtime by the user via environment variable MAD_RECV_BUFFERS
Warning
Cannot be smaller than 32.
References MADNESS_ASSERT, and task_ptr.
operator=()
RMI & madness::RMI::operator= (const RMI &) private
set_debug()
static void madness::RMI::set_debug (bool status) inline static
References debugging, and status.
set_this_thread_is_server()
static void madness::RMI::set_this_thread_is_server (bool flag = true) inline static
References is_server_thread_accessor().
Referenced by madness::RMI::RmiTask::run().
Member Data Documentation
ALIGNMENT
const size_t madness::RMI::ALIGNMENT = 64 static
Referenced by madness::RMI::RmiTask::RmiTask(), and madness::RMI::RmiTask::post_pending_huge_msg().
ATTR_ORDERED
const attrT madness::RMI::ATTR_ORDERED =0x1 static
Referenced by madness::RMI::RmiTask::is_ordered().
ATTR_UNORDERED
const attrT madness::RMI::ATTR_UNORDERED =0x0 static
Referenced by madness::WorldGopInterface::bcast_task(), madness::WorldGopInterface::group_bcast_task(), madness::WorldObject< Derived >::send_task(), and madness::WorldTaskQueue::send_task().
debugging
bool madness::RMI::debugging = false static private
Referenced by madness::RMI::RmiTask::exit(), get_debug(), madness::RMI::RmiTask::process_some(), and set_debug().
DEFAULT_MAX_MSG_LEN
const size_t madness::RMI::DEFAULT_MAX_MSG_LEN = 3*512*1024 static private
the default size of recv buffers, in bytes; the actual size can be configured by the user via envvar MAD_BUFFER_SIZE
Referenced by madness::RMI::RmiTask::RmiTask().
DEFAULT_NRECV
const int madness::RMI::DEFAULT_NRECV = 128 static private
the default # of recv buffers; the actual number can be configured by the user via envvar MAD_RECV_BUFFERS
Referenced by madness::RMI::RmiTask::RmiTask().
HEADER_LEN
const size_t madness::RMI::HEADER_LEN = ALIGNMENT static
Referenced by madness::RMI::RmiTask::huge_msg_handler().
send_req
std::list< std::unique_ptr< RMISendReq > > madness::RMI::send_req static
Referenced by clear_send_req(), and madness::WorldAmInterface::send().
stats
RMIStats madness::RMI::stats static private
Referenced by clear_send_req(), get_stats(), and madness::RMI::RmiTask::process_some().
task_ptr
std::unique_ptr< RMI::RmiTask > madness::RMI::task_ptr = nullptr static private
Referenced by begin(), end(), madness::RMI::RmiTask::huge_msg_handler(), isend(), max_msg_len(), maxq(), and nrecv().
testsome_backoff_us
int madness::RMI::testsome_backoff_us = 2 static
Referenced by begin(), and madness::RMI::RmiTask::process_some().
The documentation for this class was generated from the following files:
worldrmi.h
worldrmi.cc