MADNESS: TestCalculationParameters Class Reference
TestCalculationParameters Class Reference
helper class to set up a vector of possible values for a given key
Public Member Functions
TestCalculationParameters (const CalculationParameters &cp)
CalculationParameters copy_and_replace_key_in_parameters (const CalculationParameters &ref_parameters, const std::string &key, int index) const
template<typename T >
void extend_parameters (const std::string &key, std::vector< T > values)
std::size_t get_parameter_range (const std::string &key) const
std::vector< CalculationParameters > make_all_parameter_doubles () const
std::vector< CalculationParameters > make_all_parameter_singles () const
std::vector< CalculationParameters > make_all_parameters_for_one_key (const std::string &key) const
std::vector< CalculationParameters > make_all_parameters_for_two_keys (const std::string &key1, const std::string &key2) const
Public Member Functions inherited from madness::CalculationParameters
CalculationParameters ()
ctor reading out the input file
CalculationParameters (const CalculationParameters &other)=default
CalculationParameters (World &world, const commandlineparser &parser)
std::string ac_data () const
std::string algopt () const
std::string aobasis () const
double charge () const
bool converge_bsh_residual () const
bool converge_density () const
bool converge_each_energy () const
bool converge_total_energy () const
double dconv () const
std::string deriv () const
bool derivatives () const
std::string dft_deriv () const
bool dipole () const
bool do_localize () const
bool do_symmetry () const
double econv () const
std::string get_tag () const override
bool ginitial_hessian () const
int gmaxiter () const
bool gopt () const
double gprec () const
double gtol () const
double gval () const
bool have_beta () const
std::string hfexalg () const
int k () const
double L () const
double lo () const
int loadbalparts () const
std::string localize_method () const
bool localize_pm () const
int maxiter () const
double maxrotn () const
int maxsub () const
int nalpha () const
int nbeta () const
int nmo_alpha () const
int nmo_beta () const
bool no_compute () const
int nopen () const
int nv_factor () const
int nvalpha () const
int nvbeta () const
std::string nwfile () const
double orbitalshift () const
std::string pcm_data () const
Tensor< double > plot_cell () const
std::string pointgroup () const
std::string prefix () const
int print_level () const
std::vector< double > protocol () const
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
bool restart () const
bool restart_cphf () const
bool restartao () const
bool save () const
void set_derived_values (const Molecule &molecule)
bool spin_restricted () const
int vnucextra () const
std::string xc () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Private Types
typedef std::map< std::string, std::vector< QCParameter > > ParameterVectorContainerT
Private Attributes
ParameterVectorContainerT parameter_variations
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Static Public Attributes inherited from madness::CalculationParameters
static constexpr char const * tag = "dft"
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Detailed Description
helper class to set up a vector of possible values for a given key
derived from the CalculationParameters class; parameters member variable is kept constant, the variations are kept in the parameter_variations variable.
Member Typedef Documentation
ParameterVectorContainerT
typedef std::map<std::string,std::vector<QCParameter> > TestCalculationParameters::ParameterVectorContainerT private
Constructor & Destructor Documentation
TestCalculationParameters()
TestCalculationParameters::TestCalculationParameters (const CalculationParameters & cp) inline
Member Function Documentation
copy_and_replace_key_in_parameters()
CalculationParameters TestCalculationParameters::copy_and_replace_key_in_parameters (const CalculationParameters & ref_parameters, const std::string & key, int index) const inline
References madness::QCCalculationParametersBase::get_parameter(), p(), and parameter_variations.
Referenced by make_all_parameters_for_one_key(), and make_all_parameters_for_two_keys().
extend_parameters()
template<typename T > void TestCalculationParameters::extend_parameters (const std::string & key, std::vector< T > values) inline
References madness::QCCalculationParametersBase::get_parameter(), parameter_variations, and madness::QCCalculationParametersBase::tostring().
Referenced by main().
get_parameter_range()
std::size_t TestCalculationParameters::get_parameter_range (const std::string & key) const inline
References parameter_variations.
Referenced by make_all_parameters_for_one_key(), and make_all_parameters_for_two_keys().
make_all_parameter_doubles()
std::vector< CalculationParameters > TestCalculationParameters::make_all_parameter_doubles () const inline
References make_all_parameters_for_two_keys(), parameter_variations, and madness::print().
make_all_parameter_singles()
std::vector< CalculationParameters > TestCalculationParameters::make_all_parameter_singles () const inline
References make_all_parameters_for_one_key(), parameter_variations, and madness::print().
Referenced by main().
make_all_parameters_for_one_key()
std::vector< CalculationParameters > TestCalculationParameters::make_all_parameters_for_one_key (const std::string & key) const inline
References copy_and_replace_key_in_parameters(), and get_parameter_range().
Referenced by make_all_parameter_singles().
make_all_parameters_for_two_keys()
std::vector< CalculationParameters > TestCalculationParameters::make_all_parameters_for_two_keys (const std::string & key1, const std::string & key2) const inline
References copy_and_replace_key_in_parameters(), and get_parameter_range().
Referenced by make_all_parameter_doubles().
Member Data Documentation
parameter_variations
ParameterVectorContainerT TestCalculationParameters::parameter_variations private
Referenced by copy_and_replace_key_in_parameters(), extend_parameters(), get_parameter_range(), make_all_parameter_doubles(), and make_all_parameter_singles().
The documentation for this class was generated from the following file:
test_qc.cc