MADNESS: MiniDFT Class Reference
MiniDFT Class Reference
Public Member Functions
MiniDFT (double thresh, int kwavelet, int truncate_mode, double boxsize, const Molecule &molecule)
vector_real_function_3d apply_potential (World &world, const real_function_3d &potential, const vector_real_function_3d &psi)
void doit (World &world)
real_tensor kinetic_energy_matrix (World &world, const vector_real_function_3d &v)
vector< poperatorT > make_bsh_operators (World &world, const real_tensor &evals, double shift)
real_function_3d make_coulomb_potential (World &world, const real_function_3d &rho)
real_function_3d make_density (World &world, const vector_real_function_3d &v)
real_function_3d make_lda_potential (World &world, const real_function_3d &rho)
vector_real_function_3d makeao (World &world, const Molecule &molecule)
template<typename Q >
void orthogonalize (World &world, std::vector< Function< Q, 3 > > &psi)
vector_real_function_3d update (World &world, const vector_real_function_3d &psi, vector_real_function_3d &vpsi, const real_tensor &e, int iter, double &ravg)
Private Attributes
AtomicBasisSet aobasis
BoysLocalization boys
Molecule molecule
XCfunctional xc
Constructor & Destructor Documentation
MiniDFT()
MiniDFT::MiniDFT (double thresh, int kwavelet, int truncate_mode, double boxsize, const Molecule & molecule) inline
References madness::XCfunctional::initialize(), kwavelet, madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), thresh, truncate_mode, and xc.
Member Function Documentation
apply_potential()
vector_real_function_3d MiniDFT::apply_potential (World & world, const real_function_3d & potential, const vector_real_function_3d & psi) inline
References madness::mul_sparse(), potential(), and psi().
Referenced by doit().
doit()
void MiniDFT::doit (World & world) inline
References madness::_(), std::abs(), aobasis, madness::GTHPseudopotential< Q >::apply_potential(), apply_potential(), WSTFunctional::apply_xc(), boys, c, madness::copy(), e(), madness::FunctionDefaults< NDIM >::get_k(), madness::FunctionDefaults< NDIM >::get_thresh(), kinetic_energy_matrix(), kwavelet, make_coulomb_potential(), make_density(), make_lda_potential(), madness::GTHPseudopotential< Q >::make_pseudo_potential(), makeao(), madness::matrix_inner(), molecule, madness::norm2s(), madness::print(), madness::project(), psi(), madness::World::rank(), madness::AtomicBasisSet::read_file(), madness::GTHPseudopotential< Q >::reproject(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_k(), BoysLocalization::set_size(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::sygv(), thresh, madness::Function< T, NDIM >::thresh(), madness::Molecule::total_nuclear_charge(), madness::Function< T, NDIM >::trace(), madness::transform(), madness::transpose(), madness::truncate(), update(), v, madness::GTHPseudopotential< Q >::vlocalp, vnuc(), and xc.
Referenced by main().
kinetic_energy_matrix()
real_tensor MiniDFT::kinetic_energy_matrix (World & world, const vector_real_function_3d & v) inline
References madness::apply(), axis, gradop, madness::matrix_inner(), madness::reconstruct(), madness::Tensor< T >::scale(), and v.
Referenced by doit().
make_bsh_operators()
vector< poperatorT > MiniDFT::make_bsh_operators (World & world, const real_tensor & evals, double shift) inline
References madness::BSHOperatorPtr3D(), madness::BaseTensor::dim(), e(), madness::FunctionDefaults< NDIM >::get_thresh(), shift, and thresh.
Referenced by update().
make_coulomb_potential()
real_function_3d MiniDFT::make_coulomb_potential (World & world, const real_function_3d & rho) inline
References madness::CoulombOperator(), e(), madness::FunctionDefaults< NDIM >::get_thresh(), op(), and thresh.
Referenced by doit().
make_density()
real_function_3d MiniDFT::make_density (World & world, const vector_real_function_3d & v) inline
References madness::Function< T, NDIM >::compress(), madness::compress(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::gaxpy(), madness::World::gop, madness::square(), and v.
Referenced by doit().
make_lda_potential()
real_function_3d MiniDFT::make_lda_potential (World & world, const real_function_3d & rho) inline
References madness::copy().
Referenced by doit().
makeao()
vector_real_function_3d MiniDFT::makeao (World & world, const Molecule & molecule) inline
References aobasis, at_nbf, at_to_bf, madness::AtomicBasisSet::atoms_to_bfn(), madness::WorldGopInterface::fence(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::World::gop, molecule, madness::AtomicBasisSet::nbf(), madness::normalize(), madness::print_meminfo(), madness::World::rank(), and madness::truncate().
Referenced by doit().
orthogonalize()
template<typename Q > void MiniDFT::orthogonalize (World & world, std::vector< Function< Q, 3 > > & psi) inline
References madness::compress(), madness::Function< T, NDIM >::gaxpy(), madness::inner(), madness::Function< T, NDIM >::norm2(), psi(), Q(), and madness::Function< T, NDIM >::scale().
update()
vector_real_function_3d MiniDFT::update (World & world, const vector_real_function_3d & psi, vector_real_function_3d & vpsi, const real_tensor & e, int iter, double & ravg) inline
References madness::apply(), e(), madness::gaxpy(), make_bsh_operators(), madness::norm2(), madness::normalize(), madness::print(), psi(), madness::scale(), shift, and madness::truncate().
Referenced by doit().
Member Data Documentation
aobasis
AtomicBasisSet MiniDFT::aobasis private
Referenced by doit(), and makeao().
boys
BoysLocalization MiniDFT::boys private
Referenced by doit().
molecule
Molecule MiniDFT::molecule private
Referenced by doit(), and makeao().
xc
XCfunctional MiniDFT::xc private
Referenced by MiniDFT(), and doit().
The documentation for this class was generated from the following file:
preal.cc