MADNESS: madness::DerivativeOperator< T, NDIM > Class Template Reference
madness::DerivativeOperator< T, NDIM > Class Template Reference
#include <SCFOperators.h>
Public Member Functions
DerivativeOperator (World &world, const int axis1)
std::string info () const
print some information about this operator
T operator() (const functionT &bra, const functionT &ket) const
compute the matrix element <bra | op | ket>
functionT operator() (const functionT &ket) const
tensorT operator() (const vecfuncT &vbra, const vecfuncT &vket) const
compute the matrix <vbra | op | vket>
vecfuncT operator() (const vecfuncT &vket) const
apply this operator on the argument vector of functions
Public Member Functions inherited from madness::SCFOperatorBase< T, NDIM >
SCFOperatorBase ()=default
SCFOperatorBase (std::shared_ptr< MacroTaskQ > taskq)
virtual ~SCFOperatorBase ()
Private Types
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Private Attributes
int axis
Derivative< T, NDIM > gradop
World & world
Additional Inherited Members
Public Types inherited from madness::SCFOperatorBase< T, NDIM >
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Public Attributes inherited from madness::SCFOperatorBase< T, NDIM >
nlohmann::json statistics
std::shared_ptr< MacroTaskQ > taskq =0
Member Typedef Documentation
functionT
template<typename T , std::size_t NDIM> typedef Function<T,NDIM> madness::DerivativeOperator< T, NDIM >::functionT private
tensorT
template<typename T , std::size_t NDIM> typedef Tensor<T> madness::DerivativeOperator< T, NDIM >::tensorT private
vecfuncT
template<typename T , std::size_t NDIM> typedef std::vector<functionT> madness::DerivativeOperator< T, NDIM >::vecfuncT private
Constructor & Destructor Documentation
DerivativeOperator()
template<typename T , std::size_t NDIM> madness::DerivativeOperator< T, NDIM >::DerivativeOperator (World & world, const int axis1) inline
References madness::DerivativeOperator< T, NDIM >::axis, madness::DerivativeOperator< T, NDIM >::gradop, and madness::DerivativeOperator< T, NDIM >::world.
Member Function Documentation
info()
template<typename T , std::size_t NDIM> std::string madness::DerivativeOperator< T, NDIM >::info () const inline virtual
print some information about this operator
Implements madness::SCFOperatorBase< T, NDIM >.
operator()() [1/4]
template<typename T , std::size_t NDIM> T madness::DerivativeOperator< T, NDIM >::operator() (const functionT & bra, const functionT & ket) const inline virtual
compute the matrix element <bra | op | ket>
Parameters
bra bra state
ket ket state
Returns
the matrix element <bra | op | ket>
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::DerivativeOperator< T, NDIM >::operator()().
operator()() [2/4]
template<typename T , std::size_t NDIM> functionT madness::DerivativeOperator< T, NDIM >::operator() (const functionT & ket) const inline virtual
apply this operator on the argument function
Parameters
ket the argument function
Returns
op(ket)
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::DerivativeOperator< T, NDIM >::operator()().
Referenced by madness::DerivativeOperator< T, NDIM >::operator()(), madness::DerivativeOperator< T, NDIM >::operator()(), and madness::DerivativeOperator< T, NDIM >::operator()().
operator()() [3/4]
template<typename T , std::size_t NDIM> tensorT madness::DerivativeOperator< T, NDIM >::operator() (const vecfuncT & vbra, const vecfuncT & vket) const inline virtual
compute the matrix <vbra | op | vket>
Parameters
vbra vector of bra states
vket vector of ket states
Returns
the matrix <vbra | op | vket>
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::matrix_inner(), madness::DerivativeOperator< T, NDIM >::operator()(), and madness::DerivativeOperator< T, NDIM >::world.
operator()() [4/4]
template<typename T , std::size_t NDIM> vecfuncT madness::DerivativeOperator< T, NDIM >::operator() (const vecfuncT & vket) const inline virtual
apply this operator on the argument vector of functions
Parameters
vket argument vector
Returns
op(vket)
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::apply(), madness::WorldGopInterface::fence(), madness::World::gop, madness::DerivativeOperator< T, NDIM >::gradop, and madness::DerivativeOperator< T, NDIM >::world.
Member Data Documentation
axis
template<typename T , std::size_t NDIM> int madness::DerivativeOperator< T, NDIM >::axis private
Referenced by madness::DerivativeOperator< T, NDIM >::DerivativeOperator().
gradop
template<typename T , std::size_t NDIM> Derivative<T,NDIM> madness::DerivativeOperator< T, NDIM >::gradop private
Referenced by madness::DerivativeOperator< T, NDIM >::DerivativeOperator(), and madness::DerivativeOperator< T, NDIM >::operator()().
world
template<typename T , std::size_t NDIM> World& madness::DerivativeOperator< T, NDIM >::world private
Referenced by madness::DerivativeOperator< T, NDIM >::DerivativeOperator(), madness::DerivativeOperator< T, NDIM >::operator()(), and madness::DerivativeOperator< T, NDIM >::operator()().
The documentation for this class was generated from the following file:
SCFOperators.h