MADNESS: madness::CC2 Class Reference
madness::CC2 Class Reference
#include <CC2.h>
Public Member Functions
CC2 (World &world, const CCParameters &cc_param, const TDHFParameters &tdhf_param, const std::shared_ptr< const Nemo > nemo)
CC2 (World &world_, const commandlineparser &parser, const std::shared_ptr< Nemo > nemo_)
virtual ~CC2 ()
bool check_core_valence_separation (const Tensor< double > &fmat) const
double compute_mp3 (const Pairs< CCPair > &mp2pairs, const Info &info) const
Tensor< double > enforce_core_valence_separation (const Tensor< double > &fmat)
make sure the orbitals are block diagonalized
void initialize ()
bool initialize_pairs (Pairs< CCPair > &pairs, const CCState ftype, const CalcType ctype, const CC_vecfunction &tau, const CC_vecfunction &x, const size_t extitation, const Info &info) const
read pairs from file or initialize new ones
bool iterate_adc2_pairs (Pairs< CCPair > &cispd, const CC_vecfunction &ccs)
bool iterate_adc2_singles (Pairs< CCPair > &mp2, CC_vecfunction &singles, Pairs< CCPair > &x, Info &info)
bool iterate_ccs_singles (CC_vecfunction &x, Info &info) const
bool iterate_pair (CCPair &pair, const CC_vecfunction &singles=CC_vecfunction(UNDEFINED)) const
Iterates a pair of the CC2 doubles equations.
std::string name () const
void output_calc_info_schema (const std::string model, const double &energy) const
void plot (const real_function_3d &f, const std::string &msg="unspecified function") const
virtual bool selftest ()
nlohmann::json solve ()
solve the CC2 ground state equations, returns the correlation energy
double solve_cc2 (CC_vecfunction &tau, Pairs< CCPair > &u, Info &info) const
std::vector< CC_vecfunction > solve_ccs () const
double solve_cispd (Pairs< CCPair > &doubles, const Pairs< CCPair > &mp2_pairs, const CC_vecfunction &cis_singles)
std::tuple< Pairs< CCPair >, CC_vecfunction, double > solve_lrcc2 (Pairs< CCPair > &gs_doubles, const CC_vecfunction &gs_singles, const CC_vecfunction &cis, const std::size_t excitation, Info &info) const
solve the excited state LR-CC2 equations for a given excitation
double solve_mp2_coupled (Pairs< CCPair > &doubles, Info &info)
bool update_constant_part_adc2 (const CC_vecfunction &ccs, CCPair &pair)
bool update_constant_part_cispd (const CC_vecfunction &ccs, CCPair &pair)
double value ()
double value (const Tensor< double > &x)
Should return the value of the objective function.
Public Member Functions inherited from madness::OptimizationTargetInterface
virtual ~OptimizationTargetInterface ()
virtual Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
virtual bool provides_gradient () const
Override this to return true if the derivative is implemented.
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
Static Public Member Functions
static double compute_cc2_energy (const CC_vecfunction &singles, const Pairs< CCPair > &pairs, const Info &info, const std::string msg="")
compute the CC2 correlation energy
static double compute_cc2_energy (const CC_vecfunction &singles, const std::vector< CCPair > &pairs, const Info &info, const std::string msg="")
static Pairs< real_function_6d > compute_local_coupling (const Pairs< real_function_6d > &pairs, const Info &info)
add the coupling terms for local MP2
static Pairs< real_function_6d > compute_local_coupling (const std::vector< CCPair > &vpairs, const Info &info)
forward to the other function (converting CCPair to real_function)
static std::vector< real_function_3d > compute_local_coupling (const std::vector< real_function_3d > &singles, const Info &info)
compute the coupling of singles function if orbitals are localized
static double compute_mp2_energy (const Pairs< CCPair > &pairs, const Info &info, const std::string msg="")
compute the MP2 correlation energy
static double compute_mp2_energy (const std::vector< CCPair > &pairs, const Info &info, const std::string msg="")
static void help ()
static CC_vecfunction initialize_singles (World &, const CalcType &ctype, const FuncType type, int ex=-1)
read singles from file or initialize new ones
static CC_vecfunction initialize_singles_to_zero (World &world, const CalcType &ctype, const FuncType type, const Info &info)
static bool iterate_cc2_singles (World &world, CC_vecfunction &singles, Pairs< CCPair > &doubles, Info &info)
static bool iterate_lrcc2_pairs (World &world, const CC_vecfunction &cc2_s, const CC_vecfunction lrcc2_s, Pairs< CCPair > &lrcc2_d, const Info &info)
static bool iterate_lrcc2_singles (World &world, const CC_vecfunction &cc2_s, Pairs< CCPair > &cc2_d, CC_vecfunction &lrcc2_s, Pairs< CCPair > lrcc2_d, Info &info)
static bool iterate_singles (World &world, CC_vecfunction &singles, const CC_vecfunction singles2, const Pairs< CCPair > &gs_doubles, const Pairs< CCPair > &ex_doubles, const CalcType ctype, const std::size_t maxiter, Info &info)
static void print_parameters ()
static std::string singles_name (const CalcType &ctype, const FuncType &type, int ex=-1)
return the file name for singles
Public Attributes
CCPotentials CCOPS
The CC Operator Class.
std::shared_ptr< const Nemo > nemo
The SCF Calculation.
CCMessenger & output
Formated Output (same as used in CC2Potentials structure)
CCParameters parameters
Structure holds all the parameters used in the CC2 calculation.
std::shared_ptr< TDHF > tdhf
The excited state cis calculation.
PairVectorMap triangular_map
map Pair struct to vector
World & world
The World.
Constructor & Destructor Documentation
CC2() [1/2]
madness::CC2::CC2 (World & world, const CCParameters & cc_param, const TDHFParameters & tdhf_param, const std::shared_ptr< const Nemo > nemo) inline
References initialize().
CC2() [2/2]
madness::CC2::CC2 (World & world_, const commandlineparser & parser, const std::shared_ptr< Nemo > nemo_) inline
References initialize().
~CC2()
virtual madness::CC2::~CC2 () inline virtual
Member Function Documentation
check_core_valence_separation()
bool madness::CC2::check_core_valence_separation (const Tensor< double > & fmat) const
References madness::Localizer::check_core_valence_separation(), madness::MolecularOrbitals< T, NDIM >::get_localize_sets(), nemo, and madness::MolecularOrbitals< T, NDIM >::recompute_localize_sets().
Referenced by solve().
compute_cc2_energy() [1/2]
double madness::CC2::compute_cc2_energy (const CC_vecfunction & singles, const Pairs< CCPair > & pairs, const Info & info, const std::string msg = "") static
compute the CC2 correlation energy
References compute_cc2_energy(), madness::CCParameters::freeze(), madness::Info::mo_ket, madness::Pairs< T >::pairs2vector(), madness::Info::parameters, triangular_map, and madness::PairVectorMap::triangular_map().
Referenced by compute_cc2_energy(), compute_mp2_energy(), compute_mp2_energy(), and solve().
compute_cc2_energy() [2/2]
double madness::CC2::compute_cc2_energy (const CC_vecfunction & singles, const std::vector< CCPair > & pairs, const Info & info, const std::string msg = "") static
References madness::CCParameters::debug(), p(), madness::Info::parameters, madness::printf_msg_energy_time(), madness::World::rank(), madness::wall_time(), and world.
compute_local_coupling() [1/3]
Pairs< real_function_6d > madness::CC2::compute_local_coupling (const Pairs< real_function_6d > & pairs, const Info & info) static
add the coupling terms for local MP2
\sum_{k\neq i} f_ki |u_kj> + \sum_{l\neq j} f_lj |u_il>
Returns
\sum_{k\neq i} f_ki |u_kj> + \sum_{l\neq j} f_lj |u_il>
References madness::Pairs< T >::allpairs, madness::copy(), madness::WorldGopInterface::fence(), madness::Info::fock, madness::CCParameters::freeze(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, madness::Pairs< T >::insert(), k, MADNESS_EXCEPTION, madness::Info::mo_ket, madness::Info::parameters, q(), madness::swap_particles(), thresh, and world.
compute_local_coupling() [2/3]
static Pairs< real_function_6d > madness::CC2::compute_local_coupling (const std::vector< CCPair > & vpairs, const Info & info) inline static
forward to the other function (converting CCPair to real_function)
References a, compute_local_coupling(), madness::Pairs< T >::convert(), and madness::Pairs< T >::insert().
Referenced by compute_local_coupling(), iterate_lrcc2_pairs(), iterate_singles(), solve_cc2(), and solve_mp2_coupled().
compute_local_coupling() [3/3]
static std::vector< real_function_3d > madness::CC2::compute_local_coupling (const std::vector< real_function_3d > & singles, const Info & info) inline static
compute the coupling of singles function if orbitals are localized
Returns
the coupling terms c_i = -\sum_(j\neq i) f_ij |\phi_j> (for whatever phi is)
References madness::BaseTensor::dim(), madness::Info::fock, madness::CCParameters::freeze(), MADNESS_CHECK_THROW, madness::Info::parameters, madness::transform(), and world.
compute_mp2_energy() [1/2]
double madness::CC2::compute_mp2_energy (const Pairs< CCPair > & pairs, const Info & info, const std::string msg = "") static
compute the MP2 correlation energy
References compute_cc2_energy(), and madness::PARTICLE.
Referenced by solve(), and solve_mp2_coupled().
compute_mp2_energy() [2/2]
double madness::CC2::compute_mp2_energy (const std::vector< CCPair > & pairs, const Info & info, const std::string msg = "") static
References compute_cc2_energy(), and madness::PARTICLE.
compute_mp3()
double madness::CC2::compute_mp3 (const Pairs< CCPair > & mp2pairs, const Info & info) const inline
References madness::MP3::mp3_energy_contribution_macrotask_driver(), and world.
Referenced by solve().
enforce_core_valence_separation()
Tensor< double > madness::CC2::enforce_core_valence_separation (const Tensor< double > & fmat)
make sure the orbitals are block diagonalized
changes the orbitals in member variable nemo will throw if the fock matrix is not block diagonal
Returns
the new fock matrix
References madness::Localizer::check_core_valence_separation(), madness::copy(), madness::CCParameters::debug(), madness::MolecularOrbitals< T, NDIM >::get_eps(), madness::MolecularOrbitals< T, NDIM >::get_localize_sets(), madness::MolecularOrbitals< T, NDIM >::get_mos(), madness::Localizer::localize(), MADNESS_CHECK, nemo, parameters, madness::print(), madness::World::rank(), madness::MolecularOrbitals< T, NDIM >::recompute_localize_sets(), madness::Localizer::set_enforce_core_valence_separation(), madness::Localizer::set_method(), madness::Localizer::set_metric(), madness::BaseTensor::size(), and world.
Referenced by solve().
help()
static void madness::CC2::help () inline static
References madness::print(), and madness::print_header2().
initialize()
void madness::CC2::initialize () inline
References madness::CCParameters::dmin(), madness::CCParameters::information(), nemo, output, parameters, madness::CCParameters::sanity_check(), madness::CCMessenger::section(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_special_level(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::CCParameters::thresh_3D(), madness::CCParameters::thresh_6D(), and world.
Referenced by CC2(), and CC2().
initialize_pairs()
bool madness::CC2::initialize_pairs (Pairs< CCPair > & pairs, const CCState ftype, const CalcType ctype, const CC_vecfunction & tau, const CC_vecfunction & x, const size_t extitation, const Info & info) const
read pairs from file or initialize new ones
References madness::Pairs< T >::allpairs, madness::assign_name(), CCOPS, madness::Pairs< T >::empty(), madness::CCParameters::freeze(), madness::Pairs< T >::insert(), MADNESS_ASSERT, madness::CCPair::name(), parameters, madness::PARTICLE, madness::print(), madness::World::rank(), madness::RESPONSE, madness::CC_vecfunction::type, and world.
Referenced by solve(), and solve_lrcc2().
initialize_singles()
CC_vecfunction madness::CC2::initialize_singles (World & world, const CalcType & ctype, const FuncType type, int ex = -1) static
read singles from file or initialize new ones
type: PARTICLE (cc2) or RESPONSE (lrcc2) default_to_zero: if true, initialize with zero functions, otherwise return empty vector ex: if type is RESPONSE, the excitation number
References madness::CC_vecfunction::load_restartdata(), MADNESS_CHECK_THROW, madness::PARTICLE, madness::print(), madness::World::rank(), singles_name(), madness::type(), and world.
Referenced by solve(), and solve_lrcc2().
initialize_singles_to_zero()
CC_vecfunction madness::CC2::initialize_singles_to_zero (World & world, const CalcType & ctype, const FuncType type, const Info & info) static
References madness::CCParameters::freeze(), madness::CC_vecfunction::insert(), madness::Info::mo_ket, madness::Info::parameters, madness::type(), and world.
Referenced by iterate_singles(), and solve_cc2().
iterate_adc2_pairs()
bool madness::CC2::iterate_adc2_pairs (Pairs< CCPair > & cispd, const CC_vecfunction & ccs)
References madness::Pairs< T >::allpairs, madness::CCPair::bsh_eps, CCOPS, madness::CCPair::i, iterate_pair(), madness::CCPair::j, MADNESS_ASSERT, madness::CC_vecfunction::omega, output, madness::RESPONSE, madness::CCMessenger::section(), madness::CC_vecfunction::type, and update_constant_part_adc2().
Referenced by solve().
iterate_adc2_singles()
bool madness::CC2::iterate_adc2_singles (Pairs< CCPair > & mp2, CC_vecfunction & singles, Pairs< CCPair > & x, Info & info) inline
References madness::CCIntermediatePotentials::clear_response(), madness::CT_ADC2, madness::Info::intermediate_potentials, madness::CCParameters::iter_max_3D(), iterate_singles(), MADNESS_ASSERT, parameters, madness::RESPONSE, madness::CC_vecfunction::type, madness::UNDEFINED, and world.
Referenced by solve().
iterate_cc2_singles()
static bool madness::CC2::iterate_cc2_singles (World & world, CC_vecfunction & singles, Pairs< CCPair > & doubles, Info & info) inline static
convencience function to iterate the CC2 ground state singles, makes the right call on the iterate_singles functions
References madness::CCIntermediatePotentials::clear_all(), madness::CT_CC2, madness::Info::intermediate_potentials, madness::CCParameters::iter_max_3D(), iterate_singles(), madness::Info::parameters, madness::RESPONSE, and world.
Referenced by solve(), and solve_cc2().
iterate_ccs_singles()
bool madness::CC2::iterate_ccs_singles (CC_vecfunction & x, Info & info) const inline
convenience function to iterate the CCS Response singles, makes the right call on the iterate_singles functions
References madness::CCIntermediatePotentials::clear_response(), madness::CT_LRCCS, madness::Info::intermediate_potentials, madness::CCParameters::iter_max_3D(), iterate_singles(), madness::Info::parameters, madness::PARTICLE, and world.
Referenced by solve(), and solve_lrcc2().
iterate_lrcc2_pairs()
bool madness::CC2::iterate_lrcc2_pairs (World & world, const CC_vecfunction & cc2_s, const CC_vecfunction lrcc2_s, Pairs< CCPair > & lrcc2_d, const Info & info) static
References madness::CCSize::add(), compute_local_coupling(), madness::CCParameters::dconv_6D(), madness::CCParameters::debug(), madness::CCParameters::freeze(), madness::CC_vecfunction::get_vecfunction(), MADNESS_ASSERT, maxiter, madness::Info::mo_ket, name(), madness::norm2(), p(), madness::Pairs< T >::pairs2vector(), madness::Info::parameters, madness::print(), madness::CCSize::print(), madness::print_header3(), madness::print_size(), madness::World::rank(), madness::CC_vecfunction::reconstruct(), madness::Info::reconstruct(), madness::reconstruct(), residual(), madness::RESPONSE, madness::save(), task(), tc, triangular_map, madness::PairVectorMap::triangular_map(), madness::CC_vecfunction::type, u(), madness::Pairs< T >::vector2pairs(), madness::wall_time(), and world.
Referenced by solve_lrcc2().
iterate_lrcc2_singles()
static bool madness::CC2::iterate_lrcc2_singles (World & world, const CC_vecfunction & cc2_s, Pairs< CCPair > & cc2_d, CC_vecfunction & lrcc2_s, Pairs< CCPair > lrcc2_d, Info & info) inline static
References madness::CCIntermediatePotentials::clear_response(), madness::CT_LRCC2, madness::Info::intermediate_potentials, madness::CCParameters::iter_max_3D(), iterate_singles(), MADNESS_ASSERT, madness::Info::parameters, madness::PARTICLE, madness::RESPONSE, madness::CC_vecfunction::type, and world.
Referenced by solve_lrcc2().
iterate_pair()
bool madness::CC2::iterate_pair (CCPair & pair, const CC_vecfunction & singles = CC_vecfunction(UNDEFINED)) const
Iterates a pair of the CC2 doubles equations.
References madness::assign_name(), bsh_eps, madness::CCPair::bsh_eps, CCOPS, madness::CCPair::constant_part, madness::copy(), madness::CT_ADC2, madness::CT_CC2, madness::CT_CISPD, madness::CT_MP2, madness::CCPair::ctype, madness::CCParameters::dconv_6D(), madness::CCParameters::debug(), delta, madness::NonlinearSolverND< NDIM >::do_print, madness::CCParameters::econv_pairs(), madness::error(), madness::EXCITED_STATE, madness::CCPair::function(), madness::CC_vecfunction::get_vecfunction(), madness::GROUND_STATE, madness::CCTimer::info(), madness::CCParameters::iter_max_6D(), madness::CCParameters::kain(), madness::CCParameters::kain_subspace(), madness::CCParameters::lo(), MADNESS_ASSERT, madness::Info::mo_bra, madness::CCPair::name(), madness::Function< T, NDIM >::norm2(), omega, output, parameters, madness::Info::parameters, madness::PARTICLE, madness::Function< T, NDIM >::print_size(), madness::World::rank(), madness::Function< T, NDIM >::reduce_rank(), madness::RESPONSE, madness::save(), madness::CCMessenger::section(), madness::stringify(), madness::CCMessenger::subsection(), madness::CCParameters::thresh_bsh_6D(), madness::Function< T, NDIM >::truncate(), madness::CC_vecfunction::type, madness::CCPair::type, madness::NonlinearSolverND< NDIM >::update(), madness::CCPair::update_u(), and world.
Referenced by iterate_adc2_pairs(), and solve_cispd().
iterate_singles()
bool madness::CC2::iterate_singles (World & world, CC_vecfunction & singles, const CC_vecfunction singles2, const Pairs< CCPair > & gs_doubles, const Pairs< CCPair > & ex_doubles, const CalcType ctype, const std::size_t maxiter, Info & info) static
Iterates the singles equations for CCS, CC2, LRCC2 The corresponding regulairzation tails of the doubles are updated in every iteration (therefore doubles are not marked as const)
Parameters
[in] singles, the singles that are iterated
[in] singles2, additional set of singles for potential (in LRCC2 this are the Ground State singles)
[in] gs_doubles, Ground State doubles (Needed for CC2 and LRCC2)
[in] ex_doubles, Excited State doubles (Needed for LRCC2)
[in] ctype: the calculation type: CCS, CC2, CC2_response_
[in] maxiter: maxmial number of iterations
[out]
true if the overall change of the singles is below 10*donv_6D
References std::abs(), madness::CCSize::add(), madness::Pairs< T >::allpairs, madness::assign_name(), bsh_eps, madness::BSHOperatorPtr3D(), compute_local_coupling(), madness::copy(), madness::CT_ADC2, madness::CT_CC2, madness::CT_CISPD, madness::CT_LRCC2, madness::CT_LRCCS, madness::CT_MP2, madness::CT_TEST, madness::CCParameters::dconv_3D(), madness::CCParameters::dconv_6D(), madness::CCParameters::debug(), madness::CCParameters::econv(), madness::WorldGopInterface::fence(), madness::CCParameters::freeze(), madness::CC_vecfunction::functions, madness::CC_vecfunction::get_vecfunction(), madness::World::gop, madness::CCTimer::info(), initialize_singles_to_zero(), madness::inner(), madness::CCParameters::kain(), madness::CCParameters::lo(), MADNESS_ASSERT, MADNESS_EXCEPTION, maxiter, madness::Info::mo_bra, madness::Info::mo_ket, madness::CC_vecfunction::name(), norm(), madness::norm2(), omega, madness::CC_vecfunction::omega, madness::Info::orbital_energies, output, madness::CCParameters::output_prec(), p(), madness::Pairs< T >::pairs2vector(), madness::Info::parameters, madness::PARTICLE, madness::print(), madness::CCSize::print(), madness::print_header2(), madness::print_size(), Q(), madness::Info::R_square, madness::World::rank(), madness::Info::reconstruct(), madness::reconstruct(), residual(), madness::RESPONSE, madness::scale(), madness::CC_vecfunction::size(), madness::sub(), madness::Tensor< T >::sum(), madness::CCParameters::thresh_bsh_3D(), triangular_map, madness::PairVectorMap::triangular_map(), madness::truncate(), madness::CC_vecfunction::type, V(), madness::CCMessenger::warning(), and world.
Referenced by iterate_adc2_singles(), iterate_cc2_singles(), iterate_ccs_singles(), and iterate_lrcc2_singles().
name()
std::string madness::CC2::name () const inline virtual
Implements madness::QCPropertyInterface.
Referenced by iterate_lrcc2_pairs().
output_calc_info_schema()
void madness::CC2::output_calc_info_schema (const std::string model, const double & energy) const
References energy, nemo, madness::World::rank(), and world.
Referenced by solve().
plot()
void madness::CC2::plot (const real_function_3d & f, const std::string & msg = "unspecified function") const inline
References madness::f, output, madness::plot_plane(), and world.
print_parameters()
static void madness::CC2::print_parameters () inline static
References param, madness::print(), and madness::Molecule::print_parameters().
selftest()
virtual bool madness::CC2::selftest () inline virtual
Implements madness::QCPropertyInterface.
singles_name()
static std::string madness::CC2::singles_name (const CalcType & ctype, const FuncType & type, int ex = -1) inline static
return the file name for singles
References madness::assign_name(), madness::name(), and madness::type().
Referenced by initialize_singles(), solve_cc2(), and solve_lrcc2().
solve()
nlohmann::json madness::CC2::solve ()
solve the CC2 ground state equations, returns the correlation energy
References a, madness::Pairs< T >::allpairs, madness::assign_name(), b, c, madness::CCParameters::calc_type(), CCOPS, check_core_valence_separation(), compute_cc2_energy(), compute_mp2_energy(), compute_mp3(), madness::copy(), madness::CT_ADC2, madness::CT_CC2, madness::CT_CISPD, madness::CT_LRCC2, madness::CT_LRCCS, madness::CT_MP2, madness::CT_MP3, madness::Localizer::determine_frozen_orbitals(), enforce_core_valence_separation(), madness::CCParameters::excitations(), madness::EXCITED_STATE, madness::CCParameters::freeze(), function(), madness::GROUND_STATE, madness::CCTimer::info(), initialize_pairs(), initialize_singles(), madness::Info::intermediate_potentials, iterate_adc2_pairs(), iterate_adc2_singles(), iterate_cc2_singles(), iterate_ccs_singles(), k, MADNESS_CHECK, MADNESS_EXCEPTION, nemo, madness::CCParameters::no_compute_cc2(), madness::CCParameters::no_compute_mp2(), omega, madness::CC_vecfunction::omega, madness::CISResults::excitation_info::omega, output, output_calc_info_schema(), p(), parameters, madness::PARTICLE, madness::POT_singles_, madness::CCIntermediatePotentials::potential_exists(), madness::print(), madness::MolecularOrbitals< T, NDIM >::print_frozen_orbitals(), madness::print_header1(), madness::print_header2(), madness::print_header3(), madness::printf_msg_energy_time(), madness::World::rank(), madness::RESPONSE, madness::CCParameters::response(), madness::CCMessenger::section(), madness::QCCalculationParametersBase::set_derived_value(), madness::CC2Results::set_energies(), madness::CC_vecfunction::size(), madness::World::size(), solve_cc2(), solve_ccs(), solve_cispd(), solve_lrcc2(), solve_mp2_coupled(), tdhf, madness::CCParameters::test(), triangular_map, madness::PairVectorMap::triangular_map(), madness::wall_time(), and world.
Referenced by value().
solve_cc2()
double madness::CC2::solve_cc2 (CC_vecfunction & tau, Pairs< CCPair > & u, Info & info) const
References compute_local_coupling(), madness::CT_CC2, madness::CCParameters::dconv_6D(), madness::CCParameters::debug(), delta, madness::CCParameters::econv(), madness::CC_vecfunction::get_vecfunction(), madness::CCTimer::info(), initialize_singles_to_zero(), madness::CCParameters::iter_max(), iterate_cc2_singles(), MADNESS_ASSERT, maxiter, omega, output, p(), madness::Pairs< T >::pairs2vector(), parameters, madness::PARTICLE, madness::print(), madness::World::rank(), madness::CC_vecfunction::reconstruct(), madness::Info::reconstruct(), residual(), madness::save(), madness::CC_vecfunction::save_restartdata(), madness::CCMessenger::section(), singles_name(), madness::CC_vecfunction::size(), madness::timer::tag(), task(), triangular_map, madness::CC_vecfunction::type, madness::Pairs< T >::vector2pairs(), madness::wall_time(), and world.
Referenced by solve().
solve_ccs()
std::vector< CC_vecfunction > madness::CC2::solve_ccs () const
References madness::CCParameters::excitations(), MADNESS_EXCEPTION, parameters, and tdhf.
Referenced by solve().
solve_cispd()
double madness::CC2::solve_cispd (Pairs< CCPair > & doubles, const Pairs< CCPair > & mp2_pairs, const CC_vecfunction & cis_singles)
References madness::Pairs< T >::allpairs, madness::CCPair::bsh_eps, CCOPS, madness::CCParameters::debug(), diff(), madness::CCParameters::freeze(), madness::CCPair::functions, madness::CCPair::i, iterate_pair(), madness::CCPair::j, MADNESS_ASSERT, madness::CCParameters::no_compute_cispd(), madness::CC_vecfunction::omega, madness::CCParameters::only_pair(), output, parameters, madness::PARTICLE, madness::World::rank(), madness::RESPONSE, madness::CCMessenger::section(), madness::CC_vecfunction::size(), madness::CCParameters::thresh_6D(), madness::CC_vecfunction::type, update_constant_part_cispd(), and world.
Referenced by solve().
solve_lrcc2()
std::tuple< Pairs< CCPair >, CC_vecfunction, double > madness::CC2::solve_lrcc2 (Pairs< CCPair > & gs_doubles, const CC_vecfunction & gs_singles, const CC_vecfunction & cis, const std::size_t excitation, Info & info) const
solve the excited state LR-CC2 equations for a given excitation
Parameters
[in] gs_doubles the ground state doubles
[in] gs_singles the ground state singles
[in] cis the CIS singles
[in] excitation the excitation number
Returns
a tuple with the excited state doubles, the excited state singles and the excitation energy
read LRCC2 singles from file or use the CIS vectors as guess
References madness::assign_name(), madness::copy(), madness::CT_LRCC2, madness::CT_LRCCS, madness::CCTimer::current_time(), madness::EXCITED_STATE, madness::filename, madness::constants::hartree_electron_volt_relationship, initialize_pairs(), initialize_singles(), madness::CCParameters::iter_max(), iterate_ccs_singles(), iterate_lrcc2_pairs(), iterate_lrcc2_singles(), madness::CCParameters::no_compute_lrcc2(), madness::CC_vecfunction::omega, output, parameters, madness::Info::parameters, madness::print(), madness::print_header2(), madness::World::rank(), madness::RESPONSE, madness::CCMessenger::section(), singles_name(), madness::wall_time(), and world.
Referenced by solve().
solve_mp2_coupled()
double madness::CC2::solve_mp2_coupled (Pairs< CCPair > & doubles, Info & info)
References std::abs(), madness::CCSize::add(), madness::Pairs< T >::allpairs, c, madness::change_tree_state(), compute_local_coupling(), compute_mp2_energy(), madness::CCParameters::dconv_6D(), madness::CCParameters::debug(), delta, madness::CCParameters::econv(), madness::timer::end(), madness::MacroTask< taskT >::get_taskq(), madness::CCParameters::iter_max_6D(), madness::CCParameters::kain(), madness::CCParameters::kain_subspace(), madness::load_balance(), MADNESS_CHECK_THROW, maxiter, madness::MemoryMeasurer::measure_and_print(), madness::CCParameters::no_compute_mp2_constantpart(), p(), madness::Pairs< T >::pairs2vector(), parameters, madness::PARTICLE, madness::print(), madness::CCSize::print(), madness::print_header2(), madness::print_header3(), madness::print_size(), madness::World::rank(), madness::reconstructed, residual(), madness::save(), madness::World::size(), madness::timer::tag(), task(), madness::CCParameters::tight_thresh_6D(), triangular_map, madness::truncate(), u(), madness::Pairs< T >::vector2pairs(), madness::wall_time(), and world.
Referenced by solve().
update_constant_part_adc2()
bool madness::CC2::update_constant_part_adc2 (const CC_vecfunction & ccs, CCPair & pair) inline
References madness::assign_name(), madness::CCPair::bsh_eps, CCOPS, madness::CCPair::constant_part, madness::CT_ADC2, madness::CCPair::ctype, madness::EXCITED_STATE, madness::CCPair::i, madness::CCPair::j, madness::CCParameters::lo(), MADNESS_ASSERT, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::CCPair::name(), madness::CC_vecfunction::omega, parameters, madness::CCParameters::QtAnsatz(), madness::save(), madness::CCParameters::thresh_bsh_6D(), madness::CCPair::type, and world.
Referenced by iterate_adc2_pairs().
update_constant_part_cispd()
bool madness::CC2::update_constant_part_cispd (const CC_vecfunction & ccs, CCPair & pair) inline
References madness::CCPair::bsh_eps, CCOPS, madness::CCPair::constant_part, madness::CT_CISPD, madness::CCPair::ctype, madness::EXCITED_STATE, madness::CCPair::i, madness::Function< T, NDIM >::is_initialized(), madness::CCPair::j, madness::CCParameters::lo(), MADNESS_ASSERT, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::CCPair::name(), madness::CC_vecfunction::omega, parameters, madness::CCParameters::QtAnsatz(), madness::save(), madness::CCParameters::thresh_bsh_6D(), madness::CCPair::type, and world.
Referenced by solve_cispd().
value() [1/2]
double madness::CC2::value () inline
References nemo, and value().
Referenced by value().
value() [2/2]
double madness::CC2::value (const Tensor< double > & x) inline virtual
Should return the value of the objective function.
Implements madness::OptimizationTargetInterface.
References solve().
Member Data Documentation
CCOPS
CCPotentials madness::CC2::CCOPS
The CC Operator Class.
Referenced by initialize_pairs(), iterate_adc2_pairs(), iterate_pair(), solve(), solve_cispd(), update_constant_part_adc2(), and update_constant_part_cispd().
nemo
std::shared_ptr<const Nemo> madness::CC2::nemo
The SCF Calculation.
Referenced by check_core_valence_separation(), enforce_core_valence_separation(), initialize(), output_calc_info_schema(), solve(), and value().
output
CCMessenger& madness::CC2::output
Formated Output (same as used in CC2Potentials structure)
Referenced by initialize(), iterate_adc2_pairs(), iterate_pair(), iterate_singles(), plot(), solve(), solve_cc2(), solve_cispd(), and solve_lrcc2().
parameters
CCParameters madness::CC2::parameters
Structure holds all the parameters used in the CC2 calculation.
Referenced by enforce_core_valence_separation(), initialize(), initialize_pairs(), iterate_adc2_singles(), iterate_pair(), solve(), solve_cc2(), solve_ccs(), solve_cispd(), solve_lrcc2(), solve_mp2_coupled(), update_constant_part_adc2(), and update_constant_part_cispd().
tdhf
std::shared_ptr<TDHF> madness::CC2::tdhf
The excited state cis calculation.
Referenced by solve(), and solve_ccs().
triangular_map
PairVectorMap madness::CC2::triangular_map
map Pair struct to vector
Referenced by compute_cc2_energy(), iterate_lrcc2_pairs(), iterate_singles(), solve(), solve_cc2(), and solve_mp2_coupled().
world
World& madness::CC2::world
The World.
Referenced by compute_cc2_energy(), compute_local_coupling(), compute_local_coupling(), compute_mp3(), enforce_core_valence_separation(), initialize(), initialize_pairs(), initialize_singles(), initialize_singles_to_zero(), iterate_adc2_singles(), iterate_cc2_singles(), iterate_ccs_singles(), iterate_lrcc2_pairs(), iterate_lrcc2_singles(), iterate_pair(), iterate_singles(), output_calc_info_schema(), plot(), solve(), solve_cc2(), solve_cispd(), solve_lrcc2(), solve_mp2_coupled(), update_constant_part_adc2(), and update_constant_part_cispd().
The documentation for this class was generated from the following files:
CC2.h
CC2.cc