MADNESS: madness::ContractedGaussianShell Class Reference
madness::ContractedGaussianShell Class Reference
Represents a single shell of contracted, Cartesian, Gaussian primitives.
#include <molecularbasis.h>
Public Member Functions
ContractedGaussianShell ()
ContractedGaussianShell (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, bool donorm=true)
int angular_momentum () const
Returns the shell angular momentum.
double * eval (double rsq, double x, double y, double z, double *bf) const
Evaluates the entire shell returning the incremented result pointer.
double eval_radial (double rsq) const
Evaluates the radial part of the contracted function.
const std::vector< double > & get_coeff () const
Returns a const reference to the coefficients.
const char * get_desc (int ibf) const
Returns a string description of the basis function type.
const std::vector< double > & get_expnt () const
Returns a const reference to the exponents.
int nbf () const
Returns the number of basis functions in the shell.
int nprim () const
Returns the number of primitives in the contraction.
double rangesq () const
Returns square of the distance beyond which function is less than 1e-8.
template<typename Archive >
void serialize (Archive &ar)
Static Public Attributes
static const int maxbf =(maxtype+1)*(maxtype+2)/2
Maximum number of basis functions in a shell.
static const int maxtype =6
Maximum angular momentum supported.
Private Member Functions
void normalize ()
Private Attributes
std::vector< double > coeff
std::vector< double > expnt
int numbf
Number of basis functions in shell (type+1)*(type+2)/2.
double rsqmax
int type
Angular momentum = 0, 1, 2, ...
Detailed Description
Represents a single shell of contracted, Cartesian, Gaussian primitives.
Constructor & Destructor Documentation
ContractedGaussianShell() [1/2]
madness::ContractedGaussianShell::ContractedGaussianShell () inline
ContractedGaussianShell() [2/2]
madness::ContractedGaussianShell::ContractedGaussianShell (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, bool donorm = true) inline
References expnt, normalize(), and rsqmax.
Member Function Documentation
angular_momentum()
int madness::ContractedGaussianShell::angular_momentum () const inline
Returns the shell angular momentum.
References type.
eval()
double * madness::ContractedGaussianShell::eval (double rsq, double x, double y, double z, double * bf) const inline
Evaluates the entire shell returning the incremented result pointer.
References e(), eval_radial(), numbf, R, and type.
Referenced by madness::AtomicBasisFunction::operator()().
eval_radial()
double madness::ContractedGaussianShell::eval_radial (double rsq) const inline
Evaluates the radial part of the contracted function.
References coeff, expnt, rsqmax, and sum.
Referenced by eval().
get_coeff()
const std::vector< double > & madness::ContractedGaussianShell::get_coeff () const inline
Returns a const reference to the coefficients.
References coeff.
get_desc()
const char * madness::ContractedGaussianShell::get_desc (int ibf) const inline
Returns a string description of the basis function type.
References MADNESS_ASSERT, and type.
Referenced by madness::AtomicBasisFunction::get_desc().
get_expnt()
const std::vector< double > & madness::ContractedGaussianShell::get_expnt () const inline
Returns a const reference to the exponents.
References expnt.
nbf()
int madness::ContractedGaussianShell::nbf () const inline
Returns the number of basis functions in the shell.
References numbf.
Referenced by madness::AtomicBasis::get_shell_from_basis_function().
normalize()
void madness::ContractedGaussianShell::normalize () inline private
References coeff, expnt, madness::f, np, madness::constants::pi, pow(), sum, and type.
Referenced by ContractedGaussianShell().
nprim()
int madness::ContractedGaussianShell::nprim () const inline
Returns the number of primitives in the contraction.
References coeff.
rangesq()
double madness::ContractedGaussianShell::rangesq () const inline
Returns square of the distance beyond which function is less than 1e-8.
References rsqmax.
Referenced by madness::AtomicBasisFunction::rangesq().
serialize()
template<typename Archive > void madness::ContractedGaussianShell::serialize (Archive & ar) inline
References coeff, expnt, numbf, rsqmax, and type.
Member Data Documentation
coeff
std::vector<double> madness::ContractedGaussianShell::coeff private
Referenced by eval_radial(), get_coeff(), normalize(), nprim(), and serialize().
expnt
std::vector<double> madness::ContractedGaussianShell::expnt private
Referenced by ContractedGaussianShell(), eval_radial(), get_expnt(), normalize(), and serialize().
maxbf
const int madness::ContractedGaussianShell::maxbf =(maxtype+1)*(maxtype+2)/2 static
Maximum number of basis functions in a shell.
Referenced by madness::AtomicBasis::eval_guess_density(), and madness::AtomicBasisFunction::operator()().
maxtype
const int madness::ContractedGaussianShell::maxtype =6 static
Maximum angular momentum supported.
numbf
int madness::ContractedGaussianShell::numbf private
Number of basis functions in shell (type+1)*(type+2)/2.
Referenced by eval(), nbf(), and serialize().
rsqmax
double madness::ContractedGaussianShell::rsqmax private
Referenced by ContractedGaussianShell(), eval_radial(), rangesq(), and serialize().
type
int madness::ContractedGaussianShell::type private
Angular momentum = 0, 1, 2, ...
Referenced by angular_momentum(), eval(), get_desc(), normalize(), and serialize().
The documentation for this class was generated from the following file:
madness/chem/molecularbasis.h