MADNESS: madness::QCCalculationParametersBase Class Reference
madness::QCCalculationParametersBase Class Reference abstract
class for holding the parameters for calculation
#include <QCCalculationParametersBase.h>
Public Types
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Public Member Functions
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
virtual std::string get_tag () const =0
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Static Public Member Functions
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Private Member Functions
void read_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
read the parameters from the command line and broadcast
void read_input (World &world, const std::string filename, const std::string tag)
read the parameters from file
Friends
bool operator== (const QCCalculationParametersBase &p1, const QCCalculationParametersBase &p2)
Detailed Description
class for holding the parameters for calculation
Actual parameter classes will be derived from this class with a simple constructor (see test_QCCalculationParametersBase.cc for an example) and convenience getters for the parameters of each parameter class. Having the base class will allow consistent parameter input/output handling for all madness programs and reuse of the parsing methods. Even if the same parameter is used in different programs, default might differ (i.e. econv for 3D/6D calculations). The parameter class will effectively serve as a factory for the calculation classes (SCF, nemo, mp2, etc)
parameters are kept in a map with key (string) and value (QCParameter), types are converted whenever a parameter is accessed (i.e. should not be done too frequently in an inner loop)
Member Typedef Documentation
all_parameter_types
using madness::QCCalculationParametersBase::all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector<double>, std::vector<int>, std::vector<std::size_t>, std::vector<std::string>, std::pair<std::string, double> >
ParameterContainerT
typedef std::map<std::string, QCParameter> madness::QCCalculationParametersBase::ParameterContainerT protected
Constructor & Destructor Documentation
QCCalculationParametersBase() [1/2]
madness::QCCalculationParametersBase::QCCalculationParametersBase () inline protected
ctor for testing
QCCalculationParametersBase() [2/2]
madness::QCCalculationParametersBase::QCCalculationParametersBase (const QCCalculationParametersBase & other) inline protected
copy ctor
~QCCalculationParametersBase()
virtual madness::QCCalculationParametersBase::~QCCalculationParametersBase () inline protected virtual
destructor
Member Function Documentation
add_quotes()
static std::string madness::QCCalculationParametersBase::add_quotes (const std::string arg) inline static
References madness::arg().
Referenced by get().
check_type()
template<typename T > static bool madness::QCCalculationParametersBase::check_type (const std::string key, const QCParameter & parameter) inline static
References madness::name(), madness::nonlinear_vector_solver(), madness::print(), and T().
check_type_silent()
template<typename T > static bool madness::QCCalculationParametersBase::check_type_silent (const QCParameter & parameter) inline static
References madness::nonlinear_vector_solver(), and T().
file_exists()
bool madness::QCCalculationParametersBase::file_exists (World & world, std::string filename) const
References madness::WorldGopInterface::broadcast_serializable(), file_exists(), madness::filename, madness::World::gop, madness::nonlinear_vector_solver(), and madness::World::rank().
Referenced by file_exists(), and read_input_and_commandline_options().
from_json()
void madness::QCCalculationParametersBase::from_json (const json & j) inline
References get_parameter(), madness::nonlinear_vector_solver(), ok(), and try_set_from_json().
Referenced by madness::Molecule::from_json().
fromstring() [1/2]
template<typename T > static std::enable_if<!std::is_same< T, bool >::value, T >::type madness::QCCalculationParametersBase::fromstring (const std::string & arg) inline static
References madness::arg(), errmsg(), madness::nonlinear_vector_solver(), T(), and tostring().
fromstring() [2/2]
template<typename T > static std::enable_if< std::is_same< T, bool >::value, T >::type madness::QCCalculationParametersBase::fromstring (const std::string & arg) inline static
References madness::arg(), errmsg(), madness::nonlinear_vector_solver(), and T().
get()
template<typename T > T madness::QCCalculationParametersBase::get (const std::string key) const inline
References add_quotes(), get_parameter(), MADNESS_ASSERT, and madness::nonlinear_vector_solver().
Referenced by madness::OEP::OEP(), madness::OEP::OEP(), madness::F12Potentials::compute_hylleraas_f12_energies(), madness::SCF::do_plots(), madness::Molecule::get_structure(), madness::SCF::initial_guess(), madness::SCF::is_spin_restricted(), madness::SCF::save_mos(), madness::SCF::solve(), and test_lowrank_function().
get_all_parameters()
ParameterContainerT madness::QCCalculationParametersBase::get_all_parameters () const inline
References parameters.
Referenced by madness::Molecule::read().
get_parameter() [1/2]
const QCParameter & madness::QCCalculationParametersBase::get_parameter (const std::string & key) const inline protected
References madness::nonlinear_vector_solver(), parameter_exists(), and parameters.
Referenced by TestCalculationParameters::copy_and_replace_key_in_parameters(), TestCalculationParameters::extend_parameters(), from_json(), get(), is_user_defined(), read_internal(), set_derived_value(), set_user_defined_value(), and try_setting_user_defined_value().
get_parameter() [2/2]
QCParameter & madness::QCCalculationParametersBase::get_parameter (const std::string key) inline
References madness::nonlinear_vector_solver(), parameter_exists(), parameters, and madness::print().
get_tag()
virtual std::string madness::QCCalculationParametersBase::get_tag () const pure virtual
Implemented in DiracParameters, madness::CalculationParameters, madness::CCParameters, madness::LowRankFunctionParameters, madness::MolecularOptimizationParameters, madness::Molecule::GeometryParameters, madness::MP2::Parameters, madness::Nemo::NemoCalculationParameters, madness::OEP_Parameters, madness::PNOParameters, madness::F12Parameters, madness::TDHFParameters, madness::Complex_CIS_Parameters, madness::Nemo_complex_Parameters, madness::PlotParameters, and Parameters.
hash()
hashT madness::QCCalculationParametersBase::hash () const inline
References madness::hash_range(), and parameters.
initialize()
template<typename T > void madness::QCCalculationParametersBase::initialize (const std::string & key, const T & value, const std::string comment = "", const std::vector< T > allowed_values = {}) inline protected
is_user_defined()
bool madness::QCCalculationParametersBase::is_user_defined (std::string key) const inline
References get_parameter(), and madness::QCParameter::is_user_defined().
Referenced by madness::Molecule::GeometryParameters::set_derived_values().
overwrite_if_inf() [1/2]
template<typename T > static std::enable_if< std::is_floating_point< T >::value, void >::type madness::QCCalculationParametersBase::overwrite_if_inf (std::string & str, const T & arg) inline static
References madness::arg(), and madness::nonlinear_vector_solver().
Referenced by tostring().
overwrite_if_inf() [2/2]
template<typename T > static std::enable_if<!std::is_floating_point< T >::value, void >::type madness::QCCalculationParametersBase::overwrite_if_inf (std::string & str, const T & arg) inline static
parameter_exists()
bool madness::QCCalculationParametersBase::parameter_exists (const std::string & key) const inline
References parameters.
Referenced by get_parameter(), get_parameter(), madness::Nemo::NemoCalculationParameters::initialize_nemo_parameters(), and read_internal().
print()
void madness::QCCalculationParametersBase::print (const std::string header = "", const std::string footer = "") const
print all parameters
References madness::nonlinear_vector_solver(), madness::print(), and print_to_string().
Referenced by madness::Molecule::GeometryParameters::GeometryParameters(), madness::Molecule::Molecule(), madness::MP2::MP2(), madness::MP2::Parameters::Parameters(), madness::Zcis::Zcis(), madness::Znemo::Znemo(), main(), main(), madness::MP2::print_parameters(), madness::PNO::print_parameters(), madness::SCF::print_parameters(), madness::OEP::print_parameters(), print_parameters(), madness::OEP_Parameters::set_derived_values(), madness::PNO::solve(), madness::TDHF::test(), test_Kcommutator(), test_lowrank_function(), test_molecular_grid(), and test_serialize().
print_to_string()
std::string madness::QCCalculationParametersBase::print_to_string (const std::list< std::string > precedences = {"all"}) const
References madness::QCParameter::def, madness::QCParameter::defined, madness::QCParameter::derived, madness::nonlinear_vector_solver(), p(), param, and parameters.
Referenced by print(), and madness::Molecule::print().
qcparameter_to_json()
template<typename... Types> void madness::QCCalculationParametersBase::qcparameter_to_json (json & j, const std::pair< std::string, QCParameter > & p, const std::tuple< Types... > &) const inline
References madness::nonlinear_vector_solver(), and p().
Referenced by qcparameter_to_json_from_tuple().
qcparameter_to_json_from_tuple()
template<typename Tuple > void madness::QCCalculationParametersBase::qcparameter_to_json_from_tuple (json & j, const std::pair< std::string, QCParameter > & p, const Tuple &) const inline
References madness::nonlinear_vector_solver(), p(), and qcparameter_to_json().
Referenced by to_json(), and to_json_if_precedence().
read_commandline_options()
void madness::QCCalculationParametersBase::read_commandline_options (World & world, const commandlineparser & parser, const std::string tag) private
read the parameters from the command line and broadcast
syntax is: qcprogram –mp2='maxiter 10; freeze 1' –dft:maxiter=20 –Xmpi:debug=true the argument in quotes is the value of the parser keys
References madness::WorldGopInterface::broadcast_serializable(), madness::World::gop, madness::commandlineparser::key_exists(), madness::nonlinear_vector_solver(), q(), madness::World::rank(), read_internal(), and madness::commandlineparser::value().
Referenced by read_input_and_commandline_options().
read_input()
void madness::QCCalculationParametersBase::read_input (World & world, const std::string filename, const std::string tag) private
read the parameters from file
read the parameters from file and broadcast
only world.rank()==0 reads the input file and broadcasts to all other nodes, so we don't need to serialize the ParameterMap
References madness::WorldGopInterface::broadcast_serializable(), e(), errmsg(), madness::f, madness::filename, madness::World::gop, madness::nonlinear_vector_solver(), madness::World::rank(), and read_internal().
Referenced by read_input_and_commandline_options().
read_input_and_commandline_options()
virtual void madness::QCCalculationParametersBase::read_input_and_commandline_options (World & world, const commandlineparser & parser, const std::string tag) inline protected virtual
Reimplemented in madness::ResponseParameters, and madness::CalculationParameters.
References e(), file_exists(), madness::commandlineparser::key_exists(), madness::nonlinear_vector_solver(), madness::print(), read_commandline_options(), read_input(), and madness::commandlineparser::value().
Referenced by madness::CCParameters::CCParameters(), madness::Complex_CIS_Parameters::Complex_CIS_Parameters(), DiracParameters::DiracParameters(), madness::F12Parameters::F12Parameters(), madness::Molecule::GeometryParameters::GeometryParameters(), madness::MolecularOptimizationParameters::MolecularOptimizationParameters(), madness::Nemo_complex_Parameters::Nemo_complex_Parameters(), madness::Nemo::NemoCalculationParameters::NemoCalculationParameters(), madness::OEP_Parameters::OEP_Parameters(), madness::PlotParameters::PlotParameters(), madness::PNOParameters::PNOParameters(), madness::PNOParameters::PNOParameters(), madness::TDHFParameters::TDHFParameters(), madness::MP2::Parameters::read_and_set_derived_values(), madness::LowRankFunctionParameters::read_and_set_derived_values(), and Parameters::read_and_set_derived_values().
read_internal()
void madness::QCCalculationParametersBase::read_internal (World & world, std::string & filecontents, std::string tag) virtual
read the stream, starting from tag
only parameters that are defined in the constructor will be processed, all others will be discarded.
References e(), errmsg(), madness::f, get_parameter(), madness::QCParameter::get_type(), ignore_unknown_keys, ignore_unknown_keys_silently, madness::nonlinear_vector_solver(), parameter_exists(), madness::position_stream_to_word(), madness::print(), print_debug, and madness::World::rank().
Referenced by read_commandline_options(), and read_input().
read_quotes() [1/2]
template<typename T > static std::enable_if< std::is_same< T, std::string >::value, T >::type madness::QCCalculationParametersBase::read_quotes (std::stringstream & ssvalue) inline static
References madness::arg(), errmsg(), madness::nonlinear_vector_solver(), T(), trim_blanks(), and trim_quotes().
read_quotes() [2/2]
template<typename T > static std::enable_if<!std::is_same< T, std::string >::value, T >::type madness::QCCalculationParametersBase::read_quotes (std::stringstream & ssvalue) inline static
References madness::nonlinear_vector_solver(), and T().
serialize()
template<typename Archive > void madness::QCCalculationParametersBase::serialize (Archive & ar) inline
References parameters, and print_debug.
set_derived_value()
template<typename T > void madness::QCCalculationParametersBase::set_derived_value (const std::string & key, const T & value) inline
References get_parameter(), madness::nonlinear_vector_solver(), and tostring().
Referenced by madness::CalculationParameters::CalculationParameters(), madness::Znemo::Znemo(), main(), madness::CCPairFunction< T, NDIM >::op_dec_to_dec(), madness::TDHF::prepare_calculation(), madness::MP2::Parameters::read_and_set_derived_values(), Parameters::read_and_set_derived_values(), madness::CCParameters::set_derived_values(), madness::F12Parameters::set_derived_values(), madness::Nemo_complex_Parameters::set_derived_values(), madness::OEP_Parameters::set_derived_values(), madness::Molecule::GeometryParameters::set_derived_values(), madness::CalculationParameters::set_derived_values(), madness::PNOParameters::set_derived_values(), madness::TDHFParameters::set_derived_values(), and madness::CC2::solve().
set_user_defined_value()
template<typename T > void madness::QCCalculationParametersBase::set_user_defined_value (const std::string & key, const T & value) inline
References get_parameter(), madness::nonlinear_vector_solver(), and tostring().
Referenced by madness::CalculationParameters::CalculationParameters(), main(), madness::Molecule::GeometryParameters::set_global_convenience_options(), madness::PlotParameters::set_npoints(), madness::PlotParameters::set_origin(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_orthomethod(), madness::PlotParameters::set_plane(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_radius(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_rank_revealing_tol(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_volume_element(), madness::PlotParameters::set_zoom(), madness::TDHF::test(), madness::Molecule::update_rcut_with_eprec(), and madness::MolecularEnergy::value().
to_json() [1/2]
json madness::QCCalculationParametersBase::to_json () const inline
convert all parameters to a json object
References madness::nonlinear_vector_solver(), and to_json().
Referenced by madness::operator==(), madness::SCF::output_calc_info_schema(), madness::Molecule::to_json(), and to_json().
to_json() [2/2]
void madness::QCCalculationParametersBase::to_json (json & j) const inline
convert all parameters to a json object
References madness::nonlinear_vector_solver(), p(), parameters, and qcparameter_to_json_from_tuple().
to_json_if_precedence()
json madness::QCCalculationParametersBase::to_json_if_precedence (const std::string & precedence) const inline
convert all parameters to a json object, but only those with a given precedence
References madness::nonlinear_vector_solver(), p(), parameters, and qcparameter_to_json_from_tuple().
Referenced by madness::Molecule::to_json_if_precedence().
tostring() [1/2]
static std::string madness::QCCalculationParametersBase::tostring (const bool & arg) inline static
References madness::arg(), and madness::nonlinear_vector_solver().
Referenced by TestCalculationParameters::extend_parameters(), fromstring(), set_derived_value(), set_user_defined_value(), and try_set_from_json().
tostring() [2/2]
template<typename T > static std::string madness::QCCalculationParametersBase::tostring (const T & arg) inline static
References madness::arg(), madness::nonlinear_vector_solver(), and overwrite_if_inf().
trim_blanks()
static std::string madness::QCCalculationParametersBase::trim_blanks (const std::string arg) inline static
References madness::arg(), and madness::nonlinear_vector_solver().
Referenced by read_quotes().
trim_quotes()
static std::string madness::QCCalculationParametersBase::trim_quotes (const std::string arg) inline static
References madness::arg(), and madness::nonlinear_vector_solver().
Referenced by read_quotes().
try_set_from_json()
template<typename... Types> bool madness::QCCalculationParametersBase::try_set_from_json (QCParameter & parameter, const nlohmann::json & value) inline
References madness::nonlinear_vector_solver(), and tostring().
Referenced by from_json().
try_setting_any()
template<typename Tuple > bool madness::QCCalculationParametersBase::try_setting_any (const std::string & key, const std::string & value) inline protected
helper function for try_setting_user_defined_value
References madness::nonlinear_vector_solver(), and try_setting_any_impl().
try_setting_any_impl()
template<typename Tuple , std::size_t... I> bool madness::QCCalculationParametersBase::try_setting_any_impl (const std::string & key, const std::string & value, Tuple , std::index_sequence< I... >) inline protected
helper function for try_setting_user_defined_value
References madness::nonlinear_vector_solver().
Referenced by try_setting_any().
try_setting_user_defined_value()
template<typename T > bool madness::QCCalculationParametersBase::try_setting_user_defined_value (const std::string & key, const std::string & val) inline protected
helper function for try_setting_user_defined_value
References get_parameter(), madness::name(), madness::nonlinear_vector_solver(), madness::print(), print_debug, and T().
Friends And Related Symbol Documentation
operator==
bool operator== (const QCCalculationParametersBase & p1, const QCCalculationParametersBase & p2) friend
Member Data Documentation
ignore_unknown_keys
bool madness::QCCalculationParametersBase::ignore_unknown_keys = true protected
Referenced by madness::Molecule::GeometryParameters::GeometryParameters(), and read_internal().
ignore_unknown_keys_silently
bool madness::QCCalculationParametersBase::ignore_unknown_keys_silently = false protected
Referenced by madness::Molecule::GeometryParameters::GeometryParameters(), and read_internal().
parameters
ParameterContainerT madness::QCCalculationParametersBase::parameters protected
Referenced by get_all_parameters(), get_parameter(), get_parameter(), hash(), parameter_exists(), print_to_string(), serialize(), to_json(), and to_json_if_precedence().
print_debug
bool madness::QCCalculationParametersBase::print_debug = false protected
Referenced by read_internal(), serialize(), and try_setting_user_defined_value().
throw_if_datagroup_not_found
bool madness::QCCalculationParametersBase::throw_if_datagroup_not_found = true protected
Referenced by madness::Molecule::GeometryParameters::GeometryParameters().
The documentation for this class was generated from the following files:
QCCalculationParametersBase.h
QCCalculationParametersBase.cc