MADNESS: madness::SCFProtocol Class Reference
madness::SCFProtocol Class Reference
struct for running a protocol of subsequently tightening precision
#include <SCFProtocol.h>
Public Member Functions
SCFProtocol (World &w, const CalculationParameters &param)
bool approx (const double a, const double b) const
compare two positive doubles to be equal
bool finished () const
void infer_thresholds (const double prec)
infer thresholds starting from a target precision
void initialize ()
SCFProtocol & operator++ ()
go to the next level
Public Attributes
bool converged
flag if protocol has converged
double current_prec
current precision
double dconv
density convergence of SCF calculations
double econv
energy convergence of SCF calculations
double end_prec
final precision
double start_prec
starting precision, typically 1.e-4
double thresh
numerical precision of representing functions
double user_dconv
density convergence provided by user
World & world
Detailed Description
struct for running a protocol of subsequently tightening precision
Constructor & Destructor Documentation
SCFProtocol()
madness::SCFProtocol::SCFProtocol (World & w, const CalculationParameters & param) inline
References param, and user_dconv.
Member Function Documentation
approx()
bool madness::SCFProtocol::approx (const double a, const double b) const inline
compare two positive doubles to be equal
References a, std::abs(), and b.
Referenced by infer_thresholds().
finished()
bool madness::SCFProtocol::finished () const inline
References converged.
Referenced by madness::Nemo::compute_all_cphf().
infer_thresholds()
void madness::SCFProtocol::infer_thresholds (const double prec) inline
infer thresholds starting from a target precision
References approx(), current_prec, dconv, econv, end_prec, thresh, and user_dconv.
Referenced by initialize(), and operator++().
initialize()
void madness::SCFProtocol::initialize () inline
References converged, current_prec, dconv, econv, end_prec, infer_thresholds(), madness::print(), madness::World::rank(), start_prec, thresh, madness::wall_time(), and world.
Referenced by madness::Nemo::compute_all_cphf().
operator++()
SCFProtocol & madness::SCFProtocol::operator++ () inline
go to the next level
References converged, current_prec, end_prec, and infer_thresholds().
Member Data Documentation
converged
bool madness::SCFProtocol::converged
flag if protocol has converged
Referenced by finished(), initialize(), and operator++().
current_prec
double madness::SCFProtocol::current_prec
current precision
Referenced by madness::Nemo::compute_all_cphf(), infer_thresholds(), initialize(), and operator++().
dconv
double madness::SCFProtocol::dconv
density convergence of SCF calculations
Referenced by infer_thresholds(), initialize(), madness::Nemo::solve(), and madness::Nemo::solve_cphf().
econv
double madness::SCFProtocol::econv
energy convergence of SCF calculations
Referenced by infer_thresholds(), initialize(), and madness::Nemo::solve().
end_prec
double madness::SCFProtocol::end_prec
final precision
Referenced by madness::Nemo::compute_all_cphf(), infer_thresholds(), initialize(), and operator++().
start_prec
double madness::SCFProtocol::start_prec
starting precision, typically 1.e-4
Referenced by initialize().
thresh
double madness::SCFProtocol::thresh
numerical precision of representing functions
Referenced by infer_thresholds(), and initialize().
user_dconv
double madness::SCFProtocol::user_dconv
density convergence provided by user
Referenced by SCFProtocol(), and infer_thresholds().
world
World& madness::SCFProtocol::world
Referenced by initialize().
The documentation for this class was generated from the following file:
SCFProtocol.h