MADNESS: madness::DFTCoulombPeriodicOp< T, NDIM > Class Template Reference
madness::DFTCoulombPeriodicOp< T, NDIM > Class Template Reference
#include <dft.h>
Public Member Functions
DFTCoulombPeriodicOp (World &world, funcT rhon, double coeff, double thresh)
virtual bool is_od ()
Is there an orbitally-dependent term?
virtual bool is_rd ()
Is there a density-dependent term?
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
virtual void prepare_op (Function< double, NDIM > rho)
Public Member Functions inherited from madness::EigSolverOp< T, NDIM >
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
double coeff ()
std::string messsageME ()
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
Public Attributes
SeparatedConvolution< T, NDIM > * _cop
Public Attributes inherited from madness::EigSolverOp< T, NDIM >
World & _world
Private Types
typedef Function< T, NDIM > funcT
Private Attributes
funcT _rhon
bool _spinpol
funcT _Vc
Additional Inherited Members
Protected Member Functions inherited from madness::EigSolverOp< T, NDIM >
void messageME (std::string messageME)
double thresh ()
Member Typedef Documentation
funcT
template<typename T , int NDIM> typedef Function<T,NDIM> madness::DFTCoulombPeriodicOp< T, NDIM >::funcT private
Constructor & Destructor Documentation
DFTCoulombPeriodicOp()
template<typename T , int NDIM> madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp (World & world, funcT rhon, double coeff, double thresh)
References madness::DFTCoulombPeriodicOp< T, NDIM >::_cop, madness::DFTCoulombPeriodicOp< T, NDIM >::_rhon, madness::DFTCoulombPeriodicOp< T, NDIM >::_spinpol, e(), madness::FunctionDefaults< NDIM >::get_cell_width(), L, madness::EigSolverOp< T, NDIM >::messageME(), and madness::EigSolverOp< T, NDIM >::thresh().
Member Function Documentation
is_od()
template<typename T , int NDIM> virtual bool madness::DFTCoulombPeriodicOp< T, NDIM >::is_od () inline virtual
Is there an orbitally-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
is_rd()
template<typename T , int NDIM> virtual bool madness::DFTCoulombPeriodicOp< T, NDIM >::is_rd () inline virtual
Is there a density-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
op_r()
template<typename T , int NDIM> Function< T, NDIM > madness::DFTCoulombPeriodicOp< T, NDIM >::op_r (const funcT & rho, const funcT & psi) virtual
Density-dependent portion of operator.
Reimplemented from madness::EigSolverOp< T, NDIM >.
References psi().
prepare_op()
template<typename T , int NDIM> void madness::DFTCoulombPeriodicOp< T, NDIM >::prepare_op (Function< double, NDIM > rho) virtual
References madness::apply().
Member Data Documentation
_cop
template<typename T , int NDIM> SeparatedConvolution<T,NDIM>* madness::DFTCoulombPeriodicOp< T, NDIM >::_cop
Referenced by madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp().
_rhon
template<typename T , int NDIM> funcT madness::DFTCoulombPeriodicOp< T, NDIM >::_rhon private
Referenced by madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp().
_spinpol
template<typename T , int NDIM> bool madness::DFTCoulombPeriodicOp< T, NDIM >::_spinpol private
Referenced by madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp().
_Vc
template<typename T , int NDIM> funcT madness::DFTCoulombPeriodicOp< T, NDIM >::_Vc private
The documentation for this class was generated from the following files:
dft.h
dft.cc