MADNESS: GaussianNucleusFunctor Class Reference
GaussianNucleusFunctor Class Reference
Public Member Functions
GaussianNucleusFunctor (Molecule &molecule, double bohr_rad)
std::vector< int > get_Alist ()
int get_num_atoms ()
std::vector< coord_3d > get_Rlist ()
std::vector< double > get_xi ()
std::vector< int > get_Zlist ()
double operator() (const coord_3d &r) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual std::vector< Vector< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
std::vector< int > m_Alist
std::vector< coord_3d > m_Rlist
std::vector< double > m_xi
std::vector< int > m_Zlist
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
GaussianNucleusFunctor()
GaussianNucleusFunctor::GaussianNucleusFunctor (Molecule & molecule, double bohr_rad) inline
References madness::Molecule::get_all_coords_vec(), madness::Molecule::get_atomic_number(), molecule, and pow().
Member Function Documentation
get_Alist()
std::vector<int> GaussianNucleusFunctor::get_Alist () inline
get_num_atoms()
int GaussianNucleusFunctor::get_num_atoms () inline
get_Rlist()
std::vector<coord_3d> GaussianNucleusFunctor::get_Rlist () inline
Referenced by DF::make_gaussian_potential().
get_xi()
std::vector<double> GaussianNucleusFunctor::get_xi () inline
get_Zlist()
std::vector<int> GaussianNucleusFunctor::get_Zlist () inline
Referenced by DF::make_gaussian_potential().
operator()()
double GaussianNucleusFunctor::operator() (const coord_3d & r) const inline
Member Data Documentation
m_Alist
std::vector<int> GaussianNucleusFunctor::m_Alist private
m_Rlist
std::vector<coord_3d> GaussianNucleusFunctor::m_Rlist private
m_xi
std::vector<double> GaussianNucleusFunctor::m_xi private
m_Zlist
std::vector<int> GaussianNucleusFunctor::m_Zlist private
The documentation for this class was generated from the following file:
DF.cc