MADNESS: madness::AtomicBasisFunction Class Reference
madness::AtomicBasisFunction Class Reference
Used to represent one basis function from a shell on a specific center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasisFunction (const AtomicBasisFunction &aofunc)
AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell &shell, int ibf)
void get_coords (double &x, double &y, double &z) const
madness::Vector< double, 3 > get_coords_vec () const
const char * get_desc () const
int get_index () const
const ContractedGaussianShell & get_shell () const
double operator() (double x, double y, double z) const
void print_me (std::ostream &s) const
double rangesq () const
Private Attributes
const int ibf
const int nbf
const ContractedGaussianShell & shell
const double xx
const double yy
const double zz
Detailed Description
Used to represent one basis function from a shell on a specific center.
Constructor & Destructor Documentation
AtomicBasisFunction() [1/2]
madness::AtomicBasisFunction::AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell & shell, int ibf) inline
AtomicBasisFunction() [2/2]
madness::AtomicBasisFunction::AtomicBasisFunction (const AtomicBasisFunction & aofunc) inline
Member Function Documentation
get_coords()
void madness::AtomicBasisFunction::get_coords (double & x, double & y, double & z) const inline
References xx, yy, and zz.
Referenced by AtomicBasisFunctor< Q >::AtomicBasisFunctor(), AtomicOrbitalFunctor::AtomicOrbitalFunctor(), and madness::WSTAtomicBasisFunctor::WSTAtomicBasisFunctor().
get_coords_vec()
madness::Vector< double, 3 > madness::AtomicBasisFunction::get_coords_vec () const inline
References xx, yy, and zz.
Referenced by madchem::AtomicBasisFunctor::special_points(), and AtomicBasisFunctor< Q >::special_points().
get_desc()
const char * madness::AtomicBasisFunction::get_desc () const inline
References madness::ContractedGaussianShell::get_desc(), ibf, and shell.
Referenced by madness::AtomicBasisSet::print_anal().
get_index()
int madness::AtomicBasisFunction::get_index () const inline
References ibf.
get_shell()
const ContractedGaussianShell & madness::AtomicBasisFunction::get_shell () const inline
References shell.
operator()()
double madness::AtomicBasisFunction::operator() (double x, double y, double z) const inline
References madness::ContractedGaussianShell::eval(), ibf, madness::ContractedGaussianShell::maxbf, shell, xx, yy, and zz.
print_me()
void AtomicBasisFunction::print_me (std::ostream & s) const
References ibf, nbf, shell, xx, yy, and zz.
rangesq()
double madness::AtomicBasisFunction::rangesq () const inline
References madness::ContractedGaussianShell::rangesq(), and shell.
Referenced by AtomicOrbitalFunctor::AtomicOrbitalFunctor(), and AtomicBasisFunctor< Q >::operator()().
Member Data Documentation
ibf
const int madness::AtomicBasisFunction::ibf private
Referenced by get_desc(), get_index(), operator()(), and print_me().
nbf
const int madness::AtomicBasisFunction::nbf private
Referenced by print_me().
shell
const ContractedGaussianShell& madness::AtomicBasisFunction::shell private
Referenced by get_desc(), get_shell(), operator()(), print_me(), and rangesq().
xx
const double madness::AtomicBasisFunction::xx private
Referenced by get_coords(), get_coords_vec(), operator()(), and print_me().
yy
const double madness::AtomicBasisFunction::yy private
Referenced by get_coords(), get_coords_vec(), operator()(), and print_me().
zz
const double madness::AtomicBasisFunction::zz private
Referenced by get_coords(), get_coords_vec(), operator()(), and print_me().
The documentation for this class was generated from the following files:
madness/chem/molecularbasis.h
molecularbasis.cc