MADNESS: madness::smooth< T, NDIM > Class Template Reference
madness::smooth< T, NDIM > Class Template Reference
#include <smooth.h>
Classes
struct inv_mask_functor
struct mask_functor
Public Member Functions
smooth (World &world)
smooth (World &world, const double &box_mask_factor, const double box_mask_cutoff)
Function< T, NDIM > cut_oscillations (const Function< T, NDIM > &f, const double &cutoff, const size_t order) const
double gauss_norm (const double &exponent) const
Function< T, NDIM > gaussian_smoothing (const Function< T, NDIM > &f, const double &eps=0.04, const std::string &name="nooutput") const
double get_density_thresh () const
Function< T, NDIM > linearize (const Function< T, NDIM > &ln_rho) const
Function< T, NDIM > make_density_mask (const Function< T, NDIM > &density) const
Function< T, NDIM > make_explog (const Function< T, NDIM > &f, const std::string &msg="function") const
Function< T, NDIM > make_inv_mask (const Function< T, NDIM > &mask) const
Function< T, NDIM > make_mask (const Function< T, NDIM > &samplef, const double &thresh) const
void make_plots (const Function< T, NDIM > &f, const std::string &name="function") const
Function< T, NDIM > make_sigma (const Function< T, NDIM > &density) const
Function< T, NDIM > merge_functions (const Function< T, NDIM > &f, const Function< T, NDIM > &sf, const double &thresh) const
Function< T, NDIM > merge_functions (const Function< T, NDIM > &f, const Function< T, NDIM > &sf, const Function< T, NDIM > &mask, const std::string &name="f") const
Function< T, NDIM > munge_density (const Function< T, NDIM > &density) const
void output (const std::string &msg) const
Function< T, NDIM > smooth_density (const Function< T, NDIM > &density, const std::string &msg="function")
Function< T, NDIM > smooth_density_from_orbitals (const std::vector< Function< T, NDIM > > &orbitals) const
Function< T, NDIM > smooth_sigma (const Function< T, NDIM > &density)
void test_1d () const
Private Attributes
const Function< T, NDIM > box_mask_
Function< T, NDIM > inv_mask_
Function< T, NDIM > mask_
World & world
Constructor & Destructor Documentation
smooth() [1/2]
template<typename T , std::size_t NDIM> madness::smooth< T, NDIM >::smooth (World & world) inline
smooth() [2/2]
template<typename T , std::size_t NDIM> madness::smooth< T, NDIM >::smooth (World & world, const double & box_mask_factor, const double box_mask_cutoff) inline
Member Function Documentation
cut_oscillations()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::cut_oscillations (const Function< T, NDIM > & f, const double & cutoff, const size_t order) const inline
References madness::f, madness::smooth< T, NDIM >::merge_functions(), and madness::project().
Referenced by madness::smooth< T, NDIM >::smooth_density_from_orbitals(), and madness::smooth< T, NDIM >::smooth_sigma().
gauss_norm()
template<typename T , std::size_t NDIM> double madness::smooth< T, NDIM >::gauss_norm (const double & exponent) const inline
References pow().
Referenced by madness::smooth< T, NDIM >::gaussian_smoothing().
gaussian_smoothing()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::gaussian_smoothing (const Function< T, NDIM > & f, const double & eps = 0.04, const std::string & name = "nooutput") const inline
References madness::apply(), madness::f, madness::smooth< T, NDIM >::gauss_norm(), L, madness::smooth< T, NDIM >::make_plots(), madness::name(), op(), madness::smooth< T, NDIM >::output(), madness::stringify(), and madness::smooth< T, NDIM >::world.
Referenced by madness::smooth< T, NDIM >::make_explog(), and madness::smooth< T, NDIM >::smooth_density().
get_density_thresh()
template<typename T , std::size_t NDIM> double madness::smooth< T, NDIM >::get_density_thresh () const inline
References madness::FunctionDefaults< NDIM >::get_thresh(), pow(), and thresh.
Referenced by madness::smooth< T, NDIM >::make_density_mask(), madness::smooth< T, NDIM >::smooth_density(), and madness::smooth< T, NDIM >::smooth_sigma().
linearize()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::linearize (const Function< T, NDIM > & ln_rho) const inline
References madness::smooth< T, NDIM >::make_plots(), and madness::project().
Referenced by madness::smooth< T, NDIM >::smooth_density().
make_density_mask()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::make_density_mask (const Function< T, NDIM > & density) const inline
References madness::smooth< T, NDIM >::get_density_thresh(), madness::smooth< T, NDIM >::make_plots(), and madness::Function< T, NDIM >::reconstruct().
make_explog()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::make_explog (const Function< T, NDIM > & f, const std::string & msg = "function") const inline
References madness::copy(), madness::f, madness::smooth< T, NDIM >::gaussian_smoothing(), madness::make_exp(), madness::make_log(), madness::smooth< T, NDIM >::make_plots(), and madness::Function< T, NDIM >::unaryop().
make_inv_mask()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::make_inv_mask (const Function< T, NDIM > & mask) const inline
References madness::FunctionFactory< T, NDIM >::f(), mask, madness::project(), unit(), madness::unitfunctor(), and madness::smooth< T, NDIM >::world.
Referenced by madness::smooth< T, NDIM >::merge_functions().
make_mask()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::make_mask (const Function< T, NDIM > & samplef, const double & thresh) const inline
References madness::smooth< T, NDIM >::make_plots(), mask, madness::project(), madness::Function< T, NDIM >::reconstruct(), and thresh.
make_plots()
template<typename T , std::size_t NDIM> void madness::smooth< T, NDIM >::make_plots (const Function< T, NDIM > & f, const std::string & name = "function") const inline
References madness::f, madness::FunctionDefaults< NDIM >::get_cell_min_width(), madness::name(), madness::plot_line(), madness::plot_plane(), and madness::smooth< T, NDIM >::world.
Referenced by madness::smooth< T, NDIM >::gaussian_smoothing(), madness::smooth< T, NDIM >::linearize(), madness::smooth< T, NDIM >::make_density_mask(), madness::smooth< T, NDIM >::make_explog(), madness::smooth< T, NDIM >::make_mask(), madness::smooth< T, NDIM >::merge_functions(), madness::smooth< T, NDIM >::smooth_density(), madness::smooth< T, NDIM >::smooth_density_from_orbitals(), and madness::smooth< T, NDIM >::smooth_sigma().
make_sigma()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::make_sigma (const Function< T, NDIM > & density) const inline
References madness::Function< T, NDIM >::autorefine(), d, gradop, MADNESS_ASSERT, NDIM, sigma, and madness::smooth< T, NDIM >::world.
Referenced by madness::smooth< T, NDIM >::smooth_sigma().
merge_functions() [1/2]
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::merge_functions (const Function< T, NDIM > & f, const Function< T, NDIM > & sf, const double & thresh) const inline
References madness::f, MADNESS_ASSERT, NDIM, madness::refine_to_common_level(), thresh, and madness::smooth< T, NDIM >::world.
merge_functions() [2/2]
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::merge_functions (const Function< T, NDIM > & f, const Function< T, NDIM > & sf, const Function< T, NDIM > & mask, const std::string & name = "f") const inline
References madness::f, madness::smooth< T, NDIM >::make_inv_mask(), madness::smooth< T, NDIM >::make_plots(), mask, and madness::name().
Referenced by madness::smooth< T, NDIM >::cut_oscillations(), and madness::smooth< T, NDIM >::smooth_density().
munge_density()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::munge_density (const Function< T, NDIM > & density) const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
output()
template<typename T , std::size_t NDIM> void madness::smooth< T, NDIM >::output (const std::string & msg) const inline
References madness::World::rank(), and madness::smooth< T, NDIM >::world.
Referenced by madness::smooth< T, NDIM >::gaussian_smoothing(), and madness::smooth< T, NDIM >::test_1d().
smooth_density()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::smooth_density (const Function< T, NDIM > & density, const std::string & msg = "function") inline
References madness::copy(), madness::smooth< T, NDIM >::gaussian_smoothing(), madness::smooth< T, NDIM >::get_density_thresh(), madness::smooth< T, NDIM >::linearize(), madness::make_exp(), madness::make_log(), madness::smooth< T, NDIM >::make_plots(), madness::smooth< T, NDIM >::merge_functions(), madness::smooth< T, NDIM >::smooth_density(), and madness::Function< T, NDIM >::unaryop().
Referenced by madness::smooth< T, NDIM >::smooth_density().
smooth_density_from_orbitals()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::smooth_density_from_orbitals (const std::vector< Function< T, NDIM > > & orbitals) const inline
References madness::smooth< T, NDIM >::cut_oscillations(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::smooth< T, NDIM >::make_plots(), madness::Function< T, NDIM >::refine(), madness::stringify(), thresh, and madness::smooth< T, NDIM >::world.
Referenced by main().
smooth_sigma()
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::smooth< T, NDIM >::smooth_sigma (const Function< T, NDIM > & density) inline
References madness::smooth< T, NDIM >::cut_oscillations(), madness::smooth< T, NDIM >::get_density_thresh(), MADNESS_ASSERT, madness::smooth< T, NDIM >::make_plots(), madness::smooth< T, NDIM >::make_sigma(), NDIM, sigma, and madness::smooth< T, NDIM >::smooth_sigma().
Referenced by madness::smooth< T, NDIM >::smooth_sigma().
test_1d()
template<typename T , std::size_t NDIM> void madness::smooth< T, NDIM >::test_1d () const inline
References madness::apply(), diff(), madness::f, L, madness::norm2(), op(), madness::smooth< T, NDIM >::output(), madness::plot_line(), pow(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::stringify(), madness::test_1d_functor(), and madness::smooth< T, NDIM >::world.
Member Data Documentation
box_mask_
template<typename T , std::size_t NDIM> const Function<T, NDIM> madness::smooth< T, NDIM >::box_mask_ private
inv_mask_
template<typename T , std::size_t NDIM> Function<T, NDIM> madness::smooth< T, NDIM >::inv_mask_ private
mask_
template<typename T , std::size_t NDIM> Function<T, NDIM> madness::smooth< T, NDIM >::mask_ private
world
template<typename T , std::size_t NDIM> World& madness::smooth< T, NDIM >::world private
Referenced by madness::smooth< T, NDIM >::gaussian_smoothing(), madness::smooth< T, NDIM >::make_inv_mask(), madness::smooth< T, NDIM >::make_plots(), madness::smooth< T, NDIM >::make_sigma(), madness::smooth< T, NDIM >::merge_functions(), madness::smooth< T, NDIM >::output(), madness::smooth< T, NDIM >::smooth_density_from_orbitals(), and madness::smooth< T, NDIM >::test_1d().
The documentation for this class was generated from the following file:
smooth.h