MADNESS: madness::archive::ContainerRecordInputArchive Class Reference
madness::archive::ContainerRecordInputArchive Class Reference
#include <parallel_dc_archive.h>
Public Member Functions
ContainerRecordInputArchive (World &subworld, const containerT &dc, const keyT &key)
~ContainerRecordInputArchive ()
void close ()
void flush ()
template<class T >
std::enable_if< madness::is_trivially_serializable< T >::value, void >::type load (T *t, long n) const
void open ()
Public Member Functions inherited from madness::archive::BaseArchive
BaseArchive ()
Private Types
using containerT = WorldContainer< keyT, std::vector< unsigned char > >
using keyT = long
Private Attributes
VectorInputArchive ar
ProcessID rank
std::vector< unsigned char > v
Additional Inherited Members
Public Types inherited from madness::archive::BaseInputArchive
using is_loading = std::true_type
Type used by Boost.Serialization to determine if this object is an input archive.
Public Types inherited from madness::archive::BaseArchive
using is_loading = std::false_type
Type used by Boost.Serialization to determine if this object is an input archive.
using is_saving = std::false_type
Type used by Boost.Serialization to determine if this object is an output archive.
Static Public Attributes inherited from madness::archive::BaseInputArchive
static constexpr bool is_input_archive = true
Flag to determine if this object is an input archive.
Static Public Attributes inherited from madness::archive::BaseArchive
static constexpr bool is_archive = true
Flag to determine if this object is an archive.
static constexpr bool is_input_archive = false
Flag to determine if this object is an input archive.
static constexpr bool is_output_archive = false
Flag to determine if this object is an output archive.
static constexpr bool is_parallel_archive = false
Flag to determine if this object is a parallel archive.
Member Typedef Documentation
containerT
using madness::archive::ContainerRecordInputArchive::containerT = WorldContainer<keyT,std::vector<unsigned char> > private
keyT
using madness::archive::ContainerRecordInputArchive::keyT = long private
Constructor & Destructor Documentation
ContainerRecordInputArchive()
madness::archive::ContainerRecordInputArchive::ContainerRecordInputArchive (World & subworld, const containerT & dc, const keyT & key) inline
References madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::WorldContainer< keyT, valueT, hashfunT >::get_world(), madness::World::id(), MADNESS_EXCEPTION, rank, and v.
~ContainerRecordInputArchive()
madness::archive::ContainerRecordInputArchive::~ContainerRecordInputArchive () inline
Member Function Documentation
close()
void madness::archive::ContainerRecordInputArchive::close () inline
flush()
void madness::archive::ContainerRecordInputArchive::flush () inline
load()
template<class T > std::enable_if< madness::is_trivially_serializable<T>::value, void >::type madness::archive::ContainerRecordInputArchive::load (T * t, long n) const inline
References ar, madness::archive::VectorInputArchive::load(), MADNESS_CHECK, and rank.
open()
void madness::archive::ContainerRecordInputArchive::open () inline
Member Data Documentation
ar
VectorInputArchive madness::archive::ContainerRecordInputArchive::ar private
Referenced by load().
rank
ProcessID madness::archive::ContainerRecordInputArchive::rank private
Referenced by ContainerRecordInputArchive(), and load().
v
std::vector<unsigned char> madness::archive::ContainerRecordInputArchive::v private
Referenced by ContainerRecordInputArchive().
The documentation for this class was generated from the following file:
parallel_dc_archive.h