MADNESS: Func< FLOAT > Class Template Reference
Func< FLOAT > Class Template Reference
Public Member Functions
Func (const vector< FLOAT > &x, const vector< FLOAT > &f, const vector< FLOAT > &p, const vector< FLOAT > &dp)
Func (const vector< FLOAT > &x, const vector< FLOAT > &f, const vector< FLOAT > &p, const vector< FLOAT > &dp)
Func (const vector< FLOAT > &x, const vector< FLOAT > &f, const vector< FLOAT > &p, const vector< FLOAT > &dp)
Func (const vector< FLOAT > &x, const vector< FLOAT > &f, const vector< FLOAT > &p, const vector< FLOAT > &dp)
FLOAT operator() (const FLOAT &s) const
FLOAT operator() (const FLOAT &s) const
FLOAT operator() (const FLOAT &s) const
FLOAT operator() (const FLOAT &s) const
Private Attributes
const vector< FLOAT > & dp
const vector< FLOAT > & f
const vector< FLOAT > & p
vector< FLOAT > pnew
const vector< FLOAT > & x
Constructor & Destructor Documentation
Func() [1/4]
template<typename FLOAT > Func< FLOAT >::Func (const vector< FLOAT > & x, const vector< FLOAT > & f, const vector< FLOAT > & p, const vector< FLOAT > & dp) inline
Func() [2/4]
template<typename FLOAT > Func< FLOAT >::Func (const vector< FLOAT > & x, const vector< FLOAT > & f, const vector< FLOAT > & p, const vector< FLOAT > & dp) inline
Func() [3/4]
template<typename FLOAT > Func< FLOAT >::Func (const vector< FLOAT > & x, const vector< FLOAT > & f, const vector< FLOAT > & p, const vector< FLOAT > & dp) inline
Func() [4/4]
template<typename FLOAT > Func< FLOAT >::Func (const vector< FLOAT > & x, const vector< FLOAT > & f, const vector< FLOAT > & p, const vector< FLOAT > & dp) inline
Member Function Documentation
operator()() [1/4]
template<typename FLOAT > FLOAT Func< FLOAT >::operator() (const FLOAT & s) const inline
References Func< FLOAT >::dp, Func< FLOAT >::f, std::isnan(), makedata(), Func< FLOAT >::p, Func< FLOAT >::pnew, and Func< FLOAT >::x.
operator()() [2/4]
template<typename FLOAT > FLOAT Func< FLOAT >::operator() (const FLOAT & s) const inline
References Func< FLOAT >::dp, Func< FLOAT >::f, std::isnan(), makedata(), Func< FLOAT >::p, Func< FLOAT >::pnew, and Func< FLOAT >::x.
operator()() [3/4]
template<typename FLOAT > FLOAT Func< FLOAT >::operator() (const FLOAT & s) const inline
References Func< FLOAT >::dp, Func< FLOAT >::f, std::isnan(), makedata(), Func< FLOAT >::p, Func< FLOAT >::pnew, and Func< FLOAT >::x.
operator()() [4/4]
template<typename FLOAT > FLOAT Func< FLOAT >::operator() (const FLOAT & s) const inline
References Func< FLOAT >::dp, Func< FLOAT >::f, std::isnan(), makedata(), Func< FLOAT >::p, Func< FLOAT >::pnew, and Func< FLOAT >::x.
Member Data Documentation
dp
template<typename FLOAT > const vector< FLOAT > & Func< FLOAT >::dp private
Referenced by Func< FLOAT >::operator()().
f
template<typename FLOAT > const vector< FLOAT > & Func< FLOAT >::f private
Referenced by Func< FLOAT >::operator()().
p
template<typename FLOAT > const vector< FLOAT > & Func< FLOAT >::p private
Referenced by Func< FLOAT >::operator()().
pnew
template<typename FLOAT > vector< FLOAT > Func< FLOAT >::pnew mutable private
Referenced by Func< FLOAT >::operator()().
x
template<typename FLOAT > const vector< FLOAT > & Func< FLOAT >::x private
Referenced by Func< FLOAT >::operator()().
The documentation for this class was generated from the following files:
y.cc
y1.cc
y_signed.cc
y_varx.cc