MADNESS: madness::ConcurrentHashMap< keyT, valueT, hashfunT > Class Template Reference
madness::ConcurrentHashMap< keyT, valueT, hashfunT > Class Template Reference
#include <worldhashmap.h>
Public Types
typedef Hash_private::HashAccessor< hashT, entryT::WRITELOCK > accessor
typedef Hash_private::bin< keyT, valueT > binT
typedef Hash_private::HashAccessor< const hashT, entryT::READLOCK > const_accessor
typedef Hash_private::HashIterator< const hashT > const_iterator
typedef std::pair< const keyT, valueT > datumT
typedef Hash_private::entry< keyT, valueT > entryT
typedef ConcurrentHashMap< keyT, valueT, hashfunT > hashT
typedef Hash_private::HashIterator< hashT > iterator
Public Member Functions
ConcurrentHashMap (const hashT &h)
ConcurrentHashMap (int n=1021, const hashfunT &hf=hashfunT())
virtual ~ConcurrentHashMap ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const_iterator cend () const
void clear ()
iterator end ()
const_iterator end () const
void erase (accessor &item)
void erase (const iterator &it)
void erase (const_accessor &item)
bool find (accessor &result, const keyT &key)
iterator find (const keyT &key)
const_iterator find (const keyT &key) const
bool find (const_accessor &result, const keyT &key) const
const hashfunT & get_hash () const
bool insert (accessor &result, const datumT &datum)
Returns true if new pair was inserted; false if key is already in the map and the datum was not inserted.
bool insert (accessor &result, const keyT &key)
Returns true if new pair was inserted; false if key is already in the map.
std::pair< iterator, bool > insert (const datumT &datum)
bool insert (const_accessor &result, const datumT &datum)
Returns true if new pair was inserted; false if key is already in the map and the datum was not inserted.
bool insert (const_accessor &result, const keyT &key)
Returns true if new pair was inserted; false if key is already in the map.
hashT & operator= (const hashT &h)
valueT & operator[] (const keyT &key)
void print_stats () const
size_t size () const
bool try_erase (const keyT &key)
Protected Attributes
binT * bins
const size_t nbins
Private Member Functions
unsigned int hash_to_bin (const keyT &key) const
Static Private Member Functions
static int nbins_prime (int n)
Private Attributes
hashfunT hashfun
Friends
class Hash_private::HashIterator< const hashT >
class Hash_private::HashIterator< hashT >
Member Typedef Documentation
accessor
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef Hash_private::HashAccessor<hashT,entryT::WRITELOCK> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::accessor
binT
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef Hash_private::bin<keyT,valueT> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::binT
const_accessor
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef Hash_private::HashAccessor<const hashT,entryT::READLOCK> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::const_accessor
const_iterator
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef Hash_private::HashIterator<const hashT> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::const_iterator
datumT
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef std::pair<const keyT,valueT> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::datumT
entryT
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef Hash_private::entry<keyT,valueT> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::entryT
hashT
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef ConcurrentHashMap<keyT,valueT,hashfunT> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hashT
iterator
template<class keyT , class valueT , class hashfunT = Hash<keyT>> typedef Hash_private::HashIterator<hashT> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::iterator
Constructor & Destructor Documentation
ConcurrentHashMap() [1/2]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::ConcurrentHashMap (int n = 1021, const hashfunT & hf = hashfunT()) inline
ConcurrentHashMap() [2/2]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> madness::ConcurrentHashMap< keyT, valueT, hashfunT >::ConcurrentHashMap (const hashT & h) inline
References h().
~ConcurrentHashMap()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> virtual madness::ConcurrentHashMap< keyT, valueT, hashfunT >::~ConcurrentHashMap () inline virtual
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins.
Member Function Documentation
begin() [1/2]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin () inline
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::begin(), madness::World::get_object_ids(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1(), and test_coverage().
begin() [2/2]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const_iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::cbegin().
cbegin()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const_iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::cbegin () const inline
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin().
cend()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const_iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::cend () const inline
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end().
clear()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> void madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear () inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::nbins.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::clear(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::operator=(), madness::SimpleCache< Q, NDIM >::operator=(), and madness::Timer::reset().
end() [1/2]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end () inline
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::end(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_handler(), madness::World::get_object_ids(), madness::SimpleCache< Q, NDIM >::getptr(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::probe(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::redistribute_phase1(), and test_coverage().
end() [2/2]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const_iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::cend().
erase() [1/3]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> void madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase (accessor & item) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::Hash_private::bin< keyT, valueT >::del(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::Hash_private::HashAccessor< hashT, lockmode >::unset(), and madness::MutexReaderWriter::WRITELOCK.
erase() [2/3]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> void madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase (const iterator & it) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), MADNESS_ASSERT, MADNESS_EXCEPTION, and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::try_erase().
Referenced by madness::detail::DistCache< keyT >::get_cache_value(), madness::detail::DistCache< keyT >::get_cache_value(), madness::detail::DistCache< keyT >::set_cache_value(), and madness::World::unregister_ptr().
erase() [3/3]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> void madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase (const_accessor & item) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::Hash_private::HashAccessor< hashT, lockmode >::convert_read_lock_to_write_lock(), madness::Hash_private::bin< keyT, valueT >::del(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::Hash_private::HashAccessor< hashT, lockmode >::unset(), and madness::MutexReaderWriter::WRITELOCK.
find() [1/4]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find (accessor & result, const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::Hash_private::bin< keyT, valueT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::Hash_private::HashAccessor< hashT, lockmode >::release(), madness::Hash_private::HashAccessor< hashT, lockmode >::set(), and madness::MutexReaderWriter::WRITELOCK.
find() [2/4]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find (const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::Hash_private::bin< keyT, valueT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), and madness::MutexReaderWriter::NOLOCK.
Referenced by madness::Timer::accumulate(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_handler(), madness::SimpleCache< Q, NDIM >::getptr(), madness::World::id_from_ptr(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::probe(), madness::World::ptr_from_id(), Peasant::run(), test_coverage(), and madness::World::unregister_ptr().
find() [3/4]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const_iterator madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find (const keyT & key) const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::Hash_private::bin< keyT, valueT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), and madness::MutexReaderWriter::NOLOCK.
find() [4/4]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find (const_accessor & result, const keyT & key) const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::Hash_private::bin< keyT, valueT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::MutexReaderWriter::READLOCK, madness::Hash_private::HashAccessor< hashT, lockmode >::release(), and madness::Hash_private::HashAccessor< hashT, lockmode >::set().
get_hash()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const hashfunT & madness::ConcurrentHashMap< keyT, valueT, hashfunT >::get_hash () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hashfun.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::get_hash().
hash_to_bin()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> unsigned int madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin (const keyT & key) const inline private
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hashfun, and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::nbins.
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::try_erase().
insert() [1/5]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert (accessor & result, const datumT & datum) inline
Returns true if new pair was inserted; false if key is already in the map and the datum was not inserted.
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::Hash_private::bin< keyT, valueT >::insert(), madness::Hash_private::HashAccessor< hashT, lockmode >::release(), madness::Hash_private::HashAccessor< hashT, lockmode >::set(), and madness::MutexReaderWriter::WRITELOCK.
insert() [2/5]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert (accessor & result, const keyT & key) inline
Returns true if new pair was inserted; false if key is already in the map.
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
insert() [3/5]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> std::pair< iterator, bool > madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert (const datumT & datum) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::Hash_private::bin< keyT, valueT >::insert(), and madness::MutexReaderWriter::NOLOCK.
Referenced by madness::Timer::accumulate(), madness::detail::DistCache< keyT >::get_cache_value(), madness::detail::DistCache< keyT >::get_cache_value(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert_const_acc(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::itemfun(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::operator=(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::operator[](), madness::World::register_ptr(), madness::SimpleCache< Q, NDIM >::set(), and madness::detail::DistCache< keyT >::set_cache_value().
insert() [4/5]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert (const_accessor & result, const datumT & datum) inline
Returns true if new pair was inserted; false if key is already in the map and the datum was not inserted.
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::Hash_private::bin< keyT, valueT >::insert(), madness::MutexReaderWriter::READLOCK, madness::Hash_private::HashAccessor< hashT, lockmode >::release(), and madness::Hash_private::HashAccessor< hashT, lockmode >::set().
insert() [5/5]
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert (const_accessor & result, const keyT & key) inline
Returns true if new pair was inserted; false if key is already in the map.
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
nbins_prime()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> static int madness::ConcurrentHashMap< keyT, valueT, hashfunT >::nbins_prime (int n) inline static private
operator=()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> hashT & madness::ConcurrentHashMap< keyT, valueT, hashfunT >::operator= (const hashT & h) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), h(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), MADNESS_ASSERT, and p().
operator[]()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> valueT & madness::ConcurrentHashMap< keyT, valueT, hashfunT >::operator[] (const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
print_stats()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> void madness::ConcurrentHashMap< keyT, valueT, hashfunT >::print_stats () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::nbins, and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size().
size()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> size_t madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::nbins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size(), and sum.
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::print_stats(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::size(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size().
try_erase()
template<class keyT , class valueT , class hashfunT = Hash<keyT>> bool madness::ConcurrentHashMap< keyT, valueT, hashfunT >::try_erase (const keyT & key) inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), and madness::MutexReaderWriter::NOLOCK.
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::erase(), and madness::World::unregister_ptr().
Friends And Related Symbol Documentation
Hash_private::HashIterator< const hashT >
template<class keyT , class valueT , class hashfunT = Hash<keyT>> friend class Hash_private::HashIterator< const hashT > friend
Hash_private::HashIterator< hashT >
template<class keyT , class valueT , class hashfunT = Hash<keyT>> friend class Hash_private::HashIterator< hashT > friend
Member Data Documentation
bins
template<class keyT , class valueT , class hashfunT = Hash<keyT>> binT* madness::ConcurrentHashMap< keyT, valueT, hashfunT >::bins protected
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::~ConcurrentHashMap(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::print_stats(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::try_erase().
hashfun
template<class keyT , class valueT , class hashfunT = Hash<keyT>> hashfunT madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hashfun private
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::get_hash(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin().
nbins
template<class keyT , class valueT , class hashfunT = Hash<keyT>> const size_t madness::ConcurrentHashMap< keyT, valueT, hashfunT >::nbins protected
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::hash_to_bin(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::print_stats(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::size().
The documentation for this class was generated from the following file:
worldhashmap.h