MADNESS: TTT Class Reference
TTT Class Reference
Public Member Functions
TTT ()
double hugh (vector< Future< int > > &a)
double jody (double a, double b, double c)
Static Public Member Functions
static int bert (int input)
static int carl ()
static int dave (World *world)
static void fred ()
static string kate (World *world, const string &msg, double d)
static int mary ()
static double_complex sara (double a, const double_complex &b)
Private Attributes
int state
Constructor & Destructor Documentation
TTT()
TTT::TTT () inline
Member Function Documentation
bert()
static int TTT::bert (int input) inline static
Referenced by test5().
carl()
static int TTT::carl () inline static
Referenced by test5().
dave()
static int TTT::dave (World * world) inline static
References madness::World::rank().
Referenced by test5().
fred()
static void TTT::fred () inline static
References madness::print().
Referenced by test5().
hugh()
double TTT::hugh (vector< Future< int > > & a) inline
References a, and sum.
Referenced by test5().
jody()
double TTT::jody (double a, double b, double c) inline
References a, b, c, and state.
Referenced by test5().
kate()
static string TTT::kate (World * world, const string & msg, double d) inline static
References d, and madness::World::rank().
Referenced by test5().
mary()
static int TTT::mary () inline static
Referenced by test5().
sara()
static double_complex TTT::sara (double a, const double_complex & b) inline static
References a, and b.
Referenced by test5().
Member Data Documentation
state
int TTT::state private
Referenced by jody().
The documentation for this class was generated from the following file:
test_world.cc