MADNESS: madness::AbstractVectorSpace< T, real_type, scalar_type > Class Template Reference
madness::AbstractVectorSpace< T, real_type, scalar_type > Class Template Reference abstract
A generic vector space which provides common operations needed by linear algebra routines (norm, inner product, etc.)
#include <gmres.h>
Public Member Functions
AbstractVectorSpace (World &world)
Make a vector space.
virtual ~AbstractVectorSpace ()
virtual void destroy (T &) const
Any special instructions to be executed when a vector is no longer needed.
virtual T & gaxpy (T &x, const scalar_type &a, const T &y, const scalar_type &b) const =0
Standard bilinear gaxpy.
virtual scalar_type inner (const T &, const T &) const =0
The inner product between two vectors.
virtual real_type norm (const T &) const =0
The norm of a vector.
virtual T & scale (T &, const scalar_type &) const =0
Scales the vector (in-place) by a constant.
Public Attributes
World & world
The world.
Private Member Functions
AbstractVectorSpace ()
Bury the default constructor to prevent its use.
Detailed Description
template<typename T, typename real_type, typename scalar_type>
class madness::AbstractVectorSpace< T, real_type, scalar_type >
A generic vector space which provides common operations needed by linear algebra routines (norm, inner product, etc.)
Most of these routines will presumedly be defined, but the names may not be the same (i.e. madness:Function uses norm2, madness::Tensor uses normf)
T is the vector type
real_type the real type used for norms, etc.
scalar_type is the type used for inner products and gaxpy coefficients, etc.
When implementing a child class, real_type and scalar_type will probably be obtained from TensorTypeData<T> (see the VectorSpace and FunctionSpace classes below).
Constructor & Destructor Documentation
AbstractVectorSpace() [1/2]
template<typename T , typename real_type , typename scalar_type > madness::AbstractVectorSpace< T, real_type, scalar_type >::AbstractVectorSpace () private
Bury the default constructor to prevent its use.
AbstractVectorSpace() [2/2]
template<typename T , typename real_type , typename scalar_type > madness::AbstractVectorSpace< T, real_type, scalar_type >::AbstractVectorSpace (World & world) inline
Make a vector space.
The World is needed to limit output, and may be needed for spaces working with MADNESS functions.
Parameters
[in] world The world.
~AbstractVectorSpace()
template<typename T , typename real_type , typename scalar_type > virtual madness::AbstractVectorSpace< T, real_type, scalar_type >::~AbstractVectorSpace () inline virtual
Member Function Documentation
destroy()
template<typename T , typename real_type , typename scalar_type > virtual void madness::AbstractVectorSpace< T, real_type, scalar_type >::destroy (T &) const inline virtual
Any special instructions to be executed when a vector is no longer needed.
Unless otherwise specified, do nothing.
Reimplemented in madness::FunctionSpace< T, NDIM >, and madness::VectorOfFunctionsSpace< T, VDIM, FDIM >.
Referenced by madness::GMRES().
gaxpy()
template<typename T , typename real_type , typename scalar_type > virtual T & madness::AbstractVectorSpace< T, real_type, scalar_type >::gaxpy (T & x, const scalar_type & a, const T & y, const scalar_type & b) const pure virtual
Standard bilinear gaxpy.
Returns
The new vector,
Implemented in madness::FunctionSpace< T, NDIM >, madness::VectorOfFunctionsSpace< T, VDIM, FDIM >, and madness::VectorSpace< T, NDIM >.
Referenced by madness::GMRES().
inner()
template<typename T , typename real_type , typename scalar_type > virtual scalar_type madness::AbstractVectorSpace< T, real_type, scalar_type >::inner (const T & , const T &) const pure virtual
The inner product between two vectors.
Implemented in madness::FunctionSpace< T, NDIM >, madness::VectorOfFunctionsSpace< T, VDIM, FDIM >, and madness::VectorSpace< T, NDIM >.
Referenced by madness::GMRES().
norm()
template<typename T , typename real_type , typename scalar_type > virtual real_type madness::AbstractVectorSpace< T, real_type, scalar_type >::norm (const T &) const pure virtual
The norm of a vector.
Implemented in madness::FunctionSpace< T, NDIM >, madness::VectorOfFunctionsSpace< T, VDIM, FDIM >, and madness::VectorSpace< T, NDIM >.
Referenced by madness::GMRES().
scale()
template<typename T , typename real_type , typename scalar_type > virtual T & madness::AbstractVectorSpace< T, real_type, scalar_type >::scale (T & , const scalar_type &) const pure virtual
Scales the vector (in-place) by a constant.
Returns
The scaled vector
Implemented in madness::FunctionSpace< T, NDIM >, madness::VectorOfFunctionsSpace< T, VDIM, FDIM >, and madness::VectorSpace< T, NDIM >.
Referenced by madness::GMRES().
Member Data Documentation
world
template<typename T , typename real_type , typename scalar_type > World& madness::AbstractVectorSpace< T, real_type, scalar_type >::world
The world.
Referenced by madness::GMRES().
The documentation for this class was generated from the following file:
gmres.h