MADNESS: madness::KPoint Class Reference
madness::KPoint Class Reference
#include <eigsolver.h>
Public Member Functions
KPoint (double kx, double ky, double kz, double weight)
double kx ()
double ky ()
double kz ()
double weight ()
Private Attributes
double _kx
double _ky
double _kz
double _weight
Constructor & Destructor Documentation
KPoint()
madness::KPoint::KPoint (double kx, double ky, double kz, double weight) inline
References _kx, _ky, _kz, _weight, kx(), ky(), kz(), and weight().
Member Function Documentation
kx()
double madness::KPoint::kx () inline
References _kx.
Referenced by KPoint().
ky()
double madness::KPoint::ky () inline
References _ky.
Referenced by KPoint().
kz()
double madness::KPoint::kz () inline
References _kz.
Referenced by KPoint().
weight()
double madness::KPoint::weight () inline
References _weight.
Referenced by KPoint(), madness::Solver< T, NDIM >::compute_rho(), madness::Solver< T, NDIM >::compute_rho_slow(), and madness::Solver< T, NDIM >::init().
Member Data Documentation
_kx
double madness::KPoint::_kx private
Referenced by KPoint(), and kx().
_ky
double madness::KPoint::_ky private
Referenced by KPoint(), and ky().
_kz
double madness::KPoint::_kz private
Referenced by KPoint(), and kz().
_weight
double madness::KPoint::_weight private
Referenced by KPoint(), and weight().
The documentation for this class was generated from the following file:
eigsolver.h