MADNESS: madness::Batch Class Reference
madness::Batch Class Reference
a batch consists of a 2D-input batch and a 1D-output batch: K-batch <- (I-batch, J-batch)
#include <macrotaskpartitioner.h>
Public Member Functions
Batch ()
Batch (Batch_1D input1, Batch_1D input2, Batch_1D result)
Batch (Batch_1D input1, Batch_1D result)
Batch (const Batch &other)
template<typename tupleT >
tupleT copy_input_batch (const tupleT &arg) const
select the relevant vector elements from the argument tuple
template<typename vecT >
vecT insert_result_batch (vecT v, const vecT &v_batch) const
copy v_batch into the result vector
Batch & operator= (const Batch &other)
std::size_t size_of_input () const
Public Attributes
std::vector< Batch_1D > input
Batch_1D result
Friends
class MacroTaskPartitioner
std::ostream & operator<< (std::ostream &os, const Batch &batch)
pretty print this batch
Detailed Description
a batch consists of a 2D-input batch and a 1D-output batch: K-batch <- (I-batch, J-batch)
Constructor & Destructor Documentation
Batch() [1/4]
madness::Batch::Batch () inline
Batch() [2/4]
madness::Batch::Batch (const Batch & other) inline
Batch() [3/4]
madness::Batch::Batch (Batch_1D input1, Batch_1D result) inline
Batch() [4/4]
madness::Batch::Batch (Batch_1D input1, Batch_1D input2, Batch_1D result) inline
Member Function Documentation
copy_input_batch()
template<typename tupleT > tupleT madness::Batch::copy_input_batch (const tupleT & arg) const inline
select the relevant vector elements from the argument tuple
References madness::arg(), input, and MADNESS_CHECK.
Referenced by test_batch().
insert_result_batch()
template<typename vecT > vecT madness::Batch::insert_result_batch (vecT v, const vecT & v_batch) const inline
copy v_batch into the result vector
References madness::Batch_1D::insert_batch(), result, and v.
Referenced by test_batch().
operator=()
Batch & madness::Batch::operator= (const Batch & other) inline
References input, and result.
size_of_input()
std::size_t madness::Batch::size_of_input () const inline
References input, result, and madness::Batch_1D::size().
Referenced by madness::MacroTaskPartitioner::compute_priority().
Friends And Related Symbol Documentation
MacroTaskPartitioner
friend class MacroTaskPartitioner friend
operator<<
std::ostream & operator<< (std::ostream & os, const Batch & batch) friend
pretty print this batch
Member Data Documentation
input
std::vector<Batch_1D> madness::Batch::input
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeSimple::MacroTaskPartitionerExchange::compute_priority(), copy_input_batch(), madness::MP3::MacroTaskMP3::operator()(), VectorOfScalarTask::operator()(), operator=(), and size_of_input().
result
Batch_1D madness::Batch::result
Referenced by insert_result_batch(), madness::MP3::MacroTaskMP3::operator()(), operator=(), and size_of_input().
The documentation for this class was generated from the following file:
macrotaskpartitioner.h