MADNESS: madness::dftgrid< NDIM > Class Template Reference
madness::dftgrid< NDIM > Class Template Reference
#include <lowrankfunction.h>
Public Member Functions
dftgrid (const double volume_element, const double radius)
dftgrid (const std::size_t nradial, const std::size_t angular_order, const coord_3d origin=coord_3d())
std::vector< Vector< double, NDIM > > get_grid () const
Public Member Functions inherited from madness::gridbase
virtual ~gridbase ()=default
double get_radius () const
double get_volume_element () const
template<std::size_t NDIM>
void visualize (const std::string filename, const std::vector< Vector< double, NDIM > > &grid) const
Public Attributes
GridBuilder builder
Additional Inherited Members
Protected Attributes inherited from madness::gridbase
bool do_print =false
double radius =3
double volume_element =0.1
Constructor & Destructor Documentation
dftgrid() [1/2]
template<std::size_t NDIM> madness::dftgrid< NDIM >::dftgrid (const double volume_element, const double radius) inline explicit
References madness::dftgrid< NDIM >::builder, GridBuilder::get_points(), GridBuilder::make_grid(), madness::print(), madness::gridbase::radius, GridBuilder::set_angular_order(), GridBuilder::set_nradial(), and madness::gridbase::volume_element.
dftgrid() [2/2]
template<std::size_t NDIM> madness::dftgrid< NDIM >::dftgrid (const std::size_t nradial, const std::size_t angular_order, const coord_3d origin = coord_3d()) inline explicit
References madness::dftgrid< NDIM >::builder, GridBuilder::make_grid(), NDIM, GridBuilder::set_angular_order(), GridBuilder::set_nradial(), and GridBuilder::set_origin().
Member Function Documentation
get_grid()
template<std::size_t NDIM> std::vector< Vector< double, NDIM > > madness::dftgrid< NDIM >::get_grid () const inline
References madness::dftgrid< NDIM >::builder, and GridBuilder::get_points().
Referenced by madness::molecular_grid< NDIM >::get_grid().
Member Data Documentation
builder
template<std::size_t NDIM> GridBuilder madness::dftgrid< NDIM >::builder
Referenced by madness::dftgrid< NDIM >::dftgrid(), madness::dftgrid< NDIM >::dftgrid(), and madness::dftgrid< NDIM >::get_grid().
The documentation for this class was generated from the following file:
lowrankfunction.h