MADNESS: madness::LBDeuxPmap< NDIM > Class Template Reference
madness::LBDeuxPmap< NDIM > Class Template Reference
#include <lbdeux.h>
Public Member Functions
LBDeuxPmap (const std::vector< pairT > &v)
ProcessID owner (const keyT &key) const
Maps key to processor.
void print () const
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< NDIM > >
virtual ~WorldDCPmapInterface ()
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
virtual DistributionType distribution_type () const
by default the map is distributed
std::size_t global_size (World &world) const
Counts global number of entries in all containers associated with this process map.
std::size_t local_size () const
Counts local number of entries in all containers associated with this process map.
void print_data_sizes (World &world, const std::string msg="") const
Prints size info to std::cout.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
Private Types
typedef mapT::const_iterator iteratorT
typedef Key< NDIM > keyT
typedef std::map< keyT, ProcessID > mapT
typedef std::pair< keyT, ProcessID > pairT
Private Attributes
mapT map
Additional Inherited Members
Public Types inherited from madness::WorldDCPmapInterface< Key< NDIM > >
typedef WorldDCRedistributeInterface< Key< NDIM > > * ptrT
Member Typedef Documentation
iteratorT
template<std::size_t NDIM> typedef mapT::const_iterator madness::LBDeuxPmap< NDIM >::iteratorT private
keyT
template<std::size_t NDIM> typedef Key<NDIM> madness::LBDeuxPmap< NDIM >::keyT private
mapT
template<std::size_t NDIM> typedef std::map<keyT,ProcessID> madness::LBDeuxPmap< NDIM >::mapT private
pairT
template<std::size_t NDIM> typedef std::pair<keyT,ProcessID> madness::LBDeuxPmap< NDIM >::pairT private
Constructor & Destructor Documentation
LBDeuxPmap()
template<std::size_t NDIM> madness::LBDeuxPmap< NDIM >::LBDeuxPmap (const std::vector< pairT > & v) inline
References madness::LBDeuxPmap< NDIM >::map, and v.
Member Function Documentation
owner()
template<std::size_t NDIM> ProcessID madness::LBDeuxPmap< NDIM >::owner (const keyT & key) const inline virtual
Maps key to processor.
Parameters
[in] key Key for container
Returns
Processor that logically owns the key
Implements madness::WorldDCPmapInterface< Key< NDIM > >.
References madness::Key< NDIM >::level(), madness::LBDeuxPmap< NDIM >::map, madness::LBDeuxPmap< NDIM >::owner(), madness::Key< NDIM >::parent(), and madness::print().
Referenced by madness::LBDeuxPmap< NDIM >::owner().
print()
template<std::size_t NDIM> void madness::LBDeuxPmap< NDIM >::print () const inline virtual
Reimplemented from madness::WorldDCPmapInterface< Key< NDIM > >.
References madness::print().
Member Data Documentation
map
template<std::size_t NDIM> mapT madness::LBDeuxPmap< NDIM >::map private
Referenced by madness::LBDeuxPmap< NDIM >::LBDeuxPmap(), and madness::LBDeuxPmap< NDIM >::owner().
The documentation for this class was generated from the following file:
lbdeux.h