MADNESS: madness::MacroTaskMp2UpdatePair Class Reference
madness::MacroTaskMp2UpdatePair Class Reference
#include <CCStructures.h>
Classes
class UpdatePairPartitioner
Public Types
typedef std::tuple< const std::vector< CCPair > &, const std::vector< real_function_6d > &, const std::vector< madness::Vector< double, 3 > > &, const Info & > argtupleT
using resultT = std::vector< real_function_6d >
Public Member Functions
MacroTaskMp2UpdatePair ()
resultT allocator (World &world, const argtupleT &argtuple) const
resultT operator() (const std::vector< CCPair > &pair, const std::vector< real_function_6d > &mp2_coupling, const std::vector< madness::Vector< double, 3 > > &all_coords_vec, const Info &info) const
Public Member Functions inherited from madness::MacroTaskOperationBase
MacroTaskOperationBase ()
Additional Inherited Members
Public Attributes inherited from madness::MacroTaskOperationBase
Batch batch
std::string name ="unknown_task"
std::shared_ptr< MacroTaskPartitioner > partitioner =0
Member Typedef Documentation
argtupleT
typedef std::tuple<const std::vector<CCPair>&, const std::vector<real_function_6d>&, const std::vector<madness::Vector<double,3> >&, const Info& > madness::MacroTaskMp2UpdatePair::argtupleT
resultT
using madness::MacroTaskMp2UpdatePair::resultT = std::vector<real_function_6d>
Constructor & Destructor Documentation
MacroTaskMp2UpdatePair()
madness::MacroTaskMp2UpdatePair::MacroTaskMp2UpdatePair () inline
References madness::MacroTaskOperationBase::name, and madness::MacroTaskOperationBase::partitioner.
Member Function Documentation
allocator()
resultT madness::MacroTaskMp2UpdatePair::allocator (World & world, const argtupleT & argtuple) const inline
References madness::nonlinear_vector_solver().
operator()()
std::vector< real_function_6d > madness::MacroTaskMp2UpdatePair::operator() (const std::vector< CCPair > & pair, const std::vector< real_function_6d > & mp2_coupling, const std::vector< madness::Vector< double, 3 > > & all_coords_vec, const Info & info) const
References madness::MacroTaskOperationBase::batch, madness::Info::mo_bra, madness::Info::mo_ket, madness::nonlinear_vector_solver(), madness::Info::parameters, madness::print(), madness::World::size(), madness::Info::U1, and madness::Info::U2.
The documentation for this class was generated from the following files:
CCStructures.h
CCStructures.cc