MADNESS: SafeMPI::Request Class Reference
SafeMPI::Request Class Reference
#include <safempi.h>
Public Member Functions
Request ()
Request (const Request &other)
Request (MPI_Request other)
operator MPI_Request () const
operator MPI_Request * ()
bool operator!= (const Request &other)
Request & operator= (const MPI_Request &other)
Request & operator= (const Request &other)
bool operator== (const Request &other)
bool Test ()
bool Test (MPI_Status &status)
bool Test_got_lock_already ()
bool Test_got_lock_already (MPI_Status &status)
Static Public Member Functions
static bool Testany (int count, Request *requests, int &index)
static bool Testany (int count, Request *requests, int &index, Status &status)
static int Testsome (int incount, Request *requests, int *indices)
static int Testsome (int incount, Request *requests, int *indices, Status *statuses)
Private Attributes
MPI_Request request_
Constructor & Destructor Documentation
Request() [1/3]
SafeMPI::Request::Request () inline
Request() [2/3]
SafeMPI::Request::Request (MPI_Request other) inline
Request() [3/3]
SafeMPI::Request::Request (const Request & other) inline
Member Function Documentation
operator MPI_Request()
SafeMPI::Request::operator MPI_Request () const inline
References request_.
operator MPI_Request *()
SafeMPI::Request::operator MPI_Request * () inline
References request_.
operator!=()
bool SafeMPI::Request::operator!= (const Request & other) inline
References request_.
operator=() [1/2]
Request & SafeMPI::Request::operator= (const MPI_Request & other) inline
References request_.
operator=() [2/2]
Request & SafeMPI::Request::operator= (const Request & other) inline
References request_.
operator==()
bool SafeMPI::Request::operator== (const Request & other) inline
References request_.
Test() [1/2]
bool SafeMPI::Request::Test () inline
References SAFE_MPI_GLOBAL_MUTEX, and Test_got_lock_already().
Test() [2/2]
bool SafeMPI::Request::Test (MPI_Status & status) inline
References SAFE_MPI_GLOBAL_MUTEX, status, and Test_got_lock_already().
Referenced by madness::World::MpiRequestTester::operator()(), and madness::WorldAmInterface::SendReq::TestAndFree().
Test_got_lock_already() [1/2]
bool SafeMPI::Request::Test_got_lock_already () inline
References MADNESS_MPI_TEST, MPI_STATUS_IGNORE, MPI_Test(), and request_.
Referenced by Test(), and Test().
Test_got_lock_already() [2/2]
bool SafeMPI::Request::Test_got_lock_already (MPI_Status & status) inline
References MADNESS_MPI_TEST, MPI_Test(), request_, and status.
Testany() [1/2]
static bool SafeMPI::Request::Testany (int count, Request * requests, int & index) inline static
References MADNESS_ASSERT, MADNESS_MPI_TEST, MPI_STATUS_IGNORE, MPI_Testany(), request_, and SAFE_MPI_GLOBAL_MUTEX.
Testany() [2/2]
static bool SafeMPI::Request::Testany (int count, Request * requests, int & index, Status & status) inline static
References MADNESS_ASSERT, MADNESS_MPI_TEST, MPI_Testany(), request_, SAFE_MPI_GLOBAL_MUTEX, and status.
Testsome() [1/2]
static int SafeMPI::Request::Testsome (int incount, Request * requests, int * indices) inline static
References MADNESS_MPI_TEST, MPI_STATUSES_IGNORE, MPI_Testsome(), request_, and SAFE_MPI_GLOBAL_MUTEX.
Testsome() [2/2]
static int SafeMPI::Request::Testsome (int incount, Request * requests, int * indices, Status * statuses) inline static
References MADNESS_ASSERT, MPI_SUCCESS, MPI_Testsome(), request_, and SAFE_MPI_GLOBAL_MUTEX.
Referenced by madness::RMI::RmiTask::process_some().
Member Data Documentation
request_
MPI_Request SafeMPI::Request::request_ private
Referenced by operator MPI_Request(), operator MPI_Request *(), operator!=(), operator=(), operator=(), operator==(), Test_got_lock_already(), Test_got_lock_already(), Testany(), Testany(), Testsome(), and Testsome().
The documentation for this class was generated from the following file:
safempi.h