MADNESS: madness::CCPair Class Reference
madness::CCPair Class Reference
#include <CCStructures.h>
Public Member Functions
CCPair ()=default
CCPair (const CCPair &other)
CCPair (const size_t ii, const size_t jj, const CCState t, const CalcType c)
CCPair (const size_t ii, const size_t jj, const CCState t, const CalcType c, const std::vector< CCPairFunction< double, 6 > > &f)
std::string basename () const
return the base name like "MP2_pair_u" or "CC2_pair_x"
void cloud_load (World &world, const Cloud &cloud, Recordlist< Cloud::keyT > &recordlist)
customized function to load this from the cloud
Recordlist< Cloud::keyT > cloud_store (World &world, Cloud &cloud) const
customized function to store this to the cloud
real_function_6d function () const
gives back the pure 6D part of the pair function
bool function_exists () const
check if the pair has a function assigned
hashT hash () const
void info () const
bool load_pair (World &world, const bool verbose=false)
std::string name () const
void reconstruct () const
reconstruct constant part and all functions
template<typename Archive >
void serialize (const Archive &ar)
void store_pair (World &world, const bool verbose=false)
void update_u (const real_function_6d &u)
updates the pure 6D part of the pair function
World & world () const
return the world of the function
Public Attributes
double bsh_eps =1.0
real_function_6d constant_part
the constant part
CalcType ctype
std::vector< CCPairFunction< double, 6 > > functions
the functions which belong to the pair
size_t i
size_t j
CCState type
Constructor & Destructor Documentation
CCPair() [1/4]
madness::CCPair::CCPair () default
CCPair() [2/4]
madness::CCPair::CCPair (const size_t ii, const size_t jj, const CCState t, const CalcType c) inline
CCPair() [3/4]
madness::CCPair::CCPair (const size_t ii, const size_t jj, const CCState t, const CalcType c, const std::vector< CCPairFunction< double, 6 > > & f) inline
CCPair() [4/4]
madness::CCPair::CCPair (const CCPair & other) inline
Member Function Documentation
basename()
std::string madness::CCPair::basename () const inline
return the base name like "MP2_pair_u" or "CC2_pair_x"
References madness::assign_name(), ctype, madness::EXCITED_STATE, madness::GROUND_STATE, name(), and type.
Referenced by name().
cloud_load()
void madness::CCPair::cloud_load (World & world, const Cloud & cloud, Recordlist< Cloud::keyT > & recordlist) inline
customized function to load this from the cloud
functions and constant_part can be very large and we want to split them and store them in different records
Parameters
[in,out] recordlist containing the keys of the member variables -> will be reduced by the keys which are used
References bsh_eps, madness::Function< T, NDIM >::clear(), constant_part, ctype, madness::Cloud::forward_load(), functions, i, j, type, v, and world().
cloud_store()
Recordlist< Cloud::keyT > madness::CCPair::cloud_store (World & world, Cloud & cloud) const inline
customized function to store this to the cloud
functions and constant_part can be very large and we want to split them and store them in different records NOTE only the 6d function and the constant part are stored in the cloud, not the 3d functions NOTE
References bsh_eps, constant_part, ctype, functions, i, madness::Function< T, NDIM >::is_initialized(), j, madness::Cloud::store(), type, v, and world().
function()
real_function_6d madness::CCPair::function () const inline
gives back the pure 6D part of the pair function
References functions, and MADNESS_CHECK_THROW.
Referenced by madness::CCPairBuilder::complete_pair_with_low_rank_parts(), madness::CC2::iterate_pair(), and world().
function_exists()
bool madness::CCPair::function_exists () const inline
check if the pair has a function assigned
References functions.
Referenced by world().
hash()
hashT madness::CCPair::hash () const inline
References constant_part, madness::Function< T, NDIM >::get_impl(), madness::hash_combine(), madness::hash_value(), i, madness::Function< T, NDIM >::is_initialized(), and j.
info()
void madness::CCPair::info () const
References constant_part, functions, k, name(), madness::Function< T, NDIM >::print_size(), madness::print_size(), madness::World::rank(), and madness::Function< T, NDIM >::world().
load_pair()
bool madness::CCPair::load_pair (World & world, const bool verbose = false) inline
References constant_part, madness::archive::BaseParallelArchive< Archive >::exists(), functions, madness::Function< T, NDIM >::is_initialized(), name(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::set_thresh(), and world().
name()
std::string madness::CCPair::name () const inline
References basename(), i, j, and madness::stringify().
Referenced by basename(), info(), madness::CC2::initialize_pairs(), madness::CC2::iterate_pair(), load_pair(), madness::CCPairBuilder::make_bare_pair_from_file(), store_pair(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
reconstruct()
void madness::CCPair::reconstruct () const inline
reconstruct constant part and all functions
References constant_part, madness::f, functions, and madness::Function< T, NDIM >::reconstruct().
Referenced by store_pair().
serialize()
template<typename Archive > void madness::CCPair::serialize (const Archive & ar) inline
References bsh_eps, constant_part, ctype, f1, madness::func(), functions, i, madness::Function< T, NDIM >::is_initialized(), j, and type.
store_pair()
void madness::CCPair::store_pair (World & world, const bool verbose = false) inline
References name(), madness::print(), madness::World::rank(), reconstruct(), and world().
update_u()
void madness::CCPair::update_u (const real_function_6d & u) inline
updates the pure 6D part of the pair function
References functions, MADNESS_CHECK_THROW, and u().
Referenced by madness::CC2::iterate_pair().
world()
World & madness::CCPair::world () const inline
return the world of the function
References function(), function_exists(), MADNESS_CHECK_THROW, and madness::Function< T, NDIM >::world().
Referenced by cloud_load(), cloud_store(), load_pair(), and store_pair().
Member Data Documentation
bsh_eps
double madness::CCPair::bsh_eps =1.0
Energy for the BSH Operator Ground State: e_i + e_j Excited State: e_i + e_j + omega default to positive value to make sure this is set somewhere
Referenced by cloud_load(), cloud_store(), madness::CC2::iterate_adc2_pairs(), madness::CC2::iterate_pair(), madness::CCPairBuilder::make_bare_pair(), serialize(), madness::CC2::solve_cispd(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
constant_part
real_function_6d madness::CCPair::constant_part
the constant part
Referenced by cloud_load(), cloud_store(), hash(), info(), madness::CC2::iterate_pair(), load_pair(), madness::CCPairBuilder::make_bare_pair_from_file(), reconstruct(), serialize(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
ctype
CalcType madness::CCPair::ctype
Referenced by basename(), cloud_load(), cloud_store(), madness::CCPairBuilder::complete_pair_with_low_rank_parts(), madness::CC2::iterate_pair(), serialize(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
functions
std::vector<CCPairFunction<double,6> > madness::CCPair::functions
the functions which belong to the pair
Referenced by cloud_load(), cloud_store(), madness::CCPairBuilder::complete_pair_with_low_rank_parts(), function(), function_exists(), info(), load_pair(), madness::CCPairBuilder::make_bare_pair_from_file(), madness::CCPairBuilder::make_pair(), reconstruct(), serialize(), madness::CC2::solve_cispd(), and update_u().
i
size_t madness::CCPair::i
Referenced by cloud_load(), cloud_store(), madness::CCPairBuilder::complete_pair_with_low_rank_parts(), hash(), madness::CC2::iterate_adc2_pairs(), name(), serialize(), madness::CC2::solve_cispd(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
j
size_t madness::CCPair::j
Referenced by cloud_load(), cloud_store(), madness::CCPairBuilder::complete_pair_with_low_rank_parts(), hash(), madness::CC2::iterate_adc2_pairs(), name(), serialize(), madness::CC2::solve_cispd(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
type
CCState madness::CCPair::type
Referenced by basename(), cloud_load(), cloud_store(), madness::CC2::iterate_pair(), serialize(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
The documentation for this class was generated from the following files:
CCStructures.h
CCStructures.cc