MADNESS: madness::archive::BufferInputArchive Class Reference
madness::archive::BufferInputArchive Class Reference
MADNESS libraries » Parallel programming environment » Serialization
Wraps an archive around a memory buffer for input.
#include <buffer_archive.h>
Public Member Functions
BufferInputArchive (const void *ptr, std::size_t nbyte)
Constructor that assigns a buffer.
void close ()
Close the archive.
template<class T >
std::enable_if< madness::is_trivially_serializable< T >::value, void >::type load (T *t, long n) const
Reads data from the memory buffer.
std::size_t nbyte_avail () const
Get the amount of space yet to be read from the buffer.
void open ()
Open the archive.
void rewind () const
Reset the read location to the beginning of the buffer.
Public Member Functions inherited from madness::archive::BaseArchive
BaseArchive ()
Private Attributes
std::size_t i
Current input location.
const std::size_t nbyte
Buffer size.
const unsigned char *const ptr
The memory buffer.
Additional Inherited Members
Public Types inherited from madness::archive::BaseInputArchive
using is_loading = std::true_type
Type used by Boost.Serialization to determine if this object is an input archive.
Public Types inherited from madness::archive::BaseArchive
using is_loading = std::false_type
Type used by Boost.Serialization to determine if this object is an input archive.
using is_saving = std::false_type
Type used by Boost.Serialization to determine if this object is an output archive.
Static Public Attributes inherited from madness::archive::BaseInputArchive
static constexpr bool is_input_archive = true
Flag to determine if this object is an input archive.
Static Public Attributes inherited from madness::archive::BaseArchive
static constexpr bool is_archive = true
Flag to determine if this object is an archive.
static constexpr bool is_input_archive = false
Flag to determine if this object is an input archive.
static constexpr bool is_output_archive = false
Flag to determine if this object is an output archive.
static constexpr bool is_parallel_archive = false
Flag to determine if this object is a parallel archive.
Detailed Description
Wraps an archive around a memory buffer for input.
Note
Type checking is disabled for efficiency.
Exceptions
madness::MadnessException in case of buffer overrun.
Constructor & Destructor Documentation
BufferInputArchive()
madness::archive::BufferInputArchive::BufferInputArchive (const void * ptr, std::size_t nbyte) inline
Constructor that assigns a buffer.
Parameters
[in] ptr Pointer to the buffer.
[in] nbyte Size of the buffer.
Member Function Documentation
close()
void madness::archive::BufferInputArchive::close () inline
Close the archive.
Referenced by main().
load()
template<class T > std::enable_if< madness::is_trivially_serializable< T >::value, void >::type madness::archive::BufferInputArchive::load (T * t, long n) const inline
Reads data from the memory buffer.
The function only appears (due to enable_if) if T is serializable.
Template Parameters
T Type of the data to be read.
Parameters
[out] t Where to store the read data.
[in] n Size of data to be read.
References i, m, MADNESS_ASSERT, nbyte, ptr, and T().
Referenced by test0().
nbyte_avail()
std::size_t madness::archive::BufferInputArchive::nbyte_avail () const inline
Get the amount of space yet to be read from the buffer.
Returns
The amount of space yet to be read from the buffer.
References i, and nbyte.
open()
void madness::archive::BufferInputArchive::open () inline
Open the archive.
rewind()
void madness::archive::BufferInputArchive::rewind () const inline
Reset the read location to the beginning of the buffer.
References i.
Member Data Documentation
i
std::size_t madness::archive::BufferInputArchive::i mutable private
Current input location.
Referenced by load(), nbyte_avail(), and rewind().
nbyte
const std::size_t madness::archive::BufferInputArchive::nbyte private
Buffer size.
Referenced by load(), and nbyte_avail().
ptr
const unsigned char* const madness::archive::BufferInputArchive::ptr private
The memory buffer.
Referenced by load().
The documentation for this class was generated from the following file:
buffer_archive.h