MADNESS: madness::WorldGopInterface::DelayedSend< keyT, valueT > Class Template Reference
madness::WorldGopInterface::DelayedSend< keyT, valueT > Class Template Reference
Delayed send callback object.
Public Member Functions
DelayedSend (World &world, const ProcessID dest, const keyT &key, const Future< valueT > &value)
Constructor.
virtual ~DelayedSend ()
virtual void notify ()
Notify this object that the future has been set.
Public Member Functions inherited from madness::CallbackInterface
virtual ~CallbackInterface ()
virtual void notify_debug (const char *caller)
Same as notify(), but tracks how many times called from each caller.
Private Member Functions
DelayedSend (const DelayedSend< keyT, valueT > &)
DelayedSend< keyT, valueT > & operator= (const DelayedSend< keyT, valueT > &)
Private Attributes
const ProcessID dest_
The destination process id.
const keyT key_
The distributed id associated with value_.
Future< valueT > value_
The data to be sent.
World & world_
The communication world.
Additional Inherited Members
Protected Member Functions inherited from madness::CallbackInterface
virtual void notify_debug_impl (const char *caller)
Detailed Description
template<typename keyT, typename valueT>
class madness::WorldGopInterface::DelayedSend< keyT, valueT >
Delayed send callback object.
This callback object is used to send local data to a remove process once it has been set.
Template Parameters
keyT The data key
valueT The type of data to be sent
Constructor & Destructor Documentation
DelayedSend() [1/2]
template<typename keyT , typename valueT > madness::WorldGopInterface::DelayedSend< keyT, valueT >::DelayedSend (const DelayedSend< keyT, valueT > &) private
DelayedSend() [2/2]
template<typename keyT , typename valueT > madness::WorldGopInterface::DelayedSend< keyT, valueT >::DelayedSend (World & world, const ProcessID dest, const keyT & key, const Future< valueT > & value) inline
Constructor.
~DelayedSend()
template<typename keyT , typename valueT > virtual madness::WorldGopInterface::DelayedSend< keyT, valueT >::~DelayedSend () inline virtual
Member Function Documentation
notify()
template<typename keyT , typename valueT > virtual void madness::WorldGopInterface::DelayedSend< keyT, valueT >::notify () inline virtual
Notify this object that the future has been set.
This will set the value of the future on the remote node and delete this callback object.
Implements madness::CallbackInterface.
References madness::WorldGopInterface::DelayedSend< keyT, valueT >::dest_, madness::Future< T >::get(), madness::World::gop, madness::WorldGopInterface::DelayedSend< keyT, valueT >::key_, MADNESS_ASSERT, madness::Future< T >::probe(), madness::WorldGopInterface::send_internal(), madness::WorldGopInterface::DelayedSend< keyT, valueT >::value_, and madness::WorldGopInterface::DelayedSend< keyT, valueT >::world_.
operator=()
template<typename keyT , typename valueT > DelayedSend< keyT, valueT > & madness::WorldGopInterface::DelayedSend< keyT, valueT >::operator= (const DelayedSend< keyT, valueT > &) private
Member Data Documentation
dest_
template<typename keyT , typename valueT > const ProcessID madness::WorldGopInterface::DelayedSend< keyT, valueT >::dest_ private
The destination process id.
Referenced by madness::WorldGopInterface::DelayedSend< keyT, valueT >::notify().
key_
template<typename keyT , typename valueT > const keyT madness::WorldGopInterface::DelayedSend< keyT, valueT >::key_ private
The distributed id associated with value_.
Referenced by madness::WorldGopInterface::DelayedSend< keyT, valueT >::notify().
value_
template<typename keyT , typename valueT > Future<valueT> madness::WorldGopInterface::DelayedSend< keyT, valueT >::value_ private
The data to be sent.
Referenced by madness::WorldGopInterface::DelayedSend< keyT, valueT >::notify().
world_
template<typename keyT , typename valueT > World& madness::WorldGopInterface::DelayedSend< keyT, valueT >::world_ private
The communication world.
Referenced by madness::WorldGopInterface::DelayedSend< keyT, valueT >::notify().
The documentation for this class was generated from the following file:
worldgop.h