MADNESS: madness::MyPmap< D > Class Template Reference
madness::MyPmap< D > Class Template Reference
Procmap implemented using Tree of TreeCoords.
#include <mypmap.h>
Public Member Functions
MyPmap ()
MyPmap (const MyPmap< D > &other)
MyPmap (World &world)
MyPmap (World &world, std::vector< TreeCoords< D > > v)
MyPmap (World &world, unsigned int map_type, int n=100)
MyPmap< D > & operator= (const MyPmap< D > &other)
ProcessID owner (const KeyD &key) const
Find the owner of a given key.
void print () const
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< D > >
virtual ~WorldDCPmapInterface ()
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
virtual DistributionType distribution_type () const
by default the map is distributed
std::size_t global_size (World &world) const
Counts global number of entries in all containers associated with this process map.
std::size_t local_size () const
Counts local number of entries in all containers associated with this process map.
void print_data_sizes (World &world, const std::string msg="") const
Prints size info to std::cout.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< D > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
Static Public Member Functions
static bool costmapcmp (const std::pair< KeyD, double > &a, const std::pair< KeyD, double > &b)
Private Types
typedef Key< D > KeyD
Private Member Functions
void build_tree_map (std::vector< TreeCoords< D > > v)
private method that builds the Tree underlying the procmap
ProcessID not_so_simple_hash (const KeyD &key) const
void prepare_not_so_simple_map (World &world)
ProcessID simple_hash (const KeyD &key) const
Private Attributes
unsigned int map_type
const int n
const int nproc
Tensor< ProcessID > simple_key_map
std::shared_ptr< ProcMapImpl< D > > tree_map
Additional Inherited Members
Public Types inherited from madness::WorldDCPmapInterface< Key< D > >
typedef WorldDCRedistributeInterface< Key< D > > * ptrT
Detailed Description
template<int D>
class madness::MyPmap< D >
Procmap implemented using Tree of TreeCoords.
Member Typedef Documentation
KeyD
template<int D> typedef Key<D> madness::MyPmap< D >::KeyD private
Constructor & Destructor Documentation
MyPmap() [1/5]
template<int D> madness::MyPmap< D >::MyPmap () inline
MyPmap() [2/5]
template<int D> madness::MyPmap< D >::MyPmap (World & world) inline
MyPmap() [3/5]
template<int D> madness::MyPmap< D >::MyPmap (World & world, unsigned int map_type, int n = 100) inline
References madness::World::size().
MyPmap() [4/5]
template<int D> madness::MyPmap< D >::MyPmap (World & world, std::vector< TreeCoords< D > > v) inline
References v.
MyPmap() [5/5]
template<int D> madness::MyPmap< D >::MyPmap (const MyPmap< D > & other) inline
Member Function Documentation
build_tree_map()
template<int D> void madness::MyPmap< D >::build_tree_map (std::vector< TreeCoords< D > > v) inline private
private method that builds the Tree underlying the procmap
References v.
costmapcmp()
template<int D> static bool madness::MyPmap< D >::costmapcmp (const std::pair< KeyD, double > & a, const std::pair< KeyD, double > & b) inline static
References a, and b.
not_so_simple_hash()
template<int D> ProcessID madness::MyPmap< D >::not_so_simple_hash (const KeyD & key) const inline private
References madness::Key< NDIM >::level(), madness::Key< NDIM >::parent(), and madness::Key< NDIM >::translation().
operator=()
template<int D> MyPmap< D > & madness::MyPmap< D >::operator= (const MyPmap< D > & other) inline
References madness::MyPmap< D >::map_type, madness::MyPmap< D >::n, madness::MyPmap< D >::nproc, madness::MyPmap< D >::simple_key_map, and madness::MyPmap< D >::tree_map.
owner()
template<int D> ProcessID madness::MyPmap< D >::owner (const KeyD & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< D > >.
prepare_not_so_simple_map()
template<int D> void madness::MyPmap< D >::prepare_not_so_simple_map (World & world) inline private
References dist(), p(), madness::World::size(), and madness::Tensor< T >::unary_iterator().
print()
template<int D> void madness::MyPmap< D >::print () const inline virtual
Reimplemented from madness::WorldDCPmapInterface< Key< D > >.
References madness::print().
simple_hash()
template<int D> ProcessID madness::MyPmap< D >::simple_hash (const KeyD & key) const inline private
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
Member Data Documentation
map_type
template<int D> unsigned int madness::MyPmap< D >::map_type private
Referenced by madness::MyPmap< D >::operator=().
n
template<int D> const int madness::MyPmap< D >::n private
Referenced by madness::MyPmap< D >::operator=().
nproc
template<int D> const int madness::MyPmap< D >::nproc private
Referenced by madness::MyPmap< D >::operator=().
simple_key_map
template<int D> Tensor<ProcessID> madness::MyPmap< D >::simple_key_map private
Referenced by madness::MyPmap< D >::operator=().
tree_map
template<int D> std::shared_ptr< ProcMapImpl<D> > madness::MyPmap< D >::tree_map private
Referenced by madness::MyPmap< D >::operator=().
The documentation for this class was generated from the following file:
mypmap.h