MADNESS: madness::LoadBalanceDeux< NDIM > Class Template Reference
madness::LoadBalanceDeux< NDIM > Class Template Reference
#include <lbdeux.h>
Classes
struct add_op
struct CostPerProc
Public Member Functions
LoadBalanceDeux (World &world)
template<typename T , typename costT >
void add_tree (const Function< T, NDIM > &f, const costT &costfn, bool fence=false)
Accumulates cost from a function.
std::shared_ptr< WorldDCPmapInterface< keyT > > load_balance (double fac=1.0, bool printstuff=false)
Actually does the partitioning of the tree.
void print_tree (const keyT &key=keyT(0))
Printing for the curious.
Private Types
typedef treeT::const_iterator const_iteratorT
typedef treeT::iterator iteratorT
typedef Key< NDIM > keyT
typedef LBNodeDeux< NDIM > nodeT
typedef WorldContainer< keyT, nodeT > treeT
Private Member Functions
double sum ()
Sums costs up the tree returning to everyone the total cost.
Static Private Member Functions
static bool compare (const std::pair< keyT, double > &a, const std::pair< keyT, double > &b)
Used to sort results into descending order.
Private Attributes
treeT tree
World & world
Member Typedef Documentation
const_iteratorT
template<std::size_t NDIM> typedef treeT::const_iterator madness::LoadBalanceDeux< NDIM >::const_iteratorT private
iteratorT
template<std::size_t NDIM> typedef treeT::iterator madness::LoadBalanceDeux< NDIM >::iteratorT private
keyT
template<std::size_t NDIM> typedef Key<NDIM> madness::LoadBalanceDeux< NDIM >::keyT private
nodeT
template<std::size_t NDIM> typedef LBNodeDeux<NDIM> madness::LoadBalanceDeux< NDIM >::nodeT private
treeT
template<std::size_t NDIM> typedef WorldContainer<keyT,nodeT> madness::LoadBalanceDeux< NDIM >::treeT private
Constructor & Destructor Documentation
LoadBalanceDeux()
template<std::size_t NDIM> madness::LoadBalanceDeux< NDIM >::LoadBalanceDeux (World & world) inline
References madness::WorldGopInterface::fence(), madness::World::gop, and madness::LoadBalanceDeux< NDIM >::world.
Member Function Documentation
add_tree()
template<std::size_t NDIM> template<typename T , typename costT > void madness::LoadBalanceDeux< NDIM >::add_tree (const Function< T, NDIM > & f, const costT & costfn, bool fence = false) inline
Accumulates cost from a function.
References madness::f.
Referenced by DF::DF_load_balance(), doit(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), initial_loadbal(), iterate(), madness::load_balance(), EmbeddedDirichlet::load_balance(), load_balance(), madness::load_balance(), madness::SCF::loadbal(), loadbal(), loadbal(), loadbal(), main(), madness::SCF::make_fock_matrix(), preloadbal(), run(), test(), and trotter().
compare()
template<std::size_t NDIM> static bool madness::LoadBalanceDeux< NDIM >::compare (const std::pair< keyT, double > & a, const std::pair< keyT, double > & b) inline static private
Used to sort results into descending order.
References a, and b.
Referenced by madness::LoadBalanceDeux< NDIM >::load_balance().
load_balance()
template<std::size_t NDIM> std::shared_ptr< WorldDCPmapInterface< keyT > > madness::LoadBalanceDeux< NDIM >::load_balance (double fac = 1.0, bool printstuff = false) inline
Actually does the partitioning of the tree.
References madness::WorldContainer< keyT, valueT, hashfunT >::begin(), madness::WorldGopInterface::broadcast_serializable(), madness::LoadBalanceDeux< NDIM >::compare(), madness::WorldGopInterface::concat0(), madness::LoadBalanceDeux< NDIM >::CostPerProc::cost, madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, madness::WorldContainer< keyT, valueT, hashfunT >::owner(), p(), madness::print(), madness::LoadBalanceDeux< NDIM >::CostPerProc::proc, madness::World::rank(), madness::WorldContainer< keyT, valueT, hashfunT >::send(), madness::World::size(), madness::LoadBalanceDeux< NDIM >::sum(), madness::LoadBalanceDeux< NDIM >::tree, and madness::LoadBalanceDeux< NDIM >::world.
Referenced by DF::DF_load_balance(), doit(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), initial_loadbal(), iterate(), madness::load_balance(), EmbeddedDirichlet::load_balance(), load_balance(), madness::load_balance(), madness::SCF::loadbal(), loadbal(), loadbal(), loadbal(), main(), madness::SCF::make_fock_matrix(), preloadbal(), run(), test(), and trotter().
print_tree()
template<std::size_t NDIM> void madness::LoadBalanceDeux< NDIM >::print_tree (const keyT & key = keyT(0)) inline
Printing for the curious.
References madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::Future< T >::get(), madness::print(), madness::LoadBalanceDeux< NDIM >::print_tree(), and madness::LoadBalanceDeux< NDIM >::tree.
Referenced by madness::LoadBalanceDeux< NDIM >::print_tree().
sum()
template<std::size_t NDIM> double madness::LoadBalanceDeux< NDIM >::sum () inline private
Sums costs up the tree returning to everyone the total cost.
References madness::WorldContainer< keyT, valueT, hashfunT >::begin(), madness::WorldGopInterface::broadcast(), madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldGopInterface::fence(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::World::gop, madness::WorldContainer< keyT, valueT, hashfunT >::owner(), madness::World::rank(), madness::WorldContainer< keyT, valueT, hashfunT >::task(), madness::LoadBalanceDeux< NDIM >::tree, and madness::LoadBalanceDeux< NDIM >::world.
Referenced by madness::LoadBalanceDeux< NDIM >::load_balance().
Member Data Documentation
tree
template<std::size_t NDIM> treeT madness::LoadBalanceDeux< NDIM >::tree private
Referenced by madness::LoadBalanceDeux< NDIM >::load_balance(), madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::operator()(), madness::LoadBalanceDeux< NDIM >::print_tree(), and madness::LoadBalanceDeux< NDIM >::sum().
world
template<std::size_t NDIM> World& madness::LoadBalanceDeux< NDIM >::world private
Referenced by madness::LoadBalanceDeux< NDIM >::LoadBalanceDeux(), madness::LoadBalanceDeux< NDIM >::load_balance(), and madness::LoadBalanceDeux< NDIM >::sum().
The documentation for this class was generated from the following file:
lbdeux.h