MADNESS: madness::Molecule Class Reference
madness::Molecule Class Reference
#include <molecule.h>
Classes
struct apply_c2
struct apply_inverse
struct apply_sigma
struct GeometryParameters
Public Member Functions
Molecule ()
Makes a molecule with zero atoms.
Molecule (std::vector< Atom > atoms, double eprec, CorePotentialManager core_pot={}, madness::Tensor< double > field=madness::Tensor< double >(3L))
makes a molecule from a list of atoms
Molecule (World &world, const commandlineparser &parser)
makes a molecule using contents of parser
void add_atom (double x, double y, double z, double q, int atn)
void add_atom (double x, double y, double z, double q, int atn, bool psat)
double atomic_attraction_potential (int iatom, double x, double y, double z) const
nuclear attraction potential for a specific atom in the molecule
double bounding_cube () const
Returns the half width of the bounding cube.
void center ()
Moves the center of nuclear charge to the origin.
Tensor< double > center_of_mass () const
compute the center of mass
double core_derivative (int atom, int axis, unsigned int core, int m, double x, double y, double z) const
double core_eval (int atom, unsigned int core, int m, double x, double y, double z) const
double core_potential_derivative (int atom, int axis, double x, double y, double z) const
std::vector< std::string > cubefile_header (const Vector< double, 3 > offset=Vector< double, 3 >(0.0)) const
print out a Gaussian cubefile header
void fix_phase ()
rotates the molecule and the external field
void from_json (const json &mol_json)
madness::Tensor< double > get_all_coords () const
std::vector< madness::Vector< double, 3 > > get_all_coords_vec () const
const Atom & get_atom (unsigned int i) const
unsigned int get_atom_charge (unsigned int i) const
unsigned int get_atomic_number (unsigned int i) const
const std::vector< Atom > & get_atoms () const
double get_core_bc (unsigned int atn, unsigned int c) const
unsigned int get_core_l (unsigned int atn, unsigned int c) const
double get_eprec () const
std::string get_pointgroup () const
bool get_pseudo_atom (unsigned int i) const
std::vector< double > get_rcut () const
void get_structure ()
std::string guess_file () const
hashT hash () const
void insert_symbols_and_geometry (json &mol_json) const
double inter_atomic_distance (unsigned int i, unsigned int j) const
bool is_potential_defined (unsigned int atn) const
bool is_potential_defined_atom (int i) const
Tensor< double > massweights () const
compute the mass-weighting matrix for the hessian
double molecular_core_potential (double x, double y, double z) const
Tensor< double > moment_of_inertia () const
unsigned int n_core_orb (unsigned int atn) const
unsigned int n_core_orb_all () const
size_t natom () const
double nuclear_attraction_potential (double x, double y, double z) const
nuclear attraction potential for the whole molecule
double nuclear_attraction_potential_derivative (int atom, int axis, double x, double y, double z) const
double nuclear_attraction_potential_second_derivative (int atom, int iaxis, int jaxis, double x, double y, double z) const
the second derivative of the (smoothed) nuclear potential Z/r
double nuclear_charge_density (double x, double y, double z, double rscale=1.) const
double nuclear_dipole (int axis) const
compute the dipole moment of the nuclei
Tensor< double > nuclear_dipole_derivative (const int atom, const int axis) const
compute the derivative of the nuclear dipole wrt a nuclear displacement
double nuclear_repulsion_derivative (size_t iatom, int axis) const
double nuclear_repulsion_energy () const
Tensor< double > nuclear_repulsion_hessian () const
return the hessian matrix of the second derivatives d^2/dxdy V
double nuclear_repulsion_second_derivative (int iatom, int jatom, int iaxis, int jaxis) const
compute the nuclear-nuclear contribution to the second derivatives
bool operator== (const Molecule &other) const
void orient (bool verbose=false)
Centers and orients the molecule in a standard manner.
void print (std::ostream &os=std::cout, const bool defined_only=false) const
print all parameters and the molecular geometry
void print_defined_only (std::ostream &os=std::cout) const
print user-defined parameters and the molecular geometry
void read (std::istream &f)
void read_core_file (const std::string &filename)
void read_file (const std::string &filename)
void read_structure_from_library (const std::string &name)
void read_xyz (const std::string filename)
void rotate (const Tensor< double > &D)
template<typename Archive >
void serialize (Archive &ar)
void set_all_coords (const madness::Tensor< double > &newcoords)
void set_atom_charge (unsigned int i, double zeff)
void set_atom_coords (unsigned int i, double x, double y, double z)
void set_core_eprec (double value)
void set_core_rcut (double value)
void set_pseudo_atom (unsigned int i, bool psat)
void set_rcut (double value)
double smallest_length_scale () const
std::string symmetrize_and_identify_point_group (const double symtol)
json to_json () const
json to_json_if_precedence (std::string const &precedence) const
double total_nuclear_charge () const
void translate (const Tensor< double > &translation)
translate the molecule
void update_rcut_with_eprec (double value)
updates rcuts with given eprec
Static Public Member Functions
static std::string get_structure_library_path ()
static std::istream & position_stream_in_library (std::ifstream &f, const std::string &name)
static void print_parameters ()
Public Attributes
std::vector< double > atomic_radii
GeometryParameters parameters
Static Public Attributes
static constexpr char const * tag = "molecule"
Private Member Functions
template<typename opT >
int find_symmetry_equivalent_atom (int iatom, opT op, const double symtol) const
void swapaxes (int ix, int iy)
template<typename opT >
void symmetrize_for_op (opT op, const double symtol)
bool test_for_c2 (double xaxis, double yaxis, double zaxis, const double symtol) const
bool test_for_inverse (const double symtol) const
template<typename opT >
bool test_for_op (opT op, const double symtol) const
bool test_for_sigma (double xaxis, double yaxis, double zaxis, const double symtol) const
Private Attributes
std::vector< Atom > atoms
CorePotentialManager core_pot
madness::Tensor< double > field
std::string pointgroup_ = "c1"
std::vector< double > rcut
Constructor & Destructor Documentation
Molecule() [1/3]
madness::Molecule::Molecule () inline
Makes a molecule with zero atoms.
Molecule() [2/3]
madness::Molecule::Molecule (std::vector< Atom > atoms, double eprec, CorePotentialManager core_pot = {}, madness::Tensor< double > field = madness::Tensor<double>(3L))
makes a molecule from a list of atoms
References atomic_radii, madness::constants::atomic_unit_of_length, atoms, madness::AtomicData::covalent_radius, e(), madness::get_atomic_data(), and update_rcut_with_eprec().
Molecule() [3/3]
madness::Molecule::Molecule (World & world, const commandlineparser & parser)
makes a molecule using contents of parser
References madness::WorldGopInterface::broadcast_serializable(), madness::Molecule::GeometryParameters::core_type(), madness::Molecule::GeometryParameters::field(), field, get_structure(), madness::World::gop, MADNESS_CHECK, parameters, madness::QCCalculationParametersBase::print(), madness::World::rank(), and read_core_file().
Member Function Documentation
add_atom() [1/2]
void madness::Molecule::add_atom (double x, double y, double z, double q, int atn)
References atomic_radii, madness::constants::atomic_unit_of_length, atoms, c, madness::AtomicData::covalent_radius, e(), madness::get_atomic_data(), get_eprec(), q(), rcut, and madness::smoothing_parameter().
Referenced by from_json(), main(), read(), read_xyz(), and madness::InitParameters::readnw().
add_atom() [2/2]
void madness::Molecule::add_atom (double x, double y, double z, double q, int atn, bool psat)
References atomic_radii, madness::constants::atomic_unit_of_length, atoms, c, madness::AtomicData::covalent_radius, e(), madness::get_atomic_data(), get_eprec(), q(), rcut, and madness::smoothing_parameter().
atomic_attraction_potential()
double madness::Molecule::atomic_attraction_potential (int iatom, double x, double y, double z) const
nuclear attraction potential for a specific atom in the molecule
References atoms, madness::distance(), rcut, madness::smoothed_potential(), and sum.
Referenced by madness::NuclearCorrelationFactor::square_times_V_functor::operator()(), and madness::atomic_attraction::operator()().
bounding_cube()
double madness::Molecule::bounding_cube () const
Returns the half width of the bounding cube.
The molecule will be contained in the cube [-L,+L].
References atoms, and L.
center()
void madness::Molecule::center ()
Moves the center of nuclear charge to the origin.
References atoms, and translate().
Referenced by orient().
center_of_mass()
Tensor< double > madness::Molecule::center_of_mass () const
compute the center of mass
References get_atom(), madness::Atom::mass, natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by projector_external_dof(), and madness::MolecularOptimizer::projector_external_dof().
core_derivative()
double madness::Molecule::core_derivative (int atom, int axis, unsigned int core, int m, double x, double y, double z) const
References atoms, axis, madness::CorePotentialManager::core_derivative(), core_pot, m, and xi.
Referenced by madness::CoreOrbitalDerivativeFunctor::operator()().
core_eval()
double madness::Molecule::core_eval (int atom, unsigned int core, int m, double x, double y, double z) const
References atoms, madness::CorePotentialManager::core_eval(), core_pot, and m.
Referenced by madness::CoreOrbitalFunctor::operator()().
core_potential_derivative()
double madness::Molecule::core_potential_derivative (int atom, int axis, double x, double y, double z) const
References atoms, axis, core_pot, madness::distance(), natom(), madness::CorePotentialManager::potential_derivative(), and xi.
Referenced by madchem::CorePotentialDerivativeFunctor::operator()().
cubefile_header()
std::vector< std::string > madness::Molecule::cubefile_header (const Vector< double, 3 > offset = Vector<double, 3>(0.0)) const
print out a Gaussian cubefile header
Parameters
[in] offset the offset to be subtracted from the coordinates
References get_atom(), madness::Atom::get_atomic_number(), madness::Atom::get_coords(), natom(), and offset.
Referenced by madness::cubefile_header(), and main().
find_symmetry_equivalent_atom()
template<typename opT > int madness::Molecule::find_symmetry_equivalent_atom (int iatom, opT op, const double symtol) const private
References atoms, madness::distance(), and op().
Referenced by symmetrize_for_op(), and test_for_op().
fix_phase()
void madness::Molecule::fix_phase ()
rotates the molecule and the external field
References atoms, and e().
Referenced by orient().
from_json()
void madness::Molecule::from_json (const json & mol_json)
References add_atom(), madness::constants::atomic_unit_of_length, atoms, e(), madness::QCCalculationParametersBase::from_json(), madness::Molecule::GeometryParameters::no_orient(), orient(), parameters, q(), rcut, madness::scale(), madness::symbol_to_atomic_number(), and madness::Molecule::GeometryParameters::units().
get_all_coords()
madness::Tensor< double > madness::Molecule::get_all_coords () const
References c, get_atom(), natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by madness::Znemo::gradient(), main(), madness::MolecularEnergy::output_calc_info_schema(), run_all_calculations(), test_read_restartaodata(), test_read_restartdata(), madness::Znemo::value(), and madness::Znemo::value().
get_all_coords_vec()
std::vector< madness::Vector< double, 3 > > madness::Molecule::get_all_coords_vec () const
References c, get_atom(), natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by madness::Znemo::recompute_factors_and_potentials(), MolecularPotentialFunctor::special_points(), madchem::MolecularGuessDensityFunctor::special_points(), madness::atomic_attraction::special_points(), madness::MolecularPotentialFunctor::special_points(), madness::MolecularCorePotentialFunctor::special_points(), and madness::WignerSeitzPotentialFunctor::special_points().
get_atom()
const Atom & madness::Molecule::get_atom (unsigned int i) const
References atoms.
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), center_of_mass(), madness::PotentialManager::core_projection(), madness::PotentialManager::core_projector_derivative(), cubefile_header(), madness::SCF::derivatives(), get_all_coords(), get_all_coords_vec(), madness::Znemo::gradient(), madness::BasisFunctions::guess_virtuals_internal(), madness::SCF::initial_guess_from_nwchem(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), DF::make_fermi_potential(), DF::make_gaussian_potential(), madness::GTHPseudopotential< Q >::make_pseudo_potential(), massweights(), madness::WignerSeitzPotentialFunctor::operator()(), madchem::AtomicAttractionFunctor::operator()(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), madchem::AtomicAttractionFunctor::special_points(), madchem::MolecularDerivativeFunctor::special_points(), madchem::MolecularSecondDerivativeFunctor::special_points(), and test_ethylene().
get_atom_charge()
unsigned int madness::Molecule::get_atom_charge (unsigned int i) const
References atoms.
Referenced by madness::SCF::initial_guess().
get_atomic_number()
unsigned int madness::Molecule::get_atomic_number (unsigned int i) const
References atoms.
Referenced by get_structure(), madness::SCF::initial_guess(), and madness::Localizer::localize_new().
get_atoms()
const std::vector< Atom > & madness::Molecule::get_atoms () const inline
References atoms.
Referenced by madness::Znemo::custom_guess(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::make_atom_vec(), DF::make_fermi_potential(), madness::GaussianNuclearDensityFunctor::operator()(), madness::BasisFunctions::predefined_guess(), and DF::print_molecule().
get_core_bc()
double madness::Molecule::get_core_bc (unsigned int atn, unsigned int c) const inline
References c, core_pot, and madness::CorePotentialManager::get_core_bc().
Referenced by madness::PotentialManager::core_projection(), and madness::PotentialManager::core_projector_derivative().
get_core_l()
unsigned int madness::Molecule::get_core_l (unsigned int atn, unsigned int c) const inline
References c, core_pot, and madness::CorePotentialManager::get_core_l().
Referenced by madness::PotentialManager::core_projection(), and madness::PotentialManager::core_projector_derivative().
get_eprec()
double madness::Molecule::get_eprec () const inline
References madness::Molecule::GeometryParameters::eprec(), and parameters.
Referenced by madness::GaussSlater::GaussSlater(), madness::GradientalGaussSlater::GradientalGaussSlater(), madness::LinearSlater::LinearSlater(), madness::poly4erfc::poly4erfc(), madness::Polynomial< N >::Polynomial(), madness::PseudoNuclearCorrelationFactor::PseudoNuclearCorrelationFactor(), madness::Slater::Slater(), add_atom(), add_atom(), read_core_file(), madness::NuclearCorrelationFactor::smoothed_unitvec(), and update_rcut_with_eprec().
get_pointgroup()
std::string madness::Molecule::get_pointgroup () const inline
References pointgroup_.
get_pseudo_atom()
bool madness::Molecule::get_pseudo_atom (unsigned int i) const
References atoms.
Referenced by get_structure(), and madness::SCF::initial_guess().
get_rcut()
std::vector< double > madness::Molecule::get_rcut () const inline
References rcut.
Referenced by madness::WignerSeitzPotentialFunctor::operator()(), and madchem::AtomicAttractionFunctor::operator()().
get_structure()
void madness::Molecule::get_structure ()
References madness::Molecule::GeometryParameters::core_type(), madness::QCCalculationParametersBase::get(), get_atomic_number(), madness::get_charge_from_file(), get_pseudo_atom(), MADNESS_EXCEPTION, natom(), madness::Molecule::GeometryParameters::no_orient(), orient(), parameters, read(), read_core_file(), read_structure_from_library(), read_xyz(), set_atom_charge(), set_pseudo_atom(), madness::Molecule::GeometryParameters::source_name(), and madness::Molecule::GeometryParameters::source_type().
Referenced by Molecule().
get_structure_library_path()
std::string madness::Molecule::get_structure_library_path () static
Referenced by position_stream_in_library(), and madness::Molecule::GeometryParameters::set_derived_values().
guess_file()
std::string madness::Molecule::guess_file () const inline
References core_pot, and madness::CorePotentialManager::guess_file().
hash()
hashT madness::Molecule::hash () const inline
References atoms, h(), madness::hash_combine(), madness::hash_range(), pointgroup_, and rcut.
insert_symbols_and_geometry()
void madness::Molecule::insert_symbols_and_geometry (json & mol_json) const
References atoms, madness::get_atomic_data(), natom(), and madness::AtomicData::symbol.
Referenced by to_json(), and to_json_if_precedence().
inter_atomic_distance()
double madness::Molecule::inter_atomic_distance (unsigned int i, unsigned int j) const
References atoms, and madness::distance().
Referenced by nuclear_repulsion_derivative(), nuclear_repulsion_energy(), and nuclear_repulsion_second_derivative().
is_potential_defined()
bool madness::Molecule::is_potential_defined (unsigned int atn) const inline
References core_pot, and madness::CorePotentialManager::is_defined().
is_potential_defined_atom()
bool madness::Molecule::is_potential_defined_atom (int i) const inline
References atoms, core_pot, and madness::CorePotentialManager::is_defined().
Referenced by madness::SCF::derivatives().
massweights()
Tensor< double > madness::Molecule::massweights () const inline
compute the mass-weighting matrix for the hessian
use as mass_weighted_hessian=inner(massweights,inner(hessian,massweights));
References get_atom(), and natom().
Referenced by compute_frequencies(), madness::Nemo::compute_IR_intensities(), and compute_reduced_mass().
molecular_core_potential()
double madness::Molecule::molecular_core_potential (double x, double y, double z) const
References atoms, core_pot, madness::distance(), madness::CorePotentialManager::is_defined(), natom(), madness::CorePotentialManager::potential(), and sum.
Referenced by madness::MolecularCorePotentialFunctor::operator()().
moment_of_inertia()
Tensor< double > madness::Molecule::moment_of_inertia () const
References atoms, I, k, and q().
Referenced by projector_external_dof(), and madness::MolecularOptimizer::projector_external_dof().
n_core_orb()
unsigned int madness::Molecule::n_core_orb (unsigned int atn) const inline
References core_pot, madness::CorePotentialManager::is_defined(), and madness::CorePotentialManager::n_core_orb_base().
Referenced by madness::PotentialManager::core_projection(), and madness::PotentialManager::core_projector_derivative().
n_core_orb_all()
unsigned int madness::Molecule::n_core_orb_all () const
References atoms, core_pot, madness::CorePotentialManager::is_defined(), madness::CorePotentialManager::n_core_orb(), natom(), and sum.
Referenced by madness::SCF::initial_guess().
natom()
size_t madness::Molecule::natom () const inline
References atoms.
Referenced by NuclearVector::NuclearVector(), center_of_mass(), madness::Nemo::compute_all_cphf(), compute_frequencies(), madness::NemoBase::compute_gradient(), madness::Nemo::compute_IR_intensities(), compute_reduced_mass(), core_potential_derivative(), madness::PotentialManager::core_projection(), cubefile_header(), madness::SCF::derivatives(), get_all_coords(), get_all_coords_vec(), get_structure(), madness::Znemo::gradient(), madness::BasisFunctions::guess_virtuals_internal(), madness::Nemo::hessian(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), insert_symbols_and_geometry(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), madness::Localizer::localize_new(), DF::make_fermi_potential(), DF::make_gaussian_potential(), madness::Nemo::make_incomplete_hessian(), madness::Nemo::make_incomplete_hessian_response_part(), madness::GTHPseudopotential< Q >::make_pseudo_potential(), massweights(), molecular_core_potential(), n_core_orb_all(), nuclear_repulsion_hessian(), madness::WignerSeitzPotentialFunctor::operator()(), madness::MolecularEnergy::output_calc_info_schema(), madness::SCF::output_calc_info_schema(), print(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), read_core_file(), read_xyz(), set_all_coords(), madness::ResponseParameters::set_derived_values(), madness::SCF::solve(), madness::Nemo::solve_cphf(), madness::MolecularEnergy::value(), and madness::Znemo::value().
nuclear_attraction_potential()
double madness::Molecule::nuclear_attraction_potential (double x, double y, double z) const
nuclear attraction potential for the whole molecule
References atoms, madness::distance(), field, rcut, madness::smoothed_potential(), and sum.
Referenced by madness::MolecularPotentialFunctor::operator()(), and MolecularPotentialFunctor::operator()().
nuclear_attraction_potential_derivative()
double madness::Molecule::nuclear_attraction_potential_derivative (int atom, int axis, double x, double y, double z) const
References atoms, axis, madness::distance(), madness::dsmoothed_potential(), field, and rcut.
Referenced by madness::NuclearCorrelationFactor::square_times_V_derivative_functor::operator()(), and madchem::MolecularDerivativeFunctor::operator()().
nuclear_attraction_potential_second_derivative()
double madness::Molecule::nuclear_attraction_potential_second_derivative (int atom, int iaxis, int jaxis, double x, double y, double z) const
the second derivative of the (smoothed) nuclear potential Z/r
with
References atoms, madness::d2smoothed_potential(), madness::Vector< T, N >::normf(), rcut, madness::smoothed_potential(), and u().
Referenced by madchem::MolecularSecondDerivativeFunctor::operator()().
nuclear_charge_density()
double madness::Molecule::nuclear_charge_density (double x, double y, double z, double rscale = 1.) const
evaluate the nuclear charge density at point {x,y,z} using the default MADNESS nuclear model. See smoothed_density() for the description of the default nuclear model.
Parameters
x,y,z the point at which the nuclear charge density is evaluated
rscale setting rscale>1 will make a nucleus larger by a factor of rscale (in other words, rcut is multiplied by the inverse of by this)
Returns
the nuclear charge density at point {x,y,z}
See also
smoothed_density()
References atoms, madness::distance_sq(), MADNESS_ASSERT, rcut, and madness::smoothed_density().
Referenced by madness::NuclearDensityFunctor::operator()().
nuclear_dipole()
double madness::Molecule::nuclear_dipole (int axis) const
compute the dipole moment of the nuclei
Parameters
[in] axis the axis (x, y, z)
References atoms, axis, core_pot, madness::CorePotentialManager::is_defined(), MADNESS_EXCEPTION, madness::CorePotentialManager::n_core_orb(), and sum.
Referenced by madness::SCF::dipole().
nuclear_dipole_derivative()
Tensor< double > madness::Molecule::nuclear_dipole_derivative (const int atom, const int axis) const
compute the derivative of the nuclear dipole wrt a nuclear displacement
Parameters
[in] atom the atom which will be displaced
[in] axis the axis where the atom will be displaced
Returns
a vector which all 3 components of the dipole derivative
References atoms, and axis.
Referenced by madness::Nemo::compute_IR_intensities().
nuclear_repulsion_derivative()
double madness::Molecule::nuclear_repulsion_derivative (size_t iatom, int axis) const
References atoms, axis, core_pot, inter_atomic_distance(), madness::CorePotentialManager::is_defined(), madness::CorePotentialManager::n_core_orb(), and sum.
Referenced by madness::NemoBase::compute_gradient(), and madness::SCF::derivatives().
nuclear_repulsion_energy()
double madness::Molecule::nuclear_repulsion_energy () const
References atoms, core_pot, inter_atomic_distance(), madness::CorePotentialManager::is_defined(), madness::CorePotentialManager::n_core_orb(), and sum.
Referenced by madness::Znemo::compute_energy(), main(), and madness::SCF::solve().
nuclear_repulsion_hessian()
Tensor< double > madness::Molecule::nuclear_repulsion_hessian () const
return the hessian matrix of the second derivatives d^2/dxdy V
compute the nuclear-nuclear contribution to the molecular hessian
no factor 0.5 included
References natom(), and nuclear_repulsion_second_derivative().
Referenced by madness::Nemo::hessian(), and madness::Nemo::make_incomplete_hessian().
nuclear_repulsion_second_derivative()
double madness::Molecule::nuclear_repulsion_second_derivative (int iatom, int jatom, int iaxis, int jaxis) const
compute the nuclear-nuclear contribution to the second derivatives
Parameters
[in] iatom the i-th atom (row of the hessian)
[in] jatom the j-th atom (column of the hessian)
[in] iaxis the xyz axis of the i-th atom
[in] jaxis the xyz axis of the j-th atom return the (3*iatom + iaxis, 3*jatom + jaxis) matix element of the hessian
[in] iatom the i-th atom (row of the hessian)
[in] jatom the j-th atom (column of the hessian)
[in] iaxis the xyz axis of the i-th atom
[in] jaxis the xyz axis of the j-th atom return the (3*iatom + iaxis, 3*jatom + jaxis) matix element
References atoms, core_pot, inter_atomic_distance(), madness::CorePotentialManager::is_defined(), MADNESS_EXCEPTION, and sum.
Referenced by nuclear_repulsion_hessian().
operator==()
bool madness::Molecule::operator== (const Molecule & other) const inline
References atoms, field, parameters, pointgroup_, and rcut.
orient()
void madness::Molecule::orient (bool verbose = false)
Centers and orients the molecule in a standard manner.
References atoms, center(), e(), fix_phase(), I, k, MADNESS_CHECK, parameters, pointgroup_, madness::print(), q(), rotate(), madness::syev(), symmetrize_and_identify_point_group(), and madness::Molecule::GeometryParameters::symtol().
Referenced by madness::cubefile_header(), from_json(), get_structure(), and main().
position_stream_in_library()
std::istream & madness::Molecule::position_stream_in_library (std::ifstream & f, const std::string & name) static
References errmsg(), madness::f, get_structure_library_path(), MADNESS_CHECK_THROW, madness::name(), and madness::position_stream_to_word().
Referenced by read_structure_from_library(), and madness::Molecule::GeometryParameters::set_derived_values().
print()
void madness::Molecule::print (std::ostream & os = std::cout, const bool defined_only = false) const
print all parameters and the molecular geometry
References atoms, madness::get_atomic_data(), natom(), p(), parameters, madness::QCCalculationParametersBase::print_to_string(), and madness::AtomicData::symbol.
Referenced by madness::Znemo::Znemo(), madness::SCF::load_mos(), main(), main(), print_defined_only(), and test_ethylene().
print_defined_only()
void madness::Molecule::print_defined_only (std::ostream & os = std::cout) const inline
print user-defined parameters and the molecular geometry
References print().
print_parameters()
void madness::Molecule::print_parameters () static
References param, and madness::print().
Referenced by madness::CC2::print_parameters(), madness::MP2::print_parameters(), madness::Nemo::print_parameters(), madness::OEP::print_parameters(), madness::PNO::print_parameters(), madness::SCF::print_parameters(), madness::TDHF::print_parameters(), madness::Zcis::print_parameters(), and madness::Znemo::print_parameters().
read()
void madness::Molecule::read (std::istream & f)
References add_atom(), madness::constants::atomic_unit_of_length, atoms, madness::check_if_pseudo_atom(), e(), madness::Molecule::GeometryParameters::eprec(), madness::f, madness::QCCalculationParametersBase::get_all_parameters(), p(), parameters, madness::position_stream(), rcut, madness::scale(), madness::symbol_to_atomic_number(), tag, madness::Molecule::GeometryParameters::units(), and update_rcut_with_eprec().
Referenced by get_structure(), read_file(), and read_structure_from_library().
read_core_file()
void madness::Molecule::read_core_file (const std::string & filename)
References atoms, core_pot, madness::filename, get_eprec(), madness::CorePotentialManager::is_defined(), madness::CorePotentialManager::n_core_orb(), natom(), madness::print(), q(), rcut, madness::CorePotentialManager::read_file(), and madness::smoothing_parameter().
Referenced by Molecule(), and get_structure().
read_file()
void madness::Molecule::read_file (const std::string & filename)
References errmsg(), madness::f, madness::filename, MADNESS_EXCEPTION, and read().
Referenced by madness::cubefile_header().
read_structure_from_library()
void madness::Molecule::read_structure_from_library (const std::string & name)
References errmsg(), madness::f, MADNESS_EXCEPTION, madness::name(), position_stream_in_library(), and read().
Referenced by get_structure().
read_xyz()
void madness::Molecule::read_xyz (const std::string filename)
References add_atom(), madness::constants::atomic_unit_of_length, atoms, madness::check_if_pseudo_atom(), e(), madness::Molecule::GeometryParameters::eprec(), errmsg(), madness::f, madness::filename, MADNESS_CHECK, MADNESS_EXCEPTION, natom(), parameters, rcut, madness::scale(), madness::symbol_to_atomic_number(), tag, madness::Molecule::GeometryParameters::units(), and update_rcut_with_eprec().
Referenced by get_structure().
rotate()
void madness::Molecule::rotate (const Tensor< double > & D)
Parameters
[in] D the rotation matrix
References atoms, field, and madness::inner().
Referenced by madness::SCF::initial_guess_from_nwchem(), and orient().
serialize()
template<typename Archive > void madness::Molecule::serialize (Archive & ar) inline
References atoms, core_pot, field, parameters, pointgroup_, and rcut.
set_all_coords()
void madness::Molecule::set_all_coords (const madness::Tensor< double > & newcoords)
References atoms, c, MADNESS_ASSERT, and natom().
Referenced by madness::MolecularEnergy::value(), and madness::Znemo::value().
set_atom_charge()
void madness::Molecule::set_atom_charge (unsigned int i, double zeff)
References atoms.
Referenced by get_structure().
set_atom_coords()
void madness::Molecule::set_atom_coords (unsigned int i, double x, double y, double z)
References atoms.
set_core_eprec()
void madness::Molecule::set_core_eprec (double value) inline
References core_pot, and madness::CorePotentialManager::set_eprec().
set_core_rcut()
void madness::Molecule::set_core_rcut (double value) inline
References core_pot, and madness::CorePotentialManager::set_rcut().
set_pseudo_atom()
void madness::Molecule::set_pseudo_atom (unsigned int i, bool psat)
References atoms.
Referenced by get_structure().
set_rcut()
void madness::Molecule::set_rcut (double value)
References atoms, and rcut.
smallest_length_scale()
double madness::Molecule::smallest_length_scale () const
References atoms, and rcut.
Referenced by madness::NuclearDensityFunctor::operator()(), and madness::ResponseParameters::set_ground_state_calculation_data().
swapaxes()
void madness::Molecule::swapaxes (int ix, int iy) private
References atoms, and field.
Referenced by symmetrize_and_identify_point_group().
symmetrize_and_identify_point_group()
std::string madness::Molecule::symmetrize_and_identify_point_group (const double symtol)
References madness::inverse(), madness::print(), swapaxes(), symmetrize_for_op(), test_for_c2(), test_for_inverse(), and test_for_sigma().
Referenced by orient().
symmetrize_for_op()
template<typename opT > void madness::Molecule::symmetrize_for_op (opT op, const double symtol) private
References atoms, madness::distance(), find_symmetry_equivalent_atom(), MADNESS_CHECK, op(), and test_for_op().
Referenced by symmetrize_and_identify_point_group().
test_for_c2()
bool madness::Molecule::test_for_c2 (double xaxis, double yaxis, double zaxis, const double symtol) const private
References test_for_op().
Referenced by symmetrize_and_identify_point_group().
test_for_inverse()
bool madness::Molecule::test_for_inverse (const double symtol) const private
References test_for_op().
Referenced by symmetrize_and_identify_point_group().
test_for_op()
template<typename opT > bool madness::Molecule::test_for_op (opT op, const double symtol) const private
References atoms, find_symmetry_equivalent_atom(), and op().
Referenced by symmetrize_for_op(), test_for_c2(), test_for_inverse(), and test_for_sigma().
test_for_sigma()
bool madness::Molecule::test_for_sigma (double xaxis, double yaxis, double zaxis, const double symtol) const private
References test_for_op().
Referenced by symmetrize_and_identify_point_group().
to_json()
nlohmann::json madness::Molecule::to_json () const
References insert_symbols_and_geometry(), parameters, and madness::QCCalculationParametersBase::to_json().
Referenced by madness::MolecularEnergy::output_calc_info_schema(), madness::SCF::output_calc_info_schema(), and to_json_if_precedence().
to_json_if_precedence()
json madness::Molecule::to_json_if_precedence (std::string const & precedence) const inline
References insert_symbols_and_geometry(), parameters, to_json(), and madness::QCCalculationParametersBase::to_json_if_precedence().
total_nuclear_charge()
double madness::Molecule::total_nuclear_charge () const
References atoms, and sum.
Referenced by MiniDFT::doit(), main(), and main().
translate()
void madness::Molecule::translate (const Tensor< double > & translation)
translate the molecule
References atoms.
Referenced by center(), madness::SCF::initial_guess_from_nwchem(), projector_external_dof(), and madness::MolecularOptimizer::projector_external_dof().
update_rcut_with_eprec()
void madness::Molecule::update_rcut_with_eprec (double value)
updates rcuts with given eprec
References atoms, core_pot, get_eprec(), parameters, rcut, madness::CorePotentialManager::set_eprec(), madness::QCCalculationParametersBase::set_user_defined_value(), and madness::smoothing_parameter().
Referenced by Molecule(), dnuclear_anchor_test(), main(), read(), and read_xyz().
Member Data Documentation
atomic_radii
std::vector<double> madness::Molecule::atomic_radii
Referenced by Molecule(), add_atom(), and add_atom().
atoms
std::vector<Atom> madness::Molecule::atoms private
Referenced by Molecule(), add_atom(), add_atom(), atomic_attraction_potential(), bounding_cube(), center(), core_derivative(), core_eval(), core_potential_derivative(), find_symmetry_equivalent_atom(), fix_phase(), from_json(), get_atom(), get_atom_charge(), get_atomic_number(), get_atoms(), get_pseudo_atom(), hash(), insert_symbols_and_geometry(), inter_atomic_distance(), is_potential_defined_atom(), molecular_core_potential(), moment_of_inertia(), n_core_orb_all(), natom(), nuclear_attraction_potential(), nuclear_attraction_potential_derivative(), nuclear_attraction_potential_second_derivative(), nuclear_charge_density(), nuclear_dipole(), nuclear_dipole_derivative(), nuclear_repulsion_derivative(), nuclear_repulsion_energy(), nuclear_repulsion_second_derivative(), operator==(), orient(), print(), read(), read_core_file(), read_xyz(), rotate(), serialize(), set_all_coords(), set_atom_charge(), set_atom_coords(), set_pseudo_atom(), set_rcut(), smallest_length_scale(), swapaxes(), symmetrize_for_op(), test_for_op(), total_nuclear_charge(), translate(), and update_rcut_with_eprec().
core_pot
CorePotentialManager madness::Molecule::core_pot private
Referenced by core_derivative(), core_eval(), core_potential_derivative(), get_core_bc(), get_core_l(), guess_file(), is_potential_defined(), is_potential_defined_atom(), molecular_core_potential(), n_core_orb(), n_core_orb_all(), nuclear_dipole(), nuclear_repulsion_derivative(), nuclear_repulsion_energy(), nuclear_repulsion_second_derivative(), read_core_file(), serialize(), set_core_eprec(), set_core_rcut(), and update_rcut_with_eprec().
field
madness::Tensor<double> madness::Molecule::field private
Referenced by Molecule(), nuclear_attraction_potential(), nuclear_attraction_potential_derivative(), operator==(), rotate(), serialize(), and swapaxes().
parameters
GeometryParameters madness::Molecule::parameters
Referenced by Molecule(), madness::Nuclear< T, NDIM >::Nuclear(), madness::SCF::apply_potential(), madness::SCF::derivatives(), from_json(), get_eprec(), get_structure(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), madness::SCF::loadbal(), madness::SCF::make_nuclear_potential(), operator==(), orient(), madness::MolecularEnergy::output_calc_info_schema(), print(), read(), read_xyz(), madness::Znemo::recompute_factors_and_potentials(), serialize(), madness::SCF::solve(), to_json(), to_json_if_precedence(), and update_rcut_with_eprec().
pointgroup_
std::string madness::Molecule::pointgroup_ = "c1" private
The molecular point group is automatically assigned in the identify_pointgroup function
Referenced by get_pointgroup(), hash(), operator==(), orient(), and serialize().
rcut
std::vector<double> madness::Molecule::rcut private
Referenced by add_atom(), add_atom(), atomic_attraction_potential(), from_json(), get_rcut(), hash(), nuclear_attraction_potential(), nuclear_attraction_potential_derivative(), nuclear_attraction_potential_second_derivative(), nuclear_charge_density(), operator==(), read(), read_core_file(), read_xyz(), serialize(), set_rcut(), smallest_length_scale(), and update_rcut_with_eprec().
tag
constexpr char const* madness::Molecule::tag = "molecule" static constexpr
Referenced by madness::Molecule::GeometryParameters::GeometryParameters(), read(), and read_xyz().
The documentation for this class was generated from the following files:
molecule.h
molecule.cc