MADNESS: MicroTask< T, NDIM > Class Template Reference
MicroTask< T, NDIM > Class Template Reference
Public Types
typedef std::tuple< const Function< T, NDIM > &, const double &, const std::vector< Function< T, NDIM > > & > argtupleT
using resultT = std::vector< Function< T, NDIM > >
Public Member Functions
resultT allocator (World &world, const argtupleT &argtuple) const
resultT operator() (const Function< T, NDIM > &f1, const double &arg2, const std::vector< Function< T, NDIM > > &f2) const
Public Member Functions inherited from madness::MacroTaskOperationBase
MacroTaskOperationBase ()
Additional Inherited Members
Public Attributes inherited from madness::MacroTaskOperationBase
Batch batch
std::string name ="unknown_task"
std::shared_ptr< MacroTaskPartitioner > partitioner =0
Member Typedef Documentation
argtupleT
template<typename T , std::size_t NDIM> typedef std::tuple<const Function<T,NDIM> &, const double &, const std::vector<Function<T,NDIM> > &> MicroTask< T, NDIM >::argtupleT
resultT
template<typename T , std::size_t NDIM> using MicroTask< T, NDIM >::resultT = std::vector<Function<T,NDIM> >
Member Function Documentation
allocator()
template<typename T , std::size_t NDIM> resultT MicroTask< T, NDIM >::allocator (World & world, const argtupleT & argtuple) const inline
operator()()
template<typename T , std::size_t NDIM> resultT MicroTask< T, NDIM >::operator() (const Function< T, NDIM > & f1, const double & arg2, const std::vector< Function< T, NDIM > > & f2) const inline
References madness::apply(), f1, f2, op(), madness::print(), and madness::World::rank().
The documentation for this class was generated from the following file:
test_vectormacrotask.cc