MADNESS: DirichletCondIntOp Class Reference
DirichletCondIntOp Class Reference
The operator needed for solving for with GMRES.
#include <test_problems.h>
Public Member Functions
DirichletCondIntOp (const SeparatedConvolution< double, 3 > &gin, const Function< double, 3 > &bin)
Public Member Functions inherited from madness::Operator< Function< double, 3 > >
virtual ~Operator ()
Function< double, 3 > & applyOp (const Function< double, 3 > &in, Function< double, 3 > &out) const
Public access to the operator's action, returns out for convenience.
Protected Member Functions
void action (const Function< double, 3 > &invec, Function< double, 3 > &outvec) const
Applies the operator to invec.
Protected Attributes
const Function< double, 3 > & b
The surface function (normalized)
const SeparatedConvolution< double, 3 > & G
The Green's function.
Detailed Description
The operator needed for solving for with GMRES.
Constructor & Destructor Documentation
DirichletCondIntOp()
DirichletCondIntOp::DirichletCondIntOp (const SeparatedConvolution< double, 3 > & gin, const Function< double, 3 > & bin) inline
Member Function Documentation
action()
void DirichletCondIntOp::action (const Function< double, 3 > & invec, Function< double, 3 > & outvec) const inline protected virtual
Applies the operator to invec.
Note
G is actually .
Parameters
[in] invec The input vector
[out] outvec The action of the operator on invec
Implements madness::Operator< Function< double, 3 > >.
References b, madness::Function< T, NDIM >::broaden(), madness::f, G, madness::Function< T, NDIM >::scale(), and madness::Function< T, NDIM >::truncate().
Member Data Documentation
b
const Function<double, 3>& DirichletCondIntOp::b protected
The surface function (normalized)
Referenced by action().
G
const SeparatedConvolution<double, 3>& DirichletCondIntOp::G protected
The Green's function.
Referenced by action().
The documentation for this class was generated from the following file:
test_problems.h