MADNESS: Mary Class Reference
Mary Class Reference
Public Member Functions
Mary ()
void add (int i)
string alan (int i, int j, int proc)
string cary (int i)
string cary0 ()
void fred (int i, double j)
double galahad (const string &str, int j, double z)
uint64_t get () const
bool get_me_twice (World *world, const WorldContainer< int, Mary > &d)
void inc () const
template<typename Archive >
void serialize (const Archive &ar)
Private Attributes
uint64_t val
Constructor & Destructor Documentation
Mary()
Mary::Mary () inline
Member Function Documentation
add()
void Mary::add (int i) inline
References val.
Referenced by test10().
alan()
string Mary::alan (int i, int j, int proc) inline
References val.
Referenced by test10().
cary()
string Mary::cary (int i) inline
References val.
cary0()
string Mary::cary0 () inline
fred()
void Mary::fred (int i, double j) inline
References val.
Referenced by test10().
galahad()
double Mary::galahad (const string & str, int j, double z) inline
References madness::print(), and val.
Referenced by test10().
get()
uint64_t Mary::get () const inline
References val.
get_me_twice()
bool Mary::get_me_twice (World * world, const WorldContainer< int, Mary > & d) inline
Referenced by test10().
inc()
void Mary::inc () const inline
References val.
Referenced by pounder(), and test10().
serialize()
template<typename Archive > void Mary::serialize (const Archive & ar) inline
References val.
Member Data Documentation
val
uint64_t Mary::val mutable private
Referenced by add(), alan(), cary(), fred(), galahad(), get(), inc(), and serialize().
The documentation for this class was generated from the following file:
test_world.cc