MADNESS: MolecularGuessDensityFunctor Class Reference
MolecularGuessDensityFunctor Class Reference
Public Member Functions
MolecularGuessDensityFunctor (const Molecule &molecule, const AtomicBasisSet &aobasis)
MolecularGuessDensityFunctor (const Molecule &molecule, const AtomicBasisSet &aobasis)
double operator() (const coord_3d &x) const
double operator() (const coord_3d &x) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual std::vector< Vector< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const AtomicBasisSet & aobasis
const int maxR = 2
const Molecule & molecule
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
MolecularGuessDensityFunctor() [1/2]
MolecularGuessDensityFunctor::MolecularGuessDensityFunctor (const Molecule & molecule, const AtomicBasisSet & aobasis) inline
MolecularGuessDensityFunctor() [2/2]
MolecularGuessDensityFunctor::MolecularGuessDensityFunctor (const Molecule & molecule, const AtomicBasisSet & aobasis) inline
Member Function Documentation
operator()() [1/2]
double MolecularGuessDensityFunctor::operator() (const coord_3d & x) const inline
References aobasis, madness::AtomicBasisSet::eval_guess_density(), and molecule.
operator()() [2/2]
double MolecularGuessDensityFunctor::operator() (const coord_3d & x) const inline
References aobasis, madness::AtomicBasisSet::eval_guess_density(), k, L, maxR, molecule, and madness::sum().
Member Data Documentation
aobasis
const AtomicBasisSet & MolecularGuessDensityFunctor::aobasis private
maxR
const int MolecularGuessDensityFunctor::maxR = 2 private
molecule
const Molecule & MolecularGuessDensityFunctor::molecule private
The documentation for this class was generated from the following files:
preal.cc
testperiodicdft.cc