MADNESS: madness::MacroTaskSinglesPotentialGs Class Reference
madness::MacroTaskSinglesPotentialGs Class Reference
#include <CCStructures.h>
Public Types
typedef std::tuple< const std::vector< int > &, const CC_vecfunction &, const std::vector< CCPair > &, const int &, const Info & > argtupleT
using resultT = std::tuple< std::vector< real_function_3d >, std::vector< real_function_3d > >
first vector is the potential, second is an intermediate (if applicable, e.g. for s2b and s2c potentials)
Public Member Functions
MacroTaskSinglesPotentialGs ()
resultT allocator (World &world, const argtupleT &argtuple) const
allocate the result and set the name of this task
resultT operator() (const std::vector< int > &result_index, const CC_vecfunction &singles_gs, const std::vector< CCPair > &doubles_gs, const int &name, const Info &info)
Public Member Functions inherited from madness::MacroTaskOperationBase
MacroTaskOperationBase ()
Public Attributes
std::string basename ="SinglesPotentialGs"
Public Attributes inherited from madness::MacroTaskOperationBase
Batch batch
std::string name ="unknown_task"
std::shared_ptr< MacroTaskPartitioner > partitioner =0
World * subworld_ptr =0
Member Typedef Documentation
argtupleT
typedef std::tuple< const std::vector<int>&, const CC_vecfunction&, const std::vector<CCPair>&, const int&, const Info& > madness::MacroTaskSinglesPotentialGs::argtupleT
resultT
using madness::MacroTaskSinglesPotentialGs::resultT = std::tuple<std::vector<real_function_3d>,std::vector<real_function_3d> >
first vector is the potential, second is an intermediate (if applicable, e.g. for s2b and s2c potentials)
Constructor & Destructor Documentation
MacroTaskSinglesPotentialGs()
madness::MacroTaskSinglesPotentialGs::MacroTaskSinglesPotentialGs () inline
References madness::MacroTaskOperationBase::name.
Member Function Documentation
allocator()
resultT madness::MacroTaskSinglesPotentialGs::allocator (World & world, const argtupleT & argtuple) const inline
allocate the result and set the name of this task
References madness::assign_name(), basename, and madness::MacroTaskOperationBase::name.
operator()()
std::tuple< std::vector< real_function_3d >, std::vector< real_function_3d > > madness::MacroTaskSinglesPotentialGs::operator() (const std::vector< int > & result_index, const CC_vecfunction & singles_gs, const std::vector< CCPair > & doubles_gs, const int & name, const Info & info)
References madness::CCParameters::freeze(), madness::CC_vecfunction::get_vecfunction(), MADNESS_CHECK_THROW, madness::Info::mo_ket, madness::MacroTaskOperationBase::name, madness::Info::parameters, madness::World::size(), madness::PairVectorMap::triangular_map(), and madness::Pairs< T >::vector2pairs().
Member Data Documentation
basename
std::string madness::MacroTaskSinglesPotentialGs::basename ="SinglesPotentialGs"
Referenced by allocator().
The documentation for this class was generated from the following files:
CCStructures.h
CCStructures.cc