MADNESS: madness::Vector< T, N > Class Template Reference
madness::Vector< T, N > Class Template Reference
A simple, fixed dimension vector.
#include <vector.h>
Public Types
using arrayT = std::array< T, N >
The underlying array type.
using const_iterator = typename arrayT::const_iterator
Const iterator type.
using const_reference = typename arrayT::const_reference
Const reference type.
using const_reverse_iterator = typename arrayT::const_reverse_iterator
Const reverse iterator type.
using difference_type = typename arrayT::difference_type
Difference type.
using iterator = typename arrayT::iterator
Iterator type.
using reference = typename arrayT::reference
Reference type.
using reverse_iterator = typename arrayT::reverse_iterator
Reverse iterator type.
using size_type = typename arrayT::size_type
Size type.
using value_type = typename arrayT::value_type
The data value type.
Public Member Functions
constexpr Vector ()=default
Default constructor; does not initialize vector contents.
template<typename Q >
constexpr Vector (const Q(&t)[N])
Construct from a C-style array of the same dimension.
template<typename Q >
constexpr Vector (const std::array< Q, N > &t)
Construct from a std::array of equal length.
template<typename Q , typename A >
constexpr Vector (const std::vector< Q, A > &t)
Construct from an STL vector of equal or greater length.
template<typename Q >
constexpr Vector (const Vector< Q, N > &other)
Copy constructor is deep (because Vector is POD).
constexpr Vector (const Vector< T, N > &other)
Copy constructor is deep (because Vector is POD).
template<typename Q >
constexpr Vector (Q t)
Initialize all elements to value t.
constexpr Vector (std::initializer_list< T > list)
List initialization constructor (deep copy because Vector is POD).
constexpr reference at (size_type i)
Access element i of the Vector with bounds checking.
constexpr const_reference at (size_type i) const
Access element i of the Vector with bounds checking.
constexpr reference back ()
Access the last element.
constexpr const_reference back () const
Access the last element.
constexpr iterator begin ()
Iterator starting at the first element.
constexpr const_iterator begin () const
Const iterator starting at the first element.
constexpr T * data ()
Direct access to the underlying array.
constexpr const T * data () const
Direct access to the underlying array.
constexpr bool empty () const
Check if the Vector is empty.
constexpr iterator end ()
Iterator to the end (past the last element).
constexpr const_iterator end () const
Const iterator to the end (past the last element).
constexpr void fill (const T &t)
Fill the Vector with the specified value.
constexpr reference front ()
Access the first element.
constexpr const_reference front () const
Access the first element.
constexpr hashT hash () const
Support for MADNESS hashing.
constexpr size_type max_size () const
Get the maximum size of the Vector.
constexpr T normf () const
Calculate the 2-norm of the vector elements.
constexpr operator std::array< T, N > ()
Type conversion to a std::array.
template<typename Q >
constexpr Vector< T, N > & operator*= (Q q)
In-place, element-wise multiplcation by a scalar.
template<typename Q >
constexpr Vector< T, N > & operator+= (const Vector< Q, N > &q)
In-place, element-wise addition of another Vector.
template<typename Q >
constexpr Vector< T, N > & operator-= (const Vector< Q, N > &q)
In-place, element-wise subtraction of another Vector.
template<typename Q , typename A >
constexpr Vector< T, N > & operator= (const std::vector< Q, A > &other)
Assignment is deep (because Vector is POD).
constexpr Vector< T, N > & operator= (const T &t)
Fill from a scalar value.
template<typename Q >
constexpr Vector< T, N > & operator= (const Vector< Q, N > &other)
Assignment is deep (because Vector is POD).
constexpr Vector< T, N > & operator= (const Vector< T, N > &other)
Assignment is deep (because a Vector is POD).
constexpr Vector< T, N > & operator= (std::initializer_list< T > list)
List initialization assignment (deep copy because Vector is POD).
constexpr reference operator[] (size_type i)
Access element i of the Vector.
constexpr const_reference operator[] (size_type i) const
Access element i of the Vector.
constexpr reverse_iterator rbegin ()
Reverse iterator starting at the last element.
constexpr const_reverse_iterator rbegin () const
Const reverse iterator starting at the last element.
constexpr reverse_iterator rend ()
Reverse iterator to the beginning (before the first element).
constexpr const_reverse_iterator rend () const
Const reverse iterator to the beginning (before the first element).
template<typename Archive >
constexpr void serialize (Archive &ar)
Support for MADNESS serialization.
constexpr size_type size () const
Accessor for the number of elements in the Vector.
constexpr void swap (Vector< T, N > &other)
Swap the contents with another Vector.
Static Public Attributes
static constexpr size_type static_size = N
The size of the Vector.
Private Attributes
arrayT data_
The underlying array.
Friends
template<typename Q , std::size_t M>
class Vector
constexpr bool operator!= (const Vector< T, N > &l, const Vector< T, N > &r)
Check if any element is not equal to its partner in the other Vector.
constexpr bool operator< (const Vector< T, N > &l, const Vector< T, N > &r)
Compare l and r lexicographically.
std::ostream & operator<< (std::ostream &s, const Vector< T, N > &v)
Output a Vector to stream.
constexpr bool operator<= (const Vector< T, N > &l, const Vector< T, N > &r)
Compare l and r lexicographically.
constexpr bool operator== (const Vector< T, N > &l, const Vector< T, N > &r)
Check if each element is equal to its partner in the other Vector.
constexpr bool operator> (const Vector< T, N > &l, const Vector< T, N > &r)
Compare l and r lexicographically.
constexpr bool operator>= (const Vector< T, N > &l, const Vector< T, N > &r)
Compare l and r lexicographically.
Detailed Description
template<typename T, std::size_t N>
class madness::Vector< T, N >
A simple, fixed dimension vector.
This class eliminates memory allocation cost, is just POD (it can be copied easily and allocated on the stack), and the known dimension permits aggressive compiler optimizations.
Provides additional mathematical and I/O operations.
Template Parameters
T The type of data stored in the vector.
N The size of the vector.
Member Typedef Documentation
arrayT
template<typename T , std::size_t N> using madness::Vector< T, N >::arrayT = std::array<T,N>
The underlying array type.
const_iterator
template<typename T , std::size_t N> using madness::Vector< T, N >::const_iterator = typename arrayT::const_iterator
Const iterator type.
const_reference
template<typename T , std::size_t N> using madness::Vector< T, N >::const_reference = typename arrayT::const_reference
Const reference type.
const_reverse_iterator
template<typename T , std::size_t N> using madness::Vector< T, N >::const_reverse_iterator = typename arrayT::const_reverse_iterator
Const reverse iterator type.
difference_type
template<typename T , std::size_t N> using madness::Vector< T, N >::difference_type = typename arrayT::difference_type
Difference type.
iterator
template<typename T , std::size_t N> using madness::Vector< T, N >::iterator = typename arrayT::iterator
Iterator type.
reference
template<typename T , std::size_t N> using madness::Vector< T, N >::reference = typename arrayT::reference
Reference type.
reverse_iterator
template<typename T , std::size_t N> using madness::Vector< T, N >::reverse_iterator = typename arrayT::reverse_iterator
Reverse iterator type.
size_type
template<typename T , std::size_t N> using madness::Vector< T, N >::size_type = typename arrayT::size_type
Size type.
value_type
template<typename T , std::size_t N> using madness::Vector< T, N >::value_type = typename arrayT::value_type
The data value type.
Constructor & Destructor Documentation
Vector() [1/8]
template<typename T , std::size_t N> constexpr madness::Vector< T, N >::Vector () constexpr default
Default constructor; does not initialize vector contents.
Vector() [2/8]
template<typename T , std::size_t N> template<typename Q > constexpr madness::Vector< T, N >::Vector (Q t) inline explicit constexpr
Initialize all elements to value t.
Template Parameters
Q The type of t.
Parameters
[in] t The value used to initialized the Vector.
References madness::Vector< T, N >::fill().
Vector() [3/8]
template<typename T , std::size_t N> template<typename Q > constexpr madness::Vector< T, N >::Vector (const Q(&) t[N]) inline explicit constexpr
Construct from a C-style array of the same dimension.
Template Parameters
Q The type of data in t.
Parameters
[in] t The C-style array.
References madness::Vector< T, N >::data_, and N.
Vector() [4/8]
template<typename T , std::size_t N> template<typename Q , typename A > constexpr madness::Vector< T, N >::Vector (const std::vector< Q, A > & t) inline explicit constexpr
Construct from an STL vector of equal or greater length.
Template Parameters
Q Type of data stored in the std::vector.
A Allocator type for the std::vector.
Parameters
[in] t The std::vector.
References madness::Vector< T, N >::operator=().
Vector() [5/8]
template<typename T , std::size_t N> template<typename Q > constexpr madness::Vector< T, N >::Vector (const std::array< Q, N > & t) inline explicit constexpr
Construct from a std::array of equal length.
Template Parameters
Q Type of data stored in the original std::array.
Parameters
[in] t The std::array.
References madness::Vector< T, N >::data_.
Vector() [6/8]
template<typename T , std::size_t N> constexpr madness::Vector< T, N >::Vector (const Vector< T, N > & other) inline constexpr
Copy constructor is deep (because Vector is POD).
Parameters
[in] other The Vector to copy.
References madness::Vector< T, N >::data_, MADNESS_PRAGMA_GCC, and madness::pop().
Vector() [7/8]
template<typename T , std::size_t N> template<typename Q > constexpr madness::Vector< T, N >::Vector (const Vector< Q, N > & other) inline constexpr
Copy constructor is deep (because Vector is POD).
Template Parameters
Q Type of the Vector to copy.
Parameters
[in] other The Vector to copy.
References madness::Vector< T, N >::data_.
Vector() [8/8]
template<typename T , std::size_t N> constexpr madness::Vector< T, N >::Vector (std::initializer_list< T > list) inline constexpr
List initialization constructor (deep copy because Vector is POD).
This constructor allows initialization using, e.g.,
Vector<double, 3> v{ 1.5, 2.4, -1.9 };
Exceptions
MadnessException if the list does not contain exactly N elements.
Parameters
[in] list The initializer list; elements are copied to the Vector.
References madness::Vector< T, N >::data_, MADNESS_ASSERT, and N.
Member Function Documentation
at() [1/2]
template<typename T , std::size_t N> constexpr reference madness::Vector< T, N >::at (size_type i) inline constexpr
Access element i of the Vector with bounds checking.
Parameters
[in] i The index.
Returns
A reference to element i.
References madness::Vector< T, N >::data_.
Referenced by madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::special_points().
at() [2/2]
template<typename T , std::size_t N> constexpr const_reference madness::Vector< T, N >::at (size_type i) const inline constexpr
Access element i of the Vector with bounds checking.
Parameters
[in] i The index.
Returns
A const reference to element i.
References madness::Vector< T, N >::data_.
back() [1/2]
template<typename T , std::size_t N> constexpr reference madness::Vector< T, N >::back () inline constexpr
Access the last element.
Returns
A reference to the last element.
References madness::Vector< T, N >::data_.
back() [2/2]
template<typename T , std::size_t N> constexpr const_reference madness::Vector< T, N >::back () const inline constexpr
Access the last element.
Returns
A const reference to the last element.
References madness::Vector< T, N >::data_.
begin() [1/2]
template<typename T , std::size_t N> constexpr iterator madness::Vector< T, N >::begin () inline constexpr
Iterator starting at the first element.
Returns
Iterator to the starting element.
References madness::Vector< T, N >::data_.
Referenced by main().
begin() [2/2]
template<typename T , std::size_t N> constexpr const_iterator madness::Vector< T, N >::begin () const inline constexpr
Const iterator starting at the first element.
Returns
Const iterator to the starting element.
References madness::Vector< T, N >::data_.
data() [1/2]
template<typename T , std::size_t N> constexpr T * madness::Vector< T, N >::data () inline constexpr
Direct access to the underlying array.
Returns
Pointer to the underlying array.
References madness::Vector< T, N >::data_.
data() [2/2]
template<typename T , std::size_t N> constexpr const T * madness::Vector< T, N >::data () const inline constexpr
Direct access to the underlying array.
Returns
Const pointer to the underlying array.
References madness::Vector< T, N >::data_.
empty()
template<typename T , std::size_t N> constexpr bool madness::Vector< T, N >::empty () const inline constexpr
Check if the Vector is empty.
Returns
True if the Vector is empty; false otherwise. This should be false unless N == 0.
References madness::Vector< T, N >::data_.
end() [1/2]
template<typename T , std::size_t N> constexpr iterator madness::Vector< T, N >::end () inline constexpr
Iterator to the end (past the last element).
Returns
Iterator to the end.
References madness::Vector< T, N >::data_.
end() [2/2]
template<typename T , std::size_t N> constexpr const_iterator madness::Vector< T, N >::end () const inline constexpr
Const iterator to the end (past the last element).
Returns
Const iterator to the end.
References madness::Vector< T, N >::data_.
fill()
template<typename T , std::size_t N> constexpr void madness::Vector< T, N >::fill (const T & t) inline constexpr
Fill the Vector with the specified value.
Parameters
[in] t The value used to fill the Vector.
References madness::Vector< T, N >::data_, and N.
Referenced by madness::Vector< T, N >::Vector(), madness::cartesian_grid< NDIM >::initialize(), madness::Vector< T, N >::operator=(), test_arithmetic(), and test_lowrank_function().
front() [1/2]
template<typename T , std::size_t N> constexpr reference madness::Vector< T, N >::front () inline constexpr
Access the first element.
Returns
A reference to the first element.
References madness::Vector< T, N >::data_.
front() [2/2]
template<typename T , std::size_t N> constexpr const_reference madness::Vector< T, N >::front () const inline constexpr
Access the first element.
Returns
A const reference to the first element.
References madness::Vector< T, N >::data_.
hash()
template<typename T , std::size_t N> constexpr hashT madness::Vector< T, N >::hash () const inline constexpr
Support for MADNESS hashing.
Returns
The hash.
References madness::Vector< T, N >::data_, and madness::hash_value().
max_size()
template<typename T , std::size_t N> constexpr size_type madness::Vector< T, N >::max_size () const inline constexpr
Get the maximum size of the Vector.
Returns
The maximum size, N.
References madness::Vector< T, N >::data_.
normf()
template<typename T , std::size_t N> constexpr T madness::Vector< T, N >::normf () const inline constexpr
Calculate the 2-norm of the vector elements.
Returns
The 2-norm.
Todo:
Is there a reason this is "normf" and not "norm2"?
References d, madness::Vector< T, N >::data_, N, and T().
Referenced by madness::Diamagnetic_potential_factor::Diamagnetic_potential_factor(), madness::Diamagnetic_potential_factor::apply_potential(), bend(), madness::Diamagnetic_potential_factor::compute_nabla_R_div_R(), madness::Diamagnetic_potential_factor::compute_R_times_T_commutator_scalar_term_numerically(), madness::Diamagnetic_potential_factor::compute_U2(), madness::NuclearCorrelationFactor::dsmoothed_unitvec(), f(), f(), f(), f(), f(), madness::Diamagnetic_potential_factor::factor_with_phase(), ExactSpinor::Fvalue(), Ansatz0::make_guess(), make_Hv(), make_pw_matrix(), madness::Molecule::nuclear_attraction_potential_second_derivative(), sgl_guess::operator()(), madness::R_times_arg_div_R::operator()(), ncf::operator()(), madness::NuclearCorrelationFactor::R_functor::operator()(), madness::NuclearCorrelationFactor::U1_functor::operator()(), madness::NuclearCorrelationFactor::U1_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U1_dot_U1_functor::operator()(), madness::NuclearCorrelationFactor::U2_functor::operator()(), madness::NuclearCorrelationFactor::U3_functor::operator()(), madness::NuclearCorrelationFactor::U2_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U3_atomic_functor::operator()(), madness::NuclearCorrelationFactor::square_times_V_functor::operator()(), madness::NuclearCorrelationFactor::square_times_V_derivative_functor::operator()(), madness::NuclearCorrelationFactor::RX_functor::operator()(), madness::NuclearCorrelationFactor::U1X_functor::operator()(), madness::NuclearCorrelationFactor::U2X_functor::operator()(), madness::NuclearCorrelationFactor::U3X_functor::operator()(), refpotfunctor::operator()(), madness::Znemo::s_orbital::operator()(), madness::Znemo::p_orbital::operator()(), madness::spherical_box< NDIM >::operator()(), p_minus(), p_plus(), ExactSpinor::psivalue(), slater(), madness::NuclearCorrelationFactor::smoothed_unitvec(), madness::Slater::Sp(), madness::Polynomial< N >::Sp(), test_conversion(), test_inner(), test_Kcommutator(), test_multiply(), test_node_replicated_function(), and madness::unitvec().
operator std::array< T, N >()
template<typename T , std::size_t N> constexpr madness::Vector< T, N >::operator std::array< T, N > () inline constexpr
Type conversion to a std::array.
Returns
The underlying std::array.
operator*=()
template<typename T , std::size_t N> template<typename Q > constexpr Vector< T, N > & madness::Vector< T, N >::operator*= (Q q) inline constexpr
In-place, element-wise multiplcation by a scalar.
Template Parameters
Q Type of the scalar.
Parameters
[in] q The scalar.
Returns
A reference to this for chaining operations.
Todo:
Do we want a similar division operation?
References madness::Vector< T, N >::data_, N, and q().
operator+=()
template<typename T , std::size_t N> template<typename Q > constexpr Vector< T, N > & madness::Vector< T, N >::operator+= (const Vector< Q, N > & q) inline constexpr
In-place, element-wise addition of another Vector.
Template Parameters
Q Type stored in the other Vector.
Parameters
[in] q The other Vector.
Returns
A reference to this for chaining operations.
References madness::Vector< T, N >::data_, N, and q().
operator-=()
template<typename T , std::size_t N> template<typename Q > constexpr Vector< T, N > & madness::Vector< T, N >::operator-= (const Vector< Q, N > & q) inline constexpr
In-place, element-wise subtraction of another Vector.
Template Parameters
Q Type stored in the other Vector.
Parameters
[in] q The other Vector.
Returns
A reference to this for chaining operations.
References madness::Vector< T, N >::data_, N, and q().
operator=() [1/5]
template<typename T , std::size_t N> template<typename Q , typename A > constexpr Vector< T, N > & madness::Vector< T, N >::operator= (const std::vector< Q, A > & other) inline constexpr
Assignment is deep (because Vector is POD).
Make sure the size of other is at least N.
Template Parameters
Q The type of data in the std::vector.
A The allocator type for the std::vector.
Parameters
[in] other The std::vector to copy.
Returns
This Vector.
References madness::Vector< T, N >::data_, MADNESS_ASSERT, and N.
operator=() [2/5]
template<typename T , std::size_t N> constexpr Vector< T, N > & madness::Vector< T, N >::operator= (const T & t) inline constexpr
Fill from a scalar value.
Parameters
[in] t The scalar to use for filling.
Returns
This Vector.
References madness::Vector< T, N >::fill().
operator=() [3/5]
template<typename T , std::size_t N> template<typename Q > constexpr Vector< T, N > & madness::Vector< T, N >::operator= (const Vector< Q, N > & other) inline constexpr
Assignment is deep (because Vector is POD).
Template Parameters
Q The type of the Vector to copy.
Parameters
[in] other The Vector to copy.
Returns
This Vector.
References madness::Vector< T, N >::data_.
operator=() [4/5]
template<typename T , std::size_t N> constexpr Vector< T, N > & madness::Vector< T, N >::operator= (const Vector< T, N > & other) inline constexpr
Assignment is deep (because a Vector is POD).
Parameters
[in] other The Vector to copy.
Returns
This Vector.
References madness::Vector< T, N >::data_.
Referenced by madness::Vector< T, N >::Vector().
operator=() [5/5]
template<typename T , std::size_t N> constexpr Vector< T, N > & madness::Vector< T, N >::operator= (std::initializer_list< T > list) inline constexpr
List initialization assignment (deep copy because Vector is POD).
This assignment operator allows initialization using, e.g.,
v = { 1.5, 2.4, -1.9 };
Exceptions
MadnessException if the list does not contain exactly N elements.
Parameters
[in] list The initializer list; elements are copied to the Vector.
References madness::Vector< T, N >::data_, MADNESS_ASSERT, and N.
operator[]() [1/2]
template<typename T , std::size_t N> constexpr reference madness::Vector< T, N >::operator[] (size_type i) inline constexpr
Access element i of the Vector.
Bounds checking is not performed.
Parameters
[in] i The index.
Returns
A reference to element i.
References madness::Vector< T, N >::data_.
operator[]() [2/2]
template<typename T , std::size_t N> constexpr const_reference madness::Vector< T, N >::operator[] (size_type i) const inline constexpr
Access element i of the Vector.
Bounds checking is not performed.
Parameters
[in] i The index.
Returns
A const reference to element i.
References madness::Vector< T, N >::data_.
rbegin() [1/2]
template<typename T , std::size_t N> constexpr reverse_iterator madness::Vector< T, N >::rbegin () inline constexpr
Reverse iterator starting at the last element.
Returns
Reverse iterator to the last element.
References madness::Vector< T, N >::data_.
rbegin() [2/2]
template<typename T , std::size_t N> constexpr const_reverse_iterator madness::Vector< T, N >::rbegin () const inline constexpr
Const reverse iterator starting at the last element.
Returns
Const reverse iterator to the last element.
References madness::Vector< T, N >::data_.
rend() [1/2]
template<typename T , std::size_t N> constexpr reverse_iterator madness::Vector< T, N >::rend () inline constexpr
Reverse iterator to the beginning (before the first element).
Returns
Reverse iterator to the beginning.
References madness::Vector< T, N >::data_.
rend() [2/2]
template<typename T , std::size_t N> constexpr const_reverse_iterator madness::Vector< T, N >::rend () const inline constexpr
Const reverse iterator to the beginning (before the first element).
Returns
Const reverse iterator to the beginning.
References madness::Vector< T, N >::data_.
serialize()
template<typename T , std::size_t N> template<typename Archive > constexpr void madness::Vector< T, N >::serialize (Archive & ar) inline constexpr
Support for MADNESS serialization.
Template Parameters
Archive The archive type.
Parameters
[in,out] ar The archive.
References madness::Vector< T, N >::data_.
size()
template<typename T , std::size_t N> constexpr size_type madness::Vector< T, N >::size () const inline constexpr
Accessor for the number of elements in the Vector.
Returns
The number of elements.
References madness::Vector< T, N >::data_.
Referenced by madness::PlotParameters::origin(), and updatex().
swap()
template<typename T , std::size_t N> constexpr void madness::Vector< T, N >::swap (Vector< T, N > & other) inline constexpr
Swap the contents with another Vector.
Parameters
[in] other The other vector.
References madness::Vector< T, N >::data_.
Referenced by madness::swap().
Friends And Related Symbol Documentation
Vector
template<typename T , std::size_t N> template<typename Q , std::size_t M> friend class Vector friend
operator!=
template<typename T , std::size_t N> constexpr bool operator!= (const Vector< T, N > & l, const Vector< T, N > & r) friend
Check if any element is not equal to its partner in the other Vector.
Parameters
[in] l One Vector.
[in] r The other Vector.
Returns
True if any element is not equal to its partner; false otherwise.
operator<
template<typename T , std::size_t N> constexpr bool operator< (const Vector< T, N > & l, const Vector< T, N > & r) friend
Compare l and r lexicographically.
Parameters
[in] l One Vector.
[in] r The other Vector.
Returns
True if the contents of l are lexicographically less than the contents of r; false otherwise.
operator<<
template<typename T , std::size_t N> std::ostream & operator<< (std::ostream & s, const Vector< T, N > & v) friend
Output a Vector to stream.
Parameters
[in] s The output stream.
[in] v The Vector to output.
Returns
The output stream.
operator<=
template<typename T , std::size_t N> constexpr bool operator<= (const Vector< T, N > & l, const Vector< T, N > & r) friend
Compare l and r lexicographically.
Parameters
[in] l One Vector.
[in] r The other Vector.
Returns
True if the contents of l are lexicographically less than or equal to the contents of r; false otherwise.
operator==
template<typename T , std::size_t N> constexpr bool operator== (const Vector< T, N > & l, const Vector< T, N > & r) friend
Check if each element is equal to its partner in the other Vector.
Parameters
[in] l One Vector.
[in] r The other Vector.
Returns
True if each element is equal to its partner; false otherwise.
operator>
template<typename T , std::size_t N> constexpr bool operator> (const Vector< T, N > & l, const Vector< T, N > & r) friend
Compare l and r lexicographically.
Parameters
[in] l One Vector.
[in] r The other Vector.
Returns
True if the contents of l are lexicographically greater than the contents of r; false otherwise.
operator>=
template<typename T , std::size_t N> constexpr bool operator>= (const Vector< T, N > & l, const Vector< T, N > & r) friend
Compare l and r lexicographically.
Parameters
[in] l One Vector.
[in] r The other Vector.
Returns
True if the contents of l are lexicographically greater than or equal to the contents of r; false otherwise.
Member Data Documentation
data_
template<typename T , std::size_t N> arrayT madness::Vector< T, N >::data_ private
The underlying array.
Referenced by madness::Vector< T, N >::Vector(), madness::Vector< T, N >::Vector(), madness::Vector< T, N >::Vector(), madness::Vector< T, N >::Vector(), madness::Vector< T, N >::Vector(), madness::Vector< T, N >::at(), madness::Vector< T, N >::at(), madness::Vector< T, N >::back(), madness::Vector< T, N >::back(), madness::Vector< T, N >::begin(), madness::Vector< T, N >::begin(), madness::Vector< T, N >::data(), madness::Vector< T, N >::data(), madness::Vector< T, N >::empty(), madness::Vector< T, N >::end(), madness::Vector< T, N >::end(), madness::Vector< T, N >::fill(), madness::Vector< T, N >::front(), madness::Vector< T, N >::front(), madness::Vector< T, N >::hash(), madness::Vector< T, N >::max_size(), madness::Vector< T, N >::normf(), madness::Vector< double, NDIM >::operator std::array< double, N >(), madness::Vector< T, N >::operator*=(), madness::Vector< T, N >::operator+=(), madness::Vector< T, N >::operator-=(), madness::Vector< T, N >::operator=(), madness::Vector< T, N >::operator=(), madness::Vector< T, N >::operator=(), madness::Vector< T, N >::operator=(), madness::Vector< T, N >::operator[](), madness::Vector< T, N >::operator[](), madness::Vector< T, N >::rbegin(), madness::Vector< T, N >::rbegin(), madness::Vector< T, N >::rend(), madness::Vector< T, N >::rend(), madness::Vector< T, N >::serialize(), madness::Vector< T, N >::size(), and madness::Vector< T, N >::swap().
static_size
template<typename T , std::size_t N> constexpr size_type madness::Vector< T, N >::static_size = N inline static constexpr
The size of the Vector.
The documentation for this class was generated from the following files:
functypedefs.h
vector.h