MADNESS: NuclearChargeDensityOp< T, NDIM > Class Template Reference
NuclearChargeDensityOp< T, NDIM > Class Template Reference
Public Types
typedef Function< T, NDIM > funcT
Public Member Functions
NuclearChargeDensityOp (World &world, funcT rhon, double coeff, double thresh)
~NuclearChargeDensityOp ()
virtual bool is_od ()
Is there an orbitally-dependent term?
virtual bool is_rd ()
Is there a density-dependent term?
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
void prepare_op (Function< double, NDIM > rho)
Public Member Functions inherited from madness::EigSolverOp< T, NDIM >
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
double coeff ()
std::string messsageME ()
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
Private Attributes
SeparatedConvolution< T, NDIM > * _cop
funcT _rhon
funcT _Vnuc
Additional Inherited Members
Public Attributes inherited from madness::EigSolverOp< T, NDIM >
World & _world
Protected Member Functions inherited from madness::EigSolverOp< T, NDIM >
void messageME (std::string messageME)
double thresh ()
Member Typedef Documentation
funcT
template<typename T , int NDIM> typedef Function<T,NDIM> NuclearChargeDensityOp< T, NDIM >::funcT
Constructor & Destructor Documentation
NuclearChargeDensityOp()
template<typename T , int NDIM> NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp (World & world, funcT rhon, double coeff, double thresh) inline
References NuclearChargeDensityOp< T, NDIM >::_cop, NuclearChargeDensityOp< T, NDIM >::_rhon, NuclearChargeDensityOp< T, NDIM >::_Vnuc, madness::apply(), e(), and madness::EigSolverOp< T, NDIM >::thresh().
~NuclearChargeDensityOp()
template<typename T , int NDIM> NuclearChargeDensityOp< T, NDIM >::~NuclearChargeDensityOp () inline
References NuclearChargeDensityOp< T, NDIM >::_cop.
Member Function Documentation
is_od()
template<typename T , int NDIM> virtual bool NuclearChargeDensityOp< T, NDIM >::is_od () inline virtual
Is there an orbitally-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
is_rd()
template<typename T , int NDIM> virtual bool NuclearChargeDensityOp< T, NDIM >::is_rd () inline virtual
Is there a density-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
op_r()
template<typename T , int NDIM> virtual funcT NuclearChargeDensityOp< T, NDIM >::op_r (const funcT & rho, const funcT & psi) inline virtual
Density-dependent portion of operator.
Reimplemented from madness::EigSolverOp< T, NDIM >.
References NuclearChargeDensityOp< T, NDIM >::_Vnuc, and psi().
prepare_op()
template<typename T , int NDIM> void NuclearChargeDensityOp< T, NDIM >::prepare_op (Function< double, NDIM > rho) inline
Member Data Documentation
_cop
template<typename T , int NDIM> SeparatedConvolution<T,NDIM>* NuclearChargeDensityOp< T, NDIM >::_cop private
Referenced by NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp(), and NuclearChargeDensityOp< T, NDIM >::~NuclearChargeDensityOp().
_rhon
template<typename T , int NDIM> funcT NuclearChargeDensityOp< T, NDIM >::_rhon private
Referenced by NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp().
_Vnuc
template<typename T , int NDIM> funcT NuclearChargeDensityOp< T, NDIM >::_Vnuc private
Referenced by NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp(), and NuclearChargeDensityOp< T, NDIM >::op_r().
The documentation for this class was generated from the following file:
test_hydro.cc