MADNESS: madness::ParametrizedExchange Class Reference
madness::ParametrizedExchange Class Reference
#include <PNOStructures.h>
Public Member Functions
ParametrizedExchange (World &world, const Nemo &nemo_, const std::string &type_)
real_function_3d operator() (const real_function_3d &ket) const
vecfuncT operator() (const vecfuncT &vket, const double &mul_tol=0.0) const
Public Attributes
Exchange< double, 3 > K
const Nemo & nemo
const std::string type
World & world
Constructor & Destructor Documentation
ParametrizedExchange()
madness::ParametrizedExchange::ParametrizedExchange (World & world, const Nemo & nemo_, const std::string & type_) inline
Member Function Documentation
operator()() [1/2]
real_function_3d madness::ParametrizedExchange::operator() (const real_function_3d & ket) const inline
References madness::nonlinear_vector_solver(), and operator()().
Referenced by operator()().
operator()() [2/2]
vecfuncT madness::ParametrizedExchange::operator() (const vecfuncT & vket, const double & mul_tol = 0.0) const
References madness::Nemo::get_calc(), K, madness::Nemo::make_density(), nemo, madness::nonlinear_vector_solver(), madness::print(), madness::NemoBase::R_square, madness::World::size(), type, world, and xc.
Member Data Documentation
K
Exchange<double,3> madness::ParametrizedExchange::K
Referenced by operator()().
nemo
const Nemo& madness::ParametrizedExchange::nemo
Referenced by operator()().
type
const std::string madness::ParametrizedExchange::type
Referenced by operator()(), and madness::PNO::update_pno().
world
World& madness::ParametrizedExchange::world
Referenced by operator()().
The documentation for this class was generated from the following files:
PNOStructures.h
PNOStructures.cpp