MADNESS: DipoleVector Class Reference
DipoleVector Class Reference
#include <property.h>
Public Member Functions
DipoleVector (World &world)
Public Member Functions inherited from PropertyBase
PropertyBase ()
Additional Inherited Members
Public Attributes inherited from PropertyBase
size_t num_operators
vector_real_function_3d operator_vector
Constructor & Destructor Documentation
DipoleVector()
DipoleVector::DipoleVector (World & world)
References madness::f, madness::norm2(), PropertyBase::num_operators, PropertyBase::operator_vector, madness::print(), and madness::truncate().
The documentation for this class was generated from the following files:
property.h
property.cc