MADNESS: madness::MP2 Class Reference
madness::MP2 Class Reference
a class for computing the first order wave function and MP2 pair energies
#include <mp2.h>
Classes
struct Pairs
POD holding all electron pairs with easy access.
struct Parameters
POD for MP2 keywords.
Public Member Functions
MP2 (World &world, const commandlineparser &parser)
ctor
double asymmetry (const real_function_6d &f, const std::string s) const
bool check_core_valence_separation () const
make sure frozen orbitals don't couple with correlated ones – relocalize if necessary
double compute_gQf (const int i, const int j, ElectronPair &pair) const
compute the matrix element <ij | g12 Q12 f12 | phi^0>
double compute_gQf_cc2interface (const int i, const int j, const real_function_6d &f) const
compute the matrix element <ij | g12 Q12 f12 | phi^0>
double coord_chksum () const
return a checksum for the geometry
real_function_6d debug_cc2 (const real_function_6d &f, const size_t &i, const size_t &j) const
void enforce_core_valence_separation ()
make sure frozen orbitals don't couple with correlated ones – relocalize if necessary
HartreeFock & get_hf ()
return the underlying HF reference
real_function_6d get_residue (const real_function_6d &f, const int i, const int j)
void increment (ElectronPair &pair, real_convolution_6d &green)
compute increments: psi^1 = C + GV C + GVGV C + GVGVGV C + ..
real_function_6d iterate (const real_function_6d &f) const
solve the residual equation for electron pair (i,j)
template<typename T , size_t NDIM>
void load_function (Function< T, NDIM > &f, const std::string name) const
load a function
std::string name () const
template<typename T >
void print_options (const std::string option, const T val) const
pretty print the options
template<typename T , size_t NDIM>
void save_function (const Function< T, NDIM > &f, const std::string name) const
save a function
virtual bool selftest ()
double solve_coupled_equations (Pairs< ElectronPair > &pairs, const double econv, const double dconv) const
solve the coupled MP1 equations (e.g. for local orbitals)
void solve_residual_equations (ElectronPair &pair, const double econv, const double dconv) const
solve the residual equation for electron pair (i,j)
double value ()
return the molecular correlation energy energy (without the HF energy)
double value (const Tensor< double > &x)
return the molecular correlation energy as a function of the coordinates
double zeroth_order_energy (const int i, const int j) const
return the 0th order energy of pair ij (= sum of orbital energies)
Public Member Functions inherited from madness::OptimizationTargetInterface
virtual ~OptimizationTargetInterface ()
virtual Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
virtual bool provides_gradient () const
Override this to return true if the derivative is implemented.
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
Static Public Member Functions
static void help ()
static void print_parameters ()
Private Member Functions
void add_local_coupling (const Pairs< ElectronPair > &pairs, Pairs< real_function_6d > &coupling) const
add the coupling terms for local MP2
real_function_6d apply_exchange (const real_function_6d &f, const real_function_3d &orbital_ket, const real_function_3d &orbital_bra, const int particle) const
apply the exchange operator on f
real_function_6d apply_exchange_vector (const real_function_6d &f, const int particle) const
double compute_energy (ElectronPair &pair) const
compute the singlet and triplet energy for a given electron pair
void END_TIMER (World &world, const char *msg) const
Tensor< double > get_fock_matrix () const
void guess_mp1_3 (ElectronPair &pair) const
compute the first iteration of the residual equations and all intermediates
real_function_3d J (const real_function_3d &phi) const
apply the Coulomb operator a on orbital
real_function_6d JK1phi0_on_demand (const int i, const int j, const bool hc=false) const
return the function (J(1)-K(1)) |phi0> as on-demand function
real_function_6d JK2phi0_on_demand (const int i, const int j, const bool hc=false) const
return the function (J(2)-K(2)) |phi0> as on-demand function
real_function_3d K (const real_function_3d &phi, const bool hc=false) const
apply the exchange operator on an orbital
real_function_6d K (const real_function_6d &phi, const bool is_symmetric=false) const
apply the exchange operator on a pair function
std::vector< real_function_3d > make_chi (const real_function_3d &phi, const real_convolution_3d &op, const bool hc=false) const
make the quantity chi_k
real_function_6d make_fKphi0 (const int i, const int j) const
apply the operator K on the reference and multiply with f; fK |phi^0>
real_function_6d make_KffKphi0 (const ElectronPair &pair) const
return the function [K,f] phi0; load from disk if available
ElectronPair make_pair (const int i, const int j) const
compute some matrix elements that don't change during the SCF
real_function_6d make_Uphi0 (ElectronPair &pair) const
return the function Uphi0; load from disk if available
std::vector< real_function_3d > make_xi (const real_function_3d &phi_i, const real_function_3d &phi_j, const real_convolution_3d &op, const bool hc=false) const
make the quantity xi_k
real_function_6d multiply_with_0th_order_Hamiltonian (const real_function_6d &f, const int i, const int j) const
multiply the given function with the 0th order Hamiltonian, exluding the 0th order energy
real_function_6d nemo0_on_demand (const int i, const int j) const
return the function |F1F2> as on-demand function
real_function_6d phi0_on_demand (const int i, const int j) const
return the function |phi0> as on-demand function
void START_TIMER (World &world) const
Private Attributes
double coords_sum
check sum for the geometry
double correlation_energy
the correlation energy
CorrelationFactor corrfac
correlation factor: Slater
Tensor< double > fock
the Fock matrix
std::shared_ptr< HartreeFock > hf
our reference
std::shared_ptr< NuclearCorrelationFactor > nuclear_corrfac
Pairs< ElectronPair > pairs
pair functions and energies
Parameters param
SCF parameters for MP2.
std::shared_ptr< real_convolution_3d > poisson
StrongOrthogonalityProjector< double, 3 > Q12
double sss
double ttt
World & world
the world
Detailed Description
a class for computing the first order wave function and MP2 pair energies
Constructor & Destructor Documentation
MP2()
madness::MP2::MP2 (World & world, const commandlineparser & parser)
ctor
References madness::MP2::Parameters::check_input(), corrfac, madness::CoulombOperatorPtr(), dcut, madness::MP2::Parameters::freeze(), hf, pairs, param, poisson, madness::QCCalculationParametersBase::print(), madness::print(), madness::World::rank(), madness::MP2::Parameters::restart(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::MP2::Parameters::thresh(), and world.
Member Function Documentation
add_local_coupling()
void madness::MP2::add_local_coupling (const Pairs< ElectronPair > & pairs, Pairs< real_function_6d > & coupling) const private
add the coupling terms for local MP2
\sum_{k\neq i} f_ki |u_kj> + \sum_{l\neq j} f_lj |u_il>
Todo:
Verify this doxygen block.
Returns
\sum_{k\neq i} f_ki |u_kj> + \sum_{l\neq j} f_lj |u_il>
References madness::FunctionFactory< T, NDIM >::compressed(), madness::WorldGopInterface::fence(), madness::MP2::Parameters::freeze(), function(), get_fock_matrix(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, hf, k, MADNESS_EXCEPTION, pairs, param, madness::print(), madness::World::rank(), madness::swap_particles(), thresh, and world.
Referenced by solve_coupled_equations().
apply_exchange()
real_function_6d madness::MP2::apply_exchange (const real_function_6d & f, const real_function_3d & orbital_ket, const real_function_3d & orbital_bra, const int particle) const private
apply the exchange operator on f
if the exchange operator is similarity transformed (R-1 K R) the orbital spaces differ for the orbitals underneath the integral sign R-1 K R = \phi-ket(1) * \int \phi-bra(1') * f(1',2)
Parameters
[in] f the pair function
[in] orbital_bra the orbital underneath the integral sign (typically R2orbitals)
[in] orbital_ket the orbital to be pre-multiplied with (typically orbitals)
Returns
the pair function, on which the exchange operator has been applied
References madness::copy(), madness::CoulombOperator(), madness::f, hf, madness::load_balance(), MADNESS_ASSERT, madness::multiply(), op(), madness::Function< T, NDIM >::truncate(), and world.
apply_exchange_vector()
real_function_6d madness::MP2::apply_exchange_vector (const real_function_6d & f, const int particle) const private
References madness::apply(), madness::Function< T, NDIM >::change_tree_state(), madness::copy(), madness::CoulombOperator(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::get_impl(), madness::get_impl(), madness::World::gop, hf, madness::make_redundant(), op(), madness::print_size(), madness::reduce_rank(), madness::redundant, madness::timer::tag(), madness::truncate(), v, and world.
Referenced by K().
asymmetry()
double madness::MP2::asymmetry (const real_function_6d & f, const std::string s) const
References diff(), madness::f, madness::norm2(), madness::print(), madness::World::rank(), madness::swap_particles(), and world.
Referenced by guess_mp1_3(), and make_Uphi0().
check_core_valence_separation()
bool madness::MP2::check_core_valence_separation () const
make sure frozen orbitals don't couple with correlated ones – relocalize if necessary
References madness::Localizer::check_core_valence_separation(), madness::MolecularOrbitals< T, NDIM >::convert_set_to_slice(), madness::MP2::Parameters::freeze(), get_fock_matrix(), madness::MolecularOrbitals< T, NDIM >::get_localize_sets(), hf, param, madness::MolecularOrbitals< T, NDIM >::pretty_print(), madness::print(), and madness::MolecularOrbitals< T, NDIM >::recompute_localize_sets().
Referenced by value().
compute_energy()
double madness::MP2::compute_energy (ElectronPair & pair) const private
compute the singlet and triplet energy for a given electron pair
Returns
the energy of 1 degenerate triplet and 1 singlet pair
References madness::copy(), dcut, madness::TwoElectronFactory< T, NDIM >::dcut(), madness::ElectronPair::e_singlet, madness::ElectronPair::e_triplet, END_TIMER, madness::ElectronPair::function, madness::CompositeFactory< T, NDIM, MDIM >::g12(), hf, madness::ElectronPair::i, madness::ElectronPair::ij_gQf_ij, madness::inner(), madness::ElectronPair::j, madness::ElectronPair::ji_gQf_ij, JK1phi0_on_demand(), JK2phi0_on_demand(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::World::rank(), START_TIMER, and world.
Referenced by guess_mp1_3(), increment(), solve_coupled_equations(), and solve_residual_equations().
compute_gQf()
double madness::MP2::compute_gQf (const int i, const int j, ElectronPair & pair) const
compute the matrix element <ij | g12 Q12 f12 | phi^0>
scales quartically. I think I can get this down to cubically by setting Q12 = (1 - O1)(1 - O2) = 1- O1(1 - 0.5 O2) - O2 (1 - 0.5 O1) as for the formulas cf the article mra_molecule
Returns
the energy <ij | g Q f | kl>
References a, bsh_eps, corrfac, madness::CoulombOperator(), e(), madness::f, madness::g, hf, madness::ElectronPair::i, madness::inner(), madness::ElectronPair::j, k, lo, make_xi(), madness::matrix_inner(), madness::OT_F12, madness::OT_G12, param, madness::constants::pi, poisson, madness::print(), Q12, madness::World::rank(), madness::CCTimer::reset(), madness::SlaterF12Operator(), and world.
Referenced by compute_gQf_cc2interface(), iterate(), and make_pair().
compute_gQf_cc2interface()
double madness::MP2::compute_gQf_cc2interface (const int i, const int j, const real_function_6d & f) const inline
compute the matrix element <ij | g12 Q12 f12 | phi^0>
scales quartically. I think I can get this down to cubically by setting Q12 = (1 - O1)(1 - O2) = 1- O1(1 - 0.5 O2) - O2 (1 - 0.5 O1) as for the formulas cf the article mra_molecule
Returns
the energy <ij | g Q f | kl>
References compute_gQf(), madness::ElectronPair::constant_term, madness::copy(), madness::f, and madness::ElectronPair::function.
coord_chksum()
double madness::MP2::coord_chksum () const inline
return a checksum for the geometry
References coords_sum.
Referenced by value().
debug_cc2()
real_function_6d madness::MP2::debug_cc2 (const real_function_6d & f, const size_t & i, const size_t & j) const inline
References madness::f, and multiply_with_0th_order_Hamiltonian().
END_TIMER()
void madness::MP2::END_TIMER (World & world, const char * msg) const inline private
References madness::cpu_time(), madness::World::rank(), sss, ttt, madness::wall_time(), and world.
enforce_core_valence_separation()
void madness::MP2::enforce_core_valence_separation ()
make sure frozen orbitals don't couple with correlated ones – relocalize if necessary
References madness::Localizer::check_core_valence_separation(), madness::Tensor< T >::clear(), fock, get_fock_matrix(), hf, madness::Localizer::localize(), MADNESS_CHECK, madness::print(), madness::MolecularOrbitals< T, NDIM >::recompute_localize_sets(), madness::Localizer::set_enforce_core_valence_separation(), madness::Localizer::set_method(), madness::Localizer::set_metric(), and world.
Referenced by value().
get_fock_matrix()
Tensor< double > madness::MP2::get_fock_matrix () const inline private
References madness::copy(), fock, madness::Tensor< T >::has_data(), hf, madness::print(), madness::World::rank(), and world.
Referenced by add_local_coupling(), check_core_valence_separation(), and enforce_core_valence_separation().
get_hf()
HartreeFock & madness::MP2::get_hf () inline
return the underlying HF reference
References hf.
get_residue()
real_function_6d madness::MP2::get_residue (const real_function_6d & f, const int i, const int j) inline
References madness::f, hf, MADNESS_ASSERT, multiply_with_0th_order_Hamiltonian(), madness::NuclearCorrelationFactor::None, nuclear_corrfac, madness::print(), Q12, madness::World::rank(), madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces(), and world.
guess_mp1_3()
void madness::MP2::guess_mp1_3 (ElectronPair & pair) const private
compute the first iteration of the residual equations and all intermediates
References asymmetry(), bsh_eps, madness::Function< T, NDIM >::clear(), compute_energy(), madness::ElectronPair::constant_term, madness::copy(), corrfac, madness::SeparatedConvolution< Q, NDIM >::destructive(), madness::MP2::Parameters::do_oep(), fock, madness::ElectronPair::function, madness::FunctionDefaults< NDIM >::get_thresh(), h(), hf, madness::ElectronPair::i, madness::inner(), madness::Function< T, NDIM >::is_initialized(), madness::ElectronPair::j, k, lo, madness::load_balance(), make_KffKphi0(), make_Uphi0(), param, madness::constants::pi, poisson, madness::print(), madness::Function< T, NDIM >::print_size(), madness::Function< T, NDIM >::project_out(), Q12, madness::World::rank(), madness::Function< T, NDIM >::reduce_rank(), save_function(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::Function< T, NDIM >::set_thresh(), madness::SlaterF12Operator(), thresh, madness::FunctionFactory< T, NDIM >::thresh(), madness::transform(), madness::Function< T, NDIM >::truncate(), madness::truncate(), world, and zeroth_order_energy().
Referenced by solve_residual_equations().
help()
static void madness::MP2::help () inline static
References madness::print(), and madness::print_header2().
increment()
void madness::MP2::increment (ElectronPair & pair, real_convolution_6d & green)
compute increments: psi^1 = C + GV C + GVGV C + GVGVGV C + ..
for pre-optimization of the mp1 wave function no restart option here for now param[inout] pair the electron pair param[in] green the Green's function
apply the convolution
References compute_energy(), madness::ElectronPair::function, madness::ElectronPair::i, madness::ElectronPair::iteration, madness::ElectronPair::j, madness::load_balance(), load_function(), multiply_with_0th_order_Hamiltonian(), madness::Function< T, NDIM >::norm2(), madness::print(), madness::Function< T, NDIM >::print_size(), Q12, madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::thresh(), madness::Function< T, NDIM >::truncate(), madness::wall_time(), and world.
iterate()
real_function_6d madness::MP2::iterate (const real_function_6d & f) const inline
solve the residual equation for electron pair (i,j)
Todo:
Parameter documentation. Below are un-doxygenated comments that no longer seem relevant?
References compute_gQf(), madness::ElectronPair::constant_term, madness::copy(), madness::f, madness::ElectronPair::function, madness::ElectronPair::ij_gQf_ij, madness::ElectronPair::ji_gQf_ij, and solve_residual_equations().
J()
real_function_3d madness::MP2::J (const real_function_3d & phi) const private
apply the Coulomb operator a on orbital
Parameters
[in] phi the orbital
Returns
Jphi
References hf, and madness::Function< T, NDIM >::truncate().
Referenced by JK1phi0_on_demand(), and JK2phi0_on_demand().
JK1phi0_on_demand()
real_function_6d madness::MP2::JK1phi0_on_demand (const int i, const int j, const bool hc = false) const private
return the function (J(1)-K(1)) |phi0> as on-demand function
Parameters
[in] hc compute hermitian conjugate -> swap bra and ket space
References madness::copy(), hf, J(), K(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), and world.
Referenced by compute_energy().
JK2phi0_on_demand()
real_function_6d madness::MP2::JK2phi0_on_demand (const int i, const int j, const bool hc = false) const private
return the function (J(2)-K(2)) |phi0> as on-demand function
References madness::copy(), hf, J(), K(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), and world.
Referenced by compute_energy().
K() [1/2]
real_function_3d madness::MP2::K (const real_function_3d & phi, const bool hc = false) const private
apply the exchange operator on an orbital
Parameters
[in] phi the orbital
[in] hc hermitian conjugate -> swap bra and ket space
Returns
Kphi
References hf, k, madness::mul(), and world.
Referenced by JK1phi0_on_demand(), JK2phi0_on_demand(), make_fKphi0(), make_KffKphi0(), and multiply_with_0th_order_Hamiltonian().
K() [2/2]
real_function_6d madness::MP2::K (const real_function_6d & phi, const bool is_symmetric = false) const private
apply the exchange operator on a pair function
Parameters
[in] phi the pair function
[in] is_symmetric is the function symmetric wrt particle exchange
Returns
(K1 + K2) |phi >
References apply_exchange_vector(), madness::swap_particles(), and madness::Function< T, NDIM >::truncate().
load_function()
template<typename T , size_t NDIM> void madness::MP2::load_function (Function< T, NDIM > & f, const std::string name) const
load a function
References madness::f, name(), madness::print(), madness::World::rank(), and world.
Referenced by increment().
make_chi()
std::vector< real_function_3d > madness::MP2::make_chi (const real_function_3d & phi, const real_convolution_3d & op, const bool hc = false) const private
make the quantity chi_k
chi is the Poisson kernel applied on an orbital product of the input function and the vector of orbitals
if hc
Parameters
[in] phi orbital phi_i
[in] op the operator in SeparatedConvolution form
[in] hc compute hermitian conjugate -> pass the correct phi!
Returns
a vector of length nocc
References madness::apply(), hf, MADNESS_ASSERT, madness::mul_sparse(), op(), madness::truncate(), and world.
Referenced by make_xi().
make_fKphi0()
real_function_6d madness::MP2::make_fKphi0 (const int i, const int j) const private
apply the operator K on the reference and multiply with f; fK |phi^0>
Parameters
[in] i index of orbital i
[in] j index of orbital j
Returns
the function f12 (K(1)+K(2))|phi^0>
References madness::copy(), corrfac, madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), hf, K(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::Function< T, NDIM >::truncate(), madness::truncate(), and world.
Referenced by make_KffKphi0().
make_KffKphi0()
real_function_6d madness::MP2::make_KffKphi0 (const ElectronPair & pair) const private
return the function [K,f] phi0; load from disk if available
References a, a1, a2, madness::copy(), corrfac, madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), hf, madness::ElectronPair::i, madness::inner(), madness::ElectronPair::j, K(), MADNESS_EXCEPTION, make_fKphi0(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::World::rank(), madness::Function< T, NDIM >::reduce_rank(), madness::Function< T, NDIM >::truncate(), madness::truncate(), and world.
Referenced by guess_mp1_3().
make_pair()
ElectronPair madness::MP2::make_pair (const int i, const int j) const private
compute some matrix elements that don't change during the SCF
References compute_gQf(), p(), param, madness::World::rank(), madness::MP2::Parameters::restart(), madness::ElectronPair::uninitialized(), madness::wall_time(), and world.
Referenced by value().
make_Uphi0()
real_function_6d madness::MP2::make_Uphi0 (ElectronPair & pair) const private
return the function Uphi0; load from disk if available
References a, aa, asymmetry(), axis, madness::copy(), corrfac, diff(), e(), madness::error(), madness::Function< T, NDIM >::fill_cuspy_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::FunctionDefaults< NDIM >::get_thresh(), hf, madness::ElectronPair::i, madness::inner(), madness::ElectronPair::j, MADNESS_EXCEPTION, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::World::rank(), madness::scale(), madness::Function< T, NDIM >::set_thresh(), thresh, madness::FunctionFactory< T, NDIM >::thresh(), madness::truncate(), world, and zeroth_order_energy().
Referenced by guess_mp1_3().
make_xi()
std::vector< real_function_3d > madness::MP2::make_xi (const real_function_3d & phi_i, const real_function_3d & phi_j, const real_convolution_3d & op, const bool hc = false) const private
make the quantity xi_k
xi is chi multiplied with an orbital j
if hc
Parameters
[in] phi_i orbital i
[in] phi_j orbital j
[in] op the operator in SeparatedConvolution form
[in] hc compute hermitian conjugate -> pass the correct phi!
Returns
a vector of length k=0,..,nocc
References make_chi(), madness::mul_sparse(), op(), and world.
Referenced by compute_gQf().
multiply_with_0th_order_Hamiltonian()
real_function_6d madness::MP2::multiply_with_0th_order_Hamiltonian (const real_function_6d & f, const int i, const int j) const private
multiply the given function with the 0th order Hamiltonian, exluding the 0th order energy
Parameters
[in] f the function we apply H^0 on
Returns
the function g=H^0 f, which is NOT orthogonalized against f
References axis, bsh_eps, madness::copy(), madness::MP2::Parameters::do_oep(), END_TIMER, madness::f, madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::fill_tree(), madness::func(), madness::World::gop, hf, K(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::load(), madness::SeparatedConvolution< Q, NDIM >::modified(), param, madness::Function< T, NDIM >::print_size(), madness::print_size(), madness::Function< T, NDIM >::reduce_rank(), madness::set_thresh(), START_TIMER, madness::FunctionFactory< T, NDIM >::thresh(), madness::Function< T, NDIM >::truncate(), madness::truncate(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2(), world, and zeroth_order_energy().
Referenced by debug_cc2(), get_residue(), increment(), solve_coupled_equations(), and solve_residual_equations().
name()
std::string madness::MP2::name () const inline virtual
Implements madness::QCPropertyInterface.
Referenced by load_function(), save_function(), and solve_residual_equations().
nemo0_on_demand()
real_function_6d madness::MP2::nemo0_on_demand (const int i, const int j) const private
return the function |F1F2> as on-demand function
References madness::copy(), hf, madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), and world.
phi0_on_demand()
real_function_6d madness::MP2::phi0_on_demand (const int i, const int j) const private
return the function |phi0> as on-demand function
References madness::copy(), hf, madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), and world.
print_options()
template<typename T > void madness::MP2::print_options (const std::string option, const T val) const inline
pretty print the options
invoke only in (world.rank()==0) !!
print_parameters()
static void madness::MP2::print_parameters () inline static
References param, madness::QCCalculationParametersBase::print(), madness::print(), and madness::Molecule::print_parameters().
save_function()
template<typename T , size_t NDIM> void madness::MP2::save_function (const Function< T, NDIM > & f, const std::string name) const
save a function
References madness::f, name(), madness::print(), madness::World::rank(), and world.
Referenced by guess_mp1_3(), and solve_residual_equations().
selftest()
virtual bool madness::MP2::selftest () inline virtual
Implements madness::QCPropertyInterface.
solve_coupled_equations()
double madness::MP2::solve_coupled_equations (Pairs< ElectronPair > & pairs, const double econv, const double dconv) const
solve the coupled MP1 equations (e.g. for local orbitals)
solve the coupled MP1 equations for local orbitals
Parameters
[in] pairs set of (coupled) electron pairs to solve
[in] econv energy convergence criterion (for all pairs)
[in] dconv density convergence criterion (for all pairs)
[in] pairs solved decoupled electron pairs
References std::abs(), add_local_coupling(), bsh_eps, compute_energy(), END_TIMER, energy, madness::MP2::Parameters::freeze(), function(), hf, lo, madness::MP2::Parameters::maxiter(), multiply_with_0th_order_Hamiltonian(), pairs, param, Q12, madness::World::rank(), residual(), madness::Function< T, NDIM >::scale(), START_TIMER, madness::stringify(), madness::Function< T, NDIM >::truncate(), madness::truncate(), madness::wall_time(), world, and zeroth_order_energy().
Referenced by value().
solve_residual_equations()
void madness::MP2::solve_residual_equations (ElectronPair & pair, const double econv, const double dconv) const
solve the residual equation for electron pair (i,j)
References std::abs(), bsh_eps, compute_energy(), madness::ElectronPair::constant_term, madness::ElectronPair::converged, madness::SeparatedConvolution< Q, NDIM >::destructive(), madness::NonlinearSolverND< NDIM >::do_print, energy, madness::ElectronPair::function, guess_mp1_3(), madness::ElectronPair::i, madness::ElectronPair::iteration, madness::ElectronPair::j, lo, madness::load_balance(), madness::MP2::Parameters::maxiter(), madness::MP2::Parameters::maxsub(), multiply_with_0th_order_Hamiltonian(), name(), madness::MP2::Parameters::no_compute(), madness::Function< T, NDIM >::norm2(), param, madness::print(), madness::ElectronPair::print_energy(), madness::Function< T, NDIM >::print_size(), Q12, madness::World::rank(), residual(), save_function(), madness::Function< T, NDIM >::scale(), madness::ElectronPair::store_pair(), madness::stringify(), madness::Function< T, NDIM >::truncate(), madness::truncate(), madness::NonlinearSolverND< NDIM >::update(), madness::wall_time(), world, and zeroth_order_energy().
Referenced by iterate(), and value().
START_TIMER()
void madness::MP2::START_TIMER (World & world) const inline private
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, madness::wall_time(), and world.
value() [1/2]
double madness::MP2::value ()
return the molecular correlation energy energy (without the HF energy)
References check_core_valence_separation(), enforce_core_valence_separation(), hf, and value().
Referenced by value().
value() [2/2]
double madness::MP2::value (const Tensor< double > & x) virtual
return the molecular correlation energy as a function of the coordinates
Implements madness::OptimizationTargetInterface.
References coord_chksum(), coords_sum, correlation_energy, madness::MP2::Parameters::dconv(), madness::MP2::Parameters::econv(), madness::MP2::Parameters::freeze(), hf, madness::MP2::Parameters::i(), madness::MP2::Parameters::j(), MADNESS_CHECK, make_pair(), madness::MP2::Parameters::no_compute(), madness::NuclearCorrelationFactor::None, nuclear_corrfac, pairs, param, madness::print(), Q12, madness::World::rank(), madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces(), solve_coupled_equations(), solve_residual_equations(), madness::Tensor< T >::sumsq(), and world.
zeroth_order_energy()
double madness::MP2::zeroth_order_energy (const int i, const int j) const inline
return the 0th order energy of pair ij (= sum of orbital energies)
References hf.
Referenced by guess_mp1_3(), make_Uphi0(), multiply_with_0th_order_Hamiltonian(), solve_coupled_equations(), and solve_residual_equations().
Member Data Documentation
coords_sum
double madness::MP2::coords_sum private
check sum for the geometry
Referenced by coord_chksum(), and value().
correlation_energy
double madness::MP2::correlation_energy private
the correlation energy
Referenced by value().
corrfac
CorrelationFactor madness::MP2::corrfac private
correlation factor: Slater
Referenced by MP2(), compute_gQf(), guess_mp1_3(), make_fKphi0(), make_KffKphi0(), and make_Uphi0().
fock
Tensor<double> madness::MP2::fock mutable private
the Fock matrix
Referenced by enforce_core_valence_separation(), get_fock_matrix(), and guess_mp1_3().
hf
std::shared_ptr<HartreeFock> madness::MP2::hf private
our reference
Referenced by MP2(), add_local_coupling(), apply_exchange(), apply_exchange_vector(), check_core_valence_separation(), madness::MP2::Parameters::check_input(), compute_energy(), compute_gQf(), enforce_core_valence_separation(), get_fock_matrix(), get_hf(), get_residue(), guess_mp1_3(), J(), JK1phi0_on_demand(), JK2phi0_on_demand(), K(), make_chi(), make_fKphi0(), make_KffKphi0(), make_Uphi0(), multiply_with_0th_order_Hamiltonian(), nemo0_on_demand(), phi0_on_demand(), solve_coupled_equations(), value(), value(), and zeroth_order_energy().
nuclear_corrfac
std::shared_ptr<NuclearCorrelationFactor> madness::MP2::nuclear_corrfac private
Referenced by get_residue(), and value().
pairs
Pairs<ElectronPair> madness::MP2::pairs private
pair functions and energies
Referenced by MP2(), add_local_coupling(), solve_coupled_equations(), and value().
param
Parameters madness::MP2::param private
SCF parameters for MP2.
Referenced by MP2(), add_local_coupling(), check_core_valence_separation(), compute_gQf(), guess_mp1_3(), make_pair(), multiply_with_0th_order_Hamiltonian(), print_parameters(), solve_coupled_equations(), solve_residual_equations(), and value().
poisson
std::shared_ptr<real_convolution_3d> madness::MP2::poisson private
Referenced by MP2(), compute_gQf(), and guess_mp1_3().
Q12
StrongOrthogonalityProjector<double, 3> madness::MP2::Q12 private
Referenced by compute_gQf(), get_residue(), guess_mp1_3(), increment(), solve_coupled_equations(), solve_residual_equations(), and value().
sss
double madness::MP2::sss private
Referenced by END_TIMER(), and START_TIMER().
ttt
double madness::MP2::ttt mutable private
Referenced by END_TIMER(), and START_TIMER().
world
World& madness::MP2::world private
the world
Referenced by MP2(), madness::MP2::Parameters::Parameters(), add_local_coupling(), apply_exchange(), apply_exchange_vector(), asymmetry(), compute_energy(), compute_gQf(), END_TIMER(), enforce_core_valence_separation(), get_fock_matrix(), get_residue(), guess_mp1_3(), increment(), JK1phi0_on_demand(), JK2phi0_on_demand(), K(), load_function(), make_chi(), make_fKphi0(), make_KffKphi0(), make_pair(), make_Uphi0(), make_xi(), multiply_with_0th_order_Hamiltonian(), nemo0_on_demand(), phi0_on_demand(), madness::MP2::Parameters::read_and_set_derived_values(), save_function(), solve_coupled_equations(), solve_residual_equations(), START_TIMER(), and value().
The documentation for this class was generated from the following files:
mp2.h
madness/chem/mp2.cc