MADNESS: madness::BoxSurfaceDisplacementValidator< NDIM > Class Template Reference
madness::BoxSurfaceDisplacementValidator< NDIM > Class Template Reference
#include <displacements.h>
Public Types
using Displacement = Key< NDIM >
using DistanceSquaredFunc = std::function< Translation(const Displacement &)>
using Periodicity = array_of_bools< NDIM >
using Point = Key< NDIM >
using PointPattern = Vector< std::optional< Translation >, NDIM >
Public Member Functions
BoxSurfaceDisplacementValidator (const array_of_bools< NDIM > &is_infinite_domain, const array_of_bools< NDIM > &is_lattice_summed, const std::array< KernelRange, NDIM > &range, DistanceSquaredFunc default_distance_squared, Translation max_distsq_reached)
bool operator() (const Level level, const PointPattern &dest, std::optional< Displacement > &displacement) const
Apply filter to a displacement ending up at a point or a group of points (point pattern)
Private Attributes
DistanceSquaredFunc default_distance_squared_
std::array< ExtraDomainPolicy, NDIM > domain_policies_
Translation max_distsq_reached_
std::array< KernelRange, NDIM > range_
Detailed Description
template<size_t NDIM>
class madness::BoxSurfaceDisplacementValidator< NDIM >
This is used to filter out box surface displacements that
take us outside of the target domain, or
were already utilized as part of the the standard displacements list. For dealing with the lattice-summed operators the filter can adjusts the displacement to make sure that we end up in the simulation cell.
Member Typedef Documentation
Displacement
template<size_t NDIM> using madness::BoxSurfaceDisplacementValidator< NDIM >::Displacement = Key<NDIM>
DistanceSquaredFunc
template<size_t NDIM> using madness::BoxSurfaceDisplacementValidator< NDIM >::DistanceSquaredFunc = std::function<Translation(const Displacement&)>
Periodicity
template<size_t NDIM> using madness::BoxSurfaceDisplacementValidator< NDIM >::Periodicity = array_of_bools<NDIM>
Point
template<size_t NDIM> using madness::BoxSurfaceDisplacementValidator< NDIM >::Point = Key<NDIM>
PointPattern
template<size_t NDIM> using madness::BoxSurfaceDisplacementValidator< NDIM >::PointPattern = Vector<std::optional<Translation>, NDIM>
Constructor & Destructor Documentation
BoxSurfaceDisplacementValidator()
template<size_t NDIM> madness::BoxSurfaceDisplacementValidator< NDIM >::BoxSurfaceDisplacementValidator (const array_of_bools< NDIM > & is_infinite_domain, const array_of_bools< NDIM > & is_lattice_summed, const std::array< KernelRange, NDIM > & range, DistanceSquaredFunc default_distance_squared, Translation max_distsq_reached) inline
Parameters
is_infinite_domain whether the domain along each axis is finite (simulation cell) or infinite (the entire axis); if true for a given axis then any destination coordinate is valid, else only values in [0,2^n) are valid
is_lattice_summed if true for a given axis, displacement to x and x+2^n are equivalent, hence will be canonicalized to end up in the simulation cell. Periodic axes imply infinite domain, whatever was passed to is_infinite_domain.
range the kernel range for each axis
default_distance_squared function that converts a displacement to its effective distance squared (effective may be different from the real distance squared due to periodicity)
max_distsq_reached max effective distance squared reached by standard displacements
References madness::Discard, madness::BoxSurfaceDisplacementValidator< NDIM >::domain_policies_, madness::Keep, NDIM, and madness::Translate.
Member Function Documentation
operator()()
template<size_t NDIM> bool madness::BoxSurfaceDisplacementValidator< NDIM >::operator() (const Level level, const PointPattern & dest, std::optional< Displacement > & displacement) const inline
Apply filter to a displacement ending up at a point or a group of points (point pattern)
Parameters
level the tree level
dest the target point (when all elements are nonnull) or point pattern (when only some are). The latter is useful to skip the entire surface layer. The point coordinates are only used to determine whether we end up in or out of the domain.
displacement the optional displacement; if given then will check if it's among the standard displacement and whether it was used as part of the standard displacement set; if it has not been used and the operator is lattice summed, the displacement will be adjusted to end up in the simulation cell. Primary use case for omitting displacement is if dest is not equivalent to a point.
Returns
true if the displacement is to be used
References std::abs(), madness::Displacements< NDIM >::bmax_default(), d, madness::BoxSurfaceDisplacementValidator< NDIM >::default_distance_squared_, madness::Discard, madness::displacement(), madness::BoxSurfaceDisplacementValidator< NDIM >::domain_policies_, MADNESS_ASSERT, mask, madness::BoxSurfaceDisplacementValidator< NDIM >::max_distsq_reached_, N, NDIM, madness::BoxSurfaceDisplacementValidator< NDIM >::range_, and madness::Translate.
Member Data Documentation
default_distance_squared_
template<size_t NDIM> DistanceSquaredFunc madness::BoxSurfaceDisplacementValidator< NDIM >::default_distance_squared_ private
Referenced by madness::BoxSurfaceDisplacementValidator< NDIM >::operator()().
domain_policies_
template<size_t NDIM> std::array<ExtraDomainPolicy, NDIM> madness::BoxSurfaceDisplacementValidator< NDIM >::domain_policies_ private
Referenced by madness::BoxSurfaceDisplacementValidator< NDIM >::BoxSurfaceDisplacementValidator(), and madness::BoxSurfaceDisplacementValidator< NDIM >::operator()().
max_distsq_reached_
template<size_t NDIM> Translation madness::BoxSurfaceDisplacementValidator< NDIM >::max_distsq_reached_ private
Referenced by madness::BoxSurfaceDisplacementValidator< NDIM >::operator()().
range_
template<size_t NDIM> std::array<KernelRange, NDIM> madness::BoxSurfaceDisplacementValidator< NDIM >::range_ private
Referenced by madness::BoxSurfaceDisplacementValidator< NDIM >::operator()().
The documentation for this class was generated from the following file:
displacements.h