MADNESS: madness::archive::ContainerRecordOutputArchive Class Reference
madness::archive::ContainerRecordOutputArchive Class Reference
#include <parallel_dc_archive.h>
Public Types
using keyT = long
Public Types inherited from madness::archive::BaseOutputArchive
using is_saving = std::true_type
Type used by Boost.Serialization to determine if this object is an output archive.
Public Types inherited from madness::archive::BaseArchive
using is_loading = std::false_type
Type used by Boost.Serialization to determine if this object is an input archive.
using is_saving = std::false_type
Type used by Boost.Serialization to determine if this object is an output archive.
Public Member Functions
ContainerRecordOutputArchive (World &subworld, containerT &dc, const keyT &key)
~ContainerRecordOutputArchive ()
void close ()
void flush ()
VectorOutputArchive & get_archive ()
void open ()
template<class T >
std::enable_if< madness::is_trivially_serializable< T >::value, void >::type store (const T *t, long n) const
Public Member Functions inherited from madness::archive::BaseArchive
BaseArchive ()
Private Types
using containerT = WorldContainer< keyT, std::vector< unsigned char > >
Private Attributes
VectorOutputArchive ar
containerT & dc
keyT key
World & subworld
std::vector< unsigned char > v
Additional Inherited Members
Static Public Attributes inherited from madness::archive::BaseOutputArchive
static constexpr bool is_output_archive = true
Flag to determine if this object is an output archive.
Static Public Attributes inherited from madness::archive::BaseArchive
static constexpr bool is_archive = true
Flag to determine if this object is an archive.
static constexpr bool is_input_archive = false
Flag to determine if this object is an input archive.
static constexpr bool is_output_archive = false
Flag to determine if this object is an output archive.
static constexpr bool is_parallel_archive = false
Flag to determine if this object is a parallel archive.
Member Typedef Documentation
containerT
using madness::archive::ContainerRecordOutputArchive::containerT = WorldContainer<keyT,std::vector<unsigned char> > private
keyT
using madness::archive::ContainerRecordOutputArchive::keyT = long
Constructor & Destructor Documentation
ContainerRecordOutputArchive()
madness::archive::ContainerRecordOutputArchive::ContainerRecordOutputArchive (World & subworld, containerT & dc, const keyT & key) inline
~ContainerRecordOutputArchive()
madness::archive::ContainerRecordOutputArchive::~ContainerRecordOutputArchive () inline
References close().
Member Function Documentation
close()
void madness::archive::ContainerRecordOutputArchive::close () inline
References dc, key, madness::World::rank(), subworld, and v.
Referenced by ~ContainerRecordOutputArchive().
flush()
void madness::archive::ContainerRecordOutputArchive::flush () inline
get_archive()
VectorOutputArchive & madness::archive::ContainerRecordOutputArchive::get_archive () inline
References ar.
open()
void madness::archive::ContainerRecordOutputArchive::open () inline
store()
template<class T > std::enable_if< madness::is_trivially_serializable< T >::value, void >::type madness::archive::ContainerRecordOutputArchive::store (const T * t, long n) const inline
References ar, MADNESS_CHECK, madness::World::rank(), madness::archive::VectorOutputArchive::store(), and subworld.
Member Data Documentation
ar
VectorOutputArchive madness::archive::ContainerRecordOutputArchive::ar private
Referenced by get_archive(), and store().
dc
containerT& madness::archive::ContainerRecordOutputArchive::dc private
Referenced by close().
key
keyT madness::archive::ContainerRecordOutputArchive::key private
Referenced by close().
subworld
World& madness::archive::ContainerRecordOutputArchive::subworld private
Referenced by close(), and store().
v
std::vector<unsigned char> madness::archive::ContainerRecordOutputArchive::v private
Referenced by close().
The documentation for this class was generated from the following file:
parallel_dc_archive.h