MADNESS: TupleTask Class Reference
TupleTask Class Reference
Public Types
typedef std::tuple< const std::vector< real_function_3d > & > argtupleT
typedef std::tuple< vector_real_function_3d, vector_real_function_3d > resultT
Public Member Functions
resultT allocator (World &world, const argtupleT &argtuple) const
resultT operator() (const std::vector< real_function_3d > &f1) const
Public Member Functions inherited from madness::MacroTaskOperationBase
MacroTaskOperationBase ()
Additional Inherited Members
Public Attributes inherited from madness::MacroTaskOperationBase
Batch batch
std::string name ="unknown_task"
std::shared_ptr< MacroTaskPartitioner > partitioner =0
Member Typedef Documentation
argtupleT
typedef std::tuple<const std::vector<real_function_3d> &> TupleTask::argtupleT
resultT
typedef std::tuple<vector_real_function_3d,vector_real_function_3d> TupleTask::resultT
Member Function Documentation
allocator()
resultT TupleTask::allocator (World & world, const argtupleT & argtuple) const inline
References madness::nonlinear_vector_solver().
operator()()
resultT TupleTask::operator() (const std::vector< real_function_3d > & f1) const inline
References madness::copy(), f1, and madness::nonlinear_vector_solver().
The documentation for this class was generated from the following file:
test_vectormacrotask.cc