MADNESS: madness::NonlinearSolverND< NDIM > Class Template Reference
madness::NonlinearSolverND< NDIM > Class Template Reference
Mra » Simple Krylov-subspace nonlinear equation solver
A simple Krylov-subspace nonlinear equation solver.
#include <nonlinsol.h>
Public Member Functions
NonlinearSolverND (unsigned int maxsub=10)
unsigned int get_maxsub () const
void set_maxsub (const unsigned int &new_maxsub)
Function< double, NDIM > update (const Function< double, NDIM > &u, const Function< double, NDIM > &r, const double rcondtol=1e-8, const double cabsmax=1000.0)
Computes next trial solution vector.
Public Attributes
bool do_print
Private Attributes
unsigned int maxsub
Maximum size of subspace dimension.
real_tensor Q
std::vector< Function< double, NDIM > > rlist
std::vector< Function< double, NDIM > > ulist
Detailed Description
template<size_t NDIM>
class madness::NonlinearSolverND< NDIM >
A simple Krylov-subspace nonlinear equation solver.
Constructor & Destructor Documentation
NonlinearSolverND()
template<size_t NDIM> madness::NonlinearSolverND< NDIM >::NonlinearSolverND (unsigned int maxsub = 10) inline
Member Function Documentation
get_maxsub()
template<size_t NDIM> unsigned int madness::NonlinearSolverND< NDIM >::get_maxsub () const inline
References madness::NonlinearSolverND< NDIM >::maxsub.
set_maxsub()
template<size_t NDIM> void madness::NonlinearSolverND< NDIM >::set_maxsub (const unsigned int & new_maxsub) inline
References madness::NonlinearSolverND< NDIM >::maxsub.
update()
template<size_t NDIM> Function< double, NDIM > madness::NonlinearSolverND< NDIM >::update (const Function< double, NDIM > & u, const Function< double, NDIM > & r, const double rcondtol = 1e-8, const double cabsmax = 1000.0) inline
Computes next trial solution vector.
You are responsible for performing step restriction or line search (not necessary for linear problems).
Parameters
u Current solution vector
r Corresponding residual
Returns
Next trial solution vector
Parameters
[in] rcondtol rcond less than this will cause the subspace to be shrunk due to linear dependence
[in] cabsmax maximum element of c greater than this will cause the subspace to be shrunk due to linear dependence
References c, madness::change_tree_state(), madness::check_linear_dependence(), madness::compressed, madness::copy(), madness::NonlinearSolverND< NDIM >::do_print, madness::Function< T, NDIM >::gaxpy(), madness::inner(), madness::KAIN(), madness::NonlinearSolverND< NDIM >::maxsub, madness::print(), madness::NonlinearSolverND< NDIM >::Q, madness::reconstructed, madness::NonlinearSolverND< NDIM >::rlist, madness::Function< T, NDIM >::size(), madness::FunctionFactory< T, NDIM >::treestate(), madness::Function< T, NDIM >::truncate(), madness::TT_FULL, u(), and madness::NonlinearSolverND< NDIM >::ulist.
Referenced by madness::CC2::iterate_pair(), and madness::MP2::solve_residual_equations().
Member Data Documentation
do_print
template<size_t NDIM> bool madness::NonlinearSolverND< NDIM >::do_print
Referenced by madness::CC2::iterate_pair(), madness::MP2::solve_residual_equations(), and madness::NonlinearSolverND< NDIM >::update().
maxsub
template<size_t NDIM> unsigned int madness::NonlinearSolverND< NDIM >::maxsub private
Maximum size of subspace dimension.
Referenced by madness::NonlinearSolverND< NDIM >::get_maxsub(), madness::NonlinearSolverND< NDIM >::set_maxsub(), and madness::NonlinearSolverND< NDIM >::update().
Q
template<size_t NDIM> real_tensor madness::NonlinearSolverND< NDIM >::Q private
Referenced by madness::NonlinearSolverND< NDIM >::update().
rlist
template<size_t NDIM> std::vector<Function<double,NDIM> > madness::NonlinearSolverND< NDIM >::rlist private
Referenced by madness::NonlinearSolverND< NDIM >::update().
ulist
template<size_t NDIM> std::vector<Function<double,NDIM> > madness::NonlinearSolverND< NDIM >::ulist private
Referenced by madness::NonlinearSolverND< NDIM >::update().
The documentation for this class was generated from the following file:
nonlinsol.h