MADNESS: madness::DNuclear< T, NDIM > Class Template Reference
madness::DNuclear< T, NDIM > Class Template Reference
derivative of the (regularized) nuclear potential wrt nuclear displacements
#include <SCFOperators.h>
Public Member Functions
DNuclear (World &world, const Nemo *nemo, const int iatom, const int iaxis)
DNuclear (World &world, const SCF *calc, const int iatom, const int iaxis)
DNuclear (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const int iatom, const int iaxis)
std::string info () const
print some information about this operator
T operator() (const Function< T, NDIM > &bra, const Function< T, NDIM > &ket) const
compute the matrix element <bra | op | ket>
Function< T, NDIM > operator() (const Function< T, NDIM > &ket) const
Tensor< T > operator() (const std::vector< Function< T, NDIM > > &vbra, const std::vector< Function< T, NDIM > > &vket) const
std::vector< Function< T, NDIM > > operator() (const std::vector< Function< T, NDIM > > &vket) const
Public Member Functions inherited from madness::SCFOperatorBase< T, NDIM >
SCFOperatorBase ()=default
SCFOperatorBase (std::shared_ptr< MacroTaskQ > taskq)
virtual ~SCFOperatorBase ()
virtual tensorT operator() (const vecfuncT &vbra, const vecfuncT &vket) const =0
compute the matrix <vbra | op | vket>
virtual vecfuncT operator() (const vecfuncT &vket) const =0
apply this operator on the argument vector of functions
Private Attributes
int iatom
index of the atom which is displaced
int iaxis
x,y,z component of the atom
std::shared_ptr< NuclearCorrelationFactor > ncf
World & world
Additional Inherited Members
Public Types inherited from madness::SCFOperatorBase< T, NDIM >
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Public Attributes inherited from madness::SCFOperatorBase< T, NDIM >
nlohmann::json statistics
std::shared_ptr< MacroTaskQ > taskq =0
Detailed Description
template<typename T, std::size_t NDIM>
class madness::DNuclear< T, NDIM >
derivative of the (regularized) nuclear potential wrt nuclear displacements
Constructor & Destructor Documentation
DNuclear() [1/3]
template<typename T , std::size_t NDIM> madness::DNuclear< T, NDIM >::DNuclear (World & world, const SCF * calc, const int iatom, const int iaxis)
References madness::SCF::molecule, madness::SCF::potentialmanager, and madness::DNuclear< T, NDIM >::world.
DNuclear() [2/3]
template<typename T , std::size_t NDIM> madness::DNuclear< T, NDIM >::DNuclear (World & world, const Nemo * nemo, const int iatom, const int iaxis)
References madness::NemoBase::ncf.
DNuclear() [3/3]
template<typename T , std::size_t NDIM> madness::DNuclear< T, NDIM >::DNuclear (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const int iatom, const int iaxis) inline
Member Function Documentation
info()
template<typename T , std::size_t NDIM> std::string madness::DNuclear< T, NDIM >::info () const inline virtual
print some information about this operator
Implements madness::SCFOperatorBase< T, NDIM >.
operator()() [1/4]
template<typename T , std::size_t NDIM> T madness::DNuclear< T, NDIM >::operator() (const Function< T, NDIM > & bra, const Function< T, NDIM > & ket) const inline virtual
compute the matrix element <bra | op | ket>
Parameters
bra bra state
ket ket state
Returns
the matrix element <bra | op | ket>
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::inner().
operator()() [2/4]
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::DNuclear< T, NDIM >::operator() (const Function< T, NDIM > & ket) const inline virtual
apply this operator on the argument function
Parameters
ket the argument function
Returns
op(ket)
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::DNuclear< T, NDIM >::operator()().
Referenced by madness::DNuclear< T, NDIM >::operator()(), and madness::DNuclear< T, NDIM >::operator()().
operator()() [3/4]
template<typename T , std::size_t NDIM> Tensor< T > madness::DNuclear< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > & vbra, const std::vector< Function< T, NDIM > > & vket) const inline
References madness::matrix_inner(), madness::DNuclear< T, NDIM >::operator()(), and madness::DNuclear< T, NDIM >::world.
operator()() [4/4]
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::DNuclear< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > & vket) const
References madness::apply(), madness::FunctionDefaults< NDIM >::get_thresh(), gradop, madness::mul(), NDIM, madness::NuclearCorrelationFactor::None, madness::reconstruct(), madness::sub(), madness::Function< T, NDIM >::thresh(), and madness::truncate().
Member Data Documentation
iatom
template<typename T , std::size_t NDIM> int madness::DNuclear< T, NDIM >::iatom private
index of the atom which is displaced
iaxis
template<typename T , std::size_t NDIM> int madness::DNuclear< T, NDIM >::iaxis private
x,y,z component of the atom
ncf
template<typename T , std::size_t NDIM> std::shared_ptr<NuclearCorrelationFactor> madness::DNuclear< T, NDIM >::ncf private
world
template<typename T , std::size_t NDIM> World& madness::DNuclear< T, NDIM >::world private
Referenced by madness::DNuclear< T, NDIM >::DNuclear(), and madness::DNuclear< T, NDIM >::operator()().
The documentation for this class was generated from the following files:
SCFOperators.h
SCFOperators.cc