MADNESS: MySteepestDescent Class Reference
MySteepestDescent Class Reference
Public Member Functions
MySteepestDescent (const std::shared_ptr< OptimizationTargetInterface > &target, double tol=1e-6, double value_precision=1e-12, double gradient_precision=1e-12)
virtual ~MySteepestDescent ()
bool check_positive (tensorT &x)
bool converged () const
double gradient_norm () const
bool optimize (Tensor< double > &x)
double value () const
Public Member Functions inherited from madness::OptimizerInterface
virtual ~OptimizerInterface ()
Private Attributes
double f
double gnorm
std::shared_ptr< OptimizationTargetInterface > target
const double tol
Constructor & Destructor Documentation
MySteepestDescent()
MySteepestDescent::MySteepestDescent (const std::shared_ptr< OptimizationTargetInterface > & target, double tol = 1e-6, double value_precision = 1e-12, double gradient_precision = 1e-12) inline
References target.
~MySteepestDescent()
virtual MySteepestDescent::~MySteepestDescent () inline virtual
Member Function Documentation
check_positive()
bool MySteepestDescent::check_positive (tensorT & x) inline
References e(), madness::Tensor< T >::end(), and madness::Tensor< T >::unary_iterator().
Referenced by optimize().
converged()
bool MySteepestDescent::converged () const inline virtual
Implements madness::OptimizerInterface.
References gnorm, and tol.
Referenced by optimize().
gradient_norm()
double MySteepestDescent::gradient_norm () const inline virtual
Implements madness::OptimizerInterface.
References gnorm.
optimize()
bool MySteepestDescent::optimize (Tensor< double > & x) inline virtual
Implements madness::OptimizerInterface.
References check_positive(), converged(), f, madness::g, madness::Tensor< T >::gaxpy(), gnorm, madness::Tensor< T >::normf(), print(), and target.
Referenced by main().
value()
double MySteepestDescent::value () const inline virtual
Implements madness::OptimizerInterface.
References f.
Member Data Documentation
f
double MySteepestDescent::f private
Referenced by optimize(), and value().
gnorm
double MySteepestDescent::gnorm private
Referenced by converged(), gradient_norm(), and optimize().
target
std::shared_ptr<OptimizationTargetInterface> MySteepestDescent::target private
Referenced by MySteepestDescent(), and optimize().
tol
const double MySteepestDescent::tol private
Referenced by converged().
The documentation for this class was generated from the following file:
mcpfit.cc