MADNESS: madness::Batch_1D Class Reference
madness::Batch_1D Class Reference
#include <macrotaskpartitioner.h>
Public Member Functions
Batch_1D ()
Batch_1D (const long &begin, const long &end)
Batch_1D (const Slice &s)
template<typename tupleT , std::size_t appearance>
tupleT copy_batch (const tupleT &arg) const
select the relevant vector elements from the argument tuple
template<typename vecT >
vecT copy_batch (const vecT v) const
given vector v, return those vector elements inside this batch
template<typename vecT >
vecT insert_batch (vecT v, const vecT &v_batch) const
given vector v, copy vector elements of v_batch into vector
bool is_full_size () const
bool operator== (const Batch_1D &other) const
long size () const
Public Attributes
long begin =0
long end =-1
first and first past last index [begin,end)
Friends
class MacroTaskPartitioner
std::ostream & operator<< (std::ostream &os, const Batch_1D &batch)
Constructor & Destructor Documentation
Batch_1D() [1/3]
madness::Batch_1D::Batch_1D () inline
Batch_1D() [2/3]
madness::Batch_1D::Batch_1D (const Slice & s) inline
References MADNESS_CHECK.
Batch_1D() [3/3]
madness::Batch_1D::Batch_1D (const long & begin, const long & end) inline
Member Function Documentation
copy_batch() [1/2]
template<typename tupleT , std::size_t appearance> tupleT madness::Batch_1D::copy_batch (const tupleT & arg) const inline
select the relevant vector elements from the argument tuple
References madness::arg(), copy_batch(), is_full_size(), MADNESS_CHECK, and v.
Referenced by copy_batch(), and test_batch_1D().
copy_batch() [2/2]
template<typename vecT > vecT madness::Batch_1D::copy_batch (const vecT v) const inline
given vector v, return those vector elements inside this batch
References begin, end, and v.
insert_batch()
template<typename vecT > vecT madness::Batch_1D::insert_batch (vecT v, const vecT & v_batch) const inline
given vector v, copy vector elements of v_batch into vector
References begin, and v.
Referenced by madness::Batch::insert_result_batch(), and test_batch_1D().
is_full_size()
bool madness::Batch_1D::is_full_size () const inline
References begin, and end.
Referenced by copy_batch(), and test_batch_1D().
operator==()
bool madness::Batch_1D::operator== (const Batch_1D & other) const inline
References begin, and end.
size()
long madness::Batch_1D::size () const inline
References begin, and end.
Referenced by madness::MP3::MacroTaskMP3::operator()(), madness::Batch::size_of_input(), and test_batch_1D().
Friends And Related Symbol Documentation
MacroTaskPartitioner
friend class MacroTaskPartitioner friend
operator<<
std::ostream & operator<< (std::ostream & os, const Batch_1D & batch) friend
Member Data Documentation
begin
long madness::Batch_1D::begin =0
Referenced by copy_batch(), insert_batch(), is_full_size(), madness::MP3::MacroTaskMP3::operator()(), operator==(), and size().
end
long madness::Batch_1D::end =-1
first and first past last index [begin,end)
Referenced by copy_batch(), is_full_size(), operator==(), and size().
The documentation for this class was generated from the following file:
macrotaskpartitioner.h