MADNESS: madness::Future< void > Class Reference
madness::Future< void > Class Reference
Specialization of Future<void> for internal convenience. This does nothing useful!
#include <future.h>
Public Types
typedef RemoteReference< FutureImpl< void > > remote_refT
Public Member Functions
Future ()
Future (const archive::BufferInputArchive &input_arch)
Construct from an input archive.
Future (const RemoteReference< FutureImpl< void > > &remote_ref)
Future< void > & operator= (const Future< void > &other)
Assignment operator.
Static Public Member Functions
static bool probe ()
Check if this future has been assigned.
static remote_refT remote_ref (World &world)
static void set ()
Set the future.
static void set (const Future< void > &f)
Set the future from another void future.
Static Public Attributes
static const Future< void > value = Future<void>()
Detailed Description
Specialization of Future<void> for internal convenience. This does nothing useful!
Member Typedef Documentation
remote_refT
typedef RemoteReference< FutureImpl<void> > madness::Future< void >::remote_refT
Todo:
Brief description needed.
Constructor & Destructor Documentation
Future() [1/3]
madness::Future< void >::Future () inline
Future() [2/3]
madness::Future< void >::Future (const RemoteReference< FutureImpl< void > > & remote_ref) inline
Todo:
Brief description needed.
Todo:
Description needed.
Parameters
[in] remote_ref Description needed.
Future() [3/3]
madness::Future< void >::Future (const archive::BufferInputArchive & input_arch) inline
Construct from an input archive.
Parameters
[in] input_arch The input archive.
Member Function Documentation
operator=()
Future< void > & madness::Future< void >::operator= (const Future< void > & other) inline
Assignment operator.
Parameters
[in] other The future to copy.
Returns
This.
probe()
static bool madness::Future< void >::probe () inline static
Check if this future has been assigned.
Returns
True (in this specialization).
remote_ref()
static remote_refT madness::Future< void >::remote_ref (World & world) inline static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in,out] world Description needed.
Returns
Description needed.
set() [1/2]
static void madness::Future< void >::set () inline static
Set the future.
In this specialization, do nothing.
set() [2/2]
static void madness::Future< void >::set (const Future< void > & f) inline static
Set the future from another void future.
In this specialization, do nothing.
Parameters
[in] f The other future.
Member Data Documentation
value
const Future< void > madness::Future< void >::value = Future<void>() static
Todo:
Brief description needed.
Referenced by madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldTaskQueue::add(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::send(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), madness::WorldObject< Derived >::task(), and madness::WorldObject< Derived >::task().
The documentation for this class was generated from the following files:
future.h
future.cc