MADNESS: madness::AdhocNuclearCorrelationFactor Class Reference
madness::AdhocNuclearCorrelationFactor Class Reference
this ncf has no information about itself, only U2 and U1 assigned
#include <correlationfactor.h>
Public Member Functions
AdhocNuclearCorrelationFactor (World &world, const real_function_3d U2, const std::vector< real_function_3d > &U1)
ctor
corrfactype type () const
Public Member Functions inherited from madness::NuclearCorrelationFactor
NuclearCorrelationFactor (World &world, const Molecule &mol)
ctor
virtual ~NuclearCorrelationFactor ()
virtual destructor
virtual real_function_3d apply_U (const real_function_3d &rhs) const
apply the regularized potential U_nuc on a given function rhs
coord_3d dsmoothed_unitvec (const coord_3d &xyz, const int axis, double smoothing=0.0) const
derivative of smoothed unit vector wrt the electronic coordinate
virtual real_function_3d function () const
return the nuclear correlation factor
void initialize (const double vtol1)
initialize the regularized potentials U1 and U2
virtual real_function_3d inverse () const
return the inverse nuclear correlation factor
coord_3d smoothed_unitvec (const coord_3d &xyz, double smoothing=0.0) const
smoothed unit vector for the computation of the U1 potential
virtual real_function_3d square () const
return the square of the nuclear correlation factor
virtual real_function_3d square_times_V_derivative (const int iatom, const int axis) const
virtual const real_function_3d U1 (const int axis) const
return the U1 term of the correlation function
std::vector< real_function_3d > U1vec () const
return the U1 functions in a vector
virtual const real_function_3d U2 () const
return the U2 term of the correlation function
virtual double U2X_spherical (const double &r, const double &Z, const double &rcut) const
derivative of the U2 potential wrt nuclear coordinate X (spherical part)
Private Member Functions
double S (const double &r, const double &Z) const
the nuclear correlation factor
coord_3d Sp (const coord_3d &vr1A, const double &Z) const
radial part first derivative of the nuclear correlation factor
double Spp_div_S (const double &r, const double &Z) const
second derivative of the nuclear correlation factor
double Sr_div_S (const double &r, const double &Z) const
double Srr_div_S (const double &r, const double &Z) const
double Srrr_div_S (const double &r, const double &Z) const
Additional Inherited Members
Public Types inherited from madness::NuclearCorrelationFactor
enum corrfactype {
None , GradientalGaussSlater , GaussSlater , LinearSlater ,
Polynomial , Slater , poly4erfc , Two ,
Adhoc
}
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
Protected Attributes inherited from madness::NuclearCorrelationFactor
std::vector< real_function_3d > U1_function
the three components of the U1 potential
real_function_3d U2_function
the purely local U2 potential, having absorbed the nuclear pot V_nuc
Detailed Description
this ncf has no information about itself, only U2 and U1 assigned
Constructor & Destructor Documentation
AdhocNuclearCorrelationFactor()
madness::AdhocNuclearCorrelationFactor::AdhocNuclearCorrelationFactor (World & world, const real_function_3d U2, const std::vector< real_function_3d > & U1) inline
ctor
Parameters
[in] world the world
[in] mol molecule with the sites of the nuclei
References madness::print(), madness::World::rank(), madness::NuclearCorrelationFactor::U1(), madness::NuclearCorrelationFactor::U1_function, madness::NuclearCorrelationFactor::U2(), madness::NuclearCorrelationFactor::U2_function, and madness::NuclearCorrelationFactor::world.
Member Function Documentation
S()
double madness::AdhocNuclearCorrelationFactor::S (const double & r, const double & Z) const inline private virtual
the nuclear correlation factor
Implements madness::NuclearCorrelationFactor.
References MADNESS_EXCEPTION.
Sp()
coord_3d madness::AdhocNuclearCorrelationFactor::Sp (const coord_3d & vr1A, const double & Z) const inline private virtual
radial part first derivative of the nuclear correlation factor
Implements madness::NuclearCorrelationFactor.
References MADNESS_EXCEPTION.
Spp_div_S()
double madness::AdhocNuclearCorrelationFactor::Spp_div_S (const double & r, const double & Z) const inline private virtual
second derivative of the nuclear correlation factor
Implements madness::NuclearCorrelationFactor.
References MADNESS_EXCEPTION.
Sr_div_S()
double madness::AdhocNuclearCorrelationFactor::Sr_div_S (const double & r, const double & Z) const inline private virtual
first derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implements madness::NuclearCorrelationFactor.
References MADNESS_EXCEPTION.
Srr_div_S()
double madness::AdhocNuclearCorrelationFactor::Srr_div_S (const double & r, const double & Z) const inline private virtual
second derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implements madness::NuclearCorrelationFactor.
References MADNESS_EXCEPTION.
Srrr_div_S()
double madness::AdhocNuclearCorrelationFactor::Srrr_div_S (const double & r, const double & Z) const inline private virtual
third derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implements madness::NuclearCorrelationFactor.
References MADNESS_EXCEPTION.
type()
corrfactype madness::AdhocNuclearCorrelationFactor::type () const inline virtual
Implements madness::NuclearCorrelationFactor.
References madness::NuclearCorrelationFactor::Adhoc.
The documentation for this class was generated from the following file:
correlationfactor.h