MADNESS: madness::Exchange< T, NDIM > Class Template Reference
madness::Exchange< T, NDIM > Class Template Reference
#include <SCFOperators.h>
Classes
class ExchangeImpl
Public Types
enum ExchangeAlgorithm {
small_memory , large_memory , multiworld_efficient , multiworld_efficient_row ,
fetch_compute
}
typedef Function< T, NDIM > functionT
using implT = std::shared_ptr< ExchangeImpl >
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Public Types inherited from madness::SCFOperatorBase< T, NDIM >
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Public Member Functions
Exchange (World &world, const double lo, const double thresh=FunctionDefaults< NDIM >::get_thresh())
ctor
Exchange (World &world, const Nemo *nemo, const int ispin)
ctor with a nemo calculation
Exchange (World &world, const SCF *calc, const int ispin)
ctor with a conventional calculation
std::string info () const
print some information about this operator
bool is_symmetric () const
T operator() (const Function< T, NDIM > &bra, const Function< T, NDIM > &ket) const
compute the matrix element <bra | K | ket>
Function< T, NDIM > operator() (const Function< T, NDIM > &ket) const
Tensor< T > operator() (const vecfuncT &vbra, const vecfuncT &vket) const
compute the matrix < vbra | K | vket >
vecfuncT operator() (const vecfuncT &vket) const
apply the exchange operator on a vector of functions
Exchange & set_algorithm (const ExchangeAlgorithm &alg)
Exchange & set_bra_and_ket (const vecfuncT &bra, const vecfuncT &ket)
Exchange & set_macro_task_info (const MacroTaskInfo &info)
how the cloud will handle the data
Exchange & set_printlevel (const long &level)
Exchange & set_symmetric (const bool flag)
Exchange & set_taskq (std::shared_ptr< MacroTaskQ > taskq1)
Public Member Functions inherited from madness::SCFOperatorBase< T, NDIM >
SCFOperatorBase ()=default
SCFOperatorBase (std::shared_ptr< MacroTaskQ > taskq)
virtual ~SCFOperatorBase ()
Static Public Member Functions
static ExchangeAlgorithm string2algorithm (const std::string &alg_string)
static std::string to_string (const ExchangeAlgorithm alg)
Public Attributes
MacroTaskInfo macro_task_info = MacroTaskInfo::preset("default")
Public Attributes inherited from madness::SCFOperatorBase< T, NDIM >
nlohmann::json statistics
std::shared_ptr< MacroTaskQ > taskq =0
Private Attributes
implT impl
Friends
std::ostream & operator<< (std::ostream &os, const ExchangeAlgorithm &alg)
Member Typedef Documentation
functionT
template<typename T , std::size_t NDIM> typedef Function<T,NDIM> madness::Exchange< T, NDIM >::functionT
implT
template<typename T , std::size_t NDIM> using madness::Exchange< T, NDIM >::implT = std::shared_ptr<ExchangeImpl>
tensorT
template<typename T , std::size_t NDIM> typedef Tensor<T> madness::Exchange< T, NDIM >::tensorT
vecfuncT
template<typename T , std::size_t NDIM> typedef std::vector<functionT> madness::Exchange< T, NDIM >::vecfuncT
Member Enumeration Documentation
ExchangeAlgorithm
template<typename T , std::size_t NDIM> enum madness::Exchange::ExchangeAlgorithm
Enumerator
small_memory
large_memory
multiworld_efficient
multiworld_efficient_row
fetch_compute
Constructor & Destructor Documentation
Exchange() [1/3]
template<typename T , std::size_t NDIM> madness::Exchange< T, NDIM >::Exchange (World & world, const double lo, const double thresh = FunctionDefaults<NDIM>::get_thresh())
ctor
Exchange() [2/3]
template<typename T , std::size_t NDIM> madness::Exchange< T, NDIM >::Exchange (World & world, const SCF * calc, const int ispin)
ctor with a conventional calculation
Exchange() [3/3]
template<typename T , std::size_t NDIM> madness::Exchange< T, NDIM >::Exchange (World & world, const Nemo * nemo, const int ispin)
ctor with a nemo calculation
Member Function Documentation
info()
template<typename T , std::size_t NDIM> std::string madness::Exchange< T, NDIM >::info () const inline virtual
print some information about this operator
Implements madness::SCFOperatorBase< T, NDIM >.
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::set_macro_task_info().
is_symmetric()
template<typename T , std::size_t NDIM> bool madness::Exchange< T, NDIM >::is_symmetric () const
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_large_memory(), and madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_macrotask_efficient().
operator()() [1/4]
template<typename T , std::size_t NDIM> T madness::Exchange< T, NDIM >::operator() (const Function< T, NDIM > & bra, const Function< T, NDIM > & ket) const inline virtual
compute the matrix element <bra | K | ket>
Parameters
[in] bra real_function_3d, the bra state
[in] ket real_function_3d, the ket state
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::inner().
operator()() [2/4]
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::Exchange< T, NDIM >::operator() (const Function< T, NDIM > & ket) const inline virtual
apply this operator on the argument function
Parameters
ket the argument function
Returns
op(ket)
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::Exchange< T, NDIM >::operator()().
Referenced by madness::Exchange< T, NDIM >::operator()(), and madness::Exchange< T, NDIM >::operator()().
operator()() [3/4]
template<typename T , std::size_t NDIM> Tensor< T > madness::Exchange< T, NDIM >::operator() (const vecfuncT & vbra, const vecfuncT & vket) const inline virtual
compute the matrix < vbra | K | vket >
Parameters
[in] vbra vector of real_function_3d, the set of bra states
[in] vket vector of real_function_3d, the set of ket states
Returns
K_ij
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::matrix_inner(), and madness::Exchange< T, NDIM >::operator()().
operator()() [4/4]
template<typename T , std::size_t NDIM> vecfuncT madness::Exchange< T, NDIM >::operator() (const vecfuncT & vket) const virtual
apply the exchange operator on a vector of functions
note that only one spin is used (either alpha or beta orbitals)
Parameters
[in] vket the orbitals |i> that the operator is applied on
Returns
a vector of orbitals K| i>
Implements madness::SCFOperatorBase< T, NDIM >.
set_algorithm()
template<typename T , std::size_t NDIM> Exchange< T, NDIM > & madness::Exchange< T, NDIM >::set_algorithm (const ExchangeAlgorithm & alg)
References madness::Exchange< T, NDIM >::set_algorithm().
Referenced by madness::Nemo::compute_nemo_potentials(), make_k(), and madness::Exchange< T, NDIM >::set_algorithm().
set_bra_and_ket()
template<typename T , std::size_t NDIM> Exchange< T, NDIM > & madness::Exchange< T, NDIM >::set_bra_and_ket (const vecfuncT & bra, const vecfuncT & ket)
References MADNESS_CHECK.
Referenced by madness::OEP::compute_exchange_potential(), madness::Zcis::compute_potentials(), madness::Nemo::make_cphf_constant_term(), make_k(), and madness::Nemo::solve_cphf().
set_macro_task_info()
template<typename T , std::size_t NDIM> Exchange< T, NDIM > & madness::Exchange< T, NDIM >::set_macro_task_info (const MacroTaskInfo & info)
how the cloud will handle the data
References madness::Exchange< T, NDIM >::set_macro_task_info().
Referenced by madness::Exchange< T, NDIM >::set_macro_task_info().
set_printlevel()
template<typename T , std::size_t NDIM> Exchange< T, NDIM > & madness::Exchange< T, NDIM >::set_printlevel (const long & level)
References madness::Exchange< T, NDIM >::set_printlevel().
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_macrotask_efficient(), and madness::Exchange< T, NDIM >::set_printlevel().
set_symmetric()
template<typename T , std::size_t NDIM> Exchange< T, NDIM > & madness::Exchange< T, NDIM >::set_symmetric (const bool flag)
Referenced by madness::Nemo::compute_nemo_potentials(), madness::Nemo::make_fock_operator(), and madness::Nemo::solve_cphf().
set_taskq()
template<typename T , std::size_t NDIM> Exchange & madness::Exchange< T, NDIM >::set_taskq (std::shared_ptr< MacroTaskQ > taskq1) inline
References madness::SCFOperatorBase< T, NDIM >::taskq.
Referenced by madness::Nemo::compute_nemo_potentials().
string2algorithm()
template<typename T , std::size_t NDIM> static ExchangeAlgorithm madness::Exchange< T, NDIM >::string2algorithm (const std::string & alg_string) inline static
References madness::Exchange< T, NDIM >::fetch_compute, madness::Exchange< T, NDIM >::large_memory, MADNESS_EXCEPTION, madness::Exchange< T, NDIM >::multiworld_efficient, madness::Exchange< T, NDIM >::multiworld_efficient_row, madness::Exchange< T, NDIM >::small_memory, and madness::commandlineparser::tolower().
Referenced by main().
to_string()
template<typename T , std::size_t NDIM> static std::string madness::Exchange< T, NDIM >::to_string (const ExchangeAlgorithm alg) inline static
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::gather_statistics().
Friends And Related Symbol Documentation
operator<<
template<typename T , std::size_t NDIM> std::ostream & operator<< (std::ostream & os, const ExchangeAlgorithm & alg) friend
Member Data Documentation
impl
template<typename T , std::size_t NDIM> implT madness::Exchange< T, NDIM >::impl private
macro_task_info
template<typename T , std::size_t NDIM> MacroTaskInfo madness::Exchange< T, NDIM >::macro_task_info = MacroTaskInfo::preset("default")
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::gather_statistics(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_macrotask_efficient(), and madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::set_macro_task_info().
The documentation for this class was generated from the following files:
SCFOperators.h
SCFOperators.cc