MADNESS: Spinor Class Reference
Spinor Class Reference
defines a 4-spinor
Public Member Functions
Spinor ()
Spinor (const vector_complex_function_3d &components)
Spinor (World &world)
Spinor operator+ (const Spinor &other) const
Spinor & operator+= (const Spinor &other)
Spinor operator- (const Spinor &other) const
Spinor & operator-= (const Spinor &other)
void plot (const std::string filename) const
void print_norms (std::string text)
Spinor & truncate ()
World & world () const
Public Attributes
vector_complex_function_3d components
Friends
double_complex inner (const Spinor &bra, const Spinor &ket)
Detailed Description
defines a 4-spinor
Constructor & Destructor Documentation
Spinor() [1/3]
Spinor::Spinor () inline
References components.
Spinor() [2/3]
Spinor::Spinor (World & world) inline
References components, and world().
Spinor() [3/3]
Spinor::Spinor (const vector_complex_function_3d & components) inline
Member Function Documentation
operator+()
Spinor Spinor::operator+ (const Spinor & other) const inline
References components, copy(), and world().
operator+=()
Spinor & Spinor::operator+= (const Spinor & other) inline
References components.
operator-()
Spinor Spinor::operator- (const Spinor & other) const inline
References components, copy(), and world().
operator-=()
Spinor & Spinor::operator-= (const Spinor & other) inline
References components.
plot()
void Spinor::plot (const std::string filename) const inline
References components, madness::filename, madness::imag(), madness::plot_plane(), madness::real(), and world().
print_norms()
void Spinor::print_norms (std::string text) inline
References components, madness::imag(), k, madness::norm2s(), madness::print(), madness::real(), and world().
Referenced by eigenvector_test().
truncate()
Spinor & Spinor::truncate () inline
References clight, components, thresh, and truncate().
Referenced by apply_bsh(), MatrixOperator::operator()(), and truncate().
world()
World & Spinor::world () const inline
References components.
Referenced by Spinor(), apply_bsh(), copy(), Ansatz0::make_bra(), AnsatzBase::normalize(), operator+(), operator-(), plot(), print_norms(), and show_norms().
Friends And Related Symbol Documentation
inner
double_complex inner (const Spinor & bra, const Spinor & ket) friend
Member Data Documentation
components
vector_complex_function_3d Spinor::components
Referenced by Spinor(), Spinor(), copy(), eigenvector_test(), ExactSpinor::get_spinor(), Ansatz0::make_bra(), Ansatz0::make_guess(), AnsatzBase::normalize(), MatrixOperator::operator()(), operator+(), operator+=(), operator-(), operator-=(), plot(), print_norms(), schrodinger2dirac(), show_norms(), truncate(), and world().
The documentation for this class was generated from the following file:
dirac-hatom.cc