MADNESS: madness::WorldAmInterface::SendReq Class Reference
madness::WorldAmInterface::SendReq Class Reference
Public Member Functions
SendReq ()
SendReq (AmArg *b, const RMI::Request &r)
~SendReq ()
void set (AmArg *b, const RMI::Request &r)
bool TestAndFree ()
Public Member Functions inherited from madness::Mutex
Mutex (int junk=0)
Make and initialize a mutex ... initial state is unlocked.
virtual ~Mutex ()
void lock () const
Acquire the mutex waiting if necessary.
pthread_mutex_t * ptr () const
Return a pointer to the pthread mutex for use by a condition variable.
bool try_lock () const
Try to acquire the mutex ... return true on success, false on failure.
void unlock () const
Free a mutex owned by this thread.
Public Member Functions inherited from madness::RMISendReq
virtual ~RMISendReq ()
Private Member Functions
void free ()
Private Attributes
AmArg * buf
RMI::Request req
Constructor & Destructor Documentation
SendReq() [1/2]
madness::WorldAmInterface::SendReq::SendReq () inline
SendReq() [2/2]
madness::WorldAmInterface::SendReq::SendReq (AmArg * b, const RMI::Request & r) inline
~SendReq()
madness::WorldAmInterface::SendReq::~SendReq () inline
References free().
Member Function Documentation
free()
void madness::WorldAmInterface::SendReq::free () inline private
References buf, and madness::free_am_arg().
Referenced by ~SendReq(), and TestAndFree().
set()
void madness::WorldAmInterface::SendReq::set (AmArg * b, const RMI::Request & r) inline
References b, buf, and req.
TestAndFree()
bool madness::WorldAmInterface::SendReq::TestAndFree () inline virtual
Implements madness::RMISendReq.
References buf, free(), ok(), req, and SafeMPI::Request::Test().
Member Data Documentation
buf
AmArg* madness::WorldAmInterface::SendReq::buf private
Referenced by free(), set(), and TestAndFree().
req
RMI::Request madness::WorldAmInterface::SendReq::req private
Referenced by set(), and TestAndFree().
The documentation for this class was generated from the following file:
worldam.h