MADNESS: madness::detail::StackBase< T, isPod > Class Template Reference
madness::detail::StackBase< T, isPod > Class Template Reference
Base class for Stack which implements basic memory operations for non-POD objects.
#include <stack.h>
Static Protected Member Functions
static void destroy (T *first, T *last)
Destroy a range of non-POD objects.
static void destroy (T *ptr)
Destroy a non-POD object.
static void uninitialized_copy (T *first, T *last, T *dest)
Copy a range of POD objects.
static void uninitialized_move (T *first, T *last, T *dest)
Move a range of POD objects.
Detailed Description
template<typename T, bool isPod>
class madness::detail::StackBase< T, isPod >
Base class for Stack which implements basic memory operations for non-POD objects.
Template Parameters
T The data type of the stack.
isPod An auxiliary template parameter to select the POD/non-POD versions of this class.
Member Function Documentation
destroy() [1/2]
template<typename T , bool isPod> static void madness::detail::StackBase< T, isPod >::destroy (T * first, T * last) inline static protected
Destroy a range of non-POD objects.
Parameters
[in] first The beginning of the range to be destroyed.
[in] last The end of the range to be destroyed.
References madness::detail::StackBase< T, isPod >::destroy().
destroy() [2/2]
template<typename T , bool isPod> static void madness::detail::StackBase< T, isPod >::destroy (T * ptr) inline static protected
Destroy a non-POD object.
Parameters
[in] ptr A pointer to the object to be destroyed.
Referenced by madness::detail::StackBase< T, isPod >::destroy(), and madness::detail::StackBase< T, isPod >::uninitialized_move().
uninitialized_copy()
template<typename T , bool isPod> static void madness::detail::StackBase< T, isPod >::uninitialized_copy (T * first, T * last, T * dest) inline static protected
Copy a range of POD objects.
Parameters
[in] first The beginning of the range to be copied.
[in] last The end of the range to be copied.
[in] dest Pointer to the uninitialized memory range.
uninitialized_move()
template<typename T , bool isPod> static void madness::detail::StackBase< T, isPod >::uninitialized_move (T * first, T * last, T * dest) inline static protected
Move a range of POD objects.
Parameters
[in] first The beginning of the range to be moved.
[in] last The end of the range to be moved.
[in] dest Pointer to the uninitialized memory range.
References madness::detail::StackBase< T, isPod >::destroy(), and T().
The documentation for this class was generated from the following file:
stack.h