MADNESS: madness::PCM Class Reference
madness::PCM Class Reference
interface class to the PCMSolver library
#include <pcm.h>
Public Member Functions
PCM ()=default
default ctor
PCM (World &world, const Molecule &mol, const std::string pcm_data, const bool verbose)
constructor for the interface to PCM
double compute_pcm_energy () const
compute the PCM energy based on the most recent call of compute_pcm_potential
real_function_3d compute_pcm_potential (const real_function_3d &coulomb_potential, const bool dynamic=false) const
compute the potential induced by the surrounding solvent
Private Member Functions
Tensor< double > nuclear_mep (int nr_nuclei, const Tensor< double > &charges, const Tensor< double > &coordinates, const int grid_size, const Tensor< double > &grid) const
compute the molecular electrostatic potential from the nuclei
Private Attributes
std::string asc_lbl
file name for the total (nuclear + electronic) apparent surface charge
Tensor< double > charges
nuclear charges of the molecule, needs to be memory controlled by the PCM class
Tensor< double > coordinates
molecular coordinates, needs to be memory controlled by the PCM class
std::string mep_lbl
file name for the total (nuclear + electronic) molecular electronic potential
Tensor< int > symmetry_info
symmetry info for PCM, needs to be memory controlled by the PCM class
Detailed Description
interface class to the PCMSolver library
PCMSolver, an API for the Polarizable Continuum Model electrostatic problem. Main authors: R. Di Remigio, L. Frediani, K. Mozgawa
Constructor & Destructor Documentation
PCM() [1/2]
madness::PCM::PCM () default
default ctor
PCM() [2/2]
madness::PCM::PCM (World & world, const Molecule & mol, const std::string pcm_data, const bool verbose)
constructor for the interface to PCM
Parameters
[in] world the world
[in] mol the molecule (coordinates and charges of the nuclei)
[in] pcm_data pcm input data as read from the input file
[in] verbose print the PCM header
References MADNESS_EXCEPTION.
Member Function Documentation
compute_pcm_energy()
double madness::PCM::compute_pcm_energy () const
compute the PCM energy based on the most recent call of compute_pcm_potential
References MADNESS_EXCEPTION.
Referenced by madness::Nemo::compute_energy_regularized(), and madness::SCF::solve().
compute_pcm_potential()
real_function_3d madness::PCM::compute_pcm_potential (const real_function_3d & coulomb_potential, const bool dynamic = false) const
compute the potential induced by the surrounding solvent
Parameters
[in] coulomb_potential the (positive) potential caused by the electron density
[in] dynamic compute the contribution to a response kernel
Returns
the pcm potential with correct sign: J - K + V_nuc + V_pcm
References MADNESS_EXCEPTION.
Referenced by madness::Nemo::compute_nemo_potentials(), madness::Nemo::make_fock_operator(), and madness::SCF::solve().
nuclear_mep()
Tensor< double > madness::PCM::nuclear_mep (int nr_nuclei, const Tensor< double > & charges, const Tensor< double > & coordinates, const int grid_size, const Tensor< double > & grid) const private
compute the molecular electrostatic potential from the nuclei
References MADNESS_EXCEPTION.
Member Data Documentation
asc_lbl
std::string madness::PCM::asc_lbl private
file name for the total (nuclear + electronic) apparent surface charge
charges
Tensor<double> madness::PCM::charges private
nuclear charges of the molecule, needs to be memory controlled by the PCM class
coordinates
Tensor<double> madness::PCM::coordinates private
molecular coordinates, needs to be memory controlled by the PCM class
mep_lbl
std::string madness::PCM::mep_lbl private
file name for the total (nuclear + electronic) molecular electronic potential
symmetry_info
Tensor<int> madness::PCM::symmetry_info private
symmetry info for PCM, needs to be memory controlled by the PCM class
The documentation for this class was generated from the following files:
pcm.h
pcm.cc