MADNESS: madness::MacroTaskSinglesPotentialEx Class Reference
madness::MacroTaskSinglesPotentialEx Class Reference
#include <CCStructures.h>
Public Types
typedef std::tuple< const std::vector< int > &, const CC_vecfunction &, const std::vector< CCPair > &, const CC_vecfunction &, const std::vector< CCPair > &, const int &, const Info & > argtupleT
using resultT = std::tuple< std::vector< real_function_3d >, std::vector< real_function_3d > >
Public Member Functions
MacroTaskSinglesPotentialEx ()
resultT allocator (World &world, const argtupleT &argtuple) const
resultT operator() (const std::vector< int > &result_index, const CC_vecfunction &singles_gs, const std::vector< CCPair > &doubles_gs, const CC_vecfunction &singles_ex, const std::vector< CCPair > &doubles_ex, const int &name, const Info &info)
convenience function
Public Member Functions inherited from madness::MacroTaskOperationBase
MacroTaskOperationBase ()
Public Attributes
std::string basename ="SinglesPotentialEx"
Public Attributes inherited from madness::MacroTaskOperationBase
Batch batch
std::string name ="unknown_task"
std::shared_ptr< MacroTaskPartitioner > partitioner =0
Member Typedef Documentation
argtupleT
typedef std::tuple< const std::vector<int>&, const CC_vecfunction&, const std::vector<CCPair>&, const CC_vecfunction&, const std::vector<CCPair>&, const int&, const Info& > madness::MacroTaskSinglesPotentialEx::argtupleT
resultT
using madness::MacroTaskSinglesPotentialEx::resultT = std::tuple<std::vector<real_function_3d>,std::vector<real_function_3d> >
Constructor & Destructor Documentation
MacroTaskSinglesPotentialEx()
madness::MacroTaskSinglesPotentialEx::MacroTaskSinglesPotentialEx () inline
References madness::MacroTaskOperationBase::name, and madness::MacroTaskOperationBase::partitioner.
Member Function Documentation
allocator()
resultT madness::MacroTaskSinglesPotentialEx::allocator (World & world, const argtupleT & argtuple) const inline
References madness::assign_name(), basename, madness::MacroTaskOperationBase::name, and madness::nonlinear_vector_solver().
operator()()
std::tuple< std::vector< real_function_3d >, std::vector< real_function_3d > > madness::MacroTaskSinglesPotentialEx::operator() (const std::vector< int > & result_index, const CC_vecfunction & singles_gs, const std::vector< CCPair > & doubles_gs, const CC_vecfunction & singles_ex, const std::vector< CCPair > & doubles_ex, const int & name, const Info & info)
convenience function
References madness::CCParameters::freeze(), madness::Info::mo_ket, madness::MacroTaskOperationBase::name, madness::nonlinear_vector_solver(), madness::Info::parameters, madness::World::size(), madness::PairVectorMap::triangular_map(), and madness::Pairs< T >::vector2pairs().
Member Data Documentation
basename
std::string madness::MacroTaskSinglesPotentialEx::basename ="SinglesPotentialEx"
Referenced by allocator().
The documentation for this class was generated from the following files:
CCStructures.h
CCStructures.cc