MADNESS: madness::Hash_private::bin< keyT, valueT > Class Template Reference
madness::Hash_private::bin< keyT, valueT > Class Template Reference
#include <worldhashmap.h>
Public Member Functions
bin ()
~bin ()
void clear ()
bool del (const keyT &key, int lockmode)
entryT * find (const keyT &key, const int lockmode) const
std::pair< entryT *, bool > insert (const datumT &datum, int lockmode)
std::size_t size () const
Public Attributes
int ninbin
entryT * p
Private Types
typedef std::pair< const keyT, valueT > datumT
typedef entry< keyT, valueT > entryT
Private Member Functions
entryT * match (const keyT &key) const
Private Member Functions inherited from madness::Spinlock
Spinlock (int junk=0)
Make and initialize a spinlock ... initial state is unlocked.
virtual ~Spinlock ()
void lock () const
Acquire the spinlock waiting if necessary.
bool try_lock () const
Try to acquire the spinlock ... return true on success, false on failure.
void unlock () const
Free a spinlock owned by this thread.
Member Typedef Documentation
datumT
template<class keyT , class valueT > typedef std::pair<const keyT, valueT> madness::Hash_private::bin< keyT, valueT >::datumT private
entryT
template<class keyT , class valueT > typedef entry<keyT,valueT> madness::Hash_private::bin< keyT, valueT >::entryT private
Constructor & Destructor Documentation
bin()
template<class keyT , class valueT > madness::Hash_private::bin< keyT, valueT >::bin () inline
~bin()
template<class keyT , class valueT > madness::Hash_private::bin< keyT, valueT >::~bin () inline
References madness::Hash_private::bin< keyT, valueT >::clear().
Member Function Documentation
clear()
template<class keyT , class valueT > void madness::Hash_private::bin< keyT, valueT >::clear () inline
References madness::Spinlock::lock(), MADNESS_ASSERT, madness::Hash_private::bin< keyT, valueT >::ninbin, madness::Hash_private::bin< keyT, valueT >::p, and madness::Spinlock::unlock().
Referenced by madness::Hash_private::bin< keyT, valueT >::~bin().
del()
template<class keyT , class valueT > bool madness::Hash_private::bin< keyT, valueT >::del (const keyT & key, int lockmode) inline
References madness::Spinlock::lock(), madness::Hash_private::bin< keyT, valueT >::ninbin, madness::Hash_private::bin< keyT, valueT >::p, status, and madness::Spinlock::unlock().
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase().
find()
template<class keyT , class valueT > entryT * madness::Hash_private::bin< keyT, valueT >::find (const keyT & key, const int lockmode) const inline
References madness::Spinlock::lock(), madness::Hash_private::bin< keyT, valueT >::match(), madness::Spinlock::unlock(), and madness::MutexWaiter::wait().
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find().
insert()
template<class keyT , class valueT > std::pair< entryT *, bool > madness::Hash_private::bin< keyT, valueT >::insert (const datumT & datum, int lockmode) inline
References madness::Spinlock::lock(), madness::Hash_private::bin< keyT, valueT >::match(), madness::Hash_private::bin< keyT, valueT >::ninbin, madness::Hash_private::bin< keyT, valueT >::p, madness::Spinlock::unlock(), and madness::MutexWaiter::wait().
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
match()
template<class keyT , class valueT > entryT * madness::Hash_private::bin< keyT, valueT >::match (const keyT & key) const inline private
References madness::Hash_private::bin< keyT, valueT >::p.
Referenced by madness::Hash_private::bin< keyT, valueT >::find(), and madness::Hash_private::bin< keyT, valueT >::insert().
size()
template<class keyT , class valueT > std::size_t madness::Hash_private::bin< keyT, valueT >::size () const inline
References madness::Hash_private::bin< keyT, valueT >::ninbin.
Member Data Documentation
ninbin
template<class keyT , class valueT > int madness::Hash_private::bin< keyT, valueT >::ninbin
Referenced by madness::Hash_private::bin< keyT, valueT >::clear(), madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::insert(), and madness::Hash_private::bin< keyT, valueT >::size().
p
template<class keyT , class valueT > entryT* madness::Hash_private::bin< keyT, valueT >::p
Referenced by madness::Hash_private::bin< keyT, valueT >::clear(), madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::insert(), and madness::Hash_private::bin< keyT, valueT >::match().
The documentation for this class was generated from the following file:
worldhashmap.h