MADNESS: madness::randomgrid< NDIM > Class Template Reference
madness::randomgrid< NDIM > Class Template Reference
grid with random points around the origin, with a Gaussian distribution
#include <lowrankfunction.h>
Public Member Functions
randomgrid (const double volume_element, const double radius, const Vector< double, NDIM > origin=Vector< double, NDIM >(0.0))
std::vector< Vector< double, NDIM > > get_grid () const
Vector< double, NDIM > get_origin () const
Public Member Functions inherited from madness::gridbase
virtual ~gridbase ()=default
double get_radius () const
double get_volume_element () const
template<std::size_t NDIM>
void visualize (const std::string filename, const std::vector< Vector< double, NDIM > > &grid) const
Private Member Functions
double volume () const
Static Private Member Functions
static Vector< double, NDIM > gaussian_random_distribution (const Vector< double, NDIM > origin, double variance)
Private Attributes
Vector< double, NDIM > origin
Additional Inherited Members
Protected Attributes inherited from madness::gridbase
bool do_print =false
double radius =3
double volume_element =0.1
Detailed Description
template<std::size_t NDIM>
class madness::randomgrid< NDIM >
grid with random points around the origin, with a Gaussian distribution
Constructor & Destructor Documentation
randomgrid()
template<std::size_t NDIM> madness::randomgrid< NDIM >::randomgrid (const double volume_element, const double radius, const Vector< double, NDIM > origin = Vector<double,NDIM>(0.0)) inline
References madness::gridbase::radius, and madness::gridbase::volume_element.
Member Function Documentation
gaussian_random_distribution()
template<std::size_t NDIM> static Vector< double, NDIM > madness::randomgrid< NDIM >::gaussian_random_distribution (const Vector< double, NDIM > origin, double variance) inline static private
References d, NDIM, and madness::randomgrid< NDIM >::origin.
Referenced by madness::randomgrid< NDIM >::get_grid().
get_grid()
template<std::size_t NDIM> std::vector< Vector< double, NDIM > > madness::randomgrid< NDIM >::get_grid () const inline
References d, madness::gridbase::do_print, madness::randomgrid< NDIM >::gaussian_random_distribution(), madness::FunctionDefaults< NDIM >::get_cell(), madness::grid(), NDIM, madness::randomgrid< NDIM >::origin, madness::print(), madness::gridbase::radius, madness::randomgrid< NDIM >::volume(), and madness::gridbase::volume_element.
Referenced by madness::molecular_grid< NDIM >::get_grid().
get_origin()
template<std::size_t NDIM> Vector< double, NDIM > madness::randomgrid< NDIM >::get_origin () const inline
References madness::randomgrid< NDIM >::origin.
volume()
template<std::size_t NDIM> double madness::randomgrid< NDIM >::volume () const inline private
References MADNESS_CHECK, NDIM, madness::constants::pi, and madness::gridbase::radius.
Referenced by madness::randomgrid< NDIM >::get_grid().
Member Data Documentation
origin
template<std::size_t NDIM> Vector<double,NDIM> madness::randomgrid< NDIM >::origin private
Referenced by madness::randomgrid< NDIM >::gaussian_random_distribution(), madness::randomgrid< NDIM >::get_grid(), and madness::randomgrid< NDIM >::get_origin().
The documentation for this class was generated from the following file:
lowrankfunction.h