MADNESS: madness::molecular_grid< NDIM > Class Template Reference
madness::molecular_grid< NDIM > Class Template Reference
given a molecule, return a suitable grid
#include <lowrankfunction.h>
Public Member Functions
molecular_grid (const Molecule &molecule, std::shared_ptr< gridbase > grid)
ctor takes molecule and grid builder
molecular_grid (const std::vector< Vector< double, NDIM > > origins, const LowRankFunctionParameters &params)
ctor takes centers of the grid and the grid parameters
molecular_grid (const std::vector< Vector< double, NDIM > > origins, std::shared_ptr< gridbase > grid)
ctor takes centers of the grid and the grid builder
std::vector< Vector< double, NDIM > > get_grid () const
Public Member Functions inherited from madness::gridbase
virtual ~gridbase ()=default
double get_radius () const
double get_volume_element () const
template<std::size_t NDIM>
void visualize (const std::string filename, const std::vector< Vector< double, NDIM > > &grid) const
Private Attributes
std::vector< Vector< double, NDIM > > centers
std::shared_ptr< gridbase > grid_builder
Additional Inherited Members
Protected Attributes inherited from madness::gridbase
bool do_print =false
double radius =3
double volume_element =0.1
Detailed Description
template<std::size_t NDIM>
class madness::molecular_grid< NDIM >
given a molecule, return a suitable grid
Constructor & Destructor Documentation
molecular_grid() [1/3]
template<std::size_t NDIM> madness::molecular_grid< NDIM >::molecular_grid (const std::vector< Vector< double, NDIM > > origins, const LowRankFunctionParameters & params) inline
ctor takes centers of the grid and the grid parameters
References madness::molecular_grid< NDIM >::centers, madness::molecular_grid< NDIM >::grid_builder, madness::LowRankFunctionParameters::gridtype(), MADNESS_EXCEPTION, NDIM, madness::LowRankFunctionParameters::radius(), and madness::LowRankFunctionParameters::volume_element().
molecular_grid() [2/3]
template<std::size_t NDIM> madness::molecular_grid< NDIM >::molecular_grid (const std::vector< Vector< double, NDIM > > origins, std::shared_ptr< gridbase > grid) inline
ctor takes centers of the grid and the grid builder
References madness::molecular_grid< NDIM >::centers.
molecular_grid() [3/3]
template<std::size_t NDIM> madness::molecular_grid< NDIM >::molecular_grid (const Molecule & molecule, std::shared_ptr< gridbase > grid) inline
ctor takes molecule and grid builder
Member Function Documentation
get_grid()
template<std::size_t NDIM> std::vector< Vector< double, NDIM > > madness::molecular_grid< NDIM >::get_grid () const inline
References madness::molecular_grid< NDIM >::centers, GridBuilder::get_angular_order(), madness::dftgrid< NDIM >::get_grid(), madness::randomgrid< NDIM >::get_grid(), GridBuilder::get_nradial(), madness::grid(), madness::molecular_grid< NDIM >::grid_builder, MADNESS_CHECK_THROW, MADNESS_EXCEPTION, NDIM, and madness::print().
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), and test_molecular_grid().
Member Data Documentation
centers
template<std::size_t NDIM> std::vector<Vector<double,NDIM> > madness::molecular_grid< NDIM >::centers private
Referenced by madness::molecular_grid< NDIM >::molecular_grid(), madness::molecular_grid< NDIM >::molecular_grid(), and madness::molecular_grid< NDIM >::get_grid().
grid_builder
template<std::size_t NDIM> std::shared_ptr<gridbase> madness::molecular_grid< NDIM >::grid_builder private
Referenced by madness::molecular_grid< NDIM >::molecular_grid(), and madness::molecular_grid< NDIM >::get_grid().
The documentation for this class was generated from the following file:
lowrankfunction.h