MADNESS: MolecularNuclearPotentialFunctor2 Class Reference
MolecularNuclearPotentialFunctor2 Class Reference
Public Member Functions
MolecularNuclearPotentialFunctor2 (World &world, const MolecularEntity &mentity, const double &R, double eps, double lo=1e-12)
Tensor< double > get_coeff ()
Tensor< double > get_expnt ()
double operator() (const coordT &r) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level () const
Override this to change the minimum level of refinement at special points (default is 6)
virtual std::vector< Vector< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
BoundaryConditions< 3 > bc
Tensor< double > coeff
Tensor< double > expnt
MolecularEntity mentity
std::vector< Vector< double, 3 > > rvecs
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
MolecularNuclearPotentialFunctor2()
MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2 (World & world, const MolecularEntity & mentity, const double & R, double eps, double lo = 1e-12) inline
References bc, madness::BC_PERIODIC, coeff, madness::BaseTensor::dim(), expnt, generate_R_vectors(), madness::FunctionDefaults< NDIM >::get_bc(), madness::FunctionDefaults< NDIM >::get_cell_width(), lo, madness::Tensor< T >::max(), madness::Tensor< T >::normf(), pi, madness::constants::pi, madness::print(), R, rvecs, and madness::Tensor< T >::scale().
Member Function Documentation
get_coeff()
Tensor< double > MolecularNuclearPotentialFunctor2::get_coeff () inline
References coeff.
Referenced by test_nuclear_potential2().
get_expnt()
Tensor< double > MolecularNuclearPotentialFunctor2::get_expnt () inline
References expnt.
Referenced by test_nuclear_potential2().
operator()()
double MolecularNuclearPotentialFunctor2::operator() (const coordT & r) const inline
References coeff, expnt, MolecularEntity::get_atom(), mentity, MolecularEntity::natom(), nuclear_potential(), madness::Atom::q, rvecs, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Member Data Documentation
bc
BoundaryConditions<3> MolecularNuclearPotentialFunctor2::bc private
Referenced by MolecularNuclearPotentialFunctor2().
coeff
Tensor<double> MolecularNuclearPotentialFunctor2::coeff private
Referenced by MolecularNuclearPotentialFunctor2(), get_coeff(), and operator()().
expnt
Tensor<double> MolecularNuclearPotentialFunctor2::expnt private
Referenced by MolecularNuclearPotentialFunctor2(), get_expnt(), and operator()().
mentity
MolecularEntity MolecularNuclearPotentialFunctor2::mentity private
Referenced by operator()().
rvecs
std::vector< Vector<double,3> > MolecularNuclearPotentialFunctor2::rvecs private
Referenced by MolecularNuclearPotentialFunctor2(), and operator()().
The documentation for this class was generated from the following file:
ewald.cc