MADNESS: YetAnotherWrapperClass Class Reference
YetAnotherWrapperClass Class Reference
Public Member Functions
YetAnotherWrapperClass (const real_function_6d &f)
YetAnotherWrapperClass (const real_function_6d &f)
void operator() (const Key< 6 > &key, Tensor< double > &t) const
void operator() (const Key< 6 > &key, Tensor< double > &t) const
Private Attributes
real_function_6d eri
const real_function_6d & f
const real_function_3d f3
Tensor< double > identity
const long k
const Tensor< double > & qx
const Tensor< double > & qx3
const Tensor< double > & qx6
Constructor & Destructor Documentation
YetAnotherWrapperClass() [1/2]
YetAnotherWrapperClass::YetAnotherWrapperClass (const real_function_6d & f) inline
YetAnotherWrapperClass() [2/2]
YetAnotherWrapperClass::YetAnotherWrapperClass (const real_function_6d & f) inline
References eri, f, madness::Function< T, NDIM >::get_impl(), identity, and k.
Member Function Documentation
operator()() [1/2]
void YetAnotherWrapperClass::operator() (const Key< 6 > & key, Tensor< double > & t) const inline
References madness::Tensor< T >::emul(), f, madness::Function< T, NDIM >::get_impl(), k, qx, v, and V().
operator()() [2/2]
void YetAnotherWrapperClass::operator() (const Key< 6 > & key, Tensor< double > & t) const inline
References madness::Tensor< T >::emul(), eri, f, f3, madness::Function< T, NDIM >::get_impl(), helium_pot(), k, madness::Key< NDIM >::level(), qx3, qx6, madness::Key< NDIM >::translation(), v, and Z2().
Member Data Documentation
eri
real_function_6d YetAnotherWrapperClass::eri private
Referenced by YetAnotherWrapperClass(), and operator()().
f
const real_function_6d & YetAnotherWrapperClass::f private
Referenced by YetAnotherWrapperClass(), and operator()().
f3
const real_function_3d YetAnotherWrapperClass::f3 private
Referenced by operator()().
identity
Tensor<double> YetAnotherWrapperClass::identity private
Referenced by YetAnotherWrapperClass().
k
const long YetAnotherWrapperClass::k private
Referenced by YetAnotherWrapperClass(), and operator()().
qx
const Tensor<double>& YetAnotherWrapperClass::qx private
Referenced by operator()().
qx3
const Tensor<double>& YetAnotherWrapperClass::qx3 private
Referenced by operator()().
qx6
const Tensor<double>& YetAnotherWrapperClass::qx6 private
Referenced by operator()().
The documentation for this class was generated from the following files:
he.cc
helium_mp2.cc