MADNESS: madness::MolecularOptimizer Class Reference
madness::MolecularOptimizer Class Reference
Molecular optimizer derived from the QuasiNewton optimizer.
#include <molecular_optimizer.h>
Public Member Functions
MolecularOptimizer (World &world, const commandlineparser &parser, const std::shared_ptr< MolecularOptimizationTargetInterface > &tar)
same ctor as the QuasiNewton optimizer
bool converged () const
bool converged (const Tensor< double > &displacement) const
double gradient_norm () const
bool optimize (Tensor< double > &x)
optimize the underlying molecule
void set_hessian (const Tensor< double > &hess)
set an (initial) hessian
double value () const
Public Member Functions inherited from madness::OptimizerInterface
virtual ~OptimizerInterface ()
Static Public Member Functions
static Tensor< double > compute_frequencies (const Molecule &molecule, const Tensor< double > &hessian, Tensor< double > &normalmodes, const std::vector< std::string > &remove_dof={}, const bool print_hessian=false)
returns the vibrational frequencies
static Tensor< double > compute_reduced_mass (const Molecule &molecule, const Tensor< double > &normalmodes)
static Tensor< double > projector_external_dof (const Molecule &mol, const std::vector< std::string > &remove_dof)
compute the projector to remove transl. and rot. degrees of freedom
static void remove_external_dof (Tensor< double > &hessian, const Molecule &mol, const std::vector< std::string > &remove_dof)
remove translational degrees of freedom from the hessian
Public Attributes
MolecularOptimizationParameters parameters
Private Member Functions
Tensor< double > new_search_direction2 (const Tensor< double > &g, const Tensor< double > &hessian) const
effectively invert the hessian and multiply with the gradient
bool optimize_conjugate_gradients (Tensor< double > &x)
bool optimize_quasi_newton (Tensor< double > &x)
Private Attributes
double f =1.e10
double gnorm =1.e10
Tensor< double > h
std::shared_ptr< MolecularOptimizationTargetInterface > target
How to update the hessian: BFGS or SR1.
Detailed Description
Molecular optimizer derived from the QuasiNewton optimizer.
Essentially the QuasiNewton optimizer, but with the additional feature of projecting out rotational and translational degrees of freedom
Constructor & Destructor Documentation
MolecularOptimizer()
madness::MolecularOptimizer::MolecularOptimizer (World & world, const commandlineparser & parser, const std::shared_ptr< MolecularOptimizationTargetInterface > & tar) inline
same ctor as the QuasiNewton optimizer
Member Function Documentation
compute_frequencies()
static Tensor< double > madness::MolecularOptimizer::compute_frequencies (const Molecule & molecule, const Tensor< double > & hessian, Tensor< double > & normalmodes, const std::vector< std::string > & remove_dof = {}, const bool print_hessian = false) inline static
returns the vibrational frequencies
Parameters
[in] hessian the hessian matrix (not mass-weighted)
[out] normalmodes the normal modes
[in] project_tr whether to project out translation and rotation
[in] print_hessian whether to print the hessian matrix
Returns
the frequencies in atomic units
Referenced by optimize_quasi_newton().
compute_reduced_mass()
static Tensor< double > madness::MolecularOptimizer::compute_reduced_mass (const Molecule & molecule, const Tensor< double > & normalmodes) inline static
References madness::constants::atomic_mass_in_au, madness::copy(), madness::inner(), L, molecule, mu, and projector_external_dof().
converged() [1/2]
bool madness::MolecularOptimizer::converged () const inline virtual
Implements madness::OptimizerInterface.
References gradient_norm().
Referenced by optimize_conjugate_gradients(), and optimize_quasi_newton().
converged() [2/2]
bool madness::MolecularOptimizer::converged (const Tensor< double > & displacement) const inline
References madness::displacement(), gradient_norm(), parameters, and madness::MolecularOptimizationParameters::tol().
gradient_norm()
double madness::MolecularOptimizer::gradient_norm () const inline virtual
Implements madness::OptimizerInterface.
References gnorm.
Referenced by converged(), and converged().
new_search_direction2()
Tensor< double > madness::MolecularOptimizer::new_search_direction2 (const Tensor< double > & g, const Tensor< double > & hessian) const inline private
effectively invert the hessian and multiply with the gradient
References std::abs(), e(), madness::g, madness::MolecularOptimizationParameters::gradient_precision(), madness::inner(), parameters, madness::MolecularOptimizationParameters::printtest(), madness::syev(), and v.
Referenced by optimize_quasi_newton().
optimize()
bool madness::MolecularOptimizer::optimize (Tensor< double > & x) inline virtual
optimize the underlying molecule
Parameters
[in] x the coordinates to compute energy and gradient
Implements madness::OptimizerInterface.
References converge(), and optimize_quasi_newton().
Referenced by main().
optimize_conjugate_gradients()
bool madness::MolecularOptimizer::optimize_conjugate_gradients (Tensor< double > & x) inline private
References beta, madness::MolecularOptimizationParameters::cg_method(), converged(), madness::displacement(), energy, madness::Tensor< T >::fill(), gnorm, madness::inner(), madness::MolecularOptimizationParameters::maxiter(), madness::Tensor< T >::normf(), parameters, projector_external_dof(), madness::MolecularOptimizationParameters::remove_dof(), madness::BaseTensor::size(), and target.
optimize_quasi_newton()
bool madness::MolecularOptimizer::optimize_quasi_newton (Tensor< double > & x) inline private
References madness::Tensor< T >::absmax(), madness::constants::au2invcm, compute_frequencies(), converged(), madness::BaseTensor::dim(), e(), f, gnorm, h, madness::QuasiNewton::hessian_update_bfgs(), madness::QuasiNewton::hessian_update_sr1(), madness::inner(), madness::QuasiNewton::line_search(), madness::MolecularOptimizationParameters::maxiter(), new_search_direction2(), madness::Tensor< T >::normf(), parameters, madness::print(), madness::MolecularOptimizationParameters::printtest(), projector_external_dof(), madness::MolecularOptimizationParameters::remove_dof(), remove_external_dof(), madness::Tensor< T >::scale(), madness::BaseTensor::size(), madness::syev(), target, madness::MolecularOptimizationParameters::update(), v, and madness::MolecularOptimizationParameters::value_precision().
Referenced by optimize().
projector_external_dof()
static Tensor< double > madness::MolecularOptimizer::projector_external_dof (const Molecule & mol, const std::vector< std::string > & remove_dof) inline static
compute the projector to remove transl. and rot. degrees of freedom
taken from http://www.gaussian.com/g_whitepap/vib.htm I don't really understand the concept behind the projectors, but it seems to work, and it is not written down explicitly anywhere. NOTE THE ERROR IN THE FORMULAS ON THE WEBPAGE !
Parameters
[in] do_remove_dof which dof to remove: x,y,z,Rx,Ry,Rz (transl/rot)
References madness::_(), madness::constants::atomic_mass_in_au, madness::Molecule::center_of_mass(), e(), madness::Molecule::get_atom(), madness::Atom::get_mass_in_au(), I, madness::inner(), madness::Molecule::moment_of_inertia(), madness::Molecule::natom(), norm(), madness::Tensor< T >::normf(), p(), madness::print(), madness::Tensor< T >::scale(), madness::syev(), madness::commandlineparser::tolower(), madness::Molecule::translate(), madness::transpose(), v, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by madness::Nemo::compute_IR_intensities(), compute_reduced_mass(), optimize_conjugate_gradients(), optimize_quasi_newton(), and remove_external_dof().
remove_external_dof()
static void madness::MolecularOptimizer::remove_external_dof (Tensor< double > & hessian, const Molecule & mol, const std::vector< std::string > & remove_dof) inline static
remove translational degrees of freedom from the hessian
Parameters
[in] do_remove_dof which dof to remove: x,y,z,Rx,Ry,Rz (transl/rot)
References madness::inner(), and projector_external_dof().
Referenced by optimize_quasi_newton().
set_hessian()
void madness::MolecularOptimizer::set_hessian (const Tensor< double > & hess) inline
set an (initial) hessian
References madness::copy(), and h.
Referenced by main().
value()
double madness::MolecularOptimizer::value () const inline virtual
Implements madness::OptimizerInterface.
Member Data Documentation
f
double madness::MolecularOptimizer::f =1.e10 private
Referenced by optimize_quasi_newton().
gnorm
double madness::MolecularOptimizer::gnorm =1.e10 private
Referenced by gradient_norm(), optimize_conjugate_gradients(), and optimize_quasi_newton().
h
Tensor<double> madness::MolecularOptimizer::h private
Referenced by optimize_quasi_newton(), and set_hessian().
parameters
MolecularOptimizationParameters madness::MolecularOptimizer::parameters
Referenced by converged(), main(), new_search_direction2(), optimize_conjugate_gradients(), and optimize_quasi_newton().
target
std::shared_ptr<MolecularOptimizationTargetInterface> madness::MolecularOptimizer::target private
How to update the hessian: BFGS or SR1.
Referenced by optimize_conjugate_gradients(), and optimize_quasi_newton().
The documentation for this class was generated from the following file:
molecular_optimizer.h