MADNESS: madness::SubspaceK< T, NDIM > Class Template Reference
madness::SubspaceK< T, NDIM > Class Template Reference
MADNESS applications » Periodic Solver
The SubspaceK class is a container class holding previous orbitals and residuals.
#include <solver.h>
Public Member Functions
SubspaceK (World &world, const ElectronicStructureParams &params, const std::vector< KPoint > &kpoints)
void update_subspace (vecfuncT &awfs_new, vecfuncT &bwfs_new, const vecfuncT &awfs_old, const vecfuncT &bwfs_old)
Private Types
typedef Function< valueT, NDIM > functionT
typedef std::pair< vecfuncT, vecfuncT > pairvecfuncT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< valueT > tensorT
typedef std::complex< T > valueT
typedef std::vector< functionT > vecfuncT
typedef std::vector< subspaceT > vecsubspaceT
typedef std::vector< tensorT > vectensorT
Private Attributes
std::vector< KPoint > _kpoints
ElectronicStructureParams _params
vectensorT _Q
double _residual
vecsubspaceT _subspace
World & _world
Detailed Description
template<typename T, int NDIM>
class madness::SubspaceK< T, NDIM >
The SubspaceK class is a container class holding previous orbitals and residuals.
The Solver class uses the Krylov Accelerated Inexact Newton Solver (KAIN) accelerate the convergence a given calculation. The KAIN solver needs to store a subspace of previous orbitals and residuals. In the case is this implementation, the orbitals are store according to which k-point to which they belong.
Member Typedef Documentation
functionT
template<typename T , int NDIM> typedef Function<valueT,NDIM> madness::SubspaceK< T, NDIM >::functionT private
pairvecfuncT
template<typename T , int NDIM> typedef std::pair<vecfuncT,vecfuncT> madness::SubspaceK< T, NDIM >::pairvecfuncT private
subspaceT
template<typename T , int NDIM> typedef std::vector<pairvecfuncT> madness::SubspaceK< T, NDIM >::subspaceT private
tensorT
template<typename T , int NDIM> typedef Tensor<valueT> madness::SubspaceK< T, NDIM >::tensorT private
valueT
template<typename T , int NDIM> typedef std::complex<T> madness::SubspaceK< T, NDIM >::valueT private
vecfuncT
template<typename T , int NDIM> typedef std::vector<functionT> madness::SubspaceK< T, NDIM >::vecfuncT private
vecsubspaceT
template<typename T , int NDIM> typedef std::vector<subspaceT> madness::SubspaceK< T, NDIM >::vecsubspaceT private
vectensorT
template<typename T , int NDIM> typedef std::vector<tensorT> madness::SubspaceK< T, NDIM >::vectensorT private
Constructor & Destructor Documentation
SubspaceK()
template<typename T , int NDIM> madness::SubspaceK< T, NDIM >::SubspaceK (World & world, const ElectronicStructureParams & params, const std::vector< KPoint > & kpoints) inline
References madness::SubspaceK< T, NDIM >::_kpoints, madness::SubspaceK< T, NDIM >::_Q, madness::SubspaceK< T, NDIM >::_residual, and madness::SubspaceK< T, NDIM >::_subspace.
Member Function Documentation
update_subspace()
template<typename T , int NDIM> void madness::SubspaceK< T, NDIM >::update_subspace (vecfuncT & awfs_new, vecfuncT & bwfs_new, const vecfuncT & awfs_old, const vecfuncT & bwfs_old) inline
References madness::_(), madness::SubspaceK< T, NDIM >::_kpoints, madness::SubspaceK< T, NDIM >::_params, madness::SubspaceK< T, NDIM >::_Q, madness::SubspaceK< T, NDIM >::_residual, madness::SubspaceK< T, NDIM >::_subspace, madness::SubspaceK< T, NDIM >::_world, madness::abs(), madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::broadcast_serializable(), c, madness::compress(), e(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, madness::KAIN(), m, madness::ElectronicStructureParams::maxsub, one(), madness::print(), madness::Tensor< T >::ptr(), madness::World::rank(), madness::World::size(), madness::ElectronicStructureParams::spinpol, madness::sub(), and madness::WorldGopInterface::sum().
Member Data Documentation
_kpoints
template<typename T , int NDIM> std::vector<KPoint> madness::SubspaceK< T, NDIM >::_kpoints private
Referenced by madness::SubspaceK< T, NDIM >::SubspaceK(), and madness::SubspaceK< T, NDIM >::update_subspace().
_params
template<typename T , int NDIM> ElectronicStructureParams madness::SubspaceK< T, NDIM >::_params private
Referenced by madness::SubspaceK< T, NDIM >::update_subspace().
_Q
template<typename T , int NDIM> vectensorT madness::SubspaceK< T, NDIM >::_Q private
Referenced by madness::SubspaceK< T, NDIM >::SubspaceK(), and madness::SubspaceK< T, NDIM >::update_subspace().
_residual
template<typename T , int NDIM> double madness::SubspaceK< T, NDIM >::_residual private
Referenced by madness::SubspaceK< T, NDIM >::SubspaceK(), and madness::SubspaceK< T, NDIM >::update_subspace().
_subspace
template<typename T , int NDIM> vecsubspaceT madness::SubspaceK< T, NDIM >::_subspace private
Referenced by madness::SubspaceK< T, NDIM >::SubspaceK(), and madness::SubspaceK< T, NDIM >::update_subspace().
_world
template<typename T , int NDIM> World& madness::SubspaceK< T, NDIM >::_world private
Referenced by madness::SubspaceK< T, NDIM >::update_subspace().
The documentation for this class was generated from the following file:
solver.h