MADNESS: PartitionPmap Class Reference
PartitionPmap Class Reference
A pmap that spatially decomposes the domain and by default slightly overdcomposes to attempt to load balance.
Public Member Functions
PartitionPmap ()
PartitionPmap (size_t nproc, const Level target_level=0)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< 3 > >
virtual ~WorldDCPmapInterface ()
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
virtual DistributionType distribution_type () const
by default the map is distributed
std::size_t global_size (World &world) const
Counts global number of entries in all containers associated with this process map.
std::size_t local_size () const
Counts local number of entries in all containers associated with this process map.
virtual void print () const
void print_data_sizes (World &world, const std::string msg="") const
Prints size info to std::cout.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
Private Attributes
const int nproc
Level target_level
Additional Inherited Members
Public Types inherited from madness::WorldDCPmapInterface< Key< 3 > >
typedef WorldDCRedistributeInterface< Key< 3 > > * ptrT
Detailed Description
A pmap that spatially decomposes the domain and by default slightly overdcomposes to attempt to load balance.
Constructor & Destructor Documentation
PartitionPmap() [1/2]
PartitionPmap::PartitionPmap () inline
PartitionPmap() [2/2]
PartitionPmap::PartitionPmap (size_t nproc, const Level target_level = 0) inline
References nproc, p(), and target_level.
Member Function Documentation
owner()
ProcessID PartitionPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), nproc, madness::Key< NDIM >::parent(), and target_level.
Member Data Documentation
nproc
const int PartitionPmap::nproc private
Referenced by PartitionPmap(), and owner().
target_level
Level PartitionPmap::target_level private
Referenced by PartitionPmap(), and owner().
The documentation for this class was generated from the following file:
testttg.cc