MADNESS: madness::MemoryMeasurer Class Reference
madness::MemoryMeasurer Class Reference
measure the memory usage of all FunctionImpl objects of all worlds
#include <memory_measurement.h>
Classes
struct MemInfo
struct MemKey
Public Member Functions
void clear_map ()
reset the memory map
std::vector< std::pair< std::string, double > > memory_per_host_all_ranks (const std::vector< std::pair< std::pair< std::string, long >, double > > &mem_per_host_and_rank) const
accumulate the memory usage of all objects of all worlds over all ranks per host
std::vector< std::pair< std::pair< std::string, long >, double > > memory_per_host_and_rank (World &world) const
accumulate the memory usage of all objects of all worlds for this rank per host
void print_memory_map (World &world, std::string msg="")
void reduce_map (World &universe)
gather all information of the map on rank 0 of the universe
void search_all_worlds ()
void search_world (World &world)
double total_memory (World &world) const
return the total memory usage over all hosts
Static Public Member Functions
static std::map< std::string, std::pair< int, double > > host_to_nrank_and_rss_map (World &universe)
given the hostname, return number of ranks and total rss on that node
static void measure_and_print (World &world)
measure the memory usage of all objects of all worlds
Private Types
typedef std::map< MemKey, MemInfo > MemInfoMapT
Private Member Functions
template<typename T , std::size_t NDIM>
void add_memory_to_map (const FunctionImpl< T, NDIM > &f)
template<typename T , std::size_t NDIM>
const FunctionImpl< T, NDIM > * cast_to_funcimpl_ptr (const uniqueidT obj_id)
Static Private Member Functions
static std::string get_hostname ()
get the hostname of this machine, rank-local
Private Attributes
bool debug =false
MemInfoMapT world_memory_map
keeps track of the memory usage of all objects of one or many worlds on this rank
Friends
bool operator< (const MemKey &lhs, const MemKey &other)
Detailed Description
measure the memory usage of all FunctionImpl objects of all worlds
Assuming FunctionImpl are the largest objects in a calculation data is kept as key-value pairs in a map: key=world_id,rank,hostname,NDIM, value=#functions,memory_GB
Member Typedef Documentation
MemInfoMapT
typedef std::map<MemKey,MemInfo> madness::MemoryMeasurer::MemInfoMapT private
Member Function Documentation
add_memory_to_map()
template<typename T , std::size_t NDIM> void madness::MemoryMeasurer::add_memory_to_map (const FunctionImpl< T, NDIM > & f) inline private
References debug, madness::f, NDIM, madness::print(), T(), and world_memory_map.
Referenced by search_world().
cast_to_funcimpl_ptr()
template<typename T , std::size_t NDIM> const FunctionImpl< T, NDIM > * madness::MemoryMeasurer::cast_to_funcimpl_ptr (const uniqueidT obj_id) inline private
References madness::uniqueidT::get_world_id(), MADNESS_EXCEPTION, madness::World::ptr_from_id(), and madness::World::world_from_id().
clear_map()
void madness::MemoryMeasurer::clear_map () inline
reset the memory map
References world_memory_map.
Referenced by measure_and_print(), and reduce_map().
get_hostname()
static std::string madness::MemoryMeasurer::get_hostname () inline static private
get the hostname of this machine, rank-local
Referenced by madness::MemoryMeasurer::MemKey::MemKey().
host_to_nrank_and_rss_map()
static std::map< std::string, std::pair< int, double > > madness::MemoryMeasurer::host_to_nrank_and_rss_map (World & universe) inline static
given the hostname, return number of ranks and total rss on that node
References a, b, and madness::rank_to_host_and_rss_map().
Referenced by print_memory_map().
measure_and_print()
static void madness::MemoryMeasurer::measure_and_print (World & world) inline static
measure the memory usage of all objects of all worlds
References clear_map(), madness::WorldGopInterface::fence(), madness::World::gop, print_memory_map(), and search_all_worlds().
Referenced by madness::MacroTaskQ::run_all(), madness::CC2::solve_mp2_coupled(), and test_size().
memory_per_host_all_ranks()
std::vector< std::pair< std::string, double > > madness::MemoryMeasurer::memory_per_host_all_ranks (const std::vector< std::pair< std::pair< std::string, long >, double > > & mem_per_host_and_rank) const inline
accumulate the memory usage of all objects of all worlds over all ranks per host
integrate out world, dim and rank, only hostname is left
Referenced by print_memory_map().
memory_per_host_and_rank()
std::vector< std::pair< std::pair< std::string, long >, double > > madness::MemoryMeasurer::memory_per_host_and_rank (World & world) const inline
accumulate the memory usage of all objects of all worlds for this rank per host
integrate out world and dim from MemKey, result lives on rank 0 only
References a, b, and world_memory_map.
Referenced by print_memory_map().
print_memory_map()
void madness::MemoryMeasurer::print_memory_map (World & world, std::string msg = "") inline
Parameters
[in] msg a message to print before the memory map
[in] world used only for clean printing
References a, b, bufsize, madness::WorldGopInterface::fence(), madness::World::gop, host_to_nrank_and_rss_map(), memory_per_host_all_ranks(), memory_per_host_and_rank(), madness::print(), madness::World::rank(), reduce_map(), madness::World::size(), total_memory(), and world_memory_map.
Referenced by measure_and_print().
reduce_map()
void madness::MemoryMeasurer::reduce_map (World & universe) inline
gather all information of the map on rank 0 of the universe
References clear_map(), madness::WorldGopInterface::concat0(), madness::World::gop, and world_memory_map.
Referenced by print_memory_map().
search_all_worlds()
void madness::MemoryMeasurer::search_all_worlds () inline
add all FunctionImpl<T,NDIM> objects of all worlds to the memory map the memory map is a rank-local object
References debug, madness::World::exists(), madness::World::get_default(), madness::World::get_world_ids(), madness::print(), search_world(), and madness::World::world_from_id().
Referenced by measure_and_print().
search_world()
void madness::MemoryMeasurer::search_world (World & world) inline
add all FunctionImpl<T,NDIM> objects of the given world to the memory map the memory map is a rank-local object
References add_memory_to_map(), debug, madness::World::get_object_ids(), madness::print(), and madness::World::rank().
Referenced by search_all_worlds().
total_memory()
double madness::MemoryMeasurer::total_memory (World & world) const inline
return the total memory usage over all hosts
References total_memory(), and world_memory_map.
Referenced by print_memory_map(), and total_memory().
Friends And Related Symbol Documentation
operator<
bool operator< (const MemKey & lhs, const MemKey & other) friend
Member Data Documentation
debug
bool madness::MemoryMeasurer::debug =false private
Referenced by add_memory_to_map(), search_all_worlds(), and search_world().
world_memory_map
MemInfoMapT madness::MemoryMeasurer::world_memory_map private
keeps track of the memory usage of all objects of one or many worlds on this rank
Referenced by add_memory_to_map(), clear_map(), memory_per_host_and_rank(), print_memory_map(), reduce_map(), and total_memory().
The documentation for this class was generated from the following file:
memory_measurement.h