MADNESS: madness::TwoBodyFunctionPureComponent< T, NDIM > Class Template Reference
madness::TwoBodyFunctionPureComponent< T, NDIM > Class Template Reference
a two-body, explicitly 6-dimensional function
#include <ccpairfunction.h>
Public Member Functions
TwoBodyFunctionPureComponent ()=default
TwoBodyFunctionPureComponent (const Function< T, NDIM > &f)
TwoBodyFunctionPureComponent (const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op, const Function< T, NDIM > &f)
template<typename Q , std::size_t MDIM>
TwoBodyFunctionPureComponent apply (const SeparatedConvolution< Q, MDIM > *op, const int particle=0)
std::shared_ptr< TwoBodyFunctionComponentBase > clone () override
deep copy
Function< T, NDIM > & get_function ()
const std::shared_ptr< CCConvolutionOperator< T, LDIM > > get_operator_ptr () const
bool has_operator () const override
hashT hash () const override
bool is_pure () const override
std::string name (const bool transpose) const override
template<typename Q >
TwoBodyFunctionPureComponent & operator*= (const Q fac)
void print_size (const std::string name1="") const override
void set_operator (const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op1)
void swap_particles_inplace () override
return f(2,1)
World & world () const override
Public Member Functions inherited from madness::TwoBodyFunctionComponentBase
virtual ~TwoBodyFunctionComponentBase ()
virtual bool is_decomposed () const
Private Attributes
std::shared_ptr< CCConvolutionOperator< T, LDIM > > op
Function< T, NDIM > u
pure 6D function
Static Private Attributes
static constexpr std::size_t LDIM =NDIM/2
Detailed Description
template<typename T, std::size_t NDIM>
class madness::TwoBodyFunctionPureComponent< T, NDIM >
a two-body, explicitly 6-dimensional function
Constructor & Destructor Documentation
TwoBodyFunctionPureComponent() [1/3]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionPureComponent< T, NDIM >::TwoBodyFunctionPureComponent () default
TwoBodyFunctionPureComponent() [2/3]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionPureComponent< T, NDIM >::TwoBodyFunctionPureComponent (const Function< T, NDIM > & f) inline explicit
TwoBodyFunctionPureComponent() [3/3]
template<typename T , std::size_t NDIM> madness::TwoBodyFunctionPureComponent< T, NDIM >::TwoBodyFunctionPureComponent (const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op, const Function< T, NDIM > & f) inline explicit
Member Function Documentation
apply()
template<typename T , std::size_t NDIM> template<typename Q , std::size_t MDIM> TwoBodyFunctionPureComponent madness::TwoBodyFunctionPureComponent< T, NDIM >::apply (const SeparatedConvolution< Q, MDIM > * op, const int particle = 0) inline
clone()
template<typename T , std::size_t NDIM> std::shared_ptr< TwoBodyFunctionComponentBase > madness::TwoBodyFunctionPureComponent< T, NDIM >::clone () inline override virtual
deep copy
Implements madness::TwoBodyFunctionComponentBase.
References madness::copy(), madness::TwoBodyFunctionPureComponent< T, NDIM >::op, and madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
get_function()
template<typename T , std::size_t NDIM> Function< T, NDIM > & madness::TwoBodyFunctionPureComponent< T, NDIM >::get_function () inline
References madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
get_operator_ptr()
template<typename T , std::size_t NDIM> const std::shared_ptr< CCConvolutionOperator< T, LDIM > > madness::TwoBodyFunctionPureComponent< T, NDIM >::get_operator_ptr () const inline
References madness::TwoBodyFunctionPureComponent< T, NDIM >::op.
Referenced by madness::TwoBodyFunctionPureComponent< T, NDIM >::name().
has_operator()
template<typename T , std::size_t NDIM> bool madness::TwoBodyFunctionPureComponent< T, NDIM >::has_operator () const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionPureComponent< T, NDIM >::op.
Referenced by madness::TwoBodyFunctionPureComponent< T, NDIM >::name().
hash()
template<typename T , std::size_t NDIM> hashT madness::TwoBodyFunctionPureComponent< T, NDIM >::hash () const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::hash_combine(), madness::hash_value(), madness::TwoBodyFunctionPureComponent< T, NDIM >::op, and madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
is_pure()
template<typename T , std::size_t NDIM> bool madness::TwoBodyFunctionPureComponent< T, NDIM >::is_pure () const inline override virtual
Reimplemented from madness::TwoBodyFunctionComponentBase.
name()
template<typename T , std::size_t NDIM> std::string madness::TwoBodyFunctionPureComponent< T, NDIM >::name (const bool transpose) const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionPureComponent< T, NDIM >::get_operator_ptr(), madness::TwoBodyFunctionPureComponent< T, NDIM >::has_operator(), and madness::transpose().
Referenced by madness::TwoBodyFunctionPureComponent< T, NDIM >::print_size().
operator*=()
template<typename T , std::size_t NDIM> template<typename Q > TwoBodyFunctionPureComponent & madness::TwoBodyFunctionPureComponent< T, NDIM >::operator*= (const Q fac) inline
References madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
print_size()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionPureComponent< T, NDIM >::print_size (const std::string name1 = "") const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionPureComponent< T, NDIM >::name(), and madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
set_operator()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionPureComponent< T, NDIM >::set_operator (const std::shared_ptr< CCConvolutionOperator< T, LDIM > > op1) inline
References madness::TwoBodyFunctionPureComponent< T, NDIM >::op.
swap_particles_inplace()
template<typename T , std::size_t NDIM> void madness::TwoBodyFunctionPureComponent< T, NDIM >::swap_particles_inplace () inline override virtual
return f(2,1)
Implements madness::TwoBodyFunctionComponentBase.
References madness::swap_particles(), and madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
world()
template<typename T , std::size_t NDIM> World & madness::TwoBodyFunctionPureComponent< T, NDIM >::world () const inline override virtual
Implements madness::TwoBodyFunctionComponentBase.
References madness::TwoBodyFunctionPureComponent< T, NDIM >::u.
Member Data Documentation
LDIM
template<typename T , std::size_t NDIM> constexpr std::size_t madness::TwoBodyFunctionPureComponent< T, NDIM >::LDIM =NDIM/2 static constexpr private
op
template<typename T , std::size_t NDIM> std::shared_ptr<CCConvolutionOperator<T,LDIM> > madness::TwoBodyFunctionPureComponent< T, NDIM >::op private
Referenced by madness::TwoBodyFunctionPureComponent< T, NDIM >::clone(), madness::TwoBodyFunctionPureComponent< T, NDIM >::get_operator_ptr(), madness::TwoBodyFunctionPureComponent< T, NDIM >::has_operator(), madness::TwoBodyFunctionPureComponent< T, NDIM >::hash(), and madness::TwoBodyFunctionPureComponent< T, NDIM >::set_operator().
u
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::TwoBodyFunctionPureComponent< T, NDIM >::u private
pure 6D function
Referenced by madness::TwoBodyFunctionPureComponent< T, NDIM >::clone(), madness::TwoBodyFunctionPureComponent< T, NDIM >::get_function(), madness::TwoBodyFunctionPureComponent< T, NDIM >::hash(), madness::TwoBodyFunctionPureComponent< T, NDIM >::operator*=(), madness::TwoBodyFunctionPureComponent< T, NDIM >::print_size(), madness::TwoBodyFunctionPureComponent< T, NDIM >::swap_particles_inplace(), and madness::TwoBodyFunctionPureComponent< T, NDIM >::world().
The documentation for this class was generated from the following file:
ccpairfunction.h