MADNESS: madness::DFTNuclearChargeDensityOp< T, NDIM > Class Template Reference
madness::DFTNuclearChargeDensityOp< T, NDIM > Class Template Reference
#include <dft.h>
Public Types
typedef Function< T, NDIM > funcT
Public Member Functions
DFTNuclearChargeDensityOp (World &world, funcT rhon, double coeff, double thresh, bool periodic)
~DFTNuclearChargeDensityOp ()
virtual bool is_od ()
Is there an orbitally-dependent term?
virtual bool is_rd ()
Is there a density-dependent term?
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
void prepare_op (Function< double, NDIM > rho)
Public Member Functions inherited from madness::EigSolverOp< T, NDIM >
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
double coeff ()
std::string messsageME ()
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
Private Attributes
funcT _rhon
funcT _Vnuc
Additional Inherited Members
Public Attributes inherited from madness::EigSolverOp< T, NDIM >
World & _world
Protected Member Functions inherited from madness::EigSolverOp< T, NDIM >
void messageME (std::string messageME)
double thresh ()
Member Typedef Documentation
funcT
template<typename T , int NDIM> typedef Function<T,NDIM> madness::DFTNuclearChargeDensityOp< T, NDIM >::funcT
Constructor & Destructor Documentation
DFTNuclearChargeDensityOp()
template<typename T , int NDIM> madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp (World & world, funcT rhon, double coeff, double thresh, bool periodic)
References madness::DFTNuclearChargeDensityOp< T, NDIM >::_rhon, madness::DFTNuclearChargeDensityOp< T, NDIM >::_Vnuc, madness::apply(), e(), madness::FunctionDefaults< NDIM >::get_cell_width(), L, madness::EigSolverOp< T, NDIM >::messageME(), and madness::EigSolverOp< T, NDIM >::thresh().
~DFTNuclearChargeDensityOp()
template<typename T , int NDIM> madness::DFTNuclearChargeDensityOp< T, NDIM >::~DFTNuclearChargeDensityOp () inline
Member Function Documentation
is_od()
template<typename T , int NDIM> virtual bool madness::DFTNuclearChargeDensityOp< T, NDIM >::is_od () inline virtual
Is there an orbitally-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
is_rd()
template<typename T , int NDIM> virtual bool madness::DFTNuclearChargeDensityOp< T, NDIM >::is_rd () inline virtual
Is there a density-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
op_r()
template<typename T , int NDIM> Function< T, NDIM > madness::DFTNuclearChargeDensityOp< T, NDIM >::op_r (const funcT & rho, const funcT & psi) virtual
Density-dependent portion of operator.
Reimplemented from madness::EigSolverOp< T, NDIM >.
References psi().
prepare_op()
template<typename T , int NDIM> void madness::DFTNuclearChargeDensityOp< T, NDIM >::prepare_op (Function< double, NDIM > rho) inline
Member Data Documentation
_rhon
template<typename T , int NDIM> funcT madness::DFTNuclearChargeDensityOp< T, NDIM >::_rhon private
Referenced by madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp().
_Vnuc
template<typename T , int NDIM> funcT madness::DFTNuclearChargeDensityOp< T, NDIM >::_Vnuc private
Referenced by madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp().
The documentation for this class was generated from the following files:
dft.h
dft.cc