MADNESS: madness::Lz< T, NDIM > Class Template Reference
madness::Lz< T, NDIM > Class Template Reference
the z component of the angular momentum
#include <SCFOperators.h>
Public Member Functions
Lz (World &world, bool use_bspline_derivative=true)
std::string info () const
print some information about this operator
T operator() (const Function< T, NDIM > &bra, const Function< T, NDIM > &ket) const
compute the matrix element <bra | op | ket>
Function< T, NDIM > operator() (const Function< T, NDIM > &ket) const
Tensor< T > operator() (const std::vector< Function< T, NDIM > > &vbra, const std::vector< Function< T, NDIM > > &vket) const
std::vector< Function< T, NDIM > > operator() (const std::vector< Function< T, NDIM > > &vket) const
Public Member Functions inherited from madness::SCFOperatorBase< T, NDIM >
SCFOperatorBase ()=default
SCFOperatorBase (std::shared_ptr< MacroTaskQ > taskq)
virtual ~SCFOperatorBase ()
virtual tensorT operator() (const vecfuncT &vbra, const vecfuncT &vket) const =0
compute the matrix <vbra | op | vket>
virtual vecfuncT operator() (const vecfuncT &vket) const =0
apply this operator on the argument vector of functions
Public Attributes
bool use_bsplines =true
Public Attributes inherited from madness::SCFOperatorBase< T, NDIM >
std::shared_ptr< MacroTaskQ > taskq =0
Private Attributes
World & world
Additional Inherited Members
Public Types inherited from madness::SCFOperatorBase< T, NDIM >
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Detailed Description
template<typename T, std::size_t NDIM>
class madness::Lz< T, NDIM >
the z component of the angular momentum
takes real and complex functions as input, will return complex functions
Constructor & Destructor Documentation
Lz()
template<typename T , std::size_t NDIM> madness::Lz< T, NDIM >::Lz (World & world, bool use_bspline_derivative = true) inline
Member Function Documentation
info()
template<typename T , std::size_t NDIM> std::string madness::Lz< T, NDIM >::info () const inline virtual
print some information about this operator
Implements madness::SCFOperatorBase< T, NDIM >.
operator()() [1/4]
template<typename T , std::size_t NDIM> T madness::Lz< T, NDIM >::operator() (const Function< T, NDIM > & bra, const Function< T, NDIM > & ket) const inline virtual
compute the matrix element <bra | op | ket>
Parameters
bra bra state
ket ket state
Returns
the matrix element <bra | op | ket>
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::inner().
operator()() [2/4]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::Lz< T, NDIM >::operator() (const Function< T, NDIM > & ket) const inline virtual
apply this operator on the argument function
Parameters
ket the argument function
Returns
op(ket)
Implements madness::SCFOperatorBase< T, NDIM >.
Referenced by madness::Lz< T, NDIM >::operator()().
operator()() [3/4]
template<typename T , std::size_t NDIM> Tensor<T> madness::Lz< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > & vbra, const std::vector< Function< T, NDIM > > & vket) const inline
References madness::matrix_inner(), madness::Lz< T, NDIM >::operator()(), and madness::Lz< T, NDIM >::world.
operator()() [4/4]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::Lz< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > & vket) const inline
References madness::apply(), madness::reconstruct(), madness::Derivative< T, NDIM >::set_bspline1(), madness::Lz< T, NDIM >::use_bsplines, and madness::Lz< T, NDIM >::world.
Member Data Documentation
use_bsplines
template<typename T , std::size_t NDIM> bool madness::Lz< T, NDIM >::use_bsplines =true
Referenced by madness::Lz< T, NDIM >::operator()().
world
template<typename T , std::size_t NDIM> World& madness::Lz< T, NDIM >::world private
Referenced by madness::Lz< T, NDIM >::operator()().
The documentation for this class was generated from the following file:
SCFOperators.h