MADNESS: madness::EigSolverOp< T, NDIM > Class Template Reference
madness::EigSolverOp< T, NDIM > Class Template Reference abstract
#include <eigsolver.h>
Public Member Functions
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
double coeff ()
virtual bool is_od ()=0
Is there an orbitally-dependent term?
virtual bool is_rd ()=0
Is there a density-dependent term?
std::string messsageME ()
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
Public Attributes
World & _world
Protected Member Functions
void messageME (std::string messageME)
double thresh ()
Private Types
typedef Function< T, NDIM > funcT
Private Attributes
double _coeff
std::string _messageME
double _thresh
Member Typedef Documentation
funcT
template<typename T , int NDIM> typedef Function<T,NDIM> madness::EigSolverOp< T, NDIM >::funcT private
Constructor & Destructor Documentation
EigSolverOp()
template<typename T , int NDIM> madness::EigSolverOp< T, NDIM >::EigSolverOp (World & world, double coeff, double thresh) inline
~EigSolverOp()
template<typename T , int NDIM> virtual madness::EigSolverOp< T, NDIM >::~EigSolverOp () inline virtual
Member Function Documentation
coeff()
template<typename T , int NDIM> double madness::EigSolverOp< T, NDIM >::coeff () inline
References madness::EigSolverOp< T, NDIM >::_coeff.
is_od()
template<typename T , int NDIM> virtual bool madness::EigSolverOp< T, NDIM >::is_od () pure virtual
Is there an orbitally-dependent term?
Implemented in madness::DFTNuclearPotentialOp< T, NDIM >, madness::DFTCoulombOp< T, NDIM >, madness::DFTCoulombPeriodicOp< T, NDIM >, madness::XCFunctionalLDA< T, NDIM >, madness::DFTNuclearChargeDensityOp< T, NDIM >, madness::HartreeFockNuclearPotentialOp< T, NDIM >, madness::HartreeFockCoulombOp< T, NDIM >, madness::HartreeFockExchangeOp< T, NDIM >, and NuclearChargeDensityOp< T, NDIM >.
is_rd()
template<typename T , int NDIM> virtual bool madness::EigSolverOp< T, NDIM >::is_rd () pure virtual
Is there a density-dependent term?
Implemented in madness::DFTNuclearPotentialOp< T, NDIM >, madness::DFTCoulombOp< T, NDIM >, madness::DFTCoulombPeriodicOp< T, NDIM >, madness::XCFunctionalLDA< T, NDIM >, madness::DFTNuclearChargeDensityOp< T, NDIM >, madness::HartreeFockNuclearPotentialOp< T, NDIM >, madness::HartreeFockCoulombOp< T, NDIM >, madness::HartreeFockExchangeOp< T, NDIM >, and NuclearChargeDensityOp< T, NDIM >.
messageME()
template<typename T , int NDIM> void madness::EigSolverOp< T, NDIM >::messageME (std::string messageME) inline protected
References madness::EigSolverOp< T, NDIM >::_messageME, and madness::EigSolverOp< T, NDIM >::messageME().
Referenced by madness::DFTCoulombOp< T, NDIM >::DFTCoulombOp(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::DFTNuclearPotentialOp< T, NDIM >::DFTNuclearPotentialOp(), madness::HartreeFockCoulombOp< T, NDIM >::HartreeFockCoulombOp(), madness::HartreeFockExchangeOp< T, NDIM >::HartreeFockExchangeOp(), madness::HartreeFockNuclearPotentialOp< T, NDIM >::HartreeFockNuclearPotentialOp(), madness::XCFunctionalLDA< T, NDIM >::XCFunctionalLDA(), and madness::EigSolverOp< T, NDIM >::messageME().
messsageME()
template<typename T , int NDIM> std::string madness::EigSolverOp< T, NDIM >::messsageME () inline
References madness::EigSolverOp< T, NDIM >::_messageME.
multi_op_o()
template<typename T , int NDIM> virtual std::vector< funcT > madness::EigSolverOp< T, NDIM >::multi_op_o (const std::vector< funcT > & phis) inline virtual
Orbital-dependent portion of operator.
References madness::EigSolverOp< T, NDIM >::_world, madness::WorldGopInterface::fence(), madness::World::gop, madness::EigSolverOp< T, NDIM >::op_o(), and pi.
multi_op_r()
template<typename T , int NDIM> virtual std::vector< funcT > madness::EigSolverOp< T, NDIM >::multi_op_r (const funcT & rho, const std::vector< funcT > & phis) inline virtual
Density-dependent portion of operator.
References madness::EigSolverOp< T, NDIM >::_world, madness::WorldGopInterface::fence(), madness::World::gop, madness::EigSolverOp< T, NDIM >::op_r(), and pi.
op_o()
template<typename T , int NDIM> virtual funcT madness::EigSolverOp< T, NDIM >::op_o (const std::vector< funcT > & phis, const funcT & psi) inline virtual
Orbital-dependent portion of operator.
Reimplemented in madness::HartreeFockExchangeOp< T, NDIM >.
References madness::EigSolverOp< T, NDIM >::_world, and madness::func().
Referenced by madness::EigSolverOp< T, NDIM >::multi_op_o().
op_r()
template<typename T , int NDIM> virtual funcT madness::EigSolverOp< T, NDIM >::op_r (const funcT & rho, const funcT & psi) inline virtual
Density-dependent portion of operator.
Reimplemented in madness::DFTNuclearPotentialOp< T, NDIM >, madness::DFTCoulombOp< T, NDIM >, madness::DFTCoulombPeriodicOp< T, NDIM >, madness::XCFunctionalLDA< T, NDIM >, madness::DFTNuclearChargeDensityOp< T, NDIM >, and NuclearChargeDensityOp< T, NDIM >.
References madness::EigSolverOp< T, NDIM >::_world, and madness::func().
Referenced by madness::EigSolverOp< T, NDIM >::multi_op_r().
prepare_op()
template<typename T , int NDIM> virtual void madness::EigSolverOp< T, NDIM >::prepare_op (funcT rho) inline virtual
Build the potential from a density if a density-dependent operator.
thresh()
template<typename T , int NDIM> double madness::EigSolverOp< T, NDIM >::thresh () inline protected
References madness::EigSolverOp< T, NDIM >::_thresh.
Referenced by madness::DFTCoulombOp< T, NDIM >::DFTCoulombOp(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), and NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp().
Member Data Documentation
_coeff
template<typename T , int NDIM> double madness::EigSolverOp< T, NDIM >::_coeff private
Referenced by madness::EigSolverOp< T, NDIM >::coeff().
_messageME
template<typename T , int NDIM> std::string madness::EigSolverOp< T, NDIM >::_messageME private
Referenced by madness::EigSolverOp< T, NDIM >::messageME(), and madness::EigSolverOp< T, NDIM >::messsageME().
_thresh
template<typename T , int NDIM> double madness::EigSolverOp< T, NDIM >::_thresh private
Referenced by madness::EigSolverOp< T, NDIM >::thresh().
_world
template<typename T , int NDIM> World& madness::EigSolverOp< T, NDIM >::_world
Referenced by madness::EigSolverOp< T, NDIM >::multi_op_o(), madness::EigSolverOp< T, NDIM >::multi_op_r(), madness::EigSolverOp< T, NDIM >::op_o(), and madness::EigSolverOp< T, NDIM >::op_r().
The documentation for this class was generated from the following file:
eigsolver.h