MADNESS: madness::LocalPotentialOperator< T, NDIM > Class Template Reference
madness::LocalPotentialOperator< T, NDIM > Class Template Reference
#include <SCFOperators.h>
Public Member Functions
LocalPotentialOperator (World &world)
LocalPotentialOperator (World &world, const std::string info, const Function< T, NDIM > potential)
std::string info () const
print some information about this operator
T operator() (const Function< T, NDIM > &bra, const Function< T, NDIM > &ket) const
compute the matrix element <bra | op | ket>
Function< T, NDIM > operator() (const Function< T, NDIM > &ket) const
Tensor< T > operator() (const std::vector< Function< T, NDIM > > &vbra, const std::vector< Function< T, NDIM > > &vket) const
std::vector< Function< T, NDIM > > operator() (const std::vector< Function< T, NDIM > > &vket) const
void set_info (const std::string new_info)
void set_potential (const Function< T, NDIM > &new_potential)
Public Member Functions inherited from madness::SCFOperatorBase< T, NDIM >
SCFOperatorBase ()=default
SCFOperatorBase (std::shared_ptr< MacroTaskQ > taskq)
virtual ~SCFOperatorBase ()
virtual tensorT operator() (const vecfuncT &vbra, const vecfuncT &vket) const =0
compute the matrix <vbra | op | vket>
virtual vecfuncT operator() (const vecfuncT &vket) const =0
apply this operator on the argument vector of functions
Private Attributes
std::string info_str ="Vlocal"
Function< T, NDIM > potential
World & world
Additional Inherited Members
Public Types inherited from madness::SCFOperatorBase< T, NDIM >
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Public Attributes inherited from madness::SCFOperatorBase< T, NDIM >
nlohmann::json statistics
std::shared_ptr< MacroTaskQ > taskq =0
Constructor & Destructor Documentation
LocalPotentialOperator() [1/2]
template<typename T , std::size_t NDIM> madness::LocalPotentialOperator< T, NDIM >::LocalPotentialOperator (World & world) inline
LocalPotentialOperator() [2/2]
template<typename T , std::size_t NDIM> madness::LocalPotentialOperator< T, NDIM >::LocalPotentialOperator (World & world, const std::string info, const Function< T, NDIM > potential) inline
Member Function Documentation
info()
template<typename T , std::size_t NDIM> std::string madness::LocalPotentialOperator< T, NDIM >::info () const inline virtual
print some information about this operator
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::LocalPotentialOperator< T, NDIM >::info_str.
operator()() [1/4]
template<typename T , std::size_t NDIM> T madness::LocalPotentialOperator< T, NDIM >::operator() (const Function< T, NDIM > & bra, const Function< T, NDIM > & ket) const inline virtual
compute the matrix element <bra | op | ket>
Parameters
bra bra state
ket ket state
Returns
the matrix element <bra | op | ket>
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::inner(), and madness::LocalPotentialOperator< T, NDIM >::potential.
operator()() [2/4]
template<typename T , std::size_t NDIM> Function< T, NDIM > madness::LocalPotentialOperator< T, NDIM >::operator() (const Function< T, NDIM > & ket) const inline virtual
apply this operator on the argument function
Parameters
ket the argument function
Returns
op(ket)
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::LocalPotentialOperator< T, NDIM >::potential.
operator()() [3/4]
template<typename T , std::size_t NDIM> Tensor< T > madness::LocalPotentialOperator< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > & vbra, const std::vector< Function< T, NDIM > > & vket) const inline
References madness::matrix_inner(), madness::LocalPotentialOperator< T, NDIM >::potential, and madness::LocalPotentialOperator< T, NDIM >::world.
operator()() [4/4]
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::LocalPotentialOperator< T, NDIM >::operator() (const std::vector< Function< T, NDIM > > & vket) const inline
References madness::LocalPotentialOperator< T, NDIM >::potential, and madness::truncate().
set_info()
template<typename T , std::size_t NDIM> void madness::LocalPotentialOperator< T, NDIM >::set_info (const std::string new_info) inline
References madness::LocalPotentialOperator< T, NDIM >::info_str.
Referenced by madness::Nemo::make_fock_operator().
set_potential()
template<typename T , std::size_t NDIM> void madness::LocalPotentialOperator< T, NDIM >::set_potential (const Function< T, NDIM > & new_potential) inline
References madness::copy(), and madness::LocalPotentialOperator< T, NDIM >::potential.
Referenced by madness::Nemo::make_fock_operator().
Member Data Documentation
info_str
template<typename T , std::size_t NDIM> std::string madness::LocalPotentialOperator< T, NDIM >::info_str ="Vlocal" private
Referenced by madness::LocalPotentialOperator< T, NDIM >::info(), and madness::LocalPotentialOperator< T, NDIM >::set_info().
potential
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::LocalPotentialOperator< T, NDIM >::potential private
Referenced by madness::LocalPotentialOperator< T, NDIM >::operator()(), madness::LocalPotentialOperator< T, NDIM >::operator()(), madness::LocalPotentialOperator< T, NDIM >::operator()(), madness::LocalPotentialOperator< T, NDIM >::operator()(), and madness::LocalPotentialOperator< T, NDIM >::set_potential().
world
template<typename T , std::size_t NDIM> World& madness::LocalPotentialOperator< T, NDIM >::world private
Referenced by madness::LocalPotentialOperator< T, NDIM >::operator()().
The documentation for this class was generated from the following file:
SCFOperators.h