MADNESS: madness::MetaDataResults Class Reference
madness::MetaDataResults Class Reference
holds metadata of the calculation
#include <Results.h>
Public Member Functions
MetaDataResults (World &world)
std::string key () const override
void stop ()
nlohmann::json to_json () const override
serialize the results to a JSON object
Public Member Functions inherited from madness::ResultsBase
ResultsBase ()=default
virtual ~ResultsBase ()=default
Public Attributes
std::string finished_at =""
std::string git_hash =""
long mpi_size =-1
double time_begin =0.0
double time_end =0.0
Private Member Functions
std::string time_tag () const
borrowed from Adrian's MolDFTLib
Detailed Description
holds metadata of the calculation
create right before the calculation starts, stop() must be called after the calculation is finished
Constructor & Destructor Documentation
MetaDataResults()
madness::MetaDataResults::MetaDataResults (World & world) inline
References mpi_size, madness::World::size(), time_begin, and madness::wall_time().
Member Function Documentation
key()
std::string madness::MetaDataResults::key () const inline override virtual
Implements madness::ResultsBase.
stop()
void madness::MetaDataResults::stop () inline
References finished_at, time_end, time_tag(), and madness::wall_time().
time_tag()
std::string madness::MetaDataResults::time_tag () const inline private
borrowed from Adrian's MolDFTLib
Referenced by stop(), and to_json().
to_json()
nlohmann::json madness::MetaDataResults::to_json () const inline override virtual
serialize the results to a JSON object
Implements madness::ResultsBase.
References finished_at, git_hash, mpi_size, madness::ThreadPool::size(), time_begin, time_end, time_tag(), and madness::wall_time().
Member Data Documentation
finished_at
std::string madness::MetaDataResults::finished_at =""
Referenced by stop(), and to_json().
git_hash
std::string madness::MetaDataResults::git_hash =""
Referenced by to_json().
mpi_size
long madness::MetaDataResults::mpi_size =-1
Referenced by MetaDataResults(), and to_json().
time_begin
double madness::MetaDataResults::time_begin =0.0
Referenced by MetaDataResults(), and to_json().
time_end
double madness::MetaDataResults::time_end =0.0
Referenced by stop(), and to_json().
The documentation for this class was generated from the following file:
Results.h