MADNESS: KPeriodicBSHOperator Class Reference
KPeriodicBSHOperator Class Reference
Public Member Functions
KPeriodicBSHOperator (World &world, const double &kx, const double &ky, const double &kz, const double &L)
KPeriodicBSHOperator (World &world, const Vector< double, 3 > &kpt, const double &L)
vector_complex_function_3d apply (World &world, const vector_complex_function_3d &v, const tensor_real &evals, double shift=0.0)
Private Attributes
double kx
double ky
double kz
double L
complex_function_3d phase_m
complex_function_3d phase_p
Constructor & Destructor Documentation
KPeriodicBSHOperator() [1/2]
KPeriodicBSHOperator::KPeriodicBSHOperator (World & world, const double & kx, const double & ky, const double & kz, const double & L) inline
References I, kx, ky, kz, phase_m, and phase_p.
KPeriodicBSHOperator() [2/2]
KPeriodicBSHOperator::KPeriodicBSHOperator (World & world, const Vector< double, 3 > & kpt, const double & L) inline
References I, kx, ky, kz, phase_m, and phase_p.
Member Function Documentation
apply()
vector_complex_function_3d KPeriodicBSHOperator::apply (World & world, const vector_complex_function_3d & v, const tensor_real & evals, double shift = 0.0) inline
References apply(), madness::BaseTensor::dim(), e(), END_TIMER, kx, ky, kz, L, madness::mul(), madness::PeriodicBSHOperatorPtr3D(), phase_m, phase_p, shift, START_TIMER, madness::truncate(), v, and madness::vec().
Referenced by apply(), and update().
Member Data Documentation
kx
double KPeriodicBSHOperator::kx private
Referenced by KPeriodicBSHOperator(), KPeriodicBSHOperator(), and apply().
ky
double KPeriodicBSHOperator::ky private
Referenced by KPeriodicBSHOperator(), KPeriodicBSHOperator(), and apply().
kz
double KPeriodicBSHOperator::kz private
Referenced by KPeriodicBSHOperator(), KPeriodicBSHOperator(), and apply().
L
double KPeriodicBSHOperator::L private
Referenced by apply().
phase_m
complex_function_3d KPeriodicBSHOperator::phase_m private
Referenced by KPeriodicBSHOperator(), KPeriodicBSHOperator(), and apply().
phase_p
complex_function_3d KPeriodicBSHOperator::phase_p private
Referenced by KPeriodicBSHOperator(), KPeriodicBSHOperator(), and apply().
The documentation for this class was generated from the following file:
testperiodicdft.cc