MADNESS: madness::WorldProfile Class Reference
madness::WorldProfile Class Reference
Singleton-like class for holding profiling data and functionality.
#include <worldprofile.h>
Static Public Member Functions
static void clear ()
Clears all profiling information.
static WorldProfileEntry & get_entry (int id)
Returns a reference to the specified entry. Throws if id is invalid.
static void print (World &world)
Prints global profiling information. Global fence involved. Implemented in worldstuff.cc.
static int register_id (const char *classname, const char *function)
Returns id for the name, registering if necessary.
static int register_id (const char *name)
Returns id for the name, registering if necessary.
Static Private Member Functions
static int find (const std::string &name)
Returns id of the entry associated with the name. Returns -1 if not found;.
static std::vector< WorldProfileEntry > & nvitems ()
static void recv_stats (World &world, ProcessID p)
Private. Accumlates data from process into parallel statistics. Implemented in worldstuff.cc.
Static Private Attributes
static double cpu_start = madness::cpu_time()
static std::vector< WorldProfileEntry > items
static Spinlock mutex
static double wall_start = madness::wall_time()
Detailed Description
Singleton-like class for holding profiling data and functionality.
Use the macros PROFILE_FUNC, PROFILE_BLOCK, PROFILE_MEMBER_FUNC
Member Function Documentation
clear()
void madness::WorldProfile::clear () static
Clears all profiling information.
References cpu_start, madness::cpu_time(), fred(), mutex, nvitems(), wall_start, and madness::wall_time().
find()
int madness::WorldProfile::find (const std::string & name) static private
Returns id of the entry associated with the name. Returns -1 if not found;.
References MADNESS_EXCEPTION, madness::name(), and nvitems().
Referenced by print(), recv_stats(), register_id(), and register_id().
get_entry()
WorldProfileEntry & madness::WorldProfile::get_entry (int id) static
Returns a reference to the specified entry. Throws if id is invalid.
References MADNESS_EXCEPTION, and nvitems().
Referenced by madness::WorldProfileObj::WorldProfileObj(), madness::WorldProfileObj::~WorldProfileObj(), madness::WorldProfileObj::pause(), print(), and recv_stats().
nvitems()
std::vector< WorldProfileEntry > & madness::WorldProfile::nvitems () static private
References items.
Referenced by clear(), find(), get_entry(), register_id(), and register_id().
print()
void madness::WorldProfile::print (World & world) static
Prints global profiling information. Global fence involved. Implemented in worldstuff.cc.
References madness::WorldProfileEntry::count, cpu_start, madness::cpu_time(), madness::WorldProfileEntry::exclusivebytcmp(), madness::WorldProfileEntry::exclusivecmp(), madness::WorldGopInterface::fence(), find(), get_entry(), madness::World::gop, madness::WorldProfileEntry::inclusivebytcmp(), madness::WorldProfileEntry::inclusivecmp(), items, me, madness::World::rank(), recv_stats(), madness::ProfileStat< T >::sum, v, wall_start, madness::wall_time(), and madness::WorldProfileEntry::xcpu.
Referenced by madness::print_stats(), and realmain().
recv_stats()
void madness::WorldProfile::recv_stats (World & world, ProcessID p) static private
Private. Accumlates data from process into parallel statistics. Implemented in worldstuff.cc.
References d, find(), get_entry(), madness::name(), p(), register_id(), madness::World::size(), and v.
Referenced by print().
register_id() [1/2]
int madness::WorldProfile::register_id (const char * classname, const char * function) static
Returns id for the name, registering if necessary.
References find(), fred(), function(), mutex, madness::name(), and nvitems().
register_id() [2/2]
int madness::WorldProfile::register_id (const char * name) static
Returns id for the name, registering if necessary.
References find(), fred(), mutex, madness::name(), and nvitems().
Referenced by recv_stats().
Member Data Documentation
cpu_start
double madness::WorldProfile::cpu_start = madness::cpu_time() static private
Referenced by clear(), and print().
items
std::vector< WorldProfileEntry > madness::WorldProfile::items static private
Referenced by nvitems(), and print().
mutex
Spinlock madness::WorldProfile::mutex static private
Referenced by clear(), register_id(), and register_id().
wall_start
double madness::WorldProfile::wall_start = madness::wall_time() static private
Referenced by clear(), and print().
The documentation for this class was generated from the following files:
worldprofile.h
worldprofile.cc