MADNESS: MyDerivativeOperator< T, NDIM > Class Template Reference
MyDerivativeOperator< T, NDIM > Class Template Reference
Public Member Functions
MyDerivativeOperator (World &world, const int axis1)
std::string info () const
print some information about this operator
T operator() (const functionT &bra, const functionT &ket) const
compute the matrix element <bra | op | ket>
functionT operator() (const functionT &ket) const
tensorT operator() (const vecfuncT &vbra, const vecfuncT &vket) const
compute the matrix <vbra | op | vket>
vecfuncT operator() (const vecfuncT &vket) const
apply this operator on the argument vector of functions
void set_ble1 ()
void set_bspline1 ()
Public Member Functions inherited from madness::SCFOperatorBase< T, NDIM >
SCFOperatorBase ()=default
SCFOperatorBase (std::shared_ptr< MacroTaskQ > taskq)
virtual ~SCFOperatorBase ()
Private Types
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Private Attributes
int axis
bool ble =false
bool bsp =false
World & world
Additional Inherited Members
Public Types inherited from madness::SCFOperatorBase< T, NDIM >
typedef Function< T, NDIM > functionT
typedef Tensor< T > tensorT
typedef std::vector< functionT > vecfuncT
Public Attributes inherited from madness::SCFOperatorBase< T, NDIM >
nlohmann::json statistics
std::shared_ptr< MacroTaskQ > taskq =0
Member Typedef Documentation
functionT
template<typename T , std::size_t NDIM> typedef Function<T,NDIM> MyDerivativeOperator< T, NDIM >::functionT private
tensorT
template<typename T , std::size_t NDIM> typedef Tensor<T> MyDerivativeOperator< T, NDIM >::tensorT private
vecfuncT
template<typename T , std::size_t NDIM> typedef std::vector<functionT> MyDerivativeOperator< T, NDIM >::vecfuncT private
Constructor & Destructor Documentation
MyDerivativeOperator()
template<typename T , std::size_t NDIM> MyDerivativeOperator< T, NDIM >::MyDerivativeOperator (World & world, const int axis1) inline
Member Function Documentation
info()
template<typename T , std::size_t NDIM> std::string MyDerivativeOperator< T, NDIM >::info () const inline virtual
print some information about this operator
Implements madness::SCFOperatorBase< T, NDIM >.
References MyDerivativeOperator< T, NDIM >::axis.
operator()() [1/4]
template<typename T , std::size_t NDIM> T MyDerivativeOperator< T, NDIM >::operator() (const functionT & bra, const functionT & ket) const inline virtual
compute the matrix element <bra | op | ket>
Parameters
bra bra state
ket ket state
Returns
the matrix element <bra | op | ket>
Implements madness::SCFOperatorBase< T, NDIM >.
References MyDerivativeOperator< T, NDIM >::operator()().
operator()() [2/4]
template<typename T , std::size_t NDIM> functionT MyDerivativeOperator< T, NDIM >::operator() (const functionT & ket) const inline virtual
apply this operator on the argument function
Parameters
ket the argument function
Returns
op(ket)
Implements madness::SCFOperatorBase< T, NDIM >.
References MyDerivativeOperator< T, NDIM >::operator()().
Referenced by MyDerivativeOperator< T, NDIM >::operator()(), MyDerivativeOperator< T, NDIM >::operator()(), and MyDerivativeOperator< T, NDIM >::operator()().
operator()() [3/4]
template<typename T , std::size_t NDIM> tensorT MyDerivativeOperator< T, NDIM >::operator() (const vecfuncT & vbra, const vecfuncT & vket) const inline virtual
compute the matrix <vbra | op | vket>
Parameters
vbra vector of bra states
vket vector of ket states
Returns
the matrix <vbra | op | vket>
Implements madness::SCFOperatorBase< T, NDIM >.
References matrix_inner(), MyDerivativeOperator< T, NDIM >::operator()(), and MyDerivativeOperator< T, NDIM >::world.
operator()() [4/4]
template<typename T , std::size_t NDIM> vecfuncT MyDerivativeOperator< T, NDIM >::operator() (const vecfuncT & vket) const inline virtual
apply this operator on the argument vector of functions
Parameters
vket argument vector
Returns
op(vket)
Implements madness::SCFOperatorBase< T, NDIM >.
References madness::apply(), MyDerivativeOperator< T, NDIM >::axis, MyDerivativeOperator< T, NDIM >::ble, MyDerivativeOperator< T, NDIM >::bsp, madness::WorldGopInterface::fence(), madness::World::gop, gradop, and MyDerivativeOperator< T, NDIM >::world.
set_ble1()
template<typename T , std::size_t NDIM> void MyDerivativeOperator< T, NDIM >::set_ble1 () inline
References MyDerivativeOperator< T, NDIM >::ble.
set_bspline1()
template<typename T , std::size_t NDIM> void MyDerivativeOperator< T, NDIM >::set_bspline1 () inline
References MyDerivativeOperator< T, NDIM >::bsp.
Member Data Documentation
axis
template<typename T , std::size_t NDIM> int MyDerivativeOperator< T, NDIM >::axis private
Referenced by MyDerivativeOperator< T, NDIM >::info(), and MyDerivativeOperator< T, NDIM >::operator()().
ble
template<typename T , std::size_t NDIM> bool MyDerivativeOperator< T, NDIM >::ble =false private
Referenced by MyDerivativeOperator< T, NDIM >::operator()(), and MyDerivativeOperator< T, NDIM >::set_ble1().
bsp
template<typename T , std::size_t NDIM> bool MyDerivativeOperator< T, NDIM >::bsp =false private
Referenced by MyDerivativeOperator< T, NDIM >::operator()(), and MyDerivativeOperator< T, NDIM >::set_bspline1().
world
template<typename T , std::size_t NDIM> World& MyDerivativeOperator< T, NDIM >::world private
Referenced by MyDerivativeOperator< T, NDIM >::operator()(), and MyDerivativeOperator< T, NDIM >::operator()().
The documentation for this class was generated from the following file:
dirac-hatom.cc