MADNESS: FermiNucDistFunctor Class Reference
FermiNucDistFunctor Class Reference
Public Member Functions
FermiNucDistFunctor (int &Z, coord_3d R, double bohr_rad)
double operator() (const coord_3d &r) const
void print_details (World &world)
madness::Level special_level () const final
Override this to change the minimum level of refinement at special points (default is 6)
std::vector< coord_3d > special_points () const final
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
int m_A
double m_C
std::vector< coord_3d > m_R
double m_T
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
FermiNucDistFunctor()
FermiNucDistFunctor::FermiNucDistFunctor (int & Z, coord_3d R, double bohr_rad) inline
References m_A, m_C, m_R, m_T, PI, madness::constants::pi, pow(), R, and Z.
Member Function Documentation
operator()()
double FermiNucDistFunctor::operator() (const coord_3d & r) const inline
References m_C, m_R, and m_T.
print_details()
void FermiNucDistFunctor::print_details (World & world) inline
References PI, madness::constants::pi, pow(), madness::World::rank(), T(), and xi.
special_level()
madness::Level FermiNucDistFunctor::special_level () const inline final virtual
Override this to change the minimum level of refinement at special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
special_points()
std::vector< coord_3d > FermiNucDistFunctor::special_points () const inline final virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References m_R.
Member Data Documentation
m_A
int FermiNucDistFunctor::m_A private
Referenced by FermiNucDistFunctor().
m_C
double FermiNucDistFunctor::m_C private
Referenced by FermiNucDistFunctor(), and operator()().
m_R
std::vector<coord_3d> FermiNucDistFunctor::m_R private
Referenced by FermiNucDistFunctor(), operator()(), and special_points().
m_T
double FermiNucDistFunctor::m_T private
Referenced by FermiNucDistFunctor(), and operator()().
The documentation for this class was generated from the following file:
DF.cc