MADNESS: SafeMPI::Group Class Reference
SafeMPI::Group Class Reference
#include <safempi.h>
Classes
struct Impl
Public Member Functions
Group (const Group &other)
MPI_Group group () const
Group Incl (int n, const int *ranks) const
void Translate_ranks (int nproc, const int *ranks1, const Group &grp2, int *ranks2) const
Private Member Functions
Group ()
Group (const std::shared_ptr< Impl > &p)
Group (MPI_Comm comm)
Private Attributes
std::shared_ptr< Impl > pimpl
Friends
class Intracomm
Detailed Description
Wrapper around MPI_Group. Has a shallow copy constructor. Usually deep copy is not needed, but can be created via Group::Incl().
Constructor & Destructor Documentation
Group() [1/4]
SafeMPI::Group::Group (const Group & other) inline
Group() [2/4]
SafeMPI::Group::Group () inline private
Group() [3/4]
SafeMPI::Group::Group (MPI_Comm comm) inline private
Group() [4/4]
SafeMPI::Group::Group (const std::shared_ptr< Impl > & p) inline private
Member Function Documentation
group()
MPI_Group SafeMPI::Group::group () const inline
References MADNESS_ASSERT, and pimpl.
Referenced by SafeMPI::Intracomm::Create().
Incl()
Group SafeMPI::Group::Incl (int n, const int * ranks) const inline
References pimpl.
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::replicate_on_hosts(), test_mpi_group(), and test_multi_world().
Translate_ranks()
void SafeMPI::Group::Translate_ranks (int nproc, const int * ranks1, const Group & grp2, int * ranks2) const inline
References MADNESS_ASSERT, MADNESS_MPI_TEST, MPI_Group_translate_ranks(), and pimpl.
Referenced by madness::WorldAmInterface::WorldAmInterface().
Friends And Related Symbol Documentation
Intracomm
friend class Intracomm friend
Member Data Documentation
pimpl
std::shared_ptr<Impl> SafeMPI::Group::pimpl private
Referenced by group(), Incl(), and Translate_ranks().
The documentation for this class was generated from the following file:
safempi.h