MADNESS: madness::GTHPseudopotential< Q > Class Template Reference
madness::GTHPseudopotential< Q > Class Template Reference
#include <gth_pseudopotential.h>
Public Member Functions
GTHPseudopotential (World &world, Molecule molecule)
std::vector< Function< Q, 3 > > apply_potential (World &world, const real_function_3d &potential, const std::vector< Function< Q, 3 > > &psi, const tensorT &occ, Q &enl)
std::vector< Function< Q, 3 > > apply_potential_simple (World &world, const real_function_3d &potential, const std::vector< Function< Q, 3 > > &psi, const tensorT &occ, Q &enl)
void load_pseudo_from_file (World &world, const std::string filename)
void make_pseudo_potential (World &world)
void reproject (int k, double thresh)
real_function_3d vlocalpot ()
Public Attributes
std::vector< unsigned int > atoms_with_projectors
std::array< real_tensor, 118 > hlij
std::array< real_tensor, 118 > klij
std::array< real_tensor, 118 > localp
Molecule molecule
std::array< real_tensor, 118 > radii
real_function_3d vlocalp
Constructor & Destructor Documentation
GTHPseudopotential()
template<typename Q > madness::GTHPseudopotential< Q >::GTHPseudopotential (World & world, Molecule molecule) inline
Member Function Documentation
apply_potential()
template<typename Q > std::vector< Function< Q, 3 > > madness::GTHPseudopotential< Q >::apply_potential (World & world, const real_function_3d & potential, const std::vector< Function< Q, 3 > > & psi, const tensorT & occ, Q & enl) inline
References madness::Atom::atomic_number, madness::GTHPseudopotential< Q >::atoms_with_projectors, madness::compress(), madness::BaseTensor::dim(), e(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::Molecule::get_atom(), madness::Atom::get_coords(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, madness::GTHPseudopotential< Q >::hlij, m, madness::matrix_inner(), madness::GTHPseudopotential< Q >::molecule, madness::mul_sparse(), madness::ProjRLMStore::nlmproj(), potential(), psi(), Q(), madness::GTHPseudopotential< Q >::radii, madness::Tensor< T >::reshape(), madness::BaseTensor::size(), thresh, madness::transform(), and madness::truncate().
Referenced by MiniDFT::doit().
apply_potential_simple()
template<typename Q > std::vector< Function< Q, 3 > > madness::GTHPseudopotential< Q >::apply_potential_simple (World & world, const real_function_3d & potential, const std::vector< Function< Q, 3 > > & psi, const tensorT & occ, Q & enl) inline
References std::abs(), madness::Atom::atomic_number, madness::GTHPseudopotential< Q >::atoms_with_projectors, madness::BaseTensor::dim(), e(), madness::Molecule::get_atom(), madness::Atom::get_coords(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::GTHPseudopotential< Q >::hlij, m, madness::GTHPseudopotential< Q >::molecule, madness::mul_sparse(), madness::ProjRLMStore::nlmproj(), potential(), psi(), madness::GTHPseudopotential< Q >::radii, and thresh.
load_pseudo_from_file()
template<typename Q > void madness::GTHPseudopotential< Q >::load_pseudo_from_file (World & world, const std::string filename) inline
References madness::Atom::atomic_number, debug, madness::filename, madness::Molecule::get_atom(), madness::GTHPseudopotential< Q >::hlij, madness::GTHPseudopotential< Q >::klij, madness::GTHPseudopotential< Q >::localp, MADNESS_EXCEPTION, madness::GTHPseudopotential< Q >::molecule, madness::name(), madness::Molecule::natom(), madness::GTHPseudopotential< Q >::radii, madness::World::rank(), and madness::symbol_to_atomic_number().
Referenced by madness::GTHPseudopotential< Q >::make_pseudo_potential().
make_pseudo_potential()
template<typename Q > void madness::GTHPseudopotential< Q >::make_pseudo_potential (World & world) inline
References madness::Atom::atomic_number, madness::GTHPseudopotential< Q >::atoms_with_projectors, madness::Function< T, NDIM >::compress(), madness::Function< T, NDIM >::gaxpy(), madness::Molecule::get_atom(), madness::Atom::get_coords(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), madness::GTHPseudopotential< Q >::localp, madness::GTHPseudopotential< Q >::molecule, madness::Molecule::natom(), madness::Atom::pseudo_atom, madness::GTHPseudopotential< Q >::radii, truncate_mode, and madness::GTHPseudopotential< Q >::vlocalp.
Referenced by MiniDFT::doit().
reproject()
template<typename Q > void madness::GTHPseudopotential< Q >::reproject (int k, double thresh) inline
References k, madness::project(), thresh, and madness::GTHPseudopotential< Q >::vlocalp.
Referenced by MiniDFT::doit().
vlocalpot()
template<typename Q > real_function_3d madness::GTHPseudopotential< Q >::vlocalpot () inline
References madness::GTHPseudopotential< Q >::vlocalp.
Member Data Documentation
atoms_with_projectors
template<typename Q > std::vector<unsigned int> madness::GTHPseudopotential< Q >::atoms_with_projectors
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), and madness::GTHPseudopotential< Q >::make_pseudo_potential().
hlij
template<typename Q > std::array<real_tensor,118> madness::GTHPseudopotential< Q >::hlij
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), and madness::GTHPseudopotential< Q >::load_pseudo_from_file().
klij
template<typename Q > std::array<real_tensor,118> madness::GTHPseudopotential< Q >::klij
Referenced by madness::GTHPseudopotential< Q >::load_pseudo_from_file().
localp
template<typename Q > std::array<real_tensor,118> madness::GTHPseudopotential< Q >::localp
Referenced by madness::GTHPseudopotential< Q >::load_pseudo_from_file(), and madness::GTHPseudopotential< Q >::make_pseudo_potential().
molecule
template<typename Q > Molecule madness::GTHPseudopotential< Q >::molecule
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), and madness::GTHPseudopotential< Q >::make_pseudo_potential().
radii
template<typename Q > std::array<real_tensor,118> madness::GTHPseudopotential< Q >::radii
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), and madness::GTHPseudopotential< Q >::make_pseudo_potential().
vlocalp
template<typename Q > real_function_3d madness::GTHPseudopotential< Q >::vlocalp
Referenced by MiniDFT::doit(), madness::GTHPseudopotential< Q >::make_pseudo_potential(), madness::GTHPseudopotential< Q >::reproject(), and madness::GTHPseudopotential< Q >::vlocalpot().
The documentation for this class was generated from the following file:
gth_pseudopotential.h