MADNESS: madness::SpectralPropagatorGaussLobatto Class Reference
madness::SpectralPropagatorGaussLobatto Class Reference
#include <spectralprop.h>
Public Member Functions
SpectralPropagatorGaussLobatto (int NPT)
template<typename uT , typename expLT , typename NT >
uT step (double t, double Delta, const uT &u0, const expLT &expL, const NT &N, const double eps=1e-12, bool doprint=false)
Private Member Functions
double p (int i, double t)
template<typename uT >
uT u (double dt, const std::vector< uT > &v)
Private Attributes
const int NPT
std::vector< double > w
std::vector< double > x
Constructor & Destructor Documentation
SpectralPropagatorGaussLobatto()
madness::SpectralPropagatorGaussLobatto::SpectralPropagatorGaussLobatto (int NPT) inline
References MADNESS_ASSERT, NPT, w, and x.
Member Function Documentation
p()
double madness::SpectralPropagatorGaussLobatto::p (int i, double t) inline private
References NPT, and x.
Referenced by u().
step()
template<typename uT , typename expLT , typename NT > uT madness::SpectralPropagatorGaussLobatto::step (double t, double Delta, const uT & u0, const expLT & expL, const NT & N, const double eps = 1e-12, bool doprint = false) inline
References madness::distance(), expL(), k, N, NPT, madness::print(), u(), v, w, and x.
u()
template<typename uT > uT madness::SpectralPropagatorGaussLobatto::u (double dt, const std::vector< uT > & v) inline private
References NPT, p(), and v.
Referenced by step().
Member Data Documentation
NPT
const int madness::SpectralPropagatorGaussLobatto::NPT private
Referenced by SpectralPropagatorGaussLobatto(), p(), step(), and u().
w
std::vector<double> madness::SpectralPropagatorGaussLobatto::w private
Referenced by SpectralPropagatorGaussLobatto(), and step().
x
std::vector<double> madness::SpectralPropagatorGaussLobatto::x private
Referenced by SpectralPropagatorGaussLobatto(), p(), and step().
The documentation for this class was generated from the following file:
spectralprop.h