MADNESS: madness::Future< std::vector< Future< T > > > Class Template Reference
madness::Future< std::vector< Future< T > > > Class Template Reference
Specialization of Future for a vector of Futures.
#include <future.h>
Public Member Functions
Future ()
Future (const archive::BufferInputArchive &input_arch)
Future (const vectorT &v)
vectorT & get ()
Access the vector of futures.
const vectorT & get () const
Access the const vector of futures.
operator const vectorT & () const
Access the const vector of futures.
operator vectorT & ()
Access the vector of futures.
bool probe () const
Check if all of the futures in the vector have been assigned.
Public Member Functions inherited from madness::DependencyInterface
DependencyInterface (int ndep, const char *caller)
DependencyInterface (int ndep=0)
virtual ~DependencyInterface ()
Destructor.
void dec ()
Decrement the number of dependencies and invoke the callback if ndepend==0.
void dec_debug (const char *caller)
void inc ()
Increment the number of dependencies.
void inc_debug (const char *caller)
Same as inc(), but keeps track of caller; calling dec_debug() will signal error if no matching inc_debug() had been invoked
int ndep () const
Returns the number of unsatisfied dependencies.
void notify ()
Invoked by callbacks to notify of dependencies being satisfied.
void notify_debug (const char *caller)
Overload of CallbackInterface::notify_debug(), updates dec()
bool probe () const
Returns true if ndepend == 0 (no unsatisfied dependencies).
void register_callback (CallbackInterface *callback)
Registers a callback that will be executed when ndepend==0; immediately invoked if ndepend==0.
void register_final_callback (CallbackInterface *callback)
Registers the final callback to be executed when ndepend==0; immediately invoked if ndepend==0.
Public Member Functions inherited from madness::CallbackInterface
virtual ~CallbackInterface ()
Private Types
typedef std::vector< Future< T > > vectorT
Alias for a vector of futures.
Private Attributes
vectorT v
The vector of futures.
Additional Inherited Members
Protected Member Functions inherited from madness::CallbackInterface
virtual void notify_debug_impl (const char *caller)
Private Member Functions inherited from NO_DEFAULTS
NO_DEFAULTS ()
NO_DEFAULTS (const NO_DEFAULTS &)=delete
NO_DEFAULTS (NO_DEFAULTS &&)=delete
NO_DEFAULTS & operator= (const NO_DEFAULTS &)=delete
NO_DEFAULTS & operator= (NO_DEFAULTS &&)=delete
Detailed Description
template<typename T>
class madness::Future< std::vector< Future< T > > >
Specialization of Future for a vector of Futures.
Enables passing a vector of futures into a task and having the dependencies correctly tracked. Does not directly support most operations that other futures do; these are the responsibility of the individual futures in the vector.
Template Parameters
T The type of future.
Member Typedef Documentation
vectorT
template<typename T > typedef std::vector< Future<T> > madness::Future< std::vector< Future< T > > >::vectorT private
Alias for a vector of futures.
Constructor & Destructor Documentation
Future() [1/3]
template<typename T > madness::Future< std::vector< Future< T > > >::Future () inline
Future() [2/3]
template<typename T > madness::Future< std::vector< Future< T > > >::Future (const vectorT & v) inline
Todo:
Brief description needed.
Todo:
Description needed.
Parameters
[in] v Vector of something...
References madness::DependencyInterface::register_callback(), and v.
Future() [3/3]
template<typename T > madness::Future< std::vector< Future< T > > >::Future (const archive::BufferInputArchive & input_arch) inline explicit
Todo:
Brief description needed.
Todo:
Description needed.
Parameters
[in] input_arch Description needed.
Todo:
Not implemented. If this is deliberate, specify why and change the tag to \attention.
References v.
Member Function Documentation
get() [1/2]
template<typename T > vectorT & madness::Future< std::vector< Future< T > > >::get () inline
Access the vector of futures.
Returns
The vector of futures.
References v.
get() [2/2]
template<typename T > const vectorT & madness::Future< std::vector< Future< T > > >::get () const inline
Access the const vector of futures.
Returns
The vector of futures.
References v.
operator const vectorT &()
template<typename T > madness::Future< std::vector< Future< T > > >::operator const vectorT & () const inline
Access the const vector of futures.
Returns
The vector of futures.
References madness::Future< T >::get().
operator vectorT &()
template<typename T > madness::Future< std::vector< Future< T > > >::operator vectorT & () inline
Access the vector of futures.
Returns
The vector of futures.
References madness::Future< T >::get().
probe()
template<typename T > bool madness::Future< std::vector< Future< T > > >::probe () const inline
Check if all of the futures in the vector have been assigned.
Returns
True if all futures have been assigned; false otherwise.
References madness::DependencyInterface::probe().
Member Data Documentation
v
template<typename T > vectorT madness::Future< std::vector< Future< T > > >::v private
The vector of futures.
The documentation for this class was generated from the following file:
future.h