MADNESS: madness::MutexReaderWriter Class Reference
madness::MutexReaderWriter Class Reference
#include <worldmutex.h>
Public Member Functions
MutexReaderWriter ()
virtual ~MutexReaderWriter ()
void convert_read_lock_to_write_lock () const
Converts read to write lock without releasing the read lock.
void convert_write_lock_to_read_lock () const
Always succeeds immediately.
void lock (int lockmode) const
void read_lock () const
void read_unlock () const
bool try_convert_read_lock_to_write_lock () const
bool try_lock (int lockmode) const
bool try_read_lock () const
bool try_write_lock () const
void unlock (int lockmode) const
void write_lock () const
void write_unlock () const
Static Public Attributes
static const int NOLOCK =0
static const int READLOCK =1
static const int WRITELOCK =2
Private Attributes
int nreader
bool writeflag
Additional Inherited Members
Private Member Functions inherited from madness::Spinlock
Spinlock (int junk=0)
Make and initialize a spinlock ... initial state is unlocked.
virtual ~Spinlock ()
void lock () const
Acquire the spinlock waiting if necessary.
bool try_lock () const
Try to acquire the spinlock ... return true on success, false on failure.
void unlock () const
Free a spinlock owned by this thread.
Private Member Functions inherited from NO_DEFAULTS
NO_DEFAULTS ()
NO_DEFAULTS (const NO_DEFAULTS &)=delete
NO_DEFAULTS (NO_DEFAULTS &&)=delete
NO_DEFAULTS & operator= (const NO_DEFAULTS &)=delete
NO_DEFAULTS & operator= (NO_DEFAULTS &&)=delete
Constructor & Destructor Documentation
MutexReaderWriter()
madness::MutexReaderWriter::MutexReaderWriter () inline
~MutexReaderWriter()
virtual madness::MutexReaderWriter::~MutexReaderWriter () inline virtual
Member Function Documentation
convert_read_lock_to_write_lock()
void madness::MutexReaderWriter::convert_read_lock_to_write_lock () const inline
Converts read to write lock without releasing the read lock.
Note that deadlock is guaranteed if two+ threads wait to convert at the same time.
References madness::cpu_relax(), and try_convert_read_lock_to_write_lock().
Referenced by madness::Hash_private::HashAccessor< hashT, lockmode >::convert_read_lock_to_write_lock().
convert_write_lock_to_read_lock()
void madness::MutexReaderWriter::convert_write_lock_to_read_lock () const inline
Always succeeds immediately.
References nreader, and writeflag.
lock()
void madness::MutexReaderWriter::lock (int lockmode) const inline
References madness::cpu_relax(), and madness::Spinlock::try_lock().
read_lock()
void madness::MutexReaderWriter::read_lock () const inline
References madness::cpu_relax(), and try_read_lock().
read_unlock()
void madness::MutexReaderWriter::read_unlock () const inline
References nreader.
Referenced by unlock().
try_convert_read_lock_to_write_lock()
bool madness::MutexReaderWriter::try_convert_read_lock_to_write_lock () const inline
References nreader, and writeflag.
Referenced by convert_read_lock_to_write_lock().
try_lock()
bool madness::MutexReaderWriter::try_lock (int lockmode) const inline
References MADNESS_EXCEPTION, NOLOCK, READLOCK, try_read_lock(), try_write_lock(), and WRITELOCK.
try_read_lock()
bool madness::MutexReaderWriter::try_read_lock () const inline
References nreader, and writeflag.
Referenced by read_lock(), and try_lock().
try_write_lock()
bool madness::MutexReaderWriter::try_write_lock () const inline
References nreader, and writeflag.
Referenced by try_lock(), and write_lock().
unlock()
void madness::MutexReaderWriter::unlock (int lockmode) const inline
References MADNESS_EXCEPTION, NOLOCK, read_unlock(), READLOCK, write_unlock(), and WRITELOCK.
Referenced by madness::Hash_private::HashAccessor< hashT, lockmode >::release().
write_lock()
void madness::MutexReaderWriter::write_lock () const inline
References madness::cpu_relax(), and try_write_lock().
write_unlock()
void madness::MutexReaderWriter::write_unlock () const inline
References writeflag.
Referenced by unlock().
Member Data Documentation
NOLOCK
const int madness::MutexReaderWriter::NOLOCK =0 static
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::try_erase(), try_lock(), and unlock().
nreader
int madness::MutexReaderWriter::nreader mutable private
Referenced by convert_write_lock_to_read_lock(), read_unlock(), try_convert_read_lock_to_write_lock(), try_read_lock(), and try_write_lock().
READLOCK
const int madness::MutexReaderWriter::READLOCK =1 static
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), try_lock(), and unlock().
writeflag
bool madness::MutexReaderWriter::writeflag mutable private
Referenced by convert_write_lock_to_read_lock(), try_convert_read_lock_to_write_lock(), try_read_lock(), try_write_lock(), and write_unlock().
WRITELOCK
const int madness::MutexReaderWriter::WRITELOCK =2 static
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), try_lock(), and unlock().
The documentation for this class was generated from the following file:
worldmutex.h