MADNESS: madness::MacroTask< taskT > Class Template Reference
madness::MacroTask< taskT > Class Template Reference
#include <macrotaskq.h>
Classes
struct is_vector
struct is_vector< std::vector< Q > >
class MacroTaskInternal
Public Member Functions
MacroTask (World &world, taskT &task)
constructor takes the task, but no arguments to the task
MacroTask (World &world, taskT &task, const MacroTaskQFactory factory)
constructor takes task and a taskq factory for customization, immediate execution
MacroTask (World &world, taskT &task, std::shared_ptr< MacroTaskQ > taskq_ptr)
constructor takes the task, and a taskq, execution is not immediate
std::shared_ptr< MacroTaskQ > get_taskq () const
template<typename ... Ts>
resultT operator() (const Ts &... args)
this mimicks the original call to the task functor, called from the universe
MacroTask & set_debug (const bool value)
Private Types
typedef taskT::argtupleT argtupleT
using partitionT = MacroTaskPartitioner::partitionT
typedef Cloud::recordlistT recordlistT
typedef taskT::resultT resultT
Private Member Functions
recordlistT prepare_output_records (Cloud &cloud, resultT &result)
store pointers to the result WorldObject in the cloud and return the recordlist
Private Attributes
bool debug =false
bool immediate_execution =false
taskT task
std::shared_ptr< MacroTaskQ > taskq_ptr
World & world
Member Typedef Documentation
argtupleT
template<typename taskT > typedef taskT::argtupleT madness::MacroTask< taskT >::argtupleT private
partitionT
template<typename taskT > using madness::MacroTask< taskT >::partitionT = MacroTaskPartitioner::partitionT private
recordlistT
template<typename taskT > typedef Cloud::recordlistT madness::MacroTask< taskT >::recordlistT private
resultT
template<typename taskT > typedef taskT::resultT madness::MacroTask< taskT >::resultT private
Constructor & Destructor Documentation
MacroTask() [1/3]
template<typename taskT > madness::MacroTask< taskT >::MacroTask (World & world, taskT & task) inline explicit
constructor takes the task, but no arguments to the task
References madness::MacroTask< taskT >::immediate_execution.
MacroTask() [2/3]
template<typename taskT > madness::MacroTask< taskT >::MacroTask (World & world, taskT & task, const MacroTaskQFactory factory) inline explicit
constructor takes task and a taskq factory for customization, immediate execution
References madness::MacroTask< taskT >::immediate_execution.
MacroTask() [3/3]
template<typename taskT > madness::MacroTask< taskT >::MacroTask (World & world, taskT & task, std::shared_ptr< MacroTaskQ > taskq_ptr) inline explicit
constructor takes the task, and a taskq, execution is not immediate
References madness::MacroTask< taskT >::debug, madness::MacroTask< taskT >::immediate_execution, madness::MacroTaskInfo::to_cloud_storage_policy(), and madness::MacroTask< taskT >::world.
Member Function Documentation
get_taskq()
template<typename taskT > std::shared_ptr< MacroTaskQ > madness::MacroTask< taskT >::get_taskq () const inline
References madness::MacroTask< taskT >::taskq_ptr.
Referenced by madness::CC2::solve_mp2_coupled().
operator()()
template<typename taskT > template<typename ... Ts> resultT madness::MacroTask< taskT >::operator() (const Ts &... args) inline
this mimicks the original call to the task functor, called from the universe
store all input to the cloud, create output Function<T,NDIM> in the universe, create the batched task and shove it into the taskq. Possibly execute the taskq.
References madness::MacroTask< taskT >::debug, madness::MacroTask< taskT >::immediate_execution, madness::MacroTask< taskT >::prepare_output_records(), madness::print(), madness::World::rank(), madness::World::size(), madness::MacroTask< taskT >::task, madness::MacroTask< taskT >::taskq_ptr, and madness::MacroTask< taskT >::world.
prepare_output_records()
template<typename taskT > recordlistT madness::MacroTask< taskT >::prepare_output_records (Cloud & cloud, resultT & result) inline private
store pointers to the result WorldObject in the cloud and return the recordlist
References madness::MacroTask< taskT >::debug, madness::get_impl(), MADNESS_EXCEPTION, madness::print(), madness::Cloud::store(), v, and madness::MacroTask< taskT >::world.
Referenced by madness::MacroTask< taskT >::operator()().
set_debug()
template<typename taskT > MacroTask & madness::MacroTask< taskT >::set_debug (const bool value) inline
References madness::MacroTask< taskT >::debug.
Referenced by test_immediate(), and test_task1().
Member Data Documentation
debug
template<typename taskT > bool madness::MacroTask< taskT >::debug =false private
Referenced by madness::MacroTask< taskT >::MacroTask(), madness::MacroTask< taskT >::operator()(), madness::MacroTask< taskT >::prepare_output_records(), madness::MacroTask< taskT >::MacroTaskInternal::run(), and madness::MacroTask< taskT >::set_debug().
immediate_execution
template<typename taskT > bool madness::MacroTask< taskT >::immediate_execution =false private
Referenced by madness::MacroTask< taskT >::MacroTask(), madness::MacroTask< taskT >::MacroTask(), madness::MacroTask< taskT >::MacroTask(), and madness::MacroTask< taskT >::operator()().
task
template<typename taskT > taskT madness::MacroTask< taskT >::task private
Referenced by madness::MacroTask< taskT >::operator()().
taskq_ptr
template<typename taskT > std::shared_ptr<MacroTaskQ> madness::MacroTask< taskT >::taskq_ptr private
Referenced by madness::MacroTask< taskT >::get_taskq(), and madness::MacroTask< taskT >::operator()().
world
template<typename taskT > World& madness::MacroTask< taskT >::world private
Referenced by madness::MacroTask< taskT >::MacroTask(), madness::MacroTask< taskT >::operator()(), and madness::MacroTask< taskT >::prepare_output_records().
The documentation for this class was generated from the following file:
macrotaskq.h