MADNESS: madness::Complex_CIS_Parameters Class Reference
madness::Complex_CIS_Parameters Class Reference
#include <zcis.h>
Public Member Functions
Complex_CIS_Parameters ()
Complex_CIS_Parameters (World &world, const commandlineparser &parser)
ctor reading out the input file
double dconv () const
std::vector< std::string > exops () const
int freeze () const
std::string get_tag () const override
std::string guess_excitation_operators () const
int guess_excitations () const
int guess_maxiter () const
int maxiter () const
double omega () const
int printlevel () const
bool swap_ab () const
double thresh () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
Complex_CIS_Parameters() [1/2]
madness::Complex_CIS_Parameters::Complex_CIS_Parameters (World & world, const commandlineparser & parser) inline
ctor reading out the input file
References madness::QCCalculationParametersBase::read_input_and_commandline_options().
Complex_CIS_Parameters() [2/2]
madness::Complex_CIS_Parameters::Complex_CIS_Parameters () inline
the parameters with the enum key, the constructor taking the input file key and a default value
Member Function Documentation
dconv()
double madness::Complex_CIS_Parameters::dconv () const inline
Referenced by madness::Zcis::compute_potentials(), and madness::Zcis::iterate().
exops()
std::vector< std::string > madness::Complex_CIS_Parameters::exops () const inline
freeze()
int madness::Complex_CIS_Parameters::freeze () const inline
Referenced by madness::Zcis::active_mo(), madness::Zcis::compute_potentials(), madness::Zcis::compute_residuals(), and madness::Zcis::noct().
get_tag()
std::string madness::Complex_CIS_Parameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
guess_excitation_operators()
std::string madness::Complex_CIS_Parameters::guess_excitation_operators () const inline
Referenced by madness::Zcis::make_guess().
guess_excitations()
int madness::Complex_CIS_Parameters::guess_excitations () const inline
Referenced by madness::Zcis::compute_potentials(), madness::Zcis::iterate(), madness::Zcis::make_guess(), and madness::Zcis::read_guess().
guess_maxiter()
int madness::Complex_CIS_Parameters::guess_maxiter () const inline
Referenced by madness::Zcis::iterate().
maxiter()
int madness::Complex_CIS_Parameters::maxiter () const inline
Referenced by madness::Zcis::iterate().
omega()
double madness::Complex_CIS_Parameters::omega () const inline
Referenced by madness::Zcis::iterate().
printlevel()
int madness::Complex_CIS_Parameters::printlevel () const inline
Referenced by madness::Zcis::iterate().
swap_ab()
bool madness::Complex_CIS_Parameters::swap_ab () const inline
Referenced by madness::Zcis::value().
thresh()
double madness::Complex_CIS_Parameters::thresh () const inline
Referenced by madness::Zcis::compute_residuals(), and madness::Zcis::make_guess().
The documentation for this class was generated from the following file:
zcis.h