MADNESS: slymer::PolynomialCoeffs Class Reference
slymer::PolynomialCoeffs Class Reference
Array for storing coefficients of a polynomial of three variables with specified degree.
#include <polynomial.h>
Public Member Functions
PolynomialCoeffs ()=delete
PolynomialCoeffs (const double constant, const double x, const double y, const double z)
Create a linear function with the specified coefficients.
PolynomialCoeffs (const unsigned N)
Create a polynomial of degree N.
unsigned get_degree () const
Get the degree of the polynomial.
double operator() (const std::array< double, 3 > &pt) const
Evaluate the polynomial at the specified point.
PolynomialCoeffs operator* (const double c) const
Multiply a polynomial by a constant value.
PolynomialCoeffs operator* (const PolynomialCoeffs &rhs) const
Multiply two polynomials together.
PolynomialCoeffs & operator*= (const double c)
Scale the polynomial by a constant.
PolynomialCoeffs operator+ (const PolynomialCoeffs &rhs) const
Add two polynomials together.
PolynomialCoeffs & operator+= (const PolynomialCoeffs &rhs)
Adds another polynomial to this one.
double & operator[] (const std::array< unsigned, 3 > &pows)
Access the coefficient for the specified term.
double operator[] (const std::array< unsigned, 3 > &pows) const
Access the coefficient for the specified term.
PolynomialCoeffs pow (const unsigned j) const
Expands a linear polynomial raised to a power.
Static Protected Member Functions
static unsigned polyIndex (const std::array< unsigned, 3 > &pows)
Gets the array index for the coefficient of a particular term.
Protected Attributes
std::vector< double > coeffs
Array storing the coefficients.
unsigned degree
The degree of the polynomial.
Detailed Description
Array for storing coefficients of a polynomial of three variables with specified degree.
The general polynomial of three variables is written as
where . This data structure stores the coefficients in a vector and provides access routines in terms of the exponents , , and .
Note
This class is not designed for polynomials with a large degree.
Constructor & Destructor Documentation
PolynomialCoeffs() [1/3]
slymer::PolynomialCoeffs::PolynomialCoeffs () delete
PolynomialCoeffs() [2/3]
slymer::PolynomialCoeffs::PolynomialCoeffs (const double constant, const double x, const double y, const double z) inline
Create a linear function with the specified coefficients.
Parameters
[in] constant The constant term.
[in] x The coefficient on x.
[in] y The coefficient on y.
[in] z The coefficient on z.
References coeffs, constant(), and polyIndex().
PolynomialCoeffs() [3/3]
slymer::PolynomialCoeffs::PolynomialCoeffs (const unsigned N) inline
Create a polynomial of degree N.
Parameters
[in] N The degree of the polynomial.
References coeffs.
Member Function Documentation
get_degree()
unsigned slymer::PolynomialCoeffs::get_degree () const inline
Get the degree of the polynomial.
Returns
The degree of the polynomial.
References degree.
Referenced by slymer::PrimitiveGaussian::PrimitiveGaussian().
operator()()
double slymer::PolynomialCoeffs::operator() (const std::array< double, 3 > & pt) const
Evaluate the polynomial at the specified point.
Note
This implemention is a bit naive; it is not intended for polynomials with a large degree.
Parameters
[in] pt The point at which the polynomial is evaluated.
Returns
The value of the polynomial at the point.
References coeffs, degree, k, polyIndex(), and pow().
operator*() [1/2]
PolynomialCoeffs slymer::PolynomialCoeffs::operator* (const double c) const
Multiply a polynomial by a constant value.
*this is one of the polynomials.
Parameters
[in] c The constant value.
Returns
The product of c and the polynomial.
References c, and coeffs.
operator*() [2/2]
PolynomialCoeffs slymer::PolynomialCoeffs::operator* (const PolynomialCoeffs & rhs) const
Multiply two polynomials together.
*this is one of the polynomials.
Parameters
[in] rhs The other polynomial.
Returns
The product of *this and rhs.
References degree, and operator[]().
operator*=()
PolynomialCoeffs & slymer::PolynomialCoeffs::operator*= (const double c)
Scale the polynomial by a constant.
Parameters
[in] c The scale factor.
Returns
The scaled polynomial (*this).
References c, and coeffs.
operator+()
PolynomialCoeffs slymer::PolynomialCoeffs::operator+ (const PolynomialCoeffs & rhs) const
Add two polynomials together.
*this is one of the polynomials.
Parameters
[in] rhs The other polynomial.
Returns
The sum of *this and rhs.
References coeffs, and degree.
operator+=()
PolynomialCoeffs & slymer::PolynomialCoeffs::operator+= (const PolynomialCoeffs & rhs)
Adds another polynomial to this one.
Parameters
[in] rhs The other polynomial.
Returns
The sum of *this and rhs, in *this.
References coeffs, and degree.
operator[]() [1/2]
double & slymer::PolynomialCoeffs::operator[] (const std::array< unsigned, 3 > & pows) inline
Access the coefficient for the specified term.
Parameters
[in] pows The powers of x, y, and z for this term.
Returns
Reference to the array term.
References coeffs, and polyIndex().
Referenced by operator*().
operator[]() [2/2]
double slymer::PolynomialCoeffs::operator[] (const std::array< unsigned, 3 > & pows) const inline
Access the coefficient for the specified term.
Parameters
[in] pows The powers of x, y, and z for this term.
Returns
The array term.
References coeffs, and polyIndex().
polyIndex()
static unsigned slymer::PolynomialCoeffs::polyIndex (const std::array< unsigned, 3 > & pows) inline static protected
Gets the array index for the coefficient of a particular term.
Terms of degree 0 are stored before those of degree 1, etc.
Within a particular degree, think of the problem in the combinatorial "stars and bars" idea: there are n stars and two bars dividing them into three parts. (Each part corresponds to the number of x, y, or z factors.) The first array element will be bars in the 0 and 1 positions, then 0 and 2, ..., 0 and n+1, then 1 and 2, etc.
Parameters
[in] pows The powers of x, y, and z for this term.
Returns
The array offset, as described above.
Referenced by PolynomialCoeffs(), operator()(), operator[](), and operator[]().
pow()
PolynomialCoeffs slymer::PolynomialCoeffs::pow (const unsigned j) const
Expands a linear polynomial raised to a power.
Essentially expands the polynomial
into a new PolynomialCoeffs object. That is, output[{{p,q,r}}] is the coefficient on the term.
This function requires multinomial coefficients, which involve factorials. We assume that the arguments to the factorials will not be large and hard-code small values. An error will be thrown if the maximum value is exceeded.
Exceptions
std::runtime_error if the polynomial does not have degree 1.
Parameters
[in] j The exponent of the expansion.
Returns
The polynomial, ordered using the polyIndex scheme.
References degree, and pow().
Referenced by operator()(), and pow().
Member Data Documentation
coeffs
std::vector<double> slymer::PolynomialCoeffs::coeffs protected
Array storing the coefficients.
For a given degree n, there are monomials. The total array thus has terms. The array stores all terms with degree 0, then degree 1, then degree 2, etc.
Referenced by PolynomialCoeffs(), PolynomialCoeffs(), operator()(), operator*(), operator*=(), operator+(), operator+=(), operator[](), and operator[]().
degree
unsigned slymer::PolynomialCoeffs::degree protected
The degree of the polynomial.
Referenced by get_degree(), operator()(), operator*(), operator+(), operator+=(), and pow().
The documentation for this class was generated from the following files:
polynomial.h
polynomial.cc