MADNESS: Array Class Reference
Array Class Reference
Public Member Functions
Array (World &world, size_t size)
Make block distributed array with size elements.
Array (World &world, size_t size)
Make block distributed array with size elements.
Array (World &world, size_t size)
Make block distributed array with size elements.
Array (World &world, size_t size)
Make block distributed array with size elements.
virtual ~Array ()
ProcessID owner (size_t i) const
Return the process in which element i resides.
ProcessID owner (size_t i) const
Return the process in which element i resides.
ProcessID owner (size_t i) const
Return the process in which element i resides.
ProcessID owner (size_t i) const
Return the process in which element i resides.
Future< double > read (size_t i) const
Read element i.
Future< double > read (size_t i) const
Read element i.
Future< double > read (size_t i) const
Future< double > read (size_t i) const
Read element i.
void write (size_t i, double value)
Write element i.
void write (size_t i, double value)
Write element i.
void write (size_t i, double value)
void write (size_t i, double value)
Write element i.
Public Member Functions inherited from madness::WorldObject< Array >
WorldObject (const WorldObject &other)
WorldObject (World &world)
Constructor that associates an object (via the derived class) with a globally unique ID.
virtual ~WorldObject ()
World & get_world () const
Returns a reference to the world.
const uniqueidT & id () const
Returns the globally unique object ID.
WorldObject & operator= (const WorldObject &)=delete
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8) const
detail::task_result_type< memfnT >::futureT send (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9) const
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const a9T &a9, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8,a9).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const a8T &a8, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7,a8).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const a7T &a7, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6,a7).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const a6T &a6, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5,a6).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const a5T &a5, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4,a5).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const a4T &a4, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3,a4).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const a3T &a3, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2,a3).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const a2T &a2, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1,a2).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const a1T &a1, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)(a1).
detail::task_result_type< memfnT >::futureT task (ProcessID dest, memfnT memfn, const TaskAttributes &attr=TaskAttributes()) const
Sends task to derived class method returnT (this->*memfn)().
Public Member Functions inherited from madness::WorldObjectBase
virtual ~WorldObjectBase ()=default
Private Attributes
vector< double > v
Additional Inherited Members
Public Types inherited from madness::WorldObject< Array >
typedef WorldObject< Array > objT
Protected Member Functions inherited from madness::WorldObject< Array >
void process_pending ()
To be called from derived constructor to process pending messages.
Constructor & Destructor Documentation
Array() [1/4]
Array::Array (World & world, size_t size) inline
Make block distributed array with size elements.
References madness::WorldObject< Array >::process_pending().
Array() [2/4]
Array::Array (World & world, size_t size) inline
Make block distributed array with size elements.
References madness::WorldObject< Array >::process_pending().
Array() [3/4]
Array::Array (World & world, size_t size) inline
Make block distributed array with size elements.
References madness::WorldObject< Array >::process_pending().
Array() [4/4]
Array::Array (World & world, size_t size) inline
Make block distributed array with size elements.
References madness::WorldObject< Array >::process_pending().
~Array()
virtual Array::~Array () inline virtual
Member Function Documentation
owner() [1/4]
ProcessID Array::owner (size_t i) const inline
Return the process in which element i resides.
References v.
Referenced by read(), and write().
owner() [2/4]
ProcessID Array::owner (size_t i) const inline
Return the process in which element i resides.
References v.
owner() [3/4]
ProcessID Array::owner (size_t i) const inline
Return the process in which element i resides.
References v.
owner() [4/4]
ProcessID Array::owner (size_t i) const inline
Return the process in which element i resides.
References v.
read() [1/4]
Future< double > Array::read (size_t i) const inline
Read element i.
References owner(), madness::World::rank(), read(), madness::WorldObject< Array >::send(), v, and madness::WorldObject< Array >::world.
Referenced by main(), and read().
read() [2/4]
Future< double > Array::read (size_t i) const inline
Read element i.
References owner(), madness::World::rank(), read(), madness::WorldObject< Array >::send(), v, and madness::WorldObject< Array >::world.
read() [3/4]
Future< double > Array::read (size_t i) const inline
References madness::WorldObject< Array >::get_world(), owner(), read(), madness::WorldObject< Array >::send(), madness::World::size(), and v.
read() [4/4]
Future< double > Array::read (size_t i) const inline
Read element i.
References madness::WorldObject< Array >::get_world(), owner(), read(), madness::WorldObject< Array >::send(), madness::World::size(), and v.
write() [1/4]
void Array::write (size_t i, double value) inline
Write element i.
References owner(), madness::World::rank(), madness::WorldObject< Array >::send(), v, madness::WorldObject< Array >::world, and write().
Referenced by main(), and write().
write() [2/4]
void Array::write (size_t i, double value) inline
Write element i.
References owner(), madness::World::rank(), madness::WorldObject< Array >::send(), v, madness::WorldObject< Array >::world, and write().
write() [3/4]
void Array::write (size_t i, double value) inline
References madness::WorldObject< Array >::get_world(), owner(), madness::World::rank(), madness::WorldObject< Array >::send(), v, and write().
write() [4/4]
void Array::write (size_t i, double value) inline
Write element i.
References madness::WorldObject< Array >::get_world(), owner(), madness::World::rank(), madness::WorldObject< Array >::send(), v, and write().
Member Data Documentation
v
vector< double > Array::v private
Referenced by owner(), read(), and write().
The documentation for this class was generated from the following files:
test_comm.cc
testconv.cc
array_worldobject.cc
test_future2.cc