MADNESS: SurfaceMoleculeInteraction Class Reference
SurfaceMoleculeInteraction Class Reference
Classes
struct Bop
struct Reciprocal
Public Member Functions
SurfaceMoleculeInteraction (const double &d, const double &R, const std::vector< double > &charge_center, realfunc &rhot, const double &sigma, World &world, const int &maxiter)
std::vector< madness::Vector< double, 3 > > colloid_coords () const
std::vector< double > colloid_radii () const
realfunc make_surfcharge (const realfunc &u, const realfunc &surface, const realfunc &volume) const
realfunc perturbed_molecular_pot (const realfunc &surface, const realfunc &volume) const
Private Attributes
const std::vector< double > charge_center
const double & d
const int & maxiter
const double & R
realfunc & rhot
const double & sigma
World & world
Constructor & Destructor Documentation
SurfaceMoleculeInteraction()
SurfaceMoleculeInteraction::SurfaceMoleculeInteraction (const double & d, const double & R, const std::vector< double > & charge_center, realfunc & rhot, const double & sigma, World & world, const int & maxiter) inline
References colloid_coords(), colloid_radii(), and MADNESS_ASSERT.
Member Function Documentation
colloid_coords()
std::vector< madness::Vector< double, 3 > > SurfaceMoleculeInteraction::colloid_coords () const inline
References c, d, dist(), and R.
Referenced by SurfaceMoleculeInteraction(), colloid_radii(), and main().
colloid_radii()
std::vector< double > SurfaceMoleculeInteraction::colloid_radii () const inline
References c, colloid_coords(), and R.
Referenced by SurfaceMoleculeInteraction(), and main().
make_surfcharge()
realfunc SurfaceMoleculeInteraction::make_surfcharge (const realfunc & u, const realfunc & surface, const realfunc & volume) const inline
References madness::binary_op(), madness::copy(), lo, madness::constants::pi, madness::plot_line(), rhot, madness::Function< T, NDIM >::scale(), u(), madness::Function< T, NDIM >::unaryop(), and madness::Function< T, NDIM >::world().
Referenced by perturbed_molecular_pot().
perturbed_molecular_pot()
realfunc SurfaceMoleculeInteraction::perturbed_molecular_pot (const realfunc & surface, const realfunc & volume) const inline
References madness::CoulombOperator(), e(), lo, make_surfcharge(), maxiter, madness::Function< T, NDIM >::norm2(), op(), madness::plot_line(), madness::print(), madness::World::rank(), rhot, madness::truncate(), and world.
Referenced by main().
Member Data Documentation
charge_center
const std::vector<double> SurfaceMoleculeInteraction::charge_center private
d
const double& SurfaceMoleculeInteraction::d private
Referenced by colloid_coords(), and SurfaceMoleculeInteraction::Bop::operator()().
maxiter
const int& SurfaceMoleculeInteraction::maxiter private
Referenced by perturbed_molecular_pot().
R
const double& SurfaceMoleculeInteraction::R private
Referenced by colloid_coords(), and colloid_radii().
rhot
realfunc& SurfaceMoleculeInteraction::rhot private
Referenced by make_surfcharge(), and perturbed_molecular_pot().
sigma
const double& SurfaceMoleculeInteraction::sigma private
world
World& SurfaceMoleculeInteraction::world private
Referenced by perturbed_molecular_pot().
The documentation for this class was generated from the following file:
colloid.cc