MADNESS: GygiPot Class Reference
GygiPot Class Reference
Classes
struct Pow
struct Pow_beta_one
struct Reciprocal
Public Member Functions
GygiPot (const realfunc &rho, const realfunc &rhot, const double &rho_0, const double &epsilon, const int &maxiter, World &world, const double Gamma)
double cavitation_energy () const
realfunc depsilon_dr () const
realfunc depsilon_drho () const
realfunc dESP_drho (const realfunc u) const
realfunc dfree_drho () const
realfunc epsilon_rho () const
realfunc ESP (World &world) const
realfunc GuessPotential (World &world) const
realfunc make_surfcharge (const realfunc &u) const
realfunc MolecularPotential () const
realfunc re_epsilon_rho () const
realfunc V_epsilon (const realfunc &u) const
Private Member Functions
realfunc grad_rho (const realfunc &dens) const
realfunc ratio_rho () const
realfunc re_grad_rho (const realfunc &dens) const
realfunc re_one_plus_ratio_rho () const
realfunc rho_beta_one () const
Private Attributes
const double & epsilon
const double & Gamma
const int & maxiter
const realfunc & rho
const double & rho_0
const realfunc & rhot
World & world
Static Private Attributes
static const double cutrho = 1e-8
Constructor & Destructor Documentation
GygiPot()
GygiPot::GygiPot (const realfunc & rho, const realfunc & rhot, const double & rho_0, const double & epsilon, const int & maxiter, World & world, const double Gamma) inline
Member Function Documentation
cavitation_energy()
double GygiPot::cavitation_energy () const inline
References beta, Gamma, grad_rho(), madness::Function< T, NDIM >::norm2(), rho, and rho_0.
Referenced by main().
depsilon_dr()
realfunc GygiPot::depsilon_dr () const inline
References depsilon_drho(), grad_rho(), and rhot.
Referenced by make_surfcharge().
depsilon_drho()
realfunc GygiPot::depsilon_drho () const inline
References beta, epsilon, re_one_plus_ratio_rho(), rho_0, and rho_beta_one().
Referenced by depsilon_dr(), main(), and V_epsilon().
dESP_drho()
realfunc GygiPot::dESP_drho (const realfunc u) const inline
References u(), and V_epsilon().
Referenced by main().
dfree_drho()
realfunc GygiPot::dfree_drho () const inline
References beta, Gamma, grad_rho(), madness::Function< T, NDIM >::norm2(), re_grad_rho(), rho, rho_0, rhot, and madness::Function< T, NDIM >::world().
Referenced by main().
epsilon_rho()
realfunc GygiPot::epsilon_rho () const inline
References epsilon, ratio_rho(), and re_one_plus_ratio_rho().
Referenced by main(), and re_epsilon_rho().
ESP()
realfunc GygiPot::ESP (World & world) const inline
References madness::CoulombOperator(), e(), GuessPotential(), make_surfcharge(), maxiter, MolecularPotential(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), madness::World::rank(), madness::wall_time(), and world.
Referenced by main().
grad_rho()
realfunc GygiPot::grad_rho (const realfunc & dens) const inline private
References madness::Function< T, NDIM >::world().
Referenced by cavitation_energy(), depsilon_dr(), dfree_drho(), make_surfcharge(), re_grad_rho(), and V_epsilon().
GuessPotential()
realfunc GygiPot::GuessPotential (World & world) const inline
References madness::CoulombOperator(), madness::FunctionDefaults< NDIM >::get_thresh(), op(), re_epsilon_rho(), rho, and world.
Referenced by ESP().
make_surfcharge()
realfunc GygiPot::make_surfcharge (const realfunc & u) const inline
References depsilon_dr(), grad_rho(), madness::constants::pi, re_epsilon_rho(), madness::truncate(), and u().
Referenced by ESP(), and main().
MolecularPotential()
realfunc GygiPot::MolecularPotential () const inline
References re_epsilon_rho(), and rho.
Referenced by ESP().
ratio_rho()
realfunc GygiPot::ratio_rho () const inline private
References rho_0, rhot, and madness::Function< T, NDIM >::unaryop().
Referenced by epsilon_rho(), and re_one_plus_ratio_rho().
re_epsilon_rho()
realfunc GygiPot::re_epsilon_rho () const inline
References epsilon_rho(), and madness::Function< T, NDIM >::unaryop().
Referenced by GuessPotential(), main(), make_surfcharge(), and MolecularPotential().
re_grad_rho()
realfunc GygiPot::re_grad_rho (const realfunc & dens) const inline private
References grad_rho(), and madness::Function< T, NDIM >::unaryop().
Referenced by dfree_drho().
re_one_plus_ratio_rho()
realfunc GygiPot::re_one_plus_ratio_rho () const inline private
References ratio_rho(), and madness::Function< T, NDIM >::unaryop().
Referenced by depsilon_drho(), and epsilon_rho().
rho_beta_one()
realfunc GygiPot::rho_beta_one () const inline private
References rho_0, rhot, and madness::Function< T, NDIM >::unaryop().
Referenced by depsilon_drho().
V_epsilon()
realfunc GygiPot::V_epsilon (const realfunc & u) const inline
References depsilon_drho(), grad_rho(), madness::constants::pi, and u().
Referenced by dESP_drho(), and main().
Member Data Documentation
cutrho
const double GygiPot::cutrho = 1e-8 static private
Referenced by GygiPot::Pow< T, DIM >::operator()(), and GygiPot::Pow_beta_one< T, DIM >::operator()().
epsilon
const double& GygiPot::epsilon private
Referenced by depsilon_drho(), and epsilon_rho().
Gamma
const double& GygiPot::Gamma private
Referenced by cavitation_energy(), and dfree_drho().
maxiter
const int& GygiPot::maxiter private
Referenced by ESP().
rho
const realfunc& GygiPot::rho private
Referenced by cavitation_energy(), dfree_drho(), GuessPotential(), and MolecularPotential().
rho_0
const double& GygiPot::rho_0 private
Referenced by cavitation_energy(), depsilon_drho(), dfree_drho(), ratio_rho(), and rho_beta_one().
rhot
const realfunc& GygiPot::rhot private
Referenced by depsilon_dr(), dfree_drho(), ratio_rho(), and rho_beta_one().
world
World& GygiPot::world private
Referenced by ESP(), and GuessPotential().
The documentation for this class was generated from the following file:
gygi_soltion.cc