MADNESS: madness::PNOParameters Class Reference
madness::PNOParameters Class Reference
#include <PNOParameters.h>
Public Member Functions
PNOParameters ()
PNOParameters (const QCCalculationParametersBase &param)
PNOParameters (World &world, const commandlineparser &parser, const Molecule &molecule, const std::string &TAG="pno")
PNOParameters (World &world, const commandlineparser &parser, const std::string &TAG="pno")
std::vector< int > active_pairs_of_orbital () const
PairType adaptive_solver () const
template<typename T >
T assign_from_string (const std::string &string) const
bool canonicalize_pno () const
int chunk () const
std::vector< std::pair< int, double > > cispd () const
double dconv () const
bool debug () const
bool diagonal () const
double econv () const
double econv_macro () const
double econv_micro () const
double econv_pairs () const
std::string exchange () const
std::string exop () const
bool exop_trigo () const
bool f12 () const
std::size_t freeze () const
std::vector< std::pair< int, int > > freeze_pairs () const
std::vector< int > freeze_pairs_of_orbital () const
std::string get_tag () const override
GuessType guesstype () const
void initialize_pno_parameters ()
bool kain () const
std::size_t kain_subspace () const
int maxiter () const
int maxiter_macro () const
int maxiter_micro () const
int maxiter_t () const
int maxrank () const
PairType no_compute () const
PairType no_guess () const
PairType no_opt () const
bool no_opt_in_first_iteration () const
double op_thresh () const
std::map< std::string, std::vector< int > > partial_wave (const std::string &key="partial_wave") const
std::string predefined_guess () const
std::vector< std::vector< double > > protocol () const
int rank_increase () const
PairType restart () const
bool save_pnos () const
void set_derived_values (const Molecule &molecule)
double thresh () const
double tpno () const
double tpno_tight () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
PNOParameters() [1/4]
madness::PNOParameters::PNOParameters () inline
References initialize_pno_parameters().
PNOParameters() [2/4]
madness::PNOParameters::PNOParameters (const QCCalculationParametersBase & param) inline
References initialize_pno_parameters().
PNOParameters() [3/4]
madness::PNOParameters::PNOParameters (World & world, const commandlineparser & parser, const std::string & TAG = "pno") inline
References initialize_pno_parameters(), and madness::QCCalculationParametersBase::read_input_and_commandline_options().
PNOParameters() [4/4]
madness::PNOParameters::PNOParameters (World & world, const commandlineparser & parser, const Molecule & molecule, const std::string & TAG = "pno") inline
References initialize_pno_parameters(), molecule, madness::QCCalculationParametersBase::read_input_and_commandline_options(), and set_derived_values().
Member Function Documentation
active_pairs_of_orbital()
std::vector< int > madness::PNOParameters::active_pairs_of_orbital () const inline
Referenced by madness::PNO::freeze_insignificant_pairs().
adaptive_solver()
PairType madness::PNOParameters::adaptive_solver () const inline
Referenced by madness::PNO::iterate_pairs(), and set_derived_values().
assign_from_string()
template<typename T > T madness::PNOParameters::assign_from_string (const std::string & string) const inline
References T().
canonicalize_pno()
bool madness::PNOParameters::canonicalize_pno () const inline
Referenced by madness::PNO::iterate_pairs_internal().
chunk()
int madness::PNOParameters::chunk () const inline
Referenced by madness::PNO::iterate_pairs_internal(), and madness::PNO::update_pno().
cispd()
std::vector< std::pair< int, double > > madness::PNOParameters::cispd () const inline
References energy.
Referenced by madness::PNO::solve(), and madness::PNO::solve_cispd().
dconv()
double madness::PNOParameters::dconv () const inline
Referenced by madness::PNO::update_pno().
debug()
bool madness::PNOParameters::debug () const inline
Referenced by madness::F12Potentials::compute_fQc_integrals_ij(), madness::F12Potentials::compute_fQU_integrals(), madness::F12Potentials::convolve_with_fU(), madness::PNO::solve(), madness::PNO::t_solve(), and madness::PNO::update_pno().
diagonal()
bool madness::PNOParameters::diagonal () const inline
Referenced by madness::PNO::initialize_pairs().
econv()
double madness::PNOParameters::econv () const inline
References econv_micro().
econv_macro()
double madness::PNOParameters::econv_macro () const inline
Referenced by madness::PNO::adaptive_solver().
econv_micro()
double madness::PNOParameters::econv_micro () const inline
Referenced by madness::PNO::adaptive_solver(), econv(), and madness::PNO::iterate_pairs().
econv_pairs()
double madness::PNOParameters::econv_pairs () const inline
Referenced by madness::PNO::adaptive_solver(), and madness::PNO::freeze_insignificant_pairs().
exchange()
std::string madness::PNOParameters::exchange () const inline
Referenced by madness::F12Potentials::apply_regularized_potential().
exop()
std::string madness::PNOParameters::exop () const inline
Referenced by madness::PNO::adaptive_solver(), and madness::PNO::guess_virtuals().
exop_trigo()
bool madness::PNOParameters::exop_trigo () const inline
Referenced by madness::PNO::grow_rank(), and madness::PNO::guess_virtuals().
f12()
bool madness::PNOParameters::f12 () const inline
Referenced by madness::PNO::compute_cispd_f12_correction_gs(), madness::PNO::compute_cispd_fluctuation_matrix(), madness::PNO::compute_cispd_fluctuation_potential(), madness::PNO::compute_fluctuation_matrix(), madness::PNO::compute_fluctuation_potential(), madness::PNO::compute_V_aj_i(), madness::PNO::compute_Vreg_aj_i(), madness::PNO::compute_Vreg_aj_i(), madness::PNO::energytype(), madness::PNO::solve(), madness::PNO::solve_cispd(), and madness::PNO::solve_mp2().
freeze()
std::size_t madness::PNOParameters::freeze () const inline
Referenced by madness::F12Potentials::F12Potentials(), madness::PNO::PNO(), madness::PNO::freeze_insignificant_pairs(), madness::PNO::grow_rank(), madness::F12Potentials::initialize_active_mos(), madness::PNO::initialize_pairs(), madness::PNO::iterate_pairs_internal(), madness::PNO::nact(), madness::PNO::oit(), madness::F12Potentials::pit(), madness::F12Potentials::print_pair_energies(), set_derived_values(), and madness::PNO::solve_cispd().
freeze_pairs()
std::vector< std::pair< int, int > > madness::PNOParameters::freeze_pairs () const inline
Referenced by madness::PNO::freeze_insignificant_pairs().
freeze_pairs_of_orbital()
std::vector< int > madness::PNOParameters::freeze_pairs_of_orbital () const inline
Referenced by madness::PNO::freeze_insignificant_pairs().
get_tag()
std::string madness::PNOParameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
guesstype()
GuessType madness::PNOParameters::guesstype () const inline
Referenced by madness::PNO::guess_virtuals(), madness::PNO::initialize_pairs(), and madness::PNO::iterate_pairs().
initialize_pno_parameters()
void madness::PNOParameters::initialize_pno_parameters () inline
Referenced by PNOParameters(), PNOParameters(), PNOParameters(), and PNOParameters().
kain()
bool madness::PNOParameters::kain () const inline
Referenced by madness::PNO::t_solve().
kain_subspace()
std::size_t madness::PNOParameters::kain_subspace () const inline
Referenced by madness::PNO::t_solve().
maxiter()
int madness::PNOParameters::maxiter () const inline
References maxiter_micro().
Referenced by madness::PNO::iterate_pairs_internal().
maxiter_macro()
int madness::PNOParameters::maxiter_macro () const inline
Referenced by madness::PNO::adaptive_solver().
maxiter_micro()
int madness::PNOParameters::maxiter_micro () const inline
Referenced by madness::PNO::adaptive_solver(), madness::PNO::iterate_pairs(), and maxiter().
maxiter_t()
int madness::PNOParameters::maxiter_t () const inline
Referenced by madness::PNO::t_solve().
maxrank()
int madness::PNOParameters::maxrank () const inline
Referenced by madness::PNO::adaptive_solver(), madness::PNO::grow_rank(), madness::PNO::initialize_pairs(), and madness::PNO::iterate_pairs().
no_compute()
PairType madness::PNOParameters::no_compute () const inline
Referenced by madness::PNO::iterate_pairs_internal(), and madness::PNO::solve_cispd().
no_guess()
PairType madness::PNOParameters::no_guess () const inline
Referenced by madness::PNO::initialize_pairs().
no_opt()
PairType madness::PNOParameters::no_opt () const inline
Referenced by madness::PNO::iterate_pairs_internal().
no_opt_in_first_iteration()
bool madness::PNOParameters::no_opt_in_first_iteration () const inline
Referenced by madness::PNO::iterate_pairs_internal().
op_thresh()
double madness::PNOParameters::op_thresh () const inline
Referenced by madness::F12Potentials::F12Potentials(), madness::PNO::PNO(), and madness::PNO::make_bsh_operators().
partial_wave()
std::map< std::string, std::vector< int > > madness::PNOParameters::partial_wave (const std::string & key = "partial_wave") const inline
References MADNESS_ASSERT.
Referenced by madness::F12Parameters::auxbas(), and madness::PNO::guess_virtuals().
predefined_guess()
std::string madness::PNOParameters::predefined_guess () const inline
Referenced by madness::PNO::guess_virtuals().
protocol()
std::vector< std::vector< double > > madness::PNOParameters::protocol () const inline
rank_increase()
int madness::PNOParameters::rank_increase () const inline
Referenced by madness::PNO::adaptive_solver().
restart()
PairType madness::PNOParameters::restart () const inline
Referenced by madness::PNO::initialize_pairs(), madness::PNO::is_guess_from_scratch(), and madness::PNO::iterate_pairs_internal().
save_pnos()
bool madness::PNOParameters::save_pnos () const inline
set_derived_values()
void madness::PNOParameters::set_derived_values (const Molecule & molecule) inline
References adaptive_solver(), freeze(), gt(), molecule, madness::QCCalculationParametersBase::set_derived_value(), thresh(), and tpno().
Referenced by PNOParameters().
thresh()
double madness::PNOParameters::thresh () const inline
Referenced by madness::PNO::compute_CIS_potentials(), madness::F12Potentials::compute_hylleraas_f12_energies(), madness::PNO::compute_V_aj_i(), madness::PNO::compute_Vreg_aj_i(), madness::PNO::freeze_insignificant_pairs(), madness::PNO::initialize_pairs(), madness::F12Parameters::set_derived_values(), set_derived_values(), madness::PNO::solve(), and madness::PNO::truncate_pairs().
tpno()
double madness::PNOParameters::tpno () const inline
Referenced by madness::PNO::iterate_pairs_internal(), and set_derived_values().
tpno_tight()
double madness::PNOParameters::tpno_tight () const inline
Referenced by madness::PNO::iterate_pairs_internal().
The documentation for this class was generated from the following file:
PNOParameters.h