MADNESS: madness::BasisFunctions Class Reference
madness::BasisFunctions Class Reference
#include <PNOGuessFunctions.h>
Classes
class CartesianGaussian
class SolidHarmonicGaussian
Public Types
typedef std::vector< std::tuple< int, std::vector< double >, std::vector< double > > > cbfT
Public Member Functions
BasisFunctions (World &world, const Molecule &mol, const size_t &l)
std::vector< int > fill_peterson (const size_t &s) const
std::vector< int > fill_up (std::vector< int > v) const
vector_real_function_3d guess_contracted_virtuals_from_file () const
vector_real_function_3d guess_virtual_gaussian_shell (const Atom &atom, const int l, const double e) const
vector_real_function_3d guess_virtuals_from_file () const
vector_real_function_3d guess_virtuals_internal (const std::map< std::string, std::vector< int > > guess_map) const
vector_real_function_3d guess_with_exop (const vector_real_function_3d &f, const std::string &type="dipole+", const bool trigo=true) const
make guess virtuals by exciting with polynomials: v = poly*f
vector_real_function_3d guess_with_psi4 (const vector_real_function_3d &mos) const
size_t lqtoint (const std::string &l) const
little helper function for l-quantum numbers
std::vector< CartesianGaussian > make_cartesian_guess (const Atom &atom, int l, const double exponent)
make a set of Cartesian Gaussian functions located on atom
std::vector< SolidHarmonicGaussian > make_solidharmonic_guess (const Atom &atom, int l, const double exponent) const
make a set of Cartesian Gaussian functions located on atom
vector_real_function_3d predefined_guess (const std::string name) const
void print_contracted_basis (std::map< std::string, cbfT > &molbas) const
std::vector< std::vector< double > > read_basis_from_file (const std::string &filename, const std::string &atom) const
std::map< std::string, std::vector< std::vector< double > > > read_basis_from_file (const std::string &filename, const std::vector< madness::Atom > atoms) const
read external CABS
cbfT read_contracted_basis_from_file (const std::string &filename, const std::string &atom) const
std::map< std::string, cbfT > read_contracted_basis_from_file (const std::string &filename, const std::vector< madness::Atom > atoms) const
Public Attributes
const size_t lmax
const Molecule & molecule
World & world
Detailed Description
class which provides guess functions for pnos and cabs basis sets the guess functions are not orthonormalized or Q-projected
Member Typedef Documentation
cbfT
typedef std::vector<std::tuple<int, std::vector<double>, std::vector<double> > > madness::BasisFunctions::cbfT
Constructor & Destructor Documentation
BasisFunctions()
madness::BasisFunctions::BasisFunctions (World & world, const Molecule & mol, const size_t & l) inline
Member Function Documentation
fill_peterson()
std::vector< int > madness::BasisFunctions::fill_peterson (const size_t & s) const inline
References lmax.
Referenced by predefined_guess().
fill_up()
std::vector< int > madness::BasisFunctions::fill_up (std::vector< int > v) const inline
References lmax, and v.
guess_contracted_virtuals_from_file()
vector_real_function_3d madness::BasisFunctions::guess_contracted_virtuals_from_file () const inline
References madness::append(), madness::atomic_number_to_symbol(), c, madness::Molecule::get_atoms(), guess_virtual_gaussian_shell(), k, MADNESS_ASSERT, molecule, madness::normalize(), madness::MyTimer::print(), madness::print(), print_contracted_basis(), madness::print_size(), read_contracted_basis_from_file(), madness::MyTimer::start(), madness::MyTimer::stop(), madness::truncate(), madness::type(), and world.
Referenced by madness::PNO::guess_virtuals().
guess_virtual_gaussian_shell()
vector_real_function_3d madness::BasisFunctions::guess_virtual_gaussian_shell (const Atom & atom, const int l, const double e) const
return a shell of l-quantum l and exponent e, including all cartesian components
References e(), m, make_solidharmonic_guess(), madness::normalize(), and world.
Referenced by guess_contracted_virtuals_from_file(), guess_virtuals_from_file(), guess_virtuals_internal(), and madness::F12Potentials::read_cabs_from_file().
guess_virtuals_from_file()
vector_real_function_3d madness::BasisFunctions::guess_virtuals_from_file () const
References madness::append(), madness::atomic_number_to_symbol(), e(), madness::Molecule::get_atoms(), guess_virtual_gaussian_shell(), molecule, madness::MyTimer::print(), madness::print(), madness::World::rank(), read_basis_from_file(), madness::MyTimer::start(), madness::MyTimer::stop(), and world.
guess_virtuals_internal()
vector_real_function_3d madness::BasisFunctions::guess_virtuals_internal (const std::map< std::string, std::vector< int > > guess_map) const
References madness::append(), madness::Atom::atomic_number, madness::atomic_number_to_symbol(), e(), madness::Molecule::get_atom(), guess_virtual_gaussian_shell(), MADNESS_EXCEPTION, molecule, madness::name(), madness::Molecule::natom(), madness::plot_plane(), madness::print(), madness::World::rank(), madness::stringify(), and world.
Referenced by madness::F12Potentials::compute_hylleraas_f12_energies(), madness::PNO::guess_virtuals(), and predefined_guess().
guess_with_exop()
vector_real_function_3d madness::BasisFunctions::guess_with_exop (const vector_real_function_3d & f, const std::string & type = "dipole+", const bool trigo = true) const inline
make guess virtuals by exciting with polynomials: v = poly*f
References madness::append(), madness::guessfactory::apply_polynomial_exop(), madness::guessfactory::apply_trigonometric_exop(), madness::guessfactory::compute_centroids(), madness::copy(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, madness::guessfactory::make_predefined_exop_strings(), madness::World::rank(), madness::type(), and world.
Referenced by madness::PNO::grow_rank(), and madness::PNO::guess_virtuals().
guess_with_psi4()
vector_real_function_3d madness::BasisFunctions::guess_with_psi4 (const vector_real_function_3d & mos) const inline
References MADNESS_EXCEPTION.
Referenced by madness::PNO::guess_virtuals().
lqtoint()
size_t madness::BasisFunctions::lqtoint (const std::string & l) const
little helper function for l-quantum numbers
References MADNESS_EXCEPTION.
Referenced by read_basis_from_file(), and read_contracted_basis_from_file().
make_cartesian_guess()
std::vector< CartesianGaussian > madness::BasisFunctions::make_cartesian_guess (const Atom & atom, int l, const double exponent) inline
make a set of Cartesian Gaussian functions located on atom
Parameters
[in] atom where the Cartesian Gaussian function is located
[in] l the l-quantum number
[in] exponent exponent of the Cartesian Gaussian function
References kx, ky, and kz.
make_solidharmonic_guess()
std::vector< SolidHarmonicGaussian > madness::BasisFunctions::make_solidharmonic_guess (const Atom & atom, int l, const double exponent) const inline
make a set of Cartesian Gaussian functions located on atom
Parameters
[in] atom where the Cartesian Gaussian function is located
[in] l the l-quantum number
[in] exponent exponent of the Cartesian Gaussian function
References m.
Referenced by guess_virtual_gaussian_shell().
predefined_guess()
vector_real_function_3d madness::BasisFunctions::predefined_guess (const std::string name) const inline
References madness::atomic_number_to_symbol(), fill_peterson(), madness::Molecule::get_atoms(), guess_virtuals_internal(), lmax, MADNESS_EXCEPTION, molecule, and madness::name().
Referenced by madness::PNO::guess_virtuals().
print_contracted_basis()
void madness::BasisFunctions::print_contracted_basis (std::map< std::string, cbfT > & molbas) const inline
References c, k, and madness::type().
Referenced by guess_contracted_virtuals_from_file().
read_basis_from_file() [1/2]
std::vector< std::vector< double > > madness::BasisFunctions::read_basis_from_file (const std::string & filename, const std::string & atom) const
References madness::f, madness::filename, lqtoint(), and madness::position_stream().
read_basis_from_file() [2/2]
std::map< std::string, std::vector< std::vector< double > > > madness::BasisFunctions::read_basis_from_file (const std::string & filename, const std::vector< madness::Atom > atoms) const
read external CABS
References madness::atomic_number_to_symbol(), madness::filename, and read_basis_from_file().
Referenced by guess_virtuals_from_file(), read_basis_from_file(), and madness::F12Potentials::read_cabs_from_file().
read_contracted_basis_from_file() [1/2]
cbfT madness::BasisFunctions::read_contracted_basis_from_file (const std::string & filename, const std::string & atom) const inline
References c, madness::f, madness::filename, lqtoint(), MADNESS_ASSERT, MADNESS_EXCEPTION, and madness::position_stream().
read_contracted_basis_from_file() [2/2]
std::map< std::string, cbfT > madness::BasisFunctions::read_contracted_basis_from_file (const std::string & filename, const std::vector< madness::Atom > atoms) const inline
References madness::atomic_number_to_symbol(), madness::filename, and read_contracted_basis_from_file().
Referenced by guess_contracted_virtuals_from_file(), and read_contracted_basis_from_file().
Member Data Documentation
lmax
const size_t madness::BasisFunctions::lmax
Referenced by fill_peterson(), fill_up(), and predefined_guess().
molecule
const Molecule& madness::BasisFunctions::molecule
Referenced by guess_contracted_virtuals_from_file(), guess_virtuals_from_file(), guess_virtuals_internal(), and predefined_guess().
world
World& madness::BasisFunctions::world
Referenced by guess_contracted_virtuals_from_file(), guess_virtual_gaussian_shell(), guess_virtuals_from_file(), guess_virtuals_internal(), and guess_with_exop().
The documentation for this class was generated from the following files:
PNOGuessFunctions.h
PNOGuessFunctions.cpp