MADNESS: madness::CCPairBuilder Class Reference
madness::CCPairBuilder Class Reference
build an MP2 or CC2 or LRCC2 etc pair, possibly including the lo-rank parts
#include <CCStructures.h>
Public Member Functions
CCPairBuilder (World &world, const Info &info)
CCPair complete_pair_with_low_rank_parts (const CCPair &pair) const
complete the given pair with the low-rank parts
template<typename T , size_t NDIM>
Function< T, NDIM > load_function (const std::string name, bool do_print) const
Function to load a function from disk.
Pairs< CCPair > make_all_bare_pairs () const
make a CCPair with the 6d function only and some bookkeeping information
CCPair make_bare_pair (const int i, const int j) const
make a CCPair without the 6d function and some bookkeeping information
CCPair make_bare_pair_from_file (const int i, const int j) const
make a CCPair with the 6d function only and some bookkeeping information
CCPair make_pair (const int i, const int j, const std::vector< CCPairFunction< double, 6 > > &u) const
make a CCPair
CCPairBuilder & set_ctype (const CalcType &type)
CCPairBuilder & set_ex_singles (const CC_vecfunction &ex)
provide excited state singles, needed for CC2 and LRCC2 wave function ansatz
CCPairBuilder & set_gs_singles (const CC_vecfunction &gs)
provide ground-state singles, needed for CC2 and LRCC2 wave function ansatz
Static Public Member Functions
static CCState cc_state (const CalcType &type)
Public Attributes
CalcType ctype =CT_UNDEFINED
CC_vecfunction ex_singles
CC_vecfunction gs_singles
const Info & info
World & world
Detailed Description
build an MP2 or CC2 or LRCC2 etc pair, possibly including the lo-rank parts
Constructor & Destructor Documentation
CCPairBuilder()
madness::CCPairBuilder::CCPairBuilder (World & world, const Info & info) inline
Member Function Documentation
cc_state()
static CCState madness::CCPairBuilder::cc_state (const CalcType & type) inline static
References madness::CT_ADC2, madness::CT_CC2, madness::CT_CISPD, madness::CT_LRCC2, madness::CT_MP2, madness::CT_MP3, madness::EXCITED_STATE, madness::GROUND_STATE, MADNESS_EXCEPTION, and madness::type().
Referenced by make_bare_pair().
complete_pair_with_low_rank_parts()
CCPair madness::CCPairBuilder::complete_pair_with_low_rank_parts (const CCPair & pair) const
complete the given pair with the low-rank parts
will use pair's ctype, while builder's ctype is ignored
References madness::assign_name(), madness::CT_CC2, madness::CT_LRCC2, madness::CT_MP2, madness::CCPair::ctype, ex_singles, madness::CCPair::function(), madness::CCPair::functions, madness::Info::get_active_mo_bra(), gs_singles, madness::CCPair::i, info, madness::CCPair::j, MADNESS_CHECK_THROW, MADNESS_EXCEPTION, madness::Info::mo_bra, madness::Info::mo_ket, madness::OT_F12, madness::Info::parameters, madness::print(), madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces(), madness::CC_vecfunction::size(), madness::stringify(), madness::timer::tag(), and world.
load_function()
template<typename T , size_t NDIM> Function< T, NDIM > madness::CCPairBuilder::load_function (const std::string name, bool do_print) const inline
Function to load a function from disk.
Parameters
[in] name of the file in which the function was stored
do_print
Returns
the function, possibly not initialized if not found on disk
References madness::f, madness::name(), madness::print(), madness::World::rank(), madness::reconstructed, madness::save(), and world.
make_all_bare_pairs()
Pairs< CCPair > madness::CCPairBuilder::make_all_bare_pairs () const inline
make a CCPair with the 6d function only and some bookkeeping information
References madness::CCParameters::freeze(), info, madness::Pairs< T >::insert(), make_bare_pair(), madness::Info::mo_bra, madness::Info::mo_ket, and madness::Info::parameters.
make_bare_pair()
CCPair madness::CCPairBuilder::make_bare_pair (const int i, const int j) const
make a CCPair without the 6d function and some bookkeeping information
References madness::CCPair::bsh_eps, cc_state(), ctype, ex_singles, madness::EXCITED_STATE, madness::CCParameters::freeze(), info, MADNESS_ASSERT, madness::Info::mo_bra, madness::Info::mo_ket, madness::CC_vecfunction::omega, and madness::Info::parameters.
Referenced by make_all_bare_pairs(), make_bare_pair_from_file(), and make_pair().
make_bare_pair_from_file()
CCPair madness::CCPairBuilder::make_bare_pair_from_file (const int i, const int j) const
make a CCPair with the 6d function only and some bookkeeping information
References madness::CCPair::constant_part, madness::CCParameters::debug(), madness::CCPair::functions, info, madness::Function< T, NDIM >::is_initialized(), make_bare_pair(), madness::CCPair::name(), madness::name(), and madness::Info::parameters.
make_pair()
CCPair madness::CCPairBuilder::make_pair (const int i, const int j, const std::vector< CCPairFunction< double, 6 > > & u) const
make a CCPair
make a CCPair with the given function
References madness::CCPair::functions, MADNESS_CHECK_THROW, make_bare_pair(), and u().
set_ctype()
CCPairBuilder & madness::CCPairBuilder::set_ctype (const CalcType & type) inline
References ctype, and madness::type().
set_ex_singles()
CCPairBuilder & madness::CCPairBuilder::set_ex_singles (const CC_vecfunction & ex) inline
provide excited state singles, needed for CC2 and LRCC2 wave function ansatz
References ex_singles.
set_gs_singles()
CCPairBuilder & madness::CCPairBuilder::set_gs_singles (const CC_vecfunction & gs) inline
provide ground-state singles, needed for CC2 and LRCC2 wave function ansatz
References gs_singles.
Member Data Documentation
ctype
CalcType madness::CCPairBuilder::ctype =CT_UNDEFINED
Referenced by make_bare_pair(), and set_ctype().
ex_singles
CC_vecfunction madness::CCPairBuilder::ex_singles
Referenced by complete_pair_with_low_rank_parts(), make_bare_pair(), and set_ex_singles().
gs_singles
CC_vecfunction madness::CCPairBuilder::gs_singles
Referenced by complete_pair_with_low_rank_parts(), and set_gs_singles().
info
const Info& madness::CCPairBuilder::info
Referenced by complete_pair_with_low_rank_parts(), make_all_bare_pairs(), make_bare_pair(), and make_bare_pair_from_file().
world
World& madness::CCPairBuilder::world
Referenced by complete_pair_with_low_rank_parts(), and load_function().
The documentation for this class was generated from the following files:
CCStructures.h
CCStructures.cc