MADNESS: madness::Hash_private::HashAccessor< hashT, lockmode > Class Template Reference
madness::Hash_private::HashAccessor< hashT, lockmode > Class Template Reference
#include <worldhashmap.h>
Public Types
typedef std::conditional< std::is_const< hashT >::value, typenamestd::add_const< typenamehashT::datumT >::type, typenamehashT::datumT >::type datumT
typedef std::conditional< std::is_const< hashT >::value, typenamestd::add_const< typenamehashT::entryT >::type, typenamehashT::entryT >::type entryT
typedef datumT * pointer
typedef datumT & reference
typedef datumT value_type
Public Member Functions
HashAccessor ()
HashAccessor (entryT *entry)
~HashAccessor ()
datumT & operator* () const
datumT * operator-> () const
void release ()
Private Member Functions
void convert_read_lock_to_write_lock ()
void set (entryT *entry)
Used by Hash to set entry (assumed that it has the lock already)
void unset ()
Used by Hash after having already released lock and deleted entry.
Private Member Functions inherited from NO_DEFAULTS
NO_DEFAULTS ()
NO_DEFAULTS (const NO_DEFAULTS &)=delete
NO_DEFAULTS (NO_DEFAULTS &&)=delete
NO_DEFAULTS & operator= (const NO_DEFAULTS &)=delete
NO_DEFAULTS & operator= (NO_DEFAULTS &&)=delete
Private Attributes
entryT * entry
bool gotlock
Friends
template<class a , class b , class c >
class madness::ConcurrentHashMap
Member Typedef Documentation
datumT
template<class hashT , int lockmode> typedef std::conditional<std::is_const<hashT>::value,typenamestd::add_const<typenamehashT::datumT>::type,typenamehashT::datumT>::type madness::Hash_private::HashAccessor< hashT, lockmode >::datumT
entryT
template<class hashT , int lockmode> typedef std::conditional<std::is_const<hashT>::value,typenamestd::add_const<typenamehashT::entryT>::type,typenamehashT::entryT>::type madness::Hash_private::HashAccessor< hashT, lockmode >::entryT
pointer
template<class hashT , int lockmode> typedef datumT* madness::Hash_private::HashAccessor< hashT, lockmode >::pointer
reference
template<class hashT , int lockmode> typedef datumT& madness::Hash_private::HashAccessor< hashT, lockmode >::reference
value_type
template<class hashT , int lockmode> typedef datumT madness::Hash_private::HashAccessor< hashT, lockmode >::value_type
Constructor & Destructor Documentation
HashAccessor() [1/2]
template<class hashT , int lockmode> madness::Hash_private::HashAccessor< hashT, lockmode >::HashAccessor () inline
HashAccessor() [2/2]
template<class hashT , int lockmode> madness::Hash_private::HashAccessor< hashT, lockmode >::HashAccessor (entryT * entry) inline
~HashAccessor()
template<class hashT , int lockmode> madness::Hash_private::HashAccessor< hashT, lockmode >::~HashAccessor () inline
References madness::Hash_private::HashAccessor< hashT, lockmode >::release().
Member Function Documentation
convert_read_lock_to_write_lock()
template<class hashT , int lockmode> void madness::Hash_private::HashAccessor< hashT, lockmode >::convert_read_lock_to_write_lock () inline private
References madness::MutexReaderWriter::convert_read_lock_to_write_lock().
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase().
operator*()
template<class hashT , int lockmode> datumT & madness::Hash_private::HashAccessor< hashT, lockmode >::operator* () const inline
References madness::Hash_private::entry< keyT, valueT >::datum, and MADNESS_EXCEPTION.
operator->()
template<class hashT , int lockmode> datumT * madness::Hash_private::HashAccessor< hashT, lockmode >::operator-> () const inline
References madness::Hash_private::entry< keyT, valueT >::datum, and MADNESS_EXCEPTION.
release()
template<class hashT , int lockmode> void madness::Hash_private::HashAccessor< hashT, lockmode >::release () inline
References madness::Hash_private::HashAccessor< hashT, lockmode >::gotlock, and madness::MutexReaderWriter::unlock().
Referenced by madness::Hash_private::HashAccessor< hashT, lockmode >::~HashAccessor(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::detail::DistCache< keyT >::get_cache_value(), madness::detail::DistCache< keyT >::get_cache_value(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), madness::Hash_private::HashAccessor< hashT, lockmode >::set(), madness::detail::DistCache< keyT >::set_cache_value(), and madness::World::unregister_ptr().
set()
template<class hashT , int lockmode> void madness::Hash_private::HashAccessor< hashT, lockmode >::set (entryT * entry) inline private
Used by Hash to set entry (assumed that it has the lock already)
References madness::Hash_private::HashAccessor< hashT, lockmode >::entry, madness::Hash_private::HashAccessor< hashT, lockmode >::gotlock, and madness::Hash_private::HashAccessor< hashT, lockmode >::release().
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
unset()
template<class hashT , int lockmode> void madness::Hash_private::HashAccessor< hashT, lockmode >::unset () inline private
Used by Hash after having already released lock and deleted entry.
References madness::Hash_private::HashAccessor< hashT, lockmode >::gotlock.
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase().
Friends And Related Symbol Documentation
madness::ConcurrentHashMap
template<class hashT , int lockmode> template<class a , class b , class c > friend class madness::ConcurrentHashMap friend
Member Data Documentation
entry
template<class hashT , int lockmode> entryT* madness::Hash_private::HashAccessor< hashT, lockmode >::entry private
Referenced by madness::Hash_private::HashAccessor< hashT, lockmode >::set().
gotlock
template<class hashT , int lockmode> bool madness::Hash_private::HashAccessor< hashT, lockmode >::gotlock private
Referenced by madness::Hash_private::HashAccessor< hashT, lockmode >::release(), madness::Hash_private::HashAccessor< hashT, lockmode >::set(), and madness::Hash_private::HashAccessor< hashT, lockmode >::unset().
The documentation for this class was generated from the following file:
worldhashmap.h