MADNESS: PNOTensors::Tensor_IJ_KJ< T > Class Template Reference
PNOTensors::Tensor_IJ_KJ< T > Class Template Reference
#include <PNOTensors.h>
Public Member Functions
Tensor_IJ_KJ (size_t n)
~Tensor_IJ_KJ ()=default
madness::Tensor< T > get (size_t i, size_t j, size_t k) const
std::tuple< size_t, bool > ijk (size_t i, size_t j, size_t k) const
bool is_initialized (size_t i, size_t j, size_t k) const
bool is_unique (size_t i, size_t j, size_t k) const
void reset ()
void set (size_t i, size_t j, size_t k, const madness::Tensor< T > &t)
Private Attributes
std::valarray< madness::Tensor< T > > data_
int n_
Detailed Description
template<typename T>
class PNOTensors::Tensor_IJ_KJ< T >
stores pairs of pairs that share second index (i.e. {ij} and {kj}, where i >= j) as a 3-index tensor: case 1 – i >= j, j >= k: store as {{ij},k} case 2 – i >= j, k > j: only need i >= k, or ij >= kj; store as {{ij},k}
Constructor & Destructor Documentation
Tensor_IJ_KJ()
template<typename T > PNOTensors::Tensor_IJ_KJ< T >::Tensor_IJ_KJ (size_t n) inline
References PNOTensors::Tensor_IJ_KJ< T >::reset().
~Tensor_IJ_KJ()
template<typename T > PNOTensors::Tensor_IJ_KJ< T >::~Tensor_IJ_KJ () default
Member Function Documentation
get()
template<typename T > madness::Tensor< T > PNOTensors::Tensor_IJ_KJ< T >::get (size_t i, size_t j, size_t k) const inline
References PNOTensors::Tensor_IJ_KJ< T >::data_, PNOTensors::Tensor_IJ_KJ< T >::ijk(), k, and PNOTensors::Tensor_IJ_KJ< T >::n_.
Referenced by madness::PNO::update_pno().
ijk()
template<typename T > std::tuple< size_t, bool > PNOTensors::Tensor_IJ_KJ< T >::ijk (size_t i, size_t j, size_t k) const inline
References k, PNOTensors::Tensor_IJ_KJ< T >::n_, and PNOTensors::tridx().
Referenced by PNOTensors::Tensor_IJ_KJ< T >::get(), PNOTensors::Tensor_IJ_KJ< T >::is_initialized(), and PNOTensors::Tensor_IJ_KJ< T >::set().
is_initialized()
template<typename T > bool PNOTensors::Tensor_IJ_KJ< T >::is_initialized (size_t i, size_t j, size_t k) const inline
References PNOTensors::Tensor_IJ_KJ< T >::data_, PNOTensors::Tensor_IJ_KJ< T >::ijk(), k, and PNOTensors::Tensor_IJ_KJ< T >::n_.
Referenced by madness::PNO::iterate_pairs_internal(), and madness::PNO::update_pno().
is_unique()
template<typename T > bool PNOTensors::Tensor_IJ_KJ< T >::is_unique (size_t i, size_t j, size_t k) const inline
References k, and PNOTensors::Tensor_IJ_KJ< T >::n_.
reset()
template<typename T > void PNOTensors::Tensor_IJ_KJ< T >::reset () inline
References PNOTensors::Tensor_IJ_KJ< T >::data_.
Referenced by PNOTensors::Tensor_IJ_KJ< T >::Tensor_IJ_KJ(), madness::PNOPairs::clear_intermediates(), madness::PNO::iterate_pairs_internal(), and madness::PNO::update_pno().
set()
template<typename T > void PNOTensors::Tensor_IJ_KJ< T >::set (size_t i, size_t j, size_t k, const madness::Tensor< T > & t) inline
References PNOTensors::Tensor_IJ_KJ< T >::data_, PNOTensors::Tensor_IJ_KJ< T >::ijk(), k, PNOTensors::Tensor_IJ_KJ< T >::n_, and madness::Tensor< T >::swapdim().
Referenced by madness::PNO::iterate_pairs_internal(), and madness::PNO::update_pno().
Member Data Documentation
data_
template<typename T > std::valarray<madness::Tensor<T> > PNOTensors::Tensor_IJ_KJ< T >::data_ private
Referenced by PNOTensors::Tensor_IJ_KJ< T >::get(), PNOTensors::Tensor_IJ_KJ< T >::is_initialized(), PNOTensors::Tensor_IJ_KJ< T >::reset(), and PNOTensors::Tensor_IJ_KJ< T >::set().
n_
template<typename T > int PNOTensors::Tensor_IJ_KJ< T >::n_ private
Referenced by PNOTensors::Tensor_IJ_KJ< T >::get(), PNOTensors::Tensor_IJ_KJ< T >::ijk(), PNOTensors::Tensor_IJ_KJ< T >::is_initialized(), PNOTensors::Tensor_IJ_KJ< T >::is_unique(), and PNOTensors::Tensor_IJ_KJ< T >::set().
The documentation for this class was generated from the following file:
PNOTensors.h