MADNESS: density_smoothing.cc File Reference
density_smoothing.cc File Reference
solve the HF equations using numerical exponential MOs
#include "smooth.h"
#include "madness/mra/commandlineparser.h"
#include <madness/misc/info.h>
Functions
int main (int argc, char **argv)
Detailed Description
solve the HF equations using numerical exponential MOs
The source is here.
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), energy, madness::error(), madness::finalize(), madness::Nemo::get_calc(), madness::FunctionDefaults< NDIM >::get_cell_min_width(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::info::git_source_description(), madness::initialize(), madness::NemoBase::ncf, madness::plot_line(), madness::plot_plane(), madness::print(), R2, madness::World::rank(), madness::smooth< T, NDIM >::smooth_density_from_orbitals(), madness::startup(), madness::Function< T, NDIM >::truncate(), madness::Nemo::value(), and madness::wall_time().