MADNESS: DF.cc File Reference
DF.cc File Reference
#include "DF.h"
#include "fcwf.h"
#include <madness/chem/potentialmanager.h>
Classes
class FermiNucDistFunctor
struct function_real2complex_op< Q, NDIM >
class GaussianNucleusFunctor
struct lbcost< T, NDIM >
Functions
void apply_BSH (World &world, Fcwf &Vpsi, double &eps, double &small, double &thresh)
void apply_BSH_new (World &world, Fcwf &Vpsi, double &eps, double &small, double &thresh)
Fcwf apply_T (World &world, Fcwf &psi)
Function< std::complex< double >, 3 > function_real2complex (const Function< double, 3 > &r)
static std::vector< std::shared_ptr< SeparatedConvolution< double, 3 > > > GradBSHOperator_Joel (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
double myr (const coord_3d &r)
double myxfunc (const madness::coord_3d &r)
double myyfunc (const madness::coord_3d &r)
Tensor< std::complex< double > > Q2 (const Tensor< std::complex< double >> &s)
Function Documentation
apply_BSH()
void apply_BSH (World & world, Fcwf & Vpsi, double & eps, double & small, double & thresh)
References apply(), madness::BSHOperatorPtr3D(), madness::WorldGopInterface::fence(), madness::World::gop, madness::GradBSHOperator(), mu, op(), small, thresh, and transform().
apply_BSH_new()
void apply_BSH_new (World & world, Fcwf & Vpsi, double & eps, double & small, double & thresh)
References apply(), apply_T(), madness::BSHOperator3D(), madness::WorldGopInterface::fence(), madness::World::gop, mu, op(), small, and thresh.
Referenced by DF::iterate().
apply_T()
Fcwf apply_T (World & world, Fcwf & psi)
References apply(), Fcwf::compress(), and psi().
Referenced by apply_BSH_new(), DF::diagonalize(), and DF::rele().
function_real2complex()
Function<std::complex<double>,3> function_real2complex (const Function< double, 3 > & r)
References madness::unary_op_coeffs().
GradBSHOperator_Joel()
static std::vector< std::shared_ptr< SeparatedConvolution<double,3> > > GradBSHOperator_Joel (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating operator for convolution with grad(bsh) in 3D Returns a 3-vector containing the convolution operator for the x, y, and z components of grad(bsh)
References madness::BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), c, d(), madness::BaseTensor::dim(), madness::dir, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), pi, madness::constants::pi, and pow().
myr()
double myr (const coord_3d & r)
Referenced by DF::iterate().
myxfunc()
double myxfunc (const madness::coord_3d & r)
Referenced by madness::InitParameters::read().
myyfunc()
double myyfunc (const madness::coord_3d & r)
Referenced by madness::InitParameters::read().
Q2()
Tensor<std::complex<double> > Q2 (const Tensor< std::complex< double >> & s)
References Q().
Referenced by DF::orthogonalize_inplace().