MADNESS: DFdriver.cc File Reference
DFdriver.cc File Reference
#include <madness/misc/info.h>
#include "DF.h"
#include <stdlib.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, DF::help(), madness::initialize(), madness::commandlineparser::key_exists(), madness::print(), madness::print_header1(), DF::print_parameters(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), DF::solve(), madness::startup(), and madness::commandlineparser::value().