MADNESS: dielectric_external_field.cc File Reference
dielectric_external_field.cc File Reference
Example solution of Laplace's equations for dielectric sphere in an external field.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/funcplot.h>
#include <madness/tensor/solvers.h>
#include "molecularmask.h"
#include <madness/mra/nonlinsol.h>
#include <madness/constants.h>
#include <vector>
Functions
double exact_function (const coord_3d &x)
int main (int argc, char **argv)
Variables
const double delta = 0.65*sigma
const double epsilon_0 = 100.0
const double epsilon_1 = 1.0
const double Ez = 0.05
const int k = 6
const double L = 50
const double R = 20.0
const double sigma = 0.3
const double thresh = 1e-4
Detailed Description
Example solution of Laplace's equations for dielectric sphere in an external field.
Function Documentation
exact_function()
double exact_function (const coord_3d & x)
References epsilon_0, epsilon_1, Ez, pow(), and R.
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::_(), madness::BC_FREE, SafeMPI::COMM_WORLD, madness::CoulombOperator(), delta, epsilon_0, epsilon_1, exact_function(), Ez, madness::finalize(), madness::initialize(), k, L, lo, madness::norm2(), op(), madness::constants::pi, madness::plot_line(), madness::plotdx(), madness::print(), R, madness::Function< T, NDIM >::scale(), madness::Tensor< T >::scale(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), sigma, madness::startup(), thresh, madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), madness::truncate(), u(), and madness::NonlinearSolverND< NDIM >::update().
Variable Documentation
delta
const double delta = 0.65*sigma
Referenced by cfrac(), madness::Function< T, NDIM >::eval_cube(), madness::gauss_legendre_numeric(), madness::Zcis::iterate(), madness::CC2::iterate_pair(), madness::TDHF::iterate_vectors(), main(), madness::TDHF::make_cis_matrix(), madness::TDHF::orthonormalize(), CFFT::Perform(), CalculationParameters::print_info(), CalculationParameters::read_file(), CalculationParameters::serialize(), madness::CC2::solve_cc2(), test_convergence(), and madness::Solver< T, NDIM >::test_periodicity().
epsilon_0
const double epsilon_0 = 100.0
Referenced by exact_function(), and main().
epsilon_1
const double epsilon_1 = 1.0
Referenced by exact_function(), and main().
Ez
const double Ez = 0.05
Referenced by exact_function(), and main().
k
const int k = 6
Referenced by main().
L
const double L = 50
Referenced by main().
R
const double R = 20.0
Referenced by exact_function(), and main().
sigma
const double sigma = 0.3
Referenced by main().
thresh
const double thresh = 1e-4
Referenced by main().