MADNESS: DKops.h File Reference
DKops.h File Reference
#include <madness/mra/mra.h>
#include <madness/constants.h>
#include <madness/mra/operator.h>
#include <iostream>
#include <fstream>
#include <exception>
Functions
real_convolution_3d A (World &world)
real_convolution_3d A2 (World &world)
real_convolution_3d Ebar (World &world, double eps)
double Ebark (double t, double eps)
std::vector< real_convolution_3d_ptr > gradPbarA (World &world)
real_convolution_3d Pbar (World &world)
real_convolution_3d PbarA (World &world)
double q (double t)
real_convolution_3d Tbar (World &world)
double w (double t, double eps)
Variables
static const double opthresh = 1e-16
Function Documentation
A()
real_convolution_3d A (World & world)
References c, madness::constants::pi, pow(), madness::World::rank(), and madness::vec().
Referenced by apply_potential(), Calculation::calc_optimal_coeffs(), madness::cholesky(), madness::Diamagnetic_potential_factor::compute_lz_commutator(), madness::Znemo::compute_magnetic_vector_potential(), madness::distributed_localize_PM(), madness::jacobi(), jacobi(), KAIN(), madness::KAIN(), madness::lq_result(), make_fit(), madness::Solver< T, NDIM >::matrix_exponential(), madness::Localizer::matrix_exponential(), matrix_exponential(), madness::matrix_inner(), madness::DistributedMatrix< T >::operator+(), optimize_coeffs(), madness::rank_revealing_decompose(), madness::rr_cholesky(), madness::svd(), and madness::test_inverse().
A2()
real_convolution_3d A2 (World & world)
References c, madness::constants::pi, pow(), madness::World::rank(), and madness::vec().
Ebar()
real_convolution_3d Ebar (World & world, double eps)
References Ebark(), opthresh, madness::constants::pi, pow(), q(), madness::BaseTensor::size(), madness::vec(), and w().
Referenced by make_bsh_operator().
Ebark()
double Ebark (double t, double eps)
References e(), pow(), q(), R, and w().
Referenced by Ebar().
gradPbarA()
std::vector<real_convolution_3d_ptr> gradPbarA (World & world)
References c, cc, d(), madness::dir, madness::FunctionDefaults< NDIM >::get_cell_width(), madness::FunctionDefaults< NDIM >::get_k(), k, mu, madness::Tensor< T >::normf(), pi, madness::constants::pi, pow(), and madness::World::rank().
Referenced by apply_potential().
Pbar()
real_convolution_3d Pbar (World & world)
References c, madness::World::rank(), and madness::vec().
PbarA()
real_convolution_3d PbarA (World & world)
References c, madness::constants::pi, pow(), madness::World::rank(), and madness::vec().
Referenced by apply_potential().
q()
double q (double t)
Referenced by madness::SeparatedConvolutionData< Q, NDIM >::SeparatedConvolutionData(), madness::Molecule::add_atom(), MolecularEntity::add_atom(), PointGroup::apply(), madness::Solver< T, NDIM >::apply_hf_exchange(), madness::Solver< T, NDIM >::apply_hf_exchange4(), arithmetic_series(), madness::Tensor< T >::binary_iterator(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_spherical_moments(), check(), madness::CC2::compute_local_coupling(), da_ldaop(), DF::diagonalize(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), Ebar(), Ebark(), madness::FunctionImpl< T, NDIM >::eval_cube(), fixphases(), Key::foreach_child(), madness::GFit< T, NDIM >::gaussian_spherical_moments(), geometric_series(), he_ldaop(), QuasiNewton::hessian_update_sr1(), madness::QuasiNewton::hessian_update_sr1(), madness::SCF::initial_guess(), PointGroup::ircell(), ldaop(), madness::Molecule::moment_of_inertia(), madness::mTxmT(), madness::mul(), FiniteNucleusPotential::operator()(), madness::xc_lda_potential::operator()(), madness::Function< T, NDIM >::operator*=(), madness::Vector< T, N >::operator*=(), madness::Vector< T, N >::operator+=(), madness::Vector< T, N >::operator-=(), madness::Molecule::orient(), MolecularEntity::print(), madness::print_stats(), madness::qm_free_particle_propagator(), madness::qm_free_particle_propagatorPtr(), madness::QCCalculationParametersBase::read_commandline_options(), madness::Molecule::read_core_file(), madness::InitParameters::readnw(), madness::Function< T, NDIM >::scale(), madness::FunctionImpl< T, NDIM >::scale_inplace(), madness::FunctionImpl< T, NDIM >::scale_oop(), madness::CorePotentialManager::set_eprec(), madness::Tensor< T >::ternary_iterator(), Test6(), Test7(), test_gconv(), test_in(), test_out(), test_projector_outer(), testgradG(), madness::Localizer::undo_rotation(), and madness::XCfunctional::vxc().
Tbar()
real_convolution_3d Tbar (World & world)
References c, madness::World::rank(), and madness::vec().
Referenced by compute_energy(), and compute_energy_simple().
w()
double w (double t, double eps)
References c, PI, and madness::constants::pi.
Referenced by madness::adq1(), madness::do_adq(), doit(), Ebar(), Ebark(), errsq(), madness::FunctionImpl< T, NDIM >::filter(), madness::gauss_legendre(), madness::gauss_legendre_numeric(), madness::gauss_legendre_test(), geev_(), madness::detail::DeferredCleanup::get_deferred_cleanup(), ggev_(), madness::WorldAmInterface::handler(), main(), makedata(), madness::SRConf< T >::max_sigma(), opt(), optimize_coeffs(), madness::FunctionImpl< T, NDIM >::partial_inner_contract(), madness::OEP::print_parameters(), madness::detail::RemoteCounter::register_ptr_(), madness::TaskInterface::run(), schrodinger2dirac(), madness::TaskInterface::set_info(), syev_(), sygv_(), test(), madness::time_transform(), madness::FunctionImpl< T, NDIM >::unfilter(), updatex(), and Fred::value_and_gradient().
Variable Documentation
opthresh
const double opthresh = 1e-16 static
Referenced by Ebar().