MADNESS: erfcr.cc File Reference
erfcr.cc File Reference
#include <iostream>
#include <utility>
#include <vector>
#include <cmath>
#include <madness/misc/gnuplot.h>
Functions
int main ()
std::pair< std::vector< double >, std::vector< double > > make_fit (double a, double epsilon, double rlo)
Function Documentation
main()
int main (void)
References a, std::abs(), c, e(), epsilon, exact, fit(), make_fit(), madness::Gnuplot::plot(), R, and sum.
make_fit()
std::pair< std::vector< double >, std::vector< double > > make_fit (double a, double epsilon, double rlo)
References a, e(), epsilon, K(), omega, pi, and T().
Referenced by main().