MADNESS: excited_state_calc.cpp File Reference
excited_state_calc.cpp File Reference
#include "ExcitedResponse.hpp"
#include "ResponseExceptions.hpp"
#include "madness/tensor/tensor_json.hpp"
#include "madness/world/worldmem.h"
#include "response_functions.h"
#include "timer.h"
Typedefs
using path = std::filesystem::path
Functions
int main (int argc, char *argv[])
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
main()
int main (int argc, char * argv[])
References e(), madness::error(), madness::WorldGopInterface::fence(), madness::filename, madness::World::gop, madness::initialize(), initialize_calc_params(), madness::print(), madness::World::rank(), and madness::startup().