MADNESS: fcwf.h File Reference
fcwf.h File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <vector>
#include <math.h>
#include <complex>
Classes
class Fcwf
class Fcwf_vector_allocator
Functions
Fcwf apply (World &world, complex_derivative_3d &op, const Fcwf &psi)
Fcwf apply (World &world, real_convolution_3d &op, const Fcwf &psi)
Fcwf copy (Fcwf psi)
std::complex< double > inner (const Fcwf &psi, const Fcwf &phi)
std::complex< double > inner (std::vector< Fcwf > &a, std::vector< Fcwf > &b)
complex_function_3d inner_func (World &world, Fcwf &psi, Fcwf &phi)
Tensor< std::complex< double > > matrix_inner (World &world, std::vector< Fcwf > &a, std::vector< Fcwf > &b)
std::vector< Fcwf > operator* (const std::vector< Fcwf > &psis, std::complex< double > a)
std::vector< Fcwf > operator* (std::complex< double > a, const std::vector< Fcwf > &psis)
void operator+= (std::vector< Fcwf > &phi, const std::vector< Fcwf > &psi)
std::vector< Fcwf > operator- (const std::vector< Fcwf > &phi, const std::vector< Fcwf > &psi)
real_function_3d squaremod (Fcwf &psi)
real_function_3d squaremod_large (Fcwf &psi)
real_function_3d squaremod_small (Fcwf &psi)
std::vector< Fcwf > transform (World &world, std::vector< Fcwf > &a, Tensor< std::complex< double >> U)
Function Documentation
apply() [1/2]
Fcwf apply (World & world, complex_derivative_3d & op, const Fcwf & psi)
References Fcwf::apply(), madness::copy(), and psi().
apply() [2/2]
Fcwf apply (World & world, real_convolution_3d & op, const Fcwf & psi)
References Fcwf::apply(), madness::copy(), op(), and psi().
Referenced by apply_BSH(), apply_BSH_new(), apply_T(), DF::diagonalize(), DF::exchange(), DF::iterate(), kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), madness::Cloud::load_tuple(), molresponseExchange(), madness::MacroTask< taskT >::MacroTaskInternal::run(), DF::solve_occupied(), madness::Cloud::store_tuple(), and T().
copy()
Fcwf copy (Fcwf psi)
References psi().
Referenced by madness::Vector< T, N >::Vector(), madness::Batch_1D::copy_batch(), madness::Znemo::custom_guess(), dft_xc_lda_ene(), dft_xc_lda_V(), DF::diagonalize(), ground_exchange(), madness::LRFunctorF12< T, NDIM, LDIM >::inner(), madness::Batch_1D::insert_batch(), molresponseExchange(), madness::Vector< T, N >::operator=(), madness::XCOperator< T, NDIM >::prep_xc_args(), madness::print_meminfo(), slymer::NWChem_Interface::read_movecs(), AtomicBasis::set_guess_info(), madness::PNO::t_solve(), madness::to_flattened_vector(), madness::to_X_space(), and vector_to_PQ().
inner() [1/2]
std::complex<double> inner (const Fcwf & psi, const Fcwf & phi)
References Fcwf::getinitialize(), MADNESS_ASSERT, and psi().
Referenced by madness::NemoBase::compute_gradient(), DF::diagonalize(), DF::iterate(), kinetic_energy_matrix_slow(), madness::Q3(), and DF::rele().
inner() [2/2]
std::complex<double> inner (std::vector< Fcwf > & a, std::vector< Fcwf > & b)
References a, b, madness::inner(), and MADNESS_ASSERT.
inner_func()
complex_function_3d inner_func (World & world, Fcwf & psi, Fcwf & phi)
References a, b, c, madness::conj(), madness::copy(), Fcwf::getinitialize(), MADNESS_ASSERT, madness::mul(), psi(), and madness::sum().
matrix_inner()
Tensor<std::complex<double> > matrix_inner (World & world, std::vector< Fcwf > & a, std::vector< Fcwf > & b)
References a, b, and m.
Referenced by DF::diagonalize(), kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), and DF::orthogonalize_inplace().
operator*() [1/2]
std::vector<Fcwf> operator* (const std::vector< Fcwf > & psis, std::complex< double > a)
References a.
operator*() [2/2]
std::vector<Fcwf> operator* (std::complex< double > a, const std::vector< Fcwf > & psis)
References a.
operator+=()
void operator+= (std::vector< Fcwf > & phi, const std::vector< Fcwf > & psi)
References MADNESS_ASSERT, and psi().
operator-()
std::vector<Fcwf> operator- (const std::vector< Fcwf > & phi, const std::vector< Fcwf > & psi)
References MADNESS_ASSERT, and psi().
squaremod()
real_function_3d squaremod (Fcwf & psi)
References madness::abssq(), MADNESS_ASSERT, psi(), and madness::Function< T, NDIM >::scale().
Referenced by DF::diagonalize(), DF::iterate(), DF::make_density_lineplots(), and DF::solve_occupied().
squaremod_large()
real_function_3d squaremod_large (Fcwf & psi)
References madness::abssq(), MADNESS_ASSERT, and psi().
Referenced by DF::make_component_lineplots(), and DF::make_component_logplots().
squaremod_small()
real_function_3d squaremod_small (Fcwf & psi)
References madness::abssq(), MADNESS_ASSERT, psi(), and madness::scale().
Referenced by DF::make_component_lineplots(), and DF::make_component_logplots().
transform()
std::vector<Fcwf> transform (World & world, std::vector< Fcwf > & a, Tensor< std::complex< double >> U)
References a, k, m, and MADNESS_ASSERT.
Referenced by madness::projector_irrep::projector_irrep(), apply_BSH(), madness::response_space::copy(), madness::archive::default_serialize(), DF::diagonalize(), madness::F12Parameters::energytype(), madness::QCCalculationParametersBase::fromstring(), madness::projector_irrep::get_table(), madness::XCfunctional::initialize(), madness::ACParameters< NDIM >::initialize(), main(), madness::operator>>(), DF::orthogonalize_inplace(), madness::PNOParameters::partial_wave(), madness::QCCalculationParametersBase::read_internal(), madness::projector_irrep::set_irrep(), TEST_CASE(), madness::to_conjugate_X_space(), madness::commandlineparser::tolower(), madness::QCCalculationParametersBase::tostring(), madness::Znemo::potentials::transform(), and transform3d().