MADNESS: fred.cc File Reference
fred.cc File Reference
#include <iostream>
#include <cmath>
#include <madness/tensor/tensor.h>
#include <madness/tensor/tensor_lapack.h>
#include <madness/world/print.h>
Functions
void drot (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c)
int main ()
Function Documentation
drot()
void drot (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c)
References a, aa, b, c, and madness::nonlinear_vector_solver().
main()
int main (void)
References c, madness::copy(), d, madness::drot(), e(), IND, madness::inner(), ITERATOR, ndone, madness::nonlinear_vector_solver(), pi, madness::print(), sum, thresh, and madness::transpose().