MADNESS: FrequencyResponse.cpp File Reference
FrequencyResponse.cpp File Reference
#include "FrequencyResponse.hpp"
#include "property.h"
Functions
auto dipole_generator (World &world, FrequencyResponse &calc) -> X_space
auto nuclear_generator (World &world, FrequencyResponse &calc) -> X_space
auto vector_to_PQ (World &world, const vector_real_function_3d &rhs_operators, const vector_real_function_3d &ground_orbitals) -> response_space
Function Documentation
dipole_generator()
auto dipole_generator (World & world, FrequencyResponse & calc) -> X_space
References madness::response_space::copy(), d, madness::f, madness::WorldGopInterface::fence(), madness::World::gop, molecule, madness::print(), madness::World::rank(), vector_to_PQ(), madness::X_space::x, and madness::X_space::y.
Referenced by main(), main(), TEST_CASE(), and TEST_CASE().
nuclear_generator()
auto nuclear_generator (World & world, FrequencyResponse & calc) -> X_space
References axis, madness::func(), molecule, madness::Molecule::natom(), truncate_mode, vector_to_PQ(), madness::X_space::x, and madness::X_space::y.
Referenced by main(), TEST_CASE(), and TEST_CASE().
vector_to_PQ()
auto vector_to_PQ (World & world, const vector_real_function_3d & rhs_operators, const vector_real_function_3d & ground_orbitals) -> response_space
References b, madness::copy(), madness::mul(), pi, madness::reconstruct(), madness::World::size(), and madness::truncate().
Referenced by dipole_generator(), and nuclear_generator().