MADNESS: FunctionIOHDF5.h File Reference
FunctionIOHDF5.h File Reference
#include "ccpairfunction.h"
#include "funcdefaults.h"
#include "madness/mra/function_common_data.h"
#include <iostream>
#include <madness/mra/mra.h>
#include <h5cpp/h5cpp.hpp>
Classes
class FunctionIO< T, NDIM >
struct FunctionIOData< T, NDIM >
Functions
template<typename T , std::size_t NDIM>
void from_json (const json &j, FunctionIOData< T, NDIM > &p)
constexpr int simple_pow (int a, int b)
template<typename T , std::size_t NDIM>
void to_json (json &j, const FunctionIOData< T, NDIM > &p)
Function Documentation
from_json()
template<typename T , std::size_t NDIM> void from_json (const json & j, FunctionIOData< T, NDIM > & p)
References p().
simple_pow()
constexpr int simple_pow (int a, int b) constexpr
References a, and b.
Referenced by FunctionIOData< T, NDIM >::FunctionIOData().
to_json()
template<typename T , std::size_t NDIM> void to_json (json & j, const FunctionIOData< T, NDIM > & p)
References p().