MADNESS: generate_frequency_data.cpp File Reference
generate_frequency_data.cpp File Reference
#include "ResponseExceptions.hpp"
#include "madness/chem/SCF.h"
#include "madness/tensor/tensor_json.hpp"
#include "madness/world/worldmem.h"
#include "response_data_base.hpp"
#include "response_functions.h"
#include "string"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References e(), madness::initialize(), op(), print(), madness::startup(), and xc.