MADNESS: global_functions.h File Reference
global_functions.h File Reference
#include <memory>
#include <string>
#include <vector>
#include "response_parameters.h"
Classes
struct CalcParams
class plotCoords
Functions
auto ground_exchange (const vecfuncT &phi0, const X_space &x, bool compute_y) -> X_space
auto ground_exchange_multiworld (const vecfuncT &phi0, const X_space &x, const bool &compute_y) -> X_space
CalcParams initialize_calc_params (World &world, const std::string &input_file)
vecfuncT K (vecfuncT &ket, vecfuncT &bra, vecfuncT &vf)
auto make_k (const vecfuncT &ket, const vecfuncT &bra)
auto molresponseExchange (World &world, const vecfuncT &ket_i, const vecfuncT &bra_i, const vecfuncT &fp, const int &n, const int &num_states, const int &num_orbitals) -> X_space
vecfuncT newK (const vecfuncT &ket, const vecfuncT &bra, const vecfuncT &vf)
void print_molecule (World &world, const GroundStateCalculation &g_params)
auto response_exchange (const vecfuncT &phi0, const X_space &x, bool compute_y) -> X_space
auto response_exchange_multiworld (const vecfuncT &phi0, const X_space &chi, const bool &compute_y) -> X_space
static double rsquared (const coord_3d &r)
plotCoords SetPlotCoord (size_t i, double Lp)
response_space T (World &world, response_space &f)
Function Documentation
ground_exchange()
auto ground_exchange (const vecfuncT & phi0, const X_space & x, const bool compute_y) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References b, madness::copy(), molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, K(), molresponseExchange(), madness::nonlinear_vector_solver(), p(), madness::print(), madness::World::rank(), molresponse::start_timer(), madness::to_response_matrix(), and madness::X_space::zero_functions().
ground_exchange_multiworld()
auto ground_exchange_multiworld (const vecfuncT & phi0, const X_space & chi, const bool & compute_y) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References madness::WorldGopInterface::fence(), madness::World::gop, k0, make_k(), madness::nonlinear_vector_solver(), molresponse::start_timer(), and madness::X_space::zero_functions().
initialize_calc_params()
CalcParams initialize_calc_params (World & world, const std::string & input_file)
References madness::WorldGopInterface::fence(), madness::World::gop, molecule, madness::nonlinear_vector_solver(), madness::Molecule::print(), madness::World::rank(), and madness::commandlineparser::set_keyval().
Referenced by main(), main(), TEST_CASE(), and TEST_CASE().
K()
vecfuncT K (vecfuncT & ket, vecfuncT & bra, vecfuncT & vf)
Referenced by madness::SCF::apply_potential(), madness::OEP::compute_and_print_final_energies(), madness::Nemo::compute_energy_regularized(), madness::OEP::compute_exchange_potential(), madness::MP3::compute_mp3_klmn(), madness::Nemo::compute_nemo_potentials(), madness::Znemo::compute_potentials(), madness::OEP::compute_slater_potential(), madness::exchange_anchor_test(), exchange_anchor_test(), ground_exchange(), kth_moment_func3d(), main(), main(), make_fit(), madness::Nemo::make_fock_operator(), response_exchange(), response_exchange_multiworld(), madness::Nemo::solve_cphf(), slymer::Gaussian_Functor::special_level(), test2(), madness::test_exchange(), test_exchange(), and test_fock().
make_k()
auto make_k (const vecfuncT & ket, const vecfuncT & bra)
References k, lo, madness::Exchange< T, NDIM >::set_algorithm(), and madness::Exchange< T, NDIM >::set_bra_and_ket().
Referenced by ground_exchange_multiworld(), and response_exchange_multiworld().
molresponseExchange()
auto molresponseExchange (World & world, const vecfuncT & ket_i, const vecfuncT & bra_i, const vecfuncT & fp, const int & n, const int & num_states, const int & num_orbitals) -> X_space
References madness::apply(), b, madness::compress(), madness::copy(), madness::create_response_matrix(), molresponse::end_timer(), madness::FunctionDefaults< NDIM >::get_thresh(), lo, madness::mul(), madness::nonlinear_vector_solver(), madness::print(), madness::reconstruct(), set_poisson(), molresponse::start_timer(), madness::to_X_space(), madness::truncate(), xi, and madness::X_space::zero_functions().
Referenced by ground_exchange().
newK()
vecfuncT newK (const vecfuncT & ket, const vecfuncT & bra, const vecfuncT & vf)
References lo, madness::nonlinear_vector_solver(), and op().
print_molecule()
void print_molecule (World & world, const GroundStateCalculation & g_params)
response_exchange()
auto response_exchange (const vecfuncT & phi0, const X_space & x, const bool compute_y) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References b, K(), madness::nonlinear_vector_solver(), p(), and molresponse::start_timer().
response_exchange_multiworld()
auto response_exchange_multiworld (const vecfuncT & phi0, const X_space & chi, const bool & compute_y) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References b, madness::WorldGopInterface::fence(), madness::gaxpy_oop(), madness::World::gop, K(), make_k(), madness::nonlinear_vector_solver(), molresponse::start_timer(), and madness::X_space::zero_functions().
rsquared()
static double rsquared (const coord_3d & r) static
SetPlotCoord()
plotCoords SetPlotCoord (size_t i, double Lp)
T()
response_space T (World & world, response_space & f)
References madness::apply(), madness::f, madness::nonlinear_vector_solver(), and T().
Referenced by madness::BinSorter< T, inserterT >::BinSorter(), madness::Stack< T, N >::Stack(), madness::TensorIterator< T, Q, R >::TensorIterator(), madness::abs(), madness::Tensor< T >::absmax(), madness::Tensor< T >::absmin(), madness::add(), madness::add(), madness::add(), madness::add(), madness::MemoryMeasurer::add_memory_to_map(), madness::FutureImpl< T >::add_to_assignments(), madness::aligned_zero(), madness::Stack< T, N >::allocate(), madness::Tensor< T >::allocate(), madness::Cloud::allocator(), madness::SeparatedConvolution< Q, NDIM >::apply(), madness::apply(), madness::apply(), madness::apply(), madness::apply(), madness::SeparatedConvolution< Q, NDIM >::apply2(), madness::SeparatedConvolution< Q, NDIM >::apply2_lowdim(), madness::arg(), madness::PNOParameters::assign_from_string(), madness::WorldMpiInterface::Bcast(), madness::WorldMpiInterface::Bcast(), madness::WorldGopInterface::broadcast(), madness::Zcis::canonicalize(), slymer::cast_basis(), check(), madness::QCCalculationParametersBase::check_type(), madness::QCCalculationParametersBase::check_type_silent(), madness::Nemo::compute_fock_matrix(), madness::Zcis::compute_fock_pt(), madness::Recordlist< keyT >::compute_record(), madness::Tensor< T >::conj(), madness::conj(), madness::convert(), madness::copy(), madness::cross(), csqrt_op(), madness::SystolicMatrixAlgorithm< T >::cycle(), madness::detail::arg_holder::decay(), madness::detail::arg_holder::decay(), madness::detail::arg_holder::decay(), madness::TensorTrain< T >::decompose(), madness::archive::default_serialize(), madness::FunctionImpl< T, NDIM >::do_dot_localX(), madness::FunctionImpl< T, NDIM >::do_inner_localX(), madness::Cloud::do_load(), madness::FunctionImpl< T, NDIM >::do_mul(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::FunctionImpl< T, NDIM >::dot_local(), madness::Tensor< T >::emul(), energy(), madness::CubicInterpolationTable< T >::err(), madness::FunctionImpl< T, NDIM >::eval_cube(), madness::fast_transform(), madness::fast_transpose(), madness::fcube(), madness::Tensor< T >::fillindex(), madness::Tensor< T >::fillrandom(), find_fuzzy(), madness::Cloud::forward_load(), madness::QCCalculationParametersBase::fromstring(), madness::Tensor< T >::gaxpy(), madness::FunctionImpl< T, NDIM >::gaxpy_ext_recursive(), madness::FunctionImpl< T, NDIM >::gaxpy_inplace(), madness::gaxpy_oop(), madness::gaxpy_oop(), gen_ce(), madness::general_transform(), madness::general_transform(), madness::detail::RemoteCounter::get_shared(), madness::RemoteReference< T >::get_shared(), madness::get_size(), madness::get_size(), madness::get_size_local(), madness::Random::getv(), madness::GMRES(), madness::DQueue< T >::grow(), madness::hash_range(), madness::hash_value(), madness::Znemo::hcore_guess(), madness::DistributedMatrix< T >::idij(), madness::imag(), madness::inner(), madness::inner(), madness::inner(), madness::inner(), madness::Function< T, NDIM >::inner_adaptive(), madness::FunctionImpl< T, NDIM >::inner_adaptive_local(), madness::FunctionImpl< T, NDIM >::inner_adaptive_recursive(), madness::Function< T, NDIM >::inner_ext(), madness::FunctionImpl< T, NDIM >::inner_ext_local(), madness::Function< T, NDIM >::inner_ext_local(), madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), madness::FunctionImpl< T, NDIM >::inner_local(), madness::inner_result(), madness::innerXX(), invert(), madness::WorldMpiInterface::Irecv(), madness::WorldMpiInterface::Irecv(), madness::WorldMpiInterface::Isend(), madness::Znemo::iterate(), madness::OEP::iterate(), madness::DFT< T, NDIM >::iterateOutput(), KAIN(), madness::KAIN(), ldaeop(), ldaop(), madness::archive::ArchiveLoadImpl< Archive, Future< T >, std::enable_if_t<!std::is_void_v< T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::array< T, N >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::complex< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::list< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), madness::archive::BinaryFstreamInputArchive::load(), madness::archive::BufferInputArchive::load(), madness::archive::VectorInputArchive::load(), madness::Cloud::load_from_cache(), madness::Cloud::load_tuple(), madness::lq_result(), main(), madness::Solver< T, NDIM >::make_bsh_operators(), make_fit(), make_grad_operator(), make_operator(), madness::TDHF::make_perturbed_fock_matrix(), madness::CCPairFunction< T, NDIM >::make_xy_u(), madness::matrix_dot(), madness::matrix_dot_old(), madness::matrix_inner(), madness::matrix_inner_old(), madness::Tensor< T >::max(), madness::Tensor< T >::min(), madness::Convolution1D< Q >::mod_nonstandard(), madness::Stack< T, N >::move(), madness::mTxm(), madness::mTxmq(), madness::mTxmT(), madness::mul(), madness::FunctionImpl< T, NDIM >::mul(), madness::mul(), madness::mul(), madness::mxm(), madness::mxmT(), madness::mxmT_reference(), myp(), madness::nonlinear_vector_solver(), madness::Convolution1D< Q >::nonstandard(), madness::Tensor< T >::normf(), madness::Vector< T, N >::normf(), nuclear_anchor_test(), madness::GenTensor< T >::operator GenTensor< Q >(), madness::Tensor< T >::operator Tensor< Q >(), madness::default_allocator< T >::operator()(), madness::CompositeFunctorInterface< T, NDIM, MDIM >::operator()(), madness::Function< T, NDIM >::operator()(), GygiPot::Reciprocal< T, DIM >::operator()(), GygiPot::Pow< T, DIM >::operator()(), GygiPot::Pow_beta_one< T, DIM >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::operator()(), myunaryop_square< T, NDIM >::operator()(), SurfaceMoleculeInteraction::Reciprocal< T, NDIM >::operator()(), unaryexp< T, NDIM >::operator()(), madness::Function< T, NDIM >::SimpleUnaryOpWrapper::operator()(), madness::BSHApply< T, NDIM >::operator()(), madness::TwoElectronInterface< T, NDIM >::operator()(), madness::CubicInterpolationTable< T >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()(), madness::FunctionImpl< T, NDIM >::do_dot_local< R >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::operator()(), madness::operator*(), madness::GenTensor< T >::operator*(), madness::Tensor< T >::operator*(), madness::operator*(), madness::operator*(), madness::operator*(), madness::Tensor< T >::operator*=(), madness::Tensor< T >::operator+(), madness::Tensor< T >::operator+(), madness::Function< T, NDIM >::operator+=(), madness::Tensor< T >::operator+=(), madness::Tensor< T >::operator+=(), madness::Tensor< T >::operator-(), madness::Tensor< T >::operator-(), madness::Function< T, NDIM >::operator-=(), madness::Tensor< T >::operator-=(), madness::Tensor< T >::operator-=(), madness::Tensor< T >::operator/(), madness::archive::operator<<(), madness::operator<<(), madness::SliceTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::Stack< T, N >::operator=(), madness::SliceLowRankTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::Tensor< T >::operator=(), madness::operator>>(), madness::operator>>(), madness::orgqr(), madness::outer(), madness::outer(), madness::outer(), madness::outer_result(), madness::plotdx(), madness::DQueue< T >::pop_front(), madness::DQueue< T >::pop_front(), madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::postamble_load(), madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::preamble_load(), madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::preamble_store(), FermiNucDistFunctor::print_details(), madness::EigSolver< T, NDIM >::print_matrix_elements(), madness::FunctionImpl< T, NDIM >::print_size(), madness::Tensor< T >::product(), product(), madness::Function< T, NDIM >::project_out(), madness::FunctionImpl< T, NDIM >::project_refine_op(), madness::World::ptr_from_id(), madness::Stack< T, N >::push(), RandomGaussian(), slymer::read_endian(), madness::QCCalculationParametersBase::read_quotes(), madness::real(), madness::SRConf< T >::real_size(), madness::TensorTrain< T >::real_size(), madness::WorldMpiInterface::Recv(), madness::WorldMpiInterface::Recv(), madness::WorldMpiInterface::Recv(), madness::WorldGopInterface::reduce(), madness::World::register_ptr(), madness::Stack< T, N >::reset(), madness::GenTensor< T >::scale(), madness::DQueue< T >::scan(), madness::Tensor< T >::screen(), madness::WorldMpiInterface::Send(), madness::WorldMpiInterface::Send(), madness::archive::ArchiveSerializeImpl< Archive, std::optional< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::serialize(), madness::FutureImpl< T >::set(), madness::FutureImpl< T >::set(), madness::FutureImpl< T >::set_handler(), madness::BasisFunctions::SolidHarmonicGaussian::sgn(), madness::Nemo::solve(), squareit(), madness::archive::BinaryFstreamOutputArchive::store(), madness::archive::BufferOutputArchive::store(), madness::archive::VectorOutputArchive::store(), madness::Cloud::store_other(), madness::sub(), madness::sub(), madness::Tensor< T >::sum(), sum(), madness::Tensor< T >::sumsq(), T(), madness::Tensor< T >::TENSOR_RESULT_TYPE(), madness::GenTensor< T >::TENSOR_RESULT_TYPE(), madness::Tensor< T >::TENSOR_RESULT_TYPE(), Test5(), Test6(), Test6a(), Test7(), test_basic(), test_converged_function(), test_coulomb(), test_cross(), test_dot(), madness::test_exchange(), test_exchange(), test_fock(), test_inner(), test_kinetic(), madness::Znemo::test_landau_wave_function(), test_math(), test_op(), test_plot(), test_stuff(), madness::test_svd(), madness::test_sygv(), madness::Znemo::test_U_potentials(), madness::archive::to_abs_fn_ptr(), madness::cblas::to_cptr(), madness::lapacke::to_cptr(), madness::cblas::to_cptr(), madness::lapacke::to_cptr(), madness::archive::to_rel_fn_ptr(), madness::archive::to_rel_memfn_ptr(), madness::cblas::to_zptr(), madness::lapacke::to_zptr(), madness::cblas::to_zptr(), madness::lapacke::to_zptr(), madness::Function< T, NDIM >::trace(), madness::SRConf< T >::trace(), madness::TensorTrain< T >::trace(), madness::FunctionImpl< T, NDIM >::trace_local(), madness::transform(), madness::transform(), madness::transform(), madness::transform(), madness::transform(), transform3d(), transform3d_3c(), madness::transform_dir(), madness::transform_reconstructed(), madness::QCCalculationParametersBase::try_setting_user_defined_value(), madness::Tensor< T >::unaryop(), madness::detail::StackBase< T, true >::uninitialized_copy(), madness::detail::StackBase< T, isPod >::uninitialized_move(), madness::detail::StackBase< T, true >::uninitialized_move(), madness::SystolicMatrixAlgorithm< T >::unshuffle(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), GaussianGuess< NDIM >::val(), Vdynamic(), madness::vec(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load(), madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_load(), madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T >::wrap_load(), madness::archive::wrap_opaque(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store(), and madness::archive::ArchiveImpl< ParallelOutputArchive< localarchiveT >, T >::wrap_store().