MADNESS: global_functions.cc File Reference
global_functions.cc File Reference
#include "global_functions.h"
#include <ResponseBase.hpp>
#include <memory>
#include "madness/chem/SCFOperators.h"
#include "response_parameters.h"
Functions
auto ground_exchange (const vecfuncT &phi0, const X_space &chi, const bool &compute_y, const ResponseParameters &r_params) -> X_space
auto ground_exchange (const vecfuncT &phi0, const X_space &x, const bool compute_y) -> X_space
auto initialize_calc_params (World &world, const std::string &input_file) -> CalcParams
auto make_k (const vecfuncT &ket, const vecfuncT &bra, const ResponseParameters &r_params)
auto molresponseExchange (World &world, const vecfuncT &ket_i, const vecfuncT &bra_i, const vecfuncT &fp, const int &n, const int &num_states, const int &num_orbitals) -> X_space
auto newK (const vecfuncT &ket, const vecfuncT &bra, const vecfuncT &vf) -> vecfuncT
auto response_exchange (const vecfuncT &phi0, const X_space &chi, const bool &compute_y, const ResponseParameters &r_params) -> X_space
auto response_exchange (const vecfuncT &phi0, const X_space &x, const bool compute_y) -> X_space
static auto set_poisson (World &world, const double lo, const double econv=FunctionDefaults< 3 >::get_thresh())
auto T (World &world, response_space &f) -> response_space
Function Documentation
ground_exchange() [1/2]
auto ground_exchange (const vecfuncT & phi0, const X_space & chi, const bool & compute_y, const ResponseParameters & r_params) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References madness::WorldGopInterface::fence(), madness::World::gop, k0, make_k(), molresponse::start_timer(), and madness::X_space::zero_functions().
ground_exchange() [2/2]
auto ground_exchange (const vecfuncT & phi0, const X_space & x, const bool compute_y) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References b, madness::copy(), molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, K(), molresponseExchange(), p(), madness::print(), madness::World::rank(), molresponse::start_timer(), madness::to_response_matrix(), and madness::X_space::zero_functions().
initialize_calc_params()
auto initialize_calc_params (World & world, const std::string & input_file) -> CalcParams
References madness::WorldGopInterface::fence(), madness::World::gop, molecule, and madness::commandlineparser::set_keyval().
Referenced by main().
make_k()
auto make_k (const vecfuncT & ket, const vecfuncT & bra, const ResponseParameters & r_params)
References madness::ResponseParameters::hfexalg(), k, lo, madness::Exchange< T, NDIM >::set_algorithm(), and madness::Exchange< T, NDIM >::set_bra_and_ket().
Referenced by ground_exchange(), and response_exchange().
molresponseExchange()
auto molresponseExchange (World & world, const vecfuncT & ket_i, const vecfuncT & bra_i, const vecfuncT & fp, const int & n, const int & num_states, const int & num_orbitals) -> X_space
References madness::apply(), b, madness::compress(), madness::FunctionFactory< T, NDIM >::compressed(), madness::copy(), madness::create_response_matrix(), molresponse::end_timer(), madness::FunctionDefaults< NDIM >::get_thresh(), lo, madness::mul(), madness::print(), madness::reconstruct(), set_poisson(), molresponse::start_timer(), madness::to_X_space(), madness::truncate(), madness::X_space::x, xi, and madness::X_space::zero_functions().
Referenced by ground_exchange().
newK()
auto newK (const vecfuncT & ket, const vecfuncT & bra, const vecfuncT & vf) -> vecfuncT
References lo, and op().
response_exchange() [1/2]
auto response_exchange (const vecfuncT & phi0, const X_space & chi, const bool & compute_y, const ResponseParameters & r_params) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References b, madness::WorldGopInterface::fence(), madness::gaxpy_oop(), madness::World::gop, K(), make_k(), molresponse::start_timer(), and madness::X_space::zero_functions().
response_exchange() [2/2]
auto response_exchange (const vecfuncT & phi0, const X_space & x, const bool compute_y) -> X_space
Computes ground density exchange on response vectors This algorithm places all functions in a single vector, computes exchange and returns the result into a response matrix
Parameters
v1
v2
f
Returns
References b, K(), p(), and molresponse::start_timer().
set_poisson()
static auto set_poisson (World & world, const double lo, const double econv = FunctionDefaults<3>::get_thresh()) static
References madness::CoulombOperatorPtr(), and lo.
Referenced by madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeSimple::compute_offdiagonal_batch_in_symmetric_matrix(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_large_memory(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_small_memory(), and molresponseExchange().
T()
auto T (World & world, response_space & f) -> response_space
References madness::apply(), madness::f, and T().
Referenced by madness::BinSorter< T, inserterT >::BinSorter(), madness::Stack< T, N >::Stack(), madness::TensorIterator< T, Q, R >::TensorIterator(), madness::abs(), madness::Tensor< T >::absmax(), madness::Tensor< T >::absmin(), madness::add(), madness::add(), madness::add(), madness::add(), madness::MemoryMeasurer::add_memory_to_map(), madness::FutureImpl< T >::add_to_assignments(), madness::aligned_zero(), madness::Stack< T, N >::allocate(), madness::Tensor< T >::allocate(), madness::Cloud::allocator(), madness::SeparatedConvolution< Q, NDIM >::apply(), madness::apply(), madness::apply(), madness::apply(), madness::apply(), madness::SeparatedConvolution< Q, NDIM >::apply2(), madness::SeparatedConvolution< Q, NDIM >::apply2_lowdim(), madness::arg(), madness::PNOParameters::assign_from_string(), madness::WorldMpiInterface::Bcast(), madness::WorldMpiInterface::Bcast(), bind_function_type(), madness::WorldGopInterface::broadcast(), madness::Zcis::canonicalize(), slymer::cast_basis(), check(), madness::QCCalculationParametersBase::check_type(), madness::QCCalculationParametersBase::check_type_silent(), madness::Nemo::compute_fock_matrix(), madness::Zcis::compute_fock_pt(), madness::Recordlist< keyT >::compute_record(), madness::Tensor< T >::conj(), madness::conj(), madness::convert(), madness::copy(), madness::cross(), csqrt_op(), madness::SystolicMatrixAlgorithm< T >::cycle(), madness::detail::arg_holder::decay(), madness::detail::arg_holder::decay(), madness::detail::arg_holder::decay(), madness::TensorTrain< T >::decompose(), madness::archive::default_serialize(), madness::FunctionImpl< T, NDIM >::do_dot_localX(), madness::FunctionImpl< T, NDIM >::do_inner_localX(), madness::Cloud::do_load(), madness::FunctionImpl< T, NDIM >::do_mul(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::FunctionImpl< T, NDIM >::dot_local(), madness::Tensor< T >::emul(), energy(), madness::CubicInterpolationTable< T >::err(), madness::FunctionImpl< T, NDIM >::eval_cube(), PyFunctor< T, NDIM >::eval_scalar_loop(), madness::fast_transform(), madness::fast_transpose(), madness::fcube(), madness::Tensor< T >::fillindex(), madness::Tensor< T >::fillrandom(), find_fuzzy(), madness::Cloud::forward_load(), madness::QCCalculationParametersBase::fromstring(), madness::Tensor< T >::gaxpy(), madness::FunctionImpl< T, NDIM >::gaxpy_ext_recursive(), madness::FunctionImpl< T, NDIM >::gaxpy_inplace(), madness::gaxpy_oop(), madness::gaxpy_oop(), gen_ce(), madness::general_transform(), madness::general_transform(), madness::FutureImpl< T >::get(), madness::FutureImpl< T >::get(), madness::detail::RemoteCounter::get_shared(), madness::RemoteReference< T >::get_shared(), madness::get_size(), madness::get_size(), madness::get_size_local(), madness::Random::getv(), madness::GMRES(), madness::DQueue< T >::grow(), madness::hash_range(), madness::hash_value(), madness::Znemo::hcore_guess(), madness::DistributedMatrix< T >::idij(), madness::imag(), madness::inner(), madness::inner(), madness::inner(), madness::inner(), madness::Function< T, NDIM >::inner_adaptive(), madness::FunctionImpl< T, NDIM >::inner_adaptive_local(), madness::FunctionImpl< T, NDIM >::inner_adaptive_recursive(), madness::Function< T, NDIM >::inner_ext(), madness::FunctionImpl< T, NDIM >::inner_ext_local(), madness::Function< T, NDIM >::inner_ext_local(), madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), madness::FunctionImpl< T, NDIM >::inner_local(), madness::inner_result(), madness::innerXX(), invert(), madness::WorldMpiInterface::Irecv(), madness::WorldMpiInterface::Irecv(), madness::WorldMpiInterface::Isend(), madness::Znemo::iterate(), madness::OEP::iterate(), madness::DFT< T, NDIM >::iterateOutput(), KAIN(), madness::KAIN(), ldaeop(), ldaop(), madness::archive::ArchiveLoadImpl< Archive, Future< T >, std::enable_if_t<!std::is_void_v< T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::array< T, N >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::atomic< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::complex< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::list< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), madness::archive::BinaryFstreamInputArchive::load(), madness::archive::BufferInputArchive::load(), madness::archive::VectorInputArchive::load(), madness::Cloud::load_from_cache(), madness::Cloud::load_tuple(), madness::lq_result(), main(), madness::Solver< T, NDIM >::make_bsh_operators(), make_fit(), make_grad_operator(), make_operator(), madness::TDHF::make_perturbed_fock_matrix(), madness::CCPairFunction< T, NDIM >::make_xy_u(), madness::matrix_dot(), madness::matrix_dot_old(), madness::matrix_inner(), madness::matrix_inner_old(), madness::Tensor< T >::max(), madness::Tensor< T >::min(), madness::Convolution1D< Q >::mod_nonstandard(), madness::Stack< T, N >::move(), madness::mTxm(), madness::mTxmq(), madness::mTxmT(), madness::mul(), madness::FunctionImpl< T, NDIM >::mul(), madness::mul(), madness::mul(), madness::mxm(), madness::mxmT(), madness::mxmT_reference(), myp(), madness::nonlinear_vector_solver(), madness::Convolution1D< Q >::nonstandard(), madness::Tensor< T >::normf(), madness::Vector< T, N >::normf(), nuclear_anchor_test(), madness::GenTensor< T >::operator GenTensor< Q >(), madness::Tensor< T >::operator Tensor< Q >(), madness::default_allocator< T >::operator()(), madness::CompositeFunctorInterface< T, NDIM, MDIM >::operator()(), madness::Function< T, NDIM >::operator()(), GygiPot::Reciprocal< T, DIM >::operator()(), GygiPot::Pow< T, DIM >::operator()(), GygiPot::Pow_beta_one< T, DIM >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::operator()(), myunaryop_square< T, NDIM >::operator()(), SurfaceMoleculeInteraction::Reciprocal< T, NDIM >::operator()(), unaryexp< T, NDIM >::operator()(), madness::Function< T, NDIM >::SimpleUnaryOpWrapper::operator()(), madness::FermiNuclearDensityFunctor::operator()(), PyFunctor< T, NDIM >::operator()(), madness::BSHApply< T, NDIM >::operator()(), madness::TwoElectronInterface< T, NDIM >::operator()(), madness::CubicInterpolationTable< T >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()(), madness::FunctionImpl< T, NDIM >::do_dot_local< R >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::operator()(), madness::operator*(), madness::GenTensor< T >::operator*(), madness::Tensor< T >::operator*(), madness::operator*(), madness::operator*(), madness::operator*(), madness::Tensor< T >::operator*=(), madness::Tensor< T >::operator+(), madness::Tensor< T >::operator+(), madness::Function< T, NDIM >::operator+=(), madness::Tensor< T >::operator+=(), madness::Tensor< T >::operator+=(), madness::Tensor< T >::operator-(), madness::Tensor< T >::operator-(), madness::Function< T, NDIM >::operator-=(), madness::Tensor< T >::operator-=(), madness::Tensor< T >::operator-=(), madness::Tensor< T >::operator/(), madness::archive::operator<<(), madness::operator<<(), madness::SliceTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::Stack< T, N >::operator=(), madness::SliceLowRankTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::SliceTensor< T >::operator=(), madness::Tensor< T >::operator=(), madness::operator>>(), madness::operator>>(), madness::orgqr(), madness::outer(), madness::outer(), madness::outer(), madness::outer_result(), madness::DQueue< T >::pop_front(), madness::DQueue< T >::pop_front(), madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::postamble_load(), madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::preamble_load(), madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::preamble_store(), madness::EigSolver< T, NDIM >::print_matrix_elements(), madness::FunctionImpl< T, NDIM >::print_size(), madness::Tensor< T >::product(), product(), madness::Function< T, NDIM >::project_out(), madness::FunctionImpl< T, NDIM >::project_refine_op(), madness::World::ptr_from_id(), madness::Stack< T, N >::push(), RandomGaussian(), slymer::read_endian(), madness::QCCalculationParametersBase::read_quotes(), madness::real(), madness::SRConf< T >::real_size(), madness::TensorTrain< T >::real_size(), madness::WorldMpiInterface::Recv(), madness::WorldMpiInterface::Recv(), madness::WorldMpiInterface::Recv(), madness::WorldGopInterface::reduce(), madness::World::register_ptr(), madness::Stack< T, N >::reset(), madness::GenTensor< T >::scale(), madness::DQueue< T >::scan(), madness::Tensor< T >::screen(), madness::WorldMpiInterface::Send(), madness::WorldMpiInterface::Send(), madness::archive::ArchiveSerializeImpl< Archive, std::optional< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::serialize(), madness::FutureImpl< T >::set(), madness::FutureImpl< T >::set(), madness::FutureImpl< T >::set_handler(), madness::BasisFunctions::SolidHarmonicGaussian::sgn(), madness::Nemo::solve(), squareit(), madness::archive::BinaryFstreamOutputArchive::store(), madness::archive::BufferOutputArchive::store(), madness::archive::VectorOutputArchive::store(), madness::Cloud::store_other(), madness::sub(), madness::sub(), madness::Tensor< T >::sum(), sum(), madness::Tensor< T >::sumsq(), T(), madness::Tensor< T >::TENSOR_RESULT_TYPE(), madness::GenTensor< T >::TENSOR_RESULT_TYPE(), madness::Tensor< T >::TENSOR_RESULT_TYPE(), Test5(), Test6(), Test6a(), Test7(), test_basic(), test_converged_function(), test_coulomb(), test_cross(), test_dot(), madness::test_exchange(), test_exchange(), test_fock(), test_inner(), test_kinetic(), madness::Znemo::test_landau_wave_function(), test_math(), test_op(), test_plot(), test_stuff(), madness::test_svd(), madness::test_sygv(), madness::Znemo::test_U_potentials(), madness::archive::to_abs_fn_ptr(), madness::cblas::to_cptr(), madness::lapacke::to_cptr(), madness::cblas::to_cptr(), madness::lapacke::to_cptr(), madness::archive::to_rel_fn_ptr(), madness::archive::to_rel_memfn_ptr(), madness::cblas::to_zptr(), madness::lapacke::to_zptr(), madness::cblas::to_zptr(), madness::lapacke::to_zptr(), madness::Function< T, NDIM >::trace(), madness::SRConf< T >::trace(), madness::TensorTrain< T >::trace(), madness::FunctionImpl< T, NDIM >::trace_local(), madness::transform(), madness::transform(), madness::transform(), madness::transform(), madness::transform(), transform3d(), transform3d_3c(), madness::transform_dir(), madness::transform_reconstructed(), madness::QCCalculationParametersBase::try_setting_user_defined_value(), madness::Tensor< T >::unaryop(), madness::detail::StackBase< T, true >::uninitialized_copy(), madness::detail::StackBase< T, isPod >::uninitialized_move(), madness::detail::StackBase< T, true >::uninitialized_move(), madness::SystolicMatrixAlgorithm< T >::unshuffle(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), GaussianGuess< NDIM >::val(), madness::type_name< T >::value(), Vdynamic(), madness::vec(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load(), madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_load(), madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T >::wrap_load(), madness::archive::wrap_opaque(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store(), and madness::archive::ArchiveImpl< ParallelOutputArchive< localarchiveT >, T >::wrap_store().