MADNESS: Worlddc
Worlddc
Namespaces
namespace madness
Namespace for all elements and tools of MADNESS.
Classes
struct madness::archive::ArchiveStoreImpl< ParallelOutputArchive< localarchiveT >, WorldContainer< keyT, valueT > >
Write container to parallel archive with optional fence.
class madness::WorldContainer< keyT, valueT, hashfunT >
Makes a distributed container with specified attributes.
class madness::WorldContainerImpl< keyT, valueT, hashfunT >
Internal implementation of distributed container to facilitate shallow copy.
class madness::WorldContainerIterator< internal_iteratorT >
Iterator for distributed container wraps the local iterator.
class madness::WorldDCDefaultPmap< keyT, hashfunT >
Default process map is "random" using madness::hash(key)
class madness::WorldDCLocalPmap< keyT, hashfunT >
Local process map will always return the current process as owner.
class madness::WorldDCNodeReplicatedPmap< keyT, hashfunT >
class madness::WorldDCPmapInterface< keyT >
Interface to be provided by any process map.
Functions
static void madness::archive::ArchiveLoadImpl< ParallelInputArchive< localarchiveT >, WorldContainer< keyT, valueT > >::load (const ParallelInputArchive< localarchiveT > &ar, WorldContainer< keyT, valueT > &t)
Read container from parallel archive.
template<typename keyT , typename valueT , typename hashfunT >
void madness::swap (WorldContainer< keyT, valueT, hashfunT > &dc0, WorldContainer< keyT, valueT, hashfunT > &dc1)
Swaps the content of two WorldContainer objects. It should be called on all nodes.
Detailed Description
Function Documentation
load()
template<class keyT , class valueT , class localarchiveT > static void madness::archive::ArchiveLoadImpl< ParallelInputArchive< localarchiveT >, WorldContainer< keyT, valueT > >::load (const ParallelInputArchive< localarchiveT > & ar, WorldContainer< keyT, valueT > & t) inline static
Read container from parallel archive.
See store method above for format of file content. !!! We presently ASSUME that the number of writers and readers are the same. This is frustrating but not a show stopper since you can always run a separate job to copy to a different number.
The IO node simply reads all data and inserts entries.
References madness::archive::BaseParallelArchive< Archive >::dofence(), madness::WorldGopInterface::fence(), madness::archive::BaseParallelArchive< Archive >::get_world(), madness::World::gop, madness::archive::BaseParallelArchive< Archive >::is_io_node(), madness::archive::BaseParallelArchive< Archive >::local_archive(), and MADNESS_CHECK.
swap()
template<typename keyT , typename valueT , typename hashfunT > void madness::swap (WorldContainer< keyT, valueT, hashfunT > & dc0, WorldContainer< keyT, valueT, hashfunT > & dc1)
Swaps the content of two WorldContainer objects. It should be called on all nodes.
References madness::WorldContainer< keyT, valueT, hashfunT >::p.