MADNESS: Periodic Solver
Periodic Solver
MADNESS applications
The Periodic Solver group is a group that contains the software objects that are needed to solve a periodic Kohn-Sham hamiltonian.
Classes
class madness::Solver< T, NDIM >
The main class of the periodic DFT solver.
class Subspace
The Subspace class is a container class holding previous orbitals and residuals.
class madness::Subspace< T, NDIM >
The SubspaceK class is a container class holding previous orbitals and residuals.
class madness::SubspaceK< T, NDIM >
The SubspaceK class is a container class holding previous orbitals and residuals.
Functions
void madness::Solver< T, NDIM >::apply_potential (vecfuncT &pfuncsa, vecfuncT &pfuncsb, const vecfuncT &phisa, const vecfuncT &phisb, const rfunctionT &rhoa, const rfunctionT &rhob, const rfunctionT &rho)
Applies the LDA effective potential to each orbital. Currently only lda and spin-polarized is not implemented.
rfunctionT madness::Solver< T, NDIM >::compute_rho_slow (const vecfuncT &phis, std::vector< KPoint > kpoints, std::vector< double > occs)
Compute the electronic density for either a molecular or periodic system.
template<typename T >
T madness::stheta_fd (const T &x)
Detailed Description
The Periodic Solver group is a group that contains the software objects that are needed to solve a periodic Kohn-Sham hamiltonian.
Function Documentation
apply_potential()
template<typename T , int NDIM> void madness::Solver< T, NDIM >::apply_potential (vecfuncT & pfuncsa, vecfuncT & pfuncsb, const vecfuncT & phisa, const vecfuncT & phisb, const rfunctionT & rhoa, const rfunctionT & rhob, const rfunctionT & rho) inline
Applies the LDA effective potential to each orbital. Currently only lda and spin-polarized is not implemented.
References madness::Solver< T, NDIM >::_cop, madness::Solver< T, NDIM >::_params, madness::Solver< T, NDIM >::_phisa, madness::Solver< T, NDIM >::_phisb, madness::Solver< T, NDIM >::_vnuc, madness::Solver< T, NDIM >::_vnucrhon, madness::Solver< T, NDIM >::_world, madness::apply(), madness::Solver< T, NDIM >::apply_hf_exchange3(), madness::Solver< T, NDIM >::apply_hf_exchange4(), madness::Solver< T, NDIM >::calculate_kinetic_energy(), madness::copy(), END_TIMER, madness::ElectronicStructureParams::functional, madness::inner(), madness::ElectronicStructureParams::ispotential, MADNESS_EXCEPTION, madness::mul_sparse(), madness::ElectronicStructureParams::ngridk0, madness::ElectronicStructureParams::ngridk1, madness::ElectronicStructureParams::ngridk2, madness::norm2(), madness::World::rank(), madness::ElectronicStructureParams::spinpol, START_TIMER, madness::ElectronicStructureParams::thresh, and xc.
Referenced by madness::Solver< T, NDIM >::solve().
compute_rho_slow()
template<typename T , int NDIM> rfunctionT madness::Solver< T, NDIM >::compute_rho_slow (const vecfuncT & phis, std::vector< KPoint > kpoints, std::vector< double > occs) inline
Compute the electronic density for either a molecular or periodic system.
References madness::Solver< T, NDIM >::_outputF, madness::Solver< T, NDIM >::_world, madness::abssq(), madness::WorldGopInterface::fence(), madness::World::gop, madness::World::rank(), and madness::KPoint::weight().
stheta_fd()
template<typename T > T madness::stheta_fd (const T & x)
\Fermi-Dirac distribution function for fixing the occupation numbers
Referenced by madness::Solver< T, NDIM >::fix_occupations().