MADNESS: h2dft.cc File Reference
h2dft.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/nonlinsol.h>
#include <madness/mra/lbdeux.h>
#include <madness/mra/qmprop.h>
#include <madness/misc/misc.h>
#include <madness/misc/ran.h>
#include <madness/tensor/systolic.h>
#include <madness/tensor/solvers.h>
#include <madness/tensor/elem.h>
#include <madness/chem/xcfunctional.h>
#include <madness/chem/SCFOperators.h>
Typedefs
typedef Function< std::complex< double >, 3 > complex_functionT
typedef Convolution1D< double_complex > complex_operatorT
typedef Vector< double, 3 > coordT
typedef std::vector< complex_functionT > cvecfuncT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::pair< vecfuncT, vecfuncT > pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef std::vector< functionT > vecfuncT
Functions
static double guess (const coord_3d &r)
double iterate_ground (World &world, NonlinearSolver &solver, real_function_3d &V, real_function_3d &psi, double &eps)
int main (int argc, char **argv)
static double V (const coord_3d &r)
Variables
std::vector< std::shared_ptr< real_derivative_3d > > gradop
static const long k = 8
static const double L = 64.0*R
static const double R = 1.4
static const double thresh = 1e-5
Typedef Documentation
complex_functionT
typedef Function<std::complex<double>,3> complex_functionT
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
coordT
typedef Vector<double,3> coordT
cvecfuncT
typedef std::vector<complex_functionT> cvecfuncT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pairvecfuncT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
subspaceT
typedef std::vector<pairvecfuncT> subspaceT
tensorT
typedef Tensor<double> tensorT
vecfuncT
typedef std::vector<functionT> vecfuncT
Function Documentation
guess()
static double guess (const coord_3d & r) static
References e(), and R.
Referenced by main().
iterate_ground()
double iterate_ground (World & world, NonlinearSolver & solver, real_function_3d & V, real_function_3d & psi, double & eps)
References madness::BSHOperator3D(), e(), madness::inner(), norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), and V().
Referenced by main().
main()
int main (int argc, char ** argv)
References axis, SafeMPI::COMM_WORLD, madness::CoulombOperator(), madness::CoulombOperatorPtr(), e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, gradop, guess(), madness::initialize(), madness::inner(), iterate_ground(), k, L, op(), potential(), madness::print(), psi(), R, madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), V(), and xc.
V()
static double V (const coord_3d & r) static
References e(), and R.
Referenced by iterate_ground(), and main().
Variable Documentation
gradop
std::vector< std::shared_ptr<real_derivative_3d> > gradop
Referenced by dostuff(), kinetic_energy_matrix(), madness::Kinetic< T, NDIM >::kinetic_energy_matrix(), madness::Kinetic< T, NDIM >::kinetic_energy_matrix(), madness::Kinetic< double, 3 >::kinetic_energy_matrix(), MiniDFT::kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), main(), madness::smooth< T, NDIM >::make_sigma(), madness::Nuclear< T, NDIM >::operator()(), madness::DNuclear< T, NDIM >::operator()(), and MyDerivativeOperator< T, NDIM >::operator()().
k
const long k = 8 static
Referenced by main().
L
const double L = 64.0*R static
Referenced by main().
R
const double R = 1.4 static
Referenced by guess(), main(), and V().
thresh
const double thresh = 1e-5 static
Referenced by main().