MADNESS: hatom.cc File Reference
hatom.cc File Reference
#include <fstream>
#include <iostream>
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
Functions
std::tuple< double, double, double > compute_energy (World &world, real_function_3d &Vnuc, real_function_3d &psi)
static double guess (const coord_3d &r)
void iterate (World &world, real_function_3d &V, real_function_3d &mask, real_function_3d &psi, double &eps)
int main (int argc, char **argv)
double mask1 (double x)
static double mask3 (const coord_3d &ruser)
void run (World &world)
static double V (const coord_3d &r)
Variables
static const double F =0.0
static const long k = 8
static const double L = 32.0
static const double thresh = 1e-7
Function Documentation
compute_energy()
std::tuple<double,double,double> compute_energy (World & world, real_function_3d & Vnuc, real_function_3d & psi)
References axis, madness::inner(), psi(), and madness::square().
Referenced by run().
guess()
static double guess (const coord_3d & r) static
References madness::constants::pi.
Referenced by run().
iterate()
void iterate (World & world, real_function_3d & V, real_function_3d & mask, real_function_3d & psi, double & eps)
References madness::apply(), madness::BSHOperator3D(), e(), madness::inner(), mask(), madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), and V().
Referenced by run().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), run(), and madness::startup().
mask1()
double mask1 (double x) inline
mask3()
static double mask3 (const coord_3d & ruser) static
References lo, madness::mask1(), and madness::user_to_sim().
run()
void run (World & world)
References compute_energy(), guess(), iterate(), k, L, mask(), madness::mask3(), madness::print(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), thresh, and V().
Referenced by main().
V()
static double V (const coord_3d & r) static
Referenced by iterate(), and run().
Variable Documentation
F
const double F =0.0 static
Referenced by allocator(), madness::TDHF::canonicalize(), madness::Localizer::check_core_valence_separation(), iterate(), iterate_xy(), main(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_perturbed_fock_matrix(), allocator::operator()(), F::operator*(), F::operator-(), madness::TDHF::prepare_calculation(), InputParameters::read(), madness::OEP::recompute_HF(), residual(), and test().
k
const long k = 8 static
Referenced by run().
L
const double L = 32.0 static
Referenced by run().
thresh
const double thresh = 1e-7 static
Referenced by run().