MADNESS: hatom_sf_dirac.cc File Reference
hatom_sf_dirac.cc File Reference
#include <fstream>
#include <iostream>
#include <algorithm>
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/lbdeux.h>
#include <madness/mra/nonlinsol.h>
#include <madness/chem/atomutil.h>
Classes
struct allocator
struct F
simple class for testing the solver
struct LBCost
class Vderiv
Functions
std::tuple< double, double, double, double > compute_energy (World &world, real_function_3d &V, real_function_3d &psi, real_function_3d &phi)
double exact_energy (double Z)
double inner (const F &a, const F &b)
template<typename solverT >
std::tuple< real_function_3d, real_function_3d, double > iterate (World &world, const real_function_3d &V, const real_function_3d gradV[3], const real_function_3d &mask, const real_function_3d &psi, const real_function_3d &phi, const double energy, const int iter, solverT &solver)
int main (int argc, char **argv)
double mask1 (double x)
static double mask3 (const coord_3d &ruser)
static double phi_guess (const coord_3d &r)
static double psi_guess (const coord_3d &r)
real_function_3d pVp (World &world, const real_function_3d &V, const real_function_3d &phi)
real_function_3d pVp (World &world, const real_function_3d &V, const real_function_3d gradV[3], const real_function_3d &phi)
void run (World &world)
static double V (const coord_3d &r)
Variables
static const double c = 137.035999679
static const double eprec = 0.0
static const long k = 8
static const double L = 40.0/Z
static const double rcut = 1e-4
static const double thresh = 1e-6
static const double v = std::sqrt(1.0 - Z*Z/(c*c)) - 1.0
static const int Vtruncmode = (Z<=10 && thresh>1e-10) ? 1 : 0
static const double Z = 80.0
Function Documentation
compute_energy()
std::tuple< double, double, double, double > compute_energy (World & world, real_function_3d & V, real_function_3d & psi, real_function_3d & phi)
References axis, madness::inner(), psi(), and V().
Referenced by run().
exact_energy()
double exact_energy (double Z)
References a2, c, and Z.
Referenced by phi_guess(), psi_guess(), and run().
inner()
double inner (const F & a, const F & b)
References a, b, and madness::inner().
iterate()
template<typename solverT > std::tuple< real_function_3d, real_function_3d, double > iterate (World & world, const real_function_3d & V, const real_function_3d gradV[3], const real_function_3d & mask, const real_function_3d & psi, const real_function_3d & phi, const double energy, const int iter, solverT & solver)
References madness::apply(), madness::BSHOperator3D(), c, madness::CoulombOperator(), e(), energy, madness::f, madness::inner(), mask, norm(), madness::norm2(), op(), madness::constants::pi, madness::print(), psi(), pVp(), madness::World::rank(), rcut, thresh, madness::Function< T, NDIM >::truncate(), and V().
Referenced by run().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), run(), and madness::startup().
mask1()
double mask1 (double x) inline
Referenced by mask3().
mask3()
static double mask3 (const coord_3d & ruser) static
References lo, mask1(), and madness::user_to_sim().
Referenced by run().
phi_guess()
static double phi_guess (const coord_3d & r) static
References c, exact_energy(), madness::constants::pi, R, and Z.
Referenced by run().
psi_guess()
static double psi_guess (const coord_3d & r) static
References c, exact_energy(), madness::constants::pi, R, rcut, v, and Z.
Referenced by run().
pVp() [1/2]
real_function_3d pVp (World & world, const real_function_3d & V, const real_function_3d & phi)
References axis, c, and V().
pVp() [2/2]
real_function_3d pVp (World & world, const real_function_3d & V, const real_function_3d gradV[3], const real_function_3d & phi)
References axis, c, and V().
Referenced by iterate().
run()
void run (World & world)
References madness::LoadBalanceDeux< NDIM >::add_tree(), axis, c, compute_energy(), energy, eprec, exact_energy(), iterate(), k, L, lo, madness::LoadBalanceDeux< NDIM >::load_balance(), mask, mask3(), norm(), madness::Function< T, NDIM >::norm2(), p(), phi_guess(), madness::plot_line(), madness::print(), psi(), psi_guess(), madness::World::rank(), rcut, madness::FunctionDefaults< NDIM >::redistribute(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::XNonlinearSolver< T, C, Alloc >::set_maxsub(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::Function< T, NDIM >::size(), thresh, v, V(), Vtruncmode, and Z.
Referenced by main().
V()
static double V (const coord_3d & r) static
References rcut, madness::smoothed_potential(), and Z.
Referenced by compute_energy(), iterate(), pVp(), pVp(), and run().
Variable Documentation
c
const double c = 137.035999679 static
Referenced by exact_energy(), iterate(), phi_guess(), psi_guess(), pVp(), pVp(), and run().
eprec
const double eprec = 0.0 static
Referenced by madness::CorePotentialManager::CorePotentialManager(), madness::read_atom(), madness::CorePotentialManager::read_file(), madness::read_potential(), run(), smoothing_parameter(), smoothing_parameter(), smoothing_parameter(), smoothing_parameter(), smoothing_parameter(), madness::smoothing_parameter(), and madness::PseudoNuclearCorrelationFactor::Spp_div_S().
k
const long k = 8 static
Referenced by run().
L
const double L = 40.0/Z static
Referenced by run().
rcut
const double rcut = 1e-4 static
Referenced by iterate(), Vderiv::operator()(), madness::WignerSeitzPotentialFunctor::operator()(), madness::NuclearCorrelationFactor::U2X_functor::operator()(), psi_guess(), run(), madness::PseudoNuclearCorrelationFactor::Spp_div_S(), madness::PseudoNuclearCorrelationFactor::U2X_spherical(), and V().
thresh
const double thresh = 1e-6 static
Referenced by iterate(), and run().
v
const double v = std::sqrt(1.0 - Z*Z/(c*c)) - 1.0 static
Referenced by madness::array_of_bools< N >::array_of_bools(), madness::array_of_bools< N >::array_of_bools(), madness::CC_vecfunction::CC_vecfunction(), madness::CC_vecfunction::CC_vecfunction(), madness::CC_vecfunction::CC_vecfunction(), madness::CC_vecfunction::CC_vecfunction(), madness::CC_vecfunction::CC_vecfunction(), madness::Future< std::vector< Future< T > > >::Future(), madness::Future< std::vector< Future< T > > >::Future(), madness::LBDeuxPmap< NDIM >::LBDeuxPmap(), madness::MyPmap< D >::MyPmap(), madness::WorldContainerIterator< internal_iteratorT >::WorldContainerIterator(), a(), madness::abssq(), madness::scf_data::add_data(), madness::CCSize::add_helper(), madness::Znemo::analyze(), madness::append(), madness::apply(), madness::apply(), KPeriodicBSHOperator::apply(), madness::MP2::apply_exchange_vector(), apply_mask(), apply_potential(), madness::projector_irrep::apply_symmetry_operators(), apply_U_mix(), madness::Group::Impl::begin(), madness::FunctionImpl< T, NDIM >::broaden(), madness::FunctionImpl< T, NDIM >::broaden_op(), madness::MyPmap< D >::build_tree_map(), c_uks_vwn5__(), madness::c_uks_vwn5__(), madness::TDHF::canonicalize(), cell_volume(), madness::change_tree_state(), madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::PNO::check_orthonormality(), madness::CCPair::cloud_load(), custom_serialize_tester::cloud_load(), madness::CCPair::cloud_store(), custom_serialize_tester::cloud_store(), madness::compress(), madness::compress(), madness::compress(), madness::FunctionImpl< T, NDIM >::compress_op(), madness::FunctionImpl< T, NDIM >::compress_spawn(), madness::F12Potentials::compute_fQc_integrals_ij(), compute_madelung_energy(), compute_madelung_energy_PWSCF(), madness::WorldGopInterface::concat0(), madness::conj(), madness::convert(), madness::copy(), madness::copy(), madness::copy(), madness::copy(), madness::Batch_1D::copy_batch(), madness::Batch_1D::copy_batch(), madness::copy_n(), madness::FunctionImpl< T, NDIM >::copy_remote_coeffs_from_pid(), diag_and_transform(), madness::div(), EwaldNuclearPotentialFunctor::do_G_sum_v1(), EwaldNuclearPotentialFunctor::do_G_sum_v2(), EwaldNuclearPotentialFunctor::do_R_sum_v1(), Node::do_sum(), Node::do_sum_spawn(), MiniDFT::doit(), doit(), madness::FunctionImpl< T, NDIM >::downsample(), madness::Group::Impl::end(), energy(), madness::ensure_tree_state_respecting_fence(), madness::XCfunctional::exc(), madness::Key< NDIM >::extract_complement_key(), madness::BasisFunctions::fill_up(), madness::gaxpy(), madness::gaxpy_oop(), geev_(), geev_(), geev_(), geev_(), madness::Future< std::vector< Future< T > > >::get(), madness::Future< std::vector< Future< T > > >::get(), madness::PNO::get_average_rank(), madness::FunctionImpl< T, NDIM >::get_contraction_node_lists(), madness::get_impl(), madness::get_size(), madness::get_size_local(), madness::get_tree_state(), madness::Random::getbytes(), madness::Random::getv(), Test2::gradient(), hamiltonian_matrix(), madness::hash_combine(), HO_vphi_3d(), madness::imag(), madness::impl2function(), initial_guess(), madness::inner(), madness::inner(), madness::Batch_1D::insert_batch(), madness::Batch::insert_result_batch(), madness::FunctionImpl< T, NDIM >::insert_serialized_coeffs(), std::isnan(), iterate(), jacobi(), kinetic_energy_matrix(), madness::SCF::kinetic_energy_matrix(), madness::Kinetic< T, NDIM >::kinetic_energy_matrix(), MiniDFT::kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), line_plot(), linspace(), madness::archive::ArchiveLoadImpl< Archive, std::array< T, N >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::atomic< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::string >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< bool, Alloc > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< Future< T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), LSQ(), main(), main(), madness::TDHF::make_bra(), madness::SCF::make_density(), madness::SCF::make_density(), make_density(), MiniDFT::make_density(), make_exp(), make_exp(), madness::FunctionImpl< T, NDIM >::make_key_vec_map(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), make_kinetic_matrix(), madness::make_nonstandard(), madness::make_redundant(), madness::FunctionImpl< T, NDIM >::make_redundant_op(), madness::SRConf< T >::make_vector_with_weights(), madness::matrix_inner(), moments(), madness::mul(), madness::mul(), madness::mul_sparse(), madness::mul_sparse(), madness::Function< T, NDIM >::multiop_values(), madness::FunctionImpl< T, NDIM >::multiop_values(), madness::FunctionImpl< T, NDIM >::multiop_values_doit(), madness::multiply(), QuasiNewton::new_search_direction(), madness::QuasiNewton::new_search_direction(), madness::MolecularOptimizer::new_search_direction2(), madness::nonstandard(), norm(), madness::norm2(), madness::norm2s(), madness::norm2s(), madness::norm2s_T(), madness::norm_tree(), madness::norm_tree(), madness::FunctionImpl< T, NDIM >::norm_tree_op(), madness::FunctionImpl< T, NDIM >::norm_tree_spawn(), madness::normalize(), normalize2(), madness::R_times_arg_div_R::operator()(), YetAnotherWrapperClass::operator()(), madness::GenericConvolution1D< Q, opT >::Shmoo::operator()(), madness::operator*(), madness::operator*(), madness::KahanAccumulator< Complex, std::enable_if_t<!std::is_floating_point_v< Complex > > >::operator+=(), madness::KahanAccumulator< Complex, std::enable_if_t<!std::is_floating_point_v< Complex > > >::operator+=(), madness::KahanAccumulator< Real, std::enable_if_t< std::is_floating_point_v< Real > > >::operator+=(), madness::KahanAccumulator< Real, std::enable_if_t< std::is_floating_point_v< Real > > >::operator+=(), madness::KahanAccumulator< Complex, std::enable_if_t<!std::is_floating_point_v< Complex > > >::operator-=(), madness::KahanAccumulator< Complex, std::enable_if_t<!std::is_floating_point_v< Complex > > >::operator-=(), madness::KahanAccumulator< Real, std::enable_if_t< std::is_floating_point_v< Real > > >::operator-=(), madness::KahanAccumulator< Real, std::enable_if_t< std::is_floating_point_v< Real > > >::operator-=(), madness::operators::operator<<(), madness::operator>>(), opt(), opt(), madness::MolecularOptimizer::optimize_quasi_newton(), orth(), madness::orthonormalize_canonical(), madness::orthonormalize_canonical(), madness::orthonormalize_cd(), madness::orthonormalize_cd(), madness::orthonormalize_rrcd(), madness::orthonormalize_rrcd(), madness::orthonormalize_rrcd(), madness::orthonormalize_symmetric(), madness::orthonormalize_symmetric(), madness::FunctionImpl< T, NDIM >::partial_inner_contract(), periodic_sum_accelerated(), madness::plot_line_print_value(), madness::plot_line_print_value(), Calculation::plot_p(), madness::ThreadPool::pool_thread_main(), DF::pop(), molresponse::pop(), madness::pop(), madness::MacroTask< taskT >::prepare_output_records(), madness::WorldProfile::print(), AtomicBasisSet::print_anal(), madness::AtomicBasisSet::print_anal(), madness::print_size(), print_stats(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), psi_guess(), random_perm(), madness::SeparatedConvolution< Q, NDIM >::range_restricted(), Plotter::read_cell(), madness::real(), madness::PNOPairs::reassemble(), madness::PNOPairs::reassemble(), madness::reconstruct(), madness::reconstruct(), madness::reconstruct(), madness::WorldProfile::recv_stats(), madness::reduce_rank(), madness::FunctionImpl< T, NDIM >::refine_to_common_level(), madness::permutation::remove_duplicates(), madness::LowRankFunction< T, NDIM, LDIM >::reorthonormalize_rrcd(), rk_v(), madness::GaussianConvolution1D< Q >::rnlp(), madness::rot(), madness::Znemo::rotate_subspace(), madness::SCF::rotate_subspace(), madness::SCF::rotate_subspace(), run(), madness::scalar_result_vector(), madness::scale(), madness::scale(), madness::scale(), madness::scale(), madness::FunctionImpl< T, NDIM >::serialize_remote_coeffs(), Node::set(), madness::CC_vecfunction::set_functions(), madness::set_impl(), madness::set_thresh(), madness::projector_irrep::set_verbosity(), madness::Group::Impl::size(), madness::SpectralPropagator::solve(), madness::BinSorter< T, inserterT >::sorter(), MolecularMaskBase::special_points(), madness::square(), madness::standard(), madness::standard(), madness::SpectralPropagatorGaussLobatto::step(), madness::SpectralPropagator::step(), madness::archive::ArchiveStoreImpl< Archive, std::array< T, N >, std::enable_if_t< is_serializable_v< Archive, T > > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::atomic< T >, std::enable_if_t< is_serializable_v< Archive, T > > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::string >::store(), madness::archive::ArchiveStoreImpl< Archive, std::vector< bool, Alloc > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::vector< Future< T > > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::vector< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::store(), madness::archive::ArchiveStoreImpl< ParallelOutputArchive< ContainerRecordOutputArchive >, WorldContainer< keyT, valueT > >::store(), madness::Cloud::store_tuple(), madness::TDHF::symmetrize(), tabulate(), tensor2vec(), test13(), test8(), test9(), test_chin_chen(), test_convolution(), test_florian(), test_immediate(), test_in(), test_lda(), test_out(), test_qm(), test_time(), test_trotter(), test_XCOperator(), madness::transform(), madness::transform(), madness::transform(), madness::transform(), madness::transform(), madness::Zcis::transform(), transform(), madness::transform_reconstructed(), madness::truncate(), madness::truncate(), madness::truncate(), madness::truncate(), madness::FunctionImpl< T, NDIM >::truncate_op(), madness::FunctionImpl< T, NDIM >::truncate_reconstructed_op(), madness::FunctionImpl< T, NDIM >::truncate_reconstructed_spawn(), madness::FunctionImpl< T, NDIM >::truncate_spawn(), madness::SpectralPropagator::u(), madness::SpectralPropagatorGaussLobatto::u(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::validate_distribution_type(), Test2::value(), vec2tensor(), madness::vector_factory(), madness::vector_factory(), madness::vector_factory(), madness::vector_factory(), madness::vector_factory(), madness::vector_factory(), madness::vector_factory(), madness::vector_factory(), madness::SCF::vector_stats(), madness::verify_tree(), madness::Function< T, NDIM >::vimpl(), madness::Function< T, NDIM >::vtransform(), and madness::XCfunctional::vxc().
Vtruncmode
const int Vtruncmode = (Z<=10 && thresh>1e-10) ? 1 : 0 static
Referenced by run().
Z
const double Z = 80.0 static
Referenced by exact_energy(), Vderiv::operator()(), phi_guess(), psi_guess(), run(), and V().