MADNESS: he.cc File Reference
he.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/lbdeux.h>
Classes
struct LBCost
struct true_op
class YetAnotherWrapperClass
Functions
void distances (const coord_6d &r, double &r1, double &r2, double &r12)
double energy (World &world, const real_function_6d &psi)
static double f6d (const coord_6d &r)
int main (int argc, char **argv)
real_function_6d multiply_by_V (const real_function_6d &psi)
static double u (double r, double c)
static double V (const coord_6d &r)
Variables
static const double d12cut = 0.01
static const double dcut = 0.01
static const long k = 6
static const double L = 30.0
static const long oi = 0
static const double r12cut = 0.01
static const double rcut = 0.01
static const double thresh = 1e-4
static const long vi = 1
Function Documentation
distances()
void distances (const coord_6d & r, double & r1, double & r2, double & r12)
References madness::nonlinear_vector_solver(), and madness::r2().
Referenced by f6d(), and V().
energy()
double energy (World & world, const real_function_6d & psi)
References axis, d12cut, dcut, madness::inner(), k, L, multiply_by_V(), madness::nonlinear_vector_solver(), oi, madness::print(), psi(), r12cut, madness::World::rank(), rcut, thresh, and vi.
f6d()
static double f6d (const coord_6d & r) static
References d12cut, dcut, distances(), MADNESS_EXCEPTION, madness::nonlinear_vector_solver(), oi, and madness::r2().
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::LoadBalanceDeux< NDIM >::add_tree(), SafeMPI::COMM_WORLD, energy, madness::FunctionFactory< T, NDIM >::f(), f6d(), madness::finalize(), madness::initialize(), k, L, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::nonlinear_vector_solver(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), thresh, madness::TT_2D, and madness::wall_time().
multiply_by_V()
real_function_6d multiply_by_V (const real_function_6d & psi)
References madness::copy(), madness::nonlinear_vector_solver(), and psi().
Referenced by energy().
u()
static double u (double r, double c) static
References c, e(), madness::nonlinear_vector_solver(), and madness::r2().
Referenced by madness::TaskFn< fnT, arg1T, arg2T, arg3T, arg4T, arg5T, arg6T, arg7T, arg8T, arg9T >::TaskFn(), apply_potential(), applyexpLt(), applyN(), madness::Stack< T, N >::clear(), madness::TensorTrain< T >::decompose(), GygiPot::dESP_drho(), doit(), madness::CorePotential::eval(), madness::FunctionImpl< T, NDIM >::eval_cube(), madness::CorePotential::eval_derivative(), expL_double(), gesvd_(), gesvd_(), gesvd_(), gesvd_(), hamiltonian_matrix(), madness::hash_value(), hashbig(), hashlittle(), hashlittle2(), madness::CC2::iterate_lrcc2_pairs(), jacobi(), madness::jacobi(), jacobi(), Calculation::load_mos(), main(), main(), SVPESolver::make_surface_charge(), GygiPot::make_surfcharge(), SurfaceMoleculeInteraction::make_surfcharge(), moments(), madness::Stack< T, N >::move(), N_double(), normalize2(), madness::Molecule::nuclear_attraction_potential_second_derivative(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::Stack< T, N >::reset(), SVPESolver::solve(), madness::CC2::solve_mp2_coupled(), test(), test0(), test0GaussLobatto(), test1(), test_U_el(), testNavierStokes(), madness::NonlinearSolverND< NDIM >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::CCPair::update_u(), V(), and GygiPot::V_epsilon().
V()
static double V (const coord_6d & r) static
References distances(), MADNESS_EXCEPTION, madness::nonlinear_vector_solver(), r12cut, madness::r2(), rcut, u(), and vi.
Variable Documentation
d12cut
const double d12cut = 0.01 static
Referenced by energy(), and f6d().
dcut
const double dcut = 0.01 static
Referenced by madness::MP2::MP2(), madness::MP2::compute_energy(), madness::TwoElectronFactory< T, NDIM >::dcut(), energy(), f6d(), and test_Kcommutator().
k
const long k = 6 static
Referenced by energy(), and main().
L
const double L = 30.0 static
Referenced by energy(), and main().
oi
const long oi = 0 static
Referenced by energy(), f6d(), madness::Solver< T, NDIM >::initial_guess(), madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolver< T, NDIM >::multi_solve(), madness::EigSolver< T, NDIM >::prepare_ops(), madness::EigSolver< T, NDIM >::print_matrix_elements(), and madness::EigSolver< T, NDIM >::solve().
r12cut
const double r12cut = 0.01 static
Referenced by energy(), and V().
rcut
const double rcut = 0.01 static
Referenced by energy(), and V().
thresh
const double thresh = 1e-4 static
Referenced by energy(), and main().
vi
const long vi = 1 static
Referenced by madness::F12Potentials::apply_regularized_potential(), madness::PNO::compute_fluctuation_matrix(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), energy(), madness::response_space::operator*(), madness::response_space::operator*=(), madness::response_space::operator+(), madness::response_space::operator-(), TEST_CASE(), and V().