MADNESS: heat.cc File Reference
heat.cc File Reference
Example Green function for the 3D heat equation.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Classes
class uexact
Typedefs
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef Tensor< double > tensorT
Functions
int main (int argc, char **argv)
static double uinitial (const coordT &r)
Variables
static const double alpha = 1.9
static const double c = 2.0
static const long k = 8
static const double L = 10
static const double thresh = 1e-6
static const double tstep = 0.333
Detailed Description
Example Green function for the 3D heat equation.
Typedef Documentation
coordT
typedef Vector<double,3> coordT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
tensorT
typedef Tensor<double> tensorT
Function Documentation
main()
int main (int argc, char ** argv)
References c, SafeMPI::COMM_WORLD, madness::Function< T, NDIM >::err(), madness::WorldGopInterface::fence(), madness::finalize(), G, madness::World::gop, madness::initialize(), k, L, madness::Function< T, NDIM >::norm2(), madness::constants::pi, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), tstep, uexact(), and uinitial().
uinitial()
static double uinitial (const coordT & r) static
References alpha, madness::constants::pi, and pow().
Referenced by main().
Variable Documentation
alpha
const double alpha = 1.9 static
Referenced by uexact::operator()(), and uinitial().
c
const double c = 2.0 static
Referenced by main(), and uexact::operator()().
k
const long k = 8 static
Referenced by main().
L
const double L = 10 static
Referenced by main().
thresh
const double thresh = 1e-6 static
Referenced by main().
tstep
const double tstep = 0.333 static
Referenced by main(), propagate(), q_c(), sympgrad4(), sympgrad6(), test2(), test_chin_chen(), test_qm(), test_trotter(), and trotter().