MADNESS: hefxc.cc File Reference
hefxc.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/nonlinsol.h>
#include <madness/mra/lbdeux.h>
#include <madness/mra/qmprop.h>
#include <madness/misc/misc.h>
#include <madness/misc/ran.h>
#include <madness/tensor/systolic.h>
#include <madness/tensor/elem.h>
#include <madness/chem/xcfunctional.h>
#include <madness/chem/SCFOperators.h>
#include <madness/mra/legendre.h>
Typedefs
typedef Function< std::complex< double >, 3 > complex_functionT
typedef Convolution1D< double_complex > complex_operatorT
typedef Vector< double, 3 > coordT
typedef std::vector< complex_functionT > cvecfuncT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::pair< vecfuncT, vecfuncT > pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef std::vector< functionT > vecfuncT
Functions
static double guess (const coord_3d &r)
int main (int argc, char **argv)
Variables
std::vector< std::shared_ptr< real_derivative_3d > > gradop
static const long k = 8
static const double Length = 50.0
static const double thresh = 1e-6
Typedef Documentation
complex_functionT
typedef Function<std::complex<double>,3> complex_functionT
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
coordT
typedef Vector<double,3> coordT
cvecfuncT
typedef std::vector<complex_functionT> cvecfuncT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pairvecfuncT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
subspaceT
typedef std::vector<pairvecfuncT> subspaceT
tensorT
typedef Tensor<double> tensorT
vecfuncT
typedef std::vector<functionT> vecfuncT
Function Documentation
guess()
static double guess (const coord_3d & r) static
References e().
Referenced by main().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, gradop, guess(), madness::initialize(), k, Length, madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), and xc.
Variable Documentation
gradop
std::vector< std::shared_ptr<real_derivative_3d> > gradop
Referenced by main().
k
const long k = 8 static
Referenced by main().
Length
const double Length = 50.0 static
Referenced by main().
thresh
const double thresh = 1e-6 static
Referenced by main().