MADNESS: InitParameters.h File Reference
InitParameters.h File Reference
#include "fcwf.h"
#include <madness/chem/NWChem.h>
Classes
struct madness::InitParameters
Namespaces
madness
File holds all helper structures necessary for the CC_Operator and CC2 class.
Functions
Function< std::complex< double >, 3 > function_real2complex (const Function< double, 3 > &r)
double myxfunc (const madness::coord_3d &r)
double myyfunc (const madness::coord_3d &r)
Function Documentation
function_real2complex()
Function<std::complex<double>,3> function_real2complex (const Function< double, 3 > & r)
References madness::unary_op_coeffs().
myxfunc()
double myxfunc (const madness::coord_3d & r)
Referenced by madness::InitParameters::read().
myyfunc()
double myyfunc (const madness::coord_3d & r)
Referenced by madness::InitParameters::read().