MADNESS: InputWriter.cpp File Reference
InputWriter.cpp File Reference
#include <madness/chem/InputWriter.hpp>
Typedefs
using commandlineparser = madness::commandlineparser
using json = nlohmann::json
using path = std::filesystem::path
Functions
void write_json_to_input_file (const json &input_json, const std::vector< std::string > &keys, std::ostream &output_stream)
void write_moldft_input (const json &input_json, std::ostream &out)
void write_molecule_json_to_input_file (const json &molecule_json, std::ostream &output_stream)
void write_response_input (const json &input_json, std::ostream &out)
Typedef Documentation
commandlineparser
using commandlineparser = madness::commandlineparser
json
using json = nlohmann::json
path
using path = std::filesystem::path
Function Documentation
write_json_to_input_file()
void write_json_to_input_file (const json & input_json, const std::vector< std::string > & keys, std::ostream & output_stream)
Referenced by write_moldft_input(), and write_response_input().
write_moldft_input()
void write_moldft_input (const json & input_json, std::ostream & out)
References write_json_to_input_file(), and write_molecule_json_to_input_file().
write_molecule_json_to_input_file()
void write_molecule_json_to_input_file (const json & molecule_json, std::ostream & output_stream)
Referenced by write_moldft_input().
write_response_input()
void write_response_input (const json & input_json, std::ostream & out)
References write_json_to_input_file().