MADNESS: interp3.cc File Reference
interp3.cc File Reference
#include <iostream>
#include <cmath>
#include <vector>
#include <madness/world/worldinit.h>
#include <madness/misc/interpolation_1d.h>
Functions
double func (double x)
A simple program for testing the CubicInterpolationTable class.
int main (int argc, char *argv[])
Function Documentation
func()
double func (double x)
A simple program for testing the CubicInterpolationTable class.
Referenced by madness::PotentialManager::core_projector_derivative(), main(), nuclear_generator(), opt(), opt(), and slymer::NWChem_Interface::read_basis_set().
main()
int main (int argc, char * argv[])
References madness::finalize(), fit(), func(), and madness::initialize().