MADNESS: mad-freq.cpp File Reference
mad-freq.cpp File Reference
#include "ResponseExceptions.hpp"
#include "madness/tensor/tensor_json.hpp"
#include "madness/world/worldmem.h"
#include "response_functions.h"
#include "runners.hpp"
Typedefs
using path = std::filesystem::path
Functions
auto main (int argc, char *argv[]) -> int
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
main()
auto main (int argc, char * argv[]) -> int
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), op(), madness::print(), madness::print_stats(), madness::World::rank(), madness::startup(), and xc.