MADNESS: madinfo.cc File Reference
madinfo.cc File Reference
#include <string>
#include <iostream>
#include "madness/misc/info.h"
#include <madness/madness_config.h>
Functions
int main ()
Function Documentation
main()
int main (void)
References madness::info::build_date(), madness::info::build_time(), and madness::info::git_source_description().