MADNESS: madness_catch_main_init.cc File Reference
madness_catch_main_init.cc File Reference
#include <chem/write_test_input.h>
#include "apps/chem/SCF.h"
#include "apps/external_headers/catch.hpp"
#include "madness/world/worldmem.h"
Macros
#define CATCH_CONFIG_RUNNER
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Function Documentation
main()
int main (int argc, char * argv[])
References e(), error(), write_test_input::filename(), madness::initialize(), print(), and madness::startup().