MADNESS: madqc2.cpp File Reference
madqc2.cpp File Reference
#include <fstream>
#include <madness/misc/info.h>
#include <madness/world/worldmem.h>
#include "Drivers.hpp"
#include "MoldftLib.hpp"
#include "MolresponseLib.hpp"
#include "CCLib.hpp"
#include "ParameterManager.hpp"
Functions
static void END_TIMER (World &world, const char *msg)
int main (int argc, char **argv)
static void START_TIMER (World &world)
Variables
static double sss
static double ttt
Function Documentation
END_TIMER()
static void END_TIMER (World & world, const char * msg) static
References madness::cpu_time(), madness::World::rank(), sss, ttt, and madness::wall_time().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), MADNESS_EXCEPTION, p(), madness::print(), madness::print_header1(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_tensor_type(), START_TIMER, madness::startup(), madness::TT_2D, and madness::commandlineparser::value().
START_TIMER()
static void START_TIMER (World & world) static
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().
Variable Documentation
sss
double sss static
Referenced by END_TIMER(), and START_TIMER().
ttt
double ttt static
Referenced by END_TIMER(), and START_TIMER().