MADNESS: madqc.cpp File Reference
madqc.cpp File Reference
#include <fstream>
#include <madness/misc/info.h>
#include <madness/world/worldmem.h>
#include <Drivers.hpp>
#include <MoldftLib.hpp>
#include <MolresponseLib.hpp>
#include <CCLib.hpp>
#include <ParameterManager.hpp>
#include <madness_exception.h>
Functions
void help (std::string wf)
int main (int argc, char **argv)
void print_parameters (World &world, const commandlineparser &parser, const std::string group)
Function Documentation
help()
void help (std::string wf)
TODO:
restart options
nemo projections
numerical parameters
References madness::print().
main()
int main (int argc, char ** argv)
References e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, help, madness::initialize(), madness::commandlineparser::key_exists(), MADNESS_EXCEPTION, molecule, p(), madness::print(), madness::print_header1(), madness::print_header2(), print_parameters(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::startup(), madness::TT_2D, and madness::commandlineparser::value().
print_parameters()
void print_parameters (World & world, const commandlineparser & parser, const std::string group)
References madness::QCCalculationParametersBase::print(), and madness::print().
Referenced by main().