MADNESS: module.cpp File Reference
module.cpp File Reference
#include <pybind11/pybind11.h>
Functions
void bind_defaults (py::module_ &m)
void bind_function (py::module_ &m)
void bind_operators (py::module_ &m)
void bind_tensor (py::module_ &m)
void bind_world (py::module_ &m)
PYBIND11_MODULE (_pymadness, m)
Function Documentation
bind_defaults()
void bind_defaults (py::module_ & m)
References m.
Referenced by PYBIND11_MODULE().
bind_function()
void bind_function (py::module_ & m)
References m.
Referenced by PYBIND11_MODULE().
bind_operators()
void bind_operators (py::module_ & m)
References madness::apply(), axis, madness::BSHOperatorPtr3D(), madness::CoulombOperatorPtr(), madness::f, madness::grad(), lo, m, mu, op(), madness::SlaterOperatorPtr(), and w().
Referenced by PYBIND11_MODULE().
bind_tensor()
void bind_tensor (py::module_ & m)
References madness::BaseTensor::dim(), m, madness::BaseTensor::ndim(), numpy_to_tensor(), madness::BaseTensor::size(), and tensor_to_numpy().
Referenced by PYBIND11_MODULE().
bind_world()
void bind_world (py::module_ & m)
References madness::finalize(), madness::initialize(), m, madness::quiet(), madness::World::rank(), madness::World::size(), madness::startup(), w(), and madness::World::world_from_id().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (_pymadness , m)
References bind_defaults(), bind_function(), bind_operators(), bind_tensor(), bind_world(), and m.