MADNESS: moldft.cc File Reference
moldft.cc File Reference
Molecular HF and DFT code.
#include <madness/chem/SCF.h>
#include "madness/mra/commandlineparser.h"
#include <madness/chem/molopt.h>
#include <madness/world/worldmem.h>
#include <madness/misc/info.h>
Functions
static void END_TIMER (World &world, const char *msg)
int main (int argc, char **argv)
static void START_TIMER (World &world)
Variables
static double sss
static double ttt
Detailed Description
Molecular HF and DFT code.
Function Documentation
END_TIMER()
static void END_TIMER (World & world, const char * msg) static
References madness::cpu_time(), madness::nonlinear_vector_solver(), madness::World::rank(), sss, ttt, and madness::wall_time().
main()
int main (int argc, char ** argv)
References madness::scf_data::add_gradient(), madness::CalculationParameters::algopt(), madness::SCF::amo, madness::SCF::aocc, madness::SCF::bmo, madness::SCF::bocc, madness::SCF::current_energy, madness::CalculationParameters::derivatives(), madness::SCF::derivatives(), madness::SCF::dipole(), madness::SCF::do_plots(), e(), madness::SCF::e_data, END_TIMER, energy, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::Tensor< T >::flat(), madness::Function< T, NDIM >::gaxpy(), madness::Molecule::get_all_coords(), madness::CalculationParameters::gmaxiter(), madness::World::gop, madness::CalculationParameters::gopt(), madness::CalculationParameters::gprec(), madness::CalculationParameters::gtol(), madness::CalculationParameters::gval(), madness::SCF::help(), madness::SCF::initial_load_bal(), madness::initialize(), madness::commandlineparser::key_exists(), madness::SCF::make_density(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::CalculationParameters::nbeta(), madness::nonlinear_vector_solver(), opt(), madness::MolecularEnergy::output_calc_info_schema(), madness::SCF::output_scf_info_schema(), madness::SCF::param, madness::QCCalculationParametersBase::print(), madness::print(), madness::Molecule::print(), madness::print_header1(), madness::CalculationParameters::print_level(), madness::print_meminfo(), madness::SCF::print_parameters(), madness::info::print_revision_information(), madness::print_stats(), madness::CalculationParameters::protocol(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::SCF::set_protocol(), madness::World::size(), madness::CalculationParameters::spin_restricted(), START_TIMER, madness::startup(), target(), madness::commandlineparser::value(), and madness::MolecularEnergy::value().
START_TIMER()
static void START_TIMER (World & world) static
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().
Variable Documentation
sss
double sss static
Referenced by END_TIMER(), and START_TIMER().
ttt
double ttt static
Referenced by END_TIMER(), and START_TIMER().