MADNESS: mraplot.cc File Reference
mraplot.cc File Reference
Function plotting utility.
#include <madness/mra/mra.h>
#include <unistd.h>
#include <cstdio>
#include <madness/constants.h>
#include <madness/misc/phandler.h>
Classes
struct lbcost< T, NDIM >
class Plotter
Functions
int main (int argc, char **argv)
Variables
std::string help
Detailed Description
Function plotting utility.
Function Documentation
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::broadcast_serializable(), SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), Plotter::finished, madness::World::gop, help, madness::initialize(), Plotter::plot(), madness::print(), madness::World::rank(), Plotter::read(), and madness::startup().
Variable Documentation
help
std::string help
Referenced by main().