MADNESS: mTxm_tune.cc File Reference
mTxm_tune.cc File Reference
#include <complex>
Typedefs
typedef complex< double > double_complex
Functions
void mTxm_tune (long dimi, long dimj, long dimk, double *c, const double *a, const double *b)
void mTxm_tune (long dimi, long dimj, long dimk, double_complex *c, const double_complex *a, const double_complex *b)
Typedef Documentation
double_complex
typedef complex<double> double_complex
Function Documentation
mTxm_tune() [1/2]
void mTxm_tune (long dimi, long dimj, long dimk, double * c, const double * a, const double * b)
References a, b, c, and k.
Referenced by timer(), and trantimer().
mTxm_tune() [2/2]
void mTxm_tune (long dimi, long dimj, long dimk, double_complex * c, const double_complex * a, const double_complex * b)
References a, b, c, and k.
Referenced by timer(), and trantimer().