MADNESS: madness::info Namespace Reference
madness::info Namespace Reference
Runtime details on the configuration and version of MADNESS.
Functions
const char * build_date ()
return the build date
const char * build_time ()
return the build time
const char * git_commit ()
Get the git commit number for this version.
const char * git_source_description ()
Get the git source tree human-readable description (see git describe --dirty)
std::string print_revision_information ()
const char * version ()
Get the MADNESS version number.
Detailed Description
Runtime details on the configuration and version of MADNESS.
Function Documentation
build_date()
const char * madness::info::build_date ()
return the build date
Referenced by main(), and print_revision_information().
build_time()
const char * madness::info::build_time ()
return the build time
Referenced by main(), and print_revision_information().
git_commit()
const char * madness::info::git_commit ()
Get the git commit number for this version.
Returns
The git commit number.
git_source_description()
const char * madness::info::git_source_description ()
Get the git source tree human-readable description (see git describe --dirty)
Returns
The git commit number.
Referenced by main(), and print_revision_information().
print_revision_information()
std::string madness::info::print_revision_information ()
References build_date(), build_time(), and git_source_description().
Referenced by main().
version()
const char * madness::info::version ()
Get the MADNESS version number.
Returns
The MADNESS version number.
Referenced by madness::SCF::load_mos(), madness::InitParameters::read(), madness::MolecularOrbitals< T, NDIM >::read_restartdata(), madness::SCF::save_mos(), and madness::MolecularOrbitals< T, NDIM >::save_restartdata().