MADNESS: madness::lapacke Namespace Reference
madness::lapacke Namespace Reference
Functions
template<typename T >
const lapack_complex_float * to_cptr (const T *ptr)
template<typename T >
std::enable_if<!std::is_const< T >::value, lapack_complex_float * >::type to_cptr (T *ptr)
template<typename T >
const lapack_complex_double * to_zptr (const T *ptr)
template<typename T >
std::enable_if<!std::is_const< T >::value, lapack_complex_double * >::type to_zptr (T *ptr)
Function Documentation
to_cptr() [1/2]
template<typename T > const lapack_complex_float * madness::lapacke::to_cptr (const T * ptr)
References lapack_complex_float, and T().
to_cptr() [2/2]
template<typename T > std::enable_if<!std::is_const< T >::value, lapack_complex_float * >::type madness::lapacke::to_cptr (T * ptr)
References lapack_complex_float, and T().
to_zptr() [1/2]
template<typename T > const lapack_complex_double * madness::lapacke::to_zptr (const T * ptr)
References lapack_complex_double, and T().
to_zptr() [2/2]
template<typename T > std::enable_if<!std::is_const< T >::value, lapack_complex_double * >::type madness::lapacke::to_zptr (T * ptr)
References lapack_complex_double, and T().