MADNESS: SafeMPI::detail Namespace Reference
SafeMPI::detail Namespace Reference
Functions
void init_comm_world ()
Initialize SafeMPI::COMM_WORLD.
void print_mpi_error (const int rc, const char *function, const int line, const char *file)
Function Documentation
init_comm_world()
void SafeMPI::detail::init_comm_world () inline
Initialize SafeMPI::COMM_WORLD.
References SafeMPI::COMM_WORLD, MADNESS_MPI_TEST, MPI_Comm_rank(), MPI_Comm_set_errhandler(), MPI_Comm_size(), MPI_ERRORS_RETURN, and SafeMPI::Intracomm::pimpl.
Referenced by madness::detail::WorldMpi::WorldMpi(), SafeMPI::Init(), and SafeMPI::Init_thread().
print_mpi_error()
void SafeMPI::detail::print_mpi_error (const int rc, const char * function, const int line, const char * file) inline
References function(), MPI_Error_string(), and MPI_MAX_ERROR_STRING.
Referenced by SafeMPI::Group::Impl::~Impl().