MADNESS: molresponse Namespace Reference
molresponse Namespace Reference
Classes
struct write_response_input
will write a test input and remove it from disk upon destruction
struct write_test_input
will write a test input and remove it from disk upon destruction
Functions
void end_timer (madness::World &world, const char *msg)
void end_timer (madness::World &world, const char *msg, const std::string &key, std::map< std::string, std::pair< double, double >> &time)
double pop (std::vector< double > &v)
void start_timer (madness::World &world)
Variables
static std::vector< double > sss
static std::vector< double > ttt
Function Documentation
end_timer() [1/2]
void molresponse::end_timer (madness::World & world, const char * msg)
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, pop(), madness::World::rank(), sss, ttt, and madness::wall_time().
Referenced by ground_exchange(), molresponseExchange(), and TEST_CASE().
end_timer() [2/2]
void molresponse::end_timer (madness::World & world, const char * msg, const std::string & key, std::map< std::string, std::pair< double, double >> & time)
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, pop(), madness::World::rank(), sss, ttt, and madness::wall_time().
pop()
double molresponse::pop (std::vector< double > & v)
References v.
Referenced by end_timer().
start_timer()
void molresponse::start_timer (madness::World & world)
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().
Referenced by ground_exchange(), ground_exchange_multiworld(), main(), molresponseExchange(), response_exchange(), response_exchange_multiworld(), and TEST_CASE().
Variable Documentation
sss
std::vector<double> molresponse::sss static
Referenced by end_timer(), and start_timer().
ttt
std::vector<double> molresponse::ttt static
Referenced by end_timer(), and start_timer().