MADNESS: madness::detail::arg_holder Namespace Reference
madness::detail::arg_holder Namespace Reference
Functions
template<typename T >
T && decay (ArgHolder< T > &&arg_holder)
template<typename T >
T & decay (ArgHolder< T > &arg_holder)
template<typename T >
const T & decay (const ArgHolder< T > &arg_holder)
template<typename T >
const T & decay (const Future< T > &arg_holder)
template<typename T >
T && decay (Future< T > &&arg_holder)
template<typename T >
T & decay (Future< T > &arg_holder)
template<typename T >
T & decay (Future< T > *arg_holder)
template<typename T >
auto decay (T &&arg_holder) -> typename std::enable_if< !is_future< T >::value &&!is_arg_holder< T >::value, decltype(arg_holder)>::type
Function Documentation
decay() [1/8]
template<typename T > T && madness::detail::arg_holder::decay (ArgHolder< T > && arg_holder)
References decay(), and T().
decay() [2/8]
template<typename T > T & madness::detail::arg_holder::decay (ArgHolder< T > & arg_holder)
References decay().
Referenced by decay(), decay(), decay(), decay(), decay(), decay(), decay(), and decay().
decay() [3/8]
template<typename T > const T & madness::detail::arg_holder::decay (const ArgHolder< T > & arg_holder)
References decay().
decay() [4/8]
template<typename T > const T & madness::detail::arg_holder::decay (const Future< T > & arg_holder)
References decay().
decay() [5/8]
template<typename T > T && madness::detail::arg_holder::decay (Future< T > && arg_holder)
References decay(), and T().
decay() [6/8]
template<typename T > T & madness::detail::arg_holder::decay (Future< T > & arg_holder)
References decay().
decay() [7/8]
template<typename T > T & madness::detail::arg_holder::decay (Future< T > * arg_holder)
References decay(), and T().
decay() [8/8]
template<typename T > auto madness::detail::arg_holder::decay (T && arg_holder) -> typename std::enable_if< !is_future<T>::value && !is_arg_holder<T>::value, decltype(arg_holder)>::type
References decay().