MADNESS: std Namespace Reference
std Namespace Reference
Functions
static long abs (long a)
template<typename hashT , typename distT >
void advance (madness::Hash_private::HashIterator< hashT > &it, const distT &dist)
template<typename hashT >
int distance (const madness::Hash_private::HashIterator< hashT > &it, const madness::Hash_private::HashIterator< hashT > &jt)
madness::hashT hash_value (const madness::DistributedID &id)
Hash a DistributedID.
template<typename T >
bool isnan (const std::complex< T > &v)
Function Documentation
abs()
static long std::abs (long a) static
References a.
Referenced by madness::BandlimitedPropagator::BandlimitedPropagator(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), ExactSpinor::ExactSpinor(), GaussianGuess< NDIM >::GaussianGuess(), madness::TensorIterator< T, Q, R >::TensorIterator(), madness::abs(), madness::Tensor< T >::absmax(), madness::Tensor< T >::absmin(), madness::SeparatedConvolution< Q, NDIM >::apply(), madness::SeparatedConvolution< Q, NDIM >::apply2(), madness::SeparatedConvolution< Q, NDIM >::apply2_lowdim(), madness::GTHPseudopotential< Q >::apply_potential_simple(), madness::SCFProtocol::approx(), approximately_equal(), madness::GFit< T, NDIM >::bsh_fit_ndim(), check(), check(), chunk_example(), ExactSpinor::compute_energy(), madness::KernelRange::Data::compute_iextent_x2(), compute_madelung_energy(), compute_madelung_energy_PWSCF(), diag_and_transform(), DF::diagonalize(), madness::distance(), MiniDFT::doit(), energy(), madness::SDFParaboloid::find_root(), ExactSpinor::Fvalue(), madness::gauss_legendre_numeric(), madness::gauss_legendre_test(), gen_ce(), madness::SDFParaboloid::get_roots(), madness::SeparatedConvolution< Q, NDIM >::getmuop(), madness::SeparatedConvolution< Q, NDIM >::getmuop_modified(), madness::QuasiNewton::hessian_update_bfgs(), madness::QuasiNewton::hessian_update_sr1(), initial_guess(), madness::FunctionImpl< T, NDIM >::inner_adaptive_recursive(), madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), is_like(), madness::Key< NDIM >::is_neighbor_of(), madness::Znemo::iterate(), madness::PNO::iterate_pairs_internal(), madness::CC2::iterate_singles(), madness::QuasiNewton::line_search(), main(), main(), main(), madness::Localizer::matrix_exponential(), madness::QuasiNewton::new_search_direction(), madness::MolecularOptimizer::new_search_direction2(), madness::detail::norm(), madness::CCPairFunction< T, NDIM >::norm2(), madness::SRConf< T >::normf(), madness::TensorTrain< T >::normf(), LProjector::operator()(), madness::WignerSeitzPotentialFunctor::operator()(), madness::BasisFunctions::SolidHarmonicGaussian::operator()(), LBCost::operator()(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::BoxSurfaceDisplacementValidator< NDIM >::operator()(), MatrixOperator::operator()(), madness::WorldAbsMaxOp< T >::operator()(), madness::WorldAbsMinOp< T >::operator()(), AtomicBasisSet::AnalysisSorter< T >::operator()(), madness::AtomicBasisSet::AnalysisSorter< T >::operator()(), BoysLocalization::operator()(), orth(), madness::ortho3(), madness::ortho5(), DF::orthogonalize_inplace(), madness::orthonormalize(), madness::NemoBase::orthonormalize(), madness::Zcis::orthonormalize(), orthonormalize(), madness::SCF::orthonormalize(), madness::SCF::orthonormalize(), periodic_sum_partial(), AtomicBasisSet::print_anal(), madness::AtomicBasisSet::print_anal(), print_stats(), print_stats(), madness::GFit< T, NDIM >::prune_small_coefficients(), ExactSpinor::psivalue(), read_test_data(), slymer::GaussianFunction::removeSmallTerms(), rk_v(), madness::GaussianConvolution1D< Q >::rnlp(), run_all_calculations(), madness::detail::adqtest::runtest(), madness::Tensor< T >::screen(), madness::SDFParaboloid::sdf(), madness::MP2::solve_coupled_equations(), madness::CC2::solve_mp2_coupled(), madness::MP2::solve_residual_equations(), su_complex(), tensor_approx_equal(), madness::BandlimitedPropagator::test(), test(), madness::TDHF::test(), Test5(), Test6(), Test7(), test_basic(), test_conv(), test_converged_function(), test_conversion(), test_coulomb(), test_G_R_vectors(), test_gence(), test_gence2(), madness::OptimizationTargetInterface::test_gradient(), madness::Diamagnetic_potential_factor::test_harmonic_potential(), test_integration(), test_kinetic(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_periodic_bsh(), madness::Solver< T, NDIM >::test_periodicity(), test_plot(), madness::Diamagnetic_potential_factor::test_scalar_potentials(), test_slater_exchange(), test_spherical_box(), test_swap_particles(), madness::Znemo::test_U_potentials(), test_vector_composite(), test_xcfunctional(), madness::Localizer::undo_reordering(), madness::KernelRange::value(), madness::SCF::vector_stats(), and madness::FunctionImpl< T, NDIM >::vtransform_doit().
advance()
template<typename hashT , typename distT > void std::advance (madness::Hash_private::HashIterator< hashT > & it, const distT & dist) inline
References madness::Hash_private::HashIterator< hashT >::advance(), and dist().
Referenced by madness::Range< iteratorT >::advance(), and madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >::store().
distance()
template<typename hashT > int std::distance (const madness::Hash_private::HashIterator< hashT > & it, const madness::Hash_private::HashIterator< hashT > & jt) inline
References madness::Hash_private::HashIterator< hashT >::distance().
Referenced by madness::Range< iteratorT >::distance(), madness::PNO::iterate_pairs_internal(), madness::TDHF::iterate_vectors(), madness::Group::Impl::rank(), madness::refine_to_common_level(), test_coverage(), and madness::PNO::update_pno().
hash_value()
madness::hashT std::hash_value (const madness::DistributedID & id) inline
Hash a DistributedID.
Parameters
[in] id The distributed ID to be hashed.
Returns
The hash value of id.
References madness::detail::combine_hash(), and madness::hash_value().
isnan()
template<typename T > bool std::isnan (const std::complex< T > & v)
References isnan(), MADNESS_PRAGMA_CLANG, and v.
Referenced by madness::XCfunctional::exc(), isnan(), Func< FLOAT >::operator()(), opt(), opt(), and madness::XCfunctional::vxc().