MADNESS: PNOTensors Namespace Reference
PNOTensors Namespace Reference
Classes
class Tensor_IJ_IK
class Tensor_IJ_KJ
Functions
template<typename Int >
size_t ntri (Int n)
template<typename Int >
size_t tridx (Int row, Int col)
index in packed lower triangle matrix, row >= col
Function Documentation
ntri()
template<typename Int > size_t PNOTensors::ntri (Int n)
of elements in lower triangle matrix
Referenced by madness::PNO::pno_compress().
tridx()
template<typename Int > size_t PNOTensors::tridx (Int row, Int col)
index in packed lower triangle matrix, row >= col
Referenced by PNOTensors::Tensor_IJ_IK< T >::ijk(), and PNOTensors::Tensor_IJ_KJ< T >::ijk().