MADNESS: navstokes_cosines.cc File Reference
navstokes_cosines.cc File Reference
Example Solving the Navier-Stokes equations.
#include <madness/mra/vmra.h>
#include <madness/constants.h>
Classes
struct FunctorInterfaceWrapper
Macros
#define myfun std::vector< Function<T,NDIM> >
Typedefs
typedef Vector< double, 3 > coordT
typedef Vector< double, 1 > coordT1d
typedef Vector< double, 3 > coordT3d
typedef Function< double, 3 > functionT
typedef std::vector< functionT > functT
Functions
template<typename T , int NDIM>
void adv (const myfun &uu, myfun &advu)
template<typename T , int NDIM>
static Function< T, NDIM > diff (const Function< T, NDIM > &f, int axis)
functionT div (const functT &uint)
static double fxexact (const coordT3d &r)
static double fyexact (const coordT3d &r)
static double fzexact (const coordT3d &r)
static double init_zero (const coordT3d &r)
functionT lap (const functionT &uint)
int main (int argc, char **argv)
template<typename T , int NDIM>
myfun operator- (const myfun &l, const myfun &r)
static double pexact (const coordT3d &r)
void testNavierStokes (int argc, char **argv)
static double uxexact (const coordT3d &r)
static double uyexact (const coordT3d &r)
static double uzexact (const coordT3d &r)
Variables
const double cc = 0
const double deltaT = pi*0.0001
const int k = 10
const double L = 2*pi
const double mu = 1
double mytime = 0.0
const double N = 8.0
const int Nts = L/deltaT+10
const double pi =madness::constants::pi
const double pthresh = 1.e-9
const double pthresh1 = 1e-10
World * pworld
const double uthresh = pthresh
const double uthresh1 = pthresh1
Detailed Description
Example Solving the Navier-Stokes equations.
Macro Definition Documentation
myfun
#define myfun std::vector< Function<T,NDIM> >
Typedef Documentation
coordT
typedef Vector<double, 3> coordT
coordT1d
typedef Vector<double, 1> coordT1d
coordT3d
typedef Vector<double, 3> coordT3d
functionT
typedef Function<double, 3> functionT
functT
typedef std::vector<functionT> functT
Function Documentation
adv()
template<typename T , int NDIM> void adv (const myfun & uu, myfun & advu)
References diff().
Referenced by testNavierStokes().
diff()
template<typename T , int NDIM> static Function<T,NDIM> diff (const Function< T, NDIM > & f, int axis) static
References axis, madness::f, and NDIM.
Referenced by adv(), madness::MP2::asymmetry(), madness::HartreeFock< T, NDIM >::calculate_ke_sp(), madness::DFT< T, NDIM >::calculate_ke_sp(), div(), eigenvector_test(), energy(), madness::exchange_anchor_test(), exchange_anchor_test(), iterate(), madness::Nemo::kinetic_energy_potential(), lap(), laplacian(), madness::MP2::make_Uphi0(), madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolver< T, NDIM >::print_matrix_elements(), madness::Nemo::purify_hessian(), madness::SDFRectangle::sdf(), madness::SDFCone::sdf(), madness::SDFParaboloid::sdf(), madness::SDFBox::sdf(), madness::EigSolver< T, NDIM >::solve(), madness::CC2::solve_cispd(), test(), madness::smooth< T, NDIM >::test_1d(), test_add(), test_convolution(), test_exchange(), test_load_store(), test_lowrank_function(), test_transformations(), and testNavierStokes().
div()
functionT div (const functT & uint) inline
References diff().
Referenced by madness::XCOperator< T, NDIM >::apply_xc_kernel(), and madness::Nuclear< double, 3 >::operator()().
fxexact()
static double fxexact (const coordT3d & r) static
References cc, mu, mytime, and pow().
Referenced by testNavierStokes().
fyexact()
static double fyexact (const coordT3d & r) static
References cc, mu, mytime, and pow().
Referenced by testNavierStokes().
fzexact()
static double fzexact (const coordT3d & r) static
References cc, mu, mytime, and pow().
Referenced by testNavierStokes().
init_zero()
static double init_zero (const coordT3d & r) static
lap()
functionT lap (const functionT & uint) inline
References diff().
Referenced by testNavierStokes().
main()
int main (int argc, char ** argv)
References testNavierStokes().
operator-()
template<typename T , int NDIM> myfun operator- (const myfun & l, const myfun & r) inline
References pworld, and madness::sub().
pexact()
static double pexact (const coordT3d & r) static
References cc, and mytime.
testNavierStokes()
void testNavierStokes (int argc, char ** argv)
References a, adv(), madness::apply(), b, madness::BC_PERIODIC, c, SafeMPI::COMM_WORLD, madness::CoulombOperator(), d(), deltaT, diff(), madness::div(), e(), madness::error(), madness::FunctionFactory< T, NDIM >::f(), madness::f, madness::filename, madness::finalize(), fxexact(), fyexact(), fzexact(), madness::gaxpy(), madness::FunctionDefaults< NDIM >::get_cell_width(), madness::initialize(), k, L, lap(), madness::Function< T, NDIM >::max_depth(), mu, mytime, madness::Function< T, NDIM >::norm2(), Nts, op(), p(), pi, madness::plotvtk_begin(), madness::plotvtk_data(), madness::print(), pthresh, pthresh1, pworld, madness::World::rank(), madness::scale(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), madness::FunctionFactory< T, NDIM >::truncate_on_project(), u(), uthresh1, uxexact(), uyexact(), and uzexact().
Referenced by main().
uxexact()
static double uxexact (const coordT3d & r) static
References cc, and mytime.
Referenced by testNavierStokes().
uyexact()
static double uyexact (const coordT3d & r) static
References cc, and mytime.
Referenced by testNavierStokes().
uzexact()
static double uzexact (const coordT3d & r) static
References cc, and mytime.
Referenced by testNavierStokes().
Variable Documentation
cc
const double cc = 0
Referenced by fxexact(), fyexact(), fzexact(), gradPbarA(), madness::FunctionImpl< T, NDIM >::inner_adaptive_recursive(), madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), main(), madness::FunctionImpl< T, NDIM >::multi_to_multi_op_values_doit(), madness::FunctionImpl< T, NDIM >::multiop_values_doit(), madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::operator()(), madness::FunctionImpl< T, NDIM >::do_mapdim::operator()(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), pexact(), madness::print_seq(), madness::Diamagnetic_potential_factor::test_factor(), test_general_transform(), test_tight_diffuse(), uxexact(), uyexact(), and uzexact().
deltaT
const double deltaT = pi*0.0001
Referenced by testNavierStokes().
k
const int k = 10
Referenced by testNavierStokes().
L
const double L = 2*pi
Referenced by testNavierStokes().
mu
const double mu = 1
Referenced by madness::GFit< T, NDIM >::GFit(), madness::FunctionCommonData< T, NDIM >::_init_quadrature(), apply_bsh(), apply_BSH(), apply_BSH_new(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), madness::GFit< T, NDIM >::bsh_spherical_moments(), madness::GFit< T, NDIM >::BSHFit(), madness::BSHOperator(), madness::BSHOperator3D(), madness::BSHOperatorPtr(), madness::BSHOperatorPtr3D(), madness::MolecularOptimizer::compute_reduced_mass(), compute_reduced_mass(), madness::SCF::dipole(), errsq(), madness::F2GOperator(), madness::F2GOperatorPtr(), madness::FGOperator(), madness::FGOperatorPtr(), fxexact(), fyexact(), fzexact(), madness::GaussOperator(), madness::GaussOperatorPtr(), gen_ce(), madness::GradBSHOperator(), GradBSHOperator_Joel(), madness::GradCoulombOperator(), gradPbarA(), madness::GradSlaterOperator(), madness::TwoElectronInterface< T, NDIM >::initialize(), madness::Localizer::localize_boys(), madness::Localizer::localize_new(), main(), madness::TwoElectronInterface< T, NDIM >::make_coeff(), make_grad_operator(), makedata(), nuclear_potential(), optimize_coeffs(), madness::PeriodicBSHOp(), madness::PeriodicBSHOperator3D(), madness::PeriodicBSHOperatorPtr3D(), madness::PeriodicBSHOpPtr(), madness::PM_q(), madness::SlaterF12Operator(), madness::SlaterF12OperatorPtr(), madness::SlaterF12sqOperator(), madness::SlaterF12sqOperatorPtr(), madness::SlaterOperator(), madness::SlaterOperatorPtr(), madness::SlaterOperatorPtr_ND(), sympgrad6(), test(), test_bsh(), test_combined_operators(), test_gence(), testbsh(), testNavierStokes(), and Fred::value_and_gradient().
mytime
double mytime = 0.0
Referenced by fxexact(), fyexact(), fzexact(), pexact(), testNavierStokes(), uxexact(), uyexact(), and uzexact().
N
const double N = 8.0
Nts
const int Nts = L/deltaT+10
Referenced by testNavierStokes().
pi
const double pi =madness::constants::pi
Referenced by MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), madness::HartreeFock< T, NDIM >::calculate_tot_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_ke_sp(), madness::DFT< T, NDIM >::calculate_tot_ke_sp(), madness::HartreeFock< T, NDIM >::calculate_tot_pe_sp(), madness::Nemo::compute_IR_intensities(), dfunc(), madness::detail::adqtest::exact(), func(), madness::gauss_legendre_numeric(), madness::DistributedMatrixDistribution::get_range(), madness::GradBSHOperator(), GradBSHOperator_Joel(), madness::GradCoulombOperator(), gradPbarA(), madness::GradSlaterOperator(), madness::SeparatedConvolution< Q, NDIM >::initialize(), main(), make_grad_operator(), madness::EigSolverOp< T, NDIM >::multi_op_o(), madness::EigSolverOp< T, NDIM >::multi_op_r(), madness::EigSolver< T, NDIM >::multi_solve(), CFFT::Perform(), madness::EigSolver< T, NDIM >::solve(), test(), test_in(), test_out(), madness::test_rnlp(), testNavierStokes(), and vector_to_PQ().
pthresh
const double pthresh = 1.e-9
Referenced by testNavierStokes().
pthresh1
const double pthresh1 = 1e-10
Referenced by testNavierStokes().
pworld
World* pworld
Referenced by operator-(), and testNavierStokes().
uthresh
const double uthresh = pthresh
uthresh1
const double uthresh1 = pthresh1
Referenced by testNavierStokes().