MADNESS: newsolver_lda.cc File Reference
newsolver_lda.cc File Reference
#include <type_traits>
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/nonlinsol.h>
#include <madness/mra/lbdeux.h>
#include <madness/mra/qmprop.h>
#include <madness/misc/misc.h>
#include <madness/misc/ran.h>
#include <madness/tensor/systolic.h>
#include <madness/tensor/solvers.h>
#include <madness/tensor/elem.h>
#include <madness/chem/xcfunctional.h>
#include <madness/mra/legendre.h>
Typedefs
typedef Function< std::complex< double >, 3 > complex_functionT
typedef Convolution1D< double_complex > complex_operatorT
typedef Vector< double, 3 > coordT
typedef std::vector< complex_functionT > cvecfuncT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::pair< vecfuncT, vecfuncT > pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef std::vector< functionT > vecfuncT
Functions
static double guess (const coord_3d &r)
double iterate_excite (World &world, NonlinearSolver &solver, functionT &V, functionT &psi, functionT &dpsi, double &eps, functionT &ri)
double iterate_ground (World &world, NonlinearSolver &solver, functionT &V, functionT &psi, double &eps)
int main (int argc, char **argv)
double make_dft_energy (World &world, const vecfuncT &vf, int ispin)
functionT make_dft_kernel (World &world, const vecfuncT &vf, int ispin, int what)
functionT make_dft_potential (World &world, const vecfuncT &vf, int ispin, int what)
double rifunction (const coord_3d &r)
static double V (const coord_3d &r)
Variables
std::vector< std::shared_ptr< real_derivative_3d > > gradop
static const long k = 8
static const double L = 50.0
static const int maxiter =10
static const int maxiterp =10
static const double thresh = 1e-5
XCfunctional xc
Typedef Documentation
complex_functionT
typedef Function<std::complex<double>,3> complex_functionT
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
coordT
typedef Vector<double,3> coordT
cvecfuncT
typedef std::vector<complex_functionT> cvecfuncT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pairvecfuncT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
subspaceT
typedef std::vector<pairvecfuncT> subspaceT
tensorT
typedef Tensor<double> tensorT
vecfuncT
typedef std::vector<functionT> vecfuncT
Function Documentation
guess()
static double guess (const coord_3d & r) static
References e().
Referenced by main().
iterate_excite()
double iterate_excite (World & world, NonlinearSolver & solver, functionT & V, functionT & psi, functionT & dpsi, double & eps, functionT & ri)
References madness::BSHOperator3D(), madness::CoulombOperator(), e(), madness::inner(), make_dft_kernel(), madness::Function< T, NDIM >::norm2(), op(), madness::constants::pi, psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), madness::NonlinearSolverND< NDIM >::update(), and V().
Referenced by main().
iterate_ground()
double iterate_ground (World & world, NonlinearSolver & solver, functionT & V, functionT & psi, double & eps)
References madness::BSHOperator3D(), e(), madness::inner(), madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), madness::NonlinearSolverND< NDIM >::update(), and V().
Referenced by main().
main()
int main (int argc, char ** argv)
References allocator(), axis, SafeMPI::COMM_WORLD, madness::CoulombOperator(), madness::CoulombOperatorPtr(), e(), e1(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, gradop, guess(), madness::XCfunctional::initialize(), madness::initialize(), madness::inner(), iterate_excite(), iterate_ground(), iterate_xy(), k, L, make_dft_energy(), make_dft_potential(), maxiter, maxiterp, omega, op(), madness::plot_line(), potential(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), rifunction(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), V(), and xc.
make_dft_energy()
double make_dft_energy (World & world, const vecfuncT & vf, int ispin)
References madness::Function< T, NDIM >::trace(), and xc.
Referenced by main().
make_dft_kernel()
functionT make_dft_kernel (World & world, const vecfuncT & vf, int ispin, int what)
References xc.
Referenced by iterate_excite().
make_dft_potential()
functionT make_dft_potential (World & world, const vecfuncT & vf, int ispin, int what)
References xc.
Referenced by main().
rifunction()
double rifunction (const coord_3d & r)
Referenced by main().
V()
static double V (const coord_3d & r) static
References e().
Referenced by iterate_excite(), iterate_ground(), and main().
Variable Documentation
gradop
std::vector< std::shared_ptr<real_derivative_3d> > gradop
Referenced by main().
k
const long k = 8 static
Referenced by main().
L
const double L = 50.0 static
Referenced by main().
maxiter
const int maxiter =10 static
Referenced by main().
maxiterp
const int maxiterp =10 static
Referenced by main().
thresh
const double thresh = 1e-5 static
Referenced by main().
xc
XCfunctional xc
Referenced by MiniDFT::MiniDFT(), madness::Solver< T, NDIM >::apply_hf_exchange3(), madness::Solver< T, NDIM >::apply_hf_exchange4(), madness::Solver< T, NDIM >::apply_potential(), WSTFunctional::apply_xc(), madness::XCOperator< T, NDIM >::apply_xc_kernel(), madness::bgq_mtxmq_padded(), madness::Coulomb< double, 3 >::compute_density(), madness::XCOperator< T, NDIM >::compute_xc_energy(), MiniDFT::doit(), GroundStateCalculation::get_archive(), madness::TDHF::get_tda_potential(), GroundStateCalculation::get_xc(), main(), madness::TDHF::make_cis_matrix(), make_dft_energy(), WSTFunctional::make_dft_energy(), make_dft_kernel(), make_dft_potential(), WSTFunctional::make_dft_potential(), mtxmq(), madness::Nuclear< double, 3 >::operator()(), madness::ParametrizedExchange::operator()(), madness::XCOperator< T, NDIM >::prep_xc_args(), madness::XCOperator< T, NDIM >::prep_xc_args_response(), GroundStateCalculation::print_params(), GroundStateCalculation::read(), madness::InitParameters::read(), madness::MolecularOrbitals< T, NDIM >::read_restartdata(), madness::MolecularOrbitals< T, NDIM >::save_restartdata(), madness::Nemo::solve_cphf(), test_slater_exchange(), and test_XCOperator().