MADNESS: newsolver.cc File Reference
newsolver.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/nonlinsol.h>
Classes
struct allocator
struct F
Functions
static double guess (const coord_3d &r)
double inner (const F &a, const F &b)
double iterate_excite (World &world, NonlinearSolver &solver, real_function_3d &V, real_function_3d &psi, real_function_3d &dpsi, double &eps, real_function_3d &ri)
double iterate_ground (World &world, NonlinearSolver &solver, real_function_3d &V, real_function_3d &psi, double &eps)
template<class solverT >
double iterate_xy (World &world, solverT &solver, const real_function_3d &V, const real_function_3d &psi, double &eps, const real_function_3d &ri, real_function_3d &x, real_function_3d &y, const double omega)
solve the dynamic response equations
int main (int argc, char **argv)
double rifunction (const coord_3d &r)
static double V (const coord_3d &r)
Variables
static const long k = 8
static const double L = 64.0*R
static const double R = 1.4
static const double thresh = 1e-5
Function Documentation
guess()
static double guess (const coord_3d & r) static
References e(), madness::nonlinear_vector_solver(), and R.
Referenced by main().
inner()
double inner (const F & a, const F & b)
References a, b, and madness::inner().
iterate_excite()
double iterate_excite (World & world, NonlinearSolver & solver, real_function_3d & V, real_function_3d & psi, real_function_3d & dpsi, double & eps, real_function_3d & ri)
References madness::BSHOperator3D(), madness::CoulombOperator(), e(), madness::nonlinear_vector_solver(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::truncate(), madness::NonlinearSolverND< NDIM >::update(), and V().
Referenced by main().
iterate_ground()
double iterate_ground (World & world, NonlinearSolver & solver, real_function_3d & V, real_function_3d & psi, double & eps)
References madness::BSHOperator3D(), e(), madness::inner(), madness::nonlinear_vector_solver(), norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), madness::NonlinearSolverND< NDIM >::update(), and V().
Referenced by main().
iterate_xy()
template<class solverT > double iterate_xy (World & world, solverT & solver, const real_function_3d & V, const real_function_3d & psi, double & eps, const real_function_3d & ri, real_function_3d & x, real_function_3d & y, const double omega)
solve the dynamic response equations
Parameters
[in] world the world
[in] solver the KAIN solver
[in] V the local potential (here: V_nuc + 1/2 J)
[in] psi the orbital
[in] eps orbital energy for psi
[in] ri the external perturbation (here: z)
[in,out] x the x part of the response vector
[in,out] y the y part of the response vector
[in] omega the frequency of the external perturbation
Returns
the current error in the residual of the response equations
References madness::BSHOperator3D(), madness::CoulombOperator(), e(), madness::inner(), madness::nonlinear_vector_solver(), madness::norm2(), omega, madness::print(), psi(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), and V().
Referenced by main().
main()
int main (int argc, char ** argv)
References axis, bufsize, SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), e1(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, guess(), madness::initialize(), madness::inner(), iterate_excite(), iterate_ground(), iterate_xy(), k, L, madness::nonlinear_vector_solver(), omega, op(), madness::plot_line(), potential(), madness::print(), psi(), R, madness::World::rank(), rifunction(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), and V().
rifunction()
double rifunction (const coord_3d & r)
Referenced by main().
V()
static double V (const coord_3d & r) static
References e(), madness::nonlinear_vector_solver(), and R.
Referenced by iterate_excite(), iterate_ground(), iterate_xy(), and main().
Variable Documentation
k
const long k = 8 static
Referenced by main().
L
const double L = 64.0*R static
Referenced by main().
R
const double R = 1.4 static
Referenced by guess(), main(), and V().
thresh
const double thresh = 1e-5 static
Referenced by main().