MADNESS: plot2plane.cpp File Reference
plot2plane.cpp File Reference
#include <madness/mra/mra.h>
#include <madness/mra/funcplot.h>
#include "madness/mra/commandlineparser.h"
#include <madness/chem/CalculationParameters.h>
#include <madness/chem/molecule.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References aobasis, madness::Molecule::bounding_cube(), SafeMPI::COMM_WORLD, madness::f, madness::QCCalculationParametersBase::file_exists(), madness::filename, madness::initialize(), madness::commandlineparser::key_exists(), L, madness::load(), molecule, madness::Molecule::orient(), madness::plot_plane(), madness::World::rank(), madness::Molecule::read_file(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::CalculationParameters::set_derived_values(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and madness::commandlineparser::value().