MADNESS: plot2cube.cpp File Reference
plot2cube.cpp File Reference
#include <madness/mra/mra.h>
#include <madness/mra/funcplot.h>
#include "madness/mra/commandlineparser.h"
#include <madness/chem/CalculationParameters.h>
#include <madness/chem/molecule.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References aobasis, madness::Molecule::cubefile_header(), madness::f, madness::filename, madness::finalize(), madness::initialize(), madness::commandlineparser::key_exists(), InputParameters::L, madness::load(), molecule, madness::PlotParameters::npoints(), madness::PlotParameters::origin(), param, madness::QCCalculationParametersBase::print(), madness::Molecule::print(), madness::print_header2(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::commandlineparser::split(), madness::startup(), madness::commandlineparser::value(), and madness::PlotParameters::zoom().