MADNESS: pno.cpp File Reference
pno.cpp File Reference
#include <iomanip>
#include <madness/chem/SCF.h>
#include <madness/chem/nemo.h>
#include <madness/chem/PNO.h>
#include <madness/misc/info.h>
Functions
int main (int argc, char **argv)
Variables
const std::string TAG_CP = "computeprotocol"
const std::string TAG_F12 = "f12"
const std::string TAG_PNO = "pno"
Function Documentation
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::PNO::get_average_rank(), madness::Nemo::get_calc(), madness::World::gop, madness::PNO::help(), madness::initialize(), madness::commandlineparser::key_exists(), madness::MP2_PAIRTYPE, madness::print(), madness::print_header1(), madness::PNO::print_parameters(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), madness::PNO::solve(), madness::startup(), TAG_F12, TAG_PNO, madness::Nemo::value(), and madness::wall_time().
Variable Documentation
TAG_CP
const std::string TAG_CP = "computeprotocol"
TAG_F12
const std::string TAG_F12 = "f12"
Referenced by main().
TAG_PNO
const std::string TAG_PNO = "pno"
Referenced by main().