MADNESS: posixmem.h File Reference
posixmem.h File Reference
Implement dummy posix_memalign if it is missing on the system.
#include <madness/madness_config.h>
#include <sys/errno.h>
Functions
int posix_memalign (void **memptr, std::size_t alignment, std::size_t size)
Detailed Description
Implement dummy posix_memalign if it is missing on the system.
Function Documentation
posix_memalign()
int posix_memalign (void ** memptr, std::size_t alignment, std::size_t size) inline
References malloc().
Referenced by madness::RMI::RmiTask::RmiTask(), madness::Tensor< T >::allocate(), madness::bgq_mtxmq_padded(), madness::bgq_mtxmq_padded(), madness::bgq_mtxmq_padded(), madness::bgq_mtxmq_padded(), madness::WorldGopInterface::concat0(), main(), main(), madness::RMI::RmiTask::post_pending_huge_msg(), and madness::WorldGopInterface::reduce().