MADNESS: qcschema_json_testing.cpp File Reference
qcschema_json_testing.cpp File Reference
#include "madness/external/catch/catch.hpp"
#include "madness/tensor/tensor_json.hpp"
#include "response_functions.h"
#include "response_parameters.h"
#include "string"
#include "timer.h"
#include "x_space.h"
Functions
unsigned int Factorial (unsigned int number)
template<typename T >
bool operator== (const madness::Tensor< T > &a, const madness::Tensor< T > &b)
TEST_CASE ("Json Testing 2", "Serialization")
TEST_CASE ("Json Testing 3", "Json Tensor Indexing")
TEST_CASE ("Json Testing", "Simple JSON")
TEST_CASE ("print_QCSchema Test ", "Json Tensor Indexing")
TEST_CASE ("Response Parameters Test ", "Testing parameters to_json")
TEST_CASE ("X_space", "[copy]")
Function Documentation
Factorial()
unsigned int Factorial (unsigned int number)
References Factorial().
Referenced by Factorial().
operator==()
template<typename T > bool operator== (const madness::Tensor< T > & a, const madness::Tensor< T > & b)
References a, and b.
TEST_CASE() [1/6]
TEST_CASE ("Json Testing 2" , "Serialization")
References a, b, and c.
TEST_CASE() [2/6]
TEST_CASE ("Json Testing 3" , "Json Tensor Indexing")
References a, b, and c.
TEST_CASE() [3/6]
TEST_CASE ("Json Testing" , "Simple JSON")
TEST_CASE() [4/6]
TEST_CASE ("print_QCSchema Test " , "Json Tensor Indexing")
References madness::to_json().
TEST_CASE() [5/6]
TEST_CASE ("Response Parameters Test " , "Testing parameters to_json")
References SafeMPI::COMM_WORLD, molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, madness::initialize(), molresponse::start_timer(), madness::startup(), and madness::QCCalculationParametersBase::to_json().
TEST_CASE() [6/6]
TEST_CASE ("X_space" , "" [copy])
References SafeMPI::COMM_WORLD, molresponse::end_timer(), madness::finalize(), madness::initialize(), m, molresponse::start_timer(), madness::startup(), and v.