MADNESS: sdf_shape_tester.cc File Reference
sdf_shape_tester.cc File Reference
Demonstrates/tests use of 3D shape functions.
#include <madness/mra/mra.h>
#include <madness/mra/sdf_shape_3D.h>
#include <madness/constants.h>
Functions
int main (int argc, char **argv)
Detailed Description
Demonstrates/tests use of 3D shape functions.
Function Documentation
main()
int main (int argc, char ** argv)
References c, SafeMPI::COMM_WORLD, e(), epsilon, madness::f, madness::finalize(), madness::initialize(), L, madness::constants::pi, madness::plotdx(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::DomainMaskSDFFunctor< NDIM >::setMaskFunction(), madness::startup(), and madness::vec().