MADNESS: simple_hf.cpp File Reference
simple_hf.cpp File Reference
#include <madness.h>
#include <madchem.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References madness::_(), aobasis, madness::dot(), e(), energy, madness::finalize(), madness::initialize(), K(), lo, madness::matrix_inner(), maxiter, molecule, madness::norm2(), madness::Molecule::nuclear_repulsion_energy(), madness::orthonormalize(), madness::Molecule::print(), madness::SCF::project_ao_basis_only(), residual(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::World::size(), madness::startup(), madness::sygv(), T(), madness::Molecule::total_nuclear_charge(), madness::transform(), madness::truncate(), V(), and madness::wall_time().