MADNESS: solver_driver.cc File Reference
solver_driver.cc File Reference
#include "electronicstructureapp.h"
#include "solver.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::Solver< T, NDIM >::solve(), and madness::startup().