MADNESS: madness::abs_square_op< Q, NDIM > Struct Template Reference
madness::abs_square_op< Q, NDIM > Struct Template Reference
#include <complexfun.h>
Public Types
typedef TensorTypeData< Q >::scalar_type resultT
Public Member Functions
Tensor< resultT > operator() (const Key< NDIM > &key, const Tensor< Q > &t) const
template<typename Archive >
void serialize (Archive &ar)
Member Typedef Documentation
resultT
template<typename Q , int NDIM> typedef TensorTypeData<Q>::scalar_type madness::abs_square_op< Q, NDIM >::resultT
Member Function Documentation
operator()()
template<typename Q , int NDIM> Tensor< resultT > madness::abs_square_op< Q, NDIM >::operator() (const Key< NDIM > & key, const Tensor< Q > & t) const inline
References madness::abs(), BINARY_OPTIMIZED_ITERATOR, d, madness::BaseTensor::dims(), madness::BaseTensor::ndim(), and Q().
serialize()
template<typename Q , int NDIM> template<typename Archive > void madness::abs_square_op< Q, NDIM >::serialize (Archive & ar) inline
The documentation for this struct was generated from the following file:
complexfun.h