MADNESS: madness::FunctionImpl< T, NDIM >::do_change_tensor_type Struct Reference
madness::FunctionImpl< T, NDIM >::do_change_tensor_type Struct Reference
change representation of nodes' coeffs to low rank, optional fence
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::iterator > rangeT
Public Member Functions
do_change_tensor_type ()=default
do_change_tensor_type (const TensorArgs &targs, implT &g)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * f
TensorArgs targs
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_change_tensor_type
change representation of nodes' coeffs to low rank, optional fence
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_change_tensor_type::rangeT
Constructor & Destructor Documentation
do_change_tensor_type() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_change_tensor_type::do_change_tensor_type () default
do_change_tensor_type() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_change_tensor_type::do_change_tensor_type (const TensorArgs & targs, implT & g) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_change_tensor_type::operator() (typename rangeT::iterator & it) const inline
References madness::Timer::accumulate(), madness::change_tensor_type(), madness::FunctionNode< T, NDIM >::coeff(), madness::cpu_time(), madness::FunctionImpl< T, NDIM >::do_change_tensor_type::f, madness::FunctionImpl< T, NDIM >::do_change_tensor_type::targs, and madness::FunctionImpl< T, NDIM >::timer_change_tensor_type.
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_change_tensor_type::serialize (const Archive & ar) inline
Member Data Documentation
f
template<typename T , std::size_t NDIM> implT* madness::FunctionImpl< T, NDIM >::do_change_tensor_type::f
Referenced by madness::FunctionImpl< T, NDIM >::do_change_tensor_type::operator()().
targs
template<typename T , std::size_t NDIM> TensorArgs madness::FunctionImpl< T, NDIM >::do_change_tensor_type::targs
Referenced by madness::FunctionImpl< T, NDIM >::do_change_tensor_type::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h