MADNESS: madness::TDHF::TDHFParameters Struct Reference
madness::TDHF::TDHFParameters Struct Reference
the TDHF parameter class
#include <TDHF.h>
Public Member Functions
TDHFParameters ()
TDHFParameters (const TDHFParameters &other)=default
TDHFParameters (World &world, const commandlineparser &parser)
todo: read_from_file compatible with dist. memory computation
double damping_width () const
double dconv () const
bool debug () const
bool do_oep () const
double econv () const
std::vector< size_t > excitations () const
std::vector< std::string > exops () const
long freeze () const
CCConvolutionOperator< double, 3 >::Parameters get_ccc_parameters (const double lo) const
make parameters for convolution operator
double guess_cm () const
double guess_dconv () const
bool guess_diag () const
double guess_econv () const
std::string guess_excitation_operators () const
std::size_t guess_excitations () const
std::size_t guess_maxiter () const
void initialize_all ()
std::string irrep () const
std::size_t iterating_excitations () const
std::size_t kain_subspace () const
std::size_t maxiter () const
std::size_t nexcitations () const
bool no_compute () const
bool plot () const
int print_level () const
std::string response_kernel () const
std::string restart () const
void set_derived_values (const std::shared_ptr< SCF > &scf)
auto assigns all parameters which where not explicitly given and which depend on other parameters of the reference calculation
bool store_potential () const
double thresh () const
bool triplet () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool operator== (const QCCalculationParametersBase &other) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
void to_json (json &j) const
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys =true
bool ignore_unknown_keys_silently =false
ParameterContainerT parameters
bool print_debug =false
bool throw_if_datagroup_not_found =true
Detailed Description
the TDHF parameter class
Constructor & Destructor Documentation
TDHFParameters() [1/3]
madness::TDHF::TDHFParameters::TDHFParameters () inline
References initialize_all().
TDHFParameters() [2/3]
madness::TDHF::TDHFParameters::TDHFParameters (const TDHFParameters & other) default
TDHFParameters() [3/3]
madness::TDHF::TDHFParameters::TDHFParameters (World & world, const commandlineparser & parser) inline
todo: read_from_file compatible with dist. memory computation
References initialize_all(), madness::QCCalculationParametersBase::read_input_and_commandline_options(), and madness::TDHF::world.
Member Function Documentation
damping_width()
double madness::TDHF::TDHFParameters::damping_width () const inline
References madness::nonlinear_vector_solver().
dconv()
double madness::TDHF::TDHFParameters::dconv () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_cis_final_vectors(), set_derived_values(), and madness::TDHF::solve_cis().
debug()
bool madness::TDHF::TDHFParameters::debug () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::apply_G(), madness::TDHF::canonicalize(), madness::TDHF::get_tda_potential(), madness::TDHF::initialize(), madness::TDHF::make_bra(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_overlap_matrix(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_potentials(), madness::TDHF::make_virtuals(), and madness::TDHF::orthonormalize().
do_oep()
bool madness::TDHF::TDHFParameters::do_oep () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::TDHF(), madness::TDHF::get_tda_potential(), madness::TDHF::make_cis_matrix(), madness::TDHF::prepare_calculation(), and set_derived_values().
econv()
double madness::TDHF::TDHFParameters::econv () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_cis_final_vectors(), set_derived_values(), and madness::TDHF::solve_cis().
excitations()
std::vector< size_t > madness::TDHF::TDHFParameters::excitations () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::solve_cis().
exops()
std::vector< std::string > madness::TDHF::TDHFParameters::exops () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::apply_excitation_operators().
freeze()
long madness::TDHF::TDHFParameters::freeze () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::analyze(), madness::TDHF::apply_G(), madness::TDHF::get_active_mo_bra(), madness::TDHF::get_active_mo_ket(), get_ccc_parameters(), madness::TDHF::iterate_vectors(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::prepare_calculation(), madness::TDHF::print_frozen_orbitals(), madness::TDHF::symmetrize(), and madness::TDHF::transform().
get_ccc_parameters()
CCConvolutionOperator< double, 3 >::Parameters madness::TDHF::TDHFParameters::get_ccc_parameters (const double lo) const inline
make parameters for convolution operator
References madness::CCConvolutionOperator< T, NDIM >::Parameters::freeze, freeze(), madness::CCConvolutionOperator< T, NDIM >::Parameters::gamma, lo, madness::CCConvolutionOperator< T, NDIM >::Parameters::lo, thresh(), and madness::CCConvolutionOperator< T, NDIM >::Parameters::thresh_op.
Referenced by madness::TDHF::initialize().
guess_cm()
double madness::TDHF::TDHFParameters::guess_cm () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::make_virtuals().
guess_dconv()
double madness::TDHF::TDHFParameters::guess_dconv () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_cis_guess_vectors().
guess_diag()
bool madness::TDHF::TDHFParameters::guess_diag () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::make_cis_matrix().
guess_econv()
double madness::TDHF::TDHFParameters::guess_econv () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_cis_guess_vectors().
guess_excitation_operators()
std::string madness::TDHF::TDHFParameters::guess_excitation_operators () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::apply_excitation_operators(), and madness::TDHF::make_virtuals().
guess_excitations()
std::size_t madness::TDHF::TDHFParameters::guess_excitations () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::initialize(), madness::TDHF::make_guess_from_initial_diagonalization(), and madness::TDHF::solve_cis().
guess_maxiter()
std::size_t madness::TDHF::TDHFParameters::guess_maxiter () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::initialize(), and madness::TDHF::iterate_cis_guess_vectors().
initialize_all()
void madness::TDHF::TDHFParameters::initialize_all () inline
add center of mass functions determined by the homo-energy will add s,px,py,pz functions in the center of mass with exponent: -(e_homo/c) and c=guess_cm is the value of this parameter
use the diagonal approximation for the guess (only e_a -e_i terms in CIS matrix) much faster
determine active orbitals in guess (for all inactive orbitals only the diagonal e_a-e_i term is computed in the guess guess_active_orbitals=0 is the same as guess_diag
Vector of strings which contains the polynomial excitation operators For this to be used the tda_guess key has to be "custom" The strings are given in a format like: "c c1 x x1 y y1 z z1, c c2 x x2 y y2 z z2, ..." which will be interpreted as: c1*x^x1*y^y1*z^z1 + c2*x^x2*y^y2*z^z2 + ....
References madness::nonlinear_vector_solver().
Referenced by TDHFParameters(), and TDHFParameters().
irrep()
std::string madness::TDHF::TDHFParameters::irrep () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::check_consistency(), and madness::TDHF::make_guess_from_initial_diagonalization().
iterating_excitations()
std::size_t madness::TDHF::TDHFParameters::iterating_excitations () const inline
References madness::nonlinear_vector_solver().
Referenced by set_derived_values(), and madness::TDHF::solve_cis().
kain_subspace()
std::size_t madness::TDHF::TDHFParameters::kain_subspace () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_cis_final_vectors(), and madness::TDHF::iterate_vectors().
maxiter()
std::size_t madness::TDHF::TDHFParameters::maxiter () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_cis_final_vectors().
nexcitations()
std::size_t madness::TDHF::TDHFParameters::nexcitations () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_vectors(), set_derived_values(), madness::TDHF::solve_cis(), and madness::TDHF::solve_cis().
no_compute()
bool madness::TDHF::TDHFParameters::no_compute () const inline
References restart().
Referenced by madness::TDHF::prepare_calculation().
plot()
bool madness::TDHF::TDHFParameters::plot () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::get_tda_potential(), madness::TDHF::iterate_vectors(), and madness::TDHF::plot().
print_level()
int madness::TDHF::TDHFParameters::print_level () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::print_frozen_orbitals(), and madness::TDHF::solve_cis().
response_kernel()
std::string madness::TDHF::TDHFParameters::response_kernel () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::get_tda_potential().
restart()
std::string madness::TDHF::TDHFParameters::restart () const inline
References madness::nonlinear_vector_solver().
Referenced by no_compute(), and madness::TDHF::solve_cis().
set_derived_values()
void madness::TDHF::TDHFParameters::set_derived_values (const std::shared_ptr< SCF > & scf)
auto assigns all parameters which where not explicitly given and which depend on other parameters of the reference calculation
References dconv(), do_oep(), econv(), iterating_excitations(), nexcitations(), madness::nonlinear_vector_solver(), and madness::QCCalculationParametersBase::set_derived_value().
Referenced by madness::TDHF::TDHF().
store_potential()
bool madness::TDHF::TDHFParameters::store_potential () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::iterate_vectors().
thresh()
double madness::TDHF::TDHFParameters::thresh () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::apply_G(), get_ccc_parameters(), madness::TDHF::initialize(), madness::TDHF::iterate_vectors(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_mo_bra(), madness::TDHF::make_mo_ket(), and madness::TDHF::orthonormalize().
triplet()
bool madness::TDHF::TDHFParameters::triplet () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::TDHF::get_tda_potential().
The documentation for this struct was generated from the following files:
TDHF.h
TDHF.cc