MADNESS: madness::GenericConvolution1D< Q, opT >::Shmoo Struct Reference
madness::GenericConvolution1D< Q, opT >::Shmoo Struct Reference
#include <convolution1d.h>
Public Types
typedef Tensor< Q > returnT
Public Member Functions
Shmoo (Level n, Translation lx, const GenericConvolution1D< Q, opT > *q)
returnT operator() (double x) const
Public Attributes
Translation lx
Level n
const GenericConvolution1D< Q, opT > & q
Member Typedef Documentation
returnT
template<typename Q , typename opT > typedef Tensor<Q> madness::GenericConvolution1D< Q, opT >::Shmoo::returnT
Constructor & Destructor Documentation
Shmoo()
template<typename Q , typename opT > madness::GenericConvolution1D< Q, opT >::Shmoo::Shmoo (Level n, Translation lx, const GenericConvolution1D< Q, opT > * q) inline
Member Function Documentation
operator()()
template<typename Q , typename opT > returnT madness::GenericConvolution1D< Q, opT >::Shmoo::operator() (double x) const inline
References madness::f, madness::legendre_scaling_functions(), madness::GenericConvolution1D< Q, opT >::Shmoo::lx, madness::MAXK, madness::GenericConvolution1D< Q, opT >::Shmoo::n, p(), Q(), madness::GenericConvolution1D< Q, opT >::Shmoo::q, and v.
Member Data Documentation
lx
template<typename Q , typename opT > Translation madness::GenericConvolution1D< Q, opT >::Shmoo::lx
Referenced by madness::GenericConvolution1D< Q, opT >::Shmoo::operator()().
n
template<typename Q , typename opT > Level madness::GenericConvolution1D< Q, opT >::Shmoo::n
Referenced by madness::GenericConvolution1D< Q, opT >::Shmoo::operator()().
q
template<typename Q , typename opT > const GenericConvolution1D<Q,opT>& madness::GenericConvolution1D< Q, opT >::Shmoo::q
Referenced by madness::GenericConvolution1D< Q, opT >::Shmoo::operator()().
The documentation for this struct was generated from the following file:
convolution1d.h