MADNESS: madness::FunctionImpl< T, NDIM >::do_check_symmetry_local Struct Reference
madness::FunctionImpl< T, NDIM >::do_check_symmetry_local Struct Reference
check symmetry wrt particle exchange
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::const_iterator > rangeT
Public Member Functions
do_check_symmetry_local ()
do_check_symmetry_local (const implT &f)
double operator() (double a, double b) const
double operator() (typename rangeT::iterator &it) const
return the norm of the difference of this node and its "mirror" node
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
const implT * f
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_check_symmetry_local
check symmetry wrt particle exchange
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::const_iterator> madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::rangeT
Constructor & Destructor Documentation
do_check_symmetry_local() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::do_check_symmetry_local () inline
do_check_symmetry_local() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::do_check_symmetry_local (const implT & f) inline
Member Function Documentation
operator()() [1/2]
template<typename T , std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator() (double a, double b) const inline
References a, and b.
operator()() [2/2]
template<typename T , std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator() (typename rangeT::iterator & it) const inline
return the norm of the difference of this node and its "mirror" node
References madness::FunctionNode< T, NDIM >::coeff(), madness::copy(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::f, madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::GenTensor< T >::full_tensor_copy(), madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::FunctionNode< T, NDIM >::has_children(), madness::GenTensor< T >::has_data(), madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), madness::Tensor< T >::mapdim(), NDIM, madness::detail::norm(), madness::GenTensor< T >::normf(), madness::Tensor< T >::normf(), madness::WorldContainer< keyT, valueT, hashfunT >::probe(), madness::World::size(), madness::Key< NDIM >::translation(), and madness::FunctionImpl< T, NDIM >::world.
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
Member Data Documentation
f
template<typename T , std::size_t NDIM> const implT* madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::f
Referenced by madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h