MADNESS: madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler > Struct Template Reference
madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler > Struct Template Reference
#include <world_object.h>
Public Types
typedef std::conditional< memfunc_traits< memfnT >::constness, constobjT *, objT * >::type ptrT
typedef MemFuncWrapper< ptrT, memfnT, typename result_of< memfnT >::type > wrapperT
Static Public Member Functions
static wrapperT make_task_fn (const objT *obj, memfnT memfn)
static wrapperT make_task_fn (const WorldObject< objT > *obj, memfnT memfn)
static wrapperT make_task_fn (objT *obj, memfnT memfn)
static wrapperT make_task_fn (WorldObject< objT > *obj, memfnT memfn)
Detailed Description
template<typename objT, typename memfnT, typename Enabler = void>
struct madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >
Todo:
Brief description needed.
Todo:
Descriptions needed.
Template Parameters
objT Description needed.
memfnT Verify: Signature of the member function in the derived class to be invoked for the task.
Enabler Description needed.
Member Typedef Documentation
ptrT
template<typename objT , typename memfnT , typename Enabler = void> typedef std::conditional<memfunc_traits<memfnT>::constness,constobjT*,objT*>::type madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::ptrT
Todo:
Description needed.
wrapperT
template<typename objT , typename memfnT , typename Enabler = void> typedef MemFuncWrapper<ptrT, memfnT, typename result_of<memfnT>::type> madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::wrapperT
Todo:
Description needed.
Member Function Documentation
make_task_fn() [1/4]
template<typename objT , typename memfnT , typename Enabler = void> static wrapperT madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn (const objT * obj, memfnT memfn) inline static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in] obj Description needed.
memfn Verify: The member function to be invoked for the task.
Returns
Description needed.
Referenced by madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn(), madness::detail::WorldObjectTaskHelper< objT, memfnT, typename std::enable_if< std::is_base_of< std::enable_shared_from_this< objT >, objT >::value >::type >::make_task_fn(), madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn(), and madness::detail::WorldObjectTaskHelper< objT, memfnT, typename std::enable_if< std::is_base_of< std::enable_shared_from_this< objT >, objT >::value >::type >::make_task_fn().
make_task_fn() [2/4]
template<typename objT , typename memfnT , typename Enabler = void> static wrapperT madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn (const WorldObject< objT > * obj, memfnT memfn) inline static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in] obj Description needed.
memfn Verify: The member function to be invoked for the task.
Returns
Description needed.
References madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn().
make_task_fn() [3/4]
template<typename objT , typename memfnT , typename Enabler = void> static wrapperT madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn (objT * obj, memfnT memfn) inline static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in] obj Description needed.
memfn Verify: The member function to be invoked for the task.
Returns
Description needed.
make_task_fn() [4/4]
template<typename objT , typename memfnT , typename Enabler = void> static wrapperT madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn (WorldObject< objT > * obj, memfnT memfn) inline static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in] obj Description needed.
memfn Verify: The member function to be invoked for the task.
Returns
Description needed.
References madness::detail::WorldObjectTaskHelper< objT, memfnT, Enabler >::make_task_fn().
The documentation for this struct was generated from the following file:
world_object.h