MADNESS: madness::archive::ArchiveSerializeImpl< Archive, resT(objT::*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(objT::*)(paramT...)> > > Struct Template Reference
madness::archive::ArchiveSerializeImpl< Archive, resT(objT::*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(objT::*)(paramT...)> > > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Serialize a member function pointer.
#include <archive.h>
Static Public Member Functions
template<typename A = Archive, typename = std::enable_if_t<is_output_archive<A>::value>>
static void serialize (const A &ar, resT(objT::*(&memfn))(paramT...))
Serialize the member function pointer.
template<typename A = Archive>
static std::enable_if_t<!is_output_archive< A >::value, void > serialize (const A &ar, resT(objT::*(&memfn))(paramT...))
Detailed Description
template<class Archive, typename resT, typename objT, typename... paramT>
struct madness::archive::ArchiveSerializeImpl< Archive, resT(objT::*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(objT::*)(paramT...)> > >
Serialize a member function pointer.
Template Parameters
Archive The archive type.
resT The member function's return type.
objT The object type.
paramT Parameter pack for the member function's arguments.
Member Function Documentation
serialize() [1/2]
template<class Archive , typename resT , typename objT , typename... paramT> template<typename A = Archive, typename = std::enable_if_t<is_output_archive<A>::value>> static void madness::archive::ArchiveSerializeImpl< Archive, resT(objT::*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(objT::*)(paramT...)> > >::serialize (const A & ar, resT(objT::*(&memfn))(paramT...)) inline static
Serialize the member function pointer.
Parameters
[in] ar The archive.
[in] memfn The member function pointer.
References madness::archive::to_rel_memfn_ptr(), and madness::archive::wrap_opaque().
serialize() [2/2]
template<class Archive , typename resT , typename objT , typename... paramT> template<typename A = Archive> static std::enable_if_t<!is_output_archive< A >::value, void > madness::archive::ArchiveSerializeImpl< Archive, resT(objT::*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(objT::*)(paramT...)> > >::serialize (const A & ar, resT(objT::*(&memfn))(paramT...)) inline static
References madness::archive::to_rel_memfn_ptr(), and madness::archive::wrap_opaque().
The documentation for this struct was generated from the following file:
archive.h