MADNESS: madness::SolverTargetInterface Struct Reference
madness::SolverTargetInterface Struct Reference abstract
The interface to be provided by targets for non-linear equation solver.
#include <solvers.h>
Public Member Functions
virtual ~SolverTargetInterface ()
virtual Tensor< double > jacobian (const Tensor< double > &x)
Some solvers require the jacobian or are faster if an analytic form is available.
virtual bool provides_jacobian () const
Override this to return true if the Jacobian is implemented.
virtual Tensor< double > residual (const Tensor< double > &x)=0
Should return the resdiual (vector F(x))
virtual void residual_and_jacobian (const Tensor< double > &x, Tensor< double > &residual, Tensor< double > &jacobian)
Implement this if advantageous to compute residual and jacobian simultaneously.
Detailed Description
The interface to be provided by targets for non-linear equation solver.
Constructor & Destructor Documentation
~SolverTargetInterface()
virtual madness::SolverTargetInterface::~SolverTargetInterface () inline virtual
Member Function Documentation
jacobian()
virtual Tensor< double > madness::SolverTargetInterface::jacobian (const Tensor< double > & x) inline virtual
Some solvers require the jacobian or are faster if an analytic form is available.
J(i,j) = partial F[i] over partial x[j] where F(x) is the vector valued residual
Referenced by residual_and_jacobian().
provides_jacobian()
virtual bool madness::SolverTargetInterface::provides_jacobian () const inline virtual
Override this to return true if the Jacobian is implemented.
residual()
virtual Tensor< double > madness::SolverTargetInterface::residual (const Tensor< double > & x) pure virtual
Should return the resdiual (vector F(x))
Referenced by residual_and_jacobian().
residual_and_jacobian()
virtual void madness::SolverTargetInterface::residual_and_jacobian (const Tensor< double > & x, Tensor< double > & residual, Tensor< double > & jacobian) inline virtual
Implement this if advantageous to compute residual and jacobian simultaneously.
References jacobian(), and residual().
The documentation for this struct was generated from the following file:
solvers.h