MADNESS: madness::insert_op< T, NDIM > Struct Template Reference
madness::insert_op< T, NDIM > Struct Template Reference
insert/replaces the coefficients into the function
#include <funcimpl.h>
Public Types
typedef GenTensor< T > coeffT
typedef FunctionImpl< T, NDIM > implT
typedef Key< NDIM > keyT
typedef FunctionNode< T, NDIM > nodeT
Public Member Functions
insert_op ()
insert_op (const insert_op &other)
insert_op (implT *f)
void operator() (const keyT &key, const coeffT &coeff, const bool &is_leaf) const
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
implT * impl
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::insert_op< T, NDIM >
insert/replaces the coefficients into the function
Member Typedef Documentation
coeffT
template<typename T , std::size_t NDIM> typedef GenTensor<T> madness::insert_op< T, NDIM >::coeffT
implT
template<typename T , std::size_t NDIM> typedef FunctionImpl<T,NDIM> madness::insert_op< T, NDIM >::implT
keyT
template<typename T , std::size_t NDIM> typedef Key<NDIM> madness::insert_op< T, NDIM >::keyT
nodeT
template<typename T , std::size_t NDIM> typedef FunctionNode<T,NDIM> madness::insert_op< T, NDIM >::nodeT
Constructor & Destructor Documentation
insert_op() [1/3]
template<typename T , std::size_t NDIM> madness::insert_op< T, NDIM >::insert_op () inline
insert_op() [2/3]
template<typename T , std::size_t NDIM> madness::insert_op< T, NDIM >::insert_op (implT * f) inline
insert_op() [3/3]
template<typename T , std::size_t NDIM> madness::insert_op< T, NDIM >::insert_op (const insert_op< T, NDIM > & other) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> void madness::insert_op< T, NDIM >::operator() (const keyT & key, const coeffT & coeff, const bool & is_leaf) const inline
References madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::insert_op< T, NDIM >::impl, madness::WorldContainer< keyT, valueT, hashfunT >::is_local(), MADNESS_ASSERT, and madness::WorldContainer< keyT, valueT, hashfunT >::replace().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::insert_op< T, NDIM >::serialize (Archive & ar) inline
References madness::insert_op< T, NDIM >::impl.
Member Data Documentation
impl
template<typename T , std::size_t NDIM> implT* madness::insert_op< T, NDIM >::impl
Referenced by madness::insert_op< T, NDIM >::operator()(), and madness::insert_op< T, NDIM >::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h