MADNESS: madness::archive::ArchiveStoreImpl< Archive, Tensor< T > > Struct Template Reference
madness::archive::ArchiveStoreImpl< Archive, Tensor< T > > Struct Template Reference
Serialize a tensor.
#include <tensor.h>
Static Public Member Functions
static void store (const Archive &s, const Tensor< T > &t)
Detailed Description
template<class Archive, typename T>
struct madness::archive::ArchiveStoreImpl< Archive, Tensor< T > >
Serialize a tensor.
Member Function Documentation
store()
template<class Archive , typename T > static void madness::archive::ArchiveStoreImpl< Archive, Tensor< T > >::store (const Archive & s, const Tensor< T > & t) inline static
References madness::copy(), madness::BaseTensor::dims(), madness::BaseTensor::id(), madness::BaseTensor::iscontiguous(), madness::BaseTensor::ndim(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), TENSOR_MAXDIM, and madness::archive::wrap().
The documentation for this struct was generated from the following file:
tensor.h