MADNESS: madness::CCPairFunction Struct Reference
madness::CCPairFunction Struct Reference
#include <ccpairfunction.h>
Public Types
using T = double
Public Member Functions
CCPairFunction ()=default
empty ctor
CCPairFunction (const CCConvolutionOperator *op_, const CCFunction &f1, const CCFunction &f2)
takes a deep copy of the argument functions
CCPairFunction (const CCConvolutionOperator *op_, const std::vector< real_function_3d > &f1, const std::vector< real_function_3d > &f2)
takes a deep copy of the argument functions
CCPairFunction (const CCPairFunction &other)=default
copy ctor – shallow
CCPairFunction (const real_function_6d &ket)
takes a deep copy of the argument function
CCPairFunction (const std::pair< vector_real_function_3d, vector_real_function_3d > &f)
takes a deep copy of the argument functions
CCPairFunction (const vector_real_function_3d &f1, const vector_real_function_3d &f2)
takes a deep copy of the argument functions
const std::pair< vector_real_function_3d, vector_real_function_3d > assign_particles (const size_t particle) const
small helper function that gives back (a,b) or (b,a) depending on the value of particle
TwoBodyFunctionSeparatedComponent< T > & decomposed () const
real_function_3d dirac_convolution (const CCFunction &x, const CCConvolutionOperator &op, const size_t particle) const
real_function_3d dirac_convolution_decomposed (const CCFunction &x, const CCConvolutionOperator &op, const size_t particle) const
vector_real_function_3d get_a () const
vector_real_function_3d get_b () const
Function< T, 6 > & get_function ()
Function< T, 6 > & get_function () const
const CCConvolutionOperator & get_operator () const
bool has_operator () const
void info () const
double inner_internal (const CCPairFunction &other, const real_function_3d &R2) const
CCPairFunction invert_sign ()
bool is_decomposed () const
bool is_decomposed_no_op () const
bool is_op_decomposed () const
bool is_pure () const
double make_xy_u (const CCFunction &xx, const CCFunction &yy) const
std::string name (const bool transpose=false) const
CCPairFunction & operator() (const CCPairFunction &other)
shallow assignment operator
CCPairFunction operator* (const double fac) const
CCPairFunction & operator*= (const double fac)
real_function_3d partial_inner (const real_function_3d &f, const std::array< int, 3 > &v1, const std::array< int, 3 > &v2) const
void print_size () const
print the size of the functions
real_function_3d project_out (const CCFunction &f, const size_t particle) const
real_function_3d project_out_decomposed (const real_function_3d &f, const size_t particle) const
real_function_3d project_out_op_decomposed (const CCFunction &f, const size_t particle) const
TwoBodyFunctionPureComponent< T > & pure () const
CCPairFunction swap_particles () const
World & world () const
Public Attributes
std::shared_ptr< TwoBodyFunctionComponentBase > component
the 3 types of 6D-function that occur in the CC potential which coupled doubles to singles
Friends
template<typename Q , std::size_t MDIM>
CCPairFunction apply (const SeparatedConvolution< Q, MDIM > &G, const CCPairFunction &argument)
CCPairFunction copy (const CCPairFunction &other)
deep copy
double inner (const CCPairFunction &a, const CCPairFunction &b)
double inner (const CCPairFunction &a, const CCPairFunction &b, const real_function_3d &R2)
double inner (const std::vector< CCPairFunction > &va, const std::vector< CCPairFunction > &vb)
CCPairFunction operator* (const double fac, const CCPairFunction &f)
Detailed Description
Helper structure for the coupling potential of CC Singles and Doubles because of the regularization of the CC-Wavefunction (for CC2: |tauij> = |uij> + Qt12*f12*|titj>) we have 6D-functions in std format |u> : type==pure_ we have 6D-functions in separated format: type==decomposed_ (e.g O1*f12*|titj> = |xy> with x=|k> and y=<k|f12|ti>*|tj>) we have 6D-function like f12|xy> which are not needed to be represented on the 6D MRA-Grid, type==op_decomposed_ functionality
ctor
assignment
add
scalar multiplication
inner
inner_partial
swap_particles
apply
apply_partial (i.e. exchange)
serialize
callapse_to_pure (excl g!)
mul_partial
Member Typedef Documentation
T
using madness::CCPairFunction::T = double
Constructor & Destructor Documentation
CCPairFunction() [1/7]
madness::CCPairFunction::CCPairFunction () default
empty ctor
Referenced by inner_internal().
CCPairFunction() [2/7]
madness::CCPairFunction::CCPairFunction (const real_function_6d & ket) inline explicit
takes a deep copy of the argument function
References component, and copy.
CCPairFunction() [3/7]
madness::CCPairFunction::CCPairFunction (const vector_real_function_3d & f1, const vector_real_function_3d & f2) inline explicit
takes a deep copy of the argument functions
References component, copy, f1, f2, and world().
CCPairFunction() [4/7]
madness::CCPairFunction::CCPairFunction (const std::pair< vector_real_function_3d, vector_real_function_3d > & f) inline explicit
takes a deep copy of the argument functions
CCPairFunction() [5/7]
madness::CCPairFunction::CCPairFunction (const CCConvolutionOperator * op_, const CCFunction & f1, const CCFunction & f2) inline explicit
takes a deep copy of the argument functions
References f1.
CCPairFunction() [6/7]
madness::CCPairFunction::CCPairFunction (const CCConvolutionOperator * op_, const std::vector< real_function_3d > & f1, const std::vector< real_function_3d > & f2) inline explicit
takes a deep copy of the argument functions
References component, copy, f1, f2, and world().
CCPairFunction() [7/7]
madness::CCPairFunction::CCPairFunction (const CCPairFunction & other) default
copy ctor – shallow
Member Function Documentation
assign_particles()
const std::pair< vector_real_function_3d, vector_real_function_3d > madness::CCPairFunction::assign_particles (const size_t particle) const
small helper function that gives back (a,b) or (b,a) depending on the value of particle
References get_a(), get_b(), and MADNESS_EXCEPTION.
Referenced by dirac_convolution_decomposed(), and project_out_decomposed().
decomposed()
TwoBodyFunctionSeparatedComponent<T>& madness::CCPairFunction::decomposed () const inline
References component, and MADNESS_EXCEPTION.
Referenced by get_a(), get_b(), get_operator(), make_xy_u(), operator*=(), and project_out_op_decomposed().
dirac_convolution()
real_function_3d madness::CCPairFunction::dirac_convolution (const CCFunction & x, const CCConvolutionOperator & op, const size_t particle) const
Parameters
[in] x a 3D-CC_function
[in] op a CC_convoltion_operator which is currently either f12 or g12
[in] particle the particle on which the operation acts (can be 1 or 2)
[out] the operator is applied and afterwards a convolution with the delta function makes a 3D-function: <x|op|u>_particle
References dirac_convolution_decomposed(), get_function(), is_decomposed_no_op(), is_pure(), MADNESS_EXCEPTION, op(), and pure().
dirac_convolution_decomposed()
real_function_3d madness::CCPairFunction::dirac_convolution_decomposed (const CCFunction & x, const CCConvolutionOperator & op, const size_t particle) const
Parameters
[in] x a 3D-CC_function
[in] op a CC_convoltion_operator which is currently either f12 or g12
[in] particle the particle on which the operation acts (can be 1 or 2)
[out] the operator is applied and afterwards a convolution with the delta function makes a 3D-function: <x|op|u>_particle in this case u=|ab> and the result is <x|op|u>_1 = <x|op|a>*|b> for particle==1
References assign_particles(), madness::f, madness::CCFunction::function, madness::mul(), op(), world(), and madness::Function< T, NDIM >::world().
Referenced by dirac_convolution().
get_a()
vector_real_function_3d madness::CCPairFunction::get_a () const inline
References component, decomposed(), and MADNESS_CHECK.
Referenced by assign_particles(), make_xy_u(), project_out_decomposed(), project_out_op_decomposed(), and test_scalar_multiplication().
get_b()
vector_real_function_3d madness::CCPairFunction::get_b () const inline
References component, decomposed(), and MADNESS_CHECK.
Referenced by assign_particles(), make_xy_u(), project_out_op_decomposed(), and test_scalar_multiplication().
get_function() [1/2]
Function<T,6>& madness::CCPairFunction::get_function () inline
References component, MADNESS_CHECK, and pure().
Referenced by dirac_convolution(), make_xy_u(), and test_swap_particles().
get_function() [2/2]
Function<T,6>& madness::CCPairFunction::get_function () const inline
References component, MADNESS_CHECK, and pure().
get_operator()
const CCConvolutionOperator& madness::CCPairFunction::get_operator () const inline
References decomposed(), is_op_decomposed(), and MADNESS_CHECK.
has_operator()
bool madness::CCPairFunction::has_operator () const inline
References component.
info()
void madness::CCPairFunction::info () const inline
References print_size().
inner_internal()
double madness::CCPairFunction::inner_internal (const CCPairFunction & other, const real_function_3d & R2) const
References CCPairFunction(), a, a1, a2, aa, madness::assign_name(), b, copy, madness::TwoElectronFactory::dcut(), f1, madness::TwoElectronFactory::f12(), f2, madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::TwoElectronFactory::gamma(), madness::FunctionDefaults< NDIM >::get_thresh(), inner, MADNESS_ASSERT, MADNESS_CHECK, MADNESS_EXCEPTION, madness::matrix_inner(), name(), op(), madness::OT_F12, madness::OT_G12, madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::print(), R2, madness::sum(), thresh, madness::TwoElectronFactory::thresh(), madness::truncate(), and world().
invert_sign()
madness::CCPairFunction madness::CCPairFunction::invert_sign ()
make a deep copy and invert the sign deep copy necessary otherwise: shallow copy errors
is_decomposed()
bool madness::CCPairFunction::is_decomposed () const inline
References component.
Referenced by test_constructor().
is_decomposed_no_op()
bool madness::CCPairFunction::is_decomposed_no_op () const inline
References component.
Referenced by dirac_convolution(), make_xy_u(), partial_inner(), and project_out().
is_op_decomposed()
bool madness::CCPairFunction::is_op_decomposed () const inline
References component.
Referenced by get_operator(), make_xy_u(), partial_inner(), project_out(), and test_constructor().
is_pure()
bool madness::CCPairFunction::is_pure () const inline
References component.
Referenced by dirac_convolution(), make_xy_u(), partial_inner(), project_out(), and test_constructor().
make_xy_u()
double madness::CCPairFunction::make_xy_u (const CCFunction & xx, const CCFunction & yy) const
References madness::copy(), decomposed(), madness::CCFunction::function, get_a(), get_b(), get_function(), ij(), inner, is_decomposed_no_op(), is_op_decomposed(), is_pure(), op(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), pure(), world(), and madness::Function< T, NDIM >::world().
name()
std::string madness::CCPairFunction::name (const bool transpose = false) const inline
References component, and madness::transpose().
Referenced by inner_internal().
operator()()
CCPairFunction& madness::CCPairFunction::operator() (const CCPairFunction & other) inline
shallow assignment operator
References component.
operator*()
CCPairFunction madness::CCPairFunction::operator* (const double fac) const inline
References copy.
operator*=()
CCPairFunction& madness::CCPairFunction::operator*= (const double fac) inline
References component, decomposed(), and pure().
partial_inner()
real_function_3d madness::CCPairFunction::partial_inner (const real_function_3d & f, const std::array< int, 3 > & v1, const std::array< int, 3 > & v2) const
References madness::f, is_decomposed_no_op(), is_op_decomposed(), is_pure(), MADNESS_CHECK, MADNESS_EXCEPTION, project_out_decomposed(), project_out_op_decomposed(), and pure().
print_size()
void madness::CCPairFunction::print_size () const inline
print the size of the functions
References component.
Referenced by info().
project_out()
real_function_3d madness::CCPairFunction::project_out (const CCFunction & f, const size_t particle) const
Parameters
[in] f a 3D-CC_function
[in] particle the particle on which the operation acts
[out] <f|u>_particle (projection from 6D to 3D)
References madness::f, is_decomposed_no_op(), madness::Function< T, NDIM >::is_initialized(), is_op_decomposed(), is_pure(), MADNESS_ASSERT, MADNESS_EXCEPTION, project_out_decomposed(), project_out_op_decomposed(), and pure().
project_out_decomposed()
real_function_3d madness::CCPairFunction::project_out_decomposed (const real_function_3d & f, const size_t particle) const
Parameters
[in] f a 3D-CC_function
[in] particle the particle on which the operation acts
[out] <f|u>_particle (projection from 6D to 3D) for the case that u=|ab> so <f|u>_particle = <f|a>*|b> if particle==1
References assign_particles(), c, madness::f, get_a(), inner, and world().
Referenced by partial_inner(), and project_out().
project_out_op_decomposed()
real_function_3d madness::CCPairFunction::project_out_op_decomposed (const CCFunction & f, const size_t particle) const
Parameters
[in] f a 3D-CC_function
[in] particle the particle on which the operation acts
[out] <f|u>_particle (projection from 6D to 3D) for the case that u=op|xy> so <f|u>_particle = <f|op|x>*|y> if particle==1
References decomposed(), madness::f, get_a(), get_b(), MADNESS_EXCEPTION, madness::mul(), op(), madness::sum(), and world().
Referenced by partial_inner(), and project_out().
pure()
TwoBodyFunctionPureComponent<T>& madness::CCPairFunction::pure () const inline
References component, and MADNESS_EXCEPTION.
Referenced by dirac_convolution(), get_function(), make_xy_u(), operator*=(), partial_inner(), project_out(), and test_constructor().
swap_particles()
CCPairFunction madness::CCPairFunction::swap_particles () const inline
Parameters
[out] particles are interchanged, if the function was u(1,2) the result is u(2,1)
References component, and copy.
Referenced by test_swap_particles().
world()
World& madness::CCPairFunction::world () const inline
References component, and MADNESS_CHECK.
Referenced by CCPairFunction(), dirac_convolution_decomposed(), inner_internal(), make_xy_u(), project_out_decomposed(), and project_out_op_decomposed().
Friends And Related Function Documentation
apply
template<typename Q , std::size_t MDIM> CCPairFunction apply (const SeparatedConvolution< Q, MDIM > & G, const CCPairFunction & argument) friend
copy
CCPairFunction copy (const CCPairFunction & other) friend
deep copy
Referenced by CCPairFunction(), inner_internal(), operator*(), and swap_particles().
inner [1/3]
double inner (const CCPairFunction & a, const CCPairFunction & b) friend
inner [2/3]
double inner (const CCPairFunction & a, const CCPairFunction & b, const real_function_3d & R2) friend
Referenced by inner_internal(), make_xy_u(), and project_out_decomposed().
inner [3/3]
double inner (const std::vector< CCPairFunction > & va, const std::vector< CCPairFunction > & vb) friend
operator*
CCPairFunction operator* (const double fac, const CCPairFunction & f) friend
Member Data Documentation
component
std::shared_ptr<TwoBodyFunctionComponentBase> madness::CCPairFunction::component
the 3 types of 6D-function that occur in the CC potential which coupled doubles to singles
Referenced by CCPairFunction(), decomposed(), get_a(), get_b(), get_function(), has_operator(), is_decomposed(), is_decomposed_no_op(), is_op_decomposed(), is_pure(), name(), operator()(), operator*=(), print_size(), pure(), swap_particles(), test_constructor(), and world().
The documentation for this struct was generated from the following files:
ccpairfunction.h
ccpairfunction.cc