MADNESS: madness::timer Struct Reference
madness::timer Struct Reference
#include <timing_utilities.h>
Public Member Functions
timer (World &world, bool do_print=true)
double end (const std::string msg)
double interrupt ()
void print (const std::string msg) const
void resume ()
double tag (const std::string msg)
Public Attributes
bool do_print = true
bool is_running =false
double sss =0.0
double ttt =0.0
World & world
Constructor & Destructor Documentation
timer()
madness::timer::timer (World & world, bool do_print = true) inline
References madness::WorldGopInterface::fence(), madness::World::gop, resume(), and world.
Member Function Documentation
end()
double madness::timer::end (const std::string msg) inline
References tag().
Referenced by madness::Nemo::analyze(), madness::apply(), madness::Nemo::compute_energy_regularized(), madness::NemoBase::compute_kinetic_energy1(), madness::NemoBase::compute_kinetic_energy1a(), madness::Nemo::hessian(), main(), madness::OEP::recompute_HF(), madness::Nemo::set_protocol(), madness::Nemo::solve(), and madness::CC2::solve_mp2_coupled().
interrupt()
double madness::timer::interrupt () inline
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, is_running, sss, ttt, madness::wall_time(), and world.
Referenced by madness::MP3::compute_mp3_ef_low_scaling(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn_fast(), and tag().
print()
void madness::timer::print (const std::string msg) const inline
References do_print, madness::World::rank(), sss, ttt, and world.
Referenced by madness::PNO::compute_cispd_correction_es(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_f12_correction_es(), madness::PNO::compute_cispd_f12_correction_gs(), madness::PNO::compute_cispd_fluctuation_matrix(), madness::MP3::compute_mp3_ef_low_scaling(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn_fast(), madness::PNO::grow_rank(), madness::PNO::initialize_pairs(), madness::TDHF::iterate_vectors(), madness::PNO::orthonormalize_cholesky(), madness::TDHF::plot(), madness::PNO::pno_compress(), resume(), madness::PNO::save_pnos(), tag(), madness::PNO::truncate_pairs(), madness::PNO::update_fluctuation_potentials(), and madness::PNO::update_pno().
resume()
void madness::timer::resume () inline
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, is_running, print(), sss, ttt, madness::wall_time(), and world.
Referenced by timer(), madness::MP3::compute_mp3_ef_low_scaling(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn_fast(), and tag().
tag()
double madness::timer::tag (const std::string msg) inline
References madness::WorldGopInterface::fence(), madness::World::gop, interrupt(), print(), resume(), sss, ttt, and world.
Referenced by apply_bsh(), madness::MP2::apply_exchange_vector(), madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::CCPairBuilder::complete_pair_with_low_rank_parts(), madness::Nemo::compute_all_cphf(), madness::MP3::compute_mp3_ef(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_ghij_fast(), madness::Nemo::compute_nemo_potentials(), end(), madness::OEP::iterate(), madness::LowRankFunction< T, NDIM, LDIM >::l2error(), main(), madness::MP3::mp3_energy_contribution(), madness::MP3::mp3_energy_contribution_macrotask_driver(), madness::LowRankFunction< T, NDIM, LDIM >::optimize(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::Nemo::solve(), madness::CC2::solve_cc2(), madness::CC2::solve_mp2_coupled(), and test_Kcommutator().
Member Data Documentation
do_print
bool madness::timer::do_print = true
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::check_orthonormality(), madness::LowRankFunction< T, NDIM, LDIM >::l2error(), madness::LowRankFunction< T, NDIM, LDIM >::optimize(), print(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::project().
is_running
bool madness::timer::is_running =false
Referenced by interrupt(), and resume().
sss
double madness::timer::sss =0.0
Referenced by interrupt(), print(), resume(), and tag().
ttt
double madness::timer::ttt =0.0
Referenced by interrupt(), print(), resume(), and tag().
world
World& madness::timer::world
Referenced by timer(), interrupt(), print(), resume(), and tag().
The documentation for this struct was generated from the following file:
timing_utilities.h