MADNESS: write_test_input Struct Reference
write_test_input Struct Reference
will write a test input and remove it from disk upon destruction
Public Member Functions
write_test_input (const TestCalculationParameters &param, const std::string &mol="lih")
~write_test_input ()
std::string filename () const
Public Attributes
double eprec =1.e-6
std::string filename_
Detailed Description
will write a test input and remove it from disk upon destruction
Constructor & Destructor Documentation
write_test_input()
write_test_input::write_test_input (const TestCalculationParameters & param, const std::string & mol = "lih") inline
References eprec, filename_, and param.
~write_test_input()
write_test_input::~write_test_input () inline
References filename_.
Member Function Documentation
filename()
std::string write_test_input::filename () const inline
References filename_.
Referenced by dnuclear_anchor_test(), main(), nuclear_anchor_test(), run_all_calculations(), test_fock(), test_nemo(), test_read_restartaodata(), and test_read_restartdata().
Member Data Documentation
eprec
double write_test_input::eprec =1.e-6
Referenced by write_test_input().
filename_
std::string write_test_input::filename_
Referenced by write_test_input(), ~write_test_input(), and filename().
The documentation for this struct was generated from the following file:
test_qc.cc