MADNESS: madness::RMDFactory Struct Reference
madness::RMDFactory Struct Reference
simple factory pattern for the RandomizedMatrixDecomposition
#include <RandomizedMatrixDecomposition.h>
Public Member Functions
RMDFactory ()
RMDFactory & maxrank (const long mr)
RMDFactory & oversampling (const long os)
Public Attributes
long maxrank_ =LONG_MAX
long oversampling_ =10
Detailed Description
simple factory pattern for the RandomizedMatrixDecomposition
Constructor & Destructor Documentation
RMDFactory()
madness::RMDFactory::RMDFactory () inline
Member Function Documentation
maxrank()
RMDFactory & madness::RMDFactory::maxrank (const long mr) inline
References maxrank_.
Referenced by madness::SVDTensor< T >::compute_randomized_svd(), and madness::SVDTensor< T >::orthonormalize_random().
oversampling()
RMDFactory & madness::RMDFactory::oversampling (const long os) inline
References oversampling_.
Referenced by test_stuff().
Member Data Documentation
maxrank_
long madness::RMDFactory::maxrank_ =LONG_MAX
Referenced by maxrank().
oversampling_
long madness::RMDFactory::oversampling_ =10
Referenced by oversampling().
The documentation for this struct was generated from the following file:
RandomizedMatrixDecomposition.h