MADNESS: Calculation Struct Reference
Calculation Struct Reference
Public Member Functions
Calculation (World &world)
tensorT calc_deriv (World &world, CorePotential &cp, double r)
CorePotential calc_optimal_coeffs (World &world, CorePotential &cp)
double compute_residuals (World &world, CorePotential &cp, vecfuncT &mo, vecfuncT &vmo)
void load_mos (World &world, std::string atom)
vecfuncT make_reference (World &world, vecfuncT &mo, tensorT &occ)
vecfuncT make_Upsi (World &world, CorePotential &cp, vecfuncT &mo)
void plot_p (const char *filename, const vecfuncT &f)
void plot_z (const char *filename, const functionT &f)
void print_info ()
functionT project_potential_basis (World &world, CorePotential &cp, int i)
void set_protocol (World &world, double thresh)
CorePotential update (World &world, CorePotential &cp, tensorT &deriv, double &r)
Public Attributes
tensorT aeps
vecfuncT amo
tensorT aocc
vector< int > aset
unsigned int atn
atomic number of target atom
tensorT beps
vecfuncT bmo
tensorT bocc
vector< int > bset
CorePotentialManager corepot
poperatorT coulop
functionT mask
unsigned int nalpha
unsigned int nbeta
number of valence orbitals alpha/beta
unsigned int ncore
number of core orbitals
CalculationParameters param
bool spin_restricted
vecfuncT vamo
vecfuncT vbmo
double vtol
multiplication tolerance
Constructor & Destructor Documentation
Calculation()
Calculation::Calculation (World & world) inline
References amo, aocc, atn, bmo, bocc, madness::WorldGopInterface::broadcast_serializable(), corepot, madness::World::gop, madness::CorePotentialManager::is_defined(), madness::CalculationParameters::L(), load_mos(), MADNESS_ASSERT, make_reference(), madness::CorePotentialManager::n_core_orb(), nbeta, ncore, madness::norm2(), param, print(), print_info(), madness::World::rank(), madness::CorePotentialManager::read_file(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), set_protocol(), spin_restricted, madness::symbol_to_atomic_number(), vamo, and vbmo.
Member Function Documentation
calc_deriv()
tensorT Calculation::calc_deriv (World & world, CorePotential & cp, double r) inline
References a, madness::CorePotential::alpha, amo, bmo, calc_optimal_coeffs(), compute_residuals(), nbeta, param, spin_restricted, vamo, and vbmo.
Referenced by CoreFittingTarget::gradient().
calc_optimal_coeffs()
CorePotential Calculation::calc_optimal_coeffs (World & world, CorePotential & cp) inline
References madness::CorePotential::A, madness::CorePotential::alpha, amo, b, bmo, madness::WorldGopInterface::broadcast_serializable(), c, madness::WorldGopInterface::fence(), madness::gelss(), madness::World::gop, madness::inner(), madness::CorePotential::l, madness::matrix_inner(), madness::mul_sparse(), madness::CorePotential::n, nalpha, nbeta, print(), project_potential_basis(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), spin_restricted, tensor2vec(), madness::Function< T, NDIM >::truncate(), madness::truncate(), vamo, vbmo, and vtol.
Referenced by calc_deriv(), main(), and CoreFittingTarget::value().
compute_residuals()
double Calculation::compute_residuals (World & world, CorePotential & cp, vecfuncT & mo, vecfuncT & vmo) inline
References madness::BaseTensor::dim(), madness::WorldGopInterface::fence(), madness::World::gop, make_Upsi(), madness::mul_sparse(), madness::norm2(), param, plot_z(), print(), madness::sub(), madness::truncate(), and vtol.
Referenced by calc_deriv(), main(), update(), and CoreFittingTarget::value().
load_mos()
void Calculation::load_mos (World & world, std::string atom) inline
References aeps, amo, aocc, aset, beps, bmo, bocc, bset, e(), madness::error(), madness::WorldGopInterface::fence(), madness::filename, madness::FunctionDefaults< NDIM >::get_k(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, k, madness::matrix_inner(), nalpha, nbeta, ncore, madness::normalize(), print(), madness::project(), Q3(), madness::reconstruct(), spin_restricted, thresh, madness::transform(), madness::truncate(), u(), and vtol.
Referenced by Calculation().
make_reference()
vecfuncT Calculation::make_reference (World & world, vecfuncT & mo, tensorT & occ) inline
References amo, aocc, madness::apply(), atn, bmo, bocc, c, madness::Function< T, NDIM >::clear(), madness::Function< T, NDIM >::compress(), madness::compress(), corepot, coul(), coulop, END_TIMER, madness::WorldGopInterface::fence(), madness::gaxpy(), madness::Function< T, NDIM >::gaxpy(), madness::CorePotentialManager::get_core_bc(), madness::CorePotentialManager::get_core_l(), madness::World::gop, madness::inner(), m, madness::mul_sparse(), ncore, madness::norm_tree(), param, print(), madness::Function< T, NDIM >::reconstruct(), madness::reconstruct(), madness::smoothing_parameter(), spin_restricted, madness::square(), START_TIMER, madness::Function< T, NDIM >::thresh(), madness::Function< T, NDIM >::truncate(), madness::truncate(), and vtol.
Referenced by Calculation().
make_Upsi()
vecfuncT Calculation::make_Upsi (World & world, CorePotential & cp, vecfuncT & mo) inline
References madness::Function< T, NDIM >::clear(), END_TIMER, madness::WorldGopInterface::fence(), madness::World::gop, madness::mul_sparse(), madness::Function< T, NDIM >::reconstruct(), START_TIMER, madness::Function< T, NDIM >::thresh(), madness::Function< T, NDIM >::truncate(), madness::truncate(), and vtol.
Referenced by compute_residuals().
plot_p()
void Calculation::plot_p (const char * filename, const vecfuncT & f) inline
References madness::f, f1, f2, madness::WorldGopInterface::fence(), madness::filename, madness::World::gop, h(), lo, madness::plot_line_print_value(), madness::World::rank(), madness::reconstruct(), sum, and v.
plot_z()
void Calculation::plot_z (const char * filename, const functionT & f) inline
References madness::f, madness::filename, lo, and madness::plot_line().
Referenced by compute_residuals().
print_info()
void Calculation::print_info () inline
References aeps, aocc, atn, beps, bocc, nalpha, nbeta, ncore, print(), and spin_restricted.
Referenced by Calculation().
project_potential_basis()
functionT Calculation::project_potential_basis (World & world, CorePotential & cp, int i) inline
References madness::CorePotential::alpha, e(), madness::CorePotential::n, norm(), madness::Function< T, NDIM >::norm2(), print(), madness::CorePotential::rcut, and madness::Function< T, NDIM >::truncate().
Referenced by calc_optimal_coeffs().
set_protocol()
void Calculation::set_protocol (World & world, double thresh) inline
References madness::CoulombOperatorPtr(), coulop, madness::CalculationParameters::dconv(), e(), madness::f, madness::FunctionDefaults< NDIM >::get_thresh(), k, madness::CalculationParameters::lo(), mask, mask3(), param, print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), thresh, and vtol.
Referenced by Calculation().
update()
CorePotential Calculation::update (World & world, CorePotential & cp, tensorT & deriv, double & r) inline
References madness::CorePotential::alpha, amo, bmo, compute_residuals(), madness::CalculationParameters::dconv(), nbeta, madness::Tensor< T >::normf(), param, spin_restricted, tensor2vec(), vamo, vbmo, and vec2tensor().
Member Data Documentation
aeps
tensorT Calculation::aeps
Referenced by load_mos(), and print_info().
amo
vecfuncT Calculation::amo
Referenced by Calculation(), calc_deriv(), calc_optimal_coeffs(), load_mos(), main(), make_reference(), update(), and CoreFittingTarget::value().
aocc
tensorT Calculation::aocc
Referenced by Calculation(), load_mos(), make_reference(), and print_info().
aset
vector<int> Calculation::aset
Referenced by load_mos().
atn
unsigned int Calculation::atn
atomic number of target atom
Referenced by Calculation(), main(), make_reference(), and print_info().
beps
tensorT Calculation::beps
Referenced by load_mos(), and print_info().
bmo
vecfuncT Calculation::bmo
Referenced by Calculation(), calc_deriv(), calc_optimal_coeffs(), load_mos(), main(), make_reference(), update(), and CoreFittingTarget::value().
bocc
tensorT Calculation::bocc
Referenced by Calculation(), load_mos(), make_reference(), and print_info().
bset
vector<int> Calculation::bset
Referenced by load_mos().
corepot
CorePotentialManager Calculation::corepot
Referenced by Calculation(), main(), and make_reference().
coulop
poperatorT Calculation::coulop
Referenced by make_reference(), and set_protocol().
mask
functionT Calculation::mask
Referenced by set_protocol().
nalpha
unsigned int Calculation::nalpha
Referenced by calc_optimal_coeffs(), load_mos(), and print_info().
nbeta
unsigned int Calculation::nbeta
number of valence orbitals alpha/beta
Referenced by Calculation(), calc_deriv(), calc_optimal_coeffs(), load_mos(), main(), print_info(), update(), and CoreFittingTarget::value().
ncore
unsigned int Calculation::ncore
number of core orbitals
Referenced by Calculation(), load_mos(), make_reference(), and print_info().
param
CalculationParameters Calculation::param
Referenced by Calculation(), calc_deriv(), compute_residuals(), main(), make_reference(), set_protocol(), and update().
spin_restricted
bool Calculation::spin_restricted
Referenced by Calculation(), calc_deriv(), calc_optimal_coeffs(), load_mos(), main(), make_reference(), print_info(), update(), and CoreFittingTarget::value().
vamo
vecfuncT Calculation::vamo
Referenced by Calculation(), calc_deriv(), calc_optimal_coeffs(), main(), update(), and CoreFittingTarget::value().
vbmo
vecfuncT Calculation::vbmo
Referenced by Calculation(), calc_deriv(), calc_optimal_coeffs(), main(), update(), and CoreFittingTarget::value().
vtol
double Calculation::vtol
multiplication tolerance
Referenced by calc_optimal_coeffs(), compute_residuals(), load_mos(), make_reference(), make_Upsi(), and set_protocol().
The documentation for this struct was generated from the following file:
mcpfit.cc