MADNESS: madness::LowRankFunctionParameters Struct Reference
madness::LowRankFunctionParameters Struct Reference
#include <lowrankfunction.h>
Public Member Functions
LowRankFunctionParameters ()
std::string f12type () const
double gamma () const
std::string get_tag () const override
std::string gridtype () const
int optimize () const
std::string orthomethod () const
double radius () const
void read_and_set_derived_values (World &world, const commandlineparser &parser, std::string tag)
std::string rhsfunctiontype () const
double tol () const
double volume_element () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
LowRankFunctionParameters()
madness::LowRankFunctionParameters::LowRankFunctionParameters () inline
Member Function Documentation
f12type()
std::string madness::LowRankFunctionParameters::f12type () const inline
Referenced by test_Kcommutator(), and test_lowrank_function().
gamma()
double madness::LowRankFunctionParameters::gamma () const inline
Referenced by test_Kcommutator(), and test_lowrank_function().
get_tag()
std::string madness::LowRankFunctionParameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
gridtype()
std::string madness::LowRankFunctionParameters::gridtype () const inline
Referenced by madness::molecular_grid< NDIM >::molecular_grid(), test_Kcommutator(), and test_lowrank_function().
optimize()
int madness::LowRankFunctionParameters::optimize () const inline
Referenced by test_Kcommutator(), test_lowrank_function(), and test_molecular_grid().
orthomethod()
std::string madness::LowRankFunctionParameters::orthomethod () const inline
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), test_Kcommutator(), and test_lowrank_function().
radius()
double madness::LowRankFunctionParameters::radius () const inline
Referenced by madness::molecular_grid< NDIM >::molecular_grid(), test_Kcommutator(), and test_lowrank_function().
read_and_set_derived_values()
void madness::LowRankFunctionParameters::read_and_set_derived_values (World & world, const commandlineparser & parser, std::string tag) inline
References madness::QCCalculationParametersBase::read_input_and_commandline_options().
Referenced by main().
rhsfunctiontype()
std::string madness::LowRankFunctionParameters::rhsfunctiontype () const inline
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), test_Kcommutator(), and test_lowrank_function().
tol()
double madness::LowRankFunctionParameters::tol () const inline
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), test_Kcommutator(), test_lowrank_function(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer().
volume_element()
double madness::LowRankFunctionParameters::volume_element () const inline
Referenced by madness::molecular_grid< NDIM >::molecular_grid(), test_Kcommutator(), and test_lowrank_function().
The documentation for this struct was generated from the following file:
lowrankfunction.h