MADNESS: madness::QCParameter Struct Reference
madness::QCParameter Struct Reference
structure holding the value for a given parameter
#include <QCCalculationParametersBase.h>
Public Types
enum { def , derived , defined }
Public Member Functions
QCParameter ()
QCParameter (const std::string v, const std::string t, const std::string comment="", const std::vector< std::string > allowed_values1={})
std::string get_comment () const
int get_print_order () const
std::string get_type () const
std::string get_value () const
hashT hash () const
bool is_user_defined () const
bool operator== (const QCParameter &other) const
std::string print_line (const std::string &key) const
std::string print_precedence () const
template<typename Archive >
void serialize (Archive &ar)
void set_derived_value (const std::string val)
void set_user_defined_value (const std::string val)
Public Attributes
enum madness::QCParameter:: { ... } precedence = def
Private Member Functions
bool check_allowed ()
std::string not_allowed_errmsg () const
void set_all ()
Private Attributes
std::vector< std::string > allowed_values = std::vector<std::string>()
std::string comment = ""
std::string default_value = ""
std::string derived_value = ""
std::string null = ""
int print_order = 0
std::string type = ""
std::string user_defined_value = ""
std::string value
Detailed Description
structure holding the value for a given parameter
keeps logic about default, derived and user-defined settings (with increasing priority), as well as comments for the user (e.g. a recommended range for a given parameter).
might be extended to hold allowed values for certain parameters, e.g. localization procedures.
all values are stored as strings and must be converted to their respective types by the QCCalculationParametersBase class (see below)
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
def
derived
defined
Constructor & Destructor Documentation
QCParameter() [1/2]
madness::QCParameter::QCParameter () inline
QCParameter() [2/2]
madness::QCParameter::QCParameter (const std::string v, const std::string t, const std::string comment = "", const std::vector< std::string > allowed_values1 = {}) inline
Member Function Documentation
check_allowed()
bool madness::QCParameter::check_allowed () inline private
References allowed_values, and value.
Referenced by set_all().
get_comment()
std::string madness::QCParameter::get_comment () const inline
References comment.
Referenced by print_line().
get_print_order()
int madness::QCParameter::get_print_order () const inline
References print_order.
get_type()
std::string madness::QCParameter::get_type () const inline
References type.
Referenced by madness::QCCalculationParametersBase::check_type(), madness::QCCalculationParametersBase::check_type_silent(), madness::QCCalculationParametersBase::read_internal(), and madness::QCCalculationParametersBase::try_set_from_json().
get_value()
std::string madness::QCParameter::get_value () const inline
References value.
Referenced by madness::QCCalculationParametersBase::check_type(), madness::QCCalculationParametersBase::get(), and print_line().
hash()
hashT madness::QCParameter::hash () const inline
References madness::hash_value(), and value.
is_user_defined()
bool madness::QCParameter::is_user_defined () const inline
References defined, and precedence.
Referenced by madness::QCCalculationParametersBase::is_user_defined().
not_allowed_errmsg()
std::string madness::QCParameter::not_allowed_errmsg () const inline private
References allowed_values, errmsg(), and value.
Referenced by set_all().
operator==()
bool madness::QCParameter::operator== (const QCParameter & other) const inline
References allowed_values, comment, default_value, derived_value, null, print_order, type, user_defined_value, and value.
print_line()
std::string madness::QCParameter::print_line (const std::string & key) const inline
References allowed_values, get_comment(), get_value(), print_precedence(), and madness::commandlineparser::split().
print_precedence()
std::string madness::QCParameter::print_precedence () const inline
References def, defined, derived, and precedence.
Referenced by print_line().
serialize()
template<typename Archive > void madness::QCParameter::serialize (Archive & ar) inline
References allowed_values, comment, default_value, derived_value, null, precedence, print_order, type, user_defined_value, and value.
set_all()
void madness::QCParameter::set_all () inline private
References check_allowed(), default_value, derived_value, not_allowed_errmsg(), null, user_defined_value, and value.
Referenced by set_derived_value(), and set_user_defined_value().
set_derived_value()
void madness::QCParameter::set_derived_value (const std::string val) inline
References derived, derived_value, precedence, and set_all().
Referenced by madness::QCCalculationParametersBase::set_derived_value().
set_user_defined_value()
void madness::QCParameter::set_user_defined_value (const std::string val) inline
References defined, precedence, set_all(), and user_defined_value.
Referenced by madness::QCCalculationParametersBase::set_user_defined_value(), and madness::QCCalculationParametersBase::try_set_from_json().
Member Data Documentation
allowed_values
std::vector<std::string> madness::QCParameter::allowed_values = std::vector<std::string>() private
Referenced by check_allowed(), not_allowed_errmsg(), operator==(), print_line(), and serialize().
comment
std::string madness::QCParameter::comment = "" private
Referenced by get_comment(), operator==(), and serialize().
default_value
std::string madness::QCParameter::default_value = "" private
Referenced by operator==(), serialize(), and set_all().
derived_value
std::string madness::QCParameter::derived_value = "" private
Referenced by operator==(), serialize(), set_all(), and set_derived_value().
null
std::string madness::QCParameter::null = "" private
Referenced by operator==(), serialize(), and set_all().
[]
enum { ... } madness::QCParameter::precedence
Referenced by is_user_defined(), print_precedence(), serialize(), set_derived_value(), and set_user_defined_value().
print_order
int madness::QCParameter::print_order = 0 private
Referenced by get_print_order(), operator==(), and serialize().
type
std::string madness::QCParameter::type = "" private
Referenced by get_type(), operator==(), and serialize().
user_defined_value
std::string madness::QCParameter::user_defined_value = "" private
Referenced by operator==(), serialize(), set_all(), and set_user_defined_value().
value
std::string madness::QCParameter::value private
Referenced by check_allowed(), get_value(), hash(), not_allowed_errmsg(), operator==(), serialize(), and set_all().
The documentation for this struct was generated from the following file:
QCCalculationParametersBase.h