MADNESS: madness::X_space Struct Reference
madness::X_space Struct Reference
#include <x_space.h>
Public Member Functions
X_space ()
X_space (const X_space &A)
X_space (World &world, size_t n_states, size_t n_orbitals)
void clear ()
auto component_norm2s () const -> Tensor< double >
void compress () const
X_space copy () const
auto copy (const std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > &p_map, bool fence=false) const -> X_space
auto from_vector (const vector_real_function_3d &rf) -> void
auto norm2s () const -> Tensor< double >
size_t num_orbitals () const
size_t num_states () const
auto operator+= (const X_space &B) -> X_space &
auto operator= (const X_space &B) -> X_space &
void pop_back ()
void push_back (const vector_real_function_3d &vx, const vector_real_function_3d &vy)
void reconstruct () const
void reset_active ()
void set_active (const std::list< size_t > &new_active)
auto to_vector () const -> vector_real_function_3d
void truncate ()
void truncate (double thresh)
Static Public Member Functions
static X_space zero_functions (World &world, size_t n_states, size_t n_orbitals)
Public Attributes
std::list< size_t > active
response_space x
response_space y
Private Attributes
size_t n_orbitals
size_t n_states
Friends
template<typename T >
auto binary_apply (const X_space &A, const X_space &B, T &func) -> X_space
template<class T >
auto binary_inplace (X_space &A, const X_space &B, const T &func)
auto inner (const X_space &A, const X_space &B) -> Tensor< double >
Computes the matrix elements between two response spaces.
auto inplace_apply (X_space &A, const std::function< void(vector_real_function_3d &)> &func) -> void
auto oop_apply (const X_space &A, const std::function< vector_real_function_3d(const vector_real_function_3d &)> &func, bool fence=true) -> X_space
Apply a function to the X_space.
X_space operator* (const double &b, const X_space &A)
auto operator* (const Function< double, 3 > &f, const X_space &A) -> X_space
X_space operator* (const X_space &A, const double &b)
X_space operator* (const X_space &A, const Function< double, 3 > &f)
auto operator* (const X_space &A, const Tensor< double > &b) -> X_space
X_space operator* (const X_space &B, const X_space &A)
auto operator+ (const X_space &A, const X_space &B) -> X_space
X_space operator- (const X_space &A, const X_space &B)
auto same_size (const X_space &A, const X_space &B) -> bool
auto size_orbitals (const X_space &x) -> size_t
auto size_states (const X_space &x) -> size_t
Constructor & Destructor Documentation
X_space() [1/3]
madness::X_space::X_space () inline
Referenced by copy(), copy(), and zero_functions().
X_space() [2/3]
madness::X_space::X_space (const X_space & A) inline
X_space() [3/3]
madness::X_space::X_space (World & world, size_t n_states, size_t n_orbitals) inline
References reset_active().
Member Function Documentation
clear()
void madness::X_space::clear () inline
References active, madness::response_space::clear(), x, and y.
component_norm2s()
auto madness::X_space::component_norm2s () const -> Tensor<double> inline
References n_orbitals, n_states, madness::norm2s_T(), madness::to_flattened_vector(), and x.
compress()
void madness::X_space::compress () const inline
References active, madness::compress(), to_vector(), and x.
copy() [1/2]
X_space madness::X_space::copy () const inline
References X_space(), madness::copy(), x, and y.
copy() [2/2]
auto madness::X_space::copy (const std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > & p_map, bool fence = false) const -> X_space inline
Create a new copy of the function with different distribution and optional fence Works in either basis. Different distributions imply asynchronous communication and the optional fence is collective.
References X_space(), madness::copy(), x, and y.
from_vector()
auto madness::X_space::from_vector (const vector_real_function_3d & rf) -> void inline
References active, m, num_orbitals(), x, and y.
Referenced by operator+=(), truncate(), and truncate().
norm2s()
auto madness::X_space::norm2s () const -> Tensor<double> inline
References b, madness::WorldGopInterface::fence(), madness::World::gop, madness::norm2(), num_states(), madness::to_response_matrix(), and x.
num_orbitals()
size_t madness::X_space::num_orbitals () const inline
References n_orbitals.
Referenced by madness::copyToVector(), madness::copyToXspace(), from_vector(), push_back(), and to_vector().
num_states()
size_t madness::X_space::num_states () const inline
References n_states.
Referenced by madness::copyToVector(), madness::copyToXspace(), and norm2s().
operator+=()
auto madness::X_space::operator+= (const X_space & B) -> X_space & inline
References from_vector(), MADNESS_ASSERT, same_size, and to_vector().
operator=()
auto madness::X_space::operator= (const X_space & B) -> X_space & inline
pop_back()
void madness::X_space::pop_back () inline
References active, n_orbitals, n_states, madness::response_space::pop_back(), x, and y.
push_back()
void madness::X_space::push_back (const vector_real_function_3d & vx, const vector_real_function_3d & vy) inline
References active, MADNESS_ASSERT, n_orbitals, n_states, num_orbitals(), madness::response_space::push_back(), x, and y.
reconstruct()
void madness::X_space::reconstruct () const inline
References active, madness::reconstruct(), to_vector(), and x.
reset_active()
void madness::X_space::reset_active () inline
References madness::response_space::active, active, n_states, x, and y.
Referenced by X_space().
set_active()
void madness::X_space::set_active (const std::list< size_t > & new_active) inline
References madness::response_space::active, active, x, and y.
to_vector()
auto madness::X_space::to_vector () const -> vector_real_function_3d inline
References active, m, num_orbitals(), x, and y.
Referenced by compress(), operator+=(), reconstruct(), truncate(), and truncate().
truncate() [1/2]
void madness::X_space::truncate () inline
References from_vector(), to_vector(), and madness::truncate().
truncate() [2/2]
void madness::X_space::truncate (double thresh) inline
References from_vector(), to_vector(), and madness::truncate().
zero_functions()
static X_space madness::X_space::zero_functions (World & world, size_t n_states, size_t n_orbitals) inline static
References X_space(), madness::WorldGopInterface::fence(), madness::World::gop, n_orbitals, and n_states.
Referenced by madness::X_vector::X_vector(), ground_exchange(), ground_exchange(), molresponseExchange(), and response_exchange().
Friends And Related Symbol Documentation
binary_apply
template<typename T > auto binary_apply (const X_space & A, const X_space & B, T & func) -> X_space friend
binary_inplace
template<class T > auto binary_inplace (X_space & A, const X_space & B, const T & func) friend
inner
auto inner (const X_space & A, const X_space & B) -> Tensor<double> friend
Computes the matrix elements between two response spaces.
cij=inner(ai,bj)
Parameters
A
B
Returns
Tensor<double>
inplace_apply
auto inplace_apply (X_space & A, const std::function< void(vector_real_function_3d &)> & func) -> void friend
oop_apply
auto oop_apply (const X_space & A, const std::function< vector_real_function_3d(const vector_real_function_3d &)> & func, bool fence = true) -> X_space friend
Apply a function to the X_space.
Parameters
A
func
Returns
operator* [1/6]
X_space operator* (const double & b, const X_space & A) friend
operator* [2/6]
auto operator* (const Function< double, 3 > & f, const X_space & A) -> X_space friend
operator* [3/6]
X_space operator* (const X_space & A, const double & b) friend
operator* [4/6]
X_space operator* (const X_space & A, const Function< double, 3 > & f) friend
operator* [5/6]
auto operator* (const X_space & A, const Tensor< double > & b) -> X_space friend
operator* [6/6]
X_space operator* (const X_space & B, const X_space & A) friend
operator+
auto operator+ (const X_space & A, const X_space & B) -> X_space friend
operator-
X_space operator- (const X_space & A, const X_space & B) friend
same_size
auto same_size (const X_space & A, const X_space & B) -> bool friend
Referenced by operator+=(), and madness::X_vector::operator+=().
size_orbitals
auto size_orbitals (const X_space & x) -> size_t friend
size_states
auto size_states (const X_space & x) -> size_t friend
Member Data Documentation
active
std::list<size_t> madness::X_space::active
Referenced by clear(), compress(), from_vector(), pop_back(), push_back(), reconstruct(), reset_active(), set_active(), and to_vector().
n_orbitals
size_t madness::X_space::n_orbitals private
Referenced by component_norm2s(), num_orbitals(), pop_back(), push_back(), and zero_functions().
n_states
size_t madness::X_space::n_states private
Referenced by component_norm2s(), num_states(), pop_back(), push_back(), reset_active(), and zero_functions().
x
response_space madness::X_space::x
Referenced by madness::X_vector::X_vector(), clear(), component_norm2s(), compress(), copy(), madness::X_vector::copy(), copy(), madness::copyToVector(), madness::copyToXspace(), from_vector(), molresponseExchange(), norm2s(), pop_back(), push_back(), reconstruct(), reset_active(), set_active(), and to_vector().
y
response_space madness::X_space::y
Referenced by madness::X_vector::X_vector(), clear(), copy(), madness::X_vector::copy(), copy(), madness::copyToVector(), madness::copyToXspace(), from_vector(), pop_back(), push_back(), reset_active(), set_active(), and to_vector().
The documentation for this struct was generated from the following file:
x_space.h