MADNESS: lbcost< T, NDIM > Struct Template Reference
lbcost< T, NDIM > Struct Template Reference
Public Member Functions
lbcost (double leaf_value=1.0, double parent_value=0.0)
lbcost (double leaf_value=1.0, double parent_value=0.0)
lbcost (double leaf_value=1.0, double parent_value=1.0)
lbcost (double leaf_value=1.0, double parent_value=1.0)
lbcost (double leaf_value=1.0, double parent_value=1.0)
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
double operator() (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node) const
Public Attributes
double leaf_value
double parent_value
Constructor & Destructor Documentation
lbcost() [1/5]
template<typename T , int NDIM> lbcost< T, NDIM >::lbcost (double leaf_value = 1.0, double parent_value = 0.0) inline
lbcost() [2/5]
template<typename T , int NDIM> lbcost< T, NDIM >::lbcost (double leaf_value = 1.0, double parent_value = 0.0) inline
lbcost() [3/5]
template<typename T , int NDIM> lbcost< T, NDIM >::lbcost (double leaf_value = 1.0, double parent_value = 1.0) inline
lbcost() [4/5]
template<typename T , int NDIM> lbcost< T, NDIM >::lbcost (double leaf_value = 1.0, double parent_value = 1.0) inline
lbcost() [5/5]
template<typename T , int NDIM> lbcost< T, NDIM >::lbcost (double leaf_value = 1.0, double parent_value = 1.0) inline
Member Function Documentation
operator()() [1/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
References madness::FunctionNode< T, NDIM >::is_leaf(), lbcost< T, NDIM >::leaf_value, madness::Key< NDIM >::level(), and lbcost< T, NDIM >::parent_value.
operator()() [2/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
References madness::FunctionNode< T, NDIM >::is_leaf(), lbcost< T, NDIM >::leaf_value, madness::Key< NDIM >::level(), and lbcost< T, NDIM >::parent_value.
operator()() [3/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
References madness::FunctionNode< T, NDIM >::is_leaf(), lbcost< T, NDIM >::leaf_value, madness::Key< NDIM >::level(), and lbcost< T, NDIM >::parent_value.
operator()() [4/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
References madness::FunctionNode< T, NDIM >::is_leaf(), lbcost< T, NDIM >::leaf_value, madness::Key< NDIM >::level(), and lbcost< T, NDIM >::parent_value.
operator()() [5/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
References madness::FunctionNode< T, NDIM >::is_leaf(), lbcost< T, NDIM >::leaf_value, and lbcost< T, NDIM >::parent_value.
operator()() [6/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
operator()() [7/7]
template<typename T , int NDIM> double lbcost< T, NDIM >::operator() (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node) const inline
Member Data Documentation
leaf_value
template<typename T , int NDIM> double lbcost< T, NDIM >::leaf_value
Referenced by lbcost< T, NDIM >::operator()().
parent_value
template<typename T , int NDIM> double lbcost< T, NDIM >::parent_value
Referenced by lbcost< T, NDIM >::operator()().
The documentation for this struct was generated from the following files:
DF.cc
rk.cc
tdse.cc
tdse.confused.cc
tdse4.cc
mraplot.cc
testsuite.cc