MADNESS: Ansatz0 Struct Reference
Ansatz0 Struct Reference
Public Member Functions
Ansatz0 (const double nuclear_charge)
double energy () const
Spinor make_bra (const Spinor &ket) const
Spinor make_guess (World &world) const
MatrixOperator make_Hd (World &world) const
MatrixOperator make_Hv (World &world) const
std::string name () const
MatrixOperator R (World &world) const
MatrixOperator Rinv (World &world) const
Public Member Functions inherited from AnsatzBase
AnsatzBase (const double Z, const double a)
virtual std::string filename () const
double get_cusp_a () const
virtual std::vector< Spinor > make_vbra (const std::vector< Spinor > &ket) const
virtual double mu (const double energy) const
virtual void normalize (Spinor &bra, Spinor &ket) const
virtual void normalize (Spinor &ket) const
virtual void normalize (std::vector< Spinor > &bra, std::vector< Spinor > &ket) const
virtual void normalize (std::vector< Spinor > &ket) const
Additional Inherited Members
Public Attributes inherited from AnsatzBase
double a =-1.3
int iansatz =0
double nuclear_charge =0.0
Constructor & Destructor Documentation
Ansatz0()
Ansatz0::Ansatz0 (const double nuclear_charge) inline
References AnsatzBase::a, and AnsatzBase::iansatz.
Member Function Documentation
energy()
double Ansatz0::energy () const inline
References alpha1, compute_gamma(), and AnsatzBase::nuclear_charge.
make_bra()
Spinor Ansatz0::make_bra (const Spinor & ket) const inline virtual
Implements AnsatzBase.
References Spinor::components, copy(), and Spinor::world().
make_guess()
Spinor Ansatz0::make_guess (World & world) const inline virtual
Implements AnsatzBase.
References alpha, Spinor::components, compute_gamma(), madness::constants::fine_structure_constant, madness::Vector< T, N >::normf(), AnsatzBase::nuclear_charge, one(), and Z.
make_Hd()
MatrixOperator Ansatz0::make_Hd (World & world) const inline virtual
Implements AnsatzBase.
References alpha1.
make_Hv()
MatrixOperator Ansatz0::make_Hv (World & world) const inline
References AnsatzBase::nuclear_charge.
name()
std::string Ansatz0::name () const inline virtual
Implements AnsatzBase.
R()
MatrixOperator Ansatz0::R (World & world) const inline virtual
Reimplemented from AnsatzBase.
References make_Hdiag(), one(), and one1().
Rinv()
MatrixOperator Ansatz0::Rinv (World & world) const inline virtual
Reimplemented from AnsatzBase.
References make_Hdiag(), one(), and one1().
The documentation for this struct was generated from the following file:
dirac-hatom.cc