MADNESS: madness::Molecule::GeometryParameters Struct Reference
madness::Molecule::GeometryParameters Struct Reference
#include <molecule.h>
Public Member Functions
GeometryParameters ()
GeometryParameters (const GeometryParameters &other)=default
GeometryParameters (World &world, const commandlineparser &parser)
std::string core_type () const
double eprec () const
std::vector< double > field () const
std::string get_tag () const override
bool no_orient () const
bool psp_calc () const
bool pure_ae () const
void set_derived_values (const commandlineparser &parser)
void set_global_convenience_options (const commandlineparser &parser)
std::string source_name () const
std::string source_type () const
double symtol () const
std::string units () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Static Public Member Functions
static std::string derive_source_type_from_name (const std::string name, const commandlineparser &parser)
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
GeometryParameters() [1/3]
madness::Molecule::GeometryParameters::GeometryParameters (const GeometryParameters & other) default
GeometryParameters() [2/3]
madness::Molecule::GeometryParameters::GeometryParameters (World & world, const commandlineparser & parser) inline
References e(), madness::QCCalculationParametersBase::print(), madness::QCCalculationParametersBase::read_input_and_commandline_options(), set_derived_values(), set_global_convenience_options(), and madness::Molecule::tag.
GeometryParameters() [3/3]
madness::Molecule::GeometryParameters::GeometryParameters () inline
References madness::QCCalculationParametersBase::ignore_unknown_keys, madness::QCCalculationParametersBase::ignore_unknown_keys_silently, and madness::QCCalculationParametersBase::throw_if_datagroup_not_found.
Member Function Documentation
core_type()
std::string madness::Molecule::GeometryParameters::core_type () const inline
Referenced by madness::Molecule::Molecule(), madness::SCF::derivatives(), madness::Molecule::get_structure(), madness::SCF::initial_guess(), and madness::SCF::make_nuclear_potential().
derive_source_type_from_name()
static std::string madness::Molecule::GeometryParameters::derive_source_type_from_name (const std::string name, const commandlineparser & parser) inline static
References madness::name(), and madness::commandlineparser::value().
Referenced by set_derived_values().
eprec()
double madness::Molecule::GeometryParameters::eprec () const inline
Referenced by madness::Molecule::get_eprec(), madness::MolecularEnergy::output_calc_info_schema(), madness::Molecule::read(), and madness::Molecule::read_xyz().
field()
std::vector< double > madness::Molecule::GeometryParameters::field () const inline
Referenced by madness::Molecule::Molecule().
get_tag()
std::string madness::Molecule::GeometryParameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
no_orient()
bool madness::Molecule::GeometryParameters::no_orient () const inline
Referenced by madness::Molecule::from_json(), madness::Molecule::get_structure(), and madness::Znemo::recompute_factors_and_potentials().
psp_calc()
bool madness::Molecule::GeometryParameters::psp_calc () const inline
Referenced by madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), madness::SCF::loadbal(), madness::SCF::make_nuclear_potential(), and madness::SCF::solve().
pure_ae()
bool madness::Molecule::GeometryParameters::pure_ae () const inline
Referenced by madness::Nuclear< T, NDIM >::Nuclear(), madness::SCF::apply_potential(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), madness::SCF::loadbal(), madness::SCF::make_nuclear_potential(), and madness::SCF::solve().
set_derived_values()
void madness::Molecule::GeometryParameters::set_derived_values (const commandlineparser & parser) inline
References derive_source_type_from_name(), madness::f, madness::Molecule::get_structure_library_path(), madness::QCCalculationParametersBase::is_user_defined(), madness::commandlineparser::key_exists(), MADNESS_EXCEPTION, madness::Molecule::position_stream_in_library(), madness::print(), madness::QCCalculationParametersBase::set_derived_value(), source_name(), source_type(), units(), and madness::commandlineparser::value().
Referenced by GeometryParameters().
set_global_convenience_options()
void madness::Molecule::GeometryParameters::set_global_convenience_options (const commandlineparser & parser) inline
References madness::commandlineparser::key_exists(), madness::QCCalculationParametersBase::set_user_defined_value(), and madness::commandlineparser::value().
Referenced by GeometryParameters().
source_name()
std::string madness::Molecule::GeometryParameters::source_name () const inline
Referenced by madness::Molecule::get_structure(), and set_derived_values().
source_type()
std::string madness::Molecule::GeometryParameters::source_type () const inline
Referenced by madness::Molecule::get_structure(), and set_derived_values().
symtol()
double madness::Molecule::GeometryParameters::symtol () const inline
Referenced by madness::Molecule::orient().
units()
std::string madness::Molecule::GeometryParameters::units () const inline
Referenced by madness::Molecule::from_json(), madness::Molecule::read(), madness::Molecule::read_xyz(), and set_derived_values().
The documentation for this struct was generated from the following file:
molecule.h