MADNESS: madness::spherical_box< NDIM > Struct Template Reference
madness::spherical_box< NDIM > Struct Template Reference
an 2-dimensional smooth mask that is 1 inside the radius and 0 outside
#include <masks_and_boxes.h>
Public Types
typedef Vector< double, NDIM > coordT
Public Member Functions
spherical_box (const double r, const double deviation, const coordT o={0.0, 0.0, 0.0}, const coordT B_dir={0.0, 0.0, 1.0})
double operator() (const coordT &xyz) const
Static Public Member Functions
static double compute_tightness (const double deviation_at_dot_8_radius)
compute the tightness parameter given the deviation at 0.8 radius
Public Attributes
const coordT B_direction =coordT(0.0)
const coordT offset =coordT(0.0)
const double radius
const double tightness =11.5
Detailed Description
template<std::size_t NDIM>
struct madness::spherical_box< NDIM >
an 2-dimensional smooth mask that is 1 inside the radius and 0 outside
Member Typedef Documentation
coordT
template<std::size_t NDIM> typedef Vector<double,NDIM> madness::spherical_box< NDIM >::coordT
Constructor & Destructor Documentation
spherical_box()
template<std::size_t NDIM> madness::spherical_box< NDIM >::spherical_box (const double r, const double deviation, const coordT o = {0.0,0.0,0.0}, const coordT B_dir = {0.0,0.0,1.0}) inline
Member Function Documentation
compute_tightness()
template<std::size_t NDIM> static double madness::spherical_box< NDIM >::compute_tightness (const double deviation_at_dot_8_radius) inline static
compute the tightness parameter given the deviation at 0.8 radius
operator()()
template<std::size_t NDIM> double madness::spherical_box< NDIM >::operator() (const coordT & xyz) const inline
References madness::spherical_box< NDIM >::B_direction, madness::inner(), madness::Vector< T, N >::normf(), madness::spherical_box< NDIM >::offset, madness::spherical_box< NDIM >::radius, and madness::spherical_box< NDIM >::tightness.
Member Data Documentation
B_direction
template<std::size_t NDIM> const coordT madness::spherical_box< NDIM >::B_direction =coordT(0.0)
Referenced by madness::spherical_box< NDIM >::operator()().
offset
template<std::size_t NDIM> const coordT madness::spherical_box< NDIM >::offset =coordT(0.0)
Referenced by madness::spherical_box< NDIM >::operator()().
radius
template<std::size_t NDIM> const double madness::spherical_box< NDIM >::radius
Referenced by madness::spherical_box< NDIM >::operator()().
tightness
template<std::size_t NDIM> const double madness::spherical_box< NDIM >::tightness =11.5
Referenced by madness::spherical_box< NDIM >::operator()().
The documentation for this struct was generated from the following file:
masks_and_boxes.h