MADNESS: madness::KernelRange::Data Struct Reference
madness::KernelRange::Data Struct Reference
Public Member Functions
Data (unsigned int n, Restrictor r)
int iextent_x2 (double epsilon) const
Static Public Member Functions
static int compute_iextent_x2 (int N, const Restrictor &restrictor, double epsilon)
Public Attributes
int iextent_x2_default
unsigned int N
Restrictor restrictor
Constructor & Destructor Documentation
Data()
madness::KernelRange::Data::Data (unsigned int n, Restrictor r) inline
Member Function Documentation
compute_iextent_x2()
static int madness::KernelRange::Data::compute_iextent_x2 (int N, const Restrictor & restrictor, double epsilon) inline static
Returns
max value of |x-y| (rounded up, in units of 1/2) for which r(N/2 - |x-y|) is greater than epsilon
References std::abs(), madness::arg(), epsilon, madness::KernelRange::Hard, MADNESS_ASSERT, MADNESS_EXCEPTION, N, restrictor, madness::KernelRange::Restrictor::sigma(), madness::KernelRange::SoftErf, madness::KernelRange::Restrictor::type(), madness::KernelRange::value(), and madness::KernelRange::Restrictor::value().
Referenced by iextent_x2().
iextent_x2()
int madness::KernelRange::Data::iextent_x2 (double epsilon) const inline
Returns
max value of |x-y| (rounded up, in units of 1/2) for which r(N/2 - |x-y|) is greater than epsilon
References compute_iextent_x2(), epsilon, madness::KernelRange::extent_default_epsilon, iextent_x2_default, N, and restrictor.
Member Data Documentation
iextent_x2_default
int madness::KernelRange::Data::iextent_x2_default
Referenced by iextent_x2().
N
unsigned int madness::KernelRange::Data::N
Referenced by compute_iextent_x2(), and iextent_x2().
restrictor
Restrictor madness::KernelRange::Data::restrictor
Referenced by compute_iextent_x2(), and iextent_x2().
The documentation for this struct was generated from the following file:
kernelrange.h