MADNESS: madness::archive::ArchiveImpl< Archive, T, Enabler > Struct Template Reference
madness::archive::ArchiveImpl< Archive, T, Enabler > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Default implementations of wrap_store and wrap_load.
#include <archive.h>
Static Public Member Functions
template<typename A = Archive, typename = std::enable_if_t<is_input_archive_v<A> && has_nonmember_load_v<T,Archive>>>
static const Archive & wrap_load (const Archive &ar, const T &t)
Load an object sandwiched between its preamble and postamble.
template<typename A = Archive, typename = std::enable_if_t<is_output_archive_v<A> && has_nonmember_store_v<T,Archive>>>
static const Archive & wrap_store (const Archive &ar, const T &t)
Store an object sandwiched between its preamble and postamble.
Detailed Description
template<class Archive, class T, typename Enabler>
struct madness::archive::ArchiveImpl< Archive, T, Enabler >
Default implementations of wrap_store and wrap_load.
"Wrapping" refers to the addition of the type's preamble and postamble around the data to provide runtime type-checking.
Template Parameters
Archive The archive type.
T The data type.
Member Function Documentation
wrap_load()
template<class Archive , class T , typename Enabler > template<typename A = Archive, typename = std::enable_if_t<is_input_archive_v<A> && has_nonmember_load_v<T,Archive>>> static const Archive & madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_load (const Archive & ar, const T & t) inline static
Load an object sandwiched between its preamble and postamble.
Parameters
[in] ar The archive.
[in] t The data.
Returns
The archive.
References madness::archive::ArchiveLoadImpl< Archive, T, Enabler >::load(), MAD_ARCHIVE_DEBUG, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_load(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_load(), and T().
Referenced by madness::archive::operator&(), and madness::archive::operator>>().
wrap_store()
template<class Archive , class T , typename Enabler > template<typename A = Archive, typename = std::enable_if_t<is_output_archive_v<A> && has_nonmember_store_v<T,Archive>>> static const Archive & madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_store (const Archive & ar, const T & t) inline static
Store an object sandwiched between its preamble and postamble.
Parameters
[in] ar The archive.
[in] t The data.
Returns
The archive.
References MAD_ARCHIVE_DEBUG, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_store(), and madness::archive::ArchiveStoreImpl< Archive, T, Enabler >::store().
Referenced by madness::archive::operator&().
The documentation for this struct was generated from the following file:
archive.h