MADNESS: madness::detail::adqtest Struct Reference
madness::detail::adqtest Struct Reference
#include <adquad.h>
Public Types
typedef double returnT
Public Member Functions
double operator() (double x) const
Static Public Member Functions
static double exact ()
static bool runtest ()
Member Typedef Documentation
returnT
typedef double madness::detail::adqtest::returnT
Member Function Documentation
exact()
static double madness::detail::adqtest::exact () inline static
References pi.
Referenced by runtest().
operator()()
double madness::detail::adqtest::operator() (double x) const inline
runtest()
static bool madness::detail::adqtest::runtest () inline static
References std::abs(), madness::adq(), e(), exact(), and test().
The documentation for this struct was generated from the following file:
adquad.h