MADNESS: CoreFittingTarget Struct Reference
CoreFittingTarget Struct Reference
Public Member Functions
CoreFittingTarget (World &world, Calculation &calc, CorePotential &cp)
tensorT gradient (const tensorT &x)
Should return the derivative of the function.
bool provides_gradient () const
Override this to return true if the derivative is implemented.
double value (const tensorT &x)
Should return the value of the objective function.
Public Member Functions inherited from madness::OptimizationTargetInterface
virtual ~OptimizationTargetInterface ()
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
Public Attributes
Calculation & calc
CorePotential & cp
tensorT lastx
double r
World & world
double xsq
Constructor & Destructor Documentation
CoreFittingTarget()
CoreFittingTarget::CoreFittingTarget (World & world, Calculation & calc, CorePotential & cp) inline
Member Function Documentation
gradient()
tensorT CoreFittingTarget::gradient (const tensorT & x) inline virtual
Should return the derivative of the function.
Reimplemented from madness::OptimizationTargetInterface.
References madness::CorePotential::alpha, calc, Calculation::calc_deriv(), cp, madness::WorldGopInterface::fence(), madness::g, madness::World::gop, print(), r, tensor2vec(), value(), and world.
provides_gradient()
bool CoreFittingTarget::provides_gradient () const inline virtual
Override this to return true if the derivative is implemented.
Reimplemented from madness::OptimizationTargetInterface.
value()
double CoreFittingTarget::value (const tensorT & x) inline virtual
Should return the value of the objective function.
Implements madness::OptimizationTargetInterface.
References madness::CorePotential::alpha, Calculation::amo, Calculation::bmo, calc, Calculation::calc_optimal_coeffs(), Calculation::compute_residuals(), madness::copy(), cp, e(), madness::WorldGopInterface::fence(), madness::World::gop, lastx, Calculation::nbeta, print(), r, Calculation::spin_restricted, madness::Tensor< T >::sumsq(), tensor2vec(), Calculation::vamo, Calculation::vbmo, world, and xsq.
Referenced by gradient().
Member Data Documentation
calc
Calculation& CoreFittingTarget::calc
Referenced by gradient(), and value().
cp
CorePotential& CoreFittingTarget::cp
Referenced by gradient(), and value().
lastx
tensorT CoreFittingTarget::lastx mutable
Referenced by value().
r
double CoreFittingTarget::r mutable
Referenced by gradient(), and value().
world
World& CoreFittingTarget::world
Referenced by gradient(), and value().
xsq
double CoreFittingTarget::xsq mutable
Referenced by value().
The documentation for this struct was generated from the following file:
mcpfit.cc