MADNESS: madness::CC_vecfunction Struct Reference
madness::CC_vecfunction Struct Reference
A helper structure which holds a map of functions.
#include <CCStructures.h>
Public Types
typedef std::map< std::size_t, CCFunction< double, 3 > > CC_functionmap
Public Member Functions
CC_vecfunction ()
CC_vecfunction (const CC_vecfunction &other)
copy ctor (shallow)
CC_vecfunction (const FuncType type_)
CC_vecfunction (const std::vector< CCFunction< double, 3 > > &v)
CC_vecfunction (const std::vector< CCFunction< double, 3 > > &v, const FuncType type_)
CC_vecfunction (const vector_real_function_3d &v)
CC_vecfunction (const vector_real_function_3d &v, const FuncType &type)
CC_vecfunction (const vector_real_function_3d &v, const FuncType &type, const size_t &freeze)
vector_real_function_3d get_vecfunction () const
Returns all the functions of the map as vector.
hashT hash () const
void insert (const size_t &i, const CCFunction< double, 3 > &f)
setter
bool is_converged (const double econv, const double dconv) const
std::string name (const int ex) const
excitation irrep (direct product of x function and corresponding orbital)
CCFunction< double, 3 > & operator() (const CCFunction< double, 3 > &i)
getter
const CCFunction< double, 3 > & operator() (const CCFunction< double, 3 > &i) const
getter
CCFunction< double, 3 > & operator() (const size_t &i)
getter
const CCFunction< double, 3 > & operator() (const size_t &i) const
getter
CC_vecfunction operator* (const double &fac) const
scalar multiplication
bool operator< (const CC_vecfunction &b) const
operator needed for sort operation (sorted by omega values)
CC_vecfunction & operator= (const CC_vecfunction &other)
assignment operator, shallow wrt the functions
void plot (const std::string &msg="") const
void print_size (const std::string &msg="!?not assigned!?") const
Print the memory of which is used by all the functions in the map.
void reconstruct () const
void save_restartdata (World &world, std::string filename) const
void scale (const double &factor)
scaling (inplace)
template<typename Archive >
void serialize (const Archive &ar)
void set_functions (const vector_real_function_3d &v, const FuncType &type, const size_t &freeze)
setter
size_t size () const
Get the size vector (number of functions in the map)
Static Public Member Functions
static CC_vecfunction load_restartdata (World &world, std::string filename)
Public Attributes
double current_error
excitation energy
double delta
CC_functionmap functions
std::string irrep = "null"
double omega
FuncType type
Friends
CC_vecfunction copy (const CC_vecfunction &other)
returns a deep copy (void shallow copy errors)
Detailed Description
A helper structure which holds a map of functions.
Member Typedef Documentation
CC_functionmap
typedef std::map<std::size_t, CCFunction<double,3> > madness::CC_vecfunction::CC_functionmap
Constructor & Destructor Documentation
CC_vecfunction() [1/8]
madness::CC_vecfunction::CC_vecfunction () inline
Referenced by operator*().
CC_vecfunction() [2/8]
madness::CC_vecfunction::CC_vecfunction (const FuncType type_) inline
CC_vecfunction() [3/8]
madness::CC_vecfunction::CC_vecfunction (const vector_real_function_3d & v) inline
References functions, type, and v.
CC_vecfunction() [4/8]
madness::CC_vecfunction::CC_vecfunction (const std::vector< CCFunction< double, 3 > > & v) inline
References functions, and v.
CC_vecfunction() [5/8]
madness::CC_vecfunction::CC_vecfunction (const vector_real_function_3d & v, const FuncType & type) inline
References functions, type, and v.
CC_vecfunction() [6/8]
madness::CC_vecfunction::CC_vecfunction (const vector_real_function_3d & v, const FuncType & type, const size_t & freeze) inline
References functions, type, and v.
CC_vecfunction() [7/8]
madness::CC_vecfunction::CC_vecfunction (const std::vector< CCFunction< double, 3 > > & v, const FuncType type_) inline
References functions, and v.
CC_vecfunction() [8/8]
madness::CC_vecfunction::CC_vecfunction (const CC_vecfunction & other) inline
copy ctor (shallow)
Member Function Documentation
get_vecfunction()
vector_real_function_3d madness::CC_vecfunction::get_vecfunction () const inline
Returns all the functions of the map as vector.
References functions.
Referenced by madness::TDHF::get_tda_potential(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), madness::TDHF::make_bra(), madness::TDHF::make_cis_matrix(), madness::CCConvolutionOperator< T, NDIM >::operator()(), madness::MacroTaskSinglesPotentialEx::operator()(), madness::MacroTaskSinglesPotentialGs::operator()(), operator*(), madness::TDHF::oscillator_strength_length(), madness::TDHF::oscillator_strength_velocity(), madness::TDHF::prepare_calculation(), and madness::CC2::solve_cc2().
hash()
hashT madness::CC_vecfunction::hash () const inline
References madness::f, functions, madness::hash_combine(), madness::hash_value(), and type.
insert()
void madness::CC_vecfunction::insert (const size_t & i, const CCFunction< double, 3 > & f) inline
setter
References madness::f, and functions.
Referenced by madness::CC2::initialize_singles_to_zero().
is_converged()
bool madness::CC_vecfunction::is_converged (const double econv, const double dconv) const inline
References current_error, and delta.
Referenced by madness::TDHF::solve_cis().
load_restartdata()
static CC_vecfunction madness::CC_vecfunction::load_restartdata (World & world, std::string filename) inline static
References madness::filename.
Referenced by madness::CC2::initialize_singles(), and madness::TDHF::solve_cis().
name()
std::string madness::CC_vecfunction::name (const int ex) const inline
excitation irrep (direct product of x function and corresponding orbital)
References madness::name(), and type.
Referenced by madness::CC2::iterate_singles().
operator()() [1/4]
CCFunction< double, 3 > & madness::CC_vecfunction::operator() (const CCFunction< double, 3 > & i) inline
getter
References functions, and madness::CCFunction< T, NDIM >::i.
operator()() [2/4]
const CCFunction< double, 3 > & madness::CC_vecfunction::operator() (const CCFunction< double, 3 > & i) const inline
getter
References functions, and madness::CCFunction< T, NDIM >::i.
operator()() [3/4]
CCFunction< double, 3 > & madness::CC_vecfunction::operator() (const size_t & i) inline
getter
References functions.
operator()() [4/4]
const CCFunction< double, 3 > & madness::CC_vecfunction::operator() (const size_t & i) const inline
getter
References functions.
operator*()
CC_vecfunction madness::CC_vecfunction::operator* (const double & fac) const inline
scalar multiplication
References CC_vecfunction(), functions, get_vecfunction(), and type.
operator<()
bool madness::CC_vecfunction::operator< (const CC_vecfunction & b) const inline
operator needed for sort operation (sorted by omega values)
References b, and omega.
operator=()
CC_vecfunction & madness::CC_vecfunction::operator= (const CC_vecfunction & other) inline
assignment operator, shallow wrt the functions
References current_error, delta, functions, irrep, omega, and type.
plot()
void madness::CC_vecfunction::plot (const std::string & msg = "") const inline
References functions.
Referenced by madness::TDHF::solve_cis().
print_size()
void madness::CC_vecfunction::print_size (const std::string & msg = "!?not assigned!?") const
Print the memory of which is used by all the functions in the map.
References functions.
reconstruct()
void madness::CC_vecfunction::reconstruct () const inline
References functions.
Referenced by madness::CC2::iterate_lrcc2_pairs(), and madness::CC2::solve_cc2().
save_restartdata()
void madness::CC_vecfunction::save_restartdata (World & world, std::string filename) const inline
References madness::filename.
Referenced by madness::CC2::solve_cc2().
scale()
void madness::CC_vecfunction::scale (const double & factor) inline
scaling (inplace)
References functions.
serialize()
template<typename Archive > void madness::CC_vecfunction::serialize (const Archive & ar) inline
References current_error, delta, functions, irrep, omega, size(), type, and madness::vec().
set_functions()
void madness::CC_vecfunction::set_functions (const vector_real_function_3d & v, const FuncType & type, const size_t & freeze) inline
setter
References functions, type, and v.
Referenced by madness::TDHF::transform().
size()
size_t madness::CC_vecfunction::size () const inline
Get the size vector (number of functions in the map)
References functions.
Referenced by madness::CCPairBuilder::complete_pair_with_low_rank_parts(), madness::TDHF::get_active_mo_bra(), madness::TDHF::get_active_mo_ket(), madness::CC2::iterate_singles(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_virtuals(), serialize(), madness::CC2::solve(), madness::CC2::solve_cc2(), madness::CC2::solve_cispd(), and madness::CCConvolutionOperator< T, NDIM >::update_elements().
Friends And Related Symbol Documentation
copy
CC_vecfunction copy (const CC_vecfunction & other) friend
returns a deep copy (void shallow copy errors)
Member Data Documentation
current_error
double madness::CC_vecfunction::current_error
excitation energy
Referenced by is_converged(), operator=(), and serialize().
delta
double madness::CC_vecfunction::delta
Referenced by is_converged(), operator=(), and serialize().
functions
CC_functionmap madness::CC_vecfunction::functions
Referenced by CC_vecfunction(), CC_vecfunction(), CC_vecfunction(), CC_vecfunction(), CC_vecfunction(), madness::TDHF::get_tda_potential(), get_vecfunction(), hash(), insert(), madness::CC2::iterate_singles(), madness::CCConvolutionOperator< T, NDIM >::operator()(), operator()(), operator()(), operator()(), operator()(), operator*(), operator=(), plot(), print_size(), reconstruct(), scale(), serialize(), set_functions(), size(), and madness::CCConvolutionOperator< T, NDIM >::update_elements().
irrep
std::string madness::CC_vecfunction::irrep = "null"
Referenced by operator=(), and serialize().
omega
double madness::CC_vecfunction::omega
Referenced by madness::CC2::iterate_adc2_pairs(), madness::CC2::iterate_singles(), madness::CCPairBuilder::make_bare_pair(), operator<(), operator=(), madness::TDHF::oscillator_strength_length(), madness::TDHF::oscillator_strength_velocity(), serialize(), madness::CC2::solve(), madness::CC2::solve_cispd(), madness::CC2::solve_lrcc2(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
type
FuncType madness::CC_vecfunction::type
Referenced by CC_vecfunction(), CC_vecfunction(), CC_vecfunction(), hash(), madness::CC2::initialize_pairs(), madness::CC2::iterate_adc2_pairs(), madness::CC2::iterate_adc2_singles(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_lrcc2_singles(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), name(), madness::CCConvolutionOperator< T, NDIM >::operator()(), operator*(), operator=(), serialize(), set_functions(), madness::CC2::solve_cc2(), madness::CC2::solve_cispd(), madness::TDHF::transform(), and madness::CCConvolutionOperator< T, NDIM >::update_elements().
The documentation for this struct was generated from the following files:
CCStructures.h
CCStructures.cc