MADNESS: madness::Recordlist< keyT > Struct Template Reference
madness::Recordlist< keyT > Struct Template Reference
#include <cloud.h>
Public Types
template<typename T >
using has_member_hash = madness::meta::is_detected< member_hash_t, T >
template<typename T >
using has_member_id = madness::meta::is_detected< member_id_t, T >
template<typename T >
using member_hash_t = decltype(std::declval< T >().hash())
template<typename T >
using member_id_t = decltype(std::declval< T >().id())
Public Member Functions
Recordlist ()
Recordlist (const keyT &key)
Recordlist (const Recordlist &other)
Recordlist & operator+= (const keyT &key)
Recordlist & operator+= (const Recordlist &list2)
keyT pop_front_and_return ()
std::size_t size () const
Static Public Member Functions
template<typename T , std::size_t NDIM>
static keyT compute_record (const Function< T, NDIM > &arg)
template<typename T , std::size_t NDIM>
static keyT compute_record (const FunctionImpl< T, NDIM > *arg)
template<typename T , std::size_t NDIM>
static keyT compute_record (const std::shared_ptr< madness::FunctionImpl< T, NDIM >> &arg)
template<typename T >
static keyT compute_record (const std::shared_ptr< T > &arg)
template<typename keyQ , typename valueT >
static keyT compute_record (const std::shared_ptr< WorldContainer< keyQ, valueT >> &arg)
template<typename T >
static keyT compute_record (const std::vector< T > &arg)
template<typename T >
static keyT compute_record (const T &arg)
template<typename T >
static keyT compute_record (const Tensor< T > &arg)
template<typename keyQ , typename valueT >
static keyT compute_record (const WorldContainer< keyQ, valueT > &arg)
Public Attributes
std::list< keyT > list
Friends
std::ostream & operator<< (std::ostream &os, const Recordlist &arg)
Member Typedef Documentation
has_member_hash
template<typename keyT > template<typename T > using madness::Recordlist< keyT >::has_member_hash = madness::meta::is_detected<member_hash_t, T>
has_member_id
template<typename keyT > template<typename T > using madness::Recordlist< keyT >::has_member_id = madness::meta::is_detected<member_id_t, T>
member_hash_t
template<typename keyT > template<typename T > using madness::Recordlist< keyT >::member_hash_t = decltype(std::declval<T>().hash())
member_id_t
template<typename keyT > template<typename T > using madness::Recordlist< keyT >::member_id_t = decltype(std::declval<T>().id())
Constructor & Destructor Documentation
Recordlist() [1/3]
template<typename keyT > madness::Recordlist< keyT >::Recordlist () inline
Recordlist() [2/3]
template<typename keyT > madness::Recordlist< keyT >::Recordlist (const keyT & key) inline explicit
Recordlist() [3/3]
template<typename keyT > madness::Recordlist< keyT >::Recordlist (const Recordlist< keyT > & other) inline
Member Function Documentation
compute_record() [1/9]
template<typename keyT > template<typename T , std::size_t NDIM> static keyT madness::Recordlist< keyT >::compute_record (const Function< T, NDIM > & arg) inline static
References madness::arg(), and madness::hash_value().
Referenced by madness::Cloud::store_other().
compute_record() [2/9]
template<typename keyT > template<typename T , std::size_t NDIM> static keyT madness::Recordlist< keyT >::compute_record (const FunctionImpl< T, NDIM > * arg) inline static
References madness::arg(), and madness::hash_value().
compute_record() [3/9]
template<typename keyT > template<typename T , std::size_t NDIM> static keyT madness::Recordlist< keyT >::compute_record (const std::shared_ptr< madness::FunctionImpl< T, NDIM >> & arg) inline static
References madness::arg(), and madness::hash_value().
compute_record() [4/9]
template<typename keyT > template<typename T > static keyT madness::Recordlist< keyT >::compute_record (const std::shared_ptr< T > & arg) inline static
References madness::arg(), and madness::Recordlist< keyT >::compute_record().
Referenced by madness::Recordlist< keyT >::compute_record().
compute_record() [5/9]
template<typename keyT > template<typename keyQ , typename valueT > static keyT madness::Recordlist< keyT >::compute_record (const std::shared_ptr< WorldContainer< keyQ, valueT >> & arg) inline static
References madness::arg(), and madness::hash_value().
compute_record() [6/9]
template<typename keyT > template<typename T > static keyT madness::Recordlist< keyT >::compute_record (const std::vector< T > & arg) inline static
References madness::arg(), and madness::hash_range().
compute_record() [7/9]
template<typename keyT > template<typename T > static keyT madness::Recordlist< keyT >::compute_record (const T & arg) inline static
References madness::arg(), madness::hash_combine(), madness::hash_value(), and T().
compute_record() [8/9]
template<typename keyT > template<typename T > static keyT madness::Recordlist< keyT >::compute_record (const Tensor< T > & arg) inline static
References madness::arg(), and madness::hash_value().
compute_record() [9/9]
template<typename keyT > template<typename keyQ , typename valueT > static keyT madness::Recordlist< keyT >::compute_record (const WorldContainer< keyQ, valueT > & arg) inline static
References madness::arg(), and madness::hash_value().
operator+=() [1/2]
template<typename keyT > Recordlist& madness::Recordlist< keyT >::operator+= (const keyT & key) inline
References madness::Recordlist< keyT >::list.
operator+=() [2/2]
template<typename keyT > Recordlist& madness::Recordlist< keyT >::operator+= (const Recordlist< keyT > & list2) inline
References madness::Recordlist< keyT >::list.
pop_front_and_return()
template<typename keyT > keyT madness::Recordlist< keyT >::pop_front_and_return () inline
References madness::Recordlist< keyT >::list.
Referenced by madness::Cloud::do_load().
size()
template<typename keyT > std::size_t madness::Recordlist< keyT >::size () const inline
References madness::Recordlist< keyT >::list.
Friends And Related Function Documentation
operator<<
template<typename keyT > std::ostream& operator<< (std::ostream & os, const Recordlist< keyT > & arg) friend
Member Data Documentation
list
template<typename keyT > std::list<keyT> madness::Recordlist< keyT >::list
Referenced by madness::Cloud::clear_cache(), madness::Cloud::is_in_container(), madness::Recordlist< keyT >::operator+=(), madness::Recordlist< keyT >::pop_front_and_return(), and madness::Recordlist< keyT >::size().
The documentation for this struct was generated from the following file:
cloud.h