MADNESS: madness::CCSize Struct Reference
madness::CCSize Struct Reference
print accumulated size of all functions
#include <CCStructures.h>
Public Member Functions
CCSize ()=default
template<typename... Args>
void add (const Args &... args)
variadic template parameters to add the size of all functions and pairs
void add_helper (const std::vector< CCPair > &vp)
template<typename T , std::size_t NDIM>
void add_helper (const std::vector< Function< T, NDIM > > &v)
void print (World &world, const std::string msg="") const
Public Attributes
double size_local =0
Detailed Description
print accumulated size of all functions
Constructor & Destructor Documentation
CCSize()
madness::CCSize::CCSize () default
Member Function Documentation
add()
template<typename... Args> void madness::CCSize::add (const Args &... args) inline
variadic template parameters to add the size of all functions and pairs
References add_helper().
Referenced by madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_singles(), and madness::CC2::solve_mp2_coupled().
add_helper() [1/2]
void madness::CCSize::add_helper (const std::vector< CCPair > & vp) inline
References madness::get_size(), madness::get_size_local(), p(), and size_local.
add_helper() [2/2]
template<typename T , std::size_t NDIM> void madness::CCSize::add_helper (const std::vector< Function< T, NDIM > > & v) inline
References madness::get_size_local(), size_local, and v.
Referenced by add().
print()
void madness::CCSize::print (World & world, const std::string msg = "") const inline
References madness::WorldGopInterface::fence(), madness::World::gop, madness::print(), madness::World::rank(), size_local, and madness::WorldGopInterface::sum().
Referenced by madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_singles(), and madness::CC2::solve_mp2_coupled().
Member Data Documentation
size_local
double madness::CCSize::size_local =0
Referenced by add_helper(), add_helper(), and print().
The documentation for this struct was generated from the following file:
CCStructures.h