MADNESS: myunaryop_square< T, NDIM > Struct Template Reference
myunaryop_square< T, NDIM > Struct Template Reference
Public Types
typedef T resultT
typedef T resultT
Public Member Functions
Tensor< T > operator() (const Key< NDIM > &key, const Tensor< T > &t) const
Tensor< T > operator() (const Key< NDIM > &key, const Tensor< T > &t) const
template<typename Archive >
void serialize (Archive &ar)
template<typename Archive >
void serialize (Archive &ar)
Member Typedef Documentation
resultT [1/2]
template<typename T , int NDIM> typedef T myunaryop_square< T, NDIM >::resultT
resultT [2/2]
template<typename T , int NDIM> typedef T myunaryop_square< T, NDIM >::resultT
Member Function Documentation
operator()() [1/2]
template<typename T , int NDIM> Tensor< T > myunaryop_square< T, NDIM >::operator() (const Key< NDIM > & key, const Tensor< T > & t) const inline
References madness::copy(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), and T().
operator()() [2/2]
template<typename T , int NDIM> Tensor< T > myunaryop_square< T, NDIM >::operator() (const Key< NDIM > & key, const Tensor< T > & t) const inline
References madness::copy(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), and T().
serialize() [1/2]
template<typename T , int NDIM> template<typename Archive > void myunaryop_square< T, NDIM >::serialize (Archive & ar) inline
serialize() [2/2]
template<typename T , int NDIM> template<typename Archive > void myunaryop_square< T, NDIM >::serialize (Archive & ar) inline
The documentation for this struct was generated from the following files:
test_he.cc
testsuite.cc