MADNESS: BoysLocalization Struct Reference
BoysLocalization Struct Reference
Public Member Functions
BoysLocalization ()
BoysLocalization (unsigned int norbs)
double DIP (const real_tensor &dip, int i, int j, int k, int l)
real_tensor operator() (World &world, const vector_real_function_3d &mo, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true)
void set_size (unsigned int norbs)
Public Attributes
std::vector< int > aset
Constructor & Destructor Documentation
BoysLocalization() [1/2]
BoysLocalization::BoysLocalization () inline
BoysLocalization() [2/2]
BoysLocalization::BoysLocalization (unsigned int norbs) inline
References aset.
Member Function Documentation
DIP()
double BoysLocalization::DIP (const real_tensor & dip, int i, int j, int k, int l) inline
References k.
Referenced by operator()().
operator()()
real_tensor BoysLocalization::operator() (World & world, const vector_real_function_3d & mo, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true) inline
References madness::_(), std::abs(), aset, axis, madness::WorldGopInterface::broadcast(), c, madness::copy(), DIP(), doit(), drot(), drot3(), e(), madness::g, madness::World::gop, h(), madness::matrix_inner(), madness::mul_sparse(), ndone, madness::print(), madness::Tensor< T >::ptr(), madness::RandomValue< double >(), madness::World::rank(), madness::Tensor< T >::scale(), madness::BaseTensor::size(), sum, thresh, and madness::transpose().
set_size()
void BoysLocalization::set_size (unsigned int norbs) inline
References aset.
Referenced by MiniDFT::doit().
Member Data Documentation
aset
std::vector<int> BoysLocalization::aset
Referenced by BoysLocalization(), operator()(), and set_size().
The documentation for this struct was generated from the following file:
preal.cc