MADNESS: madness::CISData Struct Reference
madness::CISData Struct Reference
POD for CIS excitation.
#include <PNOStructures.h>
Public Member Functions
CISData ()
CISData (const size_t &n, const double &o, const vector_real_function_3d &f)
bool initialized () const
Public Attributes
vector_real_function_3d Kx =vector_real_function_3d()
int number =-1
double omega =0.0
vector_real_function_3d Vx =vector_real_function_3d()
vector_real_function_3d x =vector_real_function_3d()
Detailed Description
POD for CIS excitation.
Constructor & Destructor Documentation
CISData() [1/2]
madness::CISData::CISData () inline
CISData() [2/2]
madness::CISData::CISData (const size_t & n, const double & o, const vector_real_function_3d & f) inline
Member Function Documentation
initialized()
bool madness::CISData::initialized () const inline
References number, omega, and x.
Referenced by madness::PNOPairs::is_consistent().
Member Data Documentation
Kx
vector_real_function_3d madness::CISData::Kx =vector_real_function_3d()
Referenced by madness::PNO::compute_cispd_fluctuation_matrix(), and madness::PNO::iterate_pairs_internal().
number
int madness::CISData::number =-1
Referenced by initialized(), and madness::PNO::iterate_pairs_internal().
omega
double madness::CISData::omega =0.0
Referenced by initialized(), madness::PNO::iterate_pairs_internal(), madness::PNO::solve_cispd(), madness::PNO::t_solve(), and madness::PNO::update_pno().
Vx
vector_real_function_3d madness::CISData::Vx =vector_real_function_3d()
Referenced by madness::PNO::compute_cispd_fluctuation_matrix(), madness::PNO::compute_cispd_fluctuation_potential(), and madness::PNO::iterate_pairs_internal().
x
vector_real_function_3d madness::CISData::x =vector_real_function_3d()
Referenced by madness::PNOPairs::PNOPairs(), madness::PNO::compute_cispd_fluctuation_matrix(), madness::PNO::compute_cispd_fluctuation_potential(), madness::PNO::grow_rank(), madness::PNO::initialize_pairs(), initialized(), madness::PNO::iterate_pairs_internal(), and madness::PNO::t_solve().
The documentation for this struct was generated from the following file:
PNOStructures.h