MADNESS: madness::archive::ArchiveStoreImpl< Archive, T, Enabler > Struct Template Reference
madness::archive::ArchiveStoreImpl< Archive, T, Enabler > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Default store of an object via serialize(ar, t).
#include <archive.h>
Static Public Member Functions
template<typename A = Archive, typename U = T>
static std::enable_if_t< is_output_archive_v< A > &&!std::is_function< U >::value &&(has_member_serialize_v< U, A >||has_nonmember_serialize_v< U, A >||has_freestanding_serialize_v< U, A >||has_freestanding_default_serialize_v< U, A >), void > store (const A &ar, const U &t)
template<typename A = Archive, typename U = T, typename = std::enable_if_t<is_output_archive_v<A> && std::is_function<U>::value>>
static void store (const Archive &ar, const U &t)
Store function reference as a function pointer.
Detailed Description
template<class Archive, class T, typename Enabler>
struct madness::archive::ArchiveStoreImpl< Archive, T, Enabler >
Default store of an object via serialize(ar, t).
Template Parameters
Archive The archive type.
T The data type.
Member Function Documentation
store() [1/2]
template<class Archive , class T , typename Enabler > template<typename A = Archive, typename U = T> static std::enable_if_t<is_output_archive_v<A> && !std::is_function<U>::value && (has_member_serialize_v<U,A> || has_nonmember_serialize_v<U,A> || has_freestanding_serialize_v<U, A> || has_freestanding_default_serialize_v<U, A>), void> madness::archive::ArchiveStoreImpl< Archive, T, Enabler >::store (const A & ar, const U & t) inline static
References madness::archive::default_serialize(), MAD_ARCHIVE_DEBUG, madness::archive::serialize(), and madness::archive::ArchiveSerializeImpl< Archive, T, Enabler >::serialize().
Referenced by madness::archive::ArchiveStoreImpl< Archive, std::shared_ptr< const FunctionImpl< T, NDIM > > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::shared_ptr< FunctionImpl< T, NDIM > > >::store(), and madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_store().
store() [2/2]
template<class Archive , class T , typename Enabler > template<typename A = Archive, typename U = T, typename = std::enable_if_t<is_output_archive_v<A> && std::is_function<U>::value>> static void madness::archive::ArchiveStoreImpl< Archive, T, Enabler >::store (const Archive & ar, const U & t) inline static
Store function reference as a function pointer.
Parameters
[in] ar The archive.
[in] t The data.
References madness::archive::default_serialize(), madness::has_freestanding_default_serialize_v, madness::has_freestanding_serialize_v, MAD_ARCHIVE_DEBUG, and madness::archive::serialize().
The documentation for this struct was generated from the following file:
archive.h