MADNESS: Key Struct Reference
Key Struct Reference
Public Types
typedef unsigned long ulong
typedef unsigned long ulong
Public Member Functions
Key ()
Key ()
Key ()
Key ()
Key (int k)
Key (int k)
Key (ulong n, ulong i, ulong j, ulong k)
Key (ulong n, ulong i, ulong j, ulong k)
template<typename opT >
void foreach_child (const opT &op) const
hashT hash () const
hashT hash () const
hashT hash () const
bool operator== (const Key &b) const
bool operator== (const Key &b) const
bool operator== (const Key &b) const
bool operator== (const Key &b) const
Key parent () const
template<typename Archive >
void serialize (const Archive &ar)
template<typename Archive >
void serialize (const Archive &ar)
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
hashT hashval
ulong i
ulong j
int k
ulong k
ulong n
Member Typedef Documentation
ulong [1/2]
typedef unsigned long Key::ulong
ulong [2/2]
typedef unsigned long Key::ulong
Constructor & Destructor Documentation
Key() [1/8]
Key::Key () inline
Key() [2/8]
Key::Key (int k) inline
Key() [3/8]
Key::Key () inline
Key() [4/8]
Key::Key (int k) inline
Key() [5/8]
Key::Key () inline
Key() [6/8]
Key::Key (ulong n, ulong i, ulong j, ulong k) inline
References madness::hash_combine(), madness::hash_value(), madness::Key< NDIM >::hashval, k, and madness::Key< NDIM >::n.
Key() [7/8]
Key::Key () inline
Key() [8/8]
Key::Key (ulong n, ulong i, ulong j, ulong k) inline
References madness::hash_combine(), madness::Key< NDIM >::hashval, k, and madness::Key< NDIM >::n.
Member Function Documentation
foreach_child()
template<typename opT > void Key::foreach_child (const opT & op) const inline
References madness::Key< NDIM >::Key(), k, k2, madness::Key< NDIM >::n, op(), p(), and q().
hash() [1/3]
hashT Key::hash () const inline
References k.
Referenced by madness::SimplePmap< keyT >::owner(), and madness::LevelPmap< keyT >::owner().
hash() [2/3]
hashT Key::hash () const inline
References madness::Key< NDIM >::hashval.
hash() [3/3]
hashT Key::hash () const inline
References madness::Key< NDIM >::hashval.
operator==() [1/4]
bool Key::operator== (const Key & b) const inline
References b, and k.
operator==() [2/4]
bool Key::operator== (const Key & b) const inline
References b, and k.
operator==() [3/4]
bool Key::operator== (const Key & b) const inline
References b, madness::Key< NDIM >::hashval, k, and madness::Key< NDIM >::n.
operator==() [4/4]
bool Key::operator== (const Key & b) const inline
References b, madness::Key< NDIM >::hashval, k, and madness::Key< NDIM >::n.
parent()
Key Key::parent () const inline
References madness::Key< NDIM >::Key(), k, and madness::Key< NDIM >::n.
Referenced by madness::LevelPmap< keyT >::owner().
serialize() [1/3]
template<typename Archive > void Key::serialize (const Archive & ar) inline
References k.
serialize() [2/3]
template<typename Archive > void Key::serialize (const Archive & ar) inline
References madness::Key< NDIM >::hashval, k, and madness::Key< NDIM >::n.
serialize() [3/3]
template<typename Archive > void Key::serialize (const Archive & ar) inline
References madness::Key< NDIM >::hashval, k, and madness::Key< NDIM >::n.
Member Data Documentation
hashval
hashT Key::hashval
i
ulong Key::i
j
ulong Key::j
k [1/2]
int Key::k
k [2/2]
ulong Key::k
n
ulong Key::n
The documentation for this struct was generated from the following files:
test_dc.cc
test_tree.cc
test_world.cc
test_hashdc.cc