MADNESS: madness::FunctionImpl< T, NDIM >::do_inner_local< R > Struct Template Reference
madness::FunctionImpl< T, NDIM >::do_inner_local< R > Struct Template Reference
compute the inner product of this range with other
#include <funcimpl.h>
Public Member Functions
do_inner_local (const FunctionImpl< R, NDIM > *other, const bool leaves_only)
resultT operator() (resultT a, resultT b) const
resultT operator() (typename dcT::const_iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
typedef TENSOR_RESULT_TYPE (T, R) resultT
Public Attributes
bool leaves_only
const FunctionImpl< R, NDIM > * other
Detailed Description
template<typename T, std::size_t NDIM>
template<typename R>
struct madness::FunctionImpl< T, NDIM >::do_inner_local< R >
compute the inner product of this range with other
Constructor & Destructor Documentation
do_inner_local()
template<typename T , std::size_t NDIM> template<typename R > madness::FunctionImpl< T, NDIM >::do_inner_local< R >::do_inner_local (const FunctionImpl< R, NDIM > * other, const bool leaves_only) inline
Member Function Documentation
operator()() [1/2]
template<typename T , std::size_t NDIM> template<typename R > resultT madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator() (resultT a, resultT b) const inline
References a, and b.
operator()() [2/2]
template<typename T , std::size_t NDIM> template<typename R > resultT madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator() (typename dcT::const_iterator & it) const inline
References madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionImpl< T, NDIM >::coeffs, madness::GenTensor< T >::dim(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::FunctionNode< T, NDIM >::has_coeff(), madness::FunctionNode< T, NDIM >::is_leaf(), madness::FunctionImpl< T, NDIM >::do_inner_local< R >::leaves_only, MADNESS_EXCEPTION, madness::FunctionImpl< T, NDIM >::do_inner_local< R >::other, madness::print(), madness::WorldContainer< keyT, valueT, hashfunT >::probe(), R, madness::sum(), T(), and madness::FunctionImpl< T, NDIM >::do_inner_local< R >::TENSOR_RESULT_TYPE().
serialize()
template<typename T , std::size_t NDIM> template<typename R > template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_inner_local< R >::serialize (const Archive & ar) inline
TENSOR_RESULT_TYPE()
template<typename T , std::size_t NDIM> template<typename R > typedef madness::FunctionImpl< T, NDIM >::do_inner_local< R >::TENSOR_RESULT_TYPE (T , R)
Referenced by madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()().
Member Data Documentation
leaves_only
template<typename T , std::size_t NDIM> template<typename R > bool madness::FunctionImpl< T, NDIM >::do_inner_local< R >::leaves_only
Referenced by madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()().
other
template<typename T , std::size_t NDIM> template<typename R > const FunctionImpl<R,NDIM>* madness::FunctionImpl< T, NDIM >::do_inner_local< R >::other
Referenced by madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h