MADNESS: madness::function_real2complex_op< Q, NDIM > Struct Template Reference
madness::function_real2complex_op< Q, NDIM > Struct Template Reference
#include <complexfun.h>
Public Types
typedef std::complex< Q > resultT
Public Member Functions
Tensor< resultT > operator() (const Key< NDIM > &key, const Tensor< Q > &t) const
template<typename Archive >
void serialize (Archive &ar)
Member Typedef Documentation
resultT
template<typename Q , int NDIM> typedef std::complex<Q> madness::function_real2complex_op< Q, NDIM >::resultT
Member Function Documentation
operator()()
template<typename Q , int NDIM> Tensor< resultT > madness::function_real2complex_op< Q, NDIM >::operator() (const Key< NDIM > & key, const Tensor< Q > & t) const inline
References BINARY_OPTIMIZED_ITERATOR, madness::BaseTensor::dims(), madness::BaseTensor::ndim(), and Q().
serialize()
template<typename Q , int NDIM> template<typename Archive > void madness::function_real2complex_op< Q, NDIM >::serialize (Archive & ar) inline
The documentation for this struct was generated from the following file:
complexfun.h