MADNESS: madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> > Struct Template Reference
madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> > Struct Template Reference
#include <mw.h>
Public Member Functions
ScalingFunctionFunctor (const std::array< double, NDIM > &L, const Key< NDIM > &key, const std::array< int, NDIM > &k)
double operator() (const Vector< double, NDIM > &r) const final
You should implement this to return f(x)
virtual Level special_level () const final
Override this to change the minimum level of refinement at special points (default is 6)
virtual std::vector< Vector< double, NDIM > > special_points () const final
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, NDIM >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Public Attributes
std::array< int, NDIM > k
Key< NDIM > key
std::array< double, NDIM > L
std::array< ScalingFunctionFunctor< 1 >, NDIM > sf1
Public Attributes inherited from madness::FunctionFunctorInterface< double, NDIM >
Level special_level_
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, NDIM >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Constructor & Destructor Documentation
ScalingFunctionFunctor()
template<std::size_t NDIM> madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::ScalingFunctionFunctor (const std::array< double, NDIM > & L, const Key< NDIM > & key, const std::array< int, NDIM > & k) inline
References d, k, L, madness::Key< NDIM >::level(), and NDIM.
Member Function Documentation
operator()()
template<std::size_t NDIM> double madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::operator() (const Vector< double, NDIM > & x) const inline final virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< double, NDIM >.
References d, and NDIM.
special_level()
template<std::size_t NDIM> virtual Level madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::special_level () const inline final virtual
Override this to change the minimum level of refinement at special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, NDIM >.
References madness::Key< NDIM >::level().
special_points()
template<std::size_t NDIM> virtual std::vector< Vector< double, NDIM > > madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::special_points () const inline final virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, NDIM >.
References madness::Vector< T, N >::at(), d, and NDIM.
Member Data Documentation
k
template<std::size_t NDIM> std::array<int, NDIM> madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::k
key
template<std::size_t NDIM> Key<NDIM> madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::key
L
template<std::size_t NDIM> std::array<double, NDIM> madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::L
sf1
template<std::size_t NDIM> std::array<ScalingFunctionFunctor<1>, NDIM> madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::sf1
The documentation for this struct was generated from the following file:
mw.h