MADNESS: madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R > Struct Template Reference
madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R > Struct Template Reference
compute the inner product of this range with other
#include <funcimpl.h>
Public Member Functions
do_inner_local_on_demand (const FunctionImpl< T, NDIM > *bra, const FunctionImpl< R, NDIM > *ket, const bool leaves_only=true)
resultT operator() (resultT a, resultT b) const
resultT operator() (typename dcT::const_iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
typedef TENSOR_RESULT_TYPE (T, R) resultT
Public Attributes
const FunctionImpl< T, NDIM > * bra
const FunctionImpl< R, NDIM > * ket
bool leaves_only =true
Detailed Description
template<typename T, std::size_t NDIM>
template<typename R>
struct madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >
compute the inner product of this range with other
Constructor & Destructor Documentation
do_inner_local_on_demand()
template<typename T , std::size_t NDIM> template<typename R > madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::do_inner_local_on_demand (const FunctionImpl< T, NDIM > * bra, const FunctionImpl< R, NDIM > * ket, const bool leaves_only = true) inline
Member Function Documentation
operator()() [1/2]
template<typename T , std::size_t NDIM> template<typename R > resultT madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::operator() (resultT a, resultT b) const inline
References a, and b.
operator()() [2/2]
template<typename T , std::size_t NDIM> template<typename R > resultT madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::operator() (typename dcT::const_iterator & it) const inline
References madness::arg(), madness::Key< NDIM >::break_apart(), madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::error(), madness::GenTensor< T >::full_tensor(), madness::GenTensor< T >::full_tensor_copy(), madness::func(), madness::FunctionImpl< T, NDIM >::functor, madness::FunctionNode< T, NDIM >::has_coeff(), madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::ket, madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), madness::FunctionImpl< T, NDIM >::MADNESS_CHECK(), MADNESS_CHECK_THROW, MADNESS_EXCEPTION, max, NDIM, madness::outer(), madness::Key< NDIM >::parent(), madness::print(), madness::Tensor< T >::trace(), and madness::TT_FULL.
serialize()
template<typename T , std::size_t NDIM> template<typename R > template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::serialize (const Archive & ar) inline
TENSOR_RESULT_TYPE()
template<typename T , std::size_t NDIM> template<typename R > typedef madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::TENSOR_RESULT_TYPE (T , R)
Member Data Documentation
bra
template<typename T , std::size_t NDIM> template<typename R > const FunctionImpl<T,NDIM>* madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::bra
ket
template<typename T , std::size_t NDIM> template<typename R > const FunctionImpl<R,NDIM>* madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::ket
Referenced by madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::operator()().
leaves_only
template<typename T , std::size_t NDIM> template<typename R > bool madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::leaves_only =true
The documentation for this struct was generated from the following file:
funcimpl.h