MADNESS: madness::PairVectorMap Struct Reference
madness::PairVectorMap Struct Reference
#include <CCStructures.h>
Public Member Functions
PairVectorMap ()=default
PairVectorMap (const std::vector< std::pair< int, int > > map1)
void print (const std::string msg="PairVectorMap") const
Static Public Member Functions
static PairVectorMap quadratic_map (const int nfreeze, const int nocc)
static PairVectorMap triangular_map (const int nfreeze, const int nocc)
Public Attributes
std::vector< std::pair< int, int > > map
maps pair index (i,j) to vector index k
Constructor & Destructor Documentation
PairVectorMap() [1/2]
madness::PairVectorMap::PairVectorMap () default
Referenced by quadratic_map(), and triangular_map().
PairVectorMap() [2/2]
madness::PairVectorMap::PairVectorMap (const std::vector< std::pair< int, int > > map1) inline
Member Function Documentation
print()
void madness::PairVectorMap::print (const std::string msg = "PairVectorMap") const inline
References map, and madness::print().
quadratic_map()
static PairVectorMap madness::PairVectorMap::quadratic_map (const int nfreeze, const int nocc) inline static
< maps pair index (i,j) to vector index k
References PairVectorMap(), and map.
Referenced by madness::MP3::mp3_energy_contribution_macrotask_driver(), and madness::MP3::MacroTaskMP3::operator()().
triangular_map()
static PairVectorMap madness::PairVectorMap::triangular_map (const int nfreeze, const int nocc) inline static
< maps pair index (i,j) to vector index k
References PairVectorMap(), and map.
Referenced by madness::CC2::compute_cc2_energy(), madness::MP3::compute_mp3_ef_with_permutational_symmetry(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_singles(), madness::MP3::MacroTaskMP3::operator()(), madness::MacroTaskSinglesPotentialEx::operator()(), madness::MacroTaskSinglesPotentialGs::operator()(), and madness::CC2::solve().
Member Data Documentation
map
std::vector<std::pair<int, int> > madness::PairVectorMap::map
maps pair index (i,j) to vector index k
Referenced by madness::MP3::compute_mp3_ef_with_permutational_symmetry(), madness::MP3::MacroTaskMP3::operator()(), madness::Pairs< T >::pairs2vector(), print(), quadratic_map(), triangular_map(), and madness::Pairs< T >::vector2pairs().
The documentation for this struct was generated from the following file:
CCStructures.h