MADNESS: madness::CalculationParameters Struct Reference
madness::CalculationParameters Struct Reference
#include <CalculationParameters.h>
Public Member Functions
CalculationParameters ()
ctor reading out the input file
CalculationParameters (const CalculationParameters &other)=default
CalculationParameters (World &world, const commandlineparser &parser)
std::string ac_data () const
std::string algopt () const
std::string aobasis () const
double charge () const
bool converge_bsh_residual () const
bool converge_density () const
bool converge_each_energy () const
bool converge_total_energy () const
double dconv () const
std::string deriv () const
bool derivatives () const
std::string dft_deriv () const
bool dipole () const
bool do_localize () const
bool do_symmetry () const
double econv () const
std::string get_tag () const override
bool ginitial_hessian () const
int gmaxiter () const
bool gopt () const
double gprec () const
double gtol () const
double gval () const
bool have_beta () const
std::string hfexalg () const
int k () const
double L () const
double lo () const
int loadbalparts () const
std::string localize_method () const
bool localize_pm () const
int maxiter () const
double maxrotn () const
int maxsub () const
int nalpha () const
int nbeta () const
int nmo_alpha () const
int nmo_beta () const
bool no_compute () const
int nopen () const
int nv_factor () const
int nvalpha () const
int nvbeta () const
std::string nwfile () const
double orbitalshift () const
std::string pcm_data () const
Tensor< double > plot_cell () const
std::string pointgroup () const
std::string prefix () const
int print_level () const
std::vector< double > protocol () const
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
bool restart () const
bool restart_cphf () const
bool restartao () const
bool save () const
void set_derived_values (const Molecule &molecule)
bool spin_restricted () const
int vnucextra () const
std::string xc () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Static Public Attributes
static constexpr char const * tag = "dft"
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
CalculationParameters() [1/3]
madness::CalculationParameters::CalculationParameters (const CalculationParameters & other) default
CalculationParameters() [2/3]
madness::CalculationParameters::CalculationParameters (World & world, const commandlineparser & parser) inline
References madness::commandlineparser::base_name(), madness::commandlineparser::key_exists(), prefix(), read_input_and_commandline_options(), madness::commandlineparser::remove_extension(), madness::QCCalculationParametersBase::set_derived_value(), madness::QCCalculationParametersBase::set_user_defined_value(), and madness::commandlineparser::value().
CalculationParameters() [3/3]
madness::CalculationParameters::CalculationParameters () inline
ctor reading out the input file
Member Function Documentation
ac_data()
std::string madness::CalculationParameters::ac_data () const inline
Referenced by madness::Nemo::do_ac().
algopt()
std::string madness::CalculationParameters::algopt () const inline
Referenced by main().
aobasis()
std::string madness::CalculationParameters::aobasis () const inline
Referenced by madness::SCF::SCF(), madness::Znemo::Znemo(), madness::SCF::get_initial_orbitals(), madness::OEP::iterate(), and madness::MolecularEnergy::value().
charge()
double madness::CalculationParameters::charge () const inline
Referenced by madness::Nemo::compute_nemo_potentials(), madness::Nemo::make_fock_operator(), and set_derived_values().
converge_bsh_residual()
bool madness::CalculationParameters::converge_bsh_residual () const inline
converge_density()
bool madness::CalculationParameters::converge_density () const inline
converge_each_energy()
bool madness::CalculationParameters::converge_each_energy () const inline
converge_total_energy()
bool madness::CalculationParameters::converge_total_energy () const inline
dconv()
double madness::CalculationParameters::dconv () const inline
Referenced by madness::Znemo::iterate(), madness::MolecularEnergy::output_calc_info_schema(), Calculation::set_protocol(), madness::SCF::set_protocol(), madness::Nemo::solve(), madness::SCF::solve(), and Calculation::update().
deriv()
std::string madness::CalculationParameters::deriv () const inline
Referenced by madness::SCF::set_protocol().
derivatives()
bool madness::CalculationParameters::derivatives () const inline
Referenced by main().
dft_deriv()
std::string madness::CalculationParameters::dft_deriv () const inline
Referenced by madness::SCF::apply_potential().
dipole()
bool madness::CalculationParameters::dipole () const inline
do_localize()
bool madness::CalculationParameters::do_localize () const inline
References localize_method().
Referenced by set_derived_values(), madness::Nemo::solve(), and madness::SCF::solve().
do_symmetry()
bool madness::CalculationParameters::do_symmetry () const inline
References pointgroup().
Referenced by set_derived_values().
econv()
double madness::CalculationParameters::econv () const inline
Referenced by madness::Coulomb< T, NDIM >::Coulomb(), madness::Znemo::Znemo(), madness::MolecularEnergy::output_calc_info_schema(), madness::OEP_Parameters::set_derived_values(), madness::Nemo::solve(), and madness::SCF::solve().
get_tag()
std::string madness::CalculationParameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
References tag.
ginitial_hessian()
bool madness::CalculationParameters::ginitial_hessian () const inline
gmaxiter()
int madness::CalculationParameters::gmaxiter () const inline
Referenced by main().
gopt()
bool madness::CalculationParameters::gopt () const inline
Referenced by main().
gprec()
double madness::CalculationParameters::gprec () const inline
Referenced by main().
gtol()
double madness::CalculationParameters::gtol () const inline
Referenced by main().
gval()
double madness::CalculationParameters::gval () const inline
Referenced by main().
have_beta()
bool madness::CalculationParameters::have_beta () const inline
References nbeta(), and spin_restricted().
Referenced by madness::SCF::load_mos().
hfexalg()
std::string madness::CalculationParameters::hfexalg () const inline
Referenced by madness::SCF::apply_potential(), and main().
k()
int madness::CalculationParameters::k () const inline
Referenced by madness::Znemo::Znemo(), and madness::SCF::set_protocol().
L()
double madness::CalculationParameters::L () const inline
Referenced by Calculation::Calculation(), madness::SCF::SCF(), madness::Znemo::Znemo(), madness::SCF::load_mos(), madness::SCF::save_mos(), and madness::SCF::set_protocol().
lo()
double madness::CalculationParameters::lo () const inline
Referenced by madness::Coulomb< T, NDIM >::Coulomb(), madness::Znemo::Znemo(), madness::SCF::make_bsh_operators(), Calculation::set_protocol(), and madness::SCF::set_protocol().
loadbalparts()
int madness::CalculationParameters::loadbalparts () const inline
Referenced by madness::SCF::initial_load_bal(), madness::SCF::loadbal(), main(), and madness::SCF::make_fock_matrix().
localize_method()
std::string madness::CalculationParameters::localize_method () const inline
Referenced by do_localize(), madness::SCF::load_mos(), localize_pm(), madness::SCF::save_mos(), set_derived_values(), and madness::SCF::solve().
localize_pm()
bool madness::CalculationParameters::localize_pm () const inline
References localize_method().
Referenced by madness::SCF::group_orbital_sets().
maxiter()
int madness::CalculationParameters::maxiter () const inline
Referenced by madness::Znemo::iterate(), madness::Nemo::solve(), and madness::SCF::solve().
maxrotn()
double madness::CalculationParameters::maxrotn () const inline
Referenced by madness::Znemo::do_step_restriction(), and madness::SCF::do_step_restriction().
maxsub()
int madness::CalculationParameters::maxsub () const inline
Referenced by madness::Znemo::iterate(), and madness::SCF::update_subspace().
nalpha()
int madness::CalculationParameters::nalpha () const inline
Referenced by madness::OEP::compute_slater_potential(), madness::SCF::diag_fock_matrix(), madness::SCF::do_plots(), madness::Znemo::get_initial_orbitals(), madness::SCF::get_initial_orbitals(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::output_calc_info_schema(), madness::Znemo::read_explicit_guess_functions(), madness::SCF::restart_aos(), set_derived_values(), madness::SCF::update_subspace(), and madness::MolecularEnergy::value().
nbeta()
int madness::CalculationParameters::nbeta () const inline
Referenced by madness::XCOperator< T, NDIM >::XCOperator(), madness::OEP::compute_slater_potential(), madness::SCF::derivatives(), madness::SCF::do_plots(), madness::Znemo::get_initial_orbitals(), have_beta(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::loadbal(), main(), madness::SCF::output_calc_info_schema(), madness::SCF::project(), madness::Znemo::read_explicit_guess_functions(), madness::SCF::restart_aos(), set_derived_values(), madness::SCF::solve(), madness::SCF::update_subspace(), and madness::MolecularEnergy::value().
nmo_alpha()
int madness::CalculationParameters::nmo_alpha () const inline
Referenced by madness::SCF::SCF(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::load_mos(), madness::SCF::output_calc_info_schema(), madness::SCF::restart_aos(), madness::SCF::solve(), madness::SCF::update_subspace(), and madness::MolecularEnergy::value().
nmo_beta()
int madness::CalculationParameters::nmo_beta () const inline
Referenced by madness::SCF::SCF(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::load_mos(), madness::SCF::output_calc_info_schema(), madness::Znemo::read_real_guess(), madness::SCF::restart_aos(), madness::SCF::solve(), madness::SCF::update_subspace(), and madness::MolecularEnergy::value().
no_compute()
bool madness::CalculationParameters::no_compute () const inline
Referenced by madness::Nemo::value(), and madness::MolecularEnergy::value().
nopen()
int madness::CalculationParameters::nopen () const inline
Referenced by set_derived_values().
nv_factor()
int madness::CalculationParameters::nv_factor () const inline
Referenced by madness::MolecularEnergy::value().
nvalpha()
int madness::CalculationParameters::nvalpha () const inline
Referenced by set_derived_values().
nvbeta()
int madness::CalculationParameters::nvbeta () const inline
Referenced by set_derived_values().
nwfile()
std::string madness::CalculationParameters::nwfile () const inline
Referenced by madness::SCF::SCF(), madness::SCF::get_initial_orbitals(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::save_mos(), set_derived_values(), and madness::SCF::solve().
orbitalshift()
double madness::CalculationParameters::orbitalshift () const inline
Referenced by madness::Nemo::solve().
pcm_data()
std::string madness::CalculationParameters::pcm_data () const inline
Referenced by madness::Nemo::do_pcm(), madness::SCF::solve(), and madness::MolecularEnergy::value().
plot_cell()
Tensor< double > madness::CalculationParameters::plot_cell () const inline
Referenced by madness::SCF::do_plots().
pointgroup()
std::string madness::CalculationParameters::pointgroup () const inline
Referenced by do_symmetry().
prefix()
std::string madness::CalculationParameters::prefix () const inline
Referenced by CalculationParameters(), madness::TDHF::filename_for_roots(), madness::SCF::load_mos(), madness::SCF::output_calc_info_schema(), madness::SCF::output_scf_info_schema(), madness::SCF::restart_aos(), madness::SCF::save_mos(), and madness::SCF::solve().
print_level()
int madness::CalculationParameters::print_level () const inline
Referenced by madness::SCF::SCF(), madness::SCF::apply_potential(), madness::SCF::compute_residual(), madness::SCF::derivatives(), madness::SCF::dipole(), madness::SCF::do_step_restriction(), madness::SCF::group_orbital_sets(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::OEP::iterate(), main(), madness::SCF::make_bsh_operators(), madness::SCF::orthonormalize(), madness::SCF::orthonormalize(), madness::SCF::set_protocol(), madness::SCF::solve(), and madness::SCF::update_subspace().
protocol()
std::vector< double > madness::CalculationParameters::protocol () const inline
Referenced by main(), and madness::MolecularEnergy::value().
read_input_and_commandline_options()
void madness::QCCalculationParametersBase::read_input_and_commandline_options (World & world, const commandlineparser & parser, const std::string tag) inline
Referenced by CalculationParameters(), and madness::Znemo::Znemo().
restart()
bool madness::CalculationParameters::restart () const inline
Referenced by madness::SCF::get_initial_orbitals(), and madness::SCF::initial_guess().
restart_cphf()
bool madness::CalculationParameters::restart_cphf () const inline
restartao()
bool madness::CalculationParameters::restartao () const inline
Referenced by madness::SCF::get_initial_orbitals().
save()
bool madness::CalculationParameters::save () const inline
Referenced by madness::MolecularEnergy::value().
set_derived_values()
void madness::CalculationParameters::set_derived_values (const Molecule & molecule) inline
References charge(), do_localize(), do_symmetry(), e(), madness::error(), localize_method(), molecule, nalpha(), nbeta(), nopen(), nvalpha(), nvbeta(), nwfile(), and madness::QCCalculationParametersBase::set_derived_value().
Referenced by madness::SCF::SCF(), and madness::Znemo::Znemo().
spin_restricted()
bool madness::CalculationParameters::spin_restricted () const inline
Referenced by madness::SCF::SCF(), madness::XCOperator< T, NDIM >::XCOperator(), madness::XCOperator< T, NDIM >::XCOperator(), madness::Znemo::compute_energy(), madness::SCF::derivatives(), madness::SCF::do_plots(), madness::MolecularEnergy::energy_and_gradient(), madness::MolecularEnergy::gradient(), have_beta(), madness::SCF::initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::loadbal(), main(), madness::SCF::output_calc_info_schema(), madness::SCF::project(), madness::SCF::restart_aos(), madness::SCF::save_mos(), madness::SCF::solve(), madness::SCF::update_subspace(), and madness::MolecularEnergy::value().
vnucextra()
int madness::CalculationParameters::vnucextra () const inline
Referenced by madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), and madness::SCF::loadbal().
xc()
std::string madness::CalculationParameters::xc () const inline
Referenced by madness::SCF::SCF(), madness::XCOperator< T, NDIM >::XCOperator(), madness::XCOperator< T, NDIM >::XCOperator(), madness::SCF::load_mos(), madness::TDHF::make_cis_matrix(), and madness::SCF::save_mos().
Member Data Documentation
tag
constexpr char const* madness::CalculationParameters::tag = "dft" static constexpr
Referenced by get_tag().
The documentation for this struct was generated from the following file:
CalculationParameters.h