MADNESS: madness::write_test_input Struct Reference
madness::write_test_input Struct Reference
will write a test input and remove it from disk upon destruction
#include <write_test_input.h>
Public Member Functions
write_test_input ()
write_test_input (const CalculationParameters &param, const std::string &mol="lih")
~write_test_input ()
std::string filename () const
Static Public Member Functions
static std::ostream & write_molecule_to_test_input (std::string mol, std::ostream &of)
static std::ostream & write_to_test_input (const std::string groupname, const QCCalculationParametersBase *param, std::ostream &of)
Public Attributes
double eprec = 1.e-3
std::string filename_
bool keepfile =false
Detailed Description
will write a test input and remove it from disk upon destruction
Constructor & Destructor Documentation
write_test_input() [1/2]
madness::write_test_input::write_test_input () inline
write_test_input() [2/2]
madness::write_test_input::write_test_input (const CalculationParameters & param, const std::string & mol = "lih") inline
References filename_, param, write_molecule_to_test_input(), and write_to_test_input().
~write_test_input()
madness::write_test_input::~write_test_input () inline
References filename_, and keepfile.
Member Function Documentation
filename()
std::string madness::write_test_input::filename () const inline
References filename_.
Referenced by main(), nuclear_anchor_test(), run_all_calculations(), test_fock(), test_nemo(), test_read_restartaodata(), and test_read_restartdata().
write_molecule_to_test_input()
static std::ostream& madness::write_test_input::write_molecule_to_test_input (std::string mol, std::ostream & of) inline static
Referenced by write_test_input(), and madness::TDHF::test().
write_to_test_input()
static std::ostream& madness::write_test_input::write_to_test_input (const std::string groupname, const QCCalculationParametersBase * param, std::ostream & of) inline static
References param.
Referenced by write_test_input(), and madness::TDHF::test().
Member Data Documentation
eprec
double madness::write_test_input::eprec = 1.e-3
Referenced by write_test_input::write_test_input().
filename_
std::string madness::write_test_input::filename_
Referenced by write_test_input(), write_test_input::write_test_input(), write_test_input::~write_test_input(), ~write_test_input(), write_test_input::filename(), and filename().
keepfile
bool madness::write_test_input::keepfile =false
Referenced by ~write_test_input().
The documentation for this struct was generated from the following file:
madness/chem/write_test_input.h