MADNESS: AnsatzBase Struct Reference
AnsatzBase Struct Reference abstract
Public Member Functions
AnsatzBase (const double Z, const double a)
virtual std::string filename () const
double get_cusp_a () const
virtual Spinor make_bra (const Spinor &ket) const =0
virtual Spinor make_guess (World &world) const =0
virtual MatrixOperator make_Hd (World &world) const =0
virtual std::vector< Spinor > make_vbra (const std::vector< Spinor > &ket) const
virtual double mu (const double energy) const
virtual std::string name () const =0
virtual void normalize (Spinor &bra, Spinor &ket) const
virtual void normalize (Spinor &ket) const
virtual void normalize (std::vector< Spinor > &bra, std::vector< Spinor > &ket) const
virtual void normalize (std::vector< Spinor > &ket) const
virtual MatrixOperator R (World &world) const
virtual MatrixOperator Rinv (World &world) const
Public Attributes
double a =-1.3
int iansatz =0
double nuclear_charge =0.0
Constructor & Destructor Documentation
AnsatzBase()
AnsatzBase::AnsatzBase (const double Z, const double a) inline
Member Function Documentation
filename()
virtual std::string AnsatzBase::filename () const inline virtual
References name().
get_cusp_a()
double AnsatzBase::get_cusp_a () const inline
References a.
Referenced by ExactSpinor::set_ansatz().
make_bra()
virtual Spinor AnsatzBase::make_bra (const Spinor & ket) const pure virtual
Implemented in Ansatz0.
Referenced by normalize().
make_guess()
virtual Spinor AnsatzBase::make_guess (World & world) const pure virtual
Implemented in Ansatz0.
make_Hd()
virtual MatrixOperator AnsatzBase::make_Hd (World & world) const pure virtual
Implemented in Ansatz0.
make_vbra()
virtual std::vector< Spinor > AnsatzBase::make_vbra (const std::vector< Spinor > & ket) const inline virtual
References k, and madness::truncate().
Referenced by normalize().
mu()
virtual double AnsatzBase::mu (const double energy) const inline virtual
References alpha1, and energy.
name()
virtual std::string AnsatzBase::name () const pure virtual
Implemented in Ansatz0.
Referenced by filename().
normalize() [1/4]
virtual void AnsatzBase::normalize (Spinor & bra, Spinor & ket) const inline virtual
References Spinor::components, madness::inner(), m, norm(), madness::norm2(), madness::real(), madness::scale(), and Spinor::world().
Referenced by normalize(), normalize(), and normalize().
normalize() [2/4]
virtual void AnsatzBase::normalize (Spinor & ket) const inline virtual
References make_bra(), and normalize().
normalize() [3/4]
virtual void AnsatzBase::normalize (std::vector< Spinor > & bra, std::vector< Spinor > & ket) const inline virtual
References normalize().
normalize() [4/4]
virtual void AnsatzBase::normalize (std::vector< Spinor > & ket) const inline virtual
References make_vbra(), and normalize().
R()
virtual MatrixOperator AnsatzBase::R (World & world) const inline virtual
Reimplemented in Ansatz0.
References MADNESS_EXCEPTION.
Rinv()
virtual MatrixOperator AnsatzBase::Rinv (World & world) const inline virtual
Reimplemented in Ansatz0.
References MADNESS_EXCEPTION.
Member Data Documentation
a
double AnsatzBase::a =-1.3
Referenced by Ansatz0::Ansatz0(), and get_cusp_a().
iansatz
int AnsatzBase::iansatz =0
Referenced by Ansatz0::Ansatz0(), and ExactSpinor::set_ansatz().
nuclear_charge
double AnsatzBase::nuclear_charge =0.0
Referenced by Ansatz0::energy(), Ansatz0::make_guess(), and Ansatz0::make_Hv().
The documentation for this struct was generated from the following file:
dirac-hatom.cc