MADNESS: madness::archive::ArchiveImpl< Archive, archive_array< T > > Struct Template Reference
madness::archive::ArchiveImpl< Archive, archive_array< T > > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Partial specialization of ArchiveImpl for archive_array.
#include <archive.h>
Static Public Member Functions
static const Archive & wrap_load (const Archive &ar, const archive_array< T > &t)
Load the archive_array, using the preamble and postamble to perform runtime type-checking.
static const Archive & wrap_store (const Archive &ar, const archive_array< T > &t)
Store the archive_array, wrapped by the preamble/postamble.
Detailed Description
template<class Archive, class T>
struct madness::archive::ArchiveImpl< Archive, archive_array< T > >
Partial specialization of ArchiveImpl for archive_array.
Template Parameters
Archive The archive type.
T The data type in the archive_array.
Member Function Documentation
wrap_load()
template<class Archive , class T > static const Archive & madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load (const Archive & ar, const archive_array< T > & t) inline static
Load the archive_array, using the preamble and postamble to perform runtime type-checking.
Parameters
[in] ar The archive.
[out] t The archive_array.
Returns
The archive.
References madness::archive::default_serialize(), MAD_ARCHIVE_DEBUG, madness::archive::archive_array< T >::n, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_load(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_load(), madness::archive::archive_array< T >::ptr, madness::archive::serialize(), and T().
wrap_store()
template<class Archive , class T > static const Archive & madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store (const Archive & ar, const archive_array< T > & t) inline static
Store the archive_array, wrapped by the preamble/postamble.
Parameters
[in] ar The archive.
[in] t The archive_array.
Returns
The archive.
References madness::archive::default_serialize(), MAD_ARCHIVE_DEBUG, madness::archive::archive_array< T >::n, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_store(), madness::archive::archive_array< T >::ptr, madness::archive::serialize(), and T().
The documentation for this struct was generated from the following file:
archive.h