MADNESS: madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs Struct Reference
madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs Struct Reference
given an NS tree resulting from a convolution, truncate leafs if appropriate
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::iterator > rangeT
Public Member Functions
do_truncate_NS_leafs (const implT *f)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
const implT * f
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs
given an NS tree resulting from a convolution, truncate leafs if appropriate
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::rangeT
Constructor & Destructor Documentation
do_truncate_NS_leafs()
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::do_truncate_NS_leafs (const implT * f) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::operator() (typename rangeT::iterator & it) const inline
References madness::FunctionImpl< T, NDIM >::cdata, madness::FunctionNode< T, NDIM >::coeff(), madness::copy(), d(), madness::error(), madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::f, madness::FunctionImpl< T, NDIM >::get_thresh(), madness::GenTensor< T >::has_data(), madness::FunctionNode< T, NDIM >::is_leaf(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::serialize (const Archive & ar) inline
Member Data Documentation
f
template<typename T , std::size_t NDIM> const implT* madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::f
Referenced by madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h