MADNESS: spherical_harmonic Struct Reference
spherical_harmonic Struct Reference
Public Member Functions
spherical_harmonic (int l1, int m1, Vector< double, 3 > origin1=Vector< double, 3 >())
double operator() (const Vector< double, 3 > &r) const
Public Attributes
std::function< double(const Vector< double, 3 > &)> func
int l
int m
Vector< double, 3 > origin
Constructor & Destructor Documentation
spherical_harmonic()
spherical_harmonic::spherical_harmonic (int l1, int m1, Vector< double, 3 > origin1 = Vector<double,3>()) inline
References dx2y2_func(), dxy_func(), dxz_func(), dyz_func(), dz2_func(), func, l, m, MADNESS_EXCEPTION, px_func(), py_func(), pz_func(), and s_func().
Member Function Documentation
operator()()
double spherical_harmonic::operator() (const Vector< double, 3 > & r) const inline
References func, and origin.
Member Data Documentation
func
std::function<double(const Vector<double,3>&)> spherical_harmonic::func
Referenced by spherical_harmonic(), and operator()().
l
int spherical_harmonic::l
Referenced by spherical_harmonic().
m
int spherical_harmonic::m
Referenced by spherical_harmonic().
origin
Vector<double,3> spherical_harmonic::origin
Referenced by operator()().
The documentation for this struct was generated from the following file:
test_IntegratorXX.cc