MADNESS: madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T > Struct Template Reference
madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Implement pre/postamble storage routines for a TextFstreamOutputArchive.
#include <text_fstream_archive.h>
Static Public Member Functions
static void postamble_store (const TextFstreamOutputArchive &ar)
Write the postamble to the archive.
static void preamble_store (const TextFstreamOutputArchive &ar)
Write the preamble to the archive.
Detailed Description
template<class T>
struct madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >
Implement pre/postamble storage routines for a TextFstreamOutputArchive.
Template Parameters
T The type to be stored.
Member Function Documentation
postamble_store()
template<class T > static void madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::postamble_store (const TextFstreamOutputArchive & ar) inline static
Write the postamble to the archive.
Parameters
[in] ar The archive.
References madness::archive::TextFstreamOutputArchive::store_end_tag(), and T().
preamble_store()
template<class T > static void madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::preamble_store (const TextFstreamOutputArchive & ar) inline static
Write the preamble to the archive.
Parameters
[in] ar The archive.
References madness::archive::TextFstreamOutputArchive::store_start_tag(), and T().
The documentation for this struct was generated from the following file:
text_fstream_archive.h