MADNESS: madness::FunctionImpl< T, NDIM >::do_mirror Struct Reference
madness::FunctionImpl< T, NDIM >::do_mirror Struct Reference
mirror dimensions of this, write result on f
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::iterator > rangeT
Public Member Functions
do_mirror ()
do_mirror (const std::vector< long > mirror, implT &f)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * f
std::vector< long > mirror
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_mirror
mirror dimensions of this, write result on f
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_mirror::rangeT
Constructor & Destructor Documentation
do_mirror() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_mirror::do_mirror () inline
do_mirror() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_mirror::do_mirror (const std::vector< long > mirror, implT & f) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_mirror::operator() (typename rangeT::iterator & it) const inline
References madness::_(), madness::___, c, cc, madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionImpl< T, NDIM >::do_mirror::f, madness::GenTensor< T >::full_tensor_copy(), madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionNode< T, NDIM >::has_children(), madness::FunctionImpl< T, NDIM >::k, madness::kmax, madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::do_mirror::mirror, NDIM, madness::WorldContainer< keyT, valueT, hashfunT >::replace(), and madness::Key< NDIM >::translation().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_mirror::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
Member Data Documentation
f
template<typename T , std::size_t NDIM> implT* madness::FunctionImpl< T, NDIM >::do_mirror::f
Referenced by madness::FunctionImpl< T, NDIM >::do_mirror::operator()().
mirror
template<typename T , std::size_t NDIM> std::vector<long> madness::FunctionImpl< T, NDIM >::do_mirror::mirror
Referenced by madness::FunctionImpl< T, NDIM >::do_mirror::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h