MADNESS: madness::archive::ArchiveStoreImpl< ParallelOutputArchive< ContainerRecordOutputArchive >, WorldContainer< keyT, valueT > > Struct Template Reference
madness::archive::ArchiveStoreImpl< ParallelOutputArchive< ContainerRecordOutputArchive >, WorldContainer< keyT, valueT > > Struct Template Reference
#include <parallel_dc_archive.h>
Static Public Member Functions
static void store (const ParallelOutputArchive< ContainerRecordOutputArchive > &ar, const WorldContainer< keyT, valueT > &t)
Member Function Documentation
store()
template<class keyT , class valueT > static void madness::archive::ArchiveStoreImpl< ParallelOutputArchive< ContainerRecordOutputArchive >, WorldContainer< keyT, valueT > >::store (const ParallelOutputArchive< ContainerRecordOutputArchive > & ar, const WorldContainer< keyT, valueT > & t) inline static
References madness::archive::BaseParallelArchive< Archive >::get_world(), madness::archive::BaseParallelArchive< Archive >::local_archive(), me, madness::World::rank(), and v.
The documentation for this struct was generated from the following file:
parallel_dc_archive.h