MADNESS: madness::CCParameters Struct Reference
madness::CCParameters Struct Reference
#include <CCParameters.h>
Public Member Functions
CCParameters ()
CCParameters (const CCParameters &other)=default
copy constructor
CCParameters (World &world, const commandlineparser &parser)
ctor reading out the input file
CalcType calc_type () const
double dconv_3D () const
double dconv_6D () const
bool debug () const
bool decompose_Q () const
double dmin () const
double econv () const
double econv_pairs () const
void error (World &world, const std::string &msg) const
std::vector< std::size_t > excitations () const
long freeze () const
double gamma () const
std::string get_tag () const override
void information (World &world) const
print out the parameters
void initialize_parameters ()
std::size_t iter_max () const
std::size_t iter_max_3D () const
std::size_t iter_max_6D () const
bool kain () const
std::size_t kain_subspace () const
double lo () const
bool no_compute () const
bool no_compute_cc2 () const
bool no_compute_cispd () const
bool no_compute_gs () const
bool no_compute_lrcc2 () const
bool no_compute_mp2 () const
bool no_compute_mp2_constantpart () const
bool no_compute_response () const
std::pair< int, int > only_pair () const
std::size_t output_prec () const
bool plot () const
bool QtAnsatz () const
bool response () const
bool restart () const
void sanity_check (World &world) const
check if parameters are set correct
void set_derived_values ()
bool test () const
double thresh_3D () const
double thresh_6D () const
double thresh_bsh_3D () const
double thresh_bsh_6D () const
double thresh_f12 () const
double thresh_poisson () const
double thresh_Ue () const
double tight_thresh_3D () const
double tight_thresh_6D () const
size_t warning (World &world, const std::string &msg) const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Static Public Attributes
static constexpr char const * tag = "cc2"
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Detailed Description
Calculation TDHFParameters for CC2 and TDA calculations Maybe merge this with calculation_parameters of SCF at some point, or split into TDA and CC
Constructor & Destructor Documentation
CCParameters() [1/3]
madness::CCParameters::CCParameters () inline
References initialize_parameters().
CCParameters() [2/3]
madness::CCParameters::CCParameters (const CCParameters & other) default
copy constructor
CCParameters() [3/3]
madness::CCParameters::CCParameters (World & world, const commandlineparser & parser) inline
ctor reading out the input file
References initialize_parameters(), madness::QCCalculationParametersBase::read_input_and_commandline_options(), and set_derived_values().
Member Function Documentation
calc_type()
CalcType madness::CCParameters::calc_type () const inline
References madness::CT_ADC2, madness::CT_CC2, madness::CT_CISPD, madness::CT_LRCC2, madness::CT_LRCCS, madness::CT_MP2, madness::CT_MP3, madness::CT_TEST, and MADNESS_EXCEPTION.
Referenced by information(), response(), and madness::CC2::solve().
dconv_3D()
double madness::CCParameters::dconv_3D () const inline
Referenced by madness::CC2::iterate_singles(), and sanity_check().
dconv_6D()
double madness::CCParameters::dconv_6D () const inline
Referenced by madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), sanity_check(), set_derived_values(), madness::CC2::solve_cc2(), and madness::CC2::solve_mp2_coupled().
debug()
bool madness::CCParameters::debug () const inline
Referenced by madness::CC2::compute_cc2_energy(), madness::CC2::enforce_core_valence_separation(), madness::CCIntermediatePotentials::get_potential(), madness::CCIntermediatePotentials::insert(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), madness::CCPairBuilder::make_bare_pair_from_file(), madness::CCIntermediatePotentials::output(), madness::CC2::solve_cc2(), madness::CC2::solve_cispd(), and madness::CC2::solve_mp2_coupled().
decompose_Q()
bool madness::CCParameters::decompose_Q () const inline
dmin()
double madness::CCParameters::dmin () const inline
Referenced by madness::CC2::initialize().
econv()
double madness::CCParameters::econv () const inline
Referenced by madness::CC2::iterate_singles(), sanity_check(), set_derived_values(), madness::CC2::solve_cc2(), and madness::CC2::solve_mp2_coupled().
econv_pairs()
double madness::CCParameters::econv_pairs () const inline
Referenced by madness::CC2::iterate_pair().
error()
void madness::CCParameters::error (World & world, const std::string & msg) const inline
References MADNESS_EXCEPTION, and madness::World::rank().
excitations()
std::vector< std::size_t > madness::CCParameters::excitations () const inline
Referenced by madness::CC2::solve(), and madness::CC2::solve_ccs().
freeze()
long madness::CCParameters::freeze () const inline
Referenced by madness::CC2::compute_cc2_energy(), madness::CC2::compute_local_coupling(), madness::CC2::compute_local_coupling(), madness::MP3::compute_mp3_cd(), madness::MP3::compute_mp3_ef(), madness::MP3::compute_mp3_ef(), madness::MP3::compute_mp3_ef_low_scaling(), madness::MP3::compute_mp3_ef_with_permutational_symmetry(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_ghij_fast(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn_fast(), madness::Info::get_active_mo_bra(), madness::Info::get_active_mo_ket(), madness::CC2::initialize_pairs(), madness::CC2::initialize_singles_to_zero(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_singles(), madness::CCPairBuilder::make_all_bare_pairs(), madness::CCPairBuilder::make_bare_pair(), madness::MP3::mp3_energy_contribution(), madness::MP3::mp3_energy_contribution_macrotask_driver(), madness::CCIntermediatePotentials::operator()(), madness::MacroTaskConstantPart::operator()(), madness::MP3::MacroTaskMP3::operator()(), madness::MacroTaskSinglesPotentialEx::operator()(), madness::MacroTaskSinglesPotentialGs::operator()(), madness::CC2::solve(), and madness::CC2::solve_cispd().
gamma()
double madness::CCParameters::gamma () const inline
Referenced by test_inner().
get_tag()
std::string madness::CCParameters::get_tag () const inline override virtual
Implements madness::QCCalculationParametersBase.
References tag.
information()
void madness::CCParameters::information (World & world) const
print out the parameters
References calc_type(), madness::CT_LRCCS, madness::CT_TDHF, QtAnsatz(), and madness::World::rank().
Referenced by madness::CC2::initialize().
initialize_parameters()
void madness::CCParameters::initialize_parameters () inline
References thresh.
Referenced by CCParameters(), and CCParameters().
iter_max()
std::size_t madness::CCParameters::iter_max () const inline
Referenced by madness::CC2::solve_cc2(), and madness::CC2::solve_lrcc2().
iter_max_3D()
std::size_t madness::CCParameters::iter_max_3D () const inline
Referenced by madness::CC2::iterate_adc2_singles(), madness::CC2::iterate_cc2_singles(), madness::CC2::iterate_ccs_singles(), and madness::CC2::iterate_lrcc2_singles().
iter_max_6D()
std::size_t madness::CCParameters::iter_max_6D () const inline
Referenced by madness::CC2::iterate_pair(), and madness::CC2::solve_mp2_coupled().
kain()
bool madness::CCParameters::kain () const inline
Referenced by madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), sanity_check(), set_derived_values(), and madness::CC2::solve_mp2_coupled().
kain_subspace()
std::size_t madness::CCParameters::kain_subspace () const inline
Referenced by madness::CC2::iterate_pair(), sanity_check(), and madness::CC2::solve_mp2_coupled().
lo()
double madness::CCParameters::lo () const inline
Referenced by madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), test_inner(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
no_compute()
bool madness::CCParameters::no_compute () const inline
Referenced by sanity_check(), and set_derived_values().
no_compute_cc2()
bool madness::CCParameters::no_compute_cc2 () const inline
Referenced by madness::CC2::solve().
no_compute_cispd()
bool madness::CCParameters::no_compute_cispd () const inline
Referenced by madness::CC2::solve_cispd().
no_compute_gs()
bool madness::CCParameters::no_compute_gs () const inline
Referenced by set_derived_values().
no_compute_lrcc2()
bool madness::CCParameters::no_compute_lrcc2 () const inline
Referenced by madness::CC2::solve_lrcc2().
no_compute_mp2()
bool madness::CCParameters::no_compute_mp2 () const inline
Referenced by madness::CC2::solve().
no_compute_mp2_constantpart()
bool madness::CCParameters::no_compute_mp2_constantpart () const inline
Referenced by madness::CC2::solve_mp2_coupled().
no_compute_response()
bool madness::CCParameters::no_compute_response () const inline
Referenced by set_derived_values().
only_pair()
std::pair< int, int > madness::CCParameters::only_pair () const inline
Referenced by madness::CC2::solve_cispd().
output_prec()
std::size_t madness::CCParameters::output_prec () const inline
Referenced by madness::CC2::iterate_singles(), and set_derived_values().
plot()
bool madness::CCParameters::plot () const inline
QtAnsatz()
bool madness::CCParameters::QtAnsatz () const inline
Referenced by information(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
response()
bool madness::CCParameters::response () const inline
References calc_type(), madness::CT_ADC2, madness::CT_CISPD, madness::CT_LRCC2, and madness::CT_LRCCS.
Referenced by set_derived_values(), and madness::CC2::solve().
restart()
bool madness::CCParameters::restart () const inline
Referenced by sanity_check(), and set_derived_values().
sanity_check()
void madness::CCParameters::sanity_check (World & world) const
check if parameters are set correct
References dconv_3D(), dconv_6D(), econv(), kain(), kain_subspace(), no_compute(), madness::World::rank(), restart(), thresh_3D(), thresh_6D(), thresh_Ue(), tight_thresh_3D(), tight_thresh_6D(), and warning().
Referenced by madness::CC2::initialize().
set_derived_values()
void madness::CCParameters::set_derived_values ()
References dconv_6D(), econv(), kain(), no_compute(), no_compute_gs(), no_compute_response(), output_prec(), response(), restart(), madness::QCCalculationParametersBase::set_derived_value(), thresh_3D(), thresh_6D(), and tight_thresh_6D().
Referenced by CCParameters().
test()
bool madness::CCParameters::test () const inline
Referenced by madness::CC2::solve().
thresh_3D()
double madness::CCParameters::thresh_3D () const inline
Referenced by madness::CC2::initialize(), sanity_check(), and set_derived_values().
thresh_6D()
double madness::CCParameters::thresh_6D () const inline
Referenced by madness::CC2::initialize(), sanity_check(), set_derived_values(), and madness::CC2::solve_cispd().
thresh_bsh_3D()
double madness::CCParameters::thresh_bsh_3D () const inline
Referenced by madness::CC2::iterate_singles(), and test_inner().
thresh_bsh_6D()
double madness::CCParameters::thresh_bsh_6D () const inline
Referenced by madness::CC2::iterate_pair(), madness::CC2::update_constant_part_adc2(), and madness::CC2::update_constant_part_cispd().
thresh_f12()
double madness::CCParameters::thresh_f12 () const inline
thresh_poisson()
double madness::CCParameters::thresh_poisson () const inline
thresh_Ue()
double madness::CCParameters::thresh_Ue () const inline
Referenced by sanity_check().
tight_thresh_3D()
double madness::CCParameters::tight_thresh_3D () const inline
Referenced by sanity_check().
tight_thresh_6D()
double madness::CCParameters::tight_thresh_6D () const inline
Referenced by sanity_check(), set_derived_values(), and madness::CC2::solve_mp2_coupled().
warning()
size_t madness::CCParameters::warning (World & world, const std::string & msg) const inline
References madness::World::rank().
Referenced by sanity_check().
Member Data Documentation
tag
constexpr char const* madness::CCParameters::tag = "cc2" static constexpr
Referenced by get_tag().
The documentation for this struct was generated from the following files:
CCParameters.h
CCStructures.cc