MADNESS: madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T > Struct Template Reference
madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Implement pre/postamble load routines for a TextFstreamInputArchive.
#include <text_fstream_archive.h>
Static Public Member Functions
static void postamble_load (const TextFstreamInputArchive &ar)
Load the postamble and perform type-checking.
static void preamble_load (const TextFstreamInputArchive &ar)
Load the preamble and perform type-checking.
Detailed Description
template<class T>
struct madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >
Implement pre/postamble load routines for a TextFstreamInputArchive.
Template Parameters
T The expected type to be loaded.
Member Function Documentation
postamble_load()
template<class T > static void madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::postamble_load (const TextFstreamInputArchive & ar) inline static
Load the postamble and perform type-checking.
Parameters
[in] ar The archive.
References madness::archive::TextFstreamInputArchive::check_end_tag(), and T().
preamble_load()
template<class T > static void madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::preamble_load (const TextFstreamInputArchive & ar) inline static
Load the preamble and perform type-checking.
Parameters
[in] ar The archive.
References madness::archive::TextFstreamInputArchive::check_start_tag(), and T().
The documentation for this struct was generated from the following file:
text_fstream_archive.h