MADNESS: FunctionIOData< T, NDIM > Struct Template Reference
FunctionIOData< T, NDIM > Struct Template Reference
#include <FunctionIO.h>
Public Types
typedef Vector< double, NDIM > coordT
Type of vector holding coordinates.
typedef Vector< double, NDIM > coordT
Type of vector holding coordinates.
typedef int Level
typedef int Level
Public Member Functions
FunctionIOData ()=default
FunctionIOData ()=default
FunctionIOData ()=default
FunctionIOData (const Function< T, NDIM > &f)
FunctionIOData (const Function< T, NDIM > &f)
FunctionIOData (const Function< T, NDIM > &f)
Function< T, NDIM > create_function (World &world)
Function< T, NDIM > create_function (World &world)
Function< T, NDIM > create_function (World &world)
void initialize_func_coeffs (const Function< T, NDIM > &f, const Key< NDIM > &key)
void initialize_func_coeffs (const Function< T, NDIM > &f, const Key< NDIM > &key)
void initialize_func_coeffs (const Function< T, NDIM > &f, const Key< NDIM > &key)
void set_function_coeffs (Function< T, NDIM > &f, int num_leaf_nodes)
void set_function_coeffs (Function< T, NDIM > &f, int num_leaf_nodes)
void set_function_coeffs (Function< T, NDIM > &f, int num_leaf_nodes)
Public Attributes
std::array< std::pair< double, double >, NDIM > cell
std::vector< std::vector< coordT > > coords
long k = 0
std::size_t ndim = NDIM
std::vector< std::array< long, NDIM+1 > > nl
long npts_per_box = 0
long num_leaf_nodes {}
std::vector< std::vector< double > > values
Member Typedef Documentation
coordT [1/2]
template<typename T , std::size_t NDIM> typedef Vector<double, NDIM> FunctionIOData< T, NDIM >::coordT
Type of vector holding coordinates.
coordT [2/2]
template<typename T , std::size_t NDIM> typedef Vector<double, NDIM> FunctionIOData< T, NDIM >::coordT
Type of vector holding coordinates.
Level [1/2]
template<typename T , std::size_t NDIM> typedef int FunctionIOData< T, NDIM >::Level
Level [2/2]
template<typename T , std::size_t NDIM> typedef int FunctionIOData< T, NDIM >::Level
Constructor & Destructor Documentation
FunctionIOData() [1/6]
template<typename T , std::size_t NDIM> FunctionIOData< T, NDIM >::FunctionIOData () default
FunctionIOData() [2/6]
template<typename T , std::size_t NDIM> FunctionIOData< T, NDIM >::FunctionIOData (const Function< T, NDIM > & f) inline explicit
References FunctionIOData< T, NDIM >::cell, FunctionIO< T, NDIM >::count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), FunctionIOData< T, NDIM >::k, FunctionIOData< T, NDIM >::ndim, NDIM, FunctionIOData< T, NDIM >::npts_per_box, FunctionIOData< T, NDIM >::num_leaf_nodes, and simple_pow().
FunctionIOData() [3/6]
template<typename T , std::size_t NDIM> FunctionIOData< T, NDIM >::FunctionIOData () default
FunctionIOData() [4/6]
template<typename T , std::size_t NDIM> FunctionIOData< T, NDIM >::FunctionIOData (const Function< T, NDIM > & f) inline explicit
References FunctionIOData< T, NDIM >::cell, FunctionIO< T, NDIM >::count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), FunctionIOData< T, NDIM >::k, FunctionIOData< T, NDIM >::ndim, NDIM, FunctionIOData< T, NDIM >::npts_per_box, FunctionIOData< T, NDIM >::num_leaf_nodes, and simple_pow().
FunctionIOData() [5/6]
template<typename T , std::size_t NDIM> FunctionIOData< T, NDIM >::FunctionIOData () default
FunctionIOData() [6/6]
template<typename T , std::size_t NDIM> FunctionIOData< T, NDIM >::FunctionIOData (const Function< T, NDIM > & f) inline explicit
References FunctionIOData< T, NDIM >::cell, FunctionIO< T, NDIM >::count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), FunctionIOData< T, NDIM >::k, FunctionIOData< T, NDIM >::ndim, NDIM, FunctionIOData< T, NDIM >::npts_per_box, FunctionIOData< T, NDIM >::num_leaf_nodes, and simple_pow().
Member Function Documentation
create_function() [1/3]
template<typename T , std::size_t NDIM> Function< T, NDIM > FunctionIOData< T, NDIM >::create_function (World & world) inline
References FunctionIOData< T, NDIM >::cell, d, madness::FunctionFactory< T, NDIM >::empty(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, FunctionIOData< T, NDIM >::k, madness::FunctionFactory< T, NDIM >::k(), MADNESS_CHECK, FunctionIOData< T, NDIM >::ndim, NDIM, FunctionIOData< T, NDIM >::num_leaf_nodes, madness::FunctionDefaults< NDIM >::set_cell(), and FunctionIOData< T, NDIM >::set_function_coeffs().
Referenced by main(), and test().
create_function() [2/3]
template<typename T , std::size_t NDIM> Function< T, NDIM > FunctionIOData< T, NDIM >::create_function (World & world) inline
References FunctionIOData< T, NDIM >::cell, d, madness::FunctionFactory< T, NDIM >::empty(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, FunctionIOData< T, NDIM >::k, madness::FunctionFactory< T, NDIM >::k(), MADNESS_CHECK, FunctionIOData< T, NDIM >::ndim, NDIM, FunctionIOData< T, NDIM >::num_leaf_nodes, madness::FunctionDefaults< NDIM >::set_cell(), and FunctionIOData< T, NDIM >::set_function_coeffs().
create_function() [3/3]
template<typename T , std::size_t NDIM> Function< T, NDIM > FunctionIOData< T, NDIM >::create_function (World & world) inline
References FunctionIOData< T, NDIM >::cell, d, madness::FunctionFactory< T, NDIM >::empty(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, FunctionIOData< T, NDIM >::k, madness::FunctionFactory< T, NDIM >::k(), MADNESS_CHECK, FunctionIOData< T, NDIM >::ndim, NDIM, FunctionIOData< T, NDIM >::num_leaf_nodes, madness::FunctionDefaults< NDIM >::set_cell(), and FunctionIOData< T, NDIM >::set_function_coeffs().
initialize_func_coeffs() [1/3]
template<typename T , std::size_t NDIM> void FunctionIOData< T, NDIM >::initialize_func_coeffs (const Function< T, NDIM > & f, const Key< NDIM > & key) inline
References madness::f, FunctionIOData< T, NDIM >::initialize_func_coeffs(), madness::Key< NDIM >::level(), MADNESS_EXCEPTION, NDIM, FunctionIOData< T, NDIM >::nl, FunctionIOData< T, NDIM >::npts_per_box, madness::Key< NDIM >::translation(), and FunctionIOData< T, NDIM >::values.
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), and FunctionIOData< T, NDIM >::initialize_func_coeffs().
initialize_func_coeffs() [2/3]
template<typename T , std::size_t NDIM> void FunctionIOData< T, NDIM >::initialize_func_coeffs (const Function< T, NDIM > & f, const Key< NDIM > & key) inline
References c, FunctionIOData< T, NDIM >::cell, FunctionIOData< T, NDIM >::coords, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), madness::FunctionDefaults< NDIM >::get_cell_width(), h(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), FunctionIOData< T, NDIM >::k, madness::Key< NDIM >::level(), m, MADNESS_EXCEPTION, NDIM, FunctionIOData< T, NDIM >::nl, FunctionIOData< T, NDIM >::npts_per_box, madness::Key< NDIM >::translation(), and FunctionIOData< T, NDIM >::values.
initialize_func_coeffs() [3/3]
template<typename T , std::size_t NDIM> void FunctionIOData< T, NDIM >::initialize_func_coeffs (const Function< T, NDIM > & f, const Key< NDIM > & key) inline
References c, FunctionIOData< T, NDIM >::cell, FunctionIOData< T, NDIM >::coords, madness::BaseTensor::dim(), madness::f, madness::FunctionDefaults< NDIM >::get_cell(), madness::FunctionDefaults< NDIM >::get_cell_width(), h(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), FunctionIOData< T, NDIM >::k, madness::Key< NDIM >::level(), m, MADNESS_EXCEPTION, NDIM, FunctionIOData< T, NDIM >::nl, FunctionIOData< T, NDIM >::npts_per_box, madness::Key< NDIM >::translation(), and FunctionIOData< T, NDIM >::values.
set_function_coeffs() [1/3]
template<typename T , std::size_t NDIM> void FunctionIOData< T, NDIM >::set_function_coeffs (Function< T, NDIM > & f, int num_leaf_nodes) inline
References madness::f, NDIM, FunctionIOData< T, NDIM >::nl, FunctionIOData< T, NDIM >::num_leaf_nodes, madness::Tensor< T >::ptr(), and FunctionIOData< T, NDIM >::values.
Referenced by FunctionIOData< T, NDIM >::create_function().
set_function_coeffs() [2/3]
template<typename T , std::size_t NDIM> void FunctionIOData< T, NDIM >::set_function_coeffs (Function< T, NDIM > & f, int num_leaf_nodes) inline
References madness::f, NDIM, FunctionIOData< T, NDIM >::nl, FunctionIOData< T, NDIM >::num_leaf_nodes, madness::Tensor< T >::ptr(), and FunctionIOData< T, NDIM >::values.
set_function_coeffs() [3/3]
template<typename T , std::size_t NDIM> void FunctionIOData< T, NDIM >::set_function_coeffs (Function< T, NDIM > & f, int num_leaf_nodes) inline
References madness::f, NDIM, FunctionIOData< T, NDIM >::nl, FunctionIOData< T, NDIM >::num_leaf_nodes, madness::Tensor< T >::ptr(), and FunctionIOData< T, NDIM >::values.
Member Data Documentation
cell
template<typename T , std::size_t NDIM> std::array< std::pair< double, double >, NDIM > FunctionIOData< T, NDIM >::cell
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), FunctionIOData< T, NDIM >::create_function(), and FunctionIOData< T, NDIM >::initialize_func_coeffs().
coords
template<typename T , std::size_t NDIM> std::vector< std::vector< coordT > > FunctionIOData< T, NDIM >::coords
Referenced by FunctionIOData< T, NDIM >::initialize_func_coeffs().
k
template<typename T , std::size_t NDIM> long FunctionIOData< T, NDIM >::k = 0
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), FunctionIOData< T, NDIM >::create_function(), and FunctionIOData< T, NDIM >::initialize_func_coeffs().
ndim
template<typename T , std::size_t NDIM> std::size_t FunctionIOData< T, NDIM >::ndim = NDIM
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), and FunctionIOData< T, NDIM >::create_function().
nl
template<typename T , std::size_t NDIM> std::vector< std::array< long, NDIM+1 > > FunctionIOData< T, NDIM >::nl
Referenced by FunctionIOData< T, NDIM >::initialize_func_coeffs(), and FunctionIOData< T, NDIM >::set_function_coeffs().
npts_per_box
template<typename T , std::size_t NDIM> long FunctionIOData< T, NDIM >::npts_per_box = 0
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), and FunctionIOData< T, NDIM >::initialize_func_coeffs().
num_leaf_nodes
template<typename T , std::size_t NDIM> long FunctionIOData< T, NDIM >::num_leaf_nodes {}
Referenced by FunctionIOData< T, NDIM >::FunctionIOData(), FunctionIOData< T, NDIM >::create_function(), and FunctionIOData< T, NDIM >::set_function_coeffs().
values
template<typename T , std::size_t NDIM> std::vector< std::vector< double > > FunctionIOData< T, NDIM >::values
Referenced by FunctionIOData< T, NDIM >::initialize_func_coeffs(), and FunctionIOData< T, NDIM >::set_function_coeffs().
The documentation for this struct was generated from the following files:
FunctionIO.h
FunctionIO2.h
FunctionIOHDF5.h