MADNESS: Test2 Struct Reference
Test2 Struct Reference
Public Member Functions
Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
bool provides_gradient () const
Override this to return true if the derivative is implemented.
bool provides_gradient () const
Override this to return true if the derivative is implemented.
double value (const Tensor< double > &x)
Should return the value of the objective function.
double value (const Tensor< double > &x)
Should return the value of the objective function.
Public Member Functions inherited from madness::OptimizationTargetInterface
virtual ~OptimizationTargetInterface ()
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
Member Function Documentation
gradient() [1/2]
Tensor< double > Test2::gradient (const Tensor< double > & x) inline virtual
Should return the derivative of the function.
Reimplemented from madness::OptimizationTargetInterface.
References madness::BaseTensor::dim(), madness::g, v, and value().
gradient() [2/2]
Tensor< double > Test2::gradient (const Tensor< double > & x) inline virtual
Should return the derivative of the function.
Reimplemented from madness::OptimizationTargetInterface.
References madness::BaseTensor::dim(), madness::g, v, and value().
provides_gradient() [1/2]
bool Test2::provides_gradient () const inline virtual
Override this to return true if the derivative is implemented.
Reimplemented from madness::OptimizationTargetInterface.
provides_gradient() [2/2]
bool Test2::provides_gradient () const inline virtual
Override this to return true if the derivative is implemented.
Reimplemented from madness::OptimizationTargetInterface.
value() [1/2]
double Test2::value (const Tensor< double > & x) inline virtual
Should return the value of the objective function.
Implements madness::OptimizationTargetInterface.
References madness::BaseTensor::dim(), and v.
Referenced by gradient().
value() [2/2]
double Test2::value (const Tensor< double > & x) inline virtual
Should return the value of the objective function.
Implements madness::OptimizationTargetInterface.
References madness::BaseTensor::dim(), and v.
The documentation for this struct was generated from the following files:
kain.cc
test_solvers.cc