MADNESS: molresponse::write_test_input Struct Reference
molresponse::write_test_input Struct Reference
will write a test input and remove it from disk upon destruction
#include <write_test_input.h>
Public Member Functions
write_test_input ()
write_test_input (const CalculationParameters &param, const std::string &filename, std::string mol_path)
~write_test_input ()
std::string filename () const
Static Public Member Functions
static std::ostream & write_molecule_to_test_input (std::string mol_path, std::ostream &of)
static std::ostream & write_to_test_input (const std::string &groupname, const QCCalculationParametersBase *param, std::ostream &of)
Public Attributes
double eprec = 1.e-4
std::string filename_
bool keepfile = true
std::string molecule_path
Detailed Description
will write a test input and remove it from disk upon destruction
Constructor & Destructor Documentation
write_test_input() [1/2]
molresponse::write_test_input::write_test_input () inline
write_test_input() [2/2]
molresponse::write_test_input::write_test_input (const CalculationParameters & param, const std::string & filename, std::string mol_path) inline explicit
References filename_, molecule_path, param, write_molecule_to_test_input(), and write_to_test_input().
~write_test_input()
molresponse::write_test_input::~write_test_input () inline
References filename_, and keepfile.
Member Function Documentation
filename()
std::string molresponse::write_test_input::filename () const inline
References filename_.
write_molecule_to_test_input()
static std::ostream& molresponse::write_test_input::write_molecule_to_test_input (std::string mol_path, std::ostream & of) inline static
Referenced by write_test_input().
write_to_test_input()
static std::ostream& molresponse::write_test_input::write_to_test_input (const std::string & groupname, const QCCalculationParametersBase * param, std::ostream & of) inline static
References param.
Referenced by write_test_input().
Member Data Documentation
eprec
double molresponse::write_test_input::eprec = 1.e-4
filename_
std::string molresponse::write_test_input::filename_
Referenced by write_test_input(), ~write_test_input(), and filename().
keepfile
bool molresponse::write_test_input::keepfile = true
Referenced by ~write_test_input().
molecule_path
std::string molresponse::write_test_input::molecule_path
Referenced by write_test_input().
The documentation for this struct was generated from the following file:
apps/molresponse/testing/write_test_input.h