MADNESS: madness::XCOperator< T, NDIM >::expme Struct Reference
madness::XCOperator< T, NDIM >::expme Struct Reference
simple structure to take the pointwise exponential of a function, shifted by +14
Classes
struct expme1
Public Types
typedef double resultT
Public Member Functions
Tensor< double > operator() (const Key< 3 > &key, const Tensor< double > &val) const
template<typename Archive >
void serialize (Archive &ar)
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::XCOperator< T, NDIM >::expme
simple structure to take the pointwise exponential of a function, shifted by +14
Member Typedef Documentation
resultT
template<typename T , std::size_t NDIM> typedef double madness::XCOperator< T, NDIM >::expme::resultT
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> Tensor< double > madness::XCOperator< T, NDIM >::expme::operator() (const Key< 3 > & key, const Tensor< double > & val) const inline
References madness::copy(), op(), and madness::Tensor< T >::unaryop().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::XCOperator< T, NDIM >::expme::serialize (Archive & ar) inline
The documentation for this struct was generated from the following file:
SCFOperators.h