MADNESS: madness::archive::ArchiveSerializeImpl< Archive, resT(*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(*)(paramT...)> > > Struct Template Reference
madness::archive::ArchiveSerializeImpl< Archive, resT(*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(*)(paramT...)> > > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Serialize a function pointer.
#include <archive.h>
Static Public Member Functions
template<typename A = Archive, typename = std::enable_if_t<is_output_archive<A>::value>>
static void serialize (const A &ar, resT(*(&fn))(paramT...))
Serialize the function pointer.
template<typename A = Archive>
static std::enable_if_t<!is_output_archive< A >::value, void > serialize (const A &ar, resT(*(&fn))(paramT...))
Detailed Description
template<class Archive, typename resT, typename... paramT>
struct madness::archive::ArchiveSerializeImpl< Archive, resT(*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(*)(paramT...)> > >
Serialize a function pointer.
Template Parameters
Archive The archive type.
resT The function's return type.
paramT Parameter pack for the function's arguments.
Member Function Documentation
serialize() [1/2]
template<class Archive , typename resT , typename... paramT> template<typename A = Archive, typename = std::enable_if_t<is_output_archive<A>::value>> static void madness::archive::ArchiveSerializeImpl< Archive, resT(*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(*)(paramT...)> > >::serialize (const A & ar, resT(*(&fn))(paramT...)) inline static
Serialize the function pointer.
Parameters
[in] ar The archive.
[in] fn The function pointer.
References madness::archive::to_rel_fn_ptr(), and madness::archive::wrap_opaque().
serialize() [2/2]
template<class Archive , typename resT , typename... paramT> template<typename A = Archive> static std::enable_if_t<!is_output_archive< A >::value, void > madness::archive::ArchiveSerializeImpl< Archive, resT(*)(paramT...), std::enable_if_t<!is_default_serializable_v< Archive, resT(*)(paramT...)> > >::serialize (const A & ar, resT(*(&fn))(paramT...)) inline static
References madness::archive::to_abs_fn_ptr(), and madness::archive::wrap_opaque().
The documentation for this struct was generated from the following file:
archive.h