MADNESS: madness::Znemo::timer Struct Reference
madness::Znemo::timer Struct Reference
#include <znemo.h>
Public Member Functions
timer (World &world, bool do_print=true)
void end (const std::string msg)
void tag (const std::string msg)
Public Attributes
bool do_print =true
double sss
double ttt
World & world
Constructor & Destructor Documentation
timer()
madness::Znemo::timer::timer (World & world, bool do_print = true) inline
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, madness::wall_time(), and world.
Member Function Documentation
end()
void madness::Znemo::timer::end (const std::string msg) inline
References madness::cpu_time(), do_print, madness::WorldGopInterface::fence(), madness::World::gop, madness::World::rank(), ss1, sss, tt1, ttt, madness::wall_time(), and world.
Referenced by madness::Znemo::compute_energy(), madness::Znemo::compute_potentials(), and madness::Znemo::compute_residuals().
tag()
void madness::Znemo::timer::tag (const std::string msg) inline
References madness::cpu_time(), do_print, madness::WorldGopInterface::fence(), madness::World::gop, madness::World::rank(), ss1, sss, tt1, ttt, madness::wall_time(), and world.
Member Data Documentation
do_print
bool madness::Znemo::timer::do_print =true
Referenced by end(), and tag().
sss
double madness::Znemo::timer::sss
Referenced by timer(), end(), and tag().
ttt
double madness::Znemo::timer::ttt
Referenced by timer(), end(), and tag().
world
World& madness::Znemo::timer::world
Referenced by timer(), end(), and tag().
The documentation for this struct was generated from the following file:
znemo.h