MADNESS: SafeMPI::Group::Impl Struct Reference
SafeMPI::Group::Impl Struct Reference
Public Member Functions
Impl (const Impl &other, int n, const int *ranks)
Impl (MPI_Comm comm)
~Impl ()
Public Attributes
MPI_Group group
Constructor & Destructor Documentation
Impl() [1/2]
SafeMPI::Group::Impl::Impl (MPI_Comm comm) inline
References group, MADNESS_MPI_TEST, and MPI_Comm_group().
Impl() [2/2]
SafeMPI::Group::Impl::Impl (const Impl & other, int n, const int * ranks) inline
References group, MADNESS_MPI_TEST, and MPI_Group_incl().
~Impl()
SafeMPI::Group::Impl::~Impl () inline
References group, SafeMPI::Is_initialized(), MPI_Group_free(), MPI_SUCCESS, and SafeMPI::detail::print_mpi_error().
Member Data Documentation
group
MPI_Group SafeMPI::Group::Impl::group
Referenced by Impl(), Impl(), and ~Impl().
The documentation for this struct was generated from the following file:
safempi.h