MADNESS: madness::Pairs< T > Struct Template Reference
madness::Pairs< T > Struct Template Reference
#include <CCStructures.h>
Public Types
typedef std::map< std::pair< int, int >, T > pairmapT
Public Member Functions
template<typename R , typename opT >
Pairs< R > convert (const Pairs< T > arg, const opT op) const
convert Pairs<T> to another type
bool empty () const
void insert (int i, int j, const T &pair)
T & operator() (int i, int j)
getter
const T & operator() (int i, int j) const
getter
void swap (Pairs< T > &other)
swap the contant of the pairmap
Static Public Member Functions
static std::vector< T > pairs2vector (const Pairs< T > &argument, const PairVectorMap map)
static Pairs vector2pairs (const std::vector< T > &argument, const PairVectorMap map)
Public Attributes
pairmapT allpairs
Detailed Description
template<typename T>
struct madness::Pairs< T >
POD holding all electron pairs with easy access Similar strucutre than the Pair structure from MP2 but with some additional features (merge at some point) This structure will also be used for intermediates
Member Typedef Documentation
pairmapT
template<typename T > typedef std::map<std::pair<int, int>, T> madness::Pairs< T >::pairmapT
Member Function Documentation
convert()
template<typename T > template<typename R , typename opT > Pairs< R > madness::Pairs< T >::convert (const Pairs< T > arg, const opT op) const inline
convert Pairs<T> to another type
opT op takes an object of T and returns the result type
References madness::arg(), madness::Pairs< T >::insert(), op(), and p().
Referenced by madness::CC2::compute_local_coupling().
empty()
template<typename T > bool madness::Pairs< T >::empty () const inline
References madness::Pairs< T >::allpairs.
Referenced by madness::CC2::initialize_pairs().
insert()
template<typename T > void madness::Pairs< T >::insert (int i, int j, const T & pair) inline
setter can NOT replace elements (for this construct new pair map and swap the content)
References madness::Pairs< T >::allpairs.
Referenced by madness::CC2::compute_local_coupling(), madness::CC2::compute_local_coupling(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn_fast(), madness::Pairs< T >::convert(), madness::CC2::initialize_pairs(), madness::CCPairBuilder::make_all_bare_pairs(), and madness::Pairs< T >::vector2pairs().
operator()() [1/2]
template<typename T > T & madness::Pairs< T >::operator() (int i, int j) inline
getter
References madness::Pairs< T >::allpairs.
operator()() [2/2]
template<typename T > const T & madness::Pairs< T >::operator() (int i, int j) const inline
getter
References madness::Pairs< T >::allpairs.
pairs2vector()
template<typename T > static std::vector< T > madness::Pairs< T >::pairs2vector (const Pairs< T > & argument, const PairVectorMap map) inline static
References madness::Pairs< T >::allpairs, and madness::PairVectorMap::map.
Referenced by madness::CC2::compute_cc2_energy(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_singles(), madness::CC2::solve_cc2(), and madness::CC2::solve_mp2_coupled().
swap()
template<typename T > void madness::Pairs< T >::swap (Pairs< T > & other) inline
swap the contant of the pairmap
References madness::Pairs< T >::allpairs.
vector2pairs()
template<typename T > static Pairs madness::Pairs< T >::vector2pairs (const std::vector< T > & argument, const PairVectorMap map) inline static
References madness::Pairs< T >::insert(), and madness::PairVectorMap::map.
Referenced by madness::CC2::iterate_lrcc2_pairs(), madness::MacroTaskSinglesPotentialEx::operator()(), madness::MacroTaskSinglesPotentialGs::operator()(), madness::CC2::solve_cc2(), and madness::CC2::solve_mp2_coupled().
Member Data Documentation
allpairs
template<typename T > pairmapT madness::Pairs< T >::allpairs
Referenced by madness::CC2::compute_local_coupling(), madness::MP3::compute_mp3_ef_low_scaling(), madness::MP3::compute_mp3_ef_with_permutational_symmetry(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_ghij_fast(), madness::MP3::compute_mp3_klmn(), madness::MP3::compute_mp3_klmn_fast(), madness::Pairs< T >::empty(), madness::CC2::initialize_pairs(), madness::Pairs< T >::insert(), madness::CC2::iterate_adc2_pairs(), madness::CC2::iterate_singles(), madness::MP3::mp3_energy_contribution(), madness::MP3::mp3_energy_contribution_macrotask_driver(), madness::MP3::mp3_test(), madness::Pairs< T >::operator()(), madness::Pairs< T >::operator()(), madness::Pairs< T >::pairs2vector(), madness::CC2::solve(), madness::CC2::solve_cispd(), madness::CC2::solve_mp2_coupled(), and madness::Pairs< T >::swap().
The documentation for this struct was generated from the following file:
CCStructures.h