MADNESS: madness::LRFunctorBase< T, NDIM, LDIM > Struct Template Reference
madness::LRFunctorBase< T, NDIM, LDIM > Struct Template Reference abstract
the low-rank functor is what the LowRankFunction will represent
#include <lowrankfunction.h>
Public Member Functions
virtual ~LRFunctorBase ()
virtual Function< T, LDIM > inner (const Function< T, LDIM > &rhs, const particle< LDIM > p1, const particle< LDIM > p2) const
virtual std::vector< Function< T, LDIM > > inner (const std::vector< Function< T, LDIM > > &rhs, const particle< LDIM > p1, const particle< LDIM > p2) const =0
virtual Tensor< T >::scalar_type norm2 () const
virtual T operator() (const Vector< T, NDIM > &r) const =0
virtual World & world () const =0
Friends
Function< T, LDIM > inner (const LRFunctorBase &functor, const Function< T, LDIM > &rhs, const particle< LDIM > p1, const particle< LDIM > p2)
std::vector< Function< T, LDIM > > inner (const LRFunctorBase &functor, const std::vector< Function< T, LDIM > > &rhs, const particle< LDIM > p1, const particle< LDIM > p2)
Detailed Description
template<typename T, std::size_t NDIM, std::size_t LDIM = NDIM/2>
struct madness::LRFunctorBase< T, NDIM, LDIM >
the low-rank functor is what the LowRankFunction will represent
derive from this class : must implement in inner product may implement an operator()(const coord_nd&)
Constructor & Destructor Documentation
~LRFunctorBase()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> virtual madness::LRFunctorBase< T, NDIM, LDIM >::~LRFunctorBase () inline virtual
Member Function Documentation
inner() [1/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> virtual Function< T, LDIM > madness::LRFunctorBase< T, NDIM, LDIM >::inner (const Function< T, LDIM > & rhs, const particle< LDIM > p1, const particle< LDIM > p2) const inline virtual
References madness::LRFunctorBase< T, NDIM, LDIM >::inner.
inner() [2/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> virtual std::vector< Function< T, LDIM > > madness::LRFunctorBase< T, NDIM, LDIM >::inner (const std::vector< Function< T, LDIM > > & rhs, const particle< LDIM > p1, const particle< LDIM > p2) const pure virtual
Implemented in madness::LRFunctorF12< T, NDIM, LDIM >, and madness::LRFunctorPure< T, NDIM, LDIM >.
norm2()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> virtual Tensor< T >::scalar_type madness::LRFunctorBase< T, NDIM, LDIM >::norm2 () const inline virtual
Reimplemented in madness::LRFunctorF12< T, NDIM, LDIM >, and madness::LRFunctorPure< T, NDIM, LDIM >.
References MADNESS_EXCEPTION.
Referenced by madness::LowRankFunction< T, NDIM, LDIM >::l2error().
operator()()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> virtual T madness::LRFunctorBase< T, NDIM, LDIM >::operator() (const Vector< T, NDIM > & r) const pure virtual
world()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> virtual World & madness::LRFunctorBase< T, NDIM, LDIM >::world () const pure virtual
Implemented in madness::LRFunctorF12< T, NDIM, LDIM >, and madness::LRFunctorPure< T, NDIM, LDIM >.
Referenced by madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::Yformer().
Friends And Related Symbol Documentation
inner [1/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> Function< T, LDIM > inner (const LRFunctorBase< T, NDIM, LDIM > & functor, const Function< T, LDIM > & rhs, const particle< LDIM > p1, const particle< LDIM > p2) friend
inner [2/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > inner (const LRFunctorBase< T, NDIM, LDIM > & functor, const std::vector< Function< T, LDIM > > & rhs, const particle< LDIM > p1, const particle< LDIM > p2) friend
Referenced by madness::LRFunctorBase< T, NDIM, LDIM >::inner().
The documentation for this struct was generated from the following file:
lowrankfunction.h