MADNESS: madness::FunctionImpl< T, NDIM >::do_norm2sq_local Struct Reference
madness::FunctionImpl< T, NDIM >::do_norm2sq_local Struct Reference
#include <funcimpl.h>
Public Member Functions
double operator() (double a, double b) const
double operator() (typename dcT::const_iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Member Function Documentation
operator()() [1/2]
template<typename T , std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_norm2sq_local::operator() (double a, double b) const inline
References a, and b.
operator()() [2/2]
template<typename T , std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_norm2sq_local::operator() (typename dcT::const_iterator & it) const inline
References madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionNode< T, NDIM >::has_coeff(), norm(), and madness::GenTensor< T >::normf().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_norm2sq_local::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
The documentation for this struct was generated from the following file:
funcimpl.h