MADNESS: madness::archive::ArchiveLoadImpl< Archive, T, Enabler > Struct Template Reference
madness::archive::ArchiveLoadImpl< Archive, T, Enabler > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Default load of an object via serialize(ar, t).
#include <archive.h>
Static Public Member Functions
template<typename A = Archive, typename U = T, typename = std::enable_if_t<is_input_archive_v<A> && (has_member_serialize_v<U,A> || has_nonmember_serialize_v<U,A> || has_freestanding_serialize_v<U, A> || has_freestanding_default_serialize_v<U, A>)>>
static void load (const A &ar, const U &t)
Load an object.
template<typename A = Archive, typename U = T, typename = std::enable_if_t<is_input_archive_v<A> && std::is_function<U>::value>>
static void load (const Archive &ar, U &t)
Load function reference stored as function pointer.
Detailed Description
template<class Archive, class T, typename Enabler>
struct madness::archive::ArchiveLoadImpl< Archive, T, Enabler >
Default load of an object via serialize(ar, t).
Template Parameters
Archive The archive type.
T The data type.
Member Function Documentation
load() [1/2]
template<class Archive , class T , typename Enabler > template<typename A = Archive, typename U = T, typename = std::enable_if_t<is_input_archive_v<A> && (has_member_serialize_v<U,A> || has_nonmember_serialize_v<U,A> || has_freestanding_serialize_v<U, A> || has_freestanding_default_serialize_v<U, A>)>> static void madness::archive::ArchiveLoadImpl< Archive, T, Enabler >::load (const A & ar, const U & t) inline static
Load an object.
Parameters
[in] ar The archive.
[in] t The data.
References madness::archive::default_serialize(), MAD_ARCHIVE_DEBUG, madness::archive::serialize(), and madness::archive::ArchiveSerializeImpl< Archive, T, Enabler >::serialize().
Referenced by madness::archive::ArchiveLoadImpl< Archive, std::shared_ptr< const FunctionImpl< T, NDIM > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::shared_ptr< FunctionImpl< T, NDIM > > >::load(), and madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_load().
load() [2/2]
template<class Archive , class T , typename Enabler > template<typename A = Archive, typename U = T, typename = std::enable_if_t<is_input_archive_v<A> && std::is_function<U>::value>> static void madness::archive::ArchiveLoadImpl< Archive, T, Enabler >::load (const Archive & ar, U & t) inline static
Load function reference stored as function pointer.
Parameters
[in] ar The archive.
[in] t The data.
References madness::archive::default_serialize(), MAD_ARCHIVE_DEBUG, and madness::archive::serialize().
The documentation for this struct was generated from the following file:
archive.h