MADNESS: refop Struct Reference
refop Struct Reference
Public Member Functions
bool operator() (FunctionImpl< double_complex, 1 > *impl, const Key< 1 > &key, const Tensor< double_complex > &t) const
bool operator() (FunctionImpl< double_complex, 1 > *impl, const Key< 1 > &key, const Tensor< double_complex > &t) const
bool operator() (FunctionImpl< double_complex, 3 > *impl, const Key< 3 > &key, const Tensor< double_complex > &t) const
template<typename Archive >
void serialize (Archive &ar)
template<typename Archive >
void serialize (Archive &ar)
template<typename Archive >
void serialize (Archive &ar)
Member Function Documentation
operator()() [1/3]
bool refop::operator() (FunctionImpl< double_complex, 1 > * impl, const Key< 1 > & key, const Tensor< double_complex > & t) const inline
References madness::FunctionImpl< T, NDIM >::get_thresh(), lo, madness::FunctionImpl< T, NDIM >::tnorm(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
operator()() [2/3]
bool refop::operator() (FunctionImpl< double_complex, 1 > * impl, const Key< 1 > & key, const Tensor< double_complex > & t) const inline
References madness::FunctionImpl< T, NDIM >::get_thresh(), lo, madness::FunctionImpl< T, NDIM >::tnorm(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
operator()() [3/3]
bool refop::operator() (FunctionImpl< double_complex, 3 > * impl, const Key< 3 > & key, const Tensor< double_complex > & t) const inline
References madness::FunctionImpl< T, NDIM >::get_thresh(), lo, madness::FunctionImpl< T, NDIM >::tnorm(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
serialize() [1/3]
template<typename Archive > void refop::serialize (Archive & ar) inline
serialize() [2/3]
template<typename Archive > void refop::serialize (Archive & ar) inline
serialize() [3/3]
template<typename Archive > void refop::serialize (Archive & ar) inline
The documentation for this struct was generated from the following files:
tdse.cc
tdse1d.cc
testsuite.cc