MADNESS: madness::detail::scaleinplace< T, NDIM > Struct Template Reference
madness::detail::scaleinplace< T, NDIM > Struct Template Reference
#include <mraimpl.h>
Public Member Functions
scaleinplace ()
scaleinplace (T q)
void operator() (const Key< NDIM > &key, FunctionNode< T, NDIM > &node) const
void operator() (const Key< NDIM > &key, Tensor< T > &t) const
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
T q
Constructor & Destructor Documentation
scaleinplace() [1/2]
template<typename T , std::size_t NDIM> madness::detail::scaleinplace< T, NDIM >::scaleinplace () inline
scaleinplace() [2/2]
template<typename T , std::size_t NDIM> madness::detail::scaleinplace< T, NDIM >::scaleinplace (T q) inline
References madness::detail::scaleinplace< T, NDIM >::q.
Member Function Documentation
operator()() [1/2]
template<typename T , std::size_t NDIM> void madness::detail::scaleinplace< T, NDIM >::operator() (const Key< NDIM > & key, FunctionNode< T, NDIM > & node) const inline
References madness::FunctionNode< T, NDIM >::coeff(), madness::detail::scaleinplace< T, NDIM >::q, and madness::GenTensor< T >::scale().
operator()() [2/2]
template<typename T , std::size_t NDIM> void madness::detail::scaleinplace< T, NDIM >::operator() (const Key< NDIM > & key, Tensor< T > & t) const inline
References madness::detail::scaleinplace< T, NDIM >::q, and madness::Tensor< T >::scale().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::detail::scaleinplace< T, NDIM >::serialize (Archive & ar) inline
References madness::detail::scaleinplace< T, NDIM >::q.
Member Data Documentation
q
template<typename T , std::size_t NDIM> T madness::detail::scaleinplace< T, NDIM >::q
Referenced by madness::detail::scaleinplace< T, NDIM >::scaleinplace(), madness::detail::scaleinplace< T, NDIM >::operator()(), madness::detail::scaleinplace< T, NDIM >::operator()(), and madness::detail::scaleinplace< T, NDIM >::serialize().
The documentation for this struct was generated from the following file:
mraimpl.h