MADNESS: madness::PlotParameters Struct Reference
madness::PlotParameters Struct Reference
#include <funcplot.h>
Public Member Functions
PlotParameters ()
PlotParameters (World &world, const commandlineparser parser=commandlineparser(), const std::string tag="plot")
long npoints () const
template<std::size_t NDIM>
Vector< double, NDIM > origin () const
std::vector< std::string > plane () const
PlotParameters & set_npoints (const long n)
PlotParameters & set_origin (const std::vector< double > origin)
PlotParameters & set_plane (const std::vector< std::string > plane)
PlotParameters & set_zoom (const double z)
double zoom () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool operator== (const QCCalculationParametersBase &other) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
void to_json (json &j) const
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys =true
bool ignore_unknown_keys_silently =false
ParameterContainerT parameters
bool print_debug =false
bool throw_if_datagroup_not_found =true
Constructor & Destructor Documentation
PlotParameters() [1/2]
madness::PlotParameters::PlotParameters (World & world, const commandlineparser parser = commandlineparser(), const std::string tag = "plot") inline
References madness::QCCalculationParametersBase::read_input_and_commandline_options().
PlotParameters() [2/2]
madness::PlotParameters::PlotParameters () inline
Member Function Documentation
npoints()
long madness::PlotParameters::npoints () const inline
origin()
template<std::size_t NDIM> Vector<double,NDIM> madness::PlotParameters::origin () const inline
References NDIM.
Referenced by set_origin().
plane()
std::vector<std::string> madness::PlotParameters::plane () const inline
Referenced by set_plane().
set_npoints()
PlotParameters& madness::PlotParameters::set_npoints (const long n) inline
References madness::QCCalculationParametersBase::set_user_defined_value().
set_origin()
PlotParameters& madness::PlotParameters::set_origin (const std::vector< double > origin) inline
References origin(), and madness::QCCalculationParametersBase::set_user_defined_value().
set_plane()
PlotParameters& madness::PlotParameters::set_plane (const std::vector< std::string > plane) inline
References plane(), and madness::QCCalculationParametersBase::set_user_defined_value().
set_zoom()
PlotParameters& madness::PlotParameters::set_zoom (const double z) inline
References madness::QCCalculationParametersBase::set_user_defined_value().
zoom()
double madness::PlotParameters::zoom () const inline
The documentation for this struct was generated from the following file:
funcplot.h