MADNESS: SolverTargetInterface Struct Reference
SolverTargetInterface Struct Reference abstract
The interface to be provided by.
Public Member Functions
virtual ~SolverTargetInterface ()
virtual Tensor< double > jacobian (const Tensor< double > &x)
virtual bool provides_jacobian () const =0
virtual Tensor< double > residual (const Tensor< double > &x)=0
virtual void residual_and_jacobian (const Tensor< double > &x, Tensor< double > &residual, Tensor< double > &jacobian)
Detailed Description
The interface to be provided by.
Constructor & Destructor Documentation
~SolverTargetInterface()
virtual SolverTargetInterface::~SolverTargetInterface () inline virtual
Member Function Documentation
jacobian()
virtual Tensor< double > SolverTargetInterface::jacobian (const Tensor< double > & x) inline virtual
Referenced by residual_and_jacobian().
provides_jacobian()
virtual bool SolverTargetInterface::provides_jacobian () const pure virtual
residual()
virtual Tensor< double > SolverTargetInterface::residual (const Tensor< double > & x) pure virtual
Referenced by residual_and_jacobian().
residual_and_jacobian()
virtual void SolverTargetInterface::residual_and_jacobian (const Tensor< double > & x, Tensor< double > & residual, Tensor< double > & jacobian) inline virtual
References jacobian(), and residual().
The documentation for this struct was generated from the following file:
kain.cc