MADNESS: madness::ResponseParameters Struct Reference
madness::ResponseParameters Struct Reference
#include <response_parameters.h>
Public Member Functions
ResponseParameters ()
ResponseParameters (const ResponseParameters &other)=default
ResponseParameters (World &world, const commandlineparser &parser)
std::string archive () const
std::string calc_type () const
std::string d2_types () const
double dconv () const
std::string deriv () const
std::string dft_deriv () const
bool dipole () const
double econv () const
bool excited_state () const
bool first_order () const
bool first_run () const
std::string fock_json_file () const
vector< double > freq_range () const
size_t guess_max_iter () const
bool guess_xyz () const
std::string hfexalg () const
int k () const
bool kain () const
double L () const
size_t larger_subspace () const
double lo () const
int loadbalparts () const
std::string local () const
std::string localize () const
size_t maxiter () const
double maxrotn () const
size_t maxsub () const
bool nuclear () const
size_t num_orbitals () const
size_t num_states () const
bool nwchem () const
std::string nwchem_dir () const
double omega () const
std::string perturbation () const
std::vector< std::string > perturbations () const
bool plot () const
bool plot_all_orbitals () const
bool plot_initial () const
double plot_l () const
size_t plot_pts () const
std::string prefix () const
int print_level () const
bool property () const
std::vector< double > protocol () const
bool quadratic () const
bool random () const
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
bool restart () const
std::string restart_file () const
bool save () const
std::string save_file () const
bool second_order () const
void set_derived_values (World &world, const Molecule &molecule)
void set_ground_state_calculation_data (const GroundStateCalculation &g_params)
bool spinrestricted () const
bool step_restrict () const
bool store_potential () const
bool tda () const
bool third_order () const
std::string xc () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
virtual std::string get_tag () const =0
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (const std::list< std::string > precedences={"all"}) const
template<typename... Types>
void qcparameter_to_json (json &j, const std::pair< std::string, QCParameter > &p, const std::tuple< Types... > &) const
template<typename Tuple >
void qcparameter_to_json_from_tuple (json &j, const std::pair< std::string, QCParameter > &p, const Tuple &) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
convert all parameters to a json object
void to_json (json &j) const
convert all parameters to a json object
json to_json_if_precedence (const std::string &precedence) const
convert all parameters to a json object, but only those with a given precedence
template<typename... Types>
bool try_set_from_json (QCParameter &parameter, const nlohmann::json &value)
Static Public Attributes
static constexpr char const * tag = "response"
Additional Inherited Members
Public Types inherited from madness::QCCalculationParametersBase
using all_parameter_types = std::tuple< double, int, unsigned int, long, std::size_t, bool, std::string, std::vector< double >, std::vector< int >, std::vector< std::size_t >, std::vector< std::string >, std::pair< std::string, double > >
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string &key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename Tuple >
bool try_setting_any (const std::string &key, const std::string &value)
helper function for try_setting_user_defined_value
template<typename Tuple , std::size_t... I>
bool try_setting_any_impl (const std::string &key, const std::string &value, Tuple, std::index_sequence< I... >)
helper function for try_setting_user_defined_value
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
helper function for try_setting_user_defined_value
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys = true
bool ignore_unknown_keys_silently = false
ParameterContainerT parameters
bool print_debug = false
bool throw_if_datagroup_not_found = true
Constructor & Destructor Documentation
ResponseParameters() [1/3]
madness::ResponseParameters::ResponseParameters (const ResponseParameters & other) default
ResponseParameters() [2/3]
madness::ResponseParameters::ResponseParameters (World & world, const commandlineparser & parser) inline
References read_input_and_commandline_options().
ResponseParameters() [3/3]
madness::ResponseParameters::ResponseParameters () inline
Member Function Documentation
archive()
std::string madness::ResponseParameters::archive () const inline
calc_type()
std::string madness::ResponseParameters::calc_type () const inline
d2_types()
std::string madness::ResponseParameters::d2_types () const inline
dconv()
double madness::ResponseParameters::dconv () const inline
deriv()
std::string madness::ResponseParameters::deriv () const inline
dft_deriv()
std::string madness::ResponseParameters::dft_deriv () const inline
dipole()
bool madness::ResponseParameters::dipole () const inline
Referenced by set_derived_values().
econv()
double madness::ResponseParameters::econv () const inline
excited_state()
bool madness::ResponseParameters::excited_state () const inline
Referenced by set_derived_values().
first_order()
bool madness::ResponseParameters::first_order () const inline
first_run()
bool madness::ResponseParameters::first_run () const inline
fock_json_file()
std::string madness::ResponseParameters::fock_json_file () const inline
Referenced by main().
freq_range()
vector< double > madness::ResponseParameters::freq_range () const inline
guess_max_iter()
size_t madness::ResponseParameters::guess_max_iter () const inline
guess_xyz()
bool madness::ResponseParameters::guess_xyz () const inline
hfexalg()
std::string madness::ResponseParameters::hfexalg () const inline
Referenced by make_k().
k()
int madness::ResponseParameters::k () const inline
kain()
bool madness::ResponseParameters::kain () const inline
L()
double madness::ResponseParameters::L () const inline
larger_subspace()
size_t madness::ResponseParameters::larger_subspace () const inline
lo()
double madness::ResponseParameters::lo () const inline
loadbalparts()
int madness::ResponseParameters::loadbalparts () const inline
local()
std::string madness::ResponseParameters::local () const inline
localize()
std::string madness::ResponseParameters::localize () const inline
maxiter()
size_t madness::ResponseParameters::maxiter () const inline
maxrotn()
double madness::ResponseParameters::maxrotn () const inline
maxsub()
size_t madness::ResponseParameters::maxsub () const inline
nuclear()
bool madness::ResponseParameters::nuclear () const inline
Referenced by set_derived_values().
num_orbitals()
size_t madness::ResponseParameters::num_orbitals () const inline
num_states()
size_t madness::ResponseParameters::num_states () const inline
nwchem()
bool madness::ResponseParameters::nwchem () const inline
nwchem_dir()
std::string madness::ResponseParameters::nwchem_dir () const inline
omega()
double madness::ResponseParameters::omega () const inline
perturbation()
std::string madness::ResponseParameters::perturbation () const inline
perturbations()
std::vector< std::string > madness::ResponseParameters::perturbations () const inline
plot()
bool madness::ResponseParameters::plot () const inline
plot_all_orbitals()
bool madness::ResponseParameters::plot_all_orbitals () const inline
plot_initial()
bool madness::ResponseParameters::plot_initial () const inline
plot_l()
double madness::ResponseParameters::plot_l () const inline
plot_pts()
size_t madness::ResponseParameters::plot_pts () const inline
prefix()
std::string madness::ResponseParameters::prefix () const inline
print_level()
int madness::ResponseParameters::print_level () const inline
property()
bool madness::ResponseParameters::property () const inline
protocol()
std::vector< double > madness::ResponseParameters::protocol () const inline
quadratic()
bool madness::ResponseParameters::quadratic () const inline
random()
bool madness::ResponseParameters::random () const inline
read_input_and_commandline_options()
void madness::QCCalculationParametersBase::read_input_and_commandline_options (World & world, const commandlineparser & parser, const std::string tag) inline
Referenced by ResponseParameters().
restart()
bool madness::ResponseParameters::restart () const inline
restart_file()
std::string madness::ResponseParameters::restart_file () const inline
save()
bool madness::ResponseParameters::save () const inline
save_file()
std::string madness::ResponseParameters::save_file () const inline
second_order()
bool madness::ResponseParameters::second_order () const inline
set_derived_values()
void madness::ResponseParameters::set_derived_values (World & world, const Molecule & molecule) inline
References dipole(), excited_state(), molecule, madness::Molecule::natom(), nuclear(), and tda().
set_ground_state_calculation_data()
void madness::ResponseParameters::set_ground_state_calculation_data (const GroundStateCalculation & g_params) inline
References GroundStateCalculation::get_L(), GroundStateCalculation::get_localize_method(), GroundStateCalculation::get_xc(), GroundStateCalculation::is_spinrestricted(), GroundStateCalculation::molecule(), GroundStateCalculation::n_orbitals(), and madness::Molecule::smallest_length_scale().
spinrestricted()
bool madness::ResponseParameters::spinrestricted () const inline
step_restrict()
bool madness::ResponseParameters::step_restrict () const inline
store_potential()
bool madness::ResponseParameters::store_potential () const inline
tda()
bool madness::ResponseParameters::tda () const inline
Referenced by set_derived_values().
third_order()
bool madness::ResponseParameters::third_order () const inline
xc()
std::string madness::ResponseParameters::xc () const inline
Member Data Documentation
tag
constexpr char const* madness::ResponseParameters::tag = "response" static constexpr
The documentation for this struct was generated from the following file:
response_parameters.h