MADNESS: Node Struct Reference
Node Struct Reference
Classes
struct do_random_insert
Public Types
typedef WorldContainer< Key, Node > dcT
typedef WorldContainer< Key, Node > dcT
Public Member Functions
Node ()
Node ()
Node ()
Node (const Node &node)
Node (const Node &node)
Node (double value)
Node (double value)
Node (int k)
~Node ()
double do_sum (vector< Future< double > > v)
Future< double > do_sum_spawn (const dcT &d, const Key &key)
int get () const
double get () const
double get () const
bool is_leaf () const
bool is_leaf () const
void random_insert (const dcT &constd, const Key &key, double valin)
void random_insert (const dcT &constd, const Key &keyin, double valin)
void recursive_print (const dcT &d, const Key &key) const
template<class Archive >
void serialize (Archive &ar)
template<class Archive >
void serialize (Archive &ar)
template<typename Archive >
void serialize (const Archive &ar)
void set (double v)
void set (double v)
Public Attributes
bool isleaf
int k
Key key
double value
Member Typedef Documentation
dcT [1/2]
typedef WorldContainer<Key,Node> Node::dcT
dcT [2/2]
typedef WorldContainer<Key,Node> Node::dcT
Constructor & Destructor Documentation
Node() [1/8]
Node::Node () inline
Node() [2/8]
Node::Node (int k) inline
~Node()
Node::~Node () inline
Node() [3/8]
Node::Node () inline
Node() [4/8]
Node::Node (double value) inline
Node() [5/8]
Node::Node (const Node & node) inline
Node() [6/8]
Node::Node () inline
Node() [7/8]
Node::Node (double value) inline
Node() [8/8]
Node::Node (const Node & node) inline
Member Function Documentation
do_sum()
double Node::do_sum (vector< Future< double > > v) inline
References get(), sum, v, and value.
Referenced by do_sum_spawn().
do_sum_spawn()
Future< double > Node::do_sum_spawn (const dcT & d, const Key & key) inline
References d, do_sum(), do_sum_spawn(), is_leaf(), key, v, and value.
Referenced by do_sum_spawn(), and doit().
get() [1/3]
int Node::get () const inline
References k.
Referenced by do_sum(), and operator<<().
get() [2/3]
double Node::get () const inline
References value.
get() [3/3]
double Node::get () const inline
References value.
is_leaf() [1/2]
bool Node::is_leaf () const inline
References isleaf.
Referenced by do_sum_spawn(), operator<<(), recursive_print(), walker1(), and walker2().
is_leaf() [2/2]
bool Node::is_leaf () const inline
References isleaf.
random_insert() [1/2]
void Node::random_insert (const dcT & constd, const Key & key, double valin) inline
References d, madness::World::drand(), isleaf, key, ran(), random_insert(), and value.
Referenced by doit(), Node::do_random_insert::operator()(), random_insert(), and test11().
random_insert() [2/2]
void Node::random_insert (const dcT & constd, const Key & keyin, double valin) inline
References d, madness::World::drand(), isleaf, key, MADNESS_CHECK, madness::Key< NDIM >::n, ran(), and value.
recursive_print()
void Node::recursive_print (const dcT & d, const Key & key) const inline
References d, is_leaf(), key, madness::Key< NDIM >::n, and recursive_print().
Referenced by doit(), and recursive_print().
serialize() [1/3]
template<class Archive > void Node::serialize (Archive & ar) inline
References isleaf, and value.
serialize() [2/3]
template<class Archive > void Node::serialize (Archive & ar) inline
References isleaf, key, and value.
serialize() [3/3]
template<typename Archive > void Node::serialize (const Archive & ar) inline
References k.
set() [1/2]
void Node::set (double v) inline
References v, and value.
Referenced by walker1(), and walker2().
set() [2/2]
void Node::set (double v) inline
References v, and value.
Member Data Documentation
isleaf
bool Node::isleaf
Referenced by is_leaf(), random_insert(), random_insert(), and serialize().
k
int Node::k
Referenced by get(), operator<<(), and serialize().
key
Key Node::key
Referenced by do_sum_spawn(), Node::do_random_insert::operator()(), random_insert(), random_insert(), recursive_print(), and serialize().
value
double Node::value
Referenced by do_sum(), do_sum_spawn(), get(), random_insert(), random_insert(), serialize(), and set().
The documentation for this struct was generated from the following files:
test_dc.cc
test_tree.cc
test_world.cc