MADNESS: madness::R_times_arg_div_R Struct Reference
madness::R_times_arg_div_R Struct Reference
compute the expression (\sum_i R_i)^(-1) \sum_i R_i arg(r,B,v_i)
Public Member Functions
R_times_arg_div_R (std::function< double(const coord_3d &r, const coord_3d &B, const coord_3d &v)> &arg, const coord_3d &B, const std::vector< coord_3d > &vv, const double radius)
double operator() (const coord_3d &r) const
Public Attributes
std::function< double(const coord_3d &r, const coord_3d &B, const coord_3d &vv)> & arg
const coord_3d & B
const double radius
double tightness
const std::vector< coord_3d > & vv
Detailed Description
compute the expression (\sum_i R_i)^(-1) \sum_i R_i arg(r,B,v_i)
see compute_T_commutator_vector_term() for an example
Parameters
[in] arg the function argument arg(r,B,v)
[in] B magnetic field
[in] v the position of the nuclei (centers of the Gaussian) in A space
Constructor & Destructor Documentation
R_times_arg_div_R()
madness::R_times_arg_div_R::R_times_arg_div_R (std::function< double(const coord_3d &r, const coord_3d &B, const coord_3d &v)> & arg, const coord_3d & B, const std::vector< coord_3d > & vv, const double radius) inline
References madness::max_of_x_1_smooth::compute_tightness(), radius, and tightness.
Member Function Documentation
operator()()
double madness::R_times_arg_div_R::operator() (const coord_3d & r) const inline
References arg, madness::max_of_x_1_smooth::compute_factor(), madness::cross(), madness::inner(), MADNESS_ASSERT, madness::Vector< T, N >::normf(), radius, tightness, v, and vv.
Member Data Documentation
arg
std::function<double(const coord_3d& r, const coord_3d& B, const coord_3d& vv)>& madness::R_times_arg_div_R::arg
Referenced by operator()().
B
const coord_3d& madness::R_times_arg_div_R::B
radius
const double madness::R_times_arg_div_R::radius
Referenced by R_times_arg_div_R(), and operator()().
tightness
double madness::R_times_arg_div_R::tightness
Referenced by R_times_arg_div_R(), and operator()().
vv
const std::vector<coord_3d>& madness::R_times_arg_div_R::vv
Referenced by operator()().
The documentation for this struct was generated from the following file:
diamagneticpotentialfactor.cc