MADNESS: madness::archive::ArchiveLoadImpl< ParallelInputArchive< archiveT >, CCPairFunction< T, NDIM > > Struct Template Reference
madness::archive::ArchiveLoadImpl< ParallelInputArchive< archiveT >, CCPairFunction< T, NDIM > > Struct Template Reference
#include <ccpairfunction.h>
Static Public Member Functions
static void load (const ParallelInputArchive< archiveT > &ar, CCPairFunction< T, NDIM > &p)
Member Function Documentation
load()
template<class archiveT , class T , std::size_t NDIM> static void madness::archive::ArchiveLoadImpl< ParallelInputArchive< archiveT >, CCPairFunction< T, NDIM > >::load (const ParallelInputArchive< archiveT > & ar, CCPairFunction< T, NDIM > & p) inline static
References a, aa, b, madness::f, madness::archive::BaseParallelArchive< Archive >::get_world(), op(), madness::OT_UNDEFINED, p(), param, and madness::type().
The documentation for this struct was generated from the following file:
ccpairfunction.h