MADNESS: madness::LBCost Struct Reference
madness::LBCost Struct Reference
#include <mp2.h>
Public Member Functions
LBCost (double leaf_value=1.0, double parent_value=1.0)
double operator() (const Key< 6 > &key, const FunctionNode< double, 6 > &node) const
Public Attributes
double leaf_value
double parent_value
Constructor & Destructor Documentation
LBCost()
madness::LBCost::LBCost (double leaf_value = 1.0, double parent_value = 1.0) inline
Member Function Documentation
operator()()
double madness::LBCost::operator() (const Key< 6 > & key, const FunctionNode< double, 6 > & node) const inline
References madness::FunctionNode< T, NDIM >::coeff(), and madness::GenTensor< T >::size().
Referenced by madness::load_balance().
Member Data Documentation
leaf_value
double madness::LBCost::leaf_value
parent_value
double madness::LBCost::parent_value
The documentation for this struct was generated from the following file:
mp2.h