MADNESS: madness::MyTimer Struct Reference
madness::MyTimer Struct Reference
Timer structure.
#include <PNOStructures.h>
Public Member Functions
MyTimer (World &world)
MyTimer print () const
MyTimer print (const std::string &msg) const
MyTimer start () const
MyTimer stop ()
Public Attributes
double cstart_
double cstop_
double ctime_
std::string msg_
World & world
double wstart_
double wstop_
double wtime_
Detailed Description
Timer structure.
Constructor & Destructor Documentation
MyTimer()
madness::MyTimer::MyTimer (World & world) inline
Member Function Documentation
print() [1/2]
MyTimer madness::MyTimer::print () const inline
References ctime_, msg_, madness::World::rank(), world, and wtime_.
print() [2/2]
MyTimer madness::MyTimer::print (const std::string & msg) const inline
References ctime_, msg_, madness::World::rank(), world, and wtime_.
Referenced by madness::F12Potentials::F12Potentials(), madness::F12Potentials::apply_regularized_potential(), madness::F12Potentials::compute_hylleraas_f12_energies(), madness::F12Potentials::compute_projected_f12_energies(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::PNO::compute_Vreg_aj_i(), madness::PNO::compute_Vreg_aj_i_commutator_response(), madness::PNO::compute_Vreg_aj_i_fock_residue(), madness::F12Potentials::convolve_with_U(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::PNO::iterate_pairs_internal(), madness::F12Potentials::read_cabs_from_file(), madness::PNO::solve_cispd(), and madness::PNO::solve_mp2().
start()
MyTimer madness::MyTimer::start () const inline
References madness::cpu_time(), cstart_, madness::WorldGopInterface::fence(), madness::World::gop, madness::wall_time(), world, and wstart_.
Referenced by madness::F12Potentials::F12Potentials(), madness::F12Potentials::apply_regularized_potential(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_f12_correction_gs(), madness::F12Potentials::compute_hylleraas_f12_energies(), madness::F12Potentials::compute_projected_f12_energies(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::PNO::compute_Vreg_aj_i(), madness::PNO::compute_Vreg_aj_i_commutator_response(), madness::PNO::compute_Vreg_aj_i_fock_residue(), madness::F12Potentials::convolve_with_U(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::PNO::iterate_pairs_internal(), madness::F12Potentials::read_cabs_from_file(), madness::PNO::solve_cispd(), and madness::PNO::solve_mp2().
stop()
MyTimer madness::MyTimer::stop () inline
References madness::cpu_time(), cstart_, cstop_, ctime_, madness::wall_time(), wstart_, wstop_, and wtime_.
Referenced by madness::F12Potentials::F12Potentials(), madness::F12Potentials::apply_regularized_potential(), madness::F12Potentials::compute_hylleraas_f12_energies(), madness::F12Potentials::compute_projected_f12_energies(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::PNO::compute_Vreg_aj_i(), madness::PNO::compute_Vreg_aj_i_commutator_response(), madness::PNO::compute_Vreg_aj_i_fock_residue(), madness::F12Potentials::convolve_with_U(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::PNO::iterate_pairs_internal(), madness::F12Potentials::read_cabs_from_file(), madness::PNO::solve_cispd(), and madness::PNO::solve_mp2().
Member Data Documentation
cstart_
double madness::MyTimer::cstart_
Referenced by start(), and stop().
cstop_
double madness::MyTimer::cstop_
Referenced by stop().
ctime_
double madness::MyTimer::ctime_
Referenced by print(), print(), and stop().
msg_
std::string madness::MyTimer::msg_ mutable
Referenced by print(), and print().
world
World& madness::MyTimer::world
Referenced by print(), print(), and start().
wstart_
double madness::MyTimer::wstart_ mutable
Referenced by start(), and stop().
wstop_
double madness::MyTimer::wstop_ mutable
Referenced by stop().
wtime_
double madness::MyTimer::wtime_ mutable
Referenced by print(), print(), and stop().
The documentation for this struct was generated from the following file:
PNOStructures.h