MADNESS: HO_function< NDIM > Struct Template Reference
HO_function< NDIM > Struct Template Reference
Public Member Functions
HO_function (const double m, const double k, const std::vector< int > n)
double operator() (const Vector< double, NDIM > &r) const
Public Attributes
double alpha
std::vector< int > n
double normalization
Constructor & Destructor Documentation
HO_function()
template<std::size_t NDIM> HO_function< NDIM >::HO_function (const double m, const double k, const std::vector< int > n) inline
References HO_function< NDIM >::alpha, factorial(), HO_function< NDIM >::n, NDIM, HO_function< NDIM >::normalization, and madness::constants::pi.
Member Function Documentation
operator()()
template<std::size_t NDIM> double HO_function< NDIM >::operator() (const Vector< double, NDIM > & r) const inline
References HO_function< NDIM >::alpha, hermite(), madness::inner(), HO_function< NDIM >::n, NDIM, and HO_function< NDIM >::normalization.
Member Data Documentation
alpha
template<std::size_t NDIM> double HO_function< NDIM >::alpha
Referenced by HO_function< NDIM >::HO_function(), and HO_function< NDIM >::operator()().
n
template<std::size_t NDIM> std::vector<int> HO_function< NDIM >::n
Referenced by HO_function< NDIM >::HO_function(), and HO_function< NDIM >::operator()().
normalization
template<std::size_t NDIM> double HO_function< NDIM >::normalization
Referenced by HO_function< NDIM >::HO_function(), and HO_function< NDIM >::operator()().
The documentation for this struct was generated from the following file:
test_BSHApply.cc