MADNESS: madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM > Struct Template Reference
madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM > Struct Template Reference
#include <funcimpl.h>
Public Member Functions
pointwise_multiplier ()
pointwise_multiplier (const Key< NDIM > key, const coeffT &clhs, implT *i)
pointwise_multiplier (const Key< NDIM > key, const coeffT &clhs, implT *i, const FunctionImpl< T, LDIM > *gimpl)
coeffT operator() (const Key< NDIM > key, const coeffT &coeff_rhs)
multiply values of rhs and lhs, result on rhs, rhs and lhs are of the same dimensions
tensorT operator() (const Key< NDIM > key, const tensorT &coeff_rhs)
multiply values of rhs and lhs, result on rhs, rhs and lhs are of the same dimensions
coeffT operator() (const Key< NDIM > key, const tensorT &coeff_rhs, const int particle)
multiply values of rhs and lhs, result on rhs, rhs and lhs are of differnet dimensions
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
coeffT coeff_lhs
double error =0.0
const FunctionImpl< T, LDIM > * gimpl
double hi =0.0
double hi1 =0.0
double hi2 =0.0
const implT * impl
double lo =0.0
double lo1 =0.0
double lo2 =0.0
coeffT val_lhs
Constructor & Destructor Documentation
pointwise_multiplier() [1/3]
template<typename T , std::size_t NDIM> template<std::size_t LDIM> madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier () inline
pointwise_multiplier() [2/3]
template<typename T , std::size_t NDIM> template<std::size_t LDIM> madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier (const Key< NDIM > key, const coeffT & clhs, implT * i, const FunctionImpl< T, LDIM > * gimpl) inline
References madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::coeff_lhs, madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::GenTensor< T >::get_svdtensor(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::gimpl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi1, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi2, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo1, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo2, madness::FunctionImpl< T, NDIM >::tnorm(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::val_lhs.
pointwise_multiplier() [3/3]
template<typename T , std::size_t NDIM> template<std::size_t LDIM> madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier (const Key< NDIM > key, const coeffT & clhs, implT * i) inline
References madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::coeff_lhs, madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo, madness::FunctionImpl< T, NDIM >::tnorm(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::val_lhs.
Member Function Documentation
operator()() [1/3]
template<typename T , std::size_t NDIM> template<std::size_t LDIM> coeffT madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator() (const Key< NDIM > key, const coeffT & coeff_rhs) inline
multiply values of rhs and lhs, result on rhs, rhs and lhs are of the same dimensions
References madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::GenTensor< T >::emul(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo, madness::FunctionImpl< T, NDIM >::tnorm(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::val_lhs, and madness::FunctionImpl< T, NDIM >::values2coeffs().
operator()() [2/3]
template<typename T , std::size_t NDIM> template<std::size_t LDIM> tensorT madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator() (const Key< NDIM > key, const tensorT & coeff_rhs) inline
multiply values of rhs and lhs, result on rhs, rhs and lhs are of the same dimensions
References madness::FunctionImpl< T, NDIM >::cdata, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::coeff_lhs, madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::copy(), madness::GenTensor< T >::dim(), madness::BaseTensor::dim(), madness::Tensor< T >::emul(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::GenTensor< T >::full_tensor_copy(), madness::FunctionCommonData< T, NDIM >::get(), madness::FunctionImpl< T, NDIM >::get_k(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo, madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), madness::Tensor< T >::normf(), madness::FunctionImpl< T, NDIM >::tnorm(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::val_lhs, madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs(), and madness::FunctionImpl< T, NDIM >::values2coeffs().
operator()() [3/3]
template<typename T , std::size_t NDIM> template<std::size_t LDIM> coeffT madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator() (const Key< NDIM > key, const tensorT & coeff_rhs, const int particle) inline
multiply values of rhs and lhs, result on rhs, rhs and lhs are of differnet dimensions
References madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::cdata, madness::FunctionCommonFunctionality< T, NDIM >::cdata, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::coeff_lhs, madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::copy(), madness::GenTensor< T >::emul(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::FunctionImpl< T, NDIM >::get_k(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::gimpl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl, madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), madness::GenTensor< T >::normf(), madness::outer(), madness::GenTensor< T >::reduce_rank(), madness::FunctionImpl< T, NDIM >::targs, madness::GenTensor< T >::tensor_type(), madness::TensorArgs::thresh, madness::TT_2D, and madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs().
serialize()
template<typename T , std::size_t NDIM> template<std::size_t LDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::coeff_lhs, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::gimpl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi1, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi2, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo1, madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo2, and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::val_lhs.
Member Data Documentation
coeff_lhs
template<typename T , std::size_t NDIM> template<std::size_t LDIM> coeffT madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::coeff_lhs
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
error
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::error =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::make_sum_coeffs(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
gimpl
template<typename T , std::size_t NDIM> template<std::size_t LDIM> const FunctionImpl<T,LDIM>* madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::gimpl
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
hi
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
hi1
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi1 =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
hi2
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::hi2 =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
impl
template<typename T , std::size_t NDIM> template<std::size_t LDIM> const implT* madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::impl
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
lo
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
lo1
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo1 =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
lo2
template<typename T , std::size_t NDIM> template<std::size_t LDIM> double madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::lo2 =0.0
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
val_lhs
template<typename T , std::size_t NDIM> template<std::size_t LDIM> coeffT madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::val_lhs
Referenced by madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::pointwise_multiplier(), madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::pointwise_multiplier< LDIM >::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h