MADNESS: madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > > Struct Template Reference
madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > > Struct Template Reference
Write container to parallel archive.
#include <worlddc.h>
Static Public Member Functions
static void store (const ParallelOutputArchive< VectorOutputArchive > &ar, const WorldContainer< keyT, valueT > &t)
Detailed Description
template<class keyT, class valueT>
struct madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >
Write container to parallel archive.
specialization for parallel serialization of a WorldContainer: all threads on each process serialize some values into a buffer, which gets concatenated and finally serialized to localarchive (aka VectorOutputArchive).
Member Function Documentation
store()
template<class keyT , class valueT > static void madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >::store (const ParallelOutputArchive< VectorOutputArchive > & ar, const WorldContainer< keyT, valueT > & t) inline static
References madness::WorldTaskQueue::add(), std::advance(), madness::WorldContainer< keyT, valueT, hashfunT >::begin(), madness::WorldMpiInterface::comm(), madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldTaskQueue::fence(), madness::WorldGopInterface::fence(), SafeMPI::Intracomm::Get_mpi_comm(), madness::archive::BaseParallelArchive< Archive >::get_world(), madness::World::gop, madness::archive::BaseParallelArchive< Archive >::local_archive(), MADNESS_CHECK, madness::World::mpi, MPI_BYTE, MPI_Gather(), MPI_Gatherv(), MPI_INT, offset, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_store(), madness::World::rank(), run(), madness::ThreadPool::size(), madness::archive::BufferOutputArchive::size(), madness::World::size(), madness::WorldContainer< keyT, valueT, hashfunT >::size(), madness::WorldGopInterface::sum(), madness::World::taskq, and madness::wall_time().
The documentation for this struct was generated from the following file:
worlddc.h