MADNESS: madness::Nemo::NemoCalculationParameters Struct Reference
madness::Nemo::NemoCalculationParameters Struct Reference
class holding parameters for a nemo calculation beyond the standard dft parameters from moldft
#include <nemo.h>
Public Member Functions
NemoCalculationParameters ()
NemoCalculationParameters (const CalculationParameters &param)
NemoCalculationParameters (World &world, const commandlineparser &parser)
bool hessian () const
void initialize_nemo_parameters ()
std::pair< std::string, double > ncf () const
Public Member Functions inherited from madness::CalculationParameters
CalculationParameters ()
ctor reading out the input file
CalculationParameters (const CalculationParameters &other)=default
CalculationParameters (World &world, const commandlineparser &parser)
std::string ac_data () const
std::string algopt () const
std::string aobasis () const
double charge () const
bool converge_bsh_residual () const
bool converge_density () const
bool converge_each_energy () const
bool converge_total_energy () const
double dconv () const
std::string deriv () const
bool derivatives () const
std::string dft_deriv () const
bool dipole () const
bool do_localize () const
bool do_symmetry () const
double econv () const
bool ginitial_hessian () const
int gmaxiter () const
bool gopt () const
double gprec () const
double gtol () const
double gval () const
bool have_beta () const
std::string hfexalg () const
int k () const
double L () const
double lo () const
int loadbalparts () const
std::string localize_method () const
bool localize_pm () const
int maxiter () const
double maxrotn () const
int maxsub () const
int nalpha () const
int nbeta () const
int nmo_alpha () const
int nmo_beta () const
bool no_compute () const
int nopen () const
int nv_factor () const
int nvalpha () const
int nvbeta () const
std::string nwfile () const
double orbitalshift () const
std::string pcm_data () const
Tensor< double > plot_cell () const
std::string pointgroup () const
std::string prefix () const
int print_level () const
std::vector< double > protocol () const
virtual void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
bool restart () const
bool restart_cphf () const
bool restartao () const
bool save () const
void set_derived_values (const Molecule &molecule, const AtomicBasisSet &aobasis, const commandlineparser &parser)
bool spin_restricted () const
int vnucextra () const
std::string xc () const
Public Member Functions inherited from madness::QCCalculationParametersBase
bool file_exists (World &world, std::string filename) const
void from_json (const json &j)
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool operator== (const QCCalculationParametersBase &other) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
json to_json () const
void to_json (json &j) const
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys =true
bool ignore_unknown_keys_silently =false
ParameterContainerT parameters
bool print_debug =false
bool throw_if_datagroup_not_found =true
Detailed Description
class holding parameters for a nemo calculation beyond the standard dft parameters from moldft
Constructor & Destructor Documentation
NemoCalculationParameters() [1/3]
madness::Nemo::NemoCalculationParameters::NemoCalculationParameters (World & world, const commandlineparser & parser) inline
References initialize_nemo_parameters().
NemoCalculationParameters() [2/3]
madness::Nemo::NemoCalculationParameters::NemoCalculationParameters (const CalculationParameters & param) inline
References initialize_nemo_parameters().
NemoCalculationParameters() [3/3]
madness::Nemo::NemoCalculationParameters::NemoCalculationParameters () inline
References initialize_nemo_parameters().
Member Function Documentation
hessian()
bool madness::Nemo::NemoCalculationParameters::hessian () const inline
References madness::nonlinear_vector_solver().
initialize_nemo_parameters()
void madness::Nemo::NemoCalculationParameters::initialize_nemo_parameters () inline
References madness::nonlinear_vector_solver(), and madness::QCCalculationParametersBase::set_derived_value().
Referenced by NemoCalculationParameters(), NemoCalculationParameters(), and NemoCalculationParameters().
ncf()
std::pair< std::string, double > madness::Nemo::NemoCalculationParameters::ncf () const inline
References madness::nonlinear_vector_solver().
Referenced by madness::Znemo::recompute_factors_and_potentials(), and madness::Nemo::set_protocol().
The documentation for this struct was generated from the following file:
nemo.h