MADNESS: madness::archive::ArchiveLoadImpl< Archive, Tensor< T > > Struct Template Reference
madness::archive::ArchiveLoadImpl< Archive, Tensor< T > > Struct Template Reference
Deserialize a tensor ... existing tensor is replaced.
#include <tensor.h>
Static Public Member Functions
static void load (const Archive &s, Tensor< T > &t)
Detailed Description
template<class Archive, typename T>
struct madness::archive::ArchiveLoadImpl< Archive, Tensor< T > >
Deserialize a tensor ... existing tensor is replaced.
Member Function Documentation
load()
template<class Archive , typename T > static void madness::archive::ArchiveLoadImpl< Archive, Tensor< T > >::load (const Archive & s, Tensor< T > & t) inline static
References madness::BaseTensor::id(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), TENSOR_MAXDIM, and madness::archive::wrap().
The documentation for this struct was generated from the following file:
tensor.h