MADNESS: madness::InitParameters Struct Reference
madness::InitParameters Struct Reference
#include <InitParameters.h>
Public Member Functions
InitParameters ()
void print_params () const
void read (World &world, const std::string &filename, bool restart, bool Krestricted)
void readnw (World &world, const std::string &filename, bool Krestricted)
Public Attributes
bool closed_shell
Tensor< double > energies
Energies of input orbitals.
std::string inFile
Name of input archive to read in.
double Init_total_energy
Total energy of the nonrelativistic ground state.
double L
Box size of input - Dirac Fock calcluation is in same box.
Molecule molecule
The molecule used in input calculation.
unsigned int num_occupied
Number of orbitals.
Tensor< double > occ
Occupancy of input orbitals.
std::vector< Fcwf > orbitals
The occupied orbitals.
int order
Order of polynomial used in input.
bool spinrestricted
Indicates if input calc. was spin-restricted.
Constructor & Destructor Documentation
InitParameters()
madness::InitParameters::InitParameters () inline
Member Function Documentation
print_params()
void madness::InitParameters::print_params () const inline
References energies, inFile, Init_total_energy, L, num_occupied, order, madness::print(), and spinrestricted.
Referenced by DF::DF().
read()
void madness::InitParameters::read (World & world, const std::string & filename, bool restart, bool Krestricted) inline
References closed_shell, madness::copy(), energies, madness::filename, madness::function_real2complex(), inFile, Init_total_energy, L, MADNESS_CHECK, molecule, myxfunc(), myyfunc(), Fcwf::normalize(), num_occupied, occ, orbitals, order, madness::print(), madness::World::rank(), Fcwf::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), spinrestricted, and xc.
Referenced by DF::DF().
readnw()
void madness::InitParameters::readnw (World & world, const std::string & filename, bool Krestricted) inline
References madness::Molecule::add_atom(), slymer::ES_Interface::atoms, slymer::Properties::Basis, slymer::ES_Interface::basis_set, slymer::ES_Interface::beta_energies, slymer::ES_Interface::beta_occupancies, closed_shell, energies, slymer::Properties::Energies, slymer::ES_Interface::energies, slymer::ES_Interface::err, madness::filename, madness::function_real2complex(), madness::FunctionFactory< T, NDIM >::functor(), Init_total_energy, L, MADNESS_ASSERT, MADNESS_CHECK, molecule, slymer::Properties::MOs, slymer::ES_Interface::MOs, madness::norm2(), Fcwf::normalize(), madness::normalize(), num_occupied, slymer::Properties::Occupancies, slymer::ES_Interface::occupancies, orbitals, order, madness::print(), q(), madness::World::rank(), slymer::NWChem_Interface::read(), Fcwf::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::BaseTensor::size(), madness::symbol_to_atomic_number(), and madness::transform().
Referenced by DF::DF().
Member Data Documentation
closed_shell
bool madness::InitParameters::closed_shell
Referenced by DF::DF(), read(), and readnw().
energies
Tensor<double> madness::InitParameters::energies
Energies of input orbitals.
Referenced by DF::DF(), print_params(), read(), and readnw().
inFile
std::string madness::InitParameters::inFile
Name of input archive to read in.
Referenced by print_params(), and read().
Init_total_energy
double madness::InitParameters::Init_total_energy
Total energy of the nonrelativistic ground state.
Referenced by DF::DF(), print_params(), read(), and readnw().
L
double madness::InitParameters::L
Box size of input - Dirac Fock calcluation is in same box.
Referenced by print_params(), read(), readnw(), and DF::saveDF().
molecule
Molecule madness::InitParameters::molecule
The molecule used in input calculation.
Referenced by DF::make_fermi_potential(), DF::make_gaussian_potential(), DF::make_gaussian_potential(), DF::print_molecule(), read(), readnw(), and DF::saveDF().
num_occupied
unsigned int madness::InitParameters::num_occupied
Number of orbitals.
Referenced by DF::DF(), DF::DF_load_balance(), DF::diagonalize(), DF::exchange(), DF::iterate(), DF::make_component_lineplots(), DF::make_component_logplots(), DF::make_density_lineplots(), print_params(), DF::print_sizes(), read(), readnw(), DF::saveDF(), and DF::solve_occupied().
occ
Tensor<double> madness::InitParameters::occ
Occupancy of input orbitals.
Referenced by read().
orbitals
std::vector<Fcwf> madness::InitParameters::orbitals
The occupied orbitals.
Referenced by DF::DF(), read(), and readnw().
order
int madness::InitParameters::order
Order of polynomial used in input.
Referenced by DF::DF(), print_params(), read(), readnw(), and DF::saveDF().
spinrestricted
bool madness::InitParameters::spinrestricted
Indicates if input calc. was spin-restricted.
Referenced by print_params(), and read().
The documentation for this struct was generated from the following file:
InitParameters.h