MADNESS: madness::archive::ArchivePrePostImpl< Archive, T > Struct Template Reference
madness::archive::ArchivePrePostImpl< Archive, T > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Default implementation of the pre/postamble for type checking.
#include <archive.h>
Static Public Member Functions
static void postamble_load (const Archive &)
By default there is no postamble.
static void postamble_store (const Archive &)
By default there is no postamble.
static void preamble_load (const Archive &ar)
Deserialize a cookie and check the type.
static void preamble_store (const Archive &ar)
Serialize a cookie for type checking.
Detailed Description
template<class Archive, class T>
struct madness::archive::ArchivePrePostImpl< Archive, T >
Default implementation of the pre/postamble for type checking.
Template Parameters
Archive The archive class.
T The type to serialized or to expect upon deserialization.
Member Function Documentation
postamble_load()
template<class Archive , class T > static void madness::archive::ArchivePrePostImpl< Archive, T >::postamble_load (const Archive &) inline static
By default there is no postamble.
Referenced by madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load(), and madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_load().
postamble_store()
template<class Archive , class T > static void madness::archive::ArchivePrePostImpl< Archive, T >::postamble_store (const Archive &) inline static
By default there is no postamble.
Referenced by madness::archive::ArchiveStoreImpl< ParallelOutputArchive< localarchiveT >, WorldContainer< keyT, valueT > >::store(), madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >::store(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store(), and madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_store().
preamble_load()
template<class Archive , class T > static void madness::archive::ArchivePrePostImpl< Archive, T >::preamble_load (const Archive & ar) inline static
Deserialize a cookie and check the type.
Parameters
[in] ar The archive.
References madness::archive::archive_type_names, bufsize, MAD_ARCHIVE_DEBUG, and MADNESS_EXCEPTION.
Referenced by madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load(), and madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_load().
preamble_store()
template<class Archive , class T > static void madness::archive::ArchivePrePostImpl< Archive, T >::preamble_store (const Archive & ar) inline static
Serialize a cookie for type checking.
Parameters
[in] ar The archive.
References madness::archive::archive_type_names, and MAD_ARCHIVE_DEBUG.
Referenced by madness::archive::ArchiveStoreImpl< ParallelOutputArchive< localarchiveT >, WorldContainer< keyT, valueT > >::store(), madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >::store(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store(), and madness::archive::ArchiveImpl< Archive, T, Enabler >::wrap_store().
The documentation for this struct was generated from the following file:
archive.h