MADNESS: madness::xc_potential Struct Reference
madness::xc_potential Struct Reference
Class to compute terms of the potential.
#include <xcfunctional.h>
Public Member Functions
xc_potential (const XCfunctional &xc, int ispin)
std::size_t get_result_size () const
std::vector< madness::Tensor< double > > operator() (const madness::Key< 3 > &key, const std::vector< madness::Tensor< double > > &t) const
Public Attributes
const int ispin
const XCfunctional * xc
Detailed Description
Class to compute terms of the potential.
Constructor & Destructor Documentation
xc_potential()
madness::xc_potential::xc_potential (const XCfunctional & xc, int ispin) inline
Member Function Documentation
get_result_size()
std::size_t madness::xc_potential::get_result_size () const inline
References madness::XCfunctional::is_gga(), madness::XCfunctional::is_lda(), madness::XCfunctional::is_spin_polarized(), MADNESS_EXCEPTION, and xc.
operator()()
std::vector< madness::Tensor< double > > madness::xc_potential::operator() (const madness::Key< 3 > & key, const std::vector< madness::Tensor< double > > & t) const inline
References ispin, MADNESS_ASSERT, madness::XCfunctional::vxc(), and xc.
Member Data Documentation
ispin
const int madness::xc_potential::ispin
Referenced by operator()().
xc
const XCfunctional* madness::xc_potential::xc
Referenced by get_result_size(), and operator()().
The documentation for this struct was generated from the following file:
xcfunctional.h