MADNESS: madness::cartesian_grid< NDIM > Struct Template Reference
madness::cartesian_grid< NDIM > Struct Template Reference
#include <lowrankfunction.h>
Public Member Functions
cartesian_grid (const cartesian_grid< NDIM > &other)
cartesian_grid (const double volume_per_gridpoint, const double radius)
cartesian_grid (const long n_per_dim, const double lo, const double hi)
Vector< double, NDIM > get_coordinates () const
void initialize (const double lo, const double hi)
bool operator() () const
void operator++ ()
cartesian_grid & operator= (const cartesian_grid< NDIM > &other)
double volume_per_gridpoint () const
Public Attributes
Vector< double, NDIM > hivec
Vector< double, NDIM > increment
long index =0
Vector< double, NDIM > lovec
long n_per_dim
std::vector< long > stride
long total_n
Constructor & Destructor Documentation
cartesian_grid() [1/3]
template<std::size_t NDIM> madness::cartesian_grid< NDIM >::cartesian_grid (const double volume_per_gridpoint, const double radius) inline
References madness::cartesian_grid< NDIM >::increment, madness::cartesian_grid< NDIM >::initialize(), madness::cartesian_grid< NDIM >::n_per_dim, NDIM, pow(), madness::print(), and madness::cartesian_grid< NDIM >::volume_per_gridpoint().
cartesian_grid() [2/3]
template<std::size_t NDIM> madness::cartesian_grid< NDIM >::cartesian_grid (const long n_per_dim, const double lo, const double hi) inline
References madness::cartesian_grid< NDIM >::initialize(), and lo.
cartesian_grid() [3/3]
template<std::size_t NDIM> madness::cartesian_grid< NDIM >::cartesian_grid (const cartesian_grid< NDIM > & other) inline
Member Function Documentation
get_coordinates()
template<std::size_t NDIM> Vector<double,NDIM> madness::cartesian_grid< NDIM >::get_coordinates () const inline
References madness::cartesian_grid< NDIM >::increment, madness::cartesian_grid< NDIM >::index, madness::cartesian_grid< NDIM >::lovec, madness::cartesian_grid< NDIM >::n_per_dim, NDIM, and madness::cartesian_grid< NDIM >::stride.
initialize()
template<std::size_t NDIM> void madness::cartesian_grid< NDIM >::initialize (const double lo, const double hi) inline
References madness::Vector< T, N >::fill(), madness::cartesian_grid< NDIM >::hivec, madness::cartesian_grid< NDIM >::increment, lo, madness::cartesian_grid< NDIM >::lovec, madness::cartesian_grid< NDIM >::n_per_dim, NDIM, pow(), madness::cartesian_grid< NDIM >::stride, and madness::cartesian_grid< NDIM >::total_n.
Referenced by madness::cartesian_grid< NDIM >::cartesian_grid().
operator()()
template<std::size_t NDIM> bool madness::cartesian_grid< NDIM >::operator() () const inline
References madness::cartesian_grid< NDIM >::index, and madness::cartesian_grid< NDIM >::total_n.
operator++()
template<std::size_t NDIM> void madness::cartesian_grid< NDIM >::operator++ () inline
References madness::cartesian_grid< NDIM >::index.
operator=()
template<std::size_t NDIM> cartesian_grid& madness::cartesian_grid< NDIM >::operator= (const cartesian_grid< NDIM > & other) inline
References madness::swap().
volume_per_gridpoint()
template<std::size_t NDIM> double madness::cartesian_grid< NDIM >::volume_per_gridpoint () const inline
References madness::cartesian_grid< NDIM >::hivec, madness::cartesian_grid< NDIM >::lovec, NDIM, and madness::cartesian_grid< NDIM >::total_n.
Referenced by madness::cartesian_grid< NDIM >::cartesian_grid().
Member Data Documentation
hivec
template<std::size_t NDIM> Vector<double,NDIM> madness::cartesian_grid< NDIM >::hivec
Referenced by madness::cartesian_grid< NDIM >::initialize(), and madness::cartesian_grid< NDIM >::volume_per_gridpoint().
increment
template<std::size_t NDIM> Vector<double,NDIM> madness::cartesian_grid< NDIM >::increment
Referenced by madness::cartesian_grid< NDIM >::cartesian_grid(), madness::cartesian_grid< NDIM >::get_coordinates(), and madness::cartesian_grid< NDIM >::initialize().
index
template<std::size_t NDIM> long madness::cartesian_grid< NDIM >::index =0
Referenced by madness::cartesian_grid< NDIM >::get_coordinates(), madness::cartesian_grid< NDIM >::operator()(), and madness::cartesian_grid< NDIM >::operator++().
lovec
template<std::size_t NDIM> Vector<double,NDIM> madness::cartesian_grid< NDIM >::lovec
Referenced by madness::cartesian_grid< NDIM >::get_coordinates(), madness::cartesian_grid< NDIM >::initialize(), and madness::cartesian_grid< NDIM >::volume_per_gridpoint().
n_per_dim
template<std::size_t NDIM> long madness::cartesian_grid< NDIM >::n_per_dim
Referenced by madness::cartesian_grid< NDIM >::cartesian_grid(), madness::cartesian_grid< NDIM >::get_coordinates(), and madness::cartesian_grid< NDIM >::initialize().
stride
template<std::size_t NDIM> std::vector<long> madness::cartesian_grid< NDIM >::stride
Referenced by madness::cartesian_grid< NDIM >::get_coordinates(), and madness::cartesian_grid< NDIM >::initialize().
total_n
template<std::size_t NDIM> long madness::cartesian_grid< NDIM >::total_n
Referenced by madness::cartesian_grid< NDIM >::initialize(), madness::cartesian_grid< NDIM >::operator()(), and madness::cartesian_grid< NDIM >::volume_per_gridpoint().
The documentation for this struct was generated from the following file:
lowrankfunction.h