MADNESS: sgl_guess Struct Reference
sgl_guess Struct Reference
Public Member Functions
sgl_guess (const long n, const long l, const long m, const double Z)
double energy () const
complex_function_3d get_wf (World &world) const
double_complex operator() (const coord_3d &coord) const
Public Attributes
long l
long m
long n
double Z
Constructor & Destructor Documentation
sgl_guess()
sgl_guess::sgl_guess (const long n, const long l, const long m, const double Z) inline
Member Function Documentation
energy()
double sgl_guess::energy () const inline
References n, and Z.
get_wf()
complex_function_3d sgl_guess::get_wf (World & world) const inline
References norm(), madness::Function< T, NDIM >::norm2(), and madness::Function< T, NDIM >::scale().
operator()()
double_complex sgl_guess::operator() (const coord_3d & coord) const inline
References e(), generalized_laguerre(), l, m, n, madness::Vector< T, N >::normf(), R, and Z.
Member Data Documentation
l
long sgl_guess::l
Referenced by operator()().
m
long sgl_guess::m
Referenced by operator()().
n
long sgl_guess::n
Referenced by energy(), and operator()().
Z
double sgl_guess::Z
Referenced by energy(), and operator()().
The documentation for this struct was generated from the following file:
dirac-hatom.cc