MADNESS: data< T, NDIM > Struct Template Reference
data< T, NDIM > Struct Template Reference
Public Member Functions
data (World &world, const CCParameters &parameters)
void clear ()
auto get_ccpairfunctions ()
get some standard ccpairfunctions
auto get_functions ()
get some standard functions
void initialize ()
bool is_initialized () const
Public Attributes
Function< T, LDIM > f1
Function< T, NDIM > f12
std::shared_ptr< CCConvolutionOperator< T, LDIM > > f12_op
Function< T, LDIM > f2
Function< T, NDIM > f23
Function< T, LDIM > f3
Function< T, LDIM > f4
Function< T, LDIM > f5
CCParameters parameters
World & world
Static Public Attributes
static constexpr std::size_t LDIM =NDIM/2
Constructor & Destructor Documentation
data()
template<typename T , std::size_t NDIM> data< T, NDIM >::data (World & world, const CCParameters & parameters) inline
Member Function Documentation
clear()
template<typename T , std::size_t NDIM> void data< T, NDIM >::clear () inline
References madness::Function< T, NDIM >::clear(), data< T, NDIM >::f1, data< T, NDIM >::f12, data< T, NDIM >::f12_op, data< T, NDIM >::f2, data< T, NDIM >::f23, data< T, NDIM >::f3, data< T, NDIM >::f4, and data< T, NDIM >::f5.
get_ccpairfunctions()
template<typename T , std::size_t NDIM> auto data< T, NDIM >::get_ccpairfunctions () inline
get some standard ccpairfunctions
p1: pure, corresponds to f12 p2: dec, corresponds to f23 p3: op_dec, corresponds to f23 p4: pure, corresponds to f23 p5: op_pure, corresponds to f23
References madness::copy(), data< T, NDIM >::f1, data< T, NDIM >::f12, data< T, NDIM >::f12_op, data< T, NDIM >::f2, data< T, NDIM >::f23, data< T, NDIM >::f3, data< T, NDIM >::initialize(), and data< T, NDIM >::is_initialized().
Referenced by test_apply(), test_consolidate(), test_inner(), test_load_store(), test_multiply(), test_multiply_with_f12(), test_norm(), test_operator_apply(), and test_partial_inner_6d().
get_functions()
template<typename T , std::size_t NDIM> auto data< T, NDIM >::get_functions () inline
get some standard functions
f1: exp(-1.0 r^2) f2: exp(-2.0 r^2) f3: exp(-3.0 r^2) f4: exp(-4.0 r^2) f5: exp(-5.0 r^2) f12: exp(-r_1^2 - 2 r_2^2) f23: exp(-r_1^2 - 2 r_2^2) + exp(-2 r_1^2 - 3 r_2^2)
References data< T, NDIM >::f1, data< T, NDIM >::f12, data< T, NDIM >::f2, data< T, NDIM >::f3, data< T, NDIM >::f4, data< T, NDIM >::f5, data< T, NDIM >::initialize(), and data< T, NDIM >::is_initialized().
Referenced by test_apply(), test_constructor(), test_inner(), test_load_store(), test_multiply(), test_operator_apply(), test_partial_inner_3d(), test_partial_inner_6d(), test_projector(), test_scalar_multiplication(), test_swap_particles(), and test_transformations().
initialize()
template<typename T , std::size_t NDIM> void data< T, NDIM >::initialize () inline
References madness::FunctionFactory< T, NDIM >::f(), data< T, NDIM >::f1, data< T, NDIM >::f12, data< T, NDIM >::f12_op, data< T, NDIM >::f2, data< T, NDIM >::f23, data< T, NDIM >::f3, data< T, NDIM >::f4, data< T, NDIM >::f5, madness::g, g1(), madness::inner(), data< T, NDIM >::LDIM, NDIM, madness::OT_F12, data< T, NDIM >::parameters, madness::print(), madness::r2(), and data< T, NDIM >::world.
Referenced by data< T, NDIM >::get_ccpairfunctions(), and data< T, NDIM >::get_functions().
is_initialized()
template<typename T , std::size_t NDIM> bool data< T, NDIM >::is_initialized () const inline
References data< T, NDIM >::f1, and madness::Function< T, NDIM >::is_initialized().
Referenced by data< T, NDIM >::get_ccpairfunctions(), and data< T, NDIM >::get_functions().
Member Data Documentation
f1
template<typename T , std::size_t NDIM> Function<T,LDIM> data< T, NDIM >::f1
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), data< T, NDIM >::initialize(), and data< T, NDIM >::is_initialized().
f12
template<typename T , std::size_t NDIM> Function<T,NDIM> data< T, NDIM >::f12
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), and data< T, NDIM >::initialize().
f12_op
template<typename T , std::size_t NDIM> std::shared_ptr<CCConvolutionOperator<T,LDIM> > data< T, NDIM >::f12_op
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::initialize(), test_inner(), test_multiply_with_f12(), and test_operator_apply().
f2
template<typename T , std::size_t NDIM> Function<T,LDIM> data< T, NDIM >::f2
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), and data< T, NDIM >::initialize().
f23
template<typename T , std::size_t NDIM> Function<T,NDIM> data< T, NDIM >::f23
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_ccpairfunctions(), and data< T, NDIM >::initialize().
f3
template<typename T , std::size_t NDIM> Function<T,LDIM> data< T, NDIM >::f3
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), and data< T, NDIM >::initialize().
f4
template<typename T , std::size_t NDIM> Function<T,LDIM> data< T, NDIM >::f4
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_functions(), and data< T, NDIM >::initialize().
f5
template<typename T , std::size_t NDIM> Function<T,LDIM> data< T, NDIM >::f5
Referenced by data< T, NDIM >::clear(), data< T, NDIM >::get_functions(), and data< T, NDIM >::initialize().
LDIM
template<typename T , std::size_t NDIM> constexpr std::size_t data< T, NDIM >::LDIM =NDIM/2 static constexpr
Referenced by data< T, NDIM >::initialize().
parameters
template<typename T , std::size_t NDIM> CCParameters data< T, NDIM >::parameters
Referenced by data< T, NDIM >::initialize().
world
template<typename T , std::size_t NDIM> World& data< T, NDIM >::world
Referenced by data< T, NDIM >::initialize().
The documentation for this struct was generated from the following file:
test_ccpairfunction.cc