MADNESS: madness::apply_kernel_helper Struct Reference
madness::apply_kernel_helper Struct Reference
#include <smooth.h>
Classes
struct slater_kernel
Public Member Functions
apply_kernel_helper (const double &ipot_)
madness::Tensor< double > slater_apply (const std::vector< madness::Tensor< double > > &t, const madness::Key< 3 > &key, const FunctionCommonData< double, 3 > cdata) const
Public Attributes
asymptotic_slater asl
const double ipot
const double prefactor = 1.0 / M_PI
const double safety_thresh_ptrho = FunctionDefaults<3>::get_thresh() * 0.01
const double safety_thresh_rho = FunctionDefaults<3>::get_thresh() * 0.01
Constructor & Destructor Documentation
apply_kernel_helper()
madness::apply_kernel_helper::apply_kernel_helper (const double & ipot_) inline
Member Function Documentation
slater_apply()
madness::Tensor< double > madness::apply_kernel_helper::slater_apply (const std::vector< madness::Tensor< double > > & t, const madness::Key< 3 > & key, const FunctionCommonData< double, 3 > cdata) const inline
References madness::Tensor< T >::absmax(), asl, madness::copy(), madness::Tensor< T >::emul(), madness::FunctionDefaults< NDIM >::get_k(), k, madness::FunctionCommonData< T, NDIM >::quad_x, safety_thresh_ptrho, and madness::Tensor< T >::unaryop().
Referenced by madness::slater_kernel_apply::operator()().
Member Data Documentation
asl
asymptotic_slater madness::apply_kernel_helper::asl
Referenced by slater_apply().
ipot
const double madness::apply_kernel_helper::ipot
prefactor
const double madness::apply_kernel_helper::prefactor = 1.0 / M_PI
safety_thresh_ptrho
const double madness::apply_kernel_helper::safety_thresh_ptrho = FunctionDefaults<3>::get_thresh() * 0.01
Referenced by slater_apply().
safety_thresh_rho
const double madness::apply_kernel_helper::safety_thresh_rho = FunctionDefaults<3>::get_thresh() * 0.01
The documentation for this struct was generated from the following file:
smooth.h