MADNESS: madness::particle< PDIM > Struct Template Reference
madness::particle< PDIM > Struct Template Reference
#include <lowrankfunction.h>
Public Member Functions
particle ()=default
default constructor
particle (const int p)
particle (const int p1, const int p2)
particle (const int p1, const int p2, const int p3)
particle (const std::vector< int > p)
particle complement () const
return the other particle
std::array< int, PDIM > get_array () const
type conversion to std::array
template<std::size_t DUMMYDIM = PDIM>
std::enable_if_t< DUMMYDIM==1, std::tuple< int > > get_tuple () const
template<std::size_t DUMMYDIM = PDIM>
std::enable_if_t< DUMMYDIM==2, std::tuple< int, int > > get_tuple () const
template<std::size_t DUMMYDIM = PDIM>
std::enable_if_t< DUMMYDIM==3, std::tuple< int, int, int > > get_tuple () const
bool is_first () const
assuming two particles only
bool is_last () const
assuming two particles only
std::string str () const
Static Public Member Functions
static particle particle1 ()
convenience for particle 1 (the left/first particle)
static particle particle2 ()
convenience for particle 2 (the right/second particle)
Public Attributes
std::array< int, PDIM > dims
Constructor & Destructor Documentation
particle() [1/5]
template<std::size_t PDIM> madness::particle< PDIM >::particle () default
default constructor
particle() [2/5]
template<std::size_t PDIM> madness::particle< PDIM >::particle (const int p) inline
particle() [3/5]
template<std::size_t PDIM> madness::particle< PDIM >::particle (const int p1, const int p2) inline
particle() [4/5]
template<std::size_t PDIM> madness::particle< PDIM >::particle (const int p1, const int p2, const int p3) inline
particle() [5/5]
template<std::size_t PDIM> madness::particle< PDIM >::particle (const std::vector< int > p) inline
References madness::particle< PDIM >::dims, and p().
Member Function Documentation
complement()
template<std::size_t PDIM> particle madness::particle< PDIM >::complement () const inline
return the other particle
References madness::particle< PDIM >::is_first(), madness::particle< PDIM >::is_last(), MADNESS_CHECK, madness::particle< PDIM >::particle1(), and madness::particle< PDIM >::particle2().
Referenced by madness::inner(), and madness::inner().
get_array()
template<std::size_t PDIM> std::array< int, PDIM > madness::particle< PDIM >::get_array () const inline
type conversion to std::array
References madness::particle< PDIM >::dims.
Referenced by madness::inner(), and madness::LRFunctorPure< T, NDIM, LDIM >::inner().
get_tuple() [1/3]
template<std::size_t PDIM> template<std::size_t DUMMYDIM = PDIM> std::enable_if_t< DUMMYDIM==1, std::tuple< int > > madness::particle< PDIM >::get_tuple () const inline
References madness::particle< PDIM >::dims.
get_tuple() [2/3]
template<std::size_t PDIM> template<std::size_t DUMMYDIM = PDIM> std::enable_if_t< DUMMYDIM==2, std::tuple< int, int > > madness::particle< PDIM >::get_tuple () const inline
References madness::particle< PDIM >::dims.
get_tuple() [3/3]
template<std::size_t PDIM> template<std::size_t DUMMYDIM = PDIM> std::enable_if_t< DUMMYDIM==3, std::tuple< int, int, int > > madness::particle< PDIM >::get_tuple () const inline
References madness::particle< PDIM >::dims.
is_first()
template<std::size_t PDIM> bool madness::particle< PDIM >::is_first () const inline
assuming two particles only
References madness::particle< PDIM >::dims.
Referenced by madness::particle< PDIM >::complement(), madness::inner(), and madness::LRFunctorF12< T, NDIM, LDIM >::inner().
is_last()
template<std::size_t PDIM> bool madness::particle< PDIM >::is_last () const inline
assuming two particles only
References madness::particle< PDIM >::dims.
Referenced by madness::particle< PDIM >::complement(), and madness::inner().
particle1()
template<std::size_t PDIM> static particle madness::particle< PDIM >::particle1 () inline static
convenience for particle 1 (the left/first particle)
References madness::particle< PDIM >::dims, and p().
Referenced by madness::particle< PDIM >::complement(), and test_inner().
particle2()
template<std::size_t PDIM> static particle madness::particle< PDIM >::particle2 () inline static
convenience for particle 2 (the right/second particle)
References madness::particle< PDIM >::dims, and p().
Referenced by madness::particle< PDIM >::complement(), and test_inner().
str()
template<std::size_t PDIM> std::string madness::particle< PDIM >::str () const inline
Member Data Documentation
dims
template<std::size_t PDIM> std::array<int,PDIM> madness::particle< PDIM >::dims
Referenced by madness::particle< PDIM >::particle(), madness::particle< PDIM >::get_array(), madness::particle< PDIM >::get_tuple(), madness::particle< PDIM >::is_first(), madness::particle< PDIM >::is_last(), madness::particle< PDIM >::particle1(), and madness::particle< PDIM >::particle2().
The documentation for this struct was generated from the following file:
lowrankfunction.h