MADNESS: madness::FunctionImpl< T, NDIM >::do_mapdim Struct Reference
madness::FunctionImpl< T, NDIM >::do_mapdim Struct Reference
map this on f
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::iterator > rangeT
Public Member Functions
do_mapdim ()
do_mapdim (const std::vector< long > map, implT &f)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * f
std::vector< long > map
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_mapdim
map this on f
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_mapdim::rangeT
Constructor & Destructor Documentation
do_mapdim() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_mapdim::do_mapdim () inline
do_mapdim() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_mapdim::do_mapdim (const std::vector< long > map, implT & f) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_mapdim::operator() (typename rangeT::iterator & it) const inline
References c, cc, madness::FunctionNode< T, NDIM >::coeff(), madness::copy(), madness::FunctionImpl< T, NDIM >::do_mapdim::f, madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionNode< T, NDIM >::has_children(), madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::do_mapdim::map, NDIM, madness::GenTensor< T >::reconstruct_tensor(), madness::WorldContainer< keyT, valueT, hashfunT >::replace(), and madness::Key< NDIM >::translation().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_mapdim::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
Member Data Documentation
f
template<typename T , std::size_t NDIM> implT* madness::FunctionImpl< T, NDIM >::do_mapdim::f
Referenced by madness::FunctionImpl< T, NDIM >::do_mapdim::operator()().
map
template<typename T , std::size_t NDIM> std::vector<long> madness::FunctionImpl< T, NDIM >::do_mapdim::map
Referenced by madness::FunctionImpl< T, NDIM >::do_mapdim::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h