MADNESS: madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT > Struct Template Reference
madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT > Struct Template Reference
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::iterator > rangeT
Public Member Functions
do_unary_op_value_inplace (implT *impl, const opT &op)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * impl
opT op
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> template<typename opT > typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::rangeT
Constructor & Destructor Documentation
do_unary_op_value_inplace()
template<typename T , std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::do_unary_op_value_inplace (implT * impl, const opT & op) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> template<typename opT > bool madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator() (typename rangeT::iterator & it) const inline
References madness::FunctionImpl< T, NDIM >::cdata, madness::change_tensor_type(), madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), madness::GenTensor< T >::full_tensor(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionNode< T, NDIM >::has_coeff(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::impl, madness::Key< NDIM >::level(), NDIM, madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::op, pow(), madness::scale(), madness::transform(), and madness::TT_FULL.
serialize()
template<typename T , std::size_t NDIM> template<typename opT > template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::serialize (const Archive & ar) inline
Member Data Documentation
impl
template<typename T , std::size_t NDIM> template<typename opT > implT* madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::impl
Referenced by madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()().
op
template<typename T , std::size_t NDIM> template<typename opT > opT madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::op
Referenced by madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h