MADNESS: madness::LRFunctorF12< T, NDIM, LDIM > Struct Template Reference
madness::LRFunctorF12< T, NDIM, LDIM > Struct Template Reference
#include <lowrankfunction.h>
Public Member Functions
LRFunctorF12 (const std::shared_ptr< SeparatedConvolution< T, LDIM > > f12, const Function< T, LDIM > &a, const Function< T, LDIM > &b)
delegate to the other ctor with vector arguments
LRFunctorF12 (const std::shared_ptr< SeparatedConvolution< T, LDIM > > f12, const std::vector< Function< T, LDIM > > &a, const std::vector< Function< T, LDIM > > &b)
std::vector< Function< T, LDIM > > inner (const std::vector< Function< T, LDIM > > &rhs, const particle< LDIM > p1, const particle< LDIM > p2) const
Tensor< T >::scalar_type norm2 () const
T operator() (const Vector< double, NDIM > &r) const
World & world () const
Public Member Functions inherited from madness::LRFunctorBase< T, NDIM, LDIM >
virtual ~LRFunctorBase ()
virtual Function< T, LDIM > inner (const Function< T, LDIM > &rhs, const particle< LDIM > p1, const particle< LDIM > p2) const
virtual T operator() (const Vector< T, NDIM > &r) const =0
Private Attributes
std::vector< Function< T, LDIM > > a
std::vector< Function< T, LDIM > > b
the lo-dim functions
std::shared_ptr< SeparatedConvolution< T, LDIM > > f12
a two-particle function
Constructor & Destructor Documentation
LRFunctorF12() [1/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LRFunctorF12< T, NDIM, LDIM >::LRFunctorF12 (const std::shared_ptr< SeparatedConvolution< T, LDIM > > f12, const std::vector< Function< T, LDIM > > & a, const std::vector< Function< T, LDIM > > & b) inline
References madness::LRFunctorF12< T, NDIM, LDIM >::a, madness::LRFunctorF12< T, NDIM, LDIM >::b, and MADNESS_CHECK_THROW.
LRFunctorF12() [2/2]
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> madness::LRFunctorF12< T, NDIM, LDIM >::LRFunctorF12 (const std::shared_ptr< SeparatedConvolution< T, LDIM > > f12, const Function< T, LDIM > & a, const Function< T, LDIM > & b) inline
delegate to the other ctor with vector arguments
References madness::LRFunctorF12< T, NDIM, LDIM >::a.
Member Function Documentation
inner()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector< Function< T, LDIM > > madness::LRFunctorF12< T, NDIM, LDIM >::inner (const std::vector< Function< T, LDIM > > & rhs, const particle< LDIM > p1, const particle< LDIM > p2) const inline virtual
Implements madness::LRFunctorBase< T, NDIM, LDIM >.
References madness::LRFunctorF12< T, NDIM, LDIM >::a, madness::apply(), madness::LRFunctorF12< T, NDIM, LDIM >::b, madness::copy(), madness::LRFunctorF12< T, NDIM, LDIM >::f12, madness::particle< PDIM >::is_first(), madness::World::size(), and madness::LRFunctorF12< T, NDIM, LDIM >::world().
norm2()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> Tensor< T >::scalar_type madness::LRFunctorF12< T, NDIM, LDIM >::norm2 () const inline virtual
Reimplemented from madness::LRFunctorBase< T, NDIM, LDIM >.
References madness::LRFunctorF12< T, NDIM, LDIM >::a, aa, madness::append(), madness::LRFunctorF12< T, NDIM, LDIM >::b, madness::SeparatedConvolution< Q, NDIM >::combine, madness::FunctionFactory< T, NDIM >::f(), madness::LRFunctorF12< T, NDIM, LDIM >::f12, madness::inner(), one(), and madness::LRFunctorF12< T, NDIM, LDIM >::world().
operator()()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> T madness::LRFunctorF12< T, NDIM, LDIM >::operator() (const Vector< double, NDIM > & r) const inline
References madness::LRFunctorF12< T, NDIM, LDIM >::a, madness::LRFunctorF12< T, NDIM, LDIM >::b, madness::LRFunctorF12< T, NDIM, LDIM >::f12, madness::inner(), MADNESS_EXCEPTION, madness::OT_GAUSS, madness::OT_SLATER, and split().
world()
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> World & madness::LRFunctorF12< T, NDIM, LDIM >::world () const inline virtual
Implements madness::LRFunctorBase< T, NDIM, LDIM >.
References madness::LRFunctorF12< T, NDIM, LDIM >::f12.
Referenced by madness::LRFunctorF12< T, NDIM, LDIM >::inner(), and madness::LRFunctorF12< T, NDIM, LDIM >::norm2().
Member Data Documentation
a
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector<Function<T,LDIM> > madness::LRFunctorF12< T, NDIM, LDIM >::a private
Referenced by madness::LRFunctorF12< T, NDIM, LDIM >::LRFunctorF12(), madness::LRFunctorF12< T, NDIM, LDIM >::LRFunctorF12(), madness::LRFunctorF12< T, NDIM, LDIM >::inner(), madness::LRFunctorF12< T, NDIM, LDIM >::norm2(), and madness::LRFunctorF12< T, NDIM, LDIM >::operator()().
b
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::vector<Function<T,LDIM> > madness::LRFunctorF12< T, NDIM, LDIM >::b private
the lo-dim functions
Referenced by madness::LRFunctorF12< T, NDIM, LDIM >::LRFunctorF12(), madness::LRFunctorF12< T, NDIM, LDIM >::inner(), madness::LRFunctorF12< T, NDIM, LDIM >::norm2(), and madness::LRFunctorF12< T, NDIM, LDIM >::operator()().
f12
template<typename T , std::size_t NDIM, std::size_t LDIM = NDIM/2> std::shared_ptr<SeparatedConvolution<T,LDIM> > madness::LRFunctorF12< T, NDIM, LDIM >::f12 private
a two-particle function
Referenced by madness::LRFunctorF12< T, NDIM, LDIM >::inner(), madness::LRFunctorF12< T, NDIM, LDIM >::norm2(), madness::LRFunctorF12< T, NDIM, LDIM >::operator()(), and madness::LRFunctorF12< T, NDIM, LDIM >::world().
The documentation for this struct was generated from the following file:
lowrankfunction.h