MADNESS: madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi Struct Reference
madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi Struct Reference
#include <funcimpl.h>
Public Member Functions
do_inner_ext_local_ffi (const std::shared_ptr< FunctionFunctorInterface< T, NDIM > > f, const implT *impl, const bool leaf_refine, const bool do_leaves)
T operator() (T a, T b) const
T operator() (typename dcT::const_iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
const bool do_leaves
start with leaf nodes instead of initial_level
const std::shared_ptr< FunctionFunctorInterface< T, NDIM > > fref
const implT * impl
const bool leaf_refine
Constructor & Destructor Documentation
do_inner_ext_local_ffi()
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::do_inner_ext_local_ffi (const std::shared_ptr< FunctionFunctorInterface< T, NDIM > > f, const implT * impl, const bool leaf_refine, const bool do_leaves) inline
Member Function Documentation
operator()() [1/2]
template<typename T , std::size_t NDIM> T madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::operator() (T a, T b) const inline
References a, and b.
operator()() [2/2]
template<typename T , std::size_t NDIM> T madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::operator() (typename dcT::const_iterator & it) const inline
References cc, madness::FunctionImpl< T, NDIM >::initial_level, madness::FunctionImpl< T, NDIM >::inner_adaptive_recursive(), madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), and T().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::serialize (const Archive & ar) inline
Member Data Documentation
do_leaves
template<typename T , std::size_t NDIM> const bool madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::do_leaves
start with leaf nodes instead of initial_level
fref
template<typename T , std::size_t NDIM> const std::shared_ptr< FunctionFunctorInterface<T, NDIM> > madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::fref
impl
template<typename T , std::size_t NDIM> const implT* madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::impl
leaf_refine
template<typename T , std::size_t NDIM> const bool madness::FunctionImpl< T, NDIM >::do_inner_ext_local_ffi::leaf_refine
The documentation for this struct was generated from the following file:
funcimpl.h