MADNESS: LProjector Struct Reference
LProjector Struct Reference
Public Member Functions
LProjector (World &world)
void analyze (const Spinor &f, const std::string text="") const
void operator() (const complex_function_3d &f, const std::string text="") const
Public Attributes
long lmax =3
World & world
std::map< std::pair< long, long >, complex_function_3d > Ylm
Constructor & Destructor Documentation
LProjector()
LProjector::LProjector (World & world) inline
References lmax, m, world, and Ylm.
Member Function Documentation
analyze()
void LProjector::analyze (const Spinor & f, const std::string text = "") const inline
References c, madness::f, madness::print(), and world.
Referenced by eigenvector_test().
operator()()
void LProjector::operator() (const complex_function_3d & f, const std::string text = "") const inline
References std::abs(), madness::f, madness::inner(), lmax, m, madness::print(), and Ylm.
Member Data Documentation
lmax
long LProjector::lmax =3
Referenced by LProjector(), and operator()().
world
World& LProjector::world
Referenced by LProjector(), and analyze().
Ylm
std::map<std::pair<long,long>,complex_function_3d> LProjector::Ylm
Referenced by LProjector(), and operator()().
The documentation for this struct was generated from the following file:
dirac-hatom.cc