MADNESS: madness::GaussianConvolution1DCache< Q > Struct Template Reference
madness::GaussianConvolution1DCache< Q > Struct Template Reference
#include <convolution1d.h>
Public Types
typedef ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< Q > > >::datumT datumT
typedef ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< Q > > >::iterator iterator
Public Member Functions
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double > > > map
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double_complex > > > map
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double > > > map
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double_complex > > > map
Static Public Member Functions
static std::shared_ptr< GaussianConvolution1D< Q > > get (int k, double expnt, int m, bool periodic)
Static Public Attributes
static ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< Q > > > map
Member Typedef Documentation
datumT
template<typename Q > typedef ConcurrentHashMap<hashT, std::shared_ptr< GaussianConvolution1D<Q> > >::datumT madness::GaussianConvolution1DCache< Q >::datumT
iterator
template<typename Q > typedef ConcurrentHashMap<hashT, std::shared_ptr< GaussianConvolution1D<Q> > >::iterator madness::GaussianConvolution1DCache< Q >::iterator
Member Function Documentation
get()
template<typename Q > static std::shared_ptr< GaussianConvolution1D<Q> > madness::GaussianConvolution1DCache< Q >::get (int k, double expnt, int m, bool periodic) inline static
References madness::hash_combine(), madness::hash_value(), k, m, MADNESS_ASSERT, MADNESS_PRAGMA_CLANG, madness::GaussianConvolution1DCache< Q >::map, madness::constants::pi, madness::pop(), and Q().
map() [1/4]
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double > > > madness::GaussianConvolution1DCache< double >::map
map() [2/4]
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double_complex > > > madness::GaussianConvolution1DCache< double_complex >::map
map() [3/4]
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double > > > madness::GaussianConvolution1DCache< double >::map
map() [4/4]
ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double_complex > > > madness::GaussianConvolution1DCache< double_complex >::map
Member Data Documentation
map
template<typename Q > ConcurrentHashMap<hashT, std::shared_ptr< GaussianConvolution1D<Q> > > madness::GaussianConvolution1DCache< Q >::map static
Referenced by madness::GaussianConvolution1DCache< Q >::get().
The documentation for this struct was generated from the following file:
convolution1d.h