MADNESS: madness::KernelRange::Restrictor Struct Reference
madness::KernelRange::Restrictor Struct Reference
restrictor function
#include <kernelrange.h>
Public Member Functions
Restrictor (Type type=Hard, double sigma=1.0)
hashT hash () const
double sigma () const
double sigma_inverse () const
Type type () const
double value (double x) const
Private Attributes
std::optional< std::pair< double, double > > sigma_w_inverse_
Type type_ = Hard
Friends
bool operator== (const Restrictor &r1, const Restrictor &r2)
Detailed Description
restrictor function
Constructor & Destructor Documentation
Restrictor()
madness::KernelRange::Restrictor::Restrictor (Type type = Hard, double sigma = 1.0) inline
References MADNESS_ASSERT, sigma(), and sigma_w_inverse_.
Member Function Documentation
hash()
hashT madness::KernelRange::Restrictor::hash () const inline
References madness::hash_combine(), madness::hash_value(), sigma(), and type_.
sigma()
double madness::KernelRange::Restrictor::sigma () const inline
References MADNESS_ASSERT, and sigma_w_inverse_.
Referenced by Restrictor(), madness::KernelRange::Data::compute_iextent_x2(), hash(), and madness::KernelRange::sigma().
sigma_inverse()
double madness::KernelRange::Restrictor::sigma_inverse () const inline
References MADNESS_ASSERT, and sigma_w_inverse_.
Referenced by value().
type()
Type madness::KernelRange::Restrictor::type () const inline
References type_.
Referenced by madness::KernelRange::Data::compute_iextent_x2(), and madness::KernelRange::type().
value()
double madness::KernelRange::Restrictor::value (double x) const inline
Returns
value of restrictor function r(x) at x
References madness::f, madness::KernelRange::Hard, MADNESS_EXCEPTION, sigma_inverse(), madness::KernelRange::SoftErf, and type_.
Referenced by madness::KernelRange::Data::compute_iextent_x2(), and madness::KernelRange::value().
Friends And Related Symbol Documentation
operator==
bool operator== (const Restrictor & r1, const Restrictor & r2) friend
Returns
true if r1 and r2 are equal
Member Data Documentation
sigma_w_inverse_
std::optional<std::pair<double,double> > madness::KernelRange::Restrictor::sigma_w_inverse_ private
Referenced by Restrictor(), sigma(), and sigma_inverse().
type_
Type madness::KernelRange::Restrictor::type_ = Hard private
Referenced by hash(), type(), and value().
The documentation for this struct was generated from the following file:
kernelrange.h