MADNESS: madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T > Struct Template Reference
madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Specialization of ArchiveImpl for parallel input archives.
#include <parallel_archive.h>
Static Public Member Functions
template<typename Q >
static std::enable_if< std::is_base_of< ParallelSerializableObject, Q >::value, constParallelInputArchive< localarchiveT > & >::type wrap_load (const ParallelInputArchive< localarchiveT > &ar, const Q &t)
Load the data from the archive.
template<typename Q >
static std::enable_if<!std::is_base_of< ParallelSerializableObject, Q >::value, constParallelInputArchive< localarchiveT > & >::type wrap_load (const ParallelInputArchive< localarchiveT > &ar, const Q &t)
Load the data from the archive.
Detailed Description
template<class T, class localarchiveT>
struct madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T >
Specialization of ArchiveImpl for parallel input archives.
Attention
No type-checking is performed.
Template Parameters
T The data type.
Member Function Documentation
wrap_load() [1/2]
template<class T , class localarchiveT > template<typename Q > static std::enable_if< std::is_base_of< ParallelSerializableObject, Q >::value, constParallelInputArchive< localarchiveT > & >::type madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T >::wrap_load (const ParallelInputArchive< localarchiveT > & ar, const Q & t) inline static
Load the data from the archive.
Parallel objects are forwarded to their implementation of parallel load.
The function only appears (due to enable_if) if Q is a parallel serializable object.
Todo:
Is Q necessary? I'm sure it is, but can't figure out why at a first glance.
Template Parameters
Q Description needed.
Parameters
[in] ar The parallel archive.
[out] t Where to put the loaded parallel object.
Returns
The parallel archive.
References madness::load(), and T().
wrap_load() [2/2]
template<class T , class localarchiveT > template<typename Q > static std::enable_if<!std::is_base_of< ParallelSerializableObject, Q >::value, constParallelInputArchive< localarchiveT > & >::type madness::archive::ArchiveImpl< ParallelInputArchive< localarchiveT >, T >::wrap_load (const ParallelInputArchive< localarchiveT > & ar, const Q & t) inline static
Load the data from the archive.
Serial objects are read only from process 0 and then broadcasted.
The function only appears (due to enable_if) if Q is not a parallel serializable object.
Todo:
Same question about Q.
Template Parameters
Q Description needed.
Parameters
[in] ar The parallel archive.
[out] t Where to put the loaded data.
Returns
The parallel archive.
References madness::archive::BaseParallelArchive< Archive >::broadcast(), madness::archive::BaseParallelArchive< Archive >::get_world(), madness::archive::BaseParallelArchive< Archive >::local_archive(), madness::World::rank(), and T().
The documentation for this struct was generated from the following file:
parallel_archive.h