MADNESS: madness::CCIntermediatePotentials Struct Reference
madness::CCIntermediatePotentials Struct Reference
little helper structure which manages the stored singles potentials
#include <CCStructures.h>
Public Member Functions
CCIntermediatePotentials ()=default
CCIntermediatePotentials (const CCIntermediatePotentials &other)=default
CCIntermediatePotentials (const CCParameters &p)
void clear_all ()
deltes all stored potentials
void clear_response ()
clears only potentials of the response
void cloud_load (World &world, const Cloud &cloud, Recordlist< Cloud::keyT > &recordlist)
Recordlist< Cloud::keyT > cloud_store (World &world, Cloud &cloud) const
vector_real_function_3d get_potential (const PotentialType &ptype, const FuncType &ftype, const bool throw_if_empty) const
return a vector of the intermediate potentials
void insert (const vector_real_function_3d &potential, const CC_vecfunction &f, const PotentialType &type)
insert potential
vector_real_function_3d operator() (const CC_vecfunction &f, const PotentialType &type, const bool throw_if_empty) const
fetches the correct stored potential or throws an exception
Function< double, 3 > operator() (const CCFunction< double, 3 > &f, const PotentialType &type, const bool throw_if_empty) const
fetch the potential for a single function
CCIntermediatePotentials & operator= (const CCIntermediatePotentials &other)=default
bool potential_exists (const CC_vecfunction &f, const PotentialType &type) const
check if the intermediate potential exists
bool potential_exists (const PotentialType &type, const FuncType &ftype) const
check if the intermediate potential exists
void reconstruct () const
Public Attributes
CCParameters parameters
Private Member Functions
void output (const std::string &msg) const
structured output
Private Attributes
vector_real_function_3d current_s2b_potential_ex_
s2b_potential for the pure 6D-part of the excited-state (expensive and constant during singles iterations)
vector_real_function_3d current_s2b_potential_gs_
s2b_potential for the pure 6D-part of the ground-state (expensive and constant during singles iterations)
vector_real_function_3d current_s2c_potential_ex_
s2c_potential for the pure 6D-part of the excited_state (expensive and constant during singles iterations)
vector_real_function_3d current_s2c_potential_gs_
s2c_potential for the pure 6D-part of the ground-state (expensive and constant during singles iterations)
vector_real_function_3d current_singles_potential_ex_
whole excited state singles potential without fock-residue
vector_real_function_3d current_singles_potential_gs_
whole ground state singles potential without fock-residue
vector_real_function_3d unprojected_cc2_projector_response_
Friends
hashT hash_value (const CCIntermediatePotentials &ip)
Detailed Description
little helper structure which manages the stored singles potentials
Constructor & Destructor Documentation
CCIntermediatePotentials() [1/3]
madness::CCIntermediatePotentials::CCIntermediatePotentials () default
CCIntermediatePotentials() [2/3]
madness::CCIntermediatePotentials::CCIntermediatePotentials (const CCParameters & p) inline
CCIntermediatePotentials() [3/3]
madness::CCIntermediatePotentials::CCIntermediatePotentials (const CCIntermediatePotentials & other) default
Member Function Documentation
clear_all()
void madness::CCIntermediatePotentials::clear_all () inline
deltes all stored potentials
References current_s2b_potential_ex_, current_s2b_potential_gs_, current_s2c_potential_ex_, current_s2c_potential_gs_, current_singles_potential_ex_, and current_singles_potential_gs_.
Referenced by madness::CC2::iterate_cc2_singles().
clear_response()
void madness::CCIntermediatePotentials::clear_response () inline
clears only potentials of the response
References current_s2b_potential_ex_, current_s2c_potential_ex_, and current_singles_potential_ex_.
Referenced by madness::CC2::iterate_adc2_singles(), madness::CC2::iterate_ccs_singles(), and madness::CC2::iterate_lrcc2_singles().
cloud_load()
void madness::CCIntermediatePotentials::cloud_load (World & world, const Cloud & cloud, Recordlist< Cloud::keyT > & recordlist) inline
References current_s2b_potential_ex_, current_s2b_potential_gs_, current_s2c_potential_ex_, current_s2c_potential_gs_, current_singles_potential_ex_, current_singles_potential_gs_, madness::Cloud::forward_load(), parameters, and unprojected_cc2_projector_response_.
cloud_store()
Recordlist< Cloud::keyT > madness::CCIntermediatePotentials::cloud_store (World & world, Cloud & cloud) const inline
References current_s2b_potential_ex_, current_s2b_potential_gs_, current_s2c_potential_ex_, current_s2c_potential_gs_, current_singles_potential_ex_, current_singles_potential_gs_, parameters, madness::Cloud::store(), and unprojected_cc2_projector_response_.
get_potential()
madness::vector_real_function_3d madness::CCIntermediatePotentials::get_potential (const PotentialType & ptype, const FuncType & ftype, const bool throw_if_empty) const
return a vector of the intermediate potentials
Parameters
[in] ptype the potential type (POT_SINGLES, POT_S2B, ..)
[in] ftype the function type (HOLE, PARTICLE, RESPONSE)
References madness::assign_name(), current_s2b_potential_ex_, current_s2b_potential_gs_, current_s2c_potential_ex_, current_s2c_potential_gs_, current_singles_potential_ex_, current_singles_potential_gs_, madness::CCParameters::debug(), errmsg(), MADNESS_EXCEPTION, madness::MIXED, madness::name(), parameters, madness::PARTICLE, madness::POT_s2b_, madness::POT_s2c_, madness::POT_singles_, madness::print(), madness::print_size(), and madness::RESPONSE.
Referenced by operator()(), operator()(), and potential_exists().
insert()
void madness::CCIntermediatePotentials::insert (const vector_real_function_3d & potential, const CC_vecfunction & f, const PotentialType & type)
insert potential
References madness::assign_name(), current_s2b_potential_ex_, current_s2b_potential_gs_, current_s2c_potential_ex_, current_s2c_potential_gs_, current_singles_potential_ex_, current_singles_potential_gs_, madness::CCParameters::debug(), madness::f, MADNESS_ASSERT, madness::MIXED, output(), parameters, madness::PARTICLE, madness::POT_s2b_, madness::POT_s2c_, madness::POT_singles_, potential(), madness::print_size(), madness::World::rank(), madness::RESPONSE, and madness::type().
operator()() [1/2]
madness::vector_real_function_3d madness::CCIntermediatePotentials::operator() (const CC_vecfunction & f, const PotentialType & type, const bool throw_if_empty) const
fetches the correct stored potential or throws an exception
References madness::f, get_potential(), and madness::type().
operator()() [2/2]
madness::real_function_3d madness::CCIntermediatePotentials::operator() (const CCFunction< double, 3 > & f, const PotentialType & type, const bool throw_if_empty) const
fetch the potential for a single function
References madness::f, madness::CCParameters::freeze(), get_potential(), MADNESS_CHECK_THROW, parameters, and madness::type().
operator=()
CCIntermediatePotentials & madness::CCIntermediatePotentials::operator= (const CCIntermediatePotentials & other) default
output()
void madness::CCIntermediatePotentials::output (const std::string & msg) const inline private
structured output
References madness::CCParameters::debug(), and parameters.
Referenced by insert().
potential_exists() [1/2]
bool madness::CCIntermediatePotentials::potential_exists (const CC_vecfunction & f, const PotentialType & type) const inline
check if the intermediate potential exists
References madness::f, potential_exists(), and madness::type().
Referenced by potential_exists(), and madness::CC2::solve().
potential_exists() [2/2]
bool madness::CCIntermediatePotentials::potential_exists (const PotentialType & type, const FuncType & ftype) const inline
check if the intermediate potential exists
References get_potential(), and madness::type().
reconstruct()
void madness::CCIntermediatePotentials::reconstruct () const inline
References current_s2b_potential_ex_, current_s2b_potential_gs_, current_s2c_potential_ex_, current_s2c_potential_gs_, current_singles_potential_ex_, current_singles_potential_gs_, madness::reconstruct(), and unprojected_cc2_projector_response_.
Referenced by madness::Info::reconstruct().
Friends And Related Symbol Documentation
hash_value
hashT hash_value (const CCIntermediatePotentials & ip) friend
Member Data Documentation
current_s2b_potential_ex_
vector_real_function_3d madness::CCIntermediatePotentials::current_s2b_potential_ex_ private
s2b_potential for the pure 6D-part of the excited-state (expensive and constant during singles iterations)
Referenced by clear_all(), clear_response(), cloud_load(), cloud_store(), get_potential(), insert(), and reconstruct().
current_s2b_potential_gs_
vector_real_function_3d madness::CCIntermediatePotentials::current_s2b_potential_gs_ private
s2b_potential for the pure 6D-part of the ground-state (expensive and constant during singles iterations)
Referenced by clear_all(), cloud_load(), cloud_store(), get_potential(), insert(), and reconstruct().
current_s2c_potential_ex_
vector_real_function_3d madness::CCIntermediatePotentials::current_s2c_potential_ex_ private
s2c_potential for the pure 6D-part of the excited_state (expensive and constant during singles iterations)
Referenced by clear_all(), clear_response(), cloud_load(), cloud_store(), get_potential(), insert(), and reconstruct().
current_s2c_potential_gs_
vector_real_function_3d madness::CCIntermediatePotentials::current_s2c_potential_gs_ private
s2c_potential for the pure 6D-part of the ground-state (expensive and constant during singles iterations)
Referenced by clear_all(), cloud_load(), cloud_store(), get_potential(), insert(), and reconstruct().
current_singles_potential_ex_
vector_real_function_3d madness::CCIntermediatePotentials::current_singles_potential_ex_ private
whole excited state singles potential without fock-residue
Referenced by clear_all(), clear_response(), cloud_load(), cloud_store(), get_potential(), insert(), and reconstruct().
current_singles_potential_gs_
vector_real_function_3d madness::CCIntermediatePotentials::current_singles_potential_gs_ private
whole ground state singles potential without fock-residue
Referenced by clear_all(), cloud_load(), cloud_store(), get_potential(), insert(), and reconstruct().
parameters
CCParameters madness::CCIntermediatePotentials::parameters
Referenced by cloud_load(), cloud_store(), get_potential(), insert(), operator()(), and output().
unprojected_cc2_projector_response_
vector_real_function_3d madness::CCIntermediatePotentials::unprojected_cc2_projector_response_ private
unprojected S3c + S5c + S2b + S2c potential of CC2 singles for the projector response of the CC2 singles potential
Referenced by cloud_load(), cloud_store(), and reconstruct().
The documentation for this struct was generated from the following files:
CCStructures.h
CCStructures.cc