MADNESS: madness::OptimizationTargetInterface Struct Reference
madness::OptimizationTargetInterface Struct Reference abstract
The interface to be provided by functions to be optimized.
#include <solvers.h>
Public Member Functions
virtual ~OptimizationTargetInterface ()
virtual Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
virtual bool provides_gradient () const
Override this to return true if the derivative is implemented.
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual double value (const Tensor< double > &x)=0
Should return the value of the objective function.
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
Detailed Description
The interface to be provided by functions to be optimized.
Constructor & Destructor Documentation
~OptimizationTargetInterface()
virtual madness::OptimizationTargetInterface::~OptimizationTargetInterface () inline virtual
Member Function Documentation
gradient()
virtual Tensor<double> madness::OptimizationTargetInterface::gradient (const Tensor< double > & x) inline virtual
Should return the derivative of the function.
Reimplemented in CoreFittingTarget, madness::Znemo, Test2, Test, Test2, Test, madness::MolecularEnergy, madness::Nemo, and Fred.
Referenced by test_gradient(), and value_and_gradient().
provides_gradient()
virtual bool madness::OptimizationTargetInterface::provides_gradient () const inline virtual
Override this to return true if the derivative is implemented.
Reimplemented in Test2, Test, Test2, Test, Fred, madness::MolecularEnergy, madness::Nemo, and CoreFittingTarget.
test_gradient()
double OptimizationTargetInterface::test_gradient (Tensor< double > & x, double value_precision, bool doprint = true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
References std::abs(), madness::BaseTensor::dim(), gradient(), max, pow(), and value().
value()
virtual double madness::OptimizationTargetInterface::value (const Tensor< double > & x) pure virtual
Should return the value of the objective function.
Implemented in CoreFittingTarget, madness::Znemo, Test2, Test, Test2, Test, madness::MolecularEnergy, madness::OEP, madness::Nemo, madness::MP2, madness::CC2, and Fred.
Referenced by test_gradient(), and value_and_gradient().
value_and_gradient()
virtual void madness::OptimizationTargetInterface::value_and_gradient (const Tensor< double > & x, double & value, Tensor< double > & gradient) inline virtual
Reimplement if more efficient to evaluate both value and gradient in one call.
Reimplemented in Fred.
References gradient(), and value().
The documentation for this struct was generated from the following files:
solvers.h
solvers.cc