MADNESS: madness::UnaryOpStructure< NDIM > Struct Template Reference
madness::UnaryOpStructure< NDIM > Struct Template Reference
computes the corrected exchange correlation potential using the multipole approximation
#include <AC.h>
Public Member Functions
UnaryOpStructure (const std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f_, const std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f2_)
void operator() (const Key< NDIM > &key, Tensor< double > &t) const
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
FunctionCommonData< double, NDIM > cdata
std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f
shared pointer to object of int_factor_functor
std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f2
shared pointer to object of lr_pot_functor
Detailed Description
template<unsigned long int NDIM>
struct madness::UnaryOpStructure< NDIM >
computes the corrected exchange correlation potential using the multipole approximation
Constructor & Destructor Documentation
UnaryOpStructure()
template<unsigned long int NDIM> madness::UnaryOpStructure< NDIM >::UnaryOpStructure (const std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f_, const std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f2_) inline
Member Function Documentation
operator()()
template<unsigned long int NDIM> void madness::UnaryOpStructure< NDIM >::operator() (const Key< NDIM > & key, Tensor< double > & t) const inline
computes the corrected potential (weighting with correction factor and adding of 1/r potential)
Parameters
[in] t uncorrected exchange correlation potential
[out] t corrected exchange correlation potential
References madness::UnaryOpStructure< NDIM >::cdata, madness::BaseTensor::dims(), madness::Tensor< T >::emul(), madness::UnaryOpStructure< NDIM >::f, madness::UnaryOpStructure< NDIM >::f2, madness::fcube(), madness::BaseTensor::ndim(), and madness::FunctionCommonData< T, NDIM >::quad_x.
serialize()
template<unsigned long int NDIM> template<typename Archive > void madness::UnaryOpStructure< NDIM >::serialize (Archive & ar) inline
Member Data Documentation
cdata
template<unsigned long int NDIM> FunctionCommonData<double,NDIM> madness::UnaryOpStructure< NDIM >::cdata
Referenced by madness::UnaryOpStructure< NDIM >::operator()().
f
template<unsigned long int NDIM> std::shared_ptr<FunctionFunctorInterface<double,NDIM> > madness::UnaryOpStructure< NDIM >::f
shared pointer to object of int_factor_functor
Referenced by madness::UnaryOpStructure< NDIM >::operator()().
f2
template<unsigned long int NDIM> std::shared_ptr<FunctionFunctorInterface<double,NDIM> > madness::UnaryOpStructure< NDIM >::f2
shared pointer to object of lr_pot_functor
Referenced by madness::UnaryOpStructure< NDIM >::operator()().
The documentation for this struct was generated from the following file:
AC.h