MADNESS: madness::CoreOrbital Struct Reference
madness::CoreOrbital Struct Reference
#include <corepotential.h>
Public Member Functions
CoreOrbital ()
CoreOrbital (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, double Bc)
double eval (int m, double rsq, double x, double y, double z) const
double eval_derivative (int m, int axis, double xi, double rsq, double x, double y, double z) const
double eval_radial (double rsq) const
double eval_radial_derivative (double rsq, double xi) const
double eval_spherical_harmonics (int m, double x, double y, double z, double &dp, int axis) const
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
double Bc
vector< double > coeff
vector< double > expnt
double rsqmax
int type
Constructor & Destructor Documentation
CoreOrbital() [1/2]
madness::CoreOrbital::CoreOrbital () inline
CoreOrbital() [2/2]
madness::CoreOrbital::CoreOrbital (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, double Bc) inline
References expnt, and rsqmax.
Member Function Documentation
eval()
double madness::CoreOrbital::eval (int m, double rsq, double x, double y, double z) const
References e(), eval_radial(), eval_spherical_harmonics(), m, p(), R, and type.
eval_derivative()
double madness::CoreOrbital::eval_derivative (int m, int axis, double xi, double rsq, double x, double y, double z) const
References axis, e(), eval_radial(), eval_radial_derivative(), eval_spherical_harmonics(), m, p(), R, type, and xi.
eval_radial()
double madness::CoreOrbital::eval_radial (double rsq) const
References coeff, expnt, k, madness::constants::pi, and pow().
Referenced by eval(), and eval_derivative().
eval_radial_derivative()
double madness::CoreOrbital::eval_radial_derivative (double rsq, double xi) const
References coeff, expnt, k, madness::constants::pi, pow(), and xi.
Referenced by eval_derivative().
eval_spherical_harmonics()
double madness::CoreOrbital::eval_spherical_harmonics (int m, double x, double y, double z, double & dp, int axis = 0) const
braces need by some compilers to limit scope of fac
References axis, m, p(), and type.
Referenced by eval(), and eval_derivative().
serialize()
template<typename Archive > void madness::CoreOrbital::serialize (Archive & ar) inline
References Bc, coeff, expnt, rsqmax, and type.
Member Data Documentation
Bc
double madness::CoreOrbital::Bc
Referenced by serialize().
coeff
vector<double> madness::CoreOrbital::coeff
Referenced by eval_radial(), eval_radial_derivative(), and serialize().
expnt
vector<double> madness::CoreOrbital::expnt
Referenced by CoreOrbital(), eval_radial(), eval_radial_derivative(), and serialize().
rsqmax
double madness::CoreOrbital::rsqmax
Referenced by CoreOrbital(), and serialize().
type
int madness::CoreOrbital::type
Referenced by eval(), eval_derivative(), eval_spherical_harmonics(), and serialize().
The documentation for this struct was generated from the following files:
corepotential.h
corepotential.cc