MADNESS: madness::printleveler Struct Reference
madness::printleveler Struct Reference
#include <znemo.h>
Public Member Functions
printleveler (int printlevel)
bool print_convergence () const
bool print_debug () const
bool print_energies () const
bool print_setup () const
bool print_timings () const
Public Attributes
bool print_convergence_ =false
bool print_debug_information_ =false
bool print_energies_ =false
bool print_nothing_ =true
bool print_setup_ =false
bool print_timings_ =false
Constructor & Destructor Documentation
printleveler()
madness::printleveler::printleveler (int printlevel) inline
References print_convergence_, print_debug_information_, print_energies_, print_setup_, and print_timings_.
Member Function Documentation
print_convergence()
bool madness::printleveler::print_convergence () const inline
References print_convergence_.
Referenced by madness::Znemo::compute_residuals(), madness::Znemo::do_step_restriction(), and madness::Znemo::iterate().
print_debug()
bool madness::printleveler::print_debug () const inline
References print_debug_information_.
print_energies()
bool madness::printleveler::print_energies () const inline
References print_energies_.
Referenced by madness::Znemo::iterate().
print_setup()
bool madness::printleveler::print_setup () const inline
References print_setup_.
Referenced by madness::Znemo::Znemo().
print_timings()
bool madness::printleveler::print_timings () const inline
References print_timings_.
Referenced by madness::Znemo::compute_energy(), madness::Znemo::compute_potentials(), and madness::Znemo::compute_residuals().
Member Data Documentation
print_convergence_
bool madness::printleveler::print_convergence_ =false
Referenced by printleveler(), and print_convergence().
print_debug_information_
bool madness::printleveler::print_debug_information_ =false
Referenced by printleveler(), and print_debug().
print_energies_
bool madness::printleveler::print_energies_ =false
Referenced by printleveler(), and print_energies().
print_nothing_
bool madness::printleveler::print_nothing_ =true
print_setup_
bool madness::printleveler::print_setup_ =false
Referenced by printleveler(), and print_setup().
print_timings_
bool madness::printleveler::print_timings_ =false
Referenced by printleveler(), and print_timings().
The documentation for this struct was generated from the following file:
znemo.h