MADNESS: stubmpi.h File Reference
stubmpi.h File Reference
#include <madness/madness_config.h>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <madness/world/madness_exception.h>
#include <madness/world/timers.h>
Classes
struct MPI_Status
Macros
#define MPI_ANY_SOURCE -2
#define MPI_ANY_TAG -1
#define MPI_BAND ((MPI_Op)0x58000006)
#define MPI_BOR ((MPI_Op)0x58000008)
#define MPI_BXOR ((MPI_Op)0x5800000a)
#define MPI_BYTE ((MPI_Datatype)0x4c00010d)
#define MPI_CHAR ((MPI_Datatype)0x4c000101)
#define MPI_COMM_NULL ((MPI_Comm)0x04000000)
#define MPI_COMM_TYPE_SHARED 4
#define MPI_COMM_WORLD (0x44000000)
#define MPI_CONGRUENT 1
#define MPI_DATATYPE_NULL ((MPI_Datatype)0x0c000000)
#define MPI_DOUBLE ((MPI_Datatype)0x4c00080b)
#define MPI_ERR_ARG 12 /* Invalid argument */
#define MPI_ERR_COMM 5 /* Invalid communicator */
#define MPI_ERR_IN_STATUS 999999
#define MPI_ERRHANDLER_NULL ((MPI_Errhandler)0x14000000)
#define MPI_ERRORS_RETURN 888888
#define MPI_FLOAT ((MPI_Datatype)0x4c00040a)
#define MPI_GROUP_NULL ((MPI_Group)0x08000000)
#define MPI_IDENT 0
#define MPI_IN_PLACE ((void *) -1)
#define MPI_INT ((MPI_Datatype)0x4c000405)
#define MPI_LAND ((MPI_Op)0x58000005)
#define MPI_LONG ((MPI_Datatype)0x4c000807)
#define MPI_LONG_DOUBLE ((MPI_Datatype)0x4c00100c)
#define MPI_LONG_LONG ((MPI_Datatype)0x4c000809)
#define MPI_LONG_LONG_INT ((MPI_Datatype)0x4c000809)
#define MPI_LOR ((MPI_Op)0x58000007)
#define MPI_LXOR ((MPI_Op)0x58000009)
#define MPI_MAX ((MPI_Op)0x58000001)
#define MPI_MAX_ERROR_STRING 1024
#define MPI_MAXLOC ((MPI_Op)0x5800000c)
#define MPI_MIN ((MPI_Op)0x58000002)
#define MPI_MINLOC ((MPI_Op)0x5800000b)
#define MPI_OP_NULL ((MPI_Op)0x18000000)
#define MPI_PROC_NULL -1
#define MPI_PROD ((MPI_Op)0x58000004)
#define MPI_REPLACE ((MPI_Op)0x5800000d)
#define MPI_REQUEST_NULL ((MPI_Request)0x2c000000)
#define MPI_SHORT ((MPI_Datatype)0x4c000203)
#define MPI_SIGNED_CHAR ((MPI_Datatype)0x4c000118)
#define MPI_SIMILAR 2
#define MPI_STATUS_IGNORE ((MPI_Status *)1)
#define MPI_STATUSES_IGNORE ((MPI_Status *)1)
#define MPI_SUCCESS 0 /* Successful return code */
#define MPI_SUM ((MPI_Op)0x58000003)
#define MPI_THREAD_FUNNELED 1
#define MPI_THREAD_MULTIPLE 3
#define MPI_THREAD_SERIALIZED 2
#define MPI_THREAD_SINGLE 0
#define MPI_UNDEFINED (-32766)
#define MPI_UNEQUAL 3
#define MPI_UNSIGNED ((MPI_Datatype)0x4c000406)
#define MPI_UNSIGNED_CHAR ((MPI_Datatype)0x4c000102)
#define MPI_UNSIGNED_LONG ((MPI_Datatype)0x4c000808)
#define MPI_UNSIGNED_LONG_LONG ((MPI_Datatype)0x4c000819)
#define MPI_UNSIGNED_SHORT ((MPI_Datatype)0x4c000204)
#define MPI_WCHAR ((MPI_Datatype)0x4c00040e)
Typedefs
typedef std::ptrdiff_t MPI_Aint
typedef int MPI_Comm
typedef int MPI_Datatype
typedef int MPI_Errhandler
typedef int MPI_Group
typedef int MPI_Info
typedef int MPI_Op
typedef int MPI_Request
typedef struct MPI_Status MPI_Status
typedef void() MPI_User_function(void *a, void *b, int *len, MPI_Datatype *)
Functions
int MPI_Abort (MPI_Comm, int code)
int MPI_Allreduce (void *sendbuf, void *recvbuf, int count, MPI_Datatype, MPI_Op, MPI_Comm)
int MPI_Barrier (MPI_Comm)
int MPI_Bcast (void *, int, MPI_Datatype, int, MPI_Comm)
int MPI_Bsend (void *, int, MPI_Datatype, int, int, MPI_Comm)
int MPI_Buffer_attach (void *, int)
int MPI_Buffer_detach (void *buffer, int *size)
int MPI_Comm_compare (MPI_Comm comm1, MPI_Comm comm2, int *result)
int MPI_Comm_create (MPI_Comm, MPI_Group, MPI_Comm *newcomm)
int MPI_Comm_free (MPI_Comm *comm)
int MPI_Comm_get_attr (MPI_Comm, int, void *, int *)
int MPI_Comm_group (MPI_Comm, MPI_Group *group)
int MPI_Comm_rank (MPI_Comm, int *rank)
int MPI_Comm_set_errhandler (MPI_Comm comm, MPI_Errhandler errhandler)
unsigned int MPI_Comm_size (MPI_Comm, int *size)
int MPI_Comm_split (MPI_Comm comm, int color, int key, MPI_Comm *newcomm)
int MPI_Comm_split_type (MPI_Comm comm, int split_type, int key, MPI_Info info, MPI_Comm *newcomm)
int MPI_Error_string (int errorcode, char *string, int *resultlen)
int MPI_Finalize ()
int MPI_Finalized (int *flag)
int MPI_Gather (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
int MPI_Gatherv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, int root, MPI_Comm)
int MPI_Get_count (MPI_Status *, MPI_Datatype, int *count)
int MPI_Group_free (MPI_Group *group)
int MPI_Group_incl (MPI_Group group, int n, const int ranks[], MPI_Group *newgroup)
int MPI_Group_translate_ranks (MPI_Group, int, const int[], MPI_Group, int ranks2[])
int MPI_Info_create (MPI_Info *info)
int MPI_Info_free (MPI_Info *info)
int MPI_Init (int *, char ***)
int MPI_Init_thread (int *, char ***, int, int *provided)
int MPI_Initialized (int *flag)
int MPI_Irecv (void *, int, MPI_Datatype, int, int, MPI_Comm, MPI_Request *)
int MPI_Isend (void *, int, MPI_Datatype, int, int, MPI_Comm, MPI_Request *)
int MPI_Issend (void *, int, MPI_Datatype, int, int, MPI_Comm, MPI_Request *)
int MPI_Op_create (MPI_User_function *user_fn, int commute, MPI_Op *op)
int MPI_Op_free (MPI_Op *op)
int MPI_Query_thread (int *provided)
int MPI_Recv (void *, int, MPI_Datatype, int, int, MPI_Comm, MPI_Status *)
int MPI_Reduce (void *sendbuf, void *recvbuf, int count, MPI_Datatype, MPI_Op, int, MPI_Comm)
int MPI_Send (void *, int, MPI_Datatype, int, int, MPI_Comm)
int MPI_Ssend (void *, int, MPI_Datatype, int, int, MPI_Comm)
int MPI_Test (MPI_Request *, int *flag, MPI_Status *)
int MPI_Testany (int, MPI_Request[], int *index, int *flag, MPI_Status *)
int MPI_Testsome (int, MPI_Request *, int *outcount, int *, MPI_Status *)
int MPI_Type_get_extent (MPI_Datatype datatype, MPI_Aint *lb, MPI_Aint *extent)
double MPI_Wtime ()
Macro Definition Documentation
MPI_ANY_SOURCE
#define MPI_ANY_SOURCE -2
MPI_ANY_TAG
#define MPI_ANY_TAG -1
MPI_BAND
#define MPI_BAND ((MPI_Op)0x58000006)
MPI_BOR
#define MPI_BOR ((MPI_Op)0x58000008)
MPI_BXOR
#define MPI_BXOR ((MPI_Op)0x5800000a)
MPI_BYTE
#define MPI_BYTE ((MPI_Datatype)0x4c00010d)
MPI_CHAR
#define MPI_CHAR ((MPI_Datatype)0x4c000101)
MPI_COMM_NULL
#define MPI_COMM_NULL ((MPI_Comm)0x04000000)
MPI_COMM_TYPE_SHARED
#define MPI_COMM_TYPE_SHARED 4
MPI_COMM_WORLD
#define MPI_COMM_WORLD (0x44000000)
MPI_CONGRUENT
#define MPI_CONGRUENT 1
MPI_DATATYPE_NULL
#define MPI_DATATYPE_NULL ((MPI_Datatype)0x0c000000)
MPI_DOUBLE
#define MPI_DOUBLE ((MPI_Datatype)0x4c00080b)
MPI_ERR_ARG
#define MPI_ERR_ARG 12 /* Invalid argument */
MPI_ERR_COMM
#define MPI_ERR_COMM 5 /* Invalid communicator */
MPI_ERR_IN_STATUS
#define MPI_ERR_IN_STATUS 999999
MPI_ERRHANDLER_NULL
#define MPI_ERRHANDLER_NULL ((MPI_Errhandler)0x14000000)
MPI_ERRORS_RETURN
#define MPI_ERRORS_RETURN 888888
MPI_FLOAT
#define MPI_FLOAT ((MPI_Datatype)0x4c00040a)
MPI_GROUP_NULL
#define MPI_GROUP_NULL ((MPI_Group)0x08000000)
MPI_IDENT
#define MPI_IDENT 0
MPI_IN_PLACE
#define MPI_IN_PLACE ((void *) -1)
MPI_INT
#define MPI_INT ((MPI_Datatype)0x4c000405)
MPI_LAND
#define MPI_LAND ((MPI_Op)0x58000005)
MPI_LONG
#define MPI_LONG ((MPI_Datatype)0x4c000807)
MPI_LONG_DOUBLE
#define MPI_LONG_DOUBLE ((MPI_Datatype)0x4c00100c)
MPI_LONG_LONG
#define MPI_LONG_LONG ((MPI_Datatype)0x4c000809)
MPI_LONG_LONG_INT
#define MPI_LONG_LONG_INT ((MPI_Datatype)0x4c000809)
MPI_LOR
#define MPI_LOR ((MPI_Op)0x58000007)
MPI_LXOR
#define MPI_LXOR ((MPI_Op)0x58000009)
MPI_MAX
#define MPI_MAX ((MPI_Op)0x58000001)
MPI_MAX_ERROR_STRING
#define MPI_MAX_ERROR_STRING 1024
MPI_MAXLOC
#define MPI_MAXLOC ((MPI_Op)0x5800000c)
MPI_MIN
#define MPI_MIN ((MPI_Op)0x58000002)
MPI_MINLOC
#define MPI_MINLOC ((MPI_Op)0x5800000b)
MPI_OP_NULL
#define MPI_OP_NULL ((MPI_Op)0x18000000)
MPI_PROC_NULL
#define MPI_PROC_NULL -1
MPI_PROD
#define MPI_PROD ((MPI_Op)0x58000004)
MPI_REPLACE
#define MPI_REPLACE ((MPI_Op)0x5800000d)
MPI_REQUEST_NULL
#define MPI_REQUEST_NULL ((MPI_Request)0x2c000000)
MPI_SHORT
#define MPI_SHORT ((MPI_Datatype)0x4c000203)
MPI_SIGNED_CHAR
#define MPI_SIGNED_CHAR ((MPI_Datatype)0x4c000118)
MPI_SIMILAR
#define MPI_SIMILAR 2
MPI_STATUS_IGNORE
#define MPI_STATUS_IGNORE ((MPI_Status *)1)
MPI_STATUSES_IGNORE
#define MPI_STATUSES_IGNORE ((MPI_Status *)1)
MPI_SUCCESS
#define MPI_SUCCESS 0 /* Successful return code */
MPI_SUM
#define MPI_SUM ((MPI_Op)0x58000003)
MPI_THREAD_FUNNELED
#define MPI_THREAD_FUNNELED 1
MPI_THREAD_MULTIPLE
#define MPI_THREAD_MULTIPLE 3
MPI_THREAD_SERIALIZED
#define MPI_THREAD_SERIALIZED 2
MPI_THREAD_SINGLE
#define MPI_THREAD_SINGLE 0
MPI_UNDEFINED
#define MPI_UNDEFINED (-32766)
MPI_UNEQUAL
#define MPI_UNEQUAL 3
MPI_UNSIGNED
#define MPI_UNSIGNED ((MPI_Datatype)0x4c000406)
MPI_UNSIGNED_CHAR
#define MPI_UNSIGNED_CHAR ((MPI_Datatype)0x4c000102)
MPI_UNSIGNED_LONG
#define MPI_UNSIGNED_LONG ((MPI_Datatype)0x4c000808)
MPI_UNSIGNED_LONG_LONG
#define MPI_UNSIGNED_LONG_LONG ((MPI_Datatype)0x4c000819)
MPI_UNSIGNED_SHORT
#define MPI_UNSIGNED_SHORT ((MPI_Datatype)0x4c000204)
MPI_WCHAR
#define MPI_WCHAR ((MPI_Datatype)0x4c00040e)
Typedef Documentation
MPI_Aint
typedef std::ptrdiff_t MPI_Aint
MPI_Comm
typedef int MPI_Comm
MPI_Datatype
typedef int MPI_Datatype
MPI_Errhandler
typedef int MPI_Errhandler
MPI_Group
typedef int MPI_Group
MPI_Info
typedef int MPI_Info
MPI_Op
typedef int MPI_Op
MPI_Request
typedef int MPI_Request
MPI_Status
typedef struct MPI_Status MPI_Status
MPI_User_function
typedef void() MPI_User_function(void *a, void *b, int *len, MPI_Datatype *)
Function Documentation
MPI_Abort()
int MPI_Abort (MPI_Comm , int code) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Abort(), and madness::detail::WorldMpi::initialize().
MPI_Allreduce()
int MPI_Allreduce (void * sendbuf, void * recvbuf, int count, MPI_Datatype , MPI_Op , MPI_Comm) inline
References MPI_IN_PLACE, and MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Allreduce().
MPI_Barrier()
int MPI_Barrier (MPI_Comm) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Barrier().
MPI_Bcast()
int MPI_Bcast (void * , int , MPI_Datatype , int , MPI_Comm) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Bcast().
MPI_Bsend()
int MPI_Bsend (void * , int , MPI_Datatype , int , int , MPI_Comm) inline
References MPI_ERR_COMM.
MPI_Buffer_attach()
int MPI_Buffer_attach (void * , int) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Attach_buffer().
MPI_Buffer_detach()
int MPI_Buffer_detach (void * buffer, int * size) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Detach_buffer().
MPI_Comm_compare()
int MPI_Comm_compare (MPI_Comm comm1, MPI_Comm comm2, int * result) inline
References MPI_IDENT, MPI_SUCCESS, and MPI_UNEQUAL.
Referenced by SafeMPI::Intracomm::Comm_compare().
MPI_Comm_create()
int MPI_Comm_create (MPI_Comm , MPI_Group , MPI_Comm * newcomm) inline
References MPI_COMM_WORLD, and MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Create().
MPI_Comm_free()
int MPI_Comm_free (MPI_Comm * comm) inline
References MPI_COMM_NULL, and MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Impl::~Impl().
MPI_Comm_get_attr()
int MPI_Comm_get_attr (MPI_Comm , int , void * , int *) inline
References MPI_ERR_COMM.
Referenced by SafeMPI::Intracomm::Get_attr().
MPI_Comm_group()
int MPI_Comm_group (MPI_Comm , MPI_Group * group) inline
References MPI_GROUP_NULL, and MPI_SUCCESS.
Referenced by SafeMPI::Group::Impl::Impl().
MPI_Comm_rank()
int MPI_Comm_rank (MPI_Comm , int * rank) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Intracomm(), SafeMPI::Intracomm::Create(), SafeMPI::detail::init_comm_world(), main(), SafeMPI::Intracomm::Split(), and SafeMPI::Intracomm::Split_type().
MPI_Comm_set_errhandler()
int MPI_Comm_set_errhandler (MPI_Comm comm, MPI_Errhandler errhandler) inline
References MPI_SUCCESS.
Referenced by SafeMPI::detail::init_comm_world().
MPI_Comm_size()
unsigned int MPI_Comm_size (MPI_Comm , int * size) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Intracomm(), SafeMPI::Intracomm::Create(), SafeMPI::detail::init_comm_world(), main(), SafeMPI::Intracomm::Split(), and SafeMPI::Intracomm::Split_type().
MPI_Comm_split()
int MPI_Comm_split (MPI_Comm comm, int color, int key, MPI_Comm * newcomm) inline
References MPI_COMM_WORLD, and MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Split().
MPI_Comm_split_type()
int MPI_Comm_split_type (MPI_Comm comm, int split_type, int key, MPI_Info info, MPI_Comm * newcomm) inline
References MPI_COMM_NULL, MPI_SUCCESS, and MPI_UNDEFINED.
Referenced by SafeMPI::Intracomm::Split_type().
MPI_Error_string()
int MPI_Error_string (int errorcode, char * string, int * resultlen) inline
References MPI_ERR_ARG, MPI_ERR_COMM, and MPI_SUCCESS.
Referenced by SafeMPI::Exception::Exception(), SafeMPI::Exception::Exception(), madness::detail::WorldMpi::~WorldMpi(), and SafeMPI::detail::print_mpi_error().
MPI_Finalize()
int MPI_Finalize () inline
References MPI_SUCCESS.
Referenced by main().
MPI_Finalized()
int MPI_Finalized (int * flag) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Is_finalized().
MPI_Gather()
int MPI_Gather (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm) inline
References MPI_Gatherv().
Referenced by madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >::store().
MPI_Gatherv()
int MPI_Gatherv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, int root, MPI_Comm) inline
References MADNESS_ASSERT, MPI_SUCCESS, and MPI_Type_get_extent().
Referenced by MPI_Gather(), and madness::archive::ArchiveStoreImpl< ParallelOutputArchive< VectorOutputArchive >, WorldContainer< keyT, valueT > >::store().
MPI_Get_count()
int MPI_Get_count (MPI_Status * , MPI_Datatype , int * count) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Status::Get_count().
MPI_Group_free()
int MPI_Group_free (MPI_Group * group) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Group::Impl::~Impl().
MPI_Group_incl()
int MPI_Group_incl (MPI_Group group, int n, const int ranks[], MPI_Group * newgroup) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Group::Impl::Impl().
MPI_Group_translate_ranks()
int MPI_Group_translate_ranks (MPI_Group , int , const int [], MPI_Group , int ranks2[]) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Group::Translate_ranks().
MPI_Info_create()
int MPI_Info_create (MPI_Info * info) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Split_type().
MPI_Info_free()
int MPI_Info_free (MPI_Info * info) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Split_type().
MPI_Init()
int MPI_Init (int * , char ***) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Init(), and main().
MPI_Init_thread()
int MPI_Init_thread (int * , char *** , int , int * provided) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Init_thread().
MPI_Initialized()
int MPI_Initialized (int * flag) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Is_initialized().
MPI_Irecv()
int MPI_Irecv (void * , int , MPI_Datatype , int , int , MPI_Comm , MPI_Request *) inline
References MPI_ERR_COMM.
Referenced by SafeMPI::Intracomm::Irecv(), and main().
MPI_Isend()
int MPI_Isend (void * , int , MPI_Datatype , int , int , MPI_Comm , MPI_Request *) inline
References MPI_ERR_COMM.
Referenced by SafeMPI::Intracomm::Isend(), and main().
MPI_Issend()
int MPI_Issend (void * , int , MPI_Datatype , int , int , MPI_Comm , MPI_Request *) inline
References MPI_ERR_COMM.
Referenced by SafeMPI::Intracomm::Issend().
MPI_Op_create()
int MPI_Op_create (MPI_User_function * user_fn, int commute, MPI_Op * op) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Op_create().
MPI_Op_free()
int MPI_Op_free (MPI_Op * op) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Op_free().
MPI_Query_thread()
int MPI_Query_thread (int * provided) inline
References MPI_SUCCESS.
Referenced by SafeMPI::Query_thread().
MPI_Recv()
int MPI_Recv (void * , int , MPI_Datatype , int , int , MPI_Comm , MPI_Status *) inline
References MPI_ERR_COMM.
Referenced by SafeMPI::Intracomm::Recv(), and SafeMPI::Intracomm::Recv().
MPI_Reduce()
int MPI_Reduce (void * sendbuf, void * recvbuf, int count, MPI_Datatype , MPI_Op , int , MPI_Comm) inline
References MPI_IN_PLACE, and MPI_SUCCESS.
Referenced by SafeMPI::Intracomm::Reduce().
MPI_Send()
int MPI_Send (void * , int , MPI_Datatype , int , int , MPI_Comm) inline
References MPI_ERR_COMM.
MPI_Ssend()
int MPI_Ssend (void * , int , MPI_Datatype , int , int , MPI_Comm) inline
References MPI_ERR_COMM.
Referenced by SafeMPI::Intracomm::Send().
MPI_Test()
int MPI_Test (MPI_Request * , int * flag, MPI_Status *) inline
References MPI_SUCCESS.
Referenced by main(), SafeMPI::Request::Test_got_lock_already(), and SafeMPI::Request::Test_got_lock_already().
MPI_Testany()
int MPI_Testany (int , MPI_Request [], int * index, int * flag, MPI_Status *) inline
References MPI_SUCCESS, and MPI_UNDEFINED.
Referenced by SafeMPI::Request::Testany(), and SafeMPI::Request::Testany().
MPI_Testsome()
int MPI_Testsome (int , MPI_Request * , int * outcount, int * , MPI_Status *) inline
References MPI_SUCCESS, and MPI_UNDEFINED.
Referenced by SafeMPI::Request::Testsome(), and SafeMPI::Request::Testsome().
MPI_Type_get_extent()
int MPI_Type_get_extent (MPI_Datatype datatype, MPI_Aint * lb, MPI_Aint * extent) inline
References MPI_BYTE, MPI_CHAR, MPI_DOUBLE, MPI_FLOAT, MPI_INT, MPI_LONG, MPI_LONG_DOUBLE, MPI_LONG_LONG_INT, MPI_SHORT, MPI_SIGNED_CHAR, MPI_SUCCESS, MPI_UNDEFINED, MPI_UNSIGNED, MPI_UNSIGNED_CHAR, MPI_UNSIGNED_LONG, MPI_UNSIGNED_LONG_LONG, MPI_UNSIGNED_SHORT, and MPI_WCHAR.
Referenced by MPI_Gatherv().
MPI_Wtime()
double MPI_Wtime () inline
References madness::wall_time().
Referenced by SafeMPI::Wtime().