MADNESS: svpe.cc File Reference
svpe.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/funcplot.h>
#include <madness/tensor/solvers.h>
#include "molecularmask.h"
#include <madness/mra/nonlinsol.h>
#include <madness/constants.h>
#include <vector>
Classes
class SVPESolver
Macros
#define TIME(MSG, X)
Functions
double charge_function (const coord_3d &r)
double electronic_charge_function (const coord_3d &r)
int main (int argc, char **argv)
double nuclear_charge_function (const coord_3d &r)
double reciprocal (double x)
Variables
const double epsilon_0 = 1.0
const double epsilon_1 = 78.3600
const int k = 8
const double L = 20
const double R = 2.456644
const double sigma = 0.5
const double thresh = 1e-6
double XXstart
Macro Definition Documentation
TIME
#define TIME (MSG, X)
Value:
                    XXstart=wall_time();         \
                    X; \
                    if (world.rank() == 0) print("timer:",MSG,"used",wall_time()-XXstart) \
Function Documentation
charge_function()
double charge_function (const coord_3d & r)
References electronic_charge_function(), and nuclear_charge_function().
Referenced by main().
electronic_charge_function()
double electronic_charge_function (const coord_3d & r)
References madness::constants::pi.
Referenced by charge_function().
main()
int main (int argc, char ** argv)
References madness::BC_FREE, charge_function(), SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), epsilon_0, epsilon_1, madness::f, madness::finalize(), madness::initialize(), k, L, lo, SVPESolver::make_surface_charge(), op(), madness::plot_line(), madness::print(), R, madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), sigma, SVPESolver::solve(), madness::startup(), thresh, TIME, madness::truncate(), and u().
nuclear_charge_function()
double nuclear_charge_function (const coord_3d & r)
References madness::constants::pi, and pow().
Referenced by charge_function().
reciprocal()
double reciprocal (double x)
Variable Documentation
epsilon_0
const double epsilon_0 = 1.0
Referenced by SVPESolver::SVPESolver(), and main().
epsilon_1
const double epsilon_1 = 78.3600
Referenced by SVPESolver::SVPESolver(), and main().
k
const int k = 8
Referenced by main().
L
const double L = 20
Referenced by main().
R
const double R = 2.456644
Referenced by main().
sigma
const double sigma = 0.5
Referenced by SVPESolver::SVPESolver(), and main().
thresh
const double thresh = 1e-6
Referenced by main(), and SVPESolver::solve().
XXstart
double XXstart