MADNESS: tdse.cc File Reference
tdse.cc File Reference
Evolves the hydrogen atom in imaginary and also real time.
#include <madness/mra/mra.h>
#include <madness/mra/qmprop.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
#include <madness/tensor/vmath.h>
#include <complex>
#include <madness/mra/funcimpl.h>
#include <madness/mra/lbdeux.h>
Classes
struct InputParameters
struct lbcost< T, NDIM >
struct refop
struct unaryexp< T, NDIM >
struct unaryexp< double_complex, NDIM >
Macros
#define MAKE_PROPAGATOR(world, t)
Typedefs
typedef FunctionFactory< double_complex, 3 > complex_factoryT
typedef Function< double_complex, 3 > complex_functionT
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 3 > > complex_functorT
typedef Convolution1D< double_complex > complex_operatorT
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
Functions
complex_functionT APPLY (const complex_operatorT *q1d, const complex_functionT &psi)
complex_functionT chin_chen (const complex_functionT &expV_0, const complex_functionT &expV_tilde, const complex_functionT &expV_1, const complex_operatorT *G, const complex_functionT &psi0)
void converge (World &world, functionT &potn, functionT &psi, double &eps)
void converge2s (World &world, functionT &potn, functionT &psi, double &eps)
static double d_smoothed_potential (double r)
void doit (World &world)
void doplot (World &world, int step, const complex_functionT &psi, double Lplot, long numpt, const char *fname)
static double dVdx (const coordT &r)
static double dVdy (const coordT &r)
static double dVdz (const coordT &r)
template<typename T >
double energy (World &world, const Function< T, 3 > &psi, const functionT &potn)
static double guess1s (const coordT &r)
static double guess2s (const coordT &r)
double laser (double t)
void line_plot (World &world, int step, complex_functionT &psi)
void loadbal (World &world, functionT &potn, complex_functionT &psi)
int main (int argc, char **argv)
complex_functionT make_exp (double t, const functionT &v)
double myreal (const double_complex &t)
double myreal (double t)
std::ostream & operator<< (std::ostream &s, const InputParameters &p)
void preloadbal (World &world, functionT &potn, complex_functionT &psi)
void print_stats (World &world, int step, double t, const functionT &v, const functionT &x, const functionT &y, const functionT &z, const functionT &dV_dz, const complex_functionT &psi0, const complex_functionT &psi)
void print_stats_header (World &world)
void propagate (World &world, int step0)
static double smoothed_potential (double r)
complex_functionT trotter (World &world, const complex_functionT &expV, const complex_operatorT *G, const complex_functionT &psi0)
static double V (const coordT &r)
bool wave_function_exists (World &world, int step)
const char * wave_function_filename (int step)
const char * wave_function_large_plot_filename (int step)
complex_functionT wave_function_load (World &world, int step)
const char * wave_function_small_plot_filename (int step)
void wave_function_store (World &world, int step, const complex_functionT &psi)
double xdipole (const coordT &r)
double ydipole (const coordT &r)
double zdipole (const coordT &r)
Variables
InputParameters param
static double zero_field_time
Detailed Description
Evolves the hydrogen atom in imaginary and also real time.
Macro Definition Documentation
MAKE_PROPAGATOR
#define MAKE_PROPAGATOR (world, t)
Typedef Documentation
complex_factoryT
typedef FunctionFactory<double_complex,3> complex_factoryT
complex_functionT
typedef Function<double_complex,3> complex_functionT
complex_functorT
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,3> > complex_functorT
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
coordT
typedef Vector<double,3> coordT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
Function Documentation
APPLY()
complex_functionT APPLY (const complex_operatorT * q1d, const complex_functionT & psi)
References madness::apply_1d_realspace_push(), madness::Function< T, NDIM >::broaden(), lo, madness::nonlinear_vector_solver(), psi(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::sum_down().
Referenced by chin_chen(), and trotter().
chin_chen()
complex_functionT chin_chen (const complex_functionT & expV_0, const complex_functionT & expV_tilde, const complex_functionT & expV_1, const complex_operatorT * G, const complex_functionT & psi0)
References APPLY(), madness::nonlinear_vector_solver(), param, psi0(), InputParameters::thresh, and madness::wall_time().
Referenced by propagate().
converge()
void converge (World & world, functionT & potn, functionT & psi, double & eps)
References madness::apply(), madness::BSHOperator3D(), InputParameters::cut, e(), madness::inner(), madness::nonlinear_vector_solver(), norm(), madness::Function< T, NDIM >::norm2(), op(), param, potn(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), InputParameters::thresh, madness::Function< T, NDIM >::truncate(), and madness::wall_time().
Referenced by doit(), and madness::MolecularOptimizer::optimize().
converge2s()
void converge2s (World & world, functionT & potn, functionT & psi, double & eps)
References madness::apply(), madness::BSHOperator3D(), InputParameters::cut, e(), madness::inner(), madness::nonlinear_vector_solver(), norm(), madness::Function< T, NDIM >::norm2(), op(), param, potn(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), InputParameters::thresh, madness::Function< T, NDIM >::truncate(), and madness::wall_time().
d_smoothed_potential()
static double d_smoothed_potential (double r) static
References e(), madness::nonlinear_vector_solver(), and madness::r2().
Referenced by dVdx(), dVdy(), and dVdz().
doit()
void doit (World & world)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::apply(), madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::broadcast_serializable(), madness::BSHOperator3D(), converge(), madness::copy(), InputParameters::cut, e(), energy, madness::error(), madness::WorldGopInterface::fence(), madness::World::gop, guess1s(), guess2s(), madness::inner(), InputParameters::iState, InputParameters::k, InputParameters::L, madness::LoadBalanceDeux< NDIM >::load_balance(), myreal(), madness::nonlinear_vector_solver(), norm(), madness::response_space::norm2(), madness::Function< T, NDIM >::norm2(), op(), param, potn(), madness::print(), propagate(), madness::World::rank(), InputParameters::read(), InputParameters::safety, madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), InputParameters::thresh, madness::Function< T, NDIM >::truncate(), V(), madness::wall_time(), wave_function_exists(), wave_function_store(), ydipole(), and zdipole().
Referenced by madness::SeparatedConvolution< Q, NDIM >::apply_transformation(), madness::SeparatedConvolution< Q, NDIM >::apply_transformation2(), madness::MacroTask< taskT >::MacroTaskInternal::get_output(), main(), and BoysLocalization::operator()().
doplot()
void doplot (World & world, int step, const complex_functionT & psi, double Lplot, long numpt, const char * fname)
References madness::_(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), and madness::wall_time().
Referenced by propagate().
dVdx()
static double dVdx (const coordT & r) static
References InputParameters::cut, d_smoothed_potential(), InputParameters::natom, madness::nonlinear_vector_solver(), param, InputParameters::R, sum, and InputParameters::Z.
Referenced by propagate().
dVdy()
static double dVdy (const coordT & r) static
References InputParameters::cut, d_smoothed_potential(), InputParameters::natom, madness::nonlinear_vector_solver(), param, InputParameters::R, sum, and InputParameters::Z.
Referenced by propagate().
dVdz()
static double dVdz (const coordT & r) static
References InputParameters::cut, d_smoothed_potential(), InputParameters::natom, madness::nonlinear_vector_solver(), param, InputParameters::R, sum, and InputParameters::Z.
Referenced by propagate().
energy()
template<typename T > double energy (World & world, const Function< T, 3 > & psi, const functionT & potn)
References madness::Function< T, NDIM >::compress(), madness::WorldGopInterface::fence(), madness::World::gop, madness::inner(), myreal(), madness::nonlinear_vector_solver(), potn(), psi(), and T().
guess1s()
static double guess1s (const coordT & r) static
References InputParameters::cut, InputParameters::natom, madness::nonlinear_vector_solver(), param, InputParameters::R, sum, Z, and InputParameters::Z.
Referenced by doit().
guess2s()
static double guess2s (const coordT & r) static
References InputParameters::cut, InputParameters::natom, madness::nonlinear_vector_solver(), param, InputParameters::R, sum, Z, and InputParameters::Z.
Referenced by doit().
laser()
double laser (double t)
References InputParameters::F, InputParameters::ncycle, madness::nonlinear_vector_solver(), InputParameters::omega, param, and madness::constants::pi.
Referenced by print_stats(), and propagate().
line_plot()
void line_plot (World & world, int step, complex_functionT & psi)
References madness::f, madness::WorldGopInterface::fence(), madness::World::gop, InputParameters::Llarge, madness::nonlinear_vector_solver(), param, psi(), madness::World::rank(), madness::World::size(), madness::WorldGopInterface::sum(), v, and wave_function_filename().
Referenced by propagate().
loadbal()
void loadbal (World & world, functionT & potn, complex_functionT & psi)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), potn(), madness::print(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), and madness::World::size().
Referenced by propagate(), and test().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, doit(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), print_stats(), and madness::startup().
make_exp()
complex_functionT make_exp (double t, const functionT & v)
References expV(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::unaryop(), and v.
Referenced by propagate().
myreal() [1/2]
double myreal (const double_complex & t)
References madness::real().
myreal() [2/2]
double myreal (double t)
Referenced by doit(), and energy().
operator<<()
std::ostream & operator<< (std::ostream & s, const InputParameters & p)
References p().
preloadbal()
void preloadbal (World & world, functionT & potn, complex_functionT & psi)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), potn(), madness::print(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), and madness::World::size().
Referenced by propagate().
print_stats()
void print_stats (World & world, int step, double t, const functionT & v, const functionT & x, const functionT & y, const functionT & z, const functionT & dV_dz, const complex_functionT & psi0, const complex_functionT & psi)
References std::abs(), energy, madness::inner(), laser(), madness::nonlinear_vector_solver(), norm(), psi(), psi0(), madness::World::rank(), madness::real(), v, and madness::wall_time().
Referenced by main(), and propagate().
print_stats_header()
void print_stats_header (World & world)
References madness::nonlinear_vector_solver(), and madness::World::rank().
Referenced by propagate().
propagate()
void propagate (World & world, int step0)
References madness::WorldGopInterface::broadcast(), c, chin_chen(), madness::copy(), ctarget, InputParameters::cut, doplot(), dVdx(), dVdy(), dVdz(), expV(), madness::WorldGopInterface::fence(), madness::World::gop, InputParameters::k, InputParameters::L, laser(), line_plot(), InputParameters::Llarge, loadbal(), InputParameters::Lsmall, make_exp(), InputParameters::ndump, InputParameters::nloadbal, madness::nonlinear_vector_solver(), InputParameters::nplot, InputParameters::nprint, param, madness::constants::pi, potn(), preloadbal(), madness::print(), print_stats(), print_stats_header(), psi(), psi0(), madness::qm_1d_free_particle_propagator(), madness::World::rank(), InputParameters::target_time, tcrit, InputParameters::thresh, trotter(), madness::Function< T, NDIM >::truncate(), InputParameters::tScale, V(), madness::wall_time(), wave_function_large_plot_filename(), wave_function_load(), wave_function_small_plot_filename(), wave_function_store(), xdipole(), ydipole(), zdipole(), and zero_field_time.
Referenced by doit().
smoothed_potential()
static double smoothed_potential (double r) static
References e(), madness::nonlinear_vector_solver(), and madness::r2().
Referenced by V().
trotter()
complex_functionT trotter (World & world, const complex_functionT & expV, const complex_operatorT * G, const complex_functionT & psi0)
References APPLY(), expV(), madness::nonlinear_vector_solver(), param, madness::print(), psi0(), madness::World::rank(), madness::Function< T, NDIM >::size(), InputParameters::thresh, and madness::Function< T, NDIM >::truncate().
Referenced by propagate().
V()
static double V (const coordT & r) static
References InputParameters::cut, InputParameters::natom, madness::nonlinear_vector_solver(), param, InputParameters::R, smoothed_potential(), sum, and InputParameters::Z.
Referenced by madness::HartreeFock< T, NDIM >::HartreeFock(), madness::HartreeFockNuclearPotentialOp< T, NDIM >::HartreeFockNuclearPotentialOp(), madness::TDHF::apply_G(), compute_energy(), compute_update(), dft_xc_lda_ene(), dft_xc_lda_V(), dnuclear_anchor_test(), doit(), energy(), madness::GMRES(), iterate(), DF::iterate(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), madness::jacobi(), jacobi(), main(), main(), make_Hd(), make_Hv(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_potentials(), nuclear_anchor_test(), madness::NuclearCorrelationFactor::square_times_V_functor::operator()(), madness::TDHF::orthonormalize(), propagate(), madness::Nemo::solve_cphf(), madness::syev(), madness::syev(), madness::sygv(), madness::sygvp(), test_fock(), test_gconv(), madness::test_syev(), and madness::test_sygv().
wave_function_exists()
bool wave_function_exists (World & world, int step)
References wave_function_filename().
Referenced by doit().
wave_function_filename()
const char * wave_function_filename (int step)
References madness::nonlinear_vector_solver(), param, and InputParameters::prefix.
Referenced by line_plot(), wave_function_exists(), wave_function_load(), and wave_function_store().
wave_function_large_plot_filename()
const char * wave_function_large_plot_filename (int step)
References madness::nonlinear_vector_solver(), param, and InputParameters::prefix.
Referenced by propagate().
wave_function_load()
complex_functionT wave_function_load (World & world, int step)
References psi(), and wave_function_filename().
Referenced by propagate().
wave_function_small_plot_filename()
const char * wave_function_small_plot_filename (int step)
References madness::nonlinear_vector_solver(), param, and InputParameters::prefix.
Referenced by propagate().
wave_function_store()
void wave_function_store (World & world, int step, const complex_functionT & psi)
References InputParameters::nio, param, psi(), and wave_function_filename().
Referenced by doit(), and propagate().
xdipole()
double xdipole (const coordT & r)
Referenced by propagate().
ydipole()
double ydipole (const coordT & r)
Referenced by doit(), and propagate().
zdipole()
double zdipole (const coordT & r)
Referenced by doit(), and propagate().
Variable Documentation
param
InputParameters param
Referenced by madness::Diamagnetic_potential_factor::Diamagnetic_potential_factor(), madness::SCFProtocol::SCFProtocol(), molresponse::write_response_input::write_response_input(), molresponse::write_test_input::write_test_input(), madness::write_test_input::write_test_input(), write_test_input::write_test_input(), madness::TDHF::analyze(), madness::CCConvolutionOperator< T, NDIM >::CCConvolutionOperatorPtr(), madness::CCConvolutionOperatorPtr(), madness::NemoBase::check_convergence(), chin_chen(), madness::SCF::compute_residual(), converge(), converge2s(), dnuclear_anchor_test(), doit(), dVdx(), dVdy(), dVdz(), guess1s(), guess2s(), laser(), line_plot(), madness::archive::ArchiveLoadImpl< ParallelInputArchive< archiveT >, CCPairFunction< T, NDIM > >::load(), main(), nuclear_anchor_test(), madness::MolecularEnergy::output_calc_info_schema(), madness::plot_plane(), madness::plot_plane(), madness::CC2::print_parameters(), madness::Molecule::print_parameters(), madness::TDHF::print_parameters(), madness::Zcis::print_parameters(), madness::QCCalculationParametersBase::print_to_string(), propagate(), test_capitalization(), test_comment_lines(), test_derived(), test_empty_lines(), test_fock(), test_nemo(), test_not_allowed(), test_read_restartaodata(), test_read_restartdata(), test_serialize(), test_trailing_characters(), test_type_conversion1(), test_type_conversion2(), test_type_conversion3(), test_type_conversion4(), test_type_conversion5(), test_type_conversion6(), test_type_conversion7(), test_type_conversion8(), trotter(), V(), wave_function_filename(), wave_function_large_plot_filename(), wave_function_small_plot_filename(), wave_function_store(), molresponse::write_test_input::write_to_test_input(), molresponse::write_response_input::write_to_test_input(), and madness::write_test_input::write_to_test_input().
zero_field_time
double zero_field_time static
Referenced by propagate().