MADNESS: tensor_spec.h File Reference
tensor_spec.h File Reference
Functions
template Tensor< Tensor< double >::scalar_type > abs (const Tensor< double > &t)
template Tensor< Tensor< double_complex >::scalar_type > abs (const Tensor< double_complex > &t)
template Tensor< Tensor< float >::scalar_type > abs (const Tensor< float > &t)
template Tensor< Tensor< float_complex >::scalar_type > abs (const Tensor< float_complex > &t)
template Tensor< Tensor< int >::scalar_type > abs (const Tensor< int > &t)
template Tensor< Tensor< long >::scalar_type > abs (const Tensor< long > &t)
template Tensor< double_complex > conj (const Tensor< double_complex > &t)
template Tensor< float_complex > conj (const Tensor< float_complex > &t)
template Tensor< double_complex > conj_transpose (const Tensor< double_complex > &t)
template Tensor< float_complex > conj_transpose (const Tensor< float_complex > &t)
template Tensor< double > copy (const Tensor< double > &t)
template Tensor< double_complex > copy (const Tensor< double_complex > &t)
template Tensor< float > copy (const Tensor< float > &t)
template Tensor< float_complex > copy (const Tensor< float_complex > &t)
template Tensor< int > copy (const Tensor< int > &t)
template Tensor< long > copy (const Tensor< long > &t)
template Tensor< TensorResultType< double, double >::type > & fast_transform (const Tensor< double > &t, const Tensor< double > &c, Tensor< TensorResultType< double, double >::type > &result, Tensor< TensorResultType< double, double >::type > &work)
template Tensor< TensorResultType< double, double_complex >::type > & fast_transform (const Tensor< double > &t, const Tensor< double_complex > &c, Tensor< TensorResultType< double, double_complex >::type > &result, Tensor< TensorResultType< double, double_complex >::type > &work)
template Tensor< TensorResultType< double_complex, double >::type > & fast_transform (const Tensor< double_complex > &t, const Tensor< double > &c, Tensor< TensorResultType< double_complex, double >::type > &result, Tensor< TensorResultType< double_complex, double >::type > &work)
template Tensor< TensorResultType< double_complex, double_complex >::type > & fast_transform (const Tensor< double_complex > &t, const Tensor< double_complex > &c, Tensor< TensorResultType< double_complex, double_complex >::type > &result, Tensor< TensorResultType< double_complex, double_complex >::type > &work)
template Tensor< TensorResultType< float, float >::type > & fast_transform (const Tensor< float > &t, const Tensor< float > &c, Tensor< TensorResultType< float, float >::type > &result, Tensor< TensorResultType< float, float >::type > &work)
template Tensor< TensorResultType< float, float_complex >::type > & fast_transform (const Tensor< float > &t, const Tensor< float_complex > &c, Tensor< TensorResultType< float, float_complex >::type > &result, Tensor< TensorResultType< float, float_complex >::type > &work)
template Tensor< TensorResultType< float_complex, float >::type > & fast_transform (const Tensor< float_complex > &t, const Tensor< float > &c, Tensor< TensorResultType< float_complex, float >::type > &result, Tensor< TensorResultType< float_complex, float >::type > &work)
template Tensor< TensorResultType< float_complex, float_complex >::type > & fast_transform (const Tensor< float_complex > &t, const Tensor< float_complex > &c, Tensor< TensorResultType< float_complex, float_complex >::type > &result, Tensor< TensorResultType< float_complex, float_complex >::type > &work)
template Tensor< TensorResultType< double, double >::type > general_transform (const Tensor< double > &t, const Tensor< double > c[])
template Tensor< TensorResultType< double, double_complex >::type > general_transform (const Tensor< double > &t, const Tensor< double_complex > c[])
template Tensor< TensorResultType< double_complex, double >::type > general_transform (const Tensor< double_complex > &t, const Tensor< double > c[])
template Tensor< TensorResultType< double_complex, double_complex >::type > general_transform (const Tensor< double_complex > &t, const Tensor< double_complex > c[])
template Tensor< TensorResultType< float, float >::type > general_transform (const Tensor< float > &t, const Tensor< float > c[])
template Tensor< TensorResultType< float, float_complex >::type > general_transform (const Tensor< float > &t, const Tensor< float_complex > c[])
template Tensor< TensorResultType< float_complex, float >::type > general_transform (const Tensor< float_complex > &t, const Tensor< float > c[])
template Tensor< TensorResultType< float_complex, float_complex >::type > general_transform (const Tensor< float_complex > &t, const Tensor< float_complex > c[])
template Tensor< Tensor< double_complex >::scalar_type > imag (const Tensor< double_complex > &t)
template Tensor< Tensor< float_complex >::scalar_type > imag (const Tensor< float_complex > &t)
template Tensor< TensorResultType< double, double >::type > inner (const Tensor< double > &left, const Tensor< double > &right, long k0, long k1)
template Tensor< TensorResultType< double, double_complex >::type > inner (const Tensor< double > &left, const Tensor< double_complex > &right, long k0, long k1)
template Tensor< TensorResultType< double_complex, double >::type > inner (const Tensor< double_complex > &left, const Tensor< double > &right, long k0, long k1)
template Tensor< TensorResultType< double_complex, double_complex >::type > inner (const Tensor< double_complex > &left, const Tensor< double_complex > &right, long k0, long k1)
template Tensor< TensorResultType< float, float >::type > inner (const Tensor< float > &left, const Tensor< float > &right, long k0, long k1)
template Tensor< TensorResultType< float, float_complex >::type > inner (const Tensor< float > &left, const Tensor< float_complex > &right, long k0, long k1)
template Tensor< TensorResultType< float_complex, float >::type > inner (const Tensor< float_complex > &left, const Tensor< float > &right, long k0, long k1)
template Tensor< TensorResultType< float_complex, float_complex >::type > inner (const Tensor< float_complex > &left, const Tensor< float_complex > &right, long k0, long k1)
template void inner_result (const Tensor< double > &left, const Tensor< double > &right, long k0, long k1, Tensor< TensorResultType< double, double >::type > &result)
template void inner_result (const Tensor< double > &left, const Tensor< double_complex > &right, long k0, long k1, Tensor< TensorResultType< double, double_complex >::type > &result)
template void inner_result (const Tensor< double_complex > &left, const Tensor< double > &right, long k0, long k1, Tensor< TensorResultType< double_complex, double >::type > &result)
template void inner_result (const Tensor< double_complex > &left, const Tensor< double_complex > &right, long k0, long k1, Tensor< TensorResultType< double_complex, double_complex >::type > &result)
template void inner_result (const Tensor< float > &left, const Tensor< float > &right, long k0, long k1, Tensor< TensorResultType< float, float >::type > &result)
template void inner_result (const Tensor< float > &left, const Tensor< float_complex > &right, long k0, long k1, Tensor< TensorResultType< float, float_complex >::type > &result)
template void inner_result (const Tensor< float_complex > &left, const Tensor< float > &right, long k0, long k1, Tensor< TensorResultType< float_complex, float >::type > &result)
template void inner_result (const Tensor< float_complex > &left, const Tensor< float_complex > &right, long k0, long k1, Tensor< TensorResultType< float_complex, float_complex >::type > &result)
template std::ostream & operator<< (std::ostream &s, const Tensor< double > &t)
template std::ostream & operator<< (std::ostream &s, const Tensor< double_complex > &t)
template std::ostream & operator<< (std::ostream &s, const Tensor< float > &t)
template std::ostream & operator<< (std::ostream &s, const Tensor< float_complex > &t)
template std::ostream & operator<< (std::ostream &s, const Tensor< int > &t)
template std::ostream & operator<< (std::ostream &s, const Tensor< long > &t)
template Tensor< double > outer (const Tensor< double > &left, const Tensor< double > &right)
template Tensor< double_complex > outer (const Tensor< double_complex > &left, const Tensor< double_complex > &right)
template Tensor< float > outer (const Tensor< float > &left, const Tensor< float > &right)
template Tensor< float_complex > outer (const Tensor< float_complex > &left, const Tensor< float_complex > &right)
template Tensor< int > outer (const Tensor< int > &left, const Tensor< int > &right)
template Tensor< long > outer (const Tensor< long > &left, const Tensor< long > &right)
template Tensor< Tensor< double_complex >::scalar_type > real (const Tensor< double_complex > &t)
template Tensor< Tensor< float_complex >::scalar_type > real (const Tensor< float_complex > &t)
template Tensor< TensorResultType< double, double >::type > transform (const Tensor< double > &t, const Tensor< double > &c)
template Tensor< TensorResultType< double, double_complex >::type > transform (const Tensor< double > &t, const Tensor< double_complex > &c)
template Tensor< TensorResultType< double_complex, double >::type > transform (const Tensor< double_complex > &t, const Tensor< double > &c)
template Tensor< TensorResultType< double_complex, double_complex >::type > transform (const Tensor< double_complex > &t, const Tensor< double_complex > &c)
template Tensor< TensorResultType< float, float >::type > transform (const Tensor< float > &t, const Tensor< float > &c)
template Tensor< TensorResultType< float, float_complex >::type > transform (const Tensor< float > &t, const Tensor< float_complex > &c)
template Tensor< TensorResultType< float_complex, float >::type > transform (const Tensor< float_complex > &t, const Tensor< float > &c)
template Tensor< TensorResultType< float_complex, float_complex >::type > transform (const Tensor< float_complex > &t, const Tensor< float_complex > &c)
template Tensor< double > transpose (const Tensor< double > &t)
template Tensor< double_complex > transpose (const Tensor< double_complex > &t)
template Tensor< float > transpose (const Tensor< float > &t)
template Tensor< float_complex > transpose (const Tensor< float_complex > &t)
template Tensor< int > transpose (const Tensor< int > &t)
template Tensor< long > transpose (const Tensor< long > &t)
Function Documentation
abs() [1/6]
template Tensor< Tensor< double >::scalar_type > abs (const Tensor< double > & t)
abs() [2/6]
template Tensor< Tensor< double_complex >::scalar_type > abs (const Tensor< double_complex > & t)
abs() [3/6]
template Tensor< Tensor< float >::scalar_type > abs (const Tensor< float > & t)
abs() [4/6]
template Tensor< Tensor< float_complex >::scalar_type > abs (const Tensor< float_complex > & t)
abs() [5/6]
template Tensor< Tensor< int >::scalar_type > abs (const Tensor< int > & t)
abs() [6/6]
template Tensor< Tensor< long >::scalar_type > abs (const Tensor< long > & t)
conj() [1/2]
template Tensor< double_complex > conj (const Tensor< double_complex > & t)
Referenced by kinetic_energy_matrix_slow().
conj() [2/2]
template Tensor< float_complex > conj (const Tensor< float_complex > & t)
conj_transpose() [1/2]
template Tensor< double_complex > conj_transpose (const Tensor< double_complex > & t)
conj_transpose() [2/2]
template Tensor< float_complex > conj_transpose (const Tensor< float_complex > & t)
copy() [1/6]
template Tensor< double > copy (const Tensor< double > & t)
copy() [2/6]
template Tensor< double_complex > copy (const Tensor< double_complex > & t)
copy() [3/6]
template Tensor< float > copy (const Tensor< float > & t)
copy() [4/6]
template Tensor< float_complex > copy (const Tensor< float_complex > & t)
copy() [5/6]
template Tensor< int > copy (const Tensor< int > & t)
copy() [6/6]
template Tensor< long > copy (const Tensor< long > & t)
fast_transform() [1/8]
template Tensor< TensorResultType< double, double >::type > & fast_transform (const Tensor< double > & t, const Tensor< double > & c, Tensor< TensorResultType< double, double >::type > & result, Tensor< TensorResultType< double, double >::type > & work)
Referenced by main().
fast_transform() [2/8]
template Tensor< TensorResultType< double, double_complex >::type > & fast_transform (const Tensor< double > & t, const Tensor< double_complex > & c, Tensor< TensorResultType< double, double_complex >::type > & result, Tensor< TensorResultType< double, double_complex >::type > & work)
fast_transform() [3/8]
template Tensor< TensorResultType< double_complex, double >::type > & fast_transform (const Tensor< double_complex > & t, const Tensor< double > & c, Tensor< TensorResultType< double_complex, double >::type > & result, Tensor< TensorResultType< double_complex, double >::type > & work)
fast_transform() [4/8]
template Tensor< TensorResultType< double_complex, double_complex >::type > & fast_transform (const Tensor< double_complex > & t, const Tensor< double_complex > & c, Tensor< TensorResultType< double_complex, double_complex >::type > & result, Tensor< TensorResultType< double_complex, double_complex >::type > & work)
fast_transform() [5/8]
template Tensor< TensorResultType< float, float >::type > & fast_transform (const Tensor< float > & t, const Tensor< float > & c, Tensor< TensorResultType< float, float >::type > & result, Tensor< TensorResultType< float, float >::type > & work)
fast_transform() [6/8]
template Tensor< TensorResultType< float, float_complex >::type > & fast_transform (const Tensor< float > & t, const Tensor< float_complex > & c, Tensor< TensorResultType< float, float_complex >::type > & result, Tensor< TensorResultType< float, float_complex >::type > & work)
fast_transform() [7/8]
template Tensor< TensorResultType< float_complex, float >::type > & fast_transform (const Tensor< float_complex > & t, const Tensor< float > & c, Tensor< TensorResultType< float_complex, float >::type > & result, Tensor< TensorResultType< float_complex, float >::type > & work)
fast_transform() [8/8]
template Tensor< TensorResultType< float_complex, float_complex >::type > & fast_transform (const Tensor< float_complex > & t, const Tensor< float_complex > & c, Tensor< TensorResultType< float_complex, float_complex >::type > & result, Tensor< TensorResultType< float_complex, float_complex >::type > & work)
general_transform() [1/8]
template Tensor< TensorResultType< double, double >::type > general_transform (const Tensor< double > & t, const Tensor< double > c[])
general_transform() [2/8]
template Tensor< TensorResultType< double, double_complex >::type > general_transform (const Tensor< double > & t, const Tensor< double_complex > c[])
general_transform() [3/8]
template Tensor< TensorResultType< double_complex, double >::type > general_transform (const Tensor< double_complex > & t, const Tensor< double > c[])
general_transform() [4/8]
template Tensor< TensorResultType< double_complex, double_complex >::type > general_transform (const Tensor< double_complex > & t, const Tensor< double_complex > c[])
general_transform() [5/8]
template Tensor< TensorResultType< float, float >::type > general_transform (const Tensor< float > & t, const Tensor< float > c[])
general_transform() [6/8]
template Tensor< TensorResultType< float, float_complex >::type > general_transform (const Tensor< float > & t, const Tensor< float_complex > c[])
general_transform() [7/8]
template Tensor< TensorResultType< float_complex, float >::type > general_transform (const Tensor< float_complex > & t, const Tensor< float > c[])
general_transform() [8/8]
template Tensor< TensorResultType< float_complex, float_complex >::type > general_transform (const Tensor< float_complex > & t, const Tensor< float_complex > c[])
imag() [1/2]
template Tensor< Tensor< double_complex >::scalar_type > imag (const Tensor< double_complex > & t)
Referenced by madness::detail::imagop< NDIM >::operator()().
imag() [2/2]
template Tensor< Tensor< float_complex >::scalar_type > imag (const Tensor< float_complex > & t)
inner() [1/8]
template Tensor< TensorResultType< double, double >::type > inner (const Tensor< double > & left, const Tensor< double > & right, long k0, long k1)
inner() [2/8]
template Tensor< TensorResultType< double, double_complex >::type > inner (const Tensor< double > & left, const Tensor< double_complex > & right, long k0, long k1)
inner() [3/8]
template Tensor< TensorResultType< double_complex, double >::type > inner (const Tensor< double_complex > & left, const Tensor< double > & right, long k0, long k1)
inner() [4/8]
template Tensor< TensorResultType< double_complex, double_complex >::type > inner (const Tensor< double_complex > & left, const Tensor< double_complex > & right, long k0, long k1)
inner() [5/8]
template Tensor< TensorResultType< float, float >::type > inner (const Tensor< float > & left, const Tensor< float > & right, long k0, long k1)
inner() [6/8]
template Tensor< TensorResultType< float, float_complex >::type > inner (const Tensor< float > & left, const Tensor< float_complex > & right, long k0, long k1)
inner() [7/8]
template Tensor< TensorResultType< float_complex, float >::type > inner (const Tensor< float_complex > & left, const Tensor< float > & right, long k0, long k1)
inner() [8/8]
template Tensor< TensorResultType< float_complex, float_complex >::type > inner (const Tensor< float_complex > & left, const Tensor< float_complex > & right, long k0, long k1)
inner_result() [1/8]
template void inner_result (const Tensor< double > & left, const Tensor< double > & right, long k0, long k1, Tensor< TensorResultType< double, double >::type > & result)
inner_result() [2/8]
template void inner_result (const Tensor< double > & left, const Tensor< double_complex > & right, long k0, long k1, Tensor< TensorResultType< double, double_complex >::type > & result)
inner_result() [3/8]
template void inner_result (const Tensor< double_complex > & left, const Tensor< double > & right, long k0, long k1, Tensor< TensorResultType< double_complex, double >::type > & result)
inner_result() [4/8]
template void inner_result (const Tensor< double_complex > & left, const Tensor< double_complex > & right, long k0, long k1, Tensor< TensorResultType< double_complex, double_complex >::type > & result)
inner_result() [5/8]
template void inner_result (const Tensor< float > & left, const Tensor< float > & right, long k0, long k1, Tensor< TensorResultType< float, float >::type > & result)
inner_result() [6/8]
template void inner_result (const Tensor< float > & left, const Tensor< float_complex > & right, long k0, long k1, Tensor< TensorResultType< float, float_complex >::type > & result)
inner_result() [7/8]
template void inner_result (const Tensor< float_complex > & left, const Tensor< float > & right, long k0, long k1, Tensor< TensorResultType< float_complex, float >::type > & result)
inner_result() [8/8]
template void inner_result (const Tensor< float_complex > & left, const Tensor< float_complex > & right, long k0, long k1, Tensor< TensorResultType< float_complex, float_complex >::type > & result)
operator<<() [1/6]
template std::ostream & operator<< (std::ostream & s, const Tensor< double > & t)
operator<<() [2/6]
template std::ostream & operator<< (std::ostream & s, const Tensor< double_complex > & t)
operator<<() [3/6]
template std::ostream & operator<< (std::ostream & s, const Tensor< float > & t)
operator<<() [4/6]
template std::ostream & operator<< (std::ostream & s, const Tensor< float_complex > & t)
operator<<() [5/6]
template std::ostream & operator<< (std::ostream & s, const Tensor< int > & t)
operator<<() [6/6]
template std::ostream & operator<< (std::ostream & s, const Tensor< long > & t)
outer() [1/6]
template Tensor< double > outer (const Tensor< double > & left, const Tensor< double > & right)
outer() [2/6]
template Tensor< double_complex > outer (const Tensor< double_complex > & left, const Tensor< double_complex > & right)
outer() [3/6]
template Tensor< float > outer (const Tensor< float > & left, const Tensor< float > & right)
outer() [4/6]
template Tensor< float_complex > outer (const Tensor< float_complex > & left, const Tensor< float_complex > & right)
outer() [5/6]
template Tensor< int > outer (const Tensor< int > & left, const Tensor< int > & right)
outer() [6/6]
template Tensor< long > outer (const Tensor< long > & left, const Tensor< long > & right)
real() [1/2]
template Tensor< Tensor< double_complex >::scalar_type > real (const Tensor< double_complex > & t)
real() [2/2]
template Tensor< Tensor< float_complex >::scalar_type > real (const Tensor< float_complex > & t)
transform() [1/8]
template Tensor< TensorResultType< double, double >::type > transform (const Tensor< double > & t, const Tensor< double > & c)
transform() [2/8]
template Tensor< TensorResultType< double, double_complex >::type > transform (const Tensor< double > & t, const Tensor< double_complex > & c)
transform() [3/8]
template Tensor< TensorResultType< double_complex, double >::type > transform (const Tensor< double_complex > & t, const Tensor< double > & c)
transform() [4/8]
template Tensor< TensorResultType< double_complex, double_complex >::type > transform (const Tensor< double_complex > & t, const Tensor< double_complex > & c)
transform() [5/8]
template Tensor< TensorResultType< float, float >::type > transform (const Tensor< float > & t, const Tensor< float > & c)
transform() [6/8]
template Tensor< TensorResultType< float, float_complex >::type > transform (const Tensor< float > & t, const Tensor< float_complex > & c)
transform() [7/8]
template Tensor< TensorResultType< float_complex, float >::type > transform (const Tensor< float_complex > & t, const Tensor< float > & c)
transform() [8/8]
template Tensor< TensorResultType< float_complex, float_complex >::type > transform (const Tensor< float_complex > & t, const Tensor< float_complex > & c)
transpose() [1/6]
template Tensor< double > transpose (const Tensor< double > & t)
transpose() [2/6]
template Tensor< double_complex > transpose (const Tensor< double_complex > & t)
transpose() [3/6]
template Tensor< float > transpose (const Tensor< float > & t)
transpose() [4/6]
template Tensor< float_complex > transpose (const Tensor< float_complex > & t)
transpose() [5/6]
template Tensor< int > transpose (const Tensor< int > & t)
transpose() [6/6]
template Tensor< long > transpose (const Tensor< long > & t)