MADNESS: test_ccpairfunction.cc File Reference
test_ccpairfunction.cc File Reference
#include <madness/mra/mra.h>
#include <madness/chem/ccpairfunction.h>
#include <madness/chem/correlationfactor.h>
#include <madness/chem/electronic_correlation_factor.h>
#include <madness/chem/CCStructures.h>
#include <madness/chem/CCPotentials.h>
#include <madness/chem/projector.h>
#include <madness/world/test_utilities.h>
#include <random>
Classes
struct data< T, NDIM >
Functions
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
int test_apply (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_consolidate (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_constructor (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_inner (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameters)
template<typename T , std::size_t NDIM>
int test_load_store (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_multiply (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameters)
template<typename T , std::size_t NDIM>
int test_multiply_with_f12 (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameters)
template<typename T , std::size_t NDIM>
int test_norm (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_operator_apply (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_partial_inner_3d (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_partial_inner_6d (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_projector (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_scalar_multiplication (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
template<typename T , std::size_t NDIM>
int test_swap_particles (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameters)
template<typename T , std::size_t NDIM>
int test_transformations (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > &data, const CCParameters &parameter)
Variables
bool longtest =false
Function Documentation
main()
int main (int argc, char ** argv)
functionality
ctor OK
assignment OK
add
scalar multiplication OK
inner OK
inner_partial OK
swap_particles OK
apply
apply_partial (i.e. exchange)
serialize
collapse_to_pure (excl g!)
mul_partial
References madness::create_nuclear_correlation_factor(), e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, madness::commandlineparser::key_exists(), madness::print(), madness::Molecule::print(), madness::commandlineparser::print_map(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::commandlineparser::set_keyval(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, madness::TT_2D, and madness::commandlineparser::value().
test_apply()
template<typename T , std::size_t NDIM> int test_apply (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
f12: exp(-r_1^2 - 2 r_2^2) f23: exp(-r_1^2 - 2 r_2^2) + exp(-2 r_1^2 - 3 r_2^2) p1: pure, corresponds to f12 p2: dec, corresponds to f23 p3: op_dec, corresponds to f23 p4: pure, corresponds to f23 p5: op_pure, corresponds to f23
References madness::test_output::end(), madness::f, f1, f2, f3, data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), madness::inner(), NDIM, op(), madness::OT_F12, p(), madness::print(), and madness::r2().
test_consolidate()
template<typename T , std::size_t NDIM> int test_consolidate (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
f12: exp(-r_1^2 - 2 r_2^2) f23: exp(-r_1^2 - 2 r_2^2) + exp(-2 r_1^2 - 3 r_2^2) p1: pure, corresponds to f12 p2: dec, corresponds to f23 p3: op_dec, corresponds to f23 p4: pure, corresponds to f23 p5: op_pure, corresponds to f23
References c, madness::test_output::checkpoint(), madness::test_output::end(), data< T, NDIM >::get_ccpairfunctions(), madness::inner(), madness::is_collected(), m, NDIM, p(), madness::print(), and madness::r2().
test_constructor()
template<typename T , std::size_t NDIM> int test_constructor (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References a, a1, b, madness::test_output::checkpoint(), madness::CCPairFunction< T, NDIM >::component, madness::copy(), madness::test_output::end(), madness::f, f1, f2, f3, data< T, NDIM >::get_functions(), madness::CCPairFunction< T, NDIM >::is_decomposed(), madness::CCPairFunction< T, NDIM >::is_op_decomposed(), madness::CCPairFunction< T, NDIM >::is_pure(), MADNESS_CHECK, NDIM, op(), madness::OT_F12, p(), and madness::CCPairFunction< T, NDIM >::pure().
test_inner()
template<typename T , std::size_t NDIM> int test_inner (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameters)
f1: exp(-1.0 r^2) f2: exp(-2.0 r^2) f3: exp(-3.0 r^2) f4: exp(-4.0 r^2) f5: exp(-5.0 r^2) f: exp(-r_1^2 - 2 r_2^2) f23: exp(-r_1^2 - 2 r_2^2) + exp(-2 r_1^2 - 3 r_2^2)
p1: pure, corresponds to f12 p2: dec, corresponds to f23 p3: op_dec, corresponds to f23 p4: pure, corresponds to f23 p5: op_pure, corresponds to f23
results
References a, madness::apply(), b, madness::test_output::checkpoint(), madness::dot(), madness::test_output::end(), madness::f, f1, data< T, NDIM >::f12_op, f2, f3, madness::CCParameters::gamma(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::CCParameters::lo(), madness::matrix_inner(), NDIM, madness::print(), thresh, and madness::CCParameters::thresh_bsh_3D().
test_load_store()
template<typename T , std::size_t NDIM> int test_load_store (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References madness::test_output::checkpoint(), diff(), madness::test_output::end(), f1, f2, f3, data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), madness::inner(), and NDIM.
test_multiply()
template<typename T , std::size_t NDIM> int test_multiply (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameters)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::f, f1, f2, f3, data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::multiply(), NDIM, p(), and thresh.
test_multiply_with_f12()
template<typename T , std::size_t NDIM> int test_multiply_with_f12 (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameters)
References madness::test_output::checkpoint(), madness::test_output::end(), data< T, NDIM >::f12_op, data< T, NDIM >::get_ccpairfunctions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), NDIM, madness::r2(), and thresh.
test_norm()
template<typename T , std::size_t NDIM> int test_norm (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References madness::test_output::checkpoint(), madness::test_output::end(), data< T, NDIM >::get_ccpairfunctions(), madness::inner(), NDIM, p(), and madness::print().
test_operator_apply()
template<typename T , std::size_t NDIM> int test_operator_apply (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References madness::test_output::checkpoint(), madness::test_output::end(), f1, data< T, NDIM >::f12_op, f2, f3, madness::FunctionFactory< T, NDIM >::functor(), data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), madness::inner(), NDIM, p(), and madness::print().
test_partial_inner_3d()
template<typename T , std::size_t NDIM> int test_partial_inner_3d (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References a, aa, b, madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::f, f1, f2, f3, data< T, NDIM >::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), NDIM, norm(), madness::OT_F12, madness::print(), and thresh.
test_partial_inner_6d()
template<typename T , std::size_t NDIM> int test_partial_inner_6d (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References a, b, madness::test_output::checkpoint(), madness::CCPairFunction< T, NDIM >::convert_to_pure_no_op_inplace(), madness::test_output::end(), madness::f, f1, f2, f3, data< T, NDIM >::get_ccpairfunctions(), data< T, NDIM >::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), longtest, madness::CCPairFunction< T, NDIM >::name(), NDIM, madness::OT_F12, madness::print(), and madness::r2().
test_projector()
template<typename T , std::size_t NDIM> int test_projector (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References a, aa, b, madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::f, f1, f2, f3, data< T, NDIM >::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::matrix_inner(), NDIM, madness::OT_F12, p(), madness::print(), Q(), madness::ProjectorBase::set_particle(), madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces(), and thresh.
test_scalar_multiplication()
template<typename T , std::size_t NDIM> int test_scalar_multiplication (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References a, b, madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::f, f1, f2, f3, madness::CCPairFunction< T, NDIM >::get_a(), madness::CCPairFunction< T, NDIM >::get_b(), data< T, NDIM >::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), NDIM, madness::norm2(), p(), and madness::print().
test_swap_particles()
template<typename T , std::size_t NDIM> int test_swap_particles (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameters)
References a, std::abs(), b, madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::FunctionFactory< T, NDIM >::f(), madness::f, f1, f2, f3, madness::CCPairFunction< T, NDIM >::get_function(), data< T, NDIM >::get_functions(), madness::inner(), madness::matrix_inner(), NDIM, madness::norm2(), one(), p(), madness::print(), R2, and madness::CCPairFunction< T, NDIM >::swap_particles().
test_transformations()
template<typename T , std::size_t NDIM> int test_transformations (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, data< T, NDIM > & data, const CCParameters & parameter)
References madness::test_output::checkpoint(), madness::CCPairFunction< T, NDIM >::convert_to_pure_no_op_inplace(), madness::copy(), diff(), madness::test_output::end(), f1, f2, f3, data< T, NDIM >::get_functions(), madness::inner(), madness::CCPairFunction< T, NDIM >::is_convertible_to_pure_no_op(), madness::CCPairFunction< T, NDIM >::is_op_decomposed(), madness::CCPairFunction< T, NDIM >::is_op_pure(), madness::CCPairFunction< T, NDIM >::is_pure(), madness::CCPairFunction< T, NDIM >::is_pure_no_op(), NDIM, madness::OT_F12, and madness::OT_G12.
Variable Documentation
longtest
bool longtest =false
Referenced by main(), and test_partial_inner_6d().