MADNESS: test_dft.cc File Reference
test_dft.cc File Reference
#include <madness.h>
#include <madness/chem/SCFOperators.h>
Functions
bool check_err (double err, double thresh, std::string msg)
int main (int argc, char **argv)
double slater (const coord_3d &xyz)
double slater2 (const coord_3d &xyz)
int test_slater_exchange (World &world)
test the Slater exchange potential and the kernel
Variables
static double alpha =10.0
Function Documentation
check_err()
bool check_err (double err, double thresh, std::string msg)
References madness::nonlinear_vector_solver(), madness::print(), and thresh.
Referenced by madness::exchange_anchor_test(), and test_slater_exchange().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and test_slater_exchange().
slater()
double slater (const coord_3d & xyz)
References alpha, and madness::nonlinear_vector_solver().
slater2()
double slater2 (const coord_3d & xyz)
References madness::nonlinear_vector_solver().
Referenced by test_combined_operators(), and test_slater_exchange().
test_slater_exchange()
int test_slater_exchange (World & world)
test the Slater exchange potential and the kernel
The Slater exchange is a simple function of rho,
with
and
References std::abs(), check_err(), madness::copy(), energy, madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::nonlinear_vector_solver(), potential(), madness::print(), slater2(), thresh, and xc.
Referenced by main().
Variable Documentation
alpha
double alpha =10.0 static
Referenced by slater().