MADNESS: test_projector.cc File Reference
test_projector.cc File Reference
#include <madness/mra/mra.h>
#include <madness/chem/projector.h>
#include <madness/world/test_utilities.h>
Functions
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
int test_projector (World &world)
template<typename T , std::size_t NDIM>
int test_projector_outer (World &world)
template<typename T , std::size_t NDIM>
int test_Q12_projector (World &world)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, HAVE_GENTENSOR, madness::initialize(), k, madness::commandlineparser::key_exists(), L, madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, and madness::commandlineparser::value().
test_projector()
template<typename T , std::size_t NDIM> int test_projector (World & world)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::f, f1, f2, madness::FunctionFactory< T, NDIM >::functor(), g1(), madness::inner(), madness::matrix_inner(), NDIM, madness::norm2(), madness::orthonormalize_symmetric(), madness::print(), madness::FunctionDefaults< NDIM >::set_tensor_type(), and madness::TT_FULL.
test_projector_outer()
template<typename T , std::size_t NDIM> int test_projector_outer (World & world)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::FunctionFactory< T, NDIM >::f(), f1, g1(), madness::inner(), NDIM, madness::norm2(), madness::outer(), madness::print(), q(), madness::Q2(), and madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces().
test_Q12_projector()
template<typename T , std::size_t NDIM> int test_Q12_projector (World & world)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::f, f1, f2, f3, madness::FunctionFactory< T, NDIM >::functor(), g1(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), NDIM, madness::norm2(), madness::orthonormalize_symmetric(), madness::print(), madness::test_output::set_cout_to_terminal(), madness::ProjectorBase::set_particle(), madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces(), madness::FunctionDefaults< NDIM >::set_tensor_type(), thresh, madness::TT_2D, and madness::TT_FULL.