MADNESS: testinnerext.cc File Reference
testinnerext.cc File Reference
#include <madness/mra/mra.h>
#include <array>
Classes
class alpha_functor
class beta_functor
struct gauss< T, NDIM >
struct gauss_1d
Macros
#define END_TIMER(msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %-20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
Typedefs
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
Functions
static double alpha_func (const coord_3d &r)
static double beta_func (const coord_3d &r)
template<std::size_t NDIM>
void initialize (World &world)
bool is_like (double a, double b, double tol)
int main (int argc, char **argv)
bool test (std::string msg, double a, double b, double tol=thresh)
bool test_loose1 (std::string msg, double a, double b, double tol=thresh)
int test_partial_inner (World &world)
int test_tight_diffuse (World &world)
Variables
static const long k = 6
static const double L = 5.0*R
static const double R = 1.4
bool smalltest = true
double sss
static const double thresh = 1e-6
double ttt
Macro Definition Documentation
END_TIMER
#define END_TIMER (msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %-20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
START_TIMER
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
Typedef Documentation
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
Function Documentation
alpha_func()
static double alpha_func (const coord_3d & r) static
Referenced by main().
beta_func()
static double beta_func (const coord_3d & r) static
Referenced by main().
initialize()
template<std::size_t NDIM> void initialize (World & world)
References k, L, madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_defaults(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), and thresh.
Referenced by main().
is_like()
bool is_like (double a, double b, double tol)
References a, std::abs(), and b.
Referenced by main().
main()
int main (int argc, char ** argv)
References aa, alpha, alpha1, alpha_func(), beta, beta_func(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::Function< T, NDIM >::inner_ext(), is_like(), madness::print(), madness::World::rank(), smalltest, madness::START_TIMER(), madness::startup(), test_partial_inner(), test_tight_diffuse(), and thresh.
test()
bool test (std::string msg, double a, double b, double tol = thresh)
References a, std::abs(), b, ok(), and madness::print().
Referenced by test_loose1(), test_partial_inner(), and test_tight_diffuse().
test_loose1()
bool test_loose1 (std::string msg, double a, double b, double tol = thresh)
References a, b, and test().
Referenced by test_partial_inner().
test_partial_inner()
int test_partial_inner (World & world)
References madness::abs(), madness::cpu_time(), f2, f3, madness::hartree_product(), madness::inner(), MADNESS_CHECK, madness::print(), madness::Function< T, NDIM >::project_out(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), test(), test_loose1(), madness::TT_2D, and madness::TT_FULL.
Referenced by main().
test_tight_diffuse()
int test_tight_diffuse (World & world)
References a, aa, b, cc, madness::copy(), madness::inner(), MADNESS_CHECK, madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::constants::pi, pow(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::FunctionDefaults< NDIM >::set_thresh(), and test().
Referenced by main().
Variable Documentation
k
const long k = 6 static
Referenced by initialize().
L
const double L = 5.0*R static
Referenced by initialize().
R
const double R = 1.4 static
smalltest
bool smalltest = true
Referenced by main().
sss
double sss
thresh
const double thresh = 1e-6 static
Referenced by initialize(), and main().
ttt
double ttt