MADNESS: test_worldprofile.cc File Reference
test_worldprofile.cc File Reference
#include <madness/world/MADworld.h>
Functions
void dave (int i)
void fred (int i)
int main (int argc, char **argv)
void realmain (int argc, char **argv)
Function Documentation
dave()
void dave (int i)
References PROFILE_BLOCK, and PROFILE_FUNC.
Referenced by fred(), test5(), and Test7().
fred()
void fred (int i)
References dave(), and PROFILE_FUNC.
Referenced by realmain().
main()
int main (int argc, char ** argv)
References madness::finalize(), madness::initialize(), and realmain().
realmain()
void realmain (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), fred(), madness::World::gop, and madness::WorldProfile::print().
Referenced by main().