MADNESS: test_prof.cc File Reference
test_prof.cc File Reference
#include <madness/world/MADworld.h>
#include <cmath>
#include <cstdio>
Classes
class A
Functions
void a ()
void b ()
int main (int argc, char **argv)
Function Documentation
a()
void a ()
References b(), PROFILE_FUNC, and madness::sum().
Referenced by b(), and main().
b()
void b ()
References a(), PROFILE_FUNC, and madness::sum().
Referenced by a().
main()
int main (int argc, char ** argv)
References a(), madness::World::args(), SafeMPI::COMM_WORLD, madness::finalize(), madness::initialize(), madness::main(), madness::print_stats(), PROFILE_BLOCK, and madness::sum().