MADNESS: test_dc.cc File Reference
test_dc.cc File Reference
#include <algorithm>
#include <madness/world/MADworld.h>
#include <madness/world/worlddc.h>
#include <madness/world/worldmutex.h>
#include <madness/world/atomicint.h>
#include <madness/world/vector_archive.h>
#include <madness/world/parallel_archive.h>
Classes
class Double
struct Key
struct LargeNode
struct Node
class TestPmap
Functions
int main (int argc, char **argv)
ostream & operator<< (ostream &s, const Key &key)
ostream & operator<< (ostream &s, const Node &node)
void test0 (World &world)
void test1 (World &world)
void test_florian (World &world)
void test_local (World &world)
Variables
AtomicInt double_count
Function Documentation
main()
int main (int argc, char ** argv)
References e(), madness::error(), madness::finalize(), madness::initialize(), madness::print(), and test_florian().
operator<<() [1/2]
ostream & operator<< (ostream & s, const Key & key)
operator<<() [2/2]
ostream & operator<< (ostream & s, const Node & node)
References Node::k.
test0()
void test0 (World & world)
References c, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, and madness::World::rank().
test1()
void test1 (World & world)
References c, d, double_count, e(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, madness::print(), madness::World::rank(), and madness::WorldGopInterface::sum().
test_florian()
void test_florian (World & world)
References c, madness::WorldGopInterface::fence(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::World::gop, MADNESS_CHECK, madness::print(), madness::World::rank(), v, and madness::wall_time().
Referenced by main().
test_local()
void test_local (World & world)
References c, d, e(), madness::WorldGopInterface::fence(), madness::World::gop, madness::print(), and madness::World::rank().
Variable Documentation
double_count
AtomicInt double_count
Referenced by Double::Double(), Double::Double(), Double::~Double(), and test1().