MADNESS: test_qc.cc File Reference
test_qc.cc File Reference
#include <madness/mra/mra.h>
#include <madness/chem/CalculationParameters.h>
#include <madness/chem/SCF.h>
#include <madness/world/test_utilities.h>
Classes
class TestCalculationParameters
helper class to set up a vector of possible values for a given key
struct write_test_input
will write a test input and remove it from disk upon destruction
Functions
int main (int argc, char **argv)
int run_all_calculations (World &world, const std::vector< CalculationParameters > &all_parameters, bool test_result=false)
Function Documentation
main()
int main (int argc, char ** argv)
References e(), TestCalculationParameters::extend_parameters(), madness::finalize(), madness::initialize(), TestCalculationParameters::make_all_parameter_singles(), madness::print(), run_all_calculations(), madness::QCCalculationParametersBase::set_user_defined_value(), small, and madness::startup().
run_all_calculations()
int run_all_calculations (World & world, const std::vector< CalculationParameters > & all_parameters, bool test_result = false)
References std::abs(), madness::test_output::checkpoint(), e(), energy, write_test_input::filename(), madness::Tensor< T >::flat(), madness::Molecule::get_all_coords(), madness::SCF::molecule, madness::print(), madness::print_header2(), madness::test_output::set_cout_to_terminal(), madness::commandlineparser::set_keyval(), madness::SCF::set_protocol(), thresh, and madness::MolecularEnergy::value().
Referenced by main().