MADNESS: testopdir.cc File Reference
testopdir.cc File Reference
test different operators in different directions
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/funcplot.h>
#include <madness/constants.h>
#include <madness/world/test_utilities.h>
Classes
class Charge
class DPot
class Gaussian< T, NDIM >
class OpFExact
Functions
int main (int argc, char **argv)
template<std::size_t NDIM>
int test_combined_operators (World &world)
test the various operators following op_type
int test_opdir (World &world)
int testgradG (World &world)
Variables
bool smalltest = false
Detailed Description
test different operators in different directions
Function Documentation
main()
int main (int argc, char ** argv)
References e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), smalltest, madness::startup(), test_opdir(), and testgradG().
test_combined_operators()
template<std::size_t NDIM> int test_combined_operators (World & world)
test the various operators following op_type
References madness::arg(), madness::test_output::checkpoint(), madness::test_output::end(), madness::error(), madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), lo, mu, madness::Function< T, NDIM >::norm2(), madness::norm2(), op(), madness::OT_BSH, madness::OT_F12, madness::OT_F212, madness::OT_F2G12, madness::OT_FG12, madness::OT_G12, madness::OT_GAUSS, madness::OT_ONE, madness::OT_SIZE, madness::OT_SLATER, madness::constants::pi, madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), slater2(), thresh, and madness::type().
test_opdir()
int test_opdir (World & world)
References c, d, e(), madness::Function< T, NDIM >::err(), exact, madness::f, madness::WorldGopInterface::fence(), madness::FunctionDefaults< NDIM >::get_cell_width(), madness::FunctionDefaults< NDIM >::get_k(), madness::World::gop, k, m, norm(), madness::Function< T, NDIM >::norm2(), op(), madness::constants::pi, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), smalltest, madness::Function< T, NDIM >::trace(), and madness::Function< T, NDIM >::truncate().
Referenced by main().
testgradG()
int testgradG (World & world)
References d, e(), madness::Function< T, NDIM >::err(), madness::g, madness::GradCoulombOperator(), k, madness::print(), q(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), thresh, and madness::Function< T, NDIM >::trace().
Referenced by main().
Variable Documentation
smalltest
bool smalltest = false
Referenced by main(), and test_opdir().