MADNESS: test_tree_state.cc File Reference
test_tree_state.cc File Reference
#include <madness.h>
#include <test_utilities.h>
Functions
int main (int argc, char **argv)
int test_conversion (World &world)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::finalize(), madness::initialize(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and test_conversion().
test_conversion()
int test_conversion (World & world)
< s coeffs at the leaves only
< d coeffs in internal nodes, s and d coeffs at the root
< s and d coeffs in internal nodes
< like nonstandard, with s coeffs at the leaves
References a, std::abs(), madness::arg(), madness::change_tree_state(), madness::test_output::checkpoint(), madness::compressed, madness::copy(), madness::test_output::end(), madness::f, f1, f2, f3, madness::WorldGopInterface::fence(), madness::FunctionDefaults< NDIM >::get_k(), madness::get_tree_state(), madness::World::gop, madness::inner(), k, MADNESS_CHECK, MADNESS_CHECK_THROW, madness::nonstandard, madness::nonstandard_with_leaves, norm(), madness::norm2s(), madness::Vector< T, N >::normf(), ok(), madness::print(), madness::print_header2(), madness::reconstructed, madness::redundant, madness::redundant_after_merge, and madness::test_output::set_cout_to_terminal().
Referenced by main().