MADNESS: testgaxpyext.cc File Reference
testgaxpyext.cc File Reference
#include <madness/mra/mra.h>
Macros
#define END_TIMER(msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %-20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
Typedefs
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
Functions
static double alpha_func (const coord_3d &r)
static double beta_func (const coord_3d &r)
bool is_like (double a, double b, double tol)
int main (int argc, char **argv)
Variables
static const long k = 8
static const double L = 5.0*R
static const double R = 1.4
bool smalltest = false
double sss
static const double thresh = 1e-6
double ttt
Macro Definition Documentation
END_TIMER
#define END_TIMER (msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %-20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
START_TIMER
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
Typedef Documentation
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
Function Documentation
alpha_func()
static double alpha_func (const coord_3d & r) static
Referenced by main().
beta_func()
static double beta_func (const coord_3d & r) static
References a, and x0.
Referenced by main().
is_like()
bool is_like (double a, double b, double tol)
References a, std::abs(), and b.
Referenced by main().
main()
int main (int argc, char ** argv)
References alpha1, alpha_func(), beta, beta_func(), SafeMPI::COMM_WORLD, e(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::finalize(), madness::Function< T, NDIM >::gaxpy_ext(), madness::World::gop, madness::initialize(), is_like(), k, L, madness::Function< T, NDIM >::norm2(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_defaults(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), smalltest, madness::START_TIMER(), madness::startup(), and thresh.
Variable Documentation
k
const long k = 8 static
Referenced by main().
L
const double L = 5.0*R static
Referenced by main().
R
const double R = 1.4 static
smalltest
bool smalltest = false
Referenced by main().
sss
double sss
thresh
const double thresh = 1e-6 static
Referenced by main().
ttt
double ttt