MADNESS: test6.cc File Reference
test6.cc File Reference
test various functionality for 6d functions
#include <madness/mra/mra.h>
#include <madness/world/test_utilities.h>
Functions
int check (bool b, const std::string message)
int check_small (const double val, const double eps, const std::string message)
static double gauss_3d (const coord_3d &r)
static double gauss_plus_one_3d (const coord_3d &r)
static double gauss_plus_tight_3d (const coord_3d &r)
bool is_large (const double &val, const double &eps)
bool is_small (const double &val, const double &eps)
template<size_t NDIM>
void load_function (World &world, Function< double, NDIM > &pair, const std::string name)
int main (int argc, char **argv)
std::string ok (const bool b)
static double one_3d (const coord_3d &r)
static double one_6d (const coord_6d &r)
template<size_t NDIM>
void save_function (World &world, Function< double, NDIM > &pair, const std::string name)
int test (World &world, const long &k, const double thresh)
int test_add (World &world, const long &k, const double thresh)
test f(1,2) + g(1,2) for both f and g reconstructed
int test_convolution (World &world, const long &k, const double thresh)
test 6D convolution
int test_exchange (World &world, const long &k, const double thresh)
test f(1,2) + g(1,2) for both f and g reconstructed
template<typename T , std::size_t NDIM>
int test_hartree_product (World &world, const long &k, const double thresh)
test f(1,2) = g(1) h(2)
int test_inner (World &world, const long &k, const double thresh)
test inner product using redundant wave functions
template<typename T , std::size_t NDIM>
int test_multiply (World &world, const long &k, double thresh)
test f(1,2)*g(1)
int test_replicate (World &world, const long &k, const double thresh)
template<typename T , std::size_t NDIM>
int test_vector_composite (World &world, const long &k, const double thresh)
static double tightgauss_3d (const coord_3d &r)
static double V (const Vector< double, 3 > &r)
static double zero_3d (const coord_3d &r)
Detailed Description
test various functionality for 6d functions
Function Documentation
check()
int check (bool b, const std::string message)
References b, ok(), and madness::print().
Referenced by test_add().
check_small()
int check_small (const double val, const double eps, const std::string message)
References is_small(), ok(), and madness::print().
Referenced by test_add().
gauss_3d()
static double gauss_3d (const coord_3d & r) static
References norm(), and madness::r2().
Referenced by gauss_plus_one_3d(), gauss_plus_tight_3d(), test(), test_add(), test_convolution(), test_exchange(), test_inner(), and test_replicate().
gauss_plus_one_3d()
static double gauss_plus_one_3d (const coord_3d & r) static
References gauss_3d(), and one_3d().
Referenced by test_add().
gauss_plus_tight_3d()
static double gauss_plus_tight_3d (const coord_3d & r) static
References gauss_3d(), and tightgauss_3d().
Referenced by test_add().
is_large()
bool is_large (const double & val, const double & eps)
is_small()
bool is_small (const double & val, const double & eps)
Referenced by check_small(), madness::Convolution1D< Q >::get_issmall(), test_convolution(), test_exchange(), test_hartree_product(), and test_inner().
load_function()
template<size_t NDIM> void load_function (World & world, Function< double, NDIM > & pair, const std::string name)
References madness::Function< T, NDIM >::k(), madness::name(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::Function< T, NDIM >::thresh().
main()
int main (int argc, char ** argv)
References madness::arg(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, MADNESS_EXCEPTION, ok(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), test_add(), test_convolution(), madness::test_exchange(), test_inner(), test_replicate(), thresh, madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
ok()
std::string ok (const bool b)
References b.
Referenced by check(), check(), check_small(), madness::ensure_tree_state_respecting_fence(), madness::QCCalculationParametersBase::from_json(), main(), test(), test_apply_push_1d(), test_basic(), test_conv(), test_conversion(), test_convolution(), test_coulomb(), test_diff(), test_exchange(), test_inner(), test_io(), test_math(), test_op(), test_plot(), test_qm(), madness::WorldAmInterface::SendReq::TestAndFree(), and testbsh().
one_3d()
static double one_3d (const coord_3d & r) static
Referenced by gauss_plus_one_3d(), and test_add().
one_6d()
static double one_6d (const coord_6d & r) static
Referenced by test_add().
save_function()
template<size_t NDIM> void save_function (World & world, Function< double, NDIM > & pair, const std::string name)
References madness::name(), madness::print(), madness::Function< T, NDIM >::print_size(), and madness::World::rank().
test()
int test (World & world, const long & k, const double thresh)
References diff(), madness::error(), madness::GenTensor< T >::full_tensor_copy(), gauss_3d(), madness::hartree_product(), ij(), madness::print(), and s0.
test_add()
int test_add (World & world, const long & k, const double thresh)
test f(1,2) + g(1,2) for both f and g reconstructed
References madness::Function< T, NDIM >::add_scalar(), check(), check_small(), madness::Function< T, NDIM >::compress(), madness::copy(), madness::Function< T, NDIM >::err(), madness::error(), madness::FunctionFactory< T, NDIM >::f(), madness::f, gauss_3d(), gauss_plus_one_3d(), gauss_plus_tight_3d(), madness::gaxpy_oop(), madness::gaxpy_oop_reconstructed(), madness::hartree_product(), madness::Function< T, NDIM >::is_compressed(), madness::Function< T, NDIM >::norm2(), madness::norm2(), one_3d(), one_6d(), madness::print(), madness::r2(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::scale(), thresh, tightgauss_3d(), and zero_3d().
Referenced by main().
test_convolution()
int test_convolution (World & world, const long & k, const double thresh)
test 6D convolution
References a, madness::copy(), diff(), madness::WorldGopInterface::fence(), gauss_3d(), madness::World::gop, madness::hartree_product(), madness::inner(), is_small(), norm(), madness::Function< T, NDIM >::norm2(), ok(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::World::rank(), thresh, v, and V().
Referenced by main().
test_exchange()
int test_exchange (World & world, const long & k, const double thresh)
test f(1,2) + g(1,2) for both f and g reconstructed
References madness::CoulombOperator(), diff(), madness::f, f2, gauss_3d(), madness::hartree_product(), is_small(), madness::multiply(), norm(), madness::Function< T, NDIM >::norm2(), ok(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::World::rank(), and thresh.
test_hartree_product()
template<typename T , std::size_t NDIM> int test_hartree_product (World & world, const long & k, const double thresh)
test f(1,2) = g(1) h(2)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::FunctionFactory< T, NDIM >::f(), madness::hartree_product(), ij(), madness::inner(), is_small(), NDIM, madness::print(), madness::r2(), madness::FunctionDefaults< NDIM >::set_tensor_type(), thresh, madness::TT_2D, and madness::TT_FULL.
test_inner()
int test_inner (World & world, const long & k, const double thresh)
test inner product using redundant wave functions
References a1, a2, f1, f2, gauss_3d(), madness::hartree_product(), madness::inner(), is_small(), norm(), ok(), madness::print(), madness::World::rank(), and thresh.
Referenced by main().
test_multiply()
template<typename T , std::size_t NDIM> int test_multiply (World & world, const long & k, double thresh)
test f(1,2)*g(1)
Slater factor
References madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::FunctionFactory< T, NDIM >::f(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::FunctionFactory< T, NDIM >::is_on_demand(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), madness::multiply(), NDIM, madness::norm2(), madness::Vector< T, N >::normf(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::Function< T, NDIM >::print_size(), madness::r2(), madness::test_output::set_cout_to_terminal(), madness::FunctionDefaults< NDIM >::set_tensor_type(), thresh, madness::Function< T, NDIM >::truncate(), madness::TT_2D, madness::TT_FULL, madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), and madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2().
test_replicate()
int test_replicate (World & world, const long & k, const double thresh)
References madness::Function< T, NDIM >::distribute(), gauss_3d(), madness::Function< T, NDIM >::get_pmap(), and madness::Function< T, NDIM >::replicate().
Referenced by main().
test_vector_composite()
template<typename T , std::size_t NDIM> int test_vector_composite (World & world, const long & k, const double thresh)
test construction with a single pair of functions
test construction with a single pair of functions and eri
test construction with a vector of functions:
References std::abs(), madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::FunctionFactory< T, NDIM >::f(), madness::Function< T, NDIM >::fill_cuspy_tree(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::inner(), madness::FunctionFactory< T, NDIM >::is_on_demand(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), MADNESS_CHECK, NDIM, madness::Function< T, NDIM >::norm2(), madness::norm2(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::print(), madness::r2(), madness::FunctionDefaults< NDIM >::set_tensor_type(), thresh, and madness::TT_2D.
tightgauss_3d()
static double tightgauss_3d (const coord_3d & r) static
References norm(), and madness::r2().
Referenced by gauss_plus_tight_3d(), and test_add().
V()
static double V (const Vector< double, 3 > & r) static
References e().
Referenced by test_convolution().
zero_3d()
static double zero_3d (const coord_3d & r) static
Referenced by test_add().