MADNESS: testper.cc File Reference
testper.cc File Reference
test the periodic convolution operator
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Typedefs
typedef Vector< double, 1 > coordT
Functions
double constant (const coordT &x)
int main (int argc, char **argv)
double q (double x, double a)
int test_per (World &world)
Detailed Description
test the periodic convolution operator
Typedef Documentation
coordT
typedef Vector<double,1> coordT
Function Documentation
constant()
double constant (const coordT & x)
Referenced by slymer::PolynomialCoeffs::PolynomialCoeffs(), and test_per().
main()
int main (int argc, char ** argv)
References e(), madness::error(), madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::startup(), and test_per().
q()
double q (double x, double a)
References a.
Referenced by test_per().
test_per()
int test_per (World & world)
References madness::apply(), constant(), e(), madness::error(), madness::FunctionFactory< T, NDIM >::f(), madness::f, madness::FunctionFactory< T, NDIM >::initial_level(), k, lo, madness::FunctionFactory< T, NDIM >::norefine(), op(), madness::constants::pi, madness::print(), q(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), and thresh.
Referenced by main().