MADNESS: testperiodicdft.cc File Reference
testperiodicdft.cc File Reference
#include <madness/mra/mra.h>
#include <madness/tensor/solvers.h>
#include <madness/chem/molecule.h>
#include <madness/chem/molecularbasis.h>
#include <madness/chem/xcfunctional.h>
#include "subspace.h"
Classes
class AtomicBasisFunctor< Q >
class AtomicOrbitalFunctor
class ExpFunctor< Q >
class ExpFunctor3d< Q >
class KPeriodicBSHOperator
class MolecularGuessDensityFunctor
class NuclearDensityFunctor
class SplitterFunctor
Typedefs
typedef SeparatedConvolution< double_complex, 3 > coperatorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::shared_ptr< coperatorT > pcoperatorT
typedef std::shared_ptr< operatorT> poperatorT
typedef std::pair< vector_complex_function_3d, vector_complex_function_3d > vcpairT
Functions
complex_function_3d apply_periodic_bsh (World &world, const complex_function_3d &f, const double &kx, const double &ky, const double &kz, const double &energy, const double &L)
complex_function_3d apply_periodic_bsh (World &world, const complex_function_3d &f, const Vector< double, 3 > &kpt, const double &energy, const double &L)
vector_complex_function_3d apply_potential (World &world, const real_function_3d &potential, const vector_complex_function_3d &psi)
std::pair< vector_complex_function_3d, tensor_real > diag_and_transform (World &world, const Vector< double, 3 > kpt, const real_function_3d &v, const vector_complex_function_3d &psik, int nmo=0)
static void END_TIMER (World &world, const char *msg)
void fixphases (World &world, tensor_real &e, tensor_complex &U)
void fixphases (World &world, tensor_real &e, tensor_complex &U, vector_complex_function_3d &psik)
static const double_complex I (0, 1)
vector_complex_function_3d initial_guess (World &world, const real_function_3d &vnuc, real_function_3d &rho, const std::vector< Vector< double, 3 > > &kpoints, int nst)
int main (int argc, char **argv)
vector< poperatorT > make_bsh_operators (World &world, const tensor_real &evals, double shift)
real_function_3d make_coulomb_potential (World &world, const real_function_3d &rho)
real_function_3d make_density (World &world, const vector_complex_function_3d &v, double weight)
tensor_complex make_kinetic_matrix (World &world, const vector_complex_function_3d &v, const Vector< double, 3 > &kpt)
real_function_3d make_lda_potential (World &world, const real_function_3d &rho)
vector_complex_function_3d makeao (World &world, const std::vector< Vector< double, 3 > > &kpts, double R)
vector_complex_function_3d makeao_slow (World &world, const std::vector< Vector< double, 3 > > &kpoints)
tensor_complex matrix_exponential (const tensor_complex &A)
vector_complex_function_3d orth (World &world, const vector_complex_function_3d &v, double thresh=1.e-10)
void orthogonalize (World &world, vector_complex_function_3d &psi)
static void START_TIMER (World &world)
vcpairT update (World &world, int ik, const vector_complex_function_3d &psi, vector_complex_function_3d &vpsi, const Vector< double, 3 > &kpt, const real_function_3d &v, const tensor_real &e)
Variables
static AtomicBasisSet aobasis
static const double kwavelet = 14
static const double L = 10.6591
static const int maxR = 3
static Molecule molecule
static double sss
static Subspace * subspace
static const double thresh = 1e-5
static const int truncate_mode = 0
static double ttt
static const double twopi = 2.0*constants::pi
Typedef Documentation
coperatorT
typedef SeparatedConvolution<double_complex,3> coperatorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pcoperatorT
typedef std::shared_ptr<coperatorT> pcoperatorT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
vcpairT
typedef std::pair<vector_complex_function_3d,vector_complex_function_3d> vcpairT
Function Documentation
apply_periodic_bsh() [1/2]
complex_function_3d apply_periodic_bsh (World & world, const complex_function_3d & f, const double & kx, const double & ky, const double & kz, const double & energy, const double & L)
References madness::apply(), e(), energy, madness::f, madness::g, I(), kx, ky, kz, L, op(), madness::PeriodicBSHOperator3D(), and madness::vec().
Referenced by apply_periodic_bsh().
apply_periodic_bsh() [2/2]
complex_function_3d apply_periodic_bsh (World & world, const complex_function_3d & f, const Vector< double, 3 > & kpt, const double & energy, const double & L)
References apply_periodic_bsh(), energy, madness::f, and L.
apply_potential()
vector_complex_function_3d apply_potential (World & world, const real_function_3d & potential, const vector_complex_function_3d & psi)
References madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::World::gop, madness::mul(), potential(), psi(), and madness::START_TIMER().
Referenced by diag_and_transform(), initial_guess(), and main().
diag_and_transform()
std::pair<vector_complex_function_3d, tensor_real> diag_and_transform (World & world, const Vector< double, 3 > kpt, const real_function_3d & v, const vector_complex_function_3d & psik, int nmo = 0)
References madness::_(), std::abs(), apply_potential(), c, madness::copy(), e(), make_kinetic_matrix(), madness::matrix_inner(), madness::sygv(), thresh, madness::transform(), and v.
END_TIMER()
static void END_TIMER (World & world, const char * msg) static
References madness::cpu_time(), madness::World::rank(), madness::sss, madness::ttt, and madness::wall_time().
fixphases() [1/2]
void fixphases (World & world, tensor_real & e, tensor_complex & U)
References madness::_(), madness::Tensor< T >::absmax(), madness::arg(), madness::conj_transpose(), madness::copy(), madness::BaseTensor::dim(), e(), I(), madness::inner(), matrix_exponential(), max, madness::phase(), madness::print(), q(), madness::World::rank(), madness::rot(), and thresh.
Referenced by main().
fixphases() [2/2]
void fixphases (World & world, tensor_real & e, tensor_complex & U, vector_complex_function_3d & psik)
References madness::_(), madness::Tensor< T >::absmax(), madness::arg(), madness::BaseTensor::dim(), e(), I(), madness::matrix_inner(), max, madness::mul(), madness::phase(), madness::print(), madness::World::rank(), madness::syev(), thresh, and madness::transform().
I()
static const double_complex I (0 , 1) static
Referenced by KPeriodicBSHOperator::KPeriodicBSHOperator(), apply_periodic_bsh(), fixphases(), make_kinetic_matrix(), makeao(), and AtomicBasisFunctor< Q >::operator()().
initial_guess()
vector_complex_function_3d initial_guess (World & world, const real_function_3d & vnuc, real_function_3d & rho, const std::vector< Vector< double, 3 > > & kpoints, int nst)
References std::abs(), apply_potential(), c, e(), L, MADNESS_CHECK, make_coulomb_potential(), make_density(), make_kinetic_matrix(), make_lda_potential(), makeao(), madness::matrix_inner(), madness::print(), psi(), psi0(), madness::World::rank(), madness::BaseTensor::size(), madness::sygv(), thresh, madness::transform(), madness::transpose(), v, vnuc(), and madness::weights.
Referenced by main().
main()
int main (int argc, char ** argv)
References std::abs(), madness::Molecule::add_atom(), aobasis, apply_potential(), madness::BC_PERIODIC, c, SafeMPI::COMM_WORLD, e(), fixphases(), madness::gaxpy(), initial_guess(), madness::initialize(), kwavelet, L, MADNESS_CHECK, make_coulomb_potential(), make_density(), make_kinetic_matrix(), make_lda_potential(), madness::matrix_inner(), molecule, madness::norm2(), orthogonalize(), madness::print(), madness::project(), psi(), madness::World::rank(), madness::AtomicBasisSet::read_file(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), subspace, madness::sygv(), thresh, madness::Molecule::total_nuclear_charge(), madness::Function< T, NDIM >::trace(), madness::transform(), madness::Function< T, NDIM >::truncate(), madness::truncate(), truncate_mode, twopi, update(), madness::Molecule::update_rcut_with_eprec(), v, madness::vec(), vnuc(), and weight().
make_bsh_operators()
vector<poperatorT> make_bsh_operators (World & world, const tensor_real & evals, double shift)
References madness::BSHOperatorPtr3D(), madness::BaseTensor::dim(), e(), shift, and thresh.
Referenced by madness::EigSolver< T, NDIM >::multi_solve(), and MiniDFT::update().
make_coulomb_potential()
real_function_3d make_coulomb_potential (World & world, const real_function_3d & rho)
References madness::CoulombOperator(), e(), madness::END_TIMER(), op(), madness::START_TIMER(), and thresh.
Referenced by MiniDFT::doit(), initial_guess(), and main().
make_density()
real_function_3d make_density (World & world, const vector_complex_function_3d & v, double weight)
References madness::abssq(), madness::END_TIMER(), madness::Function< T, NDIM >::scale(), madness::START_TIMER(), madness::Function< T, NDIM >::truncate(), v, and weight().
Referenced by MiniDFT::doit(), initial_guess(), and main().
make_kinetic_matrix()
tensor_complex make_kinetic_matrix (World & world, const vector_complex_function_3d & v, const Vector< double, 3 > & kpt)
References madness::apply(), madness::END_TIMER(), f1, f2, f3, I(), kx, ky, kz, madness::matrix_inner(), madness::START_TIMER(), and v.
Referenced by diag_and_transform(), initial_guess(), and main().
make_lda_potential()
real_function_3d make_lda_potential (World & world, const real_function_3d & rho)
References madness::copy(), madness::END_TIMER(), and madness::START_TIMER().
Referenced by MiniDFT::doit(), initial_guess(), and main().
makeao()
vector_complex_function_3d makeao (World & world, const std::vector< Vector< double, 3 > > & kpts, double R)
References aobasis, madness::Function< T, NDIM >::compress(), madness::END_TIMER(), madness::Function< T, NDIM >::gaxpy(), madness::AtomicBasisSet::get_atomic_basis_function(), I(), k, L, maxR, molecule, madness::AtomicBasisSet::nbf(), madness::print(), R, madness::World::rank(), and madness::START_TIMER().
Referenced by MiniDFT::doit(), and initial_guess().
makeao_slow()
vector_complex_function_3d makeao_slow (World & world, const std::vector< Vector< double, 3 > > & kpoints)
References aobasis, madness::WorldGopInterface::fence(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::World::gop, kx, ky, kz, molecule, madness::AtomicBasisSet::nbf(), madness::normalize(), madness::AtomicBasisFunction::print_me(), and madness::truncate().
matrix_exponential()
tensor_complex matrix_exponential (const tensor_complex & A)
References A(), B, madness::BaseTensor::dim(), e(), madness::inner(), k, MADNESS_CHECK, madness::Tensor< T >::normf(), madness::Tensor< T >::scale(), and madness::scale().
Referenced by fixphases().
orth()
vector_complex_function_3d orth (World & world, const vector_complex_function_3d & v, double thresh = 1.e-10)
References madness::_(), std::abs(), madness::copy(), e(), madness::matrix_inner(), madness::normalize(), madness::print(), R, madness::syev(), thresh, madness::transform(), and v.
orthogonalize()
void orthogonalize (World & world, vector_complex_function_3d & psi)
References madness::compress(), madness::END_TIMER(), madness::Function< T, NDIM >::gaxpy(), madness::inner(), madness::Function< T, NDIM >::norm2(), psi(), madness::Function< T, NDIM >::scale(), and madness::START_TIMER().
Referenced by main().
START_TIMER()
static void START_TIMER (World & world) static
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, madness::sss, madness::ttt, and madness::wall_time().
update()
vcpairT update (World & world, int ik, const vector_complex_function_3d & psi, vector_complex_function_3d & vpsi, const Vector< double, 3 > & kpt, const real_function_3d & v, const tensor_real & e)
References KPeriodicBSHOperator::apply(), e(), madness::gaxpy(), kx, ky, kz, L, psi(), madness::World::rank(), madness::scale(), shift, madness::sub(), and madness::truncate().
Referenced by main().
Variable Documentation
aobasis
AtomicBasisSet aobasis static
Referenced by MiniDFT::doit(), madness::Nemo::localize(), main(), MiniDFT::makeao(), makeao(), makeao_slow(), MolecularGuessDensityFunctor::operator()(), madness::MolecularOrbitals< T, NDIM >::read_restartaodata(), and madness::MolecularOrbitals< T, NDIM >::save_restartaodata().
kwavelet
const double kwavelet = 14 static
Referenced by main().
L
const double L = 10.6591 static
Referenced by KPeriodicBSHOperator::apply(), apply_periodic_bsh(), initial_guess(), main(), makeao(), MolecularGuessDensityFunctor::operator()(), AtomicBasisFunctor< Q >::operator()(), and update().
maxR
const int maxR = 3 static
Referenced by madness::apply(), makeao(), MolecularGuessDensityFunctor::operator()(), AtomicBasisFunctor< Q >::operator()(), and NuclearDensityFunctor::operator()().
molecule
Molecule molecule static
Referenced by GaussianNucleusFunctor::GaussianNucleusFunctor(), madness::Nuclear< T, NDIM >::Nuclear(), NuclearVector::NuclearVector(), madness::PNOParameters::PNOParameters(), madness::AtomicBasisSet::atoms_to_bfn(), madness::AtomicBasisSet::basisfn_to_atom(), compute_frequencies(), madness::NemoBase::compute_gradient(), madness::MP3::compute_mp3_ghij(), madness::MP3::compute_mp3_ghij_fast(), madness::MolecularOptimizer::compute_reduced_mass(), compute_reduced_mass(), madness::create_nuclear_correlation_factor(), madness::cubefile_header(), dipole_generator(), madness::do_response_orbital_vtk_plots(), madness::do_vtk_plots(), MiniDFT::doit(), madness::MolecularEnergy::energy_and_gradient(), madness::AtomicBasisSet::eval(), madness::AtomicBasisSet::eval_guess_density(), madness::AtomicBasisSet::get_aeps(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::AtomicBasisSet::get_avec(), madness::ACParameters< NDIM >::initialize(), initialize_calc_params(), madness::MolecularOrbitals< T, NDIM >::load_mos(), main(), madness::make_atom_vec(), MiniDFT::makeao(), makeao(), makeao_slow(), madness::AtomicBasisSet::nbf(), nuclear_generator(), MolecularGuessDensityFunctor::operator()(), madness::atomic_attraction::operator()(), madness::MP3::MacroTaskMP3::operator()(), NuclearDensityFunctor::operator()(), madness::SCF::output_calc_info_schema(), madness::TDHF::plot(), madness::AtomicBasisSet::print(), madness::AtomicBasisSet::print_anal(), madness::MolecularOrbitals< T, NDIM >::read_restartaodata(), madness::MolecularOrbitals< T, NDIM >::read_restartdata(), madness::MolecularOrbitals< T, NDIM >::save_restartaodata(), madness::MolecularOrbitals< T, NDIM >::save_restartdata(), madness::PNOParameters::set_derived_values(), madness::CalculationParameters::set_derived_values(), madness::ResponseParameters::set_derived_values(), madness::AtomicBasisSet::shells_to_bfn(), madness::atomic_attraction::special_points(), and madness::write_molecules_to_file().
sss
double sss static
subspace
Subspace* subspace static
Referenced by main(), madness::SCF::rotate_subspace(), madness::SCF::solve(), and madness::SCF::update_subspace().
thresh
const double thresh = 1e-5 static
Referenced by diag_and_transform(), fixphases(), initial_guess(), main(), make_bsh_operators(), make_coulomb_potential(), and orth().
truncate_mode
const int truncate_mode = 0 static
Referenced by main().
ttt
double ttt static
twopi
const double twopi = 2.0*constants::pi static
Referenced by main().