MADNESS: test_hashthreaded.cc File Reference
test_hashthreaded.cc File Reference
#include <madness/world/world.h>
#include <madness/world/thread.h>
#include <madness/world/worldhash.h>
#include <madness/world/worldhashmap.h>
#include <madness/world/range.h>
#include <madness/world/timers.h>
#include <madness/world/atomicint.h>
#include <iostream>
#include <ctime>
#include <cstdlib>
#include <cstdio>
#include <vector>
#include <algorithm>
Classes
class Peasant
class Worker
Functions
void do_test_random (ConcurrentHashMap< int, double > &a, size_t &count, double &sum)
double drand ()
void errmsg (const char *msg, int status)
int main (int argc, char **argv)
vector< int > random_perm (int n)
void split (const Range< ConcurrentHashMap< int, int >::iterator > &range)
void test_accessors ()
void test_coverage ()
void test_random ()
void test_thread ()
void test_time ()
Variables
madness::AtomicInt ndone
bool smalltest = false
Function Documentation
do_test_random()
void do_test_random (ConcurrentHashMap< int, double > & a, size_t & count, double & sum)
References a, drand(), and sum.
Referenced by Worker::run(), and test_random().
drand()
double drand ()
Referenced by do_test_random(), and random_perm().
errmsg()
void errmsg (const char * msg, int status)
References status.
Referenced by madness::QCCalculationParametersBase::fromstring(), madness::CCIntermediatePotentials::get_potential(), madness::SCF::load_mos(), madness::QCParameter::not_allowed_errmsg(), madness::position_stream(), madness::Molecule::position_stream_in_library(), madness::position_stream_to_word(), madness::Molecule::read_file(), madness::QCCalculationParametersBase::read_input(), madness::QCCalculationParametersBase::read_internal(), madness::QCCalculationParametersBase::read_quotes(), madness::Molecule::read_structure_from_library(), madness::Molecule::read_xyz(), test_not_allowed(), test_trailing_characters(), test_type_conversion3(), and test_type_conversion4().
main()
int main (int argc, char ** argv)
References madness::finalize(), madness::initialize(), smalltest, test_accessors(), test_coverage(), test_random(), test_thread(), and test_time().
random_perm()
vector< int > random_perm (int n)
References drand(), madness::swap(), and v.
Referenced by test_time().
split()
void split (const Range< ConcurrentHashMap< int, int >::iterator > & range)
References c, madness::Range< iteratorT >::size(), and split().
Referenced by madness::LRFunctorF12< T, NDIM, LDIM >::operator()(), madness::redirectio(), split(), and test_coverage().
test_accessors()
void test_accessors ()
References a, a1, a2, MADNESS_EXCEPTION, and ndone.
Referenced by main().
test_coverage()
void test_coverage ()
References a, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::begin(), std::distance(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), fit(), MADNESS_ASSERT, and split().
Referenced by main().
test_random()
void test_random ()
References a, do_test_random(), and sum.
Referenced by main().
test_thread()
void test_thread ()
References a, ndone, and sum.
Referenced by main().
test_time()
void test_time ()
References a, madness::cpu_time(), MADNESS_ASSERT, random_perm(), and v.
Referenced by main().
Variable Documentation
ndone
madness::AtomicInt ndone
Referenced by Worker::run(), Peasant::run(), test_accessors(), and test_thread().
smalltest
bool smalltest = false
Referenced by main().