MADNESS: test_list.cc File Reference
test_list.cc File Reference
#include <list>
#include <iostream>
#include <time.h>
#include <sys/time.h>
Functions
double cpu_time ()
int main ()
Function Documentation
cpu_time()
double cpu_time ()
Referenced by main(), main(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeRow::row(), and madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeRow::row_fetch_compute().
main()
int main (void)
References a, b, cpu_time(), and p().