MADNESS: testcomplexfunctionsolver.cc File Reference
testcomplexfunctionsolver.cc File Reference
#include <iostream>
#include <madness/mra/mra.h>
#include <madness/mra/nonlinsol.h>
#include <complex>
#include <cmath>
Classes
struct F
Typedefs
using dataT = std::complex< double >
using factoryT = FunctionFactory< dataT, N >
using functionT = Function< dataT, N >
Functions
F allocator ()
dataT inner (const F &a, const F &b)
int main (int argc, char **argv)
F residual (const F &f)
void residualx (const Key< N > &key, Tensor< dataT > &t)
Variables
const size_t N = 1
Typedef Documentation
dataT
using dataT = std::complex<double>
factoryT
using factoryT = FunctionFactory<dataT,N>
functionT
using functionT = Function<dataT,N>
Function Documentation
allocator()
F allocator ()
References F, and madness::World::get_default().
Referenced by madness::archive::ArchiveLoadImpl< Archive, std::list< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::map< T, Q, Compare, Alloc >, std::enable_if_t< is_serializable_v< Archive, T > &&is_serializable_v< Archive, Q > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::set< T, Compare, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< bool, Alloc > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< T, Alloc >, std::enable_if_t<!is_future< T >::value &&is_serializable_v< Archive, T > > >::load(), main(), run(), and DF::solve_occupied().
inner()
dataT inner (const F & a, const F & b)
References a, b, and madness::conj().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, F, madness::WorldGopInterface::fence(), madness::finalize(), F::get(), madness::World::gop, guess(), madness::initialize(), madness::Function< T, NDIM >::norm2(), residual(), and madness::startup().
residual()
F residual (const F & f)
References madness::copy(), F, madness::f, residualx(), and madness::Function< T, NDIM >::unaryop().
Referenced by madness::TDHF::apply_G(), madness::RandomizedMatrixDecomposition< T >::check_range(), madness::Zcis::compute_residuals(), madness::OEP::iterate(), iterate(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_singles(), main(), madness::SRConf< T >::max_sigma(), madness::ortho5(), SolverTargetInterface::residual_and_jacobian(), madness::Nemo::solve(), madness::CC2::solve_cc2(), madness::MP2::solve_coupled_equations(), madness::Nemo::solve_cphf(), madness::CC2::solve_mp2_coupled(), madness::MP2::solve_residual_equations(), test_converged_function(), and test_convergence().
residualx()
void residualx (const Key< N > & key, Tensor< dataT > & t)
References UNARY_OPTIMIZED_ITERATOR.
Referenced by residual().
Variable Documentation
N
const size_t N = 1