MADNESS: test_MolecularOrbitals.cc File Reference
test_MolecularOrbitals.cc File Reference
#include <madness/chem/MolecularOrbitals.h>
#include <madness/chem/SCF.h>
#include <madness/chem/write_test_input.h>
Functions
int compare_calc_and_mos (World &world, const SCF &calc, const MolecularOrbitals< double, 3 > &amo)
int main (int argc, char **argv)
int test_read_restartaodata (World &world)
int test_read_restartdata (World &world)
Function Documentation
compare_calc_and_mos()
int compare_calc_and_mos (World & world, const SCF & calc, const MolecularOrbitals< double, 3 > & amo)
References madness::SCF::aeps, madness::SCF::amo, madness::SCF::aocc, madness::SCF::aset, madness::MolecularOrbitals< T, NDIM >::get_eps(), madness::MolecularOrbitals< T, NDIM >::get_localize_sets(), madness::MolecularOrbitals< T, NDIM >::get_mos(), madness::MolecularOrbitals< T, NDIM >::get_occ(), madness::norm2(), and madness::print().
Referenced by test_read_restartdata().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::startup(), test_read_restartaodata(), and test_read_restartdata().
test_read_restartaodata()
int test_read_restartaodata (World & world)
References madness::SCF::aobasis, e(), madness::write_test_input::filename(), madness::Tensor< T >::flat(), madness::Molecule::get_all_coords(), madness::SCF::molecule, param, madness::SCF::param, InputParameters::prefix, madness::SCF::project_ao_basis_only(), madness::MolecularOrbitals< T, NDIM >::read_restartaodata(), madness::MolecularOrbitals< T, NDIM >::read_restartdata(), madness::MolecularOrbitals< T, NDIM >::save_restartaodata(), madness::commandlineparser::set_keyval(), madness::SCF::set_protocol(), madness::QCCalculationParametersBase::set_user_defined_value(), similar(), and madness::MolecularEnergy::value().
Referenced by main().
test_read_restartdata()
int test_read_restartdata (World & world)
References compare_calc_and_mos(), e(), madness::write_test_input::filename(), madness::Tensor< T >::flat(), madness::Molecule::get_all_coords(), madness::SCF::molecule, param, madness::SCF::param, InputParameters::prefix, madness::MolecularOrbitals< T, NDIM >::read_restartdata(), madness::commandlineparser::set_keyval(), madness::SCF::set_protocol(), madness::QCCalculationParametersBase::set_user_defined_value(), and madness::MolecularEnergy::value().
Referenced by main().