MADNESS: test_hello.cc File Reference
test_hello.cc File Reference
#include <iostream>
#include <madness/world/MADworld.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::finalize(), madness::initialize(), and madness::World::rank().