MADNESS: test_preliminaries.cpp File Reference
test_preliminaries.cpp File Reference
#include "../madqc/parameter_manager.hpp"
#include "GroundStateData.hpp"
#include "ResponseManager.hpp"
#include "madness/world/world.h"
#include <cassert>
#include <cmath>
#include <iostream>
#include <string>
#include <tensor_json.hpp>
Functions
bool approximately_equal (double computed, double reference, double tol=1e-6)
std::pair< Tensor< double >, Tensor< double > > get_fock_from_json (const json &fock_json, double thresh, int k, bool spinrestricted)
int main (int argc, char **argv)
bool tensor_approx_equal (World &world, const Tensor< double > &computed, const Tensor< double > &reference, double tol=1e-6, bool verbose=true)
Function Documentation
approximately_equal()
bool approximately_equal (double computed, double reference, double tol = 1e-6)
References std::abs().
get_fock_from_json()
std::pair< Tensor< double >, Tensor< double > > get_fock_from_json (const json & fock_json, double thresh, int k, bool spinrestricted)
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), get_fock_from_json(), madness::FunctionDefaults< NDIM >::get_k(), madness::World::gop, madness::initialize(), k, madness::FunctionDefaults< NDIM >::print(), madness::print(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::startup(), tensor_approx_equal(), and thresh.
tensor_approx_equal()
bool tensor_approx_equal (World & world, const Tensor< double > & computed, const Tensor< double > & reference, double tol = 1e-6, bool verbose = true)
References a, std::abs(), b, madness::BaseTensor::dims(), madness::Tensor< T >::flat(), madness::BaseTensor::ndim(), and madness::World::rank().
Referenced by main().