MADNESS: testsuite.cc File Reference
testsuite.cc File Reference
The QA/test suite for Function.
#include <madness/mra/mra.h>
#include <unistd.h>
#include <cstdio>
#include <madness/constants.h>
#include <madness/mra/qmprop.h>
#include <madness/misc/ran.h>
Classes
class BinaryOp< resultT, L, R, opT, NDIM >
Returns a new functor combining two functors via operation op(left,right)
class DerivativeGaussian< T, NDIM >
class Gaussian< T, NDIM >
class GaussianPotential
Computes the electrostatic potential due to a Gaussian charge distribution.
struct lbcost< T, NDIM >
struct myunaryop< T, NDIM >
struct myunaryop_square< T, NDIM >
class QMtest
struct refop
struct test_multiop< T, NDIM >
Namespaces
namespace madness
Namespace for all elements and tools of MADNESS.
Macros
#define CHECK(value, threshold, message)
#define END_TIMER(msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
#define NO_GENTENSOR
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Functions
template<typename T >
T complexify (T c)
template<>
double_complex complexify< double_complex > (double_complex c)
template<>
float_complex complexify< float_complex > (float_complex c)
int main (int argc, char **argv)
template<typename T , typename L , typename R >
T product (L l, R r)
template<typename T , std::size_t NDIM>
Gaussian< T, NDIM > * RandomGaussian (const Tensor< double > cell, double expntmax=1e5)
Makes a square-normalized Gaussian with random origin and exponent.
template<typename T , typename L , typename R >
T sum (L l, R r)
template<typename T , std::size_t NDIM>
int test_apply_push_1d (World &world)
template<typename T , std::size_t NDIM>
int test_basic (World &world)
template<typename T , std::size_t NDIM>
int test_conv (World &world)
test the convergence of the MRA representation with respect to k and n
int test_coulomb (World &world)
template<typename T , std::size_t NDIM>
int test_diff (World &world)
template<typename T , std::size_t NDIM>
int test_io (World &world)
template<typename T , std::size_t NDIM>
int test_math (World &world)
template<typename T , std::size_t NDIM>
int test_op (World &world)
template<typename T , std::size_t NDIM>
int test_plot (World &world)
this essentially tests the infinity norm
int test_qm (World &world)
bool madness::test_rnlij_rangelimited (const bool log_errors)
bool madness::test_rnlp (const bool log_errors)
bool madness::test_rnlp_rangelimited (const bool log_errors)
bool madness::test_rnlp_rangelimited_erf (const bool log_errors)
Variables
const double PI = 3.1415926535897932384
bool smalltest = false
double sss
double ttt
Detailed Description
The QA/test suite for Function.
Macro Definition Documentation
CHECK
#define CHECK (value, threshold, message)
Value:
        do { \
             if (world.rank() == 0) { \
                 bool status = std::abs(value) < threshold;             \
                const char* msgs[2] = {"FAILED","OK"};                  \
                std::printf("%20.20s :%5d :%30.30s : %10.2e  < %10.2e : %s\n", (__FUNCTION__),(__LINE__),(message),(std::abs(value)),(threshold), (msgs[int(status)])); \
                if (!status) ok = false; \
             } \
        } while (0)
END_TIMER
#define END_TIMER (msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
NO_GENTENSOR
#define NO_GENTENSOR
START_TIMER
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
TO_STRING2
#define TO_STRING2 (s) #s
Function Documentation
complexify()
template<typename T > T complexify (T c)
References c.
complexify< double_complex >()
template<> double_complex complexify< double_complex > (double_complex c)
References c.
complexify< float_complex >()
template<> float_complex complexify< float_complex > (float_complex c)
References c.
main()
int main (int argc, char ** argv)
References madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, madness::initialize(), MADNESS_CHECK, madness::print(), madness::print_stats(), PROFILE_BLOCK, madness::World::rank(), madness::GaussianConvolution1D< Q >::rnlp(), madness::GenericConvolution1D< Q, opT >::rnlp(), madness::World::size(), smalltest, madness::startup(), and test_coulomb().
product()
template<typename T , typename L , typename R > T product (L l, R r) inline
References T().
RandomGaussian()
template<typename T , std::size_t NDIM> Gaussian< T, NDIM > * RandomGaussian (const Tensor< double > cell, double expntmax = 1e5)
Makes a square-normalized Gaussian with random origin and exponent.
References lo, NDIM, PI, pow(), madness::RandomValue< double >(), and T().
sum()
template<typename T , typename L , typename R > T sum (L l, R r) inline
References T().
test_apply_push_1d()
template<typename T , std::size_t NDIM> int test_apply_push_1d (World & world)
References madness::apply_1d_realspace_push(), e(), madness::Function< T, NDIM >::eval(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::World::gop, L, lo, NDIM, ok(), op(), PI, madness::plot_line(), pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::Function< T, NDIM >::sum_down(), and madness::Function< T, NDIM >::trace().
test_basic()
template<typename T , std::size_t NDIM> int test_basic (World & world)
References std::abs(), CHECK, e(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::World::gop, NDIM, norm(), ok(), PI, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), T(), and thresh.
test_conv()
template<typename T , std::size_t NDIM> int test_conv (World & world)
test the convergence of the MRA representation with respect to k and n
References std::abs(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::World::gop, madness::FunctionFactory< T, NDIM >::initial_level(), k, madness::FunctionFactory< T, NDIM >::k(), madness::kmax, NDIM, madness::FunctionFactory< T, NDIM >::norefine(), ok(), PI, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), and smalltest.
test_coulomb()
int test_coulomb (World & world)
References madness::apply_only(), CHECK, madness::CoulombOperator(), e(), END_TIMER, madness::Function< T, NDIM >::err(), madness::f, madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionFactory< T, NDIM >::initial_level(), k, norm(), madness::Function< T, NDIM >::norm2(), ok(), op(), PI, pow(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, thresh, madness::FunctionFactory< T, NDIM >::thresh(), and madness::Function< T, NDIM >::verify_tree().
Referenced by main().
test_diff()
template<typename T , std::size_t NDIM> int test_diff (World & world)
References axis, CHECK, END_TIMER, madness::Function< T, NDIM >::err(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::World::gop, NDIM, ok(), PI, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, and thresh.
test_io()
template<typename T , std::size_t NDIM> int test_io (World & world)
References CHECK, madness::archive::BaseParallelArchive< Archive >::close(), e(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::g, madness::World::gop, NDIM, madness::norm2(), ok(), PI, pow(), madness::print(), madness::World::rank(), madness::archive::BaseParallelArchive< Archive >::remove(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), and madness::World::size().
test_math()
template<typename T , std::size_t NDIM> int test_math (World & world)
References a, b, c, CHECK, madness::Function< T, NDIM >::clear(), madness::compress(), madness::default_random_generator, e(), madness::Function< T, NDIM >::err(), errsq(), madness::f, f1, f2, f3, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::World::gop, madness::mul(), NDIM, nfunc, madness::norm2(), ok(), p(), PI, pow(), madness::print(), madness::World::rank(), madness::refine_to_common_level(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::Random::setstate(), madness::square(), T(), thresh, madness::unary_op(), and madness::Function< T, NDIM >::verify_tree().
test_op()
template<typename T , std::size_t NDIM> int test_op (World & world)
References madness::apply(), CHECK, END_TIMER, madness::Function< T, NDIM >::err(), madness::f, madness::FunctionFactory< T, NDIM >::functor(), L, lo, NDIM, madness::Function< T, NDIM >::norm2(), ok(), op(), PI, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, T(), madness::test_rnlij_rangelimited(), madness::test_rnlp(), madness::test_rnlp_rangelimited(), madness::test_rnlp_rangelimited_erf(), thresh, and madness::Function< T, NDIM >::verify_tree().
test_plot()
template<typename T , std::size_t NDIM> int test_plot (World & world)
this essentially tests the infinity norm
References std::abs(), CHECK, e(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::World::gop, h(), L, NDIM, ok(), PI, madness::plot_line(), madness::plotdx(), pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::World::size(), T(), and thresh.
test_qm()
int test_qm (World & world)
References a, madness::apply_1d_realspace_push(), c, CHECK, ctarget, e(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionDefaults< NDIM >::get_cell_width(), madness::World::gop, k, L, norm(), ok(), PI, madness::print(), psi(), madness::qm_1d_free_particle_propagator(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::Function< T, NDIM >::sum_down(), tcrit, thresh, madness::Function< T, NDIM >::truncate(), tstep, and v.
Variable Documentation
PI
const double PI = 3.1415926535897932384
Referenced by QMtest::operator()(), RandomGaussian(), test_apply_push_1d(), test_basic(), test_conv(), test_coulomb(), test_diff(), test_io(), test_math(), test_op(), test_plot(), and test_qm().
smalltest
bool smalltest = false
Referenced by main(), and test_conv().
sss
double sss
ttt
double ttt