MADNESS: test_hf.cc File Reference
test_hf.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include "dft.h"
#include "hartreefock.h"
Classes
class H2Potential
Macros
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Typedefs
typedef Vector< double, 3 > coordT
Functions
int main (int argc, char **argv)
static double psi_func_be1 (const coordT &rr)
static double psi_func_be2 (const coordT &rr)
double psi_func_h2 (const Vector< double, 3 > &r)
static double psi_func_he (const coordT &r)
static double rho_func_he (const coordT &rr)
static double smoothed_potential (double r)
Regularized 1/r potential.
static double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
void test_hf_be (World &world)
void test_hf_h2 (World &world)
void test_hf_he (World &world)
static double V_func_be (const coordT &r)
double V_func_h2 (const Vector< double, 3 > &r)
static double V_func_he (const coordT &r)
Variables
const double PI = 3.1415926535897932384
Macro Definition Documentation
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
TO_STRING2
#define TO_STRING2 (s) #s
Typedef Documentation
coordT
typedef Vector<double,3> coordT
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, SafeMPI::Init(), madness::print(), madness::World::rank(), madness::World::size(), madness::startup(), test_hf_he(), and TO_STRING.
psi_func_be1()
static double psi_func_be1 (const coordT & rr) static
References e().
Referenced by test_hf_be().
psi_func_be2()
static double psi_func_be2 (const coordT & rr) static
Referenced by test_hf_be().
psi_func_h2()
double psi_func_h2 (const Vector< double, 3 > & r)
Referenced by test_hf_h2().
psi_func_he()
static double psi_func_he (const coordT & r) static
References e().
Referenced by test_hf_he().
rho_func_he()
static double rho_func_he (const coordT & rr) static
References c.
Referenced by test_hf_he().
smoothed_potential()
static double smoothed_potential (double r) static
Regularized 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References e(), PI, and madness::r2().
Referenced by V_func_be(), and V_func_he().
smoothing_parameter()
static double smoothing_parameter (double Z, double eprec) static
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, e(), eprec, pow(), and Z.
Referenced by V_func_be(), and V_func_he().
test_hf_be()
void test_hf_be (World & world)
References e(), madness::FunctionFactory< T, NDIM >::f(), madness::Function< T, NDIM >::norm2(), madness::print(), psi_func_be1(), psi_func_be2(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), thresh, madness::FunctionFactory< T, NDIM >::thresh(), and V_func_be().
test_hf_h2()
void test_hf_h2 (World & world)
References e(), madness::FunctionFactory< T, NDIM >::f(), psi(), psi_func_h2(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), thresh, and V_func_h2().
test_hf_he()
void test_hf_he (World & world)
References madness::apply(), e(), madness::error(), madness::FunctionFactory< T, NDIM >::f(), L, op(), p(), psi(), psi_func_he(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), rho_func_he(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), thresh, madness::Function< T, NDIM >::truncate(), V_func_he(), and vnuc().
Referenced by main().
V_func_be()
static double V_func_be (const coordT & r) static
References c, e(), smoothed_potential(), and smoothing_parameter().
Referenced by test_hf_be().
V_func_h2()
double V_func_h2 (const Vector< double, 3 > & r)
References e().
Referenced by test_hf_h2().
V_func_he()
static double V_func_he (const coordT & r) static
References c, e(), smoothed_potential(), and smoothing_parameter().
Referenced by test_hf_he().
Variable Documentation
PI
const double PI = 3.1415926535897932384
Referenced by smoothed_potential().