MADNESS: test_solvers.cc File Reference
test_solvers.cc File Reference
#include <madness/tensor/solvers.h>
Classes
struct Test
struct Test2
Functions
double dot_product (const Tensor< double > &a, const Tensor< double > &b)
int main ()
Tensor< double > op (const Tensor< double > &x)
Function Documentation
dot_product()
double dot_product (const Tensor< double > & a, const Tensor< double > & b)
References a, and b.
main()
int main (void)
References madness::Tensor< T >::fillrandom(), madness::QuasiNewton::optimize(), and madness::QuasiNewton::set_update().
op()
Tensor<double> op (const Tensor< double > & x)
References madness::BaseTensor::dim(), and madness::f.