MADNESS: test_lowranktensor.cc File Reference
test_lowranktensor.cc File Reference
#include <madness/tensor/gentensor.h>
#include <madness/tensor/RandomizedMatrixDecomposition.h>
Macros
#define ENABLE_GENTENSOR
Functions
template<typename T >
double compute_difference (const GenTensor< T > &lrt1, const GenTensor< T > &lrt2)
template<typename T >
double compute_difference (const GenTensor< T > &lrt1, const Tensor< T > &t2)
template<typename T >
double compute_difference (const Tensor< T > &t2, const GenTensor< T > &lrt1)
int main (int argc, char *argv[])
std::vector< long > make_dimensions (bool even=false)
template<typename T >
int test_addition (const TensorType &tt)
template<typename T >
int test_constructor ()
template<typename T >
int test_convert ()
template<typename T >
int test_emul (const TensorType &tt)
template<typename T >
int test_general_transform ()
template<typename T >
int test_reconstruct ()
template<typename T >
int test_reduce_rank (const TensorType &tt)
template<typename T >
int test_sliced_addition (const TensorType &tt)
template<typename T >
int test_sliced_assignment (const TensorType &tt)
template<typename T >
int test_stuff ()
Macro Definition Documentation
ENABLE_GENTENSOR
#define ENABLE_GENTENSOR
Function Documentation
compute_difference() [1/3]
template<typename T > double compute_difference (const GenTensor< T > & lrt1, const GenTensor< T > & lrt2)
References madness::GenTensor< T >::full_tensor_copy().
Referenced by test_addition(), test_convert(), test_emul(), test_reconstruct(), test_reduce_rank(), and test_sliced_addition().
compute_difference() [2/3]
template<typename T > double compute_difference (const GenTensor< T > & lrt1, const Tensor< T > & t2)
References madness::GenTensor< T >::full_tensor_copy().
compute_difference() [3/3]
template<typename T > double compute_difference (const Tensor< T > & t2, const GenTensor< T > & lrt1)
References madness::GenTensor< T >::full_tensor_copy().
main()
int main (int argc, char * argv[])
References madness::cpu_time(), madness::default_random_generator, madness::Random::setstate(), madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
make_dimensions()
std::vector<long> make_dimensions (bool even = false)
References d(), madness::print(), and madness::RandomValue< long >().
Referenced by test_addition(), test_constructor(), test_emul(), test_reconstruct(), and test_reduce_rank().
test_addition()
template<typename T > int test_addition (const TensorType & tt)
References compute_difference(), madness::copy(), madness::error(), madness::Tensor< T >::fillrandom(), madness::GenTensor< T >::get_svdtensor(), make_dimensions(), madness::print(), madness::GenTensor< T >::reduce_rank(), and madness::TT_2D.
test_constructor()
template<typename T > int test_constructor ()
References madness::Tensor< T >::fillrandom(), make_dimensions(), madness::print(), madness::svd(), thresh, madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
test_convert()
template<typename T > int test_convert ()
References compute_difference(), madness::GenTensor< T >::convert(), madness::Tensor< T >::fillrandom(), madness::print(), thresh, madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
test_emul()
template<typename T > int test_emul (const TensorType & tt)
References compute_difference(), madness::GenTensor< T >::emul(), madness::Tensor< T >::emul(), madness::error(), madness::Tensor< T >::fillrandom(), make_dimensions(), madness::print(), thresh, and madness::TT_2D.
test_general_transform()
template<typename T > int test_general_transform ()
References c, cc, madness::Tensor< T >::fillrandom(), madness::GenTensor< T >::full_tensor_copy(), madness::general_transform(), madness::print(), TENSOR_MAXDIM, thresh, madness::TT_2D, and madness::TT_TENSORTRAIN.
test_reconstruct()
template<typename T > int test_reconstruct ()
References compute_difference(), madness::error(), madness::Tensor< T >::fillrandom(), make_dimensions(), madness::print(), thresh, madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
test_reduce_rank()
template<typename T > int test_reduce_rank (const TensorType & tt)
References compute_difference(), madness::error(), madness::Tensor< T >::fillrandom(), make_dimensions(), madness::print(), madness::GenTensor< T >::reduce_rank(), thresh, and madness::TT_2D.
test_sliced_addition()
template<typename T > int test_sliced_addition (const TensorType & tt)
References madness::_(), compute_difference(), madness::copy(), madness::error(), madness::Tensor< T >::fillrandom(), and madness::print().
test_sliced_assignment()
template<typename T > int test_sliced_assignment (const TensorType & tt)
References madness::_(), madness::error(), madness::Tensor< T >::fillrandom(), madness::print(), and s0.
test_stuff()
template<typename T > int test_stuff ()
References madness::RandomizedMatrixDecomposition< T >::check_range(), madness::RandomizedMatrixDecomposition< T >::compute_range(), madness::SVDTensor< T >::compute_svd_from_range(), madness::error(), madness::RandomizedMatrixDecomposition< T >::exceeds_maxrank(), madness::RandomizedMatrixDecomposition< T >::get_range(), k, madness::RandomizedMatrixDecomposition< T >::make_SVD_decaying_matrix(), madness::SRConf< T >::max_sigma(), madness::RMDFactory::oversampling(), pow(), madness::print(), Q(), madness::SVDTensor< T >::rank(), madness::TensorTrain< T >::ranks(), madness::SRConf< T >::reconstruct(), madness::TensorTrain< T >::reconstruct(), madness::svd(), T(), thresh, and madness::wall_time().