MADNESS: test_mpihang.cc File Reference
test_mpihang.cc File Reference
#include <mpi.h>
#include <iostream>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References a, b, MADNESS_EXCEPTION, me, MPI_BYTE, MPI_Comm_rank(), MPI_Comm_size(), MPI_COMM_WORLD, MPI_Finalize(), MPI_Init(), MPI_Irecv(), MPI_Isend(), MPI_Test(), np, and status.