MADNESS: test_world.cc File Reference
test_world.cc File Reference
#include <vector>
#include <numeric>
#include <algorithm>
#include <madness/world/MADworld.h>
#include <madness/world/world_object.h>
#include <madness/world/worlddc.h>
#include <complex>
Classes
class B
struct Node::do_random_insert
class Foo
struct Key
class Mary
struct Node
class TestBarrier
class TestFutureForwarding
class TestTask
class TimeBarrier
class TTT
struct Walker1
Typedefs
typedef std::complex< double > double_complex
Functions
double dumb (int a1, int a2, int a3, int a4, int a5, int a6, int a7)
bool is_even (int i)
bool is_odd (int i)
int main (int argc, char **argv)
void null_func ()
ostream & operator<< (ostream &s, const Key &key)
ostream & operator<< (ostream &s, const Node &node)
void pounder (const WorldContainer< int, Mary > &m, int ind)
void test0 (World &world)
void test10 (World &world)
void test11 (World &world)
void test12 (World &world)
void test13 (World &world)
void test14 (World &world)
void test15 (World &world)
void test5 (World &world)
void test6 (World &world)
void test6a (World &world)
void test7 (World &world)
void test8 (World &world)
void test9 (World &world)
void test_multi (World &world)
void test_multi_world (World &world)
int val1d_func (int input)
int val_func ()
void walker1 (WorldContainer< Key, Node > &d, const Key &key)
void walker2 (WorldContainer< Key, Node > &d, const Key &key)
void work_even (World &world)
void work_odd (World &world)
Typedef Documentation
double_complex
typedef std::complex<double> double_complex
Function Documentation
dumb()
double dumb (int a1, int a2, int a3, int a4, int a5, int a6, int a7)
References a1, and a2.
Referenced by test5().
is_even()
bool is_even (int i) inline
References is_odd().
is_odd()
bool is_odd (int i) inline
Referenced by is_even(), and test_multi_world().
main()
int main (int argc, char ** argv)
References madness::World::args(), madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), PROFILE_BLOCK, madness::World::rank(), madness::redirectio(), madness::ThreadPool::size(), madness::World::size(), test0(), test10(), test12(), test13(), test14(), test15(), test5(), test6(), test6a(), test7(), test8(), test9(), and test_multi_world().
null_func()
void null_func ()
Referenced by test9().
operator<<() [1/2]
ostream & operator<< (ostream & s, const Key & key)
References madness::Key< NDIM >::hash(), and madness::Key< NDIM >::n.
operator<<() [2/2]
ostream & operator<< (ostream & s, const Node & node)
References Node::get(), and Node::is_leaf().
pounder()
void pounder (const WorldContainer< int, Mary > & m, int ind)
References Mary::inc(), m, and madness::print().
Referenced by test10().
test0()
void test0 (World & world)
References a, madness::archive::BufferInputArchive::load(), MADNESS_CHECK, madness::print(), PROFILE_FUNC, madness::World::rank(), and madness::archive::BufferOutputArchive::store().
Referenced by main().
test10()
void test10 (World & world)
References Mary::add(), madness::WorldTaskQueue::add(), Mary::alan(), b, madness::WorldGopInterface::fence(), Mary::fred(), Mary::galahad(), madness::Future< T >::get(), Mary::get_me_twice(), madness::World::gop, Mary::inc(), m, MADNESS_CHECK, me, pounder(), madness::print(), PROFILE_FUNC, madness::World::rank(), madness::World::size(), and madness::World::taskq.
Referenced by main(), work_even(), and work_odd().
test11()
void test11 (World & world)
References d, madness::World::drand(), madness::WorldGopInterface::fence(), madness::World::gop, me, madness::print(), PROFILE_FUNC, Node::random_insert(), madness::World::rank(), madness::World::srand(), walker1(), and walker2().
test12()
void test12 (World & world)
References c, madness::archive::BinaryFstreamOutputArchive::close(), d, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, me, madness::print(), PROFILE_FUNC, madness::World::rank(), and madness::World::size().
Referenced by main().
test13()
void test13 (World & world)
References c, madness::archive::BaseParallelArchive< Archive >::close(), d, madness::WorldGopInterface::fence(), fout, madness::World::gop, MADNESS_CHECK, me, madness::archive::BaseParallelArchive< Archive >::open(), madness::print(), PROFILE_FUNC, madness::World::rank(), madness::archive::BaseParallelArchive< Archive >::remove(), madness::World::size(), and v.
Referenced by main().
test14()
void test14 (World & world)
References madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, madness::print(), madness::World::rank(), madness::WorldGopInterface::set_max_reducebcast_msg_size(), and madness::World::size().
Referenced by main(), work_even(), and work_odd().
test15()
void test15 (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, madness::WorldGopInterface::max(), madness::print(), madness::World::rank(), and madness::World::size().
Referenced by main(), work_even(), and work_odd().
test5()
void test5 (World & world)
References madness::WorldTaskQueue::add(), TTT::bert(), TTT::carl(), dave(), TTT::dave(), dumb(), madness::WorldGopInterface::fence(), TTT::fred(), madness::Future< T >::get(), madness::World::gop, TTT::hugh(), TTT::jody(), TTT::kate(), MADNESS_CHECK, TTT::mary(), me, madness::print(), madness::Future< T >::probe(), PROFILE_FUNC, madness::World::rank(), TTT::sara(), madness::Future< T >::set(), madness::World::size(), task(), madness::World::taskq, and madness::ttt.
Referenced by main(), work_even(), and work_odd().
test6()
void test6 (World & world)
References a, madness::f, madness::WorldGopInterface::fence(), Foo::get0(), Foo::get0c(), Foo::get0f(), Foo::get1(), Foo::get1c(), Foo::get2(), Foo::get2c(), Foo::get3(), Foo::get3c(), Foo::get4(), Foo::get4c(), Foo::get5(), Foo::get5c(), Foo::getbuf0(), Foo::getbuf0c(), madness::World::gop, madness::World::id_from_ptr(), m, MADNESS_CHECK, me, madness::World::nproc(), p(), Foo::ping(), Foo::ping_am(), madness::print(), PROFILE_FUNC, madness::World::ptr_from_id(), madness::World::rank(), and madness::World::srand().
Referenced by main(), work_even(), and work_odd().
test6a()
void test6a (World & world)
References madness::WorldGopInterface::fence(), fred(), madness::World::gop, MADNESS_CHECK, madness::print(), PROFILE_FUNC, madness::World::rank(), madness::World::size(), and TestFutureForwarding::test().
Referenced by main(), work_even(), and work_odd().
test7()
void test7 (World & world)
References c, d, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, me, madness::print(), PROFILE_FUNC, madness::World::rank(), and madness::World::size().
Referenced by main(), work_even(), and work_odd().
test8()
void test8 (World & world)
References MADNESS_CHECK, p(), madness::print(), PROFILE_FUNC, madness::World::rank(), and v.
Referenced by main(), work_even(), and work_odd().
test9()
void test9 (World & world)
References madness::WorldTaskQueue::add(), madness::cpu_time(), madness::WorldTaskQueue::fence(), madness::Future< T >::get(), MADNESS_CHECK, null_func(), madness::print(), PROFILE_FUNC, madness::World::rank(), madness::Future< T >::set(), madness::World::taskq, v, val1d_func(), and val_func().
Referenced by main(), work_even(), and work_odd().
test_multi()
void test_multi (World & world)
References madness::WorldTaskQueue::add(), madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, madness::TaskAttributes::multi_threaded(), madness::print(), madness::ThreadPool::size(), and madness::World::taskq.
test_multi_world()
void test_multi_world (World & world)
References madness::WorldMpiInterface::comm(), SafeMPI::Intracomm::Create(), madness::WorldGopInterface::fence(), SafeMPI::Intracomm::Get_group(), SafeMPI::Intracomm::Get_size(), madness::World::gop, SafeMPI::Group::Incl(), is_odd(), madness::World::mpi, madness::World::rank(), SafeMPI::Intracomm::SHARED_SPLIT_TYPE, madness::World::size(), SafeMPI::Intracomm::Split(), SafeMPI::Intracomm::Split_type(), work_even(), and work_odd().
Referenced by main().
val1d_func()
int val1d_func (int input)
Referenced by test9().
val_func()
int val_func ()
Referenced by test9().
walker1()
void walker1 (WorldContainer< Key, Node > & d, const Key & key)
References d, madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), Node::is_leaf(), MADNESS_CHECK, and Node::set().
Referenced by Walker1::operator()(), and test11().
walker2()
void walker2 (WorldContainer< Key, Node > & d, const Key & key)
References d, madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), Node::is_leaf(), MADNESS_CHECK, madness::print(), and Node::set().
Referenced by test11().
work_even()
void work_even (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, test10(), test14(), test15(), test5(), test6(), test6a(), test7(), test8(), and test9().
Referenced by test_multi_world().
work_odd()
void work_odd (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, test10(), test14(), test15(), test5(), test6(), test6a(), test7(), test8(), and test9().
Referenced by test_multi_world().