MADNESS: testcosine.cc File Reference
testcosine.cc File Reference
#include <madness/mra/mra.h>
#include <madness/tensor/solvers.h>
Classes
class CosPotentialFunctor
class ExpFunctor< Q >
class ExpFunctor3d< Q >
class PWFunctor
Typedefs
typedef SeparatedConvolution< double_complex, 3 > coperatorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::shared_ptr< operatorT> poperatorT
Functions
complex_function_3d apply_periodic_bsh (World &world, const complex_function_3d &f, const double &kx, const double &ky, const double &kz, const double &energy, const double &L)
vector_complex_function_3d apply_potential (const real_function_3d &potential, const vector_complex_function_3d &psi)
std::vector< coord_3d > get_coeffs_pw (double maxKlen)
static const double_complex I (0, 1)
int main (int argc, char **argv)
vector_complex_function_3d make_basis (World &world, double maxKlen)
tensor_complex make_kinetic_matrix (World &world, const vector_complex_function_3d &v)
real_tensor make_pw_matrix (const std::vector< coord_3d > &gvecs)
void orthogonalize (World &world, vector_complex_function_3d &psi)
vector_complex_function_3d update (World &world, const vector_complex_function_3d &psi, vector_complex_function_3d &vpsi, const tensor_real &e, int iter)
Variables
static const double alpha = 2.5
static const double kwavelet = 4
static const double kx =0.5*twopi/L
static const double ky =0.5*twopi/L
static const double kz =0.5*twopi/L
static const double L = 5.0
static const double pi = constants::pi
static const double thresh = 1e-2
static const int truncate_mode = 0
static const double twopi = 2.0*constants::pi
Typedef Documentation
coperatorT
typedef SeparatedConvolution<double_complex,3> coperatorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
Function Documentation
apply_periodic_bsh()
complex_function_3d apply_periodic_bsh (World & world, const complex_function_3d & f, const double & kx, const double & ky, const double & kz, const double & energy, const double & L)
References madness::apply(), e(), energy, madness::f, madness::g, madness::FunctionDefaults< NDIM >::get_thresh(), I(), kx, ky, kz, L, op(), and madness::PeriodicBSHOperator3D().
Referenced by update().
apply_potential()
vector_complex_function_3d apply_potential (const real_function_3d & potential, const vector_complex_function_3d & psi)
References potential(), and psi().
Referenced by main().
get_coeffs_pw()
std::vector<coord_3d> get_coeffs_pw (double maxKlen)
References a, b, L, and pi.
I()
static const double_complex I (0 , 1) static
Referenced by apply_periodic_bsh(), make_basis(), and make_kinetic_matrix().
main()
int main (int argc, char ** argv)
References madness::_(), std::abs(), apply_potential(), madness::BC_PERIODIC, c, SafeMPI::COMM_WORLD, madness::copy(), e(), madness::initialize(), kwavelet, L, make_basis(), make_kinetic_matrix(), madness::matrix_inner(), madness::print(), madness::project(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), madness::sygv(), thresh, madness::transform(), truncate_mode, update(), and v.
make_basis()
vector_complex_function_3d make_basis (World & world, double maxKlen)
References I(), L, madness::normalize(), pi, and twopi.
Referenced by main().
make_kinetic_matrix()
tensor_complex make_kinetic_matrix (World & world, const vector_complex_function_3d & v)
References madness::apply(), f1, f2, f3, I(), kx, ky, kz, madness::matrix_inner(), and v.
Referenced by main().
make_pw_matrix()
real_tensor make_pw_matrix (const std::vector< coord_3d > & gvecs)
References madness::abs(), alpha, e(), L, madness::Vector< T, N >::normf(), pi, and madness::BaseTensor::size().
orthogonalize()
void orthogonalize (World & world, vector_complex_function_3d & psi)
References madness::compress(), madness::Function< T, NDIM >::gaxpy(), madness::inner(), madness::Function< T, NDIM >::norm2(), psi(), and madness::Function< T, NDIM >::scale().
Referenced by update().
update()
vector_complex_function_3d update (World & world, const vector_complex_function_3d & psi, vector_complex_function_3d & vpsi, const tensor_real & e, int iter)
References apply_periodic_bsh(), e(), madness::gaxpy(), k, kx, ky, kz, L, madness::norm2(), madness::normalize(), orthogonalize(), madness::print(), psi(), madness::World::rank(), madness::scale(), shift, and madness::truncate().
Referenced by MiniDFT::doit(), main(), QuasiNewton::optimize(), and QuasiNewton::set_update().
Variable Documentation
alpha
const double alpha = 2.5 static
Referenced by make_pw_matrix(), and CosPotentialFunctor::operator()().
kwavelet
const double kwavelet = 4 static
Referenced by MiniDFT::MiniDFT(), MiniDFT::doit(), and main().
kx
const double kx =0.5*twopi/L static
Referenced by KPeriodicBSHOperator::KPeriodicBSHOperator(), KPeriodicBSHOperator::apply(), apply_periodic_bsh(), main(), madness::BasisFunctions::make_cartesian_guess(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), makeao_slow(), AtomicBasisFunctor< Q >::operator()(), and update().
ky
const double ky =0.5*twopi/L static
Referenced by KPeriodicBSHOperator::KPeriodicBSHOperator(), KPeriodicBSHOperator::apply(), apply_periodic_bsh(), main(), madness::BasisFunctions::make_cartesian_guess(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), makeao_slow(), AtomicBasisFunctor< Q >::operator()(), and update().
kz
const double kz =0.5*twopi/L static
Referenced by KPeriodicBSHOperator::KPeriodicBSHOperator(), KPeriodicBSHOperator::apply(), apply_periodic_bsh(), main(), madness::BasisFunctions::make_cartesian_guess(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), makeao_slow(), AtomicBasisFunctor< Q >::operator()(), and update().
L
const double L = 5.0 static
Referenced by apply_periodic_bsh(), get_coeffs_pw(), main(), make_basis(), make_pw_matrix(), CosPotentialFunctor::operator()(), and update().
pi
const double pi = constants::pi static
Referenced by MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), madness::HartreeFock< T, NDIM >::calculate_tot_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_ke_sp(), madness::DFT< T, NDIM >::calculate_tot_ke_sp(), madness::HartreeFock< T, NDIM >::calculate_tot_pe_sp(), madness::Nemo::compute_IR_intensities(), dfunc(), erfaroverr(), madness::detail::adqtest::exact(), exact_cosine(), exact_spheropole(), f_cosine(), f_dipole(), f_quadrupole(), f_spheropole(), func(), madness::gauss_legendre_numeric(), get_coeffs_pw(), madness::DistributedMatrixDistribution::get_range(), madness::GradBSHOperator(), GradBSHOperator_Joel(), madness::GradCoulombOperator(), gradPbarA(), madness::GradSlaterOperator(), madness::SeparatedConvolution< Q, NDIM >::initialize(), main(), make_basis(), make_fit(), make_grad_operator(), make_pw_matrix(), madness::EigSolverOp< T, NDIM >::multi_op_o(), madness::EigSolverOp< T, NDIM >::multi_op_r(), madness::EigSolver< T, NDIM >::multi_solve(), CosPotentialFunctor::operator()(), opposing_field_potential(), CFFT::Perform(), madness::EigSolver< T, NDIM >::solve(), test(), test_in(), test_out(), madness::test_rnlp(), and vector_to_PQ().
thresh
const double thresh = 1e-2 static
Referenced by main().
truncate_mode
const int truncate_mode = 0 static
Referenced by MiniDFT::MiniDFT(), NuclearVector::NuclearVector(), madness::SCF::derivatives(), main(), madness::GTHPseudopotential< Q >::make_pseudo_potential(), nuclear_generator(), madness::FunctionDefaults< NDIM >::print(), madness::FunctionDefaults< NDIM >::set_defaults(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
twopi
const double twopi = 2.0*constants::pi static
Referenced by make_basis().