MADNESS: testpc.h File Reference
testpc.h File Reference
#include <iostream>
#include <complex>
#include <numeric>
#include <vector>
#include <cmath>
#include <madness/misc/gnuplot.h>
Functions
std::vector< double > linspace (double a, double b, size_t n, bool include_right_endpoint=true)
template<typename T >
void print (size_t m, size_t n, const std::vector< T > &M)
void set_test_case (int test_case)
std::vector< double > tabulate (double(*f)(double, double, double), std::vector< double > x, std::vector< double > y, std::vector< double > z)
Variables
double(* exact)(double, double, double)
double(* f)(double, double, double)
const double L = 1.0
const double pi = 3.14159265358979323846
const double xshift = 0.0
const double yshift = 0.0
const double zshift = 0.0
Function Documentation
linspace()
std::vector< double > linspace (double a, double b, size_t n, bool include_right_endpoint = true)
References a, b, h(), and v.
Referenced by main().
print()
template<typename T > void print (size_t m, size_t n, const std::vector< T > & M)
References m.
set_test_case()
void set_test_case (int test_case)
References exact, exact_cosine(), exact_dipole(), exact_quadrupole(), exact_spheropole(), f, f_cosine(), f_dipole(), f_quadrupole(), and f_spheropole().
Referenced by main().
tabulate()
std::vector< double > tabulate (double(*)(double, double, double) f, std::vector< double > x, std::vector< double > y, std::vector< double > z)
References f, and k.
Variable Documentation
exact
double(* exact) (double, double, double) (double , double , double) extern
Referenced by madness::GFit< T, NDIM >::BSHFit(), compare(), madness::CubicInterpolationTable< T >::err(), madness::GFit< T, NDIM >::F12Fit(), madness::GFit< T, NDIM >::F12sqFit(), madness::GFit< T, NDIM >::F2GFit(), madness::GFit< T, NDIM >::FGFit(), madness::GFit< T, NDIM >::GaussFit(), main(), main(), madness::GFit< T, NDIM >::print_accuracy(), set_test_case(), madness::GFit< T, NDIM >::slater_fit(), madness::GFit< T, NDIM >::SlaterFit(), test0(), test0GaussLobatto(), test1(), test_gconv(), test_integration(), test_opdir(), test_periodic2(), test_periodic_bsh(), and madness::test_rnlp().
f
double(* f) (double, double, double) (double , double , double) extern
Referenced by fit(), periodic_sum(), periodic_sum_accelerated(), periodic_sum_partial(), set_test_case(), solve(), and tabulate().
L
const double L = 1.0
pi
const double pi = 3.14159265358979323846
xshift
const double xshift = 0.0
Referenced by exact_dipoleX(), exact_quadrupoleX(), exact_spheropole(), f_cosine(), f_dipole(), f_quadrupole(), and f_spheropole().
yshift
const double yshift = 0.0
Referenced by exact_dipoleX(), exact_quadrupoleX(), exact_spheropole(), f_cosine(), f_dipole(), f_quadrupole(), and f_spheropole().
zshift
const double zshift = 0.0
Referenced by exact_dipoleX(), exact_quadrupoleX(), exact_spheropole(), f_cosine(), f_dipole(), f_quadrupole(), f_spheropole(), and opposing_field_potential().