MADNESS: test_distributed_matrix.cc File Reference
test_distributed_matrix.cc File Reference
#include <madness/madness_config.h>
#include <madness/world/MADworld.h>
#include <madness/tensor/distributed_matrix.h>
Functions
void check (DistributedMatrix< double > &A)
double ij (int64_t i, int64_t j)
int main (int argc, char **argv)
Function Documentation
check()
void check (DistributedMatrix< double > & A)
References ij(), m, MADNESS_CHECK, and me.
Referenced by main().
ij()
double ij (int64_t i, int64_t j)
Referenced by check(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_f12_correction_gs(), madness::F12Potentials::compute_fQg_integrals(), madness::F12Potentials::compute_fQU_integrals(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::compute_K_tile(), madness::MP3::compute_mp3_ef_with_permutational_symmetry(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeSimple::compute_offdiagonal_batch_in_symmetric_matrix(), madness::PNOPairs::extract(), madness::PNO::iterate_pairs_internal(), madness::CCPairFunction< T, NDIM >::make_xy_u(), madness::MP3::mp3_test(), madness::MP3::MacroTaskMP3::operator()(), madness::PNO::pno_compress(), madness::read_data(), madness::PNOPairs::reassemble(), madness::PNO::t_solve(), test(), test_hartree_product(), madness::test_rnlij_rangelimited(), madness::PNO::transform_pairs(), madness::PairEnergies::update(), and madness::PNO::update_pno().
main()
int main (int argc, char ** argv)
References check(), SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), and m.