MADNESS: test_SCFOperators.cc File Reference
test_SCFOperators.cc File Reference
#include <madness.h>
#include <madness/chem/SCFOperators.h>
#include <madness/chem/SCF.h>
#include <madness/chem/nemo.h>
#include <madness/chem/correlationfactor.h>
#include <madness/chem/write_test_input.h>
#include <typeinfo>
Classes
class GaussianGuess< NDIM >
an N-dimensional real-valued Gaussian function
struct refpotfunctor
reference potential for the Poisson solver of a Gaussian
Functions
bool check_err (double err, double thresh, std::string msg)
int dnuclear_anchor_test (World &world)
template<typename T >
int exchange_anchor_test (World &world, Exchange< T, 3 > &K, const double thresh)
anchor test for the exchange operator – partially hardwired
int main (int argc, char **argv)
int nuclear_anchor_test (World &world)
static double_complex p_minus (const coord_3d &xyz)
complex function p-orbital with m_l=-1
static double_complex p_plus (const coord_3d &xyz)
complex function p-orbital with m_l=1
bool similar (double val1, double val2, double thresh=1.e-6)
template<typename T , typename opT , std::size_t NDIM>
int test_asymmetric (World &world, const opT &op, double thresh)
test if the operator return correct matrix elements if bra!=ket
template<typename T >
int test_coulomb (World &world)
int test_dnuclear (World &world)
template<typename T >
int test_exchange (World &world)
int test_fock (World &world)
template<typename T , typename opT , std::size_t NDIM>
int test_hermiticity (World &world, const opT &op, double thresh)
test the hermiticity of the operator op and its translational invariance
template<typename T , std::size_t NDIM>
int test_kinetic (World &world)
int test_nemo (World &world)
int test_nuclear (World &world)
template<typename T >
int test_XCOperator (World &world)
Variables
bool smalltest = false
Function Documentation
check_err()
bool check_err (double err, double thresh, std::string msg)
References madness::print(), and thresh.
Referenced by dnuclear_anchor_test(), exchange_anchor_test(), nuclear_anchor_test(), test_asymmetric(), test_coulomb(), test_fock(), test_hermiticity(), test_kinetic(), and test_nemo().
dnuclear_anchor_test()
int dnuclear_anchor_test (World & world)
References check_err(), madness::copy(), madness::create_nuclear_correlation_factor(), madness::FunctionFactory< T, NDIM >::functor(), gaussian2(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::Nemo::NemoCalculationParameters::ncf(), param, madness::SCF::param, madness::SCF::potentialmanager, madness::print(), madness::CalculationParameters::read_input_and_commandline_options(), madness::commandlineparser::set_keyval(), madness::Function< T, NDIM >::square(), thresh, madness::FunctionFactory< T, NDIM >::truncate_on_project(), madness::Molecule::update_rcut_with_eprec(), and V().
Referenced by test_dnuclear().
exchange_anchor_test()
template<typename T > int exchange_anchor_test (World & world, Exchange< T, 3 > & K, const double thresh)
anchor test for the exchange operator – partially hardwired
References alpha, check_err(), diff(), madness::Tensor< T >::fill(), madness::FunctionFactory< T, NDIM >::functor(), k, K(), madness::matrix_inner(), madness::norm2s(), madness::print(), madness::World::rank(), madness::BaseTensor::size(), madness::sub(), thresh, madness::Function< T, NDIM >::thresh(), madness::FunctionFactory< T, NDIM >::thresh(), and madness::FunctionFactory< T, NDIM >::truncate_on_project().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_k(), smalltest, madness::startup(), and test_dnuclear().
nuclear_anchor_test()
int nuclear_anchor_test (World & world)
References check_err(), madness::copy(), madness::create_nuclear_correlation_factor(), write_test_input::filename(), madness::FunctionFactory< T, NDIM >::functor(), gaussian2(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::Nemo::NemoCalculationParameters::ncf(), param, madness::SCF::param, madness::SCF::potentialmanager, madness::print(), madness::CalculationParameters::read_input_and_commandline_options(), madness::commandlineparser::set_keyval(), madness::Function< T, NDIM >::square(), madness::square(), T(), thresh, madness::FunctionFactory< T, NDIM >::truncate_on_project(), V(), V1, and V2.
Referenced by test_nuclear().
p_minus()
static double_complex p_minus (const coord_3d & xyz) static
complex function p-orbital with m_l=-1
References madness::Vector< T, N >::normf().
p_plus()
static double_complex p_plus (const coord_3d & xyz) static
complex function p-orbital with m_l=1
References madness::Vector< T, N >::normf().
similar()
bool similar (double val1, double val2, double thresh = 1.e-6)
References thresh.
Referenced by test_read_restartaodata(), and test_XCOperator().
test_asymmetric()
template<typename T , typename opT , std::size_t NDIM> int test_asymmetric (World & world, const opT & op, double thresh)
test if the operator return correct matrix elements if bra!=ket
Parameters
[in] world the world
[in] op the operator to be tested, must implement op(vecfuncT,vecfuncT)
[in] thresh the accuracy threshold
Returns
0 if test passes, 1 if test fails
References madness::_(), check_err(), madness::copy(), madness::FunctionFactory< T, NDIM >::functor(), NDIM, madness::Tensor< T >::normf(), op(), madness::print(), madness::BaseTensor::size(), thresh, and madness::FunctionFactory< T, NDIM >::truncate_on_project().
test_coulomb()
template<typename T > int test_coulomb (World & world)
References std::abs(), madness::abs_square(), alpha, check_err(), madness::Coulomb< T, NDIM >::compute_potential(), madness::copy(), madness::FunctionFactory< T, NDIM >::functor(), madness::g, madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::Function< T, NDIM >::norm2(), madness::Coulomb< T, NDIM >::potential(), madness::print(), madness::World::rank(), madness::Coulomb< T, NDIM >::reset_poisson_operator_ptr(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_thresh(), T(), thresh, madness::Function< T, NDIM >::thresh(), and madness::FunctionFactory< T, NDIM >::truncate_on_project().
test_dnuclear()
int test_dnuclear (World & world)
References dnuclear_anchor_test(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_thresh(), and thresh.
Referenced by main().
test_exchange()
template<typename T > int test_exchange (World & world)
References alpha, madness::conj(), madness::exchange_anchor_test(), madness::Tensor< T >::fill(), madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionDefaults< NDIM >::get_thresh(), K(), lo, madness::name(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_thresh(), smalltest, T(), thresh, madness::FunctionFactory< T, NDIM >::thresh(), and madness::FunctionFactory< T, NDIM >::truncate_on_project().
test_fock()
int test_fock (World & world)
References check_err(), madness::f, f1, write_test_input::filename(), madness::FunctionFactory< T, NDIM >::functor(), madness::Nemo::get_calc(), madness::FunctionDefaults< NDIM >::get_thresh(), K(), param, madness::print(), madness::World::rank(), madness::commandlineparser::set_keyval(), madness::FunctionDefaults< NDIM >::set_thresh(), T(), thresh, madness::FunctionFactory< T, NDIM >::truncate_on_project(), V(), and madness::Nemo::value().
test_hermiticity()
template<typename T , typename opT , std::size_t NDIM> int test_hermiticity (World & world, const opT & op, double thresh)
test the hermiticity of the operator op and its translational invariance
Parameters
[in] world the world
[in] op the operator to be tested, must implement op(vecfuncT,vecfuncT)
[in] thresh the accuracy threshold
Returns
0 if test passes, 1 if test fails
References madness::abs(), check_err(), madness::conj_transpose(), madness::copy(), madness::FunctionFactory< T, NDIM >::functor(), madness::Tensor< T >::normf(), op(), madness::print(), madness::BaseTensor::size(), thresh, and madness::FunctionFactory< T, NDIM >::truncate_on_project().
test_kinetic()
template<typename T , std::size_t NDIM> int test_kinetic (World & world)
References madness::abs(), std::abs(), check_err(), madness::f, madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::name(), NDIM, madness::Function< T, NDIM >::norm2(), madness::norm2(), madness::print(), madness::World::rank(), madness::real(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), T(), thresh, and madness::FunctionFactory< T, NDIM >::truncate_on_project().
test_nemo()
int test_nemo (World & world)
References check_err(), madness::Nemo::compute_fock_matrix(), energy, write_test_input::filename(), madness::Nemo::get_calc(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::Nemo::make_fock_operator(), param, madness::print(), madness::NemoBase::R_square, madness::World::rank(), madness::commandlineparser::set_keyval(), madness::FunctionDefaults< NDIM >::set_thresh(), thresh, and madness::Nemo::value().
test_nuclear()
int test_nuclear (World & world)
References madness::FunctionDefaults< NDIM >::get_thresh(), nuclear_anchor_test(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_thresh(), and thresh.
test_XCOperator()
template<typename T > int test_XCOperator (World & world)
custom ctor with information about the XC functional
References a1, a2, madness::abs_square(), alpha, beta, madness::XCOperator< T, NDIM >::compute_xc_energy(), e(), f1, f2, madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), MADNESS_CHECK, madness::print(), madness::World::rank(), madness::refine_to_common_level(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::XCOperator< T, NDIM >::set_ispin(), madness::FunctionDefaults< NDIM >::set_thresh(), similar(), smalltest, thresh, v, and xc.
Variable Documentation
smalltest
bool smalltest = false
Referenced by madness::main(), main(), madness::test_exchange(), test_exchange(), and test_XCOperator().