MADNESS: testdiff2D.cc File Reference
testdiff2D.cc File Reference
testing for diff() in 2D
#include <madness/mra/mra.h>
#include <string>
Typedefs
typedef Vector< double, 2 > coordT
typedef FunctionFactory< double, 2 > factoryT
typedef Function< double, 2 > functionT
typedef Tensor< double > tensorT
Functions
int compare (World &world, functionT test, functionT exact, const char *str)
static double dudx_exact (const coordT &pt)
static double dudy_exact (const coordT &pt)
int main (int argc, char **argv)
static double u_exact (const coordT &pt)
static double xleft_dirichlet (const coordT &pt)
static double xleft_neumann (const coordT &pt)
static double xright_dirichlet (const coordT &pt)
static double xright_neumann (const coordT &pt)
static double yleft_dirichlet (const coordT &pt)
static double yleft_neumann (const coordT &pt)
static double yright_dirichlet (const coordT &pt)
static double yright_neumann (const coordT &pt)
Variables
static const int init_lev = 2
static const int k = 9
static const double Length = 2.
static int test_axis = 0
static const double thresh = 1.e-7
Detailed Description
testing for diff() in 2D
Typedef Documentation
coordT
typedef Vector<double,2> coordT
factoryT
typedef FunctionFactory<double,2> factoryT
functionT
typedef Function<double,2> functionT
tensorT
typedef Tensor<double> tensorT
Function Documentation
compare()
int compare (World & world, functionT test, functionT exact, const char * str)
References madness::error(), exact, madness::nonlinear_vector_solver(), madness::norm2(), madness::World::rank(), test(), and thresh.
Referenced by main().
dudx_exact()
static double dudx_exact (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
dudy_exact()
static double dudy_exact (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::BC_DIRICHLET, madness::BC_FREE, madness::BC_NEUMANN, SafeMPI::COMM_WORLD, compare(), dudx_exact(), dudy_exact(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, init_lev, madness::initialize(), k, Length, madness::nonlinear_vector_solver(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_axis, thresh, u(), u_exact(), xleft_dirichlet(), xleft_neumann(), xright_dirichlet(), xright_neumann(), yleft_dirichlet(), yleft_neumann(), yright_dirichlet(), and yright_neumann().
u_exact()
static double u_exact (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
xleft_dirichlet()
static double xleft_dirichlet (const coordT & pt) static
Referenced by main().
xleft_neumann()
static double xleft_neumann (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
xright_dirichlet()
static double xright_dirichlet (const coordT & pt) static
References Length, and madness::nonlinear_vector_solver().
Referenced by main().
xright_neumann()
static double xright_neumann (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
yleft_dirichlet()
static double yleft_dirichlet (const coordT & pt) static
Referenced by main().
yleft_neumann()
static double yleft_neumann (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
yright_dirichlet()
static double yright_dirichlet (const coordT & pt) static
References Length, and madness::nonlinear_vector_solver().
Referenced by main().
yright_neumann()
static double yright_neumann (const coordT & pt) static
References madness::nonlinear_vector_solver().
Referenced by main().
Variable Documentation
init_lev
const int init_lev = 2 static
Referenced by main().
k
const int k = 9 static
Referenced by main().
Length
const double Length = 2. static
Referenced by main(), xright_dirichlet(), and yright_dirichlet().
test_axis
int test_axis = 0 static
Referenced by main().
thresh
const double thresh = 1.e-7 static
Referenced by compare(), and main().