MADNESS: testunaryop.cc File Reference
testunaryop.cc File Reference
test a unary op
#include <madness/constants.h>
Classes
class Gaussian< T, NDIM >
Functions
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
void squareit (const Key< NDIM > &key, Tensor< T > &t)
template<typename T , std::size_t NDIM>
void test_unaryop (World &world)
Detailed Description
test a unary op
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::World::gop, SafeMPI::Init_thread(), madness::print(), and madness::startup().
squareit()
template<typename T , std::size_t NDIM> void squareit (const Key< NDIM > & key, Tensor< T > & t)
References madness::print(), T(), and UNARY_OPTIMIZED_ITERATOR.
test_unaryop()
template<typename T , std::size_t NDIM> void test_unaryop (World & world)
References madness::copy(), e(), madness::f, madness::WorldGopInterface::fence(), madness::FunctionFactory< T, NDIM >::functor(), madness::g, madness::World::gop, NDIM, norm(), madness::norm2(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), and madness::FunctionDefaults< NDIM >::set_thresh().