MADNESS: test_localizer.cc File Reference
test_localizer.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/vmra.h>
#include <madness/chem/localizer.h>
#include <madness/chem/molecularbasis.h>
#include <madness/chem/MolecularOrbitals.h>
#include <madness/chem/potentialmanager.h>
#include <madness/chem/correlationfactor.h>
#include <madness/world/test_utilities.h>
#include <madness/chem/SCFOperators.h>
#include <madness/chem/SCF.h>
#include <madness/world/timing_utilities.h>
#include <nemo.h>
#include <write_test_input.h>
#include <vector>
Functions
double bend (const Vector< double, 3 > v1, const Vector< double, 3 > v2, const Vector< double, 3 > v3)
angle in degrees between v1–v2–v3 (v2 being the center)
double dist (const Vector< double, 3 > v1, const Vector< double, 3 > v2)
distance between v1 and v2
double fock_trace (const Tensor< double > &fock)
bool is_aligned (const Vector< double, 3 > &v1, const Vector< double, 3 > &v2, const Vector< double, 3 > &v3, const double thresh=1.e-3)
bool is_centered_normal (const Vector< double, 3 > &v1, const Vector< double, 3 > &v2, const Vector< double, 3 > &v3, const double thresh=1.e-3)
check if v3 is orthogonal on v1-v2 midbond
bool is_close (const Vector< double, 3 > &v1, const Vector< double, 3 > &v2, const double thresh=1.e-3)
int main (int argc, char **argv)
bool test_ethylene (World &world, const Nemo &nemo, const std::string geometry="ethylene")
test localized orbitals
bool test_ne_boys (World &world, const Nemo &nemo)
test localized orbitals: should be pointing towards the edges of a tetrahedron
Function Documentation
bend()
double bend (const Vector< double, 3 > v1, const Vector< double, 3 > v2, const Vector< double, 3 > v3)
angle in degrees between v1–v2–v3 (v2 being the center)
References madness::inner(), madness::Vector< T, N >::normf(), and madness::constants::pi.
Referenced by test_ne_boys().
dist()
double dist (const Vector< double, 3 > v1, const Vector< double, 3 > v2)
distance between v1 and v2
Referenced by std::advance(), SurfaceMoleculeInteraction::colloid_coords(), madness::Key< NDIM >::distsq(), madness::Key< NDIM >::is_neighbor_of(), madness::PNO::iterate_pairs_internal(), DF::make_fermi_potential(), DF::make_gaussian_potential(), Sphere::operator()(), DSphere::operator()(), madness::MyPmap< D >::prepare_not_so_simple_map(), madness::SDFParaboloid::sdf(), madness::SDFCylinder::sdf(), test_ne_boys(), and madness::PNO::update_pno().
fock_trace()
double fock_trace (const Tensor< double > & fock)
References madness::BaseTensor::dim(), MADNESS_CHECK, and madness::BaseTensor::ndim().
Referenced by test_ethylene().
is_aligned()
bool is_aligned (const Vector< double, 3 > & v1, const Vector< double, 3 > & v2, const Vector< double, 3 > & v3, const double thresh = 1.e-3)
References a1, a2, madness::inner(), and thresh.
Referenced by test_ethylene().
is_centered_normal()
bool is_centered_normal (const Vector< double, 3 > & v1, const Vector< double, 3 > & v2, const Vector< double, 3 > & v3, const double thresh = 1.e-3)
check if v3 is orthogonal on v1-v2 midbond
References madness::inner(), and thresh.
Referenced by test_ethylene().
is_close()
bool is_close (const Vector< double, 3 > & v1, const Vector< double, 3 > & v2, const double thresh = 1.e-3)
References thresh.
Referenced by test_ethylene().
main()
int main (int argc, char ** argv)
References madness::test_output::end(), madness::timer::end(), madness::write_test_input::filename(), madness::finalize(), madness::initialize(), k, L, param, madness::Nemo::param, madness::QCCalculationParametersBase::print(), madness::print(), madness::commandlineparser::print_map(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::commandlineparser::set_keyval(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_ethylene(), test_ne_boys(), thresh, and madness::Nemo::value().
test_ethylene()
bool test_ethylene (World & world, const Nemo & nemo, const std::string geometry = "ethylene")
test localized orbitals
tests invariance of the Fock matrix trace, core-valence separation and location of orbitals on bonds
References c, madness::Localizer::check_core_valence_separation(), madness::test_output::checkpoint(), madness::Nemo::compute_fock_matrix(), madness::test_output::end(), fock_trace(), madness::Molecule::get_atom(), madness::Nemo::get_calc(), madness::Atom::get_coords(), madness::MolecularOrbitals< T, NDIM >::get_mos(), madness::NemoBase::get_ncf_ptr(), madness::MolecularOrbitals< T, NDIM >::get_occ(), is_aligned(), is_centered_normal(), is_close(), madness::Localizer::localize(), madness::Nemo::molecule(), madness::MolecularOrbitals< T, NDIM >::pretty_print(), madness::Molecule::print(), madness::print(), madness::Localizer::print_info(), madness::MolecularOrbitals< T, NDIM >::recompute_localize_sets(), madness::MolecularOrbitals< T, NDIM >::set_all_orbitals_occupied(), madness::Localizer::set_enforce_core_valence_separation(), madness::Localizer::set_method(), madness::Localizer::set_metric(), and madness::MolecularOrbitals< T, NDIM >::update_mos_and_eps().
Referenced by main().
test_ne_boys()
bool test_ne_boys (World & world, const Nemo & nemo)
test localized orbitals: should be pointing towards the edges of a tetrahedron
References bend(), madness::Nemo::compute_fock_matrix(), dist(), madness::test_output::end(), madness::Nemo::get_calc(), madness::MolecularOrbitals< T, NDIM >::get_mos(), madness::NemoBase::get_ncf_ptr(), madness::MolecularOrbitals< T, NDIM >::get_occ(), madness::Localizer::localize(), madness::Nemo::molecule(), madness::MolecularOrbitals< T, NDIM >::pretty_print(), madness::print(), madness::Localizer::print_info(), madness::MolecularOrbitals< T, NDIM >::recompute_localize_sets(), madness::MolecularOrbitals< T, NDIM >::set_all_orbitals_occupied(), madness::Localizer::set_enforce_core_valence_separation(), madness::Localizer::set_method(), and madness::MolecularOrbitals< T, NDIM >::update_mos_and_eps().
Referenced by main().