MADNESS: test_low_rank_function.cc File Reference
test_low_rank_function.cc File Reference
#include <madness.h>
#include <madness/chem/lowrankfunction.h>
#include <madness/world/test_utilities.h>
#include <madness/world/timing_utilities.h>
#include <random>
Functions
int main (int argc, char **argv)
template<std::size_t LDIM>
int test_arithmetic (World &world, LowRankFunctionParameters parameters)
template<std::size_t LDIM>
int test_construction_optimization (World &world, LowRankFunctionParameters parameters)
template<std::size_t LDIM>
int test_full_rank_functor (World &world, LowRankFunctionParameters parameters)
template<std::size_t LDIM>
int test_inner (World &world, LowRankFunctionParameters parameters)
test partial inner products
int test_Kcommutator (World &world, LowRankFunctionParameters &parameters)
test the K commutator of the He atom
int test_lowrank_function (World &world, LowRankFunctionParameters parameters)
template<std::size_t LDIM>
int test_molecular_grid (World &world, LowRankFunctionParameters parameters)
Function Documentation
main()
int main (int argc, char ** argv)
References e(), madness::finalize(), madness::initialize(), k, madness::commandlineparser::key_exists(), madness::QCCalculationParametersBase::print(), madness::print(), madness::LowRankFunctionParameters::read_and_set_derived_values(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::QCCalculationParametersBase::set_derived_value(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::QCCalculationParametersBase::set_user_defined_value(), madness::startup(), thresh, madness::TT_2D, madness::TT_FULL, and madness::commandlineparser::value().
test_arithmetic()
template<std::size_t LDIM> int test_arithmetic (World & world, LowRankFunctionParameters parameters)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::Vector< T, N >::fill(), madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), NDIM, madness::print(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::test_output::set_cout_to_terminal(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_orthomethod(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_radius(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_rank_revealing_tol(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_volume_element(), and thresh.
test_construction_optimization()
template<std::size_t LDIM> int test_construction_optimization (World & world, LowRankFunctionParameters parameters)
References madness::test_output::checkpoint(), madness::test_output::end(), madness::error(), madness::FunctionFactory< T, NDIM >::functor(), madness::inner(), MADNESS_CHECK, NDIM, norm(), one(), madness::OT_SLATER, madness::print(), madness::print_header2(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), and madness::test_output::set_cout_to_terminal().
test_full_rank_functor()
template<std::size_t LDIM> int test_full_rank_functor (World & world, LowRankFunctionParameters parameters)
References a, b, madness::test_output::checkpoint(), madness::test_output::end(), madness::LRFunctorPure< T, NDIM, LDIM >::f, madness::FunctionFactory< T, NDIM >::functor(), madness::inner(), NDIM, madness::print(), madness::print_header2(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::test_output::set_cout_to_terminal(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_orthomethod(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_radius(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_rank_revealing_tol(), and madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_volume_element().
test_inner()
template<std::size_t LDIM> int test_inner (World & world, LowRankFunctionParameters parameters)
test partial inner products
with f1(x,y) = exp(-a*x^2) * exp(-(x-y)^2) f2(x,y) = exp(-a*x^2) * exp(-g (x-y)^2) test the inner products a) inner(f1,f2,i,j) for i,j=0,1 b) inner(f1,
References a, madness::arg(), madness::test_output::checkpoint(), madness::test_output::end(), madness::FunctionFactory< T, NDIM >::functor(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), NDIM, madness::norm2(), madness::Vector< T, N >::normf(), madness::particle< PDIM >::particle1(), madness::particle< PDIM >::particle2(), madness::print(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_orthomethod(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_radius(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_rank_revealing_tol(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::set_volume_element(), and thresh.
test_Kcommutator()
int test_Kcommutator (World & world, LowRankFunctionParameters & parameters)
test the K commutator of the He atom
< ij | K f12 | ij >
References madness::Function< T, NDIM >::change_tree_state(), madness::copy(), madness::CoulombOperator(), madness::cpu_time(), dcut, madness::TwoElectronFactory< T, NDIM >::dcut(), madness::default_random_generator, madness::test_output::end(), madness::TwoElectronFactory< T, NDIM >::f12(), madness::LowRankFunctionParameters::f12type(), madness::Function< T, NDIM >::fill_tree(), madness::LowRankFunction< T, NDIM, LDIM >::g, madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::LowRankFunctionParameters::gamma(), madness::TwoElectronFactory< T, NDIM >::gamma(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::LowRankFunctionParameters::gridtype(), madness::LowRankFunction< T, NDIM, LDIM >::h, madness::inner(), MADNESS_EXCEPTION, madness::mul(), madness::multiply(), NDIM, madness::Function< T, NDIM >::norm2(), madness::Vector< T, N >::normf(), one(), madness::LowRankFunctionParameters::optimize(), madness::LowRankFunctionParameters::orthomethod(), madness::SeparatedConvolution< Q, NDIM >::particle(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::QCCalculationParametersBase::print(), madness::print(), madness::Function< T, NDIM >::print_size(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::LowRankFunctionParameters::radius(), madness::reconstructed, madness::LowRankFunctionParameters::rhsfunctiontype(), madness::Function< T, NDIM >::scale(), madness::test_output::set_cout_to_terminal(), madness::Random::setstate(), madness::SlaterF12OperatorPtr(), madness::SlaterOperatorPtr(), madness::timer::tag(), thresh, madness::TwoElectronFactory< T, NDIM >::thresh(), madness::LowRankFunctionParameters::tol(), madness::unique_fileid(), and madness::LowRankFunctionParameters::volume_element().
test_lowrank_function()
int test_lowrank_function (World & world, LowRankFunctionParameters parameters)
References madness::cpu_time(), madness::default_random_generator, diff(), madness::test_output::end(), madness::error(), madness::LowRankFunctionParameters::f12type(), madness::Vector< T, N >::fill(), madness::FunctionFactory< T, NDIM >::functor(), madness::Function< T, NDIM >::g(), madness::LowRankFunctionParameters::gamma(), madness::QCCalculationParametersBase::get(), madness::LowRankFunctionParameters::gridtype(), madness::inner(), MADNESS_EXCEPTION, NDIM, madness::Function< T, NDIM >::norm2(), offset, one(), madness::LowRankFunctionParameters::optimize(), madness::LowRankFunctionParameters::orthomethod(), madness::QCCalculationParametersBase::print(), madness::print(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::LowRankFunctionParameters::radius(), madness::World::rank(), madness::LowRankFunctionParameters::rhsfunctiontype(), madness::test_output::set_cout_to_terminal(), madness::Random::setstate(), madness::SlaterF12OperatorPtr(), madness::SlaterOperatorPtr(), madness::LowRankFunctionParameters::tol(), madness::transpose(), madness::unique_fileid(), and madness::LowRankFunctionParameters::volume_element().
test_molecular_grid()
template<std::size_t LDIM> int test_molecular_grid (World & world, LowRankFunctionParameters parameters)
References c, madness::test_output::checkpoint(), madness::test_output::end(), madness::error(), madness::FunctionFactory< T, NDIM >::functor(), madness::molecular_grid< NDIM >::get_grid(), madness::grid(), madness::inner(), MADNESS_CHECK, NDIM, norm(), one(), madness::LowRankFunctionParameters::optimize(), madness::OT_SLATER, madness::QCCalculationParametersBase::print(), madness::print(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::test_output::set_cout_to_terminal(), and madness::gridbase::visualize().