MADNESS: test_gmres.cc File Reference
test_gmres.cc File Reference
#include <madness/mra/mra.h>
#include <madness/tensor/gmres.h>
Classes
class ComplexFuncIdentOp
the identity operator for a complex function
class ComplexFuncLinearOp
class ComplexVecIdentOp
the identity operator for complex vectors
class ComplexVecLinearOp
an arbitrary operator for complex vectors
class RealFuncIdentOp
the identity operator for a real function
class RealFuncLinearOp
class RealVecIdentOp
the identity operator for real vectors
class RealVecLinearOp
an arbitrary operator for real vectors
Typedefs
typedef bool(* testptr) (void)
function pointer typedef (for making an array)
Functions
bool cplxfunc0 ()
test complex functions, converge after 0 steps
bool cplxfunc1 ()
test complex functions, converge after 1 step
bool cplxfunc2 ()
test complex functions, converge after >1 steps
bool cplxvec0 ()
test complex vectors, converge after 0 steps
bool cplxvec1 ()
test complex vectors, converge after 1 step
bool cplxvec2 ()
test complex vectors, converge after >1 steps
template<typename T >
static void invert (const Key< 3 > &key, Tensor< T > &t)
static double magfunc (const Vector< double, 3 > &pt)
Some functions for testing MADNESS Functions...
int main (int argc, char **argv)
main routine: execute the tests
bool realfunc0 ()
test real functions, converge after 0 steps
bool realfunc1 ()
test real functions, converge after 1 step
bool realfunc2 ()
test real functions, converge after >1 steps
bool realvec0 ()
test real vectors, converge on zeroth step
bool realvec1 ()
test real vectors, converge after 1 step
bool realvec2 ()
test real vectors, converge after >1 steps
static std::complex< double > zmagfunc (const Vector< double, 3 > &pt)
Variables
const int NTESTS = 12
test functions: true for success, false for failure
World * worldptr
pointer to the world
Typedef Documentation
testptr
typedef bool(* testptr) (void)
function pointer typedef (for making an array)
Function Documentation
cplxfunc0()
bool cplxfunc0 ()
test complex functions, converge after 0 steps
References b, madness::copy(), madness::FunctionFactory< T, NDIM >::f(), madness::GMRES(), lo, madness::FunctionSpace< T, NDIM >::norm(), worldptr, and zmagfunc().
Referenced by main().
cplxfunc1()
bool cplxfunc1 ()
test complex functions, converge after 1 step
References b, madness::FunctionFactory< T, NDIM >::f(), madness::GMRES(), lo, madness::FunctionSpace< T, NDIM >::norm(), madness::Function< T, NDIM >::truncate(), worldptr, and zmagfunc().
Referenced by main().
cplxfunc2()
bool cplxfunc2 ()
test complex functions, converge after >1 steps
References madness::Function< T, NDIM >::add_scalar(), b, madness::copy(), madness::FunctionFactory< T, NDIM >::f(), madness::GMRES(), lo, madness::FunctionSpace< T, NDIM >::norm(), madness::Function< T, NDIM >::truncate(), madness::Function< T, NDIM >::unaryop(), worldptr, and zmagfunc().
Referenced by main().
cplxvec0()
bool cplxvec0 ()
test complex vectors, converge after 0 steps
References b, madness::GMRES(), lo, madness::VectorSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
cplxvec1()
bool cplxvec1 ()
test complex vectors, converge after 1 step
References b, madness::GMRES(), lo, madness::VectorSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
cplxvec2()
bool cplxvec2 ()
test complex vectors, converge after >1 steps
References b, madness::GMRES(), lo, madness::VectorSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
invert()
template<typename T > static void invert (const Key< 3 > & key, Tensor< T > & t) inline static
References T(), and UNARY_OPTIMIZED_ITERATOR.
magfunc()
static double magfunc (const Vector< double, 3 > & pt) static
Some functions for testing MADNESS Functions...
Referenced by realfunc0(), realfunc1(), and realfunc2().
main()
int main (int argc, char ** argv)
main routine: execute the tests
References bufsize, SafeMPI::COMM_WORLD, cplxfunc0(), cplxfunc1(), cplxfunc2(), cplxvec0(), cplxvec1(), cplxvec2(), madness::finalize(), madness::initialize(), NTESTS, realfunc0(), realfunc1(), realfunc2(), realvec0(), realvec1(), realvec2(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_max_refine_level(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and worldptr.
realfunc0()
bool realfunc0 ()
test real functions, converge after 0 steps
References b, madness::copy(), madness::FunctionFactory< T, NDIM >::f(), madness::GMRES(), lo, magfunc(), madness::FunctionSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
realfunc1()
bool realfunc1 ()
test real functions, converge after 1 step
References b, madness::FunctionFactory< T, NDIM >::f(), madness::GMRES(), lo, magfunc(), madness::FunctionSpace< T, NDIM >::norm(), madness::Function< T, NDIM >::truncate(), and worldptr.
Referenced by main().
realfunc2()
bool realfunc2 ()
test real functions, converge after >1 steps
References madness::Function< T, NDIM >::add_scalar(), b, madness::Function< T, NDIM >::compress(), madness::copy(), madness::FunctionFactory< T, NDIM >::f(), madness::GMRES(), lo, magfunc(), madness::FunctionSpace< T, NDIM >::norm(), madness::Function< T, NDIM >::truncate(), madness::Function< T, NDIM >::unaryop(), and worldptr.
Referenced by main().
realvec0()
bool realvec0 ()
test real vectors, converge on zeroth step
References b, madness::GMRES(), lo, madness::VectorSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
realvec1()
bool realvec1 ()
test real vectors, converge after 1 step
References b, madness::GMRES(), lo, madness::VectorSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
realvec2()
bool realvec2 ()
test real vectors, converge after >1 steps
References b, madness::GMRES(), lo, madness::VectorSpace< T, NDIM >::norm(), and worldptr.
Referenced by main().
zmagfunc()
static std::complex< double > zmagfunc (const Vector< double, 3 > & pt) static
Referenced by cplxfunc0(), cplxfunc1(), and cplxfunc2().
Variable Documentation
NTESTS
const int NTESTS = 12
test functions: true for success, false for failure
Referenced by main().
worldptr
World* worldptr
pointer to the world
Referenced by cplxfunc0(), cplxfunc1(), cplxfunc2(), cplxvec0(), cplxvec1(), cplxvec2(), main(), realfunc0(), realfunc1(), realfunc2(), realvec0(), realvec1(), and realvec2().