MADNESS: test.cc File Reference
test.cc File Reference
Tests serialization by some of the archives.
#include "testpc.h"
#include <fftw3.h>
Functions
int main ()
Detailed Description
Tests serialization by some of the archives.
Function Documentation
main()
int main (void)
References exact, f, G, g(), h(), kx, ky, kz, L, linspace(), lo, madness::detail::norm(), pi, madness::reduce(), madness::scale(), set_test_case(), tabulate(), u(), and v.