MADNESS: test_queue.cc File Reference
test_queue.cc File Reference
#include <madness/world/MADworld.h>
Classes
class Task
Functions
void cleanup_tls ()
unsigned long * get_tls ()
void init_tls (const unsigned long nthreads)
int main (int argc, char **argv)
Variables
const int NGEN =100
const int NTASK =100000
unsigned long * thread_counters = nullptr
madness::AtomicInt thread_index
pthread_key_t thread_key
madness::AtomicInt total_count
Function Documentation
cleanup_tls()
void cleanup_tls ()
References thread_counters, and thread_key.
Referenced by main().
get_tls()
unsigned long* get_tls ()
References thread_counters, thread_index, and thread_key.
Referenced by init_tls(), and Task::run().
init_tls()
void init_tls (const unsigned long nthreads)
References get_tls(), thread_counters, thread_index, and thread_key.
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::WorldTaskQueue::add(), madness::World::await(), cleanup_tls(), SafeMPI::COMM_WORLD, madness::finalize(), Task::finished(), init_tls(), madness::initialize(), NGEN, NTASK, madness::ThreadPool::size(), smalltest, madness::World::taskq, thread_counters, total_count, and madness::wall_time().
Variable Documentation
NGEN
const int NGEN =100
Referenced by Task::finished(), and main().
NTASK
const int NTASK =100000
Referenced by Task::finished(), and main().
thread_counters
unsigned long* thread_counters = nullptr
Referenced by cleanup_tls(), get_tls(), init_tls(), and main().
thread_index
madness::AtomicInt thread_index
Referenced by get_tls(), and init_tls().
thread_key
pthread_key_t thread_key
Referenced by cleanup_tls(), get_tls(), and init_tls().
total_count
madness::AtomicInt total_count
Referenced by Task::finished(), main(), and Task::run().