MADNESS: test_systolic.cc File Reference
test_systolic.cc File Reference
#include <madness/world/MADworld.h>
#include <utility>
#include <madness/tensor/tensor.h>
#include <madness/tensor/systolic.h>
Classes
class TestSystolicMatrixAlgorithm< T >
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::_(), madness::WorldTaskQueue::add(), SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldTaskQueue::fence(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, m, MADNESS_CHECK, madness::print(), madness::redirectio(), and madness::World::taskq.