MADNESS: testpercoul.cc File Reference
testpercoul.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
Functions
int main (int argc, char **argv)
static double rho_gaussian_func3d (const madness::coord_3d &r)
Variables
const double L = 10
Function Documentation
main()
int main (int argc, char ** argv)
References madness::apply(), madness::BC_PERIODIC, madness::CoulombOperator(), e(), madness::error(), madness::FunctionFactory< T, NDIM >::f(), madness::finalize(), madness::FunctionFactory< T, NDIM >::initial_level(), madness::initialize(), k, L, p(), madness::pop(), madness::Function< T, NDIM >::reconstruct(), rho_gaussian_func3d(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionFactory< T, NDIM >::special_points(), madness::startup(), thresh, and madness::Function< T, NDIM >::truncate().
rho_gaussian_func3d()
static double rho_gaussian_func3d (const madness::coord_3d & r) static
References pow().
Referenced by main().
Variable Documentation
L
const double L = 10
Referenced by main().