MADNESS: test_runtime.cpp File Reference
test_runtime.cpp File Reference
#include <madness/world/worldgop.h>
#include <cassert>
Functions
int main (int argc, char *argv[])
int task (int i)
Function Documentation
main()
int main (int argc, char * argv[])
References madness::WorldTaskQueue::add(), madness::f, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), me, madness::World::rank(), madness::World::size(), task(), and madness::World::taskq.
task()
int task (int i)
Referenced by madness::CubicInterpolationTable< T >::CubicInterpolationTable(), madness::FunctionNode< T, NDIM >::accumulate(), madness::FunctionNode< T, NDIM >::accumulate2(), madness::ThreadPool::add(), madness::FunctionImpl< R, NDIM >::autorefine_square_test(), madness::LBNodeDeux< NDIM >::deleter(), madness::FunctionImpl< T, NDIM >::eval(), madness::FunctionImpl< T, NDIM >::eval_plot_cube(), madness::FunctionImpl< T, NDIM >::evaldepthpt(), madness::FunctionImpl< T, NDIM >::evalR(), madness::FunctionImpl< T, NDIM >::gaxpy_oop_reconstructed(), madness::FunctionImpl< T, NDIM >::get_norm_tree_recursive(), madness::innerXX(), main(), madness::CubicInterpolationTable< T >::make_interpolation(), madness::Coulomb< T, NDIM >::operator()(), madness::LBNodeDeux< NDIM >::partition(), Foo::ping(), Foo::pong(), madness::FunctionImpl< T, NDIM >::project_refine_op(), madness::FunctionImpl< T, NDIM >::reconstruct(), madness::FunctionImpl< T, NDIM >::reconstruct_op(), madness::FunctionImpl< T, NDIM >::refine_to_common_level(), madness::WorldTaskQueue::remote_task_handler(), madness::FunctionNode< T, NDIM >::set_has_children_recursive(), madness::FunctionImpl< T, NDIM >::sock_it_to_me(), madness::FunctionImpl< T, NDIM >::sock_it_to_me_too(), madness::CC2::solve_mp2_coupled(), madness::LBNodeDeux< NDIM >::sum(), madness::FunctionImpl< R, NDIM >::sum_down(), madness::FunctionImpl< T, NDIM >::sum_down_spawn(), test5(), test_2d_partitioning(), test_deferred(), test_twice(), madness::FunctionImpl< T, NDIM >::trickle_down(), madness::FunctionImpl< T, NDIM >::trickle_down_op(), madness::FunctionImpl< T, NDIM >::truncate_reconstructed_spawn(), and madness::FunctionImpl< T, NDIM >::truncate_spawn().