MADNESS: test_QCCalculationParametersBase.cc File Reference
test_QCCalculationParametersBase.cc File Reference
#include "QCCalculationParametersBase.h"
#include "parallel_archive.h"
Classes
struct inputfile
class Parameters
Functions
int main (int argc, char **argv)
bool test_capitalization (World &world)
bool test_comment_lines (World &world)
bool test_derived (World &world)
bool test_empty_lines (World &world)
bool test_not_allowed (World &world)
template<typename T >
void test_same (const T &t1, const T &t2)
bool test_serialize (World &world)
template<typename T >
bool test_trailing_characters (World &world)
bool test_type_conversion1 (World &world)
bool test_type_conversion2 (World &world)
bool test_type_conversion3 (World &world)
bool test_type_conversion4 (World &world)
bool test_type_conversion5 (World &world)
bool test_type_conversion6 (World &world)
bool test_type_conversion7 (World &world)
bool test_type_conversion8 (World &world)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), test_capitalization(), test_comment_lines(), test_derived(), test_empty_lines(), test_not_allowed(), test_serialize(), test_type_conversion1(), test_type_conversion2(), test_type_conversion3(), test_type_conversion5(), test_type_conversion6(), test_type_conversion7(), test_type_conversion8(), and madness::wall_time().
test_capitalization()
bool test_capitalization (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_comment_lines()
bool test_comment_lines (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_derived()
bool test_derived (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_empty_lines()
bool test_empty_lines (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_not_allowed()
bool test_not_allowed (World & world)
References errmsg(), madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_same()
template<typename T > void test_same (const T & t1, const T & t2)
References madness::nonlinear_vector_solver(), and madness::print().
Referenced by test_capitalization(), test_comment_lines(), test_derived(), test_empty_lines(), test_not_allowed(), test_serialize(), test_trailing_characters(), test_type_conversion1(), test_type_conversion2(), test_type_conversion3(), test_type_conversion4(), test_type_conversion5(), test_type_conversion6(), test_type_conversion7(), and test_type_conversion8().
test_serialize()
bool test_serialize (World & world)
References madness::name(), madness::nonlinear_vector_solver(), param, madness::QCCalculationParametersBase::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_trailing_characters()
template<typename T > bool test_trailing_characters (World & world)
References errmsg(), madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
test_type_conversion1()
bool test_type_conversion1 (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_type_conversion2()
bool test_type_conversion2 (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_type_conversion3()
bool test_type_conversion3 (World & world)
References errmsg(), madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_type_conversion4()
bool test_type_conversion4 (World & world)
References errmsg(), madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
test_type_conversion5()
bool test_type_conversion5 (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_type_conversion6()
bool test_type_conversion6 (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_type_conversion7()
bool test_type_conversion7 (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().
test_type_conversion8()
bool test_type_conversion8 (World & world)
References madness::nonlinear_vector_solver(), param, madness::print(), madness::commandlineparser::set_keyval(), and test_same().
Referenced by main().