MADNESS: test_IntegratorXX.cc File Reference
test_IntegratorXX.cc File Reference
#include <madness.h>
#include <madness/world/test_utilities.h>
#include <madness/chem/IntegratorXX.h>
Classes
struct spherical_harmonic
Functions
double dx2y2_func (const Vector< double, 3 > &r)
double dxy_func (const Vector< double, 3 > &r)
double dxz_func (const Vector< double, 3 > &r)
double dyz_func (const Vector< double, 3 > &r)
double dz2_func (const Vector< double, 3 > &r)
int main (int argc, char **argv)
double px_func (const Vector< double, 3 > &r)
double py_func (const Vector< double, 3 > &r)
double pz_func (const Vector< double, 3 > &r)
double s_func (const Vector< double, 3 > &r)
int test_construction ()
int test_integration (World &world)
Function Documentation
dx2y2_func()
double dx2y2_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
dxy_func()
double dxy_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
dxz_func()
double dxz_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
dyz_func()
double dyz_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
dz2_func()
double dz2_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_construction(), and test_integration().
px_func()
double px_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
py_func()
double py_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
pz_func()
double pz_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
s_func()
double s_func (const Vector< double, 3 > & r)
References madness::inner().
Referenced by spherical_harmonic::spherical_harmonic().
test_construction()
int test_construction ()
References madness::test_output::end(), GridBuilder::get_points(), GridBuilder::make_grid(), and madness::points.
Referenced by main().
test_integration()
int test_integration (World & world)
References std::abs(), madness::test_output::checkpoint(), madness::test_output::end(), madness::error(), exact, madness::f, GridBuilder::get_angular_order(), GridBuilder::get_nradial(), GridBuilder::get_points(), GridBuilder::get_weights(), madness::inner(), m, GridBuilder::make_grid(), madness::Function< T, NDIM >::norm2(), madness::points, pow(), madness::print(), madness::r2(), GridBuilder::set_angular_order(), GridBuilder::set_nradial(), GridBuilder::set_origin(), madness::BaseTensor::size(), and madness::weights.
Referenced by main().