MADNESS: test_jacobi.cc File Reference
test_jacobi.cc File Reference
#include <madness/world/madness_exception.h>
#include <madness/tensor/tensor.h>
#include <madness/world/print.h>
#include <cmath>
#include <cstdio>
#include <algorithm>
Macros
#define ROT(A, i, j)
#define ROTT(A, i, j)
Functions
double drand48 (void)
void jacobi (Tensor< double > &A, Tensor< double > &V, const std::vector< int > &set)
int main ()
Macro Definition Documentation
ROT
#define ROT (A, i, j)
Value:
    { \
      double * __restrict__ ai = &A(i,0); \
      double * __restrict__ aj = &A(j,0); \
      for (k=0; k<n; k++) { \
          double t = ai[k]; \
          double u = aj[k]; \
          ai[k] = c*t - s*u; \
          aj[k] = s*t + c*u; \
      } \
    }
ROTT
#define ROTT (A, i, j)
Value:
    { \
      double * __restrict__ ai = &A(0,i);      \
      double * __restrict__ aj = &A(0,j);       \
      for (k=0; k<n*n; k+=n) { \
          double t = ai[k]; \
          double u = aj[k]; \
          ai[k] = c*t - s*u; \
          aj[k] = s*t + c*u; \
      } \
    }
Function Documentation
drand48()
double drand48 (void)
Referenced by main(), opt(), and test2().
jacobi()
void jacobi (Tensor< double > & A, Tensor< double > & V, const std::vector< int > & set)
References A(), c, e(), k, MADNESS_CHECK, max, ROT, u(), and V().
main()
int main (void)
References a, aa, madness::copy(), drand48(), madness::inner(), madness::jacobi(), longtest, N, madness::print(), and v.