MADNESS: test_pointgroupsymmetry.cc File Reference
test_pointgroupsymmetry.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/functypedefs.h>
#include <madness/chem/pointgroupoperator.h>
#include <madness/chem/pointgroupsymmetry.h>
Namespaces
namespace madness
Namespace for all elements and tools of MADNESS.
Functions
int check_multiplication_table_c2v (World &world)
perform all operator multiplication of the c2v group, subtract the result
int check_operator_multiplications_2d (World &world)
test a small number of operator multiplications, including a hard-wire test
int check_operator_multiplications_3d (World &world)
test a small number of operator multiplications, including a hard-wire test
std::vector< std::string > madness::cubefile_header (std::string filename="input", const bool &no_orient=false)
double dgaussian (const coord_3d &r)
double gaussian_shift_2d (const coord_2d &r)
double gaussian_shift_3d (const coord_3d &r)
int main (int argc, char **argv)
double one1 (const coord_3d &r)
void plot_symmetry_operators (World &world)
double s_x_gaussian_shift_2d (const coord_2d &r)
double s_xz_dgaussian (const coord_3d &r)
int test_orthogonalization (World &world)
int test_projector (World &world)
symmetrize a trial function, check its behavior according to the group table
double xyyygaussian (const coord_2d &r)
Function Documentation
check_multiplication_table_c2v()
int check_multiplication_table_c2v (World & world)
perform all operator multiplication of the c2v group, subtract the result
References a1, a2, dgaussian(), e(), madness::norm2(), p(), madness::pg_c2x(), madness::pg_c2y(), madness::pg_c2z(), madness::pg_c4x(), madness::pg_c4y(), madness::pg_c4z(), madness::pg_identity(), madness::pg_inversion(), madness::pg_sigma_xy(), madness::pg_sigma_xz(), madness::pg_sigma_yz(), and madness::print().
Referenced by main().
check_operator_multiplications_2d()
int check_operator_multiplications_2d (World & world)
test a small number of operator multiplications, including a hard-wire test
References e(), gaussian_shift_2d(), madness::norm2(), p(), madness::pg_c2(), madness::pg_c4(), madness::pg_identity(), madness::pg_inversion(), madness::pg_sigma_x(), madness::pg_sigma_y(), madness::print(), and s_x_gaussian_shift_2d().
Referenced by main().
check_operator_multiplications_3d()
int check_operator_multiplications_3d (World & world)
test a small number of operator multiplications, including a hard-wire test
References dgaussian(), e(), madness::Function< T, NDIM >::norm2(), madness::norm2(), p(), madness::pg_c2x(), madness::pg_c2y(), madness::pg_c2z(), madness::pg_c4x(), madness::pg_c4y(), madness::pg_c4z(), madness::pg_identity(), madness::pg_inversion(), madness::pg_sigma_xy(), madness::pg_sigma_xz(), madness::pg_sigma_yz(), madness::print(), and s_xz_dgaussian().
Referenced by main().
dgaussian()
double dgaussian (const coord_3d & r)
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), and plot_symmetry_operators().
gaussian_shift_2d()
double gaussian_shift_2d (const coord_2d & r)
Referenced by check_operator_multiplications_2d(), and plot_symmetry_operators().
gaussian_shift_3d()
double gaussian_shift_3d (const coord_3d & r)
Referenced by test_orthogonalization(), and test_projector().
main()
int main (int argc, char ** argv)
References check_multiplication_table_c2v(), check_operator_multiplications_2d(), check_operator_multiplications_3d(), SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::startup(), test_orthogonalization(), and test_projector().
one1()
double one1 (const coord_3d & r)
Referenced by Ansatz0::R(), Ansatz0::Rinv(), and test_orthogonalization().
plot_symmetry_operators()
void plot_symmetry_operators (World & world)
References dgaussian(), e(), madness::f, gaussian_shift_2d(), p(), madness::pg_c2x(), madness::pg_c2y(), madness::pg_c2z(), madness::pg_c4(), madness::pg_c4x(), madness::pg_c4y(), madness::pg_c4z(), madness::pg_identity(), madness::pg_inversion(), madness::pg_sigma_x(), madness::pg_sigma_xy(), madness::pg_sigma_xz(), madness::pg_sigma_y(), madness::pg_sigma_yz(), madness::plot_plane(), and madness::print().
s_x_gaussian_shift_2d()
double s_x_gaussian_shift_2d (const coord_2d & r)
Referenced by check_operator_multiplications_2d().
s_xz_dgaussian()
double s_xz_dgaussian (const coord_3d & r)
Referenced by check_operator_multiplications_3d().
test_orthogonalization()
int test_orthogonalization (World & world)
References madness::projector_irrep::create_symmetry_adapted_basis(), madness::BaseTensor::dim(), e(), madness::error(), madness::f, gaussian_shift_3d(), madness::projector_irrep::get_table(), madness::matrix_inner(), norm(), madness::Function< T, NDIM >::norm2(), madness::Tensor< T >::normf(), one(), one1(), madness::charactertable::operators_, madness::charactertable::order_, madness::pg_c2x(), madness::pg_c2y(), madness::pg_c2z(), madness::pg_c4x(), madness::pg_c4y(), madness::pg_c4z(), madness::pg_identity(), madness::pg_inversion(), madness::pg_sigma_xy(), madness::pg_sigma_xz(), madness::pg_sigma_yz(), madness::print(), madness::projector_irrep::set_verbosity(), and madness::BaseTensor::size().
Referenced by main().
test_projector()
int test_projector (World & world)
symmetrize a trial function, check its behavior according to the group table
References madness::error(), madness::f, f1, gaussian_shift_3d(), madness::projector_irrep::get_all_irreps(), madness::projector_irrep::get_table(), madness::charactertable::irreps_, madness::pg_operator::name(), madness::norm2(), madness::charactertable::operators_, madness::charactertable::order_, madness::print(), and madness::projector_irrep::set_irrep().
Referenced by main().
xyyygaussian()
double xyyygaussian (const coord_2d & r)