MADNESS: tiny.cc File Reference
tiny.cc File Reference
Solves the Hartree-Fock and MP2 equations for the helium atom.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/funcplot.h>
#include <madness/mra/lbdeux.h>
#include <iostream>
Namespaces
namespace madness
Namespace for all elements and tools of MADNESS.
Functions
std::vector< std::string > madness::cubefile_header (std::string filename="input", const bool &no_orient=false)
void dostuff (World &world)
template<size_t NDIM>
void draw_circle (World &world, Function< double, NDIM > &pair, const std::string restart_name)
template<size_t NDIM>
void draw_line (World &world, Function< double, NDIM > &pair, const std::string restart_name)
template<size_t NDIM>
void load_function (World &world, Function< double, NDIM > &pair, const std::string name)
int main (int argc, char **argv)
template<size_t NDIM>
void save_function (World &world, Function< double, NDIM > &pair, const std::string name)
Detailed Description
Solves the Hartree-Fock and MP2 equations for the helium atom.
Function Documentation
dostuff()
void dostuff (World & world)
References madness::WorldGopInterface::fence(), madness::FunctionDefaults< NDIM >::get_cell_min_width(), madness::World::gop, gradop, madness::Function< T, NDIM >::k(), madness::load(), madness::nonlinear_vector_solver(), madness::plot_line(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::refine(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::SmoothingOperator3D(), and madness::Function< T, NDIM >::thresh().
draw_circle()
template<size_t NDIM> void draw_circle (World & world, Function< double, NDIM > & pair, const std::string restart_name)
References madness::filename, and madness::nonlinear_vector_solver().
draw_line()
template<size_t NDIM> void draw_line (World & world, Function< double, NDIM > & pair, const std::string restart_name)
References madness::filename, madness::trajectory< NDIM >::line2(), lo, and madness::nonlinear_vector_solver().
load_function()
template<size_t NDIM> void load_function (World & world, Function< double, NDIM > & pair, const std::string name)
References madness::name(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_k(), and madness::FunctionDefaults< NDIM >::set_thresh().
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::arg(), c, cc, SafeMPI::COMM_WORLD, madness::cubefile_header(), madness::f, madness::WorldGopInterface::fence(), madness::filename, madness::FunctionDefaults< NDIM >::get_cell_min_width(), madness::World::gop, madness::initialize(), L, load_function(), MADNESS_EXCEPTION, NDIM, madness::nonlinear_vector_solver(), madness::plot_line(), madness::plot_plane(), madness::position_stream(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::World::size(), madness::startup(), madness::stringify(), and madness::TT_FULL.
save_function()
template<size_t NDIM> void save_function (World & world, Function< double, NDIM > & pair, const std::string name)
References madness::name(), madness::nonlinear_vector_solver(), madness::print(), and madness::World::rank().