MADNESS: transform3d.cc File Reference
transform3d.cc File Reference
Functions
template Tensor< double > transform3d (const Tensor< double > &t, const Tensor< double > &c)
Tensor< double_complex > transform3d (const Tensor< double_complex > &t, const Tensor< double > &c)
template<class T >
Tensor< T > transform3d (const Tensor< T > &t, const Tensor< T > &c)
template Tensor< double > transform3d_3c (const Tensor< double > &t, const Tensor< double > &c0, const Tensor< double > &c1, const Tensor< double > &c2)
template<class T >
Tensor< T > transform3d_3c (const Tensor< T > &t, const Tensor< T > &c0, const Tensor< T > &c1, const Tensor< T > &c2)
Function Documentation
transform3d() [1/3]
template Tensor< double > transform3d (const Tensor< double > & t, const Tensor< double > & c)
transform3d() [2/3]
Tensor< double_complex > transform3d (const Tensor< double_complex > & t, const Tensor< double > & c)
References c, k, sum, TENSOR_ASSERT, and TENSOR_EXCEPTION.
transform3d() [3/3]
template<class T > Tensor< T > transform3d (const Tensor< T > & t, const Tensor< T > & c)
optomized 3d transform c must be 2d tensor(matrix) and must square t must be 3d tensor and must be a cube t and c dims must match t and c must be contiguous
result(i,j,k) <-- sum(i',j',k') A(i',j',k') C(i',i) C(j',j) C(k',k)
References c, mTxm(), T(), TENSOR_ASSERT, and transform().
Referenced by main().
transform3d_3c() [1/2]
template Tensor< double > transform3d_3c (const Tensor< double > & t, const Tensor< double > & c0, const Tensor< double > & c1, const Tensor< double > & c2)
transform3d_3c() [2/2]
template<class T > Tensor< T > transform3d_3c (const Tensor< T > & t, const Tensor< T > & c0, const Tensor< T > & c1, const Tensor< T > & c2)
optomized 3d transform with three different C's all three c must be 2d tensor(matrix) and must square all three c dims must match t must be 3d tensor and must be a cube t and c dims must match t and c must be contiguous
result(i,j,k) <-- sum(i',j',k') A(i',j',k') C0(i',i) C1(j',j) C2(k',k)
References mTxm(), T(), and TENSOR_ASSERT.