MADNESS: writecoeff.cc File Reference
writecoeff.cc File Reference
#include <complex>
#include <memory>
#include <madness/mra/mra.h>
#include <madness/world/worldmutex.h>
Classes
class WriteCoeff< T, D >
class WriteCoeffImpl< T, D >
Typedefs
typedef Function< std::complex< double >, D > cfunctionT
typedef Vector< double, D > coordT
typedef FunctionFactory< std::complex< double >, D > factoryT
typedef std::shared_ptr< FunctionFunctorInterface< std::complex< double >, D > > functorT
typedef SeparatedConvolution< std::complex< double >, D > operatorT
Functions
static std::complex< double > f (const coordT &r)
int main (int argc, char **argv)
Variables
static const size_t D = 2
static const long k = 3
static const double L = 32.0*R
static const double R = 1.4
static const double thresh = 1e-3
Typedef Documentation
cfunctionT
typedef Function<std::complex<double>,D> cfunctionT
coordT
typedef Vector<double,D> coordT
factoryT
typedef FunctionFactory<std::complex<double>,D> factoryT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<std::complex<double>,D> > functorT
operatorT
typedef SeparatedConvolution<std::complex<double>,D> operatorT
Function Documentation
f()
static std::complex< double > f (const coordT & r) static
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::copy(), madness::f, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, op(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), and madness::Function< T, NDIM >::unaryop().
Variable Documentation
D
const size_t D = 2 static
k
const long k = 3 static
Referenced by main().
L
const double L = 32.0*R static
Referenced by main().
R
const double R = 1.4 static
thresh
const double thresh = 1e-3 static
Referenced by main().