MADNESS: x_space_testing.cpp File Reference
x_space_testing.cpp File Reference
#include "ExcitedResponse.hpp"
#include "FrequencyResponse.hpp"
#include "ResponseExceptions.hpp"
#include "madness/external/catch/catch.hpp"
#include "madness/tensor/tensor_json.hpp"
#include "response_functions.h"
#include "string"
#include "x_space.h"
Macros
#define CATCH_CONFIG_RUNNER
Typedefs
using path = std::filesystem::path
Functions
int main (int argc, char *argv[])
TEST_CASE ("Testing New X SPACE")
TEST_CASE ("Testing xspace zero functions")
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
main()
int main (int argc, char * argv[])
References madness::initialize(), and madness::startup().
TEST_CASE() [1/2]
TEST_CASE ("Testing New X SPACE")
References madness::add(), b, CHECK, dipole_generator(), e(), madness::filename, madness::World::get_default(), initialize_calc_params(), madness::norm2(), nuclear_generator(), madness::print(), transform(), and vi.
TEST_CASE() [2/2]
TEST_CASE ("Testing xspace zero functions")
References dipole_generator(), madness::filename, madness::World::get_default(), initialize_calc_params(), nuclear_generator(), madness::print(), and madness::X_space::zero_functions().