ARG ubuntuImage=ubuntu:22.04
FROM ${ubuntuImage}

ARG BUILD_TYPE=Release
ARG BUILD_PARALLEL_JOBS=""
ARG CMAKE_EXTRA_ARGS=""
ARG MADNESS_REPO=https://github.com/m-a-d-n-e-s-s/madness

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y locales && \
    locale-gen "en_US.UTF-8" && \
    update-locale LANG=en_US.UTF-8

ENV LANGUAGE=en_US:en
ENV LANG=en_US.UTF-8 
ENV LC_ALL=en_US.UTF-8

# NB to enable nvidia docker runtime *with* --runtime nvidia
ENV NVIDIA_VISIBLE_DEVICES=all

RUN mkdir -p /home/m-a-d-n-e-s-s/
COPY ./Makefile /home/m-a-d-n-e-s-s/
WORKDIR /home/m-a-d-n-e-s-s/

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -yq update && \
    apt-get -yq install make wget curl

# main, cmake, clang
RUN make install/main && \
    make install/cmake && \
    make install/clang && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add MKL repo, download, install
RUN make apt-add-repository/intel-mkl && \
    make download/intel-mkl && \
    make install/intel-mkl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# build MADNESS for x86_64 with Intel MKL
RUN make build/madness/x86_64 \
    BUILD_TYPE="${BUILD_TYPE}" \
    BUILD_PARALLEL_JOBS="${BUILD_PARALLEL_JOBS}" \
    CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS}" \
    MADNESS_REPO="${MADNESS_REPO}" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cache

# Environment for users running madqc and developers linking against MADNESS
ENV PATH="/home/m-a-d-n-e-s-s/install/bin:${PATH}"
ENV LD_LIBRARY_PATH="/home/m-a-d-n-e-s-s/install/lib:/opt/intel/mkl/lib/intel64"
ENV CMAKE_PREFIX_PATH="/home/m-a-d-n-e-s-s/install"
ENV PKG_CONFIG_PATH="/home/m-a-d-n-e-s-s/install/lib/pkgconfig"
ENV MKLROOT=/opt/intel/mkl
ENV MRA_DATA_DIR="/home/m-a-d-n-e-s-s/install/share/madness/data"
ENV MRA_CHEMDATA_DIR="/home/m-a-d-n-e-s-s/install/share/madness/data"
ENV MAD_DATA_DIR="/home/m-a-d-n-e-s-s/install/share/madness/data"

WORKDIR /home/m-a-d-n-e-s-s/
