/* include/madness_config.h.  Generated by configure.  */

#ifndef _madness_include_madnessconfig_h_
#define _madness_include_madnessconfig_h_

/* The host architecture. */
#define HOST_ARCH "i686-pc-linux-gnu"

/* The target architecture. */
#define TARGET_ARCH "i686-pc-linux-gnu"

/* The version number. */
#define MADNESS_VERSION "1.0.0-alpha"

/* The major version number. */
#define MADNESS_MAJOR_VERSION 1

/* The minor version number. */
#define MADNESS_MINOR_VERSION 0

/* The micro version number. */
#define MADNESS_MICRO_VERSION 0

/* have stdint.h ? */
#define HAVE_STDINT_H 1

/* have boost/shared_array.hpp ? */
/* #undef HAVE_BOOST_SHARED_ARRAY_HPP */

/* can boost::shared_array<> be compiled and link? */
/* #undef HAVE_BOOST_SHARED_ARRAY_COMPILED */

/* is "restrict" keyword supported ? */
#define restrict __restrict

/* have MPI library header? */
/* #undef HAVE_MPI_H */

/* if MPI_INIT found -- we have MPI library */
/* #undef HAVE_MPI_LIB */

/* can use MPI library? */
#if HAVE_MPI_H && HAVE_MPI_LIB
  #define HAVE_MPI 1
#endif

/* have Pthreads library header? */
#define HAVE_PTHREAD_H 1

/* if pthread_join() found -- we have Pthreads library? */
#define HAVE_PTHREAD_LIB 1

/* can use Pthreads library? */
#if HAVE_PTHREAD_H && HAVE_PTHREAD_LIB
  #define HAVE_PTHREADS 1
#endif

#endif
