MADNESS: array_worldobject.cc File Reference
array_worldobject.cc File Reference
#include <madness/world/world.h>
#include <madness/world/worldgop.h>
#include <madness/world/world_object.h>
Classes
class Array
Macros
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Functions
int main (int argc, char **argv)
Macro Definition Documentation
WORLD_INSTANTIATE_STATIC_TEMPLATES
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Function Documentation
main()
int main (int argc, char ** argv)
References a, b, SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::Future< T >::get(), madness::World::gop, madness::initialize(), MADNESS_ASSERT, print(), madness::World::rand(), madness::World::rank(), and madness::World::size().