MADNESS: mtxmq.cc File Reference
bgp_tuning/mtxmq.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex>
Typedefs
typedef complex< double > double_complex
Functions
void mTxmq (long dimi, long dimj, long dimk, double *c, const double *a, const double *b)
void mTxmq (long dimi, long dimj, long dimk, double_complex *c, const double_complex *a, const double *b)
void mTxmq (long dimi, long dimj, long dimk, double_complex *c, const double_complex *a, const double_complex *b)
Typedef Documentation
double_complex
typedef complex<double> double_complex
Function Documentation
mTxmq() [1/3]
void mTxmq (long dimi, long dimj, long dimk, double * c, const double * a, const double * b)
References a, b, c, and k.
Referenced by main(), timer(), and trantimer().
mTxmq() [2/3]
void mTxmq (long dimi, long dimj, long dimk, double_complex * c, const double_complex * a, const double * b)
References a, b, c, and k.
mTxmq() [3/3]
void mTxmq (long dimi, long dimj, long dimk, double_complex * c, const double_complex * a, const double_complex * b)
References a, b, c, and k.
Referenced by main(), timer(), and trantimer().