MADNESS: cblas.h File Reference
cblas.h File Reference
Define BLAS like functions.
#include <madness/fortran_ctypes.h>
#include <madness/madness_config.h>
#include <madness/world/madness_exception.h>
#include <madness/tensor/cblas_types.h>
Namespaces
madness
File holds all helper structures necessary for the CC_Operator and CC2 class.
madness::cblas
Functions
void F77_CAXPY (const integer *, const complex_real4 *, const complex_real4 *, const integer *, complex_real4 *, const integer *)
void F77_CDOTU (complex_real4 *, const integer *, const complex_real4 *, const integer *, const complex_real4 *, const integer *)
void F77_CGEMM (const char *, const char *, const integer *, const integer *, const integer *, const complex_real4 *, const complex_real4 *, const integer *, const complex_real4 *, const integer *, const complex_real4 *, complex_real4 *, const integer *)
void F77_CGEMV (const char *, const integer *, const integer *, const complex_real4 *, const complex_real4 *, const integer *, const complex_real4 *, const integer *, const complex_real4 *, complex_real4 *, const integer *)
void F77_CGER (const integer *, const integer *, const complex_real4 *, const complex_real4 *, const integer *, const complex_real4 *, const integer *, complex_real4 *, const integer *)
void F77_CSCAL (const integer *, const complex_real4 *, complex_real4 *, const integer *)
void F77_CSSCAL (const integer *, const float *, complex_real4 *, const integer *)
void F77_DAXPY (const integer *, const double *, const double *, const integer *, double *, const integer *)
double F77_DDOT (const integer *, const double *, const integer *, const double *, const integer *)
void F77_DGEMM (const char *, const char *, const integer *, const integer *, const integer *, const double *, const double *, const integer *, const double *, const integer *, const double *, double *, const integer *)
void F77_DGEMV (const char *, const integer *, const integer *, const double *, const double *, const integer *, const double *, const integer *, const double *, double *, const integer *)
void F77_DGER (const integer *, const integer *, const double *, const double *, const integer *, const double *, const integer *, double *, const integer *)
void F77_DSCAL (const integer *, const double *, double *, const integer *)
void F77_SAXPY (const integer *, const float *, const float *, const integer *, float *, const integer *)
float F77_SDOT (const integer *, const float *, const integer *, const float *, const integer *)
void F77_SGEMM (const char *, const char *, const integer *, const integer *, const integer *, const float *, const float *, const integer *, const float *, const integer *, const float *, float *, const integer *)
void F77_SGEMV (const char *, const integer *, const integer *, const float *, const float *, const integer *, const float *, const integer *, const float *, float *, const integer *)
void F77_SGER (const integer *, const integer *, const float *, const float *, const integer *, const float *, const integer *, float *, const integer *)
void F77_SSCAL (const integer *, const float *, float *, const integer *)
void F77_ZAXPY (const integer *, const complex_real8 *, const complex_real8 *, const integer *, complex_real8 *, const integer *)
void F77_ZDOTU (complex_real8 *, const integer *, const complex_real8 *, const integer *, const complex_real8 *, const integer *)
void F77_ZDSCAL (const integer *, const double *, complex_real8 *, const integer *)
void F77_ZGEMM (const char *, const char *, const integer *, const integer *, const integer *, const complex_real8 *, const complex_real8 *, const integer *, const complex_real8 *, const integer *, const complex_real8 *, complex_real8 *, const integer *)
void F77_ZGEMV (const char *, const integer *, const integer *, const complex_real8 *, const complex_real8 *, const integer *, const complex_real8 *, const integer *, const complex_real8 *, complex_real8 *, const integer *)
void F77_ZGER (const integer *, const integer *, const complex_real8 *, const complex_real8 *, const integer *, const complex_real8 *, const integer *, complex_real8 *, const integer *)
void F77_ZSCAL (const integer *, const complex_real8 *, complex_real8 *, const integer *)
void madness::cblas::gemm (const CBLAS_TRANSPOSE OpA, const CBLAS_TRANSPOSE OpB, const integer m, const integer n, const integer k, const float alpha, const float *a, const integer lda, const float *b, const integer ldb, const float beta, float *c, const integer ldc)
Multiplies a matrix by a vector.
void madness::cblas::gemm (const CBLAS_TRANSPOSE OpA, const CBLAS_TRANSPOSE OpB, const integer m, const integer n, const integer k, const double alpha, const double *a, const integer lda, const double *b, const integer ldb, const double beta, double *c, const integer ldc)
void madness::cblas::gemm (const CBLAS_TRANSPOSE OpA, const CBLAS_TRANSPOSE OpB, const integer m, const integer n, const integer k, const complex_real4 alpha, const complex_real4 *a, const integer lda, const complex_real4 *b, const integer ldb, const complex_real4 beta, complex_real4 *c, const integer ldc)
void madness::cblas::gemm (const CBLAS_TRANSPOSE OpA, const CBLAS_TRANSPOSE OpB, const integer m, const integer n, const integer k, const complex_real8 alpha, const complex_real8 *a, const integer lda, const complex_real8 *b, const integer ldb, const complex_real8 beta, complex_real8 *c, const integer ldc)
void madness::cblas::gemv (const CBLAS_TRANSPOSE OpA, const integer m, const integer n, const float alpha, const float *A, const integer lda, const float *x, const integer incx, const float beta, float *y, const integer incy)
Multiplies a matrix by a vector.
void madness::cblas::gemv (const CBLAS_TRANSPOSE OpA, const integer m, const integer n, const double alpha, const double *A, const integer lda, const double *x, const integer incx, const double beta, double *y, const integer incy)
void madness::cblas::gemv (const CBLAS_TRANSPOSE OpA, const integer m, const integer n, const complex_real4 alpha, const complex_real4 *A, const integer lda, const complex_real4 *x, const integer incx, const complex_real4 beta, complex_real4 *y, const integer incy)
void madness::cblas::gemv (const CBLAS_TRANSPOSE OpA, const integer m, const integer n, const complex_real8 alpha, const complex_real8 *A, const integer lda, const complex_real8 *x, const integer incx, const complex_real8 beta, complex_real8 *y, const integer incy)
void madness::cblas::ger (const integer m, const integer n, const float alpha, const float *x, const integer incx, const float *y, const integer incy, float *A, const integer lda)
Multiplies vector by the transform of vector .
void madness::cblas::ger (const integer m, const integer n, const double alpha, const double *x, const integer incx, const double *y, const integer incy, double *A, const integer lda)
void madness::cblas::ger (const integer m, const integer n, const complex_real4 alpha, const complex_real4 *x, const integer incx, const complex_real4 *y, const integer incy, complex_real4 *A, const integer lda)
void madness::cblas::ger (const integer m, const integer n, const complex_real8 alpha, const complex_real8 *x, const integer incx, const complex_real8 *y, const integer incy, complex_real8 *A, const integer lda)
float madness::cblas::dot (const integer n, const float *x, const integer incx, const float *y, const integer incy)
Compute the dot product of vectors and .
double madness::cblas::dot (const integer n, const double *x, const integer incx, const double *y, const integer incy)
complex_real4 madness::cblas::dot (const integer n, const complex_real4 *x, const integer incx, const complex_real4 *y, const integer incy)
complex_real8 madness::cblas::dot (const integer n, const complex_real8 *x, const integer incx, const complex_real8 *y, const integer incy)
void madness::cblas::scal (const integer n, const float alpha, float *x, const integer incx)
Scale a vector.
void madness::cblas::scal (const integer n, const double alpha, double *x, const integer incx)
void madness::cblas::scal (const integer n, const complex_real4 alpha, complex_real4 *x, const integer incx)
void madness::cblas::scal (const integer n, const complex_real8 alpha, complex_real8 *x, const integer incx)
void madness::cblas::scal (const integer n, const float alpha, complex_real4 *x, const integer incx)
void madness::cblas::scal (const integer n, const double alpha, complex_real8 *x, const integer incx)
void madness::cblas::axpy (const integer n, const float alpha, float *x, const integer incx, float *y, const integer incy)
Scale and add a vector to another.
void madness::cblas::axpy (const integer n, const double alpha, double *x, const integer incx, double *y, const integer incy)
void madness::cblas::axpy (const integer n, const complex_real4 alpha, complex_real4 *x, const integer incx, complex_real4 *y, const integer incy)
void madness::cblas::axpy (const integer n, const complex_real8 alpha, complex_real8 *x, const integer incx, complex_real8 *y, const integer incy)
Detailed Description
Define BLAS like functions.
Function Documentation
F77_CAXPY()
void F77_CAXPY (const integer * , const complex_real4 * , const complex_real4 * , const integer * , complex_real4 * , const integer *)
Referenced by madness::cblas::axpy().
F77_CDOTU()
void F77_CDOTU (complex_real4 * , const integer * , const complex_real4 * , const integer * , const complex_real4 * , const integer *)
Referenced by madness::cblas::dot().
F77_CGEMM()
void F77_CGEMM (const char * , const char * , const integer * , const integer * , const integer * , const complex_real4 * , const complex_real4 * , const integer * , const complex_real4 * , const integer * , const complex_real4 * , complex_real4 * , const integer *)
Referenced by madness::cblas::gemm().
F77_CGEMV()
void F77_CGEMV (const char * , const integer * , const integer * , const complex_real4 * , const complex_real4 * , const integer * , const complex_real4 * , const integer * , const complex_real4 * , complex_real4 * , const integer *)
Referenced by madness::cblas::gemv().
F77_CGER()
void F77_CGER (const integer * , const integer * , const complex_real4 * , const complex_real4 * , const integer * , const complex_real4 * , const integer * , complex_real4 * , const integer *)
Referenced by madness::cblas::ger().
F77_CSCAL()
void F77_CSCAL (const integer * , const complex_real4 * , complex_real4 * , const integer *)
Referenced by madness::cblas::scal().
F77_CSSCAL()
void F77_CSSCAL (const integer * , const float * , complex_real4 * , const integer *)
Referenced by madness::cblas::scal().
F77_DAXPY()
void F77_DAXPY (const integer * , const double * , const double * , const integer * , double * , const integer *)
Referenced by madness::cblas::axpy().
F77_DDOT()
double F77_DDOT (const integer * , const double * , const integer * , const double * , const integer *)
Referenced by madness::cblas::dot().
F77_DGEMM()
void F77_DGEMM (const char * , const char * , const integer * , const integer * , const integer * , const double * , const double * , const integer * , const double * , const integer * , const double * , double * , const integer *)
Referenced by madness::cblas::gemm().
F77_DGEMV()
void F77_DGEMV (const char * , const integer * , const integer * , const double * , const double * , const integer * , const double * , const integer * , const double * , double * , const integer *)
Referenced by madness::cblas::gemv().
F77_DGER()
void F77_DGER (const integer * , const integer * , const double * , const double * , const integer * , const double * , const integer * , double * , const integer *)
Referenced by madness::cblas::ger().
F77_DSCAL()
void F77_DSCAL (const integer * , const double * , double * , const integer *)
Referenced by madness::cblas::scal().
F77_SAXPY()
void F77_SAXPY (const integer * , const float * , const float * , const integer * , float * , const integer *)
Referenced by madness::cblas::axpy().
F77_SDOT()
float F77_SDOT (const integer * , const float * , const integer * , const float * , const integer *)
Referenced by madness::cblas::dot().
F77_SGEMM()
void F77_SGEMM (const char * , const char * , const integer * , const integer * , const integer * , const float * , const float * , const integer * , const float * , const integer * , const float * , float * , const integer *)
Referenced by madness::cblas::gemm().
F77_SGEMV()
void F77_SGEMV (const char * , const integer * , const integer * , const float * , const float * , const integer * , const float * , const integer * , const float * , float * , const integer *)
Referenced by madness::cblas::gemv().
F77_SGER()
void F77_SGER (const integer * , const integer * , const float * , const float * , const integer * , const float * , const integer * , float * , const integer *)
Referenced by madness::cblas::ger().
F77_SSCAL()
void F77_SSCAL (const integer * , const float * , float * , const integer *)
Referenced by madness::cblas::scal().
F77_ZAXPY()
void F77_ZAXPY (const integer * , const complex_real8 * , const complex_real8 * , const integer * , complex_real8 * , const integer *)
Referenced by madness::cblas::axpy().
F77_ZDOTU()
void F77_ZDOTU (complex_real8 * , const integer * , const complex_real8 * , const integer * , const complex_real8 * , const integer *)
Referenced by madness::cblas::dot().
F77_ZDSCAL()
void F77_ZDSCAL (const integer * , const double * , complex_real8 * , const integer *)
Referenced by madness::cblas::scal().
F77_ZGEMM()
void F77_ZGEMM (const char * , const char * , const integer * , const integer * , const integer * , const complex_real8 * , const complex_real8 * , const integer * , const complex_real8 * , const integer * , const complex_real8 * , complex_real8 * , const integer *)
Referenced by madness::cblas::gemm().
F77_ZGEMV()
void F77_ZGEMV (const char * , const integer * , const integer * , const complex_real8 * , const complex_real8 * , const integer * , const complex_real8 * , const integer * , const complex_real8 * , complex_real8 * , const integer *)
Referenced by madness::cblas::gemv().
F77_ZGER()
void F77_ZGER (const integer * , const integer * , const complex_real8 * , const complex_real8 * , const integer * , const complex_real8 * , const integer * , complex_real8 * , const integer *)
Referenced by madness::cblas::ger().
F77_ZSCAL()
void F77_ZSCAL (const integer * , const complex_real8 * , complex_real8 * , const integer *)
Referenced by madness::cblas::scal().