MADNESS: MolecularNuclearChargeDensityFunctor Class Reference
MolecularNuclearChargeDensityFunctor Class Reference
#include <electronicstructureapp.h>
Public Member Functions
MolecularNuclearChargeDensityFunctor (const MolecularEntity &mentity, const double &R, const bool &periodic, const std::vector< coordT > &specialpts)
MolecularNuclearChargeDensityFunctor (const MolecularEntity &mentity, const double &R, const bool &periodic, const std::vector< coordT > &specialpts)
double operator() (const coordT &x) const
double operator() (const coordT &x) const
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual std::vector< coordT > special_points () const
Override this to return list of special points to be refined more deeply.
virtual std::vector< coordT > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const MolecularEntity & _mentity
const std::vector< coordT > _specialpts
double charge
const bool periodic
const double R
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
MolecularNuclearChargeDensityFunctor() [1/2]
MolecularNuclearChargeDensityFunctor::MolecularNuclearChargeDensityFunctor (const MolecularEntity & mentity, const double & R, const bool & periodic, const std::vector< coordT > & specialpts) inline
MolecularNuclearChargeDensityFunctor() [2/2]
MolecularNuclearChargeDensityFunctor::MolecularNuclearChargeDensityFunctor (const MolecularEntity & mentity, const double & R, const bool & periodic, const std::vector< coordT > & specialpts) inline
References madness::print(), and MolecularEntity::total_nuclear_charge().
Member Function Documentation
operator()() [1/2]
double MolecularNuclearChargeDensityFunctor::operator() (const coordT & x) const inline
References _mentity, MolecularEntity::nuclear_charge_density(), periodic, R, and MolecularEntity::smallest_length_scale().
operator()() [2/2]
double MolecularNuclearChargeDensityFunctor::operator() (const coordT & x) const inline
References MolecularEntity::nuclear_charge_density(), R, and MolecularEntity::smallest_length_scale().
special_level() [1/2]
virtual Level MolecularNuclearChargeDensityFunctor::special_level () inline virtual
Override this change level refinement for special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
special_level() [2/2]
virtual Level MolecularNuclearChargeDensityFunctor::special_level () inline virtual
Override this change level refinement for special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
special_points() [1/2]
virtual std::vector<coordT> MolecularNuclearChargeDensityFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References _specialpts.
special_points() [2/2]
virtual std::vector<coordT> MolecularNuclearChargeDensityFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
Member Data Documentation
_mentity
const MolecularEntity & MolecularNuclearChargeDensityFunctor::_mentity private
Referenced by operator()().
_specialpts
const std::vector< coordT > MolecularNuclearChargeDensityFunctor::_specialpts private
Referenced by special_points().
charge
double MolecularNuclearChargeDensityFunctor::charge private
periodic
const bool MolecularNuclearChargeDensityFunctor::periodic private
Referenced by operator()().
R
const double MolecularNuclearChargeDensityFunctor::R private
Referenced by operator()().
The documentation for this class was generated from the following files:
electronicstructureapp.h
ewald.cc