MADNESS: madness::Thread Class Reference
madness::Thread Class Reference
MADNESS libraries » Parallel programming environment » Multi-threading » Threads
Simplified thread wrapper to hide pthread complexity.
#include <thread.h>
Public Member Functions
Thread ()
Default constructor.
Thread (void *(*f)(void *), void *args=nullptr)
Create a thread and start it running f(args).
virtual ~Thread ()=default
void start (void *(*f)(void *), void *args=nullptr)
Start the thread by running f(args).
Public Member Functions inherited from madness::ThreadBase
ThreadBase ()
Default constructor.
virtual ~ThreadBase ()
int cancel () const
Cancel this thread.
const pthread_t & get_id () const
Get the pthread id of this thread (if running).
int get_pool_thread_index () const
Get index of this thread in ThreadPool.
void start ()
Start the thread running.
Private Member Functions
void run ()
Invokes the function for this thread.
Private Attributes
void * args
The arguments passed to this thread for execution.
void *(* f)(void *)
The function called for executing this thread.
Additional Inherited Members
Static Public Member Functions inherited from madness::ThreadBase
static void exit ()
A thread can call this to terminate its execution.
static int num_hw_processors ()
Get number of actual hardware processors.
static void set_affinity (int logical_id, int ind=-1)
static void set_affinity_pattern (const bool bind[3], const int cpu[3])
Specify the affinity pattern or how to bind threads to CPUs.
static ThreadBase * this_thread ()
Detailed Description
Simplified thread wrapper to hide pthread complexity.
Constructor & Destructor Documentation
Thread() [1/2]
madness::Thread::Thread () inline
Default constructor.
start() must be invoked to actually execute the thread.
Thread() [2/2]
madness::Thread::Thread (void *(*)(void *) f, void * args = nullptr) inline
Create a thread and start it running f(args).
Parameters
[in] f The function to be called.
[in,out] args The arguments to the function.
References madness::ThreadBase::start().
~Thread()
virtual madness::Thread::~Thread () virtual default
Member Function Documentation
run()
void madness::Thread::run () inline private virtual
Invokes the function for this thread.
Implements madness::ThreadBase.
References args, and f.
start()
void madness::Thread::start (void *(*)(void *) f, void * args = nullptr) inline
Start the thread by running f(args).
Parameters
[in] f The function to be called.
[in,out] args The arguments to the function.
References args, f, and madness::ThreadBase::start().
Referenced by madness::ThreadPool::ThreadPool().
Member Data Documentation
args
void* madness::Thread::args private
The arguments passed to this thread for execution.
Referenced by run(), and start().
f
void*(* madness::Thread::f) (void *) private
The function called for executing this thread.
Todo:
should we replace this by a std::function?
Referenced by run(), and start().
The documentation for this class was generated from the following file:
thread.h