MADNESS: madness::NuclearCorrelationFactor::square_times_V_derivative_functor Class Reference
madness::NuclearCorrelationFactor::square_times_V_derivative_functor Class Reference
#include <correlationfactor.h>
Public Member Functions
square_times_V_derivative_functor (const NuclearCorrelationFactor *ncf, const Molecule &molecule1, const size_t atom1, const int axis1)
double operator() (const coord_3d &xyz) const
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const int axis
const size_t iatom
const Molecule & molecule
const NuclearCorrelationFactor * ncf
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
square_times_V_derivative_functor()
madness::NuclearCorrelationFactor::square_times_V_derivative_functor::square_times_V_derivative_functor (const NuclearCorrelationFactor * ncf, const Molecule & molecule1, const size_t atom1, const int axis1) inline
Member Function Documentation
operator()()
double madness::NuclearCorrelationFactor::square_times_V_derivative_functor::operator() (const coord_3d & xyz) const inline
References axis, madness::Molecule::get_atom(), madness::Atom::get_coords(), iatom, madness::NuclearCorrelationFactor::molecule, molecule, madness::Molecule::natom(), ncf, madness::Vector< T, N >::normf(), madness::Molecule::nuclear_attraction_potential_derivative(), madness::Atom::q, and madness::NuclearCorrelationFactor::S().
special_points()
std::vector<coord_3d> madness::NuclearCorrelationFactor::square_times_V_derivative_functor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References madness::Molecule::get_all_coords_vec(), madness::NuclearCorrelationFactor::molecule, and ncf.
Member Data Documentation
axis
const int madness::NuclearCorrelationFactor::square_times_V_derivative_functor::axis private
Referenced by operator()().
iatom
const size_t madness::NuclearCorrelationFactor::square_times_V_derivative_functor::iatom private
Referenced by operator()().
molecule
const Molecule& madness::NuclearCorrelationFactor::square_times_V_derivative_functor::molecule private
Referenced by operator()().
ncf
const NuclearCorrelationFactor* madness::NuclearCorrelationFactor::square_times_V_derivative_functor::ncf private
Referenced by operator()(), and special_points().
The documentation for this class was generated from the following file:
correlationfactor.h