MADNESS: madness::BoundaryConditions< NDIM > Class Template Reference
madness::BoundaryConditions< NDIM > Class Template Reference
This class is used to specify boundary conditions for all operatorsExterior boundary conditions (i.e., on the simulation domain) are associated with operators (not functions). The types of boundary conditions available are in the enum BCType.
#include <funcdefaults.h>
Public Member Functions
BoundaryConditions (BCType code=BC_FREE)
Constructor. Default boundary condition set to free space.
BoundaryConditions (const BoundaryConditions< NDIM > &other)
Copy constructor is deep.
std::vector< bool > is_periodic () const
Convenience for application of integral operators.
BCType operator() (std::size_t d, int i) const
Returns value of boundary condition.
BCType & operator() (std::size_t d, int i)
Returns reference to boundary condition.
BoundaryConditions< NDIM > & operator= (const BoundaryConditions< NDIM > &other)
Assignment makes deep copy.
template<typename Archive >
void serialize (const Archive &ar)
Static Public Member Functions
static const char * code_as_string (BCType code)
Translates code into human readable string.
Private Attributes
BCType bc [NDIM *2]
Detailed Description
template<std::size_t NDIM>
class madness::BoundaryConditions< NDIM >
This class is used to specify boundary conditions for all operators
Exterior boundary conditions (i.e., on the simulation domain) are associated with operators (not functions). The types of boundary conditions available are in the enum BCType.
The default boundary conditions are obtained from the FunctionDefaults. For non-zero Dirichlet and Neumann conditions additional information must be provided when derivative operators are constructed. For integral operators, only periodic and free space are supported.
Constructor & Destructor Documentation
BoundaryConditions() [1/2]
template<std::size_t NDIM> madness::BoundaryConditions< NDIM >::BoundaryConditions (BCType code = BC_FREE) inline
Constructor. Default boundary condition set to free space.
BoundaryConditions() [2/2]
template<std::size_t NDIM> madness::BoundaryConditions< NDIM >::BoundaryConditions (const BoundaryConditions< NDIM > & other) inline
Copy constructor is deep.
Member Function Documentation
code_as_string()
template<std::size_t NDIM> static const char* madness::BoundaryConditions< NDIM >::code_as_string (BCType code) inline static
Translates code into human readable string.
Parameters
code Code for boundary condition
Returns
String describing boundary condition code
is_periodic()
template<std::size_t NDIM> std::vector<bool> madness::BoundaryConditions< NDIM >::is_periodic () const inline
Convenience for application of integral operators.
Returns
Returns a vector indicating if each dimension is periodic
Referenced by madness::Specialbox_op< T, NDIM >::check_special_points(), madness::ElectronCuspyBox_op< T, NDIM >::operator()(), madness::Leaf_op< T, NDIM, SeparatedConvolution< double, NDIM >, Specialbox_op< T, NDIM > >::post_screening(), and madness::FunctionImpl< Q, NDIM >::project_refine_op().
operator()() [1/2]
template<std::size_t NDIM> BCType madness::BoundaryConditions< NDIM >::operator() (std::size_t d, int i) const inline
Returns value of boundary condition.
Parameters
d Dimension (0,...,NDIM-1) for boundary condition
i Side (0=left, 1=right) for boundary condition
Returns
Value of boundary condition
operator()() [2/2]
template<std::size_t NDIM> BCType& madness::BoundaryConditions< NDIM >::operator() (std::size_t d, int i) inline
Returns reference to boundary condition.
Parameters
d Dimension (0,...,NDIM-1) for boundary condition
i Side (0=left, 1=right) for boundary condition
Returns
Value of boundary condition
operator=()
template<std::size_t NDIM> BoundaryConditions<NDIM>& madness::BoundaryConditions< NDIM >::operator= (const BoundaryConditions< NDIM > & other) inline
Assignment makes deep copy.
serialize()
template<std::size_t NDIM> template<typename Archive > void madness::BoundaryConditions< NDIM >::serialize (const Archive & ar) inline
Member Data Documentation
bc
template<std::size_t NDIM> BCType madness::BoundaryConditions< NDIM >::bc[NDIM *2] private
Referenced by madness::BoundaryConditions< 6 >::BoundaryConditions(), madness::BoundaryConditions< 6 >::is_periodic(), madness::BoundaryConditions< 6 >::operator()(), madness::BoundaryConditions< 6 >::operator=(), and madness::BoundaryConditions< 6 >::serialize().
The documentation for this class was generated from the following file:
funcdefaults.h