MADNESS: NuclearDensityFunctor Class Reference
NuclearDensityFunctor Class Reference
Public Member Functions
NuclearDensityFunctor (const Molecule &molecule)
NuclearDensityFunctor (const Molecule &molecule, double R)
double operator() (const Vector< double, 3 > &r) const
double operator() (const coord_3d &x) const
Level special_level ()
Override this change level refinement for special points (default is 6)
Level special_level ()
Override this change level refinement for special points (default is 6)
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const int maxR = 1
Molecule molecule
const Molecule & molecule
const double R
std::vector< coord_3d > specialpt
std::vector< coord_3d > specialpts
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Constructor & Destructor Documentation
NuclearDensityFunctor() [1/2]
NuclearDensityFunctor::NuclearDensityFunctor (const Molecule & molecule) inline
NuclearDensityFunctor() [2/2]
NuclearDensityFunctor::NuclearDensityFunctor (const Molecule & molecule, double R) inline
Member Function Documentation
operator()() [1/2]
double NuclearDensityFunctor::operator() (const Vector< double, 3 > & r) const inline
References madness::Molecule::mol_nuclear_charge_density(), and molecule.
operator()() [2/2]
double NuclearDensityFunctor::operator() (const coord_3d & x) const inline
References k, maxR, molecule, madness::Molecule::nuclear_charge_density(), R, madness::Molecule::smallest_length_scale(), and madness::sum().
special_level() [1/2]
Level NuclearDensityFunctor::special_level () inline virtual
Override this change level refinement for special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
special_level() [2/2]
Level NuclearDensityFunctor::special_level () inline virtual
Override this change level refinement for special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
special_points() [1/2]
std::vector<coord_3d> NuclearDensityFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
special_points() [2/2]
std::vector<coord_3d> NuclearDensityFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
Member Data Documentation
maxR
const int NuclearDensityFunctor::maxR = 1 private
molecule [1/2]
Molecule NuclearDensityFunctor::molecule private
molecule [2/2]
const Molecule& NuclearDensityFunctor::molecule private
R
const double NuclearDensityFunctor::R private
specialpt
std::vector<coord_3d> NuclearDensityFunctor::specialpt private
specialpts
std::vector<coord_3d> NuclearDensityFunctor::specialpts private
The documentation for this class was generated from the following files:
preal.cc
apps/moldft/testperiodic.cc