MADNESS: WSTFunctional Class Reference
WSTFunctional Class Reference
#include <wst_functional.h>
Public Member Functions
std::pair< real_function_3d, double > apply_xc (World &world, const XCfunctional &xc, real_function_3d &rho)
double make_dft_energy (World &world, const XCfunctional &xc, const vector_real_function_3d &vf, int ispin)
real_function_3d make_dft_potential (World &world, const XCfunctional &xc, const vector_real_function_3d &vf, int ispin, int what)
Member Function Documentation
apply_xc()
std::pair<real_function_3d, double> WSTFunctional::apply_xc (World & world, const XCfunctional & xc, real_function_3d & rho) inline
References axis, madness::XCfunctional::is_gga(), make_dft_energy(), make_dft_potential(), madness::reconstruct(), madness::Function< T, NDIM >::reconstruct(), madness::refine_to_common_level(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), and xc.
Referenced by MiniDFT::doit().
make_dft_energy()
double WSTFunctional::make_dft_energy (World & world, const XCfunctional & xc, const vector_real_function_3d & vf, int ispin) inline
References madness::Function< T, NDIM >::trace(), and xc.
make_dft_potential()
real_function_3d WSTFunctional::make_dft_potential (World & world, const XCfunctional & xc, const vector_real_function_3d & vf, int ispin, int what) inline
References xc.
The documentation for this class was generated from the following file:
wst_functional.h