MADNESS: ExcitingApp Class Reference
ExcitingApp Class Reference
Classes
struct vectorLengthFunctor
struct wannierf
Public Member Functions
ExcitingApp (World &world)
Tensor< std::complex< double > > compute_A_coeffs (vec3dT qvc)
int findkpt (vec3dT kvecl)
void generate_gvectors ()
void generate_lvectors ()
vec3dT r3mv (const Tensor< double > &m, const vec3dT &v)
void read_kpoints ()
void read_lattice ()
void read_wannier_functions ()
void readinput ()
void response (vec3dT qvec)
Public Attributes
Tensor< double > _ainv
Tensor< double > _avec
Tensor< double > _binv
Tensor< double > _bvec
double _domega
double _eta
std::vector< double > _glens
double _gmaxlen
std::vector< int > _gshells
std::vector< vec3dT > _gvecs
std::vector< vec3dT > _lvecs
double _maxomega
int _ngridk0
int _ngridk1
int _ngridk2
int _ngshells
int _nrshells
vec3dT _qv
std::vector< double > _rlens
double _rmaxlen
std::vector< int > _rshells
std::vector< vec3dT > _vkc
std::vector< vec3dT > _vkl
std::vector< wannierf > _wfs
std::vector< vec3dT > _wkpt
World & _world
Constructor & Destructor Documentation
ExcitingApp()
ExcitingApp::ExcitingApp (World & world) inline
References exciting_init_().
Member Function Documentation
compute_A_coeffs()
Tensor<std::complex<double> > ExcitingApp::compute_A_coeffs (vec3dT qvc) inline
References f_nwann_(), madness::inner(), and MADNESS_EXCEPTION.
findkpt()
int ExcitingApp::findkpt (vec3dT kvecl) inline
References madness::abs(), and e().
generate_gvectors()
void ExcitingApp::generate_gvectors () inline
References madness::abs(), and e().
generate_lvectors()
void ExcitingApp::generate_lvectors () inline
References madness::abs(), e(), and lo.
r3mv()
vec3dT ExcitingApp::r3mv (const Tensor< double > & m, const vec3dT & v) inline
References m.
read_kpoints()
void ExcitingApp::read_kpoints () inline
References f_kpts_(), f_ngridk_(), and f_nkpts_().
read_lattice()
void ExcitingApp::read_lattice () inline
References f_lvec_().
read_wannier_functions()
void ExcitingApp::read_wannier_functions () inline
References f_nwann_(), f_wann_center_(), and madness::Function< T, NDIM >::reconstruct().
readinput()
void ExcitingApp::readinput () inline
References MADNESS_EXCEPTION, and madness::World::rank().
response()
void ExcitingApp::response (vec3dT qvec) inline
References madness::abs(), madness::conj(), e(), f_get_evalsv_(), f_get_occsv_(), f_nstsv_(), f_nwann_(), f_wann_c_(), and mu.
Member Data Documentation
_ainv
Tensor<double> ExcitingApp::_ainv
_avec
Tensor<double> ExcitingApp::_avec
_binv
Tensor<double> ExcitingApp::_binv
_bvec
Tensor<double> ExcitingApp::_bvec
_domega
double ExcitingApp::_domega
_eta
double ExcitingApp::_eta
_glens
std::vector<double> ExcitingApp::_glens
_gmaxlen
double ExcitingApp::_gmaxlen
_gshells
std::vector<int> ExcitingApp::_gshells
_gvecs
std::vector<vec3dT> ExcitingApp::_gvecs
_lvecs
std::vector<vec3dT> ExcitingApp::_lvecs
_maxomega
double ExcitingApp::_maxomega
_ngridk0
int ExcitingApp::_ngridk0
_ngridk1
int ExcitingApp::_ngridk1
_ngridk2
int ExcitingApp::_ngridk2
_ngshells
int ExcitingApp::_ngshells
_nrshells
int ExcitingApp::_nrshells
_qv
vec3dT ExcitingApp::_qv
_rlens
std::vector<double> ExcitingApp::_rlens
_rmaxlen
double ExcitingApp::_rmaxlen
_rshells
std::vector<int> ExcitingApp::_rshells
_vkc
std::vector<vec3dT> ExcitingApp::_vkc
_vkl
std::vector<vec3dT> ExcitingApp::_vkl
_wfs
std::vector<wannierf> ExcitingApp::_wfs
_wkpt
std::vector<vec3dT> ExcitingApp::_wkpt
_world
World& ExcitingApp::_world
The documentation for this class was generated from the following file:
wannier.cc