MADNESS: madness::NuclearCorrelationFactor Class Reference
madness::NuclearCorrelationFactor Class Reference abstract
ABC for the nuclear correlation factors.
#include <correlationfactor.h>
Classes
class R_functor
class RX_functor
compute the derivative of R wrt the displacement of atom A, coord axis
class square_times_V_derivative_functor
class square_times_V_functor
class U1_atomic_functor
U1 functor for a specific atom.
class U1_dot_U1_functor
functor for a local U1 dot U1 potential
class U1_functor
functor for the local part of the U1 potential – NOTE THE SIGN
class U1X_functor
compute the derivative of U1 wrt the displacement of atom A, coord axis
class U2_atomic_functor
U2 functor for a specific atom.
class U2_functor
class U2X_functor
compute the derivative of U2 wrt the displacement of atom A
class U3_atomic_functor
U3 functor for a specific atom.
class U3_functor
class U3X_functor
compute the derivative of U3 wrt the displacement of atom A, coord axis
Public Types
enum corrfactype {
None, GradientalGaussSlater, GaussSlater, LinearSlater,
Polynomial, Slater, poly4erfc, Two
}
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
Public Member Functions
NuclearCorrelationFactor (World &world, const Molecule &mol)
ctor
virtual ~NuclearCorrelationFactor ()
virtual destructor
virtual real_function_3d apply_U (const real_function_3d &rhs) const
apply the regularized potential U_nuc on a given function rhs
coord_3d dsmoothed_unitvec (const coord_3d &xyz, const int axis, double smoothing=0.0) const
derivative of smoothed unit vector wrt the electronic coordinate
virtual real_function_3d function () const
return the nuclear correlation factor
void initialize (const double vtol1)
initialize the regularized potentials U1 and U2
virtual real_function_3d inverse () const
return the inverse nuclear correlation factor
coord_3d smoothed_unitvec (const coord_3d &xyz, double smoothing=0.0) const
smoothed unit vector for the computation of the U1 potential
virtual real_function_3d square () const
return the square of the nuclear correlation factor
virtual real_function_3d square_times_V_derivative (const int iatom, const int axis) const
virtual double Sr_div_S (const double &r, const double &Z) const =0
virtual double Srr_div_S (const double &r, const double &Z) const =0
virtual double Srrr_div_S (const double &r, const double &Z) const =0
virtual corrfactype type () const =0
virtual const real_function_3d U1 (const int axis) const
return the U1 term of the correlation function
std::vector< real_function_3d > U1vec () const
return the U1 functions in a vector
virtual const real_function_3d U2 () const
return the U2 term of the correlation function
virtual double U2X_spherical (const double &r, const double &Z, const double &rcut) const
derivative of the U2 potential wrt nuclear coordinate X (spherical part)
Private Member Functions
virtual double S (const double &r, const double &Z) const =0
the correlation factor S wrt a given atom
virtual coord_3d Sp (const coord_3d &vr1A, const double &Z) const =0
the partial derivative of correlation factor S' wrt the cartesian coordinates
virtual double Spp_div_S (const double &r, const double &Z) const =0
the regularized potential wrt a given atom wrt the cartesian coordinate
Private Attributes
const Molecule & molecule
the molecule
std::vector< real_function_3d > U1_function
the three components of the U1 potential
real_function_3d U2_function
the purely local U2 potential, having absorbed the nuclear pot V_nuc
double vtol
the threshold for initial projection
World & world
the world
Detailed Description
ABC for the nuclear correlation factors.
Member Typedef Documentation
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > madness::NuclearCorrelationFactor::functorT
Member Enumeration Documentation
corrfactype
enum madness::NuclearCorrelationFactor::corrfactype
Enumerator
None
GradientalGaussSlater
GaussSlater
LinearSlater
Polynomial
Slater
poly4erfc
Two
Constructor & Destructor Documentation
NuclearCorrelationFactor()
madness::NuclearCorrelationFactor::NuclearCorrelationFactor (World & world, const Molecule & mol) inline
ctor
Parameters
[in] world the world
[in] mol molecule with the sites of the nuclei
~NuclearCorrelationFactor()
virtual madness::NuclearCorrelationFactor::~NuclearCorrelationFactor () inline virtual
virtual destructor
Member Function Documentation
apply_U()
virtual real_function_3d madness::NuclearCorrelationFactor::apply_U (const real_function_3d & rhs) const inline virtual
apply the regularized potential U_nuc on a given function rhs
Reimplemented in madness::PseudoNuclearCorrelationFactor.
References axis, madness::Function< T, NDIM >::compress(), madness::truncate(), madness::Function< T, NDIM >::truncate(), U1(), U2(), and world.
dsmoothed_unitvec()
coord_3d madness::NuclearCorrelationFactor::dsmoothed_unitvec (const coord_3d & xyz, const int axis, double smoothing = 0.0) const inline
derivative of smoothed unit vector wrt the electronic coordinate
note the sign change for exchanging nuclear and electronic coordinates
the derivative wrt x is given by
References axis, e(), madness::Molecule::get_eprec(), molecule, madness::Vector< T, N >::normf(), p(), madness::constants::pi, and r2().
Referenced by madness::NuclearCorrelationFactor::U1X_functor::operator()(), and madness::NuclearCorrelationFactor::U3X_functor::operator()().
function()
virtual real_function_3d madness::NuclearCorrelationFactor::function () const inline virtual
return the nuclear correlation factor
References vtol, and world.
initialize()
void madness::NuclearCorrelationFactor::initialize (const double vtol1) inline
initialize the regularized potentials U1 and U2
References axis, madness::Function< T, NDIM >::set_thresh(), thresh, madness::Function< T, NDIM >::truncate(), U1_function, U2_function, vtol, and world.
inverse()
virtual real_function_3d madness::NuclearCorrelationFactor::inverse () const inline virtual
return the inverse nuclear correlation factor
References vtol, and world.
S()
virtual double madness::NuclearCorrelationFactor::S (const double & r, const double & Z) const private pure virtual
the correlation factor S wrt a given atom
Parameters
[in] r the distance of the req'd coord to the nucleus
[in] Z the nuclear charge
Returns
the nuclear correlation factor S_A(r_1A)
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
Referenced by madness::NuclearCorrelationFactor::R_functor::operator()(), madness::NuclearCorrelationFactor::square_times_V_functor::operator()(), madness::NuclearCorrelationFactor::square_times_V_derivative_functor::operator()(), and madness::NuclearCorrelationFactor::RX_functor::operator()().
smoothed_unitvec()
coord_3d madness::NuclearCorrelationFactor::smoothed_unitvec (const coord_3d & xyz, double smoothing = 0.0) const inline
smoothed unit vector for the computation of the U1 potential
note the identity for exchanging nuclear and electronic coordinates (there is a sign change, unlike for the smoothed potential)
References e(), madness::Molecule::get_eprec(), molecule, madness::Vector< T, N >::normf(), madness::constants::pi, and xi.
Referenced by madness::NuclearCorrelationFactor::U1_functor::operator()(), madness::NuclearCorrelationFactor::U1_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U3_functor::operator()(), madness::NuclearCorrelationFactor::U3_atomic_functor::operator()(), madness::NuclearCorrelationFactor::RX_functor::operator()(), madness::NuclearCorrelationFactor::U1X_functor::operator()(), madness::NuclearCorrelationFactor::U2X_functor::operator()(), madness::NuclearCorrelationFactor::U3X_functor::operator()(), madness::GaussSlater::Sp(), madness::GradientalGaussSlater::Sp(), madness::LinearSlater::Sp(), madness::Slater::Sp(), madness::poly4erfc::Sp(), and madness::Polynomial< N >::Sp().
Sp()
virtual coord_3d madness::NuclearCorrelationFactor::Sp (const coord_3d & vr1A, const double & Z) const private pure virtual
the partial derivative of correlation factor S' wrt the cartesian coordinates
Parameters
[in] vr1A the vector of the req'd coord to the nucleus
[in] Z the nuclear charge
Returns
the gradient of the nuclear correlation factor S'_A(r_1A)
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
Spp_div_S()
virtual double madness::NuclearCorrelationFactor::Spp_div_S (const double & r, const double & Z) const private pure virtual
the regularized potential wrt a given atom wrt the cartesian coordinate
S" is the Cartesian Laplacian applied on the NCF. Note the difference to Srr_div_S, which is the second derivative wrt the distance rho. this is: -S"/S - Z/r
Parameters
[in] r the distance of the req'd coord to the nucleus
[in] Z the nuclear charge
Returns
the Laplacian of the nuclear correlation factor divided by the correlation factor minus the nuclear potential
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
Referenced by madness::NuclearCorrelationFactor::U2_functor::operator()(), and madness::NuclearCorrelationFactor::U2_atomic_functor::operator()().
square()
virtual real_function_3d madness::NuclearCorrelationFactor::square () const inline virtual
return the square of the nuclear correlation factor
References R2, vtol, and world.
square_times_V_derivative()
virtual real_function_3d madness::NuclearCorrelationFactor::square_times_V_derivative (const int iatom, const int axis) const inline virtual
return the square of the nuclear correlation factor multiplied with the derivative of the nuclear potential for the specified atom
Returns
R^2 * { Z_A/r_{1A}}{ X_A}
References axis, madness::func(), molecule, R2, vtol, and world.
Sr_div_S()
virtual double madness::NuclearCorrelationFactor::Sr_div_S (const double & r, const double & Z) const pure virtual
first derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
Referenced by madness::NuclearCorrelationFactor::U1_functor::operator()(), madness::NuclearCorrelationFactor::U1_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U1_dot_U1_functor::operator()(), madness::NuclearCorrelationFactor::U3_functor::operator()(), madness::NuclearCorrelationFactor::U3_atomic_functor::operator()(), madness::NuclearCorrelationFactor::RX_functor::operator()(), madness::NuclearCorrelationFactor::U1X_functor::operator()(), madness::NuclearCorrelationFactor::U3X_functor::operator()(), madness::GaussSlater::U2X_spherical(), madness::GradientalGaussSlater::U2X_spherical(), madness::Slater::U2X_spherical(), and madness::Polynomial< N >::U2X_spherical().
Srr_div_S()
virtual double madness::NuclearCorrelationFactor::Srr_div_S (const double & r, const double & Z) const pure virtual
second derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
Referenced by madness::NuclearCorrelationFactor::U1X_functor::operator()(), madness::NuclearCorrelationFactor::U3X_functor::operator()(), madness::GaussSlater::U2X_spherical(), madness::GradientalGaussSlater::U2X_spherical(), madness::Slater::U2X_spherical(), and madness::Polynomial< N >::U2X_spherical().
Srrr_div_S()
virtual double madness::NuclearCorrelationFactor::Srrr_div_S (const double & r, const double & Z) const pure virtual
third derivative of the NCF with respect to the relative distance rho
where the distance of the electron to the nucleus A is given by
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
Referenced by madness::GaussSlater::U2X_spherical(), madness::GradientalGaussSlater::U2X_spherical(), madness::Slater::U2X_spherical(), and madness::Polynomial< N >::U2X_spherical().
type()
virtual corrfactype madness::NuclearCorrelationFactor::type () const pure virtual
Implemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::LinearSlater, madness::GradientalGaussSlater, and madness::GaussSlater.
U1()
virtual const real_function_3d madness::NuclearCorrelationFactor::U1 (const int axis) const inline virtual
return the U1 term of the correlation function
References axis, and U1_function.
Referenced by apply_U().
U1vec()
std::vector<real_function_3d> madness::NuclearCorrelationFactor::U1vec () const inline
return the U1 functions in a vector
References U1_function.
U2()
virtual const real_function_3d madness::NuclearCorrelationFactor::U2 () const inline virtual
return the U2 term of the correlation function
Reimplemented in madness::PseudoNuclearCorrelationFactor.
References U2_function.
Referenced by apply_U(), and madness::PseudoNuclearCorrelationFactor::apply_U().
U2X_spherical()
virtual double madness::NuclearCorrelationFactor::U2X_spherical (const double & r, const double & Z, const double & rcut) const inline virtual
derivative of the U2 potential wrt nuclear coordinate X (spherical part)
need to reimplement this for all derived classes due to the range for r -> 0, where the singular terms cancel. With
returns the term in the parenthesis without the the derivative of rho
Reimplemented in madness::PseudoNuclearCorrelationFactor, madness::Polynomial< N >, madness::poly4erfc, madness::Slater, madness::GradientalGaussSlater, and madness::GaussSlater.
References MADNESS_EXCEPTION, madness::print(), madness::World::rank(), and world.
Referenced by madness::NuclearCorrelationFactor::U2X_functor::operator()().
Member Data Documentation
molecule
const Molecule& madness::NuclearCorrelationFactor::molecule private
the molecule
Referenced by dsmoothed_unitvec(), madness::NuclearCorrelationFactor::R_functor::operator()(), madness::NuclearCorrelationFactor::U1_functor::operator()(), madness::NuclearCorrelationFactor::U1_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U1_dot_U1_functor::operator()(), madness::NuclearCorrelationFactor::U2_functor::operator()(), madness::NuclearCorrelationFactor::U3_functor::operator()(), madness::NuclearCorrelationFactor::U2_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U3_atomic_functor::operator()(), madness::NuclearCorrelationFactor::square_times_V_functor::operator()(), madness::NuclearCorrelationFactor::square_times_V_derivative_functor::operator()(), madness::NuclearCorrelationFactor::RX_functor::operator()(), madness::NuclearCorrelationFactor::U2X_functor::operator()(), madness::NuclearCorrelationFactor::U3X_functor::operator()(), smoothed_unitvec(), madness::NuclearCorrelationFactor::R_functor::special_points(), madness::NuclearCorrelationFactor::U1_functor::special_points(), madness::NuclearCorrelationFactor::U1_atomic_functor::special_points(), madness::NuclearCorrelationFactor::U1_dot_U1_functor::special_points(), madness::NuclearCorrelationFactor::U2_functor::special_points(), madness::NuclearCorrelationFactor::U3_functor::special_points(), madness::NuclearCorrelationFactor::U2_atomic_functor::special_points(), madness::NuclearCorrelationFactor::U3_atomic_functor::special_points(), madness::NuclearCorrelationFactor::square_times_V_functor::special_points(), madness::NuclearCorrelationFactor::square_times_V_derivative_functor::special_points(), madness::NuclearCorrelationFactor::RX_functor::special_points(), madness::NuclearCorrelationFactor::U2X_functor::special_points(), madness::NuclearCorrelationFactor::U3X_functor::special_points(), square_times_V_derivative(), and madness::NuclearCorrelationFactor::U2X_functor::U2X_functor().
U1_function
std::vector<real_function_3d> madness::NuclearCorrelationFactor::U1_function private
the three components of the U1 potential
Referenced by initialize(), U1(), and U1vec().
U2_function
real_function_3d madness::NuclearCorrelationFactor::U2_function private
the purely local U2 potential, having absorbed the nuclear pot V_nuc
Referenced by initialize(), and U2().
vtol
double madness::NuclearCorrelationFactor::vtol private
the threshold for initial projection
Referenced by function(), initialize(), inverse(), square(), and square_times_V_derivative().
world
World& madness::NuclearCorrelationFactor::world private
the world
Referenced by apply_U(), function(), madness::GaussSlater::GaussSlater(), madness::GradientalGaussSlater::GradientalGaussSlater(), initialize(), inverse(), madness::LinearSlater::LinearSlater(), madness::poly4erfc::poly4erfc(), madness::Polynomial< N >::Polynomial(), madness::PseudoNuclearCorrelationFactor::PseudoNuclearCorrelationFactor(), madness::Slater::Slater(), square(), square_times_V_derivative(), and U2X_spherical().
The documentation for this class was generated from the following file:
correlationfactor.h