MADNESS: madness::BandlimitedPropagator Class Reference
madness::BandlimitedPropagator Class Reference
Class to evaluate the filtered Schrodinger free-particle propagator in real space.
Public Types
typedef double_complex returnT
Public Member Functions
BandlimitedPropagator (double c, double t, double width)
Level natural_level () const
std::complex< double > operator() (double x) const
Static Public Member Functions
static void plot ()
static void test ()
Private Member Functions
double_complex g0_filtered (double k, double c, double t)
Private Attributes
CubicInterpolationTable< double_complex > fit
double width
double xmax
Detailed Description
Class to evaluate the filtered Schrodinger free-particle propagator in real space.
Follows the corresponding Maple worksheet and the implementation notes.
Member Typedef Documentation
returnT
typedef double_complex madness::BandlimitedPropagator::returnT
Constructor & Destructor Documentation
BandlimitedPropagator()
madness::BandlimitedPropagator::BandlimitedPropagator (double c, double t, double width) inline
References madness::abs(), std::abs(), c, e(), fit, g0_filtered(), CFFT::Inverse(), k, madness::kmax, MADNESS_ASSERT, N, madness::constants::pi, pow(), and xmax.
Member Function Documentation
g0_filtered()
double_complex madness::BandlimitedPropagator::g0_filtered (double k, double c, double t) inline private
References madness::arg(), c, k, and pow().
Referenced by BandlimitedPropagator().
natural_level()
Level madness::BandlimitedPropagator::natural_level () const inline
operator()()
std::complex<double> madness::BandlimitedPropagator::operator() (double x) const inline
References fit, width, and xmax.
plot()
static void madness::BandlimitedPropagator::plot () inline static
References c, madness::print(), tcrit, test(), and width.
Referenced by madness::bandlimited_propagator_plot().
test()
static void madness::BandlimitedPropagator::test () inline static
References std::abs(), and e().
Referenced by plot().
Member Data Documentation
fit
CubicInterpolationTable<double_complex> madness::BandlimitedPropagator::fit private
Referenced by BandlimitedPropagator(), and operator()().
width
double madness::BandlimitedPropagator::width private
Referenced by operator()(), and plot().
xmax
double madness::BandlimitedPropagator::xmax private
Referenced by BandlimitedPropagator(), and operator()().
The documentation for this class was generated from the following file:
qmprop.cc