MADNESS: madness::SCF Class Reference
madness::SCF Class Reference
#include <SCF.h>
Public Member Functions
SCF (World &world, const std::string &inputfile)
collective constructor for SCF uses contents of file filename and broadcasts to all nodes
void analyze_vectors (World &world, const vecfuncT &mo, const tensorT &occ=tensorT(), const tensorT &energy=tensorT(), const std::vector< int > &set=std::vector< int >())
complex_functionT APPLY (const complex_operatorT *q1d, const complex_functionT &psi)
vecfuncT apply_hf_exchange (World &world, const tensorT &occ, const vecfuncT &psi, const vecfuncT &f) const
apply the HF exchange on a set of orbitals
vecfuncT apply_potential (World &world, const tensorT &occ, const vecfuncT &amo, const functionT &vlocal, double &exc, double &enl, int ispin)
vecfuncT apply_potential_response (World &world, const vecfuncT &dmo, const XCOperator &xc, const functionT &vlocal, int ispin)
vecfuncT calc_dipole_mo (World &world, vecfuncT &mo, const int axis)
vecfuncT calc_djkmo (World &world, XCOperator &xc_alda, const vecfuncT &dmo1, const vecfuncT &dmo2, const functionT &drho, const vecfuncT &mo, const functionT &drhos, int spin)
void calc_dpolar (World &world, const vecfuncT &ax, const vecfuncT &ay, const vecfuncT &bx, const vecfuncT &by, const int axis, tensorT &Dpolar_total, tensorT &Dpolar_alpha, tensorT &Dpolar_beta)
functionT calc_exchange_function (World &world, const int &p, const vecfuncT &dmo1, const vecfuncT &dmo2, const vecfuncT &mo, int &spin)
void calc_freq (World &world, double &omega, tensorT &ak, tensorT &bk, int sign)
void calc_response_function (World &world, vecfuncT &dmo, std::vector< poperatorT > &op, vecfuncT &rhs)
vecfuncT calc_rhs (World &world, const vecfuncT &mo, const vecfuncT &Vdmo, const vecfuncT &dipolemo, const vecfuncT &djkmo)
vecfuncT calc_xc_function (World &world, XCOperator &xc_alda, const vecfuncT &mo, const functionT &drho)
param[in] drho the perturbed density
vecfuncT compute_residual (World &world, tensorT &occ, tensorT &fock, const vecfuncT &psi, vecfuncT &Vpsi, double &err)
vecfuncT core_projection (World &world, const vecfuncT &psi, const bool include_Bc=true)
double core_projector_derivative (World &world, const vecfuncT &mo, const tensorT &occ, int atom, int axis)
tensorT derivatives (World &world, const functionT &rho) const
tensorT diag_fock_matrix (World &world, tensorT &fock, vecfuncT &psi, vecfuncT &Vpsi, tensorT &evals, const tensorT &occ, const double thresh) const
diagonalize the fock matrix, taking care of degenerate states
double DIP (const tensorT &dip, int i, int j, int k, int l) const
tensorT dipole (World &world, const functionT &rho) const
compute the total dipole moment of the molecule
void dipole_matrix_elements (World &world, const vecfuncT &mo, const tensorT &occ=tensorT(), const tensorT &energy=tensorT(), int spin=0)
void do_plots (World &world)
double do_step_restriction (World &world, const vecfuncT &mo, vecfuncT &mo_new, std::string spin) const
perform step restriction following the KAIN solver
void dpolar (World &world, tensorT &polar, functionT &drho, const int axis)
const vecfuncT & get_amo () const
getter for the molecular orbitals, alpha spin
const tensorT & get_aocc () const
getter for the occupation numbers, alpha spin
const vecfuncT & get_bmo () const
getter for the molecular orbitals, beta spin
const tensorT & get_bocc () const
getter for the occupation numbers, alpha spin
tensorT get_fock_transformation (World &world, const tensorT &overlap, tensorT &fock, tensorT &evals, const tensorT &occ, const double thresh_degenerate) const
compute the unitary transformation that diagonalizes the fock matrix
std::vector< int > group_orbital_sets (World &world, const tensorT &eps, const tensorT &occ, const int nmo) const
group orbitals into sets of similar orbital energies for localization
void initial_guess (World &world)
void initial_load_bal (World &world)
bool is_spin_restricted () const
void iterate_trotter (World &world, Convolution1D< double_complex > *G, cvecfuncT &camo, cvecfuncT &cbmo, double t, double time_step, double thresh)
distmatT kinetic_energy_matrix (World &world, const vecfuncT &v) const
distmatT kinetic_energy_matrix (World &world, const vecfuncT &vbra, const vecfuncT &vket) const
void load_mos (World &world)
void loadbal (World &world, functionT &arho, functionT &brho, functionT &arho_old, functionT &brho_old, subspaceT &subspace)
distmatT localize_boys (World &world, const vecfuncT &mo, const std::vector< int > &set, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true, const bool doprint=false) const
distmatT localize_new (World &world, const vecfuncT &mo, const std::vector< int > &set, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true, const bool doprint=false) const
distmatT localize_PM (World &world, const vecfuncT &mo, const std::vector< int > &set, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true, const bool doprint=false) const
compute the unitary localization matrix according to Pipek-Mezey
std::vector< poperatorT > make_bsh_operators (World &world, const tensorT &evals) const
void make_BSHOperatorPtr (World &world, tensorT &ak, tensorT &bk, std::vector< poperatorT > &aop, std::vector< poperatorT > &bop)
functionT make_coulomb_potential (const functionT &rho) const
End functions for polarizability.
functionT make_density (World &world, const tensorT &occ, const vecfuncT &v) const
functionT make_density (World &world, const tensorT &occ, const cvecfuncT &v)
functionT make_density_ground (World &world, functionT &arho, functionT &brho)
functionT make_derivative_density (World &world, const vecfuncT &mo, const tensorT &occ, const vecfuncT &x, const vecfuncT &y)
double make_dft_energy (World &world, const vecfuncT &vf, int ispin)
tensorT make_fock_matrix (World &world, const vecfuncT &psi, const vecfuncT &Vpsi, const tensorT &occ, double &ekinetic) const
std::vector< poperatorT > make_gradbsh_operators (World &world, const tensorT &evals, const int axis) const
functionT make_lda_potential (World &world, const functionT &arho)
apply the HF exchange on a set of orbitals
void make_nuclear_potential (World &world)
tensorT matrix_exponential (const tensorT &A) const
void orthogonalize_response (World &world, vecfuncT &dmo, vecfuncT &mo)
void orthonormalize (World &world, vecfuncT &amo_new) const
orthonormalize the vectors
void orthonormalize (World &world, vecfuncT &amo_new, int nocc) const
orthonormalize the vectors (symmetric in occupied spaced, gramm-schmidt for virt to occ)
void polarizability (World &world)
void project (World &world)
vecfuncT project_ao_basis (World &world, const AtomicBasisSet &aobasis)
void propagate (World &world, double omega, int step0)
void reset_aobasis (const std::string &aobasisname)
double residual_response (World &world, const vecfuncT &x, const vecfuncT &y, const vecfuncT &x_old, const vecfuncT &y_old, vecfuncT &rx, vecfuncT &ry)
bool restart_aos (World &world)
void rotate_subspace (World &world, const tensorT &U, subspaceT &subspace, int lo, int nfunc, double trantol) const
void rotate_subspace (World &world, const distmatT &U, subspaceT &subspace, int lo, int nfunc, double trantol) const
void save_mos (World &world)
template<std::size_t NDIM>
void set_protocol (World &world, double thresh)
void solve (World &world)
void this_axis (World &world, const int axis)
Tensor< double > twoint (World &world, const vecfuncT &psi) const
Compute the two-electron integrals over the provided set of orbitals.
void update_response_subspace (World &world, vecfuncT &ax, vecfuncT &ay, vecfuncT &bx, vecfuncT &by, vecfuncT &rax, vecfuncT &ray, vecfuncT &rbx, vecfuncT &rby, subspaceT &subspace, tensorT &Q, double &update_residual)
Begin functions for polarizability.
void update_subspace (World &world, vecfuncT &Vpsia, vecfuncT &Vpsib, tensorT &focka, tensorT &fockb, subspaceT &subspace, tensorT &Q, double &bsh_residual, double &update_residual)
void vector_stats (const std::vector< double > &v, double &rms, double &maxabsval) const
Static Public Member Functions
static vecfuncT project_ao_basis_only (World &world, const AtomicBasisSet &aobasis, const Molecule &molecule)
Public Attributes
tensorT aeps
orbital energies for alpha and beta orbitals
vecfuncT amo
alpha and beta molecular orbitals
vecfuncT ao
MRA projection of the minimal basis set.
AtomicBasisSet aobasis
tensorT aocc
occupation numbers for alpha and beta orbitals
std::vector< int > aset
std::vector< int > at_nbf
std::vector< int > at_to_bf
tensorT beps
vecfuncT bmo
tensorT bocc
std::vector< int > bset
poperatorT coulop
double current_energy
std::vector< std::shared_ptr< real_derivative_3d > > gradop
std::shared_ptr< GTHPseudopotential< double > > gthpseudopotential
functionT mask
Molecule molecule
CalculationParameters param
PCM pcm
std::shared_ptr< PotentialManager > potentialmanager
double vtol
XCfunctional xc
Constructor & Destructor Documentation
SCF()
madness::SCF::SCF (World & world, const std::string & inputfile)
collective constructor for SCF uses contents of file filename and broadcasts to all nodes
collective constructor, reads input on rank 0, broadcasts to all
collective constructor for SCF uses contents of stream input and broadcasts to all nodes
References madness::CalculationParameters::aobasis(), aobasis, madness::WorldGopInterface::broadcast_serializable(), madness::CalculationParameters::core_type(), madness::CalculationParameters::econv(), madness::QCCalculationParametersBase::get(), madness::Molecule::get_atom_number(), madness::get_charge_from_file(), madness::Molecule::get_pseudo_atom(), madness::World::gop, madness::XCfunctional::initialize(), madness::CalculationParameters::L(), molecule, madness::Molecule::natom(), madness::CalculationParameters::no_orient(), madness::Molecule::orient(), param, madness::CalculationParameters::print_level(), madness::print_timings, PROFILE_MEMBER_FUNC, madness::World::rank(), madness::CalculationParameters::read(), madness::Molecule::read(), madness::Molecule::read_core_file(), reset_aobasis(), madness::Molecule::set_atom_charge(), madness::CalculationParameters::set_derived_values(), madness::Molecule::set_pseudo_atom(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::CalculationParameters::spin_restricted(), madness::CalculationParameters::xc(), and xc.
Member Function Documentation
analyze_vectors()
void madness::SCF::analyze_vectors (World & world, const vecfuncT & mo, const tensorT & occ = tensorT(), const tensorT & energy = tensorT(), const std::vector< int > & set = std::vector<int>())
References madness::_(), ao, aobasis, axis, C, madness::END_TIMER(), energy, madness::gesvp(), madness::inner(), madness::matrix_inner(), molecule, madness::mul_sparse(), param, madness::AtomicBasisSet::print_anal(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::World::rank(), madness::rsquared(), madness::BaseTensor::size(), madness::START_TIMER(), madness::transpose(), and vtol.
Referenced by solve().
APPLY()
complex_functionT madness::SCF::APPLY (const complex_operatorT * q1d, const complex_functionT & psi) inline
References madness::apply_1d_realspace_push(), madness::Function< T, NDIM >::broaden(), lo, psi(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::sum_down().
Referenced by iterate_trotter().
apply_hf_exchange()
vecfuncT madness::SCF::apply_hf_exchange (World & world, const tensorT & occ, const vecfuncT & psi, const vecfuncT & f) const
apply the HF exchange on a set of orbitals
Parameters
[in] world the world
[in] occ occupation numbers
[in] psi the orbitals in the exchange operator
[in] f the orbitals |i> that the operator is applied on
Returns
a vector of orbitals K| i>
apply_potential()
vecfuncT madness::SCF::apply_potential (World & world, const tensorT & occ, const vecfuncT & amo, const functionT & vlocal, double & exc, double & enl, int ispin)
References amo, madness::XCOperator::compute_xc_energy(), madness::copy(), madness::CalculationParameters::dft_deriv(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, gthpseudopotential, madness::XCfunctional::hf_exchange_coefficient(), madness::inner(), madness::XCfunctional::is_dft(), madness::XCfunctional::is_spin_polarized(), madness::mul_sparse(), param, potentialmanager, madness::print_meminfo(), PROFILE_MEMBER_FUNC, madness::CalculationParameters::pure_ae(), madness::World::rank(), madness::Exchange< T, NDIM >::same(), madness::START_TIMER(), madness::truncate(), madness::Function< T, NDIM >::truncate(), vtol, and xc.
Referenced by solve().
apply_potential_response()
vecfuncT madness::SCF::apply_potential_response (World & world, const vecfuncT & dmo, const XCOperator & xc, const functionT & vlocal, int ispin)
References amo, bmo, madness::copy(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, madness::XCfunctional::hf_exchange_coefficient(), madness::XCfunctional::is_dft(), madness::XCOperator::make_xc_potential(), madness::mul_sparse(), param, potentialmanager, madness::print_meminfo(), madness::CalculationParameters::pure_ae(), madness::World::rank(), madness::Exchange< T, NDIM >::same(), madness::XCOperator::set_ispin(), madness::START_TIMER(), madness::truncate(), vtol, and xc.
Referenced by polarizability().
calc_dipole_mo()
vecfuncT madness::SCF::calc_dipole_mo (World & world, vecfuncT & mo, const int axis)
References axis, madness::f, madness::mul_sparse(), p(), madness::print_meminfo(), madness::reconstruct(), madness::World::size(), and madness::truncate().
Referenced by polarizability().
calc_djkmo()
vecfuncT madness::SCF::calc_djkmo (World & world, XCOperator & xc_alda, const vecfuncT & dmo1, const vecfuncT & dmo2, const functionT & drho, const vecfuncT & mo, const functionT & drhos, int spin)
Parameters
[in] drho the perturbed density
References calc_exchange_function(), calc_xc_function(), madness::END_TIMER(), madness::gaxpy(), madness::XCfunctional::hf_exchange_coefficient(), p(), madness::print_meminfo(), madness::World::size(), madness::START_TIMER(), madness::truncate(), and xc.
Referenced by polarizability().
calc_dpolar()
void madness::SCF::calc_dpolar (World & world, const vecfuncT & ax, const vecfuncT & ay, const vecfuncT & bx, const vecfuncT & by, const int axis, tensorT & Dpolar_total, tensorT & Dpolar_alpha, tensorT & Dpolar_beta)
References amo, aocc, axis, bmo, bocc, madness::Function< T, NDIM >::clear(), dpolar(), make_derivative_density(), madness::CalculationParameters::nbeta(), param, pow(), madness::print(), madness::print_meminfo(), madness::World::rank(), madness::CalculationParameters::response_freq(), madness::CalculationParameters::spin_restricted(), madness::syev(), and V().
Referenced by polarizability().
calc_exchange_function()
functionT madness::SCF::calc_exchange_function (World & world, const int & p, const vecfuncT & dmo1, const vecfuncT & dmo2, const vecfuncT & mo, int & spin)
References madness::apply(), coulop, k1, k2, p(), madness::reconstruct(), and madness::Function< T, NDIM >::truncate().
Referenced by calc_djkmo().
calc_freq()
void madness::SCF::calc_freq (World & world, double & omega, tensorT & ak, tensorT & bk, int sign)
References aeps, beps, madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), omega, param, madness::print(), madness::World::rank(), and madness::CalculationParameters::spin_restricted().
Referenced by polarizability().
calc_response_function()
void madness::SCF::calc_response_function (World & world, vecfuncT & dmo, std::vector< poperatorT > & op, vecfuncT & rhs)
References madness::apply(), op(), madness::scale(), and madness::truncate().
Referenced by polarizability().
calc_rhs()
vecfuncT madness::SCF::calc_rhs (World & world, const vecfuncT & mo, const vecfuncT & Vdmo, const vecfuncT & dipolemo, const vecfuncT & djkmo)
References madness::add(), madness::print_meminfo(), madness::World::rank(), and madness::truncate().
Referenced by polarizability().
calc_xc_function()
vecfuncT madness::SCF::calc_xc_function (World & world, XCOperator & xc_alda, const vecfuncT & mo, const functionT & drho)
param[in] drho the perturbed density
References madness::apply(), madness::XCOperator::apply_xc_kernel(), coulop, madness::END_TIMER(), madness::XCfunctional::hf_exchange_coefficient(), madness::XCfunctional::is_dft(), madness::mul_sparse(), madness::print_meminfo(), madness::World::rank(), madness::reconstruct(), madness::START_TIMER(), madness::truncate(), madness::Function< T, NDIM >::truncate(), vtol, and xc.
Referenced by calc_djkmo().
compute_residual()
vecfuncT madness::SCF::compute_residual (World & world, tensorT & occ, tensorT & fock, const vecfuncT & psi, vecfuncT & Vpsi, double & err)
References madness::apply(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, make_bsh_operators(), madness::norm2s(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, psi(), madness::World::rank(), madness::scale(), madness::set_thresh(), madness::START_TIMER(), madness::sub(), madness::transform(), madness::truncate(), vector_stats(), and vtol.
Referenced by update_subspace().
core_projection()
vecfuncT madness::SCF::core_projection (World & world, const vecfuncT & psi, const bool include_Bc = true)
References madness::Atom::atomic_number, c, madness::Function< T, NDIM >::fence(), madness::Molecule::get_atom(), madness::Molecule::get_core_bc(), madness::Molecule::get_core_l(), madness::inner(), m, molecule, madness::Molecule::n_core_orb(), madness::Molecule::natom(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, psi(), and madness::Function< T, NDIM >::scale().
core_projector_derivative()
double madness::SCF::core_projector_derivative (World & world, const vecfuncT & mo, const tensorT & occ, int atom, int axis)
References madness::Atom::atomic_number, axis, c, madness::func(), madness::Molecule::get_atom(), madness::Molecule::get_core_bc(), madness::Molecule::get_core_l(), madness::inner(), m, molecule, madness::Molecule::n_core_orb(), and PROFILE_MEMBER_FUNC.
derivatives()
tensorT madness::SCF::derivatives (World & world, const functionT & rho) const
References amo, aocc, axis, bmo, bocc, madness::CalculationParameters::core_type(), madness::END_TIMER(), madness::func(), madness::Molecule::get_atom(), madness::inner(), madness::Molecule::is_potential_defined_atom(), molecule, madness::Molecule::natom(), madness::CalculationParameters::nbeta(), madness::Molecule::nuclear_repulsion_derivative(), param, potentialmanager, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::BaseTensor::size(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), truncate_mode, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by madness::MolecularEnergy::energy_and_gradient(), madness::MolecularEnergy::gradient(), and main().
diag_fock_matrix()
tensorT madness::SCF::diag_fock_matrix (World & world, tensorT & fock, vecfuncT & psi, vecfuncT & Vpsi, tensorT & evals, const tensorT & occ, const double thresh) const
diagonalize the fock matrix, taking care of degenerate states
Vpsi is passed in to make sure orbitals and Vpsi are in phase
Parameters
[in] world the world
[in,out] fock the fock matrix (diagonal upon exit)
[in,out] psi the orbitals
[in,out] Vpsi the orbital times the potential
[out] evals the orbital energies
[in] occ occupation numbers
[in] thresh threshold for rotation and truncation
Returns
the unitary matrix U: U^T F U = evals
Vpsi is passed in to make sure orbitals and Vpsi are in phase
Parameters
[in] world the world
[in,out] fock the fock matrix (diagonal upon exit)
[in,out] psi the orbitals
[in,out] Vpsi the orbital times the potential
[out] evals the orbital energies
[in] occ occupation numbers
[in] thresh threshold for rotation and truncation
Returns
the unitary matrix U: U^T F U = evals
References madness::BaseTensor::dim(), madness::END_TIMER(), get_fock_transformation(), madness::matrix_inner(), madness::CalculationParameters::nalpha(), madness::normalize(), param, PROFILE_MEMBER_FUNC, psi(), thresh, madness::transform(), madness::truncate(), and vtol.
Referenced by solve().
DIP()
double madness::SCF::DIP (const tensorT & dip, int i, int j, int k, int l) const inline
References k.
Referenced by localize_boys().
dipole()
tensorT madness::SCF::dipole (World & world, const functionT & rho) const
compute the total dipole moment of the molecule
Parameters
[in] rho the total (alpha + beta) density
Returns
the x,y,z components of the el. + nucl. dipole moment
References axis, madness::END_TIMER(), molecule, mu, madness::Molecule::nuclear_dipole(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::World::rank(), and madness::START_TIMER().
Referenced by main(), and solve().
dipole_matrix_elements()
void madness::SCF::dipole_matrix_elements (World & world, const vecfuncT & mo, const tensorT & occ = tensorT(), const tensorT & energy = tensorT(), int spin = 0)
References madness::_(), axis, madness::END_TIMER(), energy, madness::f, madness::matrix_inner(), madness::mul_sparse(), madness::START_TIMER(), and vtol.
Referenced by solve().
do_plots()
void madness::SCF::do_plots (World & world)
References amo, aocc, madness::apply(), bmo, bocc, madness::copy(), coulop, madness::END_TIMER(), madness::QCCalculationParametersBase::get(), make_density(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), param, madness::CalculationParameters::plot_cell(), madness::plotdx(), potentialmanager, PROFILE_MEMBER_FUNC, madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::scale(), madness::BaseTensor::size(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), madness::Function< T, NDIM >::truncate(), and vnuc().
Referenced by main().
do_step_restriction()
double madness::SCF::do_step_restriction (World & world, const vecfuncT & mo, vecfuncT & mo_new, std::string spin) const
perform step restriction following the KAIN solver
undo the rotation from the KAIN solver if the rotation exceeds the maxrotn parameter
Parameters
[in] world the world
[in] mo vector of orbitals from previous iteration
[in,out] mo_new vector of orbitals from the KAIN solver
[in] spin "alpha" or "beta" for user information
Returns
max residual
Limit maximum step size to make convergence more robust
Parameters
[in] world the world
[in] mo vector of orbitals from previous iteration
[in,out] new_mo vector of orbitals from the KAIN solver
[in] spin "alpha" or "beta" for user information
Returns
max residual
References madness::WorldGopInterface::fence(), madness::World::gop, madness::CalculationParameters::maxrotn(), madness::norm2s(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::World::rank(), madness::sub(), and vector_stats().
Referenced by update_subspace().
dpolar()
void madness::SCF::dpolar (World & world, tensorT & polar, functionT & drho, const int axis)
References axis, and madness::f.
Referenced by calc_dpolar().
get_amo()
const vecfuncT& madness::SCF::get_amo () const inline
getter for the molecular orbitals, alpha spin
References amo.
Referenced by madness::Coulomb::compute_density().
get_aocc()
const tensorT& madness::SCF::get_aocc () const inline
getter for the occupation numbers, alpha spin
References aocc.
Referenced by madness::Coulomb::compute_density().
get_bmo()
const vecfuncT& madness::SCF::get_bmo () const inline
getter for the molecular orbitals, beta spin
References bmo.
Referenced by madness::Coulomb::compute_density().
get_bocc()
const tensorT& madness::SCF::get_bocc () const inline
getter for the occupation numbers, alpha spin
References bocc.
Referenced by madness::Coulomb::compute_density().
get_fock_transformation()
tensorT madness::SCF::get_fock_transformation (World & world, const tensorT & overlap, tensorT & fock, tensorT & evals, const tensorT & occ, const double thresh_degenerate) const
compute the unitary transformation that diagonalizes the fock matrix
Parameters
[in] world the world
[in] overlap the overlap matrix of the orbitals
[in,out] fock the fock matrix; diagonal upon exit
[out] evals the orbital energies
[in] occ the occupation numbers
[in] thresh_degenerate threshold for orbitals being degenerate
Returns
the unitary matrix U: U^T F U = evals
Parameters
[in] world the world
[in] overlap the overlap matrix of the orbitals
[in,out] fock the fock matrix; diagonal upon exit
[out] evals the orbital energies
[in] occ the occupation numbers
[in] thresh_degenerate threshold for orbitals being degenerate
Returns
the unitary matrix U: U^T F U = evals
References madness::_(), madness::WorldGopInterface::broadcast(), madness::copy(), madness::BaseTensor::dim(), madness::END_TIMER(), madness::World::gop, madness::inner(), max, PROFILE_MEMBER_FUNC, madness::Tensor< T >::ptr(), q(), madness::Tensor< T >::scale(), sigma, madness::BaseTensor::size(), madness::START_TIMER(), madness::svd(), madness::swap(), madness::sygvp(), and madness::transpose().
Referenced by diag_fock_matrix().
group_orbital_sets()
std::vector< int > madness::SCF::group_orbital_sets (World & world, const tensorT & eps, const tensorT & occ, const int nmo) const
group orbitals into sets of similar orbital energies for localization
Parameters
[in] eps orbital energies
[in] occ occupation numbers
[in] nmo number of MOs for the given spin
Returns
vector of length nmo with the set index for each MO
References lo, madness::CalculationParameters::localize_pm(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, and madness::World::rank().
Referenced by initial_guess().
initial_guess()
void madness::SCF::initial_guess (World & world)
References madness::_(), madness::LoadBalanceDeux< NDIM >::add_tree(), aeps, amo, ao, aobasis, aocc, madness::apply(), aset, beps, bmo, bocc, bset, c, madness::Function< T, NDIM >::clear(), madness::compress(), madness::DistributedMatrix< T >::copy_to_replicated(), madness::CalculationParameters::core_type(), coulop, e(), madness::END_TIMER(), madness::QCCalculationParametersBase::get(), madness::Molecule::get_atom_charge(), madness::Molecule::get_atom_number(), madness::Molecule::get_pseudo_atom(), group_orbital_sets(), gthpseudopotential, kinetic_energy_matrix(), madness::LoadBalanceDeux< NDIM >::load_balance(), load_mos(), make_lda_potential(), madness::matrix_inner(), madness::AtomicBasisSet::modify_dmat_psp(), molecule, madness::mul_sparse(), madness::Molecule::n_core_orb_all(), madness::CalculationParameters::nalpha(), madness::Molecule::natom(), madness::CalculationParameters::nbeta(), madness::CalculationParameters::nmo_alpha(), madness::CalculationParameters::nmo_beta(), madness::normalize(), param, potential(), potentialmanager, madness::print(), madness::CalculationParameters::print_level(), madness::print_meminfo(), PROFILE_MEMBER_FUNC, madness::CalculationParameters::psp_calc(), madness::CalculationParameters::pure_ae(), madness::World::rank(), madness::reconstruct(), madness::Function< T, NDIM >::reconstruct(), madness::CalculationParameters::restart(), madness::Function< T, NDIM >::scale(), madness::World::size(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), madness::sygvp(), madness::Function< T, NDIM >::trace(), madness::transform(), madness::transpose(), madness::truncate(), madness::Function< T, NDIM >::truncate(), vnuc(), madness::CalculationParameters::vnucextra(), and vtol.
Referenced by madness::MolecularEnergy::value().
initial_load_bal()
void madness::SCF::initial_load_bal (World & world)
References madness::LoadBalanceDeux< NDIM >::add_tree(), gthpseudopotential, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::CalculationParameters::loadbalparts(), param, potentialmanager, PROFILE_MEMBER_FUNC, madness::CalculationParameters::psp_calc(), madness::CalculationParameters::pure_ae(), vnuc(), and madness::CalculationParameters::vnucextra().
Referenced by main(), and propagate().
is_spin_restricted()
bool madness::SCF::is_spin_restricted () const inline
References madness::QCCalculationParametersBase::get(), and param.
Referenced by madness::Coulomb::compute_density().
iterate_trotter()
void madness::SCF::iterate_trotter (World & world, Convolution1D< double_complex > * G, cvecfuncT & camo, cvecfuncT & cbmo, double t, double time_step, double thresh)
References amo, aocc, APPLY(), madness::apply(), bmo, bocc, coulop, expV(), make_density(), madness::make_exp(), madness::mul_sparse(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), param, potentialmanager, PROFILE_MEMBER_FUNC, madness::CalculationParameters::spin_restricted(), thresh, vnuc(), and vtol.
Referenced by propagate().
kinetic_energy_matrix() [1/2]
distmatT madness::SCF::kinetic_energy_matrix (World & world, const vecfuncT & v) const
References madness::apply(), madness::compress(), madness::DistributedMatrixDistribution::distribution(), madness::END_TIMER(), gradop, madness::matrix_inner(), PROFILE_MEMBER_FUNC, madness::reconstruct(), and madness::START_TIMER().
Referenced by initial_guess(), and make_fock_matrix().
kinetic_energy_matrix() [2/2]
distmatT madness::SCF::kinetic_energy_matrix (World & world, const vecfuncT & vbra, const vecfuncT & vket) const
References madness::apply(), madness::compress(), madness::DistributedMatrixDistribution::distribution(), gradop, MADNESS_ASSERT, madness::matrix_inner(), PROFILE_MEMBER_FUNC, and madness::reconstruct().
load_mos()
void madness::SCF::load_mos (World & world)
References aeps, amo, aocc, aset, beps, bmo, bocc, bset, madness::copy(), current_energy, madness::WorldGopInterface::fence(), madness::World::gop, k, MADNESS_ASSERT, molecule, madness::Molecule::n_core_orb_all(), madness::CalculationParameters::nmo_alpha(), madness::CalculationParameters::nmo_beta(), param, PROFILE_MEMBER_FUNC, madness::project(), madness::reconstruct(), madness::set_thresh(), madness::CalculationParameters::spin_restricted(), and thresh.
Referenced by initial_guess(), propagate(), and madness::MolecularEnergy::value().
loadbal()
void madness::SCF::loadbal (World & world, functionT & arho, functionT & brho, functionT & arho_old, functionT & brho_old, subspaceT & subspace)
References madness::LoadBalanceDeux< NDIM >::add_tree(), amo, bmo, madness::WorldGopInterface::fence(), madness::World::gop, gthpseudopotential, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::CalculationParameters::loadbalparts(), madness::CalculationParameters::nbeta(), param, potentialmanager, madness::CalculationParameters::psp_calc(), madness::CalculationParameters::pure_ae(), madness::World::size(), madness::CalculationParameters::spin_restricted(), vnuc(), and madness::CalculationParameters::vnucextra().
Referenced by solve().
localize_boys()
distmatT madness::SCF::localize_boys (World & world, const vecfuncT & mo, const std::vector< int > & set, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true, const bool doprint = false) const
References madness::_(), axis, madness::WorldGopInterface::broadcast(), madness::copy(), madness::DistributedMatrix< T >::copy_from_replicated(), DIP(), e(), madness::END_TIMER(), f1, madness::g, madness::Tensor< T >::gaxpy(), madness::World::gop, madness::inner(), matrix_exponential(), madness::matrix_inner(), max, mu, madness::mul_sparse(), N, madness::print(), madness::Tensor< T >::ptr(), madness::RandomValue< double >(), madness::World::rank(), madness::Tensor< T >::scale(), madness::BaseTensor::size(), madness::START_TIMER(), thresh, madness::Tensor< T >::trace(), madness::transpose(), and vtol.
Referenced by solve().
localize_new()
distmatT madness::SCF::localize_new (World & world, const vecfuncT & mo, const std::vector< int > & set, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true, const bool doprint = false) const
References madness::_(), a, std::abs(), aeps, ao, aobasis, at_nbf, at_to_bf, madness::WorldGopInterface::broadcast(), C, madness::copy(), madness::DistributedMatrix< T >::copy_from_replicated(), madness::BaseTensor::dim(), e(), madness::END_TIMER(), f1, madness::g, madness::Tensor< T >::gaxpy(), madness::AtomicBasisSet::get_aeps(), madness::AtomicBasisSet::get_avec(), madness::World::gop, madness::inner(), L, lo, MADNESS_ASSERT, matrix_exponential(), madness::matrix_inner(), max, molecule, mu, N, madness::Molecule::natom(), madness::print(), madness::Tensor< T >::ptr(), madness::RandomValue< double >(), madness::World::rank(), madness::Tensor< T >::scale(), madness::AtomicBasisSet::shells_to_bfn(), madness::BaseTensor::size(), madness::START_TIMER(), thresh, madness::Tensor< T >::trace(), and madness::transpose().
Referenced by solve().
localize_PM()
distmatT madness::SCF::localize_PM (World & world, const vecfuncT & mo, const std::vector< int > & set, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true, const bool doprint = false) const
compute the unitary localization matrix according to Pipek-Mezey
Parameters
[in] world the world
[in] mo the MOs
[in] set only orbitals within the same set will be mixed
[in] thresh the localization threshold
[in] thetamax ??
[in] randomize ??
References ao, at_nbf, at_to_bf, madness::distributed_localize_PM(), madness::END_TIMER(), PROFILE_MEMBER_FUNC, madness::START_TIMER(), and thresh.
Referenced by solve().
make_bsh_operators()
std::vector< poperatorT > madness::SCF::make_bsh_operators (World & world, const tensorT & evals) const
References madness::BSHOperatorPtr3D(), madness::BaseTensor::dim(), madness::CalculationParameters::lo(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, and madness::World::rank().
Referenced by compute_residual().
make_BSHOperatorPtr()
void madness::SCF::make_BSHOperatorPtr (World & world, tensorT & ak, tensorT & bk, std::vector< poperatorT > & aop, std::vector< poperatorT > & bop)
References madness::BSHOperatorPtr3D(), madness::CalculationParameters::lo(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), param, madness::print_meminfo(), madness::World::rank(), and madness::CalculationParameters::spin_restricted().
Referenced by polarizability().
make_coulomb_potential()
functionT madness::SCF::make_coulomb_potential (const functionT & rho) const inline
End functions for polarizability.
make the Coulomb potential given the total density
References madness::apply(), and coulop.
Referenced by madness::Coulomb::compute_potential().
make_density() [1/2]
functionT madness::SCF::make_density (World & world, const tensorT & occ, const vecfuncT & v) const
References madness::compress(), madness::Function< T, NDIM >::compress(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::gaxpy(), madness::World::gop, PROFILE_MEMBER_FUNC, and madness::square().
Referenced by madness::Coulomb::compute_density(), do_plots(), madness::MolecularEnergy::energy_and_gradient(), madness::MolecularEnergy::gradient(), iterate_trotter(), main(), make_density_ground(), propagate(), solve(), and madness::XCOperator::XCOperator().
make_density() [2/2]
functionT madness::SCF::make_density (World & world, const tensorT & occ, const cvecfuncT & v)
References madness::abssq(), madness::compress(), madness::Function< T, NDIM >::compress(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::gaxpy(), madness::World::gop, PROFILE_MEMBER_FUNC, madness::reconstruct(), and madness::Function< T, NDIM >::truncate().
make_density_ground()
functionT madness::SCF::make_density_ground (World & world, functionT & arho, functionT & brho)
References amo, aocc, bmo, bocc, make_density(), param, madness::print_meminfo(), madness::World::rank(), madness::CalculationParameters::spin_restricted(), and madness::Function< T, NDIM >::truncate().
Referenced by polarizability().
make_derivative_density()
functionT madness::SCF::make_derivative_density (World & world, const vecfuncT & mo, const tensorT & occ, const vecfuncT & x, const vecfuncT & y)
References madness::Function< T, NDIM >::compress(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::gaxpy(), and madness::World::gop.
Referenced by calc_dpolar(), and polarizability().
make_dft_energy()
double madness::SCF::make_dft_energy (World & world, const vecfuncT & vf, int ispin) inline
References madness::Function< T, NDIM >::trace(), and xc.
make_fock_matrix()
tensorT madness::SCF::make_fock_matrix (World & world, const vecfuncT & psi, const vecfuncT & Vpsi, const tensorT & occ, double & ekinetic) const
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::copy(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::FunctionDefaults< NDIM >::get_pmap(), madness::World::gop, k, kinetic_energy_matrix(), madness::LoadBalanceDeux< NDIM >::load_balance(), madness::CalculationParameters::loadbalparts(), madness::matrix_inner(), param, PROFILE_MEMBER_FUNC, psi(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::BaseTensor::size(), madness::World::size(), madness::START_TIMER(), and madness::transpose().
Referenced by solve().
make_gradbsh_operators()
std::vector< poperatorT > madness::SCF::make_gradbsh_operators (World & world, const tensorT & evals, const int axis) const
References axis, madness::BaseTensor::dim(), madness::GradBSHOperator(), madness::CalculationParameters::lo(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, and madness::World::rank().
make_lda_potential()
functionT madness::SCF::make_lda_potential (World & world, const functionT & arho)
apply the HF exchange on a set of orbitals
Parameters
[in] world the world
[in] occ occupation numbers
[in] psi the orbitals in the exchange operator
[in] f the orbitals |i> that the operator is applied on
Returns
a vector of orbitals K| i>
References madness::copy(), PROFILE_MEMBER_FUNC, madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::unaryop().
Referenced by initial_guess().
make_nuclear_potential()
void madness::SCF::make_nuclear_potential (World & world)
References madness::CalculationParameters::core_type(), madness::END_TIMER(), gthpseudopotential, molecule, param, potentialmanager, PROFILE_MEMBER_FUNC, madness::CalculationParameters::psp_calc(), madness::CalculationParameters::pure_ae(), and madness::START_TIMER().
Referenced by dnuclear_anchor_test(), main(), nuclear_anchor_test(), propagate(), and madness::MolecularEnergy::value().
matrix_exponential()
tensorT madness::SCF::matrix_exponential (const tensorT & A) const
References std::abs(), B, e(), madness::Tensor< T >::fillrandom(), I, madness::inner(), MADNESS_ASSERT, madness::Tensor< T >::normf(), PROFILE_MEMBER_FUNC, madness::scale(), and madness::Tensor< T >::scale().
Referenced by localize_boys(), and localize_new().
orthogonalize_response()
void madness::SCF::orthogonalize_response (World & world, vecfuncT & dmo, vecfuncT & mo)
References madness::reconstruct().
Referenced by polarizability().
orthonormalize() [1/2]
void madness::SCF::orthonormalize (World & world, vecfuncT & amo_new) const
orthonormalize the vectors
orthonormalize the vectors ignoring occupied/virtual distinctions
Parameters
[in] world the world
[in,out] amo_new the vectors to be orthonormalized
[in] world the world
[in,out] amo_new the vectors to be orthonormalized
References std::abs(), amo, madness::BaseTensor::dim(), madness::END_TIMER(), madness::matrix_inner(), max, madness::normalize(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::Q2(), madness::World::rank(), madness::START_TIMER(), madness::transform(), madness::truncate(), and vtol.
Referenced by restart_aos(), and update_subspace().
orthonormalize() [2/2]
void madness::SCF::orthonormalize (World & world, vecfuncT & amo_new, int nocc) const
orthonormalize the vectors (symmetric in occupied spaced, gramm-schmidt for virt to occ)
Parameters
[in] world the world
[in,out] amo_new the vectors to be orthonormalized
References std::abs(), madness::BaseTensor::dim(), madness::END_TIMER(), madness::matrix_inner(), max, madness::normalize(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::Q2(), madness::World::rank(), madness::Tensor< T >::screen(), madness::START_TIMER(), madness::transform(), madness::truncate(), and vtol.
polarizability()
void madness::SCF::polarizability (World & world)
Calculates the dynamic polarizability of the current system
This is the only external function for a polarizability calcualtion. The input parameters (such as frequency of perturbing radiation) are all input via the input file (which is parsed on creation of a calculation object, see SCF.h), but are listed here for completeness:
bool response; // response function calculation double response_freq; // Frequency for calculation response function std::vector<bool> response_axis; // Calculation protocol bool nonrotate; // If true do not molcule orient double rconv; // Response convergence double efield; // eps for finite field double efield_axis; // eps for finite field axis
References aeps, amo, aocc, madness::apply(), apply_potential_response(), axis, beps, bmo, bocc, calc_dipole_mo(), calc_djkmo(), calc_dpolar(), calc_freq(), calc_response_function(), calc_rhs(), coulop, madness::END_TIMER(), madness::QCCalculationParametersBase::get(), gthpseudopotential, make_BSHOperatorPtr(), make_density_ground(), make_derivative_density(), max, madness::CalculationParameters::maxiter(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), madness::norm2(), omega, orthogonalize_response(), p(), param, potentialmanager, madness::print(), madness::print_meminfo(), madness::CalculationParameters::psp_calc(), madness::CalculationParameters::pure_ae(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), residual(), residual_response(), madness::CalculationParameters::response_axis(), madness::CalculationParameters::response_freq(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), subspace, this_axis(), thresh, madness::truncate(), madness::Function< T, NDIM >::truncate(), update_response_subspace(), vnuc(), and madness::wall_time().
Referenced by main().
project()
void madness::SCF::project (World & world)
References amo, bmo, madness::WorldGopInterface::fence(), madness::World::gop, madness::CalculationParameters::nbeta(), madness::normalize(), param, PROFILE_MEMBER_FUNC, madness::project(), madness::reconstruct(), madness::CalculationParameters::spin_restricted(), and madness::truncate().
Referenced by madness::MolecularEnergy::value().
project_ao_basis()
vecfuncT madness::SCF::project_ao_basis (World & world, const AtomicBasisSet & aobasis)
References aobasis, at_nbf, at_to_bf, madness::AtomicBasisSet::atoms_to_bfn(), molecule, PROFILE_MEMBER_FUNC, and project_ao_basis_only().
Referenced by madness::MolecularEnergy::value().
project_ao_basis_only()
vecfuncT madness::SCF::project_ao_basis_only (World & world, const AtomicBasisSet & aobasis, const Molecule & molecule) static
References ao, aobasis, madness::WorldGopInterface::fence(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::World::gop, molecule, madness::AtomicBasisSet::nbf(), madness::normalize(), and madness::truncate().
Referenced by madness::Znemo::hcore_guess(), project_ao_basis(), madness::MolecularOrbitals< T, NDIM >::read_restartaodata(), madness::MolecularOrbitals< T, NDIM >::save_restartaodata(), and test_read_restartaodata().
propagate()
void madness::SCF::propagate (World & world, double omega, int step0)
References amo, aocc, bmo, c, madness::copy(), e(), initial_load_bal(), madness::inner(), iterate_trotter(), madness::CalculationParameters::L(), load_mos(), make_density(), make_nuclear_potential(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), param, madness::constants::pi, PROFILE_MEMBER_FUNC, madness::qm_1d_free_particle_propagator(), madness::CalculationParameters::spin_restricted(), and thresh.
Referenced by main().
reset_aobasis()
void madness::SCF::reset_aobasis (const std::string & aobasisname) inline
References aobasis, and madness::AtomicBasisSet::read_file().
Referenced by SCF(), and madness::MolecularEnergy::value().
residual_response()
double madness::SCF::residual_response (World & world, const vecfuncT & x, const vecfuncT & y, const vecfuncT & x_old, const vecfuncT & y_old, vecfuncT & rx, vecfuncT & ry)
References max, madness::norm2s(), madness::print_meminfo(), madness::World::rank(), residual(), madness::sub(), and vector_stats().
Referenced by polarizability().
restart_aos()
bool madness::SCF::restart_aos (World & world)
References aeps, amo, ao, aocc, aset, beps, bmo, bocc, madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::broadcast_serializable(), bset, c, madness::BaseTensor::dim(), fred(), madness::gesvp(), madness::World::gop, madness::matrix_inner(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), madness::CalculationParameters::nmo_alpha(), madness::CalculationParameters::nmo_beta(), orthonormalize(), param, madness::print(), madness::World::rank(), madness::CalculationParameters::spin_restricted(), madness::transform(), madness::truncate(), and vtol.
Referenced by madness::MolecularEnergy::value().
rotate_subspace() [1/2]
void madness::SCF::rotate_subspace (World & world, const tensorT & U, subspaceT & subspace, int lo, int nfunc, double trantol) const
References madness::WorldGopInterface::fence(), madness::World::gop, lo, PROFILE_MEMBER_FUNC, subspace, and madness::transform().
rotate_subspace() [2/2]
void madness::SCF::rotate_subspace (World & world, const distmatT & U, subspaceT & subspace, int lo, int nfunc, double trantol) const
References madness::WorldGopInterface::fence(), madness::World::gop, lo, PROFILE_MEMBER_FUNC, subspace, and madness::transform().
save_mos()
void madness::SCF::save_mos (World & world)
References aeps, amo, ao, aocc, aset, beps, bmo, bocc, bset, current_energy, madness::QCCalculationParametersBase::get(), madness::matrix_inner(), param, PROFILE_MEMBER_FUNC, madness::World::rank(), and madness::CalculationParameters::spin_restricted().
Referenced by madness::MolecularEnergy::value().
set_protocol()
template<std::size_t NDIM> void madness::SCF::set_protocol (World & world, double thresh) inline
References madness::CoulombOperatorPtr(), coulop, madness::CalculationParameters::dconv(), madness::CalculationParameters::deriv(), e(), madness::f, madness::FunctionDefaults< NDIM >::get_thresh(), gradop, k, madness::CalculationParameters::k(), madness::CalculationParameters::L(), madness::CalculationParameters::lo(), mask, madness::mask3(), max, NDIM, param, madness::print(), madness::CalculationParameters::print_level(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), thresh, and vtol.
Referenced by main(), and madness::MolecularEnergy::value().
solve()
void madness::SCF::solve (World & world)
References aeps, amo, analyze_vectors(), aocc, madness::apply(), apply_potential(), aset, beps, bmo, bocc, bset, madness::Function< T, NDIM >::clear(), madness::PCM::compute_pcm_energy(), madness::PCM::compute_pcm_potential(), coulop, current_energy, madness::DistributedMatrix< T >::data(), madness::CalculationParameters::dconv(), diag_fock_matrix(), dipole(), dipole_matrix_elements(), madness::CalculationParameters::do_localize(), e(), madness::END_TIMER(), madness::f, madness::QCCalculationParametersBase::get(), gthpseudopotential, madness::inner(), loadbal(), localize_boys(), madness::CalculationParameters::localize_method(), localize_new(), madness::CalculationParameters::localize_pm(), localize_PM(), make_density(), make_fock_matrix(), madness::matrix_inner(), max, madness::CalculationParameters::maxiter(), molecule, madness::Molecule::natom(), madness::CalculationParameters::nbeta(), madness::norm2(), madness::normalize(), madness::Molecule::nuclear_repulsion_energy(), param, pcm, madness::CalculationParameters::pcm_data(), potentialmanager, madness::print(), madness::CalculationParameters::print_level(), madness::print_meminfo(), PROFILE_MEMBER_FUNC, madness::CalculationParameters::psp_calc(), madness::CalculationParameters::pure_ae(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Tensor< T >::screen(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), subspace, madness::sygvp(), madness::transform(), madness::truncate(), madness::Function< T, NDIM >::truncate(), update_subspace(), vnuc(), vtol, and madness::wall_time().
Referenced by madness::MolecularEnergy::value().
this_axis()
void madness::SCF::this_axis (World & world, const int axis)
References axis, madness::print(), and madness::World::rank().
Referenced by polarizability().
twoint()
Tensor< double > madness::SCF::twoint (World & world, const vecfuncT & psi) const
Compute the two-electron integrals over the provided set of orbitals.
Returned is a replicated tensor of with and . The symmetry is enforced.
Important this is consistent with Coulomb
References madness::apply(), coulop, madness::WorldGopInterface::fence(), madness::World::gop, madness::matrix_inner(), madness::mul_sparse(), madness::norm_tree(), PROFILE_MEMBER_FUNC, psi(), madness::reconstruct(), and madness::truncate().
update_response_subspace()
void madness::SCF::update_response_subspace (World & world, vecfuncT & ax, vecfuncT & ay, vecfuncT & bx, vecfuncT & by, vecfuncT & rax, vecfuncT & ray, vecfuncT & rbx, vecfuncT & rby, subspaceT & subspace, tensorT & Q, double & update_residual)
Begin functions for polarizability.
References madness::_(), std::abs(), madness::WorldGopInterface::broadcast_serializable(), c, madness::compress(), e(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, madness::KAIN(), m, max, madness::CalculationParameters::maxrotn(), madness::CalculationParameters::maxsub(), madness::CalculationParameters::nbeta(), madness::norm2s(), param, madness::print(), madness::CalculationParameters::print_level(), madness::Tensor< T >::ptr(), madness::World::rank(), madness::World::size(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), madness::sub(), subspace, madness::WorldGopInterface::sum(), madness::truncate(), and vector_stats().
Referenced by polarizability().
update_subspace()
void madness::SCF::update_subspace (World & world, vecfuncT & Vpsia, vecfuncT & Vpsib, tensorT & focka, tensorT & fockb, subspaceT & subspace, tensorT & Q, double & bsh_residual, double & update_residual)
References madness::_(), amo, aocc, bmo, bocc, madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::broadcast_serializable(), c, madness::compress(), compute_residual(), do_step_restriction(), e(), madness::END_TIMER(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, madness::KAIN(), m, max, madness::CalculationParameters::maxsub(), madness::CalculationParameters::nalpha(), madness::CalculationParameters::nbeta(), madness::CalculationParameters::nmo_alpha(), madness::CalculationParameters::nmo_beta(), orthonormalize(), param, madness::print(), madness::CalculationParameters::print_level(), PROFILE_MEMBER_FUNC, madness::Tensor< T >::ptr(), madness::World::rank(), madness::CalculationParameters::spin_restricted(), madness::START_TIMER(), subspace, and madness::WorldGopInterface::sum().
Referenced by solve().
vector_stats()
void madness::SCF::vector_stats (const std::vector< double > & v, double & rms, double & maxabsval) const
References std::abs(), and PROFILE_MEMBER_FUNC.
Referenced by compute_residual(), do_step_restriction(), residual_response(), and update_response_subspace().
Member Data Documentation
aeps
tensorT madness::SCF::aeps
orbital energies for alpha and beta orbitals
Referenced by calc_freq(), compare_calc_and_mos(), initial_guess(), load_mos(), localize_new(), polarizability(), restart_aos(), save_mos(), and solve().
amo
vecfuncT madness::SCF::amo
alpha and beta molecular orbitals
Referenced by apply_potential(), apply_potential_response(), calc_dpolar(), compare_calc_and_mos(), derivatives(), do_plots(), madness::MolecularEnergy::energy_and_gradient(), madness::Exchange< double, 3 >::Exchange(), get_amo(), madness::MolecularEnergy::gradient(), initial_guess(), iterate_trotter(), load_mos(), loadbal(), main(), make_density_ground(), orthonormalize(), polarizability(), project(), propagate(), restart_aos(), save_mos(), solve(), update_subspace(), madness::MolecularEnergy::value(), and madness::XCOperator::XCOperator().
ao
vecfuncT madness::SCF::ao
MRA projection of the minimal basis set.
Referenced by analyze_vectors(), initial_guess(), localize_new(), localize_PM(), project_ao_basis_only(), restart_aos(), save_mos(), and madness::MolecularEnergy::value().
aobasis
AtomicBasisSet madness::SCF::aobasis
Referenced by analyze_vectors(), initial_guess(), localize_new(), project_ao_basis(), project_ao_basis_only(), reset_aobasis(), SCF(), and madness::MolecularEnergy::value().
aocc
tensorT madness::SCF::aocc
occupation numbers for alpha and beta orbitals
Referenced by calc_dpolar(), compare_calc_and_mos(), derivatives(), do_plots(), madness::MolecularEnergy::energy_and_gradient(), madness::Exchange< double, 3 >::Exchange(), get_aocc(), madness::MolecularEnergy::gradient(), initial_guess(), iterate_trotter(), load_mos(), main(), make_density_ground(), polarizability(), propagate(), restart_aos(), save_mos(), solve(), update_subspace(), madness::MolecularEnergy::value(), and madness::XCOperator::XCOperator().
aset
std::vector<int> madness::SCF::aset
sets of orbitals grouped by their orbital energies (for localization?) only orbitals within the same set will be mixed to localize
Referenced by compare_calc_and_mos(), initial_guess(), load_mos(), restart_aos(), save_mos(), and solve().
at_nbf
std::vector<int> madness::SCF::at_nbf
Referenced by localize_new(), localize_PM(), and project_ao_basis().
at_to_bf
std::vector<int> madness::SCF::at_to_bf
Referenced by localize_new(), localize_PM(), and project_ao_basis().
beps
tensorT madness::SCF::beps
Referenced by calc_freq(), initial_guess(), load_mos(), polarizability(), restart_aos(), save_mos(), and solve().
bmo
vecfuncT madness::SCF::bmo
Referenced by apply_potential_response(), calc_dpolar(), derivatives(), do_plots(), madness::MolecularEnergy::energy_and_gradient(), madness::Exchange< double, 3 >::Exchange(), get_bmo(), madness::MolecularEnergy::gradient(), initial_guess(), iterate_trotter(), load_mos(), loadbal(), main(), make_density_ground(), polarizability(), project(), propagate(), restart_aos(), save_mos(), solve(), update_subspace(), madness::MolecularEnergy::value(), and madness::XCOperator::XCOperator().
bocc
tensorT madness::SCF::bocc
Referenced by calc_dpolar(), derivatives(), do_plots(), madness::MolecularEnergy::energy_and_gradient(), madness::Exchange< double, 3 >::Exchange(), get_bocc(), madness::MolecularEnergy::gradient(), initial_guess(), iterate_trotter(), load_mos(), main(), make_density_ground(), polarizability(), restart_aos(), save_mos(), solve(), update_subspace(), madness::MolecularEnergy::value(), and madness::XCOperator::XCOperator().
bset
std::vector<int> madness::SCF::bset
Referenced by initial_guess(), load_mos(), restart_aos(), save_mos(), and solve().
coulop
poperatorT madness::SCF::coulop
Referenced by calc_exchange_function(), calc_xc_function(), do_plots(), initial_guess(), iterate_trotter(), make_coulomb_potential(), polarizability(), set_protocol(), solve(), and twoint().
current_energy
double madness::SCF::current_energy
Referenced by madness::MolecularEnergy::energy_and_gradient(), load_mos(), save_mos(), solve(), and madness::MolecularEnergy::value().
gradop
std::vector< std::shared_ptr<real_derivative_3d> > madness::SCF::gradop
Referenced by kinetic_energy_matrix(), and set_protocol().
gthpseudopotential
std::shared_ptr<GTHPseudopotential <double> > madness::SCF::gthpseudopotential
Referenced by apply_potential(), initial_guess(), initial_load_bal(), loadbal(), make_nuclear_potential(), polarizability(), and solve().
mask
functionT madness::SCF::mask
Referenced by set_protocol().
molecule
Molecule madness::SCF::molecule
Referenced by analyze_vectors(), core_projection(), core_projector_derivative(), derivatives(), dipole(), madness::DNuclear::DNuclear(), initial_guess(), load_mos(), localize_new(), main(), make_nuclear_potential(), madness::Nuclear::Nuclear(), project_ao_basis(), project_ao_basis_only(), SCF(), solve(), and madness::MolecularEnergy::value().
param
CalculationParameters madness::SCF::param
Referenced by analyze_vectors(), apply_potential(), apply_potential_response(), calc_dpolar(), calc_freq(), compute_residual(), core_projection(), derivatives(), diag_fock_matrix(), dipole(), do_plots(), do_step_restriction(), madness::MolecularEnergy::energy_and_gradient(), madness::Exchange< double, 3 >::Exchange(), madness::MolecularEnergy::gradient(), group_orbital_sets(), initial_guess(), initial_load_bal(), is_spin_restricted(), iterate_trotter(), load_mos(), loadbal(), main(), make_bsh_operators(), make_BSHOperatorPtr(), make_density_ground(), make_fock_matrix(), make_gradbsh_operators(), make_nuclear_potential(), orthonormalize(), polarizability(), project(), propagate(), restart_aos(), save_mos(), SCF(), set_protocol(), solve(), update_response_subspace(), update_subspace(), madness::MolecularEnergy::value(), and madness::XCOperator::XCOperator().
pcm
PCM madness::SCF::pcm
Referenced by solve(), and madness::MolecularEnergy::value().
potentialmanager
std::shared_ptr<PotentialManager> madness::SCF::potentialmanager
Referenced by apply_potential(), apply_potential_response(), apply_V(), derivatives(), madness::DNuclear::DNuclear(), do_plots(), initial_guess(), initial_load_bal(), iterate_trotter(), loadbal(), make_nuclear_potential(), madness::Nuclear::Nuclear(), polarizability(), and solve().
vtol
double madness::SCF::vtol
Referenced by analyze_vectors(), apply_potential(), apply_potential_response(), calc_xc_function(), compute_residual(), diag_fock_matrix(), dipole_matrix_elements(), initial_guess(), iterate_trotter(), localize_boys(), orthonormalize(), restart_aos(), set_protocol(), and solve().
xc
XCfunctional madness::SCF::xc
Referenced by apply_potential(), apply_potential_response(), calc_djkmo(), calc_xc_function(), make_dft_energy(), and SCF().
The documentation for this class was generated from the following files:
SCF.h
SCF.cc