MADNESS: madness::HartreeFockNuclearPotentialOp< T, NDIM > Class Template Reference
madness::HartreeFockNuclearPotentialOp< T, NDIM > Class Template Reference
#include <hartreefock.h>
Public Types
typedef Function< T, NDIM > funcT
Public Member Functions
HartreeFockNuclearPotentialOp (World &world, funcT V, double coeff, double thresh)
virtual bool is_od ()
Is there an orbitally-dependent term?
virtual bool is_rd ()
Is there a density-dependent term?
virtual funcT op_r (const funcT &rho, const funcT &rhon, const funcT &psi)
Public Member Functions inherited from madness::EigSolverOp< T, NDIM >
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
double coeff ()
std::string messsageME ()
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
Private Attributes
funcT _V
Additional Inherited Members
Public Attributes inherited from madness::EigSolverOp< T, NDIM >
World & _world
Protected Member Functions inherited from madness::EigSolverOp< T, NDIM >
void messageME (std::string messageME)
double thresh ()
Member Typedef Documentation
funcT
template<typename T , int NDIM> typedef Function<T,NDIM> madness::HartreeFockNuclearPotentialOp< T, NDIM >::funcT
Constructor & Destructor Documentation
HartreeFockNuclearPotentialOp()
template<typename T , int NDIM> madness::HartreeFockNuclearPotentialOp< T, NDIM >::HartreeFockNuclearPotentialOp (World & world, funcT V, double coeff, double thresh)
References madness::HartreeFockNuclearPotentialOp< T, NDIM >::_V, madness::EigSolverOp< T, NDIM >::messageME(), and V().
Member Function Documentation
is_od()
template<typename T , int NDIM> virtual bool madness::HartreeFockNuclearPotentialOp< T, NDIM >::is_od () inline virtual
Is there an orbitally-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
is_rd()
template<typename T , int NDIM> virtual bool madness::HartreeFockNuclearPotentialOp< T, NDIM >::is_rd () inline virtual
Is there a density-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
op_r()
template<typename T , int NDIM> Function< T, NDIM > madness::HartreeFockNuclearPotentialOp< T, NDIM >::op_r (const funcT & rho, const funcT & rhon, const funcT & psi) virtual
References psi().
Member Data Documentation
_V
template<typename T , int NDIM> funcT madness::HartreeFockNuclearPotentialOp< T, NDIM >::_V private
Referenced by madness::HartreeFockNuclearPotentialOp< T, NDIM >::HartreeFockNuclearPotentialOp().
The documentation for this class was generated from the following files:
hartreefock.h
hartreefock.cc