MADNESS: Gaussian< T, NDIM > Class Template Reference
Gaussian< T, NDIM > Class Template Reference
Public Types
typedef Vector< double, NDIM > coordT
typedef Vector< double, NDIM > coordT
typedef Vector< double, NDIM > coordT
typedef Vector< double, NDIM > coordT
typedef Vector< double, NDIM > coordT
typedef Vector< double, NDIM > coordT
Public Types inherited from madness::FunctionFunctorInterface< T, NDIM >
typedef GenTensor< T > coeffT
typedef Key< NDIM > keyT
typedef T value_type
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Member Functions
Gaussian (const coordT &center, double exponent, T coefficient)
Gaussian (const coordT &center, double exponent, T coefficient)
Gaussian (const coordT &center, double exponent, T coefficient)
Gaussian (const coordT &center, double exponent, T coefficient)
Gaussian (const coordT &center, double exponent, T coefficient)
Gaussian (const coordT &center, double exponent, T coefficient)
Gaussian (const coord_3d &center, double exponent, double coefficient)
T operator() (const coordT &x) const
You should implement this to return f(x)
T operator() (const coordT &x) const
You should implement this to return f(x)
T operator() (const coordT &x) const
You should implement this to return f(x)
T operator() (const coordT &x) const
You should implement this to return f(x)
T operator() (const coordT &x) const
You should implement this to return f(x)
T operator() (const coordT &x) const
You should implement this to return f(x)
double operator() (const coord_3d &x) const
std::vector< coordT > special_points () const
Override this to return list of special points to be refined more deeply.
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< T, NDIM >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, T *fvals, int npts) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Public Attributes
const coordT center
const coord_3d center
const T coefficient
const double coefficient
const double exponent
std::vector< coord_3d > specialpt
Public Attributes inherited from madness::FunctionFunctorInterface< T, NDIM >
Level special_level_
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Member Typedef Documentation
coordT [1/6]
template<typename T, std::size_t NDIM> typedef Vector<double,NDIM> Gaussian< T, NDIM >::coordT
coordT [2/6]
template<typename T, std::size_t NDIM> typedef Vector<double,NDIM> Gaussian< T, NDIM >::coordT
coordT [3/6]
template<typename T, std::size_t NDIM> typedef Vector<double,NDIM> Gaussian< T, NDIM >::coordT
coordT [4/6]
template<typename T, std::size_t NDIM> typedef Vector<double,NDIM> Gaussian< T, NDIM >::coordT
coordT [5/6]
template<typename T, std::size_t NDIM> typedef Vector<double,NDIM> Gaussian< T, NDIM >::coordT
coordT [6/6]
template<typename T, std::size_t NDIM> typedef Vector<double,NDIM> Gaussian< T, NDIM >::coordT
Constructor & Destructor Documentation
Gaussian() [1/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coord_3d & center, double exponent, double coefficient) inline
Gaussian() [2/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coordT & center, double exponent, T coefficient) inline
Gaussian() [3/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coordT & center, double exponent, T coefficient) inline
Gaussian() [4/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coordT & center, double exponent, T coefficient) inline
Gaussian() [5/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coordT & center, double exponent, T coefficient) inline
Gaussian() [6/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coordT & center, double exponent, T coefficient) inline
Gaussian() [7/7]
template<typename T, std::size_t NDIM> Gaussian< T, NDIM >::Gaussian (const coordT & center, double exponent, T coefficient) inline
Member Function Documentation
operator()() [1/7]
template<typename T, std::size_t NDIM> T Gaussian< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References NDIM, and madness::sum().
operator()() [2/7]
template<typename T, std::size_t NDIM> T Gaussian< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References NDIM, and madness::sum().
operator()() [3/7]
template<typename T, std::size_t NDIM> T Gaussian< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References NDIM, and madness::sum().
operator()() [4/7]
template<typename T, std::size_t NDIM> T Gaussian< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References NDIM, and madness::sum().
operator()() [5/7]
template<typename T, std::size_t NDIM> T Gaussian< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References NDIM, and madness::sum().
operator()() [6/7]
template<typename T, std::size_t NDIM> T Gaussian< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References NDIM, and madness::sum().
operator()() [7/7]
template<typename T, std::size_t NDIM> double Gaussian< T, NDIM >::operator() (const coord_3d & x) const inline
References madness::sum().
special_points() [1/2]
template<typename T, std::size_t NDIM> std::vector<coordT> Gaussian< T, NDIM >::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< T, NDIM >.
special_points() [2/2]
template<typename T, std::size_t NDIM> std::vector<coord_3d> Gaussian< T, NDIM >::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< T, NDIM >.
Member Data Documentation
center [1/2]
template<typename T, std::size_t NDIM> const coordT Gaussian< T, NDIM >::center
center [2/2]
template<typename T, std::size_t NDIM> const coordT Gaussian< T, NDIM >::center
coefficient [1/2]
template<typename T, std::size_t NDIM> const T Gaussian< T, NDIM >::coefficient
coefficient [2/2]
template<typename T, std::size_t NDIM> const T Gaussian< T, NDIM >::coefficient
exponent
template<typename T, std::size_t NDIM> const double Gaussian< T, NDIM >::exponent
specialpt
template<typename T, std::size_t NDIM> std::vector<coord_3d> Gaussian< T, NDIM >::specialpt
The documentation for this class was generated from the following files:
dataloadbal.cc
testbsh.cc
testopdir.cc
testproj.cc
testsuite.cc
testunaryop.cc
testvmra.cc