MADNESS: madness::Spinlock Class Reference
madness::Spinlock Class Reference
Spinlock using pthread spinlock operations.
#include <worldmutex.h>
Public Member Functions
Spinlock (int junk=0)
Make and initialize a spinlock ... initial state is unlocked.
virtual ~Spinlock ()
void lock () const
Acquire the spinlock waiting if necessary.
bool try_lock () const
Try to acquire the spinlock ... return true on success, false on failure.
void unlock () const
Free a spinlock owned by this thread.
Private Member Functions
Spinlock (const Spinlock &)
Copy constructor is forbidden.
void operator= (const Spinlock &)
Assignment is forbidden.
Private Attributes
pthread_spinlock_t spinlock
Detailed Description
Spinlock using pthread spinlock operations.
Constructor & Destructor Documentation
Spinlock() [1/2]
madness::Spinlock::Spinlock (const Spinlock &) private
Copy constructor is forbidden.
Spinlock() [2/2]
madness::Spinlock::Spinlock (int junk = 0) inline
Make and initialize a spinlock ... initial state is unlocked.
References spinlock.
~Spinlock()
virtual madness::Spinlock::~Spinlock () inline virtual
References spinlock.
Member Function Documentation
lock()
void madness::Spinlock::lock () const inline
Acquire the spinlock waiting if necessary.
References MADNESS_EXCEPTION, madness::detail::print_mutex_error(), and spinlock.
Referenced by madness::Hash_private::bin< keyT, valueT >::clear(), madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::find(), madness::Hash_private::bin< keyT, valueT >::insert(), madness::MutexFair::lock(), madness::WorldObject< TestFutureForwarding >::process_pending(), madness::MutexFair::try_lock(), madness::MutexFair::unlock(), and madness::ConditionVariable::wait().
operator=()
void madness::Spinlock::operator= (const Spinlock &) private
Assignment is forbidden.
try_lock()
bool madness::Spinlock::try_lock () const inline
Try to acquire the spinlock ... return true on success, false on failure.
References spinlock.
Referenced by madness::MutexReaderWriter::lock().
unlock()
void madness::Spinlock::unlock () const inline
Free a spinlock owned by this thread.
References MADNESS_EXCEPTION, madness::detail::print_mutex_error(), and spinlock.
Referenced by madness::Hash_private::bin< keyT, valueT >::clear(), madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::find(), madness::Hash_private::bin< keyT, valueT >::insert(), madness::MutexFair::lock(), madness::WorldObject< TestFutureForwarding >::process_pending(), madness::MutexFair::try_lock(), madness::MutexFair::unlock(), and madness::ConditionVariable::wait().
Member Data Documentation
spinlock
pthread_spinlock_t madness::Spinlock::spinlock mutable private
Referenced by lock(), Spinlock(), try_lock(), unlock(), and ~Spinlock().
The documentation for this class was generated from the following file:
worldmutex.h