MADNESS: MolecularMaskBase Class Reference
MolecularMaskBase Class Reference
#include <molecularmask.h>
Public Member Functions
MolecularMaskBase (double sigma, const std::vector< double > atomic_radii, const std::vector< madness::coord_3d > atomic_coords)
std::vector< madness::Vector< double, 3 > > special_points () const
Protected Member Functions
double atomic_cmask (const madness::coord_3d &r, unsigned int i) const
double atomic_mask (const madness::coord_3d &r, unsigned int i) const
double cmask (double s) const
double dmask (double s) const
madness::coord_3d grad_atomic_mask (const madness::coord_3d &r, unsigned int i) const
madness::coord_3d grad_sdf (const madness::coord_3d &r, const madness::coord_3d &center) const
madness::coord_3d gradient (const madness::coord_3d &r) const
double mask (double s) const
double sdf (const madness::coord_3d &r, const madness::coord_3d &center, double R) const
Protected Attributes
const std::vector< madness::coord_3d > atomic_coords
const std::vector< double > atomic_radii
const int natom
const double sigma
Constructor & Destructor Documentation
MolecularMaskBase()
MolecularMaskBase::MolecularMaskBase (double sigma, const std::vector< double > atomic_radii, const std::vector< madness::coord_3d > atomic_coords) inline
References atomic_coords, atomic_radii, and MADNESS_ASSERT.
Member Function Documentation
atomic_cmask()
double MolecularMaskBase::atomic_cmask (const madness::coord_3d & r, unsigned int i) const inline protected
References atomic_coords, atomic_radii, cmask(), sdf(), and sigma.
Referenced by gradient(), MolecularVolumeMask::operator()(), and MolecularVolumeComplementMask::operator()().
atomic_mask()
double MolecularMaskBase::atomic_mask (const madness::coord_3d & r, unsigned int i) const inline protected
References atomic_coords, atomic_radii, mask(), sdf(), and sigma.
cmask()
double MolecularMaskBase::cmask (double s) const inline protected
References mask().
Referenced by atomic_cmask().
dmask()
double MolecularMaskBase::dmask (double s) const inline protected
References madness::constants::pi.
Referenced by grad_atomic_mask().
grad_atomic_mask()
madness::coord_3d MolecularMaskBase::grad_atomic_mask (const madness::coord_3d & r, unsigned int i) const inline protected
References atomic_coords, atomic_radii, dmask(), grad_sdf(), sdf(), and sigma.
Referenced by gradient().
grad_sdf()
madness::coord_3d MolecularMaskBase::grad_sdf (const madness::coord_3d & r, const madness::coord_3d & center) const inline protected
References distance().
Referenced by grad_atomic_mask().
gradient()
madness::coord_3d MolecularMaskBase::gradient (const madness::coord_3d & r) const inline protected
References atomic_cmask(), e(), madness::grad(), grad_atomic_mask(), m, and natom.
Referenced by MolecularSurface::operator()(), and MolecularVolumeMaskGrad::operator()().
mask()
double MolecularMaskBase::mask (double s) const inline protected
Referenced by atomic_mask(), and cmask().
sdf()
double MolecularMaskBase::sdf (const madness::coord_3d & r, const madness::coord_3d & center, double R) const inline protected
References distance(), and R.
Referenced by atomic_cmask(), atomic_mask(), and grad_atomic_mask().
special_points()
std::vector< madness::Vector<double,3> > MolecularMaskBase::special_points () const inline
References atomic_coords, atomic_radii, natom, p(), and madness::constants::pi.
Referenced by MolecularVolumeMask::special_points(), MolecularVolumeComplementMask::special_points(), MolecularSurface::special_points(), and MolecularVolumeMaskGrad::special_points().
Member Data Documentation
atomic_coords
const std::vector<madness::coord_3d> MolecularMaskBase::atomic_coords protected
Referenced by atomic_cmask(), atomic_mask(), grad_atomic_mask(), MolecularMaskBase(), and special_points().
atomic_radii
const std::vector<double> MolecularMaskBase::atomic_radii protected
Referenced by atomic_cmask(), atomic_mask(), grad_atomic_mask(), MolecularMaskBase(), and special_points().
natom
const int MolecularMaskBase::natom protected
Referenced by gradient(), MolecularVolumeMask::operator()(), MolecularVolumeComplementMask::operator()(), and special_points().
sigma
const double MolecularMaskBase::sigma protected
Referenced by atomic_cmask(), atomic_mask(), and grad_atomic_mask().
The documentation for this class was generated from the following file:
molecularmask.h