MADNESS: madness::LowRankTensor< T > Class Template Reference
madness::LowRankTensor< T > Class Template Reference
#include <lowranktensor.h>
Classes
struct implT
Public Types
typedef TensorTypeData< T >::float_scalar_type float_scalar_type
C++ typename of the floating point type associated with scalar real type.
typedef TensorTypeData< T >::scalar_type scalar_type
C++ typename of the real type associated with a complex type.
Public Member Functions
LowRankTensor ()
empty ctor
LowRankTensor (const LowRankTensor< T > &other)
copy ctor, shallow
LowRankTensor (const std::vector< long > &dim, const TensorType &tt)
ctor with dimensions; constructs tensor filled with zeros
LowRankTensor (const std::vector< long > &dim, const TensorArgs &targs)
ctor with dimensions; constructs tensor filled with zeros
LowRankTensor (const TensorType &tt, const long k, const long ndim)
ctor with dimensions; all dims have the same value k
LowRankTensor (const Tensor< T > &rhs, const double &thresh, const TensorType &tt)
ctor with a regular Tensor and arguments, deep
LowRankTensor (const Tensor< T > &rhs, const TensorArgs &targs)
ctor with a regular Tensor and arguments, deep
LowRankTensor (const Tensor< T > &other)
ctor with a regular Tensor, deep
LowRankTensor (const TensorTrain< T > &tt)
ctor with a TensorTrain as argument, shallow
LowRankTensor (const SVDTensor< T > &t)
ctor with a SVDTensor as argument, shallow
LowRankTensor (const SliceLowRankTensor< T > &other)
ctor with a SliceLowRankTensor as argument, deep
void add_SVD (const LowRankTensor &other, const double &thresh)
SRConf< T > & config ()
LowRankTensor convert (const TensorArgs &targs) const
convert this to a new LowRankTensor of given tensor type
long dim (const int i) const
return the number of entries in dimension i
LowRankTensor< T > & emul (const LowRankTensor< T > &other)
Inplace multiply by corresponding elements of argument Tensor.
const Tensor< T > & full_tensor () const
Tensor< T > & full_tensor ()
Tensor< T > full_tensor_copy () const
LowRankTensor & gaxpy (const T alpha, const LowRankTensor &other, const T beta)
template<typename Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q)> general_transform (const Tensor< Q > c[]) const
Transform all dimensions of the tensor t by distinct matrices c.
bool has_data () const
bool has_no_data () const
void method1 ()
long ndim () const
void normalize ()
float_scalar_type normf () const
template<class Q >
operator LowRankTensor< Q > () const
Type conversion makes a deep copy.
SliceLowRankTensor< T > operator() (const std::vector< Slice > &s)
general slicing, shallow; for temporary use only!
const SliceLowRankTensor< T > operator() (const std::vector< Slice > &s) const
general slicing, shallow; for temporary use only!
template<typename Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q)> operator* (const Q &x) const
multiply with a number
LowRankTensor & operator+= (const LowRankTensor &other)
LowRankTensor & operator-= (const LowRankTensor &other)
LowRankTensor & operator= (const LowRankTensor< T > &other)
shallow assignment operator
LowRankTensor & operator= (const SliceLowRankTensor< T > &other)
deep assignment with slices: g0 = g1(s)
LowRankTensor & operator= (const T &number)
assign a number to this tensor
T * ptr (const int ivec=0)
Returns a pointer to the internal data.
const T * ptr (const int ivec=0) const
Returns a pointer to the internal data.
long rank () const
long real_size () const
Tensor< T > reconstruct_tensor () const
reconstruct this to return a full tensor
void reduce_rank (const double &thresh)
template<typename Q >
IsSupported< TensorTypeData< Q >, LowRankTensor< T > & >::type scale (Q fac)
Inplace multiplication by scalar of supported type (legacy name)
long size () const
float_scalar_type svd_normf () const
template<typename Q >
TENSOR_RESULT_TYPE (T, Q) trace_conj(const LowRankTensor< Q > &rhs) const
returns the trace of <this|rhs>
TensorType tensor_type () const
return the tensor type
template<typename Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q) > transform (const Tensor< Q > &c) const
Transform all dimensions of the tensor t by the matrix c.
template<typename Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q)> transform_dir (const Tensor< Q > &c, int axis) const
Transforms one dimension of the tensor t by the matrix c, returns new contiguous tensor.
Static Public Member Functions
static double fac_reduce ()
static double facReduce ()
Public Attributes
implT impl
TensorType type
Friends
LowRankTensor copy (const LowRankTensor &other)
deep copy
Member Typedef Documentation
float_scalar_type
template<typename T> typedef TensorTypeData<T>::float_scalar_type madness::LowRankTensor< T >::float_scalar_type
C++ typename of the floating point type associated with scalar real type.
scalar_type
template<typename T> typedef TensorTypeData<T>::scalar_type madness::LowRankTensor< T >::scalar_type
C++ typename of the real type associated with a complex type.
Constructor & Destructor Documentation
LowRankTensor() [1/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor () inline
empty ctor
Referenced by madness::LowRankTensor< T >::convert(), madness::LowRankTensor< T >::general_transform(), madness::LowRankTensor< T >::transform(), and madness::LowRankTensor< T >::transform_dir().
LowRankTensor() [2/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const LowRankTensor< T > & other) inline
copy ctor, shallow
LowRankTensor() [3/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const std::vector< long > & dim, const TensorType & tt) inline
ctor with dimensions; constructs tensor filled with zeros
References madness::LowRankTensor< T >::dim(), madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
LowRankTensor() [4/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const std::vector< long > & dim, const TensorArgs & targs) inline
ctor with dimensions; constructs tensor filled with zeros
LowRankTensor() [5/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const TensorType & tt, const long k, const long ndim) inline
ctor with dimensions; all dims have the same value k
LowRankTensor() [6/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const Tensor< T > & rhs, const double & thresh, const TensorType & tt) inline
ctor with a regular Tensor and arguments, deep
LowRankTensor() [7/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const Tensor< T > & rhs, const TensorArgs & targs) inline
ctor with a regular Tensor and arguments, deep
References madness::LowRankTensor< T >::copy, madness::BaseTensor::dim(), madness::LowRankTensor< T >::facReduce(), madness::LowRankTensor< T >::implT::full, madness::Tensor< T >::has_data(), madness::LowRankTensor< T >::impl, MADNESS_ASSERT, madness::BaseTensor::ndim(), madness::Tensor< T >::reshape(), madness::BaseTensor::size(), madness::LowRankTensor< T >::implT::svd, madness::TensorArgs::thresh, madness::transpose(), madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
LowRankTensor() [8/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const Tensor< T > & other) inline
ctor with a regular Tensor, deep
References madness::LowRankTensor< T >::copy, madness::LowRankTensor< T >::implT::full, and madness::LowRankTensor< T >::impl.
LowRankTensor() [9/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const TensorTrain< T > & tt) inline
ctor with a TensorTrain as argument, shallow
References madness::LowRankTensor< T >::impl, and madness::LowRankTensor< T >::implT::tt.
LowRankTensor() [10/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const SVDTensor< T > & t) inline
ctor with a SVDTensor as argument, shallow
References madness::LowRankTensor< T >::impl, and madness::LowRankTensor< T >::implT::svd.
LowRankTensor() [11/11]
template<typename T> madness::LowRankTensor< T >::LowRankTensor (const SliceLowRankTensor< T > & other) inline
ctor with a SliceLowRankTensor as argument, deep
Member Function Documentation
add_SVD()
template<typename T> void madness::LowRankTensor< T >::add_SVD (const LowRankTensor< T > & other, const double & thresh) inline
References madness::LowRankTensor< T >::facReduce(), madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, thresh, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
config()
template<typename T> SRConf<T>& madness::LowRankTensor< T >::config () inline
References MADNESS_EXCEPTION.
convert()
template<typename T> LowRankTensor madness::LowRankTensor< T >::convert (const TensorArgs & targs) const inline
convert this to a new LowRankTensor of given tensor type
References madness::_(), madness::LowRankTensor< T >::copy, d(), madness::BaseTensor::dim(), madness::LowRankTensor< T >::dim(), madness::LowRankTensor< T >::facReduce(), madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, k, k1, k2, madness::LowRankTensor< T >::LowRankTensor(), m, MADNESS_ASSERT, MADNESS_EXCEPTION, madness::BaseTensor::ndim(), madness::LowRankTensor< T >::ndim(), madness::LowRankTensor< T >::rank(), madness::LowRankTensor< T >::reconstruct_tensor(), madness::Tensor< T >::reshape(), madness::BaseTensor::size(), madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::tensor_type(), madness::TensorArgs::thresh, madness::transpose(), madness::LowRankTensor< T >::implT::tt, madness::TensorArgs::tt, madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
dim()
template<typename T> long madness::LowRankTensor< T >::dim (const int i) const inline
return the number of entries in dimension i
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::convert(), and madness::LowRankTensor< T >::LowRankTensor().
emul()
template<typename T> LowRankTensor<T>& madness::LowRankTensor< T >::emul (const LowRankTensor< T > & other) inline
Inplace multiply by corresponding elements of argument Tensor.
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_ASSERT, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
fac_reduce()
template<typename T> static double madness::LowRankTensor< T >::fac_reduce () inline static
facReduce()
template<typename T> static double madness::LowRankTensor< T >::facReduce () inline static
Referenced by madness::LowRankTensor< T >::add_SVD(), madness::LowRankTensor< T >::convert(), madness::LowRankTensor< T >::LowRankTensor(), and madness::LowRankTensor< T >::reduce_rank().
full_tensor() [1/2]
template<typename T> const Tensor<T>& madness::LowRankTensor< T >::full_tensor () const inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_ASSERT, madness::TT_FULL, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::reconstruct_tensor().
full_tensor() [2/2]
template<typename T> Tensor<T>& madness::LowRankTensor< T >::full_tensor () inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_ASSERT, madness::TT_FULL, and madness::LowRankTensor< T >::type.
full_tensor_copy()
template<typename T> Tensor<T> madness::LowRankTensor< T >::full_tensor_copy () const inline
References madness::LowRankTensor< T >::copy, madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::outer(), and madness::LowRankTensor< T >::reconstruct_tensor().
gaxpy()
template<typename T> LowRankTensor& madness::LowRankTensor< T >::gaxpy (const T alpha, const LowRankTensor< T > & other, const T beta) inline
References alpha, beta, madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_ASSERT, MADNESS_EXCEPTION, madness::LowRankTensor< T >::scale(), madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::operator+=(), and madness::LowRankTensor< T >::operator-=().
has_data()
template<typename T> bool madness::LowRankTensor< T >::has_data () const inline
References madness::TT_NONE, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::has_no_data(), and madness::archive::ArchiveStoreImpl< Archive, LowRankTensor< T > >::store().
has_no_data()
template<typename T> bool madness::LowRankTensor< T >::has_no_data () const inline
References madness::LowRankTensor< T >::has_data().
Referenced by madness::LowRankTensor< T >::general_transform(), madness::SliceLowRankTensor< T >::operator+=(), madness::SliceLowRankTensor< T >::operator-=(), madness::LowRankTensor< T >::transform(), and madness::LowRankTensor< T >::transform_dir().
method1()
template<typename T> void madness::LowRankTensor< T >::method1 () inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
ndim()
template<typename T> long madness::LowRankTensor< T >::ndim () const inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::convert(), madness::SliceLowRankTensor< T >::operator+=(), and madness::SliceLowRankTensor< T >::operator-=().
normalize()
template<typename T> void madness::LowRankTensor< T >::normalize () inline
References madness::LowRankTensor< T >::impl, madness::LowRankTensor< T >::implT::svd, madness::TT_2D, and madness::LowRankTensor< T >::type.
normf()
template<typename T> float_scalar_type madness::LowRankTensor< T >::normf () const inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
operator LowRankTensor< Q >()
template<typename T> template<class Q > madness::LowRankTensor< T >::operator LowRankTensor< Q > () const inline
Type conversion makes a deep copy.
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, and madness::TT_TENSORTRAIN.
operator()() [1/2]
template<typename T> SliceLowRankTensor<T> madness::LowRankTensor< T >::operator() (const std::vector< Slice > & s) inline
general slicing, shallow; for temporary use only!
operator()() [2/2]
template<typename T> const SliceLowRankTensor<T> madness::LowRankTensor< T >::operator() (const std::vector< Slice > & s) const inline
general slicing, shallow; for temporary use only!
operator*()
template<typename T> template<typename Q > LowRankTensor<TENSOR_RESULT_TYPE(T,Q)> madness::LowRankTensor< T >::operator* (const Q & x) const inline
multiply with a number
References madness::LowRankTensor< T >::copy, and madness::LowRankTensor< T >::scale().
operator+=()
template<typename T> LowRankTensor& madness::LowRankTensor< T >::operator+= (const LowRankTensor< T > & other) inline
References madness::LowRankTensor< T >::gaxpy().
operator-=()
template<typename T> LowRankTensor& madness::LowRankTensor< T >::operator-= (const LowRankTensor< T > & other) inline
References madness::LowRankTensor< T >::gaxpy().
operator=() [1/3]
template<typename T> LowRankTensor& madness::LowRankTensor< T >::operator= (const LowRankTensor< T > & other) inline
shallow assignment operator
References madness::LowRankTensor< T >::impl, and madness::LowRankTensor< T >::type.
operator=() [2/3]
template<typename T> LowRankTensor& madness::LowRankTensor< T >::operator= (const SliceLowRankTensor< T > & other) inline
deep assignment with slices: g0 = g1(s)
References madness::LowRankTensor< T >::copy, madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, madness::SliceLowRankTensor< T >::lrt, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::SliceLowRankTensor< T >::thisslice, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
operator=() [3/3]
template<typename T> LowRankTensor& madness::LowRankTensor< T >::operator= (const T & number) inline
assign a number to this tensor
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
ptr() [1/2]
template<typename T> T* madness::LowRankTensor< T >::ptr (const int ivec = 0) inline
Returns a pointer to the internal data.
Parameters
[in] ivec index of core vector to which the return values points
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
ptr() [2/2]
template<typename T> const T* madness::LowRankTensor< T >::ptr (const int ivec = 0) const inline
Returns a pointer to the internal data.
Parameters
[in] ivec index of core vector to which the return values points
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
rank()
template<typename T> long madness::LowRankTensor< T >::rank () const inline
References madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::convert(), madness::SliceLowRankTensor< T >::operator+=(), madness::SliceLowRankTensor< T >::operator-=(), and madness::LowRankTensor< T >::TENSOR_RESULT_TYPE().
real_size()
template<typename T> long madness::LowRankTensor< T >::real_size () const inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
reconstruct_tensor()
template<typename T> Tensor<T> madness::LowRankTensor< T >::reconstruct_tensor () const inline
reconstruct this to return a full tensor
References madness::LowRankTensor< T >::full_tensor(), madness::LowRankTensor< T >::full_tensor_copy(), MADNESS_EXCEPTION, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::convert().
reduce_rank()
template<typename T> void madness::LowRankTensor< T >::reduce_rank (const double & thresh) inline
References madness::LowRankTensor< T >::facReduce(), madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, thresh, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::reduce().
scale()
template<typename T> template<typename Q > IsSupported<TensorTypeData<Q>,LowRankTensor<T>&>::type madness::LowRankTensor< T >::scale (Q fac) inline
Inplace multiplication by scalar of supported type (legacy name)
Parameters
[in] x Scalar value
Returns
Reference to this tensor
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::gaxpy(), and madness::LowRankTensor< T >::operator*().
size()
template<typename T> long madness::LowRankTensor< T >::size () const inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
svd_normf()
template<typename T> float_scalar_type madness::LowRankTensor< T >::svd_normf () const inline
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
TENSOR_RESULT_TYPE()
template<typename T> template<typename Q > madness::LowRankTensor< T >::TENSOR_RESULT_TYPE (T , Q) const & inline
returns the trace of <this|rhs>
References madness::LowRankTensor< T >::implT::full, madness::LowRankTensor< T >::impl, MADNESS_ASSERT, MADNESS_EXCEPTION, madness::LowRankTensor< T >::rank(), madness::LowRankTensor< T >::implT::svd, madness::LowRankTensor< T >::implT::tt, madness::TT_2D, madness::TT_FULL, madness::TT_NONE, madness::TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::general_transform(), madness::LowRankTensor< T >::transform(), and madness::LowRankTensor< T >::transform_dir().
tensor_type()
template<typename T> TensorType madness::LowRankTensor< T >::tensor_type () const inline
return the tensor type
References madness::LowRankTensor< T >::type.
Referenced by madness::LowRankTensor< T >::convert(), madness::SliceLowRankTensor< T >::operator+=(), madness::SliceLowRankTensor< T >::operator-=(), and madness::outer().
Friends And Related Function Documentation
copy
template<typename T> LowRankTensor copy (const LowRankTensor< T > & other) friend
deep copy
Referenced by madness::LowRankTensor< T >::convert(), madness::LowRankTensor< T >::full_tensor_copy(), madness::LowRankTensor< T >::LowRankTensor(), madness::LowRankTensor< T >::operator*(), and madness::LowRankTensor< T >::operator=().
Member Data Documentation
impl
template<typename T> implT madness::LowRankTensor< T >::impl
Referenced by madness::LowRankTensor< T >::add_SVD(), madness::LowRankTensor< T >::convert(), madness::convert(), madness::LowRankTensor< T >::dim(), madness::LowRankTensor< T >::emul(), madness::LowRankTensor< T >::full_tensor(), madness::LowRankTensor< T >::full_tensor_copy(), madness::LowRankTensor< T >::gaxpy(), madness::LowRankTensor< T >::general_transform(), madness::archive::ArchiveLoadImpl< Archive, LowRankTensor< T > >::load(), madness::LowRankTensor< T >::LowRankTensor(), madness::LowRankTensor< T >::method1(), madness::LowRankTensor< T >::ndim(), madness::LowRankTensor< T >::normalize(), madness::LowRankTensor< T >::normf(), madness::LowRankTensor< T >::operator LowRankTensor< Q >(), madness::SliceLowRankTensor< T >::operator+=(), madness::SliceLowRankTensor< T >::operator-=(), madness::LowRankTensor< T >::operator=(), madness::outer(), madness::LowRankTensor< T >::ptr(), madness::LowRankTensor< T >::rank(), madness::LowRankTensor< T >::real_size(), madness::LowRankTensor< T >::reduce_rank(), madness::LowRankTensor< T >::scale(), madness::LowRankTensor< T >::size(), madness::archive::ArchiveStoreImpl< Archive, LowRankTensor< T > >::store(), madness::LowRankTensor< T >::svd_normf(), madness::LowRankTensor< T >::TENSOR_RESULT_TYPE(), madness::LowRankTensor< T >::transform(), and madness::LowRankTensor< T >::transform_dir().
type
template<typename T> TensorType madness::LowRankTensor< T >::type
Referenced by madness::LowRankTensor< T >::add_SVD(), madness::convert(), madness::LowRankTensor< T >::dim(), madness::LowRankTensor< T >::emul(), madness::LowRankTensor< T >::full_tensor(), madness::LowRankTensor< T >::full_tensor_copy(), madness::LowRankTensor< T >::gaxpy(), madness::LowRankTensor< T >::general_transform(), madness::LowRankTensor< T >::has_data(), madness::archive::ArchiveLoadImpl< Archive, LowRankTensor< T > >::load(), madness::LowRankTensor< T >::LowRankTensor(), madness::LowRankTensor< T >::method1(), madness::LowRankTensor< T >::ndim(), madness::LowRankTensor< T >::normalize(), madness::LowRankTensor< T >::normf(), madness::LowRankTensor< T >::operator=(), madness::LowRankTensor< T >::ptr(), madness::LowRankTensor< T >::rank(), madness::LowRankTensor< T >::real_size(), madness::LowRankTensor< T >::reconstruct_tensor(), madness::LowRankTensor< T >::reduce_rank(), madness::LowRankTensor< T >::scale(), madness::LowRankTensor< T >::size(), madness::archive::ArchiveStoreImpl< Archive, LowRankTensor< T > >::store(), madness::LowRankTensor< T >::svd_normf(), madness::LowRankTensor< T >::TENSOR_RESULT_TYPE(), madness::LowRankTensor< T >::tensor_type(), madness::LowRankTensor< T >::transform(), and madness::LowRankTensor< T >::transform_dir().
The documentation for this class was generated from the following file:
lowranktensor.h