MADNESS: madness::LBNodeDeux< NDIM > Class Template Reference
madness::LBNodeDeux< NDIM > Class Template Reference
#include <lbdeux.h>
Public Member Functions
LBNodeDeux ()
LBNodeDeux (const LBNodeDeux< NDIM > &other)
void add (double cost, bool got_kids)
Accumulates cost into this node.
void deleter (const treeT &tree, const keyT &key)
Logically deletes this node by setting cost to -1.
double get_total_cost () const
bool has_children () const
LBNodeDeux< NDIM > & operator= (const LBNodeDeux< NDIM > &other)
void partition (const treeT &tree, const keyT &key, double avg)
Descends tree deleting all except internal nodes and sub-tree parents.
template<typename Archive >
void serialize (Archive &ar)
void sum (const treeT &tree, const keyT &child, double value)
Accumulates cost up the tree from children.
Private Types
typedef Key< NDIM > keyT
typedef LBNodeDeux< NDIM > nodeT
typedef WorldContainer< keyT, nodeT > treeT
Private Member Functions
int index (const keyT &key)
Computes index of child key in this node using last bit of translations.
Private Attributes
volatile double child_cost [nchild]
volatile bool gotkids
volatile double my_cost
AtomicInt nsummed
volatile double total_cost
Static Private Attributes
static const int nchild = (1<<NDIM)
Member Typedef Documentation
keyT
template<std::size_t NDIM> typedef Key<NDIM> madness::LBNodeDeux< NDIM >::keyT private
nodeT
template<std::size_t NDIM> typedef LBNodeDeux<NDIM> madness::LBNodeDeux< NDIM >::nodeT private
treeT
template<std::size_t NDIM> typedef WorldContainer<keyT,nodeT> madness::LBNodeDeux< NDIM >::treeT private
Constructor & Destructor Documentation
LBNodeDeux() [1/2]
template<std::size_t NDIM> madness::LBNodeDeux< NDIM >::LBNodeDeux () inline
References madness::LBNodeDeux< NDIM >::child_cost, madness::LBNodeDeux< NDIM >::nchild, and madness::LBNodeDeux< NDIM >::nsummed.
LBNodeDeux() [2/2]
template<std::size_t NDIM> madness::LBNodeDeux< NDIM >::LBNodeDeux (const LBNodeDeux< NDIM > & other) inline
References madness::LBNodeDeux< NDIM >::child_cost, madness::LBNodeDeux< NDIM >::nchild, and madness::LBNodeDeux< NDIM >::nsummed.
Member Function Documentation
add()
template<std::size_t NDIM> void madness::LBNodeDeux< NDIM >::add (double cost, bool got_kids) inline
Accumulates cost into this node.
References madness::LBNodeDeux< NDIM >::gotkids, madness::LBNodeDeux< NDIM >::my_cost, and madness::LBNodeDeux< NDIM >::total_cost.
Referenced by madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::operator()().
deleter()
template<std::size_t NDIM> void madness::LBNodeDeux< NDIM >::deleter (const treeT & tree, const keyT & key) inline
Logically deletes this node by setting cost to -1.
Cannot actually erase this node from the container since the send() handler is holding an accessor to it.
References madness::LBNodeDeux< NDIM >::has_children(), madness::LBNodeDeux< NDIM >::my_cost, and madness::LBNodeDeux< NDIM >::total_cost.
Referenced by madness::LBNodeDeux< NDIM >::partition().
get_total_cost()
template<std::size_t NDIM> double madness::LBNodeDeux< NDIM >::get_total_cost () const inline
References madness::LBNodeDeux< NDIM >::total_cost.
Referenced by madness::LoadBalanceDeux< NDIM >::sum().
has_children()
template<std::size_t NDIM> bool madness::LBNodeDeux< NDIM >::has_children () const inline
References madness::LBNodeDeux< NDIM >::gotkids.
Referenced by madness::LBNodeDeux< NDIM >::deleter(), madness::LBNodeDeux< NDIM >::partition(), and madness::LoadBalanceDeux< NDIM >::sum().
index()
template<std::size_t NDIM> int madness::LBNodeDeux< NDIM >::index (const keyT & key) inline private
Computes index of child key in this node using last bit of translations.
References d(), NDIM, and madness::Key< NDIM >::translation().
Referenced by madness::LBNodeDeux< NDIM >::partition(), and madness::LBNodeDeux< NDIM >::sum().
operator=()
template<std::size_t NDIM> LBNodeDeux<NDIM>& madness::LBNodeDeux< NDIM >::operator= (const LBNodeDeux< NDIM > & other) inline
References madness::LBNodeDeux< NDIM >::child_cost, madness::LBNodeDeux< NDIM >::gotkids, madness::LBNodeDeux< NDIM >::my_cost, madness::LBNodeDeux< NDIM >::nchild, madness::LBNodeDeux< NDIM >::nsummed, and madness::LBNodeDeux< NDIM >::total_cost.
partition()
template<std::size_t NDIM> void madness::LBNodeDeux< NDIM >::partition (const treeT & tree, const keyT & key, double avg) inline
Descends tree deleting all except internal nodes and sub-tree parents.
References madness::LBNodeDeux< NDIM >::child_cost, madness::LBNodeDeux< NDIM >::deleter(), madness::LBNodeDeux< NDIM >::has_children(), madness::LBNodeDeux< NDIM >::index(), madness::LBNodeDeux< NDIM >::nchild, madness::swap(), and madness::LBNodeDeux< NDIM >::total_cost.
Referenced by madness::LoadBalanceDeux< NDIM >::load_balance().
serialize()
template<std::size_t NDIM> template<typename Archive > void madness::LBNodeDeux< NDIM >::serialize (Archive & ar) inline
References madness::archive::wrap_opaque().
sum()
template<std::size_t NDIM> void madness::LBNodeDeux< NDIM >::sum (const treeT & tree, const keyT & child, double value) inline
Accumulates cost up the tree from children.
References madness::LBNodeDeux< NDIM >::child_cost, madness::LBNodeDeux< NDIM >::index(), madness::Key< NDIM >::level(), madness::LBNodeDeux< NDIM >::nchild, madness::LBNodeDeux< NDIM >::nsummed, madness::Key< NDIM >::parent(), and madness::LBNodeDeux< NDIM >::total_cost.
Referenced by madness::LoadBalanceDeux< NDIM >::sum().
Member Data Documentation
child_cost
template<std::size_t NDIM> volatile double madness::LBNodeDeux< NDIM >::child_cost[nchild] private
Referenced by madness::LBNodeDeux< NDIM >::LBNodeDeux(), madness::LBNodeDeux< NDIM >::operator=(), madness::LBNodeDeux< NDIM >::partition(), and madness::LBNodeDeux< NDIM >::sum().
gotkids
template<std::size_t NDIM> volatile bool madness::LBNodeDeux< NDIM >::gotkids private
Referenced by madness::LBNodeDeux< NDIM >::add(), madness::LBNodeDeux< NDIM >::has_children(), and madness::LBNodeDeux< NDIM >::operator=().
my_cost
template<std::size_t NDIM> volatile double madness::LBNodeDeux< NDIM >::my_cost private
Referenced by madness::LBNodeDeux< NDIM >::add(), madness::LBNodeDeux< NDIM >::deleter(), and madness::LBNodeDeux< NDIM >::operator=().
nchild
template<std::size_t NDIM> const int madness::LBNodeDeux< NDIM >::nchild = (1<<NDIM) static private
Referenced by madness::LBNodeDeux< NDIM >::LBNodeDeux(), madness::LBNodeDeux< NDIM >::operator=(), madness::LBNodeDeux< NDIM >::partition(), and madness::LBNodeDeux< NDIM >::sum().
nsummed
template<std::size_t NDIM> AtomicInt madness::LBNodeDeux< NDIM >::nsummed private
Referenced by madness::LBNodeDeux< NDIM >::LBNodeDeux(), madness::LBNodeDeux< NDIM >::operator=(), and madness::LBNodeDeux< NDIM >::sum().
total_cost
template<std::size_t NDIM> volatile double madness::LBNodeDeux< NDIM >::total_cost private
Referenced by madness::LBNodeDeux< NDIM >::add(), madness::LBNodeDeux< NDIM >::deleter(), madness::LBNodeDeux< NDIM >::get_total_cost(), madness::LBNodeDeux< NDIM >::operator=(), madness::LBNodeDeux< NDIM >::partition(), and madness::LBNodeDeux< NDIM >::sum().
The documentation for this class was generated from the following file:
lbdeux.h