MADNESS: linked_list Class Reference
linked_list Class Reference
Public Member Functions
linked_list (int value=0)
void append (int value)
linked_list * get_next () const
int get_value () const
void print ()
void set_value (int val)
Private Attributes
linked_list * next
int value
Constructor & Destructor Documentation
linked_list()
linked_list::linked_list (int value = 0) inline
Referenced by append().
Member Function Documentation
append()
void linked_list::append (int value) inline
References append(), linked_list(), next, and value.
Referenced by append(), and test_out().
get_next()
linked_list* linked_list::get_next () const inline
References next.
get_value()
int linked_list::get_value () const inline
References value.
print()
void linked_list::print () inline
References next, print(), and value.
Referenced by print(), test_in(), and test_out().
set_value()
void linked_list::set_value (int val) inline
References value.
Member Data Documentation
next
linked_list* linked_list::next private
Referenced by append(), get_next(), and print().
value
int linked_list::value private
Referenced by append(), get_value(), print(), and set_value().
The documentation for this class was generated from the following file:
test_ar.cc