MADNESS: AtomicBasis Class Reference
AtomicBasis Class Reference
Represents multiple shells of contracted gaussians on a single center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasis ()
AtomicBasis (const std::vector< ContractedGaussianShell > &g)
double * eval (double x, double y, double z, double *bf) const
Evaluates the basis functions at point x, y, z relative to atomic center.
double eval_guess_density (double x, double y, double z) const
Evaluates the guess atomic density at point x, y, z relative to atomic center.
const Tensor< double > & get_avec () const
const Tensor< double > & get_bvec () const
const Tensor< double > & get_dmat () const
const ContractedGaussianShell & get_shell_from_basis_function (int ibf, int &ibf_in_shell) const
Return shell that contains basis function ibf and also return index of function in the shell.
const std::vector< ContractedGaussianShell > & get_shells () const
Returns a const reference to the shells.
bool has_guess_info () const
int nbf () const
Returns the number of basis functions on the center.
int nshell () const
Returns the number of shells on the center.
template<typename Archive >
void serialize (Archive &ar)
void set_guess_info (const Tensor< double > &dmat, const Tensor< double > &avec, const Tensor< double > &bvec)
Private Attributes
Tensor< double > avec
Tensor< double > bvec
Tensor< double > dmat
std::vector< ContractedGaussianShell > g
int numbf
double rmaxsq
Detailed Description
Represents multiple shells of contracted gaussians on a single center.
Constructor & Destructor Documentation
AtomicBasis() [1/2]
AtomicBasis::AtomicBasis () inline
AtomicBasis() [2/2]
AtomicBasis::AtomicBasis (const std::vector< ContractedGaussianShell > & g) inline
References madness::AtomicBasis::g, max, madness::AtomicBasis::numbf, and madness::AtomicBasis::rmaxsq.
Member Function Documentation
eval()
double* AtomicBasis::eval (double x, double y, double z, double * bf) const inline
Evaluates the basis functions at point x, y, z relative to atomic center.
The array bf[] must be large enough to hold nbf() values.
Returned is the incremented pointer.
References madness::AtomicBasis::g, MADNESS_ASSERT, madness::AtomicBasis::numbf, and madness::AtomicBasis::rmaxsq.
eval_guess_density()
double AtomicBasis::eval_guess_density (double x, double y, double z) const inline
Evaluates the guess atomic density at point x, y, z relative to atomic center.
References madness::AtomicBasis::dmat, madness::AtomicBasis::eval(), madness::AtomicBasis::has_guess_info(), MADNESS_ASSERT, madness::AtomicBasis::numbf, p(), madness::Tensor< T >::ptr(), madness::AtomicBasis::rmaxsq, and madness::sum().
get_avec()
const Tensor<double>& AtomicBasis::get_avec () const inline
References madness::AtomicBasis::avec.
get_bvec()
const Tensor<double>& AtomicBasis::get_bvec () const inline
References madness::AtomicBasis::bvec.
get_dmat()
const Tensor<double>& AtomicBasis::get_dmat () const inline
References madness::AtomicBasis::dmat.
get_shell_from_basis_function()
const ContractedGaussianShell& AtomicBasis::get_shell_from_basis_function (int ibf, int & ibf_in_shell) const inline
Return shell that contains basis function ibf and also return index of function in the shell.
References madness::AtomicBasis::g, MADNESS_EXCEPTION, and madness::AtomicBasis::nbf().
get_shells()
const std::vector<ContractedGaussianShell>& AtomicBasis::get_shells () const inline
Returns a const reference to the shells.
References madness::AtomicBasis::g.
has_guess_info()
bool AtomicBasis::has_guess_info () const inline
References madness::AtomicBasis::dmat, and madness::BaseTensor::size().
nbf()
int AtomicBasis::nbf () const inline
Returns the number of basis functions on the center.
References madness::AtomicBasis::numbf.
nshell()
int AtomicBasis::nshell () const inline
Returns the number of shells on the center.
References madness::AtomicBasis::g.
serialize()
template<typename Archive > void AtomicBasis::serialize (Archive & ar) inline
References madness::AtomicBasis::avec, madness::AtomicBasis::bvec, madness::AtomicBasis::dmat, madness::AtomicBasis::g, madness::AtomicBasis::numbf, and madness::AtomicBasis::rmaxsq.
set_guess_info()
void AtomicBasis::set_guess_info (const Tensor< double > & dmat, const Tensor< double > & avec, const Tensor< double > & bvec) inline
References madness::AtomicBasis::avec, madness::AtomicBasis::bvec, madness::copy(), and madness::AtomicBasis::dmat.
Member Data Documentation
avec
Tensor<double> AtomicBasis::avec private
bvec
Tensor<double> AtomicBasis::bvec private
dmat
Tensor<double> AtomicBasis::dmat private
g
std::vector<ContractedGaussianShell> AtomicBasis::g private
numbf
int AtomicBasis::numbf private
rmaxsq
double AtomicBasis::rmaxsq private
The documentation for this class was generated from the following file:
hf/molecularbasis.h