MADNESS: madness::Timer Class Reference
madness::Timer Class Reference
#include <function_common_data.h>
Public Member Functions
Timer ()
start timer
void accumulate (const double time) const
accumulate timer
void print (std::string line="") const
print timer
void reset () const
Private Types
typedef ConcurrentHashMap< int, double >::accessor accessor
typedef ConcurrentHashMap< int, double > map
Private Attributes
map data
Static Private Attributes
static const int itotal =-10
Member Typedef Documentation
accessor
typedef ConcurrentHashMap<int,double>::accessor madness::Timer::accessor private
map
typedef ConcurrentHashMap<int,double> madness::Timer::map private
Constructor & Destructor Documentation
Timer()
madness::Timer::Timer () inline
start timer
Member Function Documentation
accumulate()
void madness::Timer::accumulate (const double time) const inline
accumulate timer
References data, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
Referenced by madness::SeparatedConvolution< T, NDIM >::apply(), madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), and madness::FunctionImpl< Q, NDIM >::do_apply_kernel3().
print()
void madness::Timer::print (std::string line = "") const inline
print timer
References data, madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), and madness::print().
Referenced by madness::SeparatedConvolution< T, NDIM >::print_timer().
reset()
void madness::Timer::reset () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear(), and data.
Referenced by madness::SeparatedConvolution< T, NDIM >::reset_timer().
Member Data Documentation
data
map madness::Timer::data private
Referenced by accumulate(), print(), and reset().
itotal
const int madness::Timer::itotal =-10 static private
The documentation for this class was generated from the following file:
function_common_data.h