MADNESS: madness::CallbackInterface Class Reference
madness::CallbackInterface Class Reference abstract
The class used for callbacks (e.g., dependency tracking).
#include <dependency_interface.h>
Public Member Functions
virtual ~CallbackInterface ()
virtual void notify ()=0
Invoked by the callback to notify when a dependency is satisfied.
virtual void notify_debug (const char *caller)
Same as notify(), but tracks how many times called from each caller.
Protected Member Functions
virtual void notify_debug_impl (const char *caller)
Detailed Description
The class used for callbacks (e.g., dependency tracking).
Constructor & Destructor Documentation
~CallbackInterface()
virtual madness::CallbackInterface::~CallbackInterface () inline virtual
Member Function Documentation
notify()
virtual void madness::CallbackInterface::notify () pure virtual
Invoked by the callback to notify when a dependency is satisfied.
Implemented in madness::WorldTaskQueue, madness::WorldGopInterface::DelayedSend< keyT, valueT >, madness::DependencyInterface, and madness::TaskInterface::Submit.
Referenced by notify_debug(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::register_callback(), madness::Future< bool >::register_callback(), and madness::TaskInterface::~TaskInterface().
notify_debug()
virtual void madness::CallbackInterface::notify_debug (const char * caller) inline virtual
Same as notify(), but tracks how many times called from each caller.
Reimplemented in madness::DependencyInterface.
References notify(), and notify_debug_impl().
notify_debug_impl()
virtual void madness::CallbackInterface::notify_debug_impl (const char * caller) inline protected virtual
Referenced by notify_debug(), and madness::DependencyInterface::notify_debug().
The documentation for this class was generated from the following file:
dependency_interface.h