MADNESS: madness::SRConf< T > Class Template Reference
madness::SRConf< T > Class Template Reference
#include <srconf.h>
Public Types
typedef Tensor< T > tensorT
Public Member Functions
SRConf ()
default ctor
SRConf (const unsigned int &dim, const unsigned int &k, const TensorType &tt)
ctor with dimensions for a vector configuration (tested)
SRConf (const SRConf &rhs)
copy ctor (tested); shallow copy
SRConf (const Tensor< double > &weights, const std::vector< Tensor< T > > &vectors, const unsigned int &dim, const unsigned int maxk, const TensorType &tt)
ctor with provided weights and effective vectors; shallow copy
SRConf (const tensorT &vector1)
explicit ctor with one vector (aka full representation), shallow
SRConf (const Tensor< double > &weights, const tensorT &vector1, const tensorT &vector2, const unsigned int &dim, const unsigned int maxk)
explicit ctor with two vectors (aka SVD), shallow
~SRConf ()
dtor
SRConf< T > copy_slice (const std::vector< Slice > &s) const
return a slice of this (deep copy)
unsigned int dim () const
return the dimension of this
unsigned int dim_eff () const
return the number of vectors
int dim_per_vector () const
return the number of physical dimensions
SRConf< T > & emul (const SRConf< T > &other)
perform elementwise Hadamard product
const Tensor< T > flat_vector (const unsigned int &idim) const
return shallow copy of a slice of one of the vectors, flattened to (r,kVec)
Tensor< T > flat_vector (const unsigned int &idim)
return shallow copy of a slice of one of the vectors, flattened to (r,kVec)
const SRConf get_configs (const int &start, const int &end) const
unsigned int get_k () const
return the number of physical matrix elements per dimension
bool has_data () const
does this have any data?
bool has_no_data () const
does this have any data?
bool has_structure () const
return if this has a tensor structure (has not been flattened)
long kVec () const
return the length of the vector (dim_pv*maxk)
SRConf & operator= (const SRConf &rhs)
assignment operator (tested), shallow copy of vectors
SRConf & operator= (const T &number)
assign a number to this;
void orthonormalize (const double &thresh)
orthonormalize this
long rank () const
return the logicalrank
Tensor< T > reconstruct () const
reconstruct this to return a full tensor
Tensor< T > & ref_vector (const unsigned int &idim)
return reference to one of the vectors F
const Tensor< T > & ref_vector (const unsigned int &idim) const
return reference to one of the vectors F
template<typename Archive >
void serialize (Archive &ar)
TensorType type () const
return the tensor type
double weights (const unsigned int &i) const
return the weight
Static Public Member Functions
static int max_sigma (const double &thresh, const int &rank, const Tensor< double > &w)
Public Attributes
unsigned int dim_
the number of dimensions (the order of the tensor)
unsigned int maxk_
long rank_
what is the rank of this
std::vector< Slice > s_
TensorType tensortype_
how will this be represented
std::vector< tensorT > vector_
Tensor< typename Tensor< T >::scalar_type > weights_
for each configuration the weight; length should be r
Static Public Attributes
static const bool check_orthonormality =false
check orthonormality at low rank additions
Protected Member Functions
void inplace_add (const SRConf< T > &rhs2, std::vector< Slice > lhs_s, std::vector< Slice > rhs_s, const double alpha, const double beta)
alpha * this(lhs_s) + beta * rhs(rhs_s)
void make_slices ()
redo the Slices for getting direct access to the configurations
void make_structure (bool force=false)
void undo_structure (bool force=false)
Private Types
typedef Tensor< T >::scalar_type scalar_type
the scalar type of T
Private Member Functions
void add_SVD (const SRConf< T > &rhs, const double &thresh)
add two orthonormal configurations, yielding an optimal SVD decomposition
void append (const SRConf< T > &rhs, const double fac=1.0)
append configurations of rhs to this
void append (const SRConf< T > &rhs, const double_complex fac=1.0)
const std::vector< Slice > & c0 () const
return a Slice that corresponds the that part of vector_ that holds coefficients
bool check_right_orthonormality () const
check if the terms are orthogonal
void divide_and_conquer_reduce (const double &thresh)
reduce the rank using a divide-and-conquer approach
void fillWithRandom (const long &rank=1)
fill this SRConf with 1 flattened random configurations (tested)
template<typename Q >
SRConf< TENSOR_RESULT_TYPE(T, Q) > general_transform (const Tensor< Q > c[]) const
bool is_flat () const
return if this has only one additional dimension (apart from rank)
unsigned int nCoeff () const
return the number of coefficients
void normalize ()
normalize the vectors (tested)
TensorTypeData< T >::float_scalar_type normf () const
calculate the Frobenius norm
template<typename Q >
std::enable_if<(TensorTypeData< T >::iscomplex or TensorTypeData< Q >::iscomplex), TENSOR_RESULT_TYPE(T, Q)>::type friend overlap (const SRConf< T > &rhs, const SRConf< Q > &lhs)
template<typename Q >
std::enable_if<!(TensorTypeData< T >::iscomplex or TensorTypeData< Q >::iscomplex), TENSOR_RESULT_TYPE(T, Q)>::type friend overlap (const SRConf< T > &rhs, const SRConf< Q > &lhs)
calculate the Frobenius inner product (tested)
size_t real_size () const
return the real size of this
void reserve (long r)
reserve enough space to hold at least r configurations
void scale (const double &fac)
scale this by a number
void scale (const double_complex &fac)
TensorTypeData< T >::float_scalar_type svd_normf () const
calculate the Frobenius norm, if this is in SVD form
SRConf< T > transform (const Tensor< T > &c) const
SRConf< T > transform_dir (const Tensor< T > &c, const int &axis) const
Static Private Member Functions
static unsigned int compute_nvec (const TensorType &tt)
return the number of vectors (i.e. dim_eff) according to the TensorType
Friends
bool compatible (const SRConf &lhs, const SRConf &rhs)
check compatibility
SRConf< T > copy (const SRConf< T > &rhs)
deep copy of rhs, shrink
class GenTensor< T >
class LowRankTensor< T >
class SliceLowRankTensor< T >
Detailed Description
template<typename T>
class madness::SRConf< T >
A SRConf handles all the configurations in a Separated Representation.
Member Typedef Documentation
scalar_type
template<typename T> typedef Tensor<T>::scalar_type madness::SRConf< T >::scalar_type private
the scalar type of T
tensorT
template<typename T> typedef Tensor<T> madness::SRConf< T >::tensorT
Constructor & Destructor Documentation
SRConf() [1/6]
template<typename T> madness::SRConf< T >::SRConf () inline
default ctor
SRConf() [2/6]
template<typename T> madness::SRConf< T >::SRConf (const unsigned int & dim, const unsigned int & k, const TensorType & tt) inline
ctor with dimensions for a vector configuration (tested)
References madness::SRConf< T >::compute_nvec(), madness::SRConf< T >::dim(), madness::SRConf< T >::has_structure(), k, madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::make_structure(), madness::SRConf< T >::rank_, madness::TT_FULL, madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
SRConf() [3/6]
template<typename T> madness::SRConf< T >::SRConf (const SRConf< T > & rhs) inline
copy ctor (tested); shallow copy
References madness::SRConf< T >::has_structure(), and MADNESS_ASSERT.
SRConf() [4/6]
template<typename T> madness::SRConf< T >::SRConf (const Tensor< double > & weights, const std::vector< Tensor< T > > & vectors, const unsigned int & dim, const unsigned int maxk, const TensorType & tt) inline
ctor with provided weights and effective vectors; shallow copy
References madness::SRConf< T >::compute_nvec(), madness::SRConf< T >::dim(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::rank_, madness::SRConf< T >::vector_, madness::SRConf< T >::weights(), and madness::SRConf< T >::weights_.
SRConf() [5/6]
template<typename T> madness::SRConf< T >::SRConf (const tensorT & vector1) inline
explicit ctor with one vector (aka full representation), shallow
References madness::SRConf< T >::has_structure(), MADNESS_ASSERT, and madness::SRConf< T >::vector_.
SRConf() [6/6]
template<typename T> madness::SRConf< T >::SRConf (const Tensor< double > & weights, const tensorT & vector1, const tensorT & vector2, const unsigned int & dim, const unsigned int maxk) inline
explicit ctor with two vectors (aka SVD), shallow
References madness::BaseTensor::dim(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::BaseTensor::ndim(), madness::SRConf< T >::rank_, madness::SRConf< T >::vector_, madness::SRConf< T >::weights(), and madness::SRConf< T >::weights_.
~SRConf()
template<typename T> madness::SRConf< T >::~SRConf () inline
dtor
Member Function Documentation
add_SVD()
template<typename T> void madness::SRConf< T >::add_SVD (const SRConf< T > & rhs, const double & thresh) inline private
add two orthonormal configurations, yielding an optimal SVD decomposition
References madness::SRConf< T >::check_orthonormality, madness::SRConf< T >::check_right_orthonormality(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::ortho5(), madness::SRConf< T >::rank_, madness::SRConf< T >::ref_vector(), thresh, madness::SRConf< T >::undo_structure(), madness::wall_time(), and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::divide_and_conquer_reduce().
append() [1/2]
template<typename T> void madness::SRConf< T >::append (const SRConf< T > & rhs, const double fac = 1.0) inline private
append configurations of rhs to this
simplified version of inplace_add for flattened configurations *this += fac*rhs
References madness::_(), madness::SRConf< T >::c0(), madness::SRConf< T >::copy, madness::SRConf< T >::dim_eff(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::rank(), madness::SRConf< T >::rank_, madness::SRConf< T >::reserve(), madness::SRConf< T >::scale(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
append() [2/2]
template<typename T> void madness::SRConf< T >::append (const SRConf< T > & rhs, const double_complex fac = 1.0) inline private
References MADNESS_EXCEPTION.
c0()
template<typename T> const std::vector<Slice>& madness::SRConf< T >::c0 () const inline private
return a Slice that corresponds the that part of vector_ that holds coefficients
References MADNESS_ASSERT, and madness::SRConf< T >::s_.
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::check_right_orthonormality(), madness::SRConf< T >::flat_vector(), and madness::SRConf< T >::reserve().
check_right_orthonormality()
template<typename T> bool madness::SRConf< T >::check_right_orthonormality () const inline private
check if the terms are orthogonal
References madness::SRConf< T >::c0(), madness::BaseTensor::dim(), e(), madness::inner(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::detail::norm(), madness::Tensor< T >::normf(), madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::BaseTensor::size(), small, madness::TT_2D, and madness::SRConf< T >::type().
Referenced by madness::SRConf< T >::add_SVD().
compute_nvec()
template<typename T> static unsigned int madness::SRConf< T >::compute_nvec (const TensorType & tt) inline static private
return the number of vectors (i.e. dim_eff) according to the TensorType
References MADNESS_ASSERT, madness::print(), madness::TT_2D, and madness::TT_FULL.
Referenced by madness::SRConf< T >::SRConf().
copy_slice()
template<typename T> SRConf<T> madness::SRConf< T >::copy_slice (const std::vector< Slice > & s) const inline
return a slice of this (deep copy)
References a, madness::SRConf< T >::copy, madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::get_k(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, MADNESS_EXCEPTION, madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::weights(), and madness::SRConf< T >::weights_.
dim()
template<typename T> unsigned int madness::SRConf< T >::dim () const inline
return the dimension of this
References madness::SRConf< T >::dim_.
Referenced by madness::SRConf< T >::copy_slice(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::emul(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::normf(), madness::SRConf< T >::overlap(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::reserve(), and madness::SRConf< T >::SRConf().
dim_eff()
template<typename T> unsigned int madness::SRConf< T >::dim_eff () const inline
return the number of vectors
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::general_transform(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::nCoeff(), madness::SRConf< T >::normalize(), madness::SRConf< T >::normf(), madness::SRConf< T >::operator=(), madness::SRConf< T >::overlap(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::reserve(), madness::SRConf< T >::transform(), and madness::SRConf< T >::undo_structure().
dim_per_vector()
template<typename T> int madness::SRConf< T >::dim_per_vector () const inline
return the number of physical dimensions
References madness::SRConf< T >::dim(), MADNESS_ASSERT, and madness::SRConf< T >::vector_.
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::kVec(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::normalize(), madness::SRConf< T >::transform_dir(), and madness::SRConf< T >::undo_structure().
divide_and_conquer_reduce()
template<typename T> void madness::SRConf< T >::divide_and_conquer_reduce (const double & thresh) inline private
reduce the rank using a divide-and-conquer approach
References madness::SRConf< T >::add_SVD(), madness::SRConf< T >::divide_and_conquer_reduce(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::normalize(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::rank(), and thresh.
Referenced by madness::SRConf< T >::divide_and_conquer_reduce().
emul()
template<typename T> SRConf<T>& madness::SRConf< T >::emul (const SRConf< T > & other) inline
perform elementwise Hadamard product
References madness::_(), a1, a2, madness::SRConf< T >::dim(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::get_k(), k, madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::make_structure(), madness::SRConf< T >::normalize(), madness::outer(), madness::SRConf< T >::rank(), madness::SRConf< T >::rank_, madness::TT_2D, madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
fillWithRandom()
template<typename T> void madness::SRConf< T >::fillWithRandom (const long & rank = 1) inline private
fill this SRConf with 1 flattened random configurations (tested)
References madness::SRConf< T >::dim_eff(), madness::Tensor< T >::fillrandom(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::normalize(), madness::SRConf< T >::rank(), madness::SRConf< T >::rank_, madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
flat_vector() [1/2]
template<typename T> const Tensor<T> madness::SRConf< T >::flat_vector (const unsigned int & idim) const inline
return shallow copy of a slice of one of the vectors, flattened to (r,kVec)
References madness::SRConf< T >::c0(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::rank(), and madness::SRConf< T >::vector_.
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::emul(), madness::SRConf< T >::normf(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::overlap(), and madness::SRConf< T >::reconstruct().
flat_vector() [2/2]
template<typename T> Tensor<T> madness::SRConf< T >::flat_vector (const unsigned int & idim) inline
return shallow copy of a slice of one of the vectors, flattened to (r,kVec)
References madness::SRConf< T >::c0(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::rank(), and madness::SRConf< T >::vector_.
general_transform()
template<typename T> template<typename Q > SRConf<TENSOR_RESULT_TYPE(T,Q) > madness::SRConf< T >::general_transform (const Tensor< Q > c[]) const inline private
result(i,j,k,...) <-- sum(i',j', k',...) t(i',j',k',...)  c(i',i) c(j',j) c(k',k) ...
The input dimensions of t must all be the same .
References c, madness::SRConf< T >::copy, madness::SRConf< T >::dim_eff(), madness::general_transform(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), madness::inner(), MADNESS_ASSERT, madness::print(), madness::SRConf< T >::ref_vector(), madness::TT_FULL, and madness::SRConf< T >::type().
get_configs()
template<typename T> const SRConf madness::SRConf< T >::get_configs (const int & start, const int & end) const inline
return some of the terms of the SRConf (start,..,end), inclusively shallow copy
References madness::_(), madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::SRConf< T >::get_k(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, MADNESS_EXCEPTION, madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::SRConf< T >::s_, madness::SRConf< T >::type(), and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::divide_and_conquer_reduce().
get_k()
template<typename T> unsigned int madness::SRConf< T >::get_k () const inline
return the number of physical matrix elements per dimension
References madness::SRConf< T >::maxk_.
Referenced by madness::SRConf< T >::copy_slice(), madness::SRConf< T >::emul(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::kVec(), madness::SRConf< T >::make_structure(), and madness::SRConf< T >::reconstruct().
has_data()
template<typename T> bool madness::SRConf< T >::has_data () const inline
does this have any data?
References madness::SRConf< T >::rank(), madness::SRConf< T >::tensortype_, madness::TT_FULL, and madness::SRConf< T >::vector_.
Referenced by madness::SRConf< T >::has_no_data(), and madness::SRConf< T >::reserve().
has_no_data()
template<typename T> bool madness::SRConf< T >::has_no_data () const inline
does this have any data?
References madness::SRConf< T >::has_data().
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::append(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::divide_and_conquer_reduce(), madness::SRConf< T >::general_transform(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::normf(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::overlap(), madness::SRConf< T >::svd_normf(), madness::SRConf< T >::transform(), madness::SRConf< T >::transform_dir(), and madness::SRConf< T >::undo_structure().
has_structure()
template<typename T> bool madness::SRConf< T >::has_structure () const inline
return if this has a tensor structure (has not been flattened)
References madness::SRConf< T >::dim(), madness::SRConf< T >::get_k(), madness::SRConf< T >::has_no_data(), madness::TT_FULL, madness::SRConf< T >::type(), and madness::SRConf< T >::vector_.
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::append(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::divide_and_conquer_reduce(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::general_transform(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::normalize(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::reserve(), madness::SRConf< T >::serialize(), madness::SRConf< T >::SRConf(), madness::SRConf< T >::transform(), and madness::SRConf< T >::transform_dir().
inplace_add()
template<typename T> void madness::SRConf< T >::inplace_add (const SRConf< T > & rhs2, std::vector< Slice > lhs_s, std::vector< Slice > rhs_s, const double alpha, const double beta) inline protected
alpha * this(lhs_s) + beta * rhs(rhs_s)
bounds checking should have been performed by caller s denotes where in lhs the new contribution from rhs will be inserted
References alpha, beta, madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::get_k(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, MADNESS_EXCEPTION, madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::rank(), madness::SRConf< T >::rank_, madness::SRConf< T >::ref_vector(), madness::SRConf< T >::reserve(), madness::SRConf< T >::scale(), madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
is_flat()
template<typename T> bool madness::SRConf< T >::is_flat () const inline private
return if this has only one additional dimension (apart from rank)
References madness::SRConf< T >::vector_.
kVec()
template<typename T> long madness::SRConf< T >::kVec () const inline
return the length of the vector (dim_pv*maxk)
References madness::SRConf< T >::dim_per_vector(), and madness::SRConf< T >::get_k().
Referenced by madness::SRConf< T >::check_right_orthonormality(), madness::SRConf< T >::emul(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::nCoeff(), madness::SRConf< T >::operator=(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::reserve(), madness::SRConf< T >::SRConf(), and madness::SRConf< T >::undo_structure().
make_slices()
template<typename T> void madness::SRConf< T >::make_slices () inline protected
redo the Slices for getting direct access to the configurations
References madness::_(), madness::SRConf< T >::has_no_data(), MADNESS_EXCEPTION, madness::print(), madness::SRConf< T >::rank(), madness::SRConf< T >::s_, TENSOR_MAXDIM, madness::TT_FULL, madness::SRConf< T >::type(), and madness::SRConf< T >::vector_.
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::append(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::serialize(), madness::SRConf< T >::SRConf(), and madness::SRConf< T >::undo_structure().
make_structure()
template<typename T> void madness::SRConf< T >::make_structure (bool force = false) inline protected
References madness::SRConf< T >::dim_eff(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::get_k(), madness::SRConf< T >::has_no_data(), k, MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::emul(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::reserve(), and madness::SRConf< T >::SRConf().
max_sigma()
template<typename T> static int madness::SRConf< T >::max_sigma (const double & thresh, const int & rank, const Tensor< double > & w) inline static
return the index of the last singular vector/value to meet the threshold (returns -1 if all meet threshold, i.e. || A ||_2 < threshold) given a matrix A in SVD form, truncate the singular values such that the accuracy threshold is still met.
Parameters
[in] thresh the threshold eps: || A - A(truncated) || < eps
[in] rank the number of singular values in w
[in] w the weights/singular values of A
Returns
i the index of s_max to contribute: w(Slice(0,i)); i.e. inclusive!
References madness::SRConf< T >::rank(), residual(), and thresh.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply2(), madness::TensorTrain< T >::decompose(), madness::SeparatedConvolution< T, NDIM >::estimate_costs(), madness::ortho3(), madness::rank_revealing_decompose(), madness::TensorTrain< T >::splitdim(), and madness::TensorTrain< T >::truncate().
nCoeff()
template<typename T> unsigned int madness::SRConf< T >::nCoeff () const inline private
return the number of coefficients
References madness::SRConf< T >::dim_eff(), madness::SRConf< T >::kVec(), madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::TT_FULL, and madness::SRConf< T >::type().
normalize()
template<typename T> void madness::SRConf< T >::normalize () inline private
normalize the vectors (tested)
References madness::_(), madness::SRConf< T >::dim_eff(), madness::SRConf< T >::dim_per_vector(), e(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::detail::norm(), madness::SRConf< T >::normf(), madness::SRConf< T >::rank(), madness::SRConf< T >::scale(), madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::divide_and_conquer_reduce(), madness::SRConf< T >::emul(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::operator=(), and madness::SRConf< T >::orthonormalize().
normf()
template<typename T> TensorTypeData<T>::float_scalar_type madness::SRConf< T >::normf () const inline private
calculate the Frobenius norm
References std::abs(), madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::Tensor< T >::emul(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::has_no_data(), madness::inner_result(), MADNESS_ASSERT, madness::outer(), madness::SRConf< T >::overlap(), madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::Tensor< T >::sum(), madness::TT_FULL, madness::SRConf< T >::type(), madness::vec(), and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::normalize().
operator=() [1/2]
template<typename T> SRConf& madness::SRConf< T >::operator= (const SRConf< T > & rhs) inline
assignment operator (tested), shallow copy of vectors
References madness::SRConf< T >::dim_, madness::SRConf< T >::dim_eff(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::make_structure(), madness::SRConf< T >::maxk_, madness::SRConf< T >::rank(), madness::SRConf< T >::rank_, madness::SRConf< T >::ref_vector(), madness::SRConf< T >::s_, madness::SRConf< T >::tensortype_, madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
operator=() [2/2]
template<typename T> SRConf& madness::SRConf< T >::operator= (const T & number) inline
assign a number to this;
References madness::SRConf< T >::kVec(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::normalize(), madness::SRConf< T >::rank_, madness::TT_2D, madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
orthonormalize()
template<typename T> void madness::SRConf< T >::orthonormalize (const double & thresh) inline
orthonormalize this
References madness::SRConf< T >::flat_vector(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::normalize(), madness::ortho3(), madness::SRConf< T >::rank(), madness::SRConf< T >::rank_, madness::swap(), thresh, madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::vector_, madness::wall_time(), and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::divide_and_conquer_reduce().
overlap() [1/2]
template<typename T> template<typename Q > std::enable_if<(TensorTypeData<T>::iscomplex or TensorTypeData<Q>::iscomplex), TENSOR_RESULT_TYPE(T,Q)>::type friend madness::SRConf< T >::overlap (const SRConf< T > & rhs, const SRConf< Q > & lhs) inline private
References MADNESS_EXCEPTION.
Referenced by madness::SRConf< T >::normf(), and madness::SRConf< T >::overlap().
overlap() [2/2]
template<typename T> template<typename Q > std::enable_if<!(TensorTypeData<T>::iscomplex or TensorTypeData<Q>::iscomplex) , TENSOR_RESULT_TYPE(T,Q)>::type friend madness::SRConf< T >::overlap (const SRConf< T > & rhs, const SRConf< Q > & lhs) inline private
calculate the Frobenius inner product (tested)
References madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::Tensor< T >::emul(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::has_no_data(), madness::inner_result(), MADNESS_ASSERT, madness::outer(), madness::SRConf< T >::overlap(), madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::Tensor< T >::sum(), madness::TENSOR_RESULT_TYPE(), madness::TT_FULL, madness::SRConf< T >::type(), and madness::SRConf< T >::weights_.
rank()
template<typename T> long madness::SRConf< T >::rank () const inline
return the logicalrank
References madness::SRConf< T >::rank_.
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::check_right_orthonormality(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::divide_and_conquer_reduce(), madness::SRConf< T >::emul(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::has_data(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::make_slices(), madness::SRConf< T >::max_sigma(), madness::SRConf< T >::nCoeff(), madness::SRConf< T >::normalize(), madness::SRConf< T >::normf(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::overlap(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::reserve(), and madness::SRConf< T >::svd_normf().
real_size()
template<typename T> size_t madness::SRConf< T >::real_size () const inline private
return the real size of this
References madness::SRConf< T >::s_, madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
reconstruct()
template<typename T> Tensor<T> madness::SRConf< T >::reconstruct () const inline
reconstruct this to return a full tensor
References madness::SRConf< T >::copy, d(), madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::get_k(), madness::inner_result(), k, madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::print(), madness::SRConf< T >::rank(), madness::SRConf< T >::ref_vector(), madness::Tensor< T >::reshape(), madness::Tensor< T >::sum(), TENSOR_MAXDIM, madness::TT_FULL, madness::SRConf< T >::type(), madness::SRConf< T >::weights(), and madness::SRConf< T >::weights_.
ref_vector() [1/2]
template<typename T> Tensor<T>& madness::SRConf< T >::ref_vector (const unsigned int & idim) inline
return reference to one of the vectors F
References madness::SRConf< T >::vector_.
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::check_right_orthonormality(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::general_transform(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::nCoeff(), madness::SRConf< T >::normf(), madness::SRConf< T >::operator=(), madness::SRConf< T >::overlap(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::transform(), and madness::SRConf< T >::transform_dir().
ref_vector() [2/2]
template<typename T> const Tensor<T>& madness::SRConf< T >::ref_vector (const unsigned int & idim) const inline
return reference to one of the vectors F
References madness::SRConf< T >::vector_.
reserve()
template<typename T> void madness::SRConf< T >::reserve (long r) inline private
reserve enough space to hold at least r configurations
References madness::SRConf< T >::c0(), madness::SRConf< T >::dim(), madness::SRConf< T >::dim_eff(), madness::SRConf< T >::has_data(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::make_structure(), madness::SRConf< T >::rank(), madness::swap(), madness::SRConf< T >::undo_structure(), madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::append(), and madness::SRConf< T >::inplace_add().
scale() [1/2]
template<typename T> void madness::SRConf< T >::scale (const double & fac) inline private
scale this by a number
References madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::inplace_add(), and madness::SRConf< T >::normalize().
scale() [2/2]
template<typename T> void madness::SRConf< T >::scale (const double_complex & fac) inline private
References MADNESS_EXCEPTION.
serialize()
template<typename T> template<typename Archive > void madness::SRConf< T >::serialize (Archive & ar) inline
References madness::SRConf< T >::dim_, madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::SRConf< T >::maxk_, madness::SRConf< T >::rank_, madness::SRConf< T >::tensortype_, madness::SRConf< T >::vector_, and madness::SRConf< T >::weights_.
svd_normf()
template<typename T> TensorTypeData<T>::float_scalar_type madness::SRConf< T >::svd_normf () const inline private
calculate the Frobenius norm, if this is in SVD form
References madness::SRConf< T >::has_no_data(), MADNESS_ASSERT, madness::SRConf< T >::rank(), madness::TT_2D, madness::SRConf< T >::type(), and madness::SRConf< T >::weights_.
transform()
template<typename T> SRConf<T> madness::SRConf< T >::transform (const Tensor< T > & c) const inline private
result(i,j,k,...) <-- sum(i',j', k',...) t(i',j',k',...)  c(i',i) c(j',j) c(k',k) ...
The input dimensions of t must all be the same .
References c, madness::SRConf< T >::copy, madness::SRConf< T >::dim_eff(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), madness::inner(), MADNESS_ASSERT, madness::SRConf< T >::ref_vector(), madness::transform(), madness::TT_FULL, and madness::SRConf< T >::type().
transform_dir()
template<typename T> SRConf<T> madness::SRConf< T >::transform_dir (const Tensor< T > & c, const int & axis) const inline private
References axis, c, madness::SRConf< T >::copy, madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::has_structure(), MADNESS_ASSERT, madness::SRConf< T >::ref_vector(), madness::transform_dir(), madness::TT_FULL, and madness::SRConf< T >::type().
type()
template<typename T> TensorType madness::SRConf< T >::type () const inline
return the tensor type
References madness::SRConf< T >::tensortype_.
Referenced by madness::SRConf< T >::check_right_orthonormality(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::general_transform(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::nCoeff(), madness::SRConf< T >::normalize(), madness::SRConf< T >::normf(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::overlap(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::svd_normf(), madness::SRConf< T >::transform(), madness::SRConf< T >::transform_dir(), and madness::SRConf< T >::undo_structure().
undo_structure()
template<typename T> void madness::SRConf< T >::undo_structure (bool force = false) inline protected
References madness::SRConf< T >::dim_eff(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::has_no_data(), madness::SRConf< T >::kVec(), MADNESS_ASSERT, madness::SRConf< T >::make_slices(), madness::TT_FULL, madness::SRConf< T >::type(), and madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::add_SVD(), and madness::SRConf< T >::reserve().
weights()
template<typename T> double madness::SRConf< T >::weights (const unsigned int & i) const inline
return the weight
References madness::SRConf< T >::weights_.
Referenced by madness::SRConf< T >::copy_slice(), madness::SRConf< T >::reconstruct(), and madness::SRConf< T >::SRConf().
Friends And Related Function Documentation
compatible
template<typename T> bool compatible (const SRConf< T > & lhs, const SRConf< T > & rhs) friend
check compatibility
copy
template<typename T> SRConf<T> copy (const SRConf< T > & rhs) friend
deep copy of rhs, shrink
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::general_transform(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::transform(), and madness::SRConf< T >::transform_dir().
GenTensor< T >
template<typename T> friend class GenTensor< T > friend
LowRankTensor< T >
template<typename T> friend class LowRankTensor< T > friend
SliceLowRankTensor< T >
template<typename T> friend class SliceLowRankTensor< T > friend
Member Data Documentation
check_orthonormality
template<typename T> const bool madness::SRConf< T >::check_orthonormality =false static
check orthonormality at low rank additions
Referenced by madness::SRConf< T >::add_SVD().
dim_
template<typename T> unsigned int madness::SRConf< T >::dim_
the number of dimensions (the order of the tensor)
Referenced by madness::SRConf< T >::dim(), madness::operator<<(), madness::SRConf< T >::operator=(), and madness::SRConf< T >::serialize().
maxk_
template<typename T> unsigned int madness::SRConf< T >::maxk_
the number of underlying basis functions the dimensions of vector_ will be vector_(rank,maxk), vector_(rank,maxk,maxk), etc
Referenced by madness::SRConf< T >::get_k(), madness::SRConf< T >::operator=(), and madness::SRConf< T >::serialize().
rank_
template<typename T> long madness::SRConf< T >::rank_
what is the rank of this
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::append(), madness::SRConf< T >::emul(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::rank(), madness::SRConf< T >::serialize(), and madness::SRConf< T >::SRConf().
s_
template<typename T> std::vector<Slice> madness::SRConf< T >::s_
Slice containing the actual data in each vector, ignoring "empty" configurations; will maintain contiguity of the data.
Referenced by madness::SRConf< T >::c0(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::make_slices(), madness::SRConf< T >::operator=(), and madness::SRConf< T >::real_size().
tensortype_
template<typename T> TensorType madness::SRConf< T >::tensortype_
how will this be represented
Referenced by madness::SRConf< T >::has_data(), madness::SRConf< T >::operator=(), madness::SRConf< T >::serialize(), and madness::SRConf< T >::type().
vector_
template<typename T> std::vector<tensorT> madness::SRConf< T >::vector_
for each (physical) dimension one Tensor of (logical) dimension (r,k) for vectors or (r,kprime,k) for operators
Referenced by madness::SRConf< T >::append(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::emul(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::flat_vector(), madness::SRConf< T >::has_data(), madness::SRConf< T >::has_structure(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::is_flat(), madness::SRConf< T >::make_slices(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::normalize(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::real_size(), madness::SRConf< T >::ref_vector(), madness::SRConf< T >::reserve(), madness::SRConf< T >::serialize(), and madness::SRConf< T >::SRConf().
weights_
template<typename T> Tensor< typename Tensor<T>::scalar_type > madness::SRConf< T >::weights_
for each configuration the weight; length should be r
Referenced by madness::SRConf< T >::add_SVD(), madness::SRConf< T >::append(), madness::SRConf< T >::copy_slice(), madness::SRConf< T >::emul(), madness::SRConf< T >::fillWithRandom(), madness::SRConf< T >::get_configs(), madness::SRConf< T >::inplace_add(), madness::SRConf< T >::make_structure(), madness::SRConf< T >::normalize(), madness::SRConf< T >::normf(), madness::SRConf< T >::operator=(), madness::SRConf< T >::orthonormalize(), madness::SRConf< T >::overlap(), madness::SRConf< T >::real_size(), madness::SRConf< T >::reconstruct(), madness::SRConf< T >::reserve(), madness::SRConf< T >::scale(), madness::SRConf< T >::serialize(), madness::SRConf< T >::SRConf(), madness::SRConf< T >::svd_normf(), madness::SRConf< T >::undo_structure(), and madness::SRConf< T >::weights().
The documentation for this class was generated from the following file:
srconf.h