MADNESS: ContractedGaussianShell Class Reference
ContractedGaussianShell Class Reference
Represents a single shell of contracted, Cartesian, Gaussian primitives.
#include <molecularbasis.h>
Public Member Functions
ContractedGaussianShell ()
ContractedGaussianShell (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, bool donorm=true)
int angular_momentum () const
Returns the shell angular momentum.
double * eval (double rsq, double x, double y, double z, double *bf) const
Evaluates the entire shell returning the incremented result pointer.
double eval_radial (double rsq) const
Evaluates the radial part of the contracted function.
const std::vector< double > & get_coeff () const
Returns a const reference to the coefficients.
const char * get_desc (int ibf) const
Returns a string description of the basis function type.
const std::vector< double > & get_expnt () const
Returns a const reference to the exponents.
int nbf () const
Returns the number of basis functions in the shell.
int nprim () const
Returns the number of primitives in the contraction.
double rangesq () const
Returns square of the distance beyond which function is less than 1e-8.
template<typename Archive >
void serialize (Archive &ar)
Private Member Functions
void normalize ()
Private Attributes
std::vector< double > coeff
std::vector< double > expnt
int numbf
Number of basis functions in shell (type+1)*(type+2)/2.
double rsqmax
int type
Angular momentum = 0, 1, 2, ...
Detailed Description
Represents a single shell of contracted, Cartesian, Gaussian primitives.
Constructor & Destructor Documentation
ContractedGaussianShell() [1/2]
ContractedGaussianShell::ContractedGaussianShell () inline
ContractedGaussianShell() [2/2]
ContractedGaussianShell::ContractedGaussianShell (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, bool donorm = true) inline
References madness::ContractedGaussianShell::expnt, madness::ContractedGaussianShell::normalize(), and madness::ContractedGaussianShell::rsqmax.
Member Function Documentation
angular_momentum()
int ContractedGaussianShell::angular_momentum () const inline
Returns the shell angular momentum.
References madness::ContractedGaussianShell::type.
eval()
double* ContractedGaussianShell::eval (double rsq, double x, double y, double z, double * bf) const inline
Evaluates the entire shell returning the incremented result pointer.
References e(), madness::ContractedGaussianShell::eval_radial(), madness::ContractedGaussianShell::numbf, R, and madness::ContractedGaussianShell::type.
eval_radial()
double ContractedGaussianShell::eval_radial (double rsq) const inline
Evaluates the radial part of the contracted function.
References madness::ContractedGaussianShell::coeff, madness::ContractedGaussianShell::expnt, madness::ContractedGaussianShell::rsqmax, and madness::sum().
get_coeff()
const std::vector<double>& ContractedGaussianShell::get_coeff () const inline
Returns a const reference to the coefficients.
References madness::ContractedGaussianShell::coeff.
get_desc()
const char* ContractedGaussianShell::get_desc (int ibf) const inline
Returns a string description of the basis function type.
References MADNESS_ASSERT, and madness::ContractedGaussianShell::type.
get_expnt()
const std::vector<double>& ContractedGaussianShell::get_expnt () const inline
Returns a const reference to the exponents.
References madness::ContractedGaussianShell::expnt.
nbf()
int ContractedGaussianShell::nbf () const inline
Returns the number of basis functions in the shell.
References madness::ContractedGaussianShell::numbf.
normalize()
void ContractedGaussianShell::normalize () inline private
References madness::ContractedGaussianShell::coeff, E0(), madness::ContractedGaussianShell::expnt, madness::f, np, madness::constants::pi, pow(), madness::sum(), and madness::ContractedGaussianShell::type.
nprim()
int ContractedGaussianShell::nprim () const inline
Returns the number of primitives in the contraction.
References madness::ContractedGaussianShell::coeff.
rangesq()
double ContractedGaussianShell::rangesq () const inline
Returns square of the distance beyond which function is less than 1e-8.
References madness::ContractedGaussianShell::rsqmax.
serialize()
template<typename Archive > void ContractedGaussianShell::serialize (Archive & ar) inline
References madness::ContractedGaussianShell::coeff, madness::ContractedGaussianShell::expnt, madness::ContractedGaussianShell::numbf, madness::ContractedGaussianShell::rsqmax, and madness::ContractedGaussianShell::type.
Member Data Documentation
coeff
std::vector<double> ContractedGaussianShell::coeff private
expnt
std::vector<double> ContractedGaussianShell::expnt private
numbf
int ContractedGaussianShell::numbf private
Number of basis functions in shell (type+1)*(type+2)/2.
rsqmax
double ContractedGaussianShell::rsqmax private
type
int ContractedGaussianShell::type private
Angular momentum = 0, 1, 2, ...
The documentation for this class was generated from the following file:
hf/molecularbasis.h