MADNESS: SteepestDescent Class Reference
SteepestDescent Class Reference
Optimization via steepest descent.
Public Member Functions
SteepestDescent (const std::shared_ptr< OptimizationTargetInterface > &target, double tol=1e-6, double value_precision=1e-12, double gradient_precision=1e-12)
bool converged () const
double gradient_norm () const
bool optimize (Tensor< double > &x)
double value () const
Public Member Functions inherited from madness::OptimizerInterface
virtual ~OptimizerInterface ()
Private Attributes
double f
double gnorm
const double gradient_precision
std::shared_ptr< OptimizationTargetInterface > target
const double tol
const double value_precision
Detailed Description
Optimization via steepest descent.
Constructor & Destructor Documentation
SteepestDescent()
SteepestDescent::SteepestDescent (const std::shared_ptr< OptimizationTargetInterface > & target, double tol = 1e-6, double value_precision = 1e-12, double gradient_precision = 1e-12) inline
References target().
Member Function Documentation
converged()
bool SteepestDescent::converged () const inline virtual
Implements madness::OptimizerInterface.
gradient_norm()
double SteepestDescent::gradient_norm () const inline virtual
Implements madness::OptimizerInterface.
optimize()
bool SteepestDescent::optimize (Tensor< double > & x) inline virtual
Implements madness::OptimizerInterface.
References madness::f, madness::g, madness::Tensor< T >::gaxpy(), madness::print(), and target().
value()
double SteepestDescent::value () const inline virtual
Implements madness::OptimizerInterface.
References madness::f.
Member Data Documentation
f
double SteepestDescent::f private
gnorm
double SteepestDescent::gnorm private
gradient_precision
const double SteepestDescent::gradient_precision private
target
std::shared_ptr<OptimizationTargetInterface> SteepestDescent::target private
tol
const double SteepestDescent::tol private
value_precision
const double SteepestDescent::value_precision private
The documentation for this class was generated from the following file:
kain.cc