MADNESS: SafeMPI::Exception Class Reference
SafeMPI::Exception Class Reference
SafeMPI exception object.
#include <safempi.h>
Public Member Functions
Exception (const int mpi_error) throw ()
Exception (const int mpi_error, const int nstatuses, const int *indices, MPI_Status *const statuses) noexcept
Exception (const Exception &other) throw ()
virtual ~Exception () throw ()
bool can_elaborate () const noexcept
const char * elaborate () const noexcept
Exception & operator= (const Exception &other)
virtual const char * what () const throw ()
Private Attributes
char mpi_error_string_ [MPI_MAX_ERROR_STRING]
std::string mpi_statuses_error_string_
Friends
std::ostream & operator<< (std::ostream &os, const Exception &e)
Detailed Description
SafeMPI exception object.
This exception is thrown whenever an MPI error occurs.
Constructor & Destructor Documentation
Exception() [1/3]
SafeMPI::Exception::Exception (const int mpi_error) throw () inline
References MPI_Error_string(), mpi_error_string_, MPI_MAX_ERROR_STRING, MPI_SUCCESS, and strncpy().
Exception() [2/3]
SafeMPI::Exception::Exception (const int mpi_error, const int nstatuses, const int * indices, MPI_Status *const statuses) inline noexcept
References MPI_ERR_IN_STATUS, MPI_Error_string(), mpi_error_string_, MPI_MAX_ERROR_STRING, mpi_statuses_error_string_, MPI_SUCCESS, and strncpy().
Exception() [3/3]
SafeMPI::Exception::Exception (const Exception & other) throw () inline
References mpi_error_string_, MPI_MAX_ERROR_STRING, mpi_statuses_error_string_, and strncpy().
~Exception()
virtual SafeMPI::Exception::~Exception () throw () inline virtual
Member Function Documentation
can_elaborate()
bool SafeMPI::Exception::can_elaborate () const inline noexcept
References mpi_statuses_error_string_.
elaborate()
const char* SafeMPI::Exception::elaborate () const inline noexcept
References mpi_statuses_error_string_.
operator=()
Exception& SafeMPI::Exception::operator= (const Exception & other) inline
References mpi_error_string_, MPI_MAX_ERROR_STRING, mpi_statuses_error_string_, and strncpy().
what()
virtual const char* SafeMPI::Exception::what () const throw () inline virtual
References mpi_error_string_.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Exception & e) friend
Member Data Documentation
mpi_error_string_
char SafeMPI::Exception::mpi_error_string_[MPI_MAX_ERROR_STRING] private
Referenced by Exception(), operator=(), and what().
mpi_statuses_error_string_
std::string SafeMPI::Exception::mpi_statuses_error_string_ private
Referenced by can_elaborate(), elaborate(), Exception(), and operator=().
The documentation for this class was generated from the following file:
safempi.h