MADNESS: madness::WorldAmInterface Class Reference
madness::WorldAmInterface Class Reference
Implements AM interface.
#include <worldam.h>
Classes
class SendReq
Public Member Functions
WorldAmInterface (World &world)
virtual ~WorldAmInterface ()
void fence ()
Currently a noop.
int free_managed_buffers ()
Frees as many send buffers as possible, returning the number that are free.
void send (ProcessID dest, am_handlerT op, const AmArg *arg, const int attr=RMI::ATTR_ORDERED)
Sends a managed non-blocking active message.
Static Private Member Functions
static void handler (void *buf, std::size_t nbyte)
This handles all incoming RMI messages for all instances.
Private Attributes
volatile int cur_msg
Index of next buffer to attempt to use.
std::vector< int > map_to_comm_world
Maps rank in current MPI communicator to SafeMPI::COMM_WORLD.
const int nproc
volatile unsigned long nrecv
Counts no. of AM received for purpose of termination detection.
int nsend
Max no. of pending sends.
volatile unsigned long nsent
Counts no. of AM sent for purpose of termination detection.
const ProcessID rank
std::unique_ptr< SendReq []> send_req
Send requests and managed buffers.
unsigned long worldid
The world which contains this instance of WorldAmInterface.
Static Private Attributes
static const int DEFAULT_NSEND = 128
Friends
class World
class WorldGopInterface
Additional Inherited Members
Private Member Functions inherited from madness::Mutex
Mutex (int junk=0)
Make and initialize a mutex ... initial state is unlocked.
virtual ~Mutex ()
void lock () const
Acquire the mutex waiting if necessary.
pthread_mutex_t * ptr () const
Return a pointer to the pthread mutex for use by a condition variable.
bool try_lock () const
Try to acquire the mutex ... return true on success, false on failure.
void unlock () const
Free a mutex owned by this thread.
Detailed Description
Implements AM interface.
Constructor & Destructor Documentation
WorldAmInterface()
madness::WorldAmInterface::WorldAmInterface (World & world)
References madness::WorldMpiInterface::comm(), SafeMPI::COMM_WORLD, DEFAULT_NSEND, fred(), SafeMPI::Intracomm::Get_group(), madness::Mutex::lock(), map_to_comm_world, madness::World::mpi, nproc, nsend, send_req, SafeMPI::Group::Translate_ranks(), and madness::Mutex::unlock().
~WorldAmInterface()
madness::WorldAmInterface::~WorldAmInterface () virtual
References free_managed_buffers(), SafeMPI::Is_finalized(), madness::myusleep(), and nsend.
Member Function Documentation
fence()
void madness::WorldAmInterface::fence () inline
Currently a noop.
free_managed_buffers()
int madness::WorldAmInterface::free_managed_buffers () inline
Frees as many send buffers as possible, returning the number that are free.
References nsend, send_req, and madness::Mutex::try_lock().
Referenced by madness::WorldGopInterface::fence(), and ~WorldAmInterface().
handler()
static void madness::WorldAmInterface::handler (void * buf, std::size_t nbyte) inline static private
This handles all incoming RMI messages for all instances.
References madness::World::am, madness::arg(), madness::func(), MADNESS_ASSERT, and nrecv.
Referenced by send().
send()
void madness::WorldAmInterface::send (ProcessID dest, am_handlerT op, const AmArg * arg, const int attr = RMI::ATTR_ORDERED) inline
Sends a managed non-blocking active message.
References madness::arg(), madness::AmArg::clear_flags(), cur_msg, madness::RMI::get_this_thread_is_server(), handler(), madness::RMI::isend(), madness::Mutex::lock(), MADNESS_ASSERT, map_to_comm_world, madness::myusleep(), nsend, nsent, op(), rank, madness::RMI::send_req, send_req, madness::AmArg::set_func(), madness::AmArg::set_src(), madness::AmArg::set_worldid(), madness::Mutex::try_lock(), madness::Mutex::unlock(), and worldid.
Referenced by madness::WorldGopInterface::bcast_task(), madness::WorldGopInterface::group_bcast_task(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::reset(), madness::WorldObject< TestFutureForwarding >::send_am(), madness::WorldTaskQueue::send_task(), madness::WorldObject< TestFutureForwarding >::send_task(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::set(), and madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::set_handler().
Friends And Related Function Documentation
World
friend class World friend
WorldGopInterface
friend class WorldGopInterface friend
Member Data Documentation
cur_msg
volatile int madness::WorldAmInterface::cur_msg private
Index of next buffer to attempt to use.
Referenced by send().
DEFAULT_NSEND
const int madness::WorldAmInterface::DEFAULT_NSEND = 128 static private
Referenced by WorldAmInterface().
map_to_comm_world
std::vector<int> madness::WorldAmInterface::map_to_comm_world private
Maps rank in current MPI communicator to SafeMPI::COMM_WORLD.
Referenced by send(), and WorldAmInterface().
nproc
const int madness::WorldAmInterface::nproc private
Referenced by WorldAmInterface().
nrecv
volatile unsigned long madness::WorldAmInterface::nrecv private
Counts no. of AM received for purpose of termination detection.
Referenced by madness::WorldGopInterface::fence(), and handler().
nsend
int madness::WorldAmInterface::nsend private
Max no. of pending sends.
Referenced by free_managed_buffers(), send(), WorldAmInterface(), and ~WorldAmInterface().
nsent
volatile unsigned long madness::WorldAmInterface::nsent private
Counts no. of AM sent for purpose of termination detection.
Referenced by madness::WorldGopInterface::fence(), and send().
rank
const ProcessID madness::WorldAmInterface::rank private
Referenced by send().
send_req
std::unique_ptr<SendReq []> madness::WorldAmInterface::send_req private
Send requests and managed buffers.
Referenced by free_managed_buffers(), send(), and WorldAmInterface().
worldid
unsigned long madness::WorldAmInterface::worldid private
The world which contains this instance of WorldAmInterface.
Referenced by send(), and madness::World::World().
The documentation for this class was generated from the following files:
worldam.h
worldam.cc