MADNESS: AtomicBasisFunction Class Reference
AtomicBasisFunction Class Reference
Used to represent one basis function from a shell on a specific center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell &shell, int ibf)
AtomicBasisFunction (const AtomicBasisFunction &aofunc)
void get_coords (double &x, double &y, double &z) const
const char * get_desc () const
int get_index () const
const ContractedGaussianShell & get_shell () const
double operator() (double x, double y, double z) const
void print_me (std::ostream &s) const
double rangesq () const
Private Attributes
const int ibf
const int nbf
const ContractedGaussianShell & shell
const double xx
const double yy
const double zz
Detailed Description
Used to represent one basis function from a shell on a specific center.
Constructor & Destructor Documentation
AtomicBasisFunction() [1/2]
AtomicBasisFunction::AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell & shell, int ibf) inline
AtomicBasisFunction() [2/2]
AtomicBasisFunction::AtomicBasisFunction (const AtomicBasisFunction & aofunc) inline
Member Function Documentation
get_coords()
void AtomicBasisFunction::get_coords (double & x, double & y, double & z) const inline
References madness::AtomicBasisFunction::xx, madness::AtomicBasisFunction::yy, and madness::AtomicBasisFunction::zz.
get_desc()
const char* AtomicBasisFunction::get_desc () const inline
References madness::ContractedGaussianShell::get_desc(), madness::AtomicBasisFunction::ibf, and madness::AtomicBasisFunction::shell.
get_index()
int AtomicBasisFunction::get_index () const inline
References madness::AtomicBasisFunction::ibf.
get_shell()
const ContractedGaussianShell& AtomicBasisFunction::get_shell () const inline
References madness::AtomicBasisFunction::shell.
operator()()
double AtomicBasisFunction::operator() (double x, double y, double z) const inline
References madness::ContractedGaussianShell::eval(), madness::AtomicBasisFunction::ibf, madness::AtomicBasisFunction::nbf, madness::AtomicBasisFunction::shell, madness::AtomicBasisFunction::xx, madness::AtomicBasisFunction::yy, and madness::AtomicBasisFunction::zz.
print_me()
void AtomicBasisFunction::print_me (std::ostream & s) const inline
References madness::AtomicBasisFunction::ibf, madness::AtomicBasisFunction::nbf, madness::AtomicBasisFunction::shell, madness::AtomicBasisFunction::xx, madness::AtomicBasisFunction::yy, and madness::AtomicBasisFunction::zz.
rangesq()
double AtomicBasisFunction::rangesq () const inline
References madness::ContractedGaussianShell::rangesq(), and madness::AtomicBasisFunction::shell.
Member Data Documentation
ibf
const int AtomicBasisFunction::ibf private
nbf
const int AtomicBasisFunction::nbf private
shell
const ContractedGaussianShell& AtomicBasisFunction::shell private
xx
const double AtomicBasisFunction::xx private
yy
const double AtomicBasisFunction::yy private
zz
const double AtomicBasisFunction::zz private
The documentation for this class was generated from the following file:
hf/molecularbasis.h