MADNESS: KeyChildIterator Class Reference
KeyChildIterator Class Reference
Public Member Functions
KeyChildIterator (const Key &parent)
const Key & key ()
operator bool () const
KeyChildIterator & operator++ ()
Private Types
typedef unsigned long ulong
Private Attributes
Key child
ulong i
ulong j
ulong k
Key parent
Member Typedef Documentation
ulong
typedef unsigned long KeyChildIterator::ulong private
Constructor & Destructor Documentation
KeyChildIterator()
KeyChildIterator::KeyChildIterator (const Key & parent) inline
Member Function Documentation
key()
const Key& KeyChildIterator::key () inline
Referenced by madness::Key< OPDIM >::is_child_of(), madness::Key< OPDIM >::is_neighbor_of(), madness::Key< OPDIM >::is_parent_of(), and madness::operator<<().
operator bool()
KeyChildIterator::operator bool () const inline
References k.
operator++()
KeyChildIterator& KeyChildIterator::operator++ () inline
References k, and madness::Key< NDIM >::n.
Member Data Documentation
child
Key KeyChildIterator::child private
i
ulong KeyChildIterator::i private
Referenced by madness::Key< OPDIM >::break_apart(), madness::Key< OPDIM >::is_farther_out_than(), madness::Key< OPDIM >::is_neighbor_of(), madness::Key< OPDIM >::merge_with(), madness::Key< OPDIM >::operator<(), madness::Key< OPDIM >::operator==(), madness::Key< OPDIM >::parent(), and madness::Key< OPDIM >::thisKeyContains().
j
ulong KeyChildIterator::j private
k
ulong KeyChildIterator::k private
parent
Key KeyChildIterator::parent private
The documentation for this class was generated from the following file:
test_tree.cc