MADNESS: madness::NuclearCorrelationFactor::U1X_functor Class Reference
madness::NuclearCorrelationFactor::U1X_functor Class Reference
compute the derivative of U1 wrt the displacement of atom A, coord axis
#include <correlationfactor.h>
Public Member Functions
U1X_functor (const NuclearCorrelationFactor *ncf, const Atom &atom1, const int U1axis, const int daxis)
direction of the derivative operator
U1X_functor (const NuclearCorrelationFactor *ncf, const int iatom, const int U1axis, const int daxis)
double operator() (const coord_3d &xyz) const
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
FunctionFunctorInterface ()
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const=0
You should implement this to return f(x)
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
void set_length_scale (double lo)
adapt the special level to resolve the smallest length scale
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
Private Attributes
const int derivativeaxis
U1x/U1y/U1z potential?
const NuclearCorrelationFactor * ncf
const Atom & thisatom
const int U1axis
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
typedef double value_type
Public Attributes inherited from madness::FunctionFunctorInterface< double, 3 >
Level special_level_
Detailed Description
compute the derivative of U1 wrt the displacement of atom A, coord axis
Constructor & Destructor Documentation
U1X_functor() [1/2]
madness::NuclearCorrelationFactor::U1X_functor::U1X_functor (const NuclearCorrelationFactor * ncf, const Atom & atom1, const int U1axis, const int daxis) inline
direction of the derivative operator
References lo, madness::Atom::q, madness::FunctionFunctorInterface< double, 3 >::set_length_scale(), and thisatom.
U1X_functor() [2/2]
madness::NuclearCorrelationFactor::U1X_functor::U1X_functor (const NuclearCorrelationFactor * ncf, const int iatom, const int U1axis, const int daxis) inline
References lo, madness::Atom::q, madness::FunctionFunctorInterface< double, 3 >::set_length_scale(), and thisatom.
Member Function Documentation
operator()()
double madness::NuclearCorrelationFactor::U1X_functor::operator() (const coord_3d & xyz) const inline
References derivativeaxis, madness::NuclearCorrelationFactor::dsmoothed_unitvec(), madness::Atom::get_coords(), ncf, madness::Vector< T, N >::normf(), madness::Atom::q, madness::NuclearCorrelationFactor::smoothed_unitvec(), madness::NuclearCorrelationFactor::Sr_div_S(), madness::NuclearCorrelationFactor::Srr_div_S(), thisatom, U1axis, and Z.
special_points()
std::vector<coord_3d> madness::NuclearCorrelationFactor::U1X_functor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References c, thisatom, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Member Data Documentation
derivativeaxis
const int madness::NuclearCorrelationFactor::U1X_functor::derivativeaxis private
U1x/U1y/U1z potential?
Referenced by operator()().
ncf
const NuclearCorrelationFactor* madness::NuclearCorrelationFactor::U1X_functor::ncf private
Referenced by operator()().
thisatom
const Atom& madness::NuclearCorrelationFactor::U1X_functor::thisatom private
Referenced by operator()(), special_points(), and U1X_functor().
U1axis
const int madness::NuclearCorrelationFactor::U1X_functor::U1axis private
Referenced by operator()().
The documentation for this class was generated from the following file:
correlationfactor.h