MADNESS: madness::Nemo_complex_Parameters Class Reference
madness::Nemo_complex_Parameters Class Reference
#include <znemo.h>
Public Member Functions
Nemo_complex_Parameters (World &world)
ctor reading out the input file
std::vector< double > box () const
double explicit_B () const
std::vector< std::string > guess () const
std::vector< std::string > guess_functions () const
double physical_B () const
double potential_radius () const
int printlevel () const
void set_derived_values ()
double shift () const
bool use_v_vector () const
Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
T get (const std::string key) const
QCParameter & get_parameter (const std::string key)
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read (World &world, const std::string filename, const std::string tag)
read the parameters from file
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
ParameterContainerT parameters
bool print_debug =false
Constructor & Destructor Documentation
Nemo_complex_Parameters()
madness::Nemo_complex_Parameters::Nemo_complex_Parameters (World & world) inline
ctor reading out the input file
References madness::QCCalculationParametersBase::read().
Member Function Documentation
box()
std::vector<double> madness::Nemo_complex_Parameters::box () const inline
Referenced by madness::Znemo::recompute_factors_and_potentials().
explicit_B()
double madness::Nemo_complex_Parameters::explicit_B () const inline
Referenced by madness::Znemo::gradient(), madness::Znemo::read_real_guess(), madness::Znemo::recompute_factors_and_potentials(), and set_derived_values().
guess()
std::vector<std::string> madness::Nemo_complex_Parameters::guess () const inline
Referenced by madness::Znemo::custom_guess(), and madness::Znemo::get_initial_orbitals().
guess_functions()
std::vector<std::string> madness::Nemo_complex_Parameters::guess_functions () const inline
Referenced by madness::Znemo::get_initial_orbitals(), and madness::Znemo::read_explicit_guess_functions().
physical_B()
double madness::Nemo_complex_Parameters::physical_B () const inline
Referenced by madness::Znemo::compute_standard_gauge_shift(), madness::Znemo::hcore_guess(), madness::Znemo::iterate(), set_derived_values(), madness::Znemo::test_landau_wave_function(), and madness::Znemo::Znemo().
potential_radius()
double madness::Nemo_complex_Parameters::potential_radius () const inline
Referenced by set_derived_values().
printlevel()
int madness::Nemo_complex_Parameters::printlevel () const inline
Referenced by madness::Znemo::iterate(), and madness::Znemo::Znemo().
set_derived_values()
void madness::Nemo_complex_Parameters::set_derived_values () inline
References explicit_B(), madness::FunctionDefaults< NDIM >::get_thresh(), physical_B(), potential_radius(), madness::QCCalculationParametersBase::set_derived_value(), and thresh.
Referenced by madness::Znemo::Znemo().
shift()
double madness::Nemo_complex_Parameters::shift () const inline
Referenced by madness::Znemo::iterate().
use_v_vector()
bool madness::Nemo_complex_Parameters::use_v_vector () const inline
The documentation for this class was generated from the following file:
znemo.h