MADNESS: madness::ThreadBase Class Reference
madness::ThreadBase Class Reference abstract
MADNESS libraries » Parallel programming environment » Multi-threading » Threads
Simplified thread wrapper to hide pthread complexity.
#include <thread.h>
Public Member Functions
ThreadBase ()
Default constructor.
virtual ~ThreadBase ()
int cancel () const
Cancel this thread.
const pthread_t & get_id () const
Get the pthread id of this thread (if running).
int get_pool_thread_index () const
Get index of this thread in ThreadPool.
virtual void run ()=0
Function to be executed by the thread.
void start ()
Start the thread running.
Static Public Member Functions
static void exit ()
A thread can call this to terminate its execution.
static int num_hw_processors ()
Get number of actual hardware processors.
static void set_affinity (int logical_id, int ind=-1)
static void set_affinity_pattern (const bool bind[3], const int cpu[3])
Specify the affinity pattern or how to bind threads to CPUs.
static ThreadBase * this_thread ()
Private Member Functions
void set_pool_thread_index (int i)
Sets the index of this thread within the pool.
Static Private Member Functions
static void delete_thread_key ()
static void init_thread_key ()
static void * main (void *self)
Private Attributes
pthread_t id
int pool_num
Stores index of thread in pool or -1.
Static Private Attributes
static bool bind [3]
static int cpuhi [3]
static int cpulo [3]
static pthread_key_t thread_key
Thread id key.
Friends
class ThreadPool
Detailed Description
Simplified thread wrapper to hide pthread complexity.
If the thread is using any of the object state, you cannot delete the object until the thread has terminated.
The cleanest solution is to put the object on the heap and have the run method delete this at its end.
Constructor & Destructor Documentation
ThreadBase()
madness::ThreadBase::ThreadBase () inline
Default constructor.
Sets up the thread; however, start() must be invoked to actually begin the thread.
~ThreadBase()
virtual madness::ThreadBase::~ThreadBase () inline virtual
Member Function Documentation
cancel()
int madness::ThreadBase::cancel () const inline
Cancel this thread.
References get_id().
delete_thread_key()
static void madness::ThreadBase::delete_thread_key () inline static private
Todo:
Brief description needed.
References thread_key.
Referenced by madness::ThreadPool::end().
exit()
static void madness::ThreadBase::exit () inline static
A thread can call this to terminate its execution.
get_id()
const pthread_t& madness::ThreadBase::get_id () const inline
Get the pthread id of this thread (if running).
References id.
Referenced by cancel().
get_pool_thread_index()
int madness::ThreadBase::get_pool_thread_index () const inline
Get index of this thread in ThreadPool.
Returns
(0,...,nthread-1) or -1 if not in the ThreadPool.
References pool_num.
Referenced by madness::profiling::TaskEventList::print_events(), and madness::ThreadPool::thread_main().
init_thread_key()
static void madness::ThreadBase::init_thread_key () inline static private
Todo:
Brief description needed.
References MADNESS_EXCEPTION, and thread_key.
Referenced by madness::ThreadPool::begin().
main()
void * madness::ThreadBase::main (void * self) static private
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in,out] self Description needed.
Returns
Description needed.
References madness::begin_papi_measurement(), e(), madness::end_papi_measurement(), madness::error(), MADNESS_EXCEPTION, pool_num, madness::print(), run(), and thread_key.
Referenced by start().
num_hw_processors()
int madness::ThreadBase::num_hw_processors () static
Get number of actual hardware processors.
Returns
The number of hardward processors.
References MADNESS_EXCEPTION.
Referenced by madness::ThreadPool::default_nthread(), and set_affinity_pattern().
run()
virtual void madness::ThreadBase::run () pure virtual
Function to be executed by the thread.
Override this to do work.
Implemented in Peasant, Worker, and madness::Thread.
Referenced by main().
set_affinity()
void madness::ThreadBase::set_affinity (int logical_id, int ind = -1) static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Parameters
[in] logical_id Description needed.
[in] ind Description needed.
References bind, cpuhi, cpulo, lo, and mask().
Referenced by madness::initialize(), and madness::ThreadPool::thread_main().
set_affinity_pattern()
void madness::ThreadBase::set_affinity_pattern (const bool bind[3], const int cpu[3]) static
Specify the affinity pattern or how to bind threads to CPUs.
Todo:
Descriptions needed.
Parameters
[in] bind Description needed.
[in] cpu Description needed.
References bind, cpuhi, cpulo, and num_hw_processors().
Referenced by madness::initialize().
set_pool_thread_index()
void madness::ThreadBase::set_pool_thread_index (int i) inline private
Sets the index of this thread within the pool.
Todo:
Verify documentation.
Parameters
[in] i The index of this thread.
References pool_num.
start()
void madness::ThreadBase::start ()
Start the thread running.
References MADNESS_EXCEPTION, and main().
Referenced by madness::Thread::start(), and madness::Thread::Thread().
this_thread()
static ThreadBase* madness::ThreadBase::this_thread () inline static
Todo:
Brief description needed.
Todo:
Descriptions needed.
Returns
Description needed.
References thread_key.
Referenced by madness::profiling::TaskEventList::print_events(), and madness::ThreadPool::run_task().
Friends And Related Function Documentation
ThreadPool
friend class ThreadPool friend
Member Data Documentation
bind
bool madness::ThreadBase::bind static private
Todo:
Brief description needed.
Referenced by set_affinity(), and set_affinity_pattern().
cpuhi
int madness::ThreadBase::cpuhi static private
Todo:
Brief description needed.
Referenced by set_affinity(), and set_affinity_pattern().
cpulo
int madness::ThreadBase::cpulo static private
Todo:
Brief description needed.
Referenced by set_affinity(), and set_affinity_pattern().
id
pthread_t madness::ThreadBase::id private
Todo:
Brief description needed.
Referenced by get_id().
pool_num
int madness::ThreadBase::pool_num private
Stores index of thread in pool or -1.
Referenced by get_pool_thread_index(), main(), and set_pool_thread_index().
thread_key
pthread_key_t madness::ThreadBase::thread_key static private
Thread id key.
Referenced by delete_thread_key(), init_thread_key(), main(), this_thread(), and madness::ThreadPool::ThreadPool().
The documentation for this class was generated from the following files:
thread.h
thread.cc