MADNESS: madness::MutexFair Class Reference
madness::MutexFair Class Reference
A scalable and fair mutex (not recursive)
#include <worldmutex.h>
Public Member Functions
MutexFair ()
void lock () const
bool try_lock () const
void unlock () const
Private Attributes
volatile int back
volatile int front
volatile int n
volatile bool *volatile q [MAX_NTHREAD]
Static Private Attributes
static const int MAX_NTHREAD = 64
Additional Inherited Members
Private Member Functions inherited from madness::Spinlock
Spinlock (int junk=0)
Make and initialize a spinlock ... initial state is unlocked.
virtual ~Spinlock ()
void lock () const
Acquire the spinlock waiting if necessary.
bool try_lock () const
Try to acquire the spinlock ... return true on success, false on failure.
void unlock () const
Free a spinlock owned by this thread.
Detailed Description
A scalable and fair mutex (not recursive)
Needs rewriting to use the CV above and do we really need this if using pthread_mutex .. why not pthread_cv?
Constructor & Destructor Documentation
MutexFair()
madness::MutexFair::MutexFair () inline
Member Function Documentation
lock()
void madness::MutexFair::lock () const inline
References b, back, madness::cpu_relax(), madness::Spinlock::lock(), MAX_NTHREAD, n, q, and madness::Spinlock::unlock().
try_lock()
bool madness::MutexFair::try_lock () const inline
References madness::Spinlock::lock(), n, and madness::Spinlock::unlock().
unlock()
void madness::MutexFair::unlock () const inline
References madness::f, front, madness::Spinlock::lock(), MAX_NTHREAD, n, p(), q, and madness::Spinlock::unlock().
Member Data Documentation
back
volatile int madness::MutexFair::back mutable private
Referenced by lock().
front
volatile int madness::MutexFair::front mutable private
Referenced by unlock().
MAX_NTHREAD
const int madness::MutexFair::MAX_NTHREAD = 64 static private
Referenced by lock(), and unlock().
n
volatile int madness::MutexFair::n mutable private
Referenced by lock(), try_lock(), and unlock().
q
volatile bool* volatile madness::MutexFair::q[MAX_NTHREAD] mutable private
Referenced by lock(), and unlock().
The documentation for this class was generated from the following file:
worldmutex.h