MADNESS: madness::RMI::RmiTask Class Reference
madness::RMI::RmiTask Class Reference
Classes
struct header
Public Member Functions
RmiTask (const SafeMPI::Intracomm &comm=SafeMPI::COMM_WORLD)
virtual ~RmiTask ()
tbb::task * execute ()
void exit ()
Request isend (const void *buf, size_t nbyte, ProcessID dest, rmi_handlerT func, attrT attr)
void post_pending_huge_msg ()
void post_recv_buf (int i)
void process_some ()
Static Public Member Functions
static void huge_msg_handler (void *buf, size_t nbytein)
static bool is_ordered (attrT attr)
static void set_rmi_task_is_running (bool flag=true)
Public Attributes
SafeMPI::Intracomm comm
volatile bool finished
std::list< std::tuple< int, size_t, int > > hugeq
q of huge messages, each msg = {source,nbytes,tag}
std::unique_ptr< int[]> ind
std::size_t max_msg_len_
std::size_t maxq_
int n_in_q
const int nproc
std::size_t nrecv_
long nssend_
std::unique_ptr< qmsg[]> q
const ProcessID rank
std::unique_ptr< void *[]> recv_buf
std::unique_ptr< counterT[]> recv_counters
std::unique_ptr< SafeMPI::Request[]> recv_req
std::unique_ptr< volatile counterT[]> send_counters
std::unique_ptr< SafeMPI::Status[]> status
Private Member Functions
int unique_tag () const
Private Member Functions inherited from madness::Mutex
Mutex (int junk=0)
Make and initialize a mutex ... initial state is unlocked.
virtual ~Mutex ()
void lock () const
Acquire the mutex waiting if necessary.
pthread_mutex_t * ptr () const
Return a pointer to the pthread mutex for use by a condition variable.
bool try_lock () const
Try to acquire the mutex ... return true on success, false on failure.
void unlock () const
Free a mutex owned by this thread.
Static Private Member Functions
static constexpr int unique_tag_period ()
Constructor & Destructor Documentation
RmiTask()
madness::RMI::RmiTask::RmiTask (const SafeMPI::Intracomm & comm = SafeMPI::COMM_WORLD)
References madness::RMI::ALIGNMENT, madness::RMI::DEFAULT_MAX_MSG_LEN, madness::RMI::DEFAULT_NRECV, ind, MADNESS_EXCEPTION, max_msg_len_, maxq_, nproc, nrecv_, nssend_, posix_memalign(), post_recv_buf(), madness::print_error(), q, recv_buf, recv_counters, recv_req, send_counters, and status.
~RmiTask()
madness::RMI::RmiTask::~RmiTask () virtual
Member Function Documentation
execute()
tbb::task* madness::RMI::RmiTask::execute () inline
References finished, process_some(), set_rmi_task_is_running(), and madness::RMI::set_this_thread_is_server().
exit()
void madness::RMI::RmiTask::exit () inline
References madness::RMI::debugging, finished, madness::myusleep(), madness::print_error(), and rank.
Referenced by madness::RMI::end().
huge_msg_handler()
void madness::RMI::RmiTask::huge_msg_handler (void * buf, size_t nbytein) static
References madness::RMI::HEADER_LEN, hugeq, MADNESS_EXCEPTION, post_pending_huge_msg(), madness::ThreadPool::size(), madness::RMI::task_ptr, and unique_tag_period().
is_ordered()
static bool madness::RMI::RmiTask::is_ordered (attrT attr) inline static
References madness::RMI::ATTR_ORDERED.
Referenced by process_some().
isend()
Request madness::RMI::RmiTask::isend (const void * buf, size_t nbyte, ProcessID dest, rmi_handlerT func, attrT attr)
Referenced by madness::RMI::isend().
post_pending_huge_msg()
void madness::RMI::RmiTask::post_pending_huge_msg ()
References madness::RMI::ALIGNMENT, MADNESS_EXCEPTION, MPI_BYTE, and posix_memalign().
Referenced by huge_msg_handler(), and process_some().
post_recv_buf()
void madness::RMI::RmiTask::post_recv_buf (int i)
References MADNESS_EXCEPTION, MPI_ANY_SOURCE, MPI_BYTE, and SafeMPI::RMI_TAG.
Referenced by process_some(), and RmiTask().
process_some()
void madness::RMI::RmiTask::process_some ()
References madness::RMI::clear_send_req(), madness::RMI::debugging, madness::func(), h(), ind, is_ordered(), m, MADNESS_EXCEPTION, maxq_, MPI_BYTE, madness::myusleep(), n_in_q, madness::RMIStats::nbyte_recv, madness::RMIStats::nmsg_recv, post_pending_huge_msg(), post_recv_buf(), madness::print_error(), q, rank, recv_buf, recv_counters, recv_req, madness::MutexWaiter::reset(), madness::RMI::stats, status, SafeMPI::Request::Testsome(), and madness::RMI::testsome_backoff_us.
Referenced by execute().
set_rmi_task_is_running()
void madness::RMI::RmiTask::set_rmi_task_is_running (bool flag = true) static
References madness::rmi_task_is_running.
Referenced by execute().
unique_tag()
int madness::RMI::RmiTask::unique_tag () const private
thread-safely round-robins through tags in [first_tag, first_tag+period) range
Returns
new tag to be used in messaging
should be able to do this with atomics
unique_tag_period()
static constexpr int madness::RMI::RmiTask::unique_tag_period () inline static private
the period of tags returned by unique_tag()
Warning
this bounds how many huge messages each RmiTask will be able to process
Referenced by huge_msg_handler().
Member Data Documentation
comm
SafeMPI::Intracomm madness::RMI::RmiTask::comm
Referenced by madness::RMI::begin().
finished
volatile bool madness::RMI::RmiTask::finished
Referenced by execute(), and exit().
hugeq
std::list< std::tuple<int,size_t,int> > madness::RMI::RmiTask::hugeq
q of huge messages, each msg = {source,nbytes,tag}
Referenced by huge_msg_handler().
ind
std::unique_ptr<int[]> madness::RMI::RmiTask::ind
Referenced by process_some(), and RmiTask().
max_msg_len_
std::size_t madness::RMI::RmiTask::max_msg_len_
Referenced by madness::RMI::max_msg_len(), and RmiTask().
maxq_
std::size_t madness::RMI::RmiTask::maxq_
Referenced by madness::RMI::maxq(), process_some(), and RmiTask().
n_in_q
int madness::RMI::RmiTask::n_in_q
Referenced by process_some().
nproc
const int madness::RMI::RmiTask::nproc
Referenced by RmiTask().
nrecv_
std::size_t madness::RMI::RmiTask::nrecv_
Referenced by madness::RMI::nrecv(), and RmiTask().
nssend_
long madness::RMI::RmiTask::nssend_
Referenced by RmiTask().
q
std::unique_ptr<qmsg[]> madness::RMI::RmiTask::q
Referenced by process_some(), and RmiTask().
rank
const ProcessID madness::RMI::RmiTask::rank
Referenced by exit(), and process_some().
recv_buf
std::unique_ptr<void*[]> madness::RMI::RmiTask::recv_buf
Referenced by process_some(), and RmiTask().
recv_counters
std::unique_ptr<counterT[]> madness::RMI::RmiTask::recv_counters
Referenced by process_some(), and RmiTask().
recv_req
std::unique_ptr<SafeMPI::Request[]> madness::RMI::RmiTask::recv_req
Referenced by process_some(), and RmiTask().
send_counters
std::unique_ptr<volatile counterT[]> madness::RMI::RmiTask::send_counters
Referenced by RmiTask().
status
std::unique_ptr<SafeMPI::Status[]> madness::RMI::RmiTask::status
Referenced by process_some(), and RmiTask().
The documentation for this class was generated from the following files:
worldrmi.h
worldrmi.cc