MADNESS: Plotter Class Reference
Plotter Class Reference
Public Member Functions
Plotter (World &world)
template<typename T , std::size_t NDIM>
void dolineplot (const Function< T, NDIM > &f)
template<typename T , std::size_t NDIM>
void dolineplot (const Function< T, NDIM > &f, const Function< T, NDIM > &g)
template<typename T >
void doplot ()
template<typename T , std::size_t NDIM>
void doplot1 ()
template<typename T , std::size_t NDIM>
void dovolumeplot (const Function< T, NDIM > &f)
template<typename T , std::size_t NDIM>
void dovolumeplot (const Function< T, NDIM > &f, const Function< T, NDIM > &g)
void plot ()
void read (std::istream &input)
Tensor< double > read_cell (std::istream &input)
std::vector< long > read_npt (std::istream &input)
std::string read_to_end_of_line (std::istream &input)
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
bool binary
Tensor< double > cell
std::string data_type
bool finished
std::string formula
std::string function_name
std::string input_filename
int ndim
std::vector< long > npt
std::string output_filename
std::string output_format
Tensor< double > plot_cell
std::string plot_type
World & world
Constructor & Destructor Documentation
Plotter()
Plotter::Plotter (World & world) inline
Member Function Documentation
dolineplot() [1/2]
template<typename T , std::size_t NDIM> void Plotter::dolineplot (const Function< T, NDIM > & f) inline
References madness::f, lo, NDIM, and madness::plot_line().
dolineplot() [2/2]
template<typename T , std::size_t NDIM> void Plotter::dolineplot (const Function< T, NDIM > & f, const Function< T, NDIM > & g) inline
References madness::f, madness::g, lo, NDIM, and madness::plot_line().
doplot()
template<typename T > void Plotter::doplot () inline
References MADNESS_EXCEPTION.
doplot1()
template<typename T , std::size_t NDIM> void Plotter::doplot1 () inline
References madness::f, MADNESS_EXCEPTION, and madness::FunctionDefaults< NDIM >::set_cell().
dovolumeplot() [1/2]
template<typename T , std::size_t NDIM> void Plotter::dovolumeplot (const Function< T, NDIM > & f) inline
References madness::f, NDIM, madness::plotdx(), madness::plotvtk_begin(), and madness::plotvtk_data().
dovolumeplot() [2/2]
template<typename T , std::size_t NDIM> void Plotter::dovolumeplot (const Function< T, NDIM > & f, const Function< T, NDIM > & g) inline
References madness::f, madness::g, MADNESS_EXCEPTION, NDIM, madness::plotvtk_begin(), and madness::plotvtk_data().
plot()
void Plotter::plot () inline
References MADNESS_EXCEPTION.
Referenced by main().
read()
void Plotter::read (std::istream & input) inline
References madness::copy(), madness::BaseTensor::dim(), MADNESS_ASSERT, MADNESS_EXCEPTION, madness::print(), and madness::BaseTensor::size().
Referenced by main().
read_cell()
Tensor<double> Plotter::read_cell (std::istream & input) inline
References MADNESS_ASSERT.
read_npt()
std::vector<long> Plotter::read_npt (std::istream & input) inline
read_to_end_of_line()
std::string Plotter::read_to_end_of_line (std::istream & input) inline
References c.
serialize()
template<typename Archive > void Plotter::serialize (Archive & ar) inline
Member Data Documentation
binary
bool Plotter::binary
cell
Tensor<double> Plotter::cell
data_type
std::string Plotter::data_type
finished
bool Plotter::finished
Referenced by main().
formula
std::string Plotter::formula
function_name
std::string Plotter::function_name
input_filename
std::string Plotter::input_filename
ndim
int Plotter::ndim
npt
std::vector<long> Plotter::npt
output_filename
std::string Plotter::output_filename
output_format
std::string Plotter::output_format
plot_cell
Tensor<double> Plotter::plot_cell
plot_type
std::string Plotter::plot_type
world
World& Plotter::world
The documentation for this class was generated from the following file:
mraplot.cc