MADNESS: madness::detail::ForEachRootTask< rangeT, opT > Class Template Reference
madness::detail::ForEachRootTask< rangeT, opT > Class Template Reference
Apply an operation to a range of iterators.
#include <world_task_queue.h>
Public Member Functions
ForEachRootTask (World &, const rangeT range, const opT &op)
Constructor.
virtual ~ForEachRootTask ()=default
Virtual destructor.
virtual tbb::task * execute ()
Task run work.
const Future< bool > & result () const
Result accessor.
Public Member Functions inherited from madness::TaskInterface
TaskInterface (int ndepend=0, const TaskAttributes attr=TaskAttributes())
Create a new task with ndepend dependencies (default 0) and given attributes.
TaskInterface (int ndepend, const char *caller, const TaskAttributes attr=TaskAttributes())
TaskInterface (const TaskAttributes &attr)
Create a new task with zero dependencies and given attributes.
virtual ~TaskInterface ()
World * get_world () const
virtual void run (World &)
Runs a single-threaded task ... derived classes must implement this.
virtual void run (World &world, const TaskThreadEnv &env)
Runs a multi-threaded task.
Public Member Functions inherited from madness::PoolTaskInterface
PoolTaskInterface ()
Default constructor.
PoolTaskInterface (const TaskAttributes &attr)
virtual ~PoolTaskInterface ()=default
Destructor.
tbb::task * execute ()
void set_nthread (int nthread)
Call this to reset the number of threads before the task is submitted.
Public Member Functions inherited from madness::TaskAttributes
TaskAttributes (unsigned long flags=0)
Sets the attributes to the desired values.
TaskAttributes (const TaskAttributes &attr)
Copy constructor.
virtual ~TaskAttributes ()
int get_nthread () const
Get the number of threads.
bool is_generator () const
Test if the generator attribute is true.
bool is_high_priority () const
Test if the high priority attribute is true.
bool is_stealable () const
Test if the stealable attribute is true.
template<typename Archive >
void serialize (Archive &ar)
Serializes the attributes for I/O.
void set_generator (bool generator_hint)
Sets the generator attribute.
void set_highpriority (bool hipri)
Sets the high priority attribute.
void set_nthread (int nthread)
Set the number of threads.
void set_stealable (bool stealable)
Sets the stealable attribute.
Public Member Functions inherited from madness::DependencyInterface
DependencyInterface (int ndep=0)
DependencyInterface (int ndep, const char *caller)
virtual ~DependencyInterface ()
Destructor.
void dec ()
Decrement the number of dependencies and invoke the callback if ndepend==0.
void dec_debug (const char *caller)
void inc ()
Increment the number of dependencies.
void inc_debug (const char *caller)
Same as inc(), but keeps track of caller; calling dec_debug() will signal error if no matching inc_debug() had been invoked.
int ndep () const
Returns the number of unsatisfied dependencies.
void notify ()
Invoked by callbacks to notify of dependencies being satisfied.
void notify_debug (const char *caller)
Overload of CallbackInterface::notify_debug(), updates dec()
bool probe () const
Returns true if ndepend == 0 (no unsatisfied dependencies).
void register_callback (CallbackInterface *callback)
Registers a callback that will be executed when ndepend==0; immediately invoked if ndepend==0.
void register_final_callback (CallbackInterface *callback)
Registers the final callback to be executed when ndepend==0; immediately invoked if ndepend==0.
Public Member Functions inherited from madness::CallbackInterface
virtual ~CallbackInterface ()
Private Member Functions
virtual void get_id (std::pair< void *, unsigned short > &id) const
Get the task ID.
Private Attributes
Future< bool > completion_status_
The result of this set of tasks.
opT op_
The foreach function.
rangeT range_
The range.
Additional Inherited Members
Static Public Member Functions inherited from madness::PoolTaskInterface
static void operator delete (void *p, std::size_t size) noexcept
Destroy a task object.
static void * operator new (std::size_t size)
Static Public Member Functions inherited from madness::TaskAttributes
static TaskAttributes generator ()
static TaskAttributes hipri ()
static TaskAttributes multi_threaded (int nthread)
Static Public Attributes inherited from madness::TaskInterface
static bool debug = false
Static Public Attributes inherited from madness::TaskAttributes
static const unsigned long GENERATOR = 1ul<<8
Mask for generator bit.
static const unsigned long HIGHPRIORITY = GENERATOR<<2
Mask for priority bit.
static const unsigned long NTHREAD = 0xff
Mask for nthread byte.
static const unsigned long STEALABLE = GENERATOR<<1
Mask for stealable bit.
Protected Member Functions inherited from madness::TaskInterface
virtual void run (const TaskThreadEnv &env)
Override this method to implement a multi-threaded task.
Protected Member Functions inherited from madness::CallbackInterface
virtual void notify_debug_impl (const char *caller)
Static Protected Member Functions inherited from madness::PoolTaskInterface
template<typename fnT >
static std::enable_if< detail::function_traits< fnT >::value||detail::memfunc_traits< fnT >::value >::type make_id (std::pair< void *, unsigned short > &id, fnT fn)
template<typename fnobjT >
static std::enable_if<!(detail::function_traits< fnobjT >::value||detail::memfunc_traits< fnobjT >::value) >::type make_id (std::pair< void *, unsigned short > &id, const fnobjT &)
Detailed Description
template<typename rangeT, typename opT>
class madness::detail::ForEachRootTask< rangeT, opT >
Apply an operation to a range of iterators.
Template Parameters
rangeT The range of iterators type.
opT The operation type. This task creates for_each tasks and collects information on the results of those tasks. Once all tasks have completed it will set the result future.
Constructor & Destructor Documentation
ForEachRootTask()
template<typename rangeT, typename opT> madness::detail::ForEachRootTask< rangeT, opT >::ForEachRootTask (World & , const rangeT range, const opT & op) inline
Constructor.
Parameters
[in] world The world where the tasks will run.
[in] range The range of iterators.
[in] op The operation that will be applied to the range of iterators.
~ForEachRootTask()
template<typename rangeT, typename opT> virtual madness::detail::ForEachRootTask< rangeT, opT >::~ForEachRootTask () virtual default
Virtual destructor.
Member Function Documentation
execute()
template<typename rangeT, typename opT> virtual tbb::task* madness::detail::ForEachRootTask< rangeT, opT >::execute () inline virtual
Task run work.
Sets the result future based on the status of all iterations.
References madness::detail::ForEachRootTask< rangeT, opT >::completion_status_, madness::detail::ForEachRootTask< rangeT, opT >::op_, madness::detail::ForEachRootTask< rangeT, opT >::range_, madness::detail::ForEachRootTask< rangeT, opT >::result(), and madness::Future< T >::set().
get_id()
template<typename rangeT, typename opT> virtual void madness::detail::ForEachRootTask< rangeT, opT >::get_id (std::pair< void *, unsigned short > & id) const inline private virtual
Get the task ID.
Todo:
Verify that id is an output parameter.
Parameters
[out] id The ID to set for this task.
Reimplemented from madness::PoolTaskInterface.
References madness::PoolTaskInterface::make_id().
result()
template<typename rangeT, typename opT> const Future<bool>& madness::detail::ForEachRootTask< rangeT, opT >::result () const inline
Result accessor.
Returns
A const reference to the result future.
References madness::detail::ForEachRootTask< rangeT, opT >::completion_status_.
Referenced by madness::detail::ForEachRootTask< rangeT, opT >::execute(), and madness::WorldTaskQueue::for_each().
Member Data Documentation
completion_status_
template<typename rangeT, typename opT> Future<bool> madness::detail::ForEachRootTask< rangeT, opT >::completion_status_ private
The result of this set of tasks.
Referenced by madness::detail::ForEachRootTask< rangeT, opT >::execute(), and madness::detail::ForEachRootTask< rangeT, opT >::result().
op_
template<typename rangeT, typename opT> opT madness::detail::ForEachRootTask< rangeT, opT >::op_ private
The foreach function.
Referenced by madness::detail::ForEachRootTask< rangeT, opT >::execute().
range_
template<typename rangeT, typename opT> rangeT madness::detail::ForEachRootTask< rangeT, opT >::range_ private
The range.
Referenced by madness::detail::ForEachRootTask< rangeT, opT >::execute().
The documentation for this class was generated from the following file:
world_task_queue.h