MADNESS: crayio.c File Reference
crayio.c File Reference
#include <stdio.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/file.h>
#include <fcntl.h>
Classes
struct w_file
Macros
#define L_XTND SEEK_END
#define max_file 99
Typedefs
typedef int integer
Functions
static int CheckAddr (integer addr)
static int CheckCount (integer count)
static int CheckUnit (integer unit)
void FirstCall ()
void getwa_ (integer *unit, double *result, integer *addr, integer *count, integer *ierr)
void InitFileData (struct w_file *file)
void InitFileStats (struct w_file *file)
off_t lseek ()
char * malloc ()
void PrintFileStats (struct w_file *unit, struct w_file *file)
void putwa_ (integer *unit, double *source, integer *addr, integer *count, integer *ierr)
char * strncpy ()
void walltm_ (double *ai)
void wclose_ (integer *unit, integer *ierr)
void wopen_ (integer *unit, char *name, integer *blocks, integer *stats, integer *ierr, int lennam)
Variables
static struct w_file file_array [max_file]
static int first_call = 1
Macro Definition Documentation
L_XTND
#define L_XTND SEEK_END
Referenced by wopen_().
max_file
#define max_file 99
Referenced by CheckUnit(), FirstCall(), and wopen_().
Typedef Documentation
integer
typedef int integer
Function Documentation
CheckAddr()
static int CheckAddr (integer addr) static
Referenced by getwa_(), and putwa_().
CheckCount()
static int CheckCount (integer count) static
Referenced by getwa_(), and putwa_().
CheckUnit()
static int CheckUnit (integer unit) static
References file_array, and max_file.
Referenced by getwa_(), putwa_(), and wclose_().
FirstCall()
void FirstCall ()
References file_array, first_call, InitFileData(), InitFileStats(), and max_file.
Referenced by getwa_(), putwa_(), wclose_(), and wopen_().
getwa_()
void getwa_ (integer * unit, double * result, integer * addr, integer * count, integer * ierr)
References CheckAddr(), CheckCount(), CheckUnit(), w_file::fds, file_array, first_call, FirstCall(), w_file::length, lseek(), w_file::n_read, w_file::position, w_file::seek_read, w_file::stats, w_file::time_read, walltm_(), and w_file::words_read.
InitFileData()
void InitFileData (struct w_file * file)
References w_file::fds, w_file::length, w_file::path, and w_file::position.
Referenced by FirstCall(), and wclose_().
InitFileStats()
void InitFileStats (struct w_file * file)
References w_file::n_read, w_file::n_write, w_file::seek_read, w_file::seek_write, w_file::stats, w_file::time_read, w_file::time_write, w_file::words_read, and w_file::words_write.
Referenced by FirstCall(), and wclose_().
lseek()
off_t lseek ()
Referenced by getwa_(), putwa_(), and wopen_().
malloc()
char* malloc ()
Referenced by madness::Stack< T, N >::allocate(), madness::mTxmq_padding(), posix_memalign(), madness::ThreadPool::ThreadPool(), and wopen_().
PrintFileStats()
void PrintFileStats (struct w_file * unit, struct w_file * file)
References w_file::length, w_file::n_read, w_file::n_write, w_file::path, w_file::seek_read, w_file::seek_write, w_file::time_read, w_file::time_write, w_file::words_read, and w_file::words_write.
Referenced by wclose_().
putwa_()
void putwa_ (integer * unit, double * source, integer * addr, integer * count, integer * ierr)
References CheckAddr(), CheckCount(), CheckUnit(), w_file::fds, file_array, first_call, FirstCall(), w_file::length, lseek(), w_file::n_write, w_file::position, w_file::seek_write, source(), w_file::stats, w_file::time_write, walltm_(), and w_file::words_write.
strncpy()
char* strncpy ()
Referenced by SafeMPI::Exception::Exception(), MPI_Error_string(), SafeMPI::Exception::operator=(), wopen_(), and madness::detail::WorldMpi::~WorldMpi().
walltm_()
void walltm_ (double * ai)
References e().
Referenced by getwa_(), and putwa_().
wclose_()
void wclose_ (integer * unit, integer * ierr)
References CheckUnit(), w_file::fds, file_array, first_call, FirstCall(), InitFileData(), InitFileStats(), PrintFileStats(), and w_file::stats.
wopen_()
void wopen_ (integer * unit, char * name, integer * blocks, integer * stats, integer * ierr, int lennam)
References w_file::fds, file_array, first_call, FirstCall(), L_XTND, w_file::length, lseek(), malloc(), max_file, w_file::path, w_file::position, w_file::stats, stats, and strncpy().
Variable Documentation
file_array
struct w_file file_array[max_file] static
Referenced by CheckUnit(), FirstCall(), getwa_(), putwa_(), wclose_(), and wopen_().
first_call
int first_call = 1 static
Referenced by FirstCall(), getwa_(), putwa_(), madness::wall_time(), wclose_(), and wopen_().