MADNESS: esolver.h File Reference
esolver.h File Reference
Classes
struct KPoint
Typedefs
typedef Function< std::complex< double >, 3 > cfunctionT
typedef Vector< double, 3 > coordT
typedef Tensor< std::complex< double > > ctensorT
typedef std::vector< cfunctionT > cvecfuncT
typedef FunctionFactory< std::complex< double >, 3 > factoryT
typedef Function< std::complex< double >, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< std::complex< double >, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef FunctionFactory< double, 3 > rfactoryT
typedef Function< double, 3 > rfunctionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > rfunctorT
typedef Tensor< double > rtensorT
typedef std::vector< rfunctionT > rvecfuncT
typedef std::vector< functionT > vecfuncT
Functions
bool is_equal (double val1, double val2, double eps)
template<typename Q , int NDIM>
ctensorT kinetic_energy_matrix (World &world, const std::vector< Function< std::complex< Q >, NDIM > > &v, const bool periodic, const KPoint k=KPoint(coordT(0.0), 0.0))
template<typename Q , int NDIM>
ctensorT kinetic_energy_matrix2 (World &world, const std::vector< Function< std::complex< Q >, NDIM > > &v)
template<typename Q , int NDIM>
ctensorT kinetic_energy_matrix_slow (World &world, const std::vector< Function< std::complex< Q >, NDIM > > &v, const bool periodic, const KPoint k=KPoint(coordT(0.0), 0.0))
std::istream & operator>> (std::istream &is, KPoint &kpt)
void print_cube (World &world, const Function< double, 3 > &f, int npts)
void print_cube (World &world, const Function< double, 3 > &f1, const Function< double, 3 > &f2, int npts)
void print_cube (World &world, const Function< double, 3 > &f1, const Function< double, 3 > &f2, const Function< double, 3 > &f3, int npts)
Typedef Documentation
cfunctionT
typedef Function<std::complex<double>,3> cfunctionT
coordT
typedef Vector<double,3> coordT
ctensorT
typedef Tensor< std::complex<double> > ctensorT
cvecfuncT
typedef std::vector<cfunctionT> cvecfuncT
factoryT
typedef FunctionFactory<std::complex<double>,3> factoryT
functionT
typedef Function<std::complex<double>,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<std::complex<double>,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
rfactoryT
typedef FunctionFactory<double,3> rfactoryT
rfunctionT
typedef Function<double,3> rfunctionT
rfunctorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > rfunctorT
rtensorT
typedef Tensor<double> rtensorT
rvecfuncT
typedef std::vector<rfunctionT> rvecfuncT
vecfuncT
typedef std::vector<functionT> vecfuncT
Function Documentation
is_equal()
bool is_equal (double val1, double val2, double eps)
References d().
Referenced by madness::Solver< T, NDIM >::do_rhs(), and madness::Solver< T, NDIM >::do_rhs_simple().
kinetic_energy_matrix()
template<typename Q , int NDIM> ctensorT kinetic_energy_matrix (World & world, const std::vector< Function< std::complex< Q >, NDIM > > & v, const bool periodic, const KPoint k = KPoint(coordT(0.0), 0.0))
References madness::apply(), axis, c, madness::compress(), madness::gaxpy(), gradop, I, k, madness::matrix_inner(), NDIM, and madness::reconstruct().
Referenced by MiniDFT::doit().
kinetic_energy_matrix2()
template<typename Q , int NDIM> ctensorT kinetic_energy_matrix2 (World & world, const std::vector< Function< std::complex< Q >, NDIM > > & v)
References madness::apply(), axis, c, gradop, I, madness::matrix_inner(), NDIM, and madness::reconstruct().
kinetic_energy_matrix_slow()
template<typename Q , int NDIM> ctensorT kinetic_energy_matrix_slow (World & world, const std::vector< Function< std::complex< Q >, NDIM > > & v, const bool periodic, const KPoint k = KPoint(coordT(0.0), 0.0))
References madness::apply(), axis, c, madness::conj(), gradop, I, madness::inner(), k, k0, k1, k2, madness::matrix_inner(), NDIM, and madness::reconstruct().
operator>>()
std::istream& operator>> (std::istream & is, KPoint & kpt)
References KPoint::begin, KPoint::end, KPoint::k, and KPoint::weight.
print_cube() [1/3]
void print_cube (World & world, const Function< double, 3 > & f, int npts)
References f, k, and p().
print_cube() [2/3]
void print_cube (World & world, const Function< double, 3 > & f1, const Function< double, 3 > & f2, int npts)
References f1, f2, k, and p().
print_cube() [3/3]
void print_cube (World & world, const Function< double, 3 > & f1, const Function< double, 3 > & f2, const Function< double, 3 > & f3, int npts)
References f1, f2, f3, k, and p().