MADNESS: ewald.cc File Reference
ewald.cc File Reference
#include <madness/mra/mra.h>
#include "mentity.h"
Classes
class EwaldNuclearPotentialFunctor
class GaussianFunctor
class MolecularNuclearChargeDensityFunctor
class MolecularNuclearPotentialFunctor2
class OnesFunctor
struct vectorLengthFunctor
Typedefs
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > rfactoryT
typedef Function< double, 3 > rfunctionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > rfunctorT
typedef std::vector< rfunctionT > rvecfuncT
Functions
void compute_madelung_energy (World &world, MolecularEntity mentity, double alpha=1.5, double rmax=200.0, double gmax=200.0)
void compute_madelung_energy_PWSCF (World &world, MolecularEntity mentity, double alpha=8.5, double rmax=100.0, double gmax=100.0)
double compute_volume ()
void gen_ce (double mu, double xlo, double eps, Tensor< double > &c, Tensor< double > &e)
std::vector< Vector< double, 3 > > generate_G_vectors (World &world, double maxGlen=15.0)
std::vector< Vector< double, 3 > > generate_R_vectors (World &world, double maxRlen=50.0)
int main (int argc, char **argv)
rfunctionT make_nuclear_charge_density (World &world, const MolecularEntity &mentity, double thresh=1e-6)
rvecfuncT make_nuclear_charge_density_individual (World &world, const MolecularEntity &mentity, double thresh)
double nuclear_potential (const Tensor< double > &c, const Tensor< double > &e, double r)
void test_G_R_vectors (int argc, char **argv)
void test_gaussian_num_coeffs (int argc, char **argv)
void test_gence (int argc, char **argv)
void test_gence2 (int argc, char **argv)
void test_nuclear_energy (int argc, char **argv)
void test_nuclear_potential (int argc, char **argv)
void test_nuclear_potential2 (int argc, char **argv)
void test_nuclear_potential3 (int argc, char **argv)
void test_nuclear_potential_big_unit_cell (int argc, char **argv)
Variables
static double L = 6.5
Typedef Documentation
coordT
typedef Vector<double,3> coordT
rfactoryT
typedef FunctionFactory<double,3> rfactoryT
rfunctionT
typedef Function<double,3> rfunctionT
rfunctorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > rfunctorT
rvecfuncT
typedef std::vector<rfunctionT> rvecfuncT
Function Documentation
compute_madelung_energy()
void compute_madelung_energy (World & world, MolecularEntity mentity, double alpha = 1.5, double rmax = 200.0, double gmax = 200.0)
References std::abs(), alpha, compute_volume(), energy, G2, generate_G_vectors(), generate_R_vectors(), MolecularEntity::get_atom(), madness::imag(), MolecularEntity::natom(), madness::constants::pi, madness::Atom::q, madness::World::rank(), real(), MolecularEntity::total_nuclear_charge(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
compute_madelung_energy_PWSCF()
void compute_madelung_energy_PWSCF (World & world, MolecularEntity mentity, double alpha = 8.5, double rmax = 100.0, double gmax = 100.0)
References std::abs(), alpha, compute_volume(), energy, G2, generate_G_vectors(), generate_R_vectors(), MolecularEntity::get_atom(), L, MolecularEntity::natom(), madness::constants::pi, MolecularEntity::print(), madness::Atom::q, madness::World::rank(), real(), MolecularEntity::total_nuclear_charge(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by test_nuclear_energy().
compute_volume()
double compute_volume ()
References L.
Referenced by compute_madelung_energy(), compute_madelung_energy_PWSCF(), EwaldNuclearPotentialFunctor::do_G_sum_v1(), EwaldNuclearPotentialFunctor::do_G_sum_v2(), and EwaldNuclearPotentialFunctor::do_R_sum_v1().
gen_ce()
void gen_ce (double mu, double xlo, double eps, Tensor< double > & c, Tensor< double > & e)
References std::abs(), c, e(), h(), mu, madness::constants::pi, and madness::print().
Referenced by test_gence().
generate_G_vectors()
std::vector< Vector<double,3> > generate_G_vectors (World & world, double maxGlen = 15.0)
References L, madness::constants::pi, madness::print(), and madness::World::rank().
Referenced by compute_madelung_energy(), compute_madelung_energy_PWSCF(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), and test_G_R_vectors().
generate_R_vectors()
std::vector< Vector<double,3> > generate_R_vectors (World & world, double maxRlen = 50.0)
References L, madness::print(), madness::World::rank(), and madness::Vector< T, N >::size().
Referenced by compute_madelung_energy(), compute_madelung_energy_PWSCF(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), and test_G_R_vectors().
main()
int main (int argc, char ** argv)
References test_nuclear_potential3().
make_nuclear_charge_density()
rfunctionT make_nuclear_charge_density (World & world, const MolecularEntity & mentity, double thresh = 1e-6)
References MolecularEntity::get_atom(), L, MolecularEntity::natom(), thresh, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Referenced by test_nuclear_potential(), test_nuclear_potential3(), and test_nuclear_potential_big_unit_cell().
make_nuclear_charge_density_individual()
rvecfuncT make_nuclear_charge_density_individual (World & world, const MolecularEntity & mentity, double thresh)
References MolecularEntity::get_atom(), L, m, MolecularEntity::natom(), thresh, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
nuclear_potential()
double nuclear_potential (const Tensor< double > & c, const Tensor< double > & e, double r)
References c, e(), and mu.
Referenced by madness::Znemo::compute_energy(), MolecularNuclearPotentialFunctor2::operator()(), and test_gence2().
test_G_R_vectors()
void test_G_R_vectors (int argc, char ** argv)
References std::abs(), SafeMPI::COMM_WORLD, e(), madness::error(), madness::finalize(), generate_G_vectors(), generate_R_vectors(), madness::imag(), madness::initialize(), MADNESS_ASSERT, madness::print(), madness::World::rank(), and madness::startup().
test_gaussian_num_coeffs()
void test_gaussian_num_coeffs (int argc, char ** argv)
References madness::BC_PERIODIC, SafeMPI::COMM_WORLD, e(), madness::error(), madness::finalize(), madness::initialize(), L, madness::Function< T, NDIM >::max_nodes(), madness::constants::pi, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and madness::Function< T, NDIM >::trace().
test_gence()
void test_gence (int argc, char ** argv)
References std::abs(), c, e(), gen_ce(), and mu.
test_gence2()
void test_gence2 (int argc, char ** argv)
References std::abs(), c, e(), L, lo, nuclear_potential(), and madness::constants::pi.
test_nuclear_energy()
void test_nuclear_energy (int argc, char ** argv)
References MolecularEntity::add_atom(), madness::BC_PERIODIC, MolecularEntity::center(), SafeMPI::COMM_WORLD, compute_madelung_energy_PWSCF(), e(), madness::error(), madness::finalize(), madness::initialize(), L, MolecularEntity::print(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::startup().
test_nuclear_potential()
void test_nuclear_potential (int argc, char ** argv)
References std::abs(), MolecularEntity::add_atom(), madness::apply(), madness::BC_PERIODIC, MolecularEntity::center(), SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), madness::error(), madness::finalize(), madness::initialize(), L, make_nuclear_charge_density(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), MolecularEntity::total_nuclear_charge(), and madness::Function< T, NDIM >::trace().
test_nuclear_potential2()
void test_nuclear_potential2 (int argc, char ** argv)
References std::abs(), MolecularEntity::add_atom(), madness::BC_FREE, c, MolecularEntity::center(), SafeMPI::COMM_WORLD, e(), madness::error(), madness::finalize(), MolecularNuclearPotentialFunctor2::get_coeff(), MolecularNuclearPotentialFunctor2::get_expnt(), madness::initialize(), L, MolecularEntity::print(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::startup().
test_nuclear_potential3()
void test_nuclear_potential3 (int argc, char ** argv)
References std::abs(), MolecularEntity::add_atom(), madness::apply(), madness::BC_PERIODIC, MolecularEntity::center(), SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), madness::error(), madness::finalize(), madness::initialize(), L, make_nuclear_charge_density(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::startup().
Referenced by main().
test_nuclear_potential_big_unit_cell()
void test_nuclear_potential_big_unit_cell (int argc, char ** argv)
References MolecularEntity::add_atom(), madness::apply(), madness::BC_FREE, MolecularEntity::center(), SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), madness::error(), madness::finalize(), MolecularEntity::get_atom(), madness::initialize(), L, make_nuclear_charge_density(), MolecularEntity::print(), madness::print(), madness::Atom::q, madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
Variable Documentation
L
double L = 6.5 static
Referenced by madness::add(), madness::FunctionImpl< Q, NDIM >::add_scalar_inplace(), MolecularEntity::bounding_cube(), madness::Molecule::bounding_cube(), madness::FunctionImpl< Q, NDIM >::broaden(), madness::DFT< T, NDIM >::calculate_tot_coulomb_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::SeparatedConvolution< T, NDIM >::check_cubic(), madness::SlaterF12Interface::coeff(), compute_madelung_energy_PWSCF(), compute_reduced_mass(), madness::MolecularOptimizer::compute_reduced_mass(), compute_volume(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::FunctionImpl< Q, NDIM >::do_mul(), madness::SDFParaboloid::eval_cubic(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), madness::XCfunctional::exc(), madness::SDFParaboloid::find_root(), smooth< T, NDIM >::gaussian_smoothing(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_recursive(), generate_G_vectors(), generate_R_vectors(), madness::GenericConvolution1D< Q, opT >::GenericConvolution1D(), madness::SDFParaboloid::get_roots(), KAIN(), madness::KAIN(), madness::trajectory< NDIM >::line_xyz(), madness::SCF::localize_new(), main(), make_nuclear_charge_density(), make_nuclear_charge_density_individual(), madness::Molecule::moment_of_inertia(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast(), madness::Molecule::orient(), madness::orthonormalize_cd(), madness::PNO::orthonormalize_cholesky(), madness::orthonormalize_rrcd(), madness::PeriodicBSHOp(), madness::PeriodicBSHOpPtr(), madness::PeriodicCoulombOp(), madness::PeriodicCoulombOpPtr(), madness::MyPmap< D >::prepare_not_so_simple_map(), printfunc(), InputParameters::read(), madness::Molecule::rotate(), madness::SDFParaboloid::sdf(), InputParameters::serialize(), madness::BaseTensor::set_dims_and_size(), madness::SmoothingOperator(), madness::SmoothingOperator3D(), madness::EigSolver< T, NDIM >::solve(), solve(), madness::sub(), test0(), Test1(), smooth< T, NDIM >::test_1d(), test_apply_push_1d(), test_chin_chen(), test_gaussian_num_coeffs(), test_gence2(), test_he_potential(), test_hf_be(), test_hf_he(), test_hydro(), test_modified(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_op(), test_per(), test_plot(), test_proj(), test_qm(), test_recursive_application(), test_trotter(), madness::TensorTrain< T >::truncate(), madness::GFit< T, NDIM >::truncate_periodic_expansion(), madness::FunctionImpl< Q, NDIM >::truncate_tol(), madness::SystolicMatrixAlgorithm< double >::unshuffle(), madness::detail::Vm_cstr< wchar_t >(), madness::vmulXX(), and madness::XCfunctional::vxc().