MADNESS: zcis.cc File Reference
examples/zcis.cc File Reference
#include <chem/zcis.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::finalize(), madness::initialize(), madness::print(), madness::World::rank(), madness::startup(), madness::Zcis::value(), and madness::wall_time().