MADNESS: mp2.cc File Reference
examples/mp2.cc File Reference
#include <madness/world/info.h>
#include <chem/mp2.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::World::rank(), and madness::startup().