MADNESS: nemo.cc File Reference
examples/nemo.cc File Reference
solve the HF equations using numerical exponential MOs
#include <chem/nemo.h>
#include <chem/molecular_optimizer.h>
#include <chem/SCFOperators.h>
#include <chem/projector.h>
#include <madness/misc/gitinfo.h>
Functions
int main (int argc, char **argv)
Detailed Description
solve the HF equations using numerical exponential MOs
The source is <a href=http://code.google.com/p/m-a-d-n-e-s-s/source/browse/local /trunk/src/apps/examples/nemo.h>here.
The source is <a href=http://code.google.com/p/m-a-d-n-e-s-s/source/browse/local /trunk/src/apps/examples/nemo.cc>here.
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), energy, madness::error(), madness::finalize(), madness::Tensor< T >::flat(), madness::initialize(), madness::MolecularOptimizer::optimize(), madness::print(), madness::info::print_revision_information(), madness::World::rank(), madness::MolecularOptimizer::set_hessian(), madness::startup(), and madness::wall_time().