MADNESS: znemo.cc File Reference
examples/znemo.cc File Reference
solve the HF equations using numerical exponential MOs
#include <chem/znemo.h>
Functions
int main (int argc, char **argv)
Detailed Description
solve the HF equations using numerical exponential MOs
The source is <a href=http://code.google.com/p/m-a-d-n-e-s-s/source/browse/local /trunk/src/apps/examples/nemo.cc>here.
Function Documentation
main()
int main (int argc, char ** argv)
References a, SafeMPI::COMM_WORLD, e(), energy, madness::error(), madness::finalize(), madness::Tensor< T >::flat(), help, madness::initialize(), madness::MolecularOptimizer::optimize(), madness::MolecularOptimizer::parameters, madness::print(), madness::QCCalculationParametersBase::print(), madness::info::print_revision_information(), madness::World::rank(), madness::QCCalculationParametersBase::set_derived_value(), madness::startup(), and madness::wall_time().