MADNESS: oep.cc File Reference
examples/oep.cc File Reference
optimized effective potentials for DFT
#include <chem/oep.h>
#include <madness/misc/gitinfo.h>
Functions
int main (int argc, char **argv)
void write_test_input ()
Create a specific test input for the Be atom.
Detailed Description
optimized effective potentials for DFT
Function Documentation
main()
int main (int argc, char ** argv)
see constructor in SCF.h
TODO: find a way to save eigenvalues and implement restart options
References a, madness::arg(), SafeMPI::COMM_WORLD, madness::copy(), energy, madness::finalize(), madness::initialize(), print(), madness::info::print_revision_information(), madness::World::rank(), madness::startup(), test(), madness::wall_time(), and write_test_input().
write_test_input()
void write_test_input ()
Create a specific test input for the Be atom.
References madness::filename.
Referenced by main().