MADNESS: gaussian.cc File Reference
gaussian.cc File Reference
Examples » Getting Started
A simple example of projecting and using MADNESS functions.This example projects a simple Gaussian function,
into the MADNESS adaptive basis and computes several integrals:
.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
Functions
double gaussian (const coord_3d &r)
C++ function for projecting the Gaussian test function.
int main (int argc, char **argv)
Main function. Project the function and compute the integrals.
Detailed Description
A simple example of projecting and using MADNESS functions.
This example projects a simple Gaussian function,
into the MADNESS adaptive basis and computes several integrals:
.
Function Documentation
gaussian()
double gaussian (const coord_3d & r)
C++ function for projecting the Gaussian test function.
Parameters
[in] r The coordinate at which to evaluate the function.
Returns
The value of the Gaussian at the specified coordinate.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function. Project the function and compute the integrals.
Parameters
[in] argc The number of command-line arguments.
[in] argv The command-line arguments.
Returns
Exit status.
References SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), madness::finalize(), madness::g, gaussian(), madness::initialize(), madness::inner(), op(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), and madness::startup().