MADNESS: gfit.cc File Reference
gfit.cc File Reference
#include <madness/tensor/tensor_lapack.h>
#include <madness/tensor/solvers.h>
#include <madness/world/print.h>
#include <cmath>
#include <iostream>
#include <algorithm>
Classes
class Fred
Wrapper around vector demonstrating interface necessary.
Functions
double Akernel (double p)
Tensor< double > arithmetic_series (long n, double a, double h)
double E0 (double p)
double errsq (const Tensor< double > f, const Tensor< double > x, const Tensor< double > w, const Tensor< double > c, const Tensor< double > expnt, const double mu, const double p)
double fit (double x, const Tensor< double > &c, const Tensor< double > &expnt)
Tensor< double > geometric_series (long n, double a, double r)
int main ()
Tensor< double > map_tensor (double(*f)(double), const Tensor< double > &x)
double myexp (double x)
Tensor< double > optimize_coeffs (const Tensor< double > &f, const Tensor< double > &x, const Tensor< double > &w, const Tensor< double > &expnt, const double mu, const double p, const bool prnt=0)
double reciprocal (double x)
double square (double x)
Variables
const double c = 137.0359895
const double m = 1
const double mc2 = m*c*c
Function Documentation
Akernel()
double Akernel (double p)
References E0(), mc2, and p().
Referenced by main().
arithmetic_series()
Tensor<double> arithmetic_series (long n, double a, double h)
References a, h(), and q().
E0()
double E0 (double p)
References c, mc2, and p().
Referenced by Akernel(), ContractedGaussianShell::normalize(), and madness::ContractedGaussianShell::normalize().
errsq()
double errsq (const Tensor< double > f, const Tensor< double > x, const Tensor< double > w, const Tensor< double > c, const Tensor< double > expnt, const double mu, const double p)
References c, madness::f, fit(), mu, p(), pow(), madness::BaseTensor::size(), and madness::sum().
Referenced by Fred::gradient(), main(), test_math(), Fred::value(), and Fred::value_and_gradient().
fit()
double fit (double x, const Tensor< double > & c, const Tensor< double > & expnt)
References c, myexp(), madness::BaseTensor::size(), and madness::sum().
Referenced by errsq(), and main().
geometric_series()
Tensor<double> geometric_series (long n, double a, double r)
References a, and q().
Referenced by main().
main()
int main ()
References madness::abs(), Akernel(), c, e(), errsq(), madness::f, fit(), geometric_series(), h(), map_tensor(), max, mu, opt(), optimize_coeffs(), p(), pow(), madness::print(), madness::Tensor< T >::ptr(), reciprocal(), and madness::BaseTensor::size().
map_tensor()
Tensor<double> map_tensor (double(*)(double) f, const Tensor< double > & x)
References madness::copy(), madness::f, and madness::Tensor< T >::unaryop().
Referenced by main().
myexp()
double myexp (double x)
Referenced by fit(), Fred::make_g(), and optimize_coeffs().
optimize_coeffs()
Tensor<double> optimize_coeffs (const Tensor< double > & f, const Tensor< double > & x, const Tensor< double > & w, const Tensor< double > & expnt, const double mu, const double p, const bool prnt = 0)
References b, c, e(), madness::f, madness::gelss(), mu, myexp(), p(), pow(), and madness::BaseTensor::size().
Referenced by main(), and Fred::value_and_gradient().
reciprocal()
double reciprocal (double x)
Referenced by main().
square()
double square (double x)
Variable Documentation
c
const double c = 137.0359895
Referenced by E0(), errsq(), fit(), main(), optimize_coeffs(), and Fred::value_and_gradient().
m
const double m = 1
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), check(), madness::check_linear_dependence(), madness::column_distributed_matrix(), madness::column_distributed_matrix_distribution(), madness::guessfactory::compute_centroid(), madness::guessfactory::compute_centroids(), madness::LowRankTensor< T >::convert(), madness::copy_2d_patch(), madness::Molecule::core_derivative(), madness::CorePotentialManager::core_derivative(), madness::Molecule::core_eval(), madness::CorePotentialManager::core_eval(), madness::PotentialManager::core_projection(), madness::SCF::core_projection(), madness::PotentialManager::core_projector_derivative(), madness::SCF::core_projector_derivative(), madness::Solver< T, NDIM >::csqrt(), dgelss_(), dgesvd_(), dorgqr_(), madness::CoreOrbital::eval(), madness::CoreOrbital::eval_derivative(), madness::CoreOrbital::eval_spherical_harmonics(), madness::fast_transpose(), madness::fcube(), madness::gelss(), madness::cblas::gemm(), madness::cblas::gemv(), madness::geqp3(), madness::geqp3_result(), madness::cblas::ger(), madness::gesv(), madness::GaussianConvolution1DCache< Q >::get(), madness::projector_irrep::get_canonical_to_irrep_map(), matrix< FLOAT >::get_m(), MolecularMaskBase::gradient(), madness::BasisFunctions::guess_virtual_gaussian_shell(), madness::inner(), KAIN(), madness::KAIN(), madness::SystolicFixOrbitalOrders::kernel(), madness::Kinetic< double, 3 >::kinetic_energy_matrix(), madness::archive::VectorInputArchive::load(), madness::archive::BufferInputArchive::load(), madness::archive::MPIInputArchive::load(), AtomicBasisSet::load_tixml_matrix(), madness::AtomicBasisSet::load_tixml_matrix(), madness::lq(), madness::lq_result(), main(), make_nuclear_charge_density_individual(), Calculation::make_reference(), madness::BasisFunctions::make_solidharmonic_guess(), matrix< FLOAT >::matrix(), madness::matrix_inner(), madness::matrix_inner_old(), madness::ProjRLMStore::nlmproj(), madness::ProjRLMStore::nlmproj_functor(), matrix< FLOAT >::operator()(), OpFExact::operator()(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::operator()(), operator<<(), OpFExact::OpFExact(), madness::orgqr(), pounder(), madness::FunctionImpl< Q, NDIM >::print_stats(), madness::RMI::RmiTask::process_some(), madness::qr(), ExcitingApp::r3mv(), madness::rank_revealing_decompose(), madness::Derivative< T, NDIM >::read_from_file(), madness::row_distributed_matrix(), madness::row_distributed_matrix_distribution(), madness::archive::BufferOutputArchive::store(), madness::svd(), madness::svd_result(), test10(), test6(), test_in(), madness::Znemo::test_landau_wave_function(), test_opdir(), test_out(), madness::test_qr(), madness::test_svd(), madness::Zcis::transform(), madness::transform(), madness::TensorTrain< T >::truncate(), madness::SCF::update_response_subspace(), Subspace::update_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), madness::SCF::update_subspace(), and V().
mc2
const double mc2 = m*c*c
Referenced by Akernel(), and E0().