MADNESS: MADNESS libraries
MADNESS libraries
Modules
Containers
Parallel programming environment
Chemistry
Files
file constants.h
Defines common mathematical and physical constants.
file madness_config.h
Macros and tools pertaining to the configuration of MADNESS.
file madness_exception.cc
Implementation of madness::MadnessException.
file madness_exception.h
Defines madness::MadnessException for exception handling.By default, the MADNESS_ASSERT macro throws a madness::MadnessException. Configure options can specify other behaviors: MADNESS_ASSERT can be.
file mem_func_wrapper.h
Defines tools for encapsulating a pointer to a member function.The member pointer is stored, along with a pointer to the object with which it should be dereferenced.
file print.cc
Implementation of functions defined in print.h.
file print.h
Defines simple templates for printing to std::cout "a la Python".
file print_seq.h
Implements print_seq.
Functions
template<typename T >
std::ostream & madness::operator<< (std::ostream &s, const std::complex< T > &c)
Easy printing of complex numbers.
template<typename T , typename U >
std::ostream & madness::operator<< (std::ostream &s, const std::pair< T, U > &p)
Easy printing of pairs.
template<typename T >
std::ostream & madness::operator<< (std::ostream &s, const std::list< T > &c)
Easy printing of lists.
template<typename T >
std::ostream & madness::operator<< (std::ostream &s, const std::vector< T > &c)
Easy printing of vectors.
template<typename T , std::size_t N>
std::enable_if<!std::is_same< T, char >::value, std::ostream & >::type madness::operator<< (std::ostream &s, const T(&v)[N])
Easy printing of fixed dimension arrays.
template<typename T , typename... Ts>
void madness::print (const T &t, const Ts &... ts)
Print items to std::cout (items separated by spaces) and terminate with a new line.
void madness::print_centered (const char *s, int column=40, bool underline=true)
Print a string centered at the given column with optional underlining.
template<typename T , typename... Ts>
void madness::print_error (const T &t, const Ts &... ts)
Print items to std::cerr (items separated by spaces) and terminate with a new line.
std::ostream & madness::print_helper (std::ostream &out)
Helper function for print. Base case.
template<typename T , typename... Ts>
std::ostream & madness::print_helper (std::ostream &out, const T &t, const Ts &... ts)
Helper function for print. Prints the first item (t) and recursively passes on the other items.
void madness::print_justified (const char *s, int column=0, bool underline=true)
Print a string justified on the left to start at the given column with optional underlining.
Detailed Description
The MADNESS framework provides several container classes for convenience. They are described herein.
MADNESS is built from several libraries, such as the parallel runtime and the multiresolution analysis tools. The files and submodules listed here detail the API and implementation of these libraries.
Todo:
Add additional details to this section, if needed.
Function Documentation
operator<<() [1/5]
template<typename T > std::ostream& madness::operator<< (std::ostream & s, const std::complex< T > & c)
Easy printing of complex numbers.
Template Parameters
T The "real" type of the complex number.
Parameters
[in,out] s The output stream.
[in] c The complex number.
Returns
The output stream (for chaining).
References c.
operator<<() [2/5]
template<typename T , typename U > std::ostream& madness::operator<< (std::ostream & s, const std::pair< T, U > & p)
Easy printing of pairs.
Template Parameters
T Type 1 of the pair.
U Type 2 of the pair.
Parameters
[in,out] s The output stream.
[in] p The pair.
Returns
The output stream (for chaining).
References p().
operator<<() [3/5]
template<typename T > std::ostream& madness::operator<< (std::ostream & s, const std::list< T > & c)
Easy printing of lists.
Template Parameters
T Type stored in the list.
Parameters
[in,out] s The output stream.
[in] c The list.
Returns
The output stream (for chaining).
References c.
operator<<() [4/5]
template<typename T > std::ostream& madness::operator<< (std::ostream & s, const std::vector< T > & c)
Easy printing of vectors.
Template Parameters
T Type stored in the vector.
Parameters
[in,out] s The output stream.
[in] c The vector.
Returns
The output stream (for chaining).
References c.
operator<<() [5/5]
template<typename T , std::size_t N> std::enable_if<!std::is_same<T,char>::value, std::ostream&>::type madness::operator<< (std::ostream & s, const T(&) v[N])
Easy printing of fixed dimension arrays.
STL I/O already does char (thus the enable_if business).
Template Parameters
T Type of data in the array.
N Size of the array.
Parameters
[in,out] s The output stream.
[in] v The array.
Returns
The output stream (for chaining).
References N.
print()
template<typename T , typename... Ts> void madness::print (const T & t, const Ts &... ts)
Print items to std::cout (items separated by spaces) and terminate with a new line.
The first item is printed here so that it isn't preceded by a space.
Template Parameters
T Type of the first item to be printed.
Ts Argument pack type for the items to be printed.
Parameters
[in] t The first item to be printed.
[in] ts The remaining items to be printed in the argument pack.
References ENDL, madness::print_helper(), and madness::detail::printmutex.
Referenced by madness::detail::RemoteCounterBase::add_ref(), madness::Znemo::analyze(), madness::TDHF::analyze(), madness::apply(), madness::apply_only(), madness::projector_irrep::apply_symmetry_operators(), apply_U_mix(), apply_U_ncf(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), madness::BSHOperator(), madness::Solver< T, NDIM >::build_fock_matrix(), madness::SCF::calc_dpolar(), madness::SCF::calc_freq(), Calculation::calc_optimal_coeffs(), Calculation::Calculation(), check(), madness::TDHF::check_consistency(), check_err(), madness::check_linear_dependence(), check_multiplication_table_c2v(), check_operator_multiplications_2d(), check_operator_multiplications_3d(), madness::PNO::check_orthonormality(), check_small(), madness::Function< double, 6 >::check_symmetry(), madness::QCCalculationParametersBase::check_type(), madness::FunctionImpl< Q, NDIM >::coeffs_for_jun(), compare_calc_and_mos(), madness::Zcis::compare_to_file(), madness::FunctionImpl< Q, NDIM >::compress_op(), madness::FunctionImpl< Q, NDIM >::compress_spawn(), madness::Nemo::compute_all_cphf(), madness::OEP::compute_average_I(), madness::Znemo::compute_current_density(), compute_energy(), madness::Znemo::compute_energy(), compute_energy_with_U(), compute_frequencies(), madness::MolecularOptimizer::compute_frequencies(), madness::Nemo::compute_nemo_potentials(), madness::SRConf< T >::compute_nvec(), madness::OEP::compute_Pauli_kinetic_density(), compute_R2f2_psi(), madness::SCF::compute_residual(), madness::Zcis::compute_residuals(), madness::Znemo::compute_residuals(), Calculation::compute_residuals(), madness::OEP::compute_total_kinetic_density(), converge(), converge2s(), TestSystolicMatrixAlgorithm< T >::converged(), madness::PotentialManager::core_projection(), madness::SCF::core_projection(), madness::create_nuclear_correlation_factor(), madness::Solver< T, NDIM >::csqrt(), madness::Znemo::custom_guess(), madness::DependencyInterface::dec_debug(), madness::TensorTrain< T >::decompose(), madness::DependencyInterface::DependencyInterface(), madness::SCF::derivatives(), madness::detail::RemoteCounter::destroy(), madness::SCF::dipole(), dnuclear_anchor_test(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::SCF::do_step_restriction(), MiniDFT::doit(), doit(), doplot(), energy(), GygiPot::ESP(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), madness::XCfunctional::exc(), exchange_anchor_test(), madness::WorldGopInterface::fence(), fixphases(), TTT::fred(), Mary::galahad(), madness::gauss_legendre_test(), madness::GaussSlater::GaussSlater(), gen_ce(), madness::SRConf< T >::general_transform(), generate_G_vectors(), generate_R_vectors(), madness::MP2::get_fock_matrix(), madness::Znemo::get_initial_orbitals(), madness::MP2::get_residue(), madness::Znemo::gradient(), madness::Nemo::gradient(), CoreFittingTarget::gradient(), madness::GradientalGaussSlater::GradientalGaussSlater(), madness::SCF::group_orbital_sets(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_internal(), madness::hartree_product(), madness::Znemo::hcore_guess(), madness::Nemo::hessian(), madness::Molecule::identify_point_group(), madness::DependencyInterface::inc_debug(), madness::SCF::initial_guess(), initial_guess(), madness::Solver< T, NDIM >::initial_guess(), initial_loadbal(), madness::SCFProtocol::initialize(), madness::TDHF::initialize_singles(), iterate(), madness::Zcis::iterate(), madness::Znemo::iterate(), iterate_excite(), iterate_ground(), madness::PNO::iterate_pairs_internal(), iterate_xy(), KAIN(), madness::Nemo::kinetic_energy_potential(), madness::QuasiNewton::line_search(), QuasiNewton::line_search(), madness::LinearSlater::LinearSlater(), madness::detail::RemoteCounter::load_(), load_balance(), madness::LoadBalanceDeux< NDIM >::load_balance(), load_function(), madness::TDHF::load_function(), madness::Nemo::load_function(), madness::load_function(), Calculation::load_mos(), madness::ElectronPair::load_pair(), loadbal(), madness::SCF::localize_boys(), madness::SCF::localize_new(), madness::ThreadBase::main(), main(), TestCalculationParameters::make_all_parameter_doubles(), TestCalculationParameters::make_all_parameter_singles(), madness::SCF::make_bsh_operators(), madness::SCF::make_gradbsh_operators(), madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::Solver< T, NDIM >::make_nuclear_charge_density_impl(), madness::Solver< T, NDIM >::make_nuclear_potential(), Calculation::make_reference(), madness::SRConf< T >::make_slices(), madness::SeparatedConvolution< T, NDIM >::make_tt_representation(), makeao(), MolecularNuclearChargeDensityFunctor::MolecularNuclearChargeDensityFunctor(), MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), moments(), madness::Nemo::Nemo(), nuclear_anchor_test(), BoysLocalization::operator()(), madness::CompositeFunctorInterface< T, NDIM, MDIM >::operator()(), madness::TwoElectronInterface< double, 6 >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()(), madness::SCFProtocol::operator++(), madness::SliceLowRankTensor< T >::operator=(), madness::operator>>(), SteepestDescent::optimize(), madness::SteepestDescent::optimize(), madness::QuasiNewton::optimize(), QuasiNewton::optimize(), MySteepestDescent::optimize(), madness::MolecularOptimizer::optimize_conjugate_gradients(), madness::MolecularOptimizer::optimize_quasi_newton(), madness::Molecule::orient(), orth(), madness::SCF::orthonormalize(), madness::Solver< T, NDIM >::orthonormalize(), madness::LBDeuxPmap< NDIM >::owner(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), Foo::ping(), Foo::ping_am(), madness::BandlimitedPropagator::plot(), madness::plot_cubefile(), madness::plot_plane(), plot_symmetry_operators(), madness::PNO::pno_compress(), madness::SCF::polarizability(), madness::poly4erfc::poly4erfc(), madness::Polynomial< N >::Polynomial(), Foo::pong(), Foo::pong_am(), preloadbal(), madness::XCOperator::prep_xc_args_response(), madness::LBDeuxPmap< NDIM >::print(), madness::MyPmap< D >::print(), madness::Timer::print(), madness::QCCalculationParametersBase::print(), madness::projector_irrep::print_character_table(), madness::WorldDCPmapInterface< Key< D > >::print_data_sizes(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), madness::Diamagnetic_potential_factor::print_info(), madness::projector_irrep::print_info(), Calculation::print_info(), madness::F12Potentials::print_pair_energies(), madness::Solver< T, NDIM >::print_potential_matrix_eigs(), madness::print_seq(), madness::Function< double, 6 >::print_size(), madness::FunctionImpl< Q, NDIM >::print_stats(), madness::LoadBalanceDeux< NDIM >::print_tree(), Calculation::project_potential_basis(), madness::MolecularOptimizer::projector_external_dof(), propagate(), madness::PseudoNuclearCorrelationFactor::PseudoNuclearCorrelationFactor(), madness::Nemo::purify_hessian(), madness::TensorTrain< T >::ranks(), Plotter::read(), madness::Znemo::read_complex_guess(), madness::Molecule::read_core_file(), madness::Znemo::read_explicit_guess_functions(), madness::CorePotentialManager::read_file(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), madness::Zcis::read_guess(), madness::QCCalculationParametersBase::read_internal(), madness::Znemo::read_real_guess(), madness::Znemo::read_reference(), madness::MolecularOrbitals< T, NDIM >::read_restartaodata(), madness::Znemo::read_restartaodata(), read_test_data(), madness::Znemo::recompute_factors_and_potentials(), madness::SRConf< T >::reconstruct(), reconstruct_psi(), madness::FunctionImpl< Q, NDIM >::recursive_apply(), madness::projector_irrep::reduce(), madness::DependencyInterface::register_callback(), madness::DependencyInterface::register_final_callback(), madness::detail::RemoteCounter::register_ptr_(), madness::detail::RemoteCounterBase::release(), madness::SCF::restart_aos(), TestTask::run(), TestBarrier::run(), run_all_calculations(), save_function(), madness::Nemo::save_function(), madness::save_function(), madness::Zcis::save_guess(), madness::Znemo::save_orbitals(), madness::FunctionNode< T, NDIM >::set_coeff(), madness::XCOperator::set_extra_truncation(), madness::Function< double, 6 >::set_functor(), madness::projector_irrep::set_irrep(), madness::projector_irrep::set_ordering(), madness::SCF::set_protocol(), Calculation::set_protocol(), madness::Slater::Slater(), madness::PNO::solve(), madness::SpectralPropagator::solve(), SVPESolver::solve(), madness::Nemo::solve(), solve(), madness::SCF::solve(), madness::Solver< T, NDIM >::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), squareit(), madness::startup(), madness::SpectralPropagator::step(), madness::SpectralPropagatorGaussLobatto::step(), madness::Solver< T, NDIM >::step_restriction(), madness::archive::BufferOutputArchive::store(), madness::detail::RemoteCounter::store_(), madness::symmetrize(), madness::PNO::t_solve(), madness::IndexIterator::test(), test(), madness::Znemo::test(), test0(), test0GaussLobatto(), test1(), test10(), test11(), test12(), test13(), test2(), test5(), test6(), test6a(), Test7(), test7(), test8(), test9(), test_adaptive_tree(), test_add(), test_apply_push_1d(), test_asymmetric(), test_basic(), test_bsh(), test_capitalization(), test_chin_chen(), test_comment_lines(), test_compress(), madness::Znemo::test_compute_current_density(), test_conv(), test_convolution(), test_coulomb(), test_cross(), test_derived(), test_diff(), test_dnuclear(), test_empty_lines(), test_exchange(), test_G_R_vectors(), test_gaussian_num_coeffs(), test_gconv(), test_hartree_product(), test_hermiticity(), test_hf_be(), test_hydro(), test_inner(), test_io(), test_kinetic(), madness::Znemo::test_landau_wave_function(), test_lda(), test_math(), madness::Diamagnetic_potential_factor::test_me(), test_modified(), test_multi(), test_multi_to_multi_op(), test_multiply(), test_nemo(), test_not_allowed(), test_nuclear(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), madness::OEP::test_oep(), test_op(), test_opdir(), test_orthogonalization(), test_per(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), test_plot(), test_proj(), test_projector(), test_qm(), test_recursive_application(), test_rot(), test_same(), test_slater_exchange(), test_smooth_maxout(), test_spherical_box(), test_trailing_characters(), test_trotter(), test_truncation(), test_type_conversion1(), test_type_conversion2(), test_type_conversion3(), test_type_conversion4(), test_type_conversion5(), test_type_conversion6(), test_type_conversion7(), test_type_conversion8(), test_U_el(), test_unaryop(), test_xcfunctional(), test_XCOperator(), TestBarrier::TestBarrier(), testbsh(), testgradG(), testNavierStokes(), TestSystolicMatrixAlgorithm< T >::TestSystolicMatrixAlgorithm(), madness::SCF::this_axis(), TimeBarrier::TimeBarrier(), trotter(), madness::NuclearCorrelationFactor::U2X_spherical(), madness::NonlinearSolverND< NDIM >::update(), update(), madness::XNonlinearSolver< T, C, Alloc >::update(), MiniDFT::update(), madness::PNO::update_pno(), madness::SCF::update_response_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), madness::SCF::update_subspace(), madness::Nemo::value(), CoreFittingTarget::value(), madness::FunctionImpl< Q, NDIM >::verify_tree(), madness::XCfunctional::vxc(), walker2(), madness::Zcis::Zcis(), B::~B(), madness::DependencyInterface::~DependencyInterface(), and madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::~FutureImpl().
print_centered()
void madness::print_centered (const char * s, int column, bool underline)
Print a string centered at the given column with optional underlining.
References madness::print_justified().
print_error()
template<typename T , typename... Ts> void madness::print_error (const T & t, const Ts &... ts)
Print items to std::cerr (items separated by spaces) and terminate with a new line.
The first item is printed here so that it isn't preceded by a space.
Template Parameters
T Type of the first item to be printed.
Ts Argument pack type for the items to be printed.
Parameters
[in] t The first item to be printed.
[in] ts The remaining items to be printed in the argument pack.
References ENDL, madness::print_helper(), and madness::detail::printmutex.
Referenced by madness::RMI::RmiTask::exit(), madness::RMI::isend(), madness::RMI::RmiTask::process_some(), and madness::RMI::RmiTask::RmiTask().
print_helper() [1/2]
std::ostream& madness::print_helper (std::ostream & out) inline
Helper function for print. Base case.
This gets called recursively when there are no items left to print.
Parameters
[in,out] out Output stream.
Returns
The output stream (for chaining).
Referenced by madness::print(), madness::print_error(), and madness::print_helper().
print_helper() [2/2]
template<typename T , typename... Ts> std::ostream& madness::print_helper (std::ostream & out, const T & t, const Ts &... ts) inline
Helper function for print. Prints the first item (t) and recursively passes on the other items.
Template Parameters
T Type of the item to print in this call.
Ts Argument pack type for the remaining items.
Parameters
[in,out] out Output stream.
[in] t The item to print in this call.
[in] ts The remaining items in the argument pack (they get recursively passed on).
Returns
The output stream (for chaining).
References madness::print_helper().
print_justified()
void madness::print_justified (const char * s, int column, bool underline)
Print a string justified on the left to start at the given column with optional underlining.
References ENDL.
Referenced by madness::print_centered().