MADNESS: h2.cc File Reference
h2.cc File Reference
Solves the Hartree-Fock equations for the hydrogen molecule.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
Functions
static double guess (const coord_3d &r)
void iterate (World &world, real_function_3d &V, real_function_3d &psi, double &eps)
int main (int argc, char **argv)
static double V (const coord_3d &r)
Variables
static const long k = 8
static const double L = 64.0*R
static const double R = 1.4
static const double thresh = 1e-6
Detailed Description
Solves the Hartree-Fock equations for the hydrogen molecule.
Function Documentation
guess()
static double guess (const coord_3d & r) static
References e(), and R.
Referenced by main().
iterate()
void iterate (World & world, real_function_3d & V, real_function_3d & psi, double & eps)
References madness::BSHOperator3D(), e(), madness::inner(), madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), and V().
Referenced by main().
main()
int main (int argc, char ** argv)
References axis, SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, guess(), madness::initialize(), madness::inner(), iterate(), k, L, op(), potential(), madness::print(), psi(), R, madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, and V().
V()
static double V (const coord_3d & r) static
References e(), and R.
Referenced by iterate(), and main().
Variable Documentation
k
const long k = 8 static
Referenced by main().
L
const double L = 64.0*R static
Referenced by main().
R
const double R = 1.4 static
Referenced by guess(), main(), and V().
thresh
const double thresh = 1e-6 static
Referenced by main().