MADNESS: lda.h File Reference
lda.h File Reference
#include <madness/mra/mra.h>
#include <madness/world/MADworld.h>
#include <math.h>
#include <madness/madness_config.h>
#include <cmath>
Macros
#define max(a, b) ((a)>=(b)?(a):(b))
Typedefs
typedef double doublereal
typedef MADNESS_FORINT integer
typedef int logical
Functions
int c_rks_vwn5__ (const double *r__, double *f, double *dfdra)
int c_uks_vwn5__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
template<int NDIM>
void dft_xc_lda_ene (const Key< NDIM > &key, Tensor< double > &t)
template<int NDIM>
void dft_xc_lda_V (const Key< NDIM > &key, Tensor< double > &t)
static double pow (const double *a, const double *b)
int rks_c_vwn5__ (integer *ideriv, integer *npt, doublereal *rhoa1, doublereal *sigmaaa1, doublereal *zk, doublereal *vrhoa, doublereal *vsigmaaa, doublereal *v2rhoa2, doublereal *v2rhoasigmaaa, doublereal *v2sigmaaa2)
int rks_x_lda__ (integer *ideriv, integer *npt, doublereal *rhoa1, doublereal *sigmaaa1, doublereal *zk, doublereal *vrhoa, doublereal *vsigmaaa, doublereal *v2rhoa2, doublereal *v2rhoasigmaaa, doublereal *v2sigmaaa2)
void wst_munge_grho (int npoint, double *rho, double *grho)
void wst_munge_rho (int npoint, double *rho)
int x_rks_s__ (const double *r__, double *f, double *dfdra)
int x_uks_s__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
void xc_rks_generic_lda (Tensor< double > rho_alpha, Tensor< double > f, Tensor< double > df_drho)
Variables
static double c_b14 = 1.333333333333333333333333333333
static double c_b2 = .333333333333333333333333333333333
static double c_b7 = .333333333333333333333333333333
static double c_b8 = .5
const double THRESH_GRHO = 1e-20
const double THRESH_RHO = 1e-8
Macro Definition Documentation
max
#define max (a, b) ((a)>=(b)?(a):(b))
Referenced by madness::apply(), madness::GTHPseudopotential< Q >::apply_potential(), madness::AtomicBasis::AtomicBasis(), AtomicBasis::AtomicBasis(), MolecularEntity::bounding_cube(), madness::Molecule::bounding_cube(), madness::WorldGopInterface::broadcast(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), madness::RMI::clear_send_req(), converge(), converge2s(), madness::DistributedMatrix< double >::copy_from_replicated_patch(), madness::DistributedMatrix< double >::copy_to_replicated_patch(), madness::TensorTrain< T >::decompose(), madness::FunctionImpl< Q, NDIM >::do_apply(), madness::FunctionImpl< Q, NDIM >::do_apply_directed_screening(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), doit(), dsyev_(), dsygv_(), CubicInterpolationTable< double_complex >::err(), GygiPot::ESP(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), madness::DistributedMatrix< double >::extract_columns(), fixphases(), madness::FunctionImpl< Q, NDIM >::FunctionImpl(), madness::gelss(), madness::general_transform(), madness::PNO::get_average_rank(), madness::SCF::get_fock_transformation(), madness::trajectory< NDIM >::hueCode(), madness::DependencyInterface::inc_debug(), madness::FunctionImpl< Q, NDIM >::insert_zero_down_to_initial_level(), madness::Key< OPDIM >::is_neighbor_of(), jacobi(), madness::SCF::localize_boys(), madness::SCF::localize_new(), main(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::GaussianConvolution1D< Q >::maxR(), madness::SeparatedConvolution< T, NDIM >::munorm2_ns(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast(), madness::xc_lda_potential::operator()(), madness::dens_inv1::operator()(), BoysLocalization::operator()(), madness::XCOperator::logme::logme1::operator()(), madness::FunctionImpl< T, NDIM >::do_convert_to_color::operator()(), madness::ortho5(), madness::NemoBase::orthonormalize(), madness::Zcis::orthonormalize(), madness::SCF::orthonormalize(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), madness::FunctionImpl< Q, NDIM >::plot_cube_kernel(), madness::SCF::polarizability(), madness::DQueue< madness::PoolTaskInterface *>::pop_front(), madness::QCParameter::print_line(), madness::PNO::print_ranks(), madness::Nemo::purify_hessian(), madness::rank_revealing_decompose(), madness::Znemo::read_explicit_guess_functions(), madness::SCF::residual_response(), rks_c_vwn5__(), rks_x_lda__(), madness::SDFRectangle::sdf(), madness::SDFBox::sdf(), madness::SDFCylinder::sdf(), madness::QCParameter::set_derived_value(), madness::BaseTensor::set_dims_and_size(), madness::SCF::set_protocol(), Calculation::set_protocol(), madness::QCParameter::set_user_defined_value(), madness::GFit< T, NDIM >::slater_fit(), MolecularEntity::smallest_length_scale(), madness::Molecule::smallest_length_scale(), SVPESolver::solve(), madness::SCF::solve(), madness::SystolicPMOrbitalLocalize::start_iteration_hook(), madness::svd(), madness::syev(), madness::sygv(), OptimizationTargetInterface::test_gradient(), madness::OptimizationTargetInterface::test_gradient(), madness::test_rnlp(), madness::test_syev(), madness::test_sygv(), madness::TensorTrain< T >::trace(), madness::transform(), madness::TensorTrain< T >::truncate(), madness::SCF::update_response_subspace(), and madness::SCF::update_subspace().
Typedef Documentation
doublereal
typedef double doublereal
integer
typedef MADNESS_FORINT integer
logical
typedef int logical
Function Documentation
c_rks_vwn5__()
int c_rks_vwn5__ (const double * r__, double * f, double * dfdra) inline
References a2, madness::c_b7, c_b8, madness::f, and pow().
c_uks_vwn5__()
int c_uks_vwn5__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb) inline
References a1, a2, madness::c_b14, madness::c_b7, madness::f, f1, f2, f3, pow(), ss1, and zeta.
dft_xc_lda_ene()
template<int NDIM> void dft_xc_lda_ene (const Key< NDIM > & key, Tensor< double > & t) inline
References madness::___, madness::copy(), V(), and xc_rks_generic_lda().
dft_xc_lda_V()
template<int NDIM> void dft_xc_lda_V (const Key< NDIM > & key, Tensor< double > & t) inline
References madness::___, madness::copy(), V(), and xc_rks_generic_lda().
pow()
static double pow (const double * a, const double * b) inline static
References a, and b.
Referenced by madness::FunctionImpl< Q, NDIM >::add_scalar_inplace(), analytical_slater_functor(), madness::BandlimitedPropagator::BandlimitedPropagator(), madness::Specialbox_op< T, NDIM >::box_is_at_boundary(), madness::FunctionImpl< Q, NDIM >::broaden(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), madness::GFit< T, NDIM >::bsh_spherical_moments(), madness::c_rks_vwn5__(), c_rks_vwn5__(), madness::c_uks_vwn5__(), c_uks_vwn5__(), madness::SCF::calc_dpolar(), charge_function(), madness::SlaterF12Interface::coeff(), madness::FunctionImpl< Q, NDIM >::coeffs2values(), madness::guessfactory::PolynomialFunctor::compute_value(), madness::guessfactory::PolynomialTrigonometricsFunctor::compute_value(), converge(), madness::Diamagnetic_potential_factor::custom_factor(), madness::FunctionImpl< Q, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< Q, NDIM >::do_binary_op(), madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::do_diff2i(), madness::FunctionImpl< Q, NDIM >::do_mul(), madness::FunctionImpl< Q, NDIM >::do_print_grid(), madness::FunctionImpl< Q, NDIM >::err_box(), errsq(), madness::SeparatedConvolution< T, NDIM >::estimate_costs(), madness::CorePotential::eval(), madness::FunctionImpl< Q, NDIM >::eval_cube(), madness::CorePotential::eval_derivative(), madness::CoreOrbital::eval_radial(), madness::CoreOrbital::eval_radial_derivative(), exact_function(), madness::F12Potentials::F12Potentials(), madness::fcube(), function(), fxexact(), fyexact(), fzexact(), madness::BandlimitedPropagator::g0_filtered(), smooth< T, NDIM >::gauss_norm(), gaussian(), gaussian1(), gaussian2(), gaussian3(), madness::GFit< T, NDIM >::gaussian_spherical_moments(), smooth< T, NDIM >::get_density_thresh(), madness::GradBSHOperator(), madness::GradCoulombOperator(), madness::GradSlaterOperator(), madness::Derivative< T, NDIM >::initCoefficients(), madness::TwoElectronInterface< double, 6 >::initialize(), madness::FunctionImpl< Q, NDIM >::inner_ext_recursive(), madness::GaussianConvolution1D< Q >::issmall(), iterate(), main(), mask(), madness::FunctionImpl< Q, NDIM >::mul(), ContractedGaussianShell::normalize(), madness::ContractedGaussianShell::normalize(), madness::FunctionImpl< Q, NDIM >::NScoeffs2values(), nuc_func(), nuclear_charge_function(), madness::Molecule::nuclear_repulsion_second_derivative(), uexact::operator()(), Charge::operator()(), GygiPot::Pow< T, DIM >::operator()(), GygiPot::Pow_beta_one< T, DIM >::operator()(), slater_kernel::operator()(), Uop::operator()(), apply_kernel_helper::slater_kernel::operator()(), PotentialBasisFunctor::operator()(), madness::BasisFunctions::CartesianGaussian::operator()(), madness::BasisFunctions::SolidHarmonicGaussian::operator()(), madness::NuclearCorrelationFactor::R_functor::operator()(), madness::Znemo::landau_wave_function::operator()(), madness::GenericConvolution1D< Q, opT >::Shmoo::operator()(), QMtest::operator()(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), OpFExact::OpFExact(), optimize_coeffs(), madness::FunctionImpl< Q, NDIM >::parent_to_child(), madness::PeriodicBSHOp(), madness::PeriodicBSHOpPtr(), madness::PeriodicCoulombOp(), madness::PeriodicCoulombOpPtr(), madness::FunctionImpl< Q, NDIM >::phi_for_mul(), madness::XCfunctional::plot(), plot(), madness::FunctionImpl< Q, NDIM >::plot_cube_kernel(), madness::power(), madness::FunctionImpl< Q, NDIM >::print_plane_local(), madness::FunctionImpl< Q, NDIM >::print_stats(), madness::FunctionImpl< Q, NDIM >::project(), madness::ProjRLMFunctor::ProjRLMFunctor(), random_gaussian(), RandomGaussian(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), refpotfunctor::refpotfunctor(), rho_function(), rho_gaussian_func3d(), madness::Convolution1D< Q >::rnlij(), madness::GaussianConvolution1D< Q >::rnlp(), madness::SeparatedConvolution< T, NDIM >::SeparatedConvolution(), simpt2key(), madness::simpt2key(), madness::GFit< T, NDIM >::slater_fit(), madness::smoothed_density(), smoothing_parameter(), madness::smoothing_parameter(), madness::SmoothingOperator(), madness::SmoothingOperator3D(), test(), smooth< T, NDIM >::test_1d(), test_apply_push_1d(), test_basic(), test_bsh(), test_conv(), test_coulomb(), test_diff(), test_gaussian_num_coeffs(), OptimizationTargetInterface::test_gradient(), madness::OptimizationTargetInterface::test_gradient(), test_io(), test_math(), test_op(), test_opdir(), test_periodic(), test_periodic1(), test_plot(), test_proj(), test_smooth_maxout(), test_spherical_box(), madness::Key< OPDIM >::thisKeyContains(), madness::FunctionImpl< Q, NDIM >::trace_local(), madness::FunctionImpl< Q, NDIM >::truncate_tol(), uexact(), uinitial(), updatex(), GaussianGuess< T, NDIM >::val(), Fred::value_and_gradient(), madness::FunctionImpl< Q, NDIM >::values2coeffs(), madness::FunctionImpl< Q, NDIM >::values2NScoeffs(), Vdynamic(), madness::FunctionImpl< Q, NDIM >::vol_nsphere(), madness::x_rks_s__(), x_rks_s__(), madness::x_uks_s__(), x_uks_s__(), and xc_functor< NDIM >::xc_potential().
rks_c_vwn5__()
int rks_c_vwn5__ (integer * ideriv, integer * npt, doublereal * rhoa1, doublereal * sigmaaa1, doublereal * zk, doublereal * vrhoa, doublereal * vsigmaaa, doublereal * v2rhoa2, doublereal * v2rhoasigmaaa, doublereal * v2sigmaaa2) inline
References madness::c_b2, e(), and max.
Referenced by xc_rks_generic_lda().
rks_x_lda__()
int rks_x_lda__ (integer * ideriv, integer * npt, doublereal * rhoa1, doublereal * sigmaaa1, doublereal * zk, doublereal * vrhoa, doublereal * vsigmaaa, doublereal * v2rhoa2, doublereal * v2rhoasigmaaa, doublereal * v2sigmaaa2) inline
References madness::c_b2, e(), and max.
Referenced by xc_rks_generic_lda().
wst_munge_grho()
void wst_munge_grho (int npoint, double * rho, double * grho) inline
References THRESH_GRHO, and THRESH_RHO.
wst_munge_rho()
void wst_munge_rho (int npoint, double * rho) inline
References THRESH_RHO.
Referenced by xc_rks_generic_lda().
x_rks_s__()
int x_rks_s__ (const double * r__, double * f, double * dfdra) inline
References madness::c_b2, madness::f, and pow().
x_uks_s__()
int x_uks_s__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb) inline
References madness::c_b2, madness::f, and pow().
xc_rks_generic_lda()
void xc_rks_generic_lda (Tensor< double > rho_alpha, Tensor< double > f, Tensor< double > df_drho) inline
Parameters
rho_alpha Alpha-spin density at each grid point
f Value of functional at each grid point
df_drho Derivative of functional w.r.t. rho_alpha
References madness::BaseTensor::dim(), madness::f, madness::Tensor< T >::fill(), madness::Tensor< T >::flat(), madness::Tensor< T >::gaxpy(), madness::BaseTensor::iscontiguous(), MADNESS_ASSERT, madness::Tensor< T >::ptr(), rks_c_vwn5__(), rks_x_lda__(), and wst_munge_rho().
Referenced by dft_xc_lda_ene(), and dft_xc_lda_V().
Variable Documentation
c_b14
double c_b14 = 1.333333333333333333333333333333 static
c_b2
double c_b2 = .333333333333333333333333333333333 static
c_b7
double c_b7 = .333333333333333333333333333333 static
c_b8
double c_b8 = .5 static
Referenced by c_rks_vwn5__().
THRESH_GRHO
const double THRESH_GRHO = 1e-20
Referenced by wst_munge_grho().
THRESH_RHO
const double THRESH_RHO = 1e-8
Referenced by wst_munge_grho(), and wst_munge_rho().