MADNESS: libxc.h File Reference
libxc.h File Reference
#include <madness/mra/mra.h>
#include <madness/world/MADworld.h>
#include "lda.h"
Functions
template<typename T >
static void ldaeop (const Key< 3 > &key, Tensor< T > &t)
template<typename T >
static void ldaop (const Key< 3 > &key, Tensor< T > &t)
static double munge (double r)
Function Documentation
ldaeop()
template<typename T > static void ldaeop (const Key< 3 > & key, Tensor< T > & t) inline static
References madness::c_rks_vwn5__(), munge(), UNARY_OPTIMIZED_ITERATOR, and madness::x_rks_s__().
Referenced by madness::DFT< T, NDIM >::calculate_tot_xc_energy().
ldaop()
template<typename T > static void ldaop (const Key< 3 > & key, Tensor< T > & t) inline static
References madness::c_rks_vwn5__(), munge(), q(), UNARY_OPTIMIZED_ITERATOR, and madness::x_rks_s__().
munge()
static double munge (double r) static
References e().
Referenced by ldaeop(), and ldaop().