MADNESS: testperiodic.cc File Reference
madness/mra/testperiodic.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Typedefs
typedef Vector< double, 3 > coordT
Functions
int main (int argc, char **argv)
double potential (const coordT &r)
double_complex pw_lhs (const coord_3d &r)
double_complex pw_rhs (const coord_3d &r)
double source (const coordT &r)
double source1 (const coord_1d &r)
void test_periodic (World &world)
void test_periodic1 (World &world)
void test_periodic2 (World &world)
int test_periodic_bsh (World &world)
double u (const double x, const double expnt)
Variables
int G0 = 1
int G1 = 2
int G2 = 2
double k0 = 1.0
double k1 = 1.0
double k2 = 0.0
const double L = 3.0
double mu
const int nwave = 2
const char * status [2] = {"FAIL !!!!!","PASS"}
Typedef Documentation
coordT
typedef Vector<double,3> coordT
Function Documentation
main()
int main (int argc, char ** argv)
References madness::BC_PERIODIC, SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::FunctionDefaults< NDIM >::set_bc(), madness::startup(), and test_periodic2().
potential()
double potential (const coordT & r)
References L, nwave, madness::constants::pi, and source().
Referenced by test_periodic2().
pw_lhs()
double_complex pw_lhs (const coord_3d & r)
References G0, G1, G2, k0, k1, k2, L, and madness::constants::pi.
Referenced by test_periodic_bsh().
pw_rhs()
double_complex pw_rhs (const coord_3d & r)
References G0, G1, G2, k0, k1, k2, L, mu, and madness::constants::pi.
Referenced by test_periodic_bsh().
source()
double source (const coordT & r)
References L, nwave, and madness::constants::pi.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply(), madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::displacement(), madness::FunctionImpl< Q, NDIM >::do_apply(), madness::FunctionImpl< Q, NDIM >::do_apply_directed_screening(), madness::SeparatedConvolution< T, NDIM >::estimate_costs(), madness::SeparatedConvolution< T, NDIM >::get_source_key(), madness::SeparatedConvolution< T, NDIM >::getmuop_modified(), madness::SeparatedConvolution< T, NDIM >::getop(), madness::SeparatedConvolution< T, NDIM >::getop_modified(), madness::WorldMpiInterface::Irecv(), madness::SeparatedConvolution< T, NDIM >::make_tt_representation(), madness::op_leaf_op< T, NDIM, opT >::operator()(), madness::Leaf_op< T, NDIM, SeparatedConvolution< double, NDIM >, Specialbox_op< T, NDIM > >::post_screening(), potential(), putwa_(), SafeMPI::Intracomm::Recv(), madness::WorldGopInterface::recv(), SafeMPI::Status::Set_source(), madness::AmArg::set_src(), madness::archive::ArchiveStoreImpl< ParallelOutputArchive, WorldContainer< keyT, valueT > >::store(), test_periodic(), and test_periodic2().
source1()
double source1 (const coord_1d & r)
References L, nwave, and madness::constants::pi.
Referenced by test_periodic1().
test_periodic()
void test_periodic (World & world)
References e(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, op(), madness::constants::pi, pow(), madness::print(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), source(), status, thresh, and u().
test_periodic1()
void test_periodic1 (World & world)
References e(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, op(), madness::constants::pi, pow(), madness::print(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), source1(), status, thresh, and u().
test_periodic2()
void test_periodic2 (World & world)
References madness::CoulombOperator(), e(), exact(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, op(), potential(), madness::print(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), source(), status, and thresh.
Referenced by main().
test_periodic_bsh()
int test_periodic_bsh (World & world)
References std::abs(), madness::apply(), madness::BSHOperator3D(), e(), exact(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, mu, op(), madness::print(), pw_lhs(), pw_rhs(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), status, and thresh.
u()
double u (const double x, const double expnt)
References L, nwave, and madness::constants::pi.
Referenced by apply_potential(), applyexpLt(), applyN(), madness::checksum_file(), madness::Stack< T, N >::clear(), madness::TensorTrain< T >::decompose(), GygiPot::dESP_drho(), dgesvd_(), doit(), madness::CorePotential::eval(), madness::FunctionImpl< Q, NDIM >::eval_cube(), madness::CorePotential::eval_derivative(), expL_double(), hamiltonian_matrix(), madness::hash_value(), hashbig(), hashlittle(), hashlittle2(), jacobi(), Calculation::load_mos(), main(), SVPESolver::make_surface_charge(), SurfaceMoleculeInteraction::make_surfcharge(), GygiPot::make_surfcharge(), moments(), madness::Stack< T, N >::move(), N_double(), normalize2(), madness::Molecule::nuclear_attraction_potential_second_derivative(), madness::CCConvolutionOperator::operator()(), madness::Stack< T, N >::push(), madness::WorldTaskQueue::remote_task_handler(), madness::Stack< T, N >::reset(), madness::Molecule::set_all_coords(), SVPESolver::solve(), madness::WorldObject< TestFutureForwarding >::spawn_remote_task_handler(), madness::TaskFn< fnT, arg1T, arg2T, arg3T, arg4T, arg5T, arg6T, arg7T, arg8T, arg9T >::TaskFn(), test(), test0(), test0GaussLobatto(), test1(), test_periodic(), test_periodic1(), test_U_el(), testNavierStokes(), madness::NonlinearSolverND< NDIM >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::CCPair::update_u(), and GygiPot::V_epsilon().
Variable Documentation
G0
int G0 = 1
Referenced by pw_lhs(), pw_rhs(), test_chin_chen(), test_trotter(), and trotter().
G1
int G1 = 2
Referenced by pw_lhs(), and pw_rhs().
G2
int G2 = 2
Referenced by compute_madelung_energy(), compute_madelung_energy_PWSCF(), EwaldNuclearPotentialFunctor::do_G_sum_v2(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), pw_lhs(), and pw_rhs().
k0
double k0 = 1.0
Referenced by madness::apply(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::Solver< T, NDIM >::genkmesh(), madness::inner(), madness::inner_result(), kinetic_energy_matrix_slow(), KPoint::KPoint(), madness::TensorTrain< T >::make_operator(), madness::FunctionImpl< Q, NDIM >::print_stats(), pw_lhs(), pw_rhs(), and madness::Solver< T, NDIM >::solve().
k1
double k1 = 1.0
Referenced by madness::Solver< T, NDIM >::apply_hf_exchange(), madness::SCF::calc_exchange_function(), madness::LowRankTensor< T >::convert(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::Solver< T, NDIM >::find_kpt_from_orb(), madness::Solver< T, NDIM >::genkmesh(), madness::inner(), madness::inner_result(), kinetic_energy_matrix_slow(), KPoint::KPoint(), madness::outer(), pw_lhs(), pw_rhs(), madness::Solver< T, NDIM >::solve(), and madness::TensorTrain< T >::splitdim().
k2
double k2 = 0.0
Referenced by madness::Solver< T, NDIM >::apply_hf_exchange(), madness::SCF::calc_exchange_function(), madness::LowRankTensor< T >::convert(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), Key::foreach_child(), madness::Solver< T, NDIM >::genkmesh(), kinetic_energy_matrix_slow(), KPoint::KPoint(), madness::TensorTrain< T >::make_operator(), madness::outer(), pw_lhs(), pw_rhs(), madness::Solver< T, NDIM >::solve(), and madness::TensorTrain< T >::splitdim().
L
const double L = 3.0
Referenced by potential(), pw_lhs(), pw_rhs(), source(), source1(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), and u().
mu
double mu
Referenced by pw_rhs(), and test_periodic_bsh().
nwave
const int nwave = 2
Referenced by potential(), source(), source1(), and u().
status
const char* status[2] = {"FAIL !!!!!","PASS"}
Referenced by madness::Hash_private::bin< keyT, valueT >::del(), errmsg(), madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), main(), madness::profiling::TaskEvent::print_demangled(), madness::WorldMpiInterface::Recv(), SafeMPI::Intracomm::Recv(), madness::RMI::set_debug(), madness::WorldGopInterface::set_debug(), SafeMPI::Request::Test(), SafeMPI::Request::Test_got_lock_already(), test_in(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), and SafeMPI::Request::Testany().