MADNESS: mentity.h File Reference
mentity.h File Reference
#include <vector>
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <ctype.h>
#include <cmath>
#include <madness/misc/misc.h>
Classes
class Atom
struct AtomicData
class MolecularEntity
Macros
#define MENTITY_H_
Functions
const AtomicData & get_atomic_data (unsigned int atn)
std::ostream & operator<< (std::ostream &s, const Atom &atom)
unsigned int symbol_to_atomic_number (const std::string &symbol)
Macro Definition Documentation
MENTITY_H_
#define MENTITY_H_
Function Documentation
get_atomic_data()
const AtomicData& get_atomic_data (unsigned int atn)
References madness::atomic_data, and madness::NUMBER_OF_ATOMS_IN_TABLE.
Referenced by madness::Molecule::add_atom(), madness::Atom::Atom(), madness::Molecule::print(), AtomicBasisSet::print(), madness::AtomicBasisSet::print(), AtomicBasisSet::print_all(), madness::AtomicBasisSet::print_all(), AtomicBasisSet::print_anal(), and madness::AtomicBasisSet::print_anal().
operator<<()
std::ostream& operator<< (std::ostream & s, const Atom & atom)
symbol_to_atomic_number()
unsigned int symbol_to_atomic_number (const std::string & symbol)
References madness::atomic_data, madness::lowercase(), madness::NUMBER_OF_ATOMS_IN_TABLE, and madness::AtomicData::symbol_lowercase.
Referenced by Calculation::Calculation(), madness::get_charge_from_file(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), madness::Molecule::read(), MolecularEntity::read_file(), madness::CorePotentialManager::read_file(), AtomicBasisSet::read_file(), and madness::AtomicBasisSet::read_file().