MADNESS: miketest.cc File Reference
miketest.cc File Reference
#include <iostream>
#include <cstdio>
#include <complex>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include "tensor.h"
Functions
int main ()
Function Documentation
main()
int main ()
References c, madness::fast_transform(), k, madness::transform(), and transform3d().