MADNESS: test_mtxmq.cc File Reference
mtxmq_graveyard/bgp_tuning/test_mtxmq.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <cmath>
#include <madness/tensor/cblas.h>
#include "rdtsc.h"
Functions
int main (int argc, char **argv)
void mTxm (long dimi, long dimj, long dimk, double *c, const double *a, const double *b)
void mTxm_dgemm (long ni, long nj, long nk, double *c, const double *a, const double *b)
void mTxm_tune (long dimi, long dimj, long dimk, double *c, const double *a, const double *b)
void mTxmq (long dimi, long dimj, long dimk, double *c, const double *a, const double *b)
double ran ()
void ran_fill (int n, double *a)
void timer (const char *s, long ni, long nj, long nk, double *a, double *b, double *c)
void trantimer (const char *s, long ni, long nj, long nk, double *a, double *b, double *c)
Function Documentation
main()
int main (int argc, char ** argv)
References a, std::abs(), b, c, d(), e(), m, MPI_Finalize(), MPI_Init(), mTxm(), mTxmq(), posix_memalign(), ran_fill(), timer(), and trantimer().
mTxm()
void mTxm (long dimi, long dimj, long dimk, double * c, const double * a, const double * b)
References a, b, c, and k.
Referenced by main(), transform3d(), and transform3d_3c().
mTxm_dgemm()
void mTxm_dgemm (long ni, long nj, long nk, double * c, const double * a, const double * b)
References a, b, c, madness::cblas::gemm(), madness::cblas::NoTrans, and madness::cblas::Trans.
Referenced by timer(), and trantimer().
mTxm_tune()
void mTxm_tune (long dimi, long dimj, long dimk, double * c, const double * a, const double * b)
References a, b, c, and k.
Referenced by timer(), and trantimer().
mTxmq()
void mTxmq (long dimi, long dimj, long dimk, double * c, const double * a, const double * b)
References a, b, c, and k.
Referenced by main(), timer(), and trantimer().
ran()
double ran ()
Referenced by ran_fill(), and Node::random_insert().
ran_fill()
void ran_fill (int n, double * a)
References a, and ran().
Referenced by main().
timer()
void timer (const char * s, long ni, long nj, long nk, double * a, double * b, double * c)
References a, b, c, mTxm_dgemm(), mTxm_tune(), and mTxmq().
Referenced by madness::PNO::compute_cispd_correction_es(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_f12_correction_es(), madness::PNO::compute_cispd_f12_correction_gs(), madness::PNO::compute_cispd_fluctuation_matrix(), madness::PNO::grow_rank(), madness::PNO::initialize_pairs(), madness::TDHF::iterate_vectors(), main(), madness::PNO::orthonormalize_cholesky(), madness::TDHF::plot(), madness::PNO::pno_compress(), madness::PNO::save_pnos(), madness::TDHF::TDHF(), madness::PNO::truncate_pairs(), madness::PNO::update_fluctuation_potentials(), and madness::PNO::update_pno().
trantimer()
void trantimer (const char * s, long ni, long nj, long nk, double * a, double * b, double * c)
References a, b, c, mTxm_dgemm(), mTxm_tune(), and mTxmq().
Referenced by main().