MADNESS: test_Zmtxmq.cc File Reference
mtxmq_graveyard/bgp_tuning/test_Zmtxmq.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <cmath>
#include <complex>
#include "rdtsc.h"
Macros
#define ZGEMM_FNAME zgemm_
Typedefs
typedef std::complex< double > double_complex
Functions
int main (int argc, char **argv)
void mTxm (long dimi, long dimj, long dimk, double_complex *c, const double_complex *a, const double_complex *b)
void mTxm_tune (long dimi, long dimj, long dimk, double_complex *c, const double_complex *a, const double_complex *b)
void mTxm_zgemm (long ni, long nj, long nk, double_complex *c, const double_complex *a, const double_complex *b)
void mTxmq (long dimi, long dimj, long dimk, double_complex *c, const double_complex *a, const double_complex *b)
double_complex ran ()
void ran_fill (int n, double_complex *a)
void timer (const char *s, long ni, long nj, long nk, double_complex *a, double_complex *b, double_complex *c)
void trantimer (const char *s, long ni, long nj, long nk, double_complex *a, double_complex *b, double_complex *c)
void ZGEMM_FNAME (const char *transa, const char *transb, const int *m, const int *n, const int *k, const double_complex *alpha, const double_complex *a, const int *lda, const double_complex *b, const int *ldb, const double_complex *beta, double_complex *c, const int *ldc, int la, int lb)
Macro Definition Documentation
ZGEMM_FNAME
#define ZGEMM_FNAME zgemm_
Referenced by mTxm_zgemm().
Typedef Documentation
double_complex
typedef std::complex<double> double_complex
Function Documentation
main()
int main (int argc, char ** argv)
References a, std::abs(), b, c, d(), e(), m, MPI_Finalize(), MPI_Init(), mTxm(), mTxmq(), posix_memalign(), ran_fill(), timer(), and trantimer().
mTxm()
void mTxm (long dimi, long dimj, long dimk, double_complex * c, const double_complex * a, const double_complex * b)
References a, b, c, and k.
Referenced by main().
mTxm_tune()
void mTxm_tune (long dimi, long dimj, long dimk, double_complex * c, const double_complex * a, const double_complex * b)
References a, b, c, and k.
Referenced by timer(), and trantimer().
mTxm_zgemm()
void mTxm_zgemm (long ni, long nj, long nk, double_complex * c, const double_complex * a, const double_complex * b)
References a, b, c, and ZGEMM_FNAME.
Referenced by timer(), and trantimer().
mTxmq()
void mTxmq (long dimi, long dimj, long dimk, double_complex * c, const double_complex * a, const double_complex * b)
References a, b, c, and k.
Referenced by main(), timer(), and trantimer().
ran()
double_complex ran ()
Referenced by ran_fill().
ran_fill()
void ran_fill (int n, double_complex * a)
References a, and ran().
Referenced by main().
timer()
void timer (const char * s, long ni, long nj, long nk, double_complex * a, double_complex * b, double_complex * c)
References a, b, c, mTxm_tune(), mTxm_zgemm(), and mTxmq().
Referenced by main().
trantimer()
void trantimer (const char * s, long ni, long nj, long nk, double_complex * a, double_complex * b, double_complex * c)
References a, b, c, mTxm_tune(), mTxm_zgemm(), and mTxmq().
Referenced by main().
ZGEMM_FNAME()
void ZGEMM_FNAME (const char * transa, const char * transb, const int * m, const int * n, const int * k, const double_complex * alpha, const double_complex * a, const int * lda, const double_complex * b, const int * ldb, const double_complex * beta, double_complex * c, const int * ldc, int la, int lb)