MADNESS: madness::detail Namespace Reference
madness::detail Namespace Reference
Namespaces
arg_holder
Classes
struct absinplace
struct absop
struct abssqop
struct abssquareinplace
struct adqtest
struct ArgCount
struct ArgCountHelper
struct ArgCountHelper< void >
class ArgHolder
A wrapper object for holding task function argument objects.
struct callable_enabler
struct callable_enabler< callableT, std::enable_if_t< callable_traits< callableT >::value > >
struct callable_traits
Function traits in the spirit of boost function traits.
struct callable_traits< fnT(argTs...), typename std::enable_if_t< is_type< std::result_of_t< fnT(argTs...)> >::value > >
Function traits in the spirit of boost function traits.
struct DefaultInitPtr
Default pointer to a. object of type T.
struct DefaultInitPtr< std::shared_ptr< T > >
Default shared pointer to an object of type T.
class DeferredCleanup
Deferred cleanup of shared_ptr's.
class DistCache
Distributed caching utility.
class ForEachRootTask
Apply an operation to a range of iterators.
struct function_enabler
struct function_enabler_helper
Behave like a lazy std::enable_if.
struct function_enabler_helper< false, returnT >
Specialization that disables type when B is false.
struct function_traits
Function traits in the spirit of boost function traits.
struct function_traits< fnT(argTs...), typename std::enable_if_t< is_type< std::result_of_t< fnT(argTs...)> >::value > >
Function trait specialization for a callable (can be a function, a (generic) lambda, etc.)
struct function_traits< resultT(*&)(argTs...), void >
Function trait specialization for a reference to a free function pointer.
struct function_traits< resultT(*)(argTs...), void >
Function trait specialization for a free function pointer.
struct helper
struct helper< T, 0 >
struct helper< T, 1 >
struct imagop
struct info
struct info_base
struct is_arg_holder
struct is_arg_holder< ArgHolder< T > >
struct is_functor
struct is_functor< fnT, typename std::enable_if< is_type< typename fnT::result_type >::value >::type >
struct is_type
struct memfunc_enabler
struct memfunc_enabler< const objT *, memfnT >
struct memfunc_enabler< const objT *const, memfnT >
struct memfunc_enabler< const std::shared_ptr< objT > &, memfnT >
struct memfunc_enabler< const std::shared_ptr< objT >, memfnT >
struct memfunc_enabler< objT *, memfnT >
struct memfunc_enabler< objT *const, memfnT >
struct memfunc_enabler< std::shared_ptr< objT > &, memfnT >
struct memfunc_enabler< std::shared_ptr< objT >, memfnT >
struct memfunc_enabler_base
struct memfunc_enabler_base< objT, resT(baseT::*)(paramT...) const, typename std::enable_if< std::is_base_of< baseT, objT >::value >::type >
struct memfunc_enabler_base< objT, resT(baseT::*)(paramT...), typename std::enable_if< std::is_base_of< baseT, objT >::value >::type >
struct memfunc_traits
Member function traits in the spirit of boost function traits.
struct memfunc_traits< returnT(objT::*)(argTs...) const >
Member function traits in the spirit of boost function traits.
struct memfunc_traits< returnT(objT::*)(argTs...)>
Member function traits in the spirit of boost function traits.
class MemFuncWrapper
Functor wrapper for object and member function pointers.
class MemFuncWrapper< ptrT, memfnT, void >
Functor wrapper for object and member function pointers.
struct noop
struct PendingMsg
Common base class for pending messages to ensure in-order processing.
struct ptr_traits
struct ptr_traits< void >
Specialization of ptr_traits for type void.
struct realop
class RemoteCounter
Remote reference counter.
class RemoteCounterBase
Base class for remote counter implementation objects.
class RemoteCounterImpl
Remote counter implementation object.
struct result_of
struct result_of< fnT, typename std::enable_if< function_traits< fnT >::value >::type >
struct result_of< fnT, typename std::enable_if< is_type< decltype(&fnT::operator())>::value >::type >
struct result_of< fnT, typename std::enable_if< memfunc_traits< fnT >::value >::type >
struct scaleinplace
struct squareinplace
class StackBase
Base class for Stack which implements basic memory operations for non-POD objects.
class StackBase< T, true >
Base class for Stack which implements basic memory operations for POD objects.
struct task_arg
struct task_arg< Future< T > *>
struct task_arg< Future< T > >
struct task_arg< Future< void > >
struct task_arg< void >
struct task_result_type
struct TaskHandlerInfo
Serialization container for sending tasks to remote nodes.
class WorldMpi
MPI singleton that manages MPI setup and teardown for MADNESS.
class WorldMpiRuntime
MPI runtime reference counter.
struct WorldObjectTaskHelper
struct WorldObjectTaskHelper< objT, memfnT, typename std::enable_if< std::is_base_of< std::enable_shared_from_this< objT >, objT >::value >::type >
class WorldPtr
A global pointer address, valid anywhere in the world.
Typedefs
typedef Future< void > voidT
Functions
void combine_hash (hashT &seed, hashT hash)
Internal use only.
void compare_fn_addresses (void *addresses_in, void *addresses_inout, int *len, MPI_Datatype *type)
template<typename objT >
void deferred_cleanup (World &world, const std::shared_ptr< objT > &p)
Defer the cleanup of a shared pointer to the end of the next fence.
template<typename ptrT , typename memfnT , typename resT >
memfnT get_mem_func_ptr (const MemFuncWrapper< ptrT, memfnT, resT > &wrapper)
Returns the member function pointer from a wrapper.
unsigned short htons_x (unsigned short a)
template<typename T >
T mynorm (T t)
template<typename T >
T mynorm (std::complex< T > t)
template<typename T >
double norm (const T &t)
template<typename T >
double norm (const Tensor< T > &t)
std::ostream & operator<< (std::ostream &out, const RemoteCounter &counter)
template<typename T , typename U >
bool operator<= (const WorldPtr< T > &left, const WorldPtr< U > &right)
Less-than-equal-to comparison operator.
template<typename T , typename U >
bool operator> (const WorldPtr< T > &left, const WorldPtr< U > &right)
Greater-than comparison operator.
template<typename T , typename U >
bool operator>= (const WorldPtr< T > &left, const WorldPtr< U > &right)
Greater-than-equal-to comparison operator.
static const uniqueidT & peek (const AmArg &arg)
Extract the unique object ID from an incoming active message header.
bool & print_meminfo_flag_accessor ()
void print_mutex_error (int error_number)
template<typename fnT >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, a7T &a7, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, a7T &a7, a8T &a8, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T , typename a9T >
std::enable_if< std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (Future< void > &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, a7T &a7, a8T &a8, a9T &a9)
template<typename fnT >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, const voidT &, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, const voidT &, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, const voidT &, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, a7T &a7, const voidT &, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, a7T &a7, a8T &a8, const voidT &)
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T , typename a9T >
std::enable_if<!std::is_void< typename detail::result_of< fnT >::type >::value >::type run_function (typename task_result_type< fnT >::futureT &result, fnT fn, a1T &a1, a2T &a2, a3T &a3, a4T &a4, a5T &a5, a6T &a6, a7T &a7, a8T &a8, a9T &a9)
void swap (RemoteCounter &l, RemoteCounter &r)
template<typename T >
void swap (WorldPtr< T > &l, WorldPtr< T > &r)
Swap the content of l with r.
template<typename Char >
const Char * Vm_cstr ()
template<>
const char * Vm_cstr< char > ()
template<>
const wchar_t * Vm_cstr< wchar_t > ()
template<typename objT , typename memfnT >
MemFuncWrapper< objT *, memfnT, typename result_of< memfnT >::type > wrap_mem_fn (objT &obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from an object and a member function pointer.
template<typename objT , typename memfnT >
MemFuncWrapper< const objT *, memfnT, typename result_of< memfnT >::type > wrap_mem_fn (const objT &obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a const object and a member function pointer.
template<typename objT , typename memfnT >
MemFuncWrapper< objT *, memfnT, typename result_of< memfnT >::type > wrap_mem_fn (objT *obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a pointer and a member function pointer.
template<typename objT , typename memfnT >
MemFuncWrapper< const objT *, memfnT, typename result_of< memfnT >::type > wrap_mem_fn (const objT *obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a const pointer and a member function pointer.
template<typename objT , typename memfnT >
MemFuncWrapper< std::shared_ptr< objT >, memfnT, typename result_of< memfnT >::type > wrap_mem_fn (std::shared_ptr< objT > &obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a shared pointer and a member function pointer.
template<typename objT , typename memfnT >
MemFuncWrapper< std::shared_ptr< objT >, memfnT, typename result_of< memfnT >::type > wrap_mem_fn (const std::shared_ptr< objT > &obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a const shared pointer and a member function pointer.
Variables
Mutex printmutex
Detailed Description
Todo:
Description needed
Typedef Documentation
voidT
typedef Future<void> madness::detail::voidT
Future<void> is an empty object which is used as a placeholder for unused arguments.
Function Documentation
combine_hash()
void madness::detail::combine_hash (hashT & seed, hashT hash) inline
Internal use only.
Referenced by madness::hash_combine(), madness::hash_range(), madness::hash_value(), and std::hash_value().
compare_fn_addresses()
void madness::detail::compare_fn_addresses (void * addresses_in, void * addresses_inout, int * len, MPI_Datatype * type)
References MADNESS_ASSERT, MPI_UNSIGNED_LONG, and madness::type().
Referenced by madness::RMI::assert_aslr_off().
deferred_cleanup()
template<typename objT > void madness::detail::deferred_cleanup (World & world, const std::shared_ptr< objT > & p) inline
Defer the cleanup of a shared pointer to the end of the next fence.
Call this function before destroying a shared pointer. If the shared pointer is the last reference to the object, it is placed in the deferred deletion list. Otherwise, nothing is done with the pointer.
References madness::detail::DeferredCleanup::get_deferred_cleanup(), and p().
Referenced by madness::WorldContainer< keyT, nodeT >::~WorldContainer().
get_mem_func_ptr()
template<typename ptrT , typename memfnT , typename resT > memfnT madness::detail::get_mem_func_ptr (const MemFuncWrapper< ptrT, memfnT, resT > & wrapper)
Returns the member function pointer from a wrapper.
Template Parameters
ptrT Pointer type.
memfnT Member function pointer type.
resT Member function return type.
Parameters
wrapper Wrapper to the member function.
Returns
The member function pointer.
References madness::detail::MemFuncWrapper< ptrT, memfnT, resT >::memfn_.
Referenced by madness::TaskFn< fnT, arg1T, arg2T, arg3T, arg4T, arg5T, arg6T, arg7T, arg8T, arg9T >::get_func().
htons_x()
unsigned short madness::detail::htons_x (unsigned short a) inline
References a.
Referenced by madness::plotpovray().
mynorm() [1/2]
template<typename T > T madness::detail::mynorm (T t)
Referenced by madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::normf().
mynorm() [2/2]
template<typename T > T madness::detail::mynorm (std::complex< T > t)
References norm().
norm() [1/2]
template<typename T > double madness::detail::norm (const T & t)
References std::abs().
Referenced by madness::adq1(), madness::SRConf< T >::check_right_orthonormality(), compute_energy(), compute_energy_with_U(), converge(), converge2s(), madness::Znemo::custom_guess(), madness::FunctionImpl< Q, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< Q, NDIM >::do_apply_kernel2(), doit(), gauss_3d(), gauss_6d(), madness::GMRES(), madness::Function< double, 6 >::if(), madness::CCTimer::info(), iterate(), iterate_ground(), madness::CC2::iterate_singles(), main(), madness::ConvolutionData1D< Q >::make_approx(), madness::TDHF::make_old_guess(), madness::TDHF::make_virtuals(), mynorm(), mynorm< double_complex >(), mynorm< float_complex >(), madness::FunctionImpl< Q, NDIM >::norm_tree_spawn(), madness::SRConf< T >::normalize(), Sphere::operator()(), DSphere::operator()(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::op_leaf_op< T, NDIM, opT >::operator()(), madness::hartree_convolute_leaf_op< T, NDIM, LDIM, opT >::operator()(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::do_norm2sq_local::operator()(), madness::operator<<(), madness::Leaf_op< T, NDIM, SeparatedConvolution< double, NDIM >, Specialbox_op< T, NDIM > >::post_screening(), print_info(), madness::FunctionImpl< Q, NDIM >::print_size(), print_stats(), Calculation::project_potential_basis(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), propagate(), madness::Nemo::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), test_adaptive_tree(), test_basic(), test_bsh(), madness::Znemo::test_compute_current_density(), test_convolution(), test_coulomb(), test_exchange(), test_hartree_product(), test_inner(), test_opdir(), test_orthogonalization(), test_qm(), test_recursive_application(), test_unaryop(), madness::Diamagnetic_potential_factor::test_vector_potentials(), tightgauss_3d(), madness::unitvec(), and madness::FunctionImpl< Q, NDIM >::vtransform_doit().
norm() [2/2]
template<typename T > double madness::detail::norm (const Tensor< T > & t)
References madness::Tensor< T >::normf().
Referenced by madness::adq1().
operator<<()
std::ostream & madness::detail::operator<< (std::ostream & out, const RemoteCounter & counter)
References madness::detail::RemoteCounter::get_worldid(), madness::detail::RemoteCounter::owner(), and madness::detail::RemoteCounter::use_count().
operator<=()
template<typename T , typename U > bool madness::detail::operator<= (const WorldPtr< T > & left, const WorldPtr< U > & right)
Less-than-equal-to comparison operator.
This operator does a lexicographical comparison of world ID, rank, and pointer (in that order).
Template Parameters
T One pointer type.
U Another pointer type.
Parameters
[in] left One pointer.
[in] right The other pointer.
Returns
True if the lexicographical comparison of world ID, rank, and pointer is true; false otherwise.
operator>()
template<typename T , typename U > bool madness::detail::operator> (const WorldPtr< T > & left, const WorldPtr< U > & right)
Greater-than comparison operator.
This operator does a lexicographical comparison of world ID, rank, and pointer (in that order).
Template Parameters
T One pointer type.
U Another pointer type.
Parameters
[in] left One pointer.
[in] right The other pointer.
Returns
True if the lexicographical comparison of world ID, rank, and pointer is true; false otherwise.
operator>=()
template<typename T , typename U > bool madness::detail::operator>= (const WorldPtr< T > & left, const WorldPtr< U > & right)
Greater-than-equal-to comparison operator.
This operator does a lexicographical comparison of world ID, rank, and pointer (in that order).
Template Parameters
T One pointer type.
U Another pointer type.
Parameters
[in] left One pointer.
[in] right The other pointer.
Returns
True if the lexicographical comparison of world ID, rank, and pointer is true; false otherwise.
peek()
static const uniqueidT& madness::detail::peek (const AmArg & arg) inline static
Extract the unique object ID from an incoming active message header.
We deserialize the header and all arguments at the same time to simplify the code. However, it is common that when sending a message to an item in a container to include a pointer to the container itself. But this breaks if the container is not initialized since the deserialization throws if the object is not initialized (which seems preferable to a hidden race condition). Hence, we use this routine to extract the unique ID from the very front of the info structure. For efficiency we here rely upon the serialization of info being opaque and the ID being at the front of info.
Todo:
Verify parameter description.
Parameters
[in] arg The active message header.
References madness::arg().
Referenced by madness::WorldObject< TestFutureForwarding >::handler(), and madness::WorldObject< TestFutureForwarding >::spawn_remote_task_handler().
print_meminfo_flag_accessor()
bool & madness::detail::print_meminfo_flag_accessor ()
Referenced by madness::print_meminfo_disable(), madness::print_meminfo_enable(), and madness::print_meminfo_enabled().
print_mutex_error()
void madness::detail::print_mutex_error (int error_number)
Referenced by madness::Mutex::lock(), madness::RecursiveMutex::lock(), madness::Spinlock::lock(), madness::PthreadConditionVariable::lock(), madness::Mutex::unlock(), madness::RecursiveMutex::unlock(), madness::Spinlock::unlock(), and madness::PthreadConditionVariable::unlock().
run_function() [1/20]
template<typename fnT > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References madness::Future< void >::set().
Referenced by madness::TaskFn< fnT, arg1T, arg2T, arg3T, arg4T, arg5T, arg6T, arg7T, arg8T, arg9T >::execute(), madness::WorldObject< TestFutureForwarding >::handler(), and madness::WorldObject< TestFutureForwarding >::send_am().
run_function() [2/20]
template<typename fnT , typename a1T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [3/20]
template<typename fnT , typename a1T , typename a2T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [4/20]
template<typename fnT , typename a1T , typename a2T , typename a3T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [5/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [6/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [7/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [8/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, a7T & a7, const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [9/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, a7T & a7, a8T & a8, const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [10/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T , typename a9T > std::enable_if<std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (Future< void > & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, a7T & a7, a8T & a8, a9T & a9) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< void >::set().
run_function() [11/20]
template<typename fnT > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References madness::Future< T >::set().
run_function() [12/20]
template<typename fnT , typename a1T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [13/20]
template<typename fnT , typename a1T , typename a2T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [14/20]
template<typename fnT , typename a1T , typename a2T , typename a3T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, const voidT & , const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [15/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, const voidT & , const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [16/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, const voidT & , const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [17/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, const voidT & , const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [18/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, a7T & a7, const voidT & , const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [19/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, a7T & a7, a8T & a8, const voidT &) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
run_function() [20/20]
template<typename fnT , typename a1T , typename a2T , typename a3T , typename a4T , typename a5T , typename a6T , typename a7T , typename a8T , typename a9T > std::enable_if<!std::is_void<typename detail::result_of<fnT>::type>::value >::type madness::detail::run_function (typename task_result_type< fnT >::futureT & result, fnT fn, a1T & a1, a2T & a2, a3T & a3, a4T & a4, a5T & a5, a6T & a6, a7T & a7, a8T & a8, a9T & a9) inline
References a1, a2, madness::detail::arg_holder::decay(), and madness::Future< T >::set().
swap() [1/2]
void madness::detail::swap (RemoteCounter & l, RemoteCounter & r) inline
References madness::detail::RemoteCounter::swap().
swap() [2/2]
template<typename T > void madness::detail::swap (WorldPtr< T > & l, WorldPtr< T > & r)
Swap the content of l with r.
Template Parameters
T The world pointer type.
Parameters
[in,out] l One world pointer.
[in,out] r The other world pointer.
References madness::detail::WorldPtr< T >::swap().
Referenced by madness::detail::RemoteCounter::swap(), madness::detail::WorldPtr< madness::detail::RemoteCounterBase >::swap(), and madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::swap().
Vm_cstr()
template<typename Char > const Char* madness::detail::Vm_cstr ()
Vm_cstr< char >()
template<> const char* madness::detail::Vm_cstr< char > ()
Vm_cstr< wchar_t >()
template<> const wchar_t* madness::detail::Vm_cstr< wchar_t > ()
References L.
wrap_mem_fn() [1/6]
template<typename objT , typename memfnT > MemFuncWrapper<objT*, memfnT, typename result_of<memfnT>::type> madness::detail::wrap_mem_fn (objT & obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from an object and a member function pointer.
Template Parameters
objT The object type.
memfnT The member function pointer type.
Parameters
[in] obj The object.
[in] memfn The member function pointer.
Returns
A wrapped member function pointer.
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate(), madness::FunctionImpl< T, NDIM >::add_op::activate(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::activate(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::activate(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::activate(), and madness::WorldTaskQueue::add().
wrap_mem_fn() [2/6]
template<typename objT , typename memfnT > MemFuncWrapper<const objT*, memfnT, typename result_of<memfnT>::type> madness::detail::wrap_mem_fn (const objT & obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a const object and a member function pointer.
Template Parameters
objT The object type.
memfnT The member function pointer type.
Parameters
[in] obj The object.
[in] memfn The member function pointer.
Returns
A wrapped member function pointer.
wrap_mem_fn() [3/6]
template<typename objT , typename memfnT > MemFuncWrapper<objT*, memfnT, typename result_of<memfnT>::type> madness::detail::wrap_mem_fn (objT * obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a pointer and a member function pointer.
Template Parameters
objT The object type.
memfnT The member function pointer type.
Parameters
[in] obj Pointer to the object.
[in] memfn The member function pointer.
Returns
A wrapped member function pointer.
wrap_mem_fn() [4/6]
template<typename objT , typename memfnT > MemFuncWrapper<const objT*, memfnT, typename result_of<memfnT>::type> madness::detail::wrap_mem_fn (const objT * obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a const pointer and a member function pointer.
Template Parameters
objT The object type.
memfnT The member function pointer type.
Parameters
[in] obj Pointer to the object.
[in] memfn The member function pointer.
Returns
A wrapped member function pointer.
wrap_mem_fn() [5/6]
template<typename objT , typename memfnT > MemFuncWrapper<std::shared_ptr<objT>, memfnT, typename result_of<memfnT>::type> madness::detail::wrap_mem_fn (std::shared_ptr< objT > & obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a shared pointer and a member function pointer.
Template Parameters
objT The object type.
memfnT The member function pointer type.
Parameters
[in] obj Shared pointer to the object.
[in] memfn The member function pointer.
Returns
A wrapped member function pointer.
wrap_mem_fn() [6/6]
template<typename objT , typename memfnT > MemFuncWrapper<std::shared_ptr<objT>, memfnT, typename result_of<memfnT>::type> madness::detail::wrap_mem_fn (const std::shared_ptr< objT > & obj, memfnT memfn)
Create a member function wrapper (MemFuncWrapper) from a const shared pointer and a member function pointer.
Template Parameters
objT The object type.
memfnT The member function pointer type.
Parameters
[in] obj Shared pointer to the object.
[in] memfn The member function pointer.
Returns
A wrapped member function pointer.
Variable Documentation
printmutex
Mutex madness::detail::printmutex
Referenced by madness::print(), and madness::print_error().