MADNESS: SafeMPI Namespace Reference
SafeMPI Namespace Reference
Namespaces
detail
Classes
class Exception
SafeMPI exception object.
class Group
class Intracomm
Wrapper around MPI_Comm. Has a shallow copy constructor; use Create(Get_group()) for deep copy.
class Request
class Status
Functions
void Attach_buffer (void *buffer, int size)
Set buffer for Bsend .
int Detach_buffer (void *&buffer)
Unset the Bsend buffer.
int Finalize ()
Analogous to MPI_Finalize.
void Init (int &argc, char **&argv)
Analogous to MPI_Init.
void Init ()
Analogous to MPI_Init.
int Init_thread (int &argc, char **&argv, int requested)
Analogous to MPI_Init_thread.
int Init_thread (int requested)
Analogous to MPI_Init_thread.
bool Is_finalized ()
Check MPI finalization status.
bool Is_initialized ()
Check MPI initialization status.
MPI_Op Op_create (MPI_User_function *user_fn, int commute)
Analogous to MPI_Op_create.
void Op_free (MPI_Op op)
Analogous to MPI_Op_free.
int Query_thread ()
Analogous to MPI_Query_thread.
double Wtime ()
Wall time.
Variables
madness::SCALABLE_MUTEX_TYPE charon
Intracomm COMM_WORLD = Intracomm::WorldInitObject()
static const int DEFAULT_SEND_RECV_TAG = 1000
static const int MPIAR_TAG = 1001
static const int RMI_TAG = 1023
Function Documentation
Attach_buffer()
void SafeMPI::Attach_buffer (void * buffer, int size) inline
Set buffer for Bsend .
Parameters
buffer The buffer to be used by Bsend
size The size of the buffer in Bytes
References MADNESS_MPI_TEST, and MPI_Buffer_attach().
Referenced by madness::detail::WorldMpi::WorldMpi().
Detach_buffer()
int SafeMPI::Detach_buffer (void *& buffer) inline
Unset the Bsend buffer.
Parameters
[out] buffer The buffer that was used by Bsend
References MPI_Buffer_detach().
Referenced by madness::detail::WorldMpi::~WorldMpi().
Finalize()
int SafeMPI::Finalize () inline
Analogous to MPI_Finalize.
This returns status rather than throw an exception upon failure because this is a "destructor", and throwing from destructors is evil.
Returns
0 if successful, nonzero otherwise (see MPI_Finalize() for the return codes).
References COMM_WORLD, MPI_Finalize(), and SafeMPI::Intracomm::pimpl.
Referenced by madness::finalize(), main(), test_he(), test_hydro(), testPeriodicCoulomb3d(), and madness::detail::WorldMpi::~WorldMpi().
Init() [1/2]
void SafeMPI::Init (int & argc, char **& argv) inline
Analogous to MPI_Init.
Parameters
argc The number of arguments in argv
argv The vector of command-line arguments
References SafeMPI::detail::init_comm_world(), MADNESS_MPI_TEST, and MPI_Init().
Referenced by Init(), main(), test_he(), and testPeriodicCoulomb3d().
Init() [2/2]
void SafeMPI::Init () inline
Analogous to MPI_Init.
References Init().
Init_thread() [1/2]
int SafeMPI::Init_thread (int & argc, char **& argv, int requested) inline
Analogous to MPI_Init_thread.
Parameters
argc the number of arguments in argv
argv the vector of command-line arguments
requested the desired thread level
Returns
provided thread level
References SafeMPI::detail::init_comm_world(), MADNESS_MPI_TEST, and MPI_Init_thread().
Referenced by Init_thread(), main(), and madness::detail::WorldMpi::WorldMpi().
Init_thread() [2/2]
int SafeMPI::Init_thread (int requested) inline
Analogous to MPI_Init_thread.
Parameters
requested the desired thread level
Returns
provided thread level
References Init_thread().
Is_finalized()
bool SafeMPI::Is_finalized () inline
Check MPI finalization status.
Returns
true if MPI has been finalized, false otherwise.
References MPI_Finalized().
Referenced by madness::detail::WorldMpi::initialize(), SafeMPI::Intracomm::Impl::~Impl(), and madness::WorldAmInterface::~WorldAmInterface().
Is_initialized()
bool SafeMPI::Is_initialized () inline
Check MPI initialization status.
Returns
true if MPI has been initialized, false otherwise.
References madness::initialized(), and MPI_Initialized().
Referenced by madness::detail::WorldMpi::initialize(), SafeMPI::Intracomm::Intracomm(), SafeMPI::Group::Impl::~Impl(), and SafeMPI::Intracomm::Impl::~Impl().
Op_create()
MPI_Op SafeMPI::Op_create (MPI_User_function * user_fn, int commute) inline
Analogous to MPI_Op_create.
References MADNESS_MPI_TEST, and MPI_Op_create().
Referenced by madness::RMI::assert_aslr_off().
Op_free()
void SafeMPI::Op_free (MPI_Op op) inline
Analogous to MPI_Op_free.
References MADNESS_MPI_TEST, MPI_Op_free(), and op().
Referenced by madness::RMI::assert_aslr_off().
Query_thread()
int SafeMPI::Query_thread () inline
Analogous to MPI_Query_thread.
Returns
the MPI thread level provided by SafeMPI::Init_thread()
References MADNESS_MPI_TEST, and MPI_Query_thread().
Referenced by madness::detail::WorldMpi::initialize().
Wtime()
double SafeMPI::Wtime () inline
Wall time.
Returns
The current wall time
References MPI_Wtime().
Variable Documentation
charon
madness::SCALABLE_MUTEX_TYPE SafeMPI::charon
Referenced by SafeMPI::Intracomm::Impl::unique_reserved_tag(), and SafeMPI::Intracomm::Impl::unique_tag().
COMM_WORLD
Intracomm SafeMPI::COMM_WORLD = Intracomm::WorldInitObject()
Referenced by madness::ThreadPool::begin(), madness::error(), Finalize(), SafeMPI::detail::init_comm_world(), madness::initialize(), madness::detail::WorldMpi::initialize(), main(), realmain(), test_G_R_vectors(), test_gaussian_num_coeffs(), test_he(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), testNavierStokes(), testPeriodicCoulomb3d(), madness::ThreadPool::ThreadPool(), madness::WorldAmInterface::WorldAmInterface(), and madness::profiling::TaskProfiler::write_to_file().
DEFAULT_SEND_RECV_TAG
const int SafeMPI::DEFAULT_SEND_RECV_TAG = 1000 static
MPIAR_TAG
const int SafeMPI::MPIAR_TAG = 1001 static
RMI_TAG
const int SafeMPI::RMI_TAG = 1023 static
tags in [1,999] ... allocated once by unique_reserved_tag
tags in [1000,1023] ... statically assigned here
tags in [1024,4095] ... allocated round-robin by unique_tag
tags in [4096,8191] ... reserved for huge msg exchange by RMI
tags in [8192,MPI::TAG_UB] ... not used/managed by madness
Referenced by madness::RMI::RmiTask::post_recv_buf().