MADNESS: madness Namespace Reference
madness Namespace Reference
Mra » Function | TensorMADNESS libraries » Parallel programming environment » Multi-threading » | Atomic operationsMADNESS libraries » Parallel programming environment » | FuturesMADNESS libraries » Parallel programming environment » | Distributed computing environment (World and its relations)MADNESS libraries » Parallel programming environment » | Globally addressable objects (WorldObject)MADNESS libraries » Parallel programming environment » Multi-threading » | Task queue | Worlddc | HashingMADNESS libraries » Parallel programming environment » | Interfaces from World to MPI | Mutexes
File holds all helper structures necessary for the CC_Operator and CC2 class.
Namespaces
archive
Namespace for I/O tools.
cblas
constants
Namespace storing mathematical and physical constants.
detail
guessfactory
Hash_private
info
Runtime details on the configuration and version of MADNESS.
is_istreammable std
lapacke
meta
profiling
tr1
Classes
struct abs_op
struct abs_square_op
class AbstractVectorSpace
A generic vector space which provides common operations needed by linear algebra routines (norm, inner product, etc.)
class AC
struct ACParameters
Contains all the parameters for the asymptotic correction.
struct add_future
Boost-type-trait-like mapping of type T to Future<T>.
struct add_future< Future< T > >
Boost-type-trait-like mapping of Future<T> to Future<T>.
struct allocator
class AmArg
World active message that extends an RMI message.
class Atom
struct atom_information
Needed information about atom to compute asymptotic correction.
struct AtomCore
class atomic_attraction
class AtomicAttractionFunctor
class AtomicBasis
Represents multiple shells of contracted gaussians on a single center.
class AtomicBasisFunction
Used to represent one basis function from a shell on a specific center.
class AtomicBasisFunctor
class AtomicBasisSet
Contracted Gaussian basis.
struct AtomicData
class AtomicInt
An integer with atomic set, get, read+increment, read+decrement, and decrement+test operations.
class BandlimitedPropagator
Class to evaluate the filtered Schrodinger free-particle propagator in real space.
class Barrier
class BaseTensor
The base class for tensors defines generic capabilities.
class BasisFunctions
struct BinaryOpStructure
computes the corrected exchange correlation potential using the hartree potential
class BinSorter
A parallel bin sort across MPI processes.
class BoundaryConditions
This class is used to specify boundary conditions for all operatorsExterior boundary conditions (i.e., on the simulation domain) are associated with operators (not functions). The types of boundary conditions available are in the enum BCType.
class BSHFunctionInterface
a function like f(x) = exp(-mu x)/x
struct CalculationParameters
class CallbackInterface
The class used for callbacks (e.g., dependency tracking).
class CC2
struct CC_vecfunction
A helper structure which holds a map of functions.
struct CCConvolutionOperator
struct CCFunction
structure for a CC Function 3D which holds an index and a type
struct CCIntermediatePotentials
little helper structure which manages the stored singles potentials
struct CCMessenger
class CCPair
struct CCPairFunction
struct CCParameters
struct CCTimer
Timer Structure.
struct charactertable
struct CISData
POD for CIS excitation.
class CoeffTracker
a class to track where relevant (parent) coeffs are
class Complex_CIS_Parameters
class ComplexExp
class CompositeFactory
Factory for facile setup of a CompositeFunctorInterface and its FuncImpl.
class CompositeFunctorInterface
CompositeFunctorInterface implements a wrapper of holding several functions and functors.
class ConcurrentHashMap
struct conditional_conj_struct
For real types return value, for complex return conjugate.
struct conditional_conj_struct< Q, true >
For real types return value, for complex return conjugate.
class ConditionVariable
Scalable and fair condition variable (spins on local value)
struct conj_op
class ContractedGaussianShell
Represents a single shell of contracted, Cartesian, Gaussian primitives.
class Convolution1D
Provides the common functionality/interface of all 1D convolutions.
struct ConvolutionData1D
!!! Note that if Rnormf is zero then ALL of the tensors are empty
class ConvolutionND
Array of 1D convolutions (one / dimension)
struct CoreOrbital
class CoreOrbitalDerivativeFunctor
class CoreOrbitalFunctor
struct CorePotential
Represents a core potential.
class CorePotentialDerivativeFunctor
class CorePotentialManager
class Coulomb
struct declval< std::ostream & >()<< std::declval< const T & >())> >
struct default_allocator
class DeferredDeleter
struct dens_inv
struct dens_inv1
class DependencyInterface
Provides an interface for tracking dependencies.
class Derivative
Implements derivatives operators with variety of boundary conditions on simulation domain.
class DerivativeBase
Tri-diagonal operator traversing tree primarily for derivative operator.
class DerivativeOperator
class DFT
class DFTCoulombOp
class DFTCoulombPeriodicOp
class DFTNuclearChargeDensityOp
class DFTNuclearPotentialOp
class Diamagnetic_potential_factor
to be put in a separate file
class DipoleFunctor
A MADNESS functor to compute either x, y, or z.
class Displacements
Holds displacements for applying operators to avoid replicating for all operators.
class DistributedMatrix
Manages data associated with a row/column/block distributed array.
class DistributedMatrixDistribution
class DNuclear
derivative of the (regularized) nuclear potential wrt nuclear displacements
class DomainMaskInterface
The interface for masking functions defined by signed distance functions.
class DomainMaskSDFFunctor
Framework for combining a signed distance function (sdf) with a domain mask to produce MADNESS functions.
struct DQStats
class DQueue
A thread safe, fast but simple doubled-ended queue.
class EigSolver
class EigSolverOp
struct ElectronCuspyBox_op
struct ElectronicStructureParams
class ElectronPair
enhanced POD for the pair functions
struct ElectronPairIterator
class ElectronRepulsionInterface
a function like f(x)=1/x
class ElementaryInterface
ElementaryInterface (formerly FunctorInterfaceWrapper) interfaces a c-function.
struct error_leaf_op
class Exchange
class F12Parameters
class F12Potentials
Class that provides all necessary F12 Potentials and Integrals.
class Fock
Computes matrix representation of the Fock operator.
class Function
A multiresolution adaptive numerical function.
struct function_real2complex_op
class FunctionCommonData
FunctionCommonData holds all Function data common for given k.
class FunctionDefaults
FunctionDefaults holds default paramaters as static class members.
class FunctionFactory
FunctionFactory implements the named-parameter idiom for Function.
class FunctionFunctorInterface
Abstract base class interface required for functors used as input to Functions.
class FunctionImpl
FunctionImpl holds all Function state to facilitate shallow copy semantics.
class FunctionInterface
FunctionInterface implements a wrapper around any class with the operator()()
class FunctionNode
FunctionNode holds the coefficients, etc., at each node of the 2^NDIM-tree.
class FunctionSpace
A vector space using MADNESS Functions.
class FunctorInterface
FunctorInterface interfaces a class or struct with an operator()()
class Future
A future is a possibly yet unevaluated value.
class Future< Future< T > >
A future of a future is forbidden (by deleted constructor).
class Future< std::vector< Future< T > > >
Specialization of Future for a vector of Futures.
class Future< void >
Specialization of Future<void> for internal convenience. This does nothing useful!
struct future_to_ref
struct future_to_ref< const Future< T > & >
struct future_to_ref< Future< T > & >
struct future_to_ref< Future< T > * >
struct future_to_ref< Future< T > >
class FutureImpl
Implements the functionality of futures.
class FutureImpl< void >
Specialization of FutureImpl<void> for internal convenience. This does nothing useful!
class GaussianConvolution1D
1D convolution with (derivative) Gaussian; coeff and expnt given in simulation coordinates [0,1]
struct GaussianConvolution1DCache
class GaussianDomainMask
Use a Gaussian for the surface function and the corresponding erf for the domain mask.
class GaussianGenericFunctor
class GaussSlater
A nuclear correlation factor class.
class GenericConvolution1D
Generic 1D convolution using brute force (i.e., slow) adaptive quadrature for rnlp.
class GenTensor
class GFit
class GradientalGaussSlater
A nuclear correlation factor class.
class Group
A collection of processes.
class GTHPseudopotential
struct harmonic_potential_boxed
functor for the diamagnetic term in a box
struct hartree_convolute_leaf_op
struct hartree_leaf_op
returns true if the result of a hartree_product is a leaf node (compute norm & error)
class HartreeFock
class HartreeFockCoulombOp
class HartreeFockExchangeOp
class HartreeFockNuclearPotentialOp
struct Hash
Hash functor.
class HighDimIndexIterator
class IEigSolverObserver
struct imag_op
class IndexIterator
struct insert_op
class int_factor_functor
Functor for the correction factor, which is multiplied with the exchange correlation potential.
struct interpolate_munge_refdens
struct is_future
Boost-type-trait-like test if a type is a future.
struct is_future< Future< T > >
Boost-type-trait-like test if a type is a future.
struct is_istreammable
True for types that are "deserialiable" from an std::istream.
struct is_ostreammable
True for types that are "serialiable" to a std::ostream.
struct is_serializable
is std::true_type if T can be serialized to Archive without specialized serialize() method
struct is_serializable< archive::BinaryFstreamInputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::BinaryFstreamOutputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::BufferInputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::BufferOutputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::MPIInputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::MPIOutputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::MPIRawInputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::MPIRawOutputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::TextFstreamInputArchive, T, std::enable_if_t< is_iostreammable_v< T > > >
struct is_serializable< archive::TextFstreamOutputArchive, T, std::enable_if_t< is_iostreammable_v< T > > >
struct is_serializable< archive::VectorInputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_serializable< archive::VectorOutputArchive, T, std::enable_if_t< is_trivially_serializable< T >::value > >
struct is_trivially_serializable
struct IsSupported
struct IsSupported< TypeData, ReturnType, true >
class Key
Key is the index for a node of the 2^NDIM-tree.
class KeyChildIterator
Iterates in lexical order thru all children of a key.
class Kinetic
class KPoint
class Laplacian
the Laplacian operator: ^2_i
struct lbcost
struct LBCost
class LBDeuxPmap
class LBNodeDeux
struct leaf_op
class Leaf_op
class Leaf_op_other
class LevelPmap
A pmap that locates children on odd levels with their even level parents.
class LinearSlater
A nuclear correlation factor class.
class LLRVDomainMask
Provides the Li-Lowengrub-Ratz-Voight (LLRV) domain mask characteristic functions.
class LoadBalanceDeux
class LoadBalImpl
class LowDimIndexIterator
class LowRankTensor
class lr_pot_functor
Functor for the 1/r potential to induce the correct asymptotic behaviour of the exchange correlation potential.
class Lz
the z component of the angular momentum
class MadnessException
Base class for exceptions thrown in MADNESS.
struct MatrixInnerTask
struct max_of_x_1_smooth
class MolecularCorePotentialFunctor
class MolecularDerivativeFunctor
class MolecularEnergy
class MolecularGuessDensityFunctor
class MolecularOptimizationParameters
struct MolecularOptimizationTargetInterface
class MolecularOptimizer
Molecular optimizer derived from the QuasiNewton optimizer.
class MolecularOrbitals
class MolecularPotentialFunctor
class MolecularSecondDerivativeFunctor
class Molecule
class MomentFunctor
A MADNESS functor to compute the cartesian moment x^i * y^j * z^k (i, j, k integer and >= 0)
class MP2
a class for computing the first order wave function and MP2 pair energies
struct mul_leaf_op
class Mutex
Mutex using pthread mutex operations.
class MutexFair
A scalable and fair mutex (not recursive)
class MutexReaderWriter
class MutexWaiter
class MyPmap
Procmap implemented using Tree of TreeCoords.
struct MyTimer
Timer structure.
class Nemo
The Nemo class.
class Nemo_complex_Parameters
class NemoBase
class NonlinearSolverND
A simple Krylov-subspace nonlinear equation solver.
class NonstandardIndexIterator
struct noop
class Nuclear
class NuclearCorrelationFactor
ABC for the nuclear correlation factors.
struct NuclearCuspyBox_op
class OEP
class OEP_Parameters
struct op_leaf_op
class Operator
A generic operator: takes in one T and produces another T.
struct OptimizationTargetInterface
The interface to be provided by functions to be optimized.
struct OptimizerInterface
The interface to be provided by optimizers.
struct OrbitalIterator
iterates the third index for pair coupling
struct PairEnergies
POD structure for energies.
struct Pairs
class ParametrizedExchange
class PCM
interface class to the PCMSolver library
class pg_operator
This class implements the symmetry operations (not the point groups)
class PNO
struct PNOPairs
POD for PNO code.
class PNOParameters
class poly4erfc
class Polynomial
A nuclear correlation factor class.
class PoolTaskInterface
Lowest level task interface.
class PoolTaskNull
A no-operation task used for various purposes.
class PotentialManager
struct printleveler
class ProcessKey
Key object that includes the process information.
struct ProfileStat
Simple container for parallel profile statistic.
class Projector
simple projector class
class projector_irrep
class ProjRLMFunctor
class ProjRLMStore
class PseudoNuclearCorrelationFactor
class PthreadConditionVariable
Simple wrapper for Pthread condition variable with its own mutex.
class QCCalculationParametersBase
class for holding the parameters for calculation
struct QCParameter
structure holding the value for a given parameter
struct qmsg
class QProjector
orthogonality projector
class QuasiNewton
Optimization via quasi-Newton (BFGS or SR1 update)
struct R_times_arg_div_R
compute the expression (R_i)^(-1) R_i arg(r,B,v_i)
class Random
A random number generator (portable, vectorized, and thread-safe)
struct RandomState
class Range
Range, vaguely a la Intel TBB, to encapsulate a random-access, STL-like start and end iterator with chunksize.
struct real_op
class RecursiveMutex
Recursive mutex using pthread mutex operations.
class RemoteReference
Simple structure used to manage references/pointers to remote instances.
struct remove_fcvr
struct remove_future
Boost-type-trait-like mapping of Future<T> to T.
struct remove_future< const Future< T > &>
struct remove_future< const Future< T > >
struct remove_future< Future< T > &&>
struct remove_future< Future< T > &>
struct remove_future< Future< T > >
This metafunction maps Future<T> to T.
class RMI
This class implements the communications server thread and provides the only send interface.
struct RMISendReq
This for RMI server thread to manage lifetime of WorldAM messages that it is sending.
struct RMIStats
class SCF
class SCFProtocol
struct for running a protocol of subsequently tightening precision
class ScopedMutex
Mutex that is applied/released at start/end of a scope.
class SDFBox
A box (3 dimensions)
class SDFCircle
A circle (2 dimensions)
class SDFCone
A cone (3 dimensions)
class SDFCube
A cube (3 dimensions)
class SDFCylinder
A cylinder (3 dimensions)
class SDFEllipsoid
An ellipsoid (3 dimensions)
class SDFParaboloid
A paraboloid (3 dimensions)
class SDFPlane
A plane surface (3 dimensions)
class SDFRectangle
A rectangle (2 dimensions)
class SDFSphere
A spherical surface (3 dimensions)
class SeparatedConvolution
Convolutions in separated form (including Gaussian)
struct SeparatedConvolutionData
SeparatedConvolutionData keeps data for all terms, all dimensions.
struct SeparatedConvolutionInternal
struct ShallowNode
shallow-copy, pared-down version of FunctionNode, for special purpose only
class SignedDFInterface
The interface for a signed distance function (sdf).
class SimpleCache
Simplified interface around hash_map to cache stuff for 1D.
class SimplePmap
A simple process map.
class Slater
A nuclear correlation factor class.
class SlaterF12Interface
a function like f(x) = (1 - exp(-mu x))/(2 gamma)
class SlaterFunctionInterface
a function like f(x)=exp(-mu x)
class Slice
A slice defines a sub-range or patch of a dimension.
class SliceGenTensor
class SliceLowRankTensor
implements a temporary(!) slice of a LowRankTensor
class SliceTensor
Indexing a non-constant tensor with slices returns a SliceTensor.
class Solver
The main class of the periodic DFT solver
.
struct SolverTargetInterface
The interface to be provided by targets for non-linear equation solver.
struct Specialbox_op
class SpectralPropagator
Spectral propagtor in time. Refer to documentation of file spectralprop.h for math detail.
class SpectralPropagatorGaussLobatto
struct spherical_box
an 2-dimensional smooth mask that is 1 inside the radius and 0 outside
class Spinlock
Spinlock using pthread spinlock operations.
class SRConf
class Stack
Dynamically sized Stack with small stack size optimization.
class SteepestDescent
Unconstrained minimization via steepest descent.
class StrongOrthogonalityProjector
a SO projector class
class Subspace
The SubspaceK class is a container class holding previous orbitals and residuals.
class SubspaceK
The SubspaceK class is a container class holding previous orbitals and residuals.
class SVDTensor
class SystolicFixOrbitalOrders
class SystolicMatrixAlgorithm
Base class for parallel algorithms that employ a systolic loop to generate all row pairs in parallel.
class SystolicPMOrbitalLocalize
class TaggedKey
Key object that uses a tag to differentiate keys.
class TaskAttributes
Contains attributes of a task.
struct TaskFn
Wrap a callable object and its arguments into a task function.
struct TaskFunction
class TaskInterface
All world tasks must be derived from this public interface.
struct TaskMemfun
class TaskThreadEnv
Used to pass information about the thread environment to a user's task.
class TDHF
struct TDHF_allocator
class Tensor
A tensor is a multidimension array.
struct TensorArgs
TensorArgs holds the arguments for creating a LowRankTensor.
class TensorException
Tensor is intended to throw only TensorExceptions.
class TensorIterator
struct TensorResultType
TensorResultType<L,R>::type is the type of (L op R) where op is nominally multiplication.
class TensorTrain
class TensorTypeData
Traits class to specify support of numeric types.
class TensorTypeFromId
This provides the reverse mapping from integer id to type name.
struct test_output
small class for pretty printing of test output
class Thread
Simplified thread wrapper to hide pthread complexity.
class ThreadBase
Simplified thread wrapper to hide pthread complexity.
class ThreadPool
A singleton pool of threads for dynamic execution of tasks.
class ThreadPoolThread
ThreadPool thread object.
class Timer
struct trajectory
struct true_op
class TwoElectronFactory
factory for generating TwoElectronInterfaces
class TwoElectronInterface
base class to compute the wavelet coefficients for an isotropic 2e-operator
class twoscale_cache_class
struct unaryexp
struct UnaryOpStructure
computes the corrected exchange correlation potential using the multipole approximation
class uniqueidT
Class for unique global IDs.
struct valarray_allocator
class Vector
A simple, fixed dimension vector.
class VectorOfFunctionsSpace
A vector space using MADNESS Vectors of MADNESS Functions.
class VectorSpace
A vector space using MADNESS Vectors.
class VextCosFunctor
A generic functor to compute external potential for TDDFT.
class VLocalFunctor
class World
A parallel world class.
struct WorldAbsMaxOp
struct WorldAbsMinOp
class WorldAmInterface
Implements AM interface.
struct WorldBitAndOp
struct WorldBitOrOp
struct WorldBitXorOp
class WorldContainer
Makes a distributed container with specified attributes.
class WorldContainerImpl
Internal implementation of distributed container to facilitate shallow copy.
class WorldContainerIterator
Iterator for distributed container wraps the local iterator.
class WorldDCDefaultPmap
Default process map is "random" using madness::hash(key)
class WorldDCPmapInterface
Interface to be provided by any process map.
class WorldDCRedistributeInterface
class WorldGopInterface
Provides collectives that interoperate with the AM and task interfaces.
struct WorldLogicAndOp
struct WorldLogicOrOp
struct WorldMaxOp
class WorldMemInfo
Used to output memory statistics and control tracing, etc.
struct WorldMinOp
class WorldMpiInterface
This class wraps/extends the MPI interface for World.
struct WorldMultOp
class WorldObject
Implements most parts of a globally addressable object (via unique ID).
class WorldProfile
Singleton-like class for holding profiling data and functionality.
struct WorldProfileEntry
Used to store profiler info.
class WorldProfileObj
struct WorldSumOp
class WorldTaskQueue
Multi-threaded queue to manage and run tasks.
class WSTAtomicBasisFunctor
struct xc_functional
Class to compute the energy functional.
struct xc_kernel_apply
Class to compute terms of the kernel.
struct xc_lda_potential
Compute the spin-restricted LDA potential using unaryop (only for the initial guess)
struct xc_potential
Class to compute terms of the potential.
class XCfunctional
Simplified interface to XC functionals.
class XCFunctionalLDA
class XCOperator
operator class for the handling of DFT exchange-correlation functionals
class XNonlinearSolver
Generalized version of NonlinearSolver not limited to a single madness function.
class Zcis
class Znemo
Typedefs
typedef void(* am_handlerT) (const AmArg &)
Type of AM handler functions.
typedef SeparatedConvolution< double_complex, 1 > complex_convolution_1d
typedef std::shared_ptr< complex_convolution_1d > complex_convolution_1d_ptr
typedef SeparatedConvolution< double_complex, 2 > complex_convolution_2d
typedef std::shared_ptr< complex_convolution_2d > complex_convolution_2d_ptr
typedef SeparatedConvolution< double_complex, 3 > complex_convolution_3d
typedef std::shared_ptr< complex_convolution_3d > complex_convolution_3d_ptr
typedef SeparatedConvolution< double_complex, 4 > complex_convolution_4d
typedef std::shared_ptr< complex_convolution_4d > complex_convolution_4d_ptr
typedef SeparatedConvolution< double_complex, 5 > complex_convolution_5d
typedef std::shared_ptr< complex_convolution_5d > complex_convolution_5d_ptr
typedef SeparatedConvolution< double_complex, 6 > complex_convolution_6d
typedef std::shared_ptr< complex_convolution_6d > complex_convolution_6d_ptr
typedef Derivative< double_complex, 1 > complex_derivative_1d
typedef Derivative< double_complex, 2 > complex_derivative_2d
typedef Derivative< double_complex, 3 > complex_derivative_3d
typedef Derivative< double_complex, 4 > complex_derivative_4d
typedef Derivative< double_complex, 5 > complex_derivative_5d
typedef Derivative< double_complex, 6 > complex_derivative_6d
typedef FunctionFactory< double_complex, 1 > complex_factory_1d
typedef FunctionFactory< double_complex, 2 > complex_factory_2d
typedef FunctionFactory< double_complex, 3 > complex_factory_3d
typedef FunctionFactory< double_complex, 4 > complex_factory_4d
typedef FunctionFactory< double_complex, 5 > complex_factory_5d
typedef FunctionFactory< double_complex, 6 > complex_factory_6d
typedef FunctionImpl< double_complex, 1 > complex_funcimpl_1d
typedef FunctionImpl< double_complex, 2 > complex_funcimpl_2d
typedef FunctionImpl< double_complex, 3 > complex_funcimpl_3d
typedef FunctionImpl< double_complex, 4 > complex_funcimpl_4d
typedef FunctionImpl< double_complex, 5 > complex_funcimpl_5d
typedef FunctionImpl< double_complex, 6 > complex_funcimpl_6d
typedef Function< double_complex, 1 > complex_function_1d
typedef Function< double_complex, 2 > complex_function_2d
typedef Function< double_complex, 3 > complex_function_3d
typedef Function< double_complex, 4 > complex_function_4d
typedef Function< double_complex, 5 > complex_function_5d
typedef Function< double_complex, 6 > complex_function_6d
typedef Function< std::complex< double >, 3 > complex_functionT
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 1 > > complex_functor_1d
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 2 > > complex_functor_2d
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 3 > > complex_functor_3d
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 4 > > complex_functor_4d
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 5 > > complex_functor_5d
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 6 > > complex_functor_6d
typedef Convolution1D< double_complex > complex_operatorT
typedef Tensor< double_complex > complex_tensor
typedef PthreadConditionVariable CONDITION_VARIABLE_TYPE
typedef Vector< double, 1 > coord_1d
typedef Vector< double, 2 > coord_2d
typedef Vector< double, 3 > coord_3d
typedef Vector< double, 4 > coord_4d
typedef Vector< double, 5 > coord_5d
typedef Vector< double, 6 > coord_6d
typedef Vector< double, 3 > coordT
typedef std::vector< complex_functionT > cvecfuncT
typedef DistributedMatrix< double > distmatT
typedef std::pair< uniqueidT, std::size_t > DistributedID
Distributed ID which is used to identify objects.
typedef FunctionFactory< double, 3 > factoryT
typedef FunctionDefaults< 1 > function_defaults_1d
typedef FunctionDefaults< 2 > function_defaults_2d
typedef FunctionDefaults< 3 > function_defaults_3d
typedef FunctionDefaults< 4 > function_defaults_4d
typedef FunctionDefaults< 5 > function_defaults_5d
typedef FunctionDefaults< 6 > function_defaults_6d
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
template<typename T >
using future_to_ref_t = typename future_to_ref< T >::type
typedef std::size_t hashT
The hash value type.
typedef Pairs< real_function_3d > intermediateT
f12 and g12 intermediates of the form <f1|op|f2> (with op=f12 or op=g12) will be saved using the pair structure
typedef int Level
typedef NonlinearSolverND< 3 > NonlinearSolver
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::pair< vecfuncT, vecfuncT > pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 1 > > > pmap_1d
typedef std::shared_ptr< WorldDCPmapInterface< Key< 2 > > > pmap_2d
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmap_3d
typedef std::shared_ptr< WorldDCPmapInterface< Key< 4 > > > pmap_4d
typedef std::shared_ptr< WorldDCPmapInterface< Key< 5 > > > pmap_5d
typedef std::shared_ptr< WorldDCPmapInterface< Key< 6 > > > pmap_6d
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef SeparatedConvolution< double, 1 > real_convolution_1d
typedef std::shared_ptr< real_convolution_1d > real_convolution_1d_ptr
typedef SeparatedConvolution< double, 2 > real_convolution_2d
typedef std::shared_ptr< real_convolution_2d > real_convolution_2d_ptr
typedef SeparatedConvolution< double, 3 > real_convolution_3d
typedef std::shared_ptr< real_convolution_3d > real_convolution_3d_ptr
typedef SeparatedConvolution< double, 4 > real_convolution_4d
typedef std::shared_ptr< real_convolution_4d > real_convolution_4d_ptr
typedef SeparatedConvolution< double, 5 > real_convolution_5d
typedef std::shared_ptr< real_convolution_5d > real_convolution_5d_ptr
typedef SeparatedConvolution< double, 6 > real_convolution_6d
typedef std::shared_ptr< real_convolution_6d > real_convolution_6d_ptr
typedef Derivative< double, 1 > real_derivative_1d
typedef Derivative< double, 2 > real_derivative_2d
typedef Derivative< double, 3 > real_derivative_3d
typedef Derivative< double, 4 > real_derivative_4d
typedef Derivative< double, 5 > real_derivative_5d
typedef Derivative< double, 6 > real_derivative_6d
typedef FunctionFactory< double, 1 > real_factory_1d
typedef FunctionFactory< double, 2 > real_factory_2d
typedef FunctionFactory< double, 3 > real_factory_3d
typedef FunctionFactory< double, 4 > real_factory_4d
typedef FunctionFactory< double, 5 > real_factory_5d
typedef FunctionFactory< double, 6 > real_factory_6d
typedef FunctionImpl< double, 1 > real_funcimpl_1d
typedef FunctionImpl< double, 2 > real_funcimpl_2d
typedef FunctionImpl< double, 3 > real_funcimpl_3d
typedef FunctionImpl< double, 4 > real_funcimpl_4d
typedef FunctionImpl< double, 5 > real_funcimpl_5d
typedef FunctionImpl< double, 6 > real_funcimpl_6d
typedef Function< double, 1 > real_function_1d
typedef Function< double, 2 > real_function_2d
typedef Function< double, 3 > real_function_3d
typedef Function< double, 4 > real_function_4d
typedef Function< double, 5 > real_function_5d
typedef Function< double, 6 > real_function_6d
typedef std::shared_ptr< FunctionFunctorInterface< double, 1 > > real_functor_1d
typedef std::shared_ptr< FunctionFunctorInterface< double, 2 > > real_functor_2d
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > real_functor_3d
typedef std::shared_ptr< FunctionFunctorInterface< double, 4 > > real_functor_4d
typedef std::shared_ptr< FunctionFunctorInterface< double, 5 > > real_functor_5d
typedef std::shared_ptr< FunctionFunctorInterface< double, 6 > > real_functor_6d
typedef Tensor< double > real_tensor
template<typename T >
using remove_fcvr_t = typename remove_fcvr< T >::type
template<typename T >
using remove_future_t = typename remove_future< T >::type
C++11 version of REMFUTURE.
typedef void(* rmi_handlerT) (void *buf, size_t nbyte)
This is the generic low-level interface for a message handler.
typedef Mutex SCALABLE_MUTEX_TYPE
typedef Mutex SPINLOCK_TYPE
typedef tbb::split Split
Dummy class, a la Intel TBB, used to distinguish splitting constructor.
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double_complex > tensor_complex
typedef Tensor< double > tensor_real
typedef Tensor< double > tensorT
typedef int64_t Translation
typedef vector< functionT > vecfuncT
typedef std::vector< std::complex< double > > vector_complex
typedef std::vector< complex_function_1d > vector_complex_function_1d
typedef std::vector< complex_function_2d > vector_complex_function_2d
typedef std::vector< complex_function_3d > vector_complex_function_3d
typedef std::vector< complex_function_4d > vector_complex_function_4d
typedef std::vector< complex_function_5d > vector_complex_function_5d
typedef std::vector< complex_function_6d > vector_complex_function_6d
typedef std::vector< Vector< double, 1 > > vector_coord_1d
typedef std::vector< Vector< double, 2 > > vector_coord_2d
typedef std::vector< Vector< double, 3 > > vector_coord_3d
typedef std::vector< Vector< double, 4 > > vector_coord_4d
typedef std::vector< Vector< double, 5 > > vector_coord_5d
typedef std::vector< Vector< double, 6 > > vector_coord_6d
typedef std::vector< double > vector_real
typedef std::vector< real_function_1d > vector_real_function_1d
typedef std::vector< real_function_2d > vector_real_function_2d
typedef std::vector< real_function_3d > vector_real_function_3d
typedef std::vector< real_function_4d > vector_real_function_4d
typedef std::vector< real_function_5d > vector_real_function_5d
typedef std::vector< real_function_6d > vector_real_function_6d
Enumerations
enum BCType {
BC_ZERO, BC_PERIODIC, BC_FREE, BC_DIRICHLET,
BC_ZERONEUMANN, BC_NEUMANN
}
enum CalcType {
CT_UNDEFINED, CT_MP2, CT_CC2, CT_LRCCS,
CT_LRCC2, CT_CISPD, CT_ADC2, CT_TDHF,
CT_TEST
}
Calculation Types used by CC2.
enum CCState { CCSTATE_UNDEFINED, GROUND_STATE, EXCITED_STATE }
Type of Pairs used by CC_Pair2 class.
enum EnergyType { PROJECTED_ENERGYTYPE, HYLLERAAS_ENERGYTYPE, UNKNOWN_ENERGYTYPE }
enum FuncType {
UNDEFINED, HOLE, PARTICLE, MIXED,
RESPONSE
}
Types of Functions used by CC_function class.
enum GuessType {
PARTIAL_WAVE_GUESSTYPE, FROM_FILE_GUESSTYPE, PREDEFINED_GUESSTYPE, SCF_GUESSTYPE,
EXOP_GUESSTYPE, EMPTY_GUESSTYPE, PSI4_GUESSTYPE, UNKNOWN_GUESSTYPE
}
enum OpType { OT_UNDEFINED, OT_G12, OT_F12 }
Operatortypes used by the CCConvolutionOperator Class.
enum PairFormat { PT_UNDEFINED, PT_FULL, PT_DECOMPOSED, PT_OP_DECOMPOSED }
FuncTypes used by the CC_function_6d structure.
enum PairType {
MP2_PAIRTYPE, CISPD_PAIRTYPE, ALL_PAIRTYPE, NONE_PAIRTYPE,
UNKNOWN_PAIRTYPE
}
enum PotentialType {
POT_UNDEFINED, POT_F3D_, POT_s3a_, POT_s3b_,
POT_s3c_, POT_s5a_, POT_s5b_, POT_s5c_,
POT_s2b_, POT_s2c_, POT_s4a_, POT_s4b_,
POT_s4c_, POT_s6_, POT_ccs_, POT_cis_,
POT_singles_
}
CC2 Singles Potentials.
enum TensorType { TT_NONE, TT_FULL, TT_2D, TT_TENSORTRAIN }
low rank representations of tensors (see gentensor.h)
Functions
static const Slice _ (0,-1, 1)
static const Slice _reverse (-1, 0,-1)
Entire tensor.
double abs (double x)
template<typename Q , int NDIM>
Function< typename TensorTypeData< Q >::scalar_type, NDIM > abs (const Function< Q, NDIM > &func)
template<typename T , std::size_t NDIM>
Function< T, NDIM > abs (const Function< T, NDIM > &f, bool fence=true)
Create a new function that is the abs of f - global comm only if not reconstructed.
template<class T >
Tensor< typename Tensor< T >::scalar_type > abs (const Tensor< T > &t)
Return a new tensor holding the absolute value of each element of t.
template<std::size_t NDIM>
Function< double, NDIM > abs (const Function< double_complex, NDIM > &z, bool fence=true)
Returns a new function that is the absolute value of the input.
template<typename Q , int NDIM>
Function< typename TensorTypeData< Q >::scalar_type, NDIM > abs_square (const Function< Q, NDIM > &func)
template<typename T , std::size_t NDIM>
std::enable_if<!TensorTypeData< T >::iscomplex, Function< T, NDIM > >::type abs_square (const Function< T, NDIM > &f, bool fence=true)
Create a new function that is the abs_square of f - global comm only if not reconstructed.
template<typename T , std::size_t NDIM>
std::enable_if< TensorTypeData< T >::iscomplex, Function< typename Tensor< T >::scalar_type, NDIM > >::type abs_square (const Function< T, NDIM > &f, bool fence=true)
Create a new function that is the abs_square of f - global comm only if not reconstructed.
template<typename T , std::size_t NDIM>
std::vector< Function< typename Tensor< T >::scalar_type, NDIM > > abssq (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Computes the square of a vector of functions — q[i] = abs(v[i])**2.
template<std::size_t NDIM>
Function< double, NDIM > abssq (const Function< double_complex, NDIM > &z, bool fence=true)
Returns a new function that is the square of the absolute value of the input.
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > add (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true, unsigned int blk=1)
Returns new vector of functions — q[i] = a[i] + b[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > add (World &world, const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true, unsigned int blk=1)
Returns new vector of functions — q[i] = a + b[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > add (World &world, const std::vector< Function< R, NDIM > > &b, const Function< T, NDIM > &a, bool fence=true, unsigned int blk=1)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > add (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true)
Returns new vector of functions — q[i] = a[i] + b[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > add (World &world, const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true)
Returns new vector of functions — q[i] = a + b[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > add (World &world, const std::vector< Function< R, NDIM > > &b, const Function< T, NDIM > &a, bool fence=true)
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > add (const Function< L, NDIM > &left, const Function< R, NDIM > &right, bool fence=true)
Same as operator+ but with optional fence and no automatic compression.
template<typename funcT >
funcT::returnT adq (double lo, double hi, const funcT &func, double thresh)
template<typename funcT >
funcT::returnT adq1 (double lo, double hi, const funcT &func, double thresh, int n, const double *x, const double *w, int level)
void aligned_add (long n, double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
void aligned_add (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b)
template<typename T , typename Q >
static void aligned_add (long n, T *MADNESS_RESTRICT a, const Q *MADNESS_RESTRICT b)
template<typename T , typename Q >
static void aligned_axpy (long n, T *MADNESS_RESTRICT a, const T *MADNESS_RESTRICT b, Q s)
template<>
void aligned_axpy (long n, double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b, double s)
template<>
void aligned_axpy (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b, double_complex s)
template<>
void aligned_axpy (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b, double s)
void aligned_sub (long n, double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
void aligned_sub (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b)
template<typename T , typename Q >
static void aligned_sub (long n, T *MADNESS_RESTRICT a, const Q *MADNESS_RESTRICT b)
template<typename T >
static void aligned_zero (long n, T *a)
AmArg * alloc_am_arg (std::size_t nbyte)
Allocates a new AmArg with nbytes of user data ... delete with free_am_arg.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > append (const std::vector< Function< T, NDIM > > &lhs, const std::vector< Function< T, NDIM > > &rhs)
combine two vectors
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > append (const std::vector< std::vector< Function< T, NDIM > > > vv)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > apply (World &world, const Derivative< T, NDIM > &D, const std::vector< Function< T, NDIM > > &v, const unsigned int blk=1, const bool fence=true)
Applies a derivative operator to a vector of functions.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > apply (World &world, const Derivative< T, NDIM > &D, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Applies a derivative operator to a vector of functions.
template<typename T , std::size_t NDIM>
Function< T, NDIM > apply (const Derivative< T, NDIM > &D, const Function< T, NDIM > &f, bool fence=true)
Applies derivative operator to function (for syntactic equivalence to integral operator apply)
template<typename opT , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(typename opT::opT, R), NDIM > > apply (World &world, const std::vector< std::shared_ptr< opT > > &op, const std::vector< Function< R, NDIM > > f, const unsigned int blk=1)
Applies a vector of operators to a vector of functions — q[i] = apply(op[i],f[i])
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > apply (World &world, const SeparatedConvolution< T, NDIM > &op, const std::vector< Function< R, NDIM > > f, const unsigned int blk=1)
Applies an operator to a vector of functions — q[i] = apply(op,f[i])
template<typename opT , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(typename opT::opT, R), NDIM > > apply (World &world, const std::vector< std::shared_ptr< opT > > &op, const std::vector< Function< R, NDIM > > f)
Applies a vector of operators to a vector of functions — q[i] = apply(op[i],f[i])
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > apply (World &world, const SeparatedConvolution< T, NDIM > &op, const std::vector< Function< R, NDIM > > f)
Applies an operator to a vector of functions — q[i] = apply(op,f[i])
template<class T , class Q >
TensorTrain< TENSOR_RESULT_TYPE(T, Q)> apply (const TensorTrain< T > &op, const TensorTrain< Q > &t, const double thresh)
apply an operator in TT format on a tensor in TT format
template<typename opT , typename T , std::size_t LDIM>
Function< TENSOR_RESULT_TYPE(typename opT::opT, T), LDIM+LDIM > apply (const opT &op, const Function< T, LDIM > &f1, const Function< T, LDIM > &f2, bool fence=true)
Apply operator on a hartree product of two low-dimensional functions.
template<typename opT , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(typename opT::opT, R), NDIM > apply (const opT &op, const Function< R, NDIM > &f, bool fence=true)
Apply operator in non-standard form.
complex_functionT APPLY (const complex_operatorT *q1d, const complex_functionT &psi)
template<typename opT , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(typename opT::opT, R), NDIM > apply_1d_realspace_push (const opT &op, const Function< R, NDIM > &f, int axis, bool fence=true)
static void apply_c2 (double xaxis, double yaxis, double zaxis, double &x, double &y, double &z)
Apply to (x,y,z) a C2 rotation about an axis thru the origin and (xaxis,yaxis,zaxis)
static void apply_inverse (double xjunk, double yjunk, double zjunk, double &x, double &y, double &z)
template<typename opT , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(typename opT::opT, R), NDIM > apply_only (const opT &op, const Function< R, NDIM > &f, bool fence=true)
Apply operator ONLY in non-standard form - required other steps missing !!
static void apply_sigma (double xaxis, double yaxis, double zaxis, double &x, double &y, double &z)
Apply to (x,y,z) a reflection through a plane containing the origin with normal (xaxis,yaxis,zaxis)
template<class T >
Tensor< typename Tensor< T >::scalar_type > arg (const Tensor< T > &t)
Return a new tensor holding the argument of each element of t (complex types only)
CalcType assign_calctype (const std::string name)
Assigns enum to string.
std::string assign_name (const PairFormat &input)
Assigns strings to enums for formated output.
std::string assign_name (const CCState &input)
Assigns strings to enums for formated output.
std::string assign_name (const OpType &input)
Assigns strings to enums for formated output.
std::string assign_name (const CalcType &inp)
Assigns strings to enums for formated output.
std::string assign_name (const PotentialType &inp)
Assigns strings to enums for formated output.
std::string assign_name (const FuncType &inp)
Assigns strings to enums for formated output.
std::string atomic_number_to_symbol (const unsigned int atomic_number)
return the lower-case element symbol corresponding to the atomic number
bool autoc (int k, Tensor< double > *c)
Return the autocorrelation coefficients for scaling functions of given order.
void bandlimited_propagator_plot ()
void begin_papi_measurement ()
void bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, __complex__ double *c_x, const __complex__ double *a_x, const __complex__ double *b_x)
void bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, __complex__ double *c_x, const __complex__ double *a_x, const double *b_x)
void bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, __complex__ double *c_x, const double *a_x, const __complex__ double *b_x)
void bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, double *c_x, const double *a_x, const double *b_x)
template<typename L , typename R , typename opT , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > binary_op (const Function< L, NDIM > &left, const Function< R, NDIM > &right, const opT &op, bool fence=true)
Generate new function = op(left,right) where op acts on the function values.
template<std::size_t NDIM>
static SeparatedConvolution< double, NDIM > BSHOperator (World &world, double mu, double lo, double eps, const BoundaryConditions< NDIM > &bc=FunctionDefaults< NDIM >::get_bc(), int k=FunctionDefaults< NDIM >::get_k())
Factory function generating separated kernel for convolution with BSH kernel in general NDIM.
static SeparatedConvolution< double, 3 > BSHOperator3D (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
static SeparatedConvolution< double, 3 > * BSHOperatorPtr3D (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
int c_rks_vwn5__ (const double *r__, double *f, double *dfdra)
int c_uks_vwn5__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
template<typename T >
void change_tensor_type (GenTensor< T > &t, const TensorArgs &targs)
change representation to targ.tt
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type check_for_inf (const std::string &str, T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type check_for_inf (const std::string &str, T &arg)
bool check_if_pseudo_atom (const std::string &symbol)
template<typename C >
void check_linear_dependence (const Tensor< C > &Q, Tensor< C > &c, const double rcondtol, const double cabsmax, bool do_print=true)
check for subspace linear dependency
unsigned long checksum_file (const char *filename)
Simple checksum for ASCII characters in file.
template<typename T >
void cholesky (Tensor< T > &A)
Compute the Cholesky factorization.
template void cholesky (Tensor< double > &A)
template void cholesky (Tensor< double_complex > &A)
template<typename T >
DistributedMatrix< T > column_distributed_matrix (World &world, int64_t n, int64_t m, int64_t coltile=0)
Generates an (n,m) matrix distributed by columns (row dimension is not distributed)
static DistributedMatrixDistribution column_distributed_matrix_distribution (World &world, int64_t n, int64_t m, int64_t coltile)
Generates distribution for an (n,m) matrix distributed by columns (row dimension is not distributed)
template<typename T , std::size_t NDIM>
void compress (World &world, const std::vector< Function< T, NDIM > > &v, unsigned int blk=1, bool fence=true)
Compress a vector of functions.
template<typename T , std::size_t NDIM>
void compress (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Compress a vector of functions.
template<typename T >
DistributedMatrix< T > concatenate_columns (const DistributedMatrix< T > &a, const DistributedMatrix< T > &b)
Generates a row-distributed matrix with rows of a and b contatenated.
template<typename T >
DistributedMatrix< T > concatenate_rows (const DistributedMatrix< T > &a, const DistributedMatrix< T > &b)
Generates a column-distributed matrix with rows of a and b contatenated.
template<typename T >
DistributedMatrix< T > concatenate_rows (const DistributedMatrix< T > &a, const DistributedMatrix< T > &b, const DistributedMatrix< T > &c, const DistributedMatrix< T > &d)
Generates a column-distributed matrix with rows of a, b, c, and d contatenated in order.
template<typename Q >
Q conditional_conj (const Q &coeff)
For real types return value, for complex return conjugate.
double conj (double x)
double conj (float x)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > conj (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Returns the complex conjugate of the vector of functions.
template<typename T , std::size_t NDIM>
Function< T, NDIM > conj (const Function< T, NDIM > &f, bool fence=true)
Return the complex conjugate of the input function with the same distribution and optional fence.
template<class T >
Tensor< T > conj (const Tensor< T > &t)
Returns a new deep copy of the complex conjugate of the input tensor (complex types only)
template<class T >
Tensor< T > conj_transpose (const Tensor< T > &t)
Returns a new deep copy of the complex conjugate transpose of the input tensor.
template<class Q , class T >
LowRankTensor< Q > convert (const LowRankTensor< T > &other)
type conversion implies a deep copy
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< R, NDIM > > convert (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Returns a deep copy of a vector of functions.
template<typename T , typename Q , std::size_t NDIM>
Function< Q, NDIM > convert (const Function< T, NDIM > &f, bool fence=true)
Type conversion implies a deep copy. No communication except for optional fence.
template<class Q , class T >
Tensor< Q > convert (const Tensor< T > &t)
Returns a new contiguous tensor of type Q that is a deep copy of the input.
template<typename T >
DistributedMatrix< T > copy (const DistributedMatrix< T > &A)
Deep copy of content.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > copy (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Returns a deep copy of a vector of functions.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > copy (World &world, const Function< T, NDIM > &v, const unsigned int n, bool fence=true)
Returns a vector of deep copies of of a function.
template<typename T , std::size_t NDIM>
Function< T, NDIM > copy (const Function< T, NDIM > &f, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &pmap, bool fence=true)
Create a new copy of the function with different distribution and optional fence.
template<typename T , std::size_t NDIM>
Function< T, NDIM > copy (const Function< T, NDIM > &f, bool fence=true)
Create a new copy of the function with the same distribution and optional fence.
template<class T >
Tensor< T > copy (const Tensor< T > &t)
Returns a new contiguous tensor that is a deep copy of the input.
template<typename T >
static void copy_2d_patch (T *MADNESS_RESTRICT out, long ldout, const T *MADNESS_RESTRICT in, long ldin, long n, long m)
AmArg * copy_am_arg (const AmArg &arg)
static SeparatedConvolution< double, 3 > CoulombOperator (World &world, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with 1/r in 3D.
static SeparatedConvolution< double, 3 > * CoulombOperatorPtr (World &world, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with 1/r in 3D.
double cpu_frequency ()
Estimate the processor frequency, in Hz.
void cpu_relax ()
Do nothing and especially do not touch memory.
static double cpu_time ()
Returns the cpu time in seconds relative to an arbitrary origin.
std::shared_ptr< NuclearCorrelationFactor > create_nuclear_correlation_factor (World &world, const Molecule &molecule, const std::shared_ptr< PotentialManager > potentialmanager, const std::string inputline)
create and return a new nuclear correlation factor
std::shared_ptr< NuclearCorrelationFactor > create_nuclear_correlation_factor (World &world, const Molecule &molecule, const std::shared_ptr< PotentialManager > pm, const std::pair< std::string, double > &ncf)
template<typename T , std::size_t N>
std::enable_if< N==3, Vector< T, N > >::type cross (const Vector< T, N > &l, const Vector< T, N > &r)
compute the cross product two Vectors of dimension 3
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > cross (const std::vector< Function< T, NDIM > > &f, const std::vector< Function< R, NDIM > > &g, bool do_refine=false, bool fence=true)
shorthand cross operator
std::vector< std::string > cubefile_header (std::string filename, const bool &no_orient=false)
static uint64_t cycle_count ()
On some machines we have access to a cycle count.
double d2smoothed_potential (double r)
second radial derivative of the regularized 1/r potential
template<size_t NDIM>
Key< NDIM > displacement (const Key< NDIM > &source, const Key< NDIM > &target)
given a source and a target, return the displacement in translation
double distance (const Fred &a, const Fred &b)
double distance (madness::Function< std::complex< double >, 1ul > &a, madness::Function< std::complex< double >, 1ul > &b)
static double distance (double x1, double y1, double z1, double x2, double y2, double z2)
double distance (double a, double b)
Default function for computing the distance between two doubles.
template<typename T >
double distance (std::complex< T > &a, std::complex< T > &b)
Default function for computing the distance between two complex numbers.
static double distance_sq (double x1, double y1, double z1, double x2, double y2, double z2)
DistributedMatrix< double > distributed_localize_PM (World &world, const vecfuncT &mo, const vecfuncT &ao, const std::vector< int > &set, const std::vector< int > &at_to_bf, const std::vector< int > &at_nbf, const double thresh=1e-9, const double thetamax=0.25, const bool randomize=true, const bool doprint=false)
template<typename T , std::size_t NDIM>
Function< T, NDIM > div (const std::vector< Function< T, NDIM > > &v, bool do_refine=false, bool fence=true)
shorthand div operator
template<typename funcT >
funcT::returnT do_adq (double lo, double hi, const funcT &func, int n, const double *x, const double *w)
template<typename T , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(T, R), NDIM > dot (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true)
Multiplies and sums two vectors of functions r = a[i] * b[i].
DPEC (int, int, int)
DPEC (long, long, long)
DPEC (float, float, float)
DPEC (double, double, double)
DPEC (float_complex, float_complex, float_complex)
DPEC (double_complex, double_complex, double_complex)
void drot (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
double dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
static void dxprintvalue (FILE *f, const double t)
static void dxprintvalue (FILE *f, const double_complex &t)
void end_papi_measurement ()
static void END_TIMER (World &world, const char *msg)
static bool enforce_bc (bool is_periodic, Level n, Translation &l)
void error (const char *msg)
template<typename T >
static void error (const char *msg, const T &data)
Prints an error message, along with some data, and aborts the program.
void exception_break (bool message)
This function is executed just before a MadnessException is thrown.
template<class T , class Q >
Tensor< TENSOR_RESULT_TYPE(T, Q) > & fast_transform (const Tensor< T > &t, const Tensor< Q > &c, Tensor< TENSOR_RESULT_TYPE(T, Q) > &result, Tensor< TENSOR_RESULT_TYPE(T, Q) > &workspace)
Restricted but heavily optimized form of transform()
template<typename T >
void fast_transpose (long n, long m, const T *a, T *MADNESS_RESTRICT b)
a(n,m) --> b(m,n) ... optimized for smallish matrices
template<typename T , std::size_t NDIM>
Tensor< T > fcube (const Key< NDIM > &, T(*f)(const Vector< double, NDIM > &), const Tensor< double > &)
template<typename T , std::size_t NDIM>
Tensor< T > fcube (const Key< NDIM > &key, const FunctionFunctorInterface< T, NDIM > &f, const Tensor< double > &qx)
template<typename T , std::size_t NDIM>
void fcube (const Key< NDIM > &key, const FunctionFunctorInterface< T, NDIM > &f, const Tensor< double > &qx, Tensor< T > &fval)
forward declaration
void finalize ()
Call this once at the very end of your main program instead of MPI_Finalize().
template<std::size_t NDIM, typename opT >
void foreach_child (const Key< NDIM > &parent, opT &op)
Applies op(key) to each child key of parent.
template<std::size_t NDIM, typename objT >
void foreach_child (const Key< NDIM > &parent, objT *obj, void(objT::*memfun)(const Key< NDIM > &))
Applies member function of obj to each child key of parent.
void free_am_arg (AmArg *arg)
Frees an AmArg allocated with alloc_am_arg.
template<typename T , std::size_t NDIM>
Derivative< T, NDIM > free_space_derivative (World &world, int axis, int k=FunctionDefaults< NDIM >::get_k())
Convenience function returning derivative operator with free-space boundary conditions.
std::shared_ptr< FunctionFunctorInterface< double, 3 > > func (new opT(g))
template<typename Q , int NDIM>
Function< std::complex< Q >, NDIM > function_real2complex (const Function< Q, NDIM > &r)
static double functor_r2 (const coord_3d &r)
static double functor_x (const coord_3d &r)
static double functor_y (const coord_3d &r)
template<typename T >
std::vector< Future< T > > future_vector_factory (std::size_t n)
Factory for a vectors of futures.
bool gauss_legendre (int n, double xlo, double xhi, double *x, double *w)
bool gauss_legendre_numeric (int n, double xlo, double xhi, double *x, double *w)
Compute the Gauss-Legendre quadrature points and weights.
bool gauss_legendre_test (bool print)
template<typename T , typename Q , typename R , std::size_t NDIM>
void gaxpy (World &world, Q alpha, std::vector< Function< T, NDIM > > &a, Q beta, const std::vector< Function< R, NDIM > > &b, unsigned int blk=1, bool fence=true)
Generalized A*X+Y for vectors of functions -— a[i] = alpha*a[i] + beta*b[i].
template<typename T , typename Q , typename R , std::size_t NDIM>
void gaxpy (World &world, Q alpha, std::vector< Function< T, NDIM > > &a, Q beta, const std::vector< Function< R, NDIM > > &b, bool fence=true)
Generalized A*X+Y for vectors of functions -— a[i] = alpha*a[i] + beta*b[i].
template<typename T , typename Q , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(Q, TENSOR_RESULT_TYPE(T, R)), NDIM > > gaxpy_oop (Q alpha, const std::vector< Function< T, NDIM > > &a, Q beta, const std::vector< Function< R, NDIM > > &b, bool fence=true)
out-of-place gaxpy for two vectors: result[i] = alpha * a[i] + beta * b[i]
template<typename T , typename Q , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(Q, TENSOR_RESULT_TYPE(T, R)), NDIM > > gaxpy_oop (Q alpha, const std::vector< Function< T, NDIM > > &a, Q beta, const Function< R, NDIM > &b, bool fence=true)
out-of-place gaxpy for a vectors and a function: result[i] = alpha * a[i] + beta * b
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > gaxpy_oop (TENSOR_RESULT_TYPE(L, R) alpha, const Function< L, NDIM > &left, TENSOR_RESULT_TYPE(L, R) beta, const Function< R, NDIM > &right, bool fence=true)
Returns new function alpha*left + beta*right optional fence and no automatic compression.
template<typename T , std::size_t NDIM>
Function< T, NDIM > gaxpy_oop_reconstructed (const double alpha, const Function< T, NDIM > &left, const double beta, const Function< T, NDIM > &right, const bool fence=true)
Returns new function alpha*left + beta*right optional fence, having both addends reconstructed.
template<typename T >
void gelss (const Tensor< T > &a, const Tensor< T > &b, double rcond, Tensor< T > &x, Tensor< typename Tensor< T >::scalar_type > &s, long &rank, Tensor< typename Tensor< T >::scalar_type > &sumsq)
Solve Ax = b for general A using the LAPACK *gelss routines.
template void gelss (const Tensor< double > &a, const Tensor< double > &b, double rcond, Tensor< double > &x, Tensor< Tensor< double >::scalar_type > &s, long &rank, Tensor< Tensor< double >::scalar_type > &sumsq)
template void gelss (const Tensor< double_complex > &a, const Tensor< double_complex > &b, double rcond, Tensor< double_complex > &x, Tensor< Tensor< double_complex >::scalar_type > &s, long &rank, Tensor< Tensor< double_complex >::scalar_type > &sumsq)
template<class T , class Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q)> general_transform (const LowRankTensor< T > &t, const Tensor< Q > c[])
template<class T , class Q >
GenTensor< TENSOR_RESULT_TYPE(T, Q)> general_transform (const GenTensor< T > &t, const Tensor< Q > c[])
Transform all dimensions of the tensor t by distinct matrices c.
template<class T >
GenTensor< T > general_transform (const GenTensor< T > &t, const Tensor< T > c[])
template<class T , class Q >
TensorTrain< TENSOR_RESULT_TYPE(T, Q)> general_transform (const TensorTrain< T > &t, const Tensor< Q > c[])
Transform all dimensions of the tensor t by distinct matrices c.
template<class T , class Q >
Tensor< TENSOR_RESULT_TYPE(T, Q)> general_transform (const Tensor< T > &t, const Tensor< Q > c[])
Transform all dimensions of the tensor t by distinct matrices c.
template<typename T >
void geqp3 (Tensor< T > &A, Tensor< T > &tau, Tensor< integer > &jpvt)
Compute the QR factorization.
template void geqp3 (Tensor< double > &A, Tensor< double > &tau, Tensor< integer > &jpvt)
template<typename T >
void geqp3_result (Tensor< T > &A, Tensor< T > &tau, Tensor< integer > &jpvt, Tensor< T > &work)
template<typename T >
void gesv (const Tensor< T > &a, const Tensor< T > &b, Tensor< T > &x)
Solve Ax = b for general A using the LAPACK *gesv routines.
template void gesv (const Tensor< double > &a, const Tensor< double > &b, Tensor< double > &x)
template void gesv (const Tensor< double_complex > &a, const Tensor< double_complex > &b, Tensor< double_complex > &x)
template<typename T >
void gesvp (World &world, const Tensor< T > &a, const Tensor< T > &b, Tensor< T > &x)
const AtomicData & get_atomic_data (unsigned int atomic_number)
double get_charge_from_file (const std::string filename, unsigned int atype)
const long long * get_papi_measurement ()
template<typename T , std::size_t NDIM>
double get_size (World &world, const std::vector< Function< T, NDIM > > &v)
template<typename T , std::size_t NDIM>
double get_size (const Function< T, NDIM > &f)
template<typename T , typename real_type , typename scalar_type >
void GMRES (const AbstractVectorSpace< T, real_type, scalar_type > &space, const Operator< T > &op, const T &b, T &x, int &maxiters, real_type &resid_thresh, real_type &update_thresh, const bool outp=false)
A GMRES solver routine for linear systems, .
void gprofexit (int id, int nproc)
Rename gmon.out for each process by ordering process termination.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > grad (const Function< T, NDIM > &f, bool refine=false, bool fence=true)
shorthand gradient operator
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > grad_ble_one (const Function< T, NDIM > &f, bool refine=false, bool fence=true)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > grad_ble_two (const Function< T, NDIM > &f, bool refine=false, bool fence=true)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > grad_bpsline_two (const Function< T, NDIM > &f, bool refine=false, bool fence=true)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > grad_bspline_one (const Function< T, NDIM > &f, bool refine=false, bool fence=true)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > grad_bspline_three (const Function< T, NDIM > &f, bool refine=false, bool fence=true)
static std::vector< std::shared_ptr< SeparatedConvolution< double, 3 > > > GradBSHOperator (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating operator for convolution with grad(bsh) in 3D.
static std::vector< std::shared_ptr< SeparatedConvolution< double, 3 > > > GradCoulombOperator (World &world, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating operator for convolution with grad(1/r) in 3D.
template<typename T , std::size_t NDIM>
std::vector< std::shared_ptr< Derivative< T, NDIM > > > gradient_operator (World &world, const BoundaryConditions< NDIM > &bc=FunctionDefaults< NDIM >::get_bc(), int k=FunctionDefaults< NDIM >::get_k())
Convenience function returning vector of derivative operators implementing grad ()
static std::vector< std::shared_ptr< SeparatedConvolution< double, 3 > > > GradSlaterOperator (World &world, double gamma, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating operator for convolution with grad(e^{-*r}) in 3D.
template<typename T , std::size_t KDIM, std::size_t LDIM>
Function< T, KDIM+LDIM > hartree_product (const Function< T, KDIM > &left2, const Function< T, LDIM > &right2)
Performs a Hartree product on the two given low-dimensional functions.
template<typename T , std::size_t KDIM, std::size_t LDIM, typename opT >
Function< T, KDIM+LDIM > hartree_product (const Function< T, KDIM > &left2, const Function< T, LDIM > &right2, const opT &op)
Performs a Hartree product on the two given low-dimensional functions.
template<typename T >
bool has_zero_rank (const GenTensor< T > &g)
true if GenTensor has zero rank or no data
template<class T >
void hash_combine (hashT &seed, const T &v)
Combine hash values.
template<class It >
void hash_range (hashT &seed, It first, It last)
Combine the hash values of an iterator range.
template<class It >
hashT hash_range (It first, It last)
Combine the hash values of an iterator range.
template<class T , std::size_t n>
hashT hash_range (const T(&t)[n])
Combine the hash values of a C-style array.
template<class T , std::size_t n>
void hash_range (hashT &seed, const T(&t)[n])
Combine the hash values of a C-style array.
template<class T >
std::enable_if< std::is_fundamental< T >::value >::type hash_range (hashT &seed, const T *t, std::size_t n)
Combine the hash values of a pointer range.
template<class T >
std::enable_if<!std::is_fundamental< T >::value >::type hash_range (hashT &seed, const T *t, std::size_t n)
Combine the hash values of a pointer range.
template<class T >
hashT hash_range (const T *t, std::size_t n)
Combine the hash values of a pointer range.
template<typename T , std::size_t N>
madness::hashT hash_value (const std::array< T, N > &a)
Hash std::array with madness hash.
hashT hash_value (const uniqueidT &id)
Hash a uniqueidT.
template<class T >
std::enable_if< std::is_fundamental< T >::value &&((sizeof(T)%sizeof(uint32_t))==0), hashT >::type hash_value (const T t)
Hash a single fundamental object.
template<class T >
std::enable_if< std::is_fundamental< T >::value &&((sizeof(T)%sizeof(uint32_t)) !=0), hashT >::type hash_value (const T t)
Hash a single fundamental object.
template<typename T >
hashT hash_value (const T *t)
Hash a pointer address.
template<typename T >
std::enable_if<!(std::is_fundamental< T >::value||std::is_pointer< T >::value||std::is_array< T >::value), hashT >::type hash_value (const T &t)
Hash a class object.
template<typename T >
hashT hash_value (const std::basic_string< T > &t)
Hash a string.
double imag (double x)
template<typename Q , int NDIM>
Function< typename TensorTypeData< Q >::scalar_type, NDIM > imag (const Function< Q, NDIM > &func)
template<typename T , std::size_t NDIM>
std::vector< Function< typename Tensor< T >::scalar_type, NDIM > > imag (const std::vector< Function< T, NDIM > > &v, bool fence=true)
return the imaginary parts of the vector's function (if complex)
template<std::size_t NDIM>
Function< double, NDIM > imag (const Function< double_complex, NDIM > &z, bool fence=true)
Returns a new function that is the imaginary part of the input.
template<class T >
Tensor< typename Tensor< T >::scalar_type > imag (const Tensor< T > &t)
Return a new tensor holding the imaginary part of each element of t (complex types only)
void init_tensor_lapack ()
World/MRA initialization calls this before going multithreaded due to static data in dlamch.
World & initialize (int &argc, char **&argv, bool quiet=false)
Initialize the MADNESS runtime.
World & initialize (int &argc, char **&argv, const MPI_Comm &comm, bool quiet=false)
Initialize the MADNESS runtime.
World & initialize (int &argc, char **&argv, const SafeMPI::Intracomm &comm, bool quiet=false)
Initialize the MADNESS runtime.
void initialize_legendre_stuff ()
Call this single threaded to initialize static data (used read only by multiple threads)
void initialize_papi ()
bool initialized ()
Check if the MADNESS runtime has been initialized (and not subsequently finalized).
double inner (const std::valarray< double > &bra, const std::valarray< double > &ket)
inner product for std::valarray
template<typename T , std::size_t N>
T inner (const Vector< T, N > &l, const Vector< T, N > &r)
compute the inner product two Vectors.
template<typename T , typename R , std::size_t NDIM>
Tensor< TENSOR_RESULT_TYPE(T, R) > inner (World &world, const std::vector< Function< T, NDIM > > &f, const std::vector< Function< R, NDIM > > &g)
Computes the element-wise inner product of two function vectors - q(i) = inner(f[i],g[i])
template<typename T , typename R , std::size_t NDIM>
Tensor< TENSOR_RESULT_TYPE(T, R) > inner (World &world, const Function< T, NDIM > &f, const std::vector< Function< R, NDIM > > &g)
Computes the inner product of a function with a function vector - q(i) = inner(f,g[i])
template<class T , class Q >
Tensor< TENSOR_RESULT_TYPE(T, Q)> inner (const Tensor< T > &left, const Tensor< Q > &right, long k0=-1, long k1=0)
Inner product ... result(i,j,...,p,q,...) = sum(z) left(i,j,...,z)*right(z,p,q,...)
return f inner (g)
return f inner_adaptive (func)
template<class T , class Q >
void inner_result (const Tensor< T > &left, const Tensor< Q > &right, long k0, long k1, Tensor< TENSOR_RESULT_TYPE(T, Q) > &result)
Accumulate inner product into user provided, contiguous, correctly sized result tensor.
template<typename T >
DistributedMatrix< T > interleave_rows (const DistributedMatrix< T > &a, const DistributedMatrix< T > &b)
Generates a distributed matrix with rows of a and b interleaved.
template<typename T >
Tensor< T > inverse (const Tensor< T > &a_in)
invert general square matrix A
template Tensor< double > inverse (const Tensor< double > &A)
template<typename T >
Tensor< T > KAIN (const Tensor< T > &Q, double rcond=1e-12)
Solves non-linear equation using KAIN (returns coefficients to compute next vector)
void legendre_polynomials (double x, long order, double *p)
Evaluate the Legendre polynomials up to the given order at x in [-1,1].
void legendre_scaling_functions (double x, long k, double *p)
Evaluate the first k Legendre scaling functions.
template<class T , std::size_t NDIM>
void load (Function< T, NDIM > &f, const std::string name)
void load_coeffs (World &world, const char *dir)
Collective routine to load and cache twoscale & autorrelation coefficients.
template<typename T , size_t NDIM>
void load_function (World &world, std::vector< Function< T, NDIM > > &f, const std::string name)
load a vector of functions
void load_quadrature (World &world, const char *dir)
Collective routine to pre-load and cache the quadrature points and weights.
static xc_func_type * lookup_func (const std::string &name, bool polarized)
static std::string lookup_id (const int id)
static int lookup_name (const std::string &name)
std::string lowercase (const std::string &s)
template<typename T >
void lq (Tensor< T > &A, Tensor< T > &R)
compute the LQ decomposition of the matrix A = L Q
template void lq (Tensor< double > &A, Tensor< double > &L)
template<typename T >
void lq_result (Tensor< T > &A, Tensor< T > &R, Tensor< T > &tau, Tensor< T > &work, bool do_qr)
compute the LQ decomposition of the matrix A = L Q
template void lq_result (Tensor< double > &A, Tensor< double > &R, Tensor< double > &tau, Tensor< double > &work, bool do_qr)
std::vector< atom_information< 3 > > make_atom_vec (const Molecule &molecule, double R1_, double R2_)
std::vector< atom_information< 3 > > make_atom_vec (const std::string &input)
static Function< double_complex, 3 > make_exp (double t, const Function< double, 3 > &v)
static xc_func_type * make_func (int id, bool polarized)
template<typename T , std::size_t NDIM>
Function< T, NDIM > map_and_mirror (const Function< T, NDIM > &f, const std::vector< long > &map, const std::vector< long > &mirror, bool fence=true)
This is replaced with mirror(map(f)), optional fence.
template<typename T , std::size_t NDIM>
Function< T, NDIM > mapdim (const Function< T, NDIM > &f, const std::vector< long > &map, bool fence=true)
Generate a new function by reordering dimensions ... optional fence.
double mask1 (double x)
static double mask3 (const coordT &ruser)
static void mask_info (integer &info)
template<typename T , std::size_t NDIM>
void matrix_inner (DistributedMatrix< T > &A, const std::vector< Function< T, NDIM > > &f, const std::vector< Function< T, NDIM > > &g, bool sym=false)
template<typename T , std::size_t NDIM>
DistributedMatrix< T > matrix_inner (const DistributedMatrixDistribution &d, const std::vector< Function< T, NDIM > > &f, const std::vector< Function< T, NDIM > > &g, bool sym=false)
template<typename T , typename R , std::size_t NDIM>
Tensor< TENSOR_RESULT_TYPE(T, R) > matrix_inner (World &world, const std::vector< Function< T, NDIM > > &f, const std::vector< Function< R, NDIM > > &g, bool sym=false)
Computes the matrix inner product of two function vectors - q(i,j) = inner(f[i],g[j])
template<typename T , typename R , std::size_t NDIM>
Tensor< TENSOR_RESULT_TYPE(T, R) > matrix_inner_old (World &world, const std::vector< Function< T, NDIM > > &f, const std::vector< Function< R, NDIM > > &g, bool sym=false)
Computes the matrix inner product of two function vectors - q(i,j) = inner(f[i],g[j])
template<typename T , std::size_t NDIM>
Function< T, NDIM > mirror (const Function< T, NDIM > &f, const std::vector< long > &mirrormap, bool fence=true)
Generate a new function by mirroring within the dimensions .. optional fence.
template<typename T , typename Q , typename S >
static void mTxm (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
template<>
void mTxm (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT c, const double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
Matrix transpose * matrix (hand unrolled version)
template<typename T , typename Q , typename S >
static void mTxm_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
Matrix += Matrix transpose * matrix ... reference implementation (slow but correct)
template<typename aT , typename bT , typename cT >
void mTxmq (long dimi, long dimj, long dimk, cT *MADNESS_RESTRICT c, const aT *a, const bT *b, long ldb=-1)
template<typename aT , typename bT , typename cT >
void mTxmq_padding (long dimi, long dimj, long dimk, long ext_b, cT *c, const aT *a, const bT *b)
template<typename aT , typename bT , typename cT >
void mTxmq_reference (long dimi, long dimj, long dimk, cT *MADNESS_RESTRICT c, const aT *a, const bT *b, long ldb=-1)
Matrix = Matrix transpose * matrix ... slow reference implementation.
template<typename T , typename Q , typename S >
static void mTxmT (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
template<>
void mTxmT (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT csave, const double *MADNESS_RESTRICT asave, const double *MADNESS_RESTRICT b)
Matrix transpose * matrix transpose (hand tiled and unrolled)
template<typename T , typename Q , typename S >
static void mTxmT_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
Matrix += Matrix transpose * matrix transpose reference implementation (slow but correct)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > mul (World &world, const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &v, const unsigned int blk=1, const bool fence=true)
Multiplies a function against a vector of functions — q[i] = a * v[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > mul (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true, unsigned int blk=1)
Multiplies two vectors of functions q[i] = a[i] * b[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > mul (World &world, const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &v, bool fence=true)
Multiplies a function against a vector of functions — q[i] = a * v[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > mul (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true)
Multiplies two vectors of functions q[i] = a[i] * b[i].
template<typename Q , typename T , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(Q, T), NDIM > mul (const Q alpha, const Function< T, NDIM > &f, bool fence=true)
Returns new function equal to alpha*f(x) with optional fence.
template<typename Q , typename T , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(Q, T), NDIM > mul (const Function< T, NDIM > &f, const Q alpha, bool fence=true)
Returns new function equal to f(x)*alpha with optional fence.
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > mul (const Function< L, NDIM > &left, const Function< R, NDIM > &right, bool fence=true)
Same as operator* but with optional fence and no automatic reconstruction.
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > mul_sparse (World &world, const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &v, const double tol, const bool fence=true, const unsigned int blk=1)
Multiplies a function against a vector of functions using sparsity of a and v[i] — q[i] = a * v[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > mul_sparse (World &world, const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &v, double tol, bool fence=true)
Multiplies a function against a vector of functions using sparsity of a and v[i] — q[i] = a * v[i].
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > mul_sparse (const Function< L, NDIM > &left, const Function< R, NDIM > &right, double tol, bool fence=true)
Sparse multiplication — left and right must be reconstructed and if tol!=0 have tree of norms already created.
template<typename T , typename opT , std::size_t NDIM>
std::vector< Function< T, NDIM > > multi_to_multi_op_values (const opT &op, const std::vector< Function< T, NDIM > > &vin, const bool fence=true)
apply op on the input vector yielding an output vector of functions
template<typename T , typename opT , std::size_t NDIM>
Function< T, NDIM > multiop_values (const opT &op, const std::vector< Function< T, NDIM > > &vf)
template<typename T , std::size_t NDIM, std::size_t LDIM>
Function< T, NDIM > multiply (const Function< T, NDIM > f, const Function< T, LDIM > g, const int particle, const bool fence=true)
multiply a high-dimensional function with a low-dimensional function
template<typename T , typename Q , typename S >
static void mxm (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
template<>
void mxm (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT c, const double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
Matrix * matrix (hand unrolled version)
template<typename T , typename Q , typename S >
static void mxm_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
Matrix += Matrix * matrix reference implementation (slow but correct)
template<typename T , typename Q , typename S >
static void mxmT (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
template<>
void mxmT (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT c, const double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
Matrix * matrix transpose (hand unrolled version)
template<typename T , typename Q , typename S >
static void mxmT_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b)
Matrix += Matrix * matrix transpose ... reference implementation (slow but correct)
STATIC Tensor< float > my_conj_transpose (Tensor< float > a)
STATIC Tensor< double > my_conj_transpose (Tensor< double > a)
STATIC Tensor< float_complex > my_conj_transpose (Tensor< float_complex > a)
STATIC Tensor< double_complex > my_conj_transpose (Tensor< double_complex > a)
static void myusleep (unsigned int us)
Sleep or spin for specified number of microseconds.
template<typename... argT>
AmArg * new_am_arg (const argT &... args)
Convenience template for serializing arguments into a new AmArg.
template<typename T , std::size_t NDIM>
void nonstandard (World &world, std::vector< Function< T, NDIM > > &v, unsigned int blk=1, bool fence=true)
Generates non-standard form of a vector of functions.
template<typename T , std::size_t NDIM>
void nonstandard (World &world, std::vector< Function< T, NDIM > > &v, bool fence=true)
Generates non-standard form of a vector of functions.
template<typename T , std::size_t NDIM>
double norm2 (World &world, const std::vector< Function< T, NDIM > > &v)
Computes the 2-norm of a vector of functions.
template<typename T , std::size_t NDIM>
std::vector< double > norm2s (World &world, const std::vector< Function< T, NDIM > > &v, const unsigned int blk=1, const bool fence=true)
Computes the 2-norms of a vector of functions.
template<typename T , std::size_t NDIM>
std::vector< double > norm2s (World &world, const std::vector< Function< T, NDIM > > &v)
Computes the 2-norms of a vector of functions.
template<typename T , std::size_t NDIM>
void norm_tree (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true, unsigned int blk=1)
Makes the norm tree for all functions in a vector.
template<typename T , std::size_t NDIM>
void norm_tree (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Makes the norm tree for all functions in a vector.
template<typename T , std::size_t NDIM>
void normalize (World &world, std::vector< Function< T, NDIM > > &v, bool fence=true)
Normalizes a vector of functions — v[i] = v[i].scale(1.0/v[i].norm2())
bool operator!= (const DistributedID &left, const DistributedID &right)
Distributed ID inequality comparison operator.
template<typename T , std::size_t N, typename U >
Vector< T, N > operator* (Vector< T, N > l, U r)
Scale a Vector.
template<typename T , typename U , std::size_t N>
Vector< T, N > operator* (T l, Vector< U, N > r)
Scale a Vector.
template<typename T , std::size_t N, typename U >
Vector< T, N > operator* (Vector< T, N > l, const Vector< U, N > &r)
Multiply (element-wise) two Vectors.
template<typename T , typename Q >
IsSupported< TensorTypeData< Q >, LowRankTensor< T > >::type operator* (const Q &x, const LowRankTensor< T > &t)
The class defines tensor op scalar ... here define scalar op tensor.
template<typename T , typename Q >
IsSupported< TensorTypeData< Q >, GenTensor< T > >::type operator* (const Q &x, const GenTensor< T > &t)
The class defines tensor op scalar ... here define scalar op tensor.
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > operator* (const R fac, const std::vector< Function< T, NDIM > > &rhs)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator* (const std::vector< Function< T, NDIM > > &rhs, const R fac)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > operator* (const Function< T, NDIM > &a, const std::vector< Function< R, NDIM > > &v)
multiply a vector of functions with a function: r[i] = v[i] * a
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > operator* (const std::vector< Function< T, NDIM > > &v, const Function< R, NDIM > &a)
multiply a vector of functions with a function: r[i] = a * v[i]
template<typename Q , typename T , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(Q, T), NDIM > operator* (const Function< T, NDIM > &f, const Q alpha)
Returns new function equal to f(x)*alpha.
template<typename Q , typename T , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(Q, T), NDIM > operator* (const Q alpha, const Function< T, NDIM > &f)
Returns new function equal to alpha*f(x)
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > operator* (const Function< L, NDIM > &left, const Function< R, NDIM > &right)
Multiplies two functions with the new result being of type TensorResultType<L,R>
template<typename T , typename Q >
IsSupported< TensorTypeData< Q >, Tensor< T > >::type operator* (const Q &x, const Tensor< T > &t)
The class defines tensor op scalar ... here define scalar op tensor.
template<typename T , std::size_t N, typename U >
Vector< T, N > operator+ (Vector< T, N > l, U r)
Add a scalar to a Vector.
template<typename T , std::size_t N, typename U >
Vector< T, N > operator+ (Vector< T, N > l, const Vector< U, N > &r)
Add (element-wise) two Vectors.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator+ (const std::vector< Function< T, NDIM > > &lhs, const std::vector< Function< T, NDIM >> &rhs)
result[i] = a[i] + b[i]
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator+ (const std::vector< Function< T, NDIM > > &lhs, const Function< T, NDIM > &rhs)
result[i] = a[i] + b
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator+ (const Function< T, NDIM > &lhs, const std::vector< Function< T, NDIM > > &rhs)
result[i] = a + b[i]
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > operator+ (const Function< L, NDIM > &left, const Function< R, NDIM > &right)
Adds two functions with the new result being of type TensorResultType<L,R>
template<typename T , typename Q >
IsSupported< TensorTypeData< Q >, Tensor< T > >::type operator+ (Q x, const Tensor< T > &t)
The class defines tensor op scalar ... here define scalar op tensor.
template<typename T , typename R , std::size_t NDIM>
IsSupported< TensorTypeData< R >, Function< TENSOR_RESULT_TYPE(T, R), NDIM > >::type operator+ (const Function< T, NDIM > &f, R r)
template<typename T , typename R , std::size_t NDIM>
IsSupported< TensorTypeData< R >, Function< TENSOR_RESULT_TYPE(T, R), NDIM > >::type operator+ (R r, const Function< T, NDIM > &f)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator+= (std::vector< Function< T, NDIM > > &rhs, const std::vector< Function< T, NDIM > > &lhs)
template<typename T , std::size_t N, typename U >
Vector< T, N > operator- (Vector< T, N > l, U r)
Subtract a scalar from a Vector.
template<typename T , std::size_t N, typename U >
Vector< T, N > operator- (Vector< T, N > l, const Vector< U, N > &r)
Subtract (element-wise) two Vectors.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator- (const std::vector< Function< T, NDIM > > &lhs, const std::vector< Function< T, NDIM > > &rhs)
result[i] = a[i] - b[i]
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator- (const std::vector< Function< T, NDIM > > &lhs, const Function< T, NDIM > &rhs)
result[i] = a[i] - b
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator- (const Function< T, NDIM > &lhs, const std::vector< Function< T, NDIM > > &rhs)
result[i] = a - b[i]
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > operator- (const Function< L, NDIM > &left, const Function< R, NDIM > &right)
Subtracts two functions with the new result being of type TensorResultType<L,R>
template<typename T , typename Q >
IsSupported< TensorTypeData< Q >, Tensor< T > >::type operator- (Q x, const Tensor< T > &t)
The class defines tensor op scalar ... here define scalar op tensor.
template<typename T , typename R , std::size_t NDIM>
IsSupported< TensorTypeData< R >, Function< TENSOR_RESULT_TYPE(T, R), NDIM > >::type operator- (const Function< T, NDIM > &f, R r)
template<typename T , typename R , std::size_t NDIM>
IsSupported< TensorTypeData< R >, Function< TENSOR_RESULT_TYPE(T, R), NDIM > >::type operator- (R r, const Function< T, NDIM > &f)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > operator-= (std::vector< Function< T, NDIM > > &rhs, const std::vector< Function< T, NDIM > > &lhs)
std::ostream & operator<< (std::ostream &os, const PairType &en)
std::ostream & operator<< (std::ostream &os, const EnergyType &en)
std::ostream & operator<< (std::ostream &s, const ContractedGaussianShell &c)
std::ostream & operator<< (std::ostream &out, const MadnessException &e)
Enables easy printing of a MadnessException.
template<>
std::ostream & operator<< (std::ostream &out, const Future< void > &f)
Stream output operator for a void future.
std::ostream & operator<< (std::ostream &s, const AtomicBasis &c)
std::ostream & operator<< (std::ostream &os, const GuessType &en)
template<typename T , std::size_t N>
std::ostream & operator<< (std::ostream &s, const std::array< T, N > &a)
Output std::array to stream for human consumption.
template<typename T >
std::ostream & operator<< (std::ostream &s, const std::complex< T > &c)
Easy printing of complex numbers.
std::ostream & operator<< (std::ostream &s, const AtomicBasisFunction &a)
std::ostream & operator<< (std::ostream &s, const Atom &atom)
template<typename T , typename U >
std::ostream & operator<< (std::ostream &s, const std::pair< T, U > &p)
Easy printing of pairs.
template<typename T >
std::ostream & operator<< (std::ostream &s, const std::list< T > &c)
Easy printing of lists.
template<typename T >
std::ostream & operator<< (std::ostream &s, const std::vector< T > &c)
Easy printing of vectors.
std::ostream & operator<< (std::ostream &stream, const Slice &s)
template<typename T , std::size_t N>
std::enable_if<!std::is_same< T, char >::value, std::ostream & >::type operator<< (std::ostream &s, const T(&v)[N])
Easy printing of fixed dimension arrays.
template<std::size_t NDIM>
static std::ostream & operator<< (std::ostream &s, const BoundaryConditions< NDIM > &bc)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Future< T > &f)
Human readable printing of a Future to a stream.
static std::ostream & operator<< (std::ostream &s, const TensorType &tt)
template<std::size_t NDIM>
std::ostream & operator<< (std::ostream &s, const Key< NDIM > &key)
template<typename T , std::size_t NDIM>
std::ostream & operator<< (std::ostream &s, const FunctionNode< T, NDIM > &node)
template<typename T , std::size_t NDIM>
std::ostream & operator<< (std::ostream &s, const CoeffTracker< T, NDIM > &ct)
template<typename T >
static std::ostream & operator<< (std::ostream &s, const SRConf< T > &sr)
template<class T >
std::ostream & operator<< (std::ostream &s, const Tensor< T > &t)
Print (for human consumption) a tensor to the stream.
bool operator== (const DistributedID &left, const DistributedID &right)
Distributed ID equality comparison operator.
std::istream & operator>> (std::istream &is, PairType &en)
template<typename T , typename A = std::allocator<T>>
std::istream & operator>> (std::istream &is, std::vector< T, A > &v)
std::istream & operator>> (std::istream &is, EnergyType &en)
std::istream & operator>> (std::istream &is, GuessType &en)
template<typename Q , typename T >
std::istream & operator>> (std::istream &is, std::pair< T, Q > &p)
template<typename T >
void orgqr (Tensor< T > &A, const Tensor< T > &tau)
reconstruct the orthogonal matrix Q (e.g. from QR factorization)
template void orgqr (Tensor< float > &A, const Tensor< float > &tau)
template void orgqr (Tensor< double > &A, const Tensor< double > &tau)
template void orgqr (Tensor< complex_real4 > &A, const Tensor< complex_real4 > &tau)
template void orgqr (Tensor< double_complex > &A, const Tensor< double_complex > &tau)
template<typename T >
void ortho3 (Tensor< T > &x, Tensor< T > &y, Tensor< double > &weights, const double &thresh)
sophisticated version of ortho2
template<typename T >
void ortho5 (Tensor< T > &x1, Tensor< T > &y1, Tensor< double > &w1, const Tensor< T > &x2, const Tensor< T > &y2, const Tensor< double > &w2, const double &thresh)
specialized version of ortho3
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_canonical (const std::vector< Function< T, NDIM > > &v, const Tensor< T > &ovlp, double lindep)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_canonical (const std::vector< Function< T, NDIM > > &v, const double lindep)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_cd (const std::vector< Function< T, NDIM > > &v, Tensor< T > &ovlp)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_cd (const std::vector< Function< T, NDIM > > &v)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_rrcd (const std::vector< Function< T, NDIM > > &v, Tensor< T > &ovlp, const double tol, Tensor< integer > &piv, int &rank)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_rrcd (const std::vector< Function< T, NDIM > > &v, Tensor< T > ovlp, const double tol)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_rrcd (const std::vector< Function< T, NDIM > > &v, const double tol)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_symmetric (const std::vector< Function< T, NDIM > > &v, const Tensor< T > &ovlp)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > orthonormalize_symmetric (const std::vector< Function< T, NDIM > > &v)
template<class T >
GenTensor< T > outer (const GenTensor< T > &left, const GenTensor< T > &right, const TensorArgs final_tensor_args)
Outer product ... result(i,j,...,p,q,...) = left(i,k,...)*right(p,q,...)
template<class T >
GenTensor< T > outer (const Tensor< T > &left, const Tensor< T > &right, const TensorArgs final_tensor_args)
Outer product ... result(i,j,...,p,q,...) = left(i,k,...)*right(p,q,...)
template<class T , class Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q)> outer (const LowRankTensor< T > &t1, const LowRankTensor< Q > &t2, const TensorArgs final_tensor_args)
outer product of two Tensors, yielding a low rank tensor
template<class T , class Q >
TensorTrain< TENSOR_RESULT_TYPE(T, Q)> outer (const TensorTrain< T > &t1, const TensorTrain< Q > &t2)
computes the outer product of two tensors
template<class T >
Tensor< T > outer (const Tensor< T > &left, const Tensor< T > &right)
Outer product ... result(i,j,...,p,q,...) = left(i,k,...)*right(p,q,...)
static int parity (int i)
Return +1 if i is even, -1 if i is odd ... perverse no if-test form.
template<typename T , std::size_t NDIM>
Derivative< T, NDIM > periodic_derivative (World &world, int axis, int k=FunctionDefaults< NDIM >::get_k())
Conveinence function returning derivative operator with periodic boundary conditions.
template<typename Q , int NDIM>
SeparatedConvolution< Q, NDIM > PeriodicBSHOp (World &world, double mu, long k, double lo, double eps, Tensor< double > L)
static SeparatedConvolution< double_complex, 3 > PeriodicBSHOperator3D (World &world, Vector< double, 3 > args, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
static SeparatedConvolution< double_complex, 3 > * PeriodicBSHOperatorPtr3D (World &world, Vector< double, 3 > args, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
template<typename Q , int NDIM>
SeparatedConvolution< Q, NDIM > * PeriodicBSHOpPtr (World &world, double mu, long k, double lo, double eps, Tensor< double > L)
template<typename Q , int NDIM>
SeparatedConvolution< Q, NDIM > PeriodicCoulombOp (World &world, long k, double lo, double eps, Tensor< double > L)
template<typename Q , int NDIM>
SeparatedConvolution< Q, NDIM > * PeriodicCoulombOpPtr (World &world, long k, double lo, double eps, Tensor< double > L)
static SeparatedConvolution< double_complex, 3 > PeriodicHFExchangeOperator (World &world, Vector< double, 3 > args, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with 1/r in 3D.
static pg_operator pg_c2 ()
static pg_operator pg_c2x ()
static pg_operator pg_c2y ()
static pg_operator pg_c2z ()
static pg_operator pg_c4 ()
static pg_operator pg_c4x ()
static pg_operator pg_c4y ()
static pg_operator pg_c4z ()
static pg_operator pg_identity ()
static pg_operator pg_inversion ()
static pg_operator pg_sigma_x ()
static pg_operator pg_sigma_xy ()
static pg_operator pg_sigma_xz ()
static pg_operator pg_sigma_y ()
static pg_operator pg_sigma_yz ()
static double phase (long i)
template<size_t NDIM>
void plot (const std::vector< Function< double, NDIM > > &vf, const std::string &name, const std::vector< std::string > &header)
convenience to get plot_plane and plot_cubefile
template<size_t NDIM>
void plot_along (World &world, trajectory< NDIM > traj, const Function< double, NDIM > &function, std::string filename)
template<size_t NDIM>
void plot_along (World &world, trajectory< NDIM > traj, double(*ff)(const Vector< double, NDIM > &), std::string filename)
template<size_t NDIM>
std::enable_if< NDIM==3, void >::type plot_cubefile (World &world, const Function< double, NDIM > &f, std::string filename, std::vector< std::string > molecular_info=std::vector< std::string >())
template<typename opT , std::size_t NDIM>
void plot_line (World &world, const char *filename, int npt, const Vector< double, NDIM > &lo, const Vector< double, NDIM > &hi, const opT &op)
Generates ASCII file tabulating f(r) at npoints along line r=lo,...,hi.
template<typename T , std::size_t NDIM>
void plot_line (const char *filename, int npt, const Vector< double, NDIM > &lo, const Vector< double, NDIM > &hi, const Function< T, NDIM > &f)
Generates ASCII file tabulating f(r) at npoints along line r=lo,...,hi.
template<typename T , typename U , std::size_t NDIM>
void plot_line (const char *filename, int npt, const Vector< double, NDIM > &lo, const Vector< double, NDIM > &hi, const Function< T, NDIM > &f, const Function< U, NDIM > &g)
Generates ASCII file tabulating f(r) and g(r) at npoints along line r=lo,...,hi.
template<typename T , typename U , typename V , std::size_t NDIM>
void plot_line (const char *filename, int npt, const Vector< double, NDIM > &lo, const Vector< double, NDIM > &hi, const Function< T, NDIM > &f, const Function< U, NDIM > &g, const Function< V, NDIM > &a)
Generates ASCII file tabulating f(r), g(r), and a(r) at npoints along line r=lo,...,hi.
template<typename T , typename U , typename V , typename W , std::size_t NDIM>
void plot_line (const char *filename, int npt, const Vector< double, NDIM > &lo, const Vector< double, NDIM > &hi, const Function< T, NDIM > &f, const Function< U, NDIM > &g, const Function< V, NDIM > &a, const Function< W, NDIM > &b)
Generates ASCII file tabulating f(r), g(r), a(r), b(r) at npoints along line r=lo,...,hi.
static void plot_line_print_value (FILE *f, double_complex v)
static void plot_line_print_value (FILE *f, double v)
template<size_t NDIM>
void plot_plane (World &world, const Function< double, NDIM > &function, const std::string name)
template<size_t NDIM>
void plot_plane (World &world, const Function< double, NDIM > &function1, const Function< double, NDIM > &function2, const std::string name)
template<size_t NDIM>
void plot_plane (World &world, const Function< double, NDIM > &function1, const Function< double, NDIM > &function2, const Function< double, NDIM > &function3, const std::string name)
template<size_t NDIM>
void plot_plane (World &world, const std::vector< Function< double, NDIM > > &vfunction, const std::string name)
template<size_t NDIM, typename opT >
void plot_plane (World &world, const opT &op, const std::string name)
template<typename T , std::size_t NDIM>
void plotdx (const Function< T, NDIM > &f, const char *filename, const Tensor< double > &cell=FunctionDefaults< NDIM >::get_cell(), const std::vector< long > &npt=std::vector< long >(NDIM, 201L), bool binary=true)
Writes an OpenDX format file with a cube/slice of points on a uniform grid.
template<typename T >
static void plotpovray (const Function< T, 3 > &function, const char *filename, const Tensor< double > &cell=FunctionDefaults< 3 >::get_cell(), const std::vector< long > &npt=std::vector< long >(3, 201L))
Writes a Povray DF3 format file with a cube of points on a uniform grid.
template<std::size_t NDIM>
void plotvtk_begin (World &world, const char *filename, const Vector< double, NDIM > &plotlo, const Vector< double, NDIM > &plothi, const Vector< long, NDIM > &npt, bool binary=false)
template<typename T , std::size_t NDIM>
void plotvtk_data (const T &function, const char *fieldname, World &world, const char *filename, const Vector< double, NDIM > &plotlo, const Vector< double, NDIM > &plothi, const Vector< long, NDIM > &npt, bool binary=false)
template<typename T , std::size_t NDIM>
void plotvtk_data (const Function< T, NDIM > &function, const char *fieldname, World &world, const char *filename, const Vector< double, NDIM > &plotlo, const Vector< double, NDIM > &plothi, const Vector< long, NDIM > &npt, bool binary=false, bool plot_refine=false)
VTK data writer for real-valued (not complex) madness::functions.
template<typename T , std::size_t NDIM>
void plotvtk_data (const Function< std::complex< T >, NDIM > &function, const char *fieldname, World &world, const char *filename, const Vector< double, NDIM > &plotlo, const Vector< double, NDIM > &plothi, const Vector< long, NDIM > &npt, bool binary=false, bool plot_refine=false)
VTK data writer for complex-valued madness::functions.
template<std::size_t NDIM>
void plotvtk_end (World &world, const char *filename, bool binary=false)
static double PM_q (const tensorT &S, const double *MADNESS_RESTRICT Ci, const double *MADNESS_RESTRICT Cj, int lo, int nbf)
static double pop (std::vector< double > &v)
std::istream & position_stream (std::istream &f, const std::string &tag)
template<int D>
int power (int base=2)
template<int N, class T >
T power (T const x)
template<>
int power< 0 > (int base)
template<>
int power< 1 > (int base)
template<>
int power< 10 > (int base)
template<>
int power< 12 > (int base)
template<>
int power< 2 > (int base)
template<>
int power< 3 > (int base)
template<>
int power< 4 > (int base)
template<>
int power< 5 > (int base)
template<>
int power< 6 > (int base)
template<>
int power< 7 > (int base)
template<>
int power< 8 > (int base)
template<>
int power< 9 > (int base)
template<typename T , typename... Ts>
void print (const T &t, const Ts &... ts)
Print items to std::cout (items separated by spaces) and terminate with a new line.
void print_centered (const char *s, int column=40, bool underline=true)
Print a string centered at the given column with optional underlining.
template<typename T , typename... Ts>
void print_error (const T &t, const Ts &... ts)
Print items to std::cerr (items separated by spaces) and terminate with a new line.
std::ostream & print_helper (std::ostream &out)
Helper function for print. Base case.
template<typename T , typename... Ts>
std::ostream & print_helper (std::ostream &out, const T &t, const Ts &... ts)
Helper function for print. Prints the first item (t) and recursively passes on the other items.
void print_justified (const char *s, int column=0, bool underline=true)
Print a string justified on the left to start at the given column with optional underlining.
template<typename A , typename B , typename C , typename D >
void print_seq (World &world, const A &a, const B &b, const C &c, const D &d)
Sequentially ordered printing of (serializable) data from every process.
template<typename A , typename B , typename C >
void print_seq (World &world, const A &a, const B &b, const C &c)
Sequentially ordered printing of (serializable) data from every process.
template<typename A , typename B >
void print_seq (World &world, const A &a, const B &b)
Sequentially ordered printing of (serializable) data from every process.
template<typename A >
void print_seq (World &world, const A &a)
Sequentially ordered printing of (serializable) data from every process.
template<typename T , std::size_t NDIM>
void print_size (World &world, const std::vector< Function< T, NDIM > > &v, const std::string &msg="vectorfunction")
void print_stats (World &world)
Print miscellaneous stats on a World.
template<typename T , std::size_t NDIM>
Function< T, NDIM > project (const Function< T, NDIM > &other, int k=FunctionDefaults< NDIM >::get_k(), double thresh=FunctionDefaults< NDIM >::get_thresh(), bool fence=true)
tensorT Q2 (const tensorT &s)
Given overlap matrix, return rotation with 2nd order error to orthonormalize the vectors.
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
Convolution1D< double_complex > * qm_1d_free_particle_propagator (int k, double bandlimit, double timestep, double width)
template<std::size_t NDIM>
SeparatedConvolution< double_complex, NDIM > qm_free_particle_propagator (World &world, int k, double bandlimit, double timestep)
template<std::size_t NDIM>
SeparatedConvolution< double_complex, NDIM > * qm_free_particle_propagatorPtr (World &world, int k, double bandlimit, double timestep)
template<typename T >
void qr (Tensor< T > &A, Tensor< T > &R)
compute the QR decomposition of the matrix A
template void qr (Tensor< double > &A, Tensor< double > &R)
bool quiet ()
Check if the MADNESS runtime was initialized for quiet operation.
template<class T >
T RandomValue ()
Random value that wraps the default Fibonacci generator.
template<>
double RandomValue< double > ()
Random double.
template<>
double_complex RandomValue< double_complex > ()
Random double_complex.
template<>
float RandomValue< float > ()
Random float.
template<>
float_complex RandomValue< float_complex > ()
Random float_complex.
template<>
int RandomValue< int > ()
Random int.
template<>
long RandomValue< long > ()
Random long.
template<class T >
void RandomVector (int n, T *t)
template<>
void RandomVector< double > (int n, double *t)
template<>
void RandomVector< double_complex > (int n, double_complex *t)
template<>
void RandomVector< float > (int n, float *t)
template<>
void RandomVector< float_complex > (int n, float_complex *t)
template<typename T >
long rank_revealing_decompose (Tensor< T > &A, Tensor< T > &U, const double thresh, Tensor< typename Tensor< T >::scalar_type > &s, Tensor< T > &scr)
static AtomCore read_atom (TiXmlElement *e, unsigned int atn, double eprec)
static bool read_data ()
read_data loads the precomputed Gauss-Legendre data
static bool read_data (int k)
static bool read_orbital (TiXmlElement *e, AtomCore &ac)
static bool read_potential (TiXmlElement *elem, AtomCore &ac, double eprec)
static bool read_twoscale (int kmax)
static Tensor< double > readmat (int k, FILE *file)
double real (double x)
template<typename Q , int NDIM>
Function< typename TensorTypeData< Q >::scalar_type, NDIM > real (const Function< Q, NDIM > &func)
template<typename T , std::size_t NDIM>
std::vector< Function< typename Tensor< T >::scalar_type, NDIM > > real (const std::vector< Function< T, NDIM > > &v, bool fence=true)
return the real parts of the vector's function (if complex)
template<std::size_t NDIM>
Function< double, NDIM > real (const Function< double_complex, NDIM > &z, bool fence=true)
Returns a new function that is the real part of the input.
template<std::size_t NDIM>
Function< double, NDIM > real (const Function< double, NDIM > &z, bool fence=true)
Returns a new function that is the real part of the input.
template<class T >
Tensor< typename Tensor< T >::scalar_type > real (const Tensor< T > &t)
Return a new tensor holding the real part of each element of t (complex types only)
template<typename T , std::size_t NDIM>
void reconstruct (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Reconstruct a vector of functions.
template<typename T , std::size_t NDIM>
void reconstruct (World &world, const std::vector< Function< T, NDIM > > &v, unsigned int blk=1, bool fence=true)
Reconstruct a vector of functions.
void redirectio (const World &world, bool split=false)
redirects standard output and error to rank-specific files
template<class T >
GenTensor< T > reduce (std::list< GenTensor< T > > &addends, double eps, bool are_optimal=false)
template<typename T >
LowRankTensor< T > reduce (std::list< LowRankTensor< T > > &addends, double eps, bool are_optimal=false)
add all the GenTensors of a given list
template<typename T , std::size_t NDIM>
void refine (World &world, const std::vector< Function< T, NDIM > > &vf, bool fence=true)
refine the functions according to the autorefine criteria
template<typename T , std::size_t NDIM>
void refine_to_common_level (World &world, std::vector< Function< T, NDIM > > &vf, bool fence=true)
refine all functions to a common (finest) level
void reset_papi_measurement ()
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > rot (const std::vector< Function< T, NDIM > > &v, bool do_refine=false, bool fence=true)
shorthand rot operator
template<typename T >
DistributedMatrix< T > row_distributed_matrix (World &world, int64_t n, int64_t m, int64_t rowtile=0)
Generates an (n,m) matrix distributed by rows (column dimension is not distributed)
static DistributedMatrixDistribution row_distributed_matrix_distribution (World &world, int64_t n, int64_t m, int64_t rowtile)
Generates an (n,m) matrix distribution distributed by rows (column dimension is not distributed)
template<typename T >
void rr_cholesky (Tensor< T > &A, typename Tensor< T >::scalar_type tol, Tensor< integer > &piv, int &rank)
Compute the rank-revealing Cholesky factorization.
template void rr_cholesky (Tensor< double > &A, typename Tensor< double >::scalar_type tol, Tensor< integer > &piv, int &rank)
template void rr_cholesky (Tensor< double_complex > &A, typename Tensor< double_complex >::scalar_type tol, Tensor< integer > &piv, int &rank)
static double rsquared (const coordT &r)
template<class T , std::size_t NDIM>
void save (const Function< T, NDIM > &f, const std::string name)
template<typename T , size_t NDIM>
void save_function (const std::vector< Function< T, NDIM > > &f, const std::string name)
save a vector of functions
template<typename T , typename Q , std::size_t NDIM>
void scale (World &world, std::vector< Function< T, NDIM > > &v, const std::vector< Q > &factors, const unsigned int blk=1, const bool fence=true)
Scales inplace a vector of functions by distinct values.
template<typename T , typename Q , std::size_t NDIM>
void scale (World &world, std::vector< Function< T, NDIM > > &v, const Q factor, const unsigned int blk=1, const bool fence=true)
Scales inplace a vector of functions by the same.
template<typename T , typename Q , std::size_t NDIM>
void scale (World &world, std::vector< Function< T, NDIM > > &v, const std::vector< Q > &factors, bool fence=true)
Scales inplace a vector of functions by distinct values.
template<typename T , typename Q , std::size_t NDIM>
void scale (World &world, std::vector< Function< T, NDIM > > &v, const Q factor, bool fence=true)
Scales inplace a vector of functions by the same.
template<typename Archive >
void serialize_am_args (Archive &&)
Terminate argument serialization.
template<typename Archive , typename T , typename... argT>
void serialize_am_args (Archive &&archive, T &&t, argT &&... args)
Argument serialization.
template<typename T , std::size_t NDIM>
void set_thresh (World &world, std::vector< Function< T, NDIM > > &v, double thresh, bool fence=true)
Sets the threshold in a vector of functions.
template<std::size_t NDIM>
static void sim_to_user (const Vector< double, NDIM > &xsim, Vector< double, NDIM > &xuser)
Convert simulation coords ([0,1]^ndim) to user coords (FunctionDefaults<NDIM>::get_cell())
template<typename T , std::size_t NDIM>
static Key< NDIM > simpt2key (const Vector< T, NDIM > &pt, Level n)
double size_of (const intermediateT &im)
Returns the size of an intermediate.
double slater_radius (int atomic_number)
static SeparatedConvolution< double, 3 > SlaterF12Operator (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with (1 - exp(-mu*r))/(2 mu) in 3D.
static SeparatedConvolution< double, 3 > * SlaterF12OperatorPtr (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
Factory function generating separated kernel for convolution with (1 - exp(-mu*r))/(2 mu) in 3D.
static SeparatedConvolution< double, 3 > SlaterOperator (World &world, double mu, double lo, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
double smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
double smoothed_potential (double r)
Smoothed 1/r potential.
double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
template<std::size_t NDIM>
static SeparatedConvolution< double, NDIM > SmoothingOperator (World &world, double eps, const BoundaryConditions< NDIM > &bc=FunctionDefaults< NDIM >::get_bc(), int k=FunctionDefaults< NDIM >::get_k())
static SeparatedConvolution< double, 3 > SmoothingOperator3D (World &world, double eps, const BoundaryConditions< 3 > &bc=FunctionDefaults< 3 >::get_bc(), int k=FunctionDefaults< 3 >::get_k())
SPEC (int, long, long)
SPEC (int, float, float)
SPEC (int, double, double)
SPEC (int, float_complex, float_complex)
SPEC (int, double_complex, double_complex)
SPEC (long, float, float)
SPEC (long, double, double)
SPEC (long, float_complex, float_complex)
SPEC (long, double_complex, double_complex)
SPEC (float, double, double)
SPEC (float, float_complex, float_complex)
SPEC (float, double_complex, double_complex)
SPEC (double, float_complex, float_complex)
SPEC (double, double_complex, double_complex)
SPEC (float_complex, double_complex, double_complex)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > square (World &world, const std::vector< Function< T, NDIM > > &v, bool fence=true)
Computes the square of a vector of functions — q[i] = v[i]**2.
template<typename T , std::size_t NDIM>
Function< T, NDIM > square (const Function< T, NDIM > &f, bool fence=true)
Create a new function that is the square of f - global comm only if not reconstructed.
template<typename T , std::size_t NDIM>
void standard (World &world, std::vector< Function< T, NDIM > > &v, unsigned int blk=1, bool fence=true)
Generates standard form of a vector of functions.
template<typename T , std::size_t NDIM>
void standard (World &world, std::vector< Function< T, NDIM > > &v, bool fence=true)
Generates standard form of a vector of functions.
static void START_TIMER (World &world)
void startup (World &world, int argc, char **argv, bool doprint=false)
template<typename T >
T stheta_fd (const T &x)
template<typename T >
static std::string stringify (T arg)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > sub (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true, unsigned int blk=1)
Returns new vector of functions — q[i] = a[i] - b[i].
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > sub (World &world, const std::vector< Function< T, NDIM > > &a, const std::vector< Function< R, NDIM > > &b, bool fence=true)
Returns new vector of functions — q[i] = a[i] - b[i].
template<typename L , typename R , std::size_t NDIM>
Function< TENSOR_RESULT_TYPE(L, R), NDIM > sub (const Function< L, NDIM > &left, const Function< R, NDIM > &right, bool fence=true)
Same as operator- but with optional fence and no automatic compression.
template<typename T , std::size_t NDIM>
Function< T, NDIM > sum (World &world, const std::vector< Function< T, NDIM > > &f, bool fence=true)
Returns new function — q = sum_i f[i].
template<typename T >
void svd (const Tensor< T > &a, Tensor< T > &U, Tensor< typename Tensor< T >::scalar_type > &s, Tensor< T > &VT)
Compute the singluar value decomposition of an n-by-m matrix using *gesvd.
template void svd (const Tensor< double > &a, Tensor< double > &U, Tensor< Tensor< double >::scalar_type > &s, Tensor< double > &VT)
template void svd (const Tensor< double_complex > &a, Tensor< double_complex > &U, Tensor< Tensor< double_complex >::scalar_type > &s, Tensor< double_complex > &VT)
template<typename T >
void svd_result (Tensor< T > &a, Tensor< T > &U, Tensor< typename Tensor< T >::scalar_type > &s, Tensor< T > &VT, Tensor< T > &work)
same as svd, but it optimizes away the tensor construction: a = U * diag(s) * VT
template void svd_result (Tensor< float > &a, Tensor< float > &U, Tensor< Tensor< float >::scalar_type > &s, Tensor< float > &VT, Tensor< float > &work)
template void svd_result (Tensor< double > &a, Tensor< double > &U, Tensor< Tensor< double >::scalar_type > &s, Tensor< double > &VT, Tensor< double > &work)
template void svd_result (Tensor< float_complex > &a, Tensor< float_complex > &U, Tensor< Tensor< float_complex >::scalar_type > &s, Tensor< float_complex > &VT, Tensor< float_complex > &work)
template void svd_result (Tensor< double_complex > &a, Tensor< double_complex > &U, Tensor< Tensor< double_complex >::scalar_type > &s, Tensor< double_complex > &VT, Tensor< double_complex > &work)
template<typename keyT , typename valueT , typename hashfunT >
void swap (WorldContainer< keyT, valueT, hashfunT > &dc0, WorldContainer< keyT, valueT, hashfunT > &dc1)
Swaps the content of two WorldContainer objects. It should be called on all nodes.
template<typename T , std::size_t N>
void swap (Vector< T, N > &l, Vector< T, N > &r)
Swap the contents of two Vectors.
template<typename T , typename U >
void swap (RemoteReference< T > &l, RemoteReference< U > &r)
Swap the two remote references.
template<typename T >
Function< T, 6 > swap_particles (const Function< T, 6 > &f)
swap particles 1 and 2
template<typename T >
void syev (const Tensor< T > &A, Tensor< T > &V, Tensor< typename Tensor< T >::scalar_type > &e)
Real-symmetric or complex-Hermitian eigenproblem.
template void syev (const Tensor< double > &A, Tensor< double > &V, Tensor< Tensor< double >::scalar_type > &e)
template void syev (const Tensor< double_complex > &A, Tensor< double_complex > &V, Tensor< Tensor< double_complex >::scalar_type > &e)
template<typename T >
void sygv (const Tensor< T > &A, const Tensor< T > &B, int itype, Tensor< T > &V, Tensor< typename Tensor< T >::scalar_type > &e)
Generalized real-symmetric or complex-Hermitian eigenproblem.
template void sygv (const Tensor< double > &A, const Tensor< double > &B, int itype, Tensor< double > &V, Tensor< Tensor< double >::scalar_type > &e)
template void sygv (const Tensor< double_complex > &A, const Tensor< double_complex > &B, int itype, Tensor< double_complex > &V, Tensor< Tensor< double_complex >::scalar_type > &e)
template<typename T >
void sygvp (World &world, const Tensor< T > &a, const Tensor< T > &B, int itype, Tensor< T > &V, Tensor< typename Tensor< T >::scalar_type > &e)
unsigned int symbol_to_atomic_number (const std::string &symbol)
template<typename T , std::size_t NDIM>
Function< T, NDIM > symmetrize (const Function< T, NDIM > &f, const std::string symmetry, bool fence=true)
symmetrize a function
template<typename Q >
Tensor< Q > tensor_abs (const Tensor< std::complex< Q > > &c)
template<typename Q >
Tensor< std::complex< Q > > tensor_real2complex (const Tensor< Q > &r)
template<typename T , typename R , std::size_t NDIM>
TENSOR_RESULT_TYPE (T, R) inner(const Function< T
Computes the scalar/inner product between two functions.
template<typename T , typename opT , std::size_t NDIM>
TENSOR_RESULT_TYPE (T, typename opT::value_type) inner(const Function< T
Computes the scalar/inner product between an MRA function and an external functor.
template<typename T , typename opT , std::size_t NDIM>
TENSOR_RESULT_TYPE (T, typename opT::value_type) inner(const opT &g
Computes the scalar/inner product between an MRA function and an external functor.
template<typename Q >
Tensor< Q > tensor_ximag (const Tensor< std::complex< Q > > &c)
template<typename Q >
Tensor< Q > tensor_xreal (const Tensor< std::complex< Q > > &c)
bool test_autoc ()
template<typename T >
double test_cholesky (int n)
template<typename T >
double test_gelss (int n, int nrhs)
template<typename T >
double test_gesv (int n, int nrhs)
template<typename T >
double test_inverse (int n)
Example and test code for interface to LAPACK SVD interfae.
template<typename T >
double test_qr ()
bool test_rnlp ()
template<typename T >
double test_rr_cholesky (int n)
template<typename T >
double test_svd (int n, int m)
Example and test code for interface to LAPACK SVD interfae.
template<typename T >
double test_syev (int n)
template<typename T >
double test_sygv (int n)
bool test_tensor_lapack ()
Test the Tensor-LAPACK interface ... currently always returns true!
bool test_two_scale_coefficients ()
static double testf (int n, double x)
static void time_transform (World &world, int &mflopslo, int &mflopshi)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > transform (World &world, const std::vector< Function< T, NDIM > > &v, const Tensor< R > &c, unsigned int blki=1, unsigned int blkj=1, const bool fence=true)
Transforms a vector of functions according to new[i] = sum[j] old[j]*c[j,i].
template<typename L , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(L, R), NDIM > > transform (World &world, const std::vector< Function< L, NDIM > > &v, const Tensor< R > &c, const double tol, const unsigned int blki=1, const bool fence)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > transform (World &world, const std::vector< Function< T, NDIM > > &v, const Tensor< R > &c, bool fence=true)
Transforms a vector of functions according to new[i] = sum[j] old[j]*c[j,i].
template<typename L , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(L, R), NDIM > > transform (World &world, const std::vector< Function< L, NDIM > > &v, const Tensor< R > &c, double tol, bool fence)
template<typename T , typename R , std::size_t NDIM>
std::vector< Function< TENSOR_RESULT_TYPE(T, R), NDIM > > transform (World &world, const std::vector< Function< T, NDIM > > &v, const DistributedMatrix< R > &c, bool fence=true)
template<class T , class Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q) > transform (const LowRankTensor< Q > &t, const Tensor< T > &c)
template<class T , class Q >
TensorTrain< TENSOR_RESULT_TYPE(T, Q)> transform (const TensorTrain< T > &t, const Tensor< Q > &c)
transform each dimension with the same operator matrix
template<class T , class Q >
Tensor< TENSOR_RESULT_TYPE(T, Q)> transform (const Tensor< T > &t, const Tensor< Q > &c)
Transform all dimensions of the tensor t by the matrix c.
template<class T , class Q >
LowRankTensor< TENSOR_RESULT_TYPE(T, Q)> transform_dir (const LowRankTensor< Q > &t, const Tensor< T > &c, int axis)
Transforms one dimension of the tensor t by the matrix c, returns new contiguous tensor.
template<class T , class Q >
TensorTrain< TENSOR_RESULT_TYPE(T, Q)> transform_dir (const TensorTrain< T > &t, const Tensor< Q > &c, const int axis)
Transforms one dimension of the tensor t by the matrix c, returns new contiguous tensor.
template<class T , class Q >
Tensor< TENSOR_RESULT_TYPE(T, Q)> transform_dir (const Tensor< T > &t, const Tensor< Q > &c, int axis)
Transforms one dimension of the tensor t by the matrix c, returns new contiguous tensor.
template<class T >
Tensor< T > transpose (const Tensor< T > &t)
Returns a new deep copy of the transpose of the input tensor.
template<typename T , std::size_t NDIM>
void truncate (World &world, std::vector< Function< T, NDIM > > &v, double tol=0.0, unsigned int blk=1, bool fence=true)
Truncates a vector of functions.
template<typename T , std::size_t NDIM>
void truncate (World &world, std::vector< Function< T, NDIM > > &v, double tol=0.0, bool fence=true)
Truncates a vector of functions.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > truncate (std::vector< Function< T, NDIM > > v, double tol=0.0, bool fence=true)
Truncates a vector of functions.
bool try_two_locks (const Mutex &m1, const Mutex &m2)
Attempt to acquire two locks without blocking holding either one.
template<typename T >
TensorTrain< T > tt_identity (const long ndim, const long k)
compute the n-D identity operator with k elements per dimension
bool two_scale_coefficients (int k, Tensor< double > *h0, Tensor< double > *h1, Tensor< double > *g0, Tensor< double > *g1)
Return the two scale coefficients in the Legendre basis.
bool two_scale_hg (int k, Tensor< double > *hg)
std::string type (const PairType &n)
std::string type (const EnergyType &n)
std::string type (const GuessType &n)
TYPEINFO (0, int, false, true, int, double)
TYPEINFO (1, long, false, true, long, double)
TYPEINFO (2, float, false, true, float, float)
TYPEINFO (3, double, false, true, double, double)
TYPEINFO (4, float_complex, true, true, float, float)
TYPEINFO (5, double_complex, true, true, double, double)
template<typename Q , typename opT , std::size_t NDIM>
Function< typename opT::resultT, NDIM > unary_op (const Function< Q, NDIM > &func, const opT &op, bool fence=true)
Out of place application of unary operation to function values with optional fence.
template<typename Q , typename opT , std::size_t NDIM>
Function< typename opT::resultT, NDIM > unary_op_coeffs (const Function< Q, NDIM > &func, const opT &op, bool fence=true)
Out of place application of unary operation to scaling function coefficients with optional fence.
template<typename T , std::size_t N>
Vector< T, N > unitvec (const Vector< T, N > &r, const double eps=1.e-6)
Construct a unit-Vector that has the same direction as r.
template<std::size_t NDIM>
static void user_to_sim (const Vector< double, NDIM > &xuser, Vector< double, NDIM > &xsim)
Convert user coords (cell[][]) to simulation coords ([0,1]^ndim)
template<typename T , typename... Ts>
Vector< T, sizeof...(Ts)+1 > vec (T t, Ts... ts)
Factory function for creating a madness::Vector.
template<typename T >
std::vector< T > vector_factory (const T &v0)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1, const T &v2)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1, const T &v2, const T &v3)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1, const T &v2, const T &v3, const T &v4)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1, const T &v2, const T &v3, const T &v4, const T &v5)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1, const T &v2, const T &v3, const T &v4, const T &v5, const T &v6)
Returns a std::vector<T> initialized from the arguments.
template<typename T >
std::vector< T > vector_factory (const T &v0, const T &v1, const T &v2, const T &v3, const T &v4, const T &v5, const T &v6, const T &v7)
Returns a std::vector<T> initialized from the arguments.
template<typename T , std::size_t NDIM>
static void verify_tree (World &world, const std::vector< Function< T, NDIM > > &v)
template<typename L , typename R , std::size_t D>
std::vector< Function< TENSOR_RESULT_TYPE(L, R), D > > vmulXX (const Function< L, D > &left, const std::vector< Function< R, D > > &vright, double tol, bool fence=true)
Use the vmra/mul(...) interface instead.
double wall_time ()
Returns the wall time in seconds relative to an arbitrary origin.
WorldMemInfo * world_mem_info ()
Returns pointer to internal structure.
int x_rks_s__ (const double *r__, double *f, double *dfdra)
int x_uks_s__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
void xterm_debug (const char *path, const char *display)
void xterm_debug_breakpoint ()
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > zero_functions (World &world, int n)
Generates a vector of zero functions.
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > zero_functions (World &world, int n, bool fence=true)
Generates a vector of zero functions (reconstructed)
template<typename T , std::size_t NDIM>
std::vector< Function< T, NDIM > > zero_functions_compressed (World &world, int n, bool fence=true)
Generates a vector of zero functions (compressed)
print_meminfo
These functions are useful to instrument aggregate (not fine-grained, like WorldMemInfo) memory profiling.
Note
To make this functionality usable must set the ENABLE_MEM_PROFILE CMake cache variable to ON
void print_meminfo_disable ()
disables print_meminfo() profiling (i.e. calling it is a no-op)
void print_meminfo_enable ()
bool print_meminfo_enabled ()
template<typename String >
void print_meminfo (int rank, const String &tag, const std::string filename_prefix=std::string("MEMORY"))
print aggregate memory stats to file filename_prefix.<rank> , tagged with tag
Variables
static const std::vector< Slice > ___ = vector_factory(_,_,_,_,_,_)
Entire dimension.
static Tensor< double > _c
static Tensor< double > _cread
const double acut1e_6 = 0.25
static const AtomicData atomic_data [NUMBER_OF_ATOMS_IN_TABLE]
static const char * autocorr_filename = "autocorr"
const double c_b14 = 1.333333333333333333333333333333
const double c_b2 = 0.333333333333333333333333333333333
const double c_b7 = 0.333333333333333333333333333333
static class madness::twoscale_cache_class cache [kmax+1]
double cpufrequency
static bool data_is_read = false
static const long default_jdim = 5551212
Random default_random_generator
The default random number stream.
static const string dir = "coredata/"
static const Tag DYNAMIC_TAG_BASE = 1024
NDIM & f
static const char * filename = "gaussleg"
NDIM const Function< R, NDIM > & g
int hwthreads
template<typename T >
constexpr bool is_always_serializable
template<typename T >
constexpr bool is_iostreammable_v = is_istreammable_v<T> && is_ostreammable_v<T>
providing automatic support for serializing to/from std streams requires bidirectional streammability
template<typename T >
constexpr bool is_istreammable_v = is_istreammable<T>::value
template<typename T >
constexpr bool is_ostreammable_v = is_ostreammable<T>::value
static int kcur = -1
static const int kmax = 60
static const int kmax_autoc = 30
static int kread = -1
static bool loaded = 0
static const std::string mad_root_dir = MAD_ROOT_DIR
static const int max_npt = 64
static const int MAXK = 30
The maximum wavelet order presently supported.
static const int MAXLEVEL = 8*sizeof(Translation)-2
The maximum depth of refinement possible.
int64_t memorysize
static double nn1 [100]
static const unsigned int NUMBER_OF_ATOMS_IN_TABLE = 110
const int NUMEVENTS = 0
static double phi_norms [100]
static Tensor< double > points [max_npt+1]
static bool print_timings =false
static volatile bool rmi_task_is_running = false
static std::vector< double > sss
const char * tensor_type_names []
static AtomicInt threadcounter
static std::vector< double > ttt
static const char * twoscale_filename = "coeffs"
static Tensor< double > weights [max_npt+1]
Detailed Description
File holds all helper structures necessary for the CC_Operator and CC2 class.
Namespace for all elements and tools of MADNESS.
this block needs to be known before nonlinsol.h is included (happens when nemo is included) better move this to nonlinsol.h
We provide an abstract base class FunctionFunctorInterface, of which we derive (as of now) the following classes:
ElementaryInterface (formerly FunctorInterfaceWrapper) to wrap elementary functions
ElectronRepulsionInterface to provide 1/r12, which is not elementarily accessible
CompositeFunctionInterface to provide on-demand coefficients of pair functions
Each of these Interfaces can be used in a FunctionFactory to set up a Function
If you can recall the Intel hypercubes, their comm lib used GOP as the abbreviation.
Typedef Documentation
am_handlerT
typedef void(* madness::am_handlerT) (const AmArg &)
Type of AM handler functions.
complex_convolution_1d
typedef SeparatedConvolution<double_complex,1> madness::complex_convolution_1d
complex_convolution_1d_ptr
typedef std::shared_ptr<complex_convolution_1d> madness::complex_convolution_1d_ptr
complex_convolution_2d
typedef SeparatedConvolution<double_complex,2> madness::complex_convolution_2d
complex_convolution_2d_ptr
typedef std::shared_ptr<complex_convolution_2d> madness::complex_convolution_2d_ptr
complex_convolution_3d
typedef SeparatedConvolution<double_complex,3> madness::complex_convolution_3d
complex_convolution_3d_ptr
typedef std::shared_ptr<complex_convolution_3d> madness::complex_convolution_3d_ptr
complex_convolution_4d
typedef SeparatedConvolution<double_complex,4> madness::complex_convolution_4d
complex_convolution_4d_ptr
typedef std::shared_ptr<complex_convolution_4d> madness::complex_convolution_4d_ptr
complex_convolution_5d
typedef SeparatedConvolution<double_complex,5> madness::complex_convolution_5d
complex_convolution_5d_ptr
typedef std::shared_ptr<complex_convolution_5d> madness::complex_convolution_5d_ptr
complex_convolution_6d
typedef SeparatedConvolution<double_complex,6> madness::complex_convolution_6d
complex_convolution_6d_ptr
typedef std::shared_ptr<complex_convolution_6d> madness::complex_convolution_6d_ptr
complex_derivative_1d
typedef Derivative<double_complex,1> madness::complex_derivative_1d
complex_derivative_2d
typedef Derivative<double_complex,2> madness::complex_derivative_2d
complex_derivative_3d
typedef Derivative<double_complex,3> madness::complex_derivative_3d
complex_derivative_4d
typedef Derivative<double_complex,4> madness::complex_derivative_4d
complex_derivative_5d
typedef Derivative<double_complex,5> madness::complex_derivative_5d
complex_derivative_6d
typedef Derivative<double_complex,6> madness::complex_derivative_6d
complex_factory_1d
typedef FunctionFactory<double_complex,1> madness::complex_factory_1d
complex_factory_2d
typedef FunctionFactory<double_complex,2> madness::complex_factory_2d
complex_factory_3d
typedef FunctionFactory<double_complex,3> madness::complex_factory_3d
complex_factory_4d
typedef FunctionFactory<double_complex,4> madness::complex_factory_4d
complex_factory_5d
typedef FunctionFactory<double_complex,5> madness::complex_factory_5d
complex_factory_6d
typedef FunctionFactory<double_complex,6> madness::complex_factory_6d
complex_funcimpl_1d
typedef FunctionImpl<double_complex,1> madness::complex_funcimpl_1d
complex_funcimpl_2d
typedef FunctionImpl<double_complex,2> madness::complex_funcimpl_2d
complex_funcimpl_3d
typedef FunctionImpl<double_complex,3> madness::complex_funcimpl_3d
complex_funcimpl_4d
typedef FunctionImpl<double_complex,4> madness::complex_funcimpl_4d
complex_funcimpl_5d
typedef FunctionImpl<double_complex,5> madness::complex_funcimpl_5d
complex_funcimpl_6d
typedef FunctionImpl<double_complex,6> madness::complex_funcimpl_6d
complex_function_1d
typedef Function<double_complex,1> madness::complex_function_1d
complex_function_2d
typedef Function<double_complex,2> madness::complex_function_2d
complex_function_3d
typedef Function<double_complex,3> madness::complex_function_3d
complex_function_4d
typedef Function<double_complex,4> madness::complex_function_4d
complex_function_5d
typedef Function<double_complex,5> madness::complex_function_5d
complex_function_6d
typedef Function<double_complex,6> madness::complex_function_6d
complex_functionT
typedef Function<std::complex<double>,3> madness::complex_functionT
complex_functor_1d
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,1> > madness::complex_functor_1d
complex_functor_2d
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,2> > madness::complex_functor_2d
complex_functor_3d
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,3> > madness::complex_functor_3d
complex_functor_4d
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,4> > madness::complex_functor_4d
complex_functor_5d
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,5> > madness::complex_functor_5d
complex_functor_6d
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,6> > madness::complex_functor_6d
complex_operatorT
typedef Convolution1D<double_complex> madness::complex_operatorT
complex_tensor
typedef Tensor<double_complex> madness::complex_tensor
CONDITION_VARIABLE_TYPE
typedef PthreadConditionVariable madness::CONDITION_VARIABLE_TYPE
coord_1d
typedef Vector<double,1> madness::coord_1d
coord_2d
typedef Vector<double,2> madness::coord_2d
coord_3d
typedef Vector< double, 3 > madness::coord_3d
coord_4d
typedef Vector<double,4> madness::coord_4d
coord_5d
typedef Vector<double,5> madness::coord_5d
coord_6d
typedef Vector< double, 6 > madness::coord_6d
coordT
typedef Vector< double, 3 > madness::coordT
cvecfuncT
typedef std::vector<complex_functionT> madness::cvecfuncT
distmatT
typedef DistributedMatrix<double> madness::distmatT
DistributedID
typedef std::pair<uniqueidT, std::size_t> madness::DistributedID
Distributed ID which is used to identify objects.
factoryT
typedef FunctionFactory< double, 3 > madness::factoryT
function_defaults_1d
typedef FunctionDefaults<1> madness::function_defaults_1d
function_defaults_2d
typedef FunctionDefaults<2> madness::function_defaults_2d
function_defaults_3d
typedef FunctionDefaults<3> madness::function_defaults_3d
function_defaults_4d
typedef FunctionDefaults<4> madness::function_defaults_4d
function_defaults_5d
typedef FunctionDefaults<5> madness::function_defaults_5d
function_defaults_6d
typedef FunctionDefaults<6> madness::function_defaults_6d
functionT
typedef Function< double, 3 > madness::functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > madness::functorT
future_to_ref_t
template<typename T > using madness::future_to_ref_t = typedef typename future_to_ref< T >::type
hashT
typedef std::size_t madness::hashT
The hash value type.
intermediateT
typedef Pairs<real_function_3d> madness::intermediateT
f12 and g12 intermediates of the form <f1|op|f2> (with op=f12 or op=g12) will be saved using the pair structure
Level
typedef int madness::Level
NonlinearSolver
typedef NonlinearSolverND<3> madness::NonlinearSolver
operatorT
typedef SeparatedConvolution<double,3> madness::operatorT
pairvecfuncT
typedef std::pair<vecfuncT,vecfuncT> madness::pairvecfuncT
pmap_1d
typedef std::shared_ptr< WorldDCPmapInterface< Key<1> > > madness::pmap_1d
pmap_2d
typedef std::shared_ptr< WorldDCPmapInterface< Key<2> > > madness::pmap_2d
pmap_3d
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > madness::pmap_3d
pmap_4d
typedef std::shared_ptr< WorldDCPmapInterface< Key<4> > > madness::pmap_4d
pmap_5d
typedef std::shared_ptr< WorldDCPmapInterface< Key<5> > > madness::pmap_5d
pmap_6d
typedef std::shared_ptr< WorldDCPmapInterface< Key<6> > > madness::pmap_6d
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > madness::pmapT
poperatorT
typedef std::shared_ptr<operatorT> madness::poperatorT
real_convolution_1d
typedef SeparatedConvolution<double,1> madness::real_convolution_1d
real_convolution_1d_ptr
typedef std::shared_ptr<real_convolution_1d> madness::real_convolution_1d_ptr
real_convolution_2d
typedef SeparatedConvolution<double,2> madness::real_convolution_2d
real_convolution_2d_ptr
typedef std::shared_ptr<real_convolution_2d> madness::real_convolution_2d_ptr
real_convolution_3d
typedef SeparatedConvolution<double,3> madness::real_convolution_3d
real_convolution_3d_ptr
typedef std::shared_ptr<real_convolution_3d> madness::real_convolution_3d_ptr
real_convolution_4d
typedef SeparatedConvolution<double,4> madness::real_convolution_4d
real_convolution_4d_ptr
typedef std::shared_ptr<real_convolution_4d> madness::real_convolution_4d_ptr
real_convolution_5d
typedef SeparatedConvolution<double,5> madness::real_convolution_5d
real_convolution_5d_ptr
typedef std::shared_ptr<real_convolution_5d> madness::real_convolution_5d_ptr
real_convolution_6d
typedef SeparatedConvolution<double,6> madness::real_convolution_6d
real_convolution_6d_ptr
typedef std::shared_ptr<real_convolution_6d> madness::real_convolution_6d_ptr
real_derivative_1d
typedef Derivative<double,1> madness::real_derivative_1d
real_derivative_2d
typedef Derivative<double,2> madness::real_derivative_2d
real_derivative_3d
typedef Derivative<double,3> madness::real_derivative_3d
real_derivative_4d
typedef Derivative<double,4> madness::real_derivative_4d
real_derivative_5d
typedef Derivative<double,5> madness::real_derivative_5d
real_derivative_6d
typedef Derivative<double,6> madness::real_derivative_6d
real_factory_1d
typedef FunctionFactory<double,1> madness::real_factory_1d
real_factory_2d
typedef FunctionFactory<double,2> madness::real_factory_2d
real_factory_3d
typedef FunctionFactory<double,3> madness::real_factory_3d
real_factory_4d
typedef FunctionFactory<double,4> madness::real_factory_4d
real_factory_5d
typedef FunctionFactory<double,5> madness::real_factory_5d
real_factory_6d
typedef FunctionFactory<double,6> madness::real_factory_6d
real_funcimpl_1d
typedef FunctionImpl<double,1> madness::real_funcimpl_1d
real_funcimpl_2d
typedef FunctionImpl<double,2> madness::real_funcimpl_2d
real_funcimpl_3d
typedef FunctionImpl<double,3> madness::real_funcimpl_3d
real_funcimpl_4d
typedef FunctionImpl<double,4> madness::real_funcimpl_4d
real_funcimpl_5d
typedef FunctionImpl<double,5> madness::real_funcimpl_5d
real_funcimpl_6d
typedef FunctionImpl<double,6> madness::real_funcimpl_6d
real_function_1d
typedef Function<double,1> madness::real_function_1d
real_function_2d
typedef Function<double,2> madness::real_function_2d
real_function_3d
typedef Function<double,3> madness::real_function_3d
real_function_4d
typedef Function<double,4> madness::real_function_4d
real_function_5d
typedef Function<double,5> madness::real_function_5d
real_function_6d
typedef Function<double,6> madness::real_function_6d
real_functor_1d
typedef std::shared_ptr< FunctionFunctorInterface<double,1> > madness::real_functor_1d
real_functor_2d
typedef std::shared_ptr< FunctionFunctorInterface<double,2> > madness::real_functor_2d
real_functor_3d
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > madness::real_functor_3d
real_functor_4d
typedef std::shared_ptr< FunctionFunctorInterface<double,4> > madness::real_functor_4d
real_functor_5d
typedef std::shared_ptr< FunctionFunctorInterface<double,5> > madness::real_functor_5d
real_functor_6d
typedef std::shared_ptr< FunctionFunctorInterface<double,6> > madness::real_functor_6d
real_tensor
typedef Tensor<double> madness::real_tensor
remove_fcvr_t
template<typename T > using madness::remove_fcvr_t = typedef typename remove_fcvr<T>::type
remove_future_t
template<typename T > using madness::remove_future_t = typedef typename remove_future< T >::type
C++11 version of REMFUTURE.
rmi_handlerT
typedef void(* madness::rmi_handlerT) (void *buf, size_t nbyte)
This is the generic low-level interface for a message handler.
SCALABLE_MUTEX_TYPE
typedef Mutex madness::SCALABLE_MUTEX_TYPE
SPINLOCK_TYPE
typedef Mutex madness::SPINLOCK_TYPE
subspaceT
typedef std::vector<pairvecfuncT> madness::subspaceT
tensor_complex
typedef Tensor<double_complex> madness::tensor_complex
tensor_real
typedef Tensor<double> madness::tensor_real
tensorT
typedef Tensor< double > madness::tensorT
Translation
typedef int64_t madness::Translation
vecfuncT
typedef std::vector< real_function_3d > madness::vecfuncT
vector_complex
typedef std::vector< std::complex<double> > madness::vector_complex
vector_complex_function_1d
typedef std::vector<complex_function_1d> madness::vector_complex_function_1d
vector_complex_function_2d
typedef std::vector<complex_function_2d> madness::vector_complex_function_2d
vector_complex_function_3d
typedef std::vector<complex_function_3d> madness::vector_complex_function_3d
vector_complex_function_4d
typedef std::vector<complex_function_4d> madness::vector_complex_function_4d
vector_complex_function_5d
typedef std::vector<complex_function_5d> madness::vector_complex_function_5d
vector_complex_function_6d
typedef std::vector<complex_function_6d> madness::vector_complex_function_6d
vector_coord_1d
typedef std::vector< Vector<double,1> > madness::vector_coord_1d
vector_coord_2d
typedef std::vector< Vector<double,2> > madness::vector_coord_2d
vector_coord_3d
typedef std::vector< Vector<double,3> > madness::vector_coord_3d
vector_coord_4d
typedef std::vector< Vector<double,4> > madness::vector_coord_4d
vector_coord_5d
typedef std::vector< Vector<double,5> > madness::vector_coord_5d
vector_coord_6d
typedef std::vector< Vector<double,6> > madness::vector_coord_6d
vector_real
typedef std::vector<double> madness::vector_real
vector_real_function_1d
typedef std::vector<real_function_1d> madness::vector_real_function_1d
vector_real_function_2d
typedef std::vector<real_function_2d> madness::vector_real_function_2d
vector_real_function_3d
typedef std::vector<real_function_3d> madness::vector_real_function_3d
vector_real_function_4d
typedef std::vector<real_function_4d> madness::vector_real_function_4d
vector_real_function_5d
typedef std::vector<real_function_5d> madness::vector_real_function_5d
vector_real_function_6d
typedef std::vector<real_function_6d> madness::vector_real_function_6d
Enumeration Type Documentation
BCType
enum madness::BCType
Enumerator
BC_ZERO
BC_PERIODIC
BC_FREE
BC_DIRICHLET
BC_ZERONEUMANN
BC_NEUMANN
CalcType
enum madness::CalcType
Calculation Types used by CC2.
Enumerator
CT_UNDEFINED
CT_MP2
CT_CC2
CT_LRCCS
CT_LRCC2
CT_CISPD
CT_ADC2
CT_TDHF
CT_TEST
CCState
enum madness::CCState
Type of Pairs used by CC_Pair2 class.
Enumerator
CCSTATE_UNDEFINED
GROUND_STATE
EXCITED_STATE
EnergyType
enum madness::EnergyType
Enumerator
PROJECTED_ENERGYTYPE
HYLLERAAS_ENERGYTYPE
UNKNOWN_ENERGYTYPE
FuncType
enum madness::FuncType
Types of Functions used by CC_function class.
Enumerator
UNDEFINED
HOLE
PARTICLE
MIXED
RESPONSE
GuessType
enum madness::GuessType
Enumerator
PARTIAL_WAVE_GUESSTYPE
FROM_FILE_GUESSTYPE
PREDEFINED_GUESSTYPE
SCF_GUESSTYPE
EXOP_GUESSTYPE
EMPTY_GUESSTYPE
PSI4_GUESSTYPE
UNKNOWN_GUESSTYPE
OpType
enum madness::OpType
Operatortypes used by the CCConvolutionOperator Class.
Enumerator
OT_UNDEFINED
OT_G12
OT_F12
PairFormat
enum madness::PairFormat
FuncTypes used by the CC_function_6d structure.
Enumerator
PT_UNDEFINED
PT_FULL
PT_DECOMPOSED
PT_OP_DECOMPOSED
PairType
enum madness::PairType
Enumerator
MP2_PAIRTYPE
CISPD_PAIRTYPE
ALL_PAIRTYPE
NONE_PAIRTYPE
UNKNOWN_PAIRTYPE
PotentialType
enum madness::PotentialType
CC2 Singles Potentials.
Enumerator
POT_UNDEFINED
POT_F3D_
POT_s3a_
POT_s3b_
POT_s3c_
POT_s5a_
POT_s5b_
POT_s5c_
POT_s2b_
POT_s2c_
POT_s4a_
POT_s4b_
POT_s4c_
POT_s6_
POT_ccs_
POT_cis_
POT_singles_
TensorType
enum madness::TensorType
low rank representations of tensors (see gentensor.h)
Enumerator
TT_NONE
TT_FULL
TT_2D
TT_TENSORTRAIN
Function Documentation
_()
static const Slice madness::_ (0 , - 1, 1) static
Referenced by madness::FunctionCommonData< Q, NDIM >::_init_twoscale(), madness::SCF::analyze_vectors(), madness::SRConf< T >::append(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::projector_irrep::apply_symmetry_operators(), madness::Znemo::canonicalize(), concatenate_columns(), concatenate_rows(), madness::LowRankTensor< T >::convert(), madness::TensorTrain< T >::decompose(), diag_and_transform(), madness::SCF::dipole_matrix_elements(), madness::FunctionImpl< Q, NDIM >::dirac_convolution_op(), madness::FunctionImpl< Q, NDIM >::do_inner_localX(), madness::FunctionImpl< Q, NDIM >::do_project_out(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), doit(), MiniDFT::doit(), doplot(), doplotptk(), madness::TensorTrain< T >::emul(), madness::SRConf< T >::emul(), fixphases(), madness::TensorTrain< T >::gaxpy(), madness::SRConf< T >::get_configs(), madness::SCF::get_fock_transformation(), madness::Znemo::hcore_guess(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), interleave_rows(), madness::SCF::localize_boys(), madness::SCF::localize_new(), main(), madness::TDHF::make_cis_matrix(), madness::TwoElectronInterface< double, 6 >::make_coeff(), madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::Nemo::make_incomplete_hessian_response_part(), madness::SRConf< T >::make_slices(), madness::SeparatedConvolution< T, NDIM >::make_tt_representation(), madness::SRConf< T >::normalize(), madness::FunctionImpl< Q, NDIM >::NS_fcube_for_mul(), madness::FunctionImpl< Q, NDIM >::NScoeffs2values(), BoysLocalization::operator()(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), madness::SliceLowRankTensor< T >::operator+=(), madness::SliceLowRankTensor< T >::operator-=(), orth(), ortho3(), ortho5(), orthonormalize_canonical(), madness::PNO::pno_compress(), madness::FunctionImpl< Q, NDIM >::print_plane_local(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), rank_revealing_decompose(), madness::FunctionDefaults< NDIM >::recompute_cell_info(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_defaults(), solve(), madness::Nemo::solve_cphf(), madness::TensorTrain< T >::splitdim(), test_asymmetric(), test_syev(), test_sygv(), madness::TensorTrain< T >::truncate(), madness::SCF::update_response_subspace(), Subspace::update_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), madness::SCF::update_subspace(), and madness::FunctionImpl< Q, NDIM >::vtransform().
_reverse()
static const Slice madness::_reverse (- 1, 0 , - 1) static
Entire tensor.
abs() [1/4]
double madness::abs (double x)
Referenced by madness::Solver< T, NDIM >::apply_hf_exchange(), madness::BandlimitedPropagator::BandlimitedPropagator(), madness::OEP::compute_delta_rho(), madness::F12Potentials::compute_f12_correction(), madness::F12Potentials::compute_f12_pair_energies(), madness::F12Potentials::compute_f12_pair_energy(), ExcitingApp::findkpt(), ExcitingApp::generate_gvectors(), ExcitingApp::generate_lvectors(), QuasiNewton::hessian_update_bfgs(), QuasiNewton::hessian_update_sr1(), QuasiNewton::line_search(), main(), make_pw_matrix(), QuasiNewton::new_search_direction(), abs_square_op< Q, NDIM >::operator()(), madness::WorldAbsMaxOp< T >::operator()(), madness::WorldAbsMinOp< T >::operator()(), madness::abs_square_op< Q, NDIM >::operator()(), madness::abs_op< Q, NDIM >::operator()(), madness::detail::abssqop< NDIM >::operator()(), madness::detail::absop< NDIM >::operator()(), madness::detail::absinplace< T, NDIM >::operator()(), madness::detail::abssquareinplace< T, NDIM >::operator()(), ExcitingApp::response(), madness::Znemo::save_orbitals(), tensor_abs(), test_chin_chen(), OptimizationTargetInterface::test_gradient(), test_hermiticity(), test_kinetic(), test_rnlp(), test_trotter(), testPeriodicCoulomb3d(), Subspace::update_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), and madness::Subspace< T, NDIM >::update_subspace().
abs() [2/4]
template<typename Q , int NDIM> Function<typename TensorTypeData<Q>::scalar_type,NDIM> madness::abs (const Function< Q, NDIM > & func)
References func(), and unary_op_coeffs().
abs() [3/4]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::abs (const Function< T, NDIM > & f, bool fence = true)
Create a new function that is the abs of f - global comm only if not reconstructed.
References madness::Function< T, NDIM >::abs(), copy(), f, and PROFILE_FUNC.
abs() [4/4]
template<std::size_t NDIM> Function<double,NDIM> madness::abs (const Function< double_complex, NDIM > & z, bool fence = true)
Returns a new function that is the absolute value of the input.
References unary_op().
abs_square() [1/3]
template<typename Q , int NDIM> Function<typename TensorTypeData<Q>::scalar_type,NDIM> madness::abs_square (const Function< Q, NDIM > & func)
References func(), and unary_op().
Referenced by madness::Znemo::compute_current_density(), madness::Zcis::compute_potentials(), madness::Zcis::iterate(), test_coulomb(), and test_XCOperator().
abs_square() [2/3]
template<typename T , std::size_t NDIM> std::enable_if<!TensorTypeData<T>::iscomplex, Function<T,NDIM> >::type madness::abs_square (const Function< T, NDIM > & f, bool fence = true)
Create a new function that is the abs_square of f - global comm only if not reconstructed.
References madness::Function< T, NDIM >::abs_square(), copy(), f, and PROFILE_FUNC.
abs_square() [3/3]
template<typename T , std::size_t NDIM> std::enable_if<TensorTypeData<T>::iscomplex, Function<typename Tensor<T>::scalar_type,NDIM> >::type madness::abs_square (const Function< T, NDIM > & f, bool fence = true)
Create a new function that is the abs_square of f - global comm only if not reconstructed.
References f, and unary_op().
abssq() [1/2]
template<typename T , std::size_t NDIM> std::vector< Function<typename Tensor<T>::scalar_type,NDIM> > madness::abssq (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Computes the square of a vector of functions — q[i] = abs(v[i])**2.
References abssq(), madness::WorldGopInterface::fence(), madness::World::gop, and reconstruct().
abssq() [2/2]
template<std::size_t NDIM> Function<double,NDIM> madness::abssq (const Function< double_complex, NDIM > & z, bool fence = true)
Returns a new function that is the square of the absolute value of the input.
References unary_op().
Referenced by abssq(), madness::NemoBase::compute_density(), madness::Solver< T, NDIM >::compute_rho(), madness::Solver< T, NDIM >::compute_rho_slow(), madness::SCF::make_density(), and make_density().
add() [1/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::add (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true, unsigned int blk = 1)
Returns new vector of functions — q[i] = a[i] + b[i].
References a, add(), b, compress(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, and PROFILE_BLOCK.
add() [2/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::add (World & world, const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true, unsigned int blk = 1)
Returns new vector of functions — q[i] = a + b[i].
References a, add(), b, compress(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
add() [3/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::add (World & world, const std::vector< Function< R, NDIM > > & b, const Function< T, NDIM > & a, bool fence = true, unsigned int blk = 1) inline
References a, add(), and b.
add() [4/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::add (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true)
Returns new vector of functions — q[i] = a[i] + b[i].
References a, add(), b, compress(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, and PROFILE_BLOCK.
add() [5/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::add (World & world, const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true)
Returns new vector of functions — q[i] = a + b[i].
References a, add(), b, compress(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
add() [6/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::add (World & world, const std::vector< Function< R, NDIM > > & b, const Function< T, NDIM > & a, bool fence = true) inline
References a, add(), and b.
add() [7/7]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R),NDIM> madness::add (const Function< L, NDIM > & left, const Function< R, NDIM > & right, bool fence = true)
Same as operator+ but with optional fence and no automatic compression.
References gaxpy_oop(), L, R, and TENSOR_RESULT_TYPE().
Referenced by add(), madness::SCF::calc_rhs(), doit(), madness::TDHF::get_tda_potential(), operator+(), and operator+=().
adq()
template<typename funcT > funcT::returnT madness::adq (double lo, double hi, const funcT & func, double thresh)
References adq1(), func(), gauss_legendre(), lo, and thresh.
Referenced by madness::detail::adqtest::runtest().
adq1()
template<typename funcT > funcT::returnT madness::adq1 (double lo, double hi, const funcT & func, double thresh, int n, const double * x, const double * w, int level)
References d(), do_adq(), e(), func(), lo, madness::detail::norm(), and thresh.
Referenced by adq(), and madness::GenericConvolution1D< Q, opT >::rnlp().
aligned_add() [1/3]
void madness::aligned_add (long n, double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
Referenced by main().
aligned_add() [2/3]
void madness::aligned_add (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b)
aligned_add() [3/3]
template<typename T , typename Q > static void madness::aligned_add (long n, T *MADNESS_RESTRICT a, const Q *MADNESS_RESTRICT b) inline static
References a, and b.
aligned_axpy() [1/4]
template<typename T , typename Q > static void madness::aligned_axpy (long n, T *MADNESS_RESTRICT a, const T *MADNESS_RESTRICT b, Q s) inline static
References a, and b.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply_transformation(), and madness::SeparatedConvolution< T, NDIM >::apply_transformation2().
aligned_axpy() [2/4]
template<> void madness::aligned_axpy (long n, double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b, double s) inline
References a, madness::cblas::axpy(), and b.
aligned_axpy() [3/4]
template<> void madness::aligned_axpy (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b, double_complex s) inline
References a, madness::cblas::axpy(), and b.
aligned_axpy() [4/4]
template<> void madness::aligned_axpy (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b, double s) inline
References a, madness::cblas::axpy(), and b.
aligned_sub() [1/3]
void madness::aligned_sub (long n, double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b)
Referenced by main().
aligned_sub() [2/3]
void madness::aligned_sub (long n, double_complex *MADNESS_RESTRICT a, const double_complex *MADNESS_RESTRICT b)
aligned_sub() [3/3]
template<typename T , typename Q > static void madness::aligned_sub (long n, T *MADNESS_RESTRICT a, const Q *MADNESS_RESTRICT b) inline static
References a, and b.
aligned_zero()
template<typename T > static void madness::aligned_zero (long n, T * a) inline static
References a.
Referenced by madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::allocate().
alloc_am_arg()
AmArg* madness::alloc_am_arg (std::size_t nbyte) inline
Allocates a new AmArg with nbytes of user data ... delete with free_am_arg.
References arg().
Referenced by copy_am_arg(), and new_am_arg().
append() [1/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::append (const std::vector< Function< T, NDIM > > & lhs, const std::vector< Function< T, NDIM > > & rhs)
combine two vectors
Referenced by append(), madness::TDHF::apply_excitation_operators(), madness::F12Potentials::compute_cispd_f12_energies(), madness::Zcis::compute_residuals(), madness::PNOPairs::extract(), madness::PNO::grow_rank(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_internal(), madness::BasisFunctions::guess_with_exop(), madness::PNO::initialize_pairs(), madness::Zcis::iterate(), madness::Zcis::make_guess(), madness::F12Potentials::read_cabs_from_file(), madness::PNO::transform_pairs(), madness::PNO::truncate_pairs(), and madness::PNO::update_pno().
append() [2/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::append (const std::vector< std::vector< Function< T, NDIM > > > vv)
References append().
apply() [1/10]
template<typename T , std::size_t NDIM> std::vector< Function<T,NDIM> > madness::apply (World & world, const Derivative< T, NDIM > & D, const std::vector< Function< T, NDIM > > & v, const unsigned int blk = 1, const bool fence = true)
Applies a derivative operator to a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and reconstruct().
apply() [2/10]
template<typename T , std::size_t NDIM> std::vector< Function<T,NDIM> > madness::apply (World & world, const Derivative< T, NDIM > & D, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Applies a derivative operator to a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and reconstruct().
apply() [3/10]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::apply (const Derivative< T, NDIM > & D, const Function< T, NDIM > & f, bool fence = true)
Applies derivative operator to function (for syntactic equivalence to integral operator apply)
References f.
Referenced by KPeriodicBSHOperator::apply(), madness::TDHF::apply_G(), madness::Solver< T, NDIM >::apply_hf_exchange(), madness::Solver< T, NDIM >::apply_hf_exchange3(), madness::Solver< T, NDIM >::apply_hf_exchange4(), apply_periodic_bsh(), madness::Diamagnetic_potential_factor::apply_potential(), apply_potential(), madness::Solver< T, NDIM >::apply_potential(), madness::F12Potentials::apply_regularized_potential(), madness::SCF::calc_exchange_function(), madness::SCF::calc_response_function(), madness::SCF::calc_xc_function(), madness::HartreeFock< T, NDIM >::calculate_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_exchange_energy(), madness::DFT< T, NDIM >::calculate_tot_coulomb_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), chin_chen(), madness::Nemo::compute_all_cphf(), madness::PNO::compute_cispd_correction_es(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_f12_correction_es(), madness::PNO::compute_cispd_f12_correction_gs(), madness::F12Potentials::compute_cispd_f12_energies(), madness::Znemo::compute_energy(), madness::Nemo::compute_energy(), madness::Nemo::compute_energy_regularized(), madness::PNO::compute_fluctuation_matrix(), madness::F12Potentials::compute_fQc_integrals_ij(), madness::F12Potentials::compute_fQg_integral(), madness::F12Potentials::compute_fQg_integrals(), madness::F12Potentials::compute_fQU_integrals(), madness::OEP::compute_kinetic_energy(), madness::PNO::compute_projected_mp2_energies(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::SCF::compute_residual(), madness::Zcis::compute_residuals(), madness::Znemo::compute_residuals(), madness::PNO::compute_V_aj_i(), madness::PNO::compute_Vreg_aj_i_commutator_response(), madness::PNO::compute_Vreg_aj_i_fock_residue(), madness::F12Potentials::compute_xyab_integrals(), converge(), converge2s(), madness::F12Potentials::convolve_with_fg(), madness::F12Potentials::convolve_with_fU(), madness::F12Potentials::convolve_with_gradslater(), madness::F12Potentials::convolve_with_slater_potential(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), div(), madness::SCF::do_plots(), doit(), smooth< T, NDIM >::gaussian_smoothing(), grad(), grad_ble_one(), grad_ble_two(), grad_bpsline_two(), grad_bspline_one(), grad_bspline_three(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), iterate(), madness::SCF::iterate_trotter(), madness::Kinetic< double, 3 >::kinetic_energy_matrix(), kinetic_energy_matrix(), MiniDFT::kinetic_energy_matrix(), madness::SCF::kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), madness::Nemo::kinetic_energy_potential(), main(), madness::SCF::make_coulomb_potential(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), madness::Solver< T, NDIM >::make_nuclear_charge_density_impl(), madness::TDHF::make_perturbed_fock_matrix(), Calculation::make_reference(), madness::EigSolver< T, NDIM >::multi_solve(), NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp(), madness::HartreeFockExchangeOp< T, NDIM >::op_o(), madness::HartreeFockCoulombOp< T, NDIM >::op_r(), madness::DerivativeOperator< T, NDIM >::operator()(), madness::Nuclear::operator()(), madness::Lz::operator()(), madness::DNuclear::operator()(), madness::CCConvolutionOperator::operator()(), madness::SeparatedConvolution< T, NDIM >::operator()(), madness::TDHF::oscillator_strength_velocity(), madness::SCF::polarizability(), madness::DFTCoulombOp< T, NDIM >::prepare_op(), madness::DFTCoulombPeriodicOp< T, NDIM >::prepare_op(), rot(), madness::EigSolver< T, NDIM >::solve(), madness::Nemo::solve(), madness::SCF::solve(), madness::Solver< T, NDIM >::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), madness::Solver< T, NDIM >::Solver(), test(), smooth< T, NDIM >::test_1d(), test_he_potential(), test_hf_be(), test_hf_he(), test_nuclear_potential(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_op(), test_per(), test_periodic_bsh(), testbsh(), testNavierStokes(), testPeriodicCoulomb3d(), trotter(), madness::SCF::twoint(), MiniDFT::update(), and madness::PNO::update_pno().
apply() [4/10]
template<typename opT , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(typename opT::opT,R), NDIM> > madness::apply (World & world, const std::vector< std::shared_ptr< opT > > & op, const std::vector< Function< R, NDIM > > f, const unsigned int blk = 1)
Applies a vector of operators to a vector of functions — q[i] = apply(op[i],f[i])
References apply_only(), f, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, nonstandard(), op(), PROFILE_BLOCK, reconstruct(), madness::BaseTensor::size(), and standard().
apply() [5/10]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::apply (World & world, const SeparatedConvolution< T, NDIM > & op, const std::vector< Function< R, NDIM > > f, const unsigned int blk = 1)
Applies an operator to a vector of functions — q[i] = apply(op,f[i])
References apply_only(), f, madness::WorldGopInterface::fence(), madness::World::gop, nonstandard(), op(), PROFILE_BLOCK, reconstruct(), and standard().
apply() [6/10]
template<typename opT , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(typename opT::opT,R), NDIM> > madness::apply (World & world, const std::vector< std::shared_ptr< opT > > & op, const std::vector< Function< R, NDIM > > f)
Applies a vector of operators to a vector of functions — q[i] = apply(op[i],f[i])
References apply_only(), f, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, nonstandard(), op(), PROFILE_BLOCK, reconstruct(), madness::BaseTensor::size(), and standard().
apply() [7/10]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::apply (World & world, const SeparatedConvolution< T, NDIM > & op, const std::vector< Function< R, NDIM > > f)
Applies an operator to a vector of functions — q[i] = apply(op,f[i])
References apply_only(), f, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, MADNESS_EXCEPTION, nonstandard(), op(), PROFILE_BLOCK, R, reconstruct(), scale(), and standard().
apply() [8/10]
template<class T , class Q > TensorTrain<TENSOR_RESULT_TYPE(T,Q)> madness::apply (const TensorTrain< T > & op, const TensorTrain< Q > & t, const double thresh)
apply an operator in TT format on a tensor in TT format
Parameters
[in] op operator in TT format ..(r_1,k',k,r_2)..
[in] t tensor in TT format ..(r_1,k',r_2).. the result tensor will be .. (r_1,k,r_2) = ' ..(r_1,k',k,r_2).. ..(r_1,k',r_2).. during the apply a rank reduction will be performed 2*ndim allocates are needed
References B, copy(), madness::Tensor< T >::cycledim(), d(), madness::BaseTensor::dim(), madness::TensorTrain< T >::dim(), madness::TensorTrain< T >::dims(), madness::TensorTrain< T >::get_core(), inner_result(), k, k0, MADNESS_ASSERT, max, maxR, madness::BaseTensor::ndim(), madness::TensorTrain< T >::ndim(), op(), print(), R, R1, r2(), R2, rank_revealing_decompose(), madness::TensorTrain< T >::ranks(), madness::Tensor< T >::reshape(), TENSOR_RESULT_TYPE(), and thresh.
apply() [9/10]
template<typename opT , typename T , std::size_t LDIM> Function<TENSOR_RESULT_TYPE(typename opT::opT,T), LDIM+LDIM> madness::apply (const opT & op, const Function< T, LDIM > & f1, const Function< T, LDIM > & f2, bool fence = true)
Apply operator on a hartree product of two low-dimensional functions.
Supposed to be something like result= G(f(1)*f(2)) the hartree product is never constructed explicitly, but its coeffs are constructed on the fly and processed immediately.
Parameters
[in] op the operator
[in] f1 function of particle 1
[in] f2 function of particle 2
[in] fence if we shall fence
Returns
a function of dimension NDIM=LDIM+LDIM
References madness::FunctionFactory< T, NDIM >::empty(), f1, f2, madness::FunctionFactory< T, NDIM >::fence(), madness::Function< T, NDIM >::get_impl(), k, madness::Function< T, NDIM >::nonstandard(), op(), madness::Function< T, NDIM >::standard(), TENSOR_RESULT_TYPE(), and thresh.
apply() [10/10]
template<typename opT , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(typename opT::opT,R), NDIM> madness::apply (const opT & op, const Function< R, NDIM > & f, bool fence = true)
Apply operator in non-standard form.
Returns a new function with the same distribution
!!! For the moment does NOT respect fence option ... always fences
References apply_only(), madness::Function< T, NDIM >::clear(), f, madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::get_impl(), madness::World::gop, MADNESS_ASSERT, NDIM, madness::Function< T, NDIM >::nonstandard(), op(), madness::Function< T, NDIM >::print_size(), print_timings, R, madness::Function< T, NDIM >::reconstruct(), scale(), madness::Function< T, NDIM >::standard(), TENSOR_RESULT_TYPE(), VERIFY_TREE, madness::Function< T, NDIM >::verify_tree(), and madness::Function< T, NDIM >::world().
APPLY()
complex_functionT madness::APPLY (const complex_operatorT * q1d, const complex_functionT & psi)
References apply_1d_realspace_push(), madness::Function< T, NDIM >::broaden(), lo, psi(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::sum_down().
Referenced by applyexpLt(), chin_chen(), q_c(), sympgrad4(), sympgrad6(), and trotter().
apply_1d_realspace_push()
template<typename opT , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(typename opT::opT,R), NDIM> madness::apply_1d_realspace_push (const opT & op, const Function< R, NDIM > & f, int axis, bool fence = true)
References axis, f, madness::Function< T, NDIM >::get_impl(), op(), PROFILE_FUNC, madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::set_impl(), VERIFY_TREE, and madness::Function< T, NDIM >::verify_tree().
Referenced by APPLY(), madness::SCF::APPLY(), APPLY(), chin_chen(), test_apply_push_1d(), test_qm(), and trotter().
apply_c2()
static void madness::apply_c2 (double xaxis, double yaxis, double zaxis, double & x, double & y, double & z) static
Apply to (x,y,z) a C2 rotation about an axis thru the origin and (xaxis,yaxis,zaxis)
Referenced by madness::Molecule::test_for_c2().
apply_inverse()
static void madness::apply_inverse (double xjunk, double yjunk, double zjunk, double & x, double & y, double & z) static
Referenced by madness::Molecule::test_for_inverse().
apply_only()
template<typename opT , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(typename opT::opT,R), NDIM> madness::apply_only (const opT & op, const Function< R, NDIM > & f, bool fence = true)
Apply operator ONLY in non-standard form - required other steps missing !!
References f, madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::get_impl(), madness::World::gop, NDIM, op(), print(), print_timings, madness::World::rank(), madness::Function< T, NDIM >::set_impl(), and madness::Function< T, NDIM >::world().
Referenced by apply(), and test_coulomb().
apply_sigma()
static void madness::apply_sigma (double xaxis, double yaxis, double zaxis, double & x, double & y, double & z) static
Apply to (x,y,z) a reflection through a plane containing the origin with normal (xaxis,yaxis,zaxis)
Referenced by madness::Molecule::test_for_sigma().
assign_calctype()
CalcType madness::assign_calctype (const std::string name)
Assigns enum to string.
References CT_ADC2, CT_CC2, CT_CISPD, CT_LRCC2, CT_LRCCS, CT_MP2, CT_TDHF, CT_TEST, and MADNESS_EXCEPTION.
Referenced by madness::CCParameters::CCParameters().
assign_name() [1/6]
std::string madness::assign_name (const PairFormat & input)
Assigns strings to enums for formated output.
References MADNESS_EXCEPTION, PT_DECOMPOSED, PT_FULL, and PT_OP_DECOMPOSED.
Referenced by madness::CCConvolutionOperator::clear_intermediates(), madness::CCConvolutionOperator::error(), madness::CCParameters::information(), madness::CCConvolutionOperator::init_op(), madness::CC2::initialize_pairs(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), madness::CCIntermediatePotentials::insert(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), madness::CCConvolutionOperator::name(), madness::CCPair::name(), madness::CCConvolutionOperator::operator()(), madness::CCIntermediatePotentials::operator()(), madness::CCConvolutionOperator::print_intermediate(), madness::CC2::solve(), madness::CC2::update_constant_part_adc2(), and madness::CCConvolutionOperator::update_elements().
assign_name() [2/6]
std::string madness::assign_name (const CCState & input)
Assigns strings to enums for formated output.
References EXCITED_STATE, GROUND_STATE, and MADNESS_EXCEPTION.
assign_name() [3/6]
std::string madness::assign_name (const OpType & input)
Assigns strings to enums for formated output.
References MADNESS_EXCEPTION, OT_F12, and OT_G12.
assign_name() [4/6]
std::string madness::assign_name (const CalcType & inp)
Assigns strings to enums for formated output.
References CT_ADC2, CT_CC2, CT_CISPD, CT_LRCC2, CT_LRCCS, CT_MP2, CT_TDHF, CT_TEST, and MADNESS_EXCEPTION.
assign_name() [5/6]
std::string madness::assign_name (const PotentialType & inp)
Assigns strings to enums for formated output.
References MADNESS_EXCEPTION, POT_ccs_, POT_cis_, POT_F3D_, POT_s2b_, POT_s2c_, POT_s3a_, POT_s3b_, POT_s3c_, POT_s4a_, POT_s4b_, POT_s4c_, POT_s5a_, POT_s5b_, POT_s5c_, POT_s6_, and POT_singles_.
assign_name() [6/6]
std::string madness::assign_name (const FuncType & inp)
Assigns strings to enums for formated output.
References HOLE, MADNESS_EXCEPTION, MIXED, PARTICLE, RESPONSE, and UNDEFINED.
atomic_number_to_symbol()
std::string madness::atomic_number_to_symbol (const unsigned int atomic_number)
return the lower-case element symbol corresponding to the atomic number
References atomic_data, and madness::AtomicData::symbol_lowercase.
Referenced by madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_internal(), madness::BasisFunctions::predefined_guess(), madness::BasisFunctions::read_basis_from_file(), madness::F12Potentials::read_cabs_from_file(), and madness::BasisFunctions::read_contracted_basis_from_file().
autoc()
bool madness::autoc (int k, Tensor< double > * c)
Return the autocorrelation coefficients for scaling functions of given order.
Returned is a view of the cached data ... do not modify.
The autocorrelation functions are defined as
Phi_ij(z) = int(0,z+1) phi_i(x) phi_j(x-z)  z<=0
Phi_ij(z) = int(z,1) phi_i(x) phi_j(x-z)    z>=0
and are expanded in the double order Legendre scaling functions on either side of the origin
Phi_ij(z) = sum(p) [phi_p(z+1)*cminus_ijp + phi_p(z)*cplus_ijp]
cplus_ijp  = int(-1,0) Phi_ij(z) phi_p(z+1)
cminus_ijp = int(0,1)  Phi_ij(z) phi_p(z)
The expansion coefficients cminus and cplus have been precomputed with Maple to a precision of about 1e-30. Only cplus is stored and we use
cplus(i,j,p) = (-1)**(i+j+p) * cminus(i,j,p)
cplus(i,j,p) = (-1)**(i+j)   * cplus(j,i,p)
The returned tensor concatenates cminus and cplus.
Return true on success, false on failure (which also prints error message to stdout).
References _c, _cread, c, k, kcur, and kread.
Referenced by madness::Convolution1D< Q >::Convolution1D().
bandlimited_propagator_plot()
void madness::bandlimited_propagator_plot ()
References madness::BandlimitedPropagator::plot().
Referenced by main().
begin_papi_measurement()
void madness::begin_papi_measurement () inline
Referenced by initialize(), and madness::ThreadBase::main().
bgq_mtxmq_padded() [1/4]
void madness::bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, __complex__ double * c_x, const __complex__ double * a_x, const __complex__ double * b_x)
References a, b, c, k, and posix_memalign().
bgq_mtxmq_padded() [2/4]
void madness::bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, __complex__ double * c_x, const __complex__ double * a_x, const double * b_x)
References a, b, c, k, posix_memalign(), and xc.
bgq_mtxmq_padded() [3/4]
void madness::bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, __complex__ double * c_x, const double * a_x, const __complex__ double * b_x)
References a, b, c, k, and posix_memalign().
bgq_mtxmq_padded() [4/4]
void madness::bgq_mtxmq_padded (long dimi, long dimj, long dimk, long extb, double * c_x, const double * a_x, const double * b_x)
References a, b, c, k, and posix_memalign().
binary_op()
template<typename L , typename R , typename opT , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R),NDIM> madness::binary_op (const Function< L, NDIM > & left, const Function< R, NDIM > & right, const opT & op, bool fence = true)
Generate new function = op(left,right) where op acts on the function values.
References madness::Function< T, NDIM >::get_impl(), madness::Function< T, NDIM >::is_compressed(), op(), PROFILE_FUNC, madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::set_impl().
Referenced by madness::OEP::compute_average_I(), madness::OEP::compute_Pauli_kinetic_density(), madness::OEP::compute_slater_potential(), madness::OEP::compute_total_kinetic_density(), madness::Nemo::kinetic_energy_potential(), main(), and SurfaceMoleculeInteraction::make_surfcharge().
BSHOperator()
template<std::size_t NDIM> static SeparatedConvolution<double,NDIM> madness::BSHOperator (World & world, double mu, double lo, double eps, const BoundaryConditions< NDIM > & bc = FunctionDefaults<NDIM>::get_bc(), int k = FunctionDefaults<NDIM>::get_k()) inline static
Factory function generating separated kernel for convolution with BSH kernel in general NDIM.
References BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), e(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, MADNESS_EXCEPTION, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), print(), and madness::World::rank().
BSHOperator3D()
static SeparatedConvolution<double,3> madness::BSHOperator3D (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, and madness::Tensor< T >::normf().
Referenced by converge(), converge2s(), doit(), iterate(), iterate_excite(), iterate_ground(), iterate_xy(), main(), test_modified(), and test_periodic_bsh().
BSHOperatorPtr3D()
static SeparatedConvolution<double,3>* madness::BSHOperatorPtr3D (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, and madness::Tensor< T >::normf().
Referenced by madness::TDHF::apply_G(), madness::Zcis::compute_residuals(), madness::Znemo::compute_residuals(), madness::F12Potentials::F12Potentials(), madness::CC2::iterate_singles(), madness::PNO::make_bsh_operators(), MiniDFT::make_bsh_operators(), make_bsh_operators(), madness::SCF::make_bsh_operators(), madness::Solver< T, NDIM >::make_bsh_operators(), and madness::SCF::make_BSHOperatorPtr().
c_rks_vwn5__()
int madness::c_rks_vwn5__ (const double * r__, double * f, double * dfdra)
References a2, c_b7, f, and pow().
Referenced by madness::XCfunctional::exc(), ldaeop(), ldaop(), madness::xc_lda_potential::operator()(), and madness::XCfunctional::vxc().
c_uks_vwn5__()
int madness::c_uks_vwn5__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb)
References a1, a2, c_b14, c_b7, f, f1, f2, f3, pow(), ss1, and zeta.
Referenced by madness::XCfunctional::exc(), and madness::XCfunctional::vxc().
change_tensor_type()
template<typename T > void madness::change_tensor_type (GenTensor< T > & t, const TensorArgs & targs)
change representation to targ.tt
References MADNESS_ASSERT, madness::TensorArgs::tt, TT_2D, and TT_FULL.
Referenced by madness::FunctionImpl< Q, NDIM >::add_scalar_inplace(), madness::FunctionImpl< T, NDIM >::do_change_tensor_type::operator()(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), and madness::FunctionImpl< Q, NDIM >::unary_op_coeff_inplace().
check_for_inf() [1/2]
template<typename T > static std::enable_if<std::is_floating_point<T>::value, void>::type madness::check_for_inf (const std::string & str, T & arg) static
References arg().
Referenced by operator>>().
check_for_inf() [2/2]
template<typename T > static std::enable_if<!std::is_floating_point<T>::value, void>::type madness::check_for_inf (const std::string & str, T & arg) static
check_if_pseudo_atom()
bool madness::check_if_pseudo_atom (const std::string & symbol)
Referenced by madness::Molecule::read().
check_linear_dependence()
template<typename C > void madness::check_linear_dependence (const Tensor< C > & Q, Tensor< C > & c, const double rcondtol, const double cabsmax, bool do_print = true)
check for subspace linear dependency
Parameters
[in] Q the input matrix for KAIN
[in,out] c the coefficients for constructing the new solution
[in] rcondtol rcond less than this will cause the subspace to be shrunk due to linear dependence
[in] cabsmax maximum element of c greater than this will cause the subspace to be shrunk due to linear dependence
References c, e(), KAIN(), m, and print().
Referenced by madness::NonlinearSolverND< NDIM >::update(), and madness::XNonlinearSolver< T, C, Alloc >::update().
checksum_file()
unsigned long madness::checksum_file (const char * filename)
Simple checksum for ASCII characters in file.
References c, filename, sum(), and u().
Referenced by read_twoscale(), and test_autoc().
cholesky() [1/3]
template<typename T > void madness::cholesky (Tensor< T > & A)
Compute the Cholesky factorization.
Solves symmetric or Hermitian generalized eigenvalue problem.
Compute the Cholesky factorization of the symmetric positive definite matrix A
For memory efficiency A is modified inplace. Its upper triangle will hold the result and the lower trianlge will be zeroed such that input = inner(transpose(output),output).
Cholesky factorization
References mask_info(), potrf_(), and TENSOR_ASSERT.
Referenced by orthonormalize_cd(), and test_cholesky().
cholesky() [2/3]
template void madness::cholesky (Tensor< double > & A)
cholesky() [3/3]
template void madness::cholesky (Tensor< double_complex > & A)
column_distributed_matrix()
template<typename T > DistributedMatrix<T> madness::column_distributed_matrix (World & world, int64_t n, int64_t m, int64_t coltile = 0)
Generates an (n,m) matrix distributed by columns (row dimension is not distributed)
Quietly forces an even column tile size for ease of use in the systolic matrix algorithms
Parameters
[in] world The world
[in] n The column (first) dimension
[in] m The row (second) dimension
[in] coltile Tile size for columns forced to be even (default is to use all processes)
Returns
A new zero matrix with the requested dimensions and distribution
References column_distributed_matrix_distribution(), and m.
column_distributed_matrix_distribution()
static DistributedMatrixDistribution madness::column_distributed_matrix_distribution (World & world, int64_t n, int64_t m, int64_t coltile) inline static
Generates distribution for an (n,m) matrix distributed by columns (row dimension is not distributed)
Quietly forces an even column tile size for ease of use in the systolic matrix algorithms
Parameters
[in] world The world
[in] n The column (first) dimension
[in] m The row (second) dimension
[in] coltile Tile size for columns forced to be even (default is to use all processes)
Returns
An object encoding the dimension and distribution information
References m, and madness::World::size().
Referenced by column_distributed_matrix().
compress() [1/2]
template<typename T , std::size_t NDIM> void madness::compress (World & world, const std::vector< Function< T, NDIM > > & v, unsigned int blk = 1, bool fence = true)
Compress a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
compress() [2/2]
template<typename T , std::size_t NDIM> void madness::compress (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Compress a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Referenced by add(), madness::GTHPseudopotential< Q >::apply_potential(), madness::NemoBase::compute_gradient(), madness::Solver< T, NDIM >::compute_rho(), cross(), gaxpy(), gaxpy_oop(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), inner(), madness::Kinetic< double, 3 >::kinetic_energy_matrix(), kinetic_energy_matrix(), madness::SCF::kinetic_energy_matrix(), madness::Nemo::make_density(), MiniDFT::make_density(), madness::SCF::make_density(), madness::FunctionImpl< Q, NDIM >::make_redundant(), Calculation::make_reference(), matrix_inner(), matrix_inner_old(), orthogonalize(), MiniDFT::orthogonalize(), madness::projector_irrep::project_on_irreps(), q_c(), sub(), sum(), test_cross(), test_inner(), test_math(), test_rot(), madness::Zcis::transform(), madness::TDHF::transform(), transform(), madness::PNO::transform_pairs(), truncate(), madness::PNO::truncate_pairs(), madness::SCF::update_response_subspace(), Subspace::update_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), and madness::SCF::update_subspace().
concatenate_columns()
template<typename T > DistributedMatrix<T> madness::concatenate_columns (const DistributedMatrix< T > & a, const DistributedMatrix< T > & b)
Generates a row-distributed matrix with rows of a and b contatenated.
I.e., c[i,j] = a[i,j] if i<ma or b[i-ma,j] if i>=ma
The matrices a and b must have the same row size (i.e., the same number of columns) and be row distributed with the same row tilesze. The result is also row distributed with the same row tilesize as the input matrices.
Parameters
[in] a The first matrix
[in] b The second matrix
Returns
The result matrix
References _(), ___, a, b, c, and MADNESS_CHECK.
concatenate_rows() [1/2]
template<typename T > DistributedMatrix< T > madness::concatenate_rows (const DistributedMatrix< T > & a, const DistributedMatrix< T > & b)
Generates a column-distributed matrix with rows of a and b contatenated.
I.e., c[i,j] = a[i,j] if j<na or b[i,j-na] if j>=na
The matrices a and b must have the same column size (i.e., the same number of rows) and be column distributed with the same column tilesze. The result is also column distributed with the same column tilesize as the input matrices.
Parameters
[in] a The first matrix
[in] b The second matrix
Returns
The result matrix
References _(), ___, a, b, c, and MADNESS_CHECK.
Referenced by distributed_localize_PM().
concatenate_rows() [2/2]
template<typename T > DistributedMatrix<T> madness::concatenate_rows (const DistributedMatrix< T > & a, const DistributedMatrix< T > & b, const DistributedMatrix< T > & c, const DistributedMatrix< T > & d)
Generates a column-distributed matrix with rows of a, b, c, and d contatenated in order.
I.e., c[i,j] = a[i,j] if j in [0,na), b[i,j-na] if j in [na,na+nb), c[i,j-na-nb] if j in [na+nb,na+nb+nc), etc. The matrices must have the same column size (i.e., the same number of rows) and be column distributed with the same column tilesze. The result is also column distributed with the same column tilesize as the input matrices.
Parameters
[in] a The first matrix
[in] b The second matrix
[in] c The third matrix
[in] d The fourth matrix
Returns
The result matrix
References _(), ___, a, b, c, d(), madness::DistributedMatrix< T >::data(), and MADNESS_CHECK.
conditional_conj()
template<typename Q > Q madness::conditional_conj (const Q & coeff)
For real types return value, for complex return conjugate.
References op().
Referenced by madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::conj(), conj(), and madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::TENSOR_RESULT_TYPE().
conj() [1/4]
double madness::conj (double x) inline
conj() [2/4]
double madness::conj (float x) inline
conj() [3/4]
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::conj (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Returns the complex conjugate of the vector of functions.
References copy(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
conj() [4/4]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::conj (const Function< T, NDIM > & f, bool fence = true)
Return the complex conjugate of the input function with the same distribution and optional fence.
!!! The fence is actually not optional in the current implementation !!!
References madness::Function< T, NDIM >::conj(), copy(), f, and PROFILE_FUNC.
Referenced by madness::Solver< T, NDIM >::apply_hf_exchange(), madness::Solver< T, NDIM >::apply_hf_exchange4(), madness::Znemo::compute_current_density(), madness::Zcis::compute_potentials(), madness::Znemo::compute_potentials(), madness::FunctionImpl< Q, NDIM >::conj(), conj_transpose(), madness::Exchange< double, 3 >::Exchange(), madness::Znemo::hcore_guess(), madness::VectorSpace< T, NDIM >::inner(), madness::Zcis::iterate(), kinetic_energy_matrix_slow(), madness::Zcis::make_guess(), matrix_inner_old(), moments(), madness::conditional_conj_struct< Q, true >::op(), madness::conj_op< Q, NDIM >::operator()(), ExcitingApp::response(), and test_exchange().
convert() [1/3]
template<class Q , class T > LowRankTensor<Q> madness::convert (const LowRankTensor< T > & other)
type conversion implies a deep copy
Returns
Returns a new tensor that is a deep copy of the input
References copy(), madness::LowRankTensor< T >::impl, MADNESS_EXCEPTION, TT_2D, TT_FULL, TT_TENSORTRAIN, and madness::LowRankTensor< T >::type.
convert() [2/3]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<R,NDIM> > madness::convert (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Returns a deep copy of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
convert() [3/3]
template<typename T , typename Q , std::size_t NDIM> Function<Q,NDIM> madness::convert (const Function< T, NDIM > & f, bool fence = true)
Type conversion implies a deep copy. No communication except for optional fence.
Works in either basis but any loss of precision may result in different errors in applied in a different basis.
The new function is formed with the options from the default constructor.
There is no automatic type conversion since this is generally a rather dangerous thing and because there would be no way to make the fence optional.
References f, madness::Function< T, NDIM >::get_impl(), PROFILE_FUNC, and madness::Function< T, NDIM >::set_impl().
copy() [1/5]
template<typename T > DistributedMatrix<T> madness::copy (const DistributedMatrix< T > & A)
Deep copy of content.
Parameters
[in] A The matrix to be copied
Returns
A new matrix with identical dimensions, distribution and content (deep copy)
copy() [2/5]
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::copy (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Returns a deep copy of a vector of functions.
References copy(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
copy() [3/5]
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::copy (World & world, const Function< T, NDIM > & v, const unsigned int n, bool fence = true)
Returns a vector of deep copies of of a function.
References copy(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
copy() [4/5]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::copy (const Function< T, NDIM > & f, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & pmap, bool fence = true)
Create a new copy of the function with different distribution and optional fence.
Works in either basis. Different distributions imply asynchronous communication and the optional fence is collective.
References f, madness::Function< T, NDIM >::get_impl(), PROFILE_FUNC, madness::Function< T, NDIM >::set_impl(), VERIFY_TREE, and madness::Function< T, NDIM >::verify_tree().
Referenced by madness::FunctionCommonData< Q, NDIM >::_init_twoscale(), abs(), abs_square(), madness::FunctionNode< T, NDIM >::accumulate(), RealFuncIdentOp::action(), ComplexFuncIdentOp::action(), madness::CCIntermediatePotentials::add_unprojected_cc2_projector_response(), madness::SeparatedConvolution< T, NDIM >::apply(), apply(), madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::TDHF::apply_excitation_operators(), madness::SCF::apply_potential(), madness::Solver< T, NDIM >::apply_potential(), madness::SCF::apply_potential_response(), madness::projector_irrep::apply_symmetry_operators(), apply_U_mix(), apply_U_ncf(), apply_V(), applyexpLt(), madness::FunctionImpl< Q, NDIM >::binaryXXa(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::DFT< T, NDIM >::calculate_tot_xc_energy(), madness::FunctionImpl< Q, NDIM >::coeffs_for_jun(), madness::FunctionImpl< Q, NDIM >::compress_op(), compute_energy(), madness::MP2::compute_gQf_cc2interface(), madness::Zcis::compute_potentials(), compute_R2f2_psi(), compute_reduced_mass(), madness::MolecularOptimizer::compute_reduced_mass(), madness::Zcis::compute_residuals(), conj(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::continue_recursion(), madness::GenTensor< T >::convert(), convert(), madness::ConvolutionData1D< Q >::ConvolutionData1D(), madness::CC_vecfunction::copy(), madness::CCPairFunction::copy(), copy(), cplxfunc0(), cplxfunc2(), madness::Znemo::custom_guess(), madness::TensorTrain< T >::decompose(), dft_xc_lda_ene(), dft_xc_lda_V(), madness::DFTNuclearPotentialOp< T, NDIM >::DFTNuclearPotentialOp(), diag_and_transform(), madness::FunctionImpl< Q, NDIM >::dirac_convolution_op(), distributed_localize_PM(), dnuclear_anchor_test(), madness::Derivative< T, NDIM >::do_diff2b(), madness::SCF::do_plots(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), MiniDFT::doit(), doit(), fixphases(), madness::GenTensor< T >::full_tensor_copy(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_node(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_recursive(), gelss(), general_transform(), gesv(), madness::HartreeFock< T, NDIM >::get_coulomb_potential(), madness::MP2::get_fock_matrix(), madness::SCF::get_fock_transformation(), madness::Convolution1D< Q >::get_rnlp(), GMRES(), madness::BasisFunctions::guess_with_exop(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), madness::FunctionImpl< Q, NDIM >::inner_adaptive_recursive(), madness::FunctionImpl< Q, NDIM >::inner_ext_recursive(), inverse(), madness::CCPairFunction::invert_sign(), madness::MP2::iterate(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), madness::MolecularOrbitals< T, NDIM >::load_mos(), madness::SCF::load_mos(), loadbal(), madness::SCF::localize_boys(), madness::SCF::localize_new(), main(), madness::Nemo::make_ddensity(), smooth< T, NDIM >::make_explog(), madness::SCF::make_fock_matrix(), madness::Zcis::make_guess(), madness::Nemo::make_laplacian_density(), MiniDFT::make_lda_potential(), make_lda_potential(), madness::SCF::make_lda_potential(), madness::Solver< T, NDIM >::make_lda_potential(), madness::Solver< T, NDIM >::make_nuclear_potential_impl(), make_potential(), SurfaceMoleculeInteraction::make_surfcharge(), madness::CCPairFunction::make_xy_u(), madness::TwoElectronInterface< double, 6 >::map_coeff(), map_tensor(), madness::Convolution1D< Q >::mod_nonstandard(), madness::FunctionImpl< Q, NDIM >::mul(), madness::FunctionImpl< Q, NDIM >::multiply(), multiply_by_V(), madness::FunctionImpl< Q, NDIM >::mulXXa(), madness::FunctionImpl< Q, NDIM >::mulXXveca(), smooth< T, NDIM >::munge_density(), madness::Znemo::normalize(), nuclear_anchor_test(), madness::XCFunctionalLDA< T, NDIM >::op_r(), madness::pg_operator::operator()(), madness::interpolate_munge_refdens::operator()(), madness::Projector< double_complex, NDIM >::operator()(), BoysLocalization::operator()(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), myunaryop_square< T, NDIM >::operator()(), test_multiop< T, NDIM >::operator()(), madness::BinaryOpStructure< NDIM >::operator()(), madness::CCConvolutionOperator::operator()(), madness::XCOperator::logme::operator()(), madness::XCOperator::expme::operator()(), madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::operator()(), madness::FunctionImpl< T, NDIM >::do_keep_sum_coeffs::operator()(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::do_mapdim::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), madness::FunctionImpl< T, NDIM >::add_op::operator()(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), operator*(), madness::DistributedMatrix< double >::operator+(), madness::FunctionNode< T, NDIM >::operator=(), madness::Vector< int, 3 >::operator=(), orth(), ortho5(), madness::Znemo::orthonormalize(), outer(), plot_cubefile(), madness::XCOperator::prep_xc_args(), madness::projector_irrep::project_on_irreps(), madness::FunctionImpl< Q, NDIM >::project_refine_op(), madness::SCF::propagate(), propagate(), madness::Nemo::purify_hessian(), rank_revealing_decompose(), Plotter::read(), real(), realfunc0(), realfunc2(), madness::FunctionDefaults< NDIM >::recompute_cell_info(), madness::FunctionImpl< Q, NDIM >::reconstruct_op(), reconstruct_psi(), reduce(), madness::FunctionImpl< Q, NDIM >::refine_op(), madness::FunctionImpl< Q, NDIM >::refine_to_common_level(), madness::FunctionDefaults< NDIM >::set_cell(), madness::AtomicBasis::set_guess_info(), AtomicBasis::set_guess_info(), madness::MolecularOptimizer::set_hessian(), madness::QuasiNewton::set_hessian(), madness::Exchange< double, 3 >::set_parameters(), apply_kernel_helper::slater_apply(), smooth< T, NDIM >::smooth_density(), madness::CC2::solve(), madness::Nemo::solve(), solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), madness::Solver< T, NDIM >::Solver(), madness::Zcis::split(), square(), madness::archive::ArchiveStoreImpl< Archive, GenTensor< T > >::store(), madness::archive::ArchiveStoreImpl< Archive, Tensor< T > >::store(), madness::FunctionImpl< Q, NDIM >::sum_down_spawn(), svd(), madness::PNO::t_solve(), test2(), Test5(), Test7(), test_adaptive_tree(), test_add(), test_asymmetric(), test_bsh(), test_chin_chen(), test_cholesky(), test_compress(), test_convolution(), test_coulomb(), test_hermiticity(), test_multiply(), test_qr(), test_recursive_application(), test_rr_cholesky(), test_slater_exchange(), test_trotter(), test_truncation(), test_U_el(), test_unaryop(), madness::FunctionImpl< Q, NDIM >::tnorm(), transform(), transform_dir(), transpose(), trotter(), madness::TensorTrain< T >::truncate(), madness::FunctionImpl< Q, NDIM >::truncate_reconstructed_op(), two_scale_coefficients(), madness::NonlinearSolverND< NDIM >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::MolecularOrbitals< T, NDIM >::update_mos_and_eps(), CoreFittingTarget::value(), madness::Vector< int, 3 >::Vector(), madness::FunctionImpl< Q, NDIM >::vtransform(), and madness::MolecularOrbitals< T, NDIM >::write_to().
copy() [5/5]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::copy (const Function< T, NDIM > & f, bool fence = true)
Create a new copy of the function with the same distribution and optional fence.
References copy(), f, and PROFILE_FUNC.
copy_2d_patch()
template<typename T > static void madness::copy_2d_patch (T *MADNESS_RESTRICT out, long ldout, const T *MADNESS_RESTRICT in, long ldin, long n, long m) static
References m.
Referenced by madness::Convolution1D< Q >::nonstandard().
copy_am_arg()
AmArg* madness::copy_am_arg (const AmArg & arg) inline
References alloc_am_arg(), and arg().
Referenced by madness::WorldGopInterface::bcast_task(), and madness::WorldGopInterface::group_bcast_task().
CoulombOperator()
static SeparatedConvolution<double,3> madness::CoulombOperator (World & world, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with 1/r in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::CoulombFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), and madness::Tensor< T >::normf().
Referenced by madness::Coulomb::compute_potential(), GygiPot::ESP(), GygiPot::GuessPotential(), iterate_excite(), iterate_xy(), main(), MiniDFT::make_coulomb_potential(), make_coulomb_potential(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), test(), test_coulomb(), test_exchange(), test_nuclear_potential(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_periodic2(), and testNavierStokes().
CoulombOperatorPtr()
static SeparatedConvolution<double,3>* madness::CoulombOperatorPtr (World & world, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with 1/r in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::CoulombFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), and madness::Tensor< T >::normf().
Referenced by madness::Exchange< double, 3 >::Exchange(), madness::F12Potentials::F12Potentials(), madness::CCConvolutionOperator::init_op(), madness::Solver< T, NDIM >::initial_guess(), main(), madness::Solver< T, NDIM >::make_nuclear_potential(), madness::PNO::PNO(), madness::Znemo::recompute_factors_and_potentials(), madness::Exchange< double, 3 >::set_parameters(), madness::SCF::set_protocol(), Calculation::set_protocol(), madness::Nemo::set_protocol(), madness::Solver< T, NDIM >::Solver(), and madness::Znemo::Znemo().
cpu_frequency()
double madness::cpu_frequency ()
Estimate the processor frequency, in Hz.
First call may take about 0.1s to execute. Subsequent calls return the value, cached from the first call, so it does not respond to changing processor frequency.
If cycle_count() returns wall_time() in nanoseconds, this will return 1GHz.
If not available returns 0.
Returns
CPU frequency, in Hz.
References cycle_count(), and wall_time().
Referenced by cpu_time(), main(), startup(), and madness::World::World().
cpu_relax()
void madness::cpu_relax () inline
Do nothing and especially do not touch memory.
Todo:
Can we provide some context for this function?
Referenced by madness::MutexReaderWriter::convert_read_lock_to_write_lock(), madness::Barrier::enter(), madness::MutexReaderWriter::lock(), madness::MutexFair::lock(), myusleep(), madness::MutexReaderWriter::read_lock(), madness::MutexWaiter::wait(), madness::ConditionVariable::wait(), and madness::MutexReaderWriter::write_lock().
cpu_time()
static double madness::cpu_time () inline static
Returns the cpu time in seconds relative to an arbitrary origin.
As accurate and lightweight as we can get it, but may not be any better than the clock system call.
Returns
The cpu time, in second.
References cpu_frequency(), and cycle_count().
Referenced by madness::FunctionNode< T, NDIM >::accumulate(), madness::FunctionNode< T, NDIM >::accumulate2(), madness::SeparatedConvolution< T, NDIM >::apply(), madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::ThreadPool::await(), madness::WorldProfile::clear(), madness::FunctionImpl< Q, NDIM >::compress_op(), madness::FunctionImpl< Q, NDIM >::do_apply_kernel3(), madness::Znemo::timer::end(), madness::Nemo::timer::end(), END_TIMER(), END_TIMER(), madness::Nemo::END_TIMER(), madness::MP2::END_TIMER(), madness::Solver< T, NDIM >::END_TIMER(), initialize(), main(), myusleep(), madness::Fock::operator()(), madness::WorldProfile::print(), print_stats(), madness::MyTimer::start(), madness::CCTimer::start(), START_TIMER(), START_TIMER(), madness::Nemo::START_TIMER(), madness::MP2::START_TIMER(), madness::Solver< T, NDIM >::START_TIMER(), madness::MyTimer::stop(), madness::CCTimer::stop(), madness::Znemo::timer::tag(), madness::Nemo::timer::tag(), test9(), test_bsh(), test_multi(), test_time(), time_transform(), madness::Znemo::timer::timer(), madness::Nemo::timer::timer(), madness::CCTimer::update_time(), and madness::WorldProfileObj::~WorldProfileObj().
create_nuclear_correlation_factor() [1/2]
std::shared_ptr< NuclearCorrelationFactor > madness::create_nuclear_correlation_factor (World & world, const Molecule & molecule, const std::shared_ptr< PotentialManager > potentialmanager, const std::string inputline)
create and return a new nuclear correlation factor
Parameters
[in] world the world
[in] calc the calculation as read from the input file
Returns
a nuclear correlation factor
References a, lowercase(), MADNESS_EXCEPTION, molecule, print(), and madness::World::rank().
Referenced by madness::NemoBase::construct_nuclear_correlation_factor(), create_nuclear_correlation_factor(), dnuclear_anchor_test(), and nuclear_anchor_test().
create_nuclear_correlation_factor() [2/2]
std::shared_ptr< NuclearCorrelationFactor > madness::create_nuclear_correlation_factor (World & world, const Molecule & molecule, const std::shared_ptr< PotentialManager > pm, const std::pair< std::string, double > & ncf)
References create_nuclear_correlation_factor(), and molecule.
cross() [1/2]
template<typename T , std::size_t N> std::enable_if<N==3, Vector<T,N> >::type madness::cross (const Vector< T, N > & l, const Vector< T, N > & r)
compute the cross product two Vectors of dimension 3
Do a cross product of l and r and return the result in a new Vector.
Template Parameters
T The Vector element type.
N The Vector size.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand Vector.
Returns
the cross product
cross() [2/2]
template<typename T , typename R , std::size_t NDIM> std::vector<Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::cross (const std::vector< Function< T, NDIM > > & f, const std::vector< Function< R, NDIM > > & g, bool do_refine = false, bool fence = true)
shorthand cross operator
returns the cross product of vectors f and g
Parameters
[in] f the vector of functions on which the rot operator works on
[in] g the vector of functions on which the rot operator works on
[in] fence fence after completion; currently always fences
Returns
the vector {}{ x_i} f TODO: add this to operator fusion
References compress(), d(), f, g, MADNESS_ASSERT, mul(), and reconstruct().
Referenced by madness::Diamagnetic_potential_factor::compute_nabla_R_div_R(), madness::Diamagnetic_potential_factor::compute_U2(), madness::Diamagnetic_potential_factor::compute_v_vector(), madness::Diamagnetic_potential_factor::custom_factor(), madness::Diamagnetic_potential_factor::factor_with_phase(), madness::R_times_arg_div_R::operator()(), and test_cross().
cubefile_header()
std::vector< std::string > madness::cubefile_header (std::string filename, const bool & no_orient = false)
read molecule from the input file and return part of the header for a Gaussian cube file.
Parameters
[in] filename input file name (usually "input")
References madness::Molecule::cubefile_header(), filename, molecule, madness::Molecule::orient(), and madness::Molecule::read_file().
Referenced by main().
cycle_count()
static uint64_t madness::cycle_count () inline static
On some machines we have access to a cycle count.
For small intervals this is probably the most lightweight and accurate timer but may not be meaningful over long intervals due to O/S scheduling, migration to different cores, frequency shifts, etc. On x86 uses rtdsc. Otherwise uses wall_time() in nanoseconds.
Returns
Timing, in cycle count.
References a, d(), and wall_time().
Referenced by cpu_frequency(), and cpu_time().
d2smoothed_potential()
double madness::d2smoothed_potential (double r)
second radial derivative of the regularized 1/r potential
invoke as d2smoothed_potential(r*rc) * rc*rc*rc with rc the reciprocal smoothing radius d2u[r*rc]*rc*rc*rc 2/r^3
References e(), and madness::constants::pi.
Referenced by madness::Molecule::nuclear_attraction_potential_second_derivative().
displacement()
template<size_t NDIM> Key<NDIM> madness::displacement (const Key< NDIM > & source, const Key< NDIM > & target)
given a source and a target, return the displacement in translation
Parameters
[in] source the source key
[in] target the target key
Returns
disp such that target = source + disp
References MADNESS_ASSERT, source(), and target().
Referenced by madness::MolecularOptimizer::optimize_conjugate_gradients().
distance() [1/5]
double madness::distance (const Fred & a, const Fred & b)
References a, and b.
distance() [2/5]
double madness::distance (madness::Function< std::complex< double >, 1ul > & a, madness::Function< std::complex< double >, 1ul > & b)
References a, and b.
distance() [3/5]
static double madness::distance (double x1, double y1, double z1, double x2, double y2, double z2) inline static
Referenced by madness::Molecule::atomic_attraction_potential(), madness::Molecule::core_potential_derivative(), madness::atom_information< NDIM >::get_distance(), xc_functor< NDIM >::get_distance(), madness::int_factor_functor< NDIM >::get_distance(), madness::lr_pot_functor< NDIM >::get_distance(), MolecularEntity::inter_atomic_distance(), madness::Molecule::inter_atomic_distance(), main(), madness::Molecule::mol_nuclear_charge_density(), madness::Molecule::molecular_core_potential(), MolecularEntity::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential_derivative(), and madness::Molecule::test_for_op().
distance() [4/5]
double madness::distance (double a, double b) inline
Default function for computing the distance between two doubles.
References a, and b.
distance() [5/5]
template<typename T > double madness::distance (std::complex< T > & a, std::complex< T > & b) inline
Default function for computing the distance between two complex numbers.
References a, std::abs(), and b.
distance_sq()
static double madness::distance_sq (double x1, double y1, double z1, double x2, double y2, double z2) inline static
Referenced by madness::Molecule::nuclear_charge_density().
distributed_localize_PM()
distmatT madness::distributed_localize_PM (World & world, const vecfuncT & mo, const vecfuncT & ao, const std::vector< int > & set, const std::vector< int > & at_to_bf, const std::vector< int > & at_nbf, const double thresh = 1e-9, const double thetamax = 0.25, const bool randomize = true, const bool doprint = false)
References a, at_nbf, at_to_bf, concatenate_rows(), copy(), madness::BaseTensor::dim(), madness::DistributedMatrix< T >::extract_columns(), madness::DistributedMatrix< T >::fill_identity(), matrix_inner(), and thresh.
Referenced by madness::SCF::localize_PM().
div()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::div (const std::vector< Function< T, NDIM > > & v, bool do_refine = false, bool fence = true)
shorthand div operator
returns the dot product of nabla with a vector f
Parameters
[in] f the vector of functions on which the div operator works on
[in] refine refinement before diff'ing makes the result more accurate
[in] fence fence after completion; currently always fences
Returns
the vector {}{ x_i} f TODO: add this to operator fusion
References apply(), grad(), MADNESS_ASSERT, NDIM, reconstruct(), refine(), and sum().
Referenced by madness::XCOperator::apply_xc_kernel(), madness::Znemo::compute_current_density(), madness::Diamagnetic_potential_factor::compute_R_times_T_commutator_scalar_term_numerically(), madness::XCOperator::make_xc_potential(), test_rot(), and testNavierStokes().
do_adq()
template<typename funcT > funcT::returnT madness::do_adq (double lo, double hi, const funcT & func, int n, const double * x, const double * w)
References func(), lo, and sum().
Referenced by adq1().
dot()
template<typename T , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(T,R), NDIM> madness::dot (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true)
Multiplies and sums two vectors of functions r = a[i] * b[i].
References a, b, mul(), and sum().
Referenced by madness::TDHF::analyze(), madness::Nemo::compute_all_cphf(), madness::OEP::compute_average_I(), madness::Znemo::compute_current_density(), madness::OEP::compute_density(), madness::OEP::compute_exchange_energy_vir(), madness::Diamagnetic_potential_factor::compute_lz_commutator(), madness::OEP::compute_Pauli_kinetic_density(), madness::Zcis::compute_potentials(), madness::OEP::compute_slater_potential(), madness::OEP::compute_total_kinetic_density(), madness::Zcis::iterate(), madness::Nemo::kinetic_energy_potential(), madness::Zcis::make_guess(), madness::Nemo::make_incomplete_hessian_response_part(), madness::Nemo::make_sigma(), madness::NuclearCorrelationFactor::U3_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U3X_functor::operator()(), madness::XCOperator::prep_xc_args(), madness::XCOperator::prep_xc_args_response(), and madness::Nemo::solve_cphf().
DPEC() [1/6]
madness::DPEC (int , int , int)
DPEC() [2/6]
madness::DPEC (long , long , long)
DPEC() [3/6]
madness::DPEC (float , float , float)
DPEC() [4/6]
madness::DPEC (double , double , double)
DPEC() [5/6]
madness::DPEC (float_complex , float_complex , float_complex)
DPEC() [6/6]
madness::DPEC (double_complex , double_complex , double_complex)
drot()
void madness::drot (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
References a, aa, b, and c.
Referenced by madness::SystolicPMOrbitalLocalize::localize_PM_ij(), main(), and BoysLocalization::operator()().
dsmoothed_potential()
double madness::dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
dV/dx = (x/r) * du(r/c)/(c*c)
References a, and r2().
Referenced by madness::CorePotential::eval_derivative(), madness::Molecule::nuclear_attraction_potential_derivative(), and madness::PseudoNuclearCorrelationFactor::U2X_spherical().
dxprintvalue() [1/2]
static void madness::dxprintvalue (FILE * f, const double t) inline static
References f.
Referenced by plotdx().
dxprintvalue() [2/2]
static void madness::dxprintvalue (FILE * f, const double_complex & t) inline static
References f.
end_papi_measurement()
void madness::end_papi_measurement () inline
Referenced by madness::ThreadBase::main(), and print_stats().
END_TIMER()
static void madness::END_TIMER (World & world, const char * msg) static
References cpu_time(), pop(), print_timings, madness::World::rank(), sss, ttt, and wall_time().
Referenced by madness::SCF::analyze_vectors(), KPeriodicBSHOperator::apply(), apply_potential(), madness::SCF::apply_potential(), madness::SCF::apply_potential_response(), madness::SCF::calc_djkmo(), madness::SCF::calc_xc_function(), madness::SCF::compute_residual(), madness::SCF::derivatives(), madness::SCF::diag_fock_matrix(), madness::SCF::dipole(), madness::SCF::dipole_matrix_elements(), madness::SCF::do_plots(), madness::SCF::get_fock_transformation(), madness::SCF::initial_guess(), madness::SCF::kinetic_energy_matrix(), madness::SCF::localize_boys(), madness::SCF::localize_new(), madness::SCF::localize_PM(), main(), make_coulomb_potential(), make_density(), madness::SCF::make_fock_matrix(), make_kinetic_matrix(), make_lda_potential(), madness::SCF::make_nuclear_potential(), Calculation::make_reference(), Calculation::make_Upsi(), makeao(), orthogonalize(), madness::SCF::orthonormalize(), madness::SCF::polarizability(), madness::SCF::solve(), test_coulomb(), test_cross(), test_diff(), test_inner(), test_op(), test_rot(), madness::SCF::update_response_subspace(), and madness::SCF::update_subspace().
enforce_bc()
static bool madness::enforce_bc (bool is_periodic, Level n, Translation & l) inline static
Referenced by madness::FunctionImpl< Q, NDIM >::neighbor().
error() [1/2]
void madness::error (const char * msg)
Todo:
Brief description needed.
Todo:
Detailed description needed. I imagine this prints/logs the supplied error message and subsequently aborts the program.
Parameters
[in] msg Message associated with the error.
References SafeMPI::Intracomm::Abort(), and SafeMPI::COMM_WORLD.
Referenced by madness::WorldGopInterface::barrier(), madness::PNO::check_orthonormality(), compare(), madness::DependencyInterface::dec(), madness::DependencyInterface::dec_debug(), doit(), madness::DomainMaskSDFFunctor< NDIM >::DomainMaskSDFFunctor(), EmbeddedDirichlet::EmbeddedDirichlet(), madness::DependencyInterface::inc(), madness::DependencyInterface::inc_debug(), madness::CC2::initialize_pairs(), madness::CC2::iterate_pair(), Calculation::load_mos(), main(), madness::ThreadBase::main(), EmbeddedDirichlet::operator()(), madness::DomainMaskSDFFunctor< NDIM >::operator()(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::hartree_convolute_leaf_op< T, NDIM, LDIM, opT >::operator()(), madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::operator()(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::operator()(), madness::FunctionImpl< Q, NDIM >::print_plane_local(), madness::CalculationParameters::set_derived_values(), madness::DomainMaskSDFFunctor< NDIM >::setMaskFunction(), test(), Test1(), Test5(), Test6(), Test6a(), Test7(), test_add(), test_G_R_vectors(), test_gaussian_num_coeffs(), test_gconv(), test_hf_be(), test_hf_he(), madness::Diamagnetic_potential_factor::test_lz_commutator(), test_multi_to_multi_op(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_orthogonalization(), test_per(), test_projector(), test_qr(), test_spherical_box(), madness::Znemo::test_U_potentials(), madness::Diamagnetic_potential_factor::test_vector_potentials(), testNavierStokes(), testPeriodicCoulomb3d(), madness::FunctionImpl< Q, NDIM >::truncate_reconstructed_op(), and madness::DependencyInterface::~DependencyInterface().
error() [2/2]
template<typename T > static void madness::error (const char * msg, const T & data) static
Prints an error message, along with some data, and aborts the program.
Todo:
Does this function need to be static? (Esp. since it's in a header file...)
Template Parameters
T The type of data.
Parameters
[in] msg The error message.
[in] data The data to be printed.
References SafeMPI::Intracomm::Abort(), and SafeMPI::COMM_WORLD.
exception_break()
void madness::exception_break (bool message)
This function is executed just before a MadnessException is thrown.
Parameters
[in] message True to print an error message to cerr; false otherwise.
fast_transpose()
template<typename T > void madness::fast_transpose (long n, long m, const T * a, T *MADNESS_RESTRICT b) inline
a(n,m) --> b(m,n) ... optimized for smallish matrices
References a, a1, a2, b, and m.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply_transformation(), madness::SeparatedConvolution< T, NDIM >::apply_transformation2(), madness::Convolution1D< Q >::mod_nonstandard(), and madness::Convolution1D< Q >::nonstandard().
fcube() [1/3]
template<typename T , std::size_t NDIM> Tensor< T > madness::fcube (const Key< NDIM > & key, T(*)(const Vector< double, NDIM > &) f, const Tensor< double > & qx)
References madness::BaseTensor::dim(), f, and NDIM.
Referenced by fcube(), madness::FunctionImpl< Q, NDIM >::fcube(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_node(), madness::guessfactory::ExopUnaryOpStructure::operator()(), madness::UnaryOpStructure< NDIM >::operator()(), madness::BinaryOpStructure< NDIM >::operator()(), madness::FunctionImpl< Q, NDIM >::project(), and madness::ElementaryInterface< T, NDIM >::values().
fcube() [2/3]
template<typename T , std::size_t NDIM> Tensor< T > madness::fcube (const Key< NDIM > & key, const FunctionFunctorInterface< T, NDIM > & f, const Tensor< double > & qx)
References madness::BaseTensor::dim(), f, fcube(), and NDIM.
fcube() [3/3]
template<typename T , std::size_t NDIM> void madness::fcube (const Key< NDIM > & key, const FunctionFunctorInterface< T, NDIM > & f, const Tensor< double > & qx, Tensor< T > & fval)
forward declaration
References ___, c, madness::BaseTensor::dim(), f, madness::FunctionDefaults< NDIM >::get_cell(), madness::FunctionDefaults< NDIM >::get_cell_width(), h(), std::isnan(), k, madness::Key< NDIM >::level(), m, MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, p(), pow(), madness::Tensor< T >::ptr(), and madness::Key< NDIM >::translation().
finalize()
void madness::finalize ()
Call this once at the very end of your main program instead of MPI_Finalize().
References madness::World::default_world, madness::RMI::end(), madness::ThreadPool::end(), madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::detail::WorldMpi::finalize(), madness::World::gop, quiet(), madness::World::rank(), madness::World::size(), and madness::World::worlds.
Referenced by main(), test_G_R_vectors(), test_gaussian_num_coeffs(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), and testNavierStokes().
foreach_child() [1/2]
template<std::size_t NDIM, typename opT > void madness::foreach_child (const Key< NDIM > & parent, opT & op) inline
Applies op(key) to each child key of parent.
References op().
foreach_child() [2/2]
template<std::size_t NDIM, typename objT > void madness::foreach_child (const Key< NDIM > & parent, objT * obj, void(objT::*)(const Key< NDIM > &) memfun) inline
Applies member function of obj to each child key of parent.
free_am_arg()
void madness::free_am_arg (AmArg * arg) inline
Frees an AmArg allocated with alloc_am_arg.
References arg().
Referenced by madness::WorldAmInterface::SendReq::free(), and madness::detail::PendingMsg::invokehandler().
free_space_derivative()
template<typename T , std::size_t NDIM> Derivative<T,NDIM> madness::free_space_derivative (World & world, int axis, int k = FunctionDefaults<NDIM>::get_k())
Convenience function returning derivative operator with free-space boundary conditions.
References axis, BC_FREE, and k.
func()
std::shared_ptr< FunctionFunctorInterface<double,3> > madness::func (new opTg)
Referenced by abs(), abs_square(), abs_square(), adq(), adq1(), madness::PotentialManager::core_projector_derivative(), madness::SCF::core_projector_derivative(), madness::SCF::derivatives(), do_adq(), madness::FunctionImpl< Q, NDIM >::err_box(), madness::FunctionImpl< Q, NDIM >::errsq_local(), madness::WorldAmInterface::handler(), imag(), madness::RMI::isend(), make_func(), madness::FunctionImpl< Q, NDIM >::make_Vphi(), madness::EigSolverOp< T, NDIM >::op_o(), madness::EigSolverOp< T, NDIM >::op_r(), Wannier< T, NDIM >::operator()(), madness::RMI::RmiTask::process_some(), real(), madness::NuclearCorrelationFactor::square_times_V_derivative(), test_hydro(), unary_op(), unary_op_coeffs(), madness::FunctionImpl< Q, NDIM >::unaryXX(), madness::FunctionImpl< Q, NDIM >::unaryXXa(), and madness::FunctionImpl< Q, NDIM >::unaryXXvalues().
function_real2complex()
template<typename Q , int NDIM> Function<std::complex<Q>,NDIM> madness::function_real2complex (const Function< Q, NDIM > & r)
References unary_op_coeffs().
functor_r2()
static double madness::functor_r2 (const coord_3d & r) static
functor_x()
static double madness::functor_x (const coord_3d & r) static
functor_y()
static double madness::functor_y (const coord_3d & r) static
future_vector_factory()
template<typename T > std::vector< Future<T> > madness::future_vector_factory (std::size_t n)
Factory for a vectors of futures.
Rationale for this function can be found in Futures.
Template Parameters
T The type of future in the vector.
Parameters
[in] n The size of the vector to create.
Returns
A vector of futures, as described in Futures.
References madness::Future< T >::default_initializer().
gauss_legendre()
bool madness::gauss_legendre (int n, double xlo, double xhi, double * x, double * w)
Return precomputed (most accurate) or if not available computed (not quite as accurate) points and weights for Gauss Legendre quadrature rule on the specified interval.
References gauss_legendre_numeric(), max_npt, points, read_data(), and weights.
Referenced by madness::FunctionCommonData< Q, NDIM >::_init_quadrature(), adq(), madness::Convolution1D< Q >::Convolution1D(), gauss_legendre_test(), readin(), and madness::SpectralPropagator::SpectralPropagator().
gauss_legendre_numeric()
bool madness::gauss_legendre_numeric (int n, double xlo, double xhi, double * x, double * w)
Compute the Gauss-Legendre quadrature points and weights.
Return in x and w, which should be arrays of n elements, the points and weights for the n-point Gauss Legendre quadrature rule in [xlo,xhi].
!!!! This routine delivers accurate points, but some weights are accurate only to about 1e-13 for higher order rules. Need a more intelligent way to compute them. See internal comments for more info.
References std::abs(), delta, e(), k, legendre_polynomials(), p(), pi, and scale().
Referenced by gauss_legendre().
gauss_legendre_test()
bool madness::gauss_legendre_test (bool print)
Check error in numerical integ(x+x^2+...+x^(2n-1),x=0..1) using n-pt rule.
References std::abs(), gauss_legendre(), print(), sum(), and testf().
Referenced by startup().
gaxpy() [1/2]
template<typename T , typename Q , typename R , std::size_t NDIM> void madness::gaxpy (World & world, Q alpha, std::vector< Function< T, NDIM > > & a, Q beta, const std::vector< Function< R, NDIM > > & b, unsigned int blk = 1, bool fence = true)
Generalized A*X+Y for vectors of functions -— a[i] = alpha*a[i] + beta*b[i].
References a, alpha, b, beta, compress(), madness::WorldGopInterface::fence(), gaxpy(), madness::World::gop, MADNESS_ASSERT, and PROFILE_BLOCK.
gaxpy() [2/2]
template<typename T , typename Q , typename R , std::size_t NDIM> void madness::gaxpy (World & world, Q alpha, std::vector< Function< T, NDIM > > & a, Q beta, const std::vector< Function< R, NDIM > > & b, bool fence = true)
Generalized A*X+Y for vectors of functions -— a[i] = alpha*a[i] + beta*b[i].
References a, alpha, b, beta, compress(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, and PROFILE_BLOCK.
Referenced by madness::PotentialManager::apply_nonlocal_potential(), apply_potential(), madness::GTHPseudopotential< Q >::apply_potential(), madness::SCF::apply_potential(), madness::SCF::apply_potential_response(), madness::projector_irrep::apply_symmetry_operators(), madness::SCF::calc_djkmo(), madness::SCF::compute_residual(), madness::Solver< T, NDIM >::do_rhs(), gaxpy(), kinetic_energy_matrix(), madness::Nemo::kinetic_energy_potential(), main(), Calculation::make_reference(), madness::EigSolver< T, NDIM >::multi_solve(), q_c(), madness::Nemo::solve(), madness::Nemo::solve_cphf(), madness::Solver< T, NDIM >::step_restriction(), testNavierStokes(), madness::Zcis::transform(), transform(), madness::TDHF::transform(), update(), MiniDFT::update(), madness::SCF::update_response_subspace(), Subspace::update_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), and madness::SCF::update_subspace().
gaxpy_oop() [1/3]
template<typename T , typename Q , typename R , std::size_t NDIM> std::vector<Function<TENSOR_RESULT_TYPE(Q,TENSOR_RESULT_TYPE(T,R)),NDIM> > madness::gaxpy_oop (Q alpha, const std::vector< Function< T, NDIM > > & a, Q beta, const std::vector< Function< R, NDIM > > & b, bool fence = true)
out-of-place gaxpy for two vectors: result[i] = alpha * a[i] + beta * b[i]
References a, alpha, b, beta, compress(), madness::WorldGopInterface::fence(), gaxpy_oop(), madness::World::gop, MADNESS_ASSERT, R, and TENSOR_RESULT_TYPE().
gaxpy_oop() [2/3]
template<typename T , typename Q , typename R , std::size_t NDIM> std::vector<Function<TENSOR_RESULT_TYPE(Q,TENSOR_RESULT_TYPE(T,R)),NDIM> > madness::gaxpy_oop (Q alpha, const std::vector< Function< T, NDIM > > & a, Q beta, const Function< R, NDIM > & b, bool fence = true)
out-of-place gaxpy for a vectors and a function: result[i] = alpha * a[i] + beta * b
References a, alpha, b, beta, compress(), madness::WorldGopInterface::fence(), gaxpy_oop(), madness::World::gop, R, and TENSOR_RESULT_TYPE().
gaxpy_oop() [3/3]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R),NDIM> madness::gaxpy_oop (TENSOR_RESULT_TYPE(L, R) alpha, const Function< L, NDIM > & left, TENSOR_RESULT_TYPE(L, R) beta, const Function< R, NDIM > & right, bool fence = true)
Returns new function alpha*left + beta*right optional fence and no automatic compression.
References alpha, beta, madness::Function< T, NDIM >::gaxpy_oop(), and PROFILE_FUNC.
Referenced by add(), gaxpy_oop(), operator+(), operator-(), sub(), and test_add().
gaxpy_oop_reconstructed()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::gaxpy_oop_reconstructed (const double alpha, const Function< T, NDIM > & left, const double beta, const Function< T, NDIM > & right, const bool fence = true)
Returns new function alpha*left + beta*right optional fence, having both addends reconstructed.
References alpha, beta, madness::Function< T, NDIM >::get_impl(), madness::Function< T, NDIM >::is_compressed(), MADNESS_ASSERT, and madness::Function< T, NDIM >::set_impl().
Referenced by operator+(), operator-(), and test_add().
gelss() [1/3]
template<typename T > void madness::gelss (const Tensor< T > & a, const Tensor< T > & b, double rcond, Tensor< T > & x, Tensor< typename Tensor< T >::scalar_type > & s, long & rank, Tensor< typename Tensor< T >::scalar_type > & sumsq)
Solve Ax = b for general A using the LAPACK *gelss routines.
Solves linear equations using least squares.
A should be a matrix (float, double, float_complex, double_complex) and b should be either a vector, or a matrix with each vector stored in a column (i.e., b[n,nrhs]).
If the LAPACK routine fails, it throws a TensorException with the LAPACK info as the value. Otherwise, it returns the solution(s). The input A and b are unchanged. There is no need to worry about Python/C/Fortran ordering issues. It will solve Ax=b as written.
This from the LAPACK documentation
RCOND   (input) REAL
RCOND is used to determine the effective  rank  of A.
Singular values S(i) <= RCOND*S(1) are treated
as zero.  If RCOND < 0, machine precision is  used
instead.
RANK    (output) INTEGER
The  effective rank of A, i.e., the number of singular
values which are greater than RCOND*S(1).
Finally, the optional vector sumsq will store the sum-of-squares residual in the case of a rectangular matrix (least squares regression).
References a, b, copy(), dgelss_(), m, mask_info(), max, madness::Tensor< T >::normf(), madness::Tensor< T >::ptr(), TENSOR_ASSERT, and transpose().
Referenced by Calculation::calc_optimal_coeffs(), GMRES(), KAIN(), KAIN(), optimize_coeffs(), and test_gelss().
gelss() [2/3]
template void madness::gelss (const Tensor< double > & a, const Tensor< double > & b, double rcond, Tensor< double > & x, Tensor< Tensor< double >::scalar_type > & s, long & rank, Tensor< Tensor< double >::scalar_type > & sumsq)
gelss() [3/3]
template void madness::gelss (const Tensor< double_complex > & a, const Tensor< double_complex > & b, double rcond, Tensor< double_complex > & x, Tensor< Tensor< double_complex >::scalar_type > & s, long & rank, Tensor< Tensor< double_complex >::scalar_type > & sumsq)
general_transform() [1/3]
template<class T , class Q > LowRankTensor<TENSOR_RESULT_TYPE(T,Q)> madness::general_transform (const LowRankTensor< T > & t, const Tensor< Q > c[])
References c, and madness::LowRankTensor< T >::general_transform().
general_transform() [2/3]
template<class T , class Q > GenTensor<TENSOR_RESULT_TYPE(T,Q)> madness::general_transform (const GenTensor< T > & t, const Tensor< Q > c[])
Transform all dimensions of the tensor t by distinct matrices c.
Similar to transform but each dimension is transformed with a distinct matrix.
result(i,j,k...) <-- sum(i',j', k',...) t(i',j',k',...) c[0](i',i) c[1](j',j) c[2](k',k) ...
The first dimension of the matrices c must match the corresponding dimension of t.
References c.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply_transformation2(), madness::SeparatedConvolution< T, NDIM >::apply_transformation3(), madness::FunctionImpl< Q, NDIM >::downsample(), madness::FunctionImpl< Q, NDIM >::fcube_for_mul(), madness::GenTensor< T >::general_transform(), madness::LowRankTensor< T >::general_transform(), madness::SRConf< T >::general_transform(), madness::FunctionImpl< Q, NDIM >::NS_fcube_for_mul(), madness::SeparatedConvolution< T, NDIM >::partial_upsample(), madness::SeparatedConvolution< T, NDIM >::upsample(), and madness::FunctionImpl< Q, NDIM >::upsample().
general_transform() [3/3]
template<class T > GenTensor<T> madness::general_transform (const GenTensor< T > & t, const Tensor< T > c[])
References c.
geqp3() [1/2]
template<typename T > void madness::geqp3 (Tensor< T > & A, Tensor< T > & tau, Tensor< integer > & jpvt)
Compute the QR factorization.
Q is returned in the lapack-specific format
References geqp3_result(), m, TENSOR_ASSERT, and transpose().
geqp3() [2/2]
template void madness::geqp3 (Tensor< double > & A, Tensor< double > & tau, Tensor< integer > & jpvt)
geqp3_result()
template<typename T > void madness::geqp3_result (Tensor< T > & A, Tensor< T > & tau, Tensor< integer > & jpvt, Tensor< T > & work)
References dgeqp3_(), m, mask_info(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), and TENSOR_ASSERT.
Referenced by geqp3().
gesv() [1/3]
template<typename T > void madness::gesv (const Tensor< T > & a, const Tensor< T > & b, Tensor< T > & x)
Solve Ax = b for general A using the LAPACK *gesv routines.
Solves linear equations.
A should be a square matrix (float, double, float_complex, double_complex) and b should be either a vector, or a matrix with each vector stored in a column (i.e., b[n,nrhs]).
If the LAPACK routine fails, it throws a TensorException with the LAPACK info as the value. Otherwise, it returns the solution(s). The input A and b are unchanged. There is no need to worry about Python/C/Fortran ordering issues. It will solve Ax=b as written.
References a, b, copy(), dgesv_(), m, mask_info(), madness::Tensor< T >::ptr(), TENSOR_ASSERT, and transpose().
Referenced by madness::GFit< T, NDIM >::bsh_fit(), gesvp(), and test_gesv().
gesv() [2/3]
template void madness::gesv (const Tensor< double > & a, const Tensor< double > & b, Tensor< double > & x)
gesv() [3/3]
template void madness::gesv (const Tensor< double_complex > & a, const Tensor< double_complex > & b, Tensor< double_complex > & x)
gesvp()
template<typename T > void madness::gesvp (World & world, const Tensor< T > & a, const Tensor< T > & b, Tensor< T > & x)
References a, b, and gesv().
Referenced by madness::SCF::analyze_vectors(), madness::MolecularOrbitals< T, NDIM >::project_ao(), and madness::SCF::restart_aos().
get_atomic_data()
const AtomicData & madness::get_atomic_data (unsigned int atomic_number)
Referenced by madness::Molecule::add_atom(), madness::Atom::Atom(), madness::Molecule::print(), AtomicBasisSet::print(), madness::AtomicBasisSet::print(), AtomicBasisSet::print_all(), madness::AtomicBasisSet::print_all(), AtomicBasisSet::print_anal(), and madness::AtomicBasisSet::print_anal().
get_charge_from_file()
double madness::get_charge_from_file (const std::string filename, unsigned int atype)
References filename, MADNESS_EXCEPTION, and symbol_to_atomic_number().
Referenced by madness::SCF::SCF().
get_papi_measurement()
const long long* madness::get_papi_measurement () inline
Referenced by print_stats().
get_size() [1/2]
template<typename T , std::size_t NDIM> double madness::get_size (World & world, const std::vector< Function< T, NDIM > > & v)
References d().
Referenced by madness::PNO::compute_fluctuation_matrix(), madness::F12Potentials::compute_fQc_integrals_ij(), madness::Nemo::compute_nemo_potentials(), madness::F12Potentials::F12Potentials(), madness::PNO::initialize_pairs(), madness::PNO::iterate_pairs_internal(), madness::TDHF::print_xfunctions(), madness::PNO::truncate_pairs(), madness::PNOPairs::update_meminfo(), and madness::PNO::update_pno().
get_size() [2/2]
template<typename T , std::size_t NDIM> double madness::get_size (const Function< T, NDIM > & f)
References d(), and f.
GMRES()
template<typename T , typename real_type , typename scalar_type > void madness::GMRES (const AbstractVectorSpace< T, real_type, scalar_type > & space, const Operator< T > & op, const T & b, T & x, int & maxiters, real_type & resid_thresh, real_type & update_thresh, const bool outp = false)
A GMRES solver routine for linear systems, .
Requires the vector space, the operator, A, the inhomogeneity b, an initial guess x, the maximum number of iterations, the convergence threshold for the solution residual, the convergence threshold for the norm of the update vector, and a flag for producing output.
The vector space object provides a standard way to compute the needed linear algebra operations (norm, inner product, etc.).
The printed output, if desired, shows iteration number, the residual, the norm of the change in solution vectors from one iteration to the next, and the effective rank of the GMRES matrix at that iteration.
On output, x has the computed solution, resid_thresh has its residual, update_thresh has the latest updatenorm, and maxiters has the number of iterations needed.
Parameters
[in] space The AbstractVectorSpace interface for the type
[in] op The Operator
[in] b The right-hand-side vector
[in,out] x Input: The initial guess for . Output: The computed solution for .
[in,out] maxiters Input: Maximum number of iterations to perform. Output: Actual iterations performed.
[in,out] resid_thresh Input: Convergence threshold for the residual . Output: The residual after the final iteration.
[in,out] update_thresh Input: Convergence threshold for the update vector . Output: The value after the final iteration.
[in] outp True if output to stdout is desired, false otherwise, defaults to false if unspecified.
References b, copy(), madness::AbstractVectorSpace< T, real_type, scalar_type >::destroy(), e(), madness::AbstractVectorSpace< T, real_type, scalar_type >::gaxpy(), gelss(), imag(), madness::AbstractVectorSpace< T, real_type, scalar_type >::inner(), madness::detail::norm(), madness::AbstractVectorSpace< T, real_type, scalar_type >::norm(), madness::Tensor< T >::normf(), op(), madness::World::rank(), real(), madness::AbstractVectorSpace< T, real_type, scalar_type >::scale(), V(), and madness::AbstractVectorSpace< T, real_type, scalar_type >::world.
Referenced by cplxfunc0(), cplxfunc1(), cplxfunc2(), cplxvec0(), cplxvec1(), cplxvec2(), main(), realfunc0(), realfunc1(), realfunc2(), realvec0(), realvec1(), and realvec2().
gprofexit()
void madness::gprofexit (int id, int nproc)
Rename gmon.out for each process by ordering process termination.
Invoke with id and nproc as rank and size in MPI::COMM_WORLD
References p().
grad()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::grad (const Function< T, NDIM > & f, bool refine = false, bool fence = true)
shorthand gradient operator
returns the differentiated function f in all NDIM directions
Parameters
[in] f the function on which the grad operator works on
[in] refine refinement before diff'ing makes the result more accurate
[in] fence fence after completion; if reconstruction is needed always fence
Returns
the vector {}{ x_i} f
References apply(), f, madness::WorldGopInterface::fence(), madness::World::gop, NDIM, and refine().
Referenced by madness::Znemo::compute_current_density(), madness::OEP::compute_exchange_energy_vir(), madness::NemoBase::compute_gradient(), madness::Znemo::compute_kinetic_momentum(), madness::OEP::compute_Pauli_kinetic_density(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::OEP::compute_total_kinetic_density(), div(), grad_ble_one(), grad_ble_two(), grad_bpsline_two(), grad_bspline_one(), grad_bspline_three(), MolecularMaskBase::gradient(), madness::Znemo::gradient(), madness::Nemo::gradient(), madness::Nemo::make_sigma(), MolecularSurface::operator()(), MolecularVolumeMaskGrad::operator()(), madness::XCOperator::prep_xc_args(), madness::XCOperator::prep_xc_args_response(), rot(), test_rot(), and madness::Diamagnetic_potential_factor::test_vector_potentials().
grad_ble_one()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::grad_ble_one (const Function< T, NDIM > & f, bool refine = false, bool fence = true)
References apply(), f, madness::WorldGopInterface::fence(), madness::World::gop, grad(), NDIM, and refine().
Referenced by madness::XCOperator::prep_xc_args().
grad_ble_two()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::grad_ble_two (const Function< T, NDIM > & f, bool refine = false, bool fence = true)
References apply(), f, madness::WorldGopInterface::fence(), madness::World::gop, grad(), NDIM, and refine().
grad_bpsline_two()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::grad_bpsline_two (const Function< T, NDIM > & f, bool refine = false, bool fence = true)
References apply(), f, madness::WorldGopInterface::fence(), madness::World::gop, grad(), NDIM, and refine().
grad_bspline_one()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::grad_bspline_one (const Function< T, NDIM > & f, bool refine = false, bool fence = true)
References apply(), f, madness::WorldGopInterface::fence(), madness::World::gop, grad(), NDIM, and refine().
Referenced by madness::OEP::compute_Pauli_kinetic_density(), madness::Diamagnetic_potential_factor::compute_R_times_T_commutator_scalar_term_numerically(), madness::OEP::compute_total_kinetic_density(), and madness::XCOperator::prep_xc_args().
grad_bspline_three()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::grad_bspline_three (const Function< T, NDIM > & f, bool refine = false, bool fence = true)
References apply(), f, madness::WorldGopInterface::fence(), madness::World::gop, grad(), NDIM, and refine().
GradBSHOperator()
static std::vector< std::shared_ptr< SeparatedConvolution<double,3> > > madness::GradBSHOperator (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating operator for convolution with grad(bsh) in 3D.
Returns a 3-vector containing the convolution operator for the x, y, and z components of grad(bsh)
References BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), c, d(), madness::BaseTensor::dim(), dir, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), madness::constants::pi, pi, and pow().
Referenced by madness::SCF::make_gradbsh_operators().
GradCoulombOperator()
static std::vector< std::shared_ptr< SeparatedConvolution<double,3> > > madness::GradCoulombOperator (World & world, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating operator for convolution with grad(1/r) in 3D.
Returns a 3-vector containing the convolution operator for the x, y, and z components of grad(1/r)
References BC_PERIODIC, c, madness::GFit< T, NDIM >::CoulombFit(), d(), madness::BaseTensor::dim(), dir, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), madness::constants::pi, pi, and pow().
Referenced by testgradG().
gradient_operator()
template<typename T , std::size_t NDIM> std::vector< std::shared_ptr< Derivative<T,NDIM> > > madness::gradient_operator (World & world, const BoundaryConditions< NDIM > & bc = FunctionDefaults<NDIM>::get_bc(), int k = FunctionDefaults<NDIM>::get_k())
Convenience function returning vector of derivative operators implementing grad ()
This will only work for BC_ZERO, BC_PERIODIC, BC_FREE and BC_ZERONEUMANN since we are not passing in any boundary functions.
References BC_DIRICHLET, BC_NEUMANN, d(), k, MADNESS_ASSERT, and NDIM.
GradSlaterOperator()
static std::vector< std::shared_ptr< SeparatedConvolution<double,3> > > madness::GradSlaterOperator (World & world, double gamma, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating operator for convolution with grad(e^{-*r}) in 3D.
Returns a 3-vector containing the convolution operator for the x, y, and z components of grad(e^{-*r}) maybe move to madness library (operator.h) at some point
References BC_PERIODIC, c, d(), madness::BaseTensor::dim(), dir, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), madness::constants::pi, pi, pow(), and madness::GFit< T, NDIM >::SlaterFit().
Referenced by madness::F12Potentials::F12Potentials().
hartree_product() [1/2]
template<typename T , std::size_t KDIM, std::size_t LDIM> Function<T,KDIM+LDIM> madness::hartree_product (const Function< T, KDIM > & left2, const Function< T, LDIM > & right2)
Performs a Hartree product on the two given low-dimensional functions.
References madness::Function< T, NDIM >::do_hartree_product(), madness::FunctionFactory< T, NDIM >::empty(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::get_impl(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, k, madness::Function< T, NDIM >::k(), madness::Function< T, NDIM >::nonstandard(), madness::Function< T, NDIM >::standard(), thresh, and madness::Function< T, NDIM >::world().
Referenced by main(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), test_adaptive_tree(), test_add(), test_compress(), test_convolution(), test_exchange(), test_hartree_product(), test_inner(), and test_recursive_application().
hartree_product() [2/2]
template<typename T , std::size_t KDIM, std::size_t LDIM, typename opT > Function<T,KDIM+LDIM> madness::hartree_product (const Function< T, KDIM > & left2, const Function< T, LDIM > & right2, const opT & op)
Performs a Hartree product on the two given low-dimensional functions.
References madness::Function< T, NDIM >::do_hartree_product(), madness::FunctionFactory< T, NDIM >::empty(), madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::get_impl(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, k, madness::Function< T, NDIM >::k(), madness::Function< T, NDIM >::nonstandard(), op(), print(), madness::World::rank(), madness::Function< T, NDIM >::standard(), thresh, and madness::Function< T, NDIM >::world().
has_zero_rank()
template<typename T > bool madness::has_zero_rank (const GenTensor< T > & g)
true if GenTensor has zero rank or no data
References g, and TT_NONE.
hash_combine()
template<class T > void madness::hash_combine (hashT & seed, const T & v) inline
Combine hash values.
This function uses the standard hash function.
Template Parameters
T The type to hash
Parameters
[in,out] seed The initial hash seed value
[in] v The value to be hashed
References madness::detail::combine_hash().
Referenced by madness::GaussianConvolution1DCache< Q >::get(), Key::Key(), and madness::Key< OPDIM >::rehash().
hash_range() [1/7]
template<class It > void madness::hash_range (hashT & seed, It first, It last) inline
Combine the hash values of an iterator range.
Template Parameters
It the iterator type
Parameters
[in,out] seed The initial hash seed value
[in] first The first element of the iterator range to be hashed
[in] last The end of the iterator range to be hashed
References madness::detail::combine_hash().
Referenced by hash_range(), and hash_value().
hash_range() [2/7]
template<class It > hashT madness::hash_range (It first, It last) inline
Combine the hash values of an iterator range.
Template Parameters
It the iterator type
Parameters
[in] first The first element of the iterator range to be hashed
[in] last The end of the iterator range to be hashed
Returns
The hashed iterator range
References hash_range().
hash_range() [3/7]
template<class T , std::size_t n> hashT madness::hash_range (const T(&) t[n]) inline
Combine the hash values of a C-style array.
Template Parameters
T The type to be hashed
n The size of the C-style array
Parameters
[in] t The array to be hashed
Returns
The hashed array value
References hash_range().
hash_range() [4/7]
template<class T , std::size_t n> void madness::hash_range (hashT & seed, const T(&) t[n]) inline
Combine the hash values of a C-style array.
Template Parameters
T The type to be hashed
n The size of the C-style array
Parameters
[in,out] seed The initial hash seed value
[in] t The array to be hashed
Note
This function uses std::hash
References hash_range().
hash_range() [5/7]
template<class T > std::enable_if<std::is_fundamental<T>::value >::type madness::hash_range (hashT & seed, const T * t, std::size_t n) inline
Combine the hash values of a pointer range.
Template Parameters
T The type to be hashed
Parameters
[in,out] seed The initial hash seed value
[in] t A pointer to the beginning of the range to be hashed
[in] n The number of elements to hashed
Note
May use heavily optimized hashword when n * sizeof(T) is multiple of sizeof(uint32_t) and presumably correctly aligned.
References hashlittle(), and hashword().
hash_range() [6/7]
template<class T > std::enable_if<!std::is_fundamental<T>::value >::type madness::hash_range (hashT & seed, const T * t, std::size_t n) inline
Combine the hash values of a pointer range.
Template Parameters
T The type to be hashed
Parameters
[in,out] seed The initial hash seed value
[in] t A pointer to the beginning of the range to be hashed
[in] n The number of elements to hashed
References hash_range().
hash_range() [7/7]
template<class T > hashT madness::hash_range (const T * t, std::size_t n) inline
Combine the hash values of a pointer range.
Template Parameters
T The type to be hashed
Parameters
t A pointer to the beginning of the range to be hashed
n The number of elements to hashed
Returns
The hashed pointer range value
References hash_range().
hash_value() [1/6]
template<typename T , std::size_t N> madness::hashT madness::hash_value (const std::array< T, N > & a)
Hash std::array with madness hash.
Template Parameters
T The type of data stored in the array.
N The size of the array.
Parameters
[in] a The array.
Returns
The hash.
References a, hash_range(), and N.
Referenced by madness::GaussianConvolution1DCache< Q >::get(), madness::Vector< int, 3 >::hash(), hash_value(), std::hash_value(), Key::Key(), madness::Hash< int >::operator()(), and madness::Key< OPDIM >::rehash().
hash_value() [2/6]
template<class T > std::enable_if<std::is_fundamental<T>::value && ((sizeof(T)%sizeof(uint32_t)) == 0), hashT>::type madness::hash_value (const T t) inline
Hash a single fundamental object.
Template Parameters
T The fundamental type
Parameters
t The object to hash
Returns
The hashed value
Note
Use heavily optimized hashword when sizeof(T) is multiple of sizeof(uint32_t) and presumably correctly aligned.
References hashword(), and u().
hash_value() [3/6]
template<class T > std::enable_if<std::is_fundamental<T>::value && ((sizeof(T)%sizeof(uint32_t)) != 0), hashT>::type madness::hash_value (const T t) inline
Hash a single fundamental object.
Template Parameters
T The fundamental type
Parameters
t The object to hash
Returns
The hashed value
References hashlittle(), and u().
hash_value() [4/6]
template<typename T > hashT madness::hash_value (const T * t) inline
Hash a pointer address.
Template Parameters
T The pointer type
Parameters
t The pointer to be hashed
Returns
The hashed value
References hash_value().
hash_value() [5/6]
template<typename T > std::enable_if<!(std::is_fundamental<T>::value || std::is_pointer<T>::value || std::is_array<T>::value), hashT>::type madness::hash_value (const T & t) inline
Hash a class object.
Template Parameters
T The class type
Parameters
t The object to hash
Returns
t.hash()
hash_value() [6/6]
template<typename T > hashT madness::hash_value (const std::basic_string< T > & t) inline
Hash a string.
Template Parameters
T The character type
Parameters
t The string to hash
Returns
The hashed value of the string
References hash_range().
imag() [1/4]
static double madness::imag (double x) inline
Referenced by madness::Znemo::compute_current_density(), madness::Znemo::compute_energy(), madness::Znemo::compute_kinetic_momentum(), compute_madelung_energy(), EwaldNuclearPotentialFunctor::do_G_sum_v2(), GMRES(), imag(), madness::VectorSpace< T, NDIM >::norm(), madness::imag_op< Q, NDIM >::operator()(), madness::detail::imagop< NDIM >::operator()(), plot_line_print_value(), plotvtk_data(), tensor_ximag(), and test_G_R_vectors().
imag() [2/4]
template<typename Q , int NDIM> Function<typename TensorTypeData<Q>::scalar_type,NDIM> madness::imag (const Function< Q, NDIM > & func)
References func(), and unary_op_coeffs().
imag() [3/4]
template<typename T , std::size_t NDIM> std::vector<Function<typename Tensor<T>::scalar_type,NDIM> > madness::imag (const std::vector< Function< T, NDIM > > & v, bool fence = true)
return the imaginary parts of the vector's function (if complex)
References imag(), and NDIM.
imag() [4/4]
template<std::size_t NDIM> Function<double,NDIM> madness::imag (const Function< double_complex, NDIM > & z, bool fence = true)
Returns a new function that is the imaginary part of the input.
References unary_op_coeffs().
init_tensor_lapack()
void madness::init_tensor_lapack ()
World/MRA initialization calls this before going multithreaded due to static data in dlamch.
References dlamch_(), e(), and slamch_().
Referenced by startup().
initialize() [1/3]
World & madness::initialize (int & argc, char **& argv, bool quiet = false)
Initialize the MADNESS runtime.
Call this once at the very top of your main program to initialize the MADNESS runtime. This function should be called instead of MPI_Init() or MPI_Init_thread().
Parameters
[in,out] argc Application argument count.
[in,out] argv Application argument values.
[in] quiet If false, will announce to std::cout on rank 0 when the runtime has been initialized.
Returns
A reference to the default World, which is constructed with MPI_COMM_WORLD.
References SafeMPI::COMM_WORLD, and quiet().
Referenced by initialize(), main(), test_G_R_vectors(), test_gaussian_num_coeffs(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), and testNavierStokes().
initialize() [2/3]
World & madness::initialize (int & argc, char **& argv, const MPI_Comm & comm, bool quiet = false)
Initialize the MADNESS runtime.
Call this once at the very top of your main program to initialize the MADNESS runtime. This function should be called instead of MPI_Init() or MPI_Init_thread().
Parameters
[in,out] argc Application argument count.
[in,out] argv Application argument values.
comm The MPI communicator that should be used to construct the World object.
[in] quiet If false, will announce to std::cout on rank 0 when the runtime has been initialized.
Returns
A reference to the World constructed with comm.
References initialize(), and quiet().
initialize() [3/3]
World & madness::initialize (int & argc, char **& argv, const SafeMPI::Intracomm & comm, bool quiet = false)
Initialize the MADNESS runtime.
Call this once at the very top of your main program to initialize the MADNESS runtime. This function should be called instead of MPI_Init() or MPI_Init_thread().
Parameters
[in,out] argc Application argument count.
[in,out] argv Application argument values.
comm The communicator that should be used to construct the World object.
[in] quiet If false, will announce to std::cout on rank 0 when the runtime has been initialized.
Returns
A reference to the World constructed with comm.
References SafeMPI::Intracomm::Barrier(), madness::RMI::begin(), madness::ThreadPool::begin(), begin_papi_measurement(), cpu_time(), madness::World::default_world, SafeMPI::Intracomm::Get_rank(), SafeMPI::Intracomm::Get_size(), madness::detail::WorldMpi::initialize(), initialize_papi(), MADNESS_EXCEPTION, quiet(), madness::ThreadBase::set_affinity(), madness::ThreadBase::set_affinity_pattern(), madness::ThreadPool::size(), and wall_time().
initialize_legendre_stuff()
void madness::initialize_legendre_stuff ()
Call this single threaded to initialize static data (used read only by multiple threads)
References nn1, and phi_norms.
Referenced by startup().
initialize_papi()
void madness::initialize_papi () inline
Referenced by initialize().
initialized()
bool madness::initialized ()
Check if the MADNESS runtime has been initialized (and not subsequently finalized).
Returns
true if madness::initialize had been called more recently than madness::finalize, false otherwise.
Referenced by madness::archive::archive_initialize_type_names(), SafeMPI::Is_initialized(), wall_time(), and madness::WorldObject< TestFutureForwarding >::~WorldObject().
inner() [1/5]
double madness::inner (const std::valarray< double > & bra, const std::valarray< double > & ket)
inner product for std::valarray
Referenced by madness::Znemo::analyze(), madness::SCF::analyze_vectors(), madness::TDHF::apply_G(), madness::Solver< T, NDIM >::apply_hf_exchange3(), madness::Solver< T, NDIM >::apply_hf_exchange4(), madness::SCF::apply_potential(), madness::Solver< T, NDIM >::apply_potential(), madness::projector_irrep::apply_symmetry_operators(), madness::Diamagnetic_potential_factor::bare_diamagnetic_potential(), Calculation::calc_optimal_coeffs(), madness::HartreeFock< T, NDIM >::calculate_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_ke_sp(), madness::DFT< T, NDIM >::calculate_ke_sp(), madness::Solver< T, NDIM >::calculate_kinetic_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::SRConf< T >::check_right_orthonormality(), ExcitingApp::compute_A_coeffs(), madness::guessfactory::compute_centroids(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_f12_correction_es(), madness::PNO::compute_cispd_f12_correction_gs(), madness::F12Potentials::compute_cispd_f12_energies(), madness::OEP::compute_E_first(), compute_energy(), madness::Znemo::compute_energy(), madness::Nemo::compute_energy(), madness::OEP::compute_energy(), madness::Nemo::compute_energy_regularized(), compute_energy_with_U(), madness::OEP::compute_exchange_energy_conv(), madness::OEP::compute_exchange_energy_vir(), madness::OEP::compute_fock_diagonal_elements(), madness::Zcis::compute_fock_pt(), madness::F12Potentials::compute_fQc_integrals_ij(), madness::F12Potentials::compute_fQg_integral(), madness::F12Potentials::compute_fQg_integrals(), madness::F12Potentials::compute_fQU_integrals(), compute_frequencies(), madness::MolecularOptimizer::compute_frequencies(), madness::NemoBase::compute_gradient(), madness::Nemo::compute_IR_intensities(), madness::OEP::compute_kinetic_energy(), madness::Znemo::compute_kinetic_momentum(), madness::Znemo::compute_linear_moment(), madness::Znemo::compute_magnetic_potential_expectation(), madness::Diamagnetic_potential_factor::compute_nabla_R_div_R(), compute_R2f2_psi(), compute_reduced_mass(), madness::MolecularOptimizer::compute_reduced_mass(), madness::Zcis::compute_residuals(), madness::Znemo::compute_residuals(), madness::Diamagnetic_potential_factor::compute_U2(), converge(), converge2s(), madness::PotentialManager::core_projection(), madness::SCF::core_projection(), madness::PotentialManager::core_projector_derivative(), madness::SCF::core_projector_derivative(), madness::Diamagnetic_potential_factor::custom_factor(), madness::Znemo::custom_guess(), madness::SCF::derivatives(), dnuclear_anchor_test(), madness::Derivative< T, NDIM >::do_diff2b(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), doit(), energy(), madness::Diamagnetic_potential_factor::factor_with_phase(), fixphases(), madness::TensorTrain< T >::fusedim(), madness::SRConf< T >::general_transform(), general_transform(), madness::SCF::get_fock_transformation(), madness::Solver< T, NDIM >::gram_schmidt(), madness::Nemo::hessian(), madness::QuasiNewton::hessian_update_bfgs(), QuasiNewton::hessian_update_bfgs(), madness::QuasiNewton::hessian_update_sr1(), QuasiNewton::hessian_update_sr1(), inner(), iterate(), madness::Zcis::iterate(), madness::Znemo::iterate(), iterate_excite(), iterate_ground(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), iterate_xy(), kinetic_energy_matrix_slow(), madness::SCF::localize_boys(), madness::SCF::localize_new(), main(), madness::TDHF::make_cis_matrix(), madness::TwoElectronInterface< double, 6 >::make_coeff(), madness::Nemo::make_incomplete_hessian(), madness::Nemo::make_incomplete_hessian_response_part(), madness::TDHF::make_old_guess(), madness::TDHF::make_overlap_matrix(), madness::TDHF::make_perturbed_fock_matrix(), Calculation::make_reference(), madness::TDHF::make_virtuals(), madness::CCPairFunction::make_xy_u(), madness::EigSolver< T, NDIM >::matrix_element(), madness::SCF::matrix_exponential(), matrix_exponential(), madness::Solver< T, NDIM >::matrix_exponential(), madness::AtomicBasisSet::modify_dmat_psp(), moments(), madness::EigSolver< T, NDIM >::multi_solve(), madness::QuasiNewton::new_search_direction(), QuasiNewton::new_search_direction(), madness::MolecularOptimizer::new_search_direction2(), madness::FunctionImpl< Q, NDIM >::NScoeffs2values(), nuclear_anchor_test(), madness::R_times_arg_div_R::operator()(), madness::spherical_box< NDIM >::operator()(), madness::harmonic_potential_boxed::operator()(), madness::Coulomb::operator()(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), madness::Nuclear::operator()(), madness::Lz::operator()(), madness::DNuclear::operator()(), madness::Exchange< double, 3 >::operator()(), madness::MolecularOptimizer::optimize_conjugate_gradients(), madness::MolecularOptimizer::optimize_quasi_newton(), ortho3(), ortho5(), orthogonalize(), MiniDFT::orthogonalize(), madness::Zcis::orthonormalize(), orthonormalize_symmetric(), madness::TDHF::oscillator_strength_length(), madness::TDHF::oscillator_strength_velocity(), madness::PNO::pno_compress(), print_info(), madness::EigSolver< T, NDIM >::print_matrix_elements(), print_stats(), madness::CCPairFunction::project_out_decomposed(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), propagate(), madness::SCF::propagate(), Q3(), Q3(), madness::Solver< T, NDIM >::Q3(), madness::TensorTrain< T >::reconstruct(), reconstruct_psi(), remove_external_dof(), madness::MolecularOptimizer::remove_external_dof(), madness::Convolution1D< Q >::rnlij(), madness::Molecule::rotate(), madness::CCPairFunction::self_overlap(), madness::EigSolver< T, NDIM >::solve(), madness::SCF::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), madness::PNO::t_solve(), TENSOR_RESULT_TYPE(), test2(), Test7(), test_adaptive_tree(), test_cholesky(), madness::Znemo::test_compute_current_density(), test_convolution(), test_coulomb(), madness::Diamagnetic_potential_factor::test_factor(), test_gelss(), test_gesv(), test_he_potential(), test_inner(), test_inverse(), test_kinetic(), madness::Znemo::test_landau_wave_function(), test_modified(), madness::OEP::test_oep(), test_qr(), test_recursive_application(), test_rr_cholesky(), madness::Diamagnetic_potential_factor::test_scalar_potentials(), test_slater_exchange(), test_syev(), test_sygv(), test_two_scale_coefficients(), test_U_el(), madness::Znemo::test_U_potentials(), test_wannier(), test_XCOperator(), madness::SRConf< T >::transform(), transform(), transform_dir(), madness::PNO::transform_pairs(), madness::TensorTrain< T >::truncate(), madness::TensorTrain< T >::two_mode_representation(), madness::NonlinearSolverND< NDIM >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::PNO::update_pno(), and madness::FunctionImpl< Q, NDIM >::values2NScoeffs().
inner() [2/5]
template<typename T , std::size_t N> T madness::inner (const Vector< T, N > & l, const Vector< T, N > & r)
compute the inner product two Vectors.
Do an inner product of l and r and return the result in a new Vector.
Template Parameters
T The Vector element type.
N The Vector size.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand Vector.
Returns
the inner product, where result==\sum_i(l[i]*r[i]).
References N.
inner() [3/5]
template<typename T , typename R , std::size_t NDIM> Tensor< TENSOR_RESULT_TYPE(T, R) > madness::inner (World & world, const std::vector< Function< T, NDIM > > & f, const std::vector< Function< R, NDIM > > & g)
Computes the element-wise inner product of two function vectors - q(i) = inner(f[i],g[i])
References compress(), f, madness::WorldGopInterface::fence(), madness::WorldTaskQueue::fence(), g, madness::World::gop, m, MADNESS_CHECK, PROFILE_BLOCK, madness::Tensor< T >::ptr(), madness::WorldGopInterface::sum(), and madness::World::taskq.
inner() [4/5]
template<typename T , typename R , std::size_t NDIM> Tensor< TENSOR_RESULT_TYPE(T, R) > madness::inner (World & world, const Function< T, NDIM > & f, const std::vector< Function< R, NDIM > > & g)
Computes the inner product of a function with a function vector - q(i) = inner(f,g[i])
References compress(), f, madness::WorldGopInterface::fence(), madness::WorldTaskQueue::fence(), g, madness::World::gop, PROFILE_BLOCK, madness::Tensor< T >::ptr(), madness::WorldGopInterface::sum(), and madness::World::taskq.
inner() [5/5]
return f madness::inner (g)
inner_adaptive()
return f madness::inner_adaptive (func)
interleave_rows()
template<typename T > DistributedMatrix< T > madness::interleave_rows (const DistributedMatrix< T > & a, const DistributedMatrix< T > & b)
Generates a distributed matrix with rows of a and b interleaved.
I.e., the even rows of the result will be rows of a , and the odd rows those of b .
The matrices a and b must have the same dimensions and be identically distributed. The result will have a doubled column dimension and column tile size. The row dimension is unchanged.
Parameters
[in] a The matrix providing even rows of the result
[in] b The matrix providing odd rows of the result
Returns
The result matrix
References _(), ___, a, b, c, and MADNESS_CHECK.
inverse() [1/2]
template<typename T > Tensor< T > madness::inverse (const Tensor< T > & a_in)
invert general square matrix A
References a, copy(), dgetrf_(), dgetri_(), mask_info(), madness::Tensor< T >::ptr(), and TENSOR_ASSERT.
Referenced by madness::projector_irrep::apply_symmetry_operators(), madness::Molecule::identify_point_group(), orthonormalize_cd(), madness::PNO::orthonormalize_cholesky(), orthonormalize_rrcd(), and test_inverse().
inverse() [2/2]
template Tensor<double> madness::inverse (const Tensor< double > & A)
KAIN()
template<typename T > Tensor<T> madness::KAIN (const Tensor< T > & Q, double rcond = 1e-12)
Solves non-linear equation using KAIN (returns coefficients to compute next vector)
The Krylov-accelerated inexact-Newton method employs directional derivatives to estimate the Jacobian in the subspace and separately computes updates in the subspace and its complement.
We wish to solve the non-linear equations where and are vectors of the same dimension (e.g., consider both being MADNESS functions).
Define the following matrices and vector (with and denoting previous iterations in the Krylov subspace and the current iteration):
The subspace equation is of dimension (assuming iterations are indexed from zero) and is given by
The interior and exterior updates may be combined into one simple expression as follows. First, define an additional element of the solution vector
and then the new vector (guess for next iteration) is given by
To employ the solver, each iteration
Compute the additional row and column of the matrix that is the inner product between solution vectors () and residuals ().
Call this routine to compute the coefficients and from these compute the next solution vector
Employ step restriction or line search as necessary to ensure stable/robust solution.
Parameters
[in] Q The matrix of inner products between subspace vectors and residuals.
[in] rcond Threshold for discarding small singular values in the subspace equations.
Returns
Vector for computing next solution vector
References b, c, madness::BaseTensor::dim(), gelss(), L, and m.
Referenced by check_linear_dependence(), main(), madness::NonlinearSolverND< NDIM >::update(), madness::XNonlinearSolver< T, C, Alloc >::update(), madness::SCF::update_response_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), and madness::SCF::update_subspace().
legendre_polynomials()
void madness::legendre_polynomials (double x, long order, double * p)
Evaluate the Legendre polynomials up to the given order at x in [-1,1].
p should be an array of order+1 elements.
References nn1, and p().
Referenced by gauss_legendre_numeric(), and legendre_scaling_functions().
legendre_scaling_functions()
void madness::legendre_scaling_functions (double x, long k, double * p)
Evaluate the first k Legendre scaling functions.
p should be an array of k elements.
References k, legendre_polynomials(), p(), and phi_norms.
Referenced by madness::FunctionCommonData< Q, NDIM >::_init_quadrature(), madness::FunctionImpl< Q, NDIM >::eval_cube(), madness::GenericConvolution1D< Q, opT >::Shmoo::operator()(), madness::FunctionImpl< Q, NDIM >::phi_for_mul(), and madness::GaussianConvolution1D< Q >::rnlp().
load()
template<class T , std::size_t NDIM> void madness::load (Function< T, NDIM > & f, const std::string name)
References f.
Referenced by dostuff(), madness::TDHF::get_tda_potential(), main(), madness::Znemo::read_explicit_guess_functions(), madness::PNO::solve_cispd(), and madness::OEP::test_oep().
load_coeffs()
void madness::load_coeffs (World & world, const char * dir)
Collective routine to load and cache twoscale & autorrelation coefficients.
Only process rank 0 will access the files.
References _cread, autocorr_filename, madness::WorldGopInterface::broadcast(), cache, dir, madness::twoscale_cache_class::g0, madness::twoscale_cache_class::g1, madness::World::gop, madness::twoscale_cache_class::h0, madness::twoscale_cache_class::h1, k, kmax, kmax_autoc, kread, loaded, madness::Tensor< T >::ptr(), madness::World::rank(), read_data(), read_twoscale(), and twoscale_filename.
Referenced by startup().
load_function()
template<typename T , size_t NDIM> void madness::load_function (World & world, std::vector< Function< T, NDIM > > & f, const std::string name)
load a vector of functions
References f, print(), and madness::World::rank().
Referenced by madness::Zcis::compare_to_file(), madness::PNO::load_pnos(), main(), madness::TDHF::make_virtuals(), test_adaptive_tree(), and test_multiply().
load_quadrature()
void madness::load_quadrature (World & world, const char * dir)
Collective routine to pre-load and cache the quadrature points and weights.
Only process rank 0 will access the file.
References madness::WorldGopInterface::broadcast(), data_is_read, dir, madness::WorldGopInterface::fence(), filename, madness::World::gop, max_npt, points, madness::World::rank(), read_data(), and weights.
Referenced by startup().
lookup_func()
static xc_func_type* madness::lookup_func (const std::string & name, bool polarized) static
References lookup_name(), and make_func().
lookup_id()
static std::string madness::lookup_id (const int id) static
lookup_name()
static int madness::lookup_name (const std::string & name) static
Referenced by lookup_func().
lowercase()
std::string madness::lowercase (const std::string & s)
Referenced by create_nuclear_correlation_factor(), and symbol_to_atomic_number().
lq() [1/2]
template<typename T > void madness::lq (Tensor< T > & A, Tensor< T > & R)
compute the LQ decomposition of the matrix A = L Q
LQ decomposition.
Parameters
[in,out] A on entry the (n,m) matrix to be decomposed on exit the Q matrix
[out] R the (n,n) matrix L (square form)
Todo:
MGR: Check this.
References lq_result(), m, R, and TENSOR_ASSERT.
Referenced by test_qr().
lq() [2/2]
template void madness::lq (Tensor< double > & A, Tensor< double > & L)
lq_result() [1/2]
template<typename T > void madness::lq_result (Tensor< T > & A, Tensor< T > & R, Tensor< T > & tau, Tensor< T > & work, bool do_qr)
compute the LQ decomposition of the matrix A = L Q
LQ decomposition.
Parameters
[in,out] A on entry the (n,m) matrix to be decomposed on exit the Q matrix
[in,out] R the (n,n) matrix L (square form)
Todo:
MGR: Check this.
Parameters
[in] do_qr do QR instead of LQ
References dgeqrf_(), dorgqr_(), k, m, mask_info(), madness::Tensor< T >::ptr(), R, madness::BaseTensor::size(), and TENSOR_ASSERT.
Referenced by lq(), qr(), and madness::TensorTrain< T >::truncate().
lq_result() [2/2]
template void madness::lq_result (Tensor< double > & A, Tensor< double > & R, Tensor< double > & tau, Tensor< double > & work, bool do_qr)
make_atom_vec() [1/2]
std::vector< atom_information< 3 > > madness::make_atom_vec (const Molecule & molecule, double R1_, double R2_)
Creates vector of atom_information for the given molecule
Parameters
[in] molecule the molecule
[out] the vector containing the atom_information for each atom in the molecule
References madness::atom_information< NDIM >::charge, madness::atom_information< NDIM >::coord, madness::Molecule::get_atoms(), molecule, madness::atom_information< NDIM >::R1, madness::atom_information< NDIM >::R2, and slater_radius().
Referenced by madness::ACParameters< NDIM >::initialize(), and make_atom_vec().
make_atom_vec() [2/2]
std::vector< atom_information< 3 > > madness::make_atom_vec (const std::string & input)
Creates vector of atom_information via input file (calls make_atom_vec(const Molecule& molecule))
Parameters
[in] input file with geometry of molecule
[out] the vector containing the atom_information for each atom in the molecule
References make_atom_vec(), and molecule.
make_exp()
static Function<double_complex,3> madness::make_exp (double t, const Function< double, 3 > & v) static
References expV(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::unaryop().
Referenced by madness::SCF::iterate_trotter(), propagate(), test_chin_chen(), and test_trotter().
make_func()
static xc_func_type* madness::make_func (int id, bool polarized) static
References func().
Referenced by lookup_func().
map_and_mirror()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::map_and_mirror (const Function< T, NDIM > & f, const std::vector< long > & map, const std::vector< long > & mirror, bool fence = true)
This is replaced with mirror(map(f)), optional fence.
first map then mirror! mirror is similar to mapdim, but maps from x to -x, y to -y, and so on Example: mirror a 3d function on the xy plane: mirror={1,1,-1} Example: c4 rotation of a 3d function around the z axis: x->y, y->-x, z->z: map(1,0,2); mirror(-1,1,1)
Parameters
[in] map array holding dimensions
[in] mirror array of -1 and 1, corresponding to mirror or not
References f, madness::Function< T, NDIM >::map_and_mirror(), mirror(), and PROFILE_FUNC.
Referenced by madness::pg_operator::operator()().
mapdim()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::mapdim (const Function< T, NDIM > & f, const std::vector< long > & map, bool fence = true)
Generate a new function by reordering dimensions ... optional fence.
You provide an array of dimension NDIM that maps old to new dimensions according to
newdim = mapdim[olddim]
Works in either scaling function or wavelet basis.
Would be easy to modify this to also change the procmap here if desired but presently it uses the same procmap as f.
References f, madness::Function< T, NDIM >::mapdim(), and PROFILE_FUNC.
Referenced by swap_particles(), and madness::CCPairFunction::swap_particles_pure().
mask1()
double madness::mask1 (double x) inline
Referenced by mask3(), and mask3().
mask3()
static double madness::mask3 (const coordT & ruser) static
References lo, mask1(), and user_to_sim().
Referenced by madness::SCF::set_protocol(), and Calculation::set_protocol().
mask_info()
static void madness::mask_info (integer & info) static
Referenced by cholesky(), gelss(), geqp3_result(), gesv(), inverse(), lq_result(), orgqr(), rr_cholesky(), svd(), svd_result(), syev(), and sygv().
matrix_inner() [1/3]
template<typename T , std::size_t NDIM> void madness::matrix_inner (DistributedMatrix< T > & A, const std::vector< Function< T, NDIM > > & f, const std::vector< Function< T, NDIM > > & g, bool sym = false)
References f, g, m, MADNESS_ASSERT, and P.
Referenced by madness::SCF::analyze_vectors(), madness::GTHPseudopotential< Q >::apply_potential(), madness::projector_irrep::apply_symmetry_operators(), madness::Solver< T, NDIM >::build_fock_matrix(), Calculation::calc_optimal_coeffs(), madness::Zcis::canonicalize(), madness::TDHF::canonicalize(), madness::PNO::check_orthonormality(), madness::PNO::compute_cispd_correction_es(), madness::PNO::compute_cispd_correction_gs(), madness::PNO::compute_cispd_fluctuation_matrix(), madness::Nemo::compute_cphf_parallel_term(), madness::PNO::compute_fluctuation_matrix(), madness::Nemo::compute_fock_matrix(), madness::F12Potentials::compute_fQg_integrals(), madness::F12Potentials::compute_fQU_integrals(), madness::PNO::compute_projected_mp2_energies(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::F12Potentials::compute_uijab_integrals(), madness::Znemo::compute_vmat(), madness::F12Potentials::compute_xyab_integrals(), diag_and_transform(), madness::SCF::diag_fock_matrix(), madness::SCF::dipole_matrix_elements(), distributed_localize_PM(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), doit(), MiniDFT::doit(), exchange_anchor_test(), fixphases(), hamiltonian_matrix(), madness::Znemo::hcore_guess(), madness::SCF::initial_guess(), initial_guess(), madness::Solver< T, NDIM >::initial_guess(), madness::Znemo::iterate(), madness::PNO::iterate_pairs_internal(), madness::Kinetic< double, 3 >::kinetic_energy_matrix(), kinetic_energy_matrix(), MiniDFT::kinetic_energy_matrix(), madness::SCF::kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), Calculation::load_mos(), madness::SCF::localize_boys(), madness::SCF::localize_new(), main(), madness::TDHF::make_cis_matrix(), madness::SCF::make_fock_matrix(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), matrix_inner(), madness::Projector< double_complex, NDIM >::operator()(), madness::DerivativeOperator< T, NDIM >::operator()(), BoysLocalization::operator()(), madness::Coulomb::operator()(), madness::Nuclear::operator()(), madness::Lz::operator()(), madness::DNuclear::operator()(), madness::Exchange< double, 3 >::operator()(), orth(), madness::NemoBase::orthonormalize(), madness::SCF::orthonormalize(), madness::Solver< T, NDIM >::orthonormalize(), orthonormalize_canonical(), orthonormalize_cd(), madness::PNO::orthonormalize_cholesky(), orthonormalize_rrcd(), orthonormalize_symmetric(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), madness::Solver< T, NDIM >::print_potential_matrix_eigs(), madness::MolecularOrbitals< T, NDIM >::project_ao(), madness::SCF::restart_aos(), madness::SCF::save_mos(), madness::MolecularOrbitals< T, NDIM >::save_restartaodata(), madness::Nemo::solve(), madness::SCF::solve(), madness::Solver< T, NDIM >::solve(), madness::OEP::solve_oep(), test_inner(), test_orthogonalization(), and madness::SCF::twoint().
matrix_inner() [2/3]
template<typename T , std::size_t NDIM> DistributedMatrix<T> madness::matrix_inner (const DistributedMatrixDistribution & d, const std::vector< Function< T, NDIM > > & f, const std::vector< Function< T, NDIM > > & g, bool sym = false)
References d(), f, g, m, MADNESS_ASSERT, matrix_inner(), P, and PROFILE_FUNC.
matrix_inner() [3/3]
template<typename T , typename R , std::size_t NDIM> Tensor< TENSOR_RESULT_TYPE(T, R) > madness::matrix_inner (World & world, const std::vector< Function< T, NDIM > > & f, const std::vector< Function< R, NDIM > > & g, bool sym = false)
Computes the matrix inner product of two function vectors - q(i,j) = inner(f[i],g[j])
For complex types symmetric is interpreted as Hermitian.
The current parallel loop is non-optimal but functional.
References compress(), f, madness::WorldGopInterface::fence(), g, madness::World::gop, madness::FunctionImpl< T, NDIM >::inner_local(), madness::Tensor< T >::ptr(), and madness::WorldGopInterface::sum().
matrix_inner_old()
template<typename T , typename R , std::size_t NDIM> Tensor< TENSOR_RESULT_TYPE(T,R) > madness::matrix_inner_old (World & world, const std::vector< Function< T, NDIM > > & f, const std::vector< Function< R, NDIM > > & g, bool sym = false)
Computes the matrix inner product of two function vectors - q(i,j) = inner(f[i],g[j])
For complex types symmetric is interpreted as Hermitian.
The current parallel loop is non-optimal but functional.
References compress(), conj(), f, madness::WorldGopInterface::fence(), g, madness::World::gop, m, MADNESS_ASSERT, PROFILE_BLOCK, madness::Tensor< T >::ptr(), and madness::WorldGopInterface::sum().
Referenced by test_inner().
mirror()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::mirror (const Function< T, NDIM > & f, const std::vector< long > & mirrormap, bool fence = true)
Generate a new function by mirroring within the dimensions .. optional fence.
similar to mapdim
Parameters
[in] mirror array with -1 and 1, corresponding to mirror this dimension or not
References f, madness::Function< T, NDIM >::mirror(), and PROFILE_FUNC.
Referenced by map_and_mirror(), madness::FunctionImpl< Q, NDIM >::map_and_mirror(), and madness::pg_operator::operator()().
mTxm() [1/2]
template<typename T , typename Q , typename S > static void madness::mTxm (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
References a, b, c, and mTxm_reference().
Referenced by fast_transform(), and inner_result().
mTxm() [2/2]
template<> void madness::mTxm (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT c, const double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b) inline
Matrix transpose * matrix (hand unrolled version)
References a, b, c, k, and p().
mTxm_reference()
template<typename T , typename Q , typename S > static void madness::mTxm_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
Matrix += Matrix transpose * matrix ... reference implementation (slow but correct)
References a, b, c, and k.
Referenced by mTxm().
mTxmq()
template<typename aT , typename bT , typename cT > void madness::mTxmq (long dimi, long dimj, long dimk, cT *MADNESS_RESTRICT c, const aT * a, const bT * b, long ldb = -1)
References a, b, c, and mTxmq_reference().
Referenced by madness::SeparatedConvolution< T, NDIM >::apply_transformation(), madness::SeparatedConvolution< T, NDIM >::apply_transformation2(), fast_transform(), and main().
mTxmq_padding()
template<typename aT , typename bT , typename cT > void madness::mTxmq_padding (long dimi, long dimj, long dimk, long ext_b, cT * c, const aT * a, const bT * b)
References a, b, c, k, and malloc().
Referenced by madness::SeparatedConvolution< T, NDIM >::apply_transformation(), and fast_transform().
mTxmq_reference()
template<typename aT , typename bT , typename cT > void madness::mTxmq_reference (long dimi, long dimj, long dimk, cT *MADNESS_RESTRICT c, const aT * a, const bT * b, long ldb = -1)
Matrix = Matrix transpose * matrix ... slow reference implementation.
This routine does C=AT*B whereas mTxm does C=C+AT*B.
c(i,j) = sum(k) a(k,i)*b(k,j)  <------ does not accumulate into C
ldb is the last dimension of b in C storage (the leading dimension in fortran storage). It is here to accomodate multiplying by a matrix stored with ldb>dimj which happens in madness when transforming with low rank matrices. A matrix in dense storage has ldb=dimj which is the default for backward compatibility.
References a, b, c, k, and MADNESS_ASSERT.
Referenced by mTxmq().
mTxmT() [1/2]
template<typename T , typename Q , typename S > static void madness::mTxmT (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
References a, b, c, and mTxmT_reference().
Referenced by inner_result().
mTxmT() [2/2]
template<> void madness::mTxmT (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT csave, const double *MADNESS_RESTRICT asave, const double *MADNESS_RESTRICT b) inline
Matrix transpose * matrix transpose (hand tiled and unrolled)
References a, b, c, k, q(), and sum().
mTxmT_reference()
template<typename T , typename Q , typename S > static void madness::mTxmT_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
Matrix += Matrix transpose * matrix transpose reference implementation (slow but correct)
References a, b, c, and k.
Referenced by mTxmT().
mul() [1/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::mul (World & world, const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & v, const unsigned int blk = 1, const bool fence = true)
Multiplies a function against a vector of functions — q[i] = a * v[i].
References a, madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, reconstruct(), and vmulXX().
mul() [2/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::mul (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true, unsigned int blk = 1)
Multiplies two vectors of functions q[i] = a[i] * b[i].
References a, b, madness::WorldGopInterface::fence(), madness::World::gop, mul(), PROFILE_BLOCK, q(), and reconstruct().
mul() [3/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::mul (World & world, const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & v, bool fence = true)
Multiplies a function against a vector of functions — q[i] = a * v[i].
References a, madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, reconstruct(), and vmulXX().
mul() [4/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::mul (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true)
Multiplies two vectors of functions q[i] = a[i] * b[i].
References a, b, madness::WorldGopInterface::fence(), madness::World::gop, mul(), PROFILE_BLOCK, q(), and reconstruct().
mul() [5/7]
template<typename Q , typename T , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(Q,T),NDIM> madness::mul (const Q alpha, const Function< T, NDIM > & f, bool fence = true)
Returns new function equal to alpha*f(x) with optional fence.
References alpha, f, madness::Function< T, NDIM >::get_impl(), PROFILE_FUNC, madness::Function< T, NDIM >::set_impl(), and VERIFY_TREE.
Referenced by KPeriodicBSHOperator::apply(), apply_potential(), madness::Nemo::compute_all_cphf(), madness::Nemo::compute_cphf_parallel_term(), madness::Nemo::compute_energy(), madness::Nemo::compute_energy_regularized(), madness::PNO::compute_fluctuation_matrix(), madness::Nemo::compute_fock_matrix(), madness::F12Potentials::compute_fQc_integrals_ij(), madness::Nemo::compute_nemo_potentials(), madness::Zcis::compute_potentials(), madness::F12Potentials::compute_regularized_fluctuation_matrix(), madness::PNO::compute_V_aj_i(), cross(), madness::CCPairFunction::dirac_convolution_decomposed(), dot(), madness::Exchange< double, 3 >::Exchange(), fixphases(), madness::TDHF::get_tda_potential(), madness::Nemo::hessian(), madness::CC2::iterate_singles(), madness::Nemo::kinetic_energy_potential(), madness::Nemo::localize(), madness::TDHF::make_bra(), madness::Nemo::make_density(), madness::TDHF::make_mo_bra(), madness::TDHF::make_perturbed_fock_matrix(), mul(), madness::Coulomb::operator()(), madness::DNuclear::operator()(), madness::CCConvolutionOperator::operator()(), operator*(), madness::Nemo::solve(), madness::Nemo::solve_cphf(), test_math(), and madness::HartreeFock< T, NDIM >::value().
mul() [6/7]
template<typename Q , typename T , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(Q,T),NDIM> madness::mul (const Function< T, NDIM > & f, const Q alpha, bool fence = true)
Returns new function equal to f(x)*alpha with optional fence.
References alpha, f, mul(), and PROFILE_FUNC.
mul() [7/7]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R),NDIM> madness::mul (const Function< L, NDIM > & left, const Function< R, NDIM > & right, bool fence = true)
Same as operator* but with optional fence and no automatic reconstruction.
References mul_sparse().
mul_sparse() [1/3]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::mul_sparse (World & world, const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & v, const double tol, const bool fence = true, const unsigned int blk = 1)
Multiplies a function against a vector of functions using sparsity of a and v[i] — q[i] = a * v[i].
References a, madness::WorldGopInterface::fence(), madness::World::gop, norm_tree(), PROFILE_BLOCK, reconstruct(), and vmulXX().
mul_sparse() [2/3]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::mul_sparse (World & world, const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & v, double tol, bool fence = true)
Multiplies a function against a vector of functions using sparsity of a and v[i] — q[i] = a * v[i].
References a, madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, reconstruct(), and vmulXX().
mul_sparse() [3/3]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R),NDIM> madness::mul_sparse (const Function< L, NDIM > & left, const Function< R, NDIM > & right, double tol, bool fence = true)
Sparse multiplication — left and right must be reconstructed and if tol!=0 have tree of norms already created.
References madness::Function< T, NDIM >::get_impl(), madness::Function< T, NDIM >::is_compressed(), MADNESS_ASSERT, PROFILE_FUNC, madness::Function< T, NDIM >::set_impl(), madness::Function< T, NDIM >::verify(), VERIFY_TREE, and madness::Function< T, NDIM >::verify_tree().
Referenced by madness::SCF::analyze_vectors(), MiniDFT::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential(), madness::SCF::apply_potential(), madness::Solver< T, NDIM >::apply_potential(), madness::SCF::apply_potential_response(), madness::GTHPseudopotential< Q >::apply_potential_simple(), madness::SCF::calc_dipole_mo(), Calculation::calc_optimal_coeffs(), madness::SCF::calc_xc_function(), madness::F12Potentials::compute_fQg_integrals(), madness::F12Potentials::compute_fQU_integrals(), Calculation::compute_residuals(), madness::F12Potentials::compute_xyab_integrals(), madness::F12Potentials::convolve_with_fU(), madness::F12Potentials::convolve_with_nonlocal_U(), madness::F12Potentials::convolve_with_U(), madness::SCF::dipole_matrix_elements(), madness::SCF::initial_guess(), madness::SCF::iterate_trotter(), madness::SCF::localize_boys(), Calculation::make_reference(), Calculation::make_Upsi(), mul(), BoysLocalization::operator()(), madness::XCOperator::operator()(), and madness::SCF::twoint().
multi_to_multi_op_values()
template<typename T , typename opT , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::multi_to_multi_op_values (const opT & op, const std::vector< Function< T, NDIM > > & vin, const bool fence = true)
apply op on the input vector yielding an output vector of functions
Parameters
[in] op the operator working on vin
[in] vin vector of input Functions; needs to be refined to common level!
Returns
vector of output Functions vout = op(vin)
References MADNESS_ASSERT, madness::Function< T, NDIM >::multi_to_multi_op_values(), op(), and madness::Function< T, NDIM >::set_impl().
Referenced by madness::XCOperator::apply_xc_kernel(), madness::XCOperator::make_xc_potential(), and test_multi_to_multi_op().
multiop_values()
template<typename T , typename opT , std::size_t NDIM> Function<T,NDIM> madness::multiop_values (const opT & op, const std::vector< Function< T, NDIM > > & vf)
References madness::Function< T, NDIM >::multiop_values(), op(), and madness::Function< T, NDIM >::set_impl().
multiply()
template<typename T , std::size_t NDIM, std::size_t LDIM> Function<T,NDIM> madness::multiply (const Function< T, NDIM > f, const Function< T, LDIM > g, const int particle, const bool fence = true)
multiply a high-dimensional function with a low-dimensional function
Parameters
[in] f NDIM function of 2 particles: f=f(1,2)
[in] g LDIM function of 1 particle: g=g(1) or g=g(2)
[in] particle if g=g(1) or g=g(2)
Returns
h(1,2) = f(1,2) * g(p)
References f, madness::WorldGopInterface::fence(), g, madness::Function< T, NDIM >::get_impl(), madness::World::gop, MADNESS_ASSERT, madness::FunctionImpl< T, NDIM >::make_redundant(), NDIM, madness::Function< T, NDIM >::nonstandard(), madness::Function< T, NDIM >::set_impl(), madness::Function< T, NDIM >::standard(), madness::FunctionImpl< T, NDIM >::undo_redundant(), and madness::Function< T, NDIM >::world().
Referenced by madness::FunctionImpl< Q, NDIM >::assemble_coefficients(), madness::CCConvolutionOperator::operator()(), test_exchange(), and test_multiply().
mxm() [1/2]
template<typename T , typename Q , typename S > static void madness::mxm (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
References a, b, c, and mxm_reference().
Referenced by inner_result().
mxm() [2/2]
template<> void madness::mxm (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT c, const double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b) inline
Matrix * matrix (hand unrolled version)
References a, b, c, k, and p().
mxm_reference()
template<typename T , typename Q , typename S > static void madness::mxm_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
Matrix += Matrix * matrix reference implementation (slow but correct)
References a, b, c, and k.
Referenced by mxm().
mxmT() [1/2]
template<typename T , typename Q , typename S > static void madness::mxmT (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
References a, b, c, and mxmT_reference().
Referenced by madness::FunctionImpl< Q, NDIM >::do_inner_localX(), and inner_result().
mxmT() [2/2]
template<> void madness::mxmT (long dimi, long dimj, long dimk, double *MADNESS_RESTRICT c, const double *MADNESS_RESTRICT a, const double *MADNESS_RESTRICT b) inline
Matrix * matrix transpose (hand unrolled version)
References a, b, c, k, and sum().
mxmT_reference()
template<typename T , typename Q , typename S > static void madness::mxmT_reference (long dimi, long dimj, long dimk, T *MADNESS_RESTRICT c, const Q *MADNESS_RESTRICT a, const S *MADNESS_RESTRICT b) inline static
Matrix += Matrix * matrix transpose ... reference implementation (slow but correct)
References a, b, c, k, and sum().
Referenced by mxmT().
my_conj_transpose() [1/4]
STATIC Tensor<float> madness::my_conj_transpose (Tensor< float > a)
References a, and transpose().
Referenced by test_cholesky(), test_rr_cholesky(), and test_sygv().
my_conj_transpose() [2/4]
STATIC Tensor<double> madness::my_conj_transpose (Tensor< double > a)
References a, and transpose().
my_conj_transpose() [3/4]
STATIC Tensor<float_complex> madness::my_conj_transpose (Tensor< float_complex > a)
References a, and conj_transpose().
my_conj_transpose() [4/4]
STATIC Tensor<double_complex> madness::my_conj_transpose (Tensor< double_complex > a)
References a, and conj_transpose().
myusleep()
static void madness::myusleep (unsigned int us) inline static
Sleep or spin for specified number of microseconds.
Wrapper to ensure desired behavior across various platforms.
Parameters
[in] us The number of microseconds.
References cpu_relax(), cpu_time(), and e().
Referenced by madness::ThreadPool::await(), madness::RMI::begin(), madness::RMI::RmiTask::exit(), madness::RMI::RmiTask::process_some(), madness::WorldAmInterface::send(), madness::MutexWaiter::yield(), and madness::WorldAmInterface::~WorldAmInterface().
new_am_arg()
template<typename... argT> AmArg* madness::new_am_arg (const argT &... args) inline
Convenience template for serializing arguments into a new AmArg.
References alloc_am_arg(), serialize_am_args(), and madness::archive::BufferOutputArchive::size().
Referenced by madness::WorldGopInterface::bcast_task(), madness::WorldGopInterface::group_bcast_task(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::reset(), madness::WorldObject< TestFutureForwarding >::send_am(), madness::WorldTaskQueue::send_task(), madness::WorldObject< TestFutureForwarding >::send_task(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::set(), and madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::set_handler().
nonstandard() [1/2]
template<typename T , std::size_t NDIM> void madness::nonstandard (World & world, std::vector< Function< T, NDIM > > & v, unsigned int blk = 1, bool fence = true)
Generates non-standard form of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, and reconstruct().
nonstandard() [2/2]
template<typename T , std::size_t NDIM> void madness::nonstandard (World & world, std::vector< Function< T, NDIM > > & v, bool fence = true)
Generates non-standard form of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, and reconstruct().
Referenced by apply(), madness::FunctionImpl< Q, NDIM >::coeffs_for_jun(), madness::FunctionImpl< Q, NDIM >::compress(), madness::FunctionImpl< Q, NDIM >::compress_op(), madness::FunctionImpl< Q, NDIM >::compress_spawn(), madness::FunctionImpl< Q, NDIM >::finalize_apply(), madness::FunctionImpl< Q, NDIM >::is_nonstandard(), madness::FunctionImpl< Q, NDIM >::reconstruct(), madness::FunctionImpl< Q, NDIM >::standard(), madness::FunctionImpl< Q, NDIM >::trickle_down(), and madness::FunctionImpl< Q, NDIM >::undo_redundant().
norm2()
template<typename T , std::size_t NDIM> double madness::norm2 (World & world, const std::vector< Function< T, NDIM > > & v)
Computes the 2-norm of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, and madness::WorldGopInterface::sum().
Referenced by madness::Solver< T, NDIM >::apply_potential(), Calculation::Calculation(), check_multiplication_table_c2v(), check_operator_multiplications_2d(), check_operator_multiplications_3d(), compare(), compare_calc_and_mos(), Calculation::compute_residuals(), madness::F12Potentials::convolve_with_fU(), madness::F12Potentials::F12Potentials(), madness::TDHF::get_tda_potential(), madness::Solver< T, NDIM >::gram_schmidt(), madness::Zcis::iterate(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), iterate_xy(), madness::Nemo::kinetic_energy_potential(), main(), madness::EigSolver< T, NDIM >::multi_solve(), madness::Zcis::normalize(), madness::SCF::polarizability(), print_info(), q_c(), SVPESolver::solve(), madness::Nemo::solve(), madness::SCF::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), smooth< T, NDIM >::test_1d(), test_adaptive_tree(), test_add(), test_cross(), madness::Diamagnetic_potential_factor::test_factor(), test_gconv(), test_io(), madness::Diamagnetic_potential_factor::test_lz_commutator(), test_math(), test_multi_to_multi_op(), test_multiply(), test_projector(), test_recursive_application(), test_rot(), test_unaryop(), madness::Diamagnetic_potential_factor::test_vector_potentials(), testbsh(), update(), MiniDFT::update(), and madness::Solver< T, NDIM >::update_orbitals().
norm2s() [1/2]
template<typename T , std::size_t NDIM> std::vector<double> madness::norm2s (World & world, const std::vector< Function< T, NDIM > > & v, const unsigned int blk = 1, const bool fence = true)
Computes the 2-norms of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, and madness::WorldGopInterface::sum().
norm2s() [2/2]
template<typename T , std::size_t NDIM> std::vector<double> madness::norm2s (World & world, const std::vector< Function< T, NDIM > > & v)
Computes the 2-norms of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, and madness::WorldGopInterface::sum().
Referenced by madness::TDHF::analyze(), madness::Zcis::compare_to_file(), madness::guessfactory::compute_centroids(), madness::SCF::compute_residual(), madness::Solver< T, NDIM >::compute_rho(), madness::Znemo::do_step_restriction(), madness::SCF::do_step_restriction(), doit(), MiniDFT::doit(), exchange_anchor_test(), madness::Zcis::iterate(), madness::TDHF::iterate_vectors(), madness::NemoBase::normalize(), normalize(), normalize2(), madness::SCF::residual_response(), madness::Solver< T, NDIM >::solve(), madness::Nemo::solve_cphf(), and madness::SCF::update_response_subspace().
norm_tree() [1/2]
template<typename T , std::size_t NDIM> void madness::norm_tree (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true, unsigned int blk = 1)
Makes the norm tree for all functions in a vector.
References madness::WorldGopInterface::fence(), madness::World::gop, norm_tree(), and PROFILE_BLOCK.
norm_tree() [2/2]
template<typename T , std::size_t NDIM> void madness::norm_tree (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Makes the norm tree for all functions in a vector.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Referenced by Calculation::make_reference(), mul_sparse(), norm_tree(), madness::FunctionNode< T, NDIM >::set_norm_tree(), and madness::SCF::twoint().
normalize()
template<typename T , std::size_t NDIM> void madness::normalize (World & world, std::vector< Function< T, NDIM > > & v, bool fence = true)
Normalizes a vector of functions — v[i] = v[i].scale(1.0/v[i].norm2())
References madness::WorldGopInterface::fence(), madness::World::gop, norm2s(), PROFILE_BLOCK, and scale().
Referenced by madness::SCF::diag_fock_matrix(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_virtual_gaussian_shell(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), Calculation::load_mos(), make_basis(), MiniDFT::makeao(), makeao_slow(), orth(), madness::SCF::orthonormalize(), madness::SCF::project(), madness::SCF::project_ao_basis_only(), madness::Solver< T, NDIM >::reproject(), madness::SCF::solve(), update(), and MiniDFT::update().
operator!=()
bool madness::operator!= (const DistributedID & left, const DistributedID & right) inline
Distributed ID inequality comparison operator.
Parameters
[in] left The first key to compare.
[in] right The second key to compare.
Returns
True when first or second of left and right are not equal; otherwise false.
operator*() [1/12]
template<typename T , std::size_t N, typename U > Vector<T,N> madness::operator* (Vector< T, N > l, U r)
Scale a Vector.
Multiply each Vector element by the scalar value r.
Template Parameters
T The left-hand Vector element type.
N The Vector size.
U The right-hand scalar type.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand scalar value to be multiplied by the Vector elements.
Returns
A new Vector, c, where c[i]==(l[i]*r).
References N.
operator*() [2/12]
template<typename T , typename U , std::size_t N> Vector<T,N> madness::operator* (T l, Vector< U, N > r)
Scale a Vector.
Multiply the scalar value l by each Vector element.
Template Parameters
T The left-hand scalar type.
U The right-hand Vector element type.
N The Vector size.
Parameters
[in] l The left-hand scalar value to be multiplied by the Vector elements.
[in] r The right-hand Vector.
Returns
A new Vector, c, where c[i]==(l*r[i]).
References N.
operator*() [3/12]
template<typename T , std::size_t N, typename U > Vector<T,N> madness::operator* (Vector< T, N > l, const Vector< U, N > & r)
Multiply (element-wise) two Vectors.
Do an element-wise multiplication of l and r and return the result in a new Vector.
Template Parameters
T The left-hand Vector element type.
N The Vector size.
U The right-hand Vector element type.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand Vector.
Returns
A new Vector, c, where c[i]==(l[i]*r[i]).
References N.
operator*() [4/12]
template<typename T , typename Q > IsSupported< TensorTypeData<Q>, LowRankTensor<T> >::type madness::operator* (const Q & x, const LowRankTensor< T > & t)
The class defines tensor op scalar ... here define scalar op tensor.
operator*() [5/12]
template<typename T , typename Q > IsSupported< TensorTypeData<Q>, GenTensor<T> >::type madness::operator* (const Q & x, const GenTensor< T > & t)
The class defines tensor op scalar ... here define scalar op tensor.
operator*() [6/12]
template<typename T , typename R , std::size_t NDIM> std::vector<Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::operator* (const R fac, const std::vector< Function< T, NDIM > > & rhs)
References copy(), R, scale(), and TENSOR_RESULT_TYPE().
operator*() [7/12]
template<typename T , typename R , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator* (const std::vector< Function< T, NDIM > > & rhs, const R fac)
References copy(), R, scale(), and TENSOR_RESULT_TYPE().
operator*() [8/12]
template<typename T , typename R , std::size_t NDIM> std::vector<Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::operator* (const Function< T, NDIM > & a, const std::vector< Function< R, NDIM > > & v)
multiply a vector of functions with a function: r[i] = v[i] * a
References a, and mul().
operator*() [9/12]
template<typename T , typename R , std::size_t NDIM> std::vector<Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::operator* (const std::vector< Function< T, NDIM > > & v, const Function< R, NDIM > & a)
multiply a vector of functions with a function: r[i] = a * v[i]
References a, and mul().
operator*() [10/12]
template<typename Q , typename T , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(Q,T),NDIM> madness::operator* (const Function< T, NDIM > & f, const Q alpha)
Returns new function equal to f(x)*alpha.
Using operator notation forces a global fence after each operation
References alpha, f, and mul().
operator*() [11/12]
template<typename Q , typename T , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(Q,T),NDIM> madness::operator* (const Q alpha, const Function< T, NDIM > & f)
Returns new function equal to alpha*f(x)
Using operator notation forces a global fence after each operation
References alpha, f, and mul().
operator*() [12/12]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R), NDIM> madness::operator* (const Function< L, NDIM > & left, const Function< R, NDIM > & right)
Multiplies two functions with the new result being of type TensorResultType<L,R>
Using operator notation forces a global fence after each operation but also enables us to automatically reconstruct the input functions as required.
References madness::Function< T, NDIM >::is_compressed(), madness::Function< T, NDIM >::is_on_demand(), MADNESS_ASSERT, mul(), and madness::Function< T, NDIM >::reconstruct().
operator+() [1/8]
template<typename T , std::size_t N, typename U > Vector<T,N> madness::operator+ (Vector< T, N > l, U r)
Add a scalar to a Vector.
Add the scalar value r to each Vector element.
Template Parameters
T The left-hand Vector element type.
N The Vector size.
U The right-hand scalar type.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand scalar value to be added to the Vector.
Returns
A new Vector, c, where c[i]==(l[i]+r).
References N.
operator+() [2/8]
template<typename T , std::size_t N, typename U > Vector<T,N> madness::operator+ (Vector< T, N > l, const Vector< U, N > & r)
Add (element-wise) two Vectors.
Do an element-wise addition of l and r and return the result in a new Vector.
Template Parameters
T The left-hand Vector element type.
N The Vector size.
U The right-hand Vector element type.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand Vector.
Returns
A new Vector, c, where c[i]==(l[i]+r[i]).
References N.
operator+() [3/8]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator+ (const std::vector< Function< T, NDIM > > & lhs, const std::vector< Function< T, NDIM >> & rhs)
result[i] = a[i] + b[i]
References gaxpy_oop().
operator+() [4/8]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator+ (const std::vector< Function< T, NDIM > > & lhs, const Function< T, NDIM > & rhs)
result[i] = a[i] + b
References gaxpy_oop().
operator+() [5/8]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator+ (const Function< T, NDIM > & lhs, const std::vector< Function< T, NDIM > > & rhs)
result[i] = a + b[i]
References gaxpy_oop().
operator+() [6/8]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R), NDIM> madness::operator+ (const Function< L, NDIM > & left, const Function< R, NDIM > & right)
Adds two functions with the new result being of type TensorResultType<L,R>
Using operator notation forces a global fence after each operation
References add(), madness::Function< T, NDIM >::compress(), gaxpy_oop_reconstructed(), madness::Function< T, NDIM >::is_compressed(), NDIM, madness::Function< T, NDIM >::reconstruct(), VERIFY_TREE, and madness::Function< T, NDIM >::verify_tree().
operator+() [7/8]
template<typename T , typename R , std::size_t NDIM> IsSupported<TensorTypeData<R>, Function<TENSOR_RESULT_TYPE(T,R),NDIM> >::type madness::operator+ (const Function< T, NDIM > & f, R r)
References f, and R.
operator+() [8/8]
template<typename T , typename R , std::size_t NDIM> IsSupported<TensorTypeData<R>, Function<TENSOR_RESULT_TYPE(T,R),NDIM> >::type madness::operator+ (R r, const Function< T, NDIM > & f)
References f, and R.
operator+=()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator+= (std::vector< Function< T, NDIM > > & rhs, const std::vector< Function< T, NDIM > > & lhs)
References add().
operator-() [1/8]
template<typename T , std::size_t N, typename U > Vector<T,N> madness::operator- (Vector< T, N > l, U r)
Subtract a scalar from a Vector.
Subtract the scalar value r from the Vector elements l[i].
Template Parameters
T The left-hand Vector element type.
N The Vector size.
U The right-hand scalar type.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand scalar value to be added to the Vector.
Returns
A new Vector, c, where c[i]==(l[i]-r).
References N.
operator-() [2/8]
template<typename T , std::size_t N, typename U > Vector<T,N> madness::operator- (Vector< T, N > l, const Vector< U, N > & r)
Subtract (element-wise) two Vectors.
Do an element-wise subtraction of l and r and return the result in a new Vector.
Template Parameters
T The left-hand Vector element type.
N The Vector size.
U The right-hand Vector element type.
Parameters
[in] l The left-hand Vector.
[in] r The right-hand Vector.
Returns
A new Vector, c, where c[i]==(l[i]-r[i]).
References N.
operator-() [3/8]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator- (const std::vector< Function< T, NDIM > > & lhs, const std::vector< Function< T, NDIM > > & rhs)
result[i] = a[i] - b[i]
References gaxpy_oop().
operator-() [4/8]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator- (const std::vector< Function< T, NDIM > > & lhs, const Function< T, NDIM > & rhs)
result[i] = a[i] - b
References gaxpy_oop().
operator-() [5/8]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator- (const Function< T, NDIM > & lhs, const std::vector< Function< T, NDIM > > & rhs)
result[i] = a - b[i]
References gaxpy_oop().
operator-() [6/8]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R), NDIM> madness::operator- (const Function< L, NDIM > & left, const Function< R, NDIM > & right)
Subtracts two functions with the new result being of type TensorResultType<L,R>
Using operator notation forces a global fence after each operation
References madness::Function< T, NDIM >::compress(), gaxpy_oop_reconstructed(), madness::Function< T, NDIM >::is_compressed(), NDIM, PROFILE_FUNC, madness::Function< T, NDIM >::reconstruct(), and sub().
operator-() [7/8]
template<typename T , typename R , std::size_t NDIM> IsSupported<TensorTypeData<R>, Function<TENSOR_RESULT_TYPE(T,R),NDIM> >::type madness::operator- (const Function< T, NDIM > & f, R r)
References f, and R.
operator-() [8/8]
template<typename T , typename R , std::size_t NDIM> IsSupported<TensorTypeData<R>, Function<TENSOR_RESULT_TYPE(T,R),NDIM> >::type madness::operator- (R r, const Function< T, NDIM > & f)
References f, and R.
operator-=()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::operator-= (std::vector< Function< T, NDIM > > & rhs, const std::vector< Function< T, NDIM > > & lhs)
References sub().
operator<<() [1/18]
std::ostream & madness::operator<< (std::ostream & os, const PairType & en)
References ALL_PAIRTYPE, CISPD_PAIRTYPE, MP2_PAIRTYPE, NONE_PAIRTYPE, and UNKNOWN_PAIRTYPE.
operator<<() [2/18]
std::ostream & madness::operator<< (std::ostream & os, const EnergyType & en)
References HYLLERAAS_ENERGYTYPE, PROJECTED_ENERGYTYPE, and UNKNOWN_ENERGYTYPE.
operator<<() [3/18]
std::ostream& madness::operator<< (std::ostream & s, const ContractedGaussianShell & c)
References c, and p().
operator<<() [4/18]
std::ostream & madness::operator<< (std::ostream & out, const MadnessException & e)
Enables easy printing of a MadnessException.
Parameters
[in,out] out Output stream.
[in] e The MadnessException.
Returns
The output stream.
References e().
operator<<() [5/18]
template<> std::ostream & madness::operator<< (std::ostream & out, const Future< void > & f)
Stream output operator for a void future.
Parameters
[in,out] out The output stream.
[in] f The future.
Returns
The output stream.
operator<<() [6/18]
std::ostream& madness::operator<< (std::ostream & s, const AtomicBasis & c)
References c.
operator<<() [7/18]
std::ostream & madness::operator<< (std::ostream & os, const GuessType & en)
References EMPTY_GUESSTYPE, EXOP_GUESSTYPE, FROM_FILE_GUESSTYPE, PARTIAL_WAVE_GUESSTYPE, PREDEFINED_GUESSTYPE, PSI4_GUESSTYPE, SCF_GUESSTYPE, and UNKNOWN_GUESSTYPE.
operator<<() [8/18]
template<typename T , std::size_t N> std::ostream& madness::operator<< (std::ostream & s, const std::array< T, N > & a)
Output std::array to stream for human consumption.
Template Parameters
T The type of data stored in the array.
N The size of the array.
Parameters
[in,out] s The output stream.
[in] a The array to be output.
Returns
The output stream.
References a, and N.
operator<<() [9/18]
std::ostream& madness::operator<< (std::ostream & s, const AtomicBasisFunction & a)
References a.
operator<<() [10/18]
std::ostream & madness::operator<< (std::ostream & s, const Atom & atom)
References madness::Atom::atomic_number, madness::Atom::q, madness::Atom::x, madness::Atom::y, and madness::Atom::z.
operator<<() [11/18]
std::ostream & madness::operator<< (std::ostream & stream, const Slice & s)
References madness::Slice::end, madness::Slice::start, and madness::Slice::step.
operator<<() [12/18]
template<std::size_t NDIM> static std::ostream& madness::operator<< (std::ostream & s, const BoundaryConditions< NDIM > & bc) inline static
References d(), and NDIM.
operator<<() [13/18]
template<typename T > std::ostream & madness::operator<< (std::ostream & out, const Future< T > & f)
Human readable printing of a Future to a stream.
Stream output operator for a future.
Template Parameters
T The type of future.
Parameters
[in,out] out The output stream.
[in] f The future.
Returns
The output stream.
operator<<() [14/18]
static std::ostream& madness::operator<< (std::ostream & s, const TensorType & tt) inline static
References TT_2D, TT_FULL, TT_NONE, and TT_TENSORTRAIN.
operator<<() [15/18]
template<std::size_t NDIM> std::ostream& madness::operator<< (std::ostream & s, const Key< NDIM > & key)
References KeyChildIterator::key(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::translation().
operator<<() [16/18]
template<typename T , std::size_t NDIM> std::ostream& madness::operator<< (std::ostream & s, const FunctionNode< T, NDIM > & node)
References e(), and madness::detail::norm().
operator<<() [17/18]
template<typename T , std::size_t NDIM> std::ostream& madness::operator<< (std::ostream & s, const CoeffTracker< T, NDIM > & ct)
operator<<() [18/18]
template<typename T > static std::ostream& madness::operator<< (std::ostream & s, const SRConf< T > & sr) inline static
References madness::SRConf< T >::dim_.
operator==()
bool madness::operator== (const DistributedID & left, const DistributedID & right) inline
Distributed ID equality comparison operator.
Parameters
[in] left The first key to compare.
[in] right The second key to compare.
Returns
True when first and second of left and right are equal; otherwise false.
operator>>() [1/5]
std::istream & madness::operator>> (std::istream & is, PairType & en)
References ALL_PAIRTYPE, CISPD_PAIRTYPE, MADNESS_EXCEPTION, MP2_PAIRTYPE, NONE_PAIRTYPE, transform(), and UNKNOWN_PAIRTYPE.
operator>>() [2/5]
template<typename T , typename A = std::allocator<T>> std::istream& madness::operator>> (std::istream & is, std::vector< T, A > & v)
inverting the print method from print.h for std::vector TODO: move this where it belongs (into print.h ??)
References c, check_for_inf(), MADNESS_EXCEPTION, and print().
operator>>() [3/5]
std::istream & madness::operator>> (std::istream & is, EnergyType & en)
References HYLLERAAS_ENERGYTYPE, MADNESS_EXCEPTION, PROJECTED_ENERGYTYPE, transform(), and UNKNOWN_ENERGYTYPE.
operator>>() [4/5]
std::istream & madness::operator>> (std::istream & is, GuessType & en)
References EMPTY_GUESSTYPE, EXOP_GUESSTYPE, FROM_FILE_GUESSTYPE, MADNESS_EXCEPTION, PARTIAL_WAVE_GUESSTYPE, PREDEFINED_GUESSTYPE, PSI4_GUESSTYPE, SCF_GUESSTYPE, transform(), and UNKNOWN_GUESSTYPE.
operator>>() [5/5]
template<typename Q , typename T > std::istream& madness::operator>> (std::istream & is, std::pair< T, Q > & p)
inverting the print method from print.h for std::vector TODO: move this where it belongs (into print.h ??)
References c, MADNESS_EXCEPTION, p(), and print().
orgqr() [1/5]
template<typename T > void madness::orgqr (Tensor< T > & A, const Tensor< T > & tau)
reconstruct the orthogonal matrix Q (e.g. from QR factorization)
orgqr generates an M-by-N complex matrix Q with orthonormal columns
Parameters
[in,out] A On entry, the i-th column must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGEQRF in the first k columns of its array argument A. On exit, the M-by-N matrix Q.
[in] tau TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGEQRF.
which is defined as the first N columns of a product of K elementary reflectors of order M Q = H(1) H(2) . . . H(k) as returned by ZGEQRF.
References dorgqr_(), k, m, mask_info(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), TENSOR_ASSERT, and transpose().
orgqr() [2/5]
template void madness::orgqr (Tensor< float > & A, const Tensor< float > & tau)
orgqr() [3/5]
template void madness::orgqr (Tensor< double > & A, const Tensor< double > & tau)
orgqr() [4/5]
template void madness::orgqr (Tensor< complex_real4 > & A, const Tensor< complex_real4 > & tau)
orgqr() [5/5]
template void madness::orgqr (Tensor< double_complex > & A, const Tensor< double_complex > & tau)
ortho3()
template<typename T > void madness::ortho3 (Tensor< T > & x, Tensor< T > & y, Tensor< double > & weights, const double & thresh)
sophisticated version of ortho2
after calling this we will have an optimally rank-reduced representation with the left and right subspaces being bi-orthogonal and normalized; outline of the algorithm:
canonical orthogonalization of the subspaces (screen for small eigenvalues)
SVD of the modified overlap (incorporates the roots of eigenvalues) operation count is O(kr^2 + r^3)
Parameters
[in,out] x normalized left subspace
[in,out] y normalize right subspace
[in,out] weights weights
[in] thresh truncation threshold
References _(), std::abs(), madness::Tensor< T >::absmax(), madness::Tensor< T >::clear(), madness::BaseTensor::dim(), e(), e1(), inner(), MADNESS_ASSERT, madness::SRConf< T >::max_sigma(), madness::Tensor< T >::screen(), madness::BaseTensor::size(), svd(), syev(), thresh, wall_time(), and weights.
Referenced by madness::SRConf< T >::orthonormalize().
ortho5()
template<typename T > void madness::ortho5 (Tensor< T > & x1, Tensor< T > & y1, Tensor< double > & w1, const Tensor< T > & x2, const Tensor< T > & y2, const Tensor< double > & w2, const double & thresh)
specialized version of ortho3
does the same as ortho3, but takes two bi-orthonormal configs as input and saves on the inner product. Result will be written onto the first config
Parameters
[in,out] x1 left subspace, will hold the result on exit
[in,out] y1 right subspace, will hold the result on exit
[in] x2 left subspace, will be accumulated onto x1
[in] y2 right subspace, will be accumulated onto y1
References _(), std::abs(), madness::Tensor< T >::absmax(), madness::Tensor< T >::clear(), copy(), madness::BaseTensor::dim(), e(), e1(), madness::Tensor< T >::emul(), inner(), inner_result(), max, outer(), residual(), s0, madness::Tensor< T >::screen(), svd(), syev(), thresh, transpose(), and wall_time().
Referenced by madness::SRConf< T >::add_SVD().
orthonormalize_canonical() [1/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_canonical (const std::vector< Function< T, NDIM > > & v, const Tensor< T > & ovlp, double lindep)
canonical orthonormalization (see e.g. Szabo/Ostlund)
Parameters
[in] the vector to orthonormalize
[in] overlap matrix
[in] lindep linear dependency threshold relative to largest eigenvalue
References _(), lo, MADNESS_ASSERT, madness::BaseTensor::size(), syev(), and transform().
Referenced by madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), and orthonormalize_canonical().
orthonormalize_canonical() [2/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_canonical (const std::vector< Function< T, NDIM > > & v, const double lindep)
convenience routine for canonical routine for symmetric orthonormalization (see e.g. Szabo/Ostlund) overlap matrix is calculated
Parameters
[in] the vector to orthonormalize
References matrix_inner(), and orthonormalize_canonical().
orthonormalize_cd() [1/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_cd (const std::vector< Function< T, NDIM > > & v, Tensor< T > & ovlp)
cholesky orthonormalization without pivoting
Parameters
[in] the vector to orthonormalize
[in] overlap matrix, destroyed on return!
References cholesky(), inverse(), L, transform(), and transpose().
Referenced by orthonormalize_cd().
orthonormalize_cd() [2/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_cd (const std::vector< Function< T, NDIM > > & v)
convenience routine for cholesky orthonormalization without pivoting
Parameters
[in] the vector to orthonormalize
[in] overlap matrix
References matrix_inner(), and orthonormalize_cd().
orthonormalize_rrcd() [1/3]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_rrcd (const std::vector< Function< T, NDIM > > & v, Tensor< T > & ovlp, const double tol, Tensor< integer > & piv, int & rank)
Parameters
[in] the vector to orthonormalize
[in] overlap matrix, will be destroyed on return!
[in] tolerance for numerical rank reduction
[out] pivoting vector, no allocation on input needed
[out] rank
Returns
orthonrormalized vector (may or may not be truncated)
References inverse(), L, rr_cholesky(), transform(), and transpose().
Referenced by madness::F12Potentials::compute_hylleraas_f12_energies(), madness::PNO::initialize_pairs(), and orthonormalize_rrcd().
orthonormalize_rrcd() [2/3]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_rrcd (const std::vector< Function< T, NDIM > > & v, Tensor< T > ovlp, const double tol)
convenience routine for orthonromalize_cholesky: orthonromalize_cholesky without information on pivoting and rank
Parameters
[in] the vector to orthonormalize
[in] overlap matrix
[in] tolerance for numerical rank reduction
References orthonormalize_rrcd().
orthonormalize_rrcd() [3/3]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_rrcd (const std::vector< Function< T, NDIM > > & v, const double tol)
convenience routine for orthonromalize_cholesky: computes the overlap matrix and then calls orthonromalize_cholesky
Parameters
[in] the vector to orthonormalize
[in] tolerance for numerical rank reduction
References matrix_inner(), and orthonormalize_rrcd().
orthonormalize_symmetric() [1/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_symmetric (const std::vector< Function< T, NDIM > > & v, const Tensor< T > & ovlp)
symmetric orthonormalization (see e.g. Szabo/Ostlund)
Parameters
[in] the vector to orthonormalize
[in] overlap matrix
References inner(), syev(), transform(), and transpose().
Referenced by orthonormalize_symmetric(), and madness::MolecularOrbitals< T, NDIM >::project_ao().
orthonormalize_symmetric() [2/2]
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::orthonormalize_symmetric (const std::vector< Function< T, NDIM > > & v)
convenience routine for symmetric orthonormalization (see e.g. Szabo/Ostlund) overlap matrix is calculated
Parameters
[in] the vector to orthonormalize
References matrix_inner(), and orthonormalize_symmetric().
outer() [1/2]
template<class T , class Q > LowRankTensor<TENSOR_RESULT_TYPE(T,Q)> madness::outer (const LowRankTensor< T > & t1, const LowRankTensor< Q > & t2, const TensorArgs final_tensor_args)
outer product of two Tensors, yielding a low rank tensor
do the outer product of two tensors; distinguish these tensortype cases by the use of final_tensor_type
full x full -> full
full x full -> SVD (default)
TensorTrain x TensorTrain -> TensorTrain all other combinations are currently invalid.
References madness::LowRankTensor< T >::full_tensor_copy(), madness::LowRankTensor< T >::impl, k, MADNESS_ASSERT, MADNESS_EXCEPTION, madness::BaseTensor::ndim(), outer(), madness::Tensor< T >::reshape(), madness::BaseTensor::size(), TENSOR_RESULT_TYPE(), madness::LowRankTensor< T >::tensor_type(), madness::TensorArgs::tt, TT_2D, TT_FULL, TT_TENSORTRAIN, and weights.
outer() [2/2]
template<class T , class Q > TensorTrain<TENSOR_RESULT_TYPE(T,Q)> madness::outer (const TensorTrain< T > & t1, const TensorTrain< Q > & t2)
computes the outer product of two tensors
result(i,j,...,p,q,...) = left(i,k,...)*right(p,q,...)
Returns
Returns a new tensor train
References copy(), madness::TensorTrain< T >::core, madness::TensorTrain< T >::dim(), k1, k2, madness::TensorTrain< T >::ndim(), TENSOR_RESULT_TYPE(), and madness::TensorTrain< T >::zero_rank.
parity()
static int madness::parity (int i) inline static
Return +1 if i is even, -1 if i is odd ... perverse no if-test form.
Referenced by read_data().
periodic_derivative()
template<typename T , std::size_t NDIM> Derivative<T,NDIM> madness::periodic_derivative (World & world, int axis, int k = FunctionDefaults<NDIM>::get_k())
Conveinence function returning derivative operator with periodic boundary conditions.
References axis, BC_PERIODIC, and k.
PeriodicBSHOp()
template<typename Q , int NDIM> SeparatedConvolution<Q, NDIM> madness::PeriodicBSHOp (World & world, double mu, long k, double lo, double eps, Tensor< double > L)
References c, madness::BaseTensor::dim(), k, L, lo, mu, NDIM, and pow().
PeriodicBSHOperator3D()
static SeparatedConvolution<double_complex,3> madness::PeriodicBSHOperator3D (World & world, Vector< double, 3 > args, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, and madness::Tensor< T >::normf().
Referenced by apply_periodic_bsh().
PeriodicBSHOperatorPtr3D()
static SeparatedConvolution<double_complex,3>* madness::PeriodicBSHOperatorPtr3D (World & world, Vector< double, 3 > args, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with exp(-mu*r)/(4*pi*r) in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::BSHFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, and madness::Tensor< T >::normf().
Referenced by KPeriodicBSHOperator::apply().
PeriodicBSHOpPtr()
template<typename Q , int NDIM> SeparatedConvolution<Q, NDIM>* madness::PeriodicBSHOpPtr (World & world, double mu, long k, double lo, double eps, Tensor< double > L)
References c, madness::BaseTensor::dim(), k, L, lo, mu, NDIM, and pow().
PeriodicCoulombOp()
template<typename Q , int NDIM> SeparatedConvolution<Q, NDIM> madness::PeriodicCoulombOp (World & world, long k, double lo, double eps, Tensor< double > L)
References acut1e_6, c, madness::BaseTensor::dim(), k, L, lo, NDIM, pow(), and WST_PI.
PeriodicCoulombOpPtr()
template<typename Q , int NDIM> SeparatedConvolution<Q, NDIM>* madness::PeriodicCoulombOpPtr (World & world, long k, double lo, double eps, Tensor< double > L)
References acut1e_6, c, madness::BaseTensor::dim(), k, L, lo, NDIM, pow(), and WST_PI.
PeriodicHFExchangeOperator()
static SeparatedConvolution<double_complex,3> madness::PeriodicHFExchangeOperator (World & world, Vector< double, 3 > args, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with 1/r in 3D.
References BC_PERIODIC, madness::GFit< T, NDIM >::CoulombFit(), fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), and madness::Tensor< T >::normf().
Referenced by madness::Solver< T, NDIM >::apply_hf_exchange(), and madness::Solver< T, NDIM >::apply_hf_exchange4().
pg_c2()
static pg_operator madness::pg_c2 () inline static
Referenced by check_operator_multiplications_2d().
pg_c2x()
static pg_operator madness::pg_c2x () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), madness::projector_irrep::make_d2_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_c2y()
static pg_operator madness::pg_c2y () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), madness::projector_irrep::make_d2_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_c2z()
static pg_operator madness::pg_c2z () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), madness::projector_irrep::make_c2_table(), madness::projector_irrep::make_c2h_table(), madness::projector_irrep::make_c2v_table(), madness::projector_irrep::make_d2_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_c4()
static pg_operator madness::pg_c4 () inline static
Referenced by check_operator_multiplications_2d(), and plot_symmetry_operators().
pg_c4x()
static pg_operator madness::pg_c4x () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), plot_symmetry_operators(), and test_orthogonalization().
pg_c4y()
static pg_operator madness::pg_c4y () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), plot_symmetry_operators(), and test_orthogonalization().
pg_c4z()
static pg_operator madness::pg_c4z () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), plot_symmetry_operators(), and test_orthogonalization().
pg_identity()
static pg_operator madness::pg_identity () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_2d(), check_operator_multiplications_3d(), madness::projector_irrep::make_c1_table(), madness::projector_irrep::make_c2_table(), madness::projector_irrep::make_c2h_table(), madness::projector_irrep::make_c2v_table(), madness::projector_irrep::make_ci_table(), madness::projector_irrep::make_cs_table(), madness::projector_irrep::make_d2_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_inversion()
static pg_operator madness::pg_inversion () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_2d(), check_operator_multiplications_3d(), madness::projector_irrep::make_c2h_table(), madness::projector_irrep::make_ci_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_sigma_x()
static pg_operator madness::pg_sigma_x () inline static
Referenced by check_operator_multiplications_2d(), and plot_symmetry_operators().
pg_sigma_xy()
static pg_operator madness::pg_sigma_xy () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), madness::projector_irrep::make_c2h_table(), madness::projector_irrep::make_cs_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_sigma_xz()
static pg_operator madness::pg_sigma_xz () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), madness::projector_irrep::make_c2v_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
pg_sigma_y()
static pg_operator madness::pg_sigma_y () inline static
Referenced by check_operator_multiplications_2d(), and plot_symmetry_operators().
pg_sigma_yz()
static pg_operator madness::pg_sigma_yz () inline static
Referenced by check_multiplication_table_c2v(), check_operator_multiplications_3d(), madness::projector_irrep::make_c2v_table(), madness::projector_irrep::make_d2h_table(), plot_symmetry_operators(), and test_orthogonalization().
phase()
static double madness::phase (long i) inline static
Referenced by madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::Diamagnetic_potential_factor::factor_with_phase(), fixphases(), madness::Diamagnetic_potential_factor::make_fake_orbitals(), read_twoscale(), test_chin_chen(), test_trotter(), and GaussianGuess< T, NDIM >::val().
plot()
template<size_t NDIM> void madness::plot (const std::vector< Function< double, NDIM > > & vf, const std::string & name, const std::vector< std::string > & header)
convenience to get plot_plane and plot_cubefile
Referenced by main(), madness::TDHF::plot(), CalculationParameters::print_info(), and CalculationParameters::read_file().
plot_along() [1/2]
template<size_t NDIM> void madness::plot_along (World & world, trajectory< NDIM > traj, const Function< double, NDIM > & function, std::string filename)
References f, madness::WorldGopInterface::fence(), filename, madness::World::gop, MADNESS_EXCEPTION, madness::trajectory< NDIM >::npt, madness::trajectory< NDIM >::print_psdot(), and madness::World::rank().
Referenced by test_modified(), and test_recursive_application().
plot_along() [2/2]
template<size_t NDIM> void madness::plot_along (World & world, trajectory< NDIM > traj, double(*)(const Vector< double, NDIM > &) ff, std::string filename)
References f, madness::WorldGopInterface::fence(), filename, madness::World::gop, MADNESS_EXCEPTION, madness::trajectory< NDIM >::npt, madness::trajectory< NDIM >::print_psdot(), and madness::World::rank().
plot_cubefile()
template<size_t NDIM> std::enable_if<NDIM==3,void>::type madness::plot_cubefile (World & world, const Function< double, NDIM > & f, std::string filename, std::vector< std::string > molecular_info = std::vector<std::string>())
References copy(), f, filename, k, MADNESS_EXCEPTION, position_stream(), print(), madness::Tensor< T >::scale(), and madness::World::size().
plot_line() [1/5]
template<typename opT , std::size_t NDIM> void madness::plot_line (World & world, const char * filename, int npt, const Vector< double, NDIM > & lo, const Vector< double, NDIM > & hi, const opT & op)
Generates ASCII file tabulating f(r) at npoints along line r=lo,...,hi.
The ordinate is distance from lo
References madness::WorldGopInterface::fence(), filename, madness::World::gop, h(), lo, MADNESS_EXCEPTION, NDIM, op(), plot_line_print_value(), madness::World::rank(), and sum().
Referenced by Plotter::dolineplot(), dostuff(), madness::Solver< T, NDIM >::initial_guess(), main(), smooth< T, NDIM >::make_plots(), madness::Nemo::make_plots(), SurfaceMoleculeInteraction::make_surfcharge(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), plot(), Calculation::plot_z(), smooth< T, NDIM >::test_1d(), test_apply_push_1d(), test_gconv(), and test_plot().
plot_line() [2/5]
template<typename T , std::size_t NDIM> void madness::plot_line (const char * filename, int npt, const Vector< double, NDIM > & lo, const Vector< double, NDIM > & hi, const Function< T, NDIM > & f)
Generates ASCII file tabulating f(r) at npoints along line r=lo,...,hi.
The ordinate is distance from lo
References f, madness::WorldGopInterface::fence(), filename, madness::World::gop, h(), lo, MADNESS_EXCEPTION, NDIM, plot_line_print_value(), madness::World::rank(), and sum().
plot_line() [3/5]
template<typename T , typename U , std::size_t NDIM> void madness::plot_line (const char * filename, int npt, const Vector< double, NDIM > & lo, const Vector< double, NDIM > & hi, const Function< T, NDIM > & f, const Function< U, NDIM > & g)
Generates ASCII file tabulating f(r) and g(r) at npoints along line r=lo,...,hi.
The ordinate is distance from lo
References f, madness::WorldGopInterface::fence(), filename, g, madness::World::gop, h(), lo, MADNESS_EXCEPTION, NDIM, plot_line_print_value(), madness::World::rank(), and sum().
plot_line() [4/5]
template<typename T , typename U , typename V , std::size_t NDIM> void madness::plot_line (const char * filename, int npt, const Vector< double, NDIM > & lo, const Vector< double, NDIM > & hi, const Function< T, NDIM > & f, const Function< U, NDIM > & g, const Function< V, NDIM > & a)
Generates ASCII file tabulating f(r), g(r), and a(r) at npoints along line r=lo,...,hi.
The ordinate is distance from lo
References a, f, madness::WorldGopInterface::fence(), filename, g, madness::World::gop, h(), lo, MADNESS_EXCEPTION, NDIM, plot_line_print_value(), madness::World::rank(), and sum().
plot_line() [5/5]
template<typename T , typename U , typename V , typename W , std::size_t NDIM> void madness::plot_line (const char * filename, int npt, const Vector< double, NDIM > & lo, const Vector< double, NDIM > & hi, const Function< T, NDIM > & f, const Function< U, NDIM > & g, const Function< V, NDIM > & a, const Function< W, NDIM > & b)
Generates ASCII file tabulating f(r), g(r), a(r), b(r) at npoints along line r=lo,...,hi.
The ordinate is distance from lo
References a, b, f, madness::WorldGopInterface::fence(), filename, g, madness::World::gop, h(), lo, NDIM, plot_line_print_value(), madness::World::rank(), and sum().
plot_line_print_value() [1/2]
static void madness::plot_line_print_value (FILE * f, double_complex v) inline static
References f, imag(), and real().
Referenced by plot_line(), and Calculation::plot_p().
plot_line_print_value() [2/2]
static void madness::plot_line_print_value (FILE * f, double v) inline static
References f.
plot_plane() [1/5]
template<size_t NDIM> void madness::plot_plane (World & world, const Function< double, NDIM > & function, const std::string name)
Referenced by madness::TDHF::get_tda_potential(), madness::BasisFunctions::guess_virtuals_internal(), main(), madness::TDHF::make_old_guess(), smooth< T, NDIM >::make_plots(), madness::Nemo::make_plots(), test_correlation_factor::make_test(), madness::TDHF::oscillator_strength_length(), madness::CC2::plot(), madness::CCFunction::plot(), plot_plane(), and plot_symmetry_operators().
plot_plane() [2/5]
template<size_t NDIM> void madness::plot_plane (World & world, const Function< double, NDIM > & function1, const Function< double, NDIM > & function2, const std::string name)
References plot_plane().
plot_plane() [3/5]
template<size_t NDIM> void madness::plot_plane (World & world, const Function< double, NDIM > & function1, const Function< double, NDIM > & function2, const Function< double, NDIM > & function3, const std::string name)
References plot_plane().
plot_plane() [4/5]
template<size_t NDIM> void madness::plot_plane (World & world, const std::vector< Function< double, NDIM > > & vfunction, const std::string name)
plot a 2-d slice of a given function and the according MRA structure FIXME: doesn't work for more than 1 rank the plotting parameters are taken from the input file "input" and its data group "plot", e.g. plotting the xy plane around (0,0,0.7): plot plane x1 x2 zoom 2.0 npoints 100 origin 0.0 0.0 0.7 end
Parameters
[in] world the world
[in] vfunction the function to plot
[in] name the output name
References f, filename, madness::FunctionDefaults< NDIM >::get_cell_width(), lo, MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, position_stream(), print(), madness::World::rank(), scale(), and madness::World::size().
plot_plane() [5/5]
template<size_t NDIM, typename opT > void madness::plot_plane (World & world, const opT & op, const std::string name)
References f, filename, madness::FunctionDefaults< NDIM >::get_cell_width(), lo, MADNESS_EXCEPTION, op(), position_stream(), print(), madness::World::rank(), scale(), and madness::World::size().
plotdx()
template<typename T , std::size_t NDIM> void madness::plotdx (const Function< T, NDIM > & f, const char * filename, const Tensor< double > & cell = FunctionDefaults<NDIM>::get_cell(), const std::vector< long > & npt = std::vector<long>(NDIM,201L), bool binary = true)
Writes an OpenDX format file with a cube/slice of points on a uniform grid.
Collective operation but only process 0 writes the file. By convention OpenDX files end in ".dx" but this choice is up to the user. The binary format is more compact and vastly faster to both write and load but is not as portable.
Now follow some brief tips about how to look at files inside OpenDX.
To view a 1D function file-selector-->import-->plot-->image.
To view a 2D function as a colored plane file-selector-->import-->autocolor-->image.
To view a 2D function as a 3D surface file-selector-->import-->rubbersheet-->image.
To view a 3D function as an isosurface file-selector-->import-->isosurface-->image.
To select the real/imaginary/absolute value of a complex number insert a compute element after the import.
References c, d(), dxprintvalue(), f, madness::WorldGopInterface::fence(), filename, madness::World::gop, h(), MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, PROFILE_FUNC, madness::Tensor< T >::ptr(), madness::World::rank(), and madness::BaseTensor::size().
Referenced by madness::SCF::do_plots(), Plotter::dovolumeplot(), madness::Solver< T, NDIM >::initial_guess(), main(), madness::Solver< T, NDIM >::solve(), test_plot(), and testPeriodicCoulomb3d().
plotpovray()
template<typename T > static void madness::plotpovray (const Function< T, 3 > & function, const char * filename, const Tensor< double > & cell = FunctionDefaults<3>::get_cell(), const std::vector< long > & npt = std::vector<long>(3,201L)) static
Writes a Povray DF3 format file with a cube of points on a uniform grid.
Collective operation but only process 0 writes the file. By convention Povray files end in ".df3" but this choice is up to the user. The dynamic range of function values is mapped onto [0,1] and values stored in 16-bit fixed precision.
References d(), f, filename, madness::detail::htons_x(), MADNESS_ASSERT, MADNESS_EXCEPTION, madness::Tensor< T >::max(), madness::Tensor< T >::min(), and madness::World::rank().
Referenced by main().
plotvtk_begin()
template<std::size_t NDIM> void madness::plotvtk_begin (World & world, const char * filename, const Vector< double, NDIM > & plotlo, const Vector< double, NDIM > & plothi, const Vector< long, NDIM > & npt, bool binary = false)
Writes the header information of a VTK file for plotting in an external post-processing package (such as Paraview)
Parameters
world World communicator
filename String containing the filename to export to
plotlo Vector of double values indicating the minimum coordinate to plot to in each dimension
plothi Vector of double values indicating the maximum coordinate to plot to in each dimension
npt Vector of long integers indicating the number of points to plot in each dimension
binary (optional) Boolean indicating whether to print in binary The VTK routines are also designed for SERIAL data, parallel coming...
This header is templated by the dimension of the data.
To plot with the plotvtk_* routines: plotvtk_begin(...) plotvtk_data(...) plotvtk_data(...) ... plotvtk_end(...)
NOTE: Paraview expects the structured mesh points in a particular order, which is why the LowDimIndexIterator is used...
References f, madness::WorldGopInterface::fence(), filename, madness::World::gop, MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, PROFILE_FUNC, and madness::World::rank().
Referenced by Plotter::dovolumeplot(), and testNavierStokes().
plotvtk_data() [1/3]
template<typename T , std::size_t NDIM> void madness::plotvtk_data (const T & function, const char * fieldname, World & world, const char * filename, const Vector< double, NDIM > & plotlo, const Vector< double, NDIM > & plothi, const Vector< long, NDIM > & npt, bool binary = false)
Generic VTK data writer. Specific type instances of this function are defined for both real and complex valued functions.
Parameters
function Function (real or complex) that we wish to export the data of
fieldname A string containing the name we wish to refer to this field as in the exported data
world World communicator
filename String containing the filename to export to
plotlo Vector of double values indicating the minimum coordinate to plot to in each dimension
plothi Vector of double values indicating the maximum coordinate to plot to in each dimension
npt Vector of long integers indicating the number of points to plot in each dimension
binary (optional) Boolean indicating whether to print in binary This templated function won't do anything except print a warning message. Specialized versions of this function should be used.
References MADNESS_EXCEPTION.
Referenced by Plotter::dovolumeplot(), and testNavierStokes().
plotvtk_data() [2/3]
template<typename T , std::size_t NDIM> void madness::plotvtk_data (const Function< T, NDIM > & function, const char * fieldname, World & world, const char * filename, const Vector< double, NDIM > & plotlo, const Vector< double, NDIM > & plothi, const Vector< long, NDIM > & npt, bool binary = false, bool plot_refine = false)
VTK data writer for real-valued (not complex) madness::functions.
Set plot_refine=true to get a plot of the refinement levels of the given function.
References madness::WorldGopInterface::barrier(), f, madness::WorldGopInterface::fence(), filename, madness::World::gop, MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, PROFILE_FUNC, and madness::World::rank().
plotvtk_data() [3/3]
template<typename T , std::size_t NDIM> void madness::plotvtk_data (const Function< std::complex< T >, NDIM > & function, const char * fieldname, World & world, const char * filename, const Vector< double, NDIM > & plotlo, const Vector< double, NDIM > & plothi, const Vector< long, NDIM > & npt, bool binary = false, bool plot_refine = false)
VTK data writer for complex-valued madness::functions.
The complex-value is written as two reals (a vector from VTK's perspective. The first (X) component is the real part and the second (Y) component is the imaginary part. Set plot_refine=true to get a plot of the refinement levels of the given function.
References madness::WorldGopInterface::barrier(), f, madness::WorldGopInterface::fence(), filename, madness::World::gop, imag(), MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, PROFILE_FUNC, madness::World::rank(), and real().
plotvtk_end()
template<std::size_t NDIM> void madness::plotvtk_end (World & world, const char * filename, bool binary = false)
Writes the footer information of a VTK file for plotting in an external post-processing package (such as Paraview)
Parameters
world World communicator
filename Name of VTK file
binary (Optional) Boolean indicating whether to print in binary
References f, madness::WorldGopInterface::fence(), filename, madness::World::gop, MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, PROFILE_FUNC, and madness::World::rank().
PM_q()
static double madness::PM_q (const tensorT & S, const double *MADNESS_RESTRICT Ci, const double *MADNESS_RESTRICT Cj, int lo, int nbf) inline static
References lo, and mu.
Referenced by madness::SystolicPMOrbitalLocalize::localize_PM_ij().
pop()
static double madness::pop (std::vector< double > & v) static
References MADNESS_ASSERT.
Referenced by madness::FunctionImpl< Q, NDIM >::apply_1d_realspace_push_op(), madness::Displacements< NDIM >::Displacements(), END_TIMER(), madness::FunctionCommonData< Q, NDIM >::get(), madness::GaussianConvolution1DCache< Q >::get(), madness::WorldObject< TestFutureForwarding >::is_ready(), madness::Displacements< NDIM >::make_disp_periodicsum(), and madness::WorldObject< TestFutureForwarding >::process_pending().
position_stream()
std::istream & madness::position_stream (std::istream & f, const std::string & tag)
References errmsg(), f, and MADNESS_EXCEPTION.
Referenced by madness::CCParameters::CCParameters(), main(), plot_cubefile(), plot_plane(), madness::Molecule::read(), madness::BasisFunctions::read_basis_from_file(), madness::BasisFunctions::read_contracted_basis_from_file(), MolecularEntity::read_file(), madness::ElectronicStructureParams::read_file(), and madness::QCCalculationParametersBase::read_internal().
power() [1/2]
template<int D> int madness::power (int base = 2) inline
References pow().
power() [2/2]
template<int N, class T > T madness::power (T const x)
References madness::detail::helper< T, N >::pow().
power< 0 >()
template<> int madness::power< 0 > (int base) inline
power< 1 >()
template<> int madness::power< 1 > (int base) inline
power< 10 >()
template<> int madness::power< 10 > (int base) inline
References power< 2 >(), and power< 5 >().
power< 12 >()
template<> int madness::power< 12 > (int base) inline
References power< 3 >(), and power< 4 >().
power< 2 >()
template<> int madness::power< 2 > (int base) inline
Referenced by power< 10 >(), power< 4 >(), power< 5 >(), power< 6 >(), power< 8 >(), madness::Polynomial< N >::Spp_div_S(), madness::Polynomial< N >::Srr_div_S(), madness::Polynomial< N >::Srrr_div_S(), and madness::Polynomial< N >::U2X_spherical().
power< 3 >()
template<> int madness::power< 3 > (int base) inline
Referenced by power< 12 >(), power< 5 >(), power< 6 >(), power< 7 >(), power< 9 >(), madness::GradientalGaussSlater::Srrr_div_S(), madness::Polynomial< N >::Srrr_div_S(), and madness::Polynomial< N >::U2X_spherical().
power< 4 >()
template<> int madness::power< 4 > (int base) inline
References power< 2 >().
Referenced by power< 12 >(), power< 7 >(), power< 8 >(), madness::GradientalGaussSlater::Srr_div_S(), madness::GradientalGaussSlater::Srrr_div_S(), and madness::Polynomial< N >::U2X_spherical().
power< 5 >()
template<> int madness::power< 5 > (int base) inline
References power< 2 >(), and power< 3 >().
Referenced by power< 10 >(), and madness::Polynomial< N >::U2X_spherical().
power< 6 >()
template<> int madness::power< 6 > (int base) inline
References power< 2 >(), and power< 3 >().
Referenced by madness::GradientalGaussSlater::Srrr_div_S().
power< 7 >()
template<> int madness::power< 7 > (int base) inline
References power< 3 >(), and power< 4 >().
power< 8 >()
template<> int madness::power< 8 > (int base) inline
References power< 2 >(), and power< 4 >().
power< 9 >()
template<> int madness::power< 9 > (int base) inline
References power< 3 >().
print_meminfo()
template<typename String > void madness::print_meminfo (int rank, const String & tag, const std::string filename_prefix = std::string("MEMORY"))
print aggregate memory stats to file filename_prefix.<rank> , tagged with tag
Parameters
[in] rank process rank
[in] tag record tag as any string type, e.g. const char[] , std::string , or std::wstring
[in] filename_prefix file name prefix; the default value is "MEMORY"
Note
To make print_meminfo() usable must set the ENABLE_MEM_PROFILE CMake cache variable to ON; this makes print_meminfo() enabled by default. To disable/enable programmatically use print_meminfo_disable()/print_meminfo_enable() .
must set global locale properly with std::locale::global() if tag has nontrivial encoding
Warning
this does not fence, it is up to the user to ensure proper synchronization
References filename, and print_meminfo_enabled().
Referenced by madness::SCF::apply_potential(), madness::SCF::apply_potential_response(), madness::SCF::calc_dipole_mo(), madness::SCF::calc_djkmo(), madness::SCF::calc_dpolar(), madness::SCF::calc_rhs(), madness::SCF::calc_xc_function(), madness::SCF::initial_guess(), main(), madness::SCF::make_BSHOperatorPtr(), madness::SCF::make_density_ground(), MiniDFT::makeao(), madness::SCF::polarizability(), madness::SCF::residual_response(), and madness::SCF::solve().
print_meminfo_disable()
void madness::print_meminfo_disable ()
disables print_meminfo() profiling (i.e. calling it is a no-op)
References madness::detail::print_meminfo_flag_accessor().
print_meminfo_enable()
void madness::print_meminfo_enable ()
enables print_meminfo() profiling
Note
print_meminfo() profiling is on by default.
References madness::detail::print_meminfo_flag_accessor().
print_meminfo_enabled()
bool madness::print_meminfo_enabled ()
Returns
true if print_meminfo() will generate profiling data.
References madness::detail::print_meminfo_flag_accessor().
Referenced by print_meminfo().
print_seq() [1/4]
template<typename A , typename B , typename C , typename D > void madness::print_seq (World & world, const A & a, const B & b, const C & c, const D & d)
Sequentially ordered printing of (serializable) data from every process.
Collective, no fence.
Template Parameters
A Type of data 1.
B Type of data 2.
C Type of data 3.
D Type of data 4.
Parameters
[in] world The World object.
[in] a Data 1.
[in] b Data 2.
[in] c Data 3.
[in] d Data 4.
References a, aa, b, c, cc, d(), p(), print(), madness::World::rank(), and madness::World::size().
print_seq() [2/4]
template<typename A , typename B , typename C > void madness::print_seq (World & world, const A & a, const B & b, const C & c)
Sequentially ordered printing of (serializable) data from every process.
Collective, no fence.
Template Parameters
A Type of data 1.
B Type of data 2.
C Type of data 3.
Parameters
[in] world The World object.
[in] a Data 1.
[in] b Data 2.
[in] c Data 3.
References a, aa, b, c, cc, p(), print(), madness::World::rank(), and madness::World::size().
print_seq() [3/4]
template<typename A , typename B > void madness::print_seq (World & world, const A & a, const B & b)
Sequentially ordered printing of (serializable) data from every process.
Collective, no fence.
Template Parameters
A Type of data 1.
B Type of data 2.
Parameters
[in] world The World object.
[in] a Data 1.
[in] b Data 2.
References a, aa, b, p(), print(), madness::World::rank(), and madness::World::size().
print_seq() [4/4]
template<typename A > void madness::print_seq (World & world, const A & a)
Sequentially ordered printing of (serializable) data from every process.
Collective, no fence.
Template Parameters
A Type of data 1.
Parameters
[in] world The World object.
[in] a Data 1.
References a, aa, p(), print(), madness::World::rank(), and madness::World::size().
print_size()
template<typename T , std::size_t NDIM> void madness::print_size (World & world, const std::vector< Function< T, NDIM > > & v, const std::string & msg = "vectorfunction")
References madness::World::rank().
Referenced by madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::CCPair::info(), madness::Zcis::iterate(), madness::CC2::iterate_singles(), madness::Zcis::make_guess(), madness::CCPairFunction::print_size(), madness::TDHF::print_xfunctions(), and madness::F12Potentials::read_cabs_from_file().
print_stats()
void madness::print_stats (World & world)
Print miscellaneous stats on a World.
This requires collective operations within the World.
Parameters
[in] world The World to analyze.
References cpu_time(), end_papi_measurement(), madness::WorldGopInterface::fence(), get_papi_measurement(), madness::RMI::get_stats(), madness::ThreadPool::get_stats(), madness::World::gop, madness::WorldGopInterface::max(), madness::RMIStats::max_serv_send_q, madness::WorldGopInterface::min(), madness::RMIStats::nbyte_recv, madness::RMIStats::nbyte_sent, madness::RMIStats::nmsg_recv, madness::RMIStats::nmsg_sent, NUMEVENTS, madness::WorldMemInfo::print(), madness::WorldProfile::print(), q(), madness::World::rank(), madness::World::size(), madness::ThreadPool::size(), madness::WorldGopInterface::sum(), wall_time(), and world_mem_info().
Referenced by main(), and propagate().
project()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::project (const Function< T, NDIM > & other, int k = FunctionDefaults<NDIM>::get_k(), double thresh = FunctionDefaults<NDIM>::get_thresh(), bool fence = true)
References madness::Function< T, NDIM >::get_impl(), k, PROFILE_FUNC, madness::Function< T, NDIM >::reconstruct(), thresh, and madness::Function< T, NDIM >::world().
Referenced by smooth< T, NDIM >::cut_oscillations(), doit(), MiniDFT::doit(), smooth< T, NDIM >::linearize(), Calculation::load_mos(), madness::SCF::load_mos(), madness::Solver< T, NDIM >::load_orbitals(), main(), smooth< T, NDIM >::make_inv_mask(), smooth< T, NDIM >::make_mask(), madness::MolecularOrbitals< T, NDIM >::post_process_mos(), madness::SCF::project(), madness::FunctionImpl< Q, NDIM >::project_refine_op(), madness::GTHPseudopotential< Q >::reproject(), madness::Solver< T, NDIM >::reproject(), madness::Nemo::smoothen(), and madness::FunctionImpl< Q, NDIM >::sock_it_to_me_too().
Q2()
tensorT madness::Q2 (const tensorT & s)
Given overlap matrix, return rotation with 2nd order error to orthonormalize the vectors.
References madness::BaseTensor::dim().
Referenced by madness::SCF::orthonormalize().
Q3()
tensorT madness::Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::BaseTensor::dim(), madness::Tensor< T >::gaxpy(), inner(), and madness::Tensor< T >::scale().
Referenced by Calculation::load_mos().
qm_1d_free_particle_propagator()
Convolution1D< double_complex > * madness::qm_1d_free_particle_propagator (int k, double bandlimit, double timestep, double width)
References k.
Referenced by MAKE_PROPAGATOR(), madness::SCF::propagate(), propagate(), qm_free_particle_propagator(), qm_free_particle_propagatorPtr(), test_chin_chen(), test_qm(), and test_trotter().
qm_free_particle_propagator()
template<std::size_t NDIM> SeparatedConvolution< double_complex, NDIM > madness::qm_free_particle_propagator (World & world, int k, double bandlimit, double timestep)
References BC_FREE, madness::FunctionDefaults< NDIM >::get_cell_min_width(), k, q(), and qm_1d_free_particle_propagator().
qm_free_particle_propagatorPtr()
template<std::size_t NDIM> SeparatedConvolution< double_complex, NDIM > * madness::qm_free_particle_propagatorPtr (World & world, int k, double bandlimit, double timestep)
References BC_FREE, madness::FunctionDefaults< NDIM >::get_cell_min_width(), k, q(), and qm_1d_free_particle_propagator().
qr() [1/2]
template<typename T > void madness::qr (Tensor< T > & A, Tensor< T > & R)
compute the QR decomposition of the matrix A
QR decomposition.
Parameters
[in,out] A on entry the (n,m) matrix to be decomposed on exit the Q matrix
[out] R the (n,n) matrix R (square form)
References lq_result(), m, R, TENSOR_ASSERT, and transpose().
Referenced by test_qr().
qr() [2/2]
template void madness::qr (Tensor< double > & A, Tensor< double > & R)
quiet()
bool madness::quiet ()
Check if the MADNESS runtime was initialized for quiet operation.
Returns
true if madness::initialize was called with quiet=true .
Referenced by madness::ThreadPool::begin(), finalize(), and initialize().
RandomValue()
template<class T > T madness::RandomValue ()
Random value that wraps the default Fibonacci generator.
RandomValue< double >()
template<> double madness::RandomValue< double > ()
Random double.
References default_random_generator, and madness::Random::get().
Referenced by madness::SCF::localize_boys(), madness::SCF::localize_new(), BoysLocalization::operator()(), madness::MyPmap< D >::prepare_not_so_simple_map(), random_gaussian(), RandomGaussian(), RandomValue< double_complex >(), RandomValue< int >(), and RandomValue< long >().
RandomValue< double_complex >()
template<> double_complex madness::RandomValue< double_complex > ()
Random double_complex.
References RandomValue< double >().
RandomValue< float >()
template<> float madness::RandomValue< float > ()
Random float.
References default_random_generator, and madness::Random::get().
Referenced by RandomValue< float_complex >().
RandomValue< float_complex >()
template<> float_complex madness::RandomValue< float_complex > ()
Random float_complex.
References RandomValue< float >().
RandomValue< int >()
template<> int madness::RandomValue< int > ()
Random int.
References RandomValue< double >().
Referenced by madness::FunctionImpl< Q, NDIM >::vtransform_doit().
RandomValue< long >()
template<> long madness::RandomValue< long > ()
Random long.
References RandomValue< double >().
Referenced by test_qr().
RandomVector()
template<class T > void madness::RandomVector (int n, T * t)
RandomVector< double >()
template<> void madness::RandomVector< double > (int n, double * t)
References default_random_generator, and madness::Random::getv().
RandomVector< double_complex >()
template<> void madness::RandomVector< double_complex > (int n, double_complex * t)
References default_random_generator, and madness::Random::getv().
RandomVector< float >()
template<> void madness::RandomVector< float > (int n, float * t)
References default_random_generator, and madness::Random::getv().
RandomVector< float_complex >()
template<> void madness::RandomVector< float_complex > (int n, float_complex * t)
References default_random_generator, and madness::Random::getv().
rank_revealing_decompose()
template<typename T > long madness::rank_revealing_decompose (Tensor< T > & A, Tensor< T > & U, const double thresh, Tensor< typename Tensor< T >::scalar_type > & s, Tensor< T > & scr)
decompose the input tensor A into U and V, skipping singular vectors of small singular values. One deep copy/allocation for U is performed
Parameters
[in,out] A the input matrix, on exit the matrix VT (right sing. vectors)
[out] U contiguous new tensor holding the left sing. vectors
[in] thresh threshold for truncation of the singular vectors
[in] s scratch tensor for the singular values, dimension min(n,m)
[in] scr scratch tensor the dimension of the scratch tensor may be computed as long lwork=std::max(3*std::min(m,n)+std::max(m,n),5*std::min(m,n)) + n*m;
References _(), copy(), madness::Tensor< T >::flat(), m, MADNESS_ASSERT, max, madness::SRConf< T >::max_sigma(), R1, madness::BaseTensor::size(), svd_result(), and thresh.
Referenced by apply().
read_atom()
static AtomCore madness::read_atom (TiXmlElement * e, unsigned int atn, double eprec) static
References madness::AtomCore::atomic_number, e(), MADNESS_EXCEPTION, read_orbital(), and read_potential().
Referenced by madness::CorePotentialManager::read_file().
read_data() [1/2]
static bool madness::read_data () static
read_data loads the precomputed Gauss-Legendre data
References data_is_read, f, filename, max_npt, points, and weights.
Referenced by gauss_legendre(), load_coeffs(), load_quadrature(), and madness::guessfactory::PolynomialFunctor::read_string().
read_data() [2/2]
static bool madness::read_data (int k) static
References _cread, autocorr_filename, ij(), k, kread, p(), parity(), and test_autoc().
read_orbital()
static bool madness::read_orbital (TiXmlElement * e, AtomCore & ac) static
References c, e(), madness::AtomCore::ncore, madness::AtomCore::orbital, p(), and type().
Referenced by read_atom().
read_potential()
static bool madness::read_potential (TiXmlElement * elem, AtomCore & ac, double eprec) static
References madness::CorePotential::A, madness::CorePotential::alpha, madness::AtomCore::atomic_number, c, e(), madness::CorePotential::eprec, madness::CorePotential::l, madness::CorePotential::n, madness::AtomCore::ncore, p(), madness::AtomCore::potential, madness::CorePotential::rcut, madness::CorePotential::rcut0, and smoothing_parameter().
Referenced by read_atom().
read_twoscale()
static bool madness::read_twoscale (int kmax) static
References cache, checksum_file(), e(), madness::twoscale_cache_class::g0, madness::twoscale_cache_class::g1, madness::twoscale_cache_class::h0, madness::twoscale_cache_class::h1, k, kmax, loaded, MADNESS_CHECK, phase(), readmat(), and twoscale_filename.
Referenced by load_coeffs(), and two_scale_coefficients().
readmat()
static Tensor<double> madness::readmat (int k, FILE * file) static
References a, c, and k.
Referenced by read_twoscale().
real() [1/5]
static double madness::real (double x) inline
Referenced by madness::Solver< T, NDIM >::apply_hf_exchange3(), madness::Solver< T, NDIM >::apply_hf_exchange4(), madness::Solver< T, NDIM >::calculate_kinetic_energy(), madness::Znemo::canonicalize(), madness::guessfactory::compute_centroids(), madness::Znemo::compute_energy(), madness::Znemo::compute_linear_moment(), madness::Znemo::compute_magnetic_potential_expectation(), madness::Zcis::compute_residuals(), madness::Znemo::compute_residuals(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), energy(), GMRES(), madness::Solver< T, NDIM >::initial_guess(), madness::Zcis::iterate(), madness::Znemo::iterate(), main(), madness::Zcis::make_guess(), myreal(), madness::VectorSpace< T, NDIM >::norm(), madness::real_op< Q, NDIM >::operator()(), madness::detail::realop< NDIM >::operator()(), plot_line_print_value(), plotvtk_data(), print_stats(), real(), tensor_xreal(), test_kinetic(), and test_wannier().
real() [2/5]
template<typename Q , int NDIM> Function<typename TensorTypeData<Q>::scalar_type,NDIM> madness::real (const Function< Q, NDIM > & func)
References func(), and unary_op_coeffs().
real() [3/5]
template<typename T , std::size_t NDIM> std::vector<Function<typename Tensor<T>::scalar_type,NDIM> > madness::real (const std::vector< Function< T, NDIM > > & v, bool fence = true)
return the real parts of the vector's function (if complex)
References NDIM, and real().
real() [4/5]
template<std::size_t NDIM> Function<double,NDIM> madness::real (const Function< double_complex, NDIM > & z, bool fence = true)
Returns a new function that is the real part of the input.
References unary_op_coeffs().
real() [5/5]
template<std::size_t NDIM> Function<double,NDIM> madness::real (const Function< double, NDIM > & z, bool fence = true)
Returns a new function that is the real part of the input.
References copy().
reconstruct() [1/2]
template<typename T , std::size_t NDIM> void madness::reconstruct (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Reconstruct a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Referenced by abssq(), apply(), apply_potential(), WSTFunctional::apply_xc(), madness::SCF::calc_dipole_mo(), madness::SCF::calc_exchange_function(), madness::SCF::calc_xc_function(), madness::Solver< T, NDIM >::compute_rho(), cross(), div(), doit(), hamiltonian_matrix(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), madness::Kinetic< double, 3 >::kinetic_energy_matrix(), kinetic_energy_matrix(), MiniDFT::kinetic_energy_matrix(), madness::SCF::kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), Calculation::load_mos(), madness::SCF::load_mos(), madness::Solver< T, NDIM >::load_orbitals(), madness::SCF::make_density(), madness::TDHF::make_mo_bra(), madness::TDHF::make_mo_ket(), madness::TDHF::make_old_guess(), madness::FunctionImpl< Q, NDIM >::make_redundant(), Calculation::make_reference(), moments(), mul(), mul_sparse(), nonstandard(), madness::Nuclear::operator()(), madness::Lz::operator()(), madness::DNuclear::operator()(), madness::SCF::orthogonalize_response(), Calculation::plot_p(), madness::MolecularOrbitals< T, NDIM >::post_process_mos(), madness::SCF::project(), refine_to_common_level(), madness::Solver< T, NDIM >::reproject(), rot(), and madness::SCF::twoint().
reconstruct() [2/2]
template<typename T , std::size_t NDIM> void madness::reconstruct (World & world, const std::vector< Function< T, NDIM > > & v, unsigned int blk = 1, bool fence = true)
Reconstruct a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
redirectio()
void madness::redirectio (const World & world, bool split = false)
redirects standard output and error to rank-specific files
Parameters
[in] world the World object that determines rank of this process
[in] split if true, write standard output to log.<rank> and standard error to err.<rank>, otherwise write both standard output and error to log.<rank>. The default is false.
References filename, MADNESS_EXCEPTION, madness::World::mpi, madness::WorldMpiInterface::rank(), and split().
Referenced by main(), and startup().
reduce() [1/2]
template<class T > GenTensor<T> madness::reduce (std::list< GenTensor< T > > & addends, double eps, bool are_optimal = false)
References copy().
Referenced by madness::SeparatedConvolution< T, NDIM >::apply2().
reduce() [2/2]
template<typename T > LowRankTensor<T> madness::reduce (std::list< LowRankTensor< T > > & addends, double eps, bool are_optimal = false)
add all the GenTensors of a given list
If there are many tensors to add it's beneficial to do a sorted addition and start with those tensors with low ranks
Parameters
[in] addends a list with gentensors of same dimensions; will be destroyed upon return
[in] eps the accuracy threshold
[in] are_optimal flag if the GenTensors in the list are already in SVD format (if TT_2D)
Returns
the sum GenTensor of the input GenTensors
References copy(), and madness::LowRankTensor< T >::reduce_rank().
refine()
template<typename T , std::size_t NDIM> void madness::refine (World & world, const std::vector< Function< T, NDIM > > & vf, bool fence = true)
refine the functions according to the autorefine criteria
References f, madness::WorldGopInterface::fence(), and madness::World::gop.
Referenced by div(), grad(), grad_ble_one(), grad_ble_two(), grad_bpsline_two(), grad_bspline_one(), grad_bspline_three(), madness::Nemo::make_density(), madness::Nemo::make_incomplete_hessian(), madness::FunctionDefaults< NDIM >::print(), rot(), madness::FunctionDefaults< NDIM >::set_defaults(), and test().
refine_to_common_level()
template<typename T , std::size_t NDIM> void madness::refine_to_common_level (World & world, std::vector< Function< T, NDIM > > & vf, bool fence = true)
refine all functions to a common (finest) level
if functions are not initialized (impl==NULL) they are ignored
References c, std::distance(), reconstruct(), VERIFY_TREE, and verify_tree().
Referenced by WSTFunctional::apply_xc(), madness::XCOperator::apply_xc_kernel(), madness::XCOperator::compute_xc_energy(), madness::XCOperator::make_xc_potential(), smooth< T, NDIM >::merge_functions(), madness::FunctionImpl< Q, NDIM >::refine_to_common_level(), test_math(), test_multi_to_multi_op(), and test_XCOperator().
reset_papi_measurement()
void madness::reset_papi_measurement () inline
rot()
template<typename T , std::size_t NDIM> std::vector<Function<T,NDIM> > madness::rot (const std::vector< Function< T, NDIM > > & v, bool do_refine = false, bool fence = true)
shorthand rot operator
returns the cross product of nabla with a vector f
Parameters
[in] f the vector of functions on which the rot operator works on
[in] refine refinement before diff'ing makes the result more accurate
[in] fence fence after completion; currently always fences
Returns
the vector {}{ x_i} f TODO: add this to operator fusion
References apply(), d(), grad(), MADNESS_ASSERT, NDIM, reconstruct(), and refine().
Referenced by madness::Znemo::compute_current_density(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), fixphases(), and test_rot().
row_distributed_matrix()
template<typename T > DistributedMatrix<T> madness::row_distributed_matrix (World & world, int64_t n, int64_t m, int64_t rowtile = 0)
Generates an (n,m) matrix distributed by rows (column dimension is not distributed)
Parameters
[in] world The world
[in] n The column (first) dimension
[in] m The row (second) dimension
[in] rowtile Tile size for row (default is to use all processes)
Returns
A new zero matrix with the requested dimensions and distribution
References m, and row_distributed_matrix_distribution().
row_distributed_matrix_distribution()
static DistributedMatrixDistribution madness::row_distributed_matrix_distribution (World & world, int64_t n, int64_t m, int64_t rowtile) inline static
Generates an (n,m) matrix distribution distributed by rows (column dimension is not distributed)
Parameters
[in] world The world
[in] n The column (first) dimension
[in] m The row (second) dimension
[in] rowtile Tile size for row (default is to use all processes)
Returns
An object encoding the dimension and distribution information
References m, and madness::World::size().
Referenced by row_distributed_matrix().
rr_cholesky() [1/3]
template<typename T > void madness::rr_cholesky (Tensor< T > & A, typename Tensor< T >::scalar_type tol, Tensor< integer > & piv, int & rank)
Compute the rank-revealing Cholesky factorization.
rank-revealing Cholesky factorization
Compute the rank-revealing Cholesky factorization of the symmetric positive definite matrix A
For memory efficiency A is modified inplace. Its upper triangle will hold the result and the lower triangle will be zeroed such that input = inner(transpose(output),output).
Parameters
[in] A the positive-semidefinite matrix to be decomposed
[in] tol linear dependency threshold for discarding columns of A
[in] piv pivot vector, its 1-rank entries are the orthogonal vectors
[in] rank numerical rank of A (wrt tol)
References mask_info(), pstrf_(), madness::Tensor< T >::ptr(), and TENSOR_ASSERT.
Referenced by madness::projector_irrep::apply_symmetry_operators(), madness::PNO::orthonormalize_cholesky(), orthonormalize_rrcd(), and test_rr_cholesky().
rr_cholesky() [2/3]
template void madness::rr_cholesky (Tensor< double > & A, typename Tensor< double >::scalar_type tol, Tensor< integer > & piv, int & rank)
rr_cholesky() [3/3]
template void madness::rr_cholesky (Tensor< double_complex > & A, typename Tensor< double_complex >::scalar_type tol, Tensor< integer > & piv, int & rank)
rsquared()
static double madness::rsquared (const coordT & r) static
Referenced by madness::SCF::analyze_vectors(), and smoothed_density().
save()
template<class T , std::size_t NDIM> void madness::save (const Function< T, NDIM > & f, const std::string name)
References f.
Referenced by madness::Znemo::analyze(), madness::TDHF::analyze(), madness::Nemo::compute_all_cphf(), madness::Znemo::compute_current_density(), madness::Zcis::compute_potentials(), madness::OEP::compute_slater_potential(), madness::Zcis::iterate(), madness::CC2::iterate_pair(), madness::Nemo::kinetic_energy_potential(), main(), madness::Nemo::make_laplacian_density(), madness::Znemo::save_orbitals(), madness::CC2::solve_cc2(), madness::CC2::solve_mp2(), madness::OEP::solve_oep(), madness::Znemo::test_compute_current_density(), madness::CC2::update_constant_part_adc2(), madness::CC2::update_constant_part_cc2_gs(), madness::CC2::update_constant_part_cispd(), madness::CC2::update_constant_part_lrcc2(), madness::CC2::update_constant_part_mp2(), and madness::Nemo::value().
save_function()
template<typename T , size_t NDIM> void madness::save_function (const std::vector< Function< T, NDIM > > & f, const std::string name)
save a vector of functions
References f, print(), and madness::World::rank().
Referenced by madness::Zcis::compare_to_file(), madness::PNO::save_pnos(), solve(), test_adaptive_tree(), and test_multiply().
scale() [1/4]
template<typename T , typename Q , std::size_t NDIM> void madness::scale (World & world, std::vector< Function< T, NDIM > > & v, const std::vector< Q > & factors, const unsigned int blk = 1, const bool fence = true)
Scales inplace a vector of functions by distinct values.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
scale() [2/4]
template<typename T , typename Q , std::size_t NDIM> void madness::scale (World & world, std::vector< Function< T, NDIM > > & v, const Q factor, const unsigned int blk = 1, const bool fence = true)
Scales inplace a vector of functions by the same.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
scale() [3/4]
template<typename T , typename Q , std::size_t NDIM> void madness::scale (World & world, std::vector< Function< T, NDIM > > & v, const std::vector< Q > & factors, bool fence = true)
Scales inplace a vector of functions by distinct values.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Referenced by madness::Znemo::analyze(), apply(), madness::TDHF::apply_G(), apply_U_mix(), madness::SCF::calc_response_function(), madness::FunctionImpl< Q, NDIM >::coeffs2values(), madness::OEP::compute_average_I(), madness::Diamagnetic_potential_factor::compute_lz_commutator(), madness::Nemo::compute_nemo_potentials(), madness::Zcis::compute_potentials(), madness::SCF::compute_residual(), madness::F12Potentials::convolve_with_fU(), madness::FunctionImpl< Q, NDIM >::do_binary_op(), madness::FunctionImpl< Q, NDIM >::do_mul(), madness::FunctionImpl< Q, NDIM >::err_box(), gauss_legendre_numeric(), madness::TDHF::get_tda_potential(), madness::CCPairFunction::invert_sign(), madness::Znemo::iterate(), madness::CC2::iterate_singles(), madness::Nemo::kinetic_energy_potential(), main(), madness::TDHF::make_old_guess(), madness::SCF::matrix_exponential(), matrix_exponential(), madness::Solver< T, NDIM >::matrix_exponential(), moments(), madness::FunctionImpl< Q, NDIM >::mul(), madness::EigSolver< T, NDIM >::multi_solve(), madness::NemoBase::normalize(), madness::Zcis::normalize(), normalize(), madness::FunctionImpl< Q, NDIM >::NS_fcube_for_mul(), madness::FunctionImpl< Q, NDIM >::NScoeffs2values(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), operator*(), madness::FunctionImpl< Q, NDIM >::phi_for_mul(), plot_plane(), madness::FunctionImpl< Q, NDIM >::print_plane_local(), q_c(), madness::Molecule::read(), MolecularEntity::read_file(), scale(), madness::Nemo::solve(), madness::Solver< T, NDIM >::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), SVPESolver::SVPESolver(), testNavierStokes(), update(), MiniDFT::update(), madness::PNO::update_pno(), madness::FunctionImpl< Q, NDIM >::values2coeffs(), and madness::FunctionImpl< Q, NDIM >::values2NScoeffs().
scale() [4/4]
template<typename T , typename Q , std::size_t NDIM> void madness::scale (World & world, std::vector< Function< T, NDIM > > & v, const Q factor, bool fence = true)
Scales inplace a vector of functions by the same.
References madness::WorldGopInterface::fence(), madness::World::gop, PROFILE_BLOCK, and scale().
serialize_am_args() [1/2]
template<typename Archive > void madness::serialize_am_args (Archive &&) inline
Terminate argument serialization.
Referenced by new_am_arg(), and serialize_am_args().
serialize_am_args() [2/2]
template<typename Archive , typename T , typename... argT> void madness::serialize_am_args (Archive && archive, T && t, argT &&... args) inline
Argument serialization.
References serialize_am_args().
set_thresh()
template<typename T , std::size_t NDIM> void madness::set_thresh (World & world, std::vector< Function< T, NDIM > > & v, double thresh, bool fence = true)
Sets the threshold in a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and thresh.
Referenced by madness::SCF::compute_residual(), madness::Znemo::get_initial_orbitals(), madness::SCF::load_mos(), main(), madness::TDHF::make_mo_bra(), madness::TDHF::make_mo_ket(), madness::MolecularOrbitals< T, NDIM >::post_process_mos(), madness::Nemo::set_protocol(), madness::PNO::solve(), and smooth< T, NDIM >::test_1d().
sim_to_user()
template<std::size_t NDIM> static void madness::sim_to_user (const Vector< double, NDIM > & xsim, Vector< double, NDIM > & xuser) static
Convert simulation coords ([0,1]^ndim) to user coords (FunctionDefaults<NDIM>::get_cell())
References madness::FunctionDefaults< NDIM >::get_cell(), and NDIM.
simpt2key()
template<typename T , std::size_t NDIM> static Key<NDIM> madness::simpt2key (const Vector< T, NDIM > & pt, Level n) inline static
Returns the box at level n that contains the given point in simulation coordinates
Parameters
[in] pt point in simulation coordinates
[in] n the level of the box
References NDIM, and pow().
Referenced by madness::Specialbox_op< T, NDIM >::check_special_points(), madness::NuclearCuspyBox_op< T, NDIM >::operator()(), and madness::FunctionImpl< Q, NDIM >::project_refine_op().
size_of()
double madness::size_of (const intermediateT & im)
Returns the size of an intermediate.
References madness::Pairs< T >::allpairs.
Referenced by madness::CCConvolutionOperator::info().
slater_radius()
double madness::slater_radius (int atomic_number)
collection of slater radii needed to calculate R1 and R2; The Journal of Chemical Physics 41, 3199 (1964); doi: 10.1063/1.1725697
Parameters
[in] atomic_number atomic_number of atom
[out] slater radius corresponding to atomic_number
References MADNESS_EXCEPTION.
Referenced by main(), and make_atom_vec().
SlaterF12Operator()
static SeparatedConvolution<double,3> madness::SlaterF12Operator (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with (1 - exp(-mu*r))/(2 mu) in 3D.
References BC_PERIODIC, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), and madness::GFit< T, NDIM >::SlaterFit().
SlaterF12OperatorPtr()
static SeparatedConvolution<double,3>* madness::SlaterF12OperatorPtr (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with (1 - exp(-mu*r))/(2 mu) in 3D.
References BC_PERIODIC, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), and madness::GFit< T, NDIM >::SlaterFit().
Referenced by madness::F12Potentials::F12Potentials(), and madness::CCConvolutionOperator::init_op().
SlaterOperator()
static SeparatedConvolution<double,3> madness::SlaterOperator (World & world, double mu, double lo, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution with exp(-mu*r) in 3D Note that the 1/(2mu) factor of SlaterF12Operator is not included, this is just the exponential function
References BC_PERIODIC, fit(), madness::FunctionDefaults< NDIM >::get_cell_width(), madness::SeparatedConvolution< Q, NDIM >::is_slaterf12, k, lo, madness::Tensor< T >::max(), mu, madness::Tensor< T >::normf(), and madness::GFit< T, NDIM >::SlaterFit().
Referenced by madness::F12Potentials::F12Potentials().
smoothed_density()
double madness::smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
Invoke as rho(r/c)/c^3 where c is the radius of the smoothed volume.
References madness::constants::pi, and pow().
Referenced by madness::Molecule::mol_nuclear_charge_density(), MolecularEntity::nuclear_charge_density(), and madness::Molecule::nuclear_charge_density().
smoothed_potential()
double madness::smoothed_potential (double r)
Smoothed 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References a, and r2().
Referenced by madness::Molecule::atomic_attraction_potential(), madness::CorePotential::eval(), madness::CorePotential::eval_derivative(), MolecularEntity::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential_second_derivative(), madness::AtomicAttractionFunctor::operator()(), PotentialBasisFunctor::operator()(), NcOverR::operator()(), madness::PseudoNuclearCorrelationFactor::Spp_div_S(), V(), V_func_be(), V_func_he(), Ve(), and Vn().
smoothing_parameter()
double madness::smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, e(), pow(), and Z.
Referenced by MolecularEntity::add_atom(), madness::Molecule::add_atom(), Calculation::make_reference(), madness::Molecule::read_core_file(), read_potential(), madness::Molecule::set_eprec(), madness::CorePotentialManager::set_eprec(), madness::PseudoNuclearCorrelationFactor::Spp_div_S(), V_func_be(), and V_func_he().
SmoothingOperator()
template<std::size_t NDIM> static SeparatedConvolution<double,NDIM> madness::SmoothingOperator (World & world, double eps, const BoundaryConditions< NDIM > & bc = FunctionDefaults<NDIM>::get_bc(), int k = FunctionDefaults<NDIM>::get_k()) inline static
Factory function generating separated kernel for convolution a normalized Gaussian (aka a widened delta function)
References L, NDIM, and pow().
SmoothingOperator3D()
static SeparatedConvolution<double,3> madness::SmoothingOperator3D (World & world, double eps, const BoundaryConditions< 3 > & bc = FunctionDefaults<3>::get_bc(), int k = FunctionDefaults<3>::get_k()) inline static
Factory function generating separated kernel for convolution a normalized Gaussian (aka a widened delta function)
References L, and pow().
Referenced by dostuff(), and madness::Nemo::kinetic_energy_potential().
SPEC() [1/15]
madness::SPEC (int , long , long)
SPEC() [2/15]
madness::SPEC (int , float , float)
SPEC() [3/15]
madness::SPEC (int , double , double)
SPEC() [4/15]
madness::SPEC (int , float_complex , float_complex)
SPEC() [5/15]
madness::SPEC (int , double_complex , double_complex)
SPEC() [6/15]
madness::SPEC (long , float , float)
SPEC() [7/15]
madness::SPEC (long , double , double)
SPEC() [8/15]
madness::SPEC (long , float_complex , float_complex)
SPEC() [9/15]
madness::SPEC (long , double_complex , double_complex)
SPEC() [10/15]
madness::SPEC (float , double , double)
SPEC() [11/15]
madness::SPEC (float , float_complex , float_complex)
SPEC() [12/15]
madness::SPEC (float , double_complex , double_complex)
SPEC() [13/15]
madness::SPEC (double , float_complex , float_complex)
SPEC() [14/15]
madness::SPEC (double , double_complex , double_complex)
SPEC() [15/15]
madness::SPEC (float_complex , double_complex , double_complex)
square() [1/2]
template<typename T , std::size_t NDIM> std::vector< Function< T, NDIM > > madness::square (World & world, const std::vector< Function< T, NDIM > > & v, bool fence = true)
Computes the square of a vector of functions — q[i] = v[i]**2.
square() [2/2]
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::square (const Function< T, NDIM > & f, bool fence = true)
Create a new function that is the square of f - global comm only if not reconstructed.
References copy(), f, PROFILE_FUNC, and madness::Function< T, NDIM >::square().
Referenced by madness::OEP::compute_average_I(), madness::OEP::compute_Pauli_kinetic_density(), madness::EigSolver< T, NDIM >::compute_rho(), madness::OEP::compute_slater_potential(), madness::OEP::compute_total_kinetic_density(), main(), MiniDFT::make_density(), madness::SCF::make_density(), Calculation::make_reference(), nuclear_anchor_test(), madness::OEP::solve_oep(), test_he_potential(), and test_math().
standard() [1/2]
template<typename T , std::size_t NDIM> void madness::standard (World & world, std::vector< Function< T, NDIM > > & v, unsigned int blk = 1, bool fence = true)
Generates standard form of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
standard() [2/2]
template<typename T , std::size_t NDIM> void madness::standard (World & world, std::vector< Function< T, NDIM > > & v, bool fence = true)
Generates standard form of a vector of functions.
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Referenced by apply(), and madness::FunctionImpl< Q, NDIM >::make_redundant().
START_TIMER()
static void madness::START_TIMER (World & world) static
References cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and wall_time().
Referenced by madness::SCF::analyze_vectors(), KPeriodicBSHOperator::apply(), apply_potential(), madness::SCF::apply_potential(), madness::SCF::apply_potential_response(), madness::SCF::calc_djkmo(), madness::SCF::calc_xc_function(), madness::SCF::compute_residual(), madness::SCF::derivatives(), madness::SCF::dipole(), madness::SCF::dipole_matrix_elements(), madness::SCF::do_plots(), madness::SCF::get_fock_transformation(), madness::SCF::initial_guess(), madness::SCF::kinetic_energy_matrix(), madness::SCF::localize_boys(), madness::SCF::localize_new(), madness::SCF::localize_PM(), main(), make_coulomb_potential(), make_density(), madness::SCF::make_fock_matrix(), make_kinetic_matrix(), make_lda_potential(), madness::SCF::make_nuclear_potential(), Calculation::make_reference(), Calculation::make_Upsi(), makeao(), orthogonalize(), madness::SCF::orthonormalize(), madness::SCF::polarizability(), madness::SCF::solve(), test_coulomb(), test_cross(), test_diff(), test_inner(), test_op(), test_rot(), madness::SCF::update_response_subspace(), and madness::SCF::update_subspace().
startup()
void madness::startup (World & world, int argc, char ** argv, bool doprint = false)
References arg(), cpu_frequency(), madness::WorldGopInterface::fence(), gauss_legendre_test(), madness::World::gop, init_tensor_lapack(), initialize_legendre_stuff(), load_coeffs(), load_quadrature(), MADNESS_CHECK, print(), madness::World::rank(), redirectio(), madness::FunctionDefaults< NDIM >::set_defaults(), madness::World::size(), test_two_scale_coefficients(), time_transform(), and xterm_debug().
Referenced by main(), test_G_R_vectors(), test_gaussian_num_coeffs(), test_he(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), testNavierStokes(), and testPeriodicCoulomb3d().
stringify()
template<typename T > static std::string madness::stringify (T arg) static
References arg(), and MADNESS_EXCEPTION.
Referenced by madness::Nemo::compute_all_cphf(), madness::Nemo::compute_nemo_potentials(), madness::Zcis::compute_potentials(), smooth< T, NDIM >::gaussian_smoothing(), madness::BasisFunctions::guess_virtuals_internal(), madness::Zcis::iterate(), madness::CC2::iterate_pair(), madness::ElectronPair::load_pair(), main(), madness::guessfactory::make_auto_polynom_strings(), test_correlation_factor::make_test(), madness::CCFunction::name(), madness::CCPair::name(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), madness::Znemo::save_orbitals(), smooth< T, NDIM >::smooth_density_from_orbitals(), madness::Nemo::solve(), solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), madness::ElectronPair::store_pair(), smooth< T, NDIM >::test_1d(), test_adaptive_tree(), test_modified(), test_spherical_box(), and madness::Nemo::value().
sub() [1/3]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::sub (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true, unsigned int blk = 1)
Returns new vector of functions — q[i] = a[i] - b[i].
References a, b, compress(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, PROFILE_BLOCK, and sub().
sub() [2/3]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R), NDIM> > madness::sub (World & world, const std::vector< Function< T, NDIM > > & a, const std::vector< Function< R, NDIM > > & b, bool fence = true)
Returns new vector of functions — q[i] = a[i] - b[i].
References a, b, compress(), madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_ASSERT, PROFILE_BLOCK, and sub().
sub() [3/3]
template<typename L , typename R , std::size_t NDIM> Function<TENSOR_RESULT_TYPE(L,R),NDIM> madness::sub (const Function< L, NDIM > & left, const Function< R, NDIM > & right, bool fence = true)
Same as operator- but with optional fence and no automatic compression.
References gaxpy_oop(), L, R, and TENSOR_RESULT_TYPE().
Referenced by madness::TDHF::apply_G(), madness::Nemo::compute_nemo_potentials(), madness::SCF::compute_residual(), madness::Solver< T, NDIM >::compute_residual(), Calculation::compute_residuals(), madness::Znemo::do_step_restriction(), madness::SCF::do_step_restriction(), exchange_anchor_test(), madness::TDHF::get_tda_potential(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), madness::Nemo::kinetic_energy_potential(), madness::DNuclear::operator()(), operator-(), operator-(), operator-=(), q_c(), madness::SCF::residual_response(), madness::Nemo::solve(), sub(), update(), madness::SCF::update_response_subspace(), and madness::SubspaceK< T, NDIM >::update_subspace().
sum()
template<typename T , std::size_t NDIM> Function<T, NDIM> madness::sum (World & world, const std::vector< Function< T, NDIM > > & f, bool fence = true)
Returns new function — q = sum_i f[i].
References compress(), f, madness::WorldGopInterface::fence(), madness::Function< T, NDIM >::gaxpy(), and madness::World::gop.
Referenced by a(), madness::Molecule::atomic_attraction_potential(), b(), checksum_file(), madness::OEP::compute_average_I(), madness::F12Potentials::compute_cispd_f12_energies(), madness::NemoBase::compute_density(), madness::Nemo::compute_energy(), madness::Nemo::compute_energy_regularized(), madness::OEP::compute_kinetic_energy(), madness::OEP::compute_Pauli_kinetic_density(), madness::OEP::compute_total_kinetic_density(), div(), do_adq(), Node::do_sum(), doit(), dot(), dVdx(), dVdy(), dVdz(), errsq(), madness::FunctionImpl< Q, NDIM >::eval_cube(), madness::AtomicBasis::eval_guess_density(), AtomicBasis::eval_guess_density(), AtomicBasisSet::eval_guess_density(), madness::AtomicBasisSet::eval_guess_density(), ContractedGaussianShell::eval_radial(), madness::ContractedGaussianShell::eval_radial(), fit(), gauss_legendre_test(), gaussian_func(), madness::PNO::get_average_rank(), madness::WorldDCPmapInterface< Key< D > >::global_size(), guess(), guess1s(), guess2s(), madness::Nemo::hessian(), TTT::hugh(), madness::FunctionImpl< Q, NDIM >::inner_local(), inner_result(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), madness::Nemo::kinetic_energy_potential(), madness::WorldDCPmapInterface< Key< D > >::local_size(), main(), madness::TDHF::make_old_guess(), A::member(), madness::Molecule::molecular_core_potential(), mTxmT(), madness::SeparatedConvolution< T, NDIM >::munorm2_ns(), mxmT(), mxmT_reference(), madness::Molecule::n_core_orb_all(), madness::FunctionImpl< Q, NDIM >::norm_tree_op(), ContractedGaussianShell::normalize(), madness::ContractedGaussianShell::normalize(), MolecularEntity::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential(), madness::Molecule::nuclear_dipole(), madness::Molecule::nuclear_repulsion_derivative(), MolecularEntity::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_second_derivative(), MolecularGuessDensityFunctor::operator()(), madness::ComplexExp< NDIM >::operator()(), DerivativeGaussian< T, NDIM >::operator()(), AtomicBasisFunctor< Q >::operator()(), madness::WSTAtomicBasisFunctor::operator()(), HeElectronicChargeDensityIGuess< T, NDIM >::operator()(), Gaussian< T, NDIM >::operator()(), BoysLocalization::operator()(), HeNuclearChargeDensityIGuess< T, NDIM >::operator()(), NuclearDensityFunctor::operator()(), GaussianPotential::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()(), plot_line(), Calculation::plot_p(), madness::PNO::print_ranks(), madness::FunctionImpl< Q, NDIM >::real_size(), Adder::run(), madness::SDFEllipsoid::sdf(), madness::ConcurrentHashMap< void *, uniqueidT, hashvoidp >::size(), madness::FunctionImpl< Q, NDIM >::size(), Test7(), test_add(), testf(), MolecularEntity::total_nuclear_charge(), madness::Molecule::total_nuclear_charge(), madness::FunctionImpl< Q, NDIM >::trace_local(), madness::FunctionImpl< Q, NDIM >::tree_size(), and V().
svd() [1/3]
template<typename T > void madness::svd (const Tensor< T > & a, Tensor< T > & U, Tensor< typename Tensor< T >::scalar_type > & s, Tensor< T > & VT)
Compute the singluar value decomposition of an n-by-m matrix using *gesvd.
Computes singular value decomposition of matrix.
Returns via arguments U, s, VT where
A = U * diag(s) * VT for A real A = U * diag(s) * VH for A complex
or
UT * A * V = diag(s) for A real UH * A * V = diag(s) for A complex
If A is [m,n] and r=min(m,n) then we have U[m,r], s[r], and VT[r,n]
On failure, throws TensorException with value set to Lapack's info.
References a, copy(), dgesvd_(), m, mask_info(), max, madness::Tensor< T >::ptr(), and TENSOR_ASSERT.
Referenced by madness::SCF::get_fock_transformation(), madness::archive::ArchiveLoadImpl< Archive, LowRankTensor< T > >::load(), madness::ConvolutionData1D< Q >::make_approx(), ortho3(), ortho5(), madness::TensorTrain< T >::splitdim(), and test_svd().
svd() [2/3]
template void madness::svd (const Tensor< double > & a, Tensor< double > & U, Tensor< Tensor< double >::scalar_type > & s, Tensor< double > & VT)
svd() [3/3]
template void madness::svd (const Tensor< double_complex > & a, Tensor< double_complex > & U, Tensor< Tensor< double_complex >::scalar_type > & s, Tensor< double_complex > & VT)
svd_result() [1/5]
template<typename T > void madness::svd_result (Tensor< T > & a, Tensor< T > & U, Tensor< typename Tensor< T >::scalar_type > & s, Tensor< T > & VT, Tensor< T > & work)
same as svd, but it optimizes away the tensor construction: a = U * diag(s) * VT
note that S and VT are swapped in the calling list for c/fortran consistency!
Parameters
[in,out] a a (m,n) matrix to be svd'ed; upon return will hold VT the first min(m,n) rows of VT, stored rowwise
[in,out] U left singular vectors, stored columnwise
[in,out] s the singular values
[in,out] VT not referenced
[in,out] work work array; optimial length lwork: lwork = max<integer>(3*min(m,n)+max(m,n),5*min(m,n)-4)*32;
References a, dgesvd_(), m, mask_info(), madness::Tensor< T >::ptr(), madness::BaseTensor::size(), and TENSOR_ASSERT.
Referenced by madness::TensorTrain< T >::decompose(), rank_revealing_decompose(), and madness::TensorTrain< T >::truncate().
svd_result() [2/5]
template void madness::svd_result (Tensor< float > & a, Tensor< float > & U, Tensor< Tensor< float >::scalar_type > & s, Tensor< float > & VT, Tensor< float > & work)
svd_result() [3/5]
template void madness::svd_result (Tensor< double > & a, Tensor< double > & U, Tensor< Tensor< double >::scalar_type > & s, Tensor< double > & VT, Tensor< double > & work)
svd_result() [4/5]
template void madness::svd_result (Tensor< float_complex > & a, Tensor< float_complex > & U, Tensor< Tensor< float_complex >::scalar_type > & s, Tensor< float_complex > & VT, Tensor< float_complex > & work)
svd_result() [5/5]
template void madness::svd_result (Tensor< double_complex > & a, Tensor< double_complex > & U, Tensor< Tensor< double_complex >::scalar_type > & s, Tensor< double_complex > & VT, Tensor< double_complex > & work)
swap() [1/2]
template<typename T , std::size_t N> void madness::swap (Vector< T, N > & l, Vector< T, N > & r)
Swap the contents of two Vectors.
Template Parameters
T The type of data stored in the Vectors.
N The size of the Vectors.
Parameters
[in,out] l One Vector.
[in,out] r The other Vector.
References madness::Vector< T, N >::swap().
Referenced by madness::SeparatedConvolution< T, NDIM >::apply_transformation(), madness::SeparatedConvolution< T, NDIM >::apply_transformation2(), fast_transform(), madness::SCF::get_fock_transformation(), jacobi(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), madness::SRConf< T >::orthonormalize(), madness::LBNodeDeux< NDIM >::partition(), random_perm(), madness::SRConf< T >::reserve(), madness::Molecule::swapaxes(), madness::TensorIterator< T, Q, R >::TensorIterator(), madness::Zcis::value(), and madness::FunctionImpl< Q, NDIM >::vtransform_doit().
swap() [2/2]
template<typename T , typename U > void madness::swap (RemoteReference< T > & l, RemoteReference< U > & r)
Swap the two remote references.
Parameters
l The left reference to be swapped with r
r The right reference to be swapped with l
Note
T* must be implicitly convertible to U* and vis versa.
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::swap().
swap_particles()
template<typename T > Function<T,6> madness::swap_particles (const Function< T, 6 > & f)
swap particles 1 and 2
param[in] f a function of 2 particles f(1,2) return the input function with particles swapped g(1,2) = f(2,1)
References f, and mapdim().
syev() [1/3]
template<typename T > void madness::syev (const Tensor< T > & A, Tensor< T > & V, Tensor< typename Tensor< T >::scalar_type > & e)
Real-symmetric or complex-Hermitian eigenproblem.
Solves symmetric or Hermitian eigenvalue problem.
A is a real symmetric or complex Hermitian matrix. Return V and e where V is a matrix whose columns are the eigenvectors and e is a vector containing the corresponding eigenvalues. If the LAPACK routine fails, it raises a TensorException with value=infor. The input matrix is unchanged. The eigenvalues are sorted into ascending order. s/dsyev are used for real symmetric matrices; c/zheev are used for complex Hermitian.
The results will satisfy A*V(_,i) = V(_,i)*e(i).
References dsyev_(), e(), mask_info(), max, madness::Tensor< T >::ptr(), TENSOR_ASSERT, transpose(), and V().
Referenced by madness::projector_irrep::apply_symmetry_operators(), madness::SCF::calc_dpolar(), madness::PNO::canonicalize(), compute_frequencies(), madness::MolecularOptimizer::compute_frequencies(), madness::Solver< T, NDIM >::csqrt(), fixphases(), madness::Solver< T, NDIM >::initial_guess(), madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::QuasiNewton::new_search_direction(), QuasiNewton::new_search_direction(), madness::MolecularOptimizer::new_search_direction2(), madness::MolecularOptimizer::optimize_quasi_newton(), madness::Molecule::orient(), orth(), ortho3(), ortho5(), orthonormalize_canonical(), orthonormalize_symmetric(), madness::PNO::pno_compress(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), madness::Solver< T, NDIM >::solve(), and test_syev().
syev() [2/3]
template void madness::syev (const Tensor< double > & A, Tensor< double > & V, Tensor< Tensor< double >::scalar_type > & e)
syev() [3/3]
template void madness::syev (const Tensor< double_complex > & A, Tensor< double_complex > & V, Tensor< Tensor< double_complex >::scalar_type > & e)
sygv() [1/3]
template<typename T > void madness::sygv (const Tensor< T > & A, const Tensor< T > & B, int itype, Tensor< T > & V, Tensor< typename Tensor< T >::scalar_type > & e)
Generalized real-symmetric or complex-Hermitian eigenproblem.
Solves symmetric or Hermitian generalized eigenvalue problem.
This from the LAPACK documentation
S/DSYGV computes all the eigenvalues, and optionally, the eigenvectors
of a real generalized symmetric-definite eigenproblem, of the form
A*x=(lambda)*B*x, A*Bx=(lambda)*x, or B*A*x=(lambda)*x.  Here A and B
are assumed to be symmetric and B is also positive definite.
C/ZHEGV computes all the eigenvalues, and optionally, the eigenvectors
of a complex generalized Hermitian-definite eigenproblem, of the form
A*x=(lambda)*B*x, A*Bx=(lambda)*x, or B*A*x=(lambda)*x. Here A and B
are assumed to be Hermitian and B is also positive definite.
ITYPE   (input) INTEGER
Specifies the problem type to be solved:
= 1:  A*x = (lambda)*B*x
= 2:  A*B*x = (lambda)*x
= 3:  B*A*x = (lambda)*x
References b, dsygv_(), e(), mask_info(), max, madness::Tensor< T >::ptr(), TENSOR_ASSERT, transpose(), and V().
Referenced by madness::Znemo::canonicalize(), diag_and_transform(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), doit(), MiniDFT::doit(), initial_guess(), madness::Solver< T, NDIM >::initial_guess(), main(), madness::Zcis::orthonormalize(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), madness::Solver< T, NDIM >::print_potential_matrix_eigs(), sygvp(), and test_sygv().
sygv() [2/3]
template void madness::sygv (const Tensor< double > & A, const Tensor< double > & B, int itype, Tensor< double > & V, Tensor< Tensor< double >::scalar_type > & e)
sygv() [3/3]
template void madness::sygv (const Tensor< double_complex > & A, const Tensor< double_complex > & B, int itype, Tensor< double_complex > & V, Tensor< Tensor< double_complex >::scalar_type > & e)
sygvp()
template<typename T > void madness::sygvp (World & world, const Tensor< T > & a, const Tensor< T > & B, int itype, Tensor< T > & V, Tensor< typename Tensor< T >::scalar_type > & e)
References a, madness::WorldGopInterface::broadcast_serializable(), e(), madness::World::gop, sygv(), and V().
Referenced by madness::Zcis::canonicalize(), madness::SCF::get_fock_transformation(), madness::Znemo::hcore_guess(), madness::SCF::initial_guess(), and madness::SCF::solve().
symbol_to_atomic_number()
unsigned int madness::symbol_to_atomic_number (const std::string & symbol)
Referenced by Calculation::Calculation(), get_charge_from_file(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), madness::Molecule::read(), MolecularEntity::read_file(), madness::CorePotentialManager::read_file(), AtomicBasisSet::read_file(), and madness::AtomicBasisSet::read_file().
symmetrize()
template<typename T , std::size_t NDIM> Function<T,NDIM> madness::symmetrize (const Function< T, NDIM > & f, const std::string symmetry, bool fence = true)
symmetrize a function
Parameters
[in] symmetry possibilities are: (anti-) symmetric particle permutation ("sy_particle", "antisy_particle") symmetric mirror plane ("xy", "xz", "yz")
Returns
a new function symmetrized according to the input parameter
References f, madness::Function< T, NDIM >::get_impl(), MADNESS_ASSERT, MADNESS_EXCEPTION, madness::Function< T, NDIM >::mapdim(), NDIM, and print().
Referenced by test_adaptive_tree().
tensor_abs()
template<typename Q > Tensor<Q> madness::tensor_abs (const Tensor< std::complex< Q > > & c)
References abs(), BINARY_OPTIMIZED_ITERATOR, and c.
tensor_real2complex()
template<typename Q > Tensor< std::complex<Q> > madness::tensor_real2complex (const Tensor< Q > & r)
References BINARY_OPTIMIZED_ITERATOR, c, madness::BaseTensor::dims(), and madness::BaseTensor::ndim().
TENSOR_RESULT_TYPE() [1/3]
template<typename T , typename R , std::size_t NDIM> madness::TENSOR_RESULT_TYPE (T , R) const
Computes the scalar/inner product between two functions.
In Maple this would be int(conjugate(f(x))*g(x),x=-infinity..infinity)
inner function with right signature for the nonlinear sovler this is needed for the KAIN solvers and other functions
References f, g, inner(), and MADNESS_ASSERT.
Referenced by add(), madness::SeparatedConvolution< T, NDIM >::apply(), apply(), madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), fast_transform(), gaxpy_oop(), general_transform(), inner_result(), operator*(), outer(), madness::SRConf< T >::overlap(), sub(), madness::TensorTrain< T >::trace(), transform(), transform_dir(), and vmulXX().
TENSOR_RESULT_TYPE() [2/3]
template<typename T , typename opT , std::size_t NDIM> madness::TENSOR_RESULT_TYPE (T , typename opT::value_type) const
Computes the scalar/inner product between an MRA function and an external functor.
Currently this defaults to inner_adaptive, which might be more expensive than inner_ext since it loops over all leaf nodes. If you feel inner_ext is more efficient you need to call it directly
Parameters
[in] f MRA function
[in] g functor
Returns
inner(f,g)
TENSOR_RESULT_TYPE() [3/3]
template<typename T , typename opT , std::size_t NDIM> madness::TENSOR_RESULT_TYPE (T , typename opT::value_type) const &
Computes the scalar/inner product between an MRA function and an external functor.
Currently this defaults to inner_adaptive, which might be more expensive than inner_ext since it loops over all leaf nodes. If you feel inner_ext is more efficient you need to call it directly
Parameters
[in] g functor
[in] f MRA function
Returns
inner(f,g)
tensor_ximag()
template<typename Q > Tensor<Q> madness::tensor_ximag (const Tensor< std::complex< Q > > & c)
References BINARY_OPTIMIZED_ITERATOR, c, and imag().
tensor_xreal()
template<typename Q > Tensor<Q> madness::tensor_xreal (const Tensor< std::complex< Q > > & c)
References BINARY_OPTIMIZED_ITERATOR, c, and real().
test_autoc()
bool madness::test_autoc ()
References autocorr_filename, and checksum_file().
Referenced by read_data().
test_cholesky()
template<typename T > double madness::test_cholesky (int n)
References a, aa, cholesky(), copy(), inner(), and my_conj_transpose().
test_gelss()
template<typename T > double madness::test_gelss (int n, int nrhs)
References a, b, e(), gelss(), and inner().
test_gesv()
template<typename T > double madness::test_gesv (int n, int nrhs)
References a, b, gesv(), and inner().
test_inverse()
template<typename T > double madness::test_inverse (int n)
Example and test code for interface to LAPACK SVD interfae.
References inner(), inverse(), madness::Tensor< T >::normf(), and madness::BaseTensor::size().
test_qr()
template<typename T > double madness::test_qr ()
References copy(), error(), madness::Tensor< T >::fillrandom(), inner(), lq(), m, qr(), R, and RandomValue< long >().
test_rnlp()
bool madness::test_rnlp ()
References a, abs(), e(), exact(), g, max, and pi.
Referenced by test_op().
test_rr_cholesky()
template<typename T > double madness::test_rr_cholesky (int n)
References a, aa, copy(), inner(), my_conj_transpose(), P, rr_cholesky(), and transpose().
test_svd()
template<typename T > double madness::test_svd (int n, int m)
Example and test code for interface to LAPACK SVD interfae.
References a, b, madness::BaseTensor::dim(), k, m, and svd().
test_syev()
template<typename T > double madness::test_syev (int n)
References _(), a, e(), inner(), max, syev(), transpose(), and V().
test_sygv()
template<typename T > double madness::test_sygv (int n)
References _(), a, b, e(), inner(), max, my_conj_transpose(), sygv(), and V().
test_tensor_lapack()
bool madness::test_tensor_lapack ()
Test the Tensor-LAPACK interface ... currently always returns true!
Dunno.
Runs the tensor test code, returns true on success
References e().
Referenced by main().
test_two_scale_coefficients()
bool madness::test_two_scale_coefficients ()
Test the two scale coefficients for orthogonality
References e(), inner(), k, kmax, and two_scale_hg().
Referenced by startup().
testf()
static double madness::testf (int n, double x) static
test function for gauss_legendre_test
References sum().
Referenced by gauss_legendre_test().
time_transform()
static void madness::time_transform (World & world, int & mflopslo, int & mflopshi) static
References c, cpu_time(), e(), fast_transform(), madness::World::gop, madness::WorldGopInterface::max(), madness::WorldGopInterface::min(), and N.
Referenced by startup().
transform() [1/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::transform (World & world, const std::vector< Function< T, NDIM > > & v, const Tensor< R > & c, unsigned int blki = 1, unsigned int blkj = 1, const bool fence = true)
Transforms a vector of functions according to new[i] = sum[j] old[j]*c[j,i].
Uses sparsity in the transformation matrix — set small elements to zero to take advantage of this.
References c, compress(), gaxpy(), m, MADNESS_ASSERT, PROFILE_BLOCK, R, and TENSOR_RESULT_TYPE().
transform() [2/7]
template<typename L , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(L,R),NDIM> > madness::transform (World & world, const std::vector< Function< L, NDIM > > & v, const Tensor< R > & c, const double tol, const unsigned int blki = 1, const bool fence)
References c, compress(), madness::WorldGopInterface::fence(), madness::World::gop, m, MADNESS_ASSERT, and PROFILE_BLOCK.
transform() [3/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::transform (World & world, const std::vector< Function< T, NDIM > > & v, const Tensor< R > & c, bool fence = true)
Transforms a vector of functions according to new[i] = sum[j] old[j]*c[j,i].
Uses sparsity in the transformation matrix — set small elements to zero to take advantage of this.
References c, compress(), m, MADNESS_ASSERT, PROFILE_BLOCK, R, and TENSOR_RESULT_TYPE().
Referenced by madness::GTHPseudopotential< Q >::apply_potential(), madness::projector_irrep::apply_symmetry_operators(), madness::Zcis::canonicalize(), madness::TDHF::canonicalize(), madness::Znemo::canonicalize(), madness::CCParameters::CCParameters(), madness::FunctionImpl< Q, NDIM >::coeffs2values(), madness::Nemo::compute_cphf_parallel_term(), madness::SCF::compute_residual(), diag_and_transform(), madness::SCF::diag_fock_matrix(), madness::FunctionImpl< Q, NDIM >::do_binary_op(), madness::FunctionImpl< Q, NDIM >::do_mul(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), doit(), MiniDFT::doit(), madness::F12Parameters::energytype(), madness::FunctionImpl< Q, NDIM >::filter(), fixphases(), madness::QCCalculationParametersBase::fromstring(), madness::Convolution1D< Q >::get_rnlp(), madness::projector_irrep::get_table(), madness::TDHF::get_tda_potential(), madness::Znemo::hcore_guess(), madness::SCF::initial_guess(), initial_guess(), madness::Solver< T, NDIM >::initial_guess(), madness::ACParameters< NDIM >::initialize(), madness::XCfunctional::initialize(), Calculation::load_mos(), madness::Nemo::localize(), main(), madness::Convolution1D< Q >::mod_nonstandard(), madness::FunctionImpl< Q, NDIM >::mul(), madness::Convolution1D< Q >::nonstandard(), madness::FunctionImpl< Q, NDIM >::NScoeffs2values(), madness::Projector< double_complex, NDIM >::operator()(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), operator>>(), orth(), madness::NemoBase::orthonormalize(), madness::SCF::orthonormalize(), madness::Solver< T, NDIM >::orthonormalize(), orthonormalize_canonical(), orthonormalize_cd(), orthonormalize_rrcd(), orthonormalize_symmetric(), madness::FunctionImpl< Q, NDIM >::parent_to_child(), madness::PNOParameters::partial_wave(), madness::MolecularOrbitals< T, NDIM >::project_ao(), madness::projector_irrep::projector_irrep(), madness::QCCalculationParametersBase::read_internal(), madness::SCF::restart_aos(), madness::Znemo::rotate_subspace(), madness::Nemo::rotate_subspace(), madness::SCF::rotate_subspace(), madness::projector_irrep::set_irrep(), madness::Nemo::solve(), madness::SCF::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), Test7(), madness::QCCalculationParametersBase::tostring(), madness::Znemo::potentials::transform(), madness::LowRankTensor< T >::transform(), madness::SRConf< T >::transform(), transform3d(), madness::PNO::transform_pairs(), madness::FunctionImpl< Q, NDIM >::unfilter(), madness::FunctionImpl< Q, NDIM >::values2coeffs(), and madness::FunctionImpl< Q, NDIM >::values2NScoeffs().
transform() [4/7]
template<typename L , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(L,R),NDIM> > madness::transform (World & world, const std::vector< Function< L, NDIM > > & v, const Tensor< R > & c, double tol, bool fence)
References c, compress(), MADNESS_ASSERT, and PROFILE_BLOCK.
transform() [5/7]
template<typename T , typename R , std::size_t NDIM> std::vector< Function<TENSOR_RESULT_TYPE(T,R),NDIM> > madness::transform (World & world, const std::vector< Function< T, NDIM > > & v, const DistributedMatrix< R > & c, bool fence = true)
References c, compress(), m, MADNESS_ASSERT, PROFILE_FUNC, R, TENSOR_RESULT_TYPE(), and transpose().
transform() [6/7]
template<class T , class Q > LowRankTensor< TENSOR_RESULT_TYPE(T,Q) > madness::transform (const LowRankTensor< Q > & t, const Tensor< T > & c)
References c, and madness::LowRankTensor< T >::transform().
transform() [7/7]
template<class T , class Q > TensorTrain<TENSOR_RESULT_TYPE(T,Q)> madness::transform (const TensorTrain< T > & t, const Tensor< Q > & c)
transform each dimension with the same operator matrix
result(i,j,k...) <– sum(i',j', k',...) t(i',j',k',...) c(i',i) c(j',j) c(k',k) ... TODO: merge this with general_transform
References c, copy(), madness::TensorTrain< T >::core, d(), madness::TensorTrain< T >::dims(), inner(), inner_result(), max, madness::TensorTrain< T >::ndim(), r2(), TENSOR_RESULT_TYPE(), and madness::TensorTrain< T >::zero_rank.
truncate() [1/3]
template<typename T , std::size_t NDIM> void madness::truncate (World & world, std::vector< Function< T, NDIM > > & v, double tol = 0.0, unsigned int blk = 1, bool fence = true)
Truncates a vector of functions.
References compress(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
truncate() [2/3]
template<typename T , std::size_t NDIM> void madness::truncate (World & world, std::vector< Function< T, NDIM > > & v, double tol = 0.0, bool fence = true)
Truncates a vector of functions.
References compress(), madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Referenced by KPeriodicBSHOperator::apply(), madness::Diamagnetic_potential_factor::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential(), madness::SCF::apply_potential(), madness::SCF::apply_potential_response(), madness::F12Potentials::apply_regularized_potential(), madness::projector_irrep::apply_symmetry_operators(), madness::NuclearCorrelationFactor::apply_U(), apply_U_ncf(), madness::XCOperator::apply_xc_kernel(), madness::SCF::calc_dipole_mo(), madness::SCF::calc_djkmo(), Calculation::calc_optimal_coeffs(), madness::SCF::calc_response_function(), madness::SCF::calc_rhs(), madness::SCF::calc_xc_function(), madness::Nemo::compute_all_cphf(), madness::PNO::compute_CIS_potentials(), madness::OEP::compute_coulomb_potential(), madness::Nemo::compute_cphf_parallel_term(), madness::Znemo::compute_current_density(), madness::Znemo::compute_density(), compute_energy(), madness::Nemo::compute_energy_regularized(), madness::OEP::compute_exchange_potential(), madness::Nemo::compute_fock_matrix(), madness::F12Potentials::compute_fQg_integrals(), madness::F12Potentials::compute_fQU_integrals(), madness::Diamagnetic_potential_factor::compute_nabla_R_div_R(), madness::Nemo::compute_nemo_potentials(), madness::Coulomb::compute_potential(), madness::Zcis::compute_potentials(), madness::Znemo::compute_potentials(), madness::SCF::compute_residual(), madness::Zcis::compute_residuals(), madness::Znemo::compute_residuals(), Calculation::compute_residuals(), madness::PNO::compute_V_aj_i(), madness::Znemo::compute_vmat(), madness::PNO::compute_Vreg_aj_i(), madness::XCOperator::compute_xc_energy(), madness::F12Potentials::compute_xyab_integrals(), madness::F12Potentials::convolve_with_fg(), madness::F12Potentials::convolve_with_fU(), madness::F12Potentials::convolve_with_local_U(), madness::F12Potentials::convolve_with_nonlocal_U(), madness::F12Potentials::convolve_with_U(), madness::SCF::diag_fock_matrix(), doit(), MiniDFT::doit(), madness::Exchange< double, 3 >::Exchange(), madness::F12Potentials::F12Potentials(), madness::TDHF::get_tda_potential(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::Znemo::hcore_guess(), madness::Nemo::hessian(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), madness::PNO::initialize_pairs(), madness::Zcis::iterate(), madness::Znemo::iterate(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), Calculation::load_mos(), madness::Nemo::localize(), main(), madness::Znemo::make_bra(), madness::Nemo::make_cphf_constant_term(), madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::Nemo::make_laplacian_density(), madness::TDHF::make_mo_bra(), madness::TDHF::make_mo_ket(), madness::TDHF::make_old_guess(), Calculation::make_reference(), SVPESolver::make_surface_charge(), GygiPot::make_surfcharge(), Calculation::make_Upsi(), madness::XCOperator::make_xc_potential(), MiniDFT::makeao(), makeao_slow(), madness::EigSolver< T, NDIM >::multi_solve(), madness::Projector< double_complex, NDIM >::operator()(), madness::QProjector< double_complex, 3 >::operator()(), madness::Coulomb::operator()(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), madness::Nuclear::operator()(), madness::DNuclear::operator()(), madness::CCConvolutionOperator::operator()(), madness::NemoBase::orthonormalize(), madness::SCF::orthonormalize(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), madness::SCF::polarizability(), madness::XCOperator::prep_xc_args(), madness::XCOperator::prep_xc_args_response(), madness::SCF::project(), madness::MolecularOrbitals< T, NDIM >::project_ao(), madness::SCF::project_ao_basis_only(), madness::projector_irrep::project_on_irreps(), madness::Znemo::read_real_guess(), madness::Solver< T, NDIM >::reproject(), madness::SCF::restart_aos(), SVPESolver::solve(), madness::Nemo::solve(), madness::SCF::solve(), madness::Nemo::solve_cphf(), madness::OEP::solve_oep(), SVPESolver::SVPESolver(), test(), madness::PNO::transform_pairs(), truncate(), madness::PNO::truncate_pairs(), madness::SCF::twoint(), update(), MiniDFT::update(), madness::PNO::update_pno(), madness::SCF::update_response_subspace(), madness::Nemo::value(), and madness::XCOperator::XCOperator().
truncate() [3/3]
template<typename T , std::size_t NDIM> std::vector< Function<T,NDIM> > madness::truncate (std::vector< Function< T, NDIM > > v, double tol = 0.0, bool fence = true)
Truncates a vector of functions.
Returns
the truncated vector for chaining
References truncate().
try_two_locks()
bool madness::try_two_locks (const Mutex & m1, const Mutex & m2) inline
Attempt to acquire two locks without blocking holding either one.
The code will first attempt to acquire mutex m1 and if successful will then attempt to acquire mutex m2.
References madness::Mutex::try_lock(), and madness::Mutex::unlock().
tt_identity()
template<typename T > TensorTrain<T> madness::tt_identity (const long ndim, const long k)
compute the n-D identity operator with k elements per dimension
References madness::TensorTrain< T >::get_core(), and k.
two_scale_coefficients()
bool madness::two_scale_coefficients (int k, Tensor< double > * h0, Tensor< double > * h1, Tensor< double > * g0, Tensor< double > * g1)
Return the two scale coefficients in the Legendre basis.
Returns true on success, false on failure (and prints error message)
References cache, copy(), k, kmax, loaded, and read_twoscale().
Referenced by two_scale_hg().
two_scale_hg()
bool madness::two_scale_hg (int k, Tensor< double > * hg)
References k, and two_scale_coefficients().
Referenced by madness::FunctionCommonData< Q, NDIM >::_init_twoscale(), madness::Convolution1D< Q >::Convolution1D(), and test_two_scale_coefficients().
type() [1/3]
std::string madness::type (const PairType & n) inline
Referenced by madness::TDHF::apply_G(), madness::detail::compare_fn_addresses(), madness::BasisFunctions::guess_contracted_virtuals_from_file(), madness::BasisFunctions::guess_with_exop(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), madness::CCIntermediatePotentials::insert(), madness::TDHF::iterate_vectors(), madness::CCIntermediatePotentials::operator()(), madness::BasisFunctions::print_contracted_basis(), madness::F12Potentials::print_pair_energies(), AtomicBasisSet::read_file(), madness::AtomicBasisSet::read_file(), and read_orbital().
type() [2/3]
std::string madness::type (const EnergyType & n) inline
type() [3/3]
std::string madness::type (const GuessType & n) inline
TYPEINFO() [1/6]
madness::TYPEINFO (0 , int , false , true , int , double)
TYPEINFO() [2/6]
madness::TYPEINFO (1 , long , false , true , long , double)
TYPEINFO() [3/6]
madness::TYPEINFO (2 , float , false , true , float , float)
TYPEINFO() [4/6]
madness::TYPEINFO (3 , double , false , true , double , double)
TYPEINFO() [5/6]
madness::TYPEINFO (4 , float_complex , true , true , float , float)
TYPEINFO() [6/6]
madness::TYPEINFO (5 , double_complex , true , true , double , double)
unary_op()
template<typename Q , typename opT , std::size_t NDIM> Function<typename opT::resultT, NDIM> madness::unary_op (const Function< Q, NDIM > & func, const opT & op, bool fence = true)
Out of place application of unary operation to function values with optional fence.
References func(), madness::Function< T, NDIM >::get_impl(), op(), madness::Function< T, NDIM >::set_impl(), and VERIFY_TREE.
Referenced by abs(), abs_square(), abs_square(), abssq(), madness::OEP::compute_weighting_function(), madness::XCOperator::prep_xc_args(), test_hf_he(), and test_math().
unary_op_coeffs()
template<typename Q , typename opT , std::size_t NDIM> Function<typename opT::resultT, NDIM> madness::unary_op_coeffs (const Function< Q, NDIM > & func, const opT & op, bool fence = true)
Out of place application of unary operation to scaling function coefficients with optional fence.
References func(), op(), and madness::Function< T, NDIM >::unary_op_coeffs().
Referenced by abs(), function_real2complex(), imag(), and real().
unitvec()
template<typename T , std::size_t N> Vector<T,N> madness::unitvec (const Vector< T, N > & r, const double eps = 1.e-6)
Construct a unit-Vector that has the same direction as r.
Template Parameters
T The type of data stored in the Vector.
N The size of the Vector.
Parameters
[in] r The Vector.
[in] eps A precision. If the norm of r is less than eps, the zero vector is returned.
Returns
The desired unit-Vector (unless r is numerically the zero Vector).
References madness::detail::norm(), and madness::Vector< T, N >::normf().
user_to_sim()
template<std::size_t NDIM> static void madness::user_to_sim (const Vector< double, NDIM > & xuser, Vector< double, NDIM > & xsim) inline static
Convert user coords (cell[][]) to simulation coords ([0,1]^ndim)
References madness::FunctionDefaults< NDIM >::get_rcell_width(), and NDIM.
Referenced by madness::Specialbox_op< T, NDIM >::check_special_points(), madness::Function< double, 6 >::eval(), madness::Function< double, 6 >::eval_cube(), madness::Function< double, 6 >::eval_local_only(), madness::Function< double, 6 >::evaldepthpt(), madness::Function< double, 6 >::evalR(), mask3(), mask3(), madness::NuclearCuspyBox_op< T, NDIM >::operator()(), and madness::FunctionImpl< Q, NDIM >::project_refine_op().
vec()
template<typename T , typename... Ts> Vector<T, sizeof...(Ts) + 1> madness::vec (T t, Ts... ts) inline
Factory function for creating a madness::Vector.
Variadic templates are used to create factories that mimic
inline madness::Vector<T, N> vec(T t1, ..., T tN) {
    std::Vector<T, N> ret;
    ret[0] = t1;
    ...
    ret[N-1] = tN;
    return ret;
}
This function counts the number of arguments passed in through the argument pack, creates a std::array of the appropriate size, forwards the arguments to the std::array's constructor, and passes the std::array to madness::Vector.
Deprecated:
This function has been replaced by the list-initialization constructor and assignment operator. Rather than
Vector<double, 3> v = vec(1.4, 2.5, 4.0);
use
Vector<double, 3> v{ 1.4, 2.5, 4.0 };
or
Vector<double, 3> v = { 1.4, 2.5, 4.0 };
Note
The first argument is separated from the pack to prevent 0-size arrays and also so that the caller doesn't have to explicitly specify T. It is assumed that all arguments are of type T or are convertible to type T.
Template Parameters
T The data type for the array.
Ts The argument pack; that is, the list of arguments. The size of the resulting Vector is directly determined from the size of the argument pack.
Parameters
[in] t The first argument.
[in] ts The rest of the arguments.
Returns
The Vector with the arguments put into it.
Referenced by KPeriodicBSHOperator::apply(), apply_periodic_bsh(), madness::TaskFn< fnT, arg1T, arg2T, arg3T, arg4T, arg5T, arg6T, arg7T, arg8T, arg9T >::check_dependency(), ConstantSphere::check_pts(), InhomoConstantSphere::check_pts(), CosineSphere::check_pts(), Y20Sphere::check_pts(), madness::OEP::IsAlltrue(), main(), madness::VectorSpace< T, NDIM >::norm(), madness::FunctionSpace< T, NDIM >::norm(), madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::norm(), madness::SRConf< T >::normf(), madness::VectorSpace< T, NDIM >::scale(), madness::FunctionSpace< T, NDIM >::scale(), madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::scale(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen().
vector_factory() [1/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0) inline
Returns a std::vector<T> initialized from the arguments.
Referenced by madness::guessfactory::PolynomialFunctor::read_string().
vector_factory() [2/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1) inline
Returns a std::vector<T> initialized from the arguments.
vector_factory() [3/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1, const T & v2) inline
Returns a std::vector<T> initialized from the arguments.
vector_factory() [4/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1, const T & v2, const T & v3) inline
Returns a std::vector<T> initialized from the arguments.
vector_factory() [5/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1, const T & v2, const T & v3, const T & v4) inline
Returns a std::vector<T> initialized from the arguments.
vector_factory() [6/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1, const T & v2, const T & v3, const T & v4, const T & v5) inline
Returns a std::vector<T> initialized from the arguments.
vector_factory() [7/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1, const T & v2, const T & v3, const T & v4, const T & v5, const T & v6) inline
Returns a std::vector<T> initialized from the arguments.
vector_factory() [8/8]
template<typename T > std::vector<T> madness::vector_factory (const T & v0, const T & v1, const T & v2, const T & v3, const T & v4, const T & v5, const T & v6, const T & v7) inline
Returns a std::vector<T> initialized from the arguments.
verify_tree()
template<typename T , std::size_t NDIM> static void madness::verify_tree (World & world, const std::vector< Function< T, NDIM > > & v) static
Referenced by refine_to_common_level().
vmulXX()
template<typename L , typename R , std::size_t D> std::vector< Function<TENSOR_RESULT_TYPE(L,R),D> > madness::vmulXX (const Function< L, D > & left, const std::vector< Function< R, D > > & vright, double tol, bool fence = true)
Use the vmra/mul(...) interface instead.
This so that we don't have to have friend functions in a different header.
If using sparsity (tol != 0) you must have created the tree of norms already for both left and right.
References L, R, and TENSOR_RESULT_TYPE().
Referenced by mul(), and mul_sparse().
wall_time()
double madness::wall_time ()
Returns the wall time in seconds relative to an arbitrary origin.
As accurate and lightweight as we can get it, but may not be any better than the gettime of day system call.
Returns
The wall time (in seconds).
References e(), first_call, and initialized().
Referenced by madness::SRConf< T >::add_SVD(), chin_chen(), madness::WorldProfile::clear(), madness::Nemo::compute_all_cphf(), compute_energy(), converge(), converge2s(), cpu_frequency(), cycle_count(), doit(), doplot(), doplotptk(), madness::Znemo::timer::end(), madness::Nemo::timer::end(), END_TIMER(), END_TIMER(), madness::Nemo::END_TIMER(), madness::MP2::END_TIMER(), madness::Solver< T, NDIM >::END_TIMER(), GygiPot::ESP(), madness::FunctionImpl< Q, NDIM >::finalize_apply(), madness::SCFProtocol::finished(), madness::Nemo::hessian(), madness::SCFProtocol::initialize(), initialize(), madness::Zcis::iterate(), madness::Znemo::iterate(), iterate(), madness::PNO::iterate_pairs_internal(), main(), madness::Solver< T, NDIM >::make_nuclear_charge_density_impl(), MPI_Wtime(), madness::Fock::operator()(), ortho3(), ortho5(), madness::SRConf< T >::orthonormalize(), madness::SCF::polarizability(), madness::WorldProfile::print(), madness::FunctionImpl< Q, NDIM >::print_size(), print_stats(), print_stats(), propagate(), SVPESolver::solve(), madness::Nemo::solve(), solve(), madness::SCF::solve(), madness::OEP::solve_oep(), madness::MyTimer::start(), madness::CCTimer::start(), madness::profiling::TaskEvent::start(), START_TIMER(), START_TIMER(), madness::Nemo::START_TIMER(), madness::MP2::START_TIMER(), madness::Solver< T, NDIM >::START_TIMER(), madness::MyTimer::stop(), madness::CCTimer::stop(), madness::profiling::TaskEvent::stop(), madness::PoolTaskInterface::submit(), madness::Znemo::timer::tag(), madness::Nemo::timer::tag(), test(), test_adaptive_tree(), test_modified(), madness::Znemo::timer::timer(), madness::Nemo::timer::timer(), madness::PNO::update_pno(), and madness::CCTimer::update_time().
world_mem_info()
WorldMemInfo * madness::world_mem_info ()
Returns pointer to internal structure.
References stats.
Referenced by print_stats().
x_rks_s__()
int madness::x_rks_s__ (const double * r__, double * f, double * dfdra)
References c_b2, f, and pow().
Referenced by madness::XCfunctional::exc(), ldaeop(), ldaop(), madness::xc_lda_potential::operator()(), and madness::XCfunctional::vxc().
x_uks_s__()
int madness::x_uks_s__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb)
References c_b2, f, and pow().
Referenced by madness::XCfunctional::exc(), and madness::XCfunctional::vxc().
xterm_debug()
void madness::xterm_debug (const char * path, const char * display)
Todo:
Brief description needed.
Todo:
Detailed description needed.
Parameters
path Description.
display Description.
Referenced by madness::World::args(), and startup().
xterm_debug_breakpoint()
void madness::xterm_debug_breakpoint ()
zero_functions() [1/2]
template<typename T , std::size_t NDIM> std::vector< Function<T,NDIM> > madness::zero_functions (World & world, int n)
Generates a vector of zero functions.
References PROFILE_BLOCK.
zero_functions() [2/2]
template<typename T , std::size_t NDIM> std::vector< Function<T,NDIM> > madness::zero_functions (World & world, int n, bool fence = true)
Generates a vector of zero functions (reconstructed)
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
zero_functions_compressed()
template<typename T , std::size_t NDIM> std::vector< Function<T,NDIM> > madness::zero_functions_compressed (World & world, int n, bool fence = true)
Generates a vector of zero functions (compressed)
References madness::WorldGopInterface::fence(), madness::World::gop, and PROFILE_BLOCK.
Variable Documentation
___
const std::vector<Slice> madness::___ = vector_factory(_,_,_,_,_,_) static
Entire dimension.
Referenced by madness::FunctionImpl< Q, NDIM >::binaryXXa(), concatenate_columns(), concatenate_rows(), madness::DistributedMatrix< double >::copy_from_replicated(), madness::DistributedMatrix< double >::copy_to_replicated(), dft_xc_lda_ene(), dft_xc_lda_V(), madness::DistributedMatrix< double >::extract_columns(), fcube(), interleave_rows(), laplacian(), madness::FunctionImpl< Q, NDIM >::mulXXa(), madness::FunctionImpl< Q, NDIM >::mulXXveca(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), and madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()().
_c
Tensor<double> madness::_c static
Referenced by autoc().
_cread
Tensor<double> madness::_cread static
Referenced by autoc(), load_coeffs(), and read_data().
acut1e_6
const double madness::acut1e_6 = 0.25
Referenced by PeriodicCoulombOp(), and PeriodicCoulombOpPtr().
atomic_data
const AtomicData madness::atomic_data[NUMBER_OF_ATOMS_IN_TABLE] static
Atomic weights are taken from IUPAC 2005 (M. E. Wieser, Atomic weights of the elements 2005 (IUPAC Technical Report), Pure and Applied Chemistry, vol. 78, no. 11.) Negative masses refer to the longest-living isotope. Note that the masses refer to isotopic averaging, not to the specified isotope!
Referenced by atomic_number_to_symbol(), get_atomic_data(), MolecularEntity::print(), and symbol_to_atomic_number().
autocorr_filename
const char* madness::autocorr_filename = "autocorr" static
Referenced by load_coeffs(), read_data(), and test_autoc().
c_b14
const double madness::c_b14 = 1.333333333333333333333333333333
Referenced by c_uks_vwn5__(), and c_uks_vwn5__().
c_b2
const double madness::c_b2 = 0.333333333333333333333333333333333
Referenced by rks_c_vwn5__(), rks_x_lda__(), x_rks_s__(), x_rks_s__(), x_uks_s__(), and x_uks_s__().
c_b7
const double madness::c_b7 = 0.333333333333333333333333333333
Referenced by c_rks_vwn5__(), c_rks_vwn5__(), c_uks_vwn5__(), and c_uks_vwn5__().
cache
class madness::twoscale_cache_class madness::cache[kmax+1] static
Referenced by find_fuzzy(), madness::detail::DistCache< keyT >::get_cache_value(), load_coeffs(), read_twoscale(), madness::detail::DistCache< keyT >::set_cache_value(), and two_scale_coefficients().
cpufrequency
double madness::cpufrequency private
data_is_read
bool madness::data_is_read = false static
Referenced by load_quadrature(), and read_data().
default_jdim
const long madness::default_jdim = 5551212 static
Referenced by madness::TensorIterator< T, Q, R >::TensorIterator().
default_random_generator
Random madness::default_random_generator
The default random number stream.
Referenced by RandomValue< double >(), RandomValue< float >(), RandomVector< double >(), RandomVector< double_complex >(), RandomVector< float >(), RandomVector< float_complex >(), test(), and test_math().
dir
const string madness::dir = "coredata/" static
Referenced by GradBSHOperator(), GradCoulombOperator(), GradSlaterOperator(), load_coeffs(), load_quadrature(), DPot::operator()(), and madness::CorePotentialManager::read_file().
DYNAMIC_TAG_BASE
const Tag madness::DYNAMIC_TAG_BASE = 1024 static
Todo:
Brief description needed.
f
const Function< T, NDIM > & madness::f
Initial value:
{
        return inner(f,g)
Referenced by abs(), abs_square(), DirichletCondIntOp::action(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::add_to_assignments(), madness::LoadBalanceDeux< NDIM >::add_tree(), madness::WorldTaskQueue::am_arg(), madness::WorldObject< TestFutureForwarding >::am_arg(), apply(), madness::FunctionImpl< Q, NDIM >::apply(), apply_1d_realspace_push(), madness::FunctionImpl< Q, NDIM >::apply_1d_realspace_push(), madness::Solver< T, NDIM >::apply_hf_exchange(), apply_only(), apply_periodic_bsh(), madness::guessfactory::apply_polynomial_exop(), madness::MP2::apply_Q12(), madness::FunctionImpl< Q, NDIM >::apply_source_driven(), madness::SeparatedConvolution< T, NDIM >::apply_transformation(), madness::SeparatedConvolution< T, NDIM >::apply_transformation2(), madness::SeparatedConvolution< T, NDIM >::apply_transformation3(), madness::guessfactory::apply_trigonometric_exop(), c_rks_vwn5__(), c_rks_vwn5__(), c_uks_vwn5__(), c_uks_vwn5__(), madness::SCF::calc_dipole_mo(), madness::CCParameters::CCParameters(), madness::Specialbox_op< T, NDIM >::check_special_points(), madness::guessfactory::compute_centroid(), madness::max_of_x_1_smooth::compute_factor(), madness::MP2::compute_gQf_cc2interface(), conj(), convert(), copy(), cross(), madness::MP2::debug_cc2(), madness::FunctionSpace< T, NDIM >::destroy(), madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::destroy(), diff(), madness::FunctionImpl< Q, NDIM >::diff(), madness::SCF::dipole_matrix_elements(), madness::Function< double, 6 >::dirac_convolution(), madness::CCPairFunction::dirac_convolution_decomposed(), madness::FunctionImpl< Q, NDIM >::dirac_convolution_op(), madness::DerivativeBase< T, NDIM >::do_diff1(), madness::FunctionImpl< Q, NDIM >::do_diff1(), madness::FunctionImpl< Q, NDIM >::do_dirac_convolution(), Plotter::dolineplot(), Plotter::doplot1(), Plotter::dovolumeplot(), madness::SCF::dpolar(), dxprintvalue(), errsq(), madness::XCfunctional::exc(), expL(), fcube(), madness::FunctionImpl< Q, NDIM >::fcube(), madness::DistributedMatrix< double >::fill(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_failure_handler(), madness::DerivativeBase< T, NDIM >::find_neighbor(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::find_success_handler(), madness::DerivativeBase< T, NDIM >::forward_do_diff1(), madness::FunctionImpl< Q, NDIM >::forward_do_diff1(), madness::Function< double, 6 >::gaxpy_ext(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_node(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_recursive(), madness::FunctionImpl< Q, NDIM >::gaxpy_oop_reconstructed(), madness::TaskFn< fnT, arg1T, arg2T, arg3T, arg4T, arg5T, arg6T, arg7T, arg8T, arg9T >::get_func(), madness::MP2::get_residue(), get_size(), grad(), grad_ble_one(), grad_ble_two(), grad_bpsline_two(), grad_bspline_one(), grad_bspline_three(), madness::Solver< T, NDIM >::gram_schmidt(), madness::PNO::guess_virtuals(), madness::BasisFunctions::guess_with_exop(), madness::Znemo::hcore_guess(), madness::SCFProtocol::initialize(), inner(), madness::Function< double, 6 >::inner_adaptive(), madness::FunctionImpl< Q, NDIM >::inner_adaptive_local(), madness::FunctionImpl< Q, NDIM >::inner_adaptive_recursive(), madness::Function< double, 6 >::inner_ext(), madness::Function< double, 6 >::inner_ext_local(), madness::FunctionImpl< Q, NDIM >::inner_ext_local(), madness::FunctionImpl< Q, NDIM >::inner_ext_node(), madness::FunctionImpl< Q, NDIM >::inner_ext_recursive(), madness::CC_vecfunction::insert(), madness::CCIntermediatePotentials::insert(), madness::Zcis::iterate(), madness::MP2::iterate(), laplacian(), line_plot(), load(), madness::archive::ArchiveLoadImpl< Archive, Future< T > >::load(), madness::archive::ArchiveLoadImpl< ParallelInputArchive, Function< T, NDIM > >::load(), load(), madness::archive::ArchiveLoadImpl< Archive, std::shared_ptr< const FunctionImpl< T, NDIM > > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::shared_ptr< FunctionImpl< T, NDIM > > >::load(), EmbeddedDirichlet::load_balance(), madness::LoadBalanceDeux< NDIM >::load_balance(), madness::TDHF::load_function(), madness::Nemo::load_function(), load_function(), main(), madness::TDHF::make_old_guess(), madness::Nemo::make_plots(), madness::Function< double, 6 >::map_and_mirror(), map_and_mirror(), madness::FunctionImpl< Q, NDIM >::map_and_mirror(), map_tensor(), madness::Function< double, 6 >::mapdim(), mapdim(), madness::FunctionImpl< Q, NDIM >::mapdim(), matrix_inner(), matrix_inner_old(), madness::Function< double, 6 >::mirror(), mirror(), madness::FunctionImpl< Q, NDIM >::mirror(), mul(), madness::Function< double, 6 >::mul_on_demand(), multiply(), madness::FunctionImpl< Q, NDIM >::multiply(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast2(), N(), ContractedGaussianShell::normalize(), madness::ContractedGaussianShell::normalize(), op(), madness::xc_lda_potential::operator()(), F::operator()(), madness::pg_operator::operator()(), madness::Projector< double_complex, NDIM >::operator()(), FunctorInterfaceWrapper::operator()(), YetAnotherWrapperClass::operator()(), madness::ElectronCuspyBox_op< T, NDIM >::operator()(), madness::DerivativeBase< T, NDIM >::operator()(), madness::NuclearCuspyBox_op< T, NDIM >::operator()(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), madness::CCConvolutionOperator::operator()(), madness::GenericConvolution1D< Q, opT >::Shmoo::operator()(), madness::CCIntermediatePotentials::operator()(), madness::SeparatedConvolution< T, NDIM >::operator()(), Fred::operator*(), operator*(), operator+(), madness::SCFProtocol::operator++(), Fred::operator+=(), operator-(), operator<<(), F::operator=(), Fred::operator=(), madness::Function< double, 6 >::operator=(), SteepestDescent::optimize(), QuasiNewton::optimize(), MySteepestDescent::optimize(), optimize_coeffs(), madness::TDHF::oscillator_strength_length(), madness::TDHF::oscillator_strength_velocity(), madness::FunctionImpl< Q, NDIM >::parent_to_child_NS(), madness::CC2::plot(), plot(), madness::XCfunctional::plot(), plot_along(), plot_cubefile(), plot_line(), plot_line_print_value(), Calculation::plot_p(), plot_plane(), plot_symmetry_operators(), Calculation::plot_z(), plotdx(), plotpovray(), plotter1(), plotter2(), plotter3(), plotvtk_begin(), plotvtk_data(), plotvtk_end(), madness::DQueue< madness::PoolTaskInterface *>::pop_front(), position_stream(), madness::trajectory< NDIM >::print_psdot(), madness::TDHF::print_xfunctions(), printfunc(), madness::CCPairFunction::project_out(), madness::FunctionImpl< Q, NDIM >::project_out2(), madness::CCPairFunction::project_out_decomposed(), madness::CCPairFunction::project_out_op_decomposed(), madness::DQueue< madness::PoolTaskInterface *>::push_front(), InputParameters::read(), madness::Molecule::read(), madness::QCCalculationParametersBase::read(), madness::BasisFunctions::read_basis_from_file(), madness::BasisFunctions::read_contracted_basis_from_file(), read_data(), MolecularEntity::read_file(), madness::Molecule::read_file(), madness::ElectronicStructureParams::read_file(), CalculationParameters::read_file(), madness::Derivative< T, NDIM >::read_from_file(), madness::QCCalculationParametersBase::read_internal(), refine(), residual(), save(), save(), madness::Nemo::save_function(), save_function(), madness::FunctionImpl< Q, NDIM >::scale_oop(), madness::DQueue< madness::PoolTaskInterface *>::scan(), madness::detail::DistCache< keyT >::set_cache_value(), madness::Function< double, 6 >::set_impl(), madness::SCF::set_protocol(), Calculation::set_protocol(), madness::ConditionVariable::signal(), madness::Nemo::smoothen(), madness::SCF::solve(), square(), madness::archive::ArchiveStoreImpl< Archive, Future< T > >::store(), madness::archive::ArchiveStoreImpl< ParallelOutputArchive, Function< T, NDIM > >::store(), sum(), swap_particles(), madness::TDHF::symmetrize(), symmetrize(), tabulate(), TENSOR_RESULT_TYPE(), madness::Random::test(), test(), Test5(), Test6(), Test6a(), test_add(), test_apply_push_1d(), test_basic(), test_bsh(), test_conv(), test_coulomb(), test_cross(), test_diff(), test_exchange(), test_gconv(), test_he(), test_he_potential(), test_hf_be(), test_hf_h2(), test_hf_he(), test_hydro(), test_inner(), test_io(), test_kinetic(), madness::Znemo::test_landau_wave_function(), test_math(), test_multi_to_multi_op(), test_op(), test_opdir(), test_orthogonalization(), test_per(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), madness::Solver< T, NDIM >::test_periodicity(), test_plot(), test_proj(), test_projector(), test_qm(), test_rot(), test_unaryop(), test_xcfunctional(), testNavierStokes(), testPeriodicCoulomb3d(), madness::Function< double, 6 >::unaryop(), madness::MutexFair::unlock(), SteepestDescent::value(), QuasiNewton::value(), MySteepestDescent::value(), Fred::value_and_gradient(), madness::XCfunctional::vxc(), x_rks_s__(), x_rks_s__(), x_uks_s__(), x_uks_s__(), xc_rks_generic_lda(), and YetAnotherWrapperClass::YetAnotherWrapperClass().
filename
const char* madness::filename = "gaussleg" static
Referenced by AtomicBasisSet::AtomicBasisSet(), madness::AtomicBasisSet::AtomicBasisSet(), madness::archive::BinaryFstreamInputArchive::BinaryFstreamInputArchive(), madness::archive::BinaryFstreamOutputArchive::BinaryFstreamOutputArchive(), checksum_file(), madness::CorePotentialManager::CorePotentialManager(), cubefile_header(), madness::FunctionImpl< Q, NDIM >::do_print_grid(), madness::FunctionImpl< Q, NDIM >::do_print_plane(), draw_circle(), draw_line(), madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), get_charge_from_file(), madness::Solver< T, NDIM >::init(), OutputWriter::init_debug(), OutputWriter::init_eigv(), OutputWriter::init_log(), inputfile::inputfile(), load(), Calculation::load_mos(), madness::GTHPseudopotential< Q >::load_pseudo_from_file(), load_quadrature(), main(), MolecularEntity::MolecularEntity(), madness::Molecule::Molecule(), madness::archive::BinaryFstreamOutputArchive::open(), madness::archive::TextFstreamOutputArchive::open(), madness::archive::BinaryFstreamInputArchive::open(), madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::open(), madness::archive::TextFstreamInputArchive::open(), madness::archive::ParallelInputArchive::ParallelInputArchive(), madness::archive::ParallelOutputArchive::ParallelOutputArchive(), plot(), plot_along(), plot_cubefile(), plot_line(), Calculation::plot_p(), plot_plane(), Calculation::plot_z(), plotdx(), plotpovray(), plotvtk(), plotvtk_begin(), plotvtk_data(), plotvtk_end(), madness::FunctionImpl< Q, NDIM >::print_grid(), print_meminfo(), madness::FunctionImpl< Q, NDIM >::print_plane(), InputParameters::read(), madness::QCCalculationParametersBase::read(), madness::BasisFunctions::read_basis_from_file(), madness::F12Potentials::read_cabs_from_file(), madness::BasisFunctions::read_contracted_basis_from_file(), madness::Molecule::read_core_file(), read_data(), madness::Znemo::read_explicit_guess_functions(), MolecularEntity::read_file(), madness::Molecule::read_file(), madness::ElectronicStructureParams::read_file(), madness::CorePotentialManager::read_file(), CalculationParameters::read_file(), AtomicBasisSet::read_file(), madness::AtomicBasisSet::read_file(), madness::Derivative< T, NDIM >::read_from_file(), redirectio(), madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::remove(), save(), madness::Derivative< T, NDIM >::set_ble1(), madness::Derivative< T, NDIM >::set_ble2(), madness::Derivative< T, NDIM >::set_bspline1(), madness::Derivative< T, NDIM >::set_bspline2(), madness::Derivative< T, NDIM >::set_bspline3(), solve(), madness::Solver< T, NDIM >::Solver(), test_adaptive_tree(), test_smooth_maxout(), testNavierStokes(), madness::archive::TextFstreamInputArchive::TextFstreamInputArchive(), madness::archive::TextFstreamOutputArchive::TextFstreamOutputArchive(), and write_test_input().
g
NDIM const opT & madness::g
Initial value:
{
        PROFILE_FUNC
Referenced by apply_periodic_bsh(), cross(), madness::Znemo::custom_guess(), madness::FunctionImpl< Q, NDIM >::dirac_convolution_op(), Plotter::dolineplot(), Plotter::dovolumeplot(), madness::TwoElectronFactory::gamma(), madness::FunctionImpl< Q, NDIM >::gaxpy_inplace_reconstructed(), madness::FunctionImpl< Q, NDIM >::gaxpy_oop_reconstructed(), madness::SDFCircle::grad_sdf(), madness::SDFSphere::grad_sdf(), Fred::gradient(), Test2::gradient(), CoreFittingTarget::gradient(), has_zero_rank(), inner(), madness::SCF::localize_boys(), madness::SCF::localize_new(), main(), Fred::make_g(), matrix_inner(), matrix_inner_old(), multiply(), madness::FunctionImpl< Q, NDIM >::multiply(), madness::QuasiNewton::new_search_direction(), QuasiNewton::new_search_direction(), madness::MolecularOptimizer::new_search_direction2(), BoysLocalization::operator()(), SteepestDescent::optimize(), madness::SteepestDescent::optimize(), madness::QuasiNewton::optimize(), QuasiNewton::optimize(), MySteepestDescent::optimize(), plot_line(), madness::FunctionImpl< Q, NDIM >::project_out2(), AtomicBasisSet::read_file(), madness::AtomicBasisSet::read_file(), madness::Zcis::read_guess(), madness::Zcis::save_guess(), madness::GaussSlater::Spp_div_S(), madness::GradientalGaussSlater::Spp_div_S(), madness::GradientalGaussSlater::Sr_div_S(), madness::GradientalGaussSlater::Srr_div_S(), madness::GradientalGaussSlater::Srrr_div_S(), TENSOR_RESULT_TYPE(), test(), Test6(), test_coulomb(), test_gconv(), test_io(), test_rnlp(), test_U_el(), test_unaryop(), testgradG(), and Fred::value_and_gradient().
hwthreads
int madness::hwthreads private
is_always_serializable
template<typename T > constexpr bool madness::is_always_serializable
Initial value:
=
    std::is_arithmetic<T>::value ||
    std::is_same<std::nullptr_t, typename std::remove_cv<T>::type>::value ||
    std::is_member_function_pointer<T>::value ||
    std::is_function<T>::value  ||
    std::is_function<typename std::remove_pointer<T>::type>::value
is_iostreammable_v
template<typename T > constexpr bool madness::is_iostreammable_v = is_istreammable_v<T> && is_ostreammable_v<T>
providing automatic support for serializing to/from std streams requires bidirectional streammability
is_istreammable_v
template<typename T > constexpr bool madness::is_istreammable_v = is_istreammable<T>::value
is_ostreammable_v
template<typename T > constexpr bool madness::is_ostreammable_v = is_ostreammable<T>::value
kcur
int madness::kcur = -1 static
Referenced by autoc().
kmax
const int madness::kmax = 60 static
Referenced by madness::BandlimitedPropagator::BandlimitedPropagator(), load_coeffs(), wstFunctor< Q >::operator()(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), read_twoscale(), test_bsh(), test_conv(), test_two_scale_coefficients(), madness::TensorTrain< T >::truncate(), and two_scale_coefficients().
kmax_autoc
const int madness::kmax_autoc = 30 static
Referenced by load_coeffs().
kread
int madness::kread = -1 static
Referenced by autoc(), load_coeffs(), and read_data().
loaded
bool madness::loaded = 0 static
Referenced by load_coeffs(), read_twoscale(), and two_scale_coefficients().
mad_root_dir
const std::string madness::mad_root_dir = MAD_ROOT_DIR static
Referenced by madness::Derivative< T, NDIM >::set_ble1(), madness::Derivative< T, NDIM >::set_ble2(), madness::Derivative< T, NDIM >::set_bspline1(), madness::Derivative< T, NDIM >::set_bspline2(), and madness::Derivative< T, NDIM >::set_bspline3().
max_npt
const int madness::max_npt = 64 static
Referenced by gauss_legendre(), load_quadrature(), and read_data().
MAXK
const int madness::MAXK = 30 static
The maximum wavelet order presently supported.
Referenced by madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionImpl< Q, NDIM >::FunctionImpl(), madness::FunctionCommonData< Q, NDIM >::get(), madness::FunctionNode< T, NDIM >::set_coeff(), and madness::FunctionDefaults< NDIM >::set_k().
MAXLEVEL
const int madness::MAXLEVEL = 8*sizeof(Translation)-2 static
The maximum depth of refinement possible.
Referenced by madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_max_refine_level(), and madness::FunctionDefaults< NDIM >::set_special_level().
memorysize
int64_t madness::memorysize private
nn1
double madness::nn1[100] static
Referenced by initialize_legendre_stuff(), and legendre_polynomials().
NUMBER_OF_ATOMS_IN_TABLE
const unsigned int madness::NUMBER_OF_ATOMS_IN_TABLE = 110 static
Referenced by get_atomic_data(), and symbol_to_atomic_number().
NUMEVENTS
const int madness::NUMEVENTS = 0
Referenced by print_stats().
phi_norms
double madness::phi_norms[100] static
Referenced by initialize_legendre_stuff(), and legendre_scaling_functions().
points
Tensor<double> madness::points[max_npt+1] static
Referenced by gauss_legendre(), load_quadrature(), and read_data().
print_timings
bool madness::print_timings =false static
Referenced by apply(), apply_only(), END_TIMER(), and madness::SCF::SCF().
rmi_task_is_running
volatile bool madness::rmi_task_is_running = false static
Referenced by madness::RMI::begin(), and madness::RMI::RmiTask::set_rmi_task_is_running().
sss
std::vector<double> madness::sss static
Referenced by END_TIMER(), END_TIMER(), START_TIMER(), and START_TIMER().
tensor_type_names
const char* madness::tensor_type_names[]
Referenced by Test1(), Test3(), Test5(), Test6(), and Test7().
threadcounter
AtomicInt madness::threadcounter static
Referenced by madness::WorldProfileObj::WorldProfileObj().
ttt
std::vector<double> madness::ttt static
Referenced by madness::FunctionImpl< Q, NDIM >::add_scalar_inplace(), END_TIMER(), END_TIMER(), START_TIMER(), START_TIMER(), and test5().
twoscale_filename
const char* madness::twoscale_filename = "coeffs" static
Referenced by load_coeffs(), and read_twoscale().
weights
Tensor<double> madness::weights[max_npt+1] static
Referenced by gauss_legendre(), initial_guess(), load_quadrature(), ortho3(), outer(), and read_data().