MADNESS: ploterr.cc File Reference
ploterr.cc File Reference
#include <madness/mra/mra.h>
Functions
int main (int argc, char **argv)
double myf (const coord_1d &r)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::f, madness::finalize(), madness::initialize(), k, myf(), pow(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and thresh.
myf()
double myf (const coord_1d & r)
References e().
Referenced by main().