MADNESS: plotxc.cc File Reference
plotxc.cc File Reference
#include <madness/world/world.h>
#include <madness/mra/mra.h>
#include <madness/tensor/tensor.h>
#include <fstream>
#include "xcfunctional.h"
Classes
struct xcfunc_data_point
Functions
int main (int argc, char **argv)
std::vector< xcfunc_data_point > read_test_data (const std::string &dfname, bool spin_polarized)
void test_xcfunctional (World &world)
Variables
static std::string df_repo_functionals []
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), and test_xcfunctional().
read_test_data()
std::vector<xcfunc_data_point> read_test_data (const std::string & dfname, bool spin_polarized)
References std::abs(), e(), xcfunc_data_point::rhoa, xcfunc_data_point::rhob, xcfunc_data_point::sigmaaa, xcfunc_data_point::sigmaab, xcfunc_data_point::sigmabb, xcfunc_data_point::v2rhoa2, xcfunc_data_point::v2rhoab, xcfunc_data_point::v2rhob2, xcfunc_data_point::vrhoa, xcfunc_data_point::vrhob, xcfunc_data_point::vsigmaaa, xcfunc_data_point::vsigmaab, xcfunc_data_point::vsigmabb, and xcfunc_data_point::zk.
Referenced by test_xcfunctional().
test_xcfunctional()
void test_xcfunctional (World & world)
References df_repo_functionals, madness::f, madness::XCfunctional::initialize(), madness::XCfunctional::is_gga(), madness::XCfunctional::is_spin_polarized(), madness::print(), read_test_data(), and madness::XCfunctional::vxc().
Referenced by main().
Variable Documentation
df_repo_functionals
std::string df_repo_functionals[] static
Initial value:
= {
"lda_x",
"lda_c_vwn",
"gga_x_pbe",
"gga_c_pbe",
"gga_x_pw91",
"gga_c_pw91",
"gga_x_b88",
"gga_c_lyp",
"lda_c_vwn_rpa",
"lda_c_vwn",
"lda_c_pz",
"lda_c_pw",
"hyb_gga_xc_b3lyp",
"gga_xc_hcth_93",
"gga_xc_hcth_407",
"gga_xc_hcth_147",
"gga_xc_hcth_120",
"gga_xc_edf1",
"gga_xc_b97_2",
"gga_xc_b97_1",
"gga_xc_b97",
"gga_x_pw91",
"gga_x_pbe",
"gga_x_ft97_b",
"gga_x_b88",
"gga_c_pw91",
"gga_c_pbe",
"gga_c_p86",
"gga_c_lyp"}
Referenced by test_xcfunctional().