MADNESS: scott.cc File Reference
scott.cc File Reference
#include <iostream>
Functions
void gndstate_ ()
int main (int argc, char **argv)
void readinput_ ()
Function Documentation
gndstate_()
void gndstate_ ()
Referenced by main().
main()
int main (int argc, char ** argv)
References gndstate_(), and readinput_().
readinput_()
void readinput_ ()
Referenced by main().