MADNESS: smooth.h File Reference
smooth.h File Reference
#include <iostream>
#include <string>
#include <chem/nemo.h>
#include <madness/mra/funcplot.h>
#include <cmath>
#include <chem/SCFOperators.h>
#include <madness/mra/function_common_data.h>
Classes
struct apply_kernel_helper
struct asymptotic_density
struct asymptotic_slater
struct asymptotic_slater_kernel
struct density_mask_operator
struct smooth< T, NDIM >::inv_mask_functor
struct smooth< T, NDIM >::mask_functor
struct merging_operator
struct munging_operator
struct apply_kernel_helper::slater_kernel
struct slater_kernel
struct slater_kernel_apply
class smooth< T, NDIM >
Functions
static double analytical_slater_functor (double rho)
double estimate_area (double x)
double make_exp (double x)
double make_log (double x)
template<std::size_t NDIM>
static double make_radius (const Vector< double, NDIM > &x)
static double mask_functor_box (const coord_3d &x)
template<std::size_t NDIM>
static double mask_munging (const double x)
template<std::size_t NDIM>
static double munge (const double x)
static double r2 (const coord_3d &x)
static double slater_functor (const coord_3d &x)
static double test_1d_functor (const coord_1d &x)
template<std::size_t NDIM>
static double unitfunctor (const Vector< double, NDIM > &x)
static double xf (const coord_3d &x)
Variables
static double cutoff_radius = 5.0
static double mask_factor = 5.0
static double RHOMIN = 1.e-20
Function Documentation
analytical_slater_functor()
static double analytical_slater_functor (double rho) static
References pow().
estimate_area()
double estimate_area (double x)
References thresh.
make_exp()
double make_exp (double x)
Referenced by smooth< T, NDIM >::make_explog(), and smooth< T, NDIM >::smooth_density().
make_log()
double make_log (double x)
References RHOMIN.
Referenced by smooth< T, NDIM >::make_explog(), and smooth< T, NDIM >::smooth_density().
make_radius()
template<std::size_t NDIM> static double make_radius (const Vector< double, NDIM > & x) static
References r2(), and xi.
mask_functor_box()
static double mask_functor_box (const coord_3d & x) static
References r2().
mask_munging()
template<std::size_t NDIM> static double mask_munging (const double x) static
munge()
template<std::size_t NDIM> static double munge (const double x) static
r2()
static double r2 (const coord_3d & x) static
Referenced by madness::apply(), apply_U_ncf(), apply_V(), area_two_spheres(), coul(), d_smoothed_potential(), distances(), dsmoothed_potential(), madness::dsmoothed_potential(), madness::NuclearCorrelationFactor::dsmoothed_unitvec(), f6d(), gauss_3d(), gauss_6d(), madness::general_transform(), he_orbitals(), helium_pot(), hylleraas_3term(), main(), madness::TwoElectronInterface< double, 6 >::make_coeff(), make_radius(), mask_functor_box(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), madness::BasisFunctions::SolidHarmonicGaussian::operator()(), r2r(), slater_functor(), smoothed_potential(), madness::smoothed_potential(), madness::TensorTrain< T >::splitdim(), test_add(), madness::Solver< T, NDIM >::test_periodicity(), tightgauss_3d(), madness::transform(), u(), madness::GaussSlater::U2X_spherical(), madness::GradientalGaussSlater::U2X_spherical(), madness::Slater::U2X_spherical(), madness::Polynomial< N >::U2X_spherical(), V(), V_1(), V_times_phi(), and volume_two_spheres().
slater_functor()
static double slater_functor (const coord_3d & x) static
References r2().
test_1d_functor()
static double test_1d_functor (const coord_1d & x) static
Referenced by smooth< T, NDIM >::test_1d().
unitfunctor()
template<std::size_t NDIM> static double unitfunctor (const Vector< double, NDIM > & x) static
Referenced by smooth< T, NDIM >::make_inv_mask().
xf()
static double xf (const coord_3d & x) static
Referenced by madness::XCfunctional::exc(), and madness::XCfunctional::vxc().
Variable Documentation
cutoff_radius
double cutoff_radius = 5.0 static
mask_factor
double mask_factor = 5.0 static
RHOMIN
double RHOMIN = 1.e-20 static
Referenced by make_log().