MADNESS: madness::BinaryOpStructure< NDIM > Struct Template Reference
madness::BinaryOpStructure< NDIM > Struct Template Reference
computes the corrected exchange correlation potential using the hartree potential
#include <AC.h>
Public Member Functions
BinaryOpStructure ()
necessary to compile the program without getting a strange error i dont understand
BinaryOpStructure (const std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f_)
BinaryOpStructure (const BinaryOpStructure< NDIM > &other)
void operator() (const Key< NDIM > &key, Tensor< double > &result, const Tensor< double > &vxc, const Tensor< double > &vhartree) const
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
FunctionCommonData< double, NDIM > cdata
std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f
shared pointer to object of int_factor_functor
Detailed Description
template<unsigned long int NDIM>
struct madness::BinaryOpStructure< NDIM >
computes the corrected exchange correlation potential using the hartree potential
Constructor & Destructor Documentation
BinaryOpStructure() [1/3]
template<unsigned long int NDIM> madness::BinaryOpStructure< NDIM >::BinaryOpStructure () inline
necessary to compile the program without getting a strange error i dont understand
BinaryOpStructure() [2/3]
template<unsigned long int NDIM> madness::BinaryOpStructure< NDIM >::BinaryOpStructure (const std::shared_ptr< FunctionFunctorInterface< double, NDIM > > f_) inline
BinaryOpStructure() [3/3]
template<unsigned long int NDIM> madness::BinaryOpStructure< NDIM >::BinaryOpStructure (const BinaryOpStructure< NDIM > & other) inline
Member Function Documentation
operator()()
template<unsigned long int NDIM> void madness::BinaryOpStructure< NDIM >::operator() (const Key< NDIM > & key, Tensor< double > & result, const Tensor< double > & vxc, const Tensor< double > & vhartree) const inline
computes the corrected potential (weighting with correction factor and adding of 1/r potential)
Parameters
[in] t uncorrected exchange correlation potential
[out] t corrected exchange correlation potential
References madness::BinaryOpStructure< NDIM >::cdata, madness::copy(), madness::BaseTensor::dims(), madness::BinaryOpStructure< NDIM >::f, madness::fcube(), MADNESS_EXCEPTION, madness::BaseTensor::ndim(), and madness::FunctionCommonData< T, NDIM >::quad_x.
serialize()
template<unsigned long int NDIM> template<typename Archive > void madness::BinaryOpStructure< NDIM >::serialize (Archive & ar) inline
Member Data Documentation
cdata
template<unsigned long int NDIM> FunctionCommonData<double,NDIM> madness::BinaryOpStructure< NDIM >::cdata
Referenced by madness::BinaryOpStructure< NDIM >::operator()().
f
template<unsigned long int NDIM> std::shared_ptr<FunctionFunctorInterface<double,NDIM> > madness::BinaryOpStructure< NDIM >::f
shared pointer to object of int_factor_functor
Referenced by madness::BinaryOpStructure< NDIM >::operator()().
The documentation for this struct was generated from the following file:
AC.h