MADNESS: madness::ConvolutionData1D< Q > Struct Template Reference
madness::ConvolutionData1D< Q > Struct Template Reference
!!! Note that if Rnormf is zero then ALL of the tensors are empty
#include <convolution1d.h>
Public Member Functions
ConvolutionData1D (const Tensor< Q > &R, const Tensor< Q > &T)
ConvolutionData1D (const Tensor< Q > &R, const Tensor< Q > &T, const bool modified)
void make_approx (const Tensor< Q > &R, Tensor< Q > &RU, Tensor< typename Tensor< Q >::scalar_type > &Rs, Tensor< Q > &RVT, double &norm)
Public Attributes
double N_diff
double N_F
the norms according to Beylkin 2008, Eq. (21) ff
double N_up
double NSnormf
Tensor< Q > R
double Rnorm
double Rnormf
Tensor< typename Tensor< Q >::scalar_type > Rs
Tensor< Q > RU
Tensor< Q > RVT
Tensor< Q > T
if NS: R=ns, T=T part of ns; if modified NS: T= r^(n-1)
double Tnorm
double Tnormf
Tensor< typename Tensor< Q >::scalar_type > Ts
hold relative errors, NOT the singular values..
Tensor< Q > TU
Tensor< Q > TVT
SVD approximations to R and T.
Detailed Description
template<typename Q>
struct madness::ConvolutionData1D< Q >
!!! Note that if Rnormf is zero then ALL of the tensors are empty
actual data for 1 dimension and for 1 term and for 1 displacement for a convolution operator here we keep the transformation matrices
Constructor & Destructor Documentation
ConvolutionData1D() [1/2]
template<typename Q> madness::ConvolutionData1D< Q >::ConvolutionData1D (const Tensor< Q > & R, const Tensor< Q > & T) inline
ctor for NS form make the operator matrices r^n and r^(n-1)
Parameters
[in] R operator matrix of the requested level; NS: unfilter(r^(n+1)); modified NS: r^n
[in] T upsampled operator matrix from level n-1; NS: r^n; modified NS: filter(r^(n-1))
References madness::copy(), madness::BaseTensor::dim(), e(), k, madness::ConvolutionData1D< Q >::make_approx(), madness::ConvolutionData1D< Q >::N_diff, madness::ConvolutionData1D< Q >::N_F, madness::ConvolutionData1D< Q >::N_up, madness::Tensor< T >::normf(), madness::ConvolutionData1D< Q >::NSnormf, madness::ConvolutionData1D< Q >::R, madness::ConvolutionData1D< Q >::Rnorm, madness::ConvolutionData1D< Q >::Rnormf, madness::ConvolutionData1D< Q >::Rs, madness::ConvolutionData1D< Q >::RU, madness::ConvolutionData1D< Q >::RVT, madness::ConvolutionData1D< Q >::T, madness::ConvolutionData1D< Q >::Tnorm, madness::ConvolutionData1D< Q >::Tnormf, madness::ConvolutionData1D< Q >::Ts, madness::ConvolutionData1D< Q >::TU, and madness::ConvolutionData1D< Q >::TVT.
ConvolutionData1D() [2/2]
template<typename Q> madness::ConvolutionData1D< Q >::ConvolutionData1D (const Tensor< Q > & R, const Tensor< Q > & T, const bool modified) inline
ctor for modified NS form make the operator matrices r^n and r^(n-1)
Parameters
[in] R operator matrix of the requested level; NS: unfilter(r^(n+1)); modified NS: r^n
[in] T upsampled operator matrix from level n-1; NS: r^n; modified NS: filter(r^(n-1))
[in] modified use (un) modified NS form
References e(), madness::ConvolutionData1D< Q >::make_approx(), madness::ConvolutionData1D< Q >::N_diff, madness::ConvolutionData1D< Q >::N_F, madness::ConvolutionData1D< Q >::N_up, madness::Tensor< T >::normf(), madness::ConvolutionData1D< Q >::R, madness::ConvolutionData1D< Q >::Rnorm, madness::ConvolutionData1D< Q >::Rnormf, madness::ConvolutionData1D< Q >::Rs, madness::ConvolutionData1D< Q >::RU, madness::ConvolutionData1D< Q >::RVT, madness::ConvolutionData1D< Q >::T, madness::ConvolutionData1D< Q >::Tnorm, madness::ConvolutionData1D< Q >::Tnormf, madness::ConvolutionData1D< Q >::Ts, madness::ConvolutionData1D< Q >::TU, and madness::ConvolutionData1D< Q >::TVT.
Member Function Documentation
make_approx()
template<typename Q> void madness::ConvolutionData1D< Q >::make_approx (const Tensor< Q > & R, Tensor< Q > & RU, Tensor< typename Tensor< Q >::scalar_type > & Rs, Tensor< Q > & RVT, double & norm) inline
approximate the operator matrices using SVD, and abuse Rs to hold the error instead of the singular values (seriously, who named this??)
References madness::BaseTensor::dim(), madness::detail::norm(), madness::ConvolutionData1D< Q >::R, madness::ConvolutionData1D< Q >::Rs, madness::ConvolutionData1D< Q >::RU, madness::ConvolutionData1D< Q >::RVT, and madness::svd().
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
Member Data Documentation
N_diff
template<typename Q> double madness::ConvolutionData1D< Q >::N_diff
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::SeparatedConvolution< T, NDIM >::munorm2_modified().
N_F
template<typename Q> double madness::ConvolutionData1D< Q >::N_F
the norms according to Beylkin 2008, Eq. (21) ff
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::SeparatedConvolution< T, NDIM >::munorm2_modified().
N_up
template<typename Q> double madness::ConvolutionData1D< Q >::N_up
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::SeparatedConvolution< T, NDIM >::munorm2_modified().
NSnormf
template<typename Q> double madness::ConvolutionData1D< Q >::NSnormf
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
R
template<typename Q> Tensor<Q> madness::ConvolutionData1D< Q >::R
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::ConvolutionData1D< Q >::make_approx().
Rnorm
template<typename Q> double madness::ConvolutionData1D< Q >::Rnorm
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
Rnormf
template<typename Q> double madness::ConvolutionData1D< Q >::Rnormf
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
Rs
template<typename Q> Tensor<typename Tensor<Q>::scalar_type> madness::ConvolutionData1D< Q >::Rs
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::ConvolutionData1D< Q >::make_approx().
RU
template<typename Q> Tensor<Q> madness::ConvolutionData1D< Q >::RU
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::ConvolutionData1D< Q >::make_approx().
RVT
template<typename Q> Tensor<Q> madness::ConvolutionData1D< Q >::RVT
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D(), and madness::ConvolutionData1D< Q >::make_approx().
T
template<typename Q> Tensor<Q> madness::ConvolutionData1D< Q >::T
if NS: R=ns, T=T part of ns; if modified NS: T= r^(n-1)
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
Tnorm
template<typename Q> double madness::ConvolutionData1D< Q >::Tnorm
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
Tnormf
template<typename Q> double madness::ConvolutionData1D< Q >::Tnormf
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
Ts
template<typename Q> Tensor<typename Tensor<Q>::scalar_type> madness::ConvolutionData1D< Q >::Ts
hold relative errors, NOT the singular values..
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
TU
template<typename Q> Tensor<Q> madness::ConvolutionData1D< Q >::TU
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
TVT
template<typename Q> Tensor<Q> madness::ConvolutionData1D< Q >::TVT
SVD approximations to R and T.
Referenced by madness::ConvolutionData1D< Q >::ConvolutionData1D().
The documentation for this struct was generated from the following file:
convolution1d.h