MADNESS: madness::CCMessenger Struct Reference
madness::CCMessenger Struct Reference
#include <CCStructures.h>
Public Member Functions
CCMessenger (World &world)
void debug_output (const std::string &msg) const
void operator() (const std::string &msg) const
template<class T >
CCMessenger operator<< (const T &t) const
void output (const std::string &msg) const
void print_warnings () const
void section (const std::string &msg) const
void subsection (const std::string &msg) const
void warning (const std::string &msg) const
Public Attributes
bool debug
std::ostream & os
output stream
size_t output_prec
bool scientific
std::vector< std::string > warnings
collect all warnings that occur to print out at the end of the job
World & world
Constructor & Destructor Documentation
CCMessenger()
madness::CCMessenger::CCMessenger (World & world) inline
Member Function Documentation
debug_output()
void madness::CCMessenger::debug_output (const std::string & msg) const inline
References debug, and output().
operator()()
void madness::CCMessenger::operator() (const std::string & msg) const inline
References output().
operator<<()
template<class T > CCMessenger madness::CCMessenger::operator<< (const T & t) const inline
References os, madness::World::rank(), and world.
output()
void madness::CCMessenger::output (const std::string & msg) const
References output_prec, madness::World::rank(), scientific, and world.
Referenced by madness::PNO::adaptive_solver(), madness::TDHF::apply_G(), debug_output(), madness::TDHF::initialize(), madness::TDHF::initialize_singles(), madness::PNO::iterate_pairs(), madness::TDHF::iterate_vectors(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_virtuals(), operator()(), section(), madness::TDHF::solve_cis(), subsection(), madness::TDHF::TDHF(), and warning().
print_warnings()
void madness::CCMessenger::print_warnings () const inline
References madness::World::rank(), warnings, and world.
Referenced by madness::TDHF::solve_cis().
section()
void madness::CCMessenger::section (const std::string & msg) const
References output(), madness::World::rank(), and world.
Referenced by madness::PNO::adaptive_solver(), madness::CC2::CC2(), madness::CC2::iterate_adc2_pairs(), madness::CC2::iterate_lrcc2_pairs(), madness::CC2::iterate_pair(), madness::PNO::iterate_pairs(), madness::CC2::solve(), madness::CC2::solve_cc2(), madness::CC2::solve_ccs(), madness::TDHF::solve_cis(), madness::PNO::solve_cispd(), madness::CC2::solve_cispd(), madness::PNO::solve_mp2(), madness::CC2::solve_mp2(), madness::TDHF::solve_tdhf(), and madness::TDHF::TDHF().
subsection()
void madness::CCMessenger::subsection (const std::string & msg) const
References output(), madness::World::rank(), and world.
Referenced by madness::TDHF::initialize(), madness::CC2::iterate_pair(), madness::PNO::iterate_pairs_internal(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), madness::TDHF::make_virtuals(), madness::TDHF::solve_cis(), and madness::TDHF::TDHF().
warning()
void madness::CCMessenger::warning (const std::string & msg) const
References output(), and warnings.
Referenced by madness::TDHF::apply_G(), madness::TDHF::get_tda_potential(), madness::PNO::iterate_pairs(), madness::CC2::iterate_singles(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::CC2::solve_cc2(), madness::PNO::t_solve(), and madness::TDHF::TDHF().
Member Data Documentation
debug
bool madness::CCMessenger::debug
Referenced by debug_output(), and madness::TDHF::TDHF().
os
std::ostream& madness::CCMessenger::os
output stream
Referenced by operator<<().
output_prec
size_t madness::CCMessenger::output_prec
Referenced by output(), and madness::TDHF::print_xfunctions().
scientific
bool madness::CCMessenger::scientific
Referenced by output().
warnings
std::vector<std::string> madness::CCMessenger::warnings mutable
collect all warnings that occur to print out at the end of the job
Referenced by print_warnings(), and warning().
world
World& madness::CCMessenger::world
Referenced by operator<<(), output(), print_warnings(), section(), and subsection().
The documentation for this struct was generated from the following files:
CCStructures.h
CCStructures.cc