MADNESS: madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT > Struct Template Reference
madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT > Struct Template Reference
Hartree product of two LDIM functions to yield a NDIM = 2*LDIM function.
#include <funcimpl.h>
Public Types
typedef CoeffTracker< T, LDIM > ctL
typedef hartree_op< LDIM, leaf_opT > this_type
Public Member Functions
hartree_op ()
hartree_op (implT *result, const ctL &p11, const ctL &p22, const leaf_opT &leaf_op)
Future< this_type > activate () const
this_type forward_ctor (implT *result1, const ctL &p11, const ctL &p22, const leaf_opT &leaf_op)
this_type make_child (const keyT &child) const
std::pair< bool, coeffT > operator() (const Key< NDIM > &key) const
bool randomize () const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
leaf_opT leaf_op
determine if a given node will be a leaf node
ctL p1
ctL p2
tracking coeffs of the two lo-dim functions
implT * result
where to construct the pair function
Detailed Description
template<typename T, std::size_t NDIM>
template<size_t LDIM, typename leaf_opT>
struct madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >
Hartree product of two LDIM functions to yield a NDIM = 2*LDIM function.
Member Typedef Documentation
ctL
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > typedef CoeffTracker<T,LDIM> madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::ctL
this_type
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > typedef hartree_op<LDIM,leaf_opT> madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::this_type
Constructor & Destructor Documentation
hartree_op() [1/2]
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::hartree_op () inline
hartree_op() [2/2]
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::hartree_op (implT * result, const ctL & p11, const ctL & p22, const leaf_opT & leaf_op) inline
References madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), and NDIM.
Member Function Documentation
activate()
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > Future<this_type> madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::activate () const inline
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::forward_ctor(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p1, madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p2, madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::result, madness::World::taskq, madness::FunctionImpl< T, NDIM >::world, and madness::detail::wrap_mem_fn().
forward_ctor()
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > this_type madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::forward_ctor (implT * result1, const ctL & p11, const ctL & p22, const leaf_opT & leaf_op) inline
Referenced by madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::activate().
make_child()
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > this_type madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::make_child (const keyT & child) const inline
References madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::leaf_op, madness::CoeffTracker< T, NDIM >::make_child(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p1, madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p2, and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::result.
operator()()
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator() (const Key< NDIM > & key) const inline
References madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::cdata, madness::CoeffTracker< T, NDIM >::coeff(), madness::GenTensor< T >::full_tensor(), madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::leaf_op, madness::outer(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p1, madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p2, and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::result.
randomize()
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > bool madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::randomize () const inline
serialize()
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > template<typename Archive > void madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::leaf_op, madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p1, madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p2, and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::result.
Member Data Documentation
leaf_op
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > leaf_opT madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::leaf_op
determine if a given node will be a leaf node
Referenced by madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::make_child(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator()(), and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::serialize().
p1
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > ctL madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p1
Referenced by madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::activate(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::make_child(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator()(), and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::serialize().
p2
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > ctL madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::p2
tracking coeffs of the two lo-dim functions
Referenced by madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::activate(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::make_child(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator()(), and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::serialize().
result
template<typename T, std::size_t NDIM> template<size_t LDIM, typename leaf_opT > implT* madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::result
where to construct the pair function
Referenced by madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::activate(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::make_child(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator()(), and madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h