MADNESS: madness::FunctionImpl< T, NDIM >::add_op Struct Reference
madness::FunctionImpl< T, NDIM >::add_op Struct Reference
add two functions f and g: result=alpha * f + beta * g
#include <funcimpl.h>
Public Types
typedef CoeffTracker< T, NDIM > ctT
typedef add_op this_type
Public Member Functions
add_op ()
add_op (const ctT &f, const ctT &g, const double alpha, const double beta)
Future< this_type > activate () const
retrieve the coefficients (parent coeffs might be remote)
this_type forward_ctor (const ctT &f1, const ctT &g1, const double alpha, const double beta)
taskq-compatible ctor
this_type make_child (const keyT &child) const
std::pair< bool, coeffT > operator() (const keyT &key) const
if we are at the bottom of the trees, return the sum of the coeffs
bool randomize () const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
double alpha
prefactor for f, g
double beta
ctT f
tracking coeffs of first and second addend
ctT g
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::add_op
add two functions f and g: result=alpha * f + beta * g
Member Typedef Documentation
ctT
template<typename T, std::size_t NDIM> typedef CoeffTracker<T,NDIM> madness::FunctionImpl< T, NDIM >::add_op::ctT
this_type
template<typename T, std::size_t NDIM> typedef add_op madness::FunctionImpl< T, NDIM >::add_op::this_type
Constructor & Destructor Documentation
add_op() [1/2]
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::add_op::add_op () inline
add_op() [2/2]
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::add_op::add_op (const ctT & f, const ctT & g, const double alpha, const double beta) inline
Member Function Documentation
activate()
template<typename T, std::size_t NDIM> Future<this_type> madness::FunctionImpl< T, NDIM >::add_op::activate () const inline
retrieve the coefficients (parent coeffs might be remote)
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), madness::FunctionImpl< T, NDIM >::add_op::alpha, madness::FunctionImpl< T, NDIM >::add_op::beta, madness::FunctionImpl< T, NDIM >::add_op::f, f1, madness::FunctionImpl< T, NDIM >::add_op::forward_ctor(), madness::FunctionImpl< T, NDIM >::add_op::g, madness::CoeffTracker< T, NDIM >::get_impl(), madness::World::taskq, madness::FunctionImpl< T, NDIM >::world, and madness::detail::wrap_mem_fn().
forward_ctor()
template<typename T, std::size_t NDIM> this_type madness::FunctionImpl< T, NDIM >::add_op::forward_ctor (const ctT & f1, const ctT & g1, const double alpha, const double beta) inline
taskq-compatible ctor
References madness::FunctionImpl< T, NDIM >::add_op::alpha, madness::FunctionImpl< T, NDIM >::add_op::beta, and f1.
Referenced by madness::FunctionImpl< T, NDIM >::add_op::activate().
make_child()
template<typename T, std::size_t NDIM> this_type madness::FunctionImpl< T, NDIM >::add_op::make_child (const keyT & child) const inline
References madness::FunctionImpl< T, NDIM >::add_op::alpha, madness::FunctionImpl< T, NDIM >::add_op::beta, madness::FunctionImpl< T, NDIM >::add_op::f, madness::FunctionImpl< T, NDIM >::add_op::g, and madness::CoeffTracker< T, NDIM >::make_child().
operator()()
template<typename T, std::size_t NDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::add_op::operator() (const keyT & key) const inline
if we are at the bottom of the trees, return the sum of the coeffs
References madness::FunctionImpl< T, NDIM >::add_op::alpha, madness::FunctionImpl< T, NDIM >::add_op::beta, madness::CoeffTracker< T, NDIM >::coeff(), madness::copy(), madness::FunctionImpl< T, NDIM >::add_op::f, madness::FunctionImpl< T, NDIM >::add_op::g, madness::Tensor< T >::gaxpy(), madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::CoeffTracker< T, NDIM >::is_leaf(), madness::CoeffTracker< T, NDIM >::key(), madness::FunctionImpl< T, NDIM >::parent_to_child(), madness::GenTensor< T >::reduce_rank(), and madness::TensorArgs::thresh.
randomize()
template<typename T, std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::add_op::randomize () const inline
serialize()
template<typename T, std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::add_op::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::add_op::alpha, madness::FunctionImpl< T, NDIM >::add_op::beta, madness::FunctionImpl< T, NDIM >::add_op::f, and madness::FunctionImpl< T, NDIM >::add_op::g.
Member Data Documentation
alpha
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::add_op::alpha
prefactor for f, g
Referenced by madness::FunctionImpl< T, NDIM >::add_op::activate(), madness::FunctionImpl< T, NDIM >::add_op::forward_ctor(), madness::FunctionImpl< T, NDIM >::add_op::make_child(), madness::FunctionImpl< T, NDIM >::add_op::operator()(), and madness::FunctionImpl< T, NDIM >::add_op::serialize().
beta
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::add_op::beta
Referenced by madness::FunctionImpl< T, NDIM >::add_op::activate(), madness::FunctionImpl< T, NDIM >::add_op::forward_ctor(), madness::FunctionImpl< T, NDIM >::add_op::make_child(), madness::FunctionImpl< T, NDIM >::add_op::operator()(), and madness::FunctionImpl< T, NDIM >::add_op::serialize().
f
template<typename T, std::size_t NDIM> ctT madness::FunctionImpl< T, NDIM >::add_op::f
tracking coeffs of first and second addend
Referenced by madness::FunctionImpl< T, NDIM >::add_op::activate(), madness::FunctionImpl< T, NDIM >::add_op::make_child(), madness::FunctionImpl< T, NDIM >::add_op::operator()(), and madness::FunctionImpl< T, NDIM >::add_op::serialize().
g
template<typename T, std::size_t NDIM> ctT madness::FunctionImpl< T, NDIM >::add_op::g
Referenced by madness::FunctionImpl< T, NDIM >::add_op::activate(), madness::FunctionImpl< T, NDIM >::add_op::make_child(), madness::FunctionImpl< T, NDIM >::add_op::operator()(), and madness::FunctionImpl< T, NDIM >::add_op::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h