MADNESS: madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM > Struct Template Reference
madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM > Struct Template Reference
recursive part of recursive_apply
#include <funcimpl.h>
Public Types
typedef recursive_apply_op< opT, LDIM > this_type
Public Member Functions
recursive_apply_op ()
recursive_apply_op (implT *result, const CoeffTracker< T, LDIM > &iaf, const CoeffTracker< T, LDIM > &iag, const opT *apply_op)
recursive_apply_op (const recursive_apply_op &other)
Future< this_type > activate () const
std::pair< bool, coeffT > finalize (const double kernel_norm, const keyT &key, const coeffT &coeff) const
sole purpose is to wait for the kernel norm, wrap it and send it back to caller
this_type forward_ctor (implT *r, const CoeffTracker< T, LDIM > &f1, const CoeffTracker< T, LDIM > &g1, const opT *apply_op1)
this_type make_child (const keyT &child) const
std::pair< bool, coeffT > operator() (const Key< NDIM > &key) const
make the NS-coefficients and send off the application of the operator
bool randomize () const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
opT * apply_op
CoeffTracker< T, LDIM > iaf
CoeffTracker< T, LDIM > iag
implT * result
Detailed Description
template<typename T, std::size_t NDIM>
template<typename opT, std::size_t LDIM>
struct madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >
recursive part of recursive_apply
Member Typedef Documentation
this_type
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> typedef recursive_apply_op<opT,LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::this_type
Constructor & Destructor Documentation
recursive_apply_op() [1/3]
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op () inline
recursive_apply_op() [2/3]
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op (implT * result, const CoeffTracker< T, LDIM > & iaf, const CoeffTracker< T, LDIM > & iag, const opT * apply_op) inline
References madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), and NDIM.
recursive_apply_op() [3/3]
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op (const recursive_apply_op< opT, LDIM > & other) inline
Member Function Documentation
activate()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> Future<this_type> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate () const inline
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op, f1, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::forward_ctor(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iaf, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iag, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result, madness::World::taskq, madness::FunctionImpl< T, NDIM >::world, and madness::detail::wrap_mem_fn().
finalize()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::finalize (const double kernel_norm, const keyT & key, const coeffT & coeff) const inline
sole purpose is to wait for the kernel norm, wrap it and send it back to caller
References madness::FunctionImpl< T, NDIM >::get_thresh(), madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result, madness::FunctionImpl< T, NDIM >::thresh, and madness::FunctionImpl< T, NDIM >::truncate_tol().
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()().
forward_ctor()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> this_type madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::forward_ctor (implT * r, const CoeffTracker< T, LDIM > & f1, const CoeffTracker< T, LDIM > & g1, const opT * apply_op1) inline
References f1.
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate().
make_child()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> this_type madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child (const keyT & child) const inline
References madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op, madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iaf, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iag, madness::CoeffTracker< T, NDIM >::make_child(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result.
operator()()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator() (const Key< NDIM > & key) const inline
make the NS-coefficients and send off the application of the operator
Returns
a Future<bool,coeffT>(is_leaf,coeffT())
References madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op, madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::cdata, madness::CoeffTracker< T, NDIM >::coeff(), madness::copy(), madness::FunctionImpl< T, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::finalize(), madness::GenTensor< T >::full_tensor(), madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_k(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iaf, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iag, madness::outer(), p(), madness::World::rank(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result, s0, madness::FunctionImpl< T, NDIM >::targs, madness::WorldObject< Derived >::task(), and madness::FunctionImpl< T, NDIM >::world.
randomize()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> bool madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::randomize () const inline
serialize()
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iaf, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iag, and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result.
Member Data Documentation
apply_op
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> opT* madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize().
iaf
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> CoeffTracker<T,LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iaf
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize().
iag
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> CoeffTracker<T,LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iag
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize().
result
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> implT* madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::finalize(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h