MADNESS: madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op Struct Reference
madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op Struct Reference
#include <worlddc.h>
Public Types
typedef Range< typename std::vector< keyT >::const_iterator > rangeT
Public Member Functions
P2Op (implT *impl)
P2Op (const P2Op &p)
bool operator() (typename rangeT::iterator &iterator) const
Public Attributes
implT * impl
Member Typedef Documentation
rangeT
template<typename keyT , typename valueT , typename hashfunT > typedef Range<typename std::vector<keyT>::const_iterator> madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::rangeT
Constructor & Destructor Documentation
P2Op() [1/2]
template<typename keyT , typename valueT , typename hashfunT > madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::P2Op (implT * impl) inline
P2Op() [2/2]
template<typename keyT , typename valueT , typename hashfunT > madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::P2Op (const P2Op & p) inline
Member Function Documentation
operator()()
template<typename keyT , typename valueT , typename hashfunT > bool madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::operator() (typename rangeT::iterator & iterator) const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::erase(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::impl, madness::WorldContainerImpl< keyT, valueT, hashfunT >::insert(), madness::WorldContainerImpl< keyT, valueT, hashfunT >::local, MADNESS_ASSERT, madness::WorldContainerImpl< keyT, valueT, hashfunT >::owner(), and madness::WorldObject< Derived >::task().
Member Data Documentation
impl
template<typename keyT , typename valueT , typename hashfunT > implT* madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::impl
Referenced by madness::WorldContainerImpl< keyT, valueT, hashfunT >::P2Op::operator()().
The documentation for this struct was generated from the following file:
worlddc.h