MADNESS: madness::CCFunction Struct Reference
madness::CCFunction Struct Reference
structure for a CC Function 3D which holds an index and a type
#include <CCStructures.h>
Public Member Functions
CCFunction ()
CCFunction (const real_function_3d &f)
CCFunction (const real_function_3d &f, const size_t &ii)
CCFunction (const real_function_3d &f, const size_t &ii, const FuncType &type_)
CCFunction (const CCFunction &other)
real_function_3d f () const
real_function_3d get () const
void info (World &world, const std::string &msg=" ") const
double inner (const CCFunction &f) const
double inner (const real_function_3d &f) const
std::string name () const
CCFunction operator* (const double &fac) const
scalar multiplication
bool operator== (const CCFunction &other) const
void plot (const std::string &msg="") const
plotting
void set (const real_function_3d &other)
Public Attributes
double current_error
real_function_3d function
size_t i
FuncType type
Detailed Description
structure for a CC Function 3D which holds an index and a type
Constructor & Destructor Documentation
CCFunction() [1/5]
madness::CCFunction::CCFunction () inline
Referenced by operator*().
CCFunction() [2/5]
madness::CCFunction::CCFunction (const real_function_3d & f) inline
CCFunction() [3/5]
madness::CCFunction::CCFunction (const real_function_3d & f, const size_t & ii) inline
CCFunction() [4/5]
madness::CCFunction::CCFunction (const real_function_3d & f, const size_t & ii, const FuncType & type_) inline
CCFunction() [5/5]
madness::CCFunction::CCFunction (const CCFunction & other) inline
Member Function Documentation
f()
real_function_3d madness::CCFunction::f () const inline
Referenced by inner().
get()
real_function_3d madness::CCFunction::get () const inline
info()
void madness::CCFunction::info (World & world, const std::string & msg = " ") const
References current_error, name(), and madness::World::rank().
inner() [1/2]
double madness::CCFunction::inner (const CCFunction & f) const inline
References f().
inner() [2/2]
double madness::CCFunction::inner (const real_function_3d & f) const inline
References f().
name()
std::string madness::CCFunction::name () const
References madness::HOLE, i, madness::MIXED, madness::PARTICLE, madness::RESPONSE, madness::stringify(), and type.
Referenced by info(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), madness::CCConvolutionOperator::operator()(), plot(), and madness::CCPairFunction::print_size().
operator*()
CCFunction madness::CCFunction::operator* (const double & fac) const inline
scalar multiplication
References CCFunction(), i, and type.
operator==()
bool madness::CCFunction::operator== (const CCFunction & other) const inline
References i, and type.
plot()
void madness::CCFunction::plot (const std::string & msg = "") const inline
plotting
References name(), and madness::plot_plane().
set()
void madness::CCFunction::set (const real_function_3d & other) inline
Member Data Documentation
current_error
double madness::CCFunction::current_error
Referenced by info().
function
real_function_3d madness::CCFunction::function
Referenced by madness::CCPairFunction::copy(), madness::CCPairFunction::dirac_convolution_decomposed(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), madness::CCPairFunction::invert_sign(), madness::CCPairFunction::make_xy_u(), madness::CCConvolutionOperator::operator()(), madness::CCPairFunction::print_size(), madness::CCPairFunction::project_out_op_decomposed(), and madness::CCConvolutionOperator::update_elements().
i
size_t madness::CCFunction::i
Referenced by madness::CCPairFunction::copy(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), name(), madness::CC_vecfunction::operator()(), madness::CCConvolutionOperator::operator()(), operator*(), operator==(), and madness::CCConvolutionOperator::update_elements().
type
FuncType madness::CCFunction::type
Referenced by madness::CCPairFunction::copy(), madness::TDHF::initialize_singles(), madness::CC2::initialize_singles(), name(), madness::CCConvolutionOperator::operator()(), operator*(), and operator==().
The documentation for this struct was generated from the following files:
CCStructures.h
CCStructures.cc