MADNESS: madness::CCConvolutionOperator Struct Reference
madness::CCConvolutionOperator Struct Reference
#include <CCStructures.h>
Classes
struct Parameters
parameter class
Public Member Functions
CCConvolutionOperator (World &world, const OpType type, const Parameters &param)
void clear_all_intermediates ()
name speaks for itself
void clear_intermediates (const FuncType &type)
TwoElectronFactory get_kernel () const
create a TwoElectronFactory with the operatorkernel
size_t info () const
prints out information (operatorname, number of stored intermediates ...)
std::string name () const
real_function_3d operator() (const real_function_3d &f) const
vector_real_function_3d operator() (const CC_vecfunction &bra, const CCFunction &ket) const
vector_real_function_3d operator() (const vector_real_function_3d &f) const
real_function_3d operator() (const CCFunction &bra, const CCFunction &ket, const bool use_im=true) const
real_function_6d operator() (const real_function_6d &u, const size_t particle) const
real_function_3d operator() (const CCFunction &bra, const real_function_6d &u, const size_t particle) const
void print_intermediate (const FuncType type) const
void sanity () const
sanity check .. doens not do so much
OpType type () const
void update_elements (const CC_vecfunction &bra, const CC_vecfunction &ket)
Public Attributes
const Parameters & parameters
Private Member Functions
void error (const std::string &msg) const
SeparatedConvolution< double, 3 > * init_op (const OpType &type, const Parameters &parameters) const
Private Attributes
intermediateT imH
intermediateT imP
intermediateT imR
const std::shared_ptr< real_convolution_3d > op
const OpType operator_type
the operatortype, currently this can be g12_ or f12_
World & world
the world
Detailed Description
Helper Structure that carries out operations on CC_functions The structure can hold intermediates for g12 and f12 of type : <mo_bra_k|op|type> with type=HOLE,PARTICLE or RESPONSE some 6D operations are also included The structure does not know if nuclear correlation facors are used, so the corresponding bra states have to be prepared beforehand
Constructor & Destructor Documentation
CCConvolutionOperator()
madness::CCConvolutionOperator::CCConvolutionOperator (World & world, const OpType type, const Parameters & param) inline
Parameters
[in] world
[in] optype the operatortype (can be g12_ or f12_)
[in] param the parameters of the current CC-Calculation (including function and operator thresholds and the exponent for f12)
Member Function Documentation
clear_all_intermediates()
void madness::CCConvolutionOperator::clear_all_intermediates () inline
name speaks for itself
References clear_intermediates(), madness::HOLE, madness::PARTICLE, and madness::RESPONSE.
clear_intermediates()
void madness::CCConvolutionOperator::clear_intermediates (const FuncType & type)
Parameters
[in] the type of which intermediates will be deleted e.g if(type==HOLE) then all intermediates of type <mo_bra_k|op|HOLE> will be deleted
References madness::Pairs< T >::allpairs, madness::assign_name(), error(), madness::HOLE, imH, imP, imR, name(), madness::PARTICLE, madness::World::rank(), madness::RESPONSE, type(), and world.
Referenced by clear_all_intermediates().
error()
void madness::CCConvolutionOperator::error (const std::string & msg) const inline private
Parameters
[in] msg output message the function will throw an MADNESS_EXCEPTION
References madness::assign_name(), MADNESS_EXCEPTION, operator_type, madness::World::rank(), and world.
Referenced by clear_intermediates(), get_kernel(), init_op(), and update_elements().
get_kernel()
TwoElectronFactory madness::CCConvolutionOperator::get_kernel () const inline
create a TwoElectronFactory with the operatorkernel
References madness::TwoElectronFactory::dcut(), e(), error(), madness::TwoElectronFactory::f12(), madness::TwoElectronFactory::gamma(), madness::CCConvolutionOperator::Parameters::gamma, name(), madness::OT_F12, madness::OT_G12, parameters, type(), and world.
info()
size_t madness::CCConvolutionOperator::info () const
prints out information (operatorname, number of stored intermediates ...)
References madness::Pairs< T >::allpairs, imH, imP, imR, name(), madness::World::rank(), madness::size_of(), and world.
init_op()
SeparatedConvolution< double, 3 > * madness::CCConvolutionOperator::init_op (const OpType & type, const Parameters & parameters) const private
Parameters
[in] optype can be f12_ or g12_ depending on which operator shall be intitialzied
[in] parameters parameters (thresholds etc) initializes the operators
References madness::assign_name(), madness::CoulombOperatorPtr(), error(), madness::CCConvolutionOperator::Parameters::gamma, madness::CCConvolutionOperator::Parameters::lo, MADNESS_EXCEPTION, madness::OT_F12, madness::OT_G12, parameters, madness::World::rank(), madness::SlaterF12OperatorPtr(), madness::CCConvolutionOperator::Parameters::thresh_op, type(), and world.
name()
std::string madness::CCConvolutionOperator::name () const inline
Parameters
[out] prints the name of the operator (convenience) which is g12 or f12 or maybe other things like gf in the future
References madness::assign_name(), and operator_type.
Referenced by clear_intermediates(), get_kernel(), info(), madness::CCPairFunction::name(), and update_elements().
operator()() [1/6]
real_function_3d madness::CCConvolutionOperator::operator() (const real_function_3d & f) const inline
Parameters
[in] f a 3D function
[out] the convolution op(f), no intermediates are used
References madness::f, op, and madness::Function< T, NDIM >::truncate().
Referenced by operator()().
operator()() [2/6]
vector_real_function_3d madness::CCConvolutionOperator::operator() (const CC_vecfunction & bra, const CCFunction & ket) const inline
Parameters
[in] bra a CC_vecfunction
[in] ket a CC_function
[out] vector[i] = <bra[i]|op|ket>
References madness::apply(), madness::CCFunction::function, madness::CC_vecfunction::functions, madness::CC_vecfunction::get_vecfunction(), madness::HOLE, madness::mul(), op, operator()(), madness::truncate(), madness::CC_vecfunction::type, and world.
operator()() [3/6]
vector_real_function_3d madness::CCConvolutionOperator::operator() (const vector_real_function_3d & f) const inline
References madness::f, and world.
operator()() [4/6]
real_function_3d madness::CCConvolutionOperator::operator() (const CCFunction & bra, const CCFunction & ket, const bool use_im = true) const
References madness::Pairs< T >::allpairs, madness::assign_name(), madness::CCFunction::function, madness::HOLE, madness::CCFunction::i, imH, imP, imR, madness::MIXED, madness::CCFunction::name(), operator_type, madness::PARTICLE, madness::World::rank(), madness::RESPONSE, madness::Function< T, NDIM >::truncate(), madness::CCFunction::type, and world.
operator()() [5/6]
real_function_6d madness::CCConvolutionOperator::operator() (const real_function_6d & u, const size_t particle) const
References MADNESS_ASSERT, op, operator_type, madness::OT_G12, and u().
operator()() [6/6]
real_function_3d madness::CCConvolutionOperator::operator() (const CCFunction & bra, const real_function_6d & u, const size_t particle) const
References madness::copy(), madness::Function< T, NDIM >::dirac_convolution(), madness::CCFunction::function, MADNESS_ASSERT, madness::multiply(), op, operator_type, madness::OT_G12, and u().
print_intermediate()
void madness::CCConvolutionOperator::print_intermediate (const FuncType type) const inline
Parameters
[in] type the type of intermediates which will be printed, can be HOLE,PARTICLE or RESPONSE
References madness::Pairs< T >::allpairs, madness::assign_name(), madness::HOLE, imH, imP, imR, operator_type, madness::PARTICLE, madness::RESPONSE, and type().
Referenced by sanity().
sanity()
void madness::CCConvolutionOperator::sanity () const inline
sanity check .. doens not do so much
References madness::HOLE, and print_intermediate().
type()
OpType madness::CCConvolutionOperator::type () const inline
References operator_type.
Referenced by clear_intermediates(), get_kernel(), init_op(), and print_intermediate().
update_elements()
void madness::CCConvolutionOperator::update_elements (const CC_vecfunction & bra, const CC_vecfunction & ket)
Parameters
[in] bra a vector of CC_functions, the type has to be HOLE
[in] ket a vector of CC_functions, the type can be HOLE,PARTICLE,RESPONSE updates intermediates of the type <bra|op|ket>
References madness::assign_name(), error(), madness::CCFunction::function, madness::CC_vecfunction::functions, madness::HOLE, madness::CCFunction::i, imH, imP, imR, madness::Pairs< T >::insert(), k, name(), madness::PARTICLE, madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::RESPONSE, madness::CC_vecfunction::size(), madness::Function< T, NDIM >::truncate(), madness::CC_vecfunction::type, and world.
Referenced by madness::TDHF::TDHF().
Member Data Documentation
imH
intermediateT madness::CCConvolutionOperator::imH private
Referenced by clear_intermediates(), info(), operator()(), print_intermediate(), and update_elements().
imP
intermediateT madness::CCConvolutionOperator::imP private
Referenced by clear_intermediates(), info(), operator()(), print_intermediate(), and update_elements().
imR
intermediateT madness::CCConvolutionOperator::imR private
Referenced by clear_intermediates(), info(), operator()(), print_intermediate(), and update_elements().
op
const std::shared_ptr<real_convolution_3d> madness::CCConvolutionOperator::op private
Referenced by operator()().
operator_type
const OpType madness::CCConvolutionOperator::operator_type private
the operatortype, currently this can be g12_ or f12_
Referenced by error(), name(), operator()(), print_intermediate(), and type().
parameters
const Parameters& madness::CCConvolutionOperator::parameters
Referenced by get_kernel(), and init_op().
world
World& madness::CCConvolutionOperator::world private
the world
Referenced by clear_intermediates(), error(), get_kernel(), info(), init_op(), operator()(), and update_elements().
The documentation for this struct was generated from the following files:
CCStructures.h
CCStructures.cc