MADNESS: madness::CCTimer Struct Reference
madness::CCTimer Struct Reference
Timer Structure.
#include <CCStructures.h>
Public Member Functions
CCTimer (World &world, std::string msg)
double current_cpu ()
std::pair< double, double > current_time (bool printout=false)
double current_wall ()
double get_cpu_time_diff () const
double get_wall_time_diff () const
void info (const bool debug=true, const double norm=12345.6789)
print out information about the passed time since the CC_TIMER object was created
void print ()
void print () const
void print (const std::pair< double, double > &times) const
CCTimer start ()
CCTimer stop ()
void update_time ()
Public Attributes
double end_cpu
double end_wall
std::string operation
double start_cpu
double start_wall
double time_cpu
double time_wall
World & world
Detailed Description
Timer Structure.
Constructor & Destructor Documentation
CCTimer()
madness::CCTimer::CCTimer (World & world, std::string msg) inline
TDA_TIMER contructor
Parameters
[in] world the world
[in] msg a string that contains the desired printout when info function is called
Member Function Documentation
current_cpu()
double madness::CCTimer::current_cpu () inline
References current_time().
current_time()
std::pair<double,double> madness::CCTimer::current_time (bool printout = false) inline
References stop(), time_cpu, and time_wall.
Referenced by current_cpu(), current_wall(), print(), and madness::CC2::solve().
current_wall()
double madness::CCTimer::current_wall () inline
References current_time().
get_cpu_time_diff()
double madness::CCTimer::get_cpu_time_diff () const inline
References end_cpu.
get_wall_time_diff()
double madness::CCTimer::get_wall_time_diff () const inline
References end_wall.
info()
void madness::CCTimer::info (const bool debug = true, const double norm = 12345.6789)
print out information about the passed time since the CC_TIMER object was created
References madness::detail::norm(), operation, madness::World::rank(), time_cpu, time_wall, update_time(), and world.
Referenced by madness::TDHF::apply_G(), madness::TDHF::get_tda_potential(), madness::CC2::iterate_singles(), madness::TDHF::make_bra(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_overlap_matrix(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_potentials(), madness::TDHF::orthonormalize(), madness::CC2::solve(), madness::CC2::solve_cc2(), madness::TDHF::solve_cis(), madness::CC2::update_reg_residues_ex(), and madness::CC2::update_reg_residues_gs().
print() [1/3]
void madness::CCTimer::print () inline
References current_time().
Referenced by madness::TDHF::apply_excitation_operators(), madness::TDHF::canonicalize(), madness::TDHF::iterate_vectors(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_virtuals(), and print().
print() [2/3]
void madness::CCTimer::print () const inline
References print(), time_cpu, and time_wall.
print() [3/3]
void madness::CCTimer::print (const std::pair< double, double > & times) const inline
References operation, madness::World::rank(), and world.
start()
CCTimer madness::CCTimer::start () inline
References madness::cpu_time(), start_cpu, start_wall, and madness::wall_time().
Referenced by madness::TDHF::make_perturbed_fock_matrix().
stop()
CCTimer madness::CCTimer::stop () inline
References madness::cpu_time(), end_cpu, end_wall, start_cpu, start_wall, time_cpu, time_wall, and madness::wall_time().
Referenced by current_time(), and madness::TDHF::make_perturbed_fock_matrix().
update_time()
void madness::CCTimer::update_time () inline
References madness::cpu_time(), start_cpu, start_wall, time_cpu, time_wall, and madness::wall_time().
Referenced by info().
Member Data Documentation
end_cpu
double madness::CCTimer::end_cpu
Referenced by get_cpu_time_diff(), and stop().
end_wall
double madness::CCTimer::end_wall
Referenced by get_wall_time_diff(), and stop().
operation
std::string madness::CCTimer::operation
Referenced by info(), and print().
start_cpu
double madness::CCTimer::start_cpu
Referenced by start(), stop(), and update_time().
start_wall
double madness::CCTimer::start_wall
Referenced by start(), stop(), and update_time().
time_cpu
double madness::CCTimer::time_cpu
Referenced by current_time(), info(), print(), stop(), and update_time().
time_wall
double madness::CCTimer::time_wall
Referenced by current_time(), info(), print(), stop(), and update_time().
world
World& madness::CCTimer::world
Referenced by info(), and print().
The documentation for this struct was generated from the following files:
CCStructures.h
CCStructures.cc