MADNESS: test_correlation_factor Struct Reference
test_correlation_factor Struct Reference
#include <test_correlation_factor.h>
Public Member Functions
test_correlation_factor (World &world, const real_function_3d &f, const double eps)
test_correlation_factor (World &world, const CorrelationFactor &corrfactor, const real_function_3d &f, const double eps)
void make_test ()
void output (const std::string &msg) const
Public Attributes
CorrelationFactor corrfac
const double eps
real_function_3d f
World & world
Constructor & Destructor Documentation
test_correlation_factor() [1/2]
test_correlation_factor::test_correlation_factor (World & world, const real_function_3d & f, const double eps) inline
References corrfac, e(), and world.
test_correlation_factor() [2/2]
test_correlation_factor::test_correlation_factor (World & world, const CorrelationFactor & corrfactor, const real_function_3d & f, const double eps) inline
Member Function Documentation
make_test()
void test_correlation_factor::make_test () inline
References corrfac, eps, f, output(), madness::plot_plane(), madness::stringify(), and world.
output()
void test_correlation_factor::output (const std::string & msg) const inline
References world.
Referenced by make_test().
Member Data Documentation
corrfac
CorrelationFactor test_correlation_factor::corrfac
Referenced by make_test(), and test_correlation_factor().
eps
const double test_correlation_factor::eps
Referenced by make_test().
f
real_function_3d test_correlation_factor::f
Referenced by make_test().
world
World& test_correlation_factor::world
Referenced by make_test(), output(), and test_correlation_factor().
The documentation for this struct was generated from the following file:
test_correlation_factor.h