MADNESS: CalculationParameters Struct Reference
CalculationParameters Struct Reference
Public Member Functions
CalculationParameters ()
void print_info ()
void read_file (const std::string filename)
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
double dconv
conversion criteria
double delta
step size to calc numerical derivative of residual
double eprec
precision of smoothing parameter
double L
box size
double lo
smallest length scale we need to resolve
int maxiter
max number of iteration
int nio
number of I/O node
bool nonlinear
if true do non linear optimization
bool plot
if true plot vmo or umo
std::string symbol
symbol of target atom
double thresh
truncation threshold
Constructor & Destructor Documentation
CalculationParameters()
CalculationParameters::CalculationParameters () inline
Member Function Documentation
print_info()
void CalculationParameters::print_info () inline
References madness::CalculationParameters::dconv(), delta, madness::CalculationParameters::L(), madness::CalculationParameters::lo(), madness::CalculationParameters::maxiter(), madness::plot(), madness::QCCalculationParametersBase::print(), and thresh.
read_file()
void CalculationParameters::read_file (const std::string filename) inline
References madness::CalculationParameters::dconv(), delta, madness::f, madness::filename, madness::CalculationParameters::L(), madness::CalculationParameters::maxiter(), madness::plot(), print_info(), and thresh.
serialize()
template<typename Archive > void CalculationParameters::serialize (Archive & ar) inline
References madness::CalculationParameters::dconv(), delta, madness::CalculationParameters::L(), madness::CalculationParameters::lo(), madness::CalculationParameters::maxiter(), and thresh.
Member Data Documentation
dconv
double CalculationParameters::dconv
conversion criteria
delta
double CalculationParameters::delta
step size to calc numerical derivative of residual
eprec
double CalculationParameters::eprec
precision of smoothing parameter
L
double CalculationParameters::L
box size
lo
double CalculationParameters::lo
smallest length scale we need to resolve
maxiter
int CalculationParameters::maxiter
max number of iteration
nio
int CalculationParameters::nio
number of I/O node
nonlinear
bool CalculationParameters::nonlinear
if true do non linear optimization
plot
bool CalculationParameters::plot
if true plot vmo or umo
symbol
std::string CalculationParameters::symbol
symbol of target atom
thresh
double CalculationParameters::thresh
truncation threshold
The documentation for this struct was generated from the following file:
mcpfit.cc