MADNESS: madness::TDHF::Parameters Struct Reference
madness::TDHF::Parameters Struct Reference
the TDHF parameter class
#include <TDHF.h>
Public Member Functions
Parameters ()
Parameters (const Parameters &other)
Parameters (World &world, const std::shared_ptr< SCF > &scf, const std::string &input)
todo: read_from_file compatible with dist. memory computation
double damping_width () const
double dconv () const
bool debug () const
bool do_oep () const
double econv () const
std::size_t excitations () const
std::vector< std::string > exops () const
std::size_t freeze () const
CCConvolutionOperator::Parameters get_ccc_parameters () const
make parameters for convolution operator
std::size_t guess_active_orbitals () const
double guess_cm () const
double guess_dconv () const
bool guess_diag () const
double guess_econv () const
std::string guess_excitation_operators () const
std::size_t guess_excitations () const
std::size_t guess_maxiter () const
std::size_t guess_occ_to_virt () const
void initialize_all ()
std::string irrep () const
std::size_t iterating_excitations () const
std::size_t kain_subspace () const
double lo () const
std::size_t maxiter () const
bool no_compute () const
bool plot () const
std::vector< size_t > restart () const
void set_derived_values (const std::shared_ptr< SCF > &scf)
auto assigns all parameters which where not explicitly given and which depend on other parameters of the reference calculation
bool store_potential () const
double thresh () const
bool triplet () const
Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
T get (const std::string key) const
QCParameter & get_parameter (const std::string key)
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read (World &world, const std::string filename, const std::string tag)
read the parameters from file
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
ParameterContainerT parameters
bool print_debug =false
Detailed Description
the TDHF parameter class
Constructor & Destructor Documentation
Parameters() [1/3]
madness::TDHF::Parameters::Parameters () inline
References initialize_all().
Parameters() [2/3]
madness::TDHF::Parameters::Parameters (const Parameters & other) inline
Parameters() [3/3]
madness::TDHF::Parameters::Parameters (World & world, const std::shared_ptr< SCF > & scf, const std::string & input) inline
todo: read_from_file compatible with dist. memory computation
References initialize_all(), madness::QCCalculationParametersBase::read(), set_derived_values(), and madness::TDHF::world.
Member Function Documentation
damping_width()
double madness::TDHF::Parameters::damping_width () const inline
Referenced by madness::TDHF::make_old_guess().
dconv()
double madness::TDHF::Parameters::dconv () const inline
Referenced by madness::TDHF::iterate_cis_final_vectors(), and set_derived_values().
debug()
bool madness::TDHF::Parameters::debug () const inline
Referenced by madness::TDHF::apply_G(), madness::TDHF::canonicalize(), madness::TDHF::get_tda_potential(), madness::TDHF::make_bra(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_overlap_matrix(), madness::TDHF::make_perturbed_fock_matrix(), madness::TDHF::make_potentials(), madness::TDHF::make_virtuals(), madness::TDHF::orthonormalize(), and madness::TDHF::TDHF().
do_oep()
bool madness::TDHF::Parameters::do_oep () const inline
Referenced by madness::TDHF::get_tda_potential().
econv()
double madness::TDHF::Parameters::econv () const inline
Referenced by madness::TDHF::iterate_cis_final_vectors(), and set_derived_values().
excitations()
std::size_t madness::TDHF::Parameters::excitations () const inline
Referenced by madness::TDHF::iterate_vectors(), set_derived_values(), and madness::TDHF::solve_cis().
exops()
std::vector<std::string> madness::TDHF::Parameters::exops () const inline
Referenced by madness::TDHF::apply_excitation_operators(), and madness::TDHF::make_old_guess().
freeze()
std::size_t madness::TDHF::Parameters::freeze () const inline
Referenced by madness::TDHF::analyze(), madness::TDHF::apply_G(), madness::TDHF::get_active_mo_bra(), madness::TDHF::get_active_mo_ket(), get_ccc_parameters(), madness::TDHF::initialize_singles(), madness::TDHF::iterate_vectors(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_old_guess(), madness::TDHF::make_perturbed_fock_matrix(), set_derived_values(), madness::TDHF::symmetrize(), madness::TDHF::TDHF(), and madness::TDHF::transform().
get_ccc_parameters()
CCConvolutionOperator::Parameters madness::TDHF::Parameters::get_ccc_parameters () const inline
make parameters for convolution operator
References freeze(), madness::CCConvolutionOperator::Parameters::freeze, madness::CCConvolutionOperator::Parameters::gamma, lo(), madness::CCConvolutionOperator::Parameters::lo, thresh(), and madness::CCConvolutionOperator::Parameters::thresh_op.
guess_active_orbitals()
std::size_t madness::TDHF::Parameters::guess_active_orbitals () const inline
Referenced by madness::TDHF::make_cis_matrix().
guess_cm()
double madness::TDHF::Parameters::guess_cm () const inline
Referenced by madness::TDHF::make_virtuals().
guess_dconv()
double madness::TDHF::Parameters::guess_dconv () const inline
Referenced by madness::TDHF::iterate_cis_guess_vectors().
guess_diag()
bool madness::TDHF::Parameters::guess_diag () const inline
Referenced by madness::TDHF::make_cis_matrix().
guess_econv()
double madness::TDHF::Parameters::guess_econv () const inline
Referenced by madness::TDHF::iterate_cis_guess_vectors().
guess_excitation_operators()
std::string madness::TDHF::Parameters::guess_excitation_operators () const inline
Referenced by madness::TDHF::apply_excitation_operators(), madness::TDHF::make_old_guess(), and madness::TDHF::make_virtuals().
guess_excitations()
std::size_t madness::TDHF::Parameters::guess_excitations () const inline
Referenced by madness::TDHF::initialize(), madness::TDHF::make_guess_from_initial_diagonalization(), and madness::TDHF::solve_cis().
guess_maxiter()
std::size_t madness::TDHF::Parameters::guess_maxiter () const inline
Referenced by madness::TDHF::initialize(), and madness::TDHF::iterate_cis_guess_vectors().
guess_occ_to_virt()
std::size_t madness::TDHF::Parameters::guess_occ_to_virt () const inline
Referenced by madness::TDHF::make_old_guess(), and madness::TDHF::make_virtuals().
initialize_all()
void madness::TDHF::Parameters::initialize_all () inline
add center of mass functions determined by the homo-energy will add s,px,py,pz functions in the center of mass with exponent: -(e_homo/c) and c=guess_cm is the value of this parameter
use the diagonal approximation for the guess (only e_a -e_i terms in CIS matrix) much faster
determine active orbitals in guess (for all inactive orbitals only the diagonal e_a-e_i term is computed in the guess guess_active_orbitals=0 is the same as guess_diag
Vector of strings which contains the polynomial excitation operators For this to be used the tda_guess key has to be "custom" The strings are given in a format like: "c c1 x x1 y y1 z z1, c c2 x x2 y y2 z z2, ..." which will be interpreted as: c1*x^x1*y^y1*z^z1 + c2*x^x2*y^y2*z^z2 + ....
Referenced by Parameters().
irrep()
std::string madness::TDHF::Parameters::irrep () const inline
Referenced by madness::TDHF::check_consistency(), and madness::TDHF::make_guess_from_initial_diagonalization().
iterating_excitations()
std::size_t madness::TDHF::Parameters::iterating_excitations () const inline
Referenced by set_derived_values(), and madness::TDHF::solve_cis().
kain_subspace()
std::size_t madness::TDHF::Parameters::kain_subspace () const inline
Referenced by madness::TDHF::iterate_cis_final_vectors(), and madness::TDHF::iterate_vectors().
lo()
double madness::TDHF::Parameters::lo () const inline
Referenced by madness::TDHF::apply_G(), get_ccc_parameters(), and madness::TDHF::get_tda_potential().
maxiter()
std::size_t madness::TDHF::Parameters::maxiter () const inline
Referenced by madness::TDHF::iterate_cis_final_vectors().
no_compute()
bool madness::TDHF::Parameters::no_compute () const inline
Referenced by madness::TDHF::TDHF().
plot()
bool madness::TDHF::Parameters::plot () const inline
Referenced by madness::TDHF::get_tda_potential(), madness::TDHF::iterate_vectors(), and madness::TDHF::plot().
restart()
std::vector<size_t> madness::TDHF::Parameters::restart () const inline
Referenced by madness::TDHF::solve_cis().
set_derived_values()
void madness::TDHF::Parameters::set_derived_values (const std::shared_ptr< SCF > & scf)
auto assigns all parameters which where not explicitly given and which depend on other parameters of the reference calculation
References dconv(), econv(), excitations(), freeze(), madness::FunctionDefaults< NDIM >::get_thresh(), iterating_excitations(), madness::QCCalculationParametersBase::set_derived_value(), and thresh().
Referenced by Parameters().
store_potential()
bool madness::TDHF::Parameters::store_potential () const inline
Referenced by madness::TDHF::iterate_vectors().
thresh()
double madness::TDHF::Parameters::thresh () const inline
Referenced by madness::TDHF::apply_G(), madness::TDHF::canonicalize(), get_ccc_parameters(), madness::TDHF::get_tda_potential(), madness::TDHF::iterate_vectors(), madness::TDHF::make_guess_from_initial_diagonalization(), madness::TDHF::make_mo_bra(), madness::TDHF::make_mo_ket(), madness::TDHF::orthonormalize(), set_derived_values(), and madness::TDHF::TDHF().
triplet()
bool madness::TDHF::Parameters::triplet () const inline
Referenced by madness::TDHF::get_tda_potential().
The documentation for this struct was generated from the following files:
TDHF.h
TDHF.cc