MADNESS: madness::archive::ArchiveImpl< ParallelOutputArchive, T > Struct Template Reference
madness::archive::ArchiveImpl< ParallelOutputArchive, T > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Specialization of ArchiveImpl for parallel output archives.
#include <parallel_archive.h>
Static Public Member Functions
template<typename Q >
static std::enable_if< std::is_base_of< ParallelSerializableObject, Q >::value, const ParallelOutputArchive & >::type wrap_store (const ParallelOutputArchive &ar, const Q &t)
Store the data in the archive.
template<typename Q >
static std::enable_if<!std::is_base_of< ParallelSerializableObject, Q >::value, const ParallelOutputArchive & >::type wrap_store (const ParallelOutputArchive &ar, const Q &t)
Store the data in the archive.
Detailed Description
template<class T>
struct madness::archive::ArchiveImpl< ParallelOutputArchive, T >
Specialization of ArchiveImpl for parallel output archives.
Attention
No type-checking is performed.
Template Parameters
T The data type.
Member Function Documentation
wrap_store() [1/2]
template<class T > template<typename Q > static std::enable_if<std::is_base_of<ParallelSerializableObject, Q>::value, const ParallelOutputArchive&>::type madness::archive::ArchiveImpl< ParallelOutputArchive, T >::wrap_store (const ParallelOutputArchive & ar, const Q & t) inline static
Store the data in the archive.
Parallel objects are forwarded to their implementation of parallel store.
The function only appears (due to enable_if) if Q is a parallel serializable object.
Todo:
Is Q necessary? I'm sure it is, but can't figure out why at a first glance.
Template Parameters
Q Description needed.
Parameters
[in] ar The parallel archive.
[in] t The parallel object to store.
Returns
The parallel archive.
References madness::archive::ArchiveStoreImpl< Archive, T >::store().
wrap_store() [2/2]
template<class T > template<typename Q > static std::enable_if<!std::is_base_of<ParallelSerializableObject, Q>::value, const ParallelOutputArchive&>::type madness::archive::ArchiveImpl< ParallelOutputArchive, T >::wrap_store (const ParallelOutputArchive & ar, const Q & t) inline static
Store the data in the archive.
Serial objects write only from process 0.
The function only appears (due to enable_if) if Q is not a parallel serializable object.
Todo:
Same question about Q.
Template Parameters
Q Description needed.
Parameters
[in] ar The parallel archive.
[in] t The serial data.
Returns
The parallel archive.
References madness::archive::BaseParallelArchive< Archive >::get_world(), madness::archive::BaseParallelArchive< Archive >::local_archive(), and madness::World::rank().
The documentation for this struct was generated from the following file:
parallel_archive.h