MADNESS: abs_square_op< Q, NDIM > Struct Template Reference
abs_square_op< Q, NDIM > Struct Template Reference
Public Types
typedef TensorTypeData< Q >::scalar_type resultT
Public Member Functions
Tensor< resultT > operator() (const Key< NDIM > &key, const Tensor< Q > &t) const
template<typename Archive >
void serialize (Archive &ar)
Member Typedef Documentation
resultT
template<typename Q , int NDIM> typedef TensorTypeData<Q>::scalar_type abs_square_op< Q, NDIM >::resultT
Member Function Documentation
operator()()
template<typename Q , int NDIM> Tensor<resultT> abs_square_op< Q, NDIM >::operator() (const Key< NDIM > & key, const Tensor< Q > & t) const inline
References madness::abs(), BINARY_OPTIMIZED_ITERATOR, d(), madness::BaseTensor::dim(), and madness::BaseTensor::ndim().
serialize()
template<typename Q , int NDIM> template<typename Archive > void abs_square_op< Q, NDIM >::serialize (Archive & ar) inline
The documentation for this struct was generated from the following file:
wannier.cc