MADNESS: refpotfunctor Struct Reference
refpotfunctor Struct Reference
reference potential for the Poisson solver of a Gaussian
Public Member Functions
refpotfunctor (double alpha)
ctor takes the exponent of the corresponding Gaussian exp(-alpha r^2)
double operator() (const coord_3d &xyz) const
Public Attributes
double arg
double exponent
double prefac
double sigma
Detailed Description
reference potential for the Poisson solver of a Gaussian
Given a unnormalized Gaussian return the result of the Poisson equation: [ V(r) = dr' 1/|r-r'| exp(-alpha r'^2) ] Formulas taken from wikipedia: http://en.wikipedia.org/wiki/Poisson%27s_equation#Potential_of_a_Gaussian_charge_density [ ^2 = (r) = Q * exp(-alpha r^2) (r) = Q * 1/r erf(r/{2}) ] where the Gaussian function is NOT normalized, and alpha = 1/(2 sigma^2)
Constructor & Destructor Documentation
refpotfunctor()
refpotfunctor::refpotfunctor (double alpha) inline
ctor takes the exponent of the corresponding Gaussian exp(-alpha r^2)
References madness::arg(), madness::constants::pi, pow(), and sigma.
Member Function Documentation
operator()()
double refpotfunctor::operator() (const coord_3d & xyz) const inline
References madness::arg(), and madness::Vector< T, N >::normf().
Member Data Documentation
arg
double refpotfunctor::arg
exponent
double refpotfunctor::exponent
prefac
double refpotfunctor::prefac
sigma
double refpotfunctor::sigma
The documentation for this struct was generated from the following file:
test_SCFOperators.cc