MADNESS: madness::MP2::Parameters Struct Reference
madness::MP2::Parameters Struct Reference
POD for MP2 keywords.
Public Member Functions
Parameters (World &world)
ctor reading out the input file
void check_input (const std::shared_ptr< HartreeFock > hf) const
check the user input
double dconv () const
convenience function
double econv () const
convenience function
int freeze () const
convenience function
int i () const
convenience function
int j () const
convenience function
int maxiter () const
convenience function
int maxsub () const
convenience function
void read_and_set_derived_values (World &world)
int restart () const
convenience function
double thresh () const
Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
T get (const std::string key) const
QCParameter & get_parameter (const std::string key)
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
Public Attributes
bool do_oep
use OEP orbitals
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read (World &world, const std::string filename, const std::string tag)
read the parameters from file
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
ParameterContainerT parameters
bool print_debug =false
Detailed Description
POD for MP2 keywords.
Constructor & Destructor Documentation
Parameters()
madness::MP2::Parameters::Parameters (World & world) inline
ctor reading out the input file
the map with initial values
References madness::QCCalculationParametersBase::print(), madness::World::rank(), read_and_set_derived_values(), and madness::MP2::world.
Member Function Documentation
check_input()
void madness::MP2::Parameters::check_input (const std::shared_ptr< HartreeFock > hf) const inline
check the user input
References freeze(), madness::MP2::hf, i(), j(), MADNESS_EXCEPTION, and thresh().
dconv()
double madness::MP2::Parameters::dconv () const inline
convenience function
econv()
double madness::MP2::Parameters::econv () const inline
convenience function
freeze()
int madness::MP2::Parameters::freeze () const inline
convenience function
Referenced by check_input().
i()
int madness::MP2::Parameters::i () const inline
convenience function
Referenced by check_input().
j()
int madness::MP2::Parameters::j () const inline
convenience function
Referenced by check_input().
maxiter()
int madness::MP2::Parameters::maxiter () const inline
convenience function
maxsub()
int madness::MP2::Parameters::maxsub () const inline
convenience function
read_and_set_derived_values()
void madness::MP2::Parameters::read_and_set_derived_values (World & world) inline
References madness::QCCalculationParametersBase::read(), madness::QCCalculationParametersBase::set_derived_value(), and madness::MP2::world.
Referenced by Parameters().
restart()
int madness::MP2::Parameters::restart () const inline
convenience function
thresh()
double madness::MP2::Parameters::thresh () const inline
Referenced by check_input().
Member Data Documentation
do_oep
bool madness::MP2::Parameters::do_oep
use OEP orbitals
The documentation for this struct was generated from the following file:
mp2.h