MADNESS: madness::archive::ArchiveImpl< ParallelOutputArchive, archive_array< T > > Struct Template Reference
madness::archive::ArchiveImpl< ParallelOutputArchive, archive_array< T > > Struct Template Reference
MADNESS libraries » Parallel programming environment » Serialization
Write the archive array only from process zero.
#include <parallel_archive.h>
Static Public Member Functions
static const ParallelOutputArchive & wrap_store (const ParallelOutputArchive &ar, const archive_array< T > &t)
Store the archive_array in the parallel archive.
Detailed Description
template<class T>
struct madness::archive::ArchiveImpl< ParallelOutputArchive, archive_array< T > >
Write the archive array only from process zero.
Template Parameters
T The array data type.
Member Function Documentation
wrap_store()
template<class T > static const ParallelOutputArchive& madness::archive::ArchiveImpl< ParallelOutputArchive, archive_array< T > >::wrap_store (const ParallelOutputArchive & ar, const archive_array< T > & t) inline static
Store the archive_array in the parallel archive.
Parameters
[in] ar The parallel archive.
[in] t The array to store.
Returns
The parallel archive.
References madness::archive::BaseParallelArchive< Archive >::get_world(), madness::archive::BaseParallelArchive< Archive >::local_archive(), and madness::World::rank().
The documentation for this struct was generated from the following file:
parallel_archive.h