MADNESS: madness::Nemo::timer Struct Reference
madness::Nemo::timer Struct Reference
#include <nemo.h>
Public Member Functions
timer (World &world)
void end (const std::string msg)
void tag (const std::string msg)
Public Attributes
double sss
double ttt
World & world
Constructor & Destructor Documentation
timer()
madness::Nemo::timer::timer (World & world) inline
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, madness::wall_time(), and world.
Member Function Documentation
end()
void madness::Nemo::timer::end (const std::string msg) inline
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, madness::World::rank(), ss1, sss, tt1, ttt, madness::wall_time(), and world.
Referenced by madness::Nemo::hessian(), and madness::Nemo::set_protocol().
tag()
void madness::Nemo::timer::tag (const std::string msg) inline
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, madness::World::rank(), ss1, sss, tt1, ttt, madness::wall_time(), and world.
Referenced by madness::Nemo::compute_all_cphf().
Member Data Documentation
sss
double madness::Nemo::timer::sss
Referenced by end(), tag(), and timer().
ttt
double madness::Nemo::timer::ttt
Referenced by end(), tag(), and timer().
world
World& madness::Nemo::timer::world
Referenced by end(), tag(), and timer().
The documentation for this struct was generated from the following file:
nemo.h