MADNESS: madness::FunctionImpl< T, NDIM >::multiply_op< LDIM > Struct Template Reference
madness::FunctionImpl< T, NDIM >::multiply_op< LDIM > Struct Template Reference
perform this multiplication: h(1,2) = f(1,2) * g(1)
#include <funcimpl.h>
Public Types
typedef CoeffTracker< T, LDIM > ctL
typedef CoeffTracker< T, NDIM > ctT
typedef multiply_op< LDIM > this_type
Public Member Functions
multiply_op ()
multiply_op (implT *h, const ctT &f, const ctL &g, const int particle)
Future< this_type > activate () const
this_type forward_ctor (implT *h1, const ctT &f1, const ctL &g1, const int particle)
this_type make_child (const keyT &child) const
std::pair< bool, coeffT > operator() (const Key< NDIM > &key) const
apply this on a FunctionNode of f and g of Key key
bool screen (const coeffT &fcoeff, const coeffT &gcoeff, const keyT &key) const
return true if this will be a leaf node
template<typename Archive >
void serialize (const Archive &ar)
Static Public Member Functions
static bool randomize ()
Public Attributes
ctT f
ctL g
implT * h
the result function h(1,2) = f(1,2) * g(1)
int particle
if g is g(1) or g(2)
Detailed Description
template<typename T, std::size_t NDIM>
template<size_t LDIM>
struct madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >
perform this multiplication: h(1,2) = f(1,2) * g(1)
Member Typedef Documentation
ctL
template<typename T, std::size_t NDIM> template<size_t LDIM> typedef CoeffTracker<T,LDIM> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::ctL
ctT
template<typename T, std::size_t NDIM> template<size_t LDIM> typedef CoeffTracker<T,NDIM> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::ctT
this_type
template<typename T, std::size_t NDIM> template<size_t LDIM> typedef multiply_op<LDIM> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::this_type
Constructor & Destructor Documentation
multiply_op() [1/2]
template<typename T, std::size_t NDIM> template<size_t LDIM> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::multiply_op () inline
multiply_op() [2/2]
template<typename T, std::size_t NDIM> template<size_t LDIM> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::multiply_op (implT * h, const ctT & f, const ctL & g, const int particle) inline
Member Function Documentation
activate()
template<typename T, std::size_t NDIM> template<size_t LDIM> Future<this_type> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate () const inline
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::f, f1, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::forward_ctor(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::g, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::h, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::particle, madness::World::taskq, madness::FunctionImpl< T, NDIM >::world, and madness::detail::wrap_mem_fn().
forward_ctor()
template<typename T, std::size_t NDIM> template<size_t LDIM> this_type madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::forward_ctor (implT * h1, const ctT & f1, const ctL & g1, const int particle) inline
References f1, and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::particle.
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate().
make_child()
template<typename T, std::size_t NDIM> template<size_t LDIM> this_type madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::make_child (const keyT & child) const inline
References madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::f, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::g, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::h, madness::CoeffTracker< T, NDIM >::make_child(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::particle.
operator()()
template<typename T, std::size_t NDIM> template<size_t LDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator() (const Key< NDIM > & key) const inline
apply this on a FunctionNode of f and g of Key key
Parameters
[in] key key for FunctionNode in f and g, (g: broken into particles)
Returns
<this node is a leaf, coefficients of this node>
References madness::Key< NDIM >::break_apart(), madness::CoeffTracker< T, NDIM >::coeff(), madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::GenTensor< T >::convert(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::f, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::g, madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionImpl< T, NDIM >::get_tensor_type(), madness::FunctionImpl< T, NDIM >::get_thresh(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::h, madness::CoeffTracker< T, NDIM >::key(), madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::multiply(), madness::GenTensor< T >::normalize(), madness::FunctionImpl< T, NDIM >::parent_to_child(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::particle, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen(), madness::GenTensor< T >::tensor_type(), madness::TT_2D, and madness::FunctionImpl< T, NDIM >::values2coeffs().
randomize()
template<typename T, std::size_t NDIM> template<size_t LDIM> static bool madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::randomize () inline static
screen()
template<typename T, std::size_t NDIM> template<size_t LDIM> bool madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen (const coeffT & fcoeff, const coeffT & gcoeff, const keyT & key) const inline
return true if this will be a leaf node
use generalization of tnorm for a GenTensor
References madness::_(), c, madness::GenTensor< T >::config(), madness::BaseTensor::dim(), madness::GenTensor< T >::full_tensor(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::g, madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_thresh(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::h, lo, madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::particle, madness::GenTensor< T >::rank(), madness::GenTensor< T >::tensor_type(), madness::FunctionImpl< T, NDIM >::tnorm(), madness::FunctionImpl< T, NDIM >::truncate_tol(), madness::TT_2D, madness::TT_FULL, and madness::vec().
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()().
serialize()
template<typename T, std::size_t NDIM> template<size_t LDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::f, madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::g, and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::h.
Member Data Documentation
f
template<typename T, std::size_t NDIM> template<size_t LDIM> ctT madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::f
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::serialize().
g
template<typename T, std::size_t NDIM> template<size_t LDIM> ctL madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::g
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::serialize().
h
template<typename T, std::size_t NDIM> template<size_t LDIM> implT* madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::h
the result function h(1,2) = f(1,2) * g(1)
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::serialize().
particle
template<typename T, std::size_t NDIM> template<size_t LDIM> int madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::particle
if g is g(1) or g(2)
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::forward_ctor(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen().
The documentation for this struct was generated from the following file:
funcimpl.h