MADNESS: madness::xc_lda_potential Struct Reference
madness::xc_lda_potential Struct Reference
Compute the spin-restricted LDA potential using unaryop (only for the initial guess)
#include <xcfunctional.h>
Public Member Functions
xc_lda_potential ()
void operator() (const Key< 3 > &key, Tensor< double > &t) const
Detailed Description
Compute the spin-restricted LDA potential using unaryop (only for the initial guess)
Constructor & Destructor Documentation
xc_lda_potential()
madness::xc_lda_potential::xc_lda_potential () inline
Member Function Documentation
operator()()
void madness::xc_lda_potential::operator() (const Key< 3 > & key, Tensor< double > & t) const inline
References madness::c_rks_vwn5__(), e(), madness::f, max, madness::Tensor< T >::ptr(), q(), madness::BaseTensor::size(), and madness::x_rks_s__().
The documentation for this struct was generated from the following file:
xcfunctional.h