MADNESS: tdse_example.cc File Reference
tdse_example.cc File Reference
Evolves the hydrogen atom in imaginary and also real time.
#include <madness/mra/lbdeux.h>
#include <madness/mra/mra.h>
#include <madness/mra/qmprop.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Classes
struct unaryexp< T, NDIM >
Typedefs
typedef FunctionFactory< double_complex, 3 > complex_factoryT
typedef Function< double_complex, 3 > complex_functionT
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 3 > > complex_functorT
typedef SeparatedConvolution< double_complex, 3 > complex_operatorT
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
Functions
void converge (World &world, functionT &potn, functionT &psi, double &eps)
Evolve the wave function in imaginary time to converge to ground state.
template<typename T >
double energy (World &world, const Function< T, 3 > &psi, const functionT &potn)
Given psi and V evaluate the energy.
static double guess (const coordT &r)
Initial guess wave function.
double laser (double t)
Strength of the laser field at time t ... 1 full cycle.
template<typename T , int NDIM>
double lbcost (const Key< NDIM > &key, const FunctionNode< T, NDIM > &node)
template<typename T , std::size_t NDIM>
void load_balance (World &world, const madness::Function< T, NDIM > &psi)
int main (int argc, char **argv)
void propagate (World &world, functionT &potn, functionT &psi0, double &eps)
Evolve the wave function in real time.
static double smoothed_potential (double r)
Regularized 1/r potential.
static double V (const coordT &r)
Smoothed 1/r nuclear potential.
double zdipole (const coordT &r)
z-dipole
Variables
static const double cut = 0.2
static const double F = 1.0
static const long k = 8
static const double L = 23.0
static const double omega = 1.0
static const double thresh = 1e-6
Detailed Description
Evolves the hydrogen atom in imaginary and also real time.
Typedef Documentation
complex_factoryT
typedef FunctionFactory<double_complex,3> complex_factoryT
complex_functionT
typedef Function<double_complex,3> complex_functionT
complex_functorT
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,3> > complex_functorT
complex_operatorT
typedef SeparatedConvolution<double_complex,3> complex_operatorT
coordT
typedef Vector<double,3> coordT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
Function Documentation
converge()
void converge (World & world, functionT & potn, functionT & psi, double & eps)
Evolve the wave function in imaginary time to converge to ground state.
References energy(), expV(), load_balance(), madness::detail::norm(), op(), madness::constants::pi, pow(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::truncate(), madness::Function< T, NDIM >::unaryop(), and V().
Referenced by main().
energy()
template<typename T > double energy (World & world, const Function< T, 3 > & psi, const functionT & potn)
Given psi and V evaluate the energy.
References std::abs(), axis, madness::inner(), madness::print(), psi(), and madness::World::rank().
Referenced by converge(), main(), and propagate().
guess()
static double guess (const coordT & r) static
Initial guess wave function.
References cut.
Referenced by main().
laser()
double laser (double t)
Strength of the laser field at time t ... 1 full cycle.
References omega, and madness::constants::pi.
Referenced by propagate().
lbcost()
template<typename T , int NDIM> double lbcost (const Key< NDIM > & key, const FunctionNode< T, NDIM > & node)
load_balance()
template<typename T , std::size_t NDIM> void load_balance (World & world, const madness::Function< T, NDIM > & psi)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::LoadBalanceDeux< NDIM >::load_balance(), madness::print(), psi(), madness::World::rank(), and madness::FunctionDefaults< NDIM >::redistribute().
Referenced by converge(), and propagate().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, converge(), energy(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, guess(), madness::initialize(), k, L, madness::print(), propagate(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, and V().
propagate()
void propagate (World & world, functionT & potn, functionT & psi0, double & eps)
Evolve the wave function in real time.
References madness::Function< T, NDIM >::add_scalar(), c, ctarget, cut, energy(), expV(), G, madness::inner(), k, laser(), load_balance(), madness::detail::norm(), madness::Function< T, NDIM >::norm2(), madness::constants::pi, madness::print(), psi(), psi0(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), tcrit, madness::Function< T, NDIM >::truncate(), tstep, madness::Function< T, NDIM >::unaryop(), and zdipole().
Referenced by main().
smoothed_potential()
static double smoothed_potential (double r) static
Regularized 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References e(), PI, and r2().
V()
static double V (const coordT & r) static
Smoothed 1/r nuclear potential.
References cut, and madness::smoothed_potential().
Referenced by converge(), and main().
zdipole()
double zdipole (const coordT & r)
z-dipole
Referenced by propagate().
Variable Documentation
cut
const double cut = 0.2 static
Referenced by guess(), propagate(), InputParameters::read(), InputParameters::serialize(), V(), and Vn().
F
const double F = 1.0 static
Referenced by allocator(), madness::TDHF::canonicalize(), iterate_xy(), madness::TDHF::make_cis_matrix(), madness::TDHF::make_perturbed_fock_matrix(), allocator::operator()(), F::operator*(), F::operator-(), InputParameters::read(), residual(), madness::OEP::solve_oep(), madness::TDHF::TDHF(), and test().
k
const long k = 8 static
Referenced by main(), and propagate().
L
const double L = 23.0 static
Referenced by main().
omega
const double omega = 1.0 static
Referenced by madness::TDHF::apply_G(), madness::SCF::calc_freq(), madness::Zcis::iterate(), madness::CC2::iterate_pair(), madness::PNO::iterate_pairs_internal(), madness::CC2::iterate_singles(), madness::TDHF::iterate_vectors(), iterate_xy(), laser(), main(), madness::SCF::polarizability(), InputParameters::read(), InputParameters::serialize(), madness::CC2::solve_cc2(), madness::PNO::solve_cispd(), madness::CC2::solve_mp2(), madness::PNO::t_solve(), and madness::PNO::update_pno().
thresh
const double thresh = 1e-6 static
Referenced by main().