MADNESS: tdse4.cc File Reference
tdse4.cc File Reference
Evolves the hydrogen molecular ion in 4D ... 3 electron + 1 nuclear degree of freedom.
#include <madness/mra/mra.h>
#include <madness/mra/funcimpl.h>
#include <madness/mra/qmprop.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
#include <madness/tensor/vmath.h>
#include <madness/mra/lbdeux.h>
Classes
struct InputParameters
struct lbcost< T, NDIM >
struct unaryexp< T, NDIM >
struct unaryexp< double_complex, NDIM >
Typedefs
typedef FunctionFactory< double_complex, 4 > complex_factoryT
typedef Function< double_complex, 4 > complex_functionT
typedef std::shared_ptr< FunctionFunctorInterface< double_complex, 4 > > complex_functorT
typedef Convolution1D< double_complex > complex_operatorT
typedef Vector< double, 4 > coordT
typedef FunctionFactory< double, 4 > factoryT
typedef Function< double, 4 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 4 > > functorT
typedef SeparatedConvolution< double, 4 > operatorT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 4 > > > pmapT
Functions
complex_functionT APPLY (const complex_operatorT *Ge, const complex_operatorT *Gn, const complex_functionT &psi)
double bond_length (const coordT &r)
void converge (World &world, functionT &potn, functionT &pote, functionT &pot, functionT &psi, double &eps)
double delsqfred (const coordT &r)
void doit (World &world)
template<typename T >
double energy (World &world, const Function< T, 4 > &psi, const functionT &pote, const functionT &potn, const functionT &potf)
double fred (const coordT &r)
static double guess (const coordT &r)
template<typename T >
void initial_loadbal (World &world, functionT &pote, functionT &potn, functionT &pot, Function< T, 4 > &psi)
double laser (double t)
void loadbal (World &world, functionT &pote, functionT &potn, functionT &pot, functionT &vt, complex_functionT &psi, complex_functionT &psi0, functionT &x, functionT &y, functionT &z, functionT &R)
int main (int argc, char **argv)
complex_functionT make_exp (double t, const functionT &v)
double myreal (double t)
double myreal (const double_complex &t)
std::ostream & operator<< (std::ostream &s, const InputParameters &p)
void print_stats (World &world, int step, double t, const functionT &pote, const functionT &potn, const functionT &potf, const functionT &x, const functionT &y, const functionT &z, const functionT &R, const complex_functionT &psi0, const complex_functionT &psi)
void print_stats_header (World &world)
void propagate (World &world, functionT &pote, functionT &potn, functionT &pot, int step0)
double real (double a)
static double smoothed_potential (double r)
void testbsh (World &world)
complex_functionT trotter (World &world, const complex_functionT &expV, const complex_operatorT *Ge, const complex_operatorT *Gn, const complex_functionT &psi0)
static double Ve (const coordT &r)
static double Vn (const coordT &r)
bool wave_function_exists (World &world, int step)
const char * wave_function_filename (int step)
const char * wave_function_large_plot_filename (int step)
complex_functionT wave_function_load (World &world, int step)
const char * wave_function_small_plot_filename (int step)
void wave_function_store (World &world, int step, const complex_functionT &psi)
double xdipole (const coordT &r)
double ydipole (const coordT &r)
double zdipole (const coordT &r)
Variables
InputParameters param
static const double R0 = 2.04
static const double reduced_mass = 0.5*constants::proton_electron_mass_ratio
static const double s0 = sqrtmu*R0
static const double sqrtmu = sqrt(reduced_mass)
static const double Z =1.0
static double zero_field_time
Detailed Description
Evolves the hydrogen molecular ion in 4D ... 3 electron + 1 nuclear degree of freedom.
Typedef Documentation
complex_factoryT
typedef FunctionFactory<double_complex,4> complex_factoryT
complex_functionT
typedef Function<double_complex,4> complex_functionT
complex_functorT
typedef std::shared_ptr< FunctionFunctorInterface<double_complex,4> > complex_functorT
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
coordT
typedef Vector<double,4> coordT
factoryT
typedef FunctionFactory<double,4> factoryT
functionT
typedef Function<double,4> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,4> > functorT
operatorT
typedef SeparatedConvolution<double,4> operatorT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<4> > > pmapT
Function Documentation
APPLY()
complex_functionT APPLY (const complex_operatorT * Ge, const complex_operatorT * Gn, const complex_functionT & psi)
References madness::apply_1d_realspace_push(), madness::Function< T, NDIM >::broaden(), psi(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::sum_down().
bond_length()
double bond_length (const coordT & r)
References R0, and sqrtmu.
Referenced by propagate().
converge()
void converge (World & world, functionT & potn, functionT & pote, functionT & pot, functionT & psi, double & eps)
References madness::apply(), InputParameters::cut, d(), e(), energy(), madness::inner(), max, madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), param, madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), InputParameters::thresh, madness::Function< T, NDIM >::truncate(), and madness::wall_time().
Referenced by doit().
delsqfred()
double delsqfred (const coordT & r)
References a.
Referenced by testbsh().
doit()
void doit (World & world)
References madness::WorldGopInterface::broadcast(), madness::WorldGopInterface::broadcast_serializable(), converge(), energy(), madness::error(), madness::WorldGopInterface::fence(), madness::World::gop, guess(), initial_loadbal(), InputParameters::k, InputParameters::L, param, madness::print(), propagate(), psi(), madness::World::rank(), InputParameters::read(), s0, InputParameters::safety, madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), InputParameters::thresh, madness::Function< T, NDIM >::truncate(), Ve(), Vn(), madness::wall_time(), wave_function_exists(), and wave_function_store().
Referenced by main().
energy()
template<typename T > double energy (World & world, const Function< T, 4 > & psi, const functionT & pote, const functionT & potn, const functionT & potf)
References madness::Function< T, NDIM >::clear(), madness::Function< T, NDIM >::compress(), madness::WorldGopInterface::fence(), madness::World::gop, madness::inner(), myreal(), psi(), madness::World::rank(), and madness::real().
Referenced by converge(), doit(), and print_stats().
fred()
double fred (const coordT & r)
References a.
Referenced by madness::WorldProfile::clear(), main(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::register_callback(), madness::WorldProfile::register_id(), madness::SCF::restart_aos(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::set(), madness::Future< bool >::set(), madness::FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) >::set_handler(), test6a(), Test7(), testbsh(), and madness::WorldAmInterface::WorldAmInterface().
guess()
static double guess (const coordT & r) static
References a, alpha, beta, R, R0, R2, sqrtmu, and Z.
Referenced by doit().
initial_loadbal()
template<typename T > void initial_loadbal (World & world, functionT & pote, functionT & potn, functionT & pot, Function< T, 4 > & psi)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::print(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), and madness::World::size().
Referenced by doit(), and propagate().
laser()
double laser (double t)
References InputParameters::F, InputParameters::ncycle, InputParameters::omega, param, and madness::constants::pi.
Referenced by print_stats(), and propagate().
loadbal()
void loadbal (World & world, functionT & pote, functionT & potn, functionT & pot, functionT & vt, complex_functionT & psi, complex_functionT & psi0, functionT & x, functionT & y, functionT & z, functionT & R)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::print(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), and madness::World::size().
Referenced by propagate().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, doit(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::print_stats(), and madness::startup().
make_exp()
complex_functionT make_exp (double t, const functionT & v)
References expV(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::unaryop().
myreal() [1/2]
double myreal (double t)
Referenced by energy().
myreal() [2/2]
double myreal (const double_complex & t)
References madness::real().
operator<<()
std::ostream& operator<< (std::ostream & s, const InputParameters & p)
References p().
print_stats()
void print_stats (World & world, int step, double t, const functionT & pote, const functionT & potn, const functionT & potf, const functionT & x, const functionT & y, const functionT & z, const functionT & R, const complex_functionT & psi0, const complex_functionT & psi)
References std::abs(), energy(), madness::inner(), laser(), madness::detail::norm(), psi(), psi0(), R, madness::World::rank(), madness::real(), and madness::wall_time().
print_stats_header()
void print_stats_header (World & world)
References madness::World::rank().
Referenced by propagate().
propagate()
void propagate (World & world, functionT & pote, functionT & potn, functionT & pot, int step0)
References bond_length(), madness::WorldGopInterface::broadcast(), c, ctarget, InputParameters::cut, expV(), madness::WorldGopInterface::fence(), madness::World::gop, initial_loadbal(), InputParameters::k, InputParameters::L, laser(), loadbal(), madness::make_exp(), InputParameters::ndump, InputParameters::nloadbal, InputParameters::nprint, param, madness::constants::pi, madness::print(), madness::print_stats(), print_stats_header(), psi(), psi0(), madness::qm_1d_free_particle_propagator(), R, madness::World::rank(), s0, InputParameters::target_time, tcrit, trotter(), InputParameters::tScale, madness::wall_time(), wave_function_load(), wave_function_store(), xdipole(), ydipole(), zdipole(), and zero_field_time.
Referenced by doit().
real()
double real (double a)
References a.
smoothed_potential()
static double smoothed_potential (double r) static
References e(), and r2().
testbsh()
void testbsh (World & world)
References madness::apply(), delsqfred(), e(), fred(), madness::FunctionDefaults< NDIM >::get_thresh(), mu, madness::norm2(), ok(), op(), madness::print(), test(), and madness::Function< T, NDIM >::truncate().
trotter()
complex_functionT trotter (World & world, const complex_functionT & expV, const complex_operatorT * Ge, const complex_operatorT * Gn, const complex_functionT & psi0)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::APPLY(), madness::copy(), expV(), madness::FunctionDefaults< NDIM >::get_pmap(), madness::LoadBalanceDeux< NDIM >::load_balance(), param, madness::print(), psi0(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::Function< T, NDIM >::size(), InputParameters::thresh, and madness::Function< T, NDIM >::truncate().
Referenced by propagate().
Ve()
static double Ve (const coordT & r) static
References InputParameters::cut, param, R, R0, madness::smoothed_potential(), sqrtmu, and Z.
Referenced by doit(), and main().
Vn()
static double Vn (const coordT & r) static
References cut, R, R0, madness::smoothed_potential(), and sqrtmu.
Referenced by doit().
wave_function_exists()
bool wave_function_exists (World & world, int step)
References madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), and wave_function_filename().
Referenced by doit().
wave_function_filename()
const char* wave_function_filename (int step)
References param, and InputParameters::prefix.
Referenced by wave_function_exists(), wave_function_load(), and wave_function_store().
wave_function_large_plot_filename()
const char* wave_function_large_plot_filename (int step)
References param, and InputParameters::prefix.
wave_function_load()
complex_functionT wave_function_load (World & world, int step)
References psi(), and wave_function_filename().
Referenced by propagate().
wave_function_small_plot_filename()
const char* wave_function_small_plot_filename (int step)
References param, and InputParameters::prefix.
wave_function_store()
void wave_function_store (World & world, int step, const complex_functionT & psi)
References InputParameters::nio, param, psi(), and wave_function_filename().
Referenced by doit(), and propagate().
xdipole()
double xdipole (const coordT & r)
Referenced by propagate().
ydipole()
double ydipole (const coordT & r)
Referenced by propagate().
zdipole()
double zdipole (const coordT & r)
Referenced by propagate().
Variable Documentation
param
InputParameters param
Referenced by converge(), doit(), laser(), propagate(), trotter(), Ve(), wave_function_filename(), wave_function_large_plot_filename(), wave_function_small_plot_filename(), and wave_function_store().
R0
const double R0 = 2.04 static
Referenced by bond_length(), guess(), InputParameters::read(), Ve(), and Vn().
reduced_mass
const double reduced_mass = 0.5*constants::proton_electron_mass_ratio static
Referenced by InputParameters::read().
s0
const double s0 = sqrtmu*R0 static
Referenced by doit(), madness::inner_result(), madness::Convolution1D< Q >::mod_nonstandard(), madness::Convolution1D< Q >::nonstandard(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), madness::ortho5(), madness::FunctionImpl< Q, NDIM >::project_refine_op(), propagate(), and test().
sqrtmu
const double sqrtmu = sqrt(reduced_mass) static
Referenced by bond_length(), guess(), InputParameters::read(), Ve(), and Vn().
Z
const double Z =1.0 static
Referenced by guess(), guess1s(), guess2s(), main(), madness::NuclearCorrelationFactor::U1_functor::operator()(), madness::NuclearCorrelationFactor::U1_atomic_functor::operator()(), madness::NuclearCorrelationFactor::U1_dot_U1_functor::operator()(), madness::NuclearCorrelationFactor::RX_functor::operator()(), madness::NuclearCorrelationFactor::U1X_functor::operator()(), madness::NuclearCorrelationFactor::U2X_functor::operator()(), InputParameters::read(), madness::GaussSlater::S(), madness::GradientalGaussSlater::S(), madness::LinearSlater::S(), madness::Slater::S(), madness::poly4erfc::S(), madness::Polynomial< N >::S(), InputParameters::serialize(), smoothing_parameter(), madness::smoothing_parameter(), madness::GaussSlater::Sp(), madness::GradientalGaussSlater::Sp(), madness::LinearSlater::Sp(), madness::Slater::Sp(), madness::Polynomial< N >::Sp(), madness::GaussSlater::Spp_div_S(), madness::GradientalGaussSlater::Spp_div_S(), madness::LinearSlater::Spp_div_S(), madness::Slater::Spp_div_S(), madness::poly4erfc::Spp_div_S(), madness::Polynomial< N >::Spp_div_S(), madness::PseudoNuclearCorrelationFactor::Spp_div_S(), madness::GaussSlater::Sr_div_S(), madness::GradientalGaussSlater::Sr_div_S(), madness::LinearSlater::Sr_div_S(), madness::Slater::Sr_div_S(), madness::poly4erfc::Sr_div_S(), madness::Polynomial< N >::Sr_div_S(), madness::GaussSlater::Srr_div_S(), madness::GradientalGaussSlater::Srr_div_S(), madness::LinearSlater::Srr_div_S(), madness::Slater::Srr_div_S(), madness::Polynomial< N >::Srr_div_S(), madness::GaussSlater::Srrr_div_S(), madness::GradientalGaussSlater::Srrr_div_S(), madness::LinearSlater::Srrr_div_S(), madness::Slater::Srrr_div_S(), madness::Polynomial< N >::Srrr_div_S(), madness::GaussSlater::U2X_spherical(), madness::GradientalGaussSlater::U2X_spherical(), madness::Slater::U2X_spherical(), madness::Polynomial< N >::U2X_spherical(), madness::PseudoNuclearCorrelationFactor::U2X_spherical(), and Ve().
zero_field_time
double zero_field_time static
Referenced by propagate().