MADNESS: testpg.cc File Reference
testpg.cc File Reference
#include <madness/world/MADworld.h>
#include <moldft/pointgroup.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), and PointGroup::test().