MADNESS: test_sig.cc File Reference
test_sig.cc File Reference
#include <iostream>
#include <signal.h>
#include <cstdlib>
#include <cstdio>
#include <execinfo.h>
Functions
void a ()
void b ()
void c ()
void d ()
void e ()
void madness_signal_action (int signum, siginfo_t *info, void *context)
int main ()
void print_backtrace (int fd)
Function Documentation
a()
void a ()
References b().
Referenced by main().
b()
void b ()
References c().
Referenced by a().
c()
void c ()
References d().
Referenced by b().
d()
void d ()
References e().
Referenced by madness::adq1(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::allocate(), madness::apply(), madness::SeparatedConvolution< T, NDIM >::apply_transformation(), madness::SeparatedConvolution< T, NDIM >::apply_transformation2(), area_two_spheres(), madness::FunctionImpl< Q, NDIM >::broaden(), c(), madness::SeparatedConvolution< T, NDIM >::check_cubic(), madness::Displacements< NDIM >::cmp_keys_periodicsum(), madness::FunctionImpl< Q, NDIM >::coeffs_for_jun(), SurfaceMoleculeInteraction::colloid_coords(), madness::FunctionImpl< Q, NDIM >::compress_op(), madness::concatenate_rows(), converge(), madness::LowRankTensor< T >::convert(), madness::cross(), madness::cycle_count(), madness::TensorTrain< T >::decompose(), dfunc(), madness::TensorTrain< T >::dims(), madness::Key< OPDIM >::distsq(), madness::LLRVDomainMask::dmask(), madness::GaussianDomainMask::dmask(), madness::FunctionImpl< Q, NDIM >::do_apply(), madness::FunctionImpl< Q, NDIM >::do_apply_directed_screening(), madness::Derivative< T, NDIM >::do_diff2b(), madness::Derivative< T, NDIM >::do_diff2i(), madness::FunctionImpl< Q, NDIM >::do_print_grid(), Node::do_sum_spawn(), doit(), madness::LLRVDomainMask::dsurface(), madness::GaussianDomainMask::dsurface(), madness::Function< double, 6 >::eval(), madness::Function< double, 6 >::eval_cube(), madness::SDFParaboloid::eval_cubic(), madness::Function< double, 6 >::eval_local_only(), madness::Function< double, 6 >::evaldepthpt(), madness::Function< double, 6 >::evalR(), expV(), madness::FunctionImpl< Q, NDIM >::fcube_for_mul(), madness::SDFParaboloid::find_root(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::flat(), madness::BaseTensor::flat_inplace(), func(), madness::TensorTrain< T >::fusedim(), madness::TensorTrain< T >::gaxpy(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_recursive(), madness::general_transform(), madness::SDFParaboloid::get_roots(), madness::get_size(), madness::SeparatedConvolution< T, NDIM >::getmuop(), madness::SeparatedConvolution< T, NDIM >::getmuop_modified(), madness::SeparatedConvolution< T, NDIM >::getop(), madness::SeparatedConvolution< T, NDIM >::getop_ns(), madness::GradBSHOperator(), madness::GradCoulombOperator(), madness::gradient_operator(), madness::GradSlaterOperator(), madness::LBNodeDeux< NDIM >::index(), madness::IndexIterator::IndexIterator(), madness::TwoElectronInterface< double, 6 >::initialize(), madness::inner(), madness::FunctionImpl< Q, NDIM >::inner_adaptive_recursive(), madness::FunctionImpl< Q, NDIM >::inner_ext_recursive(), is_equal(), madness::BoundaryConditions< 6 >::is_periodic(), TTT::kate(), madness::SystolicPMOrbitalLocalize::localize_PM_ij(), main(), madness::Displacements< NDIM >::make_disp(), madness::Displacements< NDIM >::make_disp_periodicsum(), smooth< T, NDIM >::make_sigma(), madness::SeparatedConvolution< T, NDIM >::make_tt_representation(), madness::LLRVDomainMask::mask(), madness::GaussianDomainMask::mask(), madness::matrix_inner(), madness::SeparatedConvolution< T, NDIM >::munorm2_modified(), madness::SeparatedConvolution< T, NDIM >::munorm2_ns(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast2(), madness::SeparatedConvolution< T, NDIM >::norm(), madness::Vector< int, 3 >::normf(), madness::FunctionImpl< Q, NDIM >::NS_fcube_for_mul(), madness::dens_inv1::operator()(), madness::dens_inv::operator()(), abs_square_op< Q, NDIM >::operator()(), OpFExact::operator()(), DSphere::operator()(), SurfaceMoleculeInteraction::Bop::operator()(), madness::BoundaryConditions< 6 >::operator()(), madness::abs_square_op< Q, NDIM >::operator()(), slater_kernel::operator()(), Uop::operator()(), madness::int_factor_functor< NDIM >::operator()(), madness::lr_pot_functor< NDIM >::operator()(), madness::op_leaf_op< T, NDIM, opT >::operator()(), madness::hartree_convolute_leaf_op< T, NDIM, LDIM, opT >::operator()(), Node::do_random_insert::operator()(), Walker1::operator()(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::operator()(), madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::operator()(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::operator()(), Fred::operator*(), madness::TensorIterator< T, Q, R >::operator++(), madness::IndexIterator::operator++(), madness::HighDimIndexIterator::operator++(), madness::LowDimIndexIterator::operator++(), madness::NonstandardIndexIterator::operator++(), madness::operator<<(), madness::DistributedMatrixDistribution::operator==(), madness::IndexIterator::operator[](), OpFExact::OpFExact(), madness::outer(), madness::WorldProfileObj::pause(), madness::FunctionImpl< Q, NDIM >::plot_cube_kernel(), madness::plotdx(), madness::plotpovray(), madness::XCfunctional::polyn(), madness::Leaf_op< T, NDIM, SeparatedConvolution< double, NDIM >, Specialbox_op< T, NDIM > >::post_screening(), madness::print_seq(), madness::FunctionImpl< Q, NDIM >::print_size(), madness::FunctionImpl< Q, NDIM >::project_refine_op(), Node::random_insert(), madness::TensorTrain< T >::reconstruct(), madness::SRConf< T >::reconstruct(), madness::FunctionImpl< Q, NDIM >::reconstruct_op(), Node::recursive_print(), madness::WorldProfile::recv_stats(), madness::FunctionImpl< Q, NDIM >::refine_op(), madness::FunctionImpl< Q, NDIM >::refine_to_common_level(), madness::IndexIterator::reset(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::reshape(), madness::BaseTensor::reshape_inplace(), madness::rot(), madness::SDFParaboloid::sdf(), madness::SeparatedConvolution< T, NDIM >::SeparatedConvolution(), madness::TensorTrain< T >::serialize(), madness::BaseTensor::set_dims_and_size(), madness::FunctionImpl< Q, NDIM >::sum_down_spawn(), madness::LLRVDomainMask::surface(), madness::GaussianDomainMask::surface(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::Tensor(), madness::TensorTrain< T >::TensorTrain(), Test1(), test1(), test11(), test12(), test13(), Test5(), test7(), test_in(), test_opdir(), test_out(), testgradG(), testNavierStokes(), madness::TensorTrain< T >::trace(), madness::transform(), madness::FunctionImpl< Q, NDIM >::trickle_down_op(), madness::TensorTrain< T >::truncate(), madness::FunctionImpl< Q, NDIM >::truncate_reconstructed_op(), madness::TwoElectronInterface< double, 6 >::TwoElectronInterface(), madness::TensorTrain< T >::verify(), volume_two_spheres(), walker1(), walker2(), and madness::WorldProfileObj::~WorldProfileObj().
e()
void e ()
References f.
Referenced by MolecularEntity::add_atom(), madness::Molecule::add_atom(), madness::adq1(), KPeriodicBSHOperator::apply(), madness::Solver< T, NDIM >::apply_hf_exchange(), apply_periodic_bsh(), madness::GTHPseudopotential< Q >::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), applyexpLt(), madness::SCFProtocol::approx(), madness::BandlimitedPropagator::BandlimitedPropagator(), madness::GFit< T, NDIM >::bsh_fit(), madness::BSHOperator(), madness::HartreeFock< T, NDIM >::calculate_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_exchange_energy(), madness::DFT< T, NDIM >::calculate_tot_coulomb_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::CCParameters::CCParameters(), ParserHandler< T, NDIM >::changeExpr(), madness::SeparatedConvolution< T, NDIM >::check_cubic(), madness::check_linear_dependence(), check_multiplication_table_c2v(), check_operator_multiplications_2d(), check_operator_multiplications_3d(), madness::PNO::check_orthonormality(), MySteepestDescent::check_positive(), madness::SRConf< T >::check_right_orthonormality(), compare_calc_and_mos(), madness::Znemo::compute_energy(), compute_energy(), madness::Nemo::compute_IR_intensities(), madness::F12Potentials::compute_projected_f12_energies(), compute_reduced_mass(), madness::MolecularOptimizer::compute_reduced_mass(), madness::Zcis::compute_residuals(), converge(), converge2s(), madness::ConvolutionData1D< Q >::ConvolutionData1D(), madness::Solver< T, NDIM >::csqrt(), d(), madness::d2smoothed_potential(), d_smoothed_potential(), delta(), madness::DFTCoulombOp< T, NDIM >::DFTCoulombOp(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), diag_and_transform(), CosineSphere::DirichletCond(), Y20Sphere::DirichletCond(), EwaldNuclearPotentialFunctor::do_G_sum_v2(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), MiniDFT::doit(), doit(), dsmoothed_potential(), madness::NuclearCorrelationFactor::dsmoothed_unitvec(), madness::ElectronicStructureParams::ElectronicStructureParams(), GygiPot::ESP(), madness::CoreOrbital::eval(), ContractedGaussianShell::eval(), madness::ContractedGaussianShell::eval(), madness::Function< double, 6 >::eval(), madness::Function< double, 6 >::eval_cube(), madness::CoreOrbital::eval_derivative(), madness::Function< double, 6 >::eval_local_only(), madness::Function< double, 6 >::evaldepthpt(), madness::Function< double, 6 >::evalR(), EwaldNuclearPotentialFunctor::EwaldNuclearPotentialFunctor(), find_fuzzy(), ExcitingApp::findkpt(), madness::Solver< T, NDIM >::fix_occupations(), fixphases(), madness::gauss_legendre_numeric(), gen_ce(), ExcitingApp::generate_gvectors(), ExcitingApp::generate_lvectors(), madness::GenericConvolution1D< Q, opT >::GenericConvolution1D(), madness::CCConvolutionOperator::get_kernel(), madness::GMRES(), madness::SDFCircle::grad_sdf(), MolecularMaskBase::gradient(), guess(), madness::BasisFunctions::guess_virtual_gaussian_shell(), madness::BasisFunctions::guess_virtuals_from_file(), madness::BasisFunctions::guess_virtuals_internal(), h_orbital(), madness::Znemo::hcore_guess(), he_munge(), he_plus_orbital(), madness::QuasiNewton::hessian_update_bfgs(), QuasiNewton::hessian_update_bfgs(), madness::QuasiNewton::hessian_update_sr1(), QuasiNewton::hessian_update_sr1(), madness::SCFProtocol::infer_thresholds(), madness::init_tensor_lapack(), madness::SCF::initial_guess(), initial_guess(), madness::Solver< T, NDIM >::initial_guess(), madness::XCfunctional::initialize(), iterate(), iterate_excite(), iterate_ground(), iterate_xy(), jacobi(), KAIN(), Calculation::load_mos(), madness::Nemo::localize(), madness::SCF::localize_boys(), madness::SCF::localize_new(), madness::SystolicPMOrbitalLocalize::localize_PM_ij(), madness::ThreadBase::main(), main(), madness::EigSolver< T, NDIM >::make_bsh_operators(), MiniDFT::make_bsh_operators(), make_bsh_operators(), madness::TDHF::make_cis_matrix(), MiniDFT::make_coulomb_potential(), make_coulomb_potential(), madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), make_pw_matrix(), madness::SeparatedConvolution< T, NDIM >::make_tt_representation(), madness::SCF::matrix_exponential(), matrix_exponential(), madness::Solver< T, NDIM >::matrix_exponential(), madness::AtomicBasisSet::modify_dmat_psp(), munge(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast(), madness::SeparatedConvolution< T, NDIM >::muopxv_fast2(), myf(), madness::myusleep(), madness::QuasiNewton::new_search_direction(), QuasiNewton::new_search_direction(), madness::MolecularOptimizer::new_search_direction2(), madness::SRConf< T >::normalize(), nuclear_potential(), NuclearChargeDensityOp< T, NDIM >::NuclearChargeDensityOp(), madness::HartreeFockExchangeOp< T, NDIM >::op_o(), madness::HartreeFockCoulombOp< T, NDIM >::op_r(), madness::xc_lda_potential::operator()(), ParserHandler< T, NDIM >::operator()(), OpFExact::operator()(), HeElectronicChargeDensityIGuess< T, NDIM >::operator()(), BoysLocalization::operator()(), H2Potential::operator()(), AtomicBasisFunctor< Q >::operator()(), madness::BasisFunctions::CartesianGaussian::operator()(), madness::XCOperator::logme::logme1::operator()(), GaussianPotential::operator()(), madness::operator<<(), opt(), optimize_coeffs(), madness::MolecularOptimizer::optimize_quasi_newton(), madness::Molecule::orient(), orth(), madness::ortho3(), madness::ortho5(), madness::Zcis::orthonormalize(), ParserHandler< T, NDIM >::ParserHandler(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), madness::FunctionImpl< Q, NDIM >::phi_for_mul(), madness::XCfunctional::plot(), plot_symmetry_operators(), madness::XCfunctional::polyn(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), Calculation::project_potential_basis(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), madness::SCF::propagate(), psi(), psi_func_be1(), psi_func_he(), q(), random_gaussian(), madness::Molecule::read(), madness::read_atom(), madness::F12Potentials::read_cabs_from_file(), MolecularEntity::read_file(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), madness::QCCalculationParametersBase::read_internal(), madness::read_orbital(), madness::read_potential(), read_test_data(), madness::read_twoscale(), ExcitingApp::response(), rks_c_vwn5__(), rks_x_lda__(), madness::GenericConvolution1D< Q, opT >::rnlp(), madness::GaussianConvolution1D< Q >::rnlp(), run_all_calculations(), madness::detail::adqtest::runtest(), madness::CCParameters::sanity_check(), madness::ProjRLMFunctor::screened(), madness::FunctionDefaults< NDIM >::set_defaults(), madness::CalculationParameters::set_derived_values(), madness::SCF::set_protocol(), Calculation::set_protocol(), madness::GFit< T, NDIM >::slater_fit(), smoothed_potential(), madness::NuclearCorrelationFactor::smoothed_unitvec(), smoothing_parameter(), madness::smoothing_parameter(), SVPESolver::solve(), madness::EigSolver< T, NDIM >::solve(), madness::Nemo::solve(), madness::SCF::solve(), madness::OEP::solve_oep(), madness::GaussSlater::Spp_div_S(), madness::GradientalGaussSlater::Spp_div_S(), madness::LinearSlater::Spp_div_S(), madness::Slater::Spp_div_S(), madness::Polynomial< N >::Spp_div_S(), madness::GradientalGaussSlater::Sr_div_S(), madness::GradientalGaussSlater::Srr_div_S(), madness::GradientalGaussSlater::Srrr_div_S(), madness::syev(), madness::sygv(), madness::sygvp(), madness::TDHF::TDHF(), madness::BandlimitedPropagator::test(), test(), test0GaussLobatto(), Test1(), test1(), Test5(), Test6(), Test7(), smooth< T, NDIM >::test_1d(), test_adaptive_tree(), test_apply_push_1d(), test_basic(), test_bsh(), test_chin_chen(), test_compress(), test_correlation_factor::test_correlation_factor(), test_coulomb(), test_dnuclear(), test_exchange(), madness::Diamagnetic_potential_factor::test_factor(), madness::Molecule::test_for_op(), test_G_R_vectors(), test_gaussian_num_coeffs(), madness::test_gelss(), test_gence(), test_gence2(), test_he(), test_he_potential(), test_hf_be(), test_hf_h2(), test_hf_he(), test_hydro(), test_in(), test_io(), test_lda(), test_math(), test_modified(), test_nemo(), test_nuclear(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_opdir(), test_orthogonalization(), test_out(), test_per(), test_periodic(), test_periodic1(), test_periodic2(), test_periodic_bsh(), madness::Solver< T, NDIM >::test_periodicity(), test_plot(), test_proj(), test_projector(), test_qm(), test_recursive_application(), madness::test_rnlp(), madness::test_syev(), madness::test_sygv(), madness::test_tensor_lapack(), test_trotter(), madness::test_two_scale_coefficients(), test_unaryop(), test_wannier(), test_XCOperator(), testbsh(), testgradG(), testNavierStokes(), testPeriodicCoulomb3d(), madness::time_transform(), madness::GFit< T, NDIM >::truncate_periodic_expansion(), u(), madness::GaussSlater::U2X_spherical(), madness::GradientalGaussSlater::U2X_spherical(), madness::Slater::U2X_spherical(), madness::Polynomial< N >::U2X_spherical(), update(), MiniDFT::update(), madness::PNO::update_pno(), madness::SCF::update_response_subspace(), Subspace::update_subspace(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), madness::SCF::update_subspace(), V(), V_func_be(), V_func_h2(), V_func_he(), GaussianGuess< T, NDIM >::val(), CoreFittingTarget::value(), Fred::value_and_gradient(), madness::wall_time(), walltm_(), madness::XCfunctional::XCfunctional(), and YetAnotherWrapperClass::YetAnotherWrapperClass().
madness_signal_action()
void madness_signal_action (int signum, siginfo_t * info, void * context)
References print_backtrace().
Referenced by main().
main()
int main ()
References a(), and madness_signal_action().
print_backtrace()
void print_backtrace (int fd)
Referenced by madness_signal_action().