MADNESS: test_future3.cc File Reference
test_future3.cc File Reference
#include <madness/world/MADworld.h>
#include <madness/world/world_object.h>
Classes
class Foo
Macros
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Functions
int main (int argc, char **argv)
Macro Definition Documentation
WORLD_INSTANTIATE_STATIC_TEMPLATES
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Function Documentation
main()
int main (int argc, char ** argv)
References a, b, SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), Foo::get(), madness::Future< T >::get(), madness::World::gop, madness::initialize(), MADNESS_CHECK, p(), madness::print(), madness::World::rank(), and madness::World::size().