MADNESS: test_ar.cc File Reference
test_ar.cc File Reference
#include <iostream>
#include <cmath>
#include <madness/world/text_fstream_archive.h>
#include <madness/world/binary_fstream_archive.h>
#include <madness/world/vector_archive.h>
#include <madness/world/buffer_archive.h>
#include <madness/world/array_addons.h>
Classes
class A
struct madness::archive::ArchiveLoadImpl< Archive, C >
struct madness::archive::ArchiveLoadImpl< Archive, linked_list >
struct madness::archive::ArchiveSerializeImpl< Archive, B >
struct madness::archive::ArchiveStoreImpl< Archive, C >
struct madness::archive::ArchiveStoreImpl< Archive, linked_list >
class B
class C
struct D
struct F
class linked_list
Namespaces
madness
File holds all helper structures necessary for the CC_Operator and CC2 class.
madness::archive
Namespace for I/O tools.
Macros
#define ARCHIVE_REGISTER_TYPE_INSTANTIATE_HERE
#define TEST(cond)
Typedefs
typedef std::complex< double > double_complex
typedef std::map< short, std::complex< double > > madness::archive::map_short_complex_double
typedef std::pair< int, double > madness::archive::pair_int_double
typedef std::pair< short, std::complex< double > > madness::archive::pair_short_complex_double
typedef std::tuple< int, double, std::complex< float > > tuple_int_double_complexfloat
Functions
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (A, 128)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (B, 129)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (C, 130)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (linked_list, 131)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (pair_int_double, 132)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (map_short_complex_double, 133)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (pair_short_complex_double, 134)
int main ()
std::ostream & operator<< (std::ostream &os, const F &data)
std::istream & operator>> (std::istream &os, F &data)
template<typename Archive , typename POD , typename Disabler = std::enable_if_t<std::is_same<std::decay_t<Archive>,TextFstreamInputArchive>::value>>
void pod_deserialize_dispatch (Archive &&ar, POD &&pod)
template<typename Archive , typename POD >
void pod_deserialize_dispatch (Archive &&ar, POD &&pod, std::enable_if_t<!std::is_same< std::decay_t< Archive >, TextFstreamInputArchive >::value > *=nullptr)
template<typename Archive , typename POD , typename Disabler = std::enable_if_t<std::is_same<std::decay_t<Archive>,TextFstreamOutputArchive>::value>>
void pod_serialize_dispatch (Archive &&ar, const POD &pod)
template<typename Archive , typename POD >
void pod_serialize_dispatch (Archive &&ar, const POD &pod, std::enable_if_t<!std::is_same< std::decay_t< Archive >, TextFstreamOutputArchive >::value > *=nullptr)
template<class InputArchive >
void test_in (const InputArchive &iar)
template<class OutputArchive >
void test_out (const OutputArchive &oar)
Macro Definition Documentation
ARCHIVE_REGISTER_TYPE_INSTANTIATE_HERE
#define ARCHIVE_REGISTER_TYPE_INSTANTIATE_HERE
TEST
#define TEST (cond)
Value:
status &= cond;  \
                   if (!(cond)) std::cout << #cond << " failed" << std::endl
Referenced by test_in().
Typedef Documentation
double_complex
typedef std::complex<double> double_complex
tuple_int_double_complexfloat
typedef std::tuple<int,double,std::complex<float> > tuple_int_double_complexfloat
Function Documentation
main()
int main ()
References madness::archive::archive_initialize_type_names(), ARCHIVE_REGISTER_TYPE_AND_PTR_NAMES, madness::archive::VectorOutputArchive::close(), madness::archive::BinaryFstreamOutputArchive::close(), madness::archive::BufferOutputArchive::close(), madness::archive::TextFstreamOutputArchive::close(), madness::archive::BinaryFstreamInputArchive::close(), madness::archive::VectorInputArchive::close(), madness::archive::BufferInputArchive::close(), madness::archive::TextFstreamInputArchive::close(), f, madness::archive::BufferOutputArchive::size(), test_in(), and test_out().
operator<<()
std::ostream& operator<< (std::ostream & os, const F & data)
References F::i, and F::l.
operator>>()
std::istream& operator>> (std::istream & os, F & data)
References F::i, and F::l.
pod_deserialize_dispatch() [1/2]
template<typename Archive , typename POD , typename Disabler = std::enable_if_t<std::is_same<std::decay_t<Archive>,TextFstreamInputArchive>::value>> void pod_deserialize_dispatch (Archive && ar, POD && pod)
Referenced by test_in().
pod_deserialize_dispatch() [2/2]
template<typename Archive , typename POD > void pod_deserialize_dispatch (Archive && ar, POD && pod, std::enable_if_t<!std::is_same< std::decay_t< Archive >, TextFstreamInputArchive >::value > * = nullptr)
pod_serialize_dispatch() [1/2]
template<typename Archive , typename POD , typename Disabler = std::enable_if_t<std::is_same<std::decay_t<Archive>,TextFstreamOutputArchive>::value>> void pod_serialize_dispatch (Archive && ar, const POD & pod)
Referenced by test_out().
pod_serialize_dispatch() [2/2]
template<typename Archive , typename POD > void pod_serialize_dispatch (Archive && ar, const POD & pod, std::enable_if_t<!std::is_same< std::decay_t< Archive >, TextFstreamOutputArchive >::value > * = nullptr)
test_in()
template<class InputArchive > void test_in (const InputArchive & iar)
References A::a, a, B::b, b, c, C::c, d(), e(), f, D::i, F::i, k, D::l, F::l, m, MAD_ARCHIVE_DEBUG, p(), pi, pod_deserialize_dispatch(), linked_list::print(), q(), status, TEST, and madness::archive::wrap().
Referenced by main().
test_out()
template<class OutputArchive > void test_out (const OutputArchive & oar)
References A::a, a, linked_list::append(), B::b, b, c, C::c, d(), e(), f, D::i, F::i, k, D::l, F::l, m, MAD_ARCHIVE_DEBUG, p(), pi, pod_serialize_dispatch(), linked_list::print(), q(), and madness::archive::wrap().
Referenced by main().