MADNESS: testbsh.cc File Reference
testbsh.cc File Reference
test the bsh operator
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Classes
class Gaussian< T, NDIM >
struct Qfunc
the result of the convolution
Functions
int main (int argc, char **argv)
double q (double r)
template<typename T >
int test_bsh (World &world)
Variables
double aa
bool smalltest = false
Detailed Description
test the bsh operator
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), smalltest, and madness::startup().
q()
double q (double r)
References aa, e(), e1(), and madness::constants::pi.
Referenced by MolecularEntity::add_atom(), madness::Molecule::add_atom(), PointGroup::apply(), madness::Solver< T, NDIM >::apply_hf_exchange(), madness::Solver< T, NDIM >::apply_hf_exchange4(), arithmetic_series(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::binary_iterator(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_spherical_moments(), check(), madness::FunctionImpl< Q, NDIM >::coeffs_for_jun(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::FunctionImpl< Q, NDIM >::eval_cube(), fixphases(), Key::foreach_child(), madness::GFit< T, NDIM >::gaussian_spherical_moments(), geometric_series(), madness::SCF::get_fock_transformation(), he_ldaop(), madness::QuasiNewton::hessian_update_sr1(), QuasiNewton::hessian_update_sr1(), PointGroup::ircell(), ldaop(), madness::Molecule::moment_of_inertia(), madness::mTxmT(), madness::mul(), madness::xc_lda_potential::operator()(), Qfunc::operator()(), madness::Vector< int, 3 >::operator*=(), madness::Function< double, 6 >::operator*=(), madness::Vector< int, 3 >::operator+=(), madness::Vector< int, 3 >::operator-=(), madness::Molecule::orient(), MolecularEntity::print(), madness::Molecule::print(), madness::print_stats(), madness::qm_free_particle_propagator(), madness::qm_free_particle_propagatorPtr(), madness::Molecule::read_core_file(), madness::Function< double, 6 >::scale(), madness::FunctionImpl< Q, NDIM >::scale_inplace(), madness::FunctionImpl< Q, NDIM >::scale_oop(), madness::SeparatedConvolutionData< Q, NDIM >::SeparatedConvolutionData(), madness::Molecule::set_eprec(), madness::CorePotentialManager::set_eprec(), madness::Tensor< TENSOR_RESULT_TYPE(T, R)>::ternary_iterator(), Test6(), Test7(), test_gconv(), test_in(), test_out(), testgradG(), and madness::XCfunctional::vxc().
test_bsh()
template<typename T > int test_bsh (World & world)
References aa, madness::Function< T, NDIM >::clear(), madness::copy(), madness::cpu_time(), e(), madness::Function< T, NDIM >::err(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, madness::kmax, mu, madness::detail::norm(), op(), madness::constants::pi, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), smalltest, and madness::Function< T, NDIM >::verify_tree().
Variable Documentation
aa
double aa
Referenced by compute_energy(), madness::NemoBase::compute_gradient(), madness::TensorTrain< T >::decompose(), drot(), main(), madness::SeparatedConvolution< T, NDIM >::munorm2_ns(), madness::poly4erfc::poly4erfc(), madness::print_seq(), q(), test_bsh(), madness::test_cholesky(), and madness::test_rr_cholesky().
smalltest
bool smalltest = false
Referenced by main(), and test_bsh().