MADNESS: testdiff1D.cc File Reference
testdiff1D.cc File Reference
testing for diff() in 1D
#include <madness/mra/mra.h>
Typedefs
typedef Vector< double, 1 > coordT
typedef FunctionFactory< double, 1 > factoryT
typedef Function< double, 1 > functionT
typedef Tensor< double > tensorT
Functions
int compare (World &world, functionT test, functionT exact, const char *str)
static double du_exact (const coordT &pt)
static double left_dirichlet (const coordT &pt)
static double left_neumann (const coordT &pt)
int main (int argc, char **argv)
static double right_dirichlet (const coordT &pt)
static double right_neumann (const coordT &pt)
static double u_exact (const coordT &pt)
Variables
static const int init_lev = 2
static const int k = 9
static const double Length = 4.
static const int test_axis = 0
static const double thresh = 1.e-7
Detailed Description
testing for diff() in 1D
Typedef Documentation
coordT
typedef Vector<double,1> coordT
factoryT
typedef FunctionFactory<double,1> factoryT
functionT
typedef Function<double,1> functionT
tensorT
typedef Tensor<double> tensorT
Function Documentation
compare()
int compare (World & world, functionT test, functionT exact, const char * str)
References madness::error(), exact(), madness::norm2(), madness::World::rank(), test(), and thresh.
Referenced by main().
du_exact()
static double du_exact (const coordT & pt) static
Referenced by main().
left_dirichlet()
static double left_dirichlet (const coordT & pt) static
Referenced by main().
left_neumann()
static double left_neumann (const coordT & pt) static
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::BC_DIRICHLET, madness::BC_FREE, madness::BC_NEUMANN, SafeMPI::COMM_WORLD, compare(), du_exact(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, init_lev, madness::initialize(), k, left_dirichlet(), left_neumann(), Length, right_dirichlet(), right_neumann(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_axis, thresh, u(), and u_exact().
right_dirichlet()
static double right_dirichlet (const coordT & pt) static
References Length.
Referenced by main().
right_neumann()
static double right_neumann (const coordT & pt) static
Referenced by main().
u_exact()
static double u_exact (const coordT & pt) static
Referenced by main().
Variable Documentation
init_lev
const int init_lev = 2 static
Referenced by main().
k
const int k = 9 static
Referenced by main().
Length
const double Length = 4. static
Referenced by main(), and right_dirichlet().
test_axis
const int test_axis = 0 static
Referenced by main().
thresh
const double thresh = 1.e-7 static
Referenced by compare(), and main().