MADNESS: test_papi.cc File Reference
test_papi.cc File Reference
#include <iostream>
#include <unistd.h>
#include <pthread.h>
#include <papi.h>
Functions
void * f1 (void *p)
int main ()
Variables
int events [NUMEVENTS] = {PAPI_FP_OPS}
const int NUMEVENTS = 1
long long values1 [NUMEVENTS]
Function Documentation
f1()
void* f1 (void * p)
References events, NUMEVENTS, p(), sum, and values1.
Referenced by main().
main()
int main ()
References f1(), and values1.
Variable Documentation
events
int events[NUMEVENTS] = {PAPI_FP_OPS}
Referenced by f1().
NUMEVENTS
const int NUMEVENTS = 1
Referenced by f1().
values1
long long values1[NUMEVENTS]
Referenced by f1(), and main().