MADNESS: wannier.cc File Reference
wannier.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include <cmath>
#include <complex>
Classes
struct abs_square_op< Q, NDIM >
class ComplexExpFunction
class ExcitingApp
struct ExcitingApp::vectorLengthFunctor
class Wannier< T, NDIM >
struct ExcitingApp::wannierf
Macros
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Typedefs
typedef FunctionFactory< std::complex< double >, 3 > cfactoryT
typedef Function< std::complex< double >, 3 > cfunctionT
typedef std::shared_ptr< FunctionFunctorInterface< std::complex< double >,3 > > cfunctorT
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef Vector< double, 3 > vec3dT
Functions
template<typename Q , int NDIM>
Function< typename TensorTypeData< Q >::scalar_type, NDIM > abs_square (const Function< Q, NDIM > &func)
void exciting_init_ ()
void f_get_evalsv_ (int *, double *)
void f_get_occsv_ (int *, double *)
void f_kpts_ (int *, double *, double *, double *, double *)
void f_lvec_ (double(*)[3], double(*)[3], double(*)[3], double(*)[3])
void f_ngridk_ (int *, int *, int *)
void f_nkpts_ (int *)
void f_nstsv_ (int *)
void f_nwann_ (int *)
void f_rho_ (double *vrc, double *val)
void f_veff_ (double *vrc, double *val)
void f_wann_ (int *n, int *ispn, double *d0, int *itr, double *vrc, double *val)
void f_wann_c_ (int *, int *, int *, double *)
void f_wann_center_ (int *, double *)
std::complex< double > func (int n, int t1, int t2, int t3, double xx, double yy, double zz)
int main (int argc, char **argv)
double real (double x)
void test_wannier (World &world)
void test_wannier2 (World &world)
Macro Definition Documentation
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
Referenced by main().
TO_STRING2
#define TO_STRING2 (s) #s
Typedef Documentation
cfactoryT
typedef FunctionFactory<std::complex<double>,3> cfactoryT
cfunctionT
typedef Function<std::complex<double>,3> cfunctionT
cfunctorT
typedef std::shared_ptr< FunctionFunctorInterface< std::complex<double> ,3> > cfunctorT
coordT
typedef Vector<double,3> coordT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
vec3dT
typedef Vector<double,3> vec3dT
Function Documentation
abs_square()
template<typename Q , int NDIM> Function<typename TensorTypeData<Q>::scalar_type,NDIM> abs_square (const Function< Q, NDIM > & func)
References madness::func(), and madness::unary_op().
exciting_init_()
void exciting_init_ ()
Referenced by ExcitingApp::ExcitingApp(), and test_wannier().
f_get_evalsv_()
void f_get_evalsv_ (int * , double *)
Referenced by ExcitingApp::response().
f_get_occsv_()
void f_get_occsv_ (int * , double *)
Referenced by ExcitingApp::response().
f_kpts_()
void f_kpts_ (int * , double * , double * , double * , double *)
Referenced by ExcitingApp::read_kpoints().
f_lvec_()
void f_lvec_ (double(*) [3], double(*) [3], double(*) [3], double(*) [3])
Referenced by ExcitingApp::read_lattice().
f_ngridk_()
void f_ngridk_ (int * , int * , int *)
Referenced by ExcitingApp::read_kpoints().
f_nkpts_()
void f_nkpts_ (int *)
Referenced by ExcitingApp::read_kpoints().
f_nstsv_()
void f_nstsv_ (int *)
Referenced by ExcitingApp::response().
f_nwann_()
void f_nwann_ (int *)
Referenced by ExcitingApp::compute_A_coeffs(), ExcitingApp::read_wannier_functions(), and ExcitingApp::response().
f_rho_()
void f_rho_ (double * vrc, double * val)
f_veff_()
void f_veff_ (double * vrc, double * val)
f_wann_()
void f_wann_ (int * n, int * ispn, double * d0, int * itr, double * vrc, double * val)
Referenced by func().
f_wann_c_()
void f_wann_c_ (int * , int * , int * , double *)
Referenced by ExcitingApp::response().
f_wann_center_()
void f_wann_center_ (int * , double *)
Referenced by ExcitingApp::read_wannier_functions().
func()
std::complex<double> func (int n, int t1, int t2, int t3, double xx, double yy, double zz)
References f_wann_().
Referenced by opt().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, madness::initialize(), madness::print(), madness::World::rank(), madness::World::size(), madness::startup(), test_wannier2(), and TO_STRING.
real()
double real (double x)
Referenced by compute_madelung_energy(), compute_madelung_energy_PWSCF(), EwaldNuclearPotentialFunctor::operator()(), and test_XCOperator().
test_wannier()
void test_wannier (World & world)
References e(), exciting_init_(), madness::inner(), madness::Function< T, NDIM >::norm2(), madness::World::rank(), madness::real(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), and thresh.
test_wannier2()
void test_wannier2 (World & world)
Referenced by main().