TOPDIR = ../../../..

TARGET_TO_MAKE = libMADxc

CSRC = xc_c_lyp.c  xc_c_pw91.c  xc_c_vwn5.c      xc_x_b88.c     xc_xc_b97_2.c  xc_xc_hcth120.c  xc_xc_hcth.c  xc_x_pbe.c \
       xc_c_p86.c  xc_c_pw92.c  xc_c_vwn5rpa.c  xc_xc_b3lyp.c   xc_xc_b97.c    xc_xc_hcth147.c  xc_xc_pw91.c  xc_x_pw91.c \
       xc_c_pbe.c  xc_c_pz81.c  xc_x_b3.c        xc_xc_b97_1.c  xc_xc_edf1.c   xc_xc_hcth407.c  xc_x_lda.c \

include $(TOPDIR)/config/GlobalMakefile

INCLUDES += -I.


