name: publish-doxygen

# Trigger this when a pull request is merged (which implies pushing to master).
on:
  push:
    branches:
      - master

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build g++-13 liblapack-dev openmpi-bin libopenmpi-dev libtbb-dev doxygen graphviz

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cd build && cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build doxygen docs
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target html-madness

      - name: Deploy to GitHub Pages
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          cmake -E make_directory ${{github.workspace}}/gh-pages-deploy
          cp -rp ${{github.workspace}}/build/doc/html ${{github.workspace}}/gh-pages-deploy/api-doc
          cd ${{github.workspace}}/gh-pages-deploy
          # create a brand-new repo so that gh-pages contains no history
          git init
          git add .
          git commit -q -m "Generated API doc via GitHub Actions (run $GITHUB_RUN_NUMBER)"
          git checkout -b gh-pages
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin +gh-pages

      - name: Result URLs
        run: |
          REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          echo "Formatted API docs:  https://$REPO_OWNER.github.io/$REPO_NAME/api-doc"
          echo ""
          echo "GitHub pages branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/gh-pages"
